### ISSUE TITLE
[Proposal]: Extractor Specific `escape` Function & Specify Extractor Name(s) in `RuleMeta`

### ISSUE THREAD

**Issue by zojize** [unocss/unocss#1004]
## Motivation

I was experimenting[^1] with the icons preset to allow icons to be declared as custom HTML tags. For example, the following HTML code

```html
<i-carbon-sun />
```

would generate CSS below

```css
i-carbon-sun {
  --un-icon:url("...");
  mask:var(--un-icon) no-repeat;
  mask-size:100% 100%;
  -webkit-mask:var(--un-icon) no-repeat;
  -webkit-mask-size:100% 100%;
  background-color:currentColor;
  width:1.2em;
  height:1.2em;
}
```

However, there were a number of issues I encountered during my experiment:

1. Tag names are not extracted by default (fine, I'll create my own extractor)
2. Extracted raw tag names will be automatically escaped[^2] as class selectors (no workaround)[^3]
3. CSS for icon classes will still be generated (no workaround)

With these limitations stated above, I find it impossible to implement this feature without changing the internal generation mechanism. Hence, this proposal.

### Extractor Specific `escape` Function

Extractors can define a custom escape function to allow other custom escaping logic for the extracted content. e.g.

```js
const extractorClassNames = {
  name: 'class-names',
  extract(ctx) { /* logic */ },
  escape: selector => `.${selector}`
}
```

Extractors that don't define this method can still fallback to the default behavior for backwards compatibility. This would allow custom escape behavior other than the default.

### Specify Extractor Name(s) in `RuleMeta`

Rules should be able to specify which extractor(s) to generate CSS from. e.g.

```js
export default defineConfig({
  rules: [
    // lets say these extractors exist and behave as expected
    ['foo', { color: 'red' }, { extractors: 'tag-name' }],
    ['bar', { color: 'green' }, { extractors: 'attributify' }],
    ['baz', { color: 'blue' }, { extractors: ['class-name', 'attributify'] }],
  ]
})
```

With this config, the following HTML

```html
<foo bar class="baz" baz />
```

should generate this CSS

```css
foo { color: red; }
[bar=""] { color: green; }
.baz, [baz=""] { color: blue; }
```

This feature combined with extractor specific escape function would allow powerful customization capabilities, and attributify selectors can now be implemented as extractor + rule instead of hard-coded internal support. Rules without extractor specified should default to `['class-name', 'attributify']` for backwards compatibility.

## Potential Problems

- Refactor complexity
- Escaping attributified selectors (see below)

### Escaping Attributified Selectors

With the above proposal, we should be able to define the attributify extractor with a custom escape function.

```js
const extractorAttributify = {
  name: 'attributify',
  extract(ctx) { /* extractor logic */ },
  escape(matcher) {
    const splitted = matcher.split(/-/)
    return `[${splitted[0]}="${splitted.slice(1).join('-')}"]`
  }
}
```

Therefore this HTML

```html
<div flex="~ col" border-b="1 red solid" />
```

Should extract `Set { 'flex', 'flex-col', 'border-b-1', 'border-b-red', 'border-b-solid' }`. And rules with attributify extractors specified can match these. However, there is a catch. Our code is unaware of whether to escape `'border-b-1'` as `[border-b-1=""]` or `[border-b="1"]` or `[border="b-1"]`. To this problem I don't have an elegant solution. The only thing I can think of is to provide more information from the extractor and pass that info in the escape function.

```js
const extractorAttributify = {
  name: 'attributify',
  extract(ctx) {
    const result = new Set()
    //          matcher      payload
    result.add(['border-b-1', { head: 'border-b', tail: '1' }])
    return result
  },
  escape(matcher, { head, tail }) {
    return `[${head}="${tail}"]`
  }
}
```

[^1]: [experiment](https://github.com/zojize/unocss-icon-tag)
[^2]: [toEscapedSelector](https://github.com/unocss/unocss/blob/49a20e54668ebdc6bbc321cb9ecfcd3c25619e29/packages/core/src/generator/index.ts#L557-L562)
[^3]: Technically I could use full control rules, but this brings other problems

**Comment by antfu** [comment]
To me, rules should be agnostic to extractors and variants and composable with different combinations in the userland. (e.g. attributify provides the ability for any rules you defined). 

Here is a working example of things you want to achieve: 
https://uno.antfu.me/play/?html=DwFwpgHiC0BOYBMB84p0cA9Km9lA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnzBr8IAIZQA1qihwAvHQD6MQURm04AehVwhRYMw3CxUADRxmAC0FYiqODAhwA7mfgBPCPXvmY3VAA9IsFBiC9AA28GiYOPiEwEQAFAiccHBQIaisAFxwANqJSdm0zPT81AC0KcGotEZIvMHQmbRQqMjKpAC6uW0GuT4wUILMNlAZ2blJCXlJvf2D8cYQaGQAlIhjk00w9FBY2QB0%2B7xou0IwpgCCwcGxKgA8sVkAOnYlbQDUSypES23HgmCxwEkAD4hKJxK9gFkAIxtFaTeEIxFI5FJNZkNakTrdJIAN2EwA8Ixykwm8JOpgBWDA9BgK1JCOA6DgsQAhNhqTBdvxhDBWAB1YAwEyxUH6JZLNHwjZbLCSpLS7arFHkkziTLsmlc4LaVAivTiXYVCxCpbY5GsVAVQb1ODAKRA21anV6sFQQ2oY0mOCvOBQiVIzEIwN5YMdUhLIA&options=N4IgzgLgTglgxhEAuAZgQwDZgKYF8g

**Comment by antfu** [comment]
And that's an interesting idea, I think we could have it directly in the monorepo, something like `@unocss/preset-tagify` or a better name :P

**Comment by zojize** [comment]
Thanks for your response! I did come across a similar solution to yours at one point in my experiment, but it didn't really resonate with me aesthetically. It felt to me like too much of a hardcoded trickery and I think it deserves internal support. But I also think you're right about rules being agnostic from extractors, and my proposal definitely breaks that.

**Comment by antfu** [comment]
To me, I think the "aesthetic" is more important in the user-facing APIs rather than the internal. Even tho it's might be a bit hacky, I think it's great that it doesn't leak the hack and can achieve the goal in this a few lines.

@zojize do you want to send a PR for the new package? Or I can do that as well

**Comment by zojize** [comment]
I could draft a PR ;) love to learn how to ship a package in a monorepo

**Comment by antfu** [comment]
Any progress on it? Or I can make one and ship it as the next minor with your credits

**Comment by zojize** [comment]
Sorry for the wait, I was busy with something else earlier and only got an MVP working yesterday, but it's still lacking some tests/docs. Should be able to make the PR today :). If that doesn't happen feel free to ship your own.
