### ISSUE TITLE
Disable preset utilities

### ISSUE THREAD

**Issue by NicolaSpadari** [unocss/unocss#1006]
I use WindiCSS with Bootstrap to fill the gaps in a project I'm working on, currently trying to switch from Windi to UnoCSS, but in Windi I can disable the `container` utility to use the Bootstrap one.
How can I achieve this with Uno? Any way to override the utility or disable it?

**Comment by antfu** [comment]
https://github.com/unocss/unocss/blob/ab4d0409990835d7829b09b903132e6ed8521204/packages/core/src/types.ts#L272-L276
