### ISSUE TITLE
SvelteKit missing Vite?

### ISSUE THREAD

**Issue by MrVoshel** [unocss/unocss#1007]
Hi, it seems like even though everything is working once installed it shows this error with every next dependecy I try to install
![Code_MPQzDFwJ4D](https://user-images.githubusercontent.com/54818101/170339184-7220b4c0-ea40-4d72-9e6d-3fe458df1659.png)
which seems strange since SvelteKit should include Vite.
The steps to reproduce this are:
`pnpm create svelte something`

![image](https://user-images.githubusercontent.com/54818101/170339511-f3e0a0cd-354a-4bfc-b3c3-a0ad211119cc.png)
```
cd something
pnpm install
pnpm i -D @unocss/vite
```

**Comment by userquin** [comment]
try installing unocss as dev dependency

**Comment by userquin** [comment]
@MrVoshel provide a repro on github or stackblitzt: check the `vite` entry is added inside `kit` option.

**Comment by MrVoshel** [comment]
> @MrVoshel provide a repro on github or stackblitzt: check the `vite` entry is added inside `kit` option.

I wanted to make it clear that the errors shows up before even touching svelte.config.js just by installing @unocss/vite, but here's the [repository](https://github.com/MrVoshel/test). Let me know if the error is reproducible in your system.

**Comment by antfu** [comment]
There is nothing we can do on our side. Basically it's an false alarm, you can either disable the strict peer option in pnpm, or just install `vite` to bypass it.
