### ISSUE TITLE
[Question] How do I override preset-typography's max-width

### ISSUE THREAD

**Issue by Codermar** [unocss/unocss#1008]
For the life of me I can't override max-width

https://github.com/unocss/unocss/blob/49a20e54668ebdc6bbc321cb9ecfcd3c25619e29/packages/preset-typography/src/index.ts#L75

I am using a vitesse template. I tried the following with no luck
```
    presetTypography({
      cssExtend: {
        prose: {
          'max-width': '75ch',
        },
      },
    }),
```

**Comment by ydcjeff** [comment]
You can overwrite the max width with normal `max-w-[value]` utility.
