### ISSUE TITLE
Import preset-uno?

### ISSUE THREAD

**Issue by mzaini30** [unocss/unocss#1014]
I see the different in https://github.com/unocss/unocss/blob/7135bf359057de722850a088f11326d708f3ef33/packages/preset-uno/README.md?plain=1#L14 and https://github.com/unocss/unocss/blob/7135bf359057de722850a088f11326d708f3ef33/packages/preset-typography/README.md?plain=1#L15 about import preset-uno

**Comment by antfu** [comment]
No, just an alias.
