### ISSUE TITLE
theme() breaks @apply

### ISSUE THREAD

**Issue by ameinhardt** [unocss/unocss#1021]
Very cool that you are including theme() support!
It seems that @apply and theme() currently can't be used in the same rule. Even if it's only mentioned as a comment, see [Stackblitz](https://stackblitz.com/edit/vitejs-vite-qabktp?file=src%2Fstyle.css&terminal=dev)

Also, with that implementation after parsing to AST, it won't be applied to `childNode.type === 'Declaration' && childNode.value.type === "Raw"`, isn't it? This is how users might expect it from [tailwind](https://play.tailwindcss.com/Hnd4BmJbK9?file=css) or [windi](https://windicss.org/play.html?html=DwEwlgbgBAxgNgQwM5ILwCIAuBTJn0B8AFtnHAPbAD04EBQA&css=CYSwbgBA3gUBEAECGAHFAbAnhAZugpgB4QAWAtDgK7roQDuF1tAVpQM4AuIOmZAxvgB2HfACcIIEQFs2-ISNEBuOBDJkpvPgHt0W0QC4IHEvin4AFAHJtu0WwB0o-MHsBWAAzvLASmXwbeoZgSKLmahr8Onq%2BMAC%2BQA).
Would it be an option to use simple string replacement [before AST parsing](https://github.com/unocss/unocss/blob/3e2182460457da98bbd92943ccd999d86f10b08d/packages/transformer-directives/src/index.ts#L53) instead? As in something like the following:
```javascript
  const regTheme = /theme\((["']?)([^\1)]+)\1\)/g;
  let result = regTheme.exec(code.original);
  while (result != null) {
    const [match,, args] = result
    const keys = args.split(".")
    let value = uno.config.theme
    keys.every((key) => {
      if (!Reflect.has(value, key)) {
        value = null
        return false
      }
      value = value[key]
      return true
    })
    code.overwrite(result.index, result.index + match.length, value);
    result = regTheme.exec(code.original);
  }
```

**Comment by antfu** [comment]
PR welcome!
