### ISSUE TITLE
[Vscode extension] the preset config is prerequisite

### ISSUE THREAD

**Issue by TrickyPi** [unocss/unocss#1032]
I want to use Unocss Vscode extension in my unocss+vite+react project, it doesn't work until i config presets, and i didn't find this prerequisite for using Unocss Vscode extension. if it isn't a bug, maybe we should list this prerequisite in the README.md under packages/vscode?

# addtional info
it doesn't work
```js
//vite.config.ts
import { defineConfig } from 'vite'
import Unocss from 'unocss/vite'
import react from '@vitejs/plugin-react'
import tsconfigPaths from 'vite-tsconfig-paths'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
    Unocss({}),
    tsconfigPaths(),
  ],
})

```
it works
```js
//vite.config.ts
import { defineConfig } from 'vite'
import Unocss from 'unocss/vite'
import { presetUno } from 'unocss'
import react from '@vitejs/plugin-react'
import tsconfigPaths from 'vite-tsconfig-paths'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
    Unocss({
      presets: [presetUno()],
    }),
    tsconfigPaths(),
  ],
})

```
Please let me know if you need more information.

**Comment by coderzhaoziwei** [comment]
I think... If the option for unocss is none, unocss doesn't work because there is nothing for unocss to do.

**Comment by TrickyPi** [comment]
unocss will use [@unocss/preset-uno](https://github.com/unocss/unocss/tree/main/packages/preset-uno)  as the default presets if we didn't config presets.

**Comment by TrickyPi** [comment]
closes via https://github.com/unocss/unocss/commit/1ea7dd78e636805ce2147d266514f91f93348c22
