### ISSUE TITLE
npm run build 报错，内容如下：

### ISSUE THREAD

**Issue by MrJelly** [unocss/unocss#1043]
[unocss:global:build:scan] pluginContext.emitFile is not a function
error during build:
TypeError: pluginContext.emitFile is not a function

**Comment by antfu** [comment]
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)
