### ISSUE TITLE
preset/wind -> grid-template-columns value

### ISSUE THREAD

**Issue by kleinptr9** [unocss/unocss#1044]
I am not sure, but it looks like bad implementation of grid-cols

![image](https://user-images.githubusercontent.com/17269309/171177669-d4f7764a-7195-4d55-8935-0de89e5547d2.png)

as we can see, it puts comma between values, but in the windi docs, there is no comma

![image](https://user-images.githubusercontent.com/17269309/171177503-1011bcb7-e52e-4b18-87da-084a57536f89.png)

https://windicss.org/utilities/layout/grid.html

**Comment by antfu** [comment]
UnoCSS uses `_` instead of `,` for seperator

**Comment by kleinptr9** [comment]
ok, didn't know, I was searching here https://uno.antfu.me/?s=grid-cols

Thanks for clarify

**Comment by iagafonov** [comment]
> UnoCSS uses `_` instead of `,` for seperator

@antfu I think this information should be posted on the main page

**Comment by melMass** [comment]
> UnoCSS uses `_` instead of `,` for seperator

Ah nice! I just spent an hour debugging everything 😅! On the plus side I looked into every packages and really like the project.

I think it should be part of the Tailwind migration guide too as it works the same in tailwindCSS !
