### ISSUE TITLE
[unocss:global:build:scan] pluginContext.emitFile is not a function error during build

### ISSUE THREAD

**Issue by MrJelly** [unocss/unocss#1048]
[https://github.com/MrJelly/unocss-watch](url)

1. `pnpm install`

2. `pnpm run build`

3. There will be an error. as shown below:

[unocss:global:build:scan] pluginContext.emitFile is not a function
error during build:
TypeError: pluginContext.emitFile is not a function

4. when I perform `pnpm run dev`,It is appropriate, how should I do?

**Comment by whidy** [comment]
I've found out what the problem.

With rules, we must very carefully!

My code and @MrJelly have a common problem that use `@` to reference the real path, if we change it to a normal path, It   will be okay.

code by @MrJelly is here: <background: `url(@/assets/images/${img}) center center no-repeat`,>

if changes to:

```
background: `url(./src/assets/images/${img}) center center no-repeat`,
```

build will pass.

BTW, if rules contain `@apply`, we should add `;` at the end, though development is ok, but build error.

so we should very very carefully about writing `rules`.

---

我找到原因，是因为在`rules`里面使用了`@`来映射图片的真实地址。如果改成相对路径的地址，可以解决构建时报错的问题。

当然，我也发现在编写rules的时候，要格外注意其格式的严谨性，有时候开发模式下是正常的，但是编译报错，我推测和压缩代码，因为原始代码不会自动补分号或者自动解析`@`之类，所以造成的问题，目前为了避免这些问题，可以试着更“原始”的写法。

不过这个开发模式能解析`@`，生产就完蛋的问题，也许也是unocss的不完善的地方。希望 @antfu 可以关注下~

**Comment by antfu** [comment]
I think this is more like an integrations issue rather than I think we can fix in UnoCSS. UnoCSS does NOT parse the CSS you provided thus the custom alias will not be resolved. You might need to avoid using alias, or resolve it on rule generation.

**Comment by enochzzz** [comment]
I created a simple plugin to handle this requirement.
[vite-plugin-unocss-bgimg](https://github.com/enochzzz/vite-plugin-unocss-bgimg)
