### ISSUE TITLE
Support in Astro

### ISSUE THREAD

**Issue by matthewp** [unocss/unocss#105]
Hi, I'm one of the core team means of Astro and we're in the process of converting our backend to use Vite. I'm trying to get Astro to support unocss and could use some help understanding how your Vite plugins work.

In development mode there is a request for `/__uno.css` which is correctly handled by your plugin and everything works beautifully. When the build is ran that same `/__uno.css` request goes through but another set of plugins are run which do not resolve this id and therefore the build breaks as no plugin claims this id.

I would expect that resolution to happen [here](https://github.com/antfu/unocss/blob/main/packages/vite/src/modes/global/build.ts#L35) but it does not. I'm thinking that build must work a bit differently and on the Astro side we are not sending through what unocss expects to receive.

Can you explain what type of id the plugin is expecting here, or any other guidance. Thank you!

**Comment by antfu** [comment]
I am not familiar with Astro, do you mind sharing a minimal setup so I can test it out? Thanks.

**Comment by hans-d** [comment]
https://stackblitz.com/edit/github-d4rp6r?file=package.json

by default it will be in dev mode. On the terminal you can do eg `npm run build`

**Comment by matthewp** [comment]
@antfu, yes, the template shared by @hans-d is what i was working on. It's very possible that this a bug in Astro in and not in unocss, I was just hoping for information on what that plugin expects to receive so I can track down where things are going differently in our build vs. the vanilla Vite setup.

**Comment by hans-d** [comment]
Hi @antfu, could you help out @matthewp by providing some more info re the inner details of your vite plugin ? That would help him figuring out where astro might need some nudges. Thanks in advance!

**Comment by antfu** [comment]
I just pulled down your repo and played out. I can see the unresolved id error in the build.

In build, UnoCSS uses a virtual module to serve the CSS stub and replaced it in `generateBundle` hook. Can you help confirm first if the simple plugin example in Vite docs passed build on Astro? https://vitejs.dev/guide/api-plugin.html#simple-examples

**Comment by matthewp** [comment]
Yes, that does work, see here: https://stackblitz.com/edit/github-5hwrzj?file=dist%2Findex.html&on=stackblitz

What is the virtual module that UnoCSS uses? Astro is a static site generator so what the user imports in their code only goes through the pipeline in SSR. Like I said, what is going through the build pipeline is `/__uno.css`. Is that what SSR is resolving `uno.css` to?

**Comment by matthewp** [comment]
For clarity, how Astro generates pages statically is (in regards to CSS):

1. Render a page.
2. Examine Vite's module graph for what CSS is imported.
3. Create our own virtual module when imports all of those CSS.
4. Create an asset chunk at the end that concats all of the CSS together.

I'm now thinking the issue we are running into happens at step (2). Since the page has been loaded in SSR module we are getting the resolved ID and what we need to send through is the unresolved version. 

Is the unresolved version `uno.css`?

**Comment by antfu** [comment]
`uno.css` will be normalized to `/__uno.css`, and both `uno.css` and `/__uno.css` will be served. Can you share me the pointers of how 3 & 4 been implemented?

**Comment by matthewp** [comment]
Yeah, that happens in our CSS plugin: https://github.com/snowpackjs/astro/blob/main/packages/astro/src/vite-plugin-build-css/index.ts

So the mystery here is why `/__uno.css` is not picked up by your build plugins.

**Comment by antfu** [comment]
https://github.com/snowpackjs/astro/issues/1969

**Comment by matthewp** [comment]
An update on our end, we might be able to solve this on our end without you needing to do anything. Since the CSS is already loaded and JITed during the SSR load phase we should be able to fetch the code from that, just like what happens in dev.

**Comment by matthewp** [comment]
I *almost* have a fix on our end. Since the CSS is loaded through SSR (the reason the plugin runs twice), it already exists and we can just request the `/__uno.css` file from Vite.

It fails currently because of this though: https://github.com/antfu/unocss/blob/7481fc3f9d5c61c0aea33a8fa31caf341a749ceb/packages/vite/src/modes/global/build.ts#L119-L120

I think this throw is possibly wrong; it assumes that if a project has CSS it must be unocss usage, but Astro allows mixing CSS techniques. If the user has client-side usage of uno it will pass; if its only used in .astro files this will throw.

I think this throw should be removed.

**Comment by antfu** [comment]
It should not be enabled on SSR

https://github.com/antfu/unocss/blob/7481fc3f9d5c61c0aea33a8fa31caf341a749ceb/packages/vite/src/modes/global/build.ts#L88-L90

Can you test if you remove the error locally it would work or not?

**Comment by matthewp** [comment]
Yeah removing it does work. However I might be able to set `ssr: true`, so let me try that.

**Comment by kathirr007** [comment]
Hi @matthewp / @antfu ,
Any update on this to use unocss in Astro project?

Very much thanks in Advance

**Comment by matthewp** [comment]
I can give an update. When you use UnoCSS in a `.astro` file that file never actually gets built by Vite. That's the core issue blocking usage of UnoCSS (and other Vite plugins).

I'm working on changing how our build works and that will be release behind a flag in the near future (first PR is already submitted). That will unblock many Vite plugins. From what I saw in my testing, the UnoCSS plugin still doesn't work, however. I didn't dive into why yet; in theory it should work similar to how it works with the typical SPA setup. I'll look into this more soon and give an update here.

**Comment by johannschopplich** [comment]
The same issue occurs when using UnoCSS with îles. When building, especially with hydration, îles will throw an error as well:

```
[unocss:global:build:generate] [unocss] does not found CSS placeholder in the generated chunks,
this is likely an internal bug of unocss vite plugin
```

**Comment by electroheadfx** [comment]
I have no error, just work at first run, but the classes change doesn't update (the style are cleared). The unocss update work only from a restart.

**Comment by electroheadfx** [comment]
> The same issue occurs when using UnoCSS with [îles](https://github.com/ElMassimo/iles). When building, especially with hydration, îles will throw an error as well:
> 
> ```
> [unocss:global:build:generate] [unocss] does not found CSS placeholder in the generated chunks,
> this is likely an internal bug of unocss vite plugin
> ```

it works very nice and smooth in Iles. Did u put ```import 'uno.css';```in app.ts  ?

**Comment by NexZhu** [comment]
> > The same issue occurs when using UnoCSS with [îles](https://github.com/ElMassimo/iles). When building, especially with hydration, îles will throw an error as well:
> > ```
> > [unocss:global:build:generate] [unocss] does not found CSS placeholder in the generated chunks,
> > this is likely an internal bug of unocss vite plugin
> > ```
> 
> it works very nice and smooth in Iles. Did u put `import 'uno.css';`in app.ts ?

What is the correct way to use this in an UI library?
Should I `import 'uno.css'` in `index.ts` or externalize the import?

**Comment by veritem** [comment]
use `import 'uno.css` in `index.ts`

**Comment by matthewp** [comment]
0.24 (which is in prerelease currently) should unlock Unocss working in Astro.

**Comment by djmtype** [comment]
@matthewp I'm using Astro 0.25.4 and unocss 0.30.7. 

During development, after I run `npm run dev`, and apply WindiCSS' classes to my elements, the styles are not updating until I restart the server.

During production, there are no errors, but instead of the WindiCSS' utility classes I used, I get…

```css
#--unocss-- {
	layer: __ALL__;
}
```

**Comment by matthewp** [comment]
I don't know about WindiCSS but I believe UnoCSS will need a plugin to work with Astro, my previous comment just meant that there is nothing special needed any more as was the case when this issue was originally filed. Astro builds to files just like with any frontend framework now.

**Comment by yjl9903** [comment]
Hi @matthewp @antfu, Unocss dev HMR does not work in astro.

And I tried to debug it with vite-plugin-inspect. When using astro, I found the vite-css:post plugin does not generate js code with HMR.

![image](https://user-images.githubusercontent.com/30072175/162249900-c02b4511-68e5-4bac-bea9-e7e064ccbfb3.png)

I create [a test astro project](https://github.com/yjl9903/unocss/tree/main/examples/astro) in the `/example` dir.

**Comment by matthewp** [comment]
It's known that it doesn't work, that's what this issue is about.

**Comment by shiva-prasad-reddy** [comment]
Same issue with nuxt3 & unocss
I have no error, just works at first run, but the classes change doesn't update. The styles are reflected only by doing a page refresh.

**Comment by XiNiHa** [comment]
I just tried with Astro 1.0.0-rc.2. It works flawlessly in most cases. However, since all Vite plugins get applied AFTER the Astro framework integrations(which contain JSX transforms), Attributify mode is currently broken. I wonder if we could bypass this by providing our own Astro integration.

**Comment by XiNiHa** [comment]
edit: just tried building the production bundle and it's completely broken :D
I have tried several workarounds but all of them are not working.

- Directly importing `uno.css` in `.astro` file / Importing `uno.css` from static framework components (framework components that are not used as an island)
  - Breaks with an error `does not found CSS placeholder in the generated chunks`.
    - The `bundle` parameter of the hook `generateBundle()` only contained JS files and not CSS. I think that's the problem (since I was able to identify the hash placeholder in the built CSS)
- Importing `uno.css` in inline `<script>` / Importing `uno.css` from an island (tried with SolidJS integration)
  - Generates a correct CSS file. However it's not imported. only `empty css` comment is present in the hoisted JS file.

Looks like we should definitely make an integration...

**Comment by XiNiHa** [comment]
Update: things work flawlessly when I patch the `@unocss/vite` plugin's `unocss:global:build:generate` sub-plugin to run on SSR only. Although this sounds like a very Astro-specific tweak, I believe this is worth exposing as an option. (to pick between client bundle, SSR bundle, or both)

@antfu What do you think about this? I can make a PR if you agree with the direction.

**Comment by XiNiHa** [comment]
Update again: [astro-uno](https://github.com/AllanChain/astro-uno) does all the tricks to support Astro, like monkey-patching the Vite plugin to run on SSR mode. I ended up with using this without any patches and tricks.

**Comment by antfu** [comment]
https://github.com/unocss/unocss/tree/main/packages/astro

**Comment by antfu** [comment]
@XiNiHa Oh sorry I missed your comments. Thanks for making the integration! I have now implemented it directly in this repo https://github.com/unocss/unocss/tree/main/packages/astro, and enabled SSR to build for `unocss:global:build:generate`. I haven't dividing in deep about the HMR issue, but if you do, would you like to send a few PR to improve it? Thank you!

**Comment by XiNiHa** [comment]
I'm not the one who made the integration, @AllanChain did! 🚀 I guess they will know what should be done further :D

**Comment by AllanChain** [comment]
> I guess they will know what should be done further :D

Sorry for the late reply. I'm trying to solve some issue on Astro's side (https://github.com/withastro/astro/pull/4621)

The fix for attributify mode ([docs](https://github.com/AllanChain/astro-uno#what-it-does), [code](https://github.com/AllanChain/astro-uno/blob/2677a314ae4468350a93d5584c7ccea3299cd481/astro-uno/src/index.ts#L21-L34)) should be included in UnoCSS. But the current fix is a bit hacky. Maybe we should support some custom preprocessing before extracting?

**Comment by aspiiire** [comment]
> The same issue occurs when using UnoCSS with [îles](https://github.com/ElMassimo/iles). When building, especially with hydration, îles will throw an error as well:
> 
> ```
> [unocss:global:build:generate] [unocss] does not found CSS placeholder in the generated chunks,
> this is likely an internal bug of unocss vite plugin
> ```

Having this exact issue when doing build, I have solved with @AllanChain's package astro-uno, but If I am not wrong this should be fixed by Astro now... Does anyone have the same problem?

**Comment by LorenzoRottigni** [comment]
I am also having this problem:
`ℹ Using Tailwind CSS from ~/assets/sass/tailwind.sass                                                                                      nuxt:tailwindcss 18:59:48
vite v3.2.3 building for production...                                                                                                                      18:59:50
✓ 316 modules transformed.                                                                                                                                  19:00:00
rendering chunks (23)...
 ERROR  [unocss:global:build:generate] [unocss] does not found CSS placeholder in the generated chunks                                                      19:00:00
This is likely an internal bug of unocss vite plugin


 ERROR  [unocss] does not found CSS placeholder in the generated chunks                                                                                     19:00:00
This is likely an internal bug of unocss vite plugin

  This is likely an internal bug of unocss vite plugin`

**Comment by LorenzoRottigni** [comment]
I am using nuxt 3 with vite + tailwindCSS
