### ISSUE TITLE
在 web components 中使用 transform 和 filter 不生效

### ISSUE THREAD

**Issue by Zhang-Wei-666** [unocss/unocss#1053]
[复现](https://github.com/Zhang-Wei-666/unocss2)

![image](https://user-images.githubusercontent.com/37876877/171579124-969a2436-bf17-4ff4-8e8b-51d0ff9c90eb.png)

**Comment by okxiaoliang4** [comment]
web components有样式隔离。
[参考一下](https://www.haorooms.com/post/web_components)

**Comment by antfu** [comment]
Released 0.37.3

**Comment by Zhang-Wei-666** [comment]
@chu121su12 
![image](https://user-images.githubusercontent.com/37876877/172079253-c929df2d-1652-48a6-8738-7c428ded39de.png)

**Comment by Zhang-Wei-666** [comment]
这样是可以的

![image](https://user-images.githubusercontent.com/37876877/172079716-befcabb3-0a94-4f7b-992f-85726a9d84f8.png)

应该是因为其他 CSS 变量的值无效引起的

![image](https://user-images.githubusercontent.com/37876877/172079803-eccfe26e-c8f6-4a62-8f98-01099db8bbdf.png)
