### ISSUE TITLE
Attributefy Linting Error with Volar latest update

### ISSUE THREAD

**Issue by folamy** [unocss/unocss#1058]
I updated vscode and volar to the latest update, then I start getting linting error!
![Screenshot from 2022-06-03 04-15-01](https://user-images.githubusercontent.com/4560948/171844018-cb788e41-2283-45fc-8cdb-c9dc178ce19a.png)

Is there a way to correct this?

**Comment by johnsoncodehk** [comment]
See https://github.com/johnsoncodehk/volar/issues/1077#issuecomment-1145361472.

**Comment by antfu** [comment]
Thanks! Close to be track in https://github.com/johnsoncodehk/volar/issues/1077

**Comment by folamy** [comment]
@antfu and  @johnsoncodehk! Thanks, I will try this in a bit. 

> See [johnsoncodehk/volar#1077 (comment)](https://github.com/johnsoncodehk/volar/issues/1077#issuecomment-1145361472).
