### ISSUE TITLE
ts2322 when use attributify

### ISSUE THREAD

**Issue by TangsWang** [unocss/unocss#1061]
`<div relative>`

env:
nuxt rc2
@unocss/nuxt 0.37.1

不能将类型“{ relative: boolean; }”分配给类型“ElementAttrs<HTMLAttributes>”。
  类型“ElementAttrs<HTMLAttributes>”上不存在属性“relative”。ts(2322)

suddenly happened,   i did nothing, i don't know why, what's the problem?

**Comment by antfu** [comment]
https://github.com/unocss/unocss/tree/main/packages/preset-attributify#vue
