### ISSUE TITLE
Use unocss in Blazor

### ISSUE THREAD

**Issue by MAST1999** [unocss/unocss#1075]
I'm trying out `tailwindcss` and `windicss` in `blazor` with `postcss` then I found `unocss` and it looks amazing!

But I can't figure out how to use it in `blazor`, so I wondered if it is possible?

**Comment by Suyashtnt** [comment]
Blazor would require a custom extractor, and I don't think blazor use webpack or vite

**Comment by icetech233** [comment]
where download   unocss all .css

**Comment by benitoanagua** [comment]
https://github.com/hal-wang/BlazorUnoCSS
