### ISSUE TITLE
CSS does not generate in `iife` build

### ISSUE THREAD

**Issue by imohuan** [unocss/unocss#1077]
Mode Dev:  The normal display
![image](https://user-images.githubusercontent.com/41279222/172516062-82541070-ff22-4176-9ca1-9cc3088d28d1.png)

Mode Prod: The CSS cannot be obtained
![image](https://user-images.githubusercontent.com/41279222/172516245-5fe3d371-513c-44dd-944e-0a45b5b25d61.png)

`main.ts`
``` typescript
import css from "uno.css";
console.log("css", css);
```

`vite.config.ts`
``` typescript
export default {
  // ...
  plugins: [
    vue(),
    Unocss({
      mode: "global",
      presets: [
        presetUno(),
        presetWind(),
        presetAttributify() as any,
        presetMini(),
        presetScrollbar(),
        presetScalpel({})
      ],
      transformers: [transformerDirectives()],

    });
  ]
}
```

**Comment by antfu** [comment]
Emm why do you want the css string in runtime?

**Comment by imohuan** [comment]
This is for demonstration purposes, not for anything else

**Comment by imohuan** [comment]
If you look at unoCSS compiled CSS, you will find that there is no valid CSS in the packaged compilation

**Comment by antfu** [comment]
We are deploying https://uno.antfu.me/ with the latest UnoCSS and we never faced such regression. Please provide a minimal reproduction, thanks.

**Comment by imohuan** [comment]
According to my test: Find the problem, but not sure how to fix it
`vite.config.ts`
``` typescript
export default defineConfig({
  base: "./",
  plugins: [vue(), Unocss()],
  build: {
    rollupOptions: {
      // ！The problem was changing format to Iife
      output: { format: "iife", inlineDynamicImports: true }, 
    },
  },
});
```
[mini-vue.zip](https://github.com/unocss/unocss/files/8866623/mini-vue.zip)

**Comment by nieyuyao** [comment]
I also have this problem when set output format to `umd`.

```javascript
export default defineConfig({
  base: "./",
  plugins: [vue(), Unocss()],
  build: {
    rollupOptions: {
      output: { format: 'umd' }
    },
  },
});

```

**Comment by nieyuyao** [comment]
CSS is bundled into js when format are `iife`, `amd` or `umd`. So the css file cannot be generated.

https://github.com/unocss/unocss/blob/1000830e1a202db30a00e4a683c6c9640bbc594f/packages/vite/src/modes/global/build.ts#L148-L154
