### ISSUE TITLE
Feature request: make `layer-xxx:` works even no native css layer support

### ISSUE THREAD

**Issue by hackwaly** [unocss/unocss#1079]
One of well-known issue of tailwind is that you can't easily override classes via className, except you define the component classes in css. There's npm package tailwind-override solves that issue in runtime with high overhead. 

We already have `layer-xxx:` syntax to support generate native css layer output. This solves the override issue, but it requires browser to support native css layers.

We can advance one small step: Instead of generate native css layer output, we can generate those rules with other rules by take care of the ordering to achieve the same effect.

**Comment by antfu** [comment]
You can use `uno-layer-xxx:` for unocss defined layers, see https://github.com/unocss/unocss#layers
