### ISSUE TITLE
how to use unocss with next.js?

### ISSUE THREAD

**Issue by little3201** [unocss/unocss#1094]
how to use unocss with next.js?

**Comment by Suyashtnt** [comment]
> how to use unocss with next.js?

Does nextjs support vite? If so just add it to the vite config

**Comment by antfu** [comment]
We have the webpack plugin: https://github.com/unocss/unocss/tree/main/packages/webpack

It would be great to also have a Next example in https://github.com/unocss/unocss/tree/main/examples if anyone is interested in.

**Comment by AirOne01** [comment]
From those coming from Google, you are looking for [the Next.JS example](https://github.com/unocss/unocss/tree/main/examples/next). Read the README, it has everything there. **Don't forget to delete your `.next` folder periodically to recompile the app**.

**Comment by alexandrosk** [comment]
Whatever I do I always get this after one 2 `pnpm run dev` someitmes it works thought lol 

```
./node_modules/.pnpm/next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[8].oneOf[13].use[1]!./node_modules/.pnpm/next@13.5.4_@babel+core@7.23.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[8].oneOf[13].use[2]!./src/pages/utils/globals.css
TypeError: fetch failed
```

followed the tutorial exactly and readme above always same issue :/
