### ISSUE TITLE
Shadow rules other than `shadow-inner` are doesn't work in shadow-dom mode

### ISSUE THREAD

**Issue by kwaa** [unocss/unocss#1099]
It seems to be due to the lack of preflights layer.
since `examples/vite-lit` doesn't seem to mention this, I try to report the problem here.

Reproduction:
- [with shadow-dom](https://stackblitz.com/edit/vitejs-vite-g9fts9)
- [without shadow-dom (works fine)](https://stackblitz.com/edit/vitejs-vite-r6pch1)

![with shadow-dom](https://user-images.githubusercontent.com/50108258/173294980-455dbd4b-b703-4ca4-997a-01ca39707318.png)
![without shadow-dom](https://user-images.githubusercontent.com/50108258/173294914-2aa2f839-105c-4c9c-88c6-f82253f94406.png)

**Comment by userquin** [comment]
@kwaa the `preflights` are not included: https://github.com/unocss/unocss/blob/main/packages/vite/src/modes/shadow-dom.ts#L51

**Comment by userquin** [comment]
@kwaa adding `preflights` works, PR in a few minutes:

![imagen](https://user-images.githubusercontent.com/6311119/174357883-2093c2ac-458a-45bc-9338-62d1fb0f91b8.png)
