### ISSUE TITLE
`checked:next:bg-red` styles are generated wrongly

### ISSUE THREAD

**Issue by jd-solanki** [unocss/unocss#1104]
Previously I was able to apply style to next children via `checked:next:bg-red`. Unfortunately from now on, I can't.

~~Docs link: https://uno.antfu.me/?s=checked:next:bg-primary~~
Docs link: https://uno.antfu.me/?s=checked:next:bg-red

**Comment by jd-solanki** [comment]
In my existing project:
![image](https://user-images.githubusercontent.com/47495003/173807302-45636a50-6bc6-4c48-81b7-ea082031c4b1.png)

In 0.39.0:
https://uno.antfu.me/?s=checked:next:bg-red

**Comment by chris-zhu** [comment]
I remember a PR that changed the order of the variants， try to use `next:checked:bg-red`

**Comment by jd-solanki** [comment]
Upon inspect I found that usage of `checked:next:bg-red` is now `next:checked:bg-red`. But, I think previous `checked:next:bg-red` was making much more sense:

- `checked:` => Current state
- `next:` => Aim for all children
- `bg-red` => Add bg

**Comment by jd-solanki** [comment]
@chris-zhu Please let me know your thoughts on the above comment.

If you think the order is fine and not confusing you can close this issue.

Regards :)
