### ISSUE TITLE
Icons do not get loaded in shadow-dom

### ISSUE THREAD

**Issue by davidboom95** [unocss/unocss#1106]

**Comment by userquin** [comment]
@davidboom95 the logo on `vite-lit` example is not working?

**Comment by antfu** [comment]
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)
