### ISSUE TITLE
Unocss Icons do not get loaded inside shadow-dom using pug

### ISSUE THREAD

**Issue by davidboom95** [unocss/unocss#1107]
Icons inside the template do not get loaded inside shadow dom using class syntax. 

```ts
// vite.config.ts
Vue({
    customElement: true,
}),
Unocss({
    mode: 'shadow-dom',
}),
```

## Class syntax
```vue
// Registered component.ce.vue
<template lang="pug">
.parent
  .i-carbon-close
</template>
<style>@unocss-placeholder</style>
<style lang="postcss">...</style>
```

### Compiles inside shadow-dom
```html
<style>
.i-carbon-close{
  /* Correct icon definition/
}
/* Other unocss classes*/
</style>
```
❌ Not working

## Tag syntax 
```vue
<template lang="pug">
// Registered component.ce.vue
.parent
   i-carbon-close
</template>
<style>@unocss-placeholder</style>
<style lang="postcss">...</style>
```

### Compiles inside shadow-dom
```html
<style>
/* No unocss icons compiled*/
/* Other unocss classes*/
</style>
```
❌ Not working

## Class + Tag
```vue
<template lang="pug">
// Registered component.ce.vue
.parent
   i-carbon-close
   .i-carbon-close
</template>
<style>@unocss-placeholder</style>
<style lang="postcss">...</style>
```
✅  Working

In summary:
1. `i-carbon-close` (tag) for some reason compiles the CSS with `.i-carbon-close { ... }`
2. `div(class="i-carbon-close")` (class) do not compile the CSS with `.i-carbon-close { ... }`, Actually, no icon css is compiled.
3. But if I use both of them,`tag` compiles the icon class but do not use it,`class` do not compile css it but uses compiled class it.

**Comment by userquin** [comment]
@davidboom95 I'm not familiar with `pug`, please provide a repro.
