### ISSUE TITLE
dynamic class or attributify value not updating until manually chaning with fixed text value

### ISSUE THREAD

**Issue by minkoonim** [unocss/unocss#1108]
using nuxt 3 rc4, unocss

when yarn dev,
after one of attributify attr is manually updated with fixed text value at least once, 
below works

```
<script setup>
const p = "x-20px y-10px"
</sript>

<template>
<div>
    <div :p="p">hello there</div>
</div>
</template>
```

but after initial start up, if not update manually,
"p" doesn't work
am i doing something wrong?

**Comment by antfu** [comment]
Attributify mode has to be inlined. You may use class mode or variant group for this case.

**Comment by minkoonim** [comment]
> Attributify mode has to be inlined. You may use class mode or variant group for this case.
大师什么时候再直播啊?
加油vue 加油nuxt3 加油 antfu ~
