### ISSUE TITLE
Typography Element Modifiers

### ISSUE THREAD

**Issue by soerenmartius** [unocss/unocss#1123]
In Tailwindcss, we have [element modifiers](https://tailwindcss.com/docs/typography-plugin#element-modifiers) to customize the style of individual elements in typography content.

However, this doesn't seem to work in unocss. Eg, 

```
  'prose',
  'prose-headings:underline',
  'prose-headings:text-3xl',
  'prose-headings:tracking-tight',
  'prose-headings:font-medium',
```

seems to be ignored when added to the wrapper of typography content. 

What's the recommended way of styling individual elements in UnoCSS?

**Comment by ydcjeff** [comment]
Yes, preset typography isn't exactly same as Tailwind typography plugin. Current way is to use [`cssExtend`](https://github.com/unocss/unocss/tree/main/packages/preset-typography#configurations) if you want to style individual elements.

**Comment by soerenmartius** [comment]
> Yes, preset typography isn't exactly same as Tailwind typography plugin. Current way is to use [`cssExtend`](https://github.com/unocss/unocss/tree/main/packages/preset-typography#configurations) if you want to style individual elements.

thank you!

**Comment by danielwaltz** [comment]
I don't suppose there's any chance this could be revisited? I must say I quite like the way tailwind handles this with [element modifiers](https://tailwindcss.com/docs/typography-plugin#element-modifiers) as I can use the same tokens I'm using across the site for colors/sizing/etc without needing to manually redefine colors and sizes inside of the UnoCSS config file.

**Comment by relferreira** [comment]
Is there any plan to support those modifiers directly on the classNames?
Like:

```
prose-h1:{utility}
```
