### ISSUE TITLE
Matches/extracts text from comments

### ISSUE THREAD

**Issue by CanRau** [unocss/unocss#1139]
Not sure this is expected or it's me, I've got the following (in Deno) and am feeding the raw text of a `.tsx` file as code to `generate` and it's extracting the word `inline` I've got in a JS comment.

```js
// @todo: My comment containing the word inline
```

```ts
import { createGenerator } from "https://esm.sh/@unocss/core@0.39.3";
import presetUno from "https://esm.sh/@unocss/preset-uno@0.39.3";

const generator = createGenerator({ presets: [presetUno()] });

const code = await Deno.readTextFile(
  path.join(Deno.cwd(), "app", "routes", "index.tsx"),
);

const { css } = await generator.generate(code)
```
This is just a snippet of the relevant code

The resulting `css` contains `.inline{display:inline;}` even though I don't use the class anywhere

I think I'd be great if Uno wouldn't extract from commented code, an alternative would be that I strip comments before passing the code to `generate`

**Comment by antfu** [comment]
UnoCSS extracts the code regardless of the context. One reason is for performance, and the other is to support different types of inputs. We can't possibly parse JS, TS, JSX, HTML, Vue, Svelte, Pug or something unknown perfectly. Stripping comments would also be hard to do right (I even made a package https://github.com/antfu/strip-literal), especially with a different type of input.

In general, I think this is sadly a bit of imperfection. But consider this is rather small to the generated CSS, and you might probably also using the `inline` util elsewhere when your app get larger, I would consider the current trade-off is worthy.

**Comment by CanRau** [comment]
Okay, just wanted to make sure it's "expected", I get what you're saying and am fine with the current behavior, just noticed and thought better ask and see, cause maybe I was doing something wrong here.

And thanks for mentioning `strip-literal` using a different package at the moment but am going to give yours a try 🙌
