### ISSUE TITLE
How to set Class starts with '-' in shortcuts

### ISSUE THREAD

**Issue by TYDD** [unocss/unocss#1141]
like this:
`shortcuts: [
        ['-enter-x', 'translate-x-12'],
]`

**Comment by chris-zhu** [comment]
[Negative variant](https://github.com/unocss/unocss/blob/main/packages/preset-mini/src/variants/negative.ts) will matched string that start with `-`.
[Playground](https://unocss.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIC0AXATggOyUWwFNMAPTARgAZ0A%2BAKCigFcCB7GFJ4AenARmoSLEQoMeQsQRlKmGvWasO3XgKHMgA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcEWWwCGuOlmggMUAGrr2mmAHEoELmCQBfOFksg4Aci4qJdOi6RIMAD0hYdGx1LgAbeEwcfCISYFIACmRUKAj6AC44AG0qVGyXCS46GAgQAFo08IwXckQ4KXDoLJdaNBc4WwBdKi7ZOgALaBgimDoslNRXIpKy8sHh0ZcWmACYcvDSOFX-dehNUgw4IYA3fQyd9dX1cJ9UW1kRBXGcvLlRJRVEgEpZYXlGCw2JweHx%2BD8-u8FJJpMk3qg6BIbhgsgBGAB0ACZIagJGhcC0BqwwOMAPSk%2BggdGDUl3Ka2X69NRQTTaXT6F65KbbFlaHRQPSGYzAUwWKxgCFMuzfJBAA&options=N4IgzgLgTglgxhEAuaBXApgGhNAhgOzADMB7KAW2SNwBswsQp0wAHEwmAN3StvoF8gA)

**Comment by TYDD** [comment]
> [Negative variant](https://github.com/unocss/unocss/blob/main/packages/preset-mini/src/variants/negative.ts) will matched string that start with `-`. [Playground](https://unocss.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIC0AXATggOyUWwFNMAPTARgAZ0A%2BAKCigFcCB7GFJ4AenARmoSLEQoMeQsQRlKmGvWasO3XgKHMgA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcEWWwCGuOlmggMUAGrr2mmAHEoELmCQBfOFksg4Aci4qJdOi6RIMAD0hYdGx1LgAbeEwcfCISYFIACmRUKAj6AC44AG0qVGyXCS46GAgQAFo08IwXckQ4KXDoLJdaNBc4WwBdKi7ZOgALaBgimDoslNRXIpKy8sHh0ZcWmACYcvDSOFX-dehNUgw4IYA3fQyd9dX1cJ9UW1kRBXGcvLlRJRVEgEpZYXlGCw2JweHx%2BD8-u8FJJpMk3qg6BIbhgsgBGAB0ACZIagJGhcC0BqwwOMAPSk%2BggdGDUl3Ka2X69NRQTTaXT6F65KbbFlaHRQPSGYzAUwWKxgCFMuzfJBAA&options=N4IgzgLgTglgxhEAuaBXApgGhNAhgOzADMB7KAW2SNwBswsQp0wAHEwmAN3StvoF8gA)

sorry. Maybe I didn't express it well. I mean '-custom-shortcut' not effective.  
[Playground](https://unocss.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIC0MCuSAuA9gLaZIAWhATvrvugHwBQUUOAdoTCk8APTgIzUJFiIUGXARJlKNOoxZtO3JLwGRmQA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcEWWwCGuOlmggMUAGrr2mmAHEoELmCQBfOFksg4Aci4qJdOi6RIMAD0hYdGx1LgAbeEwcfCISYFIACmRUKAj6AC44AG0qVGyXCS46GAgQAFo08IwXckQ4KXDoLJdaNBc4WwBdKi7ZOgALaBgimDoslNRXIpKy8sHh0ZcWmACYcvDSOFX-dehNUgw4IYA3fQyd9dX1cNq813KZ0oqF2CWVtY2ty-L93EPjhAzlALp9rrcqLZZCIFOMcvcYYxlBBEgBKWTCeSMFhsTg8Pj8NEYuSiGCSaTJe6oOgSG4YLIARgAdAAmYmoCRoXAtAasMDjAD0AvoICZgwFPimnXRvTUUE02l0%2BjhuSlGi0OigekMxmApgsVjARNldlRSCAA&options=N4IgzgLgTglgxhEAuaBXApgGhNAhgOzADMB7KAW2SNwBswsQp0wAHEwmAN3StvoF8gA) 
Or will it be supported in the future

**Comment by carpad88** [comment]
@chris-zhu do you know how can I acces the negative variant inside a rule?

My rule looks like this 

```js
[/^ft-(\d+)$/, ([, match], { theme }) => {
     const { minWidth, maxWidth, base } = theme.fluid
     ... // more code here
}
```

I want to know catch the pattern `-ft-4` and do soemthing if it's negative.

**Comment by chris-zhu** [comment]
> @chris-zhu do you know how can I acces the negative variant inside a rule?
> 
> My rule looks like this
> 
> ```js
> [/^ft-(\d+)$/, ([, match], { theme }) => {
>      const { minWidth, maxWidth, base } = theme.fluid
>      ... // more code here
> }
> ```
> 
> I want to catch the pattern `-ft-4` and do something if it's negative.

You can use `rawSelector` to catch you want.
 ```js
 [/^ft-(\d+)$/, ([, match], { theme, rawSelector }) => {
      const { minWidth, maxWidth, base } = theme.fluid
      ... // more code here
     console.log(rawSelector)
 }
 ```
