### ISSUE TITLE
Feature request: Allow escaping of characters in `@apply

### ISSUE THREAD

**Issue by UltraCakeBakery** [unocss/unocss#1148]
I am running into an edge case issue where due to a postcss plugin I am unable to use a `$` as a character inside my CSS.

I am trying to do this:

```css

@apply border-r-\$theme-color;
	
```

but this results into incorrectly generated css:

![image](https://user-images.githubusercontent.com/12383587/175397187-ac94b93e-9b05-4283-ba3f-ab471e342461.png)

**Comment by antfu** [comment]
cc @hannoeru 👀
