### ISSUE TITLE
Feature request: named groups

### ISSUE THREAD

**Issue by UltraCakeBakery** [unocss/unocss#1149]
I need functionality like the one concepted below for one of my projects;

```
<div group-wrapper>
	<div group-item>
		<div hidden group-item-hover:block></div>
	</div>
	<div group-item>
		<div hidden group-item-hover:block></div>
	</div>

	<div hidden group-wrapper-hover:block>
		Click on one of the items above!
	</div>
</div>
```

**Comment by chu121su12** [comment]
I'd suggest configuring your own variant

https://github.com/unocss/unocss/blob/979b6936c2c47e0c989076c7d259d6276fc09c95/packages/preset-mini/src/variants/default.ts#L28

Or wait until #1128 gets merged.

**Comment by UltraCakeBakery** [comment]
> I'd suggest configuring your own variant
> 
> https://github.com/unocss/unocss/blob/979b6936c2c47e0c989076c7d259d6276fc09c95/packages/preset-mini/src/variants/default.ts#L28
> 
> Or wait until #1128 gets merged.

#1128 would do the trick. If I thought about it enough i would even go as far as saying they make groups and their variants obsolete..
