### ISSUE TITLE
[typography] Allow using `not-prose` to block

### ISSUE THREAD

**Issue by jd-solanki** [unocss/unocss#1159]
In the typography preset if we want to remove styling then we need to add `not-prose` to each element.

```html
<p>content</p>
<div class="demo">
  <p class="not-prose">content</p>
  <p class="not-prose">content</p>
</div>
```

However, if we allow not-prose to block we can just do it with single class.

```html
<p>content</p>
<div class="demo not-prose">
  <p>content</p>
  <p>content</p>
</div>
```

Thanks.

**Comment by UltraCakeBakery** [comment]
You can do `children:not-prose`. Or maybe add a custom variant named `*` to your config, which is selector just being a wildcard. This would allow you to do `*:not-prose`

**Comment by jd-solanki** [comment]
IG it's not working at the moment: https://uno.antfu.me/?s=children:not-prose
