### ISSUE TITLE
Is it possible to convert rem unit to em via variant or transformer

### ISSUE THREAD

**Issue by jd-solanki** [unocss/unocss#1160]
Hi 👋🏻 

I am trying to create a responsive typography using em unit instead of, rem. Certainly I can extend theme to add new classes like `text-rlg` but I have to align those with UnoCSS typography. Moreover, `em:text-lg` is more elegant than `text-rlg`.

I checked creating custom variants but I think we can't do this with custom variants. Then I checked transformers but I don't have enough insights/experience of UnoCSS transforms at the moment to make a PR.

Can anybody help here?

**Comment by chu121su12** [comment]
If your only need is to replace the existing units, these variants should be of help:

https://github.com/unocss/unocss/blob/main/packages/preset-mini/src/variants/important.ts
https://github.com/unocss/unocss/blob/main/packages/preset-mini/src/variants/negative.ts

**Comment by jd-solanki** [comment]
Sorry I was unclear. I have classes like `text-2xl` which will give `font-size: 1.5rem` but instead of `rem` unit I want `em`. Desired style `font-size: 1.5em`.

To achieve this I extended theme with below font-size:

```js
fontSize: {
        rxs: ['0.75em', '1em'],
        rsm: ['0.875em', '1.25em'],
        rbase: ['1em', '1.5em'],
        rlg: ['1.125em', '1.75em'],
        rxl: ['1.25em', '1.75em'],
        r2xl: ['1.5em', '2em'],
        r3xl: ['1.875em', '2.25em'],
        r4xl: ['2.25em', '2.5em'],
        r5xl: ['3em', '1em'],
        r6xl: ['3.75em', '1em'],
        r7xl: ['4.5em', '1em'],
        r8xl: ['6em', '1em'],
        r9xl: ['8em', '1em'],
      },
```

I want to know can I use some transformer or variant so I don't have to extend theme and just prefix that variant to convert the `rem` to `em` when style is generated via class:

```
text-2xl => font-size: 1.5rem
em:text-2xl => font-size: 1.5em
```

_(also there's line height that needs conversion)_

Mentioned both variant's won't help here I guess 🤔

**Comment by chu121su12** [comment]
Consider the `important` variant. 

https://github.com/unocss/unocss/blob/c919198b3d1eb823a98881e89afd8d2dec9ba247/packages/preset-mini/src/variants/important.ts#L19-L20

Without handling the edge cases, simplest way may be just replacing `rem` to `em` in `v[1]`.

There's also https://github.com/unocss/unocss/tree/main/packages/preset-rem-to-px but this is a global unit replacement

https://github.com/unocss/unocss/blob/c919198b3d1eb823a98881e89afd8d2dec9ba247/packages/preset-rem-to-px/src/index.ts#L22-L24

**Comment by jd-solanki** [comment]
Oh, I didn't I can modify the value. Thanks, I will give it a try and will let you know.

Can I keep this open till I resolve this?

**Comment by jd-solanki** [comment]
Hi, @chu121su12 Thanks for the hint. I have created a new variant for converting `rem` to `em`.

```ts
[

  // `em:` variant converts rem unit into em
  (matcher: string) => {
    if (!matcher.startsWith('em:'))
      return matcher

    return {

      // slice `em:` prefix and passed to the next variants and rules
      matcher: matcher.slice(3),
      body: (body: unknown[][]) => {
        body.forEach(v => {

          // v[1] can also be number
          if (typeof v[1] === 'string' && v[1].endsWith('rem'))
            v[1] = `${v[1].slice(0, -3)}em`
        })

        return body
      },
    }
  },
],
```

Thanks `@antfu` for keeping this open.

As custom variant allows modifying body as well, it should be documented. Moreover, if you can let me know what edge cases I need to handle with the above variant I will be able to make it robust and if you want, I will make a PR for this variant 🥳 

> I'm closing this as my query is resolved.
