### ISSUE TITLE
Error when using with stylelint

### ISSUE THREAD

**Issue by hackyoMa** [unocss/unocss#1181]
[plugin:vite:stylelint] No files matching the pattern "/__uno.css" were found.
<img width="659" alt="image" src="https://user-images.githubusercontent.com/18374520/176067156-bcfc6d6a-42ee-48f4-bafc-c46d4ce1a8e7.png">

**Comment by antfu** [comment]
Can you just ignore the entry? I am actually against running linter in build pipelines as it's meanless to lint intermediate state of the transformed code.
