### ISSUE TITLE
arbitrary background-image not working

### ISSUE THREAD

**Issue by CanRau** [unocss/unocss#1182]
I'm trying to use `bg-[url('/img/hero-pattern.svg')]`, which should work due to this [PR#757](https://github.com/unocss/unocss/pull/757) requested by this [issue#755](https://github.com/unocss/unocss/issues/755)

I've got the following config (using as lib within a Remix Deno route using `Deno.readTextFile` to read the code to feed into `generator.generate`)

```ts
const generator = createGenerator({
  presets: [
    presetUno(),
    presetIcons({
      collections: {
        carbon: async () => {
          const response = await fetch("https://esm.sh/@iconify-json/carbon@1.1.5/icons.json");
          return JSON.parse(await response.text());
        },
      },
    }),
  ],
});
```

also tried to add 

```ts
[/bg-\[(url\([^\s]+\))\]/, ([a, b]) => {
  console.log({ a, b });
  return { backgroundImage: b };
}],
```
this doesn't even log to the console 🤔 in different variations without any luck, it's never picking up bg-images, though the `bg-[length:10_20rem]` class which I took from the [PRs test](https://github.com/unocss/unocss/pull/757/files#diff-44cf4f0b3cecf380c5f93e4e5dd6f7442227a23d2737ceb191e27d3245d5fae2) works as expected

this is my tsx
```tsx
className="text-red-500 bg-[length:10_20rem] bg-[url('/img/hero-pattern.svg')]"
```

by the way I'm checking the generated css which is tiny and doesn't contain any background-image related stuff

okay finally got it working with the following custom rule

```ts
[/bg-\[(.+)\]/, ([a, b]) => {
  console.log({ a, b });
  return { "background-image": b };
}],
```
and using the following class `bg-[url(/assets/wholesitekond_illu.jpg)]` omitting the `'` single quotes, otherwise it wouldn't work 🤔🤷‍♂️

Though would be great to have the preset rule work and also with quotes in the class to have easier interop with tailwind as I'm currently trying to switch

**Comment by chris-zhu** [comment]
Unocss has this util function resolve url string, and other rules resolve url missed `'` single quotes both.
https://github.com/unocss/unocss/blob/47a861d628eaa67f0967756f76ad72acc2e79c8b/packages/preset-mini/src/utils/handlers/handlers.ts#L97-L117

If we add `'` single quotes to align with tailwind, it would be a breaking change

**Comment by CanRau** [comment]
Huh, you're right I didn't consider trying the built-in rule without quotes, so now I can at least drop my custom rule, thanks a lot 🙏

**Comment by chu121su12** [comment]
The rule should support single quote just fine, however the quotes get removed earlier in the splitting phase
https://github.com/unocss/unocss/blob/6b392951b59cb46d737140e5b6d16e78a161ab84/packages/core/src/extractors/split.ts#L4

This [example](https://unocss.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIBGBzAtAbQFcAnOACgHowBbbCgCwFNiB7XABwQBcvmA7AHRII2AJQBddAD4AhACggA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAqrhJQL5xZQQhwDkAV1YBjOnX5IkGAB6RY6bAENBAG3iYc%2BIiWCkAFMlQ16jOgC44AbSrHaDZq30BKSqgC6buHSVYMq4DoYSxtUVAAiACNSAForQShVfX4AelBSFIALDB4YsCUYGBzcADo6ADdSfmd3cK9PJHZnJCA&options=N4IgzgLgTglgxhEAuaBXApgXyA) places the quoted token in the safelist, which is processed as is and if you have access to the generator, sending in `Set()` will work similarly.

https://github.com/unocss/unocss/blob/6b392951b59cb46d737140e5b6d16e78a161ab84/packages/core/src/generator/index.ts#L134-L136



I guess removing the single quote from the splitter may cause problem in vue-like class-object syntax or something similar.
```
:class="{ 'border': condition }"
```

**Comment by antfu** [comment]
It's not recommended to use urls inside the bracket. I would suggest writing a custom rule for that, or directly using `style` in your components. UnoCSS uses quotes to split the utils on extracting and we are probably not going to support quotes in rule, at least in the near future. Quote matching is a very complex thing to do right and will hurt the performance.
