### ISSUE TITLE
[vscode-intelisence] incorrectly detects typescript class as CSS

### ISSUE THREAD

**Issue by OmgImAlexis** [unocss/unocss#1183]
In a project I have code similar to the following, `static` is being detected by `UnoCSS`.

```ts
export class UserService {
    static async findById(id: string) {
        console.log(id);
    }
}
```

![image](https://user-images.githubusercontent.com/6525926/176335814-0f7b5d2e-7634-4595-9d51-bc5568c4b1fe.png)
![image](https://user-images.githubusercontent.com/6525926/176335838-51c27c62-7883-4b6a-8dff-96a065709969.png)

**Comment by TrickyPi** [comment]
Same as #978

**Comment by OmgImAlexis** [comment]
> Same as #978

Agreed only I cant really change `static` in this case. I also noticed it happening in `.d.ts` files which as far as I know will never have CSS in them.

**Comment by TrickyPi** [comment]
Currently, we can override `exclude` config for avoid this issue.

```js
Unocss({
  exclude:[/\.d\.ts$/]
})
```

**Comment by TrickyPi** [comment]
Currently, we can override `exclude` config for avoid this issue.

```js
Unocss({
  exclude:[/\.d\.ts$/]
})
```

**Comment by antfu** [comment]
.d.ts is not included by default

**Comment by TrickyPi** [comment]
Currently,  the`defaultExclude` not included  .d.ts.
https://github.com/unocss/unocss/blob/6b392951b59cb46d737140e5b6d16e78a161ab84/packages/shared-integration/src/defaults.ts#L3-L4

**Comment by OmgImAlexis** [comment]
> .d.ts is not included by default

Curious as to how it's being picked up then as I installed the plugin and havent changed any settings yet.
