### ISSUE TITLE
preflights styles should default to preflights layer instead of default

### ISSUE THREAD

**Issue by CanRau** [unocss/unocss#1186]
This was kind of confusing, I had to specifically set `layers: "preflights"` 

```
preflights: [
    {
      layer: "preflights", //    <----------- this
      getCSS: ({ theme }) => `
        .preflight {
          background: red;
        }
      `,
    },
  ],
```
I think this is really confusing as I'm specifically defining a preflight here, so I'd expect it to be in preflight and therefore ordered before other styles instead of needing to manually "duplicate" my intend.

What do you think? Though at this point this might be a breaking change I guess?

Also `preflights` aren't minified etc, I kinda understand that those are injected as is, though it feels unnecessary overhead for me to have to think about and do this 🤔

**Comment by antfu** [comment]
Yeah, that makes sense. PR welcome!
