### ISSUE TITLE
How to use nuxt development module template to develop UI Library

### ISSUE THREAD

**Issue by 516310460** [unocss/unocss#1209]
template: https://github.com/nuxt/starter/tree/module
Ask for your help

**Comment by antfu** [comment]
Can you be more specific?

**Comment by 516310460** [comment]
如何使用unocss和nuxt的模版[https://github.com/nuxt/starter/tree/module]，开发一套UI，目前我正在尝试，但是到了css这一块，我不知道该如何让组件拥有样式

**Comment by 516310460** [comment]
目前我知道的一个本办法就是让用户自己把所需要客制化的配置文件，在用一次，但是那可能需要再次让用户安装unocss以及其他插件

**Comment by 516310460** [comment]
主要是目前antdv和elementui对nuxt-v3的版本兼容真的是太难了，不可能让他们为了nuxt来调整，所以想自己着手写一个。采用sfc-tsx的方式，让代码更简洁、易懂，但是在css方便还是对unocss情有独钟，因为它非常棒

**Comment by antfu** [comment]
Since UnoCSS works at build time, I'd suggest asking users to use UnoCSS as well (or you can wrap a module and install it for users). You may refer to this project https://github.com/nuxt/ui/tree/main/packages/ui

**Comment by 516310460** [comment]
谢谢，没有想到这里已经有官方在开发UI库了，也许我应该贡献
