### ISSUE TITLE
breakpoints deep merge not working

### ISSUE THREAD

**Issue by Shyrro** [unocss/unocss#1211]
Hi there, 

I just ran into an issue when trying to configure custom breakpoints in a `Nuxt3` project.
If you configure your breakpoints like this : 

```ts
export default defineNuxtConfig({
    ...,
   unocss: {
     theme: {
        ...,
        breakpoints: {
          xs: '320px',
        },
     }
   }
})
```

All other breakpoints seem to be removed. You can check this commit that i added to my project : 

https://github.com/Shyrro/personnal-website/commit/36d6e24665966869718d9309d1f876bd6132df4a

If i uncomment the breakpoints config with the `xs` only, it doesn't work unless if i also uncomment the `md` breakpoint.

**Comment by antfu** [comment]
Able to reproduce:
https://uno.antfu.me/play/?html=DwEwlgbgBAtiBcAXApgD0QWgOYCdnIDspUBnJNTPEAPgBULgB6cCaoA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6NKD2UPx6eTBWMInQ9rikGIkAHAAME3AcpIkA7lXAvemR%2BvYSEhi4MN36vZb9EvxD41MzcxxOGwDWqy36HDC4e3ptIB38cDUAbhhQwQ2Wx23wgfwBhkwUCceDSslQeieuAATK93p9QeDgj4DkcTrgztNZokrrc4JD-jD8ABKMyoNSyEQKRrhNZMxjKCA%2BanwuSiZisdjcXgCbm89kwSTSPxrVB0CT2VKhACMADpkbzUBI0Lg8lVWGBGgB6I30ECq6pGuktNQ88qyGBVDAgDBNKgASA4tHsN0geAaboeLUsLL0AGZkRMwJZ7jbZGokLakEA&options=N4IgzgLgTglgxhEAuaBXApgGhNAhgOzADMB7KAW2SNwBswsQp0wAHEwmAN3StvoF8gA

**Comment by chris-zhu** [comment]
> Able to reproduce: https://uno.antfu.me/play/?html=DwEwlgbgBAtiBcAXApgD0QWgOYCdnIDspUBnJNTPEAPgBULgB6cCaoA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6NKD2UPx6eTBWMInQ9rikGIkAHAAME3AcpIkA7lXAvemR%2BvYSEhi4MN36vZb9EvxD41MzcxxOGwDWqy36HDC4e3ptIB38cDUAbhhQwQ2Wx23wgfwBhkwUCceDSslQeieuAATK93p9QeDgj4DkcTrgztNZokrrc4JD-jD8ABKMyoNSyEQKRrhNZMxjKCA%2BanwuSiZisdjcXgCbm89kwSTSPxrVB0CT2VKhACMADpkbzUBI0Lg8lVWGBGgB6I30ECq6pGuktNQ88qyGBVDAgDBNKgASA4tHsN0geAaboeLUsLL0AGZkRMwJZ7jbZGokLakEA&options=N4IgzgLgTglgxhEAuaBXApgGhNAhgOzADMB7KAW2SNwBswsQp0wAHEwmAN3StvoF8gA

This question isn't theme deep merge unsuccess.
https://github.com/unocss/unocss/blob/e8f5f1bd56bb8e21aa6fb01ebe52feaba947922f/packages/preset-mini/src/utils/utilities.ts#L182-L191
This function  resolve breakpoints use user configuration is preferred, it's the reason for this bug.
Last modify by #784, I don't understand the significance of this change.

Should we use the theme configuration directly?
```
export const resolveBreakpoints = ({ theme, generator }: Readonly<VariantContext<Theme>>) => {
  // let breakpoints: Record<string, string> | undefined
  // if (generator.userConfig && generator.userConfig.theme)
  //   breakpoints = (generator.userConfig.theme as any).breakpoints

  // if (!breakpoints)
  //   breakpoints = theme.breakpoints

  return theme.breakpoints
}
```

**Comment by antfu** [comment]
Yeah, I guess this is probably intended for users to have full control of the breakpoints.

You might probably just copy over the built-in breakpoints and append yours.

**Comment by Shyrro** [comment]
If that's the case, then the documentation should be updated here to specify it : 

https://github.com/unocss/unocss/blob/e8f5f1bd56bb8e21aa6fb01ebe52feaba947922f/README.md?plain=1#L477

Because it clearly states that the theme configuration is deep merged with a given example of breakpoints.
