### ISSUE TITLE
Variant groups broken by uneven amount of quotes

### ISSUE THREAD

**Issue by t2t2** [unocss/unocss#1215]
For example caused by English words like "can't":

```html
<div class="before:(content-[✅] mx-2)">
  Checkmark
</div>
Can't use variant groups after this
<div class="before:(content-[✅] mx-2)">
  Missing
</div>
```
[playground](https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIBGBTAZgewCdsAuAChnwDsAXbWgWgG1BQcgF0oBbADwYCYAlOgB8AKChQAwgAtsMANacEheaOAB6cBDGSEVAOQ0oAVyTYoEZWD1GA5oXzGADkigJcdQlBrSwSNVqwiCgYOATE5JS09DTM7Fy8giLiUACyfkhgVLZqmpBiQA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpwxQCGuAzltCBlAGq1TD0wDiUCAFcwlVGCgYGGGAFVcESgF84WQSDgByIQoDGDBpqRIMAD0ix02WkIA28TDnxESwUgApkqKHakAuOABtKlRAzV0hBhgIEABaH1sMTXJEOF0IW2gAzUk0TTglAF0qQrE4BgALaBgImAYAr1QtCKiY2Mrq2s1smDMYWNtSaj7Y6HpSDDgqgDc2P17Tft7aWyNUJTKJKRl6oJC4Lek5BXcASjLSqhp6JhY2XeCm6jpGZihWDi4eXH5BETOSkglKckEA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g)

It's not an issue if there's more than one word using the quote, but it breaks again if there's an odd amount until end of file:

```html
<div class="before:(content-[✅] mx-2)">
  Checkmark
</div>
Works b'tween
<div class="before:(content-[✅] mx-2)">
  Checkmark
</div>
And a'ter
<div class="before:(content-[✅] mx-2)">
  Checkmark
</div>
But breaks again on odd'th quote
<div class="before:(content-[✅] mx-2)">
  Missing
</div>
```
[playground](https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIBGBTAZgewCdsAuAChnwDsAXbWgWgG1BQcgF0oBbADwYCYAlOgB8AKChQAwgAtsMANacEheaOAB6cBDEB1IvKRRMAchoB3bPTVbYiFBhwFi5SrXo1m7Lr0EjxU2QUlFTVNSDEAQSoQKARTbEJrSFtkNCw8IlIKajpGVg4efiExCRk5RWVVDS0xACEAVxojYgQDWIBzBDAqKGpekBBTaSgAR3r8OiToeFSHDOdstzyvQt8SqABZMBRu9tCa0SA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpwxQCGuAzltCBlAGq1TD0wDiUCAFcwlVGCgYGGGAFVcESgF84WQSDgByIQoDGDBpqRIMAD0ix02WkIA28TDnxESwUgApkqKHakAuOABtKlRAzV0hBhgIEABaH1sMTXJEOF0IW2gAzUk0TTglAF0qQrE4BgALaBgImAYAr1QtCKiY2Mrq2s1smDMYWNtSaj7Y6HpSDDgqgDc2P17Tft7aWyNUJTKJKRl6oJC4Lek5BXcASjLSqhp6JhY2XeCm6jpGZihWDi4eXH5BETOSkglKckEA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g)

One more test case:

```html
<div class="before:(content-[✅] mx-2)">
  Checkmark
</div>
<div :class="'before:(content-[✅] mx-2)'">
  Transformed
</div>
And for vue'like
<div class="before:(content-[✅] mx-2)">
  Checkmark
</div>
<div :class="'before:(content-[✅] mx-2)'">
  Not transformed
</div>
<div class="before:(content-[✅] mx-2)">
  Missing
</div>
```
[playground](https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIBGBTAZgewCdsAuAChnwDsAXbWgWgG1BQcgF0oBbADwYCYAlOgB8AKChQAwgAtsMANacEheaOAB6cBDGhIUEvGRp0AchwFi5SrXo1m7Lr0EmR4qABVCCKkgudsIGqakGIAglQgUBZQEACu2CZwYPLYalqwiCgY5kSkFNR0jKwcPPxCYhIycorKqhpaOukGmcZmeLlWBbb2JU4CLhVQAHL4NFA0Xj5%2BAUENaXqGWVjtlvk2RQ6lgq4SALJgKGBUAOazIaJAA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpwxQCGuAzltCBlAGq1TD0wDiUCAFcwlVGCgYGGGAFVcESgF84WQSDgByIQoDGDBpqRIMAD0ix02WkIA28TDnxESwUgApkqKHakAuOABtKlRAzV0hBhgIEABaH1sMTXJEOF0IW2gAzUk0TTglAF0qQrE4BgALaBgImAYAr1QtCKiY2Mrq2s1smDMYWNtSaj7Y6HpSDDgqgDc2P17Tft7aWyNUJTKJKRl6oJC4Lek5BXcASjLSqhp6JhY2XeCm6jpGZihWDi4eXH5BETOSkglKckEA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g)

**Comment by chris-zhu** [comment]
It seems that this function does not match the code correctly.
https://github.com/unocss/unocss/blob/cfdffe5690edc5acbfb1ad6b6c9493b7c9d90f27/packages/core/src/utils/extractQuoted.ts#L45-L124

I will handle this question be later.
