### ISSUE TITLE
Conflict with other component properties

### ISSUE THREAD

**Issue by shtse8** [unocss/unocss#1218]
Attributify mode is really cool. I like it very much. it has great experience comparing writhing string in class attribute.
but sometime it has conflict with other component properties. Any better solution to solve this?

for example: `v-height` which has conflict with vue reactive property.

**Comment by antfu** [comment]
You can use add `un-` prefix: https://github.com/unocss/unocss/blob/main/packages/preset-attributify/README.md#properties-conflicts
