### ISSUE TITLE
UnoCSS for VSCode failed to load vite config

### ISSUE THREAD

**Issue by Garfield550** [unocss/unocss#1219]
I tried uninstall and reinstall (local and remote ssh).

VSCode Version: 1.68.1 (Universal)

```
UnoCSS for VS Code  v0.43.0 <home>
[info] Resolving config for <projectRoot>
[info] Resolving config for <projectRoot>
[info] New configuration loaded from
    - <projectRoot>/vite.config.ts
[error] Error: ENOENT: no such file or directory, unlink '<projectRoot>/__unconfig_vite.config.ts'
[error] Error occurred while loading config. Config directory: <projectRoot>
```

<img width="928" alt="09233" src="https://user-images.githubusercontent.com/3471836/177159473-21785fb8-9ba1-492d-8f3d-52c90954e3f5.png">
<img width="212" alt="image" src="https://user-images.githubusercontent.com/3471836/177159553-143ee7da-3f4b-4ed8-ba77-db145c82c5ec.png">

**Comment by so1ve** [comment]
The UnoCSS plugin is stuck loading configuration.
This problem happens in my Nuxt3 project and Vite + React project.

````
UnoCSS for VS Code v0.43.1 D:\Code-Insiders
[info] Resolving config for e:\Node\dolan-client-ref
[info] Resolving config for e:\Node\dolan-client-ref
````

**Comment by Garfield550** [comment]
After upgrading to 0.43.1 it worked again, but the error message still exists.
But it's still not stable, it won't work when you open VSCode and wait until it restores the last remote connection.

<img width="318" alt="image" src="https://user-images.githubusercontent.com/3471836/177269317-571f5c94-d0e0-4ebf-8e5f-bfba7d7f8c9f.png">


```
UnoCSS for VS Code  v0.43.1 <home>
[info] Resolving config for <projectRoot>
[info] Resolving config for <projectRoot>
[info] New configuration loaded from
    - <projectRoot>/vite.config.ts
[error] Error: ENOENT: no such file or directory, unlink '<projectRoot>/__unconfig_vite.config.ts'
[error] Error occurred while loading config. Config directory: <projectRoot>
```
