### ISSUE TITLE
windicss divide-y 错误

### ISSUE THREAD

**Issue by c4ys** [unocss/unocss#1222]
在windicss中以下代码会正确显示，每行之间的中划线

```
<div class="text-4xl text-green-700 text-center py-20">
      <h1>Hello windi-css!</h1>
      <div class="flex flex-col divide-y divide-dark-500">
        <div>test</div>
        <div>test</div>
        <div>test</div>
      </div>
</div>
```
在unocss下，必须：

```
<div class="text-4xl text-green-700 text-center py-20">
      <h1>Hello windi-css!</h1>
      <div class="flex flex-col divide-y divide-x-0 divide-solid divide-dark-500 divide-solid">
        <div>test</div>
        <div>test</div>
        <div>test</div>
      </div>
    </div>
```

**Comment by chris-zhu** [comment]
> 在windicss中以下代码会正确显示，每行之间的中划线
> 
> # Hello windi-css!
> test
> test
> test
> 在unocss下，必须：
> 
> # Hello windi-css!
> test
> test
> test

There seems to be no problem.
[Playground](https://unocss.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCJwTCApgWgE8oscCAXXBOfAVgAZ70A%2BAKCilEmYEZgB6LGw5cIzAEwCh7TkIDMU7q0VjlAIwBO-NqJKQyGYpWp1GLGaN4rhs7pMFKR868oeqgA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyYbRYTt4AFjB0AFya9k4MslDO9FEA2lSoyXoSXHQwOgC0CU4YeuSIcFJO0FF6tGh6cGoAulSNsnQh0DBZ4VH%2BqPpZOfntnd161TBWMHlOpHCTltPQ9rikGHAdAG4YUBEL05MxZqhqsiIKkXCp-XKiSio%2BAJSyAXcsbJw8fPxPL7cKkmkfjS-ToEhiGCiAEYAHQAJj%2BqAkaFw1TCMDAkQA9Fj6CAYe0scd%2Bmpni11I8kEA&options=N4IgzgLgTglgxhEAuaBXApgGhNAhgOzADMB7KAW2SNwBswsQp0wAHEwmAN3StvoF8gA)

**Comment by c4ys** [comment]
昨天使用vue默认模板也有这个问题，所以今天再用solidjs试一下，然后直接用windicss就显示正常。恰好solidjs模板都支持windi和unocss.

感谢回复。

**Comment by chris-zhu** [comment]
> 昨天使用vue默认模板也有这个问题，所以今天再用solidjs试一下，然后直接用windicss就显示正常。恰好solidjs模板都支持windi和unocss.
> 
> 感谢回复。

Yes, i understand it. `divide-y` missed `divide-solid`, i will resolve it be later.
Previously, `border` had the same problem, it had fixed. Thanks for the discovery

**Comment by c4ys** [comment]
在我的环境生成的css:

```
.divide-teal-500>:not([hidden])~:not([hidden]) {
    --un-divide-opacity: 1;
    border-color: rgba(20,184,166,var(--un-divide-opacity));
}

.divide-y>:not([hidden])~:not([hidden]) {
    --un-divide-y-reverse: 0;
    border-top-width: calc(1px * calc(1 - var(--un-divide-y-reverse)));
    border-bottom-width: calc(1px * var(--un-divide-y-reverse));
}
```

在playgroud环境生成的css：

```
.divide-teal-500>:not([hidden])~:not([hidden]), [divide~="teal-500"]>:not([hidden])~:not([hidden]) {
    --un-divide-opacity: 1;
    border-color: rgba(20,184,166,var(--un-divide-opacity));
}
.divide-y>:not([hidden])~:not([hidden]), [divide~="y"]>:not([hidden])~:not([hidden]) {
    --un-divide-y-reverse: 0;
    border-top-width: calc(1px * calc(1 - var(--un-divide-y-reverse)));
    border-bottom-width: calc(1px * var(--un-divide-y-reverse));
}
```

**Comment by chris-zhu** [comment]
> 

以上生成的css代码没有差别，在你本地`divide` 没有显示`border`的原因，是因为缺少`border-style`。在playground中能看到，是因为引入@unocss/reset 进行样式重置。我会提个PR尝试去修复`divide`。
