### ISSUE TITLE
unocss/preset-icons setting error

### ISSUE THREAD

**Issue by daluozha** [unocss/unocss#1227]
Here is my setting in vite.config.ts:
<img width="614" alt="image" src="https://user-images.githubusercontent.com/35727398/177495177-bafae34f-f075-43b6-949d-8054d1d5a2e4.png">

but some error messages appeared:

>  Type 'Preset<{}>' is not assignable to type 'Preset<Theme> | Preset<Theme>[]'.
  Type 'Preset<{}>' is not assignable to type 'Preset<Theme>'.
    Types of property 'rules' are incompatible.
      Type 'Rule<{}>[] | undefined' is not assignable to type 'Rule<Theme>[] | undefined'.
        Type 'Rule<{}>[]' is not assignable to type 'Rule<Theme>[]'.
          Type 'Rule<{}>' is not assignable to type 'Rule<Theme>'.
            Type '[RegExp, DynamicMatcher<{}>]' is not assignable to type 'Rule<Theme>'.
              Type '[RegExp, DynamicMatcher<{}>]' is not assignable to type '[string, CSSObject | CSSEntries]'.
                Type at position 0 in source is not compatible with type at position 0 in target.
                  Type 'RegExp' is not assignable to type 'string'.ts(2322)

How can I fix the problem ? 

vite.config.ts full text : [click here](https://github.com/daluozha/PAPERCRAFT/blob/luozha/feat_preset-icons/vite.config.ts)

**Comment by antfu** [comment]
The version does not match https://github.com/daluozha/PAPERCRAFT/blob/472e78f2624f7f9488159b4b4d38e1936aac0dce/package.json#L20-L24
