### ISSUE TITLE
theme.colors nesting issues

### ISSUE THREAD

**Issue by blowsie** [unocss/unocss#1230]
Creating nested colors in the theme config does not work.
I was able to make a workaround by using lowerCamelCasedKeys.

I believe this is a bug?

```javascript
  theme:{
    colors:{
      crimson: 'crimson', // bg-crimson PASS
      nested: {
       yellow: 'yellow', //  bg-nested-yellow PASS
       twice: {
         green: 'green' // bg-nested-twice-green FAIL
       }
      },
      nestingWorkaroundGreen: 'green' // bg-nesting-workaround-green PASS
    }
  },
```

[Playground Reproduction](https://uno.antfu.me/play/?html=DwCwTgBAxgNghgZwQXgEQCMDmBaKYCWAtggPYB2EA7tgCwQi0SGNgkCuZAJgKafYDMEdCTA8wqAHwAoUJFiIUGHGW4IALr2wBPbjBglKVRgzrM6rDjz6Dho7uOmzo8JGizYV6zWsr4o3bEwwbm4KajoTJhZ2Lk0bETFJGXBnBTdlVTV8MhxKEQBrOAsuQODQowjGMwhiqwEhBPtJIA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVDAAFhggGABc-qhwUk7QdBFUUdHsIHTEYfoSKWm4erJJ%2BHQwGGgZkUlw-BhOsQDuGXpVNRC1eYlJMLXAEuGI7RWktBi4DYMYw2YVqGr9cGr5UYW8uKQA6tAA1vbahmgA4kMj%2BmMT7TPTslDO9BkA2u23ehJcRToAtFdOGHmI0RCxUAatDQejmAF0qGDZHRAtAYM8YPE%2Bkkni8YO8YXCEXoGsVLDA3k5SHA8QToPYVhg4LCAG4YQGkt7FexOSZzWQiBRI%2B5JTmMZQQHwASgWfOYrHY3F4AmFovk4ikuDoflmdAkLN6AEYAHQAJgWqAkaCOekCrDA8QA9Jb6CBtTDLWzpiLIUg1EKkEA&options=N4XyA)

**Comment by chris-zhu** [comment]
UnoCSS supports nesting levels of less than or equal to 2.

https://github.com/unocss/unocss/blob/aa41449259b5404ad27fe4b1262440393284df9c/packages/preset-mini/src/utils/utilities.ts#L86-L90
