### ISSUE TITLE
Dynamic shortcut named "link" not work

### ISSUE THREAD

**Issue by impcyber** [unocss/unocss#1232]
shortcut with "link-" doesn't work:
```js[
/^link-(.*)$/, ([, c]) => `text-${c}-700 border-b-1 border-${c}/30 hover:text-${c}-500 hover:border-${c}-500/10`],
```

if i rename "link-" to "test-" works fine:
```js
[/^test-(.*)$/, ([, c]) => `text-${c}-700 border-b-1 border-${c}/30 hover:text-${c}-500 hover:border-${c}-500/10`],
```

[Playground](https://uno.antfu.me/play/?html=DwEwlgbgBArgtAMwDYFMAeBeARAPygYwHsktY4ALbBGJEssAFxQFsBnbfFAOyYCdT4AKxisGYBAE8O3PlgB8AKChRgAQyjleKBNgDEAuEjBcA1thzyjp4AHpVi5Wo1adWfWStmsrExMvGTKB8JW3slFXVNbT0DT3Mg339TBIkoHFCHFQAjXigbTKco13d4JlFzeTKGDPDClxiyKuxgypRRFJrHSPq3AybcFNb24LSa23AIOSA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVHQAFtAwEjx0AFxwANpUqAD08Yh6TngA1npRejBWMAC0TqRwOZb50Pa4pBhwwQBuGFARJfk59k56arKo0fEAeqm4aXk%2BAHQAVACUACTx5HA%2B0XMSALoTcAC8AHxwAAbNeVMIEmp5AOwADOdwHNCYUHkceQCM17cNB0dq8QDMV3UNTVyH2OeQArJcahB6o0blA7sCTuDzvEnucdssujE%2Bjk6PlRpMZnMFktVhttnsgYcQRcrrD4Y8XnT3lSvr9IdDAaUEWCIf8YW97iyecjUejZBiqCIFJEYnE5KIlCo-HLULV7Ox7BwnBgAAq0HCWLJcPJ6TGoeysdjcXgCHUMLhoCBRNhcDCYtQTTFSxgsNicHh8fjK1Ah%2BUGo0ms1h4CWDBoADyuCc-GdUFd7s9cu9MEk0mDobguSg9j1EDADV49Ci-gLqDQwDoYCc9hT%2BjwAwwDycEAkGSjnTlHqoyyQQ6AA&options=N4XyA)

**Comment by chu121su12** [comment]
`link` is part of pseudo prefix

https://cs.github.com/unocss/unocss/blob/aa41449259b5404ad27fe4b1262440393284df9c/packages/preset-mini/src/variants/pseudo.ts#L12

**Comment by impcyber** [comment]
@chu121su12 Thanks!
