### ISSUE TITLE
@apply and variant groups throws errors

### ISSUE THREAD

**Issue by ErlinEmrys** [unocss/unocss#1234]
Hi guys,

I'm new in web development, so maybe I'm doing some mistakes here, but I can't find what I'm doing wrong.

I have created project, that using vite, svelte and unocss (with attributify). Unfortunately some features of unocss throws me an errors even if majority of it works. What bothers me is that:

1. I'm getting error if I try to use @apply directive (Semicolon or block is expected). If I use "--at-apply" instead, it is working.
2.  Variant groups throws error (xxx is not a valid attribute name) when inline or just don't work when used as "--at-apply".

I have sample project, both issues can be observed here:
[https://github.com/ErlinEmrys/WebAppTemplate/blob/main/ClientApp/src/Pages/Home.svelte](https://github.com/ErlinEmrys/WebAppTemplate/blob/main/ClientApp/src/Pages/Home.svelte)

Could you please help me identify what is going on? Thank you

**Comment by antfu** [comment]
1. It's probably because Svelte does not understand `@apply`, that's why we have `--at-apply` as another option.
2. It's `hover:` not `hoover:`

**Comment by ErlinEmrys** [comment]
Thank you for your time @antfu !

1. I thought that `@apply` is css directive and does not have connection to svelte at all. But as I said, I'm beginner at this.
2. Oh, that was typo. It works somewhat now, thank you.
