### ISSUE TITLE
`text-[0.7rem]` is generating wrong CSS

### ISSUE THREAD

**Issue by jd-solanki** [unocss/unocss#1235]
Interactive docs: [View](https://uno.antfu.me/?s=text-[0.7rem])

Tailwind play: [View](https://play.tailwindcss.com/XIPrEWuhkx)

**Comment by chu121su12** [comment]
Currently this is intentional. See #935.

**Comment by antfu** [comment]
@chu121su12 Maybe we could do an auto-detection when the context is not specified?
