### ISSUE TITLE
Compatibility issues with new SvelteKit version and vite config

### ISSUE THREAD

**Issue by UltraCakeBakery** [unocss/unocss#1236]
SvelteKit no longer has the vite plugin inside `svelte.config.js`. It now is just inside `vite.config.js`. This change makes the unocss docs outdated.

Besides that, there is also an issue where if the SvelteKit vite plugin runs BEFORE the unocss plugin, unocss causes SvelteKit to not work. Not sure why though.

You can check the new SvelteKit project structure out by quickly initializing a skeleton project using `npm init svelte@next`. Then install unocss inside the `vite.config.js`. Depending on the order of vite plugins as I described above, SvelteKit may not work.

**Comment by userquin** [comment]
@UltraCakeBakery we need to update the example, PR welcome

**Comment by userquin** [comment]
@UltraCakeBakery I'll take a look and check what's happening...

**Comment by userquin** [comment]
@UltraCakeBakery I have `SvelteKit` plugin before and after `UnoCss` running in dev and build + preview, what's the error in your side?

**Comment by userquin** [comment]
build + preview with SvelteKit next.367 and static adapter next.35 (SvelteKit plugin after UnoCSS plugin)

https://streamable.com/2e0k6r ()

**Comment by UltraCakeBakery** [comment]
> @UltraCakeBakery I have `SvelteKit` plugin before and after `UnoCss` running in dev and build + preview, what's the error in your side?

There is no error. SvelteKit simply isn't responding as if it is endlessly processing something. I'll put together a reproduction tomorrow.

**Comment by userquin** [comment]
@UltraCakeBakery https://stackblitz.com/edit/sveltejs-kit-template-default-wnmf33
