### ISSUE TITLE
Attributify mode not working with React

### ISSUE THREAD

**Issue by Shyrro** [unocss/unocss#1238]
Hi, 

Just launched an app with React, classes seem to be present when using classes, but when using attributify-mode, react throws  a console error : 

```
Warning: Received `true` for a non-boolean attribute `bg-red`.

If you want to write it to the DOM, pass a string instead: bg-red="true" or bg-red={value.toString()}
```

I've also tried to pass `bg-red=""` because that's what it compiles to in the DOM but didn't work either.

Here is a reproduction : 

https://stackblitz.com/edit/vitejs-vite-nhdc1l?file=src%2FApp.jsx&terminal=dev

**Comment by so1ve** [comment]
Hey,
read the docs.
https://github.com/unocss/unocss/tree/main/packages/vite
You should do this:
```
export default defineConfig({
  plugins: [
    Unocss({
      presets: [presetAttributify(), presetUno()],
    }),
    react(),
  ],
});
```

**Comment by antfu** [comment]
Sadly I think this is a limitation of React https://stackoverflow.com/questions/49784294/warning-received-false-for-a-non-boolean-attribute-how-do-i-pass-a-boolean-f

You probably need to avoid using valueless attributify mode but use `bg="red"` instead.
