### ISSUE TITLE
Extend theme from a rule

### ISSUE THREAD

**Issue by carpad88** [unocss/unocss#1251]
Hi, this is not an issue but a question about extending the `theme` inside rules.

Is it possible to extend the `theme` object from a custom rule?

I have the following rule:

```js
[/^fluid-\[(\d+)_(\d+)(?:\/(.+)_(.+))?]$/, ([, min, max, minL, maxL], { rawSelector, constructCSS, theme }) => {
    const selector = escapeSelector(rawSelector)
    const { valueZero, min: minFont, max: maxFont } = sizesParser({ min, max })
    const { valueZero: leading } = sizesParser({ min: minL, max: maxL })

    const cssProperties = constructCSS([
      ['--tt-key', selector],
      ['--tt-max', 1440],
      ['font-size', `${((minFont + maxFont) / 2) / 16}rem`],
    ])

    const keyFrame = `
      @keyframes ${selector} {
          0% {
              font-size: ${valueZero / 16}rem;
              line-height: ${leading};
          }
          100% {
              font-size: ${maxFont / 16}rem;
              line-height: ${maxL};
          }
      }
    `
    return [cssProperties, keyFrame]
  }],
```

The idea here is to add the keyframe to the `theme` object,  as if it was added in the `unocss.config` like this:

```js
theme: {
  animation: {
    keyframes: {
      fluidType: '{ 0% { font-size: 1rem;  line-height: 1.6; }  100% { font-size: 1.5rem; line-height: 1.2; }}'
    },
  }
}
```

But using rules to be able to generate keyframes dynamically

**Comment by carpad88** [comment]
> I am not sure why you want to do this. Theme should be served as data/config to consume but probably not a good idea to use it to preserve/interchange states

I'm trying to make a preset to use fluid-typographic as [here](https://docs.typetura.com/how-typetura-works).

My goal is to write something like this `fluid[16_24]` that under the hood needs to create some dynamic animation and use it. I already saw how to add animation easily to the `theme.config`, so for that reason I was looking how to edit the theme from the rule, but maybe  I'm missing something and I should try other approach.

The problem I'm getting is that the rule at has to create the animation but at the same time the css class that will be using it any that is where I got stuck.

**Comment by carpad88** [comment]
@antfu 
Is it possible with unoccs to inject a css keyframe on the fly and return only the selector from the rule?

I managed to get this working in this way

```html
<h1 class="ft[16_48/1.1_1.3]">
  This is a fluid heading
</h1>
```

```js
  [/^ft\[(\d+)_(\d+)(?:\/(.+)_(.+))?]$/, ([, min, max, minL, maxL], { rawSelector, constructCSS, generator }) => {
    const selector = escapeSelector(rawSelector)
    const { valueZero, min: minFont, max: maxFont } = sizesParser({ min, max })
    const { valueZero: leading } = sizesParser({ min: minL, max: maxL })

    return `
      @keyframes ${selector} {
          0% {
              font-size: ${valueZero / 16}rem;
              line-height: ${leading};
          }
          100% {
              font-size: ${maxFont / 16}rem;
              line-height: ${maxL};
          }
      }
      .${selector} {
        --tt-key: ${selector};
        --tt-max: 1440;
        font-size: ${((minFont + maxFont) / 2) / 16}rem;
      }
    `
  }],
```

However when I want to use in a shorcut or with `@apply` I got this on the browser, therefore the utility doesn't work as expected.

```css
h2 {
  @keyframes ft\[13_32\/1\.1_1\.3\] { 0% { font-size: 0.47321428571428575rem;
  line-height: 1.042857142857143;
  } 100% { font-size: 2rem;
  line-height: 1.3;
  } } .ft\[13_32\/1\.1_1\.3\] { --tt-key: ft\[13_32\/1\.1_1\.3\];
  --tt-max: 1440;
  font-size: 1.40625rem;
  }: ;
}
```

**Comment by antfu** [comment]
https://github.com/antfu/unocss/blob/d290c847cb261bc50d31773a6841cee09df8c8f6/packages/preset-wind/src/rules/animation.ts#L23-L29
