### ISSUE TITLE
'@unocss/reset/tailwind.css'   Causes the Element-Plus button to have no color

### ISSUE THREAD

**Issue by k983551019** [unocss/unocss#1254]
button, [type='button'], [type='reset'], [type='submit'] {
    -webkit-appearance: button;
    background-color: transparent;
    background-image: none;
}
![image](https://user-images.githubusercontent.com/48147837/178741653-0481a414-a0de-4c24-8d76-173f3770e478.png)

![image](https://user-images.githubusercontent.com/48147837/178741496-2648e862-19fc-4880-bf6d-2268b13a0ab5.png)

**Comment by antfu** [comment]
You don't need the reset when using with component lib

**Comment by JessicaSachs** [comment]
@antfu without the reset, rings, active state, etc don't work. Is it possible to have a scoped reset?

**Comment by zyyv** [comment]
> @antfu without the reset, rings, active state, etc don't work. Is it possible to have a scoped reset?

Related to #2127, we will soon have in #2128. You can review or comment at #2128.
