### ISSUE TITLE
VSCode extension error, no tooltip

### ISSUE THREAD

**Issue by wu-pan** [unocss/unocss#1255]
VSCode version：1.69.1
extension version：0.44.1
Disable other extensions, only UnoCSS is enabled

```
UnoCSS for VS Code  v0.44.1 C:\Users\wupan\AppData\Local\Programs\Microsoft VS Code
[info] Resolving config for c:\Users\wupan\code\unocss-test
[error] ReferenceError: Cannot access '_require2' before initialization
[error] Error occurred while loading config. Config directory: c:\Users\wupan\code\unocss-test
```

**Comment by dusionlike** [comment]
add the file `unocss.config.ts`
can be empty🤨

**Comment by wu-pan** [comment]
> add the file `unocss.config.ts` can be empty🤨

work!!
but the directory already has vite.config.ts, I wonder why not.
thank you

**Comment by antfu** [comment]
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by adamburgess** [comment]
@antfu https://github.com/adamburgess/unocss-vscode-bug
`git clone`, `npm i`, and load into vscode, and you'll get the same error as OP.

**Comment by hcwhan** [comment]
some error

**Comment by Aicmortal** [comment]
me too
