### ISSUE TITLE
bug: input placeholder attr will be treated as className

### ISSUE THREAD

**Issue by NMTuan** [unocss/unocss#1257]
```html
<div class="w-96 mx-auto py-10 border bg-gray-100">
  <input class="p-4" placeholder=" border bg-red-400 "/>
</div>
```

url: https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIDuBaAnANigFsAPbBAVwBcB7KABwE9sBGABigCMaAnEAUx5cA5tmE8Ezdm3QA%2BAFBQowMADt61WIhQZ62ACzoGiGPwAWNOAJ4YuvayOw9%2BIA2w7oA9AuCfwEWSA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUkNikEA&options=N4XyA

**Comment by NMTuan** [comment]
I find this

![image](https://user-images.githubusercontent.com/2149763/178907579-a9c956bc-0810-42d8-a817-3d3cd00b8b0a.png)

I think, some attrs like placeholder should be a default options.

**Comment by chris-zhu** [comment]
You can use `un-placeholder="border bg-red-400"` instead of it

**Comment by NMTuan** [comment]
> You can use `un-placeholder="border bg-red-400"` instead of it

Sorry, i didn't express clearly
i want placeholder === 'border bg-red-400', and style !== 'border bg-red-400'.
like this:

![image](https://user-images.githubusercontent.com/2149763/178911870-19e18bba-be53-40a6-9403-905feccb17b4.png)

**Comment by chris-zhu** [comment]
> > You can use `un-placeholder="border bg-red-400"` instead of it
> 
> Sorry, i didn't express clearly i want placeholder === 'border bg-red-400', and style !== 'border bg-red-400'. like this:
> 
> ![image](https://user-images.githubusercontent.com/2149763/178911870-19e18bba-be53-40a6-9403-905feccb17b4.png)

Sorry, i understand your mean now.

**Comment by antfu** [comment]
Maybe we should add `placeholder` intro the default ignore list
