### ISSUE TITLE
Feature Request: add configFiles for hmr

### ISSUE THREAD

**Issue by YunYouJun** [unocss/unocss#1262]
## Request

Add `configFiles: string[]` to allow users pass multiple configs and merge them.

## Reason

I am writing a project that will allow users to place multiple `unocss.config.ts`.
I'm manually merging them, and use them for `unocss/vite` initialization.

`configDeps` can watch files and reload, but I have no way to retrigger their configuration read and merge.
It seems almost impossible to do this from the outside.

So I want to request unocss add `configFiles` option, or provide another way to do hot update.

**Comment by antfu** [comment]
Can you make an example project? I am not sure why you can't retrigger the merging.
