### ISSUE TITLE
[Nuxt rc.5] Unocss nuxt plugin shows warning : You are using a plugin that has not been wrapped in `defineNuxtPlugin`

### ISSUE THREAD

**Issue by leo91000** [unocss/unocss#1264]
In nuxt RC5, uno shows the following warning :

```
You are using a plugin that has not been wrapped in `defineNuxtPlugin`. It is advised to wrap your plugins as in the future this may enable enhancements: () => {}
```

[Reproduction](https://stackblitz.com/edit/github-uw48qt?file=nuxt.config.ts)

It should be fixeable by wrapping a `defineNuxtConfig` around the function here
https://github.com/unocss/unocss/blob/8e224a80c44a1f99fa139d7119c644883a2db096/packages/nuxt/src/index.ts#L40

**Comment by leosin** [comment]
try this 
```js
export default defineNuxtConfig({
  modules: ['@unocss/nuxt'],
  unocss: {},
});
```

**Comment by leo91000** [comment]
> try this
> 
> ```js
> export default defineNuxtConfig({
>   modules: ['@unocss/nuxt'],
>   unocss: {},
> });
> ```

Did it in the [Reproduction](https://stackblitz.com/edit/github-uw48qt-rlawwn?file=nuxt.config.ts) and I still have the same warning 🤔
