### ISSUE TITLE
unocss vscode extension not initializing

### ISSUE THREAD

**Issue by cpakken** [unocss/unocss#1280]
Same error in Windows 10 and WSL2.

My minimal testing setup
1) `pnpm create vite`  (using the react-ts template)
2) Added the `unocss/vite` plugin to `vite.config.ts`

Unocss Output from vscode:
```
UnoCSS for VS Code  v0.44.2 /mnt/c/Users/ckwon/AppData/Local/Programs/Microsoft VS Code
[info] Resolving config for /mnt/c/Users/ckwon/code/test/uno-react-ts
[error] ReferenceError: Cannot access '_require2' before initialization
[error] Error occurred while loading config. Config directory: /mnt/c/Users/ckwon/code/test/uno-react-ts
```
![image](https://user-images.githubusercontent.com/61718569/179339432-37432ac2-7ea1-4d3d-8c0b-05cab36ac36e.png)

Also reloading unocss from command pallet
![image](https://user-images.githubusercontent.com/61718569/179339387-2c945c19-1494-41e0-9803-7f1895998912.png)

Shows the error
![image](https://user-images.githubusercontent.com/61718569/179339405-1b3c9777-b3bf-4cb5-b33c-0a605a2dc78c.png)

**Comment by GODLiangCY** [comment]
To solve this, you should write your own unocss config in `vite.config.ts` or `unocss.config.ts`
e.g. In `vite.config.ts`
```typescript
import { defineConfig } from 'vite'
import unocss from 'unocss/vite'
import { presetUno, presetAttributify } from 'unocss'

export default defineConfig({
  plugins: [
    unocss({
      presets: [
        presetUno(),
        presetAttributify()
      ]
    })
  ]
})

```
Then the unocss extension works normally!

**Comment by GODLiangCY** [comment]
To solve this, you should write your own unocss config in `vite.config.ts` or `unocss.config.ts`
e.g. In `vite.config.ts`
```typescript
import { defineConfig } from 'vite'
import unocss from 'unocss/vite'
import { presetUno, presetAttributify } from 'unocss'

export default defineConfig({
  plugins: [
    unocss({
      presets: [
        presetUno(),
        presetAttributify()
      ]
    })
  ]
})

```
Then the unocss extension works normally!

**Comment by cpakken** [comment]
@GODLiangCY thanks for trying, but error still persists after adding the presets in vite.config.js

```ts
// vite.config.ts
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import Unocss from 'unocss/vite'
import { presetUno, presetAttributify } from 'unocss'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
    Unocss({
      presets: [presetUno(), presetAttributify()],
    }),
  ],
})

```

**Comment by cpakken** [comment]
Added unocss.config.ts and vscode unocss extension now loads. 

I don't think the extension is scanning my unocss configuration in vite.config.ts as stated in extension page details https://marketplace.visualstudio.com/items?itemName=antfu.unocss

How does unocss resolve its configuration if it's both declared in vite.config.ts and uno.config.ts?

**Comment by antfu** [comment]
> How does unocss resolve its configuration if it's both declared in vite.config.ts and uno.config.ts?

If `uno.config.ts` is presented, it will take the higher priority and ignores the one in vite.config.ts
