### ISSUE TITLE
Next.js dev compilation hangs indefinitely when disabling Webpack caching

### ISSUE THREAD

**Issue by han-tyumi** [unocss/unocss#1281]
### Description
Following https://github.com/unocss/unocss/tree/main/examples/next#hot-module-reload,
when I disable caching, this causes the Next.js `dev` script to hang indefinitely.

### Reproduction
https://stackblitz.com/edit/node-13p6fc?file=my-app/next.config.mjs
```sh
cd my-app; npm i; npm run dev
```

**Comment by Songkeys** [comment]
see https://github.com/unocss/unocss/pull/1105#issuecomment-1171572872
