### ISSUE TITLE
Nuxt3 - wind preset instead of uno

### ISSUE THREAD

**Issue by tasiotas** [unocss/unocss#1286]
Hi,

"@unocss/nuxt": "0.44.3"

I set this in nuxt.config.ts
```js
  unocss: {
    wind: true,
    icons: true, 
  },
```

But still, Tychons syntax is being accepted by uno.

`class="h3"` is converted to:
```
.h3 {
    height: 0.75rem;
}
```

With `windi:true` I was expecting to have only Tailwind syntax accepted.
`class="h3"` is clashing with another CSS library that I use, Inkline.

Thank you!

**Comment by chris-zhu** [comment]
In fact, `preset-wind` includes `preset-mini` by default, and `preset-uno` like a `preset-wind` alias, it includes both `preset-wind` and `preset-mini`.

**Comment by tasiotas** [comment]
Is there a way to get rid of Tychons syntax?
I thought we can pick and choose which syntax we want to use.

```
By default, UnoCSS applies the default preset, which provides a common superset of the popular utilities-first frameworks Tailwind CSS, Windi CSS, Bootstrap, Tachyons, etc.

For example: ml-3 (Tailwind), ms-2 (Bootstrap), ma4 (Tachyons), and mt-10px (Windi CSS) are all valid.
```

**Comment by antfu** [comment]
You can use blocklist (regex supported) to exclude the ones you don't want https://github.com/antfu/unocss/blob/92ef8b0c22f3fe1ca0d0d220fdeaacbaaf7c47ce/packages/core/src/types.ts#L317-L322

Since things are on-demand and dynamic, sadly there is no option to customize it.

**Comment by tasiotas** [comment]
amazing, thank you!
