### ISSUE TITLE
body used already for: https://esm.sh... error with slow network

### ISSUE THREAD

**Issue by Aybee5** [unocss/unocss#1291]
When unocss icons are used with a slow connection, it creates the following error(in the screenshot), has to stop a server and restart before the error is gone.

> Environment:
"nuxt": "3.0.0-rc.4",
"@unocss/nuxt": "^0.41.1",
"@unocss/preset-icons": "^0.41.1",

> Unocss configuration:
```
unocss: {
    preflight: false,
    presets: [
      presetIcons({
        cdn: 'https://esm.sh/',
      }),
    ],
  },
```
Step to reproduce:
Have a project with unocss with the above configurations with a slow network, and start a nuxt dev server

![image](https://user-images.githubusercontent.com/42099896/179502165-fac3a93c-8854-4b4e-91bc-798bc1609031.png)

Is there a way to make the error a warning and make the icon load once the internet speed is back?

**Comment by antfu** [comment]
This seems to be a `node-fetch` or `ohmyfetch` issue https://github.com/node-fetch/node-fetch/issues/533#issuecomment-611016960
