### ISSUE TITLE
support for postcss @apply with complex classes, including responsive and pseudo-class variants

### ISSUE THREAD

**Issue by syffs** [unocss/unocss#1293]
using unocss with postcss, I am unable to use `@apply` for complex classes including responsive and pseudo-class variants (`md:...`,`lg:...`,...`hover:...`) as such:
```postcss
h2 {
    @apply text-2xl md:text-5xl;
}
```
it's returning error: `Semicolon or block is expected`

It may be more of a [postcss](https://github.com/postcss/postcss) issue, but tailwind [did address the issue](https://github.com/tailwindlabs/tailwindcss/pull/2159), so I'm not sure.

**Comment by antfu** [comment]
You may try `--at-apply: text-2xl md:text-5xl`. UnoCSS is agnostic to PostCSS so we can't interpose its behavior.
