### ISSUE TITLE
Can not use lodash in uno.config.js

### ISSUE THREAD

**Issue by winter-ice** [unocss/unocss#1299]
`import { range } from 'lodash-es'`
...
  rules: [
    range(10, 1).map(i => `grid-cols-${i}`)
  ],
...

Will cause vite dev cannot start

**Comment by antfu** [comment]
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by winter-ice** [comment]
@antfu isn't it is a minimal reproduction?
