### ISSUE TITLE
【Attributify mode】It doesn't seem to support white-space？

### ISSUE THREAD

**Issue by szmxx** [unocss/unocss#1302]
<img width="585" alt="image" src="https://user-images.githubusercontent.com/24505926/179792708-9862e47f-7dbb-46aa-ab6e-5e6e497713eb.png">

**Comment by chris-zhu** [comment]
It's supported. [playground](https://uno.antfu.me/play/?html=DwEwlgbgBA7gFmALgUwM4AcCGBjZBaAOwHsYAnTdWBFDHZAXgCJiyLGoB6APgCgg&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCqWEZF1tAgjDFMAEYCuMYOgCecAL5x0UCCDgByPowDGVKnIBQ61AA9IsFBgCGfADbw0mHPkLAiACgTq45SjRhUAXHADaLNwwg7AEpmV3ZObn5BEWCAXRJ1MSD1IA&options=N4IgzgLgTglgxhEAuaBXApgXyA)
