### ISSUE TITLE
getCSS with files seems to be impossible

### ISSUE THREAD

**Issue by Nukiloco** [unocss/unocss#1308]
Currently on the preflight config, I been trying to use await fetch which has been returning errors and I have tried multiple of ways of importing my css file for preflight.

```
getCSS: () => (await fetch('file://src/client/app.css)).text())
```
returns the error of
```
cause: Error: not implemented... yet...
```

I try to bypass it bypassing it by returning this string
```
getCSS: () => `
@import url(src/client/app.css)
`
```
which returns the error of
```
[vite:css] @import must precede all other statements (besides @charset or empty @layer)
```

**Comment by mboyakanni** [comment]
A 501 Not Implemented Error is an HTTP error that indicates the method used to fulfill the request does not work or was not found on the server. Here are my suggestions on how to fix it: 
```
Try reloading the page
Clear Your Browser's Cache
Disable Proxy Server Settings
Get in Touch With Your Host
```

**Comment by Nukiloco** [comment]
This is not on the website or a web browser. This is using fetch inside the vitejs config itself.

**Comment by antfu** [comment]
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)
