### ISSUE TITLE
upper shadow/drop-shadow

### ISSUE THREAD

**Issue by shtse8** [unocss/unocss#1317]
I can't figure out how to make upper shadow or drop shadow.
there is negative shadow/drop shadow, but they are working the same.

```html
<div class="text-15 my-2 text-center shadow">
   shadow
</div>
  
<div class="text-15 my-2 text-center -shadow">
   -shadow
</div>

<div class="text-15 my-2 text-center drop-shadow">
   drop-shadow
</div>
  
<div class="text-15 my-2 text-center -drop-shadow">
   -drop-shadow
</div>
```

target css:
```css
box-shadow: 0px -2px 10px rgb(0 0 0 / 15%);
```

the negative seems only applied to the first value. `0px` === `-0px`

**Comment by chu121su12** [comment]
For now, negative variant isn't meant to be applied on shadows. You may want to set your own *directed* shadow in the theme

**Comment by antfu** [comment]
You could use theme to extend dropShadow, or right your custom rule for that. Currently, we probably not going to support it built in.
