### ISSUE TITLE
auto invert color and bg color in dark mode

### ISSUE THREAD

**Issue by shtse8** [unocss/unocss#1318]
everything works fine in dark mode without any additional settings. Except applying `c-white` or `bg-white` on element, the color won't invert in dark mode. it needs us to specific `dark:bg-black` to invert the color in dark mode. any easy way to do it automatically applying all colors? it seems `invert` can do the job but it will invert the style of dark mode too.

**Comment by antfu** [comment]
I commonly use shortcuts to do this:

```ts
{
  shortcuts: {
    'bg-base': 'bg-white dark:bg-dark',
    // ...
  }
}
```

I am not sure if there is a good algorithm to "invert" colors nicely. But feel free to experiment with the idea via a preset.

**Comment by shtse8** [comment]
> I commonly use shortcuts to do this:
> 
> ```ts
> {
>   shortcuts: {
>     'bg-base': 'bg-white dark:bg-dark',
>     // ...
>   }
> }
> ```
> 
> I am not sure if there is a good algorithm to "invert" colors nicely. But feel free to experiment with the idea via a preset.

that's what I am doing. but It needs to map each color one by one in another file.

I think for dark mode, the easiest algorithm is to invert color to opposite side.
for `c-gray-100` then in dark mode it should be `c-gray-800`.
for `c-gray-800` then in dark mode it should be `c-gray-100`
for `c-zinc-400` then in dark mode it should be `c-zinc-500`

**Comment by antfu** [comment]
It will not always work in every design. Even if we could have an algorithm that makes sense, it would still be hard for ppl to customize it to fit their design. UnoCSS probably won't have this built-in. But ask said, feel free to experiment as a user preset or so.
