### ISSUE TITLE
Custom css var does not work

### ISSUE THREAD

**Issue by hooray** [unocss/unocss#1322]
I want to use my custom css var like `color: var(--test-var);`, so I use `color-$test-var` and test in playground, it's works. but in my project I use it, it doesn't work.

![image](https://user-images.githubusercontent.com/1574903/180616889-46565158-5995-4ff4-9fcb-113447fe7687.png)

But when I modified it to `color="$test-var"`, it's working.

I'm not sure if it's a problem with the unocss configuration, here is my configuration:

```ts
// unocss.config.ts
import { defineConfig, presetAttributify, presetIcons, presetUno } from 'unocss'

export default defineConfig({
  presets: [
    presetUno(),
    presetAttributify(),
    presetIcons({
      extraProperties: {
        'display': 'inline-block',
        'vertical-align': 'middle',
      },
    }),
  ],
})
```

**Comment by hannoeru** [comment]
That is because `color-$test-var` is not a valid attribute name, so you better to void using this name in Attributify mode, use `class="color-$test-var"` instead.

**Comment by antfu** [comment]
This is the limitation of HTML spec. As mentioned, you need to workaround with it.
