### ISSUE TITLE
`@unocss/runtime`: arbitrary variant doesn't work on page load

### ISSUE THREAD

**Issue by NamesMT** [unocss/unocss#1323]
Arbitrary variant doesn't work on page load, only takes effect (generates css) if were added in dynamically via hot reload (dev env) or Console HTML edit
Easily reproduced with basic .html file / online editor:
![image](https://user-images.githubusercontent.com/23612546/180625920-2c46eb82-211d-4504-8a01-225d50965614.png)
![image](https://user-images.githubusercontent.com/23612546/180625938-ed9f3432-d209-41af-b34a-b7f3dc1c6812.png)

(After edited using Console:)
![image](https://user-images.githubusercontent.com/23612546/180625950-b087d2cb-325b-4404-8d54-e4bb5ee1b421.png)

**Comment by chu121su12** [comment]
Somewhere around extraction, the code is working on parsed html, hence the string is no longer `&` but `&amp;`.

![image](https://user-images.githubusercontent.com/379924/180628609-3e238cca-4feb-43e1-9a28-47ac897b3d42.png)
