### ISSUE TITLE
preset-icons with runtime

### ISSUE THREAD

**Issue by gotjoshua** [unocss/unocss#1328]
I am trying to package preset-icons to work with the unocss runtime, and running into issues that imply preset-icons needs node polyfills.

Is there a way to use preset-icons in runtime cdn only mode without the node deps?

**Comment by gotjoshua** [comment]
ok, so i ripped this:
https://cdn.jsdelivr.net/npm/@unocss/preset-icons@0.44.5/dist/index.mjs

and then removed the node checks and managed to get a cdn only version built and working... will update soonish...

**Comment by antfu** [comment]
Yeah, I think we should make a node-free build for easier usage

**Comment by gotjoshua** [comment]
many thanks for the quick update!!
