### ISSUE TITLE
atomic icon collections

### ISSUE THREAD

**Issue by gotjoshua** [unocss/unocss#1329]
1. is it a good idea at all?
2. I have a mvp working:
https://f.cdn.zt.ax/unocss/

which fetches from here:
https://f.cdn.zt.ax/@iconify-json-atomic/logos/atomic/unocss.json. 

which is generated in [this build script](https://gitlab.com/onezoomin/ztax/cdn.zt.ax/-/blob/trunk/src/%40iconify-json-atomic/build.mjs))

and fetched [via this custom collection](https://gitlab.com/onezoomin/ztax/cdn.zt.ax/-/blob/trunk/src/unocss/test.js#L37):
```js
presetIcons({
    customizations: {
      trimCustomSvg: true,
    },
    collections: {
      'logos-atomic': async (iconName) => {
        // your custom loader here. Do whatever you want.
        // for example, fetch from a remote server:
        const iconURL = `https://f.cdn.zt.ax/@iconify-json-atomic/logos/atomic/${iconName}.json`
        const fetched = await fetch(iconURL)
        const textVal = await fetched.text()
        console.log({ iconURL, textVal })
        const { body } = JSON.parse(textVal)
        console.log({ body })

        return `<svg xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid meet" viewBox="0 0 256 256" width="1em" height="1em">
          ${body}
        </svg>`
      },
    },
  })
```

not bad, its faster than loading the whole [logos/icons.json](https://esm.sh/@iconify-json/logos@1.1.12/icons.json) (2.3MB)...
but some icons (like the html-5 for example) are cut off.

I assume that i am missing out on some of the uno magic but not sure how to access that mojo.

any help?

**Comment by antfu** [comment]
Sorry I didn't get what you mean. Can you explain more?

**Comment by gotjoshua** [comment]
I split the collections into individual json files.
Loading works fine.
The auto sizing and other normalizing features are not working because i am wrapping the json with hardcoded SVG, instead of the Uno magic.

How can I employ that magic from my custom single icon loader?

**Comment by antfu** [comment]
If you are following the format of `@iconify-json`, I think you don't need to construct the SVG manually.
