### ISSUE TITLE
include styles from imported libs

### ISSUE THREAD

**Issue by jerrythomas** [unocss/unocss#1336]
Is there a way to include styles used in imported libraries?

WindiCSS has this extract option to include imported libraries (under node_modules.
```
extract: {
   include: [
	'./**/*.{html,js,svelte,ts,css}',
	'./node_modules/ui-lib/src/**/*.{html,js,svelte,ts,css}'
  ]
}
```

How do I do this when using `Unocss`?

**Comment by antfu** [comment]
See https://github.com/unocss/unocss#scanning, UnoCSS scans the file in your build pipeline including ones under node_modules. Note that it does not scan js/ts by default.
