### ISSUE TITLE
What does $$ mean (used by variants)

### ISSUE THREAD

**Issue by aleclarson** [unocss/unocss#1337]
Like here, for example:
https://github.com/unocss/unocss/blob/d290c847cb261bc50d31773a6841cee09df8c8f6/packages/preset-mini/src/variants/dark.ts#L12

**Comment by aleclarson** [comment]
Ok so I found out it's a placeholder used by UnoCSS core:
https://github.com/unocss/unocss/blob/d290c847cb261bc50d31773a6841cee09df8c8f6/packages/core/src/generator/index.ts#L634

Still not sure what it's needed for

**Comment by antfu** [comment]
It's used in scope mode, indicating the position the scope selector should be. When not presented, it will be prefixed. For example, if the scope is `.unocss`

```html
<div class="unocss">
  <div class="text-red">Red</div>
</div>
<div class="test-red">Not affected</div>
```

Where the generated CSS would be:

```css
.unocss .text-red { color: red }
```

`$$` is just an internal placeholder for generating:

```css
.dark .unocss .dark\:text-red { color: red }
```
