### ISSUE TITLE
border inset

### ISSUE THREAD

**Issue by gotjoshua** [unocss/unocss#1338]
i am working on a custom rule for using box-shadow to draw an inset border ([in part to avoid this anti-aliasing issue](https://stackoverflow.com/questions/35511130/parent-s-background-shows-around-the-child-s-border-radius-when-the-parent-has-o)).

```js
rules: [
  [/^b-inset-(\d)$/, ([, w]) => ({ 'box-shadow': `inset 0 0 0 ${w}px var(--un-shadow-color)` })],
],
```
i can use it with attributify mode just fine
```html
<flex-col data-theme="night" 
          b="inset-2" 
          shadow="blue-500"
   ...
```

but i need to use the shadow color instead of the border color. which works, but is less elegant than 
`b="inset-2 blue-500"` would be.

Is there a way to 
a. interpret a color name within a simple rule like this?
b. assign the interpreted border color to a variable?
c. do something more clever and elegant?

**Comment by antfu** [comment]
You could set a shortcut for alias:

```ts
shotcuts: [
  [/^b-(.*)$/, ([, m]) => `shadow-${m}`]
]
```

Just note that you might need to improve the regex or the function to make the matching more precise.

**Comment by gotjoshua** [comment]
> shortcut for alias:

```ts
 rules: [
    [/^b-inset-(\d)$/, ([, w]: [any, string]) => 
      ({ 'box-shadow': `inset 0 0 0 ${w}px var(--un-shadow-color)` })], // matches width
  ],
  shortcuts: [
    [/^b-inset-([^\d]*-[\d]{3})$/, ([, c]: [any, string]) => `shadow-${c}`], // matches colors
  ]
```

just to close this one up. I made this more specific reg ex and then the rules can be used together with attributify

```html
<div b="inset-2 inset-blue-500"  />
```
