### ISSUE TITLE
theme.animation.keyframes deep merge not working

### ISSUE THREAD

**Issue by gwsbhqt** [unocss/unocss#1340]
Hey Tony. 

I found that there are some deep merges and some overwrites under the theme configuration items. 

Similar to this question #1211, theme.animation.keyframes also an overwrite item. more details, please refer to these two playgrounds.

[customized](https://uno.antfu.me/play/?html=DwEwlgbgBAhgdmAtjALgUwLQCMD2BXOAYzVgWXQwAs0AbGnAPiA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAKq4ISAL5wsUCCDgByLpIDGdOsqRIMAD0ix02AIZcANvEw58REsFIAKZMNoMYdAFxwA2lTdRGAkIJwBKIVRqd0YWNk4ePn5wyIBdSJgACwwQDB9XOABIU1xQU15ifICogGsMfnlTXO9EaqiVbIsLCGUfZQQABgBScgBGAeGEDlN1GtIFNTQAWkg6YArcL2G4YYBuaQBWSenZ%2BYhFlYg1ja9x7buh-ekddtRpave3mTCkIA&options=N4IgzgLgTglgxhEAuaBXApgGhNAhgOzADMB7KAW2SNwBswsQp0wAHEwmAN3StvoF8gA)
[annotated](https://uno.antfu.me/play/?html=DwEwlgbgBAhgdmAtjALgUwLQCMD2BXOAYzVgWXQwAs0AbGnAPiA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAKq4ISAL5wsUCCDgByLpIDGdOsqRIMAD0ix02AIZcANvEw58REsFIAKZMNoMYdAFxwA2lTdRGAkIJwBKIVRqd0YWNk4ePn5wyIBdSJgACwwQDB9XOABIU1xQU15ifICogHoAKjgAawx%2BeVNc70RqqJVsiwsIZR9lBAAGAFJyAEZRiYQOU3VG0gU1NABaSDpgCtwvCbgJgG5pAFY5haWViDXNiG3drxmD5-GT6R0e1Fk6murpKgA6RhJBAA&options=N4IgzgLgTglgxhEAuaBXApgGhNAhgOzADMB7KAW2SNwBswsQp0wAHEwmAN3StvoF8gA)

Sometimes we just do some simple modifications and extensions, and I don't think keyframes should be an override. The documentation only mentions that breakpoint is an override item, I hope it can be described more clearly.

**Comment by chris-zhu** [comment]
This might conflict with  https://github.com/unocss/unocss/commit/8f4f6b7503ad8bc1565755b9352ff42df135f713

**Comment by gwsbhqt** [comment]
I looked at this [https://github.com/unocss/unocss/commit/8f4f6b7503ad8bc1565755b9352ff42df135f713](https://github.com/unocss/unocss/commit/8f4f6b7503ad8bc1565755b9352ff42df135f713) commit, and what this commit is trying to solve.

I think a better solution is:
For objects, it should be a full depth merge.
For arrays, it should be overriding.

**Comment by chris-zhu** [comment]
> 

Yes, i agree with you to resolve unocss theme merge deeply
>  For arrays, it should be overriding.

However, I'm a little worried that `deepMerge` is exported as a utility function, its meaning is deep merge, and there is no meaning of override.
