### ISSUE TITLE
[unocss:global:build:generate] [unocss] does not found CSS placeholder in the generated chunks

### ISSUE THREAD

**Issue by ckvv** [unocss/unocss#1341]
<https://github.com/ckvv/vite-project>

The following error is thrown when the output file is multiple in library mode
https://github.com/ckvv/vite-project/blob/3b4f3c84c2b9cd4f0e0ee883da6439077cad1811/vite.config.js#L12

```
[unocss:global:build:generate] [unocss] does not found CSS placeholder in the generated chunks,
this is likely an internal bug of unocss vite plugin
error during build:
Error: [unocss] does not found CSS placeholder in the generated chunks,
this is likely an internal bug of unocss vite plugin
    at Object.generateBundle (/Users/chenkai/Downloads/mini-vue/node_modules/.pnpm/@unocss+vite@0.44.7_vite@2.9.14/node_modules/@unocss/vite/dist/index.cjs:364:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Bundle.generate (/Users/chenkai/Downloads/mini-vue/node_modules/.pnpm/rollup@2.77.1/node_modules/rollup/dist/shared/rollup.js:16103:9)
    at async /Users/chenkai/Downloads/mini-vue/node_modules/.pnpm/rollup@2.77.1/node_modules/rollup/dist/shared/rollup.js:23746:27
    at async catchUnfinishedHookActions (/Users/chenkai/Downloads/mini-vue/node_modules/.pnpm/rollup@2.77.1/node_modules/rollup/dist/shared/rollup.js:23161:20)
    at async doBuild (/Users/chenkai/Downloads/mini-vue/node_modules/.pnpm/vite@2.9.14/node_modules/vite/dist/node/chunks/dep-c9998dc6.js:41721:26)
    at async build (/Users/chenkai/Downloads/mini-vue/node_modules/.pnpm/vite@2.9.14/node_modules/vite/dist/node/chunks/dep-c9998dc6.js:41552:16)
    at async CAC.<anonymous> (/Users/chenkai/Downloads/mini-vue/node_modules/.pnpm/vite@2.9.14/node_modules/vite/dist/node/cli.js:738:9)
```

The problem occurs in version v0.43.2

related to this commit<https://github.com/unocss/unocss/pull/1217>

**Comment by Xwudao** [comment]
With lib mode in vite.js, the option `build.cssCodeSplit` force be set to `false` https://vitejs.dev/config/build-options.html#build-csscodesplit

And, build.cssCodeSplit=false, the unocss will occur this error.

**Comment by kingcw** [comment]
These steps worked for me, it's for mode "global", but you can play with other modes to seek the correct config:

1. in package.json, needs to add "type" field:
```
"type": "module"
```
2. set build.cssCodeSplit=false
3. if you want to generate "umd" or "iife", you can't specify filenames, so in vite.config.ts:

```ts
   build: {
        lib: {
            entry: resolve(__dirname, "index.ts"),
            name: "xxx",
        },
        rollupOptions: {
            output: [
                    ...
                    {
                           dir: "dist/umd",
                           format: "umd",
                           name: "xxx",
                           sourcemap: false,
                     }
                    ...
            ]
        }
   }
```

but you can specify entryFilenames for es and cjs

> this should also be the answer to issue #1241 and #1332<br>
<br>

**Comment by kingcw** [comment]
above config only works for umd.  

For iife, after set build.cssCodeSplit = true,  it's a hit and miss, you build several times, it might succeed one time.  The inconsistency looks like a parallel async bug.

but just use umd for now would be fine I guess.

**Comment by alvarosabu** [comment]
@Xwudao you might want to be able to export the styles in your library to be imported separately by the consume in lib mode.

**Comment by alvarosabu** [comment]
@ckvv it must be something recent because I fixed it by downgrading to `"unocss": "^0.33.4"`

**Comment by Jelenkee** [comment]
I'm having the same problem with [Astro](https://astro.build/). In dev mode everything works fine but when I build the project, it fails.
Setting build.cssCodeSplit to false did not help.
I'm using unocss 0.45.1

astro.config.mjs
```js
import { defineConfig } from 'astro/config';
import { presetUno } from "unocss";
import unocss from "unocss/vite";
import icons from "@unocss/preset-icons";
import svelte from "@astrojs/svelte";
import { extractorSvelte } from "@unocss/core";


export default defineConfig({
    integrations: [svelte()],
    vite: {
        plugins: [
            unocss({
                presets: [
                    presetUno(),
                    icons()
                ],
                extractors: [extractorSvelte],
            }),
        ],
        ssr: {
            noExternal: ["modern-normalize"]
        }
    }
});

```

layout.astro
```md
---
import "modern-normalize";
import "uno.css";
import "../main.scss"
import Header from "../layouts/header.astro";
---
<some-markup>
```

**Comment by Xwudao** [comment]
> Setting build.cssCodeSplit to false did not help.

we said set it to `true`

**Comment by antfu** [comment]
This is probable related to https://github.com/vitejs/vite/discussions/9443

**Comment by Jelenkee** [comment]
> > Setting build.cssCodeSplit to false did not help.
> 
> we said set it to `true`

Did not help either. According to vite docs true is the default

**Comment by vipero07** [comment]
> > Setting build.cssCodeSplit to false did not help.
> 
> we said set it to `true`

This actually fixed the issue for me.
