### ISSUE TITLE
Suggest: Why not put nonValueAttributify into `classList`? it can reduce project size.

### ISSUE THREAD

**Issue by SnowingFox** [unocss/unocss#1352]
In `preset-attributify`, for example
```html
<div text-red />
<div class="text-red" />
```
will produce
```css
.text-red, [text-red=""] {}
```
I think `[text-red=""]` is redundant, because it will increase the size of project. So a better way to solve it is put nonValueAttributfiy `text-red` into classList and it will compiled to
```html
<div class="text-red" />
<div class="text-red" />
```
and the outcome of css is
```css
.text-red {}
```
we don't `need [text-red=""]` any more

**Comment by michael-azogu** [comment]
if only it was trivial

**Comment by antfu** [comment]
This will need to modify the source code which is a very difficult thing to do right. We probably won't have it built in, but please feel to experiment on your custom presets. Thanks.
