### ISSUE TITLE
`@unocss/preset-icons`: no corresponding CSS is generated when the icon attribute is passed to components through props.

### ISSUE THREAD

**Issue by lhj-web** [unocss/unocss#1355]
I encapsulate an Icon component and pass the icon attribute with Vue props, but I don't see the icon, finally, I find the CSS is not generated.
After many attempts, I find that only full icon value (It also includes comments. e.g. `<!-- <div i="ion-settings-outline"> -->`) that appear in the current component can be detected and CSS generated accordingly.

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/64905610/182069786-975b4402-33d3-4aad-b8b1-f1b104d991ab.png">

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/64905610/182069833-0d480448-a26b-42eb-afb5-a92ea9506b5c.png">

Please click [here](https://stackblitz.com/edit/vitejs-vite-tngomb?file=src/components/Icon.vue) for an example

**Comment by chris-zhu** [comment]
Please refer to #1108

**Comment by lhj-web** [comment]
@chris-zhu 
I try to use the class mode, but it doesn't seem to be working.

**Comment by userquin** [comment]
you're trying to add vue bind to unocss attributify, you need to add them to safelist, or just map any used icon in the parent component (or in the component itself).

For example, I have this:

![imagen](https://user-images.githubusercontent.com/6311119/182125089-37fab14a-d143-42f2-8e9e-f3b2291a5d54.png)

and then I use the icon in the component

![imagen](https://user-images.githubusercontent.com/6311119/182125234-862a3a6a-3bd8-43ca-afaa-385e8c86c716.png)

**Comment by lhj-web** [comment]
thanks!

**Comment by antfu** [comment]
Yeah, it's just how UnoCSS works. https://github.com/unocss/unocss#scanning
