### ISSUE TITLE
VSCode extension: how to activate extension when vite.config.js is not in project root

### ISSUE THREAD

**Issue by carlosyan1807** [unocss/unocss#1358]
I put all the configurations related to Vite in `./config` directory, there are no `vite.config.js` and `uno.config.js` in root directory, how to activate the extension?

<img width="145" alt="image" src="https://user-images.githubusercontent.com/50797685/182148312-38a74632-f28d-406d-93b7-55a1dc488aad.png">

```
UnoCSS for VS Code  v0.45.1 /mnt/c/Program Files/Microsoft VS Code
[info] Resolving config for /home/carlos/projects/arkham/apps/dashboard
```
```typescript
// ./config/vite.config.base.ts
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import { resolve } from 'path'

import configAutoImportPlugin from './plugins/auto-import'
import configNaiveUiResolverPlugin from './plugins/naive-ui-resolver'
import configUnocssPlugin from './plugins/unocss'
export default defineConfig({
  plugins: [vue(), configAutoImportPlugin(), configNaiveUiResolverPlugin(), configUnocssPlugin()],
  resolve: {
    alias: {
      '@': resolve(__dirname, '../src'),
    },
  },
})
```

```typescript
// ./config/plugins/unocss.ts
import Unocss from 'unocss/vite'
import {
  presetAttributify,
  presetUno,
  transformerDirectives,
  transformerVariantGroup,
} from 'unocss'

export default function configUnocssPlugin() {
  const unocssPlugin = Unocss({
    presets: [presetUno(), presetAttributify({ strict: false, prefixedOnly: true })],
    transformers: [transformerVariantGroup(), transformerDirectives({ enforce: 'pre' })],
    // theme: {},
  })

  return unocssPlugin
}

```

When I create `./uno.config.js` empty file, the extension can be activated, but I don't know whether this is the correct loading `./config/plugins/unocss.ts` configuration.

```
UnoCSS for VS Code  v0.45.1 /mnt/c/Program Files/Microsoft VS Code
[info] Resolving config for /home/carlos/projects/arkham/apps/dashboard
[info] New configuration loaded from
    - /home/carlos/projects/arkham/apps/dashboard/uno.config.js`
```

<img width="348" alt="image" src="https://user-images.githubusercontent.com/50797685/182151352-e4ae2eeb-cdce-4680-aed4-47f25d033870.png">

Another question, if this is a monorepo project with multiple frontend, including `web`, `electron`, `mobile`, etc., how to set `unocss.root` in `settings.json`, which does not seem to accept arrays.

**Comment by jd-solanki** [comment]
Have you tried extension config:
```json
"unocss.root": "packages/client"
```

You can read here: https://marketplace.visualstudio.com/items?itemName=antfu.unocss

**Comment by AaronBeaudoin** [comment]
See his explanation here:

https://github.com/unocss/unocss/tree/main/packages/vscode#config

**Comment by hanzhenfang** [comment]
Hi, I face the same problem. 
![image](https://user-images.githubusercontent.com/99874763/232357646-ece43397-a755-47f1-afd2-0ac30b503fa1.png)
