### ISSUE TITLE
Allow unresolved icon fallback to API/cdn mode

### ISSUE THREAD

**Issue by jd-solanki** [unocss/unocss#1359]
Hi,

I am building Theme for third party developers where they can insert any icons for rendering this like. This same issue I described here: https://github.com/unocss/unocss/issues/544

I guess with new CDN option we can fallback to CDN mode when installed icon collection is not found.

assume, we have `mdi` collection installed and someone uses `bx` then Uno will fetch from cdn.

**Comment by antfu** [comment]
The CDN mode is for running UnoCSS in runtime with dynamic needs

- https://github.com/unocss/unocss#scanning
- https://github.com/unocss/unocss/tree/main/packages/runtime
- https://github.com/unocss/unocss/tree/main/packages/preset-icons#browser

**Comment by jd-solanki** [comment]
When we use cdn mode with regular [nodejs](https://github.com/unocss/unocss/tree/main/packages/preset-icons#nodejs) mode, cdn mode takes over and all icons are fetched from API instead of first searching locally.

Feature request is same behavior as how Iconify Icon component works. It first tries to fetch it from registered collection and if collection is not found it fetches it from network/cdn.

Reproduction: https://codesandbox.io/s/uno-dynamic-icons-using-cdn-xndn5u

Previously you also gave me hint https://github.com/unocss/unocss/issues/544#issuecomment-1077757755 but unfortunetly I wasn't able to understand what you were refering to.

Regards.
