### ISSUE TITLE
UnoCSS VS Code plugin fails to initialize if config is written like `vite.defineConfig({` in `vite.config.ts`

### ISSUE THREAD

**Issue by AaronBeaudoin** [unocss/unocss#1362]
If I write my `vite.config.ts` like this...

```ts
import { defineConfig } from "vite";

export default defineConfig({
  ...
});
```

...UnoCSS's VS Code plugin works fine. But if I write it like this...

```ts
import vite from "vite";

export default vite.defineConfig({
  ...
});
```

...it doesn't work. The plugin's "Runtime Status" tab shows the following error:

```
Cannot read properties of undefined (reading 'defineConfig')
```

**Comment by antfu** [comment]
According to the semantics in ESM, the two statements are not equivalent. Please always use named import for `defineConfig`
