### ISSUE TITLE
VS Code autocomplete not working until part of rule is typed

### ISSUE THREAD

**Issue by AaronBeaudoin** [unocss/unocss#1363]
Suppose I have the following UnoCSS config:

```ts
{
  mode: "vue-scoped",
  presets: [],
  rules: [
    [
      "m-1",
      { "margin": "50px" }
    ],
    [
      /^bg-([a-z]+)$/,
      match => ({ "background-color": match[1] }),
      { autocomplete: ["bg-(red|blue|green)"] }
    ]
  ]
}
```

Now, in some file `test.page.vue`, here is what I see as I type.

I hit <kbd>ctrl</kbd>+<kbd>space</kbd>.

![image](https://user-images.githubusercontent.com/26592486/182430615-d13c366f-06ed-4813-93c5-b00c0353b753.png)

Looks like it's just VS Code's guessing based on the words I've used in the file.

I hit <kbd>esc</kbd> then type `b` then hit <kbd>ctrl</kbd>+<kbd>space</kbd> again.

![image](https://user-images.githubusercontent.com/26592486/182430889-15d41940-1b5e-4c23-acfd-7df3d1a66690.png)

As you can see, nothing.

I hit <kbd>esc</kbd> then type `g` then hit <kbd>ctrl</kbd>+<kbd>space</kbd> again.

I get the same as above.

I hit <kbd>esc</kbd> then type `-` then hit <kbd>ctrl</kbd>+<kbd>space</kbd> again.

![image](https://user-images.githubusercontent.com/26592486/182431056-f4323038-0326-4af5-8c09-9d44869623e4.png)

Now I can see the suggestions.

Is this by design? I'd like to be able to hit <kbd>ctrl</kbd>+<kbd>space</kbd> before typing anything and see suggestions, just like the Tailwind CSS extension does. Is this possible?

**Comment by antfu** [comment]
Yes, for now, the autocomplete is only triggered by `:` and `-`.

https://github.com/unocss/unocss/blob/b727d55121e7b4946a951c6654a48e542f13caaf/packages/vscode/src/autocomplete.ts#L128-L132

I do not yet know a better way to do that. If you got any idea, PR would be greatly welcome. Thanks.
