### ISSUE TITLE
unified plugin production (adds rollup/esbuild)

### ISSUE THREAD

**Issue by janat08** [unocss/unocss#1370]
https://github.com/unjs/unplugin

**Comment by janat08** [comment]
I considered just trying to roll my own fork, but it's based around rollup which you also don't have.

**Comment by antfu** [comment]
I created `unplugin` 😅 - so yes I am aware of it.

We are already using `unplugin` in webpack integration to make it easier. But the thing is that UnoCSS requires many bundler-specific optimizations to make it work the best and unplugin is not enough for it.
