### ISSUE TITLE
[Question] Does the `vue-scoped` mode solve the same problem as `tailwind-merge` on NPM?

### ISSUE THREAD

**Issue by AaronBeaudoin** [unocss/unocss#1374]
Someone created this Tailwind CSS helper called [`tailwind-merge`](https://www.npmjs.com/package/tailwind-merge). Its purpose (among several) is to prevent the CSS cascade from overriding atomic classes outside a child component with atomic classes inside. Check out the [short explanation](https://github.com/dcastil/tailwind-merge#what-is-it-for) in the helper's README.

My question is this: Does the `vue-scoped` mode provided by UnoCSS also solve this same issue for Vue SFCs, either directly or as a happy side effect?

**Comment by antfu** [comment]
Probably. Tho I'd consider they are solving different scope of the problem. You might also want to check https://github.com/unocss/unocss/tree/main/packages/transformer-compile-class
