### ISSUE TITLE
使用 @unocss/preset-icons 时图标不显示

### ISSUE THREAD

**Issue by Mascot1** [unocss/unocss#1376]
在使用 @unocss/preset-icons 图标时，从接口端获取的图标无法正常显示，没有从接口获取的可以正常显示

"unocss": "^0.45.3",
"@unocss/preset-icons": "^0.45.3",

接口代码
··· 
import { ref} from 'vue';
const routes = ref([]);
axios
      .get('https://www.fastmock.site/mock/6d96d8787248021f989c4bf9615ff464/basic/getMenus')
      .then((res) => {
        routes.value = res.data.result.menus;
      });
···

unocss.config.js
```
import {
  defineConfig,
  presetAttributify,
  presetIcons,
  presetTypography,
  presetUno,
  presetWebFonts,
  transformerDirectives,
  transformerVariantGroup,
} from 'unocss';

export default defineConfig({
  shortcuts: [],
  presets: [
    presetUno(),
    presetAttributify(),
    presetIcons({
      cdn: 'https://esm.sh/', 
      scale: 1.2,
      warn: true,
    }),
  ],
  transformers: [transformerDirectives(), transformerVariantGroup()],
});
```

**Comment by chris-zhu** [comment]
You can add your icons that get for request to `safelist`

**Comment by Mascot1** [comment]
> You can add your icons that get for request to `safelist`

但我觉得这个并不是一个好主意，首先我想要实现的是一个添加自定义菜单的功能，图标是我选择的，我并不能确定选择的图标在 safelist 里面

**Comment by Mascot1** [comment]
> You can add your icons that get for request to `safelist`

但我觉得这个并不是一个好主意，首先我想要实现的是一个添加自定义菜单的功能，图标是我选择的，我并不能确定选择的图标在 safelist 里面

**Comment by chris-zhu** [comment]
> > You can add your icons that get for request to `safelist`
> 
> 但我觉得这个并不是一个好主意，首先我想要实现的是一个添加自定义菜单的功能，图标是我选择的，我并不能确定选择的图标在 safelist 里面

It's up to you. And your example is similar to use dynamic class, or you can refer to [runtime](https://github.com/unocss/unocss/tree/main/packages/runtime)

**Comment by antfu** [comment]
https://github.com/unocss/unocss#scanning

**Comment by Mascot1** [comment]
> It's up to you. And your example is similar to use dynamic class, or you can refer to

非常感谢你的回答，我已经试过这个方案，但是仍然无法达到我想要的效果。但是仍然非常的感谢你的回答，谢谢

**Comment by Mascot1** [comment]
> https://github.com/unocss/unocss#scanning

好的，谢谢，我会参考你的回答做一次尝试！万分感谢！！！

**Comment by linyu520** [comment]
> > https://github.com/unocss/unocss#scanning
> 
> 好的，谢谢，我会参考你的回答做一次尝试！万分感谢！！！

请问解决了吗

**Comment by Tricker39** [comment]
> > > https://github.com/unocss/unocss#scanning
> > 
> > 
> > 好的，谢谢，我会参考你的回答做一次尝试！万分感谢！！！
> 
> 请问解决了吗
 配置了 safelist 可以实现效果，暂时使用这种方式
