### ISSUE TITLE
How to add icon sets to `safelist`

### ISSUE THREAD

**Issue by jiangmaniu** [unocss/unocss#1377]
As [@Mascot1](https://github.com/unocss/unocss/issues/1376#issuecomment-1206283810) said, I need to have an `IconPicker` in my business to provide users to select icons when customizing certain elements, so I need to encapsulate the `IconPicker` component, in which I will loop all icons of a certain icon set Traversing and rendering it out for users to choose, by importing the `JSON` file of the icon set, I successfully traversed the icons, but unfortunately, `unocss` can only be statically extracted and constructed, and will not recognize dynamically rendered icons.

I looked at the `README.md` and `Issuse` of the `unocss repo` and found that these dynamic icons are added to the `Safelist` configuration of `unocss`. My idea is to traverse the `JSON` of the relevant icon set and add the `key` of the icon to the `Safelist`. And added the cdn address to the icon.

```ts
// unocss.config.ts
import { icons as antdIcons } from '@iconify-json/ant-design'
import { icons as riIcons } from '@iconify-json/ri'

const getSafelist = () => {
  const base = 'prose prose-sm m-auto text-left'.split(' ')

  const riIconNames = Object.keys(riIcons.icons).map(iconName => `i-${riIcons.prefix}:${iconName}`)
  const antdIconNames = Object.keys(antdIcons.icons).map(iconName => `i-${antdIcons.prefix}:${iconName}`)

  return [...riIconNames, ...antdIconNames, ...base]
}

export default defineConfig({
  // ...
  presets: [
    presetIcons({
      cdn: 'https://esm.sh/',
    }),
  ],
  // ...
  safelist: getSafelist(),
})
```

```ssh
PS F:\learnings\vitesse\vitesse> nr dev

> @ dev F:\learnings\vitesse\vitesse
> vite --port 3333 --open

error when starting dev server:
FetchError: request to https://esm.sh/@iconify-json/ant-design@1.1.3/icons.json failed, reason: connect ETIMEDOUT 172.67.192.37:443 ()
    at async $fetchRaw2 (file:///F:/learnings/vitesse/vitesse/node_modules/.pnpm/ohmyfetch@0.4.18/node_modules/ohmyfetch/dist/chunks/fetch.mjs:131:20)
    at async F:\learnings\vitesse\vitesse\node_modules\.pnpm\@unocss+preset-icons@0.44.7\node_modules\@unocss\preset-icons\dist\chunks\cdn.cjs:426:21
    at async rules.layer.layer (F:\learnings\vitesse\vitesse\node_modules\.pnpm\@unocss+preset-icons@0.44.7\node_modules\@unocss\preset-icons\dist\core.cjs:70:19)
    at async UnoGenerator.parseUtil (F:\learnings\vitesse\vitesse\node_modules\.pnpm\@unocss+core@0.44.7\node_modules\@unocss\core\dist\index.cjs:733:22)
    at async UnoGenerator.parseToken (F:\learnings\vitesse\vitesse\node_modules\.pnpm\@unocss+core@0.44.7\node_modules\@unocss\core\dist\index.cjs:500:22)
    at async F:\learnings\vitesse\vitesse\node_modules\.pnpm\@unocss+core@0.44.7\node_modules\@unocss\core\dist\index.cjs:527:23
    at async Promise.all (index 2789)
    at async UnoGenerator.generate (F:\learnings\vitesse\vitesse\node_modules\.pnpm\@unocss+core@0.44.7\node_modules\@unocss\core\dist\index.cjs:559:5)
    at async Context.buildStart (F:\learnings\vitesse\vitesse\node_modules\.pnpm\@unocss+vite@0.44.7_vite@3.0.3\node_modules\@unocss\vite\dist\index.cjs:453:9)
    at async Promise.all (index 5)
 ELIFECYCLE  Command failed with exit code 1.
```

Unfortunately, the `JSON` of the icon set can't seem to be loaded via the CDN when starting the service, I checked for my network issues, accessing [https://esm.sh/@iconify-json/ant-design@1.1.3/icons.json](https://esm.sh/@iconify-json/ant-design@1.1.3/icons.json) address seems to be available.

![image](https://user-images.githubusercontent.com/50100681/183087087-c8d394f4-f6de-4f8d-8692-2e445485c3f5.png)

I tried not to get it through CDN and let `unocss` generate the relevant icon set styles.

```ts
// unocss.config.ts
export default defineConfig({
  ...
  presets: [
    presetIcons({
      // cdn: 'https://esm.sh/',
    }),
  ],
  ...
  safelist: getSafelist(),
})
```

However, after starting the service, when accessing the page after startup, `unocss` will always generate and update `CSS`, and the application cannot be rendered normally.

![image](https://user-images.githubusercontent.com/50100681/183084842-f06c98b9-1ffa-45fd-9618-a5119e8d8821.png)

Is there any solution for this kind of business? what should I do?

Reproduction: https://github.com/jiangmaniu/unocss-icon-set-repo

**Comment by antfu** [comment]
Including the entire icon set will make your CSS extremely heavy. I would not recommend doing that. Instead you might want a runtime solution for loading the icons on-demand, you can try https://iconify.design/.

**Comment by AemonCao** [comment]
> Including the entire icon set will make your CSS extremely heavy. I would not recommend doing that. Instead you might want a runtime solution for loading the icons on-demand, you can try https://iconify.design/.

当我要在内网中使用，是不是就没有好的办法了？只能将整个图标集遍历后添加到safelist。

**Comment by vampirefan** [comment]
> > Including the entire icon set will make your CSS extremely heavy. I would not recommend doing that. Instead you might want a runtime solution for loading the icons on-demand, you can try https://iconify.design/.
> 
> 当我要在内网中使用，是不是就没有好的办法了？只能将整个图标集遍历后添加到safelist。

我也一直想找个更优雅的解决办法，我看到 `nuxt ui` 里面的 icon 组件可以添加 dynamic 属性来实现添加动态的图标。也可以配置 iconset。但是我也不想为了这个功能再加一个对 `nuxt ui` 的依赖，何况好多功能和 unocss 是重复的。
