### ISSUE TITLE
unocss does not apply color on exact-active-link in nuxt 3

### ISSUE THREAD

**Issue by shadear** [unocss/unocss#1378]
I have noticed that color blue is not applied (or the ordering is off) on the exacr-active-link, but other colors are fine.

Reproduction: https://stackblitz.com/edit/github-g1qrcw?file=pages/index.vue

An example code:
```
<template>
  <div class="inline-flex gap-4">
    <NuxtLink
      to="/"
      class="text-light-9 px-5 bg-light py-3 rounded font-black"
      exact-active-class="text-blue-5"
    >
      BLUE
    </NuxtLink>

    <NuxtLink
      to="/"
      class="text-light-9 px-5 bg-light py-3 rounded font-black"
      exact-active-class="text-red-5"
    >
      RED
    </NuxtLink>
  </div>
</template>
```

For Blue:
![Screenshot from 2022-08-05 19-12-16](https://user-images.githubusercontent.com/47904282/183118140-106f67be-aabe-4d46-ae80-9ddb8816ef1e.png)

For Red:
![Screenshot from 2022-08-05 19-11-55](https://user-images.githubusercontent.com/47904282/183118104-15a1656e-d19d-4a29-a066-6022ca02578d.png)

**Comment by antfu** [comment]
`text-light-9` and `text-blue-5` have the same priority, you should avoid using them together in the same element. Try:

```vue
 <NuxtLink
      to="/"
      class="text-light-9 px-5 bg-light py-3 rounded font-black"
      exact-active-class="!text-blue-5"
    >
```
