### ISSUE TITLE
Feature request (preset-wind): process `tailwind.css` through preflights

### ISSUE THREAD

**Issue by sibbng** [unocss/unocss#1385]
Related https://github.com/unocss/unocss/pull/1353#issuecomment-1207274337

Maybe adding an option to presetWind to include Tailwind CSS reset in preflights layers with processed `fontFamily.sans`, `borderColor.DEFAULT` and `colors.gray.400` like their [preflights.css](https://github.com/tailwindlabs/tailwindcss/blob/99b53b416085413a0b0459a37d57daac53cb9d4d/src/css/preflight.css#L12) would further increase Tailwind CSS compatibility. What do you think about this?

**Comment by antfu** [comment]
Sure. As long as we provide an option to toggle it. PR welcome
