### ISSUE TITLE
How to use background images in UNOCSS？

### ISSUE THREAD

**Issue by Soumns777** [unocss/unocss#1387]
I configured the backgroundImage in Theme in unocss.config.js, but did not get the expected result. I looked at the theme type and it seems that there is no backgroundImage type. I wonder if UNOCSS does not support the background picture for now. See the trouble to explain, very thank you!!

**Comment by Soumns777** [comment]
import {
  defineConfig,
  presetAttributify,
  presetIcons,
  presetTypography,
  presetUno,
  presetWebFonts,
  transformerDirectives,
  transformerVariantGroup,
} from 'unocss';

export default defineConfig({
  theme: {
    colors: {
      nice: 'skyblue',
    },
    backgroundImage: {
      hero: "url('/src/assets/uploads/bg.png)",
    },
  },
  rules: [
    // 在这个可以增加预设规则, 也可以使用正则表达式
    [
      'soumns-center', // 使用时只需要写 p-c 即可应用该组样式
      {
        position: 'absolute',
        top: '50%',
        left: '50%',
        transform: `translate(-50%, -50%)`,
      },
    ],
    [
      'soumns-dfl',
      {
        'background-color': '#80D1c8',
      },
    ],
    [
      'soumns-kly',
      {
        color: '#002EA6',
      },
    ],
    [
      'soumns-flex',
      {
        display: 'flex',
        'align-items': 'center',
        'justify-content': 'center',
      },
    ],
    [
      'soumns-bg',
      {
        'background-repeat': 'no-repeat',
        'background-size': '100% 100%',
      },
    ],
  ],
  shortcuts: [
    {
      'soumns-btn':
        'py-2 px-4 font-semibold rounded-lg shadow-md  border-none  cursor-pointer text-center',
    },
    // 动态颜色
    [
      /^soumns-btn-(.*)$/,
      ([, c]) =>
        `bg-${c}-400 text-${c}-100 py-2 px-4 rounded-lg shadow-md  border-none  cursor-pointer text-center`,
    ],
  ],
  presets: [
    presetUno(),
    presetAttributify(),
    presetIcons({
      scale: 1.2,
      warn: true,
    }),
    presetTypography(),
    presetWebFonts({
      fonts: {
        sans: 'DM Sans',
        serif: 'DM Serif Display',
        mono: 'DM Mono',
      },
    }),
  ],
  transformers: [transformerDirectives(), transformerVariantGroup()],
  safelist: 'prose prose-sm m-auto text-left'.split(' '),
});

**Comment by Soumns777** [comment]
This is the configuration of my uno. Config. js, the background picture configured in the backgroundImage is not successful, I wonder if there is something wrong with my writing method

**Comment by chris-zhu** [comment]
It's supported. Try to use `bg-[url(xxx.png)]`
[Playground](https://uno.antfu.me/play/?html=DwEwlgbgBA7gtARgAxQBaJQIygYwDYCGAzkQLwBEmA5nANoCuATngBSoAu7ADkQFwD0-AhALsCjIgDoqYdqnqZ6RAKaMcAewB27ZdskaAtv3r8ALACYEAZgCcAdgCspgPwRSpgJQBdKNTgaIVXIAPmB%2BcAhgoA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAKq4ISAL5wsUCCDgByLpIDGdOsqRIMAD0ix02AIZcANvEw58REsFIAKZMNoMYdAFxwA2lTdRGAkIJwBKIVRqd0YWNk4ePn5wyIBdSJgACwwQDB9XKI4IfQBlTNM0CAB3LwLUAEh1LjoYRR9lAAY4LoBGDrB9OAAmAbgAYiGMdR71dR0ouGlI6RkwpCA&options=N4IgzgLgTglgxhEAuaBXApgGhNAhgOzADMB7KAW2SNwBswsQp0wAHEwmAN3StvoF8gA)

**Comment by Soumns777** [comment]
Hi, I was wondering if it doesn't work to refer to a local image, and how does it work if you want to define an image permanently? That would be nice. Thank you very much

**Comment by Soumns777** [comment]
<div
    w-100px
    h-100px
    b
    class="bg-['url(src/assets/uploads/bg.png'] bg-cover"
  ></div>

this cant't work

**Comment by Soumns777** [comment]
<div
    w-100px
    h-100px
    b
    class="bg-['url(src/assets/uploads/bg.png'] bg-cover"
  ></div>

**Comment by Soumns777** [comment]
Hi, I would like to know if UNOCSS can configure the backgroundImage in Theme in unocss.config.js like tailwind.

**Comment by chris-zhu** [comment]
> 嗨，我想知道UNOCSS是否可以像tailwind一样在unocss.config.js中配置Theme中的backgroundImage。

There is no such configuration item in theme

**Comment by Soumns777** [comment]
Ok, now I have a new problem, that is, I can show my local background picture normally in the test environment by using this way, but I can't show my background picture normally in the production environment after I pack it up. Want to know why?





#### 一、普通写法

```html
<div bg="center no-repeat" class="bg-[url(./src/assets/uploads/bg.png)]"></div>
```

#### 二、配置写法

```html
 <!-- <div soumns-min soumns-bg-bg-png>777</div> -->
```

```javascript
rules:[
  [
      'soumns-min',
      {
        'min-width': '100vw',
        'min-height': '100vh',
        'box-sizing': 'border-box'
      }
    ],
    // 动态背景
    [
      /^soumns-bg-(.*)$/,
      ([_, d]) => {
        let img = d.split('-')[0]
        let type = d.split('-')[1]
        return {
          background: `url('./src/assets/uploads/${img}.${type}')`,
          'background-size': '100% 100%',
          'background-repeat': 'no-repeat',
          'box-sizing': 'border-box'
        }
      }
    ]
]
```

**Comment by Mrlilili** [comment]
> It's supported. Try to use `bg-[url(xxx.png)]` [Playground](https://uno.antfu.me/play/?html=DwEwlgbgBA7gtARgAxQBaJQIygYwDYCGAzkQLwBEmA5nANoCuATngBSoAu7ADkQFwD0-AhALsCjIgDoqYdqnqZ6RAKaMcAewB27ZdskaAtv3r8ALACYEAZgCcAdgCspgPwRSpgJQBdKNTgaIVXIAPmB%2BcAhgoA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAKq4ISAL5wsUCCDgByLpIDGdOsqRIMAD0ix02AIZcANvEw58REsFIAKZMNoMYdAFxwA2lTdRGAkIJwBKIVRqd0YWNk4ePn5wyIBdSJgACwwQDB9XKI4IfQBlTNM0CAB3LwLUAEh1LjoYRR9lAAY4LoBGDrB9OAAmAbgAYiGMdR71dR0ouGlI6RkwpCA&options=N4IgzgLgTglgxhEAuaBXApgGhNAhgOzADMB7KAW2SNwBswsQp0wAHEwmAN3StvoF8gA)

If 'xxx.png' is a relative path that can't display the picture normally, is there any good solution? I wanted to use custom rules to solve the problem, but found that custom rules could not get the path of the current processing file


reproduce playground: https://stackblitz.com/edit/vitejs-vite-qvshx2?file=src%2FApp.vue

**Comment by Mrlilili** [comment]
> 

I guess it's a file path issue

**Comment by Mrlilili** [comment]
> Ok, now I have a new problem, that is, I can show my local background picture normally in the test environment by using this way, but I can't show my background picture normally in the production environment after I pack it up. Want to know why?
> 
> #### 一、普通写法
> ```
> <div bg="center no-repeat" class="bg-[url(./src/assets/uploads/bg.png)]"></div>
> ```
> 
> #### 二、配置写法
> ```
>  
> ```
> 
> ```js
> rules:[
>   [
>       'soumns-min',
>       {
>         'min-width': '100vw',
>         'min-height': '100vh',
>         'box-sizing': 'border-box'
>       }
>     ],
>     // 动态背景
>     [
>       /^soumns-bg-(.*)$/,
>       ([_, d]) => {
>         let img = d.split('-')[0]
>         let type = d.split('-')[1]
>         return {
>           background: `url('./src/assets/uploads/${img}.${type}')`,
>           'background-size': '100% 100%',
>           'background-repeat': 'no-repeat',
>           'box-sizing': 'border-box'
>         }
>       }
>     ]
> ]
> ```

I guess it's a file path issue

**Comment by zyyv** [comment]
Tip: Uno is a utility class for extracting static templates, so using a relative address will not convert it like a packaging tool.

**Comment by LeonIsACoder** [comment]
> Ok, now I have a new problem, that is, I can show my local background picture normally in the test environment by using this way, but I can't show my background picture normally in the production environment after I pack it up. Want to know why?
> 
> #### 一、普通写法
> ```
> <div bg="center no-repeat" class="bg-[url(./src/assets/uploads/bg.png)]"></div>
> ```
> 
> #### 二、配置写法
> ```
>  
> ```
> 
> ```js
> rules:[
>   [
>       'soumns-min',
>       {
>         'min-width': '100vw',
>         'min-height': '100vh',
>         'box-sizing': 'border-box'
>       }
>     ],
>     // 动态背景
>     [
>       /^soumns-bg-(.*)$/,
>       ([_, d]) => {
>         let img = d.split('-')[0]
>         let type = d.split('-')[1]
>         return {
>           background: `url('./src/assets/uploads/${img}.${type}')`,
>           'background-size': '100% 100%',
>           'background-repeat': 'no-repeat',
>           'box-sizing': 'border-box'
>         }
>       }
>     ]
> ]
> ```

请问这种背景图快捷方式配置，生效了吗？
