### ISSUE TITLE
Text size conflicts with PrimeFlex

### ISSUE THREAD

**Issue by DoubleJ-G** [unocss/unocss#1388]
In the presets, including the mini they seem to make `text-{number}` into a class that sets the text size but [primeflex](https://www.primefaces.org/primeflex/textcolor)   uses text-100 to text-900 for colors. 

Is there a way to disable this specific rule or whatever is causing it so that it doesnt conflict?

**Comment by antfu** [comment]
https://github.com/unocss/unocss/blob/2180281ba36fab75b395330bf76c89f845c4e8df/packages/core/src/types.ts#L317-L321

You can set `blocklist: [/^text-.*$/]`
