### ISSUE TITLE
Is there some thought for dark/light theme doesn't only by `dark:`

### ISSUE THREAD

**Issue by Xwudao** [unocss/unocss#1390]
Now, not only `unocss` but also `wind`, `tailwind` support dark mode only with `dark` variant.

It means We should write more class name for supporting dark mode.

A better method for this that use `color palette` (refer to mui: https://mui.com/material-ui/customization/dark-mode/#main-content):

We design two color tokens, and automaticly change those tokens with compute mode changed or by user manual.

unocss has any plans to implement this?

**Comment by antfu** [comment]
You can write your own variant to support that:

https://github.com/unocss/unocss/blob/2180281ba36fab75b395330bf76c89f845c4e8df/packages/preset-mini/src/variants/dark.ts#L1-L22

**Comment by Xwudao** [comment]
@antfu Hi,

I mean I define two sets of colors in the configuration file. Then, at some point in time, uno automatically switches which set of colors to use.


----

Now I have a preliminary idea to use CSS variable, for example:

```html
<head>
    <style>
        body[data-theme="dark"] {
            --bg-main: rgb(167, 28, 28);
        }

        body {
            --bg-main: rgb(199, 189, 189);
        }

        .bg-gray {
            width: 40px;
            height: 40px;
            background-color: var(--bg-main);
        }
    </style>
</head>

<!-- <body data-theme="dark"> -->

<body>
    <div class="bg-gray">hello this</div>
</body>
```

---

I try to use in unocss:

```css
// index.css imported by main.ts
body{
  --bg-gray: red
}

```

```ts
//vite.config.ts
  Unocss({
      theme: {
          color: {
              main: 'var(--bg-gray)',
          }
      },
  })
```

```tsx
//App.tsx
<div className="bg-main">hello uno</div>
```

That's not work.

However, even if it works, it is not the best implement in my mind.

In my mind the best ways to implement is that we define two sets of colors in unocss config file.

example:

```ts
//vite.config.ts
  Unocss({
      theme: {
        dark: {
            color: {
                main: '#fff',
            }
        },
        light: {
            color: {
                main: '#f1f1f1',
            }
        }
      },
  })
```

I only use `bg-main`，the uno will automatic to switch which real color would be used.

**Comment by antfu** [comment]
I see. I like your idea and I see the usage. However, it requires an overhaul of all the utilities and might break existing apps. I would recommend starting a new preset with this idea in mind. If you do, I am happy to list it as a community preset in the readme.

On the other hand, I am using this approach: https://twitter.com/antfu7/status/1533584342228037632

**Comment by Xwudao** [comment]
@antfu 

All right. In fact, I am not familiar with the development of uno preset. But I'd like to try it in my spare time.

**Comment by jd-solanki** [comment]
**Another way of changing theme without adding classes:**

You can use CSS variables/properties like [this](https://github.com/jd-solanki/anu/blob/main/packages/anu-vue/src/presets/theme-default/index.ts#L115-L119) and change them in dark theme like [this](https://github.com/jd-solanki/anu/blob/main/packages/documentation/docs/.vitepress/theme/style.css#L115-L119).

In this way, you can create unlimited color schemes. Want to add theme named coffee, Yes you can :)

Moreover, you can change them at runtime. You can checkout the demo [here](https://anu-vue.netlify.app/guide/getting-started/customization.html) _(Click on "Change Primary" button)_.

**Comment by Dunqing** [comment]
Now I've made a [preset](https://github.com/Dunqing/unocss-preset-theme) that supports it
