### ISSUE TITLE
How to add autoprefixer with unocss?

### ISSUE THREAD

**Issue by zouhangwithsweet** [unocss/unocss#1391]

**Comment by chris-zhu** [comment]
https://github.com/unocss/unocss/blob/2180281ba36fab75b395330bf76c89f845c4e8df/packages/preset-mini/src/index.ts#L43-L54

Do these two configuration items help you?

**Comment by antfu** [comment]
Isn't it work already?

**Comment by antfu** [comment]
Please provide a reproduction

**Comment by antfu** [comment]
😅 minimal, please

**Comment by antfu** [comment]
I would suggest: 

- Create a new project using just UnoCSS and PostCSS
- Adding a plain CSS and ensure PostCSS prefixed it
- Adding a corresponding UnoCSS util that doesn't work

to make the repro.
