### ISSUE TITLE
[BUG] New classes not generated without server restart with Nuxt 3 and UnoCSS (Gitpod)

### ISSUE THREAD

**Issue by alping** [unocss/unocss#1392]
When adding new UnoCSS classes to HTML elements, these new classes are not generated while the Nuxt/Vite dev server is running. To update the CSS, a restart of the dev server is required. Due to limitations in my setup, I have only been able to test this using a Gitpod workspace.

### Minimal Example
Created using the documentation for [Nuxt 3](https://v3.nuxtjs.org/getting-started/quick-start) and [UnoCSS for Nuxt 3](https://github.com/unocss/unocss/tree/ccd3cff4418bb87923613073df2311dd828e1c16/packages/nuxt).

- Gitpod snapshot: https://gitpod.io#snapshot/fc6ce8dd-dc61-4e18-93b8-9e241be628d9
- GitLab repo: https://gitlab.com/alping/nuxt3-test

1. Run dev server with `yarn dev`
2. The background of the text is blue
3. In `app.vue` change `bg-blue` to `bg-red`
4. There is now no background to the text
5. Restart the dev server `CTRL-C` and `yarn dev`
6. The background is now red

### Environment
Nuxt: 3.0.0-rc.6
UnoCSS: 0.45.5
Platform: Gitpod ([Workspace-Full](https://github.com/gitpod-io/workspace-images/blob/481f7600b725e0ab507fbf8377641a562a475625/dazzle.yaml#L18))

---

New issue based on:
> I see a similar issue when using UnoCSS with Nuxt 3 (Content 2). I have to fully restart the server and sometimes also delete the `.nuxt` folder for new classes to be applied. Unfortunately the vue-scoped mode is not available for UnoCSS with Nuxt (as far as I know), so I haven't found a workaround. Since Nuxt uses SSR by default, I suspect this is a related issue.

_Originally posted by @alping in https://github.com/unocss/unocss/issues/1351#issuecomment-1206389271_

**Comment by josh-israel** [comment]
Having the same problem, new classes are only generated when re-serving the application. (if you never used something like "p-2", you'll need to serve again).

**Comment by alping** [comment]
Using the latest Nuxt 3 release from the Edge Channel fixed the problem for me:
https://v3.nuxtjs.org/guide/going-further/edge-channel/

```json
{
  "devDependencies": {
    "nuxt": "npm:nuxt3@latest"
  }
}
```
