### ISSUE TITLE
content-visibility CSS

### ISSUE THREAD

**Issue by richex-cn** [unocss/unocss#1396]
Like [windicss-content-visibility](https://github.com/Felix-Icaza/windicss-content-visibility)

**Comment by chris-zhu** [comment]
> 

For [windicss-content-visibility](https://github.com/Felix-Icaza/windicss-content-visibility),  `content-` rules is conflict with `align-content` rules. Use `content-visibility-xxx` instead of it, or you can send a PR with better way to change it.
