### ISSUE TITLE
Unocss works well with background images in test environments, but does not display them properly when packed into production

### ISSUE THREAD

**Issue by Soumns777** [unocss/unocss#1397]
#### 一、普通写法

```html
<div bg="center no-repeat" class="bg-[url(./src/assets/uploads/bg.png)]"></div>
```

#### 二、配置写法

```html
 <!-- <div soumns-min soumns-bg-bg-png>777</div> -->
```

```javascript
rules:[
  [
      'soumns-min',
      {
        'min-width': '100vw',
        'min-height': '100vh',
        'box-sizing': 'border-box'
      }
    ],
    // 动态背景
    [
      /^soumns-bg-(.*)$/,
      ([_, d]) => {
        let img = d.split('-')[0]
        let type = d.split('-')[1]
        return {
          background: `url('./src/assets/uploads/${img}.${type}')`,
          'background-size': '100% 100%',
          'background-repeat': 'no-repeat',
          'box-sizing': 'border-box'
        }
      }
    ]
]
```

**Comment by Soumns777** [comment]
In my test environment, I was able to display the background image using both methods, but after packaging, the background image was not displayed properly even with the absolute path

**Comment by UltraCakeBakery** [comment]
When you say "not displayed properly", do you mean "it is not loading" or "the position of the image is not the same"?
If the image is simply not loading (you got an error in your devtools network tab for example), it is not being bundeled. Is there a `static` folder in your project files? If so you probably want to upload the image to that folder instead.

**Comment by Soumns777** [comment]
I split the image file in the Vite packaging configuration, but I don't see the background image I introduced with UNOCSS in the PNG folder after packaging

**Comment by UltraCakeBakery** [comment]
This issue is probably not related to unocss. You probably want to read up on https://vitejs.dev/guide/assets.html#the-public-directory

Basically, vite does not bundle your images because they are in your src folder. It isn't aware of them. You want them in the public folder instead (or the static folder like in frameworks like svelte-kit and nuxt).

**Comment by antfu** [comment]
It's recommended to use an absolute path (e.g. CDN) for URLs in CSS. It's out-of-scope of UnoCSS.

**Comment by Soumns777** [comment]
####  💫 Use Unocss BackgroundImage

```vue
<template>
 <!-- The online pictures can be displayed normally  -->
   <div
    bg="no-repeat center cover"
    w-screen
    h-screen
    class="bg-[url(https://avatars.githubusercontent.com/u/42139754?v=4)]"
  />
  
<!-- Local images cannot be displayed properly -->
  <div
    bg="no-repeat center cover"
    w-screen
    h-screen
    class="bg-[url(./src/assets/uploads/bg.png)]"
  />
</template>
```



#### 💫 My Vite.config.js

```javascript
import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';
import Unocss from 'unocss/vite';
import AutoImport from 'unplugin-auto-import/vite';
import Components from 'unplugin-vue-components/vite';

import {
  ElementPlusResolver,
  VantResolver,
} from 'unplugin-vue-components/resolvers';
import Inspector from 'vite-plugin-vue-inspector';
import VueSetupExtend from 'vite-plugin-vue-setup-extend';
import path from 'path';
const pathSrc = path.resolve(__dirname, 'src');

// https://vitejs.dev/config/
export default defineConfig({
  base: './',
  publicDir: 'public',
  build: {
     target: 'modules',
     outDir: 'dist/www', 
     assetsDir: 'assets', 
     minify: 'terser' 
     sourcemap: false, 
  },
  plugins: [
    vue({
      reactivityTransform: true, 
    }),
    AutoImport({
      imports: [
        'vue',
        'vue-router',
        'vue/macros',
        '@vueuse/core',
        'pinia',
        '@vueuse/head',
      ],
      dts: 'src/auto-imports.d.ts',
      resolvers: [ElementPlusResolver()],
    }),
    Components({
      // allow auto load markdown components under `./src/components/`
      extensions: ['vue', 'md'],
      // allow auto import and register components used in markdown
      include: [/\.vue$/, /\.vue\?vue/, /\.md$/],
      dts: 'src/components.d.ts',
      resolvers: [ElementPlusResolver(), VantResolver()],
    }),
    Unocss(),
    VueSetupExtend(),
  ],
  resolve: {
    alias: {
      '@': pathSrc,
    },
  },
  css: {
    preprocessorOptions: {
      scss: {
        additionalData: `@import "@/assets/sass/index.scss";`,
      },
    },
  },
  server: {
    host: '0.0.0.0',
    open: true,
    proxy: {
      '/api': {
        target: 'http://v.juhe.cn',
        changeOrigin: true,
        secure: false,
        ws: true,
        rewrite: (path) => path.replace(/^\/api/, ''),
      },
    },
  },
});

```

#### 💫  Show

https://images.cnblogs.com/cnblogs_com/soumns777/2207767/o_220824033152_unocss.png

**Comment by enochzzz** [comment]
I created a simple plugin to handle this requirement.
[vite-plugin-unocss-bgimg](https://github.com/enochzzz/vite-plugin-unocss-bgimg)

**Comment by pzehrel** [comment]
I recently had a similar requirement. You can get the caller's file path in the transformer to modify the resource file path, converting it to either an absolute path or a path alias. Vite will handle resource files with both types of paths.

References:
https://github.com/pzehrel/autobg/blob/main/packages/unocss/src/transformer.ts
https://github.com/pzehrel/autobg/blob/main/packages/unocss/src/rules.ts

**Comment by zyyv** [comment]
> I recently had a similar requirement. You can get the caller's file path in the transformer to modify the resource file path, converting it to either an absolute path or a path alias. Vite will handle resource files with both types of paths.
> 
> References: https://github.com/pzehrel/autobg/blob/main/packages/unocss/src/transformer.ts https://github.com/pzehrel/autobg/blob/main/packages/unocss/src/rules.ts

Yes, since unocss is a static extract, we need to use vite's transformer to rewrite the relative path in advance.

Do you want to help us create a PR?

**Comment by pzehrel** [comment]
> > I recently had a similar requirement. You can get the caller's file path in the transformer to modify the resource file path, converting it to either an absolute path or a path alias. Vite will handle resource files with both types of paths.
> > References: https://github.com/pzehrel/autobg/blob/main/packages/unocss/src/transformer.ts https://github.com/pzehrel/autobg/blob/main/packages/unocss/src/rules.ts
> 
> Yes, since unocss is a static extract, we need to use vite's transformer to rewrite the relative path in advance.
> 
> Do you want to help us create a PR?

Of course, I will try to maintain the `/^bg-(.+)$/` rule.
