### ISSUE TITLE
[unocss] does not found CSS placeholder in the generated chunks

### ISSUE THREAD

**Issue by Jelenkee** [unocss/unocss#1402]
I get this error message when I try to build my [Astro](https://github.com/withastro/astro) project where I use unocss.

Version: 0.45.6

There was a fix for #1341 but it didn't work for me.
I am not sure if this problem is caused by unocss, astro, svelte or even vite. Maybe you can help me.

I started debugging into unocss and found out that at this [line](https://github.com/unocss/unocss/blob/c2cdbd2fa75fb2bc21734b99805229eb7d52abb0/packages/vite/src/modes/global/build.ts#L154) the bundle contains a CSS-asset with css generated from my [svelte components](https://svelte.dev/docs#component-format-style). But this CSS doesn't contain the placeholder which unocss is looking for. So it cannot be replaced and the variable `replaced` remains `false`.
![image](https://user-images.githubusercontent.com/59470612/184192340-fe6b1b74-9689-44c1-bfdc-758033899674.png)

I tried to set the svelte option `emitCss` to `false` but it didn't work. Maybe it is overridden by the astro-svelte-plugin.

**Comment by Dunqing** [comment]
Can you provide repo? I don't know astro.

**Comment by Jelenkee** [comment]
There you go
https://github.com/CPUEater/bug-astro
Just run `npm run build`

**Comment by Dunqing** [comment]
I tested it and found the same problem before version 0.43, I guess `unocss` doesn't support `astro`.

**Comment by Dunqing** [comment]
See #1423.

**Comment by Jelenkee** [comment]
Sorry, I don't understand your 'solution'.
Using `import uno.css` in a script tag should not work, because JS in script tags is executed in the browser only (according to the [docs](https://docs.astro.build/en/core-concepts/astro-components/#client-side-scripts)).

Just to clarify: I can only reproduce the problem with astro and svelte. When I comment out the css in the style tag in my svelte component, it works fine.

**Comment by Dunqing** [comment]
Vite will transform `script`  refer [Using Hoisted Scripts](https://docs.astro.build/en/core-concepts/astro-components/#using-hoisted-scripts)

**Comment by Dunqing** [comment]
> Just to clarify: I can only reproduce the problem with astro and svelte. When I comment out the css in the style tag in my svelte component, it works fine.

Because `svelte` is processed through `vite`

**Comment by jolo-dev** [comment]
@Jelenkee it works what @Dunqing said.

I remove the `import uno.css` from the frontmatter and put it above the ending `</body>`- tag.

```vue
---
// Component Imports
import MainHead from '../components/MainHead.astro';

---

<html lang="en">

<head>
	<MainHead title={title} description={description} />
</head>

<body class="dark:bg-gray-700">
	<slot />
	<script>import 'uno.css'</script>.
</body>

</html>
```

**Comment by Jelenkee** [comment]
Putting the `import uno.css` into script tags does only work in dev mode. When I build the page no css file is generated.
Unfortunately the new unocss-astro-plugin did not fix my problem either.
I use the unocss CLI as a workaround

**Comment by jolo-dev** [comment]
@Jelenkee it works for me
https://jolodev.guru/
is written in Unocss ;)

**Comment by Jelenkee** [comment]
@jolo-dev Can you show me your repo?

**Comment by jolo-dev** [comment]
@Jelenkee No, I can't.
But really did it like [here](https://github.com/unocss/unocss/issues/1402#issuecomment-1218488562) in my `BaseLayout.astro`.
And here is my `astro.config.ts`

```ts
 import Unocss from 'unocss/vite';

// https://astro.build/config
export default defineConfig(
{
  vite: {
    build: {
      cssCodeSplit: true,
    },
    plugins: [Unocss({
      // Some config
    })]
  }
});
```

**Comment by jcayzac** [comment]
Seeing this too.
