### ISSUE TITLE
apply rules only when a specific input is checked

### ISSUE THREAD

**Issue by gotjoshua** [unocss/unocss#1403]
i am playing with daisyui and enjoying the css only ux "tricks".
i am trying to implement something like
`[#tab-details:checked]:tab-active`
so that if the input element with id "tab-details" is checked, then apply the tab-active rule to the current element

is there a way to do this already?

i tried a fully custom rule
```
 [/^\[(.*):(.*)\]:(.*)$/, ([, id, state, rule]: [any, string, string, string], { _rawSelector, _currentSelector, _variantHandlers, _theme }) => { return `#${id}:${state} ~ * label[for=${id}] { --at-apply: ${rule}; background-color: #33d; }` }
```

the rule gets created but doesn't match.

but i have the feeling there may be an easier way already available in uno.

**Comment by chris-zhu** [comment]
I guess `group`、 `peer`  ...etc variant maybe help you.

**Comment by gotjoshua** [comment]
> maybe help you.

thanks for the reply @chris-zhu !

i think my problem is due to css limitations. 
group and peer both depend on a child or sibling relationship between entities that are meant to affect each other.

For the tab group that i am trying to create, i can use labels and hidden checkboxes to show the correct content, but then the checkbox is outside of the sibling tree, so group and peer can't work.

I got it working with minimal js (just for adding the tab-active style of the actual tab label element) and peer css for the content:
https://gitlab.com/onezoomin/ztax/cdn.zt.ax/-/blob/trunk/apps/color-schemes/components/tab-box.ts

i think thats the best i can do with the current css limitations.
