### ISSUE TITLE
When reading configuration from nuxt.config.ts, cannot preview the generated css.

### ISSUE THREAD

**Issue by so1ve** [unocss/unocss#1410]
Reading from uno.config.ts(with underline):

![](https://user-images.githubusercontent.com/58381667/184466188-605a0061-1275-48c2-abbd-c7c88917540d.png)
![](https://user-images.githubusercontent.com/58381667/184466191-010131af-175b-4930-a113-5d4fcee4d424.png) 

Reading from nuxt.config.ts(no underline):

![](https://user-images.githubusercontent.com/58381667/184466194-30abd888-8857-49d3-a573-6ba3448dd1ce.png)
![](https://user-images.githubusercontent.com/58381667/184466362-1c0e7215-4f36-4b9e-9cf4-2b3faba7ef37.png)

**Comment by momoathome** [comment]
You can add `/* @unocss-include */` (as a code comment) anywhere in the nuxt.config.ts 
[https://github.com/unocss/unocss#scanning](url)

**Comment by so1ve** [comment]
thank you for your reply!
I imitated antfu/vitesse-nuxt3 and defined the unocss configuration file in uno.config.ts.
