### ISSUE TITLE
In attributify mode, the "active" pseudo-class selector is generated before "hover"

### ISSUE THREAD

**Issue by varmiral** [unocss/unocss#1422]
https://uno.antfu.me/play/?html=DwIwrgLhD2B2BQACRECeAHApgXgETijlyUQGMAbAQwGdq8BbEAWgCYAGdAD0S6YEYAHFx6p%2BHbiADmTamBD0AlhBSZOEJgApBwgMQAzAwEpE5TJQAmC2NPbCIAJ0qxqShXERnqmJlabRIiOZgjhBusGJsxMgAFtAAbpj2eFIycorqsQn2UYiUpKEJydKy8kpMeQWYgcGUoXBMAKyR8AB8JABCkDAIwAD0BN0tQA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcEWWwCGuOlmggMUAGrr2mmAHEoELmEoBfOFksg4Aci4qJdOi6RIMAD0hYdGx1LgAbeEwcfCISYFIACmRUKAj6AC44AG0qVGyXCS46GAgQAFo08IwXckQ4KXDoLJdaNBc4WwBdKi7ZOgALaBgimDoslNRXIpKy8sHh0ZcWmACYcvDSOFX-dehNUgw4IYA3fQyd9dX1cJ9UW1kRBXGcvLlRJRVEgEpZYXlGCw2JweHx%2BD8-u8FJJpMk3qg6BIbhgsgBGAB0ACZIagJGhcC0BqwwOMAPSk%2BggdGDUl3Ka2X69NRQTTaXT6F65KbbFlaHRQPSGYzAUwWKxgH5MqgwAYYPQTN6NaAvSbcuhcDggYAwBXc7kAEQAogAxJiKAAyABUWgBiADsqIkAA4AMxO2rwqanc6uG3qABsaDQro9eqm6gkvDOtoALHa7WhMS7Q3qHm80-c7N8kEA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g

**However, inside the class attr., it works as expected:**

https://uno.antfu.me/play/?html=DwIwrgLhD2B2BQACRECeAHApgXgETijlyUQGMAbAQwGdq8BbEAWgCYAGdAD0S6YEYAHFx6p%2BHbiADmTamBD0AlhBSZOEJgApBwgMQAzAwEpE5TJQAmC2NPbCIAJ0qxqShXERnqmJlabRIiOZgjhBusGJsiAAW0ABumPYAXFIycorqMfH2iJSkofGJGimy8kpMufmYgcGUoXBMAKxshsQAfCQAQpAwCMAA9AQ9rUA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcEWWwCGuOlmggMUAGrr2mmAHEoELmEoBfOFksg4Aci4qJdOi6RIMAD0hYdGx1LgAbeEwcfCISYFIACmRUKAj6AC44AG0qVGyXCS46GAgQAFo08IwXckQ4KXDoLJdaNBc4WwBdKi7ZOgALaBgimDoslNRXIpKy8sHh0ZcWmACYcvDSOFX-dehNUgw4IYA3fQyd9dX1cJ9UW1kRBXGcvLlRJRVEgEpZYXlGCw2JweHx%2BD8-u8FJJpMk3qg6BIbhgsgBGAB0ACZIagJGhcC0BqwwOMAPSk%2BggdGDUl3Ka2X69NRQTTaXT6F65KbbFlaHRQPSGYzAUwWKxgH5MqgwAYYPQTN6NaAvSbcuhcDggYAwBXc7kAEQAogAxJiKAAyABUWgBiADsqIkAA4AMxO2rwqanc6uG3qABsaDQro9eqm6gkvDOtoALHa7WhMS7Q3qHm80-c7N8kEA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g

**Comment by chris-zhu** [comment]
It should be that the css weight is not enough.
[playground](https://uno.antfu.me/play/?html=DwIwrgLhD2B2BQACRECeAHApgXgETijlyUQGMAbAQwGdq8BbEAWgCYAGdAD0S6YEYAHFx6p%2BHbiADmTamBD0AlhBSZOEJgApBwgMQAzAwEpE5TJQAmC2NPbCIAJ0qxqShXERnqmJlabRIiOZgjhBusGJsxMgAFtAAbpj2eFIycorqsQn2UYgK9OjQ9hBO6pSkoQnJ0rLySkxlFZiBwZShcEwArJHwAHwkAEKQMAjAAPQEwz1AA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcEWWwCGuOlmggMUAGrr2mmAHEoELmEoBfOFksg4Aci4qJdOi6RIMAD0hYdGx1LgAbeEwcfCISYFIACmRUKAj6AC44AG0qVGyXCS46GAgQAFo08IwXckQ4KXDoLJdaNBc4WwBdKi7ZOgALaBgimDoslNRXIpKy8sHh0ZcWmACYcvDSOFX-dehNUgw4IYA3fQyd9dX1cJ9UW1kRBXGcvLlRJRVEgEpZYXlGCw2JweHx%2BD8-u8FJJpMk3qg6BIbhgsgBGAB0ACZIagJGhcC0BqwwOMAPSk%2BggdGDUl3Ka2X69NRQTTaXT6F65KbbFlaHRQPSGYzAUwWKxgH5MqgwAYYPQTN6NaAvSbcuhcDggYAwBXc7kAEQAogAxJiKAAyABUWgBiADsqIkAA4AMxO2rwqanc6uG3qABsaDQro9eqm6gkvDOtoALHa7WhMS7Q3qHm80-c7N8kEA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g)
