### ISSUE TITLE
uniapp compile to ios , unocss induced build failure

### ISSUE THREAD

**Issue by each1026** [unocss/unocss#1424]
Reproduction method

![error](https://s2.loli.net/2022/08/16/NRCV8e29DSwizZG.png)

run to IOS in hbuildex
![run](https://s2.loli.net/2022/08/16/kRBeZY45Xbfa2Cd.png)

[File.zip](https://drive.google.com/file/d/1e_2aRpK5T8KBZx26LRhNo4yWBopH3CBl/view?usp=sharing)

**Comment by each1026** [comment]
Now I find that finding the problem is not the most difficult, the most difficult and tedious is to abstract the project into a separate demo

**Comment by each1026** [comment]
Hi @zguolee, I see you are the author of [unocss-preset-uni](https://github.com/zguolee/unocss-preset-uni) , have you tried to compile to ios, will you also encounter this problem?

**Comment by zguolee** [comment]
No, I only use applet. I think it's better to open the issue in the [uniapp](https://github.com/dcloudio/uni-app) repo instead of here😂.

**Comment by each1026** [comment]
> It looks like your nodejs doesnot support optional chaining

Optional chains? Any solution suggestions? Update node? or upgrade package.json?

**Comment by each1026** [comment]
> update you nodejs to v14
> node -v
v16.14.2 There should be no problem with the version, right?

**Comment by each1026** [comment]
> You should check your the version of node that hbuildex used.

This is difficult for me, how to check ah . If it's hbuildex, can I fix it?

**Comment by each1026** [comment]
No solution until now?

**Comment by zguolee** [comment]
> No solution until now?

You should make the following configuration in `HBuilderX`.
```ts
{
  "node.path" : "xxx",
  "npm.path" : "xxx",
}
```

**Comment by each1026** [comment]
> > No solution until now?
> 
> You should make the following configuration in `HBuilderX`.
> 
> ```ts
> {
>   "node.path" : "xxx",
>   "npm.path" : "xxx",
> }
> ```

![img](https://s2.loli.net/2022/08/18/XqheFb74DUgozjP.png) 

I'm trying to configure ` node Path ` and ` NPM After "path", the same problem still occurs during operation.
If there is no configuration error in the path, the same error will still occur
```ts
14:56:52.326 failed to load config from /Users/eachann-/Documents/Work/uniapp/vite.config.ts
14:56:52.330 error during build:
14:56:52.331 /Users/eachann-/Documents/Work/uniapp/node_modules/@unocss/vite/dist/index.cjs:332
14:56:52.336         return command === "build" && !options.build?.ssr;
14:56:52.336                                                      ^
14:56:52.349 SyntaxError: Unexpected token '.'
14:56:52.350     at wrapSafe (internal/modules/cjs/loader.js:915:16)
14:56:52.355     at Module._compile (internal/modules/cjs/loader.js:963:27)
14:56:52.355     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
14:56:52.366     at Module.load (internal/modules/cjs/loader.js:863:32)
14:56:52.366     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
14:56:52.371     at Module.require (internal/modules/cjs/loader.js:887:19)
14:56:52.382     at require (internal/modules/cjs/helpers.js:74:18)
```

**Comment by antfu** [comment]
I consider this as out-of-scope. UniApp should support Node v14 as v12 is EOL already.
https://node.green/#ES2020-features-optional-chaining-operator-----
