### ISSUE TITLE
如图，这些默认的 css var 变量有配置可以删除吗

### ISSUE THREAD

**Issue by Miofly** [unocss/unocss#1425]
以前 `import` 的时候可以 `import 'uno:default.css';`，现在这样不行了是为什么？这样 `import 'uno.css';` 引入的话就会产生如图一堆 css 变量 
![image](https://user-images.githubusercontent.com/42859910/184875216-f3b8c640-1c8a-4e74-825a-13cd035d8bf6.png)

**Comment by chris-zhu** [comment]
dupliate of #1226
