### ISSUE TITLE
<md not supported

### ISSUE THREAD

**Issue by FireMasterK** [unocss/unocss#1427]
Hi, I was migrating a project from WindiCSS to UnoCSS, but found that <md (and other sizes) does not work in UnoCSS like it did in WindiCSS.

Example:
```html
<span class="<md:hidden">Hello World!</span>
```

**Comment by momoathome** [comment]
Hey, i just read that in some other Issue. You need to write `lt-md:hidden` for `<md:hidden` and `gt-md:hidden` for `>md:hidden`
heres the answered Issue #997
