### ISSUE TITLE
[webpack]: infinite compile in dev mode

### ISSUE THREAD

**Issue by ChpShy** [unocss/unocss#1429]
# description

I create a new project by `vue-cli`@5.0.7, and when i run `pnpm run serve`, it is infinite compile, looks like caused by `/uno.css `.

And strangely, it is good in `vue-cli@4.x`.

# minimal reproduction
https://github.com/ChpShy/unocss-infinite-demo

# step 
`pnpm install`
`pnpm run serve`

**Comment by chris-zhu** [comment]
It's so crazy for infinite compile😂

**Comment by ChpShy** [comment]
yeah...unbelievable...
