### ISSUE TITLE
Arbitrary variant selector syntax not working

### ISSUE THREAD

**Issue by zaydek** [unocss/unocss#1431]
Hi, thank you for your work on UnoCSS. I am working with Solid and I am trying to use UnoCSS’s arbitrary selector feature which works in the playground.

Given the following code:

```tsx
function App() {
  return <>
    <div class="[color:red]">Hello, world!</div>
    <div class="[&>*]:[color:red]">
      <div>Hello, world!</div>
      <div>Hello, world!</div>
      <div>Hello, world!</div>
      <div>Hello, world!</div>
    </div>
  </>
}
```

I expected all lines to be red but I’m only seeing the first line render as red.

Here’s a MVP repro: https://github.com/zaydek/solid-unocss-arbitrary-variant-bug. 

Here is the playground version using the same code and config (I originally copied the config from the playground): https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIDaMD2ccBOAXAQKYgC66AfABKlz4A0UA7oXCAITAD04EagChQkWIhQZMAMmoAqCkWx5CJclWFQoowfUY4W7Apx79Im7QLoNmbDtz5WhWndf2H7ppy6t7bRk0dzETNBIA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAqrhJQL5xZQQhwDkAV1YBjOnX5IkGAB6RY6bAENBAG3iYc%2BIiWCkAFMlQ16jOgC44AbSrHaDZq30BKSqgC6Sds6RA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g.

Is there something I’m doing wrong? Thank you.

**Comment by chris-zhu** [comment]
I'm just only see playground, all lines was red. It's same as your expect.😅

**Comment by zaydek** [comment]
> I'm just only see playground, all lines was red. It's same as your expect.😅

Yes. That’s the expected output. If you open the repro I created and run npx vite you will see different results.

**Comment by chris-zhu** [comment]
I found it's encoded. Can't be parsed.
<img width="812" alt="image" src="https://user-images.githubusercontent.com/42139754/185167544-78dd06c8-84af-424e-86a8-9a428d73ea58.png">

**Comment by zaydek** [comment]
Oh this must be a side-effect of Solid being transformed by Babel. I’ll bring this to the attention of Solid. Thanks for diagnosing!

**Comment by chris-zhu** [comment]
> Oh this must be a side-effect of Solid being transformed by Babel. I’ll bring this to the attention of Solid. Thanks for diagnosing!

Oh ! i paste your  test code in unocss' example named `vite-solid` project. I find it's work success.
And i'm not familiar with solid, may be giving you the wrong hint. I'm sorry to if that.
Finally, You can try and check the difference between [unocss example](https://github.com/unocss/unocss/tree/main/examples/vite-solid) and your repo.

**Comment by zaydek** [comment]
> > Oh this must be a side-effect of Solid being transformed by Babel. I’ll bring this to the attention of Solid. Thanks for diagnosing!
> 
> Oh ! i paste your test code in unocss' example named `vite-solid` project. I find it's work success. And i'm not familiar with solid, may be giving you the wrong hint. I'm sorry to if that. Finally, You can try and check the difference between [unocss example](https://github.com/unocss/unocss/tree/main/examples/vite-solid) and your repo.

Thank you! I'll try vite-solid and check if that works.

**Comment by zaydek** [comment]
@chris-zhu It looks like it’s the order of the plugins. By calling `{ ...solidPlugin(), enforce: "post" }` it works. I did try to repro the repo you linked but I got the same results until I used enforce. I also tried `pre` on UnoCSS but got the error linked here: https://github.com/solidjs/solid/issues/1169#issuecomment-1221322246.

```ts
export default defineConfig({
  plugins: [
    {
      ...solidPlugin(),
      enforce: "post",
    },
    // ...
  ],
  // ...
})
```

Is there any foreseeable problem using enforce to get plugins to work together? Thank you.

**Comment by zaydek** [comment]
Alright I’m gonna close this issue since this is working. If future Solid users run into this, you can simply use:

```tsx
import { defineConfig } from "vite"
import solid from "vite-plugin-solid"
import unocss from "unocss/vite"

export default defineConfig({
  plugins: [
    unocss(),
    solid({
      hot: false,
    }),
  ],
  server: {
    port: 3000,
  },
  build: {
    target: "esnext",
  },
})
```

Thanks @chris-zhu!
