### ISSUE TITLE
Why can't I use the inspector after installing the vite-plugin-html

### ISSUE THREAD

**Issue by maddenBoy** [unocss/unocss#1444]
## description
First, I create a project with vite, then i install vite-plugin-html, I can't visit http://localhost:5173/__unocss in my Vite dev server normally.

## minimal reproduction
https://github.com/maddenBoy/unocss-nowork-inspector/tree/main/unocss-nowork-inspector

## step
```pnpm install```
```pnpm run serve```

**Comment by chenbimo** [comment]
这个问题也遇到了。
