### ISSUE TITLE
@unocss/webpack after 0.45.8 is not work

### ISSUE THREAD

**Issue by MellowCo** [unocss/unocss#1455]
use [unocss/examples/vue-cli4](https://github.com/unocss/unocss/tree/main/examples/vue-cli4) and  [unocss/examples/vue-cli5](https://github.com/unocss/unocss/tree/main/examples/vue-cli5)

### `@unocss/webpack` with `0.45.8`
![image](https://user-images.githubusercontent.com/47939250/185912003-c672638c-0e1d-46e6-8760-8080dbaa640f.png)
### is ok
![image](https://user-images.githubusercontent.com/47939250/185912152-27be0b53-da50-4cea-a7c5-3fd6d2f9379a.png)

### `@unocss/webpack` after `0.45.8`  like `0.45.9` or `0.45.12`
![image](https://user-images.githubusercontent.com/47939250/185912836-588fc3ea-2119-4b66-a2c6-8028498226a3.png)

### is not work
![image](https://user-images.githubusercontent.com/47939250/185912903-38ab2aa8-fe34-430e-8516-6334c0b118d0.png)

### `@unocss/webpack` with `0.45.8`
![image](https://user-images.githubusercontent.com/47939250/185913554-cbd53b48-5bba-42c9-bf2c-4afaf6097b6d.png)

### is ok
![image](https://user-images.githubusercontent.com/47939250/185913453-2f9b3090-3f81-453b-ac60-36840f9e4255.png)

### `@unocss/webpack` after `0.45.8`  like `0.45.9` or `0.45.12`
![image](https://user-images.githubusercontent.com/47939250/185913888-521f872e-c941-429d-95d2-711bb91798e4.png)

### is not work
![image](https://user-images.githubusercontent.com/47939250/185913824-d026120e-833f-4491-beb1-4bc07de1058c.png)

**Comment by ChpShy** [comment]
It looks ok in my project or example in unocss. Maybe you can add a minimal reproduction?

**Comment by yangguang6** [comment]
minimal reproduction:
https://github.com/yangguang6/unocss-webpack-issue

**Comment by ChpShy** [comment]
I tried to run your repo and it is ok in first load, but not take effect in HMR load. In my mind, this is an old problem in webpack. 🤔

**Comment by MellowCo** [comment]
### minimal reproduction:
[vue-cli4](https://github.com/MellowCo/vue-cli4) [vue-cli5](https://github.com/MellowCo/vue-cli5)

**Comment by antfu** [comment]
Could relate to https://github.com/unjs/unplugin/pull/155?

**Comment by Candinya** [comment]
Same issue but only reproduced on Windows (Windows 11 21H1, Node v18.7.0), seems OK on macOS (macOS 12.4, Node v18.7.0). There might be an OS related issue? 🤔

**Comment by lamualfa** [comment]
@antfu any idea about this issue?
