### ISSUE TITLE
compatibility problem:  __uno.css:9 Uncaught SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by JiatLn** [unocss/unocss#1461]
maybe is a compatibility problem?

browser: **Sogou Browser**
version: 11.0.1.34700

example project: https://github.com/JiatLn/vvtt

when run `npm run dev`, the page is empty and throw error `__uno.css:9 Uncaught SyntaxError: Unexpected reserved word`
on console following:

![image](https://user-images.githubusercontent.com/16984236/186368041-6212bb3e-132e-41c8-a779-e8320b588572.png)

![image](https://user-images.githubusercontent.com/16984236/186367981-361b421e-381e-4507-94ea-bf45b9f98e78.png)

**Comment by antfu** [comment]
Can you try with the latest Chrome?

**Comment by JiatLn** [comment]
> Can you try with the latest Chrome?

yes, is work in chrome but not in Sogou Browser

**Comment by antfu** [comment]
Maybe it's because the browser does not support top-level await? Any reason to use it over Chrome for development?

**Comment by JiatLn** [comment]
> Maybe it's because the browser does not support top-level await? Any reason to use it over Chrome for development?

I development was used chorme, but also need to debug at other browser, so :(

**Comment by Jurool** [comment]
> > Maybe it's because the browser does not support top-level await? Any reason to use it over Chrome for development?
> 
> I development was used chorme, but also need to debug at other browser to fix other style compatibility problem, so :(

Chrome is recommended for development, and compatibility should be tested in build mode

**Comment by vinoMamba** [comment]
If you are developing on dingtalk enviroment, you should upgrade you dingtalk  debugg tool

**Comment by zyyv** [comment]
We optimized it on #2066 , you can try it.
https://github.com/unocss/unocss/blob/65dc7a4f822606592267d9c54d7f04979f85fda0/packages/vite/src/types.ts#L40-L50
