### ISSUE TITLE
@apply not working  by vue-cli5.0.8(Vue2.6.14) initialization project

### ISSUE THREAD

**Issue by Alkaidcc** [unocss/unocss#1465]
I want import `@unocss/transformer-directives` to use `@apply`, but it not working in the below project.

Minimal reproducible example:
https://stackblitz.com/edit/vue2-vue-cli-sutyue
and when I use `--at-apply`, it still not working

But in Vite(Vue3.2.37), it works well.
https://stackblitz.com/edit/vitejs-vite-nsvplp

**Comment by Alkaidcc** [comment]
looks like same as #1455

**Comment by mdxiaohu** [comment]
@Alkaidcc Can you use '@ apply' now? I also encountered the same problem as you,
Was it resolved by reducing the version?
