### ISSUE TITLE
How to create a variant for custom pseudo-elements

### ISSUE THREAD

**Issue by itpropro** [unocss/unocss#1466]
I want to customize an input field of type `range` with unocss classes. To customize the track and thumb, we need to target browser specific pseudo-elements (`moz-range-track`, `-webkit-slider-runnable-track`, `-moz-range-thumb`, `-webkit-slider-thumb`). Therefore, I created two shortscuts and two variant matcher:

```typescript
  const trackVariants = /^((moz|webkit)?-range-track):.+$/;
  const thumbVariants = /^((moz|webkit)?-range-thumb):.+$/;

  shortcuts: [
    [/^range-track:(.+)$/, ([, s]) => `moz-range-track:${s} webkit-range-track:${s}`],
    [/^range-thumb:(.+)$/, ([, s]) => `moz-range-thumb:${s} webkit-range-thumb:${s}`],
  ],

  variants: [
    // range-track
    (matcher) => {
      if (!trackVariants.test(matcher))
        return;
      const prefix = matcher.replace(trackVariants, '$2');
      return {
        matcher: matcher.slice(prefix.length + 13),
        selector: (s) => {
          switch (prefix) {
            case 'moz':
              console.log(`${s}::-moz-range-track`);
              return `${s}::-moz-range-track`;
            case 'webkit':
              console.log(`${s}::-webkit-slider-runnable-track`);
              return `${s}::-webkit-slider-runnable-track`;
          }
        }
      };
    },
    // range-thumb
    (matcher) => {
      if (!thumbVariants.test(matcher))
        return;
      const prefix = matcher.replace(thumbVariants, '$2');
      return {
        matcher: matcher.slice(prefix.length + 13),
        selector: (s) => {
          switch (prefix) {
            case 'moz':
              return `${s}::-moz-range-thumb`;
            case 'webkit':
              return `${s}::-webkit-slider-thumb`;
          }
        }
      };
    },
  ],
```

Unfortunately, the generated CSS only works for Firefox: 

```
<template>
  <input
    type="range"
    min="0"
    max="100"
    v-model="value"
    class="w-full range-track:bg-red-400 range-thumb:bg-green"
  />
</template>

---> Generated CSS

.range-thumb\\:bg-green::-moz-range-thumb,
.range-thumb\\:bg-green::-webkit-slider-thumb {
  --un-bg-opacity: 1;
  background-color: rgba(74, 222, 128, var(--un-bg-opacity));
}

.range-track\\:bg-red-400::-moz-range-track,
.range-track\\:bg-red-400::-webkit-slider-runnable-track {
  --un-bg-opacity: 1;
  background-color: rgba(248, 113, 113, var(--un-bg-opacity));
}
```

What would be the best way to implement such pseudo-elements where each browser has specific variants (there is also the `-ms-track` and `-ms-thumb` variant for the input)?

**Comment by chris-zhu** [comment]
There is a similar case https://github.com/unocss/unocss/issues/1391.

**Comment by itpropro** [comment]
Is autoprefixer the right place for adding multiple custom pseudo-elements? If you have any tips on how I could generate more than one variant for the same class or how to impact the generated CSS in a way that the selectors work, it would be enough @chris-zhu. My problem is that it works with just one variant like this:

```css
.range-track\\:bg-red-400::-moz-range-track {
  --un-bg-opacity: 1;
  background-color: rgba(248, 113, 113, var(--un-bg-opacity));
}
```

or respective this

```css
.range-track\\:bg-red-400::-webkit-slider-runnable-track {
  --un-bg-opacity: 1;
  background-color: rgba(248, 113, 113, var(--un-bg-opacity));
}
```

But as soon as I have two or more generated, the targeting only works for the first one in the list.

**Comment by chris-zhu** [comment]
I'm sorry for not reading your question carefully. I will keep watching and try to help on the right way

**Comment by itpropro** [comment]
@antfu do you maybe have a tip, which way to go for this? :)

**Comment by chu121su12** [comment]
Maybe [related](https://css-tricks.com/styling-cross-browser-compatible-range-inputs-css/)

> Note that while we’re repeating code here, that’s necessary as you can’t comma-separate these type of selectors. Browsers will drop the entire selector if it doesn’t understand a part of it.

This is due to `::-moz-range-track` and `::-webkit-slider-runnable-track` got merged due to the use of a single variant. Depending on which selector is earlier, say `moz`, webkit browsers will drop the whole definition since they don't undersatnd `moz` prefix. 

Please check the updated `noMerge` paramater introduced in the merged pr; you can also check the tests for examples.

**Comment by itpropro** [comment]
Thanks for the hint @chu121su12 ! I know all the pseudo-elements and that article, but the `noMerge` option is exactly what I needed 👍

**Comment by aviadmini** [comment]
For future reference:
I've had success with [postcss](https://unocss.dev/integrations/postcss) integration and this postcss plugin: [postcss-input-range](https://www.npmjs.com/package/postcss-input-range) 

Here are my variants from `uno.config.ts`
```ts
variants: [
        // range-thumb:
        {
            match: (matcher) => {
                if (!matcher.startsWith('range-thumb:')) { return matcher; }
                return {
                    // slice `range-thumb:` prefix and passed to the next variants and rules
                    matcher: matcher.slice(12),
                    handle: (input, next) => next({
                        ...input,
                        pseudo: `${input.pseudo}::range-thumb`,
                        noMerge: true,
                    })
                }
            }
        },
        // range-track:
        {
            match: (matcher) => {
                if (!matcher.startsWith('range-track:')) { return matcher; }
                return {
                    // slice `range-track:` prefix and passed to the next variants and rules
                    matcher: matcher.slice(12),
                    handle: (input, next) => next({
                        ...input,
                        pseudo: `${input.pseudo}::range-track`,
                        noMerge: true,
                    })
                }
            }
        }
    ],
    ```
