### ISSUE TITLE
Are UNOCSS/NUXT presets configurable or not injected?

### ISSUE THREAD

**Issue by itmanyong** [unocss/unocss#1467]
English is not good! Please forgive me!
The phenomenon of:
     Nuxt3 + unocss/nuxt collocation! May affect the default style of other third-party component libraries. As shown in the figure below
![image](https://user-images.githubusercontent.com/53500371/186656039-35700a48-d9ba-4969-a733-31a41b29e8f1.png)
The problem arises when：
   After configuring @unocss/nuxt in Modules, the style tag is automatically injected as shown below
![image](https://user-images.githubusercontent.com/53500371/186656211-87529557-18cd-42bc-adb7-1b1ab6180607.png)
![image](https://user-images.githubusercontent.com/53500371/186656267-1598223d-0203-49b8-a10c-8a44464244bb.png)

tips:
1.Is there any way to remove this part of autoinjection? Or turn it off

**Comment by antfu** [comment]
https://github.com/unocss/unocss/blob/47a0905daf042b0f56bf10eeaf71df95cba7f971/packages/nuxt/src/types.ts#L11-L23
