### ISSUE TITLE
defect

### ISSUE THREAD

**Issue by Hachiaaa** [unocss/unocss#1471]
If i write some string in vue `<script>` label , like `const a = "text-red"`, unocss would extract it as valid match result and generate relative css code. But that is not what i want , how to prevent this? thanks @antfu

**Comment by chris-zhu** [comment]
This is unavoidable, UnoCSS will do its best to generate css for you.
If you want dont scan that files, please refer to [scanning](https://github.com/unocss/unocss#scanning)
