### ISSUE TITLE
`unocss` highlight does't work when the unocss configurations are nested under `vite.config.ts`

### ISSUE THREAD

**Issue by priority3** [unocss/unocss#1474]
`unocss` highlight does't work in .vue file when the unocss configurations are nested under `vite.config.ts`，I can resolve it by use `class`  with `windicss` plugin
当我的unocss在`vite.config.ts`下做嵌套配置时，unocss的高亮在vue文件中并不会生效，只有使用类名借助windicss插件解决,如下
![image](https://user-images.githubusercontent.com/75966543/186847785-5b225c02-7c86-49c5-a4c5-d9f14f31cc60.png)
My style highlight does't work in this case,
此时我的样式高亮并不会生效
![image](https://user-images.githubusercontent.com/75966543/186847847-d923ae81-71e6-44c5-bccc-a337dd07dcc1.png)
However, when I don't nest the configuration of unocss under `vite.config.ts` or directly provide `unocss.config.ts`,everything works normally
但是当我将unocss的配置在`vite.config.ts`下不做嵌套时，或者直接提供`unocss.config.ts`，所有一切都正常工作 
![image](https://user-images.githubusercontent.com/75966543/186848224-12b1c2d9-70a5-40a6-a2bb-564df65ec545.png)
![image](https://user-images.githubusercontent.com/75966543/186848274-0991e321-87c8-42b1-9991-c7bf11fb8bf6.png)

**Comment by antfu** [comment]
This is how it works. The VS Code extension needs a way to grab the config. It's recommended to use a separate `uno.config.ts`

**Comment by priority3** [comment]
> This is how it works. The VS Code extension needs a way to grab the config. It's recommended to use a separate `uno.config.ts`

i got it ，thanks😊
