### ISSUE TITLE
Arbitrary grid template columns incorrect

### ISSUE THREAD

**Issue by lawrencecchen** [unocss/unocss#1478]
`grid-cols-[1fr,2fr]` should be "grid-template-columns: 1fr 2fr", not "grid-template-columns:1fr,2fr;

Reproduction:
https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIDmAnMIC0MA9nEvgNoCMAZtgDQBMtAuugHzAD04EbQA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUkNikEA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g

WindiCSS's behavior:
https://windicss.org/utilities/layout/grid.html#:~:text=cols%2D%5B1fr%2C2fr%5D-,CSS,2c%202fr%5C%5D%20%7B%0A%20%20grid%2Dtemplate%2Dcolumns%3A%201fr%202fr%3B%0A%7D,-1

MDN spec:
https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-columns

**Comment by chris-zhu** [comment]
You can use `grid-cols-[1fr_2fr]`

**Comment by 0phoff** [comment]
Is this behaviour documented somewhere ?  
I had to look at this issue to find a solution for my problem.  
The syntax in windicss is with comma's so it might not be immediately obvious for people who are switching over. :innocent:
