### ISSUE TITLE
How do I override Elements Plus UI default styles in a production environment?

### ISSUE THREAD

**Issue by wangfunfun** [unocss/unocss#1497]
This code is normal in the development environment, but it is overwritten by the Elements Plus UI style in the production environment and will not work.
```
<el-button  h-14 text-4  mr-8  font-600  type="primary"  p-x="6" @click="goLogin">
  {{ t('website.home.getStart') }}
</el-button>
```
😵‍💫 So what should I do?

**Comment by chris-zhu** [comment]
Can you provide a minimal repo ?

**Comment by wangfunfun** [comment]
This is my project: https://github.com/wangfunfun/fa-web-app/tree/dev

**Comment by wangfunfun** [comment]
> Can you provide a minimal repo ?

This is my project: https://github.com/wangfunfun/fa-web-app/tree/dev

**Comment by sudongyuer** [comment]
Have a try !important

**Comment by wangfunfun** [comment]
> Have a try !important

How should I implement '!important' on an HTML tag via unoCSS

**Comment by sudongyuer** [comment]
> > Have a try !important
> 
> How should I implement '!important' on an HTML tag via unoCSS
I'm not very familiar with UNOCSS, but it seems like this will make it work. Try it
![image](https://user-images.githubusercontent.com/76603360/187354895-f326c9ff-6c11-4ab7-9b65-210c5e2818c8.png)

**Comment by wangfunfun** [comment]
> > > Have a try !important
> > 
> > 
> > How should I implement '!important' on an HTML tag via unoCSS
> > I'm not very familiar with UNOCSS, but it seems like this will make it work. Try it
> > ![image](https://user-images.githubusercontent.com/76603360/187354895-f326c9ff-6c11-4ab7-9b65-210c5e2818c8.png)

Thank you very much. I solved the problem by installing your method 😃🤩

**Comment by chris-zhu** [comment]
Well, i think you just need import `uno.css` after `element-plus`. In my project, it's work fine.
```ts
import 'element-plus/dist/index.css'
import 'uno.css'
```

**Comment by wangfunfun** [comment]
> Well, i think you just need import `uno.css` after `element-plus`. In my project, it's work fine.
> 
> ```ts
> import 'element-plus/dist/index.css'
> import 'uno.css'
> ```

Okay, thank you, but I'm using on-demand import Element Plus's style.
And with the help of Sudongyuer, I used important to solve the problem, but I hope to find the fundamental solution ❤️

**Comment by chu121su12** [comment]
Methodologically, this is css issue. Libraries and UI libraries have their own way of importing additional css with their own ordering. If the import/apply order cannot be altered easily, you have to depend on how css resolve its [specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity).
