### ISSUE TITLE
how to make classname has underline when using `@apply`?

### ISSUE THREAD

**Issue by hequ9** [unocss/unocss#1498]
### When i using in the `class` attribute,it works fine:
![微信截图_20220830131835](https://user-images.githubusercontent.com/49673052/187357370-5b2e65c8-5262-4b8e-a16f-b2c910426338.png)

###  using `@apply`:
![2](https://user-images.githubusercontent.com/49673052/187357596-390d8e07-08db-422a-a684-df657d6c560e.png)

someone help me?

**Comment by chris-zhu** [comment]
try `--at-apply` instead of `@apply`

**Comment by hequ9** [comment]
![微信截图_20220830143921](https://user-images.githubusercontent.com/49673052/187369204-ef8d9063-0f94-4747-a2e4-26a1e2d0d23c.png)
---
actually I tried it earlier but it still doesn't work.🥲

**Comment by chris-zhu** [comment]
<img width="369" alt="image" src="https://user-images.githubusercontent.com/42139754/187372631-97ef6a6a-99aa-43c5-9055-27e46baa00c3.png">
<img width="295" alt="image" src="https://user-images.githubusercontent.com/42139754/187373277-2fefc220-56ae-4682-a19e-fc63c7582ea2.png">

In my local, although he successfully displayed, there are still some small problems.

<img width="397" alt="image" src="https://user-images.githubusercontent.com/42139754/187373720-e7abe5fe-de03-4b09-908c-e05221ae7bbb.png">

**Comment by hequ9** [comment]
i think there is something wrong with my vscode extension for language support although im not sure which one, but thanks🤝

**Comment by hequ9** [comment]
anyway even comments, except `@apply` and `--at-apply`🤣🤣
https://user-images.githubusercontent.com/49673052/187392410-247e62de-930a-4543-bed8-f9fe6e50546d.mp4

**Comment by hequ9** [comment]
i seem to have found something wrong.

when `transformerDirectives`  in my `uno.config.ts`, it will fail.

![1](https://user-images.githubusercontent.com/49673052/187574049-f6c0426b-1810-4ffb-bcac-d95ee49d6a78.png)

![2](https://user-images.githubusercontent.com/49673052/187574201-b5e7f56b-5b36-4f55-b940-24387dc581b4.png)

the way i solved it was to add `transformerDirectives` to `vite.config.ts`, now it's ok.

![3](https://user-images.githubusercontent.com/49673052/187576156-3feb7f43-9d3d-4603-b706-45216e2a1387.png)

im not sure if this is a bug from unocss extension?

**Comment by lrstanley** [comment]
Using both the latest extension as well as the latest version of unocss with vite, running into the same issue with vscode. `@apply` is broken, including hovering over utility classes inside of `@apply`. What's odd is this works for me inside of a `vue` SFC file, but not in `.css` files. Tried both loading the config from vite, as well as a standalone file. Properly set `unocss.root` as well in vscode.
