### ISSUE TITLE
`svelte-scoped` broken with both Svelte and SvelteKit

### ISSUE THREAD

**Issue by Coretteket** [unocss/unocss#1499]
In both Svelte and SvelteKit apps, using the `svelte-scoped` mode throws the following error:
```
[plugin:vite:import-analysis] Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.
/home/projects/vitejs-vite-roa5ya/src/App.svelte:202:30
    at formatError (file:///home/projects/vitejs-vite-roa5ya/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35378:46)
    at TransformContext.error (file:///home/projects/vitejs-vite-roa5ya/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35374:19)
    at TransformContext.transform (file:///home/projects/vitejs-vite-roa5ya/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:40238:22)
    at async Object.transform (file:///home/projects/vitejs-vite-roa5ya/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35627:30)
    at async loadAndTransform (file:///home/projects/vitejs-vite-roa5ya/node_modules/vite/dist/node/chunks/dep-0fc8
```

**Minimal reproductions:**
Svelte: https://stackblitz.com/edit/vitejs-vite-roa5ya?file=vite.config.js
SvelteKit: https://stackblitz.com/edit/sveltejs-kit-template-default-zz2ro7?file=vite.config.js
(both are the default StackBlitz templates with just the `vite.config.js` edited)

Am I using the mode wrong, or is this a bug?

**Comment by sudongyuer** [comment]
It looks like a bug

**Comment by sudongyuer** [comment]
I will try to solve this problem later

**Comment by sudongyuer** [comment]
> In both Svelte and SvelteKit apps, using the `svelte-scoped` mode throws the following error:
> 
> ```
> [plugin:vite:import-analysis] Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.
> /home/projects/vitejs-vite-roa5ya/src/App.svelte:202:30
>     at formatError (file:///home/projects/vitejs-vite-roa5ya/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35378:46)
>     at TransformContext.error (file:///home/projects/vitejs-vite-roa5ya/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35374:19)
>     at TransformContext.transform (file:///home/projects/vitejs-vite-roa5ya/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:40238:22)
>     at async Object.transform (file:///home/projects/vitejs-vite-roa5ya/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35627:30)
>     at async loadAndTransform (file:///home/projects/vitejs-vite-roa5ya/node_modules/vite/dist/node/chunks/dep-0fc8
> ```
> 
> **Minimal reproductions:** Svelte: https://stackblitz.com/edit/vitejs-vite-roa5ya?file=vite.config.js SvelteKit: https://stackblitz.com/edit/sveltejs-kit-template-default-zz2ro7?file=vite.config.js (both are the default StackBlitz templates with just the `vite.config.js` edited)
> 
> Am I using the mode wrong, or is this a bug?

Hey bro , i found that not a bug , follow this below you will solve this problem
https://github.com/sudongyuer/demo-svelte/blob/master/vite.config.js
![image](https://user-images.githubusercontent.com/76603360/187579108-025d1f05-f0f1-48cc-b317-7aa346fc838d.png)
ref:https://github.com/unocss/unocss/tree/main/packages/vite#svelte

**Comment by Coretteket** [comment]
Thanks so much for the quick response! That's definitely a mistake on my part for the Svelte example, but it appears like my SvelteKit example follows the correct plugin order of the [documentation](https://github.com/unocss/unocss/tree/main/packages/vite#sveltekit). Switching the order to `[unocss({ mode: 'svelte-scoped' }), sveltekit()]` does seem to work, though!
