### ISSUE TITLE
suggestion: storybook addons

### ISSUE THREAD

**Issue by productdevbook** [unocss/unocss#150]
I think unocss and all its features should be handled by the [storybook](https://storybook.js.org) with vite addons. It would be great if someone could do it.

[storybook-builder-vite](https://github.com/eirslett/storybook-builder-vite)

**Comment by stephenhebert** [comment]
This seems to work for me with a little configuration.  A simple example, using the vitesse template:

In `.storybook/main.js`:
```
const path = require('path');
const Inspect = require('vite-plugin-inspect');
const Unocss = require('unocss/vite');

module.exports = {
  ...
  async viteFinal(config, { configType }) {
    config.resolve.alias['~'] =  `${path.resolve(__dirname, 'src')}/`;
    config.plugins.push(Unocss.default());
    config.plugins.push(Inspect());
    return config;
  }
```

In `.storybook/preview.js`:
```
import '@unocss/reset/tailwind.css'
import '../../src/styles/main.css'
import 'uno.css'
```

**Comment by toeyeen** [comment]
For anyone using storybook version ^7.0.0, vitesse vue starter pack where UnoCss is used for styling, all that is required from you is to add this to the storybook config object in the .storybook/main.ts file

```
import Unocss from 'unocss/vite';

const config: StorybookConfig = {
  viteFinal(config){
    config.plugins?.push(Unocss())
    // Add other configuration here depending on your use case
    return config
  }
}

```

Also, on the .storybook/preveiw.ts file import your styles
```
import '../src/styles/main.css';
import '@unocss/reset/tailwind.css';
import 'uno.css'; 
````

**Comment by blowsie** [comment]
UnoCSS doesnt work on classes inside the `.stories.ts` files, any suggestions?

**Comment by blowsie** [comment]
Here is a solution to add support for stories 🎉
```
 content: {
    pipeline: {
      include: [
        // the default
        /\.(vue|svelte|[jt]sx|mdx?|astro|elm|php|phtml|html)($|\?)/,
        // Include Storybook stories
        'src/**/*.stories.{js,ts}',
        'stories/**/*',
      ],
    },
  },
  ```

**Comment by sethfacade** [comment]
> 

@blowsie I am trying to get this to work as well, is this supposed to be added in the main.ts file? I have a StoryBookConfig type and it's linting me on content.

**Comment by blowsie** [comment]
You need to add the above config to your unu.config.ts

**Comment by sethfacade** [comment]
Thanks! Was able to get it to work. I was on an older version so the syntax was a little different. Leaving up my solution here as well for others. If you don't have `uno.config.ts` file setup, you can just stick it in the `main.ts file` this is on an older version. If you're on the latest version, the above solution blowsie shown works.

```const config: StorybookConfig = {
  viteFinal(config) {
    return mergeConfig(config, {
      plugins: [
        unocss({
          include: [/\.(vue|svelte|[jt]sx|mdx?|astro|elm|php|phtml|html|stories?)($|\?)/],
          extraContent: {
               filesystem: [file-path-to-stories]
          },
        })
      ],
    });
  },
}
```
