### ISSUE TITLE
Using css variable inside arbitrary values not working

### ISSUE THREAD

**Issue by NamesMT** [unocss/unocss#1507]
Without arbitrary value squares:  ✓

![image](https://user-images.githubusercontent.com/23612546/187843130-1425ca50-f4ae-41e7-9f78-cd125eec211c.png)

With arbitrary value squares: X
![image](https://user-images.githubusercontent.com/23612546/187844475-f7b2d519-4dfc-43c1-bdc2-672a6a7e43ec.png)

With arbitrary value squares, written as var(): X
![image](https://user-images.githubusercontent.com/23612546/187844556-eb981d55-d1ba-4f90-8c58-dafe284d6474.png)

With arbitrary value squares, written as var(), with escape slash: X
![image](https://user-images.githubusercontent.com/23612546/187844675-e90bf257-3af4-4b85-9472-57f00836cc66.png)

Example needed usecase:
![image](https://user-images.githubusercontent.com/23612546/187845008-ee731b1f-3891-4949-98e2-e7562fcd7cee.png)

**Comment by NamesMT** [comment]
After a re-look, this issue is more like a "underscore arbitrary escape not working" issue, could do a title rename.

**Comment by chris-zhu** [comment]
I think you must follow the hermit usage rules in `bracket`.

**Comment by NamesMT** [comment]
@chris-zhu could you give me a lead / link?, I'm too lost in the docs maze and can't a way to use the css variable in unocss.
In Tailwind Playground I could use arbitrary css variable with escape slash:
![image](https://user-images.githubusercontent.com/23612546/187885661-d0c455d3-6ed3-4a32-bef6-92295304a35c.png)

**Comment by chris-zhu** [comment]
Just use `$variable`;  e.g. : `ml-$M_L`

**Comment by NamesMT** [comment]
Hi Chris,
As you can see in my examples, it didn't work, in a use case where arbitrary value is needed.
 
https://github.com/unocss/unocss/issues/1507#issue-1358312281

**Comment by NamesMT** [comment]
This whole issue comes down to escape slash for underscore ("`\_`") in uno is bugged, we can close this issue and create a new one for more clarity of purpose.
