### ISSUE TITLE
theme.colors extend bug for base-only colors

### ISSUE THREAD

**Issue by NamesMT** [unocss/unocss#1509]
On theme.colors extend, base-only colors like `black` and `white` will be unable to use it's base style (ie: `bg-white`)

[Playground Reproduce](https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIAuBTAHpgWgCNEYBrKIgc2LgFdt0B6APgCgALMKTD7AJ2xA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAqrhJQL5xZQQhwDkAV1YBjOnX5IkGAB6RY6bAENBAG3iYc%2BIiWCkAFMlQwAFhhAYAXIiqoREVdDrWjqNwCNVSkQGsXtt1QaUCUoAE9rfgBiLFi4-kpA1HZEpM9BKxskt2CQUIiBKIAGAFYSgBYAMUqEgOTU%2BqoUqhp6Rmc4AG0A1oZmVn0ASlSAXSR2QaQgA&options=N4XyA)

Image from Playground Reproduce:
![image](https://user-images.githubusercontent.com/23612546/187857333-2541d948-d5ab-4161-8e3e-ffccb201a7c1.png)

(Old) Image:
![image](https://user-images.githubusercontent.com/23612546/187856421-45ea517a-e2fb-4f6c-b43c-af93001454aa.png)

**Comment by NamesMT** [comment]
Would be fixed with a modification to [preset-mini/colors](https://github.com/unocss/unocss/blob/main/packages/preset-mini/src/_theme/colors.ts).
But I can't of the most efficient of doing it rn.

**Comment by chris-zhu** [comment]
You rewrite this color, add `DEFAULT` key to make it work.

[Playground](https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIAuBTAHpgWgCNEYBrKIgc2LgFdt0B6APgCgALMKTD7AJ2xA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAqrhJQL5xZQQhwDkAV1YBjOnX5IkGAB6RY6bAENBAG3iYc%2BIiWCkAFMlQwAFhhAYAXIiqoREVdDrWjqNwCNVSkQGsXtt1QAEQBRADEAQSYAGQAVa34AYgAGVP5KQMCaUCUoAE8ExKxikvSA1HYMzM9BKxtMt2yQXIKBFIBWdoAWMLCyhsqAwYqqmnpGZzgAbQCxhmZWfQBKKoBdJHYlpCA&options=N4XyA)

**Comment by NamesMT** [comment]
Thanks for the reply.
Yes, I know I could type a DEFAULT key (hence the PR).
What I meant with the issue and PR was shouldn't `black`/`white` still have their default (base) color when extended without a DEFAULT key?, since all other colors do theirs (auto parsed from color[400]).

**Comment by NamesMT** [comment]
Maybe it's just my opinion, thanks a lot anyway!
