### ISSUE TITLE
How do I disable Outline

### ISSUE THREAD

**Issue by muchenfine** [unocss/unocss#1515]
```
 WindiCSS({ preflight: false, config: { corePlugins: { outline: false }, important: "#app" } })
```

In WindCSS you can do that, but in UNOCSS, I don't know how do I disable it

**Comment by ydcjeff** [comment]
You can use a [reset package](https://github.com/unocss/unocss/tree/main/packages/reset) or `outline-none` utility.

**Comment by ydcjeff** [comment]
Check the docs at https://uno.antfu.me/?s=outline-none

**Comment by ydcjeff** [comment]
Then you can use `tailwind` reset or global css
```css
* {
  outline: none;
}
```

**Comment by chu121su12** [comment]
Since there's no [default plugins](https://github.com/unocss/unocss#features) for unocss, you may want to add preflight if you need a config-based solution:
```js
preflights: [
  {
    getCSS: () => `* { outline: none; }`,
  }
]
```
