### ISSUE TITLE
add preset-rem-to-px  as nuxt shortcut

### ISSUE THREAD

**Issue by joseehilton147** [unocss/unocss#1517]
Today we dont have rem to px as shortcut on nuxt, can you provide it please?

![image](https://user-images.githubusercontent.com/53986027/187934720-3797370e-eab7-43b2-af86-10ed11943dec.png)

Something like that:

![image](https://user-images.githubusercontent.com/53986027/187934881-c9f1a9e6-9060-456f-8669-c0408e2bbe9f.png)

**Comment by ydcjeff** [comment]
You can install the package separately and include it in the preset array.

**Comment by joseehilton147** [comment]
> You can install the package separately and include it in the preset array.

if i do that, this error occur: [https://github.com/unocss/unocss/issues/1518](#1518 )

**Comment by joseehilton147** [comment]
> You can install the package separately and include it in the preset array.

If i do this, this error occur: #1518

**Comment by antfu** [comment]
When you set `presets`, the shorthand `uno: true` will not be applied, you need to pass all the presets you want explicitly. I would also suggest moving to a separate `unocss.config.ts` for better IDE support.

**Comment by antfu** [comment]
rem-to-px will not be included as default presets at this moment.
