### ISSUE TITLE
vscode extension not working with rem-to-px preset nuxt

### ISSUE THREAD

**Issue by joseehilton147** [unocss/unocss#1518]
if i enable preset rem to px the extension stop working.

without preset:
![image](https://user-images.githubusercontent.com/53986027/187939586-cb2f1642-efd2-49b6-8ca3-62de565bf6fb.png)

with preset:
![image](https://user-images.githubusercontent.com/53986027/187939476-781643e9-18fb-464c-9715-d1e2cfac0534.png)

nuxt.config.ts:
![image](https://user-images.githubusercontent.com/53986027/187939703-bbb2de42-9195-4965-bcbd-7380df015503.png)
![image](https://user-images.githubusercontent.com/53986027/187939743-0acc2dfb-2d47-47a0-a02d-ccc5094bf323.png)

**Comment by chris-zhu** [comment]
I suggest you use `unocs.config.ts` file to configure UnoCSS.
If you use `presets` option, we consider you to have complete control over the presets.

https://github.com/unocss/unocss/blob/093e9273a385f155cb30a9f7ce747152286b4539/packages/nuxt/src/options.ts#L11-L27
