### ISSUE TITLE
@media css priority error

### ISSUE THREAD

**Issue by social-uni** [unocss/unocss#1521]
Sorry, my vpn is too bad to use online encoding, so I can only provide a minimal reproduction git address

## minimal reproduction git address

[https://github.com/social-uni/test-unocss-priority.git](https://github.com/social-uni/test-unocss-priority.git)

![image](https://user-images.githubusercontent.com/14007972/187948307-edcdc4a0-9595-455f-a8c5-3f554f70205f.png)

![image](https://user-images.githubusercontent.com/14007972/187950050-f38d89fe-5dec-4b53-9fc0-94219206a238.png)

vite.config.ts
```
Unocss({
      presets: [],
      rules: [
        StylesUtil.generateReactiveCss([/^font-(\d+)(.+)?$/, match => ({'font-size': `${match[1] || 20}${match[2] || 'px'}`})]),
      ]
    }),
```
```
import Breakpoints from "./Breakpoints";

export default class StylesUtil {
    static generateReactiveCss(rule: [RegExp, (match: string[]) => any]): [RegExp, (match: string[]) => any] {
        //返回的应该是newReg和包裹的方法
        const ruleReg = rule[0]
        const matchFun = rule[1]
        if (!ruleReg || !matchFun) {
            return rule
        }
        //第一个参数得到了
        const ruleStr = String(ruleReg)
        const newPointRuleStr = ruleStr.replace(/^\/\^(.+)\$\/$/, (inputText, matchVal) => {
            const newPointRule = '^((.+)\\:)?(' + matchVal + ')$'
            return newPointRule
        })

        const newPointRule = new RegExp(newPointRuleStr)

        //入参和返回参数都应该是两个方法
        function newMatchFun(matchStrAry: string[]) {
            //过滤掉自定义的参数，保留原始的参数
            const originalMatchStrAry = matchStrAry.filter((item, index) => ![1, 2, 3].includes(index))
            if (matchStrAry.length < 3) {
                return matchFun(originalMatchStrAry)
            }
            const point = matchStrAry[2]
            if (!Breakpoints.points.includes(point)) {
                return matchFun(originalMatchStrAry)
            }


            const matchRes = matchFun(originalMatchStrAry)

            let resStr = matchRes

            if (typeof matchRes !== "string") {
                resStr = JSON.stringify(resStr).replace(/"/g, '')
            }

            const endResStr = `
    @media (min-width: 768px) {
      .${point}\\:${matchStrAry[3]}${resStr}
      }
    `
            return endResStr
        }

        return [newPointRule, newMatchFun]
    }
}

```

**Comment by chris-zhu** [comment]
It's no problem in [Playground](https://uno.antfu.me/play/?html=DwEwlgbgBALgpgDxgWgIwA4AOCoGcC2AXPEsgMwCs2AfAFBRQD2AdsiHPgIbMhQDtUMM1wxuMflABmAVwA2sgJ5QAxtJGN8YAF6cARrLi1gAenARqQA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUkNikEA&options=N4IgTgpgzgDg9gOygSwG4RALgC5gK4QA0IA7sgCbYAWWAbAOz0B0ALAEwCctAHPQKzEqEZAHMq2LPQAMfJl158AvkA). You should check your `StylesUtil `. And i think you should have better way to resolve your problem.
