### ISSUE TITLE
[Bugs] Arbitrary variants group regex not match in VsCode Extention + not work expected

### ISSUE THREAD

**Issue by harrytran998** [unocss/unocss#1523]
Here is the code in React. 

![image](https://user-images.githubusercontent.com/24296018/187956529-22d3dc79-58fc-45d2-a2d4-f3e84d4adad0.png)

As you can see, the VsCode extension does not work correctly, but the weird behavior presents here when I add another class name same as in the arbitrary group --> The suggestion worked both - but the generator doesn't work. 

![image](https://user-images.githubusercontent.com/24296018/187956982-ee70812a-9ce8-47dd-931c-7346b1bb9298.png)

![image](https://user-images.githubusercontent.com/24296018/187957843-a175fa4b-c678-473a-9fe4-9faccda65e35.png)

But when I do not group the arbitrary anymore --> Worked as expected.

`<ul className="list-none p0 [&>li]:py5 [&>li]:border-b [&>li]:border-b-gray-300/80">`

![image](https://user-images.githubusercontent.com/24296018/187958325-13eb7ded-558e-4eac-964b-ddfd1afaa0cd.png)

So hope your team can fix this 😆. Thanks!

**Comment by QiroNT** [comment]
The VSCode issue is in #999, it currently doesn't support variant groups.
Can you check if you're using `@unocss/transformer-variant-group`? If yes then please provide a full reproduction, thanks.
Also check #1419, a similar issue has just been fixed recently, so try an update and see if it still happens.
