### ISSUE TITLE
How to override some presets in preset-uno

### ISSUE THREAD

**Issue by social-uni** [unocss/unocss#1526]
For example, I want to rewrite the text-14 style class, but I also want to keep other style classes in preset-uno, and I don't want to delete preset-uno. Is there a way to do it?

As far as I know, I can only delete the preset-uno preset, and then write the rule implementation myself. Is there a way to rewrite or override some presets?

i want  result
```
.text-14{
   font-size:14px;
}
```

preset-uni result
```
.text-14{
  font-size: 3.5rem;
}
```

**Comment by ydcjeff** [comment]
You can use `text-14px` ([playground](https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIAuBTAHpgWgEYAWAB13QD4g&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUkNikEA&options=N4XyA))

**Comment by social-uni** [comment]
> You can use `text-14px` ([playground](https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIAuBTAHpgWgEYAWAB13QD4g&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUkNikEA&options=N4XyA))

So why should I use unocss instead of windicss?

I use unocss because it is highly customizable

If you can only use the default style classes in preset, what is highly customizable?

![image](https://user-images.githubusercontent.com/14007972/188051247-b211f246-3b74-4d17-a6ee-1ac760e3d4f4.png)

I don't want to use text-14px, only to raise issues, for example I want to use .font-14{ font-size:14px}

**Comment by ydcjeff** [comment]
The default presets are made to be compatible with the existing frameworks. If you want to use `font-14`, then you need to write your own preset or find one that already provides for you. You can also use the default presets along with your own preset.

The fully customizable feature is referring to UnoCSS engine.

**Comment by social-uni** [comment]
What I want to ask is, in the default preset-uno
font-14 is
```
.font-14 { 
    font-weight: 14
}
```
I want him to be font-14
```
.font-14 { 
    font-size: 14px
}

Can I override him with rules?

**Comment by social-uni** [comment]
> 默认预设与现有框架兼容。如果要使用`font-14`，则需要编写自己的预设或找到已经为您提供的预设。您还可以将默认预设与您自己的预设一起使用。
> 
> 完全可定制的功能是指 UnoCSS 引擎。

is work

Sorry I didn't understand his rationale, so I thought I couldn't do it


```
Unocss({
      rules: [
        StylesUtil.generateReactiveCss([/^font-(\d+)(.+)?$/, match => ({'font-size': `${match[1] || 20}${match[2] || 'px'}`})]),
      ]
    }),
```

![image](https://user-images.githubusercontent.com/14007972/188052341-abde0f44-f601-421e-a03d-38c40eee0193.png)
