### ISSUE TITLE
How to override the core/utils/handler in preset, or modify default size unit handler？

### ISSUE THREAD

**Issue by social-uni** [unocss/unocss#1528]
unocss preset

```
p-{num} {
   padding: {num / 4}rem;
}
```
I want to change to

```
p-{num} {
   padding: {num}px;
}
```

The following are the relevant presets in unocss. Is there any external configuration that can rewrite or override them?

```
export function rem(str: string) {
  if (str.match(unitOnlyRE))
    return `1${str}`
  const match = str.match(numberWithUnitRE)
  if (!match)
    return
  const [, n, unit] = match
  const num = parseFloat(n)
  if (!Number.isNaN(num))
    return unit ? `${round(num)}${unit}` : `${round(num / 4)}rem`
}


export function px(str: string) {
  if (str.match(unitOnlyRE))
    return `1${str}`
  const match = str.match(numberWithUnitRE)
  if (!match)
    return
  const [, n, unit] = match
  const num = parseFloat(n)
  if (!Number.isNaN(num))
    return unit ? `${round(num)}${unit}` : `${round(num)}px`
}
```
Now the default size unit handler is rem, I want to change it to px, is there any relevant configuration to do this?

I want all the presets in unocss, only the default size unit preset I want to replace from rem to px, is there any way?

**Comment by SnowingFox** [comment]
```ts
export default defineConfig({
  rules: [
    [/p-[0-9]+/, ([a]) => {
        return { padding: `${a.replace('p-', '')}px` }
      }
    ],
  ],
})
```
if u have question about unocss not bug report or feature request, plase go [here](https://github.com/unocss/unocss/discussions) ask for help.

**Comment by chris-zhu** [comment]
You can check`postprocess` hook.

[Playground](https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIDuBaAjABnygAs9CoAjdAPgFcA7AexhWAHpwJqAoASCA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCCMMUwARgK4zDoCeZF1tAJIBjAlT6UaMAKpYIcAL5x0UCCDgByNnOFUqGgFABIVAA9IsFBgCGbADbw0mHPkLAiACgTG4cKPeoALjgAbRCNYTYqGDUAWn87VA0yJFE7aGCNSmQNRQBdPJIfOCoAC2gYSJgqYKQIqJiQWLKKqo1MmDMYWLsiOE7TbuhrLCJUOHKAN1QoQIHuzus7XIUio19%2BKRrQ4o3JWlkIDwBKNd89gXpGZnZOHhOz882hUSwqLxLhJdRggEYAOgATGRhMgsJlSowwDUAPQw6ggf5lGErU7FQrFSDRCgQYTUbYeDjAOzHOAAXgAfIhdnAiXZ-qgsExgNR-uhoABRazCUoeDzAUmU6nrc6%2BV7ROCTJZscZkuDAEK-PI03xcOAeKV2GVwABkOv63DAqAg6El0tlZLlGmizFGuT1cBhAD1YgB%2BEIAHX%2BHuQeQA1JQQAASGH-TrRDXm47HFXnBVK8lwAAGQYQfs1MqRdmAeI8AAYyLEAMykgBUcAALAowKYkzSFDGRatjA3jEA&options=N4XyA)

**Comment by social-uni** [comment]
> ```ts
> export default defineConfig({
>   rules: [
>     [/p-[0-9]+/, ([a]) => {
>         return { padding: `${a.replace('p-', '')}px` }
>       }
>     ],
>   ],
> })
> ```
> 
> 如果您对 unocss 的使用问题而不是错误报告或功能请求有疑问，请到[这里](https://github.com/unocss/unocss/discussions)寻求帮助。

Not only padding, margin, height, weight, top, left, etc., I want to change the default to px



> ```ts
> export default defineConfig({
>   rules: [
>     [/p-[0-9]+/, ([a]) => {
>         return { padding: `${a.replace('p-', '')}px` }
>       }
>     ],
>   ],
> })
> ```
> 
> if u have question about unocss in usage rather bug report or feature request, plase go [here](https://github.com/unocss/unocss/discussions) ask for help.

Not only padding, margin, height, weight, top, left, etc., I want to change the default to px

**Comment by social-uni** [comment]
> You can check [`postprocess`](https://github.com/unocss/unocss/blob/80f304becc2d2766188387fcf2bbd2281888c2a1/packages/core/src/types.ts#L364-L367) hook.
> 
> [Playground](https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIDuBaAjABnygAs9CoAjdAPgFcA7AexhWAHpwJqAoASCA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCCMMUwARgK4zDoCeZF1tAJIBjAlT6UaMAKpYIcAL5x0UCCDgByNnOFUqGgFABIVAA9IsFBgCGbADbw0mHPkLAiACgTG4cKPeoALjgAbRCNYTYqGDUAWn87VA0yJFE7aGCNSmQNRQBdPJIfOCoAC2gYSJgqYKQIqJiQWLKKqo1MmDMYWLsiOE7TbuhrLCJUOHKAN1QoQIHuzus7XIUio19%2BKRrQ4o3JWlkIDwBKNd89gXpGZnZOHhOz882hUSwqLxLhJdRggEYAOgATGRhMgsJlSowwDUAPQw6ggf5lGErU7FQrFSDRCgQYTUbYeDjAOzHOAAXgAfIhdnAiXZ-qgsExgNR-uhoABRazCUoeDzAUmU6nrc6%2BV7ROCTJZscZkuDAEK-PI03xcOAeKV2GVwABkOv63DAqAg6El0tlZLlGmizFGuT1cBhAD1YgB%2BEIAHX%2BHuQeQA1JQQAASGH-TrRDXm47HFXnBVK8lwAAGQYQfs1MqRdmAeI8AAYyLEAMykgBUcAALAowKYkzSFDGRatjA3jEA&options=N4XyA)

thank you
