### ISSUE TITLE
Allow removing safe listed classes from REPL

### ISSUE THREAD

**Issue by jd-solanki** [unocss/unocss#1530]
Hi 👋🏻

I am building component lib [anu](https://anu-vue.netlify.app/). I have a few safe listed classes and when I try to use REPL on `localhost:5173/__unocss`, I get all of the safe listed classes and can't figure out what my written code generated. Below is screenshot
![Screenshot 2022-09-03 at 12 10 16 AM](https://user-images.githubusercontent.com/47495003/188217454-64278a19-7894-4fd9-a854-c4162b379471.png)

Adding a checkbox to remove safe listed classes will be good.

**Comment by antfu** [comment]
PR welcome. We could probably not include safelist by default
