### ISSUE TITLE
How to use external css class in shortcuts？

### ISSUE THREAD

**Issue by social-uni** [unocss/unocss#1537]
i have a css class  .use-click 
it's

use.css
```
.use-click {
    cursor: pointer;
}

.use-click:hover {
    opacity: 0.9;
}

.use-click:focus {
    opacity: 0.9;
}

.use-click:active {
    opacity: 0.6;
}
```

i want use it in  shortcuts

vite.config.js
```
shortcuts: [
                [/^btn-(.*)$/, ([, c]) => `bg-${c} color-white py-10 px-20 bd-radius-20 use-click`],
            ]
```

it not work

Is it a problem with the way I use it, or does unocss not support external css classes?

**Comment by social-uni** [comment]
console tips : unmatched utility "use-click" in shortcut "btn-theme"

**Comment by chris-zhu** [comment]
Mixed use is not recommended. You can try to add outside class to `shortcuts `

[Playground](https://uno.antfu.me/play/?html=DwEwlgbgBARgLgOwHwCgpQKoIPYGEDK%2BKwA9OBEkA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6cRiJEk7AEgDWenmxUHTQiZB4MBhQcDUAbpPBEGCJABwADJoQsY2LK%2Bv2ErxzC0sArKvpkfocMLj9%2BhOWMIkA7lXAE3BtHV29ZqhqshECka4UuQMYyggPgAlLJhPJGCw2JweHx%2BDC4XJRDBJNI-JdUHQJPZUqEAIwAOgATJjUBI0Lg8lVWGBGgB6Nn0EAU6psv4tNSw8pIQVIIA&options=N4IgTgpgzgDg9gOygSwG4RALgC5gK4QA0IA7sgCbYAWWA7AKwBsAdAIyMDMAHIwJwBMrAAxd6XYlQjIA5lWx0h9Zr1qMALEP6NWa%2BkNa0AvkA)

**Comment by social-uni** [comment]
> Mixed use is not recommended. You can try to add outside class to `shortcuts `
> 
> [Playground](https://uno.antfu.me/play/?html=DwEwlgbgBARgLgOwHwCgpQKoIPYGEDK%2BKwA9OBEkA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6cRiJEk7AEgDWenmxUHTQiZB4MBhQcDUAbpPBEGCJABwADJoQsY2LK%2Bv2ErxzC0sArKvpkfocMLj9%2BhOWMIkA7lXAE3BtHV29ZqhqshECka4UuQMYyggPgAlLJhPJGCw2JweHx%2BDC4XJRDBJNI-JdUHQJPZUqEAIwAOgATJjUBI0Lg8lVWGBGgB6Nn0EAU6psv4tNSw8pIQVIIA&options=N4IgTgpgzgDg9gOygSwG4RALgC5gK4QA0IA7sgCbYAWWA7AKwBsAdAIyMDMAHIwJwBMrAAxd6XYlQjIA5lWx0h9Zr1qMALEP6NWa%2BkNa0AvkA)

External style classes are very numerous, I would be exhausted to write a rule for each style, can we support external style classes in the future? Is there any consideration for not supporting it? I was curious so I asked, thanks for your answer

**Comment by chu121su12** [comment]
By default, your `shortcut` is not supported because for what I understand you want the `btn-x` to add class `use-click`, which basically is a transformer behavior. Your option are:
- Remove `use-click` from the shortcut, and write a transformer to add the required classes (ex. `class="btn-x"` -> `class="btn-x use-click"`)
- Remove `use-click` from the shortcut, but use separate class `class="btn-x use-click"`, and add your custom css either via `<link>` or [preflight](https://github.com/unocss/unocss#preflight)
- Register `use-click` as [fully controlled rule](https://github.com/unocss/unocss#full-controlled-rules) so that `use-click` will be matched & applied with your existing shortcut of `[/^btn-(.*)$/, ([, c]) => bg-${c} ... use-click],`

**Comment by social-uni** [comment]
> 默认情况下，`shortcut`不支持您的，因为据我所知，您希望`btn-x`添加 class `use-click`，这基本上是一种转换器行为。您的选择是：
> 
> * 从快捷方式中删除`use-click`，并编写一个转换器来添加所需的类（例如`class="btn-x"`-> `class="btn-x use-click"`）
> * `use-click`从快捷方式中删除，但使用单独的 class ，`class="btn-x use-click"`并通过`<link>`或[preflight添加您的自定义 css](https://github.com/unocss/unocss#preflight)
> * 注册`use-click`为[完全受控的规则](https://github.com/unocss/unocss#full-controlled-rules)，以便`use-click`与您现有的快捷方式匹配并应用`[/^btn-(.*)$/, ([, c]) => bg-${c} ... use-click],`


The way you said can solve my problem, thank you,

But I think the use of css class in rule is a very common requirement, I hope to consider supporting it, I can't think of any valid reasons not to support it
