### ISSUE TITLE
Adding purgecss for vuetify on Nuxt3 breaks uno.

### ISSUE THREAD

**Issue by kstraszewski** [unocss/unocss#1538]
Hi I am using Uno css + vuetify on Nuxt3 project and everything works great. Unfortunately vuetify generate lots of unused CSS so I wanted to add purgecss by postcss. When I add this I'm getting this error:

```
[unocss] does not found CSS placeholder in the generated chunks                                                                                           16:06:14
This is likely an internal bug of unocss vite plugin

```

Removing ''@unocss/nuxt' from  nuxt.config modules fix this, and purger works great (70% reduce) but I do not want to remove uno from project :(

Reproduction:
1. Go to https://stackblitz.com/edit/github-w6cj1g?file=nuxt.config.ts
2. do `npm run build`

**Comment by kstraszewski** [comment]
Ok i got it. @antfu UnoCSS fire `unocss:global:build:generate` after postcss. When I've added purger to postcss to Nuxt3, purger purged all of uno placeholders. When I've added this to purger whitelist ` /--unocss--/g,` everything works great. It Would be great if uno build fired before postcss

**Comment by popdo** [comment]
> Ok i got workaround. @antfu UnoCSS fire `generateBundle()` after postcss. When I've added purger to postcss to Nuxt3, purger purged all of uno placeholders. When I've added this to purger whitelist ` /--unocss--/g,` everything works great. It Would be great if uno build fired before postcss.

How to whitelist unocss? Can I ask for some guidance?
