### ISSUE TITLE
Bug: VSCode extension freezes the editor until config (re)loaded

### ISSUE THREAD

**Issue by kidonng** [unocss/unocss#1540]
One thing particular strange is the load time. Does it really take that long?

Note: freezing also happens during the initial load, not just reloads.

OS: macOS (I can't replicate this behavior on Linux with GitHub Codespaces)
VSCode:  1.71.0
UnoCSS extension: v0.45.15

Vite config:

```js
import { defineConfig } from 'vite'
import unocss from 'unocss/vite'

export default defineConfig({
  // Must pass an option or else the extension won't load
  //               ↓
  plugins: [unocss({})]
})
```

Demo:

https://user-images.githubusercontent.com/44045911/188325991-cad5906f-572d-49ad-a5cb-2f264703b440.mov

**Comment by antfu** [comment]
Fix in unconfig@0.3.6. Meanwhile, it's recommended to use a separate `unocss.config.ts`
