### ISSUE TITLE
Bug: cannot reload VSCode extension unless it loads successfully

### ISSUE THREAD

**Issue by kidonng** [unocss/unocss#1541]
The `unocss.reload` command is only configured after the extension loads successfully, as it is guarded by multiple early returns:

https://github.com/unocss/unocss/blob/cceb4a95e4d6b2ca42e216b57641657f2908ccbd/packages/vscode/src/index.ts#L39-L43

This poses a serious usability problem: one cannot use it to reload after resolving a config issue that stopped the extension from loading.

OS: macOS
VSCode:  1.71.0
UnoCSS extension: v0.45.15

Demo:

https://user-images.githubusercontent.com/44045911/188326288-c3a14ffe-3d24-4111-ae1b-e79b849c4615.mov

**Comment by antfu** [comment]
I see. PR welcome to fix, thanks!
