### ISSUE TITLE
Way to import a default color from `preset-mini`?

### ISSUE THREAD

**Issue by devunt** [unocss/unocss#1543]
In tailwind[1] or windi[2], it is common to override default `gray` color to more specific variant of gray in order to keep the overall tone of website constant.

Unocss defines its default color palette in `preset-mini`, but I can't find a way to import a default color from there.

[1] https://tailwindcss.com/docs/customizing-colors#aliasing-color-names
[2] https://windicss.org/utilities/general/colors.html#reuse-colors

**Comment by chris-zhu** [comment]
Try to use `import { colors } from '@unocss/preset-mini'`

https://github.com/unocss/unocss/blob/cceb4a95e4d6b2ca42e216b57641657f2908ccbd/packages/preset-mini/package.json#L43-L46
