### ISSUE TITLE
@apply directives can't built properly in build & preview Nuxt 3

### ISSUE THREAD

**Issue by chrisnaadhi** [unocss/unocss#1545]
Heyo!
It's my first time to open an issue in unocss.
Directive @apply work flawlessly on dev mode, but seems like the generated build on Nuxt 3 doesn't built properly with @apply directive.
**Dev Mode** : 
![dev time work](https://user-images.githubusercontent.com/29543851/188409619-66601e2b-1ce1-4085-ad3c-84f4ba56b51c.png)

**Built & Preview** : 
![build time bug](https://user-images.githubusercontent.com/29543851/188409082-966a9fe5-2ccb-4856-80a5-25201c163e21.png)

While using --at-apply work flawlessly as intended on dev mode & built mode.

**Reproduction** : 
~Install Nuxt 3 with UnoCSS module then use `@apply` directive and built it with `npm run build`~
made a repro : https://stackblitz.com/github/chrisnaadhi/apply-uno-repro

**Comment by cinob** [comment]
same question

**Comment by nguyenvuhoangbt** [comment]
@chrisnaadhi have you fixed it ? I ran into this problem on my site. If you manage to fix it, can you share with me ?

**Comment by chrisnaadhi** [comment]
> @chrisnaadhi have you fixed it ? I ran into this problem on my site. If you manage to fix it, can you share with me ?

@nguyenvuhoangbt i'm able to fix it to change the `@apply` to `--at-apply`
example :
`@apply bg-red-300 text-center;`
change to
`--at-apply: bg-red-300 text-center;`

**Comment by nguyenvuhoangbt** [comment]
@chrisnaadhi It works for me. Thank you so much

**Comment by sibbng** [comment]
This is fixed in [v0.47.3](https://github.com/unocss/unocss/commit/d0c3d4b30820e43951d6c7697366017dec6d5ee1)

Related PR: #1930
