### ISSUE TITLE
VSCode extension broken in last update

### ISSUE THREAD

**Issue by joseehilton147** [unocss/unocss#1550]
UnoCSS VSCode extension version: 0.45.15 isnt working:
![image](https://user-images.githubusercontent.com/53986027/188513734-61e1306d-fbb7-4a33-bb03-2097693fd554.png)
![image](https://user-images.githubusercontent.com/53986027/188513746-2a970c92-0448-4b04-a27d-38b079b8fd91.png)

ive downgraded to 0.45.14 and works fine:
![image](https://user-images.githubusercontent.com/53986027/188513670-e0089a72-2a8b-4dc9-9661-d0b27185f88f.png)
![image](https://user-images.githubusercontent.com/53986027/188513771-19e76384-096c-43f6-bb4d-8ce79c4256fd.png)

cant reproduce that in any place so dont close this issue or tell me how to reproduce that for you in any place because isnt a code error, is a extension bug

**Comment by azaleta** [comment]
compare release note between 2 versions and I don't see any plugin-related patch.
https://github.com/unocss/unocss/releases/tag/v0.45.15

And it works fine. 
don't you get any log/output?
![1](https://user-images.githubusercontent.com/22554452/188529914-d25e010b-cc6d-466d-97fb-dded2b186b5f.png)

**Comment by joseehilton147** [comment]
tried again with latest version of extension and is working again

![image](https://user-images.githubusercontent.com/53986027/190008229-8dfa8392-bc6c-46da-85a6-b56a47d7e046.png)
