### ISSUE TITLE
Nuxt3使用unocss时，flex布局问题

### ISSUE THREAD

**Issue by canrili** [unocss/unocss#1551]
div使用flex布局，div的子元素会自动生成flex：1 1 auto

**Comment by antfu** [comment]
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)
