### ISSUE TITLE
VSCode extension autocomplete not working in .vue but work in .tsx

### ISSUE THREAD

**Issue by 3kinglee** [unocss/unocss#1553]
## when i use unocss in vue, it worked, but  autocomplete didn't work in .vue file

https://user-images.githubusercontent.com/14836590/188540533-5aee3643-b8fb-468b-b622-b02e55402dbf.mov

## but  autocomplete work  in .tsx file

https://user-images.githubusercontent.com/14836590/188540787-1118a1c8-9b4e-4d1b-94e7-8cd7ee9c3ae7.mov

i use vite to create the demo

**Comment by dylan237** [comment]
I got similar situation, It used to work fine with my tsx file, but now it's not.
I'm using Vite 2.9.12 and vscode extension 0.45.18.

**Comment by lainbo** [comment]
I had a similar problem. After 0.45.13, there were some problems with the VSCode extension. using `@apply` or `-at-apply`  in the `.vue` file can cause the extension to fail completely in this file

**Comment by lainbo** [comment]
> ### **`unocss extension`‘s autocomplete is almost unavailable.**
> I recommend you to install a `windicss intelliSense` to help `unocss` autocomplete. ![image](https://user-images.githubusercontent.com/21095710/189308724-c04f5856-bacd-4eb0-98dc-2cd494901259.png) I use both all them a few month. Very efficient!

How do you use windicss extension in unocss projects? Need to create a `windicss.config.ts` in the project ?

**Comment by samydoesit** [comment]
VsCode Extension doesn't work at all in my case.

[Repro](https://github.com/samydoesit/vue-turbo-starter)
`pnpm i` and open vscode try to edit some classes. No autocomplete or syntax highlighting.

The Debug Output from UnoCSS is correctly detecting my config.

**Comment by loosheng** [comment]
Unfortunately, after my investigation, this may be caused by volar, if volar is disabled, unocss's autocomplete is working.
![volar](https://user-images.githubusercontent.com/30114549/204076680-acfa2f80-2c01-49ad-877f-eee0ea9c4217.gif)

**Comment by loosheng** [comment]
link https://github.com/johnsoncodehk/volar/issues/2146

**Comment by AisonSu** [comment]
Same situation as mine

**Comment by AisonSu** [comment]
I wonder why tailwind and windi extensions works normally and unocss couldn't, Maybe it is not caused by volar?

**Comment by AisonSu** [comment]
Everone who really need the autocomplete, you can trigger IntelliSense manually by typing Ctrl+Space behind the key word(like w-, bg- )，and i am trying to find out why the trigger key doesn't work correctly

**Comment by kaname-png** [comment]
Same problem here with nuxt 3, vue 3 and volar extension.

**Comment by Gahotx** [comment]
I have the same problem https://github.com/unocss/unocss/discussions/1500

**Comment by bennymi** [comment]
I have the same problem that autocomplete isn't working for rules and shortcuts in my Svelte files.

**Comment by ikxin** [comment]
I also encountered this issue, which can be used normally in HTML files, but cannot be used in Vue files

**Comment by ItsRyanWu** [comment]
Same issue here

**Comment by serkodev** [comment]
After a little bit dive in, I think the main problem is Volar defines a custom word definition including `-` so it makes UnoCSS's extension cannot trigger the auto suggestion by `-` symbol  ([source](https://github.com/microsoft/vscode/issues/171349#issuecomment-1383651001)). As currently it can successfully trigger suggestion by `:` (try to type `hover:`).

One of the solution is UnoCSS add support's for more trigger symbol like `space`, `"` or `'` and able to start suggestion when typing nothing (just like WindiCSS).

**Comment by serkodev** [comment]
I just add supports for more trigger symbol and some optimization to make sure only suggest inside attribute value string area. If maintainer agree this is a good direction, I can make a PR with test case to makes it ready for production. 😀

Source
https://github.com/serkodev/unocss/tree/feat/add-vscode-delimiters

### Preview
https://github.com/unocss/unocss/assets/44749100/24bceaca-d4f6-49de-b6ac-4d2d209bebbc

**Comment by zouhangwithsweet** [comment]
> Although I can't fix for the `-` trigger symbol problem, I just add supports for more trigger symbol and some optimization to make sure only suggest inside attribute value string area. If maintainer agree this is a good direction, I can make a PR with test case to makes it ready for production. 😀
> 
> Source https://github.com/serkodev/unocss/tree/feat/add-vscode-delimiters
> 
> ### Preview
>  delimiters.mov

need it!

**Comment by rdzhaoxin** [comment]
"Vue Language Features (Volar)" is a ghost, disable "Vue Language Features (Volar)", Intellisense can work normally
