### ISSUE TITLE
how do i use static image in background-image?

### ISSUE THREAD

**Issue by lwwing** [unocss/unocss#1557]
I tried to write a rule, but why it does not work?

`class="bg-url(http://localhost:12580/src/assets/images/recharge/bg.png)"`.

rule
`
  [
    /^bg-url\((.+)\)$/,
    ([
      ,
      d1,
    ]) => ({ 'background-image': `${d1}`, }),
  ],
`

**Comment by chris-zhu** [comment]
Try existing rules. `bg-[url(http://localhost:12580/src/assets/images/recharge/bg.png)]`

**Comment by qxdmmc** [comment]
`
[/^bg-url\((.+)\)$/, ([ , d1, ]) => ({ 'background-image': `url(${d1})`})]
`
because of missing 'url()'.
