### ISSUE TITLE
Feature: automatically applied `border` utility when adding a color utility like `border-graylight`

### ISSUE THREAD

**Issue by UltraCakeBakery** [unocss/unocss#1560]
I often find myself having styling like this `<div class="border border-light-400">` in my codebase. I'm getting a bit tired of adding the `border` utility first.

Can one of UnoCSS's presets automatically add the `border` utility when I only specify `<div class="border-light-400">`?

A bit like how the `transform` utility works now.

**Comment by SnowingFox** [comment]
```ts
Unocss({
    preset: [...],
    postprocess: (util) => {
        if (/^\.border-(.*)$/.test(util.selector)) {
        	util.entries.push(...[
            	['border-width', '1px'],
              	['border-style', 'solid']
            ])
        }
    },
})
```

**Comment by UltraCakeBakery** [comment]
Got it, but I rather have it in unocss's presets themselves, so I don't have to add this custom config in every project.

**Comment by antfu** [comment]
The reason is that it could have other combinations like `border-b border-red` which would only make the red border on the bottom.

**Comment by UltraCakeBakery** [comment]
> The reason is that it could have other combinations like `border-b border-red` which would only make the red border on the bottom.

Ahh... I didn't think about that scenario 🤦🏻‍♂️.

Is there a way already to specify what class should be generated first?

 If so...

###### Possible Solution
1. Generate border color utility CSS _before_ the border width / direction utilities
2. Change the border width / direction utilities their generated CSS to use a full 4 value `border-width` instead:

```css
.border-lightgray {
  border-color: lightgray;
  border-style: solid;
  border-width: 1px;
}

.border-b {
  border-width: 0px 0px 1px 0px;
}
```

**Comment by antfu** [comment]
They are basically trade-offs, your solution will still not make `border-t border-b border-red` work - this is how Tailwind decided to, and we are just aligning with it. You could try to provide your own custom rule for your need.
