### ISSUE TITLE
@unocss/runtime can't prevent default execution

### ISSUE THREAD

**Issue by jd-solanki** [unocss/unocss#1562]
Hi 👋🏻

I am trying UnoCSS runtime to only load the icons I get via API response.

Finally, everything is working except [ready](https://github.com/unocss/unocss/blob/main/packages/runtime/src/index.ts#L22). As per the description of ready function if we return the false in config it should stop the default execution (the first one).

However, it parses the content of body and extracts the icons without need. _(I am already using Uno and its various presets including preset icon which generates known icons styles)_

I inspected the code and found that there's something wrong [here](https://github.com/unocss/unocss/blob/main/packages/runtime/src/index.ts#L246).

IG it should take the user config `if (inlineConfig?.ready?.(unoCssRuntime) !== false)`. I haven't create PR because there is also `window.__unocss` involved.

Moreover, to stop the initial execution according to current code, I had to write config like below:
```ts
import presetIcons from '@unocss/preset-icons/browser';
import initUnocssRuntime from '@unocss/runtime';

// - To stop initial execution, I had to passready via window.__unocss
window.__unocss = {
  runtime: {
    ready: function() { return false }
  },
}

initUnocssRuntime({
  defaults: {
    presets: [
      presetIcons({
          cdn: 'https://esm.sh/'
      })
    ]
  },
  // This isn't working
  ready(runtime) {
      return false
  },
})
```

passing `ready` function to `window.__unocss` does the trick for now.

Here's the reproduction repo: https://github.com/jd-solanki/unocss-runtime-preset-icons

Regards.

**Comment by jd-solanki** [comment]
Hi @chu121su12 

Sorry for the ping but I am curious why you closed the PR? Was that incorrect?

**Comment by chu121su12** [comment]
I'm sorry I must have deleted the branch accidentaly. It is reopened now.
