### ISSUE TITLE
Please add option to configure backgrounds like in windi.css :pray: 

### ISSUE THREAD

**Issue by kamilbedalaboratorium** [unocss/unocss#1564]
![image](https://user-images.githubusercontent.com/69455435/188891042-08962143-abae-4fb2-b2dc-98a239a379ab.png)

https://windicss.org/utilities/backgrounds/gradients.html#gradient-direction

**Comment by chris-zhu** [comment]
Refer to [background image](https://uno.antfu.me/?s=bg-[url(http://xxx.xxx.png)])
Another way is use shortcuts.

**Comment by kamilbedalaboratorium** [comment]
I have a gradient which is used all over my website:
```
background-image: linear-gradient(225deg, #3B1AA7 0%, #4E31B3 30.49%, #9636EF 64.35%, #F682BD 100%);
```
It's crazy and definitely not DRY to use it like this `bg-[linear-gradient(225deg, #3B1AA7 0%, #4E31B3 30.49%, #9636EF 64.35%, #F682BD 100%)]` and shortcuts feature doesn't help in any way to abstract it away to something like bg-customGradient

**Comment by kamilbedalaboratorium** [comment]
`bg-[linear-gradient(225deg, #3B1AA7 0%, #4E31B3 30.49%, #9636EF 64.35%, #F682BD 100%)]` does not work

**Comment by chris-zhu** [comment]
Check the [Playground](https://uno.antfu.me/play/?html=DwEwlgbgUABDDuBaAjABlbGALF7MGMAbAQwGdSBeAIgCMBzROgJ2PAFMA7AF0ULA7bEmMUlmIAHNogDaaVCDZ0AujHqMW7bogBmTAPYBbREzYhVDZqzCceEMMUR6WHOm3PqrNxFz2IahAFc2KigAPkwACTZCQj0AGgQnQhAAQihgAHpwCHDQSEwkOUwcIrhRCTZqaQAmaoBWBWUQuDVLTS5qPgEhGF1DY1MYOwcnYhc3Hz9A4LDI6NiE%2BCTU9KzIcKA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUkNikEA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g)

**Comment by kamilbedalaboratorium** [comment]
Thank you for your answers. I really appreciate it! Using utils that you've showcased in the playground I could ALMOST achieve the gradient I need. But I cannot set exact percentage steps so it doesn't work for me... I need it to look exactly like at the design I have.
I still believe that uno.css is missing essential feature of creating shortcuts for your complex backgrounds like the gradient I need. 
I'd love to add this feature myself but I'm not sure where to start.

**Comment by chris-zhu** [comment]
[Playground](https://uno.antfu.me/play/?html=DwEwlgbgUABDDuBaAjABlbGALF7MGMAbAQwGdSBeAIgCMBzROgJ2PAFMA7AF0ULA7bEmiANoAKAEwSArCDZ0ANAH0AxAGYAQsgCC2gOxLUAUmUqALAFE1yDWqVrUAOjMBOE6pcA2NZ4sAxJU8zRzVpdxU-TwAOCQ0AESU0YwBKAF0qKAA%2BTAAJNkJCAHsFBEKmQhAAQihgAHpwCGyoIA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCCMMUwARgK4zDoCeZF1tAJIBjAlT6UaMAKpYIcAL5x0UCCDgByNnOFUqGgFChIsRHAAWAQyzIANqiiLlq9RoAC2iLqoB6flIBaEGxgHw5gW30DA1QADxN4NHRLNltEjGw8AmIACgQDODgoVOoALjgAbQLCyo1hNioYNQDi%2Bw0yJFFbaHKNSmQNRQBdEmrCqpqanwA9FiIAoihLZGBULBgAnIB%2BUsowVEtOLHmASi3bTMsoTYA6AGoTgBIfUcnCnIqyKiGTuABeAB8cDyYzeGhYlmEAGtFhBtMgAqBLERUBpygADC44K4LJYrNYwR4IKw2exQG4sJbQ2g5KgnBTo15vBQnJmFEbVDmFKjmaAweowKjlfKTOoNJogAI8vkCtGaGBxDa2IhwBWxDbQawoiwQABuDlKao2Csstna1QUTP8tCFlVB1pkchyrPtkloDCYrHCPGdbPIbpgIjEILecCowlNqHKAEYbgAmP2FYTILC9cyMMBCnw%2BaggG48nzmyYspkclkGIA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g)

**Comment by kamilbedalaboratorium** [comment]
This is the solution. Thank you!
Unfortunately it doesn't work in my environment ;(
I'm using latest uno.css version with vite and vue and it seems like I'm missing something...
Maybe I need some other preset?
Other utils work as expected :confused: 

Here are my presets and transformers:
```
presets: [
    presetUno(),
    presetAttributify(),
    presetIcons({
      scale: 1.2,
      warn: true,
    }),
    presetTypography(),
  ],
  transformers: [
    transformerDirectives(),
    transformerVariantGroup(),
  ],
```

**Comment by kamilbedalaboratorium** [comment]
Never mind! I've found config tab in the playground and I see the custom rule you've added. 
Thank you for your help!

**Comment by kamilbedalaboratorium** [comment]
Now I can use a shortcut like this:
```
 rules: [
    [
      /^bg-gradient-(?:repeating-)?linear-(.+)$/,
      ([, s]) => ({
        'background-image': `linear-gradient${handler.bracket(s)}`,
      }),
    ],
  ],
  shortcuts: [
    ['bg-purple-gradient', 'bg-gradient-linear-[(225deg,_#3B1AA7_0%,_#4E31B3_30.49%,_#9636EF_64.35%,_#F682BD_100%)]']
  ],
```
:fire:
