### ISSUE TITLE
BUG：第一次进入项目时，部分样式并不生效，刷新页面才全部样式生效

### ISSUE THREAD

**Issue by LeslieLiangLiang** [unocss/unocss#1565]

**Comment by sudongyuer** [comment]
能提供最小复现么？

**Comment by LeslieLiangLiang** [comment]
![image](https://user-images.githubusercontent.com/48022893/189025088-0c84b08b-560f-4d72-985b-ec7d98ff246f.png)
上图是在第一次跑起项目，第一次打开页面时，点击菜单跳转至该路由，部分样式不生效的截图。这个元素只有.italic生效了。
重新刷新页面后，样式正常了，如下图。关闭页面后重新打开，样式也是正常的。
![image](https://user-images.githubusercontent.com/48022893/189025293-25b75c40-0112-4fa8-9ca3-ff83a2a9bb4a.png)

我的vite是2.1.5版本，unocss是0.45.13版本。希望大佬可以帮忙定位下问题，谢谢！
> 能提供最小复现么？

**Comment by sudongyuer** [comment]
> 
我感觉像 vite的问题，你尝试升级一下vite试试呢

**Comment by LeslieLiangLiang** [comment]
> 

我升级vite到2.9或3.1也还是不行，初始化时样式还是部分不生效。会不会是跟我写的类名是参考tailwindcss的有关？

> > 
> 
> 我感觉像 vite的问题，你尝试升级一下vite试试呢

**Comment by pany-ang** [comment]
这个项目的开发环境，能直接复现这个问题 https://github.com/un-pany/v3-admin-vite

**Comment by LeslieLiangLiang** [comment]
> 这个项目的开发环境，能直接复现这个问题 https://github.com/un-pany/v3-admin-vite

打包后还会存在这个问题吗？

**Comment by pany-ang** [comment]
> > 这个项目的开发环境，能直接复现这个问题 https://github.com/un-pany/v3-admin-vite
> 
> 打包后还会存在这个问题吗？

暂时没发现打包后有任务问题

**Comment by lainbo** [comment]
I also have this problem, the difference is that my projects tend to happen after `pnpm i`

**Comment by harrytran998** [comment]
I have the same problem with NextJs project 😆 - Hope that can fix

**Comment by sudongyuer** [comment]
> I have the same problem with NextJs project 😆 - Hope that can fix

vite project？

**Comment by yuguaa** [comment]
在vue2项目中同样出现了

**Comment by Jiang1996** [comment]
webpack的vue2项目中遇到了类似问题，首次加载unocss样式不生效，修改了unocss样式之后热重载样式才出来，有类似问题的解决方法或者思路吗

**Comment by harwinvoid** [comment]
是不是用了啥多线程编译的插件？

**Comment by YuFengjie97** [comment]
我也遇到了，刷新一下就好了。难道unocss的类样式是异步编译的？

**Comment by yuguaa** [comment]
> 我也遇到了，刷新一下就好了。难道unocss的类样式是异步编译的？

我投向了tailwindcss

**Comment by Simon-He95** [comment]
能提供一下复现的最小demo吗

**Comment by syn-666** [comment]
修复了吗? 怎么修复的, 我也出现这个问题了

**Comment by Simon-He95** [comment]
> 修复了吗? 怎么修复的, 我也出现这个问题了

还没有人提供最小化demo哦😃

**Comment by syn-666** [comment]
在项目中使用了自定义的插件去导入virtual:unocss

插件:
export default function AutoGlobalImport(imports) {
  const importStr = imports.map((pkg) => {
    return `import '${pkg}';\n`;
  }).join('');
  return {
    name: 'vite-plugin-global-import',
    transform(code, id) {
      if (id.endsWith('main.ts')) {
        return {
          code: `${importStr}${code}`,
          map: null
        };
      }
      return null;
    }
  };
}

vite.config.ts中:
plugins: [
    AutoGlobalImport(['virtual:uno.css']),
]
这样子会出现这个问题, 直接在main.ts导入unocss不会出现问题

**Comment by ArealRJ** [comment]
我也碰到了，我是首次加载不生效，必须修改不生效的.vue文件后，再刷新才会生效
```json
// package.json
{
  "devDependencies":{
     "@unocss/transformer-directives": "^0.62.2",
     "@unocss/webpack": "^0.46.5",
     "unocss": "^0.46.5",
     "@vue/cli-service": "~4.5.14",
  }
}
```
```js
// unocss.config.js
const { defineConfig, presetUno,transformerVariantGroup } = require("unocss")
const transformerDirectives  =require('@unocss/transformer-directives')

export default defineConfig({
  presets: [
    presetUno(),
  ],
  transformers: [
    transformerVariantGroup()
  ],
  },
})
```
```js
// vue.config.js
const UnoCSS = require("@unocss/webpack").default;
module.exports = {
// ...
  configureWebpack: (config) => {
   return {
   plugins:[UnoCSS()]
 }
},
 css: {
    extract:{
      filename: "[name].[hash:9].css",
      ignoreOrder: true
    },
}'
```
```ts
// main.ts
import 'virtual:uno.css';
```

**Comment by ArealRJ** [comment]
> 我也碰到了，我是首次加载不生效，必须修改不生效的.vue文件后，再刷新才会生效
> 
> ```json
> // package.json
> {
>   "devDependencies":{
>      "@unocss/transformer-directives": "^0.62.2",
>      "@unocss/webpack": "^0.46.5",
>      "unocss": "^0.46.5",
>      "@vue/cli-service": "~4.5.14",
>   }
> }
> ```
> 
> ```js
> // unocss.config.js
> const { defineConfig, presetUno,transformerVariantGroup } = require("unocss")
> const transformerDirectives  =require('@unocss/transformer-directives')
> 
> export default defineConfig({
>   presets: [
>     presetUno(),
>   ],
>   transformers: [
>     transformerVariantGroup()
>   ],
>   },
> })
> ```
> 
> ```js
> // vue.config.js
> const UnoCSS = require("@unocss/webpack").default;
> module.exports = {
> // ...
>   configureWebpack: (config) => {
>    return {
>    plugins:[UnoCSS()]
>  }
> },
>  css: {
>     extract:{
>       filename: "[name].[hash:9].css",
>       ignoreOrder: true
>     },
> }'
> ```
> 
> ```ts
> // main.ts
> import 'virtual:uno.css';
> ```

[https://github.com/unocss/unocss/issues/1455](url)
目前发现是这个导致的，使用了**"@unocss/webpack": "^0.45.8"**之后的版本，就会出现这个问题，切换到0.45.8之后问题消失了

**Comment by ArealRJ** [comment]
> webpack的vue2项目中遇到了类似问题，首次加载unocss样式不生效，修改了unocss样式之后热重载样式才出来，有类似问题的解决方法或者思路吗

我也碰到了，必须修改完样式再重新刷新才会生效，而且只有修改的这个页面的样式生效，请问后面解决了吗

**Comment by J-co1e** [comment]
// vue.config.js
import UnoCSS from 'unocss/webpack'
module.exports = {
  configureWebpack: {
    plugins: [UnoCSS({})]
  }
}
已解决，上面是我之前的代码，用的是vue-cli webpack的，改成下面的就可以了，感觉是有用缓存的原因
const process = require('node:process')
module.exports = function () {
  return import('@unocss/webpack').then(({ default: UnoCSS }) => ({
    configureWebpack: {
      devtool: 'inline-source-map',
      plugins: [UnoCSS()],
      optimization: {
        realContentHash: true
      }
    },
    chainWebpack(config) {
      config.module.rule('vue').uses.delete('cache-loader')
      config.module.rule('tsx').uses.delete('cache-loader')
      config.merge({
        cache: false
      })
    },
    css: {
      extract:
        process.env.NODE_ENV === 'development'
          ? {
              filename: 'css/[name].css',
              chunkFilename: 'css/[name].css'
            }
          : true
    }
  }))
}
