### ISSUE TITLE
IDEA & Webstorm Eslint ^8.23.0 error

### ISSUE THREAD

**Issue by sudongyuer** [unocss/unocss#1566]
<img width="1387" alt="image" src="https://user-images.githubusercontent.com/76603360/188917581-47054388-6877-4b1b-84ed-596f4b6f06ba.png">

## References
stackoverflow: https://stackoverflow.com/questions/73509984/eslint-typeerror-this-liboptions-parse-is-not-a-function

Eslint: https://github.com/eslint/eslint/issues/16250

jetbrains: https://youtrack.jetbrains.com/issue/WEB-57089/ESLint823-TypeError-thislibOptionsparse-is-not-a-function

**Comment by gaojiangtao-git** [comment]
这个问题  webstorm  问题,解决方案:1.降级eslint  版本即可 8.21, 2.webstorm  下一个版本更新

**Comment by userquin** [comment]
@sudongyuer use the lint and lint-fix scripts from root (`pnpm run lint` or `pnpm run lint-fix`)
