### ISSUE TITLE
Using `transformerDirectives()` breaks style suggestions & underline in <style>

### ISSUE THREAD

**Issue by rogi27** [unocss/unocss#1570]
I noticed that using `transformerDirectives()` breaks Visual Studio UnoCSS extension in my Nuxt 3 project.
You can reproduce it by simply using `Nuxt 3.0.0-rc9` and use CSS or SCSS in `<style>` block and adding `transformerDirectives()` in transformers option for `@unocss/nuxt`.

Before adding transformer option:
![image](https://user-images.githubusercontent.com/10144091/188957442-164cffbc-ebc7-4b0f-8018-b9e061c709f6.png)
After:
![image](https://user-images.githubusercontent.com/10144091/188957337-4e40cf95-f36d-461a-a439-980d5e1049dd.png)

**Comment by rogi27** [comment]
@antfu Is there any way to fix this? Or this is problem on extension side?

**Comment by JuerGenie** [comment]
so am i...

**Comment by JuerGenie** [comment]
> @antfu Is there any way to fix this? Or this is problem on extension side?

@rogi27 ,
My solution for this problem is create a `unocss.config.ts`, and put `transformerDirectives` to `vite-plugin-unocss`'s `transformer`, like this:

```typescript
// unocss.config.ts
import {
  defineConfig,
  presetUno,
  presetIcons,
  presetAttributify,
  transformerVariantGroup,
} from "unocss";

export default defineConfig({
  presets: [presetAttributify(), presetUno(), presetIcons()],
  transformers: [transformerVariantGroup()],
});
```
```typescript
import { defineConfig } from "vite";
import solidPlugin from "vite-plugin-solid";
import UnocssPlugin from "@unocss/vite";
import transformerDirectives from "@unocss/transformer-directives";

export default defineConfig({
  plugins: [
    solidPlugin(),
    UnocssPlugin({
      transformers: [transformerDirectives()],
    }),
  ],
  build: {
    target: "esnext",
  },
});
```

its working, cause extension will ignore the config in `vite.config.ts`.
