### ISSUE TITLE
@dark doesn't work with variant groups

### ISSUE THREAD

**Issue by FireMasterK** [unocss/unocss#1571]
Example:
```
.auto {
    @apply @dark:(text-white bg-dark-900);
}
```
I think this is a bug as it works with other things such as `hover:`, and it worked in windicss too.

Version: 0.45.18

**Comment by cpreston321** [comment]
@FireMasterK this works as I use it in my current project [here](https://github.com/cpreston321/christianpreston.com/blob/991affd5c1afb1b8bada4569886d432af5c71148/components/BgWrapper.vue#L24)

```
.auto {
    @apply dark:(text-white bg-dark-900);
}```

**Comment by FireMasterK** [comment]
> @FireMasterK this works as I use it in my current project [here](https://github.com/cpreston321/christianpreston.com/blob/991affd5c1afb1b8bada4569886d432af5c71148/components/BgWrapper.vue#L24)
> 
> ```
> .auto {
>     @apply dark:(text-white bg-dark-900);
> }
> ```
> 
> The two @ will throw off the parser. Just need the one for `@apply`

But, this doesn't use the media query, does it?

**Comment by cpreston321** [comment]
In my project example the `dark` class gets added to my body. Then the css will be generated like so

```css
.dark .text-white {
  text-color: "#FFF";
 }
 ```

but you are correct it does not use the media query.

**Comment by cpreston321** [comment]
<img width="719" alt="image" src="https://user-images.githubusercontent.com/6619884/189488464-57d2b429-70bd-4a20-bead-27cf3f8aa07f.png">

**Comment by Flower-F** [comment]
Did you mean that you want the `@dark` media query support in unocss? After searching in the google for a long time, I  think that the windicss has removed this feature now. Could you please give an example of windicss that uses this feature?

**Comment by FireMasterK** [comment]
Yes, in windicss, I had `darkMode: "media",` in the config, which allowed the regular `dark:` to act as a media query.

**Comment by Flower-F** [comment]
> Yes, in windicss, I had `darkMode: "media",` in the config, which allowed the regular `dark:` to act as a media query.
> 
> Unocss has support for the media query, but it doesn't work as a variant group. For example this works: `@dark:text-white @dark:bg-dark-900`

But I think the grammar should be still `dark:` instead of `@dark:`, right?

**Comment by FireMasterK** [comment]
> But I think the grammar should be still `dark:` instead of `@dark:`, right? See in https://windicss.org/features/dark-mode.html#media-query-mode

Yes, that's right in windicss. Unocss doesn't have such an option. (I couldn't find anything)

**Comment by Flower-F** [comment]
> > But I think the grammar should be still `dark:` instead of `@dark:`, right? See in https://windicss.org/features/dark-mode.html#media-query-mode
> 
> Yes, that's right in windicss. Unocss doesn't have such an option. (I couldn't find anything)

Yes, the unocss doesn't provide the configuration of it.

**Comment by Flower-F** [comment]
> > > But I think the grammar should be still `dark:` instead of `@dark:`, right? See in https://windicss.org/features/dark-mode.html#media-query-mode
> > 
> > 
> > Yes, that's right in windicss. Unocss doesn't have such an option. (I couldn't find anything)
> 
> Yes, the unocss doesn't provide the configuration of it.

Sorry, my bad. I found the config options [here](https://github.com/unocss/unocss/tree/main/packages/preset-mini#dark-mode). And I think that it can meet your needs.

**Comment by FireMasterK** [comment]
> > Yes, the unocss doesn't provide the configuration of it.
> 
> Sorry, my bad. I found the config options [here](https://github.com/unocss/unocss/tree/main/packages/preset-mini#dark-mode). And I think that it can meet your needs.

That's perfect, it works great, thank you!

Should I keep this issue open or close it? I'm not sure since it technically is a bug, but this is a workaround.

**Comment by Flower-F** [comment]
> Should I keep this issue open or close it? I'm not sure since it technically is a bug, but this is a workaround.

Haha, I think it depends on you. If you strongly need the `transformer-directives` support of `@dark`, you can keep it open and change the title, or your can close it.

**Comment by FireMasterK** [comment]
Well, I don't need it since this is enough for me, only though about it to keep things consistent. Closing, thanks 👍
