### ISSUE TITLE
The custom methods in `unocss.config.ts` in mac computer

### ISSUE THREAD

**Issue by wulinsheng123** [unocss/unocss#1574]
![image](https://user-images.githubusercontent.com/27261522/189097417-7e84f020-c373-4bea-b9c4-5fbc525d0535.png)
![image](https://user-images.githubusercontent.com/27261522/189097452-6f8280c3-9bd9-4306-ba6b-72e9847f27ac.png)
![image](https://user-images.githubusercontent.com/27261522/189097513-1fa5161a-97fa-438c-a20e-a444c00656a0.png)

![image](https://user-images.githubusercontent.com/27261522/189097861-b1945c30-7a19-4d8c-bd20-fd46e4deb97c.png)
![image](https://user-images.githubusercontent.com/27261522/189097935-0dd25a1c-1cdb-452e-9638-972121fb723c.png)

I installed two plugins, and there was a root directory in this project.
It can't IntelliSense when I type a predefined class name where there are in **unocss.config.ts**
It's weird, the same project in different OS(windows and mac ), the window computer run well.
only  my mac computer had trouble

**Comment by azaleta** [comment]
what's the vscode output of unocss?Did your config be loaded?
![image](https://user-images.githubusercontent.com/22554452/189132689-bc358b9c-12d0-461a-84ed-cf296ede088c.png)

**Comment by azaleta** [comment]
what's the vscode output of unocss?Did your config be loaded?
![image](https://user-images.githubusercontent.com/22554452/189132689-bc358b9c-12d0-461a-84ed-cf296ede088c.png)

**Comment by wulinsheng123** [comment]
https://github.com/unocss/unocss/issues/1574#issuecomment-1240710685
I haven't found this plugin。
