### ISSUE TITLE
Nuxt 3 Edge Channel - Broke Build for unocss.

### ISSUE THREAD

**Issue by cpreston321** [unocss/unocss#1580]
# CONTEXT 
I was working on a project and came across this on the edge channel. I saw that they updated this in the draft of RC 10 of Nuxt. 

[Nuxt SSR Styles inline](https://github.com/nuxt/framework/pull/7344/files) This could be potentially the culprit that broke the `build` / `generate`. 

I just wanted to give you a heads up as I was diving deeper into the issue as it was not present until I tested it on the edge channel. 

package.json
```json
{
  "private": true,
  "scripts": {
    "postinstall": "yarn generate",
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview"
  },
  "devDependencies": {
    "@iconify-json/akar-icons": "^1.1.8",
    "@iconify-json/ant-design": "^1.1.3",
    "@iconify-json/eva": "^1.1.2",
    "@iconify-json/ic": "^1.1.9",
    "@iconify-json/mdi": "^1.1.31",
    "@iconify-json/charm": "^1.1.5",
    "@iconify-json/codicon": "^1.1.16",
    "@iconify-json/ci": "^1.1.2",
    "@nuxt/content": "^2.1.0",
    "@vueuse/motion": "^2.0.0-beta.12",
    "@vueuse/nuxt": "^9.2.0",
    "@unocss/nuxt": "^0.45.18",
    "nuxt": "npm:nuxt3@latest",
    "nuxt-schema-org": "^1.1.0-beta.2"
  }
}
```

## ERROR

```bash 
ℹ Client built in 5259ms
ℹ Building server...  

 ERROR  Could not resolve entry module (../../../../../__uno.css?inline&used). 
 ERROR  Could not resolve entry module (../../../../../__uno.css?inline&used). 

  at error (node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
  at ModuleLoader.loadEntryModule (node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:22369:20)
  at async Promise.all (index 0)
```

## END RESULT 

Once I verified that was the issue I disabled the `autoImports: false` and the build worked since it wasn't importing 

```js
import 'uno.css'
```

and the `build` / `generate` worked again. 

Hopefully this is helpful.

## Stackblitz Link

Run `npm run build` or `npm run generate`

[Here](https://stackblitz.com/edit/nuxt-edge-unocss-bug?file=nuxt.config.ts)

Thanks,
Christian

**Comment by itsmnthn** [comment]
facing same issue. `dev` works fine but getting error while `build`

```
 ERROR  Could not resolve entry module (../../../../__uno.css?inline&used).                                                                         14:04:29
 ERROR  Could not resolve entry module (../../../../__uno.css?inline&used).  
```

**Comment by antfu** [comment]
Should be fixed by https://github.com/unocss/unocss/pull/1578
