### ISSUE TITLE
expandVariantGroup incorrectly transforming non-css code

### ISSUE THREAD

**Issue by smcenlly** [unocss/unocss#1581]
@antfu - thanks for your contributions to OSS.

When recently using your [`vitesse` starter kit](https://github.com/antfu/vitesse), I encountered an error when some of my code was being removed, resulting in a build failure. I tracked this down to `expandVariantGroup` and believe the behavior is incorrect.

I created a sample test (currently failing) to reproduce what I believe is incorrect behavior:

**[test/transformer-variant-group.test.ts](https://github.com/unocss/unocss/blob/main/test/transformer-variant-group.test.ts)**
```javascript
...
  test('should not change source code and non-css code', async () => {
    async function transform(code: string) {
      const s = new MagicString(code)
      expandVariantGroup(s, [':'])
      return s.toString()
    }

    const file = `<script setup lang="ts">
    const myString = "get:() set:()"
</script>
    
<template>
  <h1>Name:(Test)</h1>
  <div class="sm:hover:(bg-gray-100 font-medium)" />
</template>`
    const result = await transform(file)
    expect(result).toMatchInlineSnapshot(`
      "<script setup lang=\\"ts\\">
          const myString = \\"get:() set:()\\"
      </script>
          
      <template>
        <h1>Name:(Test)</h1>
        <div class=\\"sm:hover:bg-gray-100 sm:hover:font-medium\\" />
      </template>"
    `)
  });
...
```

If I understand the purpose of `expandVariantGroup`, it would appear this regex:

https://github.com/unocss/unocss/blob/1572e6ef62aeab553d213d1208455abb76a65e96/packages/core/src/utils/variantGroup.ts#L3

should be updated to only process strings within `class` HTML elements to reduce the chance of false positive replacements.

---

I understand that this behavior can be ignored with an `IGNORE_COMMENT` but this appears to affect the entire file, which in our case will lead to undesirable behavior.

We are working on a new VS Code extension (https://console-ninja.com) that injects some javascript code (similar to `var a = { p:()=>{} }`) into a page (before any unocss transforms) which is how we found the problem.

**Comment by antfu** [comment]
This is the limitation I think, and that's why this transformer is opt-in. Maybe we could introduce a `strict` mode to only rewrite in a certain format. PR welcome if you think it's possible to solve it without introducing full parsers.

**Comment by smcenlly** [comment]
Am I correct in assuming that the replace should only be within `class` attributes? If so, happy to take a quick look at additional heuristic to also check for `class` as part of regex. I think that'll solve most cases without worrying about a parser.

**Comment by antfu** [comment]
It might not always be. Imagine:

```ts
<script setup>
const custom = foo ? 'hover:(text-red font-bold)': ''
</script>

<template>
  <div :class="custom"> 
</template>
```

Checking `class` will break this usage. That's why I think it should be an `strict` option for ppl to opt-in.

**Comment by xsjcTony** [comment]
And also React's `className`, and some `clsx` / `classnames` usage.
I guess this feature might help in this case, e.g. `.transformRegex`
https://github.com/unocss/unocss/issues/2975

**Comment by zyyv** [comment]
Supported it in https://github.com/unocss/unocss/pull/2770.
