### ISSUE TITLE
Attributify with Astro missing some styles in some cases

### ISSUE THREAD

**Issue by AllanChain** [unocss/unocss#1584]
This is a known problem and has been mentioned in https://github.com/unocss/unocss/issues/105#issuecomment-1236294993. I'm opening a new issue here for further tracking it.

## The case

The attributify extractor fails to generate style for `text-red-500`

```html
<a href={href} text-red-500>Vite</a>
```

**Reproduction:** https://stackblitz.com/edit/withastro-astro-vkmvgi?file=src%2Fpages%2Findex.astro

## Why

As I've [mentioned](https://github.com/AllanChain/astro-uno/#what-it-does):

> Astro pre-processes the .astro files and transforms them into something like:
> 
> ```js
> return $$render`<img${$$addAttribute(src, "src")} w-full>`;
> ```
> UnoCSS expected a space after `<img` but Astro gives `$$addAttribute` part instead, making attributify mode not work well. Here we pass modified code with extra space to UnoCSS for extracting the tokens.

### Option 1: pre-process the source before extracting

This is what I've done in [astro-uno](https://github.com/AllanChain/astro-uno), but it's a bit hacky.

```js
        // Fixing attributify preset
        const attributifyPreset = options.presets.find(preset =>
          !Array.isArray(preset) && preset.name === '@unocss/preset-attributify'
        )
        if (!Array.isArray(attributifyPreset) && attributifyPreset) {
          const attributifyExtractor = attributifyPreset.extractors
            .find(extractor => extractor.name === 'attributify')
          const extract = attributifyExtractor.extract
          attributifyExtractor.extract = ({ code, original }) => extract({
            // Adding a space here, otherwise UnoCSS doesn't recognize the tag
            code: code.replace(/(<\w+)(\$\{\$\$addAttribute)/g, '$1 $2'),
            original
          })
        }
```

### Option 2: make Astro allow UnoCSS to be applied earlier

This is not quite possible since the use case is rare. (And the Astro guys chose not to include official UnoCSS integration, didn't they?)

### Option 3: add an option for custom extractors

We can add some APIs for creating custom extractors from existing ones and pass them to attributify. This is similar to option 1 but less hacky. Also, if we decide to support a new framework in the future but the existing extractors are not working well, we can create a new extractor to solve this.

### Other options

...

## Additional comments

This is the last fix `astro-uno` provides but is not included in `unocss/astro`. `astro-uno` can safely retire after `unocss/astro` provides this fix.

**EDIT 1:** Related issue: #1734

**Comment by impcyber** [comment]
an alternative way could be to use a `transformer` in uno config:
```ts
  transformers: [
    {
      name: 'uno-astro-patch',
      enforce: 'pre',
      idFilter: id => !!id.match(/\.astro$/),
      async transform(code) {
        const matches = [...code.original.matchAll(/\$\{\$\$(addAttribute|spreadAttributes)/g)]

        if (!matches.length)
          return

        for (const match of matches) {
          const start = match.index

          code.overwrite(start, start + match[0].length, ` ${match[0]}`)
        }
      },
    },
    ...
  ],
```

**Comment by AllanChain** [comment]
I think @impcyber means a Vite transformer. This alternative is better and easier but will add an extra space to the final output. And we can add another transformer to remove the spaces, if the spaces ever matter.

**Comment by sibbng** [comment]
As a workaround you can use `extraContent` option for now:

```ts
// https://astro.build/config
export default defineConfig({
  integrations: [
    Unocss({
      extraContent: {
        filesystem: ['src/**/*.astro']
      },
      presets: [presetUno(), presetAttributify()],
    }),
  ],
});
```
