### ISSUE TITLE
bg-opacity-<value> doesn't work with arbitrary values

### ISSUE THREAD

**Issue by jd-solanki** [unocss/unocss#1587]
Hi,
I want to use CSS variables with `bg-` and found that it doesn't generate the style to adjust the background opacity.

Here's playground [link](https://uno.antfu.me/play/?html=DwBwBAzgLgngNgUwLwCIC0aDGAuMAnBAExTEzgEMIJUAjAczQBJMx60B7EczAS1jQCsABhQA%2BAEpEwAdz4ALMMICkYTtz4xgAehCiAUKFIUqtBgG0ChALqsGa3v2FjJhGfMVCV9jdt0HwZJTUKGyWthxcDjCCIhJSslAKyqqRPjqiQA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUkNikEA&options=N4XyA)

`--un-bg-opacity: 1;` style is only generated for static class `bg-red` and not for `bg-$c` & `bg-[red]`.

**Comment by chris-zhu** [comment]
How about in another way implement it? [Playground](https://uno.antfu.me/play/?html=DwBwBAzgLgngNgUwLwCIC0aDGAuMAnBAExTEzgEMIJUAjAczQBJMx60B7EczAS1jQCsABhQA%2BAEpEwAdz4ALMMICkYTtz4xgAehCiAUKFIUqtBgG0ChALqsGa3v2FjJhGfMVCV9jdt0HwZJTUKGyWthxcDjCCIhJSslAKyqqRPjr6BjR4WhmG0PDI6Fi4AEwCAgA0QlUkgSYhDJgArtDsALbYTnGuCUmeKeqwvvpAA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCCMMUwARgK4zDoCeZF1tAJIBjAlT6UaMAKpYIcAL5x0UCCDgByNnOFUqGgFAHUAD0iwUGAIZsANvDSYc%2BQsCIAKBAbhwod6gBccADawRrCbFQwagC0fraoGmRIorbQQRqUyBqKALq5JN5wMAAWqCCoQV4%2BPqnQVFVFNXARUWoZUEQsVu4AblZQ7jExwgCUJACkVrZgJVajSU2KhT4KK3BUJdAwETANiEvhkdEgMZvbuxoZMKYwMbZExbcx0FZYRKhwW72oUAE3JjuN2mi1W634Un2wSWENosgg7nGMMktAYTFYHC43ER6x8sJgIjEniWPiowmmlTgAEYAHQAJlxNWEyCwGRKjDADQA9FzqCAaZsuaCagokT4CgZRQYgA&options=N4XyA)

**Comment by jd-solanki** [comment]
Great 🎉 

We got a workaround 😇 

I can use it for now but this is not on the fly style we had to update the config, this is find for a single CSS var. Moreover, still `bg-[red]` isn't resolved yet.

BTW, is there docs regarding magic strings/characters like `:` in `bg-custom:50`.

Thanks.

**Comment by chu121su12** [comment]
CSS color values are not resolved from theme or keywords. For the keyword part, you may want to add the list of values to [the preset](https://github.com/unocss/unocss/blob/f3d60f8269932abe8e320ffd7773aff0c217412a/packages/preset-mini/src/_utils/colors.ts#L126).

**Comment by chu121su12** [comment]
> `--un-bg-opacity: 1;` style is only generated for static class `bg-red` and not for `bg-$c` & `bg-[red]`.

As I understand, `util-$value` and `util-[value]` generally use the intended `value` as is, so usually there are no processing involved.


> Thanks for the information. For CSS vars do I have to add each of them to `colors` as @chris-zhu mentioned above?

For now, you have to add them separately. The rationale is that `--x` in `var(--x)` can contain `#f00`, `red`, `255, 0, 0`, `rgb(255, 0, 0)` or even any other string.

Another thing you can do maybe is to add custom shortcut
```js
shortcuts: [
  [/^bg2-(.*?)$/, ([_, c]) => `bg-[rgba(var(--${c}),var(--un-bg-opacity,1))]`],
]
```


> BTW, is there docs regarding magic strings/characters like `:` in `bg-custom:50`.

Mostly tailwind syntax works: `variant:util`, `[prop:value]` and `color-util:opacity`

**Comment by jd-solanki** [comment]
Thanks for the detailed response. I guess `util-[value]` does get parsed because with `bg-[#eee]` we do get the opacity variable: [Docs](https://uno.antfu.me/?s=bg-[%23eee])

Moreover, magically `hsla` value is parsed correctly and `--un-bg-opacity` is assigned proper value: [playground](https://uno.antfu.me/play/?html=DwBwBAzgLgngNgUwLwCIC0aDGAuMAnBAExTEzgEMIJUAjAczQBJMx60B7EczAS1jQCsABhQA%2BAEpEwAdz4ALMMICkYTtz4xgAehCiAUKFIUqtBgG0ChALqsGa3v2FjJhGfMVCV9jdt0HwZJTUKGyWthxcDjCCIhJSslAKyqqRPjr6BjR4WhmG0PDI6Fi4AEwCAgA0QlUkgSYhDJgArtDsALbYTnGuCUmeKeqwvrlZOXr%2BRkGmaGZyEBQAFACM1SueFWtKFcoAlFbO8e7J3kPpQA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCCMMUwARgK4zDoCeZF1tAJIBjAlT6UaMAKpYIcAL5x0UCCDgByNnOFUqGgFAHUAD0iwUGAIZsANvDSYc%2BQsCIAKBAbhwod6gBccADawRrCbFQwagC0fraoGmRIorbQQRqUyBqKALq5JN5wMAAWqCCoQV4%2BPqnQVFVFNXARUWoZUEQsVu4AblZQ7jExwgCUJACkVrZgJVajSU2KhT4KK3BUJdAwETANiEvhkdEgMZvbuxoZMKYwMbZExbcx0FZYRKhwW72oUAE3JjuN2mi1W634Un2wSWENosgg7nGMMktAYTFYHC43ER6x8sJgIjEniWPiowmmlTgAEYAHQAJlxNWEyCwGRKjDADQA9FzqCAaZsuaCagokT4CgZRQYgA&options=N4XyA)

I guess, it is working as intended because we have to handle the case where opacity might be defined in CSS var itself: [playground](https://uno.antfu.me/play/?html=DwBwBAzgLgngNgUwLwCIC0aDGAuMAnBAExTEzgEMIJUAjAczQBJMx60B7EczAS1jQCsABhQA%2BAEpEwAdz4ALMMICkYTtz4xgAehCiAUKFIUqtBgG0ChALqsGa3v2FjJhGfMVCV9jdt0HwZJTUKGyWthxcDjCCIhJSslAKyqqRPjr6BjR4WhmG0PDI6Fi4AEwCAgA0QlUkgSYhDJgArtDsALbYTnGuCUmeKeqwvrlZOXr%2BRkGmaGZyEBQAFACM1SueFWtKFcoAlFbO8e7J3kPp48CjueD5iKgYOGBziysbQuub2547tcbBbMwHHpHfonTTpIA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCCMMUwARgK4zDoCeZF1tAJIBjAlT6UaMAKpYIcAL5x0UCCDgByNnOFUqGgFAHUAD0iwUGAIZsANvDSYc%2BQsCIAKBAbhwod6gBccADawRrCbFQwagC0fraoGmRIorbQQRqUyBqKALq5JN5wMAAWqCCoQV4%2BPqnQVFVFNXARUWoZUEQsVu4AblZQ7jExwgCUJACkVrZgJVajSU2KhT4KK3BUJdAwETANiEvhkdEgMZvbuxoZMKYwMbZExbcx0FZYRKhwW72oUAE3JjuN2mi1W634Un2wSWENosgg7nGMMktAYTFYHC43ER6x8sJgIjEniWPiowmmlTgAEYAHQAJlxNWEyCwGRKjDADQA9FzqCAaZsuaCagokT4CgZRQYgA&options=N4XyA) (_checkout the last demo_)

Closing this.
