### ISSUE TITLE
Feature Request: presetIcons can load binary images (such as .png)

### ISSUE THREAD

**Issue by quanzaiyu** [unocss/unocss#1595]
Now I create a function to handle static images as a icon:

![image](https://user-images.githubusercontent.com/13745132/190078946-419f06e9-0dec-44c1-a38b-ab46c6f67193.png)
![image](https://user-images.githubusercontent.com/13745132/190078995-a97d0333-e0f6-4b33-870c-ab0d5354c0a2.png)
![image](https://user-images.githubusercontent.com/13745132/190080710-4f343cc2-b7c3-4ff0-8102-af6248763f71.png)
![image](https://user-images.githubusercontent.com/13745132/190083118-97eec425-961d-459b-bfb2-83db323cd982.png)

It works well.

I try to use `presetIcons` to integrate static images.

example:
![image](https://user-images.githubusercontent.com/13745132/190078422-7d3b990b-252f-4b81-a697-cfe92bc6fb5f.png)

```js
    presetIcons({
      collections: {
        'my-icon': FileSystemIconLoader('./static/icons/*.png'),
        icon: {
          base: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADEAAAAwCAYAAAC4wJK5AAAAAXNSR0IArs4c6QAAAhVJREFUaEPtmk1rE1EUhp83mFJsC0JTk0EQwa3gRqgLNyK4dVcLQsGNYuKI667cFroppOA/UOhCdGELQsH6D3RVuq7JWD9WLmqbe6UJjbXOJJMyM53Wm23mnPM+5z3JvTc34hS8dAoYcBB5cbGnE/YBRa5WHgL3sFxBGs1cuLUB8JbC7pyqX9fD6kdC2PqFcWitIF3LXHhoQbsDzKrWnD/8diiEfcYQpcoa0mQ+AA6okJ1Stbl0UFc4xGL5LhRe5g5gT5DlO+8b57VEa19fBERlFXQzlxBtkNZtPf7yrh/EL1AxtxDikaqN530gPJtbgLYw81S1YMFBHL9Lzonj96CjwDlxFCfsfc5sv2JneBMxcpQM/8Zk7IRqjfaCauveD8Q5B9HtgHNi8GFw4xTZMzdOEa0xu1Pyt/46qMQdPDtXGmO0+BG4FDcmncXOmDvygzfxRfx5snOK9DYQF+PHu3GK36vuXt8tdlFNc+PkxunkbgDBTLMVvGbC+wacHdzLsIiMPxPJiD6cxUGk09fBszonBu9ZOhH/kRM/k/s6TMML66vWrHf3Z2El7KL3AbiRRvlEchpzS36w2huiXp5GhReJFEw+ySatxmU9Ybs3xN5BZaKyBif4uqv9Y9f8WInhkeVcXTwaZuXHvHjct6lzBVyewWoGdB0xlPx09Mlo7WekZYxZkB98Cnva/aMgc1ciCjon8uLEb7sqS0BvmMphAAAAAElFTkSuQmCC',
          plus: fs.readFile(
            './static/icons/icon-plus.png',
            {
              encoding: 'binary'
            },
            (err, img) => {
              const buffer = new Buffer.from(img, 'binary')
              let base64 = buffer.toString('base64')
              console.log(base64)
              return base64
            }
          )
        }
      }
    })
```

But it cannot work. 

I hope adding new features to  integrate these  static images as icon.

**Comment by antfu** [comment]
This could probably be out-of-scope of the icons preset. I think it's better to do it as a separate user preset.

**Comment by quanzaiyu** [comment]
Well, thanks!  I'll try to write a preset for myself.
