### ISSUE TITLE
bug: cannot resolve computed class in svelte

### ISSUE THREAD

**Issue by Stvchm9703** [unocss/unocss#1598]
currently I use carbon-components-svelte as the component library, and I want to use unocss as the CSS JIT engine, instead of prebuild css, 
but I get fail to let unocss recognize/scan the computed class in component :

for example :
node_modules\carbon-components-svelte\src\Button\Button.svelte
![image](https://user-images.githubusercontent.com/15327054/190176410-641fe159-a473-490f-817c-4b9aaf8b4b31.png)

preset-carbon-design (implement)
![image](https://user-images.githubusercontent.com/15327054/190177133-7c97303d-8c81-44a0-8ee0-0d97bfd1cfab.png)

+page.svelte 
![image](https://user-images.githubusercontent.com/15327054/190177133-7c97303d-8c81-44a0-8ee0-0d97bfd1cfab.png)
----

so far, the outcome of svelte component is as the expected, should show the classlist in DOM node, but the unocss do not pass the `bx--btn--secondary` 
![image](https://user-images.githubusercontent.com/15327054/190178621-0479145a-5732-48ad-8ad9-fe9179ffa601.png)

and I check the inspector, `bx--btn--secondary`  is valid to use,

is it the vite plugin order issue ?

**Comment by chris-zhu** [comment]
You are using dynamic class, and you can look through previous issues to find related issues.

**Comment by Stvchm9703** [comment]
@chris-zhu  thx for your help ! I get it there!

**Comment by Stvchm9703** [comment]
one thing may I ask : if I am not using bx--btn,  the safe-list is keep injected to output, is it a way to handle it?
