### ISSUE TITLE
Feature request: add support for `Collection Aliases`

### ISSUE THREAD

**Issue by hamedbaatour** [unocss/unocss#1599]
It would be great to add support for [Collection Aliases](https://github.com/antfu/unplugin-icons#collection-aliases) just like in `unplugin-icons`

an addition of an `alias` option to the `IconsOptions` object would be great!

```
  Unocss({
           presets: [
             presetIcons({
               alias: {
                 park: 'icon-park',
                 fas: 'fa-solid',
                 // ...
               }
             }),
           ],
         })
```

**Comment by chris-zhu** [comment]
How about use `shortcuts` option? (Please excuse me for not used `unplugin-icons`)

**Comment by hamedbaatour** [comment]
yup, that is possible. actually, there are two possible workarounds that could work.

Still, adding an alias option would make the syntax clear and much more consistent with `unplugin-icons` as opposed to using the `shortcuts` array as the latter is meant to be used to combine multiple CSS classes not necessarily deal with icons aliases.

just for reference here's an example to use `icon` as an alias for `material-symbol` with current possible workarounds:

- workaround 1: using `shortucts`
```js

Unocss({
  rules: [],
  shortcuts:[
    [/^icon-(.*)$/, ([, d]) => `i-material-symbols-${d}`],
  ],
  presets: [
    presetIcons({
      scale: 1.2,
      warn: true,
    }),
  ],
}),
```

- workaround 2: using `collections`
```js
Unocss({
  rules: [],
  presets: [
    presetIcons({
      collections: {
        "": () =>
          JSON.parse(
            readFileSync(
              "./node_modules/@iconify-json/material-symbols/icons.json",
              "utf-8"
            )
          ),
      },
      prefix: "icon",
      scale: 1.2,
      warn: true,
    }),
  ],
}),
```
