### ISSUE TITLE
Help Wanted: How to override size variants

### ISSUE THREAD

**Issue by erdoganmegma** [unocss/unocss#1600]
I want to override `text-[xs,sm,lg,xl]` font sizing variants defaults.
For example `text-sm` output like `0.875rem` but i want to change this `0.625rem`

Am I need override with custom-rules ? 
https://github.com/unocss/unocss#custom-rules

**Comment by chris-zhu** [comment]
You just need override the theme `fontSize`.
[Playground](http://localhost:5173/play/?html=DwEwlgbgBAxgNgQwM5ILwCIAuBTAHpgWiQFt0oB6APgCgg&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCCMMUwARgK4zDoCeZF1tAJIBjAlT6UaMAKpYIcAL5x0UCCDgByNnOFUqGgFAHUAD0iwUGAIZsANvDSYc%2BQsCIAKBAbhwod6gBccADawRrCbFQwagC0fraoGmRIorbQQRqUyBqKALq5JN5wVAAW0DARMFRBXj4%2B4ZHRIDGl5ZUaGTCmMDG2RHBdJj3QVlhEqHBlAG6oUAGDPV1WtklFCoU%2BMCWoIKg1RT7oBDAAysAAXnuIB3VUIEFhAIwAdI9vlCBJmi8ATH8fGgKN3Waw25EktGqIRu-Cksgg7gAlGCfLDaAwmKwOFxuEiUeCBDARGJPDcfFRhMsrr98T5hMgsBkSowwNUAPRs6ggZ6lNmrOqKZFFIEKREGIA&options=N4XyA)
