### ISSUE TITLE
[Bug] UnoCss not respect the order of css class name

### ISSUE THREAD

**Issue by harrytran998** [unocss/unocss#1603]
Example:

With the below HTML, the text color should be `blue` -- But this display `text-gray-900`

```html
<a class="text-gray-900 text-white hover:text-red-700 text-blue hover:no-underline hover:text-white">Hello where are you now?</a>
```

Here it the playground for the reproduction: https://uno.antfu.me/play/?html=DwEwlgbgBA7gtAJgB4BsoAtGqgMxQUySgCsBXAZwBcwcBPOAY3wDtL8AnKMNgW3MZZt2APgBQUYAENxUWXKgMUk8uQC8AIjZJKcAObtJ9AJwAGE1C06Y6bvgwB7CBwBcluO3wg4AdjMXCVjZsDk7szsz2cKTMIBwoYMx26I4ubta26jLysugeOBrolJQADuTOAPTlutzopABGAHQM9jzl0fYMKm0RneSZ2XKUkuy6%2BJQaAPp1SswA1v3ZwgAS%2BCgo9rDoHHbDdrT2pFARMAD8wOWSYufgEMJAA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUkNikEA&options=N4IgTgpgzgDg9gOygSwG4RALgGYEMA2UEAvkA

**Comment by chu121su12** [comment]
As with multiple rules, dynamic rules that produce multiple css have their generated css sorted alphabetically (text-blue < text-gray). You can alter the order with the [important or (internal) layer variant](https://uno.antfu.me/play/?html=DwEwlgbgfMCGAEBjANrAzmgvAIgC4FMAPXAWgHMAnWATxIE4AGB%2BA4kgI2QFd9soAJfMmQB7eAHcAFvgr54sWfGoiu8AHYjxAfmAB6WFABQoSDAQp0WPEVKUa9JvACErUpx59BwsVJlyFcsqqGtp6Bsbg0HBIqBg4ruRUtIzMXBokqNQyJPgATABcCe68AkKiEtKKAUoq6po6%2BkZAA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUkNikEA&options=N4IgTgpgzgDg9gOygSwG4RALgGYEMA2UEAvkA)
