### ISSUE TITLE
🎖 Mentioning frameworks in UnoCSS README

### ISSUE THREAD

**Issue by jd-solanki** [unocss/unocss#1605]
Hi @antfu 

I am really sorry for the ping but I wanted to point out that in **Anthony's** discord channel there was a [question](https://discord.com/channels/937808017016119440/937811334907723806/1019973544219787274) regarding available frameworks based on UnoCSS.

As you already know [Anu](https://github.com/jd-solanki/anu) is now emerging UI framework (_Thanks to your tweet 😇_) I think we can mention Anu in UnoCSS README for visibility of ecosystem build around UnoCSS, This will wider adoption of UnoCSS 🏆

I will a make PR upon your approval. But before can you please let me know in which section I should mention frameworks based on UnoCSS.

Thanks for UnoCSS ❤️

**Comment by antfu** [comment]
Sure I am happy to have them (awesome work!). PR welcome!

**Comment by antfu** [comment]
Probably after `Community Presets` and say `Community Frameworks`?
