### ISSUE TITLE
Css properties with two or more words inside of a class in rules doesn't work (Nuxt.js)

### ISSUE THREAD

**Issue by Ali-Guliyev** [unocss/unocss#1606]
When I am trying to add a rule with two or more words inside of a css property i can't use them in my nuxt app. Are there any solutions for this issue?

 ```javascript
export default defineConfig({
    rules: [
        ['button', { borderWidth: '1.5px' }],
    ]
)}
```

**Comment by chu121su12** [comment]
Currently there's no name normalization on property name. Use `{ 'border-width': '1.5px' }`
