### ISSUE TITLE
Attributify doesn't work for arbitary class name.

### ISSUE THREAD

**Issue by humbleCoder1990** [unocss/unocss#1607]
![image](https://user-images.githubusercontent.com/87828192/190882566-2f660506-8a40-45af-a768-172061940d29.png)

**Comment by chris-zhu** [comment]
`[]` does not meet the html attribute naming rules.
Use `grid="rows-[38px_1fr]"` or `grid-rows="[38px_1fr]"` instead of it. Another way back to use class.
