### ISSUE TITLE
Bug: unocss lib-build not work with @unocss-include 

### ISSUE THREAD

**Issue by Simon-He95** [unocss/unocss#1612]
[repo](https://github.com/Simon-He95/git-fork)
in subpackage, it works, but when on another project with npm-import `class="fixed left-0 top-0"` will be lost

**Comment by Simon-He95** [comment]
Unocss packaging does not generate CSS or package the unocss syntax in my library into bundle,
temporarily, I use [vite-plugin-Inspector-lib-css](https://github.com/Simon-He95/vite-plugin-Inspector-lib-css) powered by unocss to analyze and inspector CSS build in to bundle. 

There may be some configurations that I do not know can be done directly, if there are please let me know, thanks

**Comment by Flower-F** [comment]
You'd better provide a minimal reproduction. This repo is so big that I don't know what the problem is.
