### ISSUE TITLE
Nested css property for rules

### ISSUE THREAD

**Issue by devunt** [unocss/unocss#1614]
Is there a way to declare nested css property for rules?

e.g.
```
  rules: [
    ['keep-all', { 'word-break': 'keep-all' }],
    [
      'scrollbar-hide',
      { 'scrollbar-width': 'none', '-ms-overflow-style': 'none', '&::-webkit-scrollbar': { display: 'none' } },
                                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^ errors now
    ],
  ],
```

**Comment by chu121su12** [comment]
This constitues generating multiple selector, so you'd want to use either [raw css](https://github.com/unocss/unocss#full-controlled-rules) or [variant](https://github.com/unocss/unocss#custom-variants).
