### ISSUE TITLE
Unocss presets brokes with Nuxt 3.0.0-rc.10

### ISSUE THREAD

**Issue by alvarosabu** [unocss/unocss#1615]
## Describe the bug

After updating to Nuxt `3.0.0-rc.10` and unocss `v0.45.21` , if `presets` property is present on `unocss.config.ts` whole page CSS is broken (unocss doesn't seem to generate the styles)

## Reproduction 

https://stackblitz.com/edit/github-mtfdou?file=nuxt.config.ts

```
export default defineConfig({
  theme: {
    ...
  },
  shortcuts: [],
  rules: [],
  presets: [
    presetTypography({
      cssExtend: {
        h1: headlineStyles,
        h2: headlineStyles,
        h3: headlineStyles,
      },
    }),
  ],
  transformers: [transformerDirectives(), transformerVariantGroup()],
});
```

## Steps to reproduce 

1. Open reproduction link https://stackblitz.com/edit/github-mtfdou?file=nuxt.config.ts 
2. Presets property is present on `unocss.config.ts` 
3. Header with text "Holi" should have bg of color teal
4. Comment `presets` and reload
5. Now header should have the correct background

### Unocss
```
    "@unocss/nuxt": "^0.45.21",
    "@unocss/preset-typography": "^0.45.21",
    "@unocss/preset-web-fonts": "0.45.21",
```

### Nuxt
```
------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.11.0`
- Nuxt Version:     `3.0.0-rc.10`
- Nitro Version:    `0.5.3`
- Package Manager:  `pnpm@7.8.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------
```

**Comment by chris-zhu** [comment]
You haven't use `presetUno`. Those base tokens need `presetUno` supported.
