### ISSUE TITLE
Feature request: COPY class name in interactive docs

### ISSUE THREAD

**Issue by unickhow** [unocss/unocss#1619]
Hi, I was thinking if there's a clipboard button next to class name would be great. especially looking up a long name with hyphens like `backdrop-filter-revert-layer`, even a `select-all` on the class name might be more friendly?

<img width="851" alt="image" src="https://user-images.githubusercontent.com/22793771/191571543-d6fe1e44-3451-4618-9400-048790ef5072.png">

**Comment by sudongyuer** [comment]
This issue already solved, can close ~
