### ISSUE TITLE
add option to disable built-in `container` class

### ISSUE THREAD

**Issue by zamanruhy** [unocss/unocss#1620]
Hi! Thanks for a great tool!
It would be nice to be able to disable the built-in `.container` class because I want to create my own fluid one.
Currently, I have to do the following:
```js
// uno.config.js
export default defineConfig({
  blocklist: ['container']
})
```
```css
/* main.css */
.container {
  @apply mx-auto box-content max-w-1200px px-4;
}
```
but it's a little ugly (

**Comment by zamanruhy** [comment]
But I want to keep the breakpoints as they are.
Another option is to use post-processing:
```js
postprocess: [
  (util) => {
    if (util.selector === '.container') {
      const px = 4
      const maxWidth = 1200
      util.entries = util.parent
        ? []
        : [
            ['margin-left', 'auto'],
            ['margin-right', 'auto'],
            ['box-sizing', 'content-box'],
            ['padding-left', `${px * 4}px`],
            ['padding-right', `${px * 4}px`],
            ['max-width', `${maxWidth}px`]
          ]
    }
  }
]
```
but again not ideal.

**Comment by antfu** [comment]
You can just add your custom rule, it should just override the builtin one

**Comment by azaleta** [comment]
https://github.com/unocss/unocss/blob/d2b022d313c39aa9c1e309a6167f4be699489fd4/packages/core/src/generator/index.ts#L105-L108

`container` can be loaded from func `expandShortcut` (from preset-wind)
So it will be only processed `stringifyShortcuts` (preset thing only)  and skip the custom rules.

Maybe a merge/override logic is needed? (a flag defined in RuleMeta as well)

if `merge` -> return preset rules + custom rules
if `override` -> return custom rules only

**Comment by doantu05150** [comment]
Do the same like using tailwind. Put it on `theme`

```typescript
container: {
    center: true,
    padding: {
       'DEFAULT': '1rem',
       'md': '2rem',
    },
    maxWidth: {
      lg: '1024px',
    },
  },
```

**Comment by chenweiyi** [comment]
确实有这个问题，container无法通过rules覆盖，还有什么更好的方案吗？

**Comment by FLaMeH** [comment]
> 确实有这个问题，container无法通过rules覆盖，还有什么更好的方案吗？

export default defineConfig({
  rules: [['custom-rule', { color: 'red' }]],
  theme: {
    breakpoints: {
      xs: '320px',
      sm: '640px',
      md: '768px',
      lg: '1200px',
      // ...
    },
  }
})

**Comment by Nick742037091** [comment]
use [Mini preset](https://unocss.dev/presets/mini#rules) which not contain `container`class

**Comment by magicdawn** [comment]
```ts
import { presetUno } from 'unocss'

const _presetUno = presetUno()
delete _presetUno.shortcuts
_presetUno.rules = _presetUno.rules?.filter((rule) => !rule[0].toString().includes('container'))
```

**Comment by luckyjoke** [comment]
在配置文件上自定义 .container还是无法覆盖样式，导致项目全部 .container带上了媒体查询max-width

**Comment by luckyjoke** [comment]
> use [Mini preset](https://unocss.dev/presets/mini#rules) which not contain `container`class

尝试使用mini  成功了
