### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by ancientfutures** [unocss/unocss#1621]
- Issue Type: `Bug`
- Extension Name: `unocss`
- Extension Version: `0.45.21`
- OS Version: `Darwin x64 21.6.0`
- VS Code version: `1.71.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by chris-zhu** [comment]
What is that? I haven't see anywhere about the warning message.

**Comment by ancientfutures** [comment]
so the plugin not response, event i put setting on setting.json

**Comment by antfu** [comment]
https://github.com/unocss/unocss/issues/1664
