### ISSUE TITLE
VsCode Extension Runtime Status Error

### ISSUE THREAD

**Issue by erdoganmegma** [unocss/unocss#1623]
VsCode extension not working with vite-i18n package.

My vite.config.ts for i18n 
```typescript
import VueI18n from "@intlify/vite-plugin-vue-i18n";

export default defineConfig({
plugins:[
      VueI18n({
      include: [path.resolve(__dirname, "locales/**")],
    }),
 ]
})
```
<img width="551" alt="image" src="https://user-images.githubusercontent.com/66623898/191713899-ce080550-3284-4d31-93eb-45a91ea69b9c.png">

**Comment by sudongyuer** [comment]
close #1661
