### ISSUE TITLE
Some suggestions of unocss VSCode extension 

### ISSUE THREAD

**Issue by you-hengh** [unocss/unocss#1631]
目前根据文档介绍, unocss 插件会检测根目录下的 uno.config.js 等配置文件,

我使用的是 cdn 环境的 unocss,而且因为一些原因,我不能把 uno.config.js 配置在根目录, 从而导致无法使用插件提示,

我希望能够插件能够检测 html 文件所在目录

```
xxxxx     
├─ unocss 版          
│  ├─ index.html     
│  ├─ style.css      
│  └─ uno.config.js  
└─ 原版                
   ├─ index.html     
   └─ style.css  
```    
尽管我知道 vscode 可以通过打开 unocss 版 这个文件夹来使用插件, 但我还需要参照原版的 css 结构来重构 unocss 版本

我希望上述目录结构下  unocss 的插件依旧能够提示我, 非常感谢作者开发!

vscode版本: 1.70.2 (Universal)
提交: e4503b30fc78200f846c62cf8091b76ff5547662
日期: 2022-08-16T05:36:37.829Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.6.0

unocss插件版本: v0.45.21

**Comment by azaleta** [comment]
https://github.com/unocss/unocss/tree/main/packages/vscode#config

**Comment by you-hengh** [comment]
> https://github.com/unocss/unocss/tree/main/packages/vscode#config

谢谢, 但这个依旧不是特别方便 在插件支持之前 我不再关注这个问题了
