### ISSUE TITLE
vscode extension doesn't work after upgrating to 0.45.23

### ISSUE THREAD

**Issue by Flower-F** [unocss/unocss#1644]
After upgrating the extension to version 0.45.23, the extension doesn't work anymore with TSX.
![屏幕截图 2022-09-26 220246](https://user-images.githubusercontent.com/78215016/192297517-2e120ecc-2b8f-44ee-91f5-889f584445b0.png)
Revert to version 0.45.21, there isn't any problem.
![屏幕截图 2022-09-26 220126](https://user-images.githubusercontent.com/78215016/192297743-7fb07e2a-b2ac-493e-9b2c-c8e85472ac2b.png)
Here is the [reproduction](https://github.com/Flower-F/uno-vscode-reproduction). There isn't anything special, just a normal React template created by Vite. And I think it's because of this [commit](https://github.com/unocss/unocss/commit/b8c8844a).

**Comment by joseehilton147** [comment]
same here

**Comment by chris-zhu** [comment]
I'm not sure the reason about that commit, but it works well in my vue project.

**Comment by Flower-F** [comment]
> I'm not sure the reason about that commit, but it works well in my vue project.

I tried a Vue3 project, and the issue still exsits when upgrating to version 0.45.23. And I use the Windows system, are you using the Mac OS?

**Comment by sudongyuer** [comment]
This [commit](https://github.com/unocss/unocss/commit/b8c8844a) seems not resovle this issue , the issue #1565 still exist

**Comment by Flower-F** [comment]
> And this [commit](https://github.com/unocss/unocss/commit/b8c8844a) seems not resovle this issue , the issue #1565 still exist

I think it might need to make a revert just as sxzz said.(

**Comment by azaleta** [comment]
The problem is not in #1565 
PR is coming #1645

**Comment by Flower-F** [comment]
> @Flower-F you are on Windows, am I right?

Yes

**Comment by sudongyuer** [comment]
> The problem is not in #1565 PR is coming #1645

Yes, you are right , thx
