### ISSUE TITLE
text-size totally ignored if defined inside rules or shortcuts

### ISSUE THREAD

**Issue by aspiiire** [unocss/unocss#1646]
I don't understand the logic, I have defined many rules and shortcuts, but the ones with text-size-[Xpx] get ignored totally, if I apply inline classes with text-size-8 for example it works perfectly.

This are rule examples that I tried to test it out... what I-am doing wrong?

```
[/^ts-(d+)$/, ([, d]) => `text-size-[4px]`],
['ts-8', () => ({ 'font-size': '25rem' })],
```

**Comment by aspiiire** [comment]
Ok thanks, I have provided an example of what I want to achieve on the playground link that you have shared

**Comment by chris-zhu** [comment]
> Ok thanks, I have provided an example of what I want to achieve on the playground link that you have shared

Where is the link?

**Comment by aspiiire** [comment]
Sorry how can I share my code from this playground?

**Comment by chris-zhu** [comment]
> Sorry how can I share my code from this playground?

Share the URL link.

**Comment by antfu** [comment]
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)
