### ISSUE TITLE
vscode@0.45.25 run error

### ISSUE THREAD

**Issue by wkeylin** [unocss/unocss#1652]
error message: Activating extension 'antfu.@unocss/vscode' failed: The "path" argument must be of type string or an instance of URL. Received undefined.

Platform: Mac

because of this pr https://github.com/unocss/unocss/pull/1645

**Comment by azaleta** [comment]
@sudongyuer 
seems this ref to vite has some problem?
![image](https://user-images.githubusercontent.com/22554452/192421743-f8b5e8cf-2ab0-4083-bed2-73657581c055.png)

**Comment by sudongyuer** [comment]
> error message: Activating extension 'antfu.@unocss/vscode' failed: The "path" argument must be of type string or an instance of URL. Received undefined.
> 
> Platform: Mac
> 
> because of this pr #1645

sorry, that's my bad , As a quick workaround you can revert the vscode extension to 0.45.21 make it works
<img width="959" alt="image" src="https://user-images.githubusercontent.com/76603360/192423944-5e0e0f69-ac6e-481f-92d0-4c1017fb07b2.png">

**Comment by itpropro** [comment]
I can confirm that no UnoCSS VSCode extension works since 0.45.21 on Windows 11 with current VSCode.
Since 0.45.23, the configs cannot be loaded anymore and since 0.45.24, it's not loading at all.
The only fix I found was to revert to 0.45.21.

**Comment by varmiral** [comment]
+
