### ISSUE TITLE
Warning: failed to find vite:css-post plugin. It might be an internal bug of UnoCSS

### ISSUE THREAD

**Issue by lightglitch** [unocss/unocss#1653]
I'm using pnpm with nuxt 3:
```
- Operating System: `Windows_NT`
- Node Version:     `v18.9.1`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `pnpm@7.12.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
```
How can I debug the issue and solve it?

**Comment by sudongyuer** [comment]
you can provide a reproduction would be better~

**Comment by chris-zhu** [comment]
> you can provide a reproduction would be better~

Is this issue about `pathe`?

**Comment by lightglitch** [comment]
@chris-zhu I don't think so, I downgraded to 0.45.20 to test it and still happens.

**Comment by JackieCheung** [comment]
same issue

**Comment by sudongyuer** [comment]
> 

Can you provide a minimal reproduction ?

**Comment by mrsai** [comment]
same question。

**Comment by lightglitch** [comment]
@sudongyuer you can use https://github.com/lightglitch/nuxt3-pnpm-monorepo to replicate the issue.

**Comment by lightglitch** [comment]
@ydcjeff please reopen this issue because doesn't have nothing to do with pathe.

**Comment by therealokoro** [comment]
Same issue....same setup with mine

- Operating System: `Windows_NT`
- Node Version:     `v17.4.0`
- Nuxt Version:     `3.0.0-rc.11`
- Nitro Version:    `0.5.4`
- Package Manager:  `pnpm@7.11.x`
- Builder:          `vite`

In my case this happens when I run `nuxi generate` or `build`.

Unocss recognises and bundles styles in the template but ignores styles in the style tag when I have `lang="scss"` set on the style tag

see example below

```vue
<script setup lang="ts"></script>

<template>
    <div>
        <h1 class="myClass bg-green">Hello from unocss</h1>
    </div>
</template>

<style scoped>
    .myClass{
        @apply text-red; // this is generated in final build
    }
</style>
```

Notice the `lang="scss"` below
```html
<style scoped lang="scss">
    .myClass{
        @apply text-red; // this is NOT generated in final build
    }
</style>
```
```

**Comment by lightglitch** [comment]
With version v0.45.26 I don't get this warning anymore, maybe `pathe` was responsible for the error.

@therealokoro if your issue is also fixed please close this.

**Comment by therealokoro** [comment]
v0.45.26 doesn't still fix it, Unfortunately s😥

Styles in lang=scss still don't get generate

**Comment by antfu** [comment]
@therealokoro Please create a new issue with a minimal reproduction

**Comment by lightglitch** [comment]
@therealokoro have installed the loaders for sass? Because I was able to use your example just fine.

**Comment by pegiadise** [comment]
minimal repro config:
```js
export default defineConfig({
  publicDir: 'src/assets/libAssets',
  resolve: {
    alias: {
      '@lib': resolve(__dirname, 'src/lib'),
      '@assets': resolve(__dirname, 'src/assets'),
    },
  },
  plugins: [
    unoCSS(),
    vue(),
    dts({
      insertTypesEntry: true,
      outputDir: 'dist/libDist',
    }),
  ],
  build: {
    lib: {
      entry: resolve(__dirname, 'src/lib/main.lib.ts'),
      formats: ['es'],
      name: 'my-lib',
      fileName: 'my-lib',
    },
    rollupOptions: {
      external: ['vue', 'core-js', 'vue-i18n'],
      output: {
        sourcemap: true,
        assetFileNames: 'my-lib.[ext]',
        dir: 'dist/libDist', // THIS IS CAUSING THE ERROR
        globals: {
          vue: 'Vue',
        },
      },
    },
  },
})
```
