### ISSUE TITLE
Vscode Extension Not Work

### ISSUE THREAD

**Issue by jackZmym** [unocss/unocss#1661]
最新版本，mac上无提示反应，只能重装都两周之前的版本才可以

**Comment by azaleta** [comment]
https://github.com/unocss/unocss/issues/1652
Down to .21
or wait for next release

**Comment by chris-zhu** [comment]
@antfu Sorry ping, can you release a new version?

**Comment by vv4304** [comment]
windows10 vscode1.71.2上使用v0.45.25 css不显示横线
![image](https://user-images.githubusercontent.com/25363272/192978275-ae905d37-59e8-46f3-bacf-a355c1e793db.png)
![image](https://user-images.githubusercontent.com/25363272/192978496-2fa84907-c3bd-40de-925b-78e2523371f6.png)
![image](https://user-images.githubusercontent.com/25363272/192978596-1fd09af2-4a83-460f-8828-60f8ffd36f53.png)

**Comment by sudongyuer** [comment]
Sorry for that,  As a quick workaround you can revert the vscode extension to 0.45.21 make it works . we will release latest version soon

**Comment by antfu** [comment]
Released
