### ISSUE TITLE
[plugin:unocss:global:build:scan] [unocss] failed to find vite:css-post plugin. It might be an internal bug of UnoCSS

### ISSUE THREAD

**Issue by Ryuuki6602** [unocss/unocss#1663]
An error occourred when building my project.
OS: windows 10
node version: v16.15.1
package manager: pnpm
builder: vite 3.1.4

It's building properly when using javascipt in my another project which applied the same version of unocss. But in typescript, it does't.

**Comment by Ryuuki6602** [comment]
it's just a static template without function, http request, nothing inside,

**Comment by therealokoro** [comment]
I had same issue. See link to comment I made on it

#1653
