### ISSUE TITLE
bug(vsocde): `defineNuxtConfig` is not defined

### ISSUE THREAD

**Issue by cpreston321** [unocss/unocss#1665]
# Context 

As of the later rc versions of nuxt 3 you don't need `import { defineNuxtConfig } from "nuxt/config";` at the top of the file anymore. If you don't include this it will disable the plugin from vscode saying that `defineNuxtConfig is not defined. Unocss is disabled`. 

I think it would be a pretty easy fix as this was an issue with the `nuxi` CLI too. This can referenced here. https://github.com/nuxt/framework/blob/2e080c259fc5068fcc71e3790b4f5b75cef83eea/packages/nuxi/src/commands/info.ts#L122-L125

**Comment by zyyv** [comment]
Resolved
