### ISSUE TITLE
Attributify doesn't work with SvelteKit

### ISSUE THREAD

**Issue by juliesaia** [unocss/unocss#1675]
Minimum repro: https://stackblitz.com/edit/vitejs-vite-p2vidb?file=src/App.svelte

I was trying to use attributify with SvelteKit but including the preset breaks everything. In the stackblitz you can see the main element isn't even using attributify `<main class="bg-green-500">` but the background still doesn't change.

**Comment by jacob-8** [comment]
> Minimum repro: https://stackblitz.com/edit/vitejs-vite-p2vidb?file=src/App.svelte

You gave the wrong link - your repro doesn't have unocss anywhere.
