### ISSUE TITLE
Classes not generated for pages without server restart in Nuxt 3

### ISSUE THREAD

**Issue by enkot** [unocss/unocss#1682]
This is the same issue described here - #1392, but for files inside "/pages" directory only. 
When adding new classes to page inside `/pages` directory, they are not generated while the Nuxt/Vite dev server is running. But it works fine for files inside `/components`.

### Minimal Reproduction 
https://stackblitz.com/edit/github-ncxynv-mjthv5?file=pages/index.vue

Try to change `bg-blue-500` to `bg-red-500` in the `index.vue` - styles will not be applied.

**Comment by avinean** [comment]
Try this https://nextjs.org/
