### ISSUE TITLE
VsCode Extension Not Work (Still Not Work)

### ISSUE THREAD

**Issue by erdoganmegma** [unocss/unocss#1683]
- https://github.com/unocss/unocss/issues/1623
- https://github.com/unocss/unocss/issues/1661

I'm still getting this error with latest release

<img width="616" alt="image" src="https://user-images.githubusercontent.com/66623898/194100588-2f0b9885-53e1-479e-81ac-7ad6bd17de8f.png">

**Comment by wozien** [comment]
me too.

**Comment by JessicaSachs** [comment]
Pin your version to `0.45.25` in the meantime.

**Reproduction:**
* Vue + Vite project that **does not contain UnoCSS or Vue i18n**.
* My other project which does contain Vue i18n + UnoCSS works fine on `0.45.26`.

<img width="792" alt="Screen Shot 2022-10-05 at 1 54 15 PM" src="https://user-images.githubusercontent.com/2801156/194128473-b9d8b22b-5498-4be4-a261-8a1a2093652e.png">

**Comment by Lexpeartha** [comment]
> Pin your version to `0.45.25` in the meantime.
> 
> **Reproduction:**
> 
>     * Vue + Vite project that **does not contain UnoCSS or Vue i18n** fails to initialize language features.
> 
>     * My other project which does contain Vue i18n + UnoCSS works fine on `0.45.26`.

I'm too experiencing this, but reverting to **any** of the previous 5-6 versions still doesn't work for me.

**Comment by antfu** [comment]
Can anyone share a minimal reproduction? Thanks

**Comment by JessicaSachs** [comment]
Fixed for me in 0.45.28. I did not have time to create a reproduction yet.

**Comment by Lexpeartha** [comment]
@antfu Could you test out the extension in this project? https://github.com/Lexpeartha/astro-uno
It doesn't highlight classes classes for me

**Comment by manuganji** [comment]
Latest version of VSCode Extension doesn't work. I'm following the configuration in [Svelte Kit Scoped Example](examples/sveltekit-scoped)

![Screenshot 2022-10-20 at 22 13 08](https://user-images.githubusercontent.com/1709986/197037773-0fa5de40-3212-4e46-a1fd-3a3645712860.png)

OS: Mac OS
VS Code Version: 1.72
Node.js version: v18.11.0

There are no autocomplete suggestions or colour display. I see some errors in the Runtime Status tab in the VSCode extension page.

**Comment by Atmos4** [comment]
I just want to add that if you add the `uno.config.ts` file, you might need to restart VSCode for the extension to detect the newly created config file! Maybe that might help a few people

**Comment by Simon-He95** [comment]
> I just want to add that if you add the `uno.config.ts` file, you might need to restart VSCode for the extension to detect the newly created config file! Maybe that might help a few people

Currently, unocss has a mechanism for monitoring config creation and automatic updates.
