### ISSUE TITLE
`@unocss/cli` warn about duplication of preset

### ISSUE THREAD

**Issue by avxit** [unocss/unocss#1689]
<img width="648" alt="image" src="https://user-images.githubusercontent.com/38064714/194375192-9c045f02-66df-41c5-a1f9-175b97c28323.png">

To reproduce, install `@unocss/cli`, create `uno.config.js` and add any preset then run the CLI. Warning message is always appeared in screen.

After some digging, I think `loader.load()` doesn't work correctly. It's duplicate entries of `presets` array instead of "merge" or something and that cause the problem.

https://github.com/unocss/unocss/blob/76b883f3d412b61be85f35b08ebc5f616abef818/packages/config/src/index.ts#L57

**Comment by sudongyuer** [comment]
Can you provide a mimimum reproduction ？

**Comment by avxit** [comment]
> Can you provide a mimimum reproduction ？

Here it is: https://github.com/avxit/unocss-cli-bug

**Comment by sudongyuer** [comment]
> > Can you provide a mimimum reproduction ？
> 
> Here it is: https://github.com/avxit/unocss-cli-bug

Hi~,the presetUno() is a default built-in preset of unocss/cli .

**Comment by avxit** [comment]
> Hi~,the presetUno() is a default built-in preset of unocss/cli .

Don't know what you mean about this, but you can substitute it with any other preset, and warning message is still there.

<img width="707" alt="image" src="https://user-images.githubusercontent.com/38064714/194713837-43641860-0758-4001-a951-ab76606b36a2.png">

`@unocss/preset-web-font`

<img width="733" alt="image" src="https://user-images.githubusercontent.com/38064714/194713884-0b2ad916-abe1-4428-9760-9e5cfcec320d.png">

`@unocss/preset-uno` and `@unocss/preset-web-font`

I also updated the minimum reproduction with `@unocss/preset-web-font`.

**Comment by sudongyuer** [comment]
> > Hi~,the presetUno() is a default built-in preset of unocss/cli .
> 
> Don't know what do you mean about this, but you can substitute `@unocss/preset-uno` or combine with any other preset, and warning message is still there.
> 
> <img alt="image" width="707" src="https://user-images.githubusercontent.com/38064714/194713837-43641860-0758-4001-a951-ab76606b36a2.png">
> 
> `@unocss/preset-web-font`
> 
> <img alt="image" width="733" src="https://user-images.githubusercontent.com/38064714/194713884-0b2ad916-abe1-4428-9760-9e5cfcec320d.png">
> 
> `@unocss/preset-uno` and `@unocss/preset-web-font`
> 
> I am also updated the minimum reproduction with `@unocss/preset-web-font`.

Oh~,i see , there might to be some bugs
![image](https://user-images.githubusercontent.com/76603360/194714632-57a7d99c-9106-4853-a463-2a72d369bb76.png)

**Comment by sudongyuer** [comment]
At packages/cli/src/index.ts
![image](https://user-images.githubusercontent.com/76603360/194740527-c506dbc8-928e-4330-b0dc-163202c544b3.png)
