### ISSUE TITLE
[unocss:global:build:generate] [unocss] does not found CSS placeholder in the generated chunks This is likely an internal bug of unocss vite plugin

### ISSUE THREAD

**Issue by aspiiire** [unocss/unocss#1691]
Hi I am using Astro and having this issue when using `yarn build`, while `yarn run dev` works properly with unocss without any issue.

Any idea how to solve this issue?

**Comment by antfu** [comment]
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-a
