### ISSUE TITLE
build error: Inlined implicit external

### ISSUE THREAD

**Issue by zoeyzhao19** [unocss/unocss#1696]
### descroption
I fork the unocss repo then clone to my pc, but build failed after I have installed all deps.
### what is expected
**build success**
### what actually happened
**build error**
![1665207740910](https://user-images.githubusercontent.com/70888488/194691130-8465ab4c-ba09-4247-a7d5-62d5ab7874e3.jpg)

### reproduction
[https://github.com/zoeyzhao19/unocss](url)

just excute **ni** and **nr build**. (I use [https://github.com/antfu/ni](ni) globally to manage packages)

#### environment
 System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz
    Memory: 9.64 GB / 23.74 GB
  Binaries:
    Node: 16.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - C:\Program Files\nodejs\yarn.CMD
    npm: 7.24.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (106.0.1370.37)
    Internet Explorer: 11.0.22000.120

**Comment by sudongyuer** [comment]
In my computer run build successful, macOS13.0
![image](https://user-images.githubusercontent.com/76603360/194713804-1f1cc572-8f51-4bf5-a627-f95e13c1048a.png)

**Comment by zoeyzhao19** [comment]
@sudongyuer . I think [this commit](https://github.com/unocss/unocss/commit/c1aa6d03b9c4cd7124582348df0e42d48639da66)  have solved my problem. But I am still doubt that the code segement ` ctx.options.rollup.inlineDependencies || id[0] === '.' || id[0] === '/' || id.match(/src[\\/]/) || id.startsWith(ctx.pkg.name!)` in [file](https://github.com/unjs/unbuild/blob/main/src/builder/rollup.ts). `/src[\\/]/` seems to be invalid on [regex101](https://regex101.com/)
