### ISSUE TITLE
shims.d.ts slow VSCode down.

### ISSUE THREAD

**Issue by withyellow** [unocss/unocss#1702]
```ts
// shims.d.ts

import type { AttributifyAttributes } from '@unocss/preset-attributify';

declare module 'react' {
  interface HTMLAttributes<T> extends AttributifyAttributes {}
}

```

Code above will slow some part of typescript language service of VSCode, eg. error report. IntelliSense works fine.

Steps to repoduce please checkout: https://github.com/Xwil/unocss-slow-down-vs-code.

It happens in `Vite+React+TS` and `Next.js+TS` projects.

**Comment by antfu** [comment]
What would you expect for the fix? I am not sure if there is anything we could do.

**Comment by Xwil** [comment]
> What would you expect for the fix? I am not sure if there is anything we could do.

Well, I am not sure about this too, but I think a hint may be helpful, it may take a long time to find out those codes may cause the editor to slow down.

**Comment by Flower-F** [comment]
Yes, it will slow down the TypeScript inference. But we must to do that to avoid the limitation of React, or we can't use the Attributify well.

**Comment by ffxixslh** [comment]
Maybe you can try this to avoid the slow:

```ts
// src/shims.d.ts
import * as React from 'react'
declare module 'react' {
  interface HTMLAttributes<T> extends AriaAttributes, DOMAttributes<T> {
    flex?: boolean
    relative?: boolean
    text?: string
    grid?: boolean
    before?: string
    after?: string
    shadow?: boolean
    absolute?: boolean
  }
}
```

But it needs you to add the attributes manually.😂

**Comment by Tzxhy** [comment]
for this problem, i decide not to use Attributify.
