### ISSUE TITLE
Should support `content-raw-[attr(xx)]`

### ISSUE THREAD

**Issue by xhebox** [unocss/unocss#1713]
Something like:

```diff
--- a/dist/shared/preset-mini.b300afab.cjs
+++ b/dist/shared/preset-mini.b300afab.cjs
@@ -487,7 +487,7 @@ const contentVisibility = [
   ...colors.makeGlobalStaticRules("content-visibility")
 ];
 const contents = [
-  [/^content-\[(.+)\]$/, ([, v]) => ({ content: `"${v}"` })],
+  [/^content-\[(.+)\]$/, ([, v]) => ({ content: /^attr\(.+\)$/.test(v) ? `${v}` : `"${v}"` })],
   [/^content-(\$.+)]$/, ([, v]) => ({ content: colors.handler.cssvar(v) })],
   ["content-empty", { content: '""' }],
   ["content-none", { content: '""' }]
```

Since I am not very familiar with tests of unocss, I'll file a PR for now.

**Comment by sudongyuer** [comment]
I will do it right now ~ thx for this suggest

**Comment by antfu** [comment]
I am afraid this would be a bit magical. The bracket syntax should forward as-is, using `attr()` out of nowhere could be confusing. Maybe instead we could have `content-raw-[foo]`?

**Comment by xhebox** [comment]
> I am afraid this would be a bit magical. The bracket syntax should forward as-is, using `attr()` out of nowhere could be confusing. Maybe instead we could have `content-raw-[foo]`?

I am OK with both. It does not need to be compatible with tailwindcss.

**Comment by xhebox** [comment]
I thought I wrote 'I won't file a PR for now`... Whatever, here is the PR, #1715 . Feel free to suggest changes :)
