### ISSUE TITLE
A bug about all-revert

### ISSUE THREAD

**Issue by peterroe** [unocss/unocss#1726]
Not work:
```html
<button border bg-red all-revert>sdf<button>
```
```ts
export default defineConfig({
  rules: [
    ['all-revert', { all: 'revert !important'}]
  ],
})
```

https://uno.antfu.me/play/?html=DwIwrgLhD2B2AEJoCcAmBTZiDmBaZ6q8AhgDan7oBumEAfAM6oBmokMsdQA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6slF69k5OyRgAbhiw6ZlVTnm0DbYAhKA2MPa4MHqlVGVUdAAW0DCxMHSh-qj6sfFJk9OzenkwVjCJTqRwO5Z70AOkGHBTncHHeztVZqhqsiIK8%2BGRcqJKKj4AlOVvgoWGxODw%2BPwAUC3uIpLg6H4vqg6BIqhhQgBGAB0ACYgagJGhcHkJqwwPMAPSU%2BggbGTSlPJZqQGjJAspBAA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g

Work:
```html
<button border bg-red allrevert>sdf<button>
```
```ts
export default defineConfig({
  rules: [
    ['allrevert', { all: 'revert !important'}]
  ],
}}
```

https://uno.antfu.me/play/?html=DwIwrgLhD2B2AEJoCcAmBTZiDmBaZ6q8AhgDakEBumEAfAM6oBmokMstQA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6slF69k5OtABuGLDpmVVOeXUN8ACEoDYw9rgweqVUZVR0ABbQMLEwdKH%2BqPqx8UkTUzN6eTBWMIlOpHDblrvQ-aQYcJP1UMFHu9tVZqhqsiIKc%2BGRcqJKKj4AlOVvgoWGxODw%2BPwAUC3uIpLg6H4vqg6BIqhhQgBGAB0ACYgagJGhcHlxqwwHMAPSU%2BggbETSlPRZqQEjJAspBAA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g

It seem that I can't use `all-revert` as custom rule key, But if I just use `!all-revert` as class, it not work, too.

https://uno.antfu.me/play/?html=DwIwrgLhD2B2AEJoCcAmBTZiDmBaZ6q8AhAIYA25%2B6AbphAHwDOqAZqJDLA0A&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6smVUdAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLlQSkhsUggA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g

**Comment by chris-zhu** [comment]
Because of we have `all` variant. UnoCSS apply variant first when parse tokens.
https://github.com/unocss/unocss/blob/477ce2b5339e780dd2ed2611714149944a77caa7/packages/preset-mini/src/_variants/combinators.ts#L23

**Comment by peterroe** [comment]
OK，But Is this conflict expected?

**Comment by chris-zhu** [comment]
> OK，But Is this conflict expected?

Emm... Maybe yes, i remembered that "this is intentional" in a antfu's live stream said.
