### ISSUE TITLE
Reduce generated CSS

### ISSUE THREAD

**Issue by pierredewilde** [unocss/unocss#1727]
When UnoCSS variables are only used once, generated CSS could be reduced by replacing variables by its value.

Eg instead of 
```
a:hover {
    border-radius: .25rem;
    --un-bg-opacity: 1;
    background-color: rgba(254,240,138,var(--un-bg-opacity));
    --un-text-opacity: 1;
    color: rgba(17,24,39,var(--un-text-opacity))
}
```
generate this
```
a:hover {
    border-radius: .25rem;
    background-color: rgba(254,240,138,1);
    color: rgba(17,24,39,1)
}
```

**Comment by antfu** [comment]
It's really hard for a tool to know "only used once" and you don't override the variable somewhere else. If you know you won't change the opacity, you can explicit set the opacity `text-red:100`, which will be inlined as you expected.
