### ISSUE TITLE
Astro build lost some style

### ISSUE THREAD

**Issue by alexzhang1030** [unocss/unocss#1734]
Here is a minimal prodution repository -> [repo](https://github.com/alexzhang1030/astro-with-unocss-issue)

Only appears in attributify mode

Execute astro build by using Solid-JS and Island Component, the corresponding rule is not generated in final css file.

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/49969959/195410832-ffba32f3-1b44-43f8-819c-1417d946d6ce.png">

<img width="903" alt="image" src="https://user-images.githubusercontent.com/49969959/195410789-6bebd836-1dfb-49f9-ad7a-62db1039a41e.png">

But Vue works.

**Comment by chu121su12** [comment]
Attributify mode needs separator before the closing tag (eg. space, quote).

Try `<div color-blue-600 >`

**Comment by alexzhang1030** [comment]
> separator

No...I tried, but noting happened.

**Comment by antfu** [comment]
I guess it's more of a Solid issue, that Solid transform the TSX before UnoCSS read it, causing it to fail to match the attributes in HTML. I will try to investigate

**Comment by laurieherault** [comment]
Is not limited to attributify mode. 
@antfu I think you are right. I have to put missing styles in the safelist and it's work.

**Comment by sibbng** [comment]
I believe this is can be fixed by https://github.com/unocss/unocss/pull/1963
