### ISSUE TITLE
Attributify's attribute `align` doesn't work in SolidJS's `<div>` element

### ISSUE THREAD

**Issue by wjq990112** [unocss/unocss#1736]
As the title says, I tried to use the `align` attribute on the `<div>` element in SolidJS, but it didn't work.

```tsx
// App.tsx
function App() {
  return (
    <div h="50px" flex="~" justify="around" align="items-center">
      <div>Box 1</div>
      <div>Box 2</div>
      <div>Box 3</div>
    </div>
  );
}

export default App;
```

Maybe because the `align` attribute is an attribute of the HTMLDivElement, I added the `align` attribute into the `ignoreAttributes` list, and used the `un-align` instead, but still not working.

```tsx
// vite.config.ts
import { defineConfig } from 'vite';
import solidPlugin from 'vite-plugin-solid';
import unocssPlugin from 'unocss/vite';
import presetUno from '@unocss/preset-uno';
import presetAttributify from '@unocss/preset-attributify';

export default defineConfig({
  plugins: [
    solidPlugin(),
    unocssPlugin({
      presets: [
        presetUno(),
        presetAttributify({ ignoreAttributes: ['align'] }),
      ],
    }),
  ],
  server: {
    port: 3000,
  },
  build: {
    target: 'esnext',
  },
});
```

```tsx
// App.tsx
function App() {
  return (
    <div h="50px" flex="~" justify="around" un-align="items-center">
      <div>Box 1</div>
      <div>Box 2</div>
      <div>Box 3</div>
    </div>
  );
}

export default App;
```

This is the reproduction link: https://stackblitz.com/edit/reproduce-uno-solid-attributify-bug?file=src%2FApp.jsx,vite.config.js

Is this an UnoCSS bug? If it is, I'm more than willing to fix it, and need some guidance.

**Comment by chris-zhu** [comment]
https://uno.antfu.me/?s=items-center

**Comment by wjq990112** [comment]
> https://uno.antfu.me/?s=items-center We don't have that rule.

Oh! `items="center"` is working, but throw a type error:

<img width="804" alt="image" src="https://user-images.githubusercontent.com/45777252/195509689-8de8c0ca-d9b7-4520-932c-0977b1d6a439.png">

**Comment by wjq990112** [comment]
Why not use the same rules as WindiCSS?

https://windicss.org/posts/attributify.html#align

**Comment by wjq990112** [comment]
> > https://uno.antfu.me/?s=items-center
> > We don't have that rule.
> 
> Oh! `items="center"` is working, but throws a type error:
> 
> <img alt="image" width="804" src="https://user-images.githubusercontent.com/45777252/195509689-8de8c0ca-d9b7-4520-932c-0977b1d6a439.png">

Looks like the `AttributifyAttributes` type doesn't include the `items` attribute.

**Comment by chris-zhu** [comment]
> Why not use the same rules as WindiCSS?
> 
> https://windicss.org/posts/attributify.html#align

https://uno.antfu.me/?s=align I guess we have aligned with tw & windi, `align` rule about `vertical-align`.

**Comment by chris-zhu** [comment]
> > > https://uno.antfu.me/?s=items-center
> > > We don't have that rule.
> > 
> > 
> > Oh! `items="center"` is working, but throws a type error:
> > <img alt="image" width="804" src="https://user-images.githubusercontent.com/45777252/195509689-8de8c0ca-d9b7-4520-932c-0977b1d6a439.png">
> 
> Looks like the `AttributifyAttributes` type doesn't include the `items` attribute.

https://github.com/unocss/unocss/blob/main/packages/preset-attributify/README.md#typescript-support-jsxtsx

**Comment by wjq990112** [comment]
> > > > https://uno.antfu.me/?s=items-center
> > > > We don't have that rule.
> > > 
> > > 
> > > Oh! `items="center"` is working, but throws a type error:
> > > <img alt="image" width="804" src="https://user-images.githubusercontent.com/45777252/195509689-8de8c0ca-d9b7-4520-932c-0977b1d6a439.png">
> > 
> > 
> > Looks like the `AttributifyAttributes` type doesn't include the `items` attribute.
> 
> https://github.com/unocss/unocss/blob/main/packages/preset-attributify/README.md#typescript-support-jsxtsx

I have read and done this guide, and it still throws this error.

**Comment by wjq990112** [comment]
I would like to fix it!

**Comment by chris-zhu** [comment]
I didn't see the reply in time, one step faster than you. If I don't solve it well, you can send a new pr

**Comment by wjq990112** [comment]
@chris-zhu So fast! 👍🏻

In my opinion, I prefer the rules like Windi, maybe just fixing type checks isn't a good choice?
The `@unocss/preset-uno` is the same as Windi, but the `@unocss/preset-attributify` isn't the same, from the user's point of view, are there any splits?

**Comment by chris-zhu** [comment]
In fact, `@unocss/preset-attributify` only extract code to generate tokens, more parsed power depends on unocss engine and base on those rules that comes from `@unocss/preset-uno` .

> from the user's point of view, are there any splits?

I don't think I'm equipped to answer this question😅
