### ISSUE TITLE
Styles not generated for pages when I use Dynamic classes

### ISSUE THREAD

**Issue by pinky-pig** [unocss/unocss#1744]
Heyo!
It's my first time to open an issue in unocss.
I use dynamic classes to generate gird layout ,because I have undetermined number of rows and columns. But it doesn't generate styles for pages, so it doestn't work.

**Dynamic Classes:** 
![image](https://user-images.githubusercontent.com/42307398/195750689-61e60a2b-073f-4314-9ae0-164987b6ab27.png)

**Normal Classes:** 
![image](https://user-images.githubusercontent.com/42307398/195750855-4deded78-3b29-4be8-bc86-b461d96df8ee.png)

After I add `grid-rows-5 grid-cols-5` and HMR, it worked. 
![image](https://user-images.githubusercontent.com/42307398/195750965-73a850f1-2013-48ce-8f2f-c34fc25ba2f3.png)

But restarted, the same issue was reappear.Styles not generated for pages.
I have no idea about that, and just to konw why and find a sulotion to generate styles with dynami classes.Thanks.😊

**Comment by impcyber** [comment]
Hi, @pinky-pig!
Here is dome explanation: https://github.com/unocss/unocss/issues/801

**Comment by chris-zhu** [comment]
I guess you can spend a little time to find the answer in https://github.com/unocss/unocss/issues?q=dynamic+class
