### ISSUE TITLE
WeChat APP has a built-in browser. Using unocss in the "development environment" will make the project inaccessible

### ISSUE THREAD

**Issue by liiivay** [unocss/unocss#1745]
WeChat APP has a built-in browser. Using unocss in the "development environment" will make the project inaccessible;
The 'pnpm run preview' project can be accessed normally in the "production environment".

It is found that there is no problem with unocs of version 0.45.3, which will not cause the above problems.

0.45.29_development: pnpm run dev

![image](https://user-images.githubusercontent.com/62145087/195779702-7800415e-5636-43e5-89a8-a7ce8b6418ad.png)

0.45.29_production: pnpm run preview

![image](https://user-images.githubusercontent.com/62145087/195779593-fccfead8-6c0f-48b9-9d28-52bdd5a725f1.png)

**Comment by sudongyuer** [comment]
Sorry, I don't use WeChat App for dev ,can't help you. But you can left a minimual reproduction
