### ISSUE TITLE
VSCode extension : support electron-vite

### ISSUE THREAD

**Issue by michael-dm** [unocss/unocss#1750]
electron-vite use a special `electron.vite.config.ts` file, it is not currently detected by unoCSS extension.

https://evite.netlify.app/guide/project-structure.html

**Comment by azaleta** [comment]
you can use a separate `unocss.config.ts/uno.config.ts`

**Comment by antfu** [comment]
https://github.com/unocss/unocss/pull/1751#issuecomment-1279907398
