### ISSUE TITLE
use vue-cli meet a compile question

### ISSUE THREAD

**Issue by a982246809** [unocss/unocss#1755]
eviroment :
vue-cli4 , yarn

detail:
in serve mode , sometime style of unocss not work
but i delete node_modules/.cache to yarn serve again , it is work.
or i save (,vue file) of current page , it also work

**Comment by a982246809** [comment]
https://github.com/unocss/unocss/issues/1245#issue-1301570540

好吧   虽然用了这个配置就好了
但只算一种妥协吧
只是配置了不在去缓存了而已

**Comment by mdxiaohu** [comment]
@a982246809 Removed cache, resulting in extremely slow build speed. Changing one line of code takes a few minutes to see the effect .
