### ISSUE TITLE
un-cloak  Conflicts with echarts occur 

### ISSUE THREAD

**Issue by laterdays** [unocss/unocss#1759]
un-cloak  Conflicts with echarts occur 

When the un-cloak is set, echarts assumes that the corresponding parent element is not found，Change the echarts width to 100

nonuse un-cloak
![image](https://user-images.githubusercontent.com/112848218/196033290-d9631640-0a36-42a5-a013-8776306620fa.png)

After using the UN - cloak
![image](https://user-images.githubusercontent.com/112848218/196033217-09fc60d4-dd74-44a8-9dec-bc0c9a09d3e2.png)

How should we solve this problem, or is there an alternative to un cloak

**Comment by sudongyuer** [comment]
Can you provide a minimal reproduction?

**Comment by laterdays** [comment]
@sudongyuer  

[test (2).zip](https://github.com/unocss/unocss/files/9794630/test.2.zip)


I hope you can test it

**Comment by lishaobos** [comment]
> @sudongyuer
> 
> [test (2).zip](https://github.com/unocss/unocss/files/9794630/test.2.zip)
> 
> I hope you can test it

you can replace un-cloak to anthoer attribute, or use [prefix](https://github.com/unocss/unocss/blob/main/packages/preset-uno/src/index.ts#L27])

**Comment by laterdays** [comment]
@lishaobos  Where does anthoer come from， Can you describe how it should be fixed

**Comment by sibbng** [comment]
Related https://github.com/apache/echarts/issues/11155#issuecomment-531539723

You need to call `chart.resize()` when un-cloak is removed. We don't have a hook to run a function right after the removal of un-cloak, but you can use that code:

```ts
  const observer = new MutationObserver(function(mutations) {
    mutations.forEach(function(mutation) {
      // Check if the mutation is a removal of an attribute
      if (mutation.type === 'attributes' && mutation.attributeName === 'un-cloak') {
        // Run your function here
        chart.resize()
      }
    });
  });

  // Start observing the document.body element for attribute changes
  observer.observe(document.body, { attributes: true });
```

**Comment by laterdays** [comment]
@sibbng   The chart appears, but the console warns 

```
Can't get DOM width or height. Please check dom.clientWidth and dom.clientHeight. They should not be 0.For example, you may need to call this in the callback of window.onload.
```

**Comment by sibbng** [comment]
Try `setTimeout(() => chart.resize(), 0)`

**Comment by sibbng** [comment]
And be sure, you are observing the right element. The code above will only check for body element.

**Comment by laterdays** [comment]
@sibbng     observing, should it be set before or after initChart?

**Comment by laterdays** [comment]
observing that the correct nodes have been set up

**Comment by sibbng** [comment]
You can also try initializing the chart in the observer.

**Comment by laterdays** [comment]
@sibbng   initChart in observing, may lead to multiple init?

**Comment by sibbng** [comment]
I don't know. You have to figure out what works for you.
