### ISSUE TITLE
Chrome sends thousands of requests in few seconds and does not stop

### ISSUE THREAD

**Issue by lkj4** [unocss/unocss#176]
This happened to me few times the last days, just three times today. I cannot reproduce it reliably, so feel free to close. I still thought, it might be good to let you know.

Sometimes, my browser starts to dispatch thousands of requests in few seconds and does not stop. Reloading, loading in a new tab, restarting docker-compose, all together does all not help, initially. At some point after I did all of the aforementioned things a few times and waited things got back to normal.

This happened with SvelteKit@next in dev mode.

Inspectors' Netowrk tab looks like this:

![image](https://user-images.githubusercontent.com/84568845/143681028-729ed820-2bde-4403-b898-1cfb1dfb5bee.png)

**Comment by antfu** [comment]
I noticed the same once in Nuxt as well, but can't reproduce either. This is probably a bug, but I guess I will need more information to find the root cause and fix it. Leave the comment below and share your reproduction steps or any more context if you also faced the same. Thanks a lot!

**Comment by ccollie** [comment]
I get this intermittently, but it resolves itself eventually - normally after restarting `vite` once or twice.

**Comment by zhiyuanzmj** [comment]
When I gave my colleague my project address and then restarted Vite, This bug is 100% recurring.
The two computers must open the URL together
