### ISSUE TITLE
unocss vscode extension root configuration item does not support configuring multiple subdirectories 

### ISSUE THREAD

**Issue by zhump** [unocss/unocss#1764]
my project directory

```
├── node_modules
├── package.json
├── packages
        ├── web-demo1
        ├── web-demo2
├── pnpm-lock.yaml
├── pnpm-workspace.yaml
```
<img width="728" alt="image" src="https://user-images.githubusercontent.com/7962067/196161735-eaa8109a-aa89-41bb-9e80-5071c9a1ff23.png">

unocss vscode extension root configuration item does not support configuring multiple subdirectories 
I would like to support configuring multiple folders
```
{
  "unocss.root": "packages/*"
}
```

how can i solve this problem？

**Comment by azaleta** [comment]
web-demo1 or web-demo2
do not support multi entry now.

**Comment by zhump** [comment]
> web-demo1 or web-demo2 do not support multi entry now.

Are there plans to support this feature? tailwindcss is currently supported.

**Comment by dxhuii** [comment]
我也有这样的问题，啥时候能支持？或者这样也行
```json
{
  "unocss.root": ['apps/a', 'apps/b', 'packages/a', 'packages/b']
}
```
数组的形式也行。

**Comment by SKT1yang** [comment]
monorepo项目就是没提示，很郁闷啊 啥提示没有

**Comment by SKT1yang** [comment]
项目运行没问题，{
  "unocss.root": 'config/vite/src/unocss.config.ts'
}
外部vscode插件不生效，

**Comment by tobiasdalhof** [comment]
Do you have different unocss configs across your monorepo?  

If no, why not create a single unocss config file in your project root and pass the config path in your vite config?

```ts
// vite.config.ts in ./example

import { resolve } from 'path'
import { defineConfig } from 'vite'
import UnoCSS from 'unocss/vite'

export default defineConfig({
  plugins: [
    UnoCSS(resolve(__dirname, '../unocss.config.ts')),
  ],
})

```

**Comment by panzhangguo** [comment]
> 项目运行没问题，{ "unocss.root": 'config/vite/src/unocss.config.ts' } 外部vscode插件不生效，

处理了吗
