### ISSUE TITLE
Isolation in embedded apps

### ISSUE THREAD

**Issue by arpowers** [unocss/unocss#1766]
hey there guys, 

just looking for a bit of guidance... we using Uno in an embedded UI (going into customer's websites)... and are looking for a way to isolate CSS classes and prevent interaction between the sites and the embedded ui (could be an issue with standard tailwind style css)

Ideally, we'd just run an obfuscation plugin or option to hash classes on builds, but from what I can tell, that hasn't been implemented yet. For now, we are running the `transformerCompileClass` transformer, but that forces us to add a special class (`:uno:`) on all elements.. which is a bit tedious... 

Is there a better way to do this?

**Comment by chu121su12** [comment]
For basic usecase, there's scope-ing function on the generator.

https://github.com/unocss/unocss/blob/main/test/scope.test.ts
https://github.com/unocss/unocss/blob/main/test/__snapshots__/scope.test.ts.snap

**Comment by arpowers** [comment]
Wouldn't that still allow site styles to interact?

**Comment by chu121su12** [comment]
Note that this and my previous comment is outside code transforming.

Depending how you define interaction, scoped selector should be isolated between each named scoped, just like `.a .b{}` should not affect standalone `<div class"b">`. If `b` had global style or it had parent wth class `a`. you may want to use prefix in addition to scope.
https://github.com/unocss/unocss/blob/main/test/prefix.test.ts
https://github.com/unocss/unocss/blob/main/test/__snapshots__/prefix.test.ts.snap

There's also `layer-x` variant but this may be limited by the browser support

**Comment by arpowers** [comment]
The prefix is a problem because it prevents IDE and linting support for utility classes (tried it!)

If this hasn't been implemented yet, then I'd just leave it as a roadmap suggestion for @antfu or whoever. For now, we have a workable solution (:uno:) it's just not ideal.

**Comment by antfu** [comment]
`:uno:` is required because otherwise, the UnoCSS won't be able to identify what is the class and what is not. consider the following example:

```ts
const classes = 'mx1 grid' // this should be compiled
const article = 'some grid' // this should not

<div :class="classes"/>
```

Until someone can provide a better solution, I don't think it's something doable to be consider as a roadmap

**Comment by arpowers** [comment]
Thanks Anthony. I'm not totally familiar w the Vue internals and all the other use cases you guys deal with so can't comment on feasibility.

Perhaps the approach of "opt out vs opt in" would be workable? 

As an aside, I think Uno has potential to find a niche in embedded and testing apps since it feels much lighter weight than Tailwind.

Overall it's still very nice, and I have much  respect for the work you guys have done and continue to do. It's incredible.
