### ISSUE TITLE
UnoCSS does not scan app.html in SvelteKit project

### ISSUE THREAD

**Issue by AlistairKeiller** [unocss/unocss#1774]
Minimal reproducible example: https://stackblitz.com/edit/sveltejs-kit-template-default-pp7q8l?file=src/routes/+page.svelte

This works in TailwindCSS. Am I missing something from the documentation?

**Comment by jacob-8** [comment]
> This works in TailwindCSS. Am I missing something from the documentation?

Adding a class to the `index.html` file of the [vite-svelte example](https://github.com/jacob-8/unocss/blob/scoped-compilation/examples/vite-svelte) works just fine. It is just SvelteKit where it doesn't work properly. SvelteKit's `app.html` file is never passed to the [transformIndexHtml hook](https://github.com/unocss/unocss/blob/main/packages/vite/src/modes/global/dev.ts#L112) in the global plugin. I'm interested in the solution here also so will try to compare to find the difference between the regular vite-svelte-plugin and the sveltekit plugin.

**Comment by sibbng** [comment]
We added `extraContent` option in https://github.com/unocss/unocss/pull/1963 and it's released as part of v0.48

You can add that in your config and classes in app.html will be extracted. But transformers will not be applied to those files.

```ts
extraContent: {
  filesystem: ['src/app.html']
},
```
