### ISSUE TITLE
[Icons] Dynamic icon loading (from user options)

### ISSUE THREAD

**Issue by arpowers** [unocss/unocss#1780]
hey guys, 
after reading all the docs, nothing is specifically mentioned on how we might handle dynamically included classes. For example, a class that is user defined. 

In our case, we're creating options for users'  so they can set their own icons in UI. It looks like this: 

<img width="1355" alt="Screen Shot 2022-10-19 at 1 39 23 PM" src="https://user-images.githubusercontent.com/308134/196804714-5fa79aff-a139-4584-bbcc-bfeeea400cd9.png">

Is there a way to allow users to include their own classes? ... or should we just create a predefined list of icons and hard code it (so Uno picks that up)

**Comment by chris-zhu** [comment]
> should we just create a predefined list of icons

Try to add the predefined list of icons to `safelist`

**Comment by kleinptr9** [comment]
> > should we just create a predefined list of icons
> 
> Try to add the predefined list of icons to `safelist`

And what should I do when I use to load the whole icons set? For example for flags? when I generate safelist manually, it is not convenient becauase the load time is slow with all hot reload. So is there any way how to load the whole package?

**Comment by userquin** [comment]
You can create a virtual module exporting all flag names (read the json file and extract flag names mapping them to the corresponding icon name), then import the virtual in the component and provide a prop.

**Comment by userquin** [comment]
I have a repo with an example using vite, I Will send the link later

**Comment by AemonCao** [comment]
> I have a repo with an example using vite, I Will send the link later

Thank you for your suggestion! I'm very interested in the method you mentioned, and I would also like to see the example you referred to. Please send me the link and I'll take a careful look and get back to you as soon as possible.

**Comment by clopezpro** [comment]
> Tengo un repositorio con un ejemplo usando vite, enviaré el enlace más tarde

Please send it, I am in the same situation
check https://stackblitz.com/edit/nuxt-starter-xgbti7?file=app.vue
