### ISSUE TITLE
Icon not visible after build on nuxt3, ok in dev mode since last version v0.45.30

### ISSUE THREAD

**Issue by slarrasoain** [unocss/unocss#1782]
After upgrade in v0.45.30 icon are not visible on my project after build.
I can reproduce it with a fresh install of Nuxt3 ~~RC12~~ RC11
Add @unocss/nuxt nuxt module and  @iconify-json/mdi collection
`npm i @unocss/nuxt @iconify-json/mdi`

My nuxt.config.ts
```
 // https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
    ssr:true,
    modules: [
      '@unocss/nuxt',
    ],
    unocss: {
      // presets
      uno: false, // enabled `@unocss/preset-uno`
      icons: true, // enabled `@unocss/preset-icons`
      attributify: true, // enabled `@unocss/preset-attributify`,
  
      // core options
      shortcuts: [],
      rules: [],
    }
})
```

My app.vue
```
<template>
     <div>
        <div class="i-mdi-pencil"></div>
    </div>
</template>
```

All run well with : 
`npm run dev`
But icon is not visible after build
`npm run build`
 with : 
`npm run preview`

**Comment by chris-zhu** [comment]
Can you provide a minimal repo? it works well in my local.

**Comment by AndrewBogdanovTSS** [comment]
It's not working fine, I'm using Nuxt RC12 but still have the same issue. Problem is that icons aren't visible if JS is disabled (without hydration) on the page, for some reason generated CSS is not bound to class selectors
![image](https://user-images.githubusercontent.com/2766448/197998715-54960286-cd64-48b8-9b62-51847421d54e.png)
![image](https://user-images.githubusercontent.com/2766448/197998820-386a99a7-f984-4c4c-a652-aaf19f70384d.png)
![image](https://user-images.githubusercontent.com/2766448/197998877-bc2d6312-ec21-4395-9759-64d697c9ba31.png)

**Comment by antfu** [comment]
Seems to work fine on https://github.com/antfu/vitesse-nuxt3

Can any one provide a reproduction repo?

**Comment by AndrewBogdanovTSS** [comment]
@antfu it's working fine because you disabled **inlineSSRStyles** here https://github.com/antfu/vitesse-nuxt3/blob/main/nuxt.config.ts#L10
I think it should somehow be stated in the docs that it's a known issue with Nuxt 3

**Comment by antfu** [comment]
It's a bug we are investigating on Nuxt.

**Comment by AndrewBogdanovTSS** [comment]
yes, I understand that, but it's blocking correct behavior of UnoCSS including icons rendering

**Comment by antfu** [comment]
In that sense, I would consider this not a bug of UnoCSS. Please track on https://github.com/nuxt/framework/issues/8352 instead.
