### ISSUE TITLE
Latest version of VSCode Extension doesn't work in a Svelte Kit project

### ISSUE THREAD

**Issue by manuganji** [unocss/unocss#1784]
Latest version of VSCode Extension doesn't work. I'm following the configuration in [Svelte Kit Scoped Example](https://github.com/unocss/unocss/tree/main/examples/sveltekit-scoped)

![Screenshot 2022-10-20 at 22 13 08](https://user-images.githubusercontent.com/1709986/197037773-0fa5de40-3212-4e46-a1fd-3a3645712860.png)

OS: Mac OS
VS Code Version: 1.72
Node.js version: v18.11.0

There are no autocomplete suggestions or colour display. I see some errors in the Runtime Status tab in the VSCode extension page.

_Originally posted by @manuganji in https://github.com/unocss/unocss/issues/1683#issuecomment-1286028744_

**Comment by milesingrams** [comment]
Definitely some changes in the VSCode extension causing issues. My VSCode was running 200% CPU and after doing an extension bisect to find the source it turns out it was the UnoCSS extension. Perhaps it's stuck in a loop?

**Comment by azaleta** [comment]
FYI
![image](https://user-images.githubusercontent.com/22554452/197122348-fdfb8b40-27d3-4d8d-8df7-7cae7f3c444f.png)
```
[2022-10-21 12:02:55.512] [renderer20] [error] await is only valid in async functions and the top level bodies of modules: C:/projects/ffgghh/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.516_svelte@3.51.0+vite@3.1.8/node_modules/@sveltejs/kit/src/core/sync/write_types/index.js:28
  ts = await Promise.resolve().then(() => require('typescript')).default;
       ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at new Script (node:vm:100:7)
    at createScript (node:vm:257:10)
    at Object.runInThisContext (node:vm:305:10)
    at jiti2 (c:\Users\208523672\.vscode\extensions\antfu.unocss-0.45.30\dist\index.js:5698:48)
    at C:/projects/ffgghh/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.516_svelte@3.51.0+vite@3.1.8/node_modules/@sveltejs/kit/src/core/sync/sync.js:8:15
```

https://github.com/sveltejs/kit/blob/3edb24022a11e7ff22af124cd953c22452613688/packages/kit/src/core/sync/write_types/index.js#L25-L29

**Comment by azaleta** [comment]
@manuganji 
I tried `unocss/example`, just fine.
I think update  Svelte Kit version may be helpful.
![image](https://user-images.githubusercontent.com/22554452/197309311-258f2933-ff28-4ee2-9099-594249ae08b6.png)

Also some related issue can be found in Svelte Kit (sorry I am not Svelte guy, so I could not get a clear picture of that part)
https://github.com/sveltejs/kit/issues/7300

**Comment by manuganji** [comment]
@azaleta Thank you for replying. I tried updating kit. It didn't help. I'll post back here if I come to know of any other changes in kit that could've caused this issue.

> @manuganji I tried `unocss/example`, just fine. I think update Svelte Kit version may be helpful.

**Comment by NicolasSeiler** [comment]
> @manuganji I tried `unocss/example`, just fine. I think update Svelte Kit version may be helpful. ![image](https://user-images.githubusercontent.com/22554452/197309311-258f2933-ff28-4ee2-9099-594249ae08b6.png)
> 
> Also some related issue can be found in Svelte Kit (sorry I am not Svelte guy, so I could not get a clear picture of that part) [sveltejs/kit#7300](https://github.com/sveltejs/kit/issues/7300)

This doesnt actually work correctly. In the sveltekit example there us just an empty `unocss.config.ts` file that the extension reads. https://github.com/unocss/unocss/blob/main/examples/sveltekit/unocss.config.ts
It doesn't actually load the users config.
