### ISSUE TITLE
Can you specify rules for compiling the props of the component

### ISSUE THREAD

**Issue by jackZmym** [unocss/unocss#1785]
<el-table :data="tableData" border></el-table>
Compiled into
.border {
  border-width: 1px;
  border-style: solid;
}

**Comment by chris-zhu** [comment]
What I understand is that you used the border property of the component, did unocss accidentally generate the border style?

**Comment by jackZmym** [comment]
> 我的理解是你使用了组件的border属性，是unocss不小心生成了边框样式吗？

是的呢

**Comment by chris-zhu** [comment]
Ok, as a workaround, you can add `border` to `blocklist`, if you need to use this property later, you can use `b` instead.
[Playground](https://uno.antfu.me/play/?html=DwEwlgbgBA7gtARgAxQBaJQIwPYCcQCmuUA9AHwBQoksGadmplQA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCCMMUwARgK4zDoCeZF1tAKpYIcAL5x0UCCDgByNiIDGVKnIBQ61AA9IsFBgCGbADbw0mHPkLAiACgTq4cFiYhKA1ieBUYALjgAbTkWaDQoOQBdEidyShoYKgDA-gThCDsASj542gYmVg4ubizo9TFM9SA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g)
