### ISSUE TITLE
Problem with transformer-attributify-jsx and Remix

### ISSUE THREAD

**Issue by AxelBriche** [unocss/unocss#1787]
On Remix framework, when I save (cmd+S), my attributes is converted inside my project files.

Problem presented in video:
https://user-images.githubusercontent.com/1295251/197163635-e95b0ecd-ace0-4f57-9e00-030e9ee82539.mp4

I have uploaded a minimal reproduction project here:
https://github.com/AxelBriche/remix-unocss-bug (key files are `app/routes/index.tsx` and `unocss.config.js`)

Just clone the repo, and run:
```
npm run dev:css
npm run dev
```

Why `=""` is added and visible **inside my real project file** ?
Is this normal or a bug?

**Comment by chris-zhu** [comment]
Because of you used unocss `cli` with `transformer`
