### ISSUE TITLE
Adding tailwind reset  hide button style of unocss

### ISSUE THREAD

**Issue by MuhammadKhizar7** [unocss/unocss#1788]
Adding tailwind reset unocss style is not applied as tailwind reset hide button
```
// app.js
<template>
  <NuxtLayout>
    <NuxtPage />
  </NuxtLayout>
</template>
<script setup>
import '@unocss/reset/tailwind.css'
</script>
```
```
 <button
      type="button"
      class="
        h-10
        px-4
        py-2
        m-1
        text-white
        transition-colors
        duration-200
        transform
        bg-teal-500
        rounded-md
        hover:bg-teal-400
        focus:outline-none focus:bg-teal-400
      "
    >
      button text
    </button>
```

I think it's because of reset style

```
button, [type='button'], [type='reset'], [type='submit'] {
    -webkit-appearance: button;
    background-color: transparent;
    background-image: none;
}

```

here minimum reproduction link 

https://stackblitz.com/edit/github-ncxynv-mogumk?file=app.vue

**Comment by chris-zhu** [comment]
>  https://stackblitz.com/edit/github-ncxynv-mogumk?file=app.vue This is a fail link, can't work.

But i remember that `nuxt3` use `moduels` instead of `buildModules`,
and in your `app.vue` you can remove the `import unocss/reset/tainwind.css` line, just add unocss config to `nuxt.config.ts`  with `preflight` option.
https://github.com/unocss/unocss/blob/bd0286daf073418164bcccfb190ed68d1e08cca2/packages/nuxt/src/types.ts#L18-L23

If you have any question, please fix the  minimal reproduction link first.

**Comment by MuhammadKhizar7** [comment]
@chris-zhu Thanks for point me right direction it helped me fix issue, but it's not in docs it says import CSS file for reset

**Comment by nos-nart** [comment]
@MuhammadKhizar7 how did you fix this, I encounter the same problem which button component's background it's being reset by tailwind reset. I've tried to comment out the css reset in `nuxt.config.ts` still the tailwind reset css file imported somewhere
```ts
// my nuxt.config.ts
unocss: {
    preflight: true,
},
css: [
  '@unocss/reset/tailwind.css',
],
```

**Comment by zyyv** [comment]
@nos-nart Refer to https://unocss.dev/guide/style-reset#tailwind-compat

**Comment by nos-nart** [comment]
@zyyv I even tried https://unocss.dev/guide/style-reset#tailwind-compat before get here It just not work
