### ISSUE TITLE
In the vscode vue template, there is no code prompt when hovering the mouse

### ISSUE THREAD

**Issue by wz20206** [unocss/unocss#1792]
![image](https://user-images.githubusercontent.com/67646124/197392155-cfe6b617-856a-48e9-9912-0bf28541b8c8.png)

**Comment by wz20206** [comment]
In the vue template of the nuxt3 framework

**Comment by chris-zhu** [comment]
Can you provide a minimal repo or more infos? It works fine on my local.

**Comment by wz20206** [comment]
> Can you provide a minimal repo or more infos? It works fine on my local.

![image](https://user-images.githubusercontent.com/67646124/197392565-8a75b1a3-9275-487c-8de9-c1d10cf9664c.png)
![image](https://user-images.githubusercontent.com/67646124/197392579-77dd4f09-243e-4881-8b95-cebfeabf5ce6.png)
![image](https://user-images.githubusercontent.com/67646124/197392594-66e73675-3350-4995-9f5e-9faa4bc752a6.png)

**Comment by wz20206** [comment]
![image](https://user-images.githubusercontent.com/67646124/197392648-707ca4d0-b1d6-4c66-923a-22429cd566bd.png)
![image](https://user-images.githubusercontent.com/67646124/197392664-30859ca7-4cdb-4ed4-b87f-a106ec690f22.png)

**Comment by Readpato** [comment]
What does the output of the UnoCSS plugin says?
In example, you can find it here:

![image](https://user-images.githubusercontent.com/87768087/197397466-b1d6c426-ee7a-4680-bb11-aeed0bf05d76.png)

**Comment by wz20206** [comment]
好像是和自动引入的插件不兼容
![image](https://user-images.githubusercontent.com/67646124/197437634-e5e02920-f9b4-4f37-934c-685306517994.png)

**Comment by wz20206** [comment]
![image](https://user-images.githubusercontent.com/67646124/197437801-19aac4fd-f51d-4ce9-9f01-45aa2c269ce4.png)

**Comment by wz20206** [comment]
It seems that it is incompatible with the automatically introduced plug-in

![image](https://user-images.githubusercontent.com/67646124/197438919-92c76aed-e154-429b-95cf-9c8704227605.png)


This error occurs after the comment

![image](https://user-images.githubusercontent.com/67646124/197439045-edd8dd88-2058-415f-8169-b19195974e87.png)

**Comment by antfu** [comment]
I see. This is because the VS Code extension doesn't inject the `defineNuxtConfig` function. Please use a separate `unocss.config.ts` for now.

**Comment by wz20206** [comment]
How should I configure unocss.config.ts, or do I have a reference template?😊

**Comment by Readpato** [comment]
You can use this as a reference :) I have been utilizing Unocss with a separate config file for a while and it works with nuxt3.
Hopefully it can guide you to create your own!

![image](https://user-images.githubusercontent.com/87768087/197504292-e3983fb7-ee8c-45da-bba8-32174df0f443.png)
