### ISSUE TITLE
Apply css rules based on html data attribute

### ISSUE THREAD

**Issue by mtt-artis** [unocss/unocss#1793]
I'm using Radix-UI and i'd like to apply css rules based on html data attribute.

Is there a syntax or a variant to do so ?

something like this:
```tsx
const A = ({state}: {state: "active" | "error"}) => (
  <button
    data-state={state}
    className='[data-state="active"]:bg-blue [data-state="error"]:bg-red'
  >
    my button
  </button>
)
```

**Comment by therealokoro** [comment]
Hmmmmmm 🤔, this could be very useful you know. I guess this should fall under custom selectors

**Comment by mtt-artis** [comment]
so i made a custom variant in my unocss config

```js
import react from '@vitejs/plugin-react';
import Unocss from 'unocss/vite';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(), 
    Unocss({
      variants: [
        (matcher) => {
          const [, attribute = '', value = ''] = matcher.match(/^\[([^\/]+)\/?(.*)\]:/) ?? []
          if (!attribute) {
            return { matcher }
          }
          const attributeValue = value ? `="${value}"` : value;
          return {
            matcher: matcher.replace(/^\[.+\]:(.*)$/, '$1'),
            selector: (s) => `[${attribute}${attributeValue}]${s}`,
          }
        }
      ]
    }),
  ]
})
```

and use it like this

```jsx
const A = ({state}: {state: "active" | "error"}) => (
  <button
    data-state={state}
    className='[data-state/active]:bg-blue [data-state/error]:bg-red'
  >
    my button
  </button>
)
```

i had some issues if i kept the `=` so i replaced it with a `/`,  i wish someone could make a `=` version 
and I removed the quotes as they might interact with the class string

PS: is there a discord community ?

**Comment by chris-zhu** [comment]
```jsx
const A = ({state}: {state: "active" | "error"}) => (
  const className = state === 'active' ? 'bg-blue' : 'bg-red'
  <button className='{className}'>
    my button
  </button>
)
```
Excuse me for not knowing Radix-UI, but wouldn't it be simpler?

> ps: here is UnoCSS discord community. [https://discord.gg/xagTXneNHd](https://discord.gg/xagTXneNHd)

**Comment by chu121su12** [comment]
The latest tailwind release contains 2 useful variants: [`aria`](https://tailwindcss.com/blog/tailwindcss-v3-2#aria-attribute-variants) and [`data`](https://tailwindcss.com/blog/tailwindcss-v3-2#data-attribute-variants). I'm unsure how this will interact with attributify but they are quite useful

**Comment by mtt-artis** [comment]
i do not know how Radix works under the hood but 
it applies data-attributes on html element and they are not accessible from the tsx.

moreover, it's easier if you have multiple attributes to check

**Comment by mtt-artis** [comment]
@chu121su12 Are these variants already implemented in preset-wind?

**Comment by sibbng** [comment]
This feature is added in https://github.com/unocss/unocss/pull/1816
