### ISSUE TITLE
[unocss] unmatched utility "2xl:2xl:2xl:xl:lg:__container"

### ISSUE THREAD

**Issue by sondh0127** [unocss/unocss#1796]
`container` no longer work if prefix was defined customize `h-container`
![image](https://user-images.githubusercontent.com/62163604/197811221-15859396-434c-404a-bab2-e565044d1c40.png)

```
presets: [
  presetUno({
    prefix: 'h-',
    variablePrefix: 'h-'
  }),
]
```

**Comment by antfu** [comment]
Would be great if you can send a PR with the failing tests.
