### ISSUE TITLE
(feature request): add utility class for zoom css property

### ISSUE THREAD

**Issue by therealokoro** [unocss/unocss#1799]
Hello, y'all.

So I noticed that the css property `zoom` does not have a utility class in unocss. I find this useful and humbly ask if it could be added.
And as an example , It would be useful with the `print` variant.

I came across a situation were i needed to change the zoom level of a page during printing using css.

See implementation using css

```css
@media print {
    .result {
        zoom: 58%;
    }
}
```

See proposed unocss equivalent
```html
<body class="print:zoom-58%"></body>
```

😁😁😁

**EDITED**

So I made some more research and found out that the use of the `zoom` property is kind of discouraged for some reasons. So i can understand why it might have not been added by default to unocss.

Though I still find it useful in some use case 🤷‍♂️

See reference link https://developer.mozilla.org/en-US/docs/Web/CSS/zoom

**Comment by chu121su12** [comment]
You can always use aribtrary rule

[Playground](https://uno.antfu.me/play/?html=DwEwlgbgBADgTmAdgFwFwG0BeB7bBbVAJgAYBSAXSgD4g&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUkNikEA&options=N4XyA)

**Comment by therealokoro** [comment]
@chu121su12 awesome...thanks
