### ISSUE TITLE
Blank page in ios14.3 with vite dev mode

### ISSUE THREAD

**Issue by Jiny3213** [unocss/unocss#1804]
I just init a vite3.1.0 project with vue3 and ts, and i want to preview my page in iphone(ios14.3)

I add uno like this: (like what it say in document)
```
// vite.config.ts
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import Unocss from 'unocss/vite'

export default defineConfig({
  plugins: [vue(),Unocss({ /* options */ })],
  server: {
    host: '0.0.0.0', // I want to preview in my phone
    port: 3000,
  }
})

// main.ts
import { createApp } from 'vue'
import './style.css'
import App from './App.vue'
import 'uno.css' // <=== this line make page blank!!

createApp(App).mount('#app')
```
and i run `npm run dev`, and enter my develop ip

with that line, my page is blank. remove that line, my page work.
it happen in ios14.3, but not in ios15.5
it don‘t happen in pc browser
I want to find out why it happen, bug or compatibility issues or vite problem ?

**Comment by antfu** [comment]
In dev mode, UnoCSS is `fetch` API for HMR, which is not available in the early version of Safari. We would expect developers use the latest version of browsers for development.

**Comment by aewing** [comment]
It looks like this also impacts tauri in dev mode @antfu
