### ISSUE TITLE
Nuxt rc.12 - UnoCSS Inspector is gone

### ISSUE THREAD

**Issue by samydoesit** [unocss/unocss#1805]
Hello since Nuxt rc.12 the UnoCSS Inspector is gone.

Can somebody help?

[Reproduction on Stackblitz](https://stackblitz.com/edit/github-ncxynv-q4oa7f?file=package.json)

Steps to reproduce:
- Open Stackblitz wait until it fully loads
- append `__unocss` to the url.

Expected behavior:
Unocss Inspector should show up.

When you downgrade to Nuxt rc.11 UnoCSS Inspector will be back.

**Comment by chris-zhu** [comment]
Hi, I guess it's a problem with nuxt@rc.12

**Comment by samydoesit** [comment]
I created an Issue there.
nuxt/framework/issues/8522

**Comment by samydoesit** [comment]
Fixed by https://github.com/nuxt/framework/pull/8601
