### ISSUE TITLE
Nuxt - Broken styles after SSR (before hydration)

### ISSUE THREAD

**Issue by Kylyi** [unocss/unocss#1806]
So, I'm not really sure if this issue is related to UnoCSS, Nuxt or Vue itself but here goes.

In some specific cases, after SSR but  before the hydration of Nuxt app, unocss styles get broken for no apparent reason and then they load after the hydration perfectly fine. But there is the short amount of time of flicker effect. I've only been able to reproduce it while having `CPU 6x slowdown` turned on in dev tools. Also, it only happens in **production**!

Steps to reproduce:

1. Clone this repo - https://github.com/Kylyi/nuxt-unocss-css-issue
2. `pnpm i` -> `pnpm build` -> `node .output/server/index.mjs`
3. Check localhost:3000
4. Turn on CPU 6x slowdown in devtools
5. Refresh
6. Now, you should see, for a brief moment before the page gets hydrated, that some elements are missing and background will flicker for some elements
7. It is caused specifically by the inner content of the `<div>` element in `/components/Navigation/Navigation.vue` on line 6.  If you comment it out, everything works perfectly fine

Nuxt rc.12.  Windows 11. Tried chrome, edge and firefox, same result.

![image](https://user-images.githubusercontent.com/19700450/198167411-61fbfd46-9768-43ca-83fb-5ca3de35afa3.png)
![image](https://user-images.githubusercontent.com/19700450/198167501-4d2dd1a1-ddc4-4b2a-bacc-202c90234e95.png)

**Comment by chris-zhu** [comment]
There seems to be an online example here, it's my [personal site](https://zyob.top), built with nuxt@rc.12 and unocss@latest, and the flicker is clearly visible when every refrash. 🥲

**Comment by antfu** [comment]
I think it's a bug of Nuxt, you can work around it with:

```ts
export default defineNuxtConfig({
  experimental: {
    inlineSSRStyles: false,
  }
})
```

**Comment by AndrewBogdanovTSS** [comment]
@antfu you made my day!
