### ISSUE TITLE
How do you pronounce `unocss`? And the history?

### ISSUE THREAD

**Issue by CharleeWa** [unocss/unocss#1814]
Every time I introduce it to someone, I don't read it naturally. So, I suggest adding pronunciation and history to readme.

**Comment by chris-zhu** [comment]
About the pronounce, we read it  as `[u:lɔ] css` `:(乌咯 css  谐音勿怪🤪`.

**Comment by userquin** [comment]
uno is the `number one` or the `first one` in Spanish and also Italian (not sure about second one in Italian, I'm from Spain) ;) 

IIRC Anthony mentions this in some video/podcast

**Comment by CharleeWa** [comment]
That sounds very interesting. Thanks! @chris-zhu @userquin 🌈
