### ISSUE TITLE
Color preview doesn't show up if there is `>` next to it.

### ISSUE THREAD

**Issue by MrFoxPro** [unocss/unocss#1817]
UnoCSS extension: 0.46.1
https://user-images.githubusercontent.com/17229619/198821883-2ed6a1bb-c0ed-47dc-a7ba-4951766f55a1.mp4

**Comment by chu121su12** [comment]
This is by design because we need to match the `>` sign in arbitrary variant instead of splitting it. (ex. `[&>:hover]:something`)
