### ISSUE TITLE
"before:content-['']" doesn't work in class property uno/windi preset

### ISSUE THREAD

**Issue by ErriourMe** [unocss/unocss#1820]
I'm trying to write ul>li menu with dots.

If I used `before:content-['']` like in code below, then nothing happens, there is no class in browser.
```
<li
    v-for="(item, i) in navList"
    :key="`menu-item-${i}`"
    class="text-base text-white flex items-center before:(block rounded-full w-1 h-1 mx-7 bg-white/15 content-[''])"
>
    <NuxtLink :to="item.link">{{ item.title }}</NuxtLink>
</li>
```

But if I'm trying to @apply class, all works fine
```
<style lang="scss">
.menu {
  ul {
    li {
      @apply before:(content-['']);
    }
  }
}
</style>
```

**Why?**

Deps:
* Nuxt 3: rc.12
* @unocss/nuxt: 0.46.1

**Comment by chu121su12** [comment]
The default splitter will split on `'` so `content-['']` usually is not available. You may use `content-none` instead.

**Comment by sail-sail** [comment]
`<div class="after:content-[':']"></div>`
can no work?

**Comment by zyyv** [comment]
try `content-[quoted::]`.

**Comment by zyyv** [comment]
> `<div class="after:content-[':']"></div>` can no work?

try `content-[quoted::]`

**Comment by sail-sail** [comment]
> > `<div class="after:content-[':']"></div>` can no work?
> 
> try `content-[quoted::]`, you can get more infos in #1741.

Yes , It work, Thank You!
