### ISSUE TITLE
[unocss-hmr] TypeError: __vite_ssr_import_meta__.hot.send is not a function

### ISSUE THREAD

**Issue by winchesHe** [unocss/unocss#1823]
import global uno.css in the histoire.set.up
```ts
// src/histoire.setup.ts
import 'uno.css'
```
histoire.config.ts
<img width="540" alt="image" src="https://user-images.githubusercontent.com/96854855/198866189-ee3331e0-8f08-4968-9690-6cc4c8940bef.png">

vite.config.ts
<img width="574" alt="image" src="https://user-images.githubusercontent.com/96854855/198866194-d404bdbb-11cf-468c-927e-ae57eb2e5238.png">

uno.config.ts
<img width="789" alt="image" src="https://user-images.githubusercontent.com/96854855/198866214-71d84395-a668-41cf-8c6e-28f0de5378b7.png">

and run dev can't not find the import.meta.hot.send function
<img width="784" alt="image" src="https://user-images.githubusercontent.com/96854855/198866297-8162c91d-0ab6-4e62-ae94-267312b3a9d9.png">

<img width="971" alt="image" src="https://user-images.githubusercontent.com/96854855/198866344-af295763-0200-4b08-9603-fe5427d442e2.png">

how can i fix that

**Comment by sudongyuer** [comment]
Hi ，hope you can provide a minimum reproduction

**Comment by winchesHe** [comment]
> Hi ，hope you can provide a minimum reproduction

[Idux-interactive-histoire-main.zip](https://codeload.github.com/winchesHe/Idux-interactive-histoire/zip/refs/heads/main)

**Comment by sudongyuer** [comment]
A github repo would be better (  🫥

**Comment by winchesHe** [comment]
> A github repo would be better ( 🫥

https://github.com/winchesHe/Idux-interactive-histoire

**Comment by sudongyuer** [comment]
> > A github repo would be better ( 🫥
> 
> https://github.com/winchesHe/Idux-interactive-histoire

I found that you may need add this line 
![image](https://user-images.githubusercontent.com/76603360/198874994-a0ba5bec-69ed-4b33-a401-10f8d195dfb7.png)

**Comment by sudongyuer** [comment]
Hi , i found that this warning isn't block your code , the above pr can fix it ~

**Comment by winchesHe** [comment]
> Hi , i found that this warning isn't block your code , the above pr can fix it ~

ok，thx~ :-D

**Comment by Hrishikesh-K** [comment]
Facing the same issue with a similar setup, but looks like the above PR was closed without merging 🙁

**Comment by Mehdi-Hp** [comment]
Experiencing the same issue with `"unocss": "^0.50.6"` and `"histoire": "^0.15.9"`
