### ISSUE TITLE
Sorting classes

### ISSUE THREAD

**Issue by MrFoxPro** [unocss/unocss#1825]
Tailwind has prettier plugin to sort classes: https://github.com/tailwindlabs/prettier-plugin-tailwindcss
WindiCSS has this feature in VSCode extension: https://windicss.org/editors/vscode.html#extension-settings

I think it would be nice to implmeent such as IDE extension/prettier plugin/cli command alongside with https://github.com/unocss/unocss/issues/1576.

I would like to implement this feature, however I'm not sure where to start.
Any ideas / drafts?

**Comment by MrFoxPro** [comment]
I would like to implement this feature, however I'm not sure where to start

**Comment by chu121su12** [comment]
Currently the default preset sorting is done through rule orders. Also with help of layering (`uno-layer-x:rule`) you can reorder sections of the css output around (alphabetically by default). In addition, variant and rule have their own sort key you can utilize.

Please find the relevant usages in the codebase:
https://github.com/unocss/unocss/blob/f4954d2a2b2a3dc4ad32d1ea098aab07596c55b1/packages/core/src/types.ts#L153
https://github.com/unocss/unocss/blob/f4954d2a2b2a3dc4ad32d1ea098aab07596c55b1/packages/core/src/types.ts#L230
https://github.com/unocss/unocss/blob/f4954d2a2b2a3dc4ad32d1ea098aab07596c55b1/packages/core/src/types.ts#L352
https://github.com/unocss/unocss/blob/f4954d2a2b2a3dc4ad32d1ea098aab07596c55b1/packages/core/src/types.ts#L357

**Comment by MrFoxPro** [comment]
> Please find the relevant usages in the codebase:

I'm not sure you understood me correctly, I mean sorting inside source code

**Comment by itpropro** [comment]
Just for context, I think @MrFoxPro is referencing to [this feature](https://tailwindcss.com/blog/automatic-class-sorting-with-prettier), which is also available in Windi and would be a great addition to the DX with unocss.

**Comment by chu121su12** [comment]
Thank you and sorry that I missed your point the first time.

> Any ideas / drafts?

Due to the similarity of api, I think you could start from both sides, either via extension or prettier

**Comment by MrFoxPro** [comment]
I checked extension. Btw I'm not sure how sorting should be done at all, if there are variant groups.
Also, I saw that extension is using custom HTMlParser based on REs to get classes, so, it's unclear how to swap utilities in class string or even attributes

**Comment by MrFoxPro** [comment]
WindiCSS uses ast parsing for this purpose.

**Comment by itpropro** [comment]
> Thank you and sorry that I missed your point the first time.
> 
> > Any ideas / drafts?
> 
> Due to the similarity of api, I think you could start from both sides, either via extension or prettier

I would prefer to not force users to use prettier. I think the VSCode extension would be the correct place, maybe the implementation of the transformers would be a good starting point, as they already need to identify e.g. if there a variant groups etc.. Sorting also has to consider the usage of different transformers.

**Comment by HigherOrderLogic** [comment]
> > Thank you and sorry that I missed your point the first time.
> > > Any ideas / drafts?
> > 
> > 
> > Due to the similarity of api, I think you could start from both sides, either via extension or prettier
> 
> I would prefer to not force users to use prettier. I think the VSCode extension would be the correct place, maybe the implementation of the transformers would be a good starting point, as they already need to identify e.g. if there are variant groups etc.. Sorting also has to consider the usage of different transformers.

I don't think transformer will work. Transformer is just transformation when you build your app, it can't format code or check style like `prettier` does.

**Comment by CanRau** [comment]
would love to have this feature in the vscode extension as well 🙏🏼

**Comment by antfu** [comment]
https://github.com/unocss/unocss/commit/da06c6562ddc15447a4eaa7419fdf7cc73ce8249 this commit added a utility to sort the rules, if anyone is interested, feel free to create a eslint/prettier plugin for that

**Comment by JaKXz** [comment]
Thanks @antfu! Curious if anyone can share / confirm their eslint config with `@unocss`, I'm not sure that I'm seeing any linting, but I'm not sure if it's working correctly or if I'm seeing false negatives with this config:

```js
	extends: ['eslint:recommended', '@unocss', 'prettier'],
	plugins: ['svelte3'],
	overrides: [{ files: ['*.svelte'], processor: 'svelte3/svelte3' }],
```

**Comment by HigherOrderLogic** [comment]
Is it feasible to make the plugin read config from `nuxt.config.ts` file as well?

**Comment by antfu** [comment]
> Is it feasible to make the plugin read config from `nuxt.config.ts` file as well?

It's recommended to use a standalone `uno.config.ts`

**Comment by antfu** [comment]
Closing this as we have shipped the eslint plugin for a long while. Currently, we don't have enough bandwidth for a prettier plugin but open to contributions.

**Comment by MrFoxPro** [comment]
So, is it possible to sort in semantic order? For example: positioning first, styling like color and background last
