### ISSUE TITLE
Svelte `class:` regression in 0.46.2

### ISSUE THREAD

**Issue by pheuter** [unocss/unocss#1828]
```svelte
<a
  class:text-gray-800={$page.url.pathname.startsWith('/test')}
  class:bg-gray-200={$page.url.pathname.startsWith('/test')}>
```

UnoCSS is able to extract the class attributes above in v0.46.1 but fails in v0.46.2 with no app config or code changes.

**Comment by chu121su12** [comment]
There's similar test case but it didn't register a fail/update.
https://github.com/unocss/unocss/blob/c93b15d446d2c0c26be3fda9a8af9129ff44fd45/test/svelte-scoped.test.ts#L342

However, most probably the failure is coming from the splitter update to support `data-x` and `aria-x` variants.
