### ISSUE TITLE
`import uno.css` not working only on Safari

### ISSUE THREAD

**Issue by pheuter** [unocss/unocss#1835]
Works perfectly fine in Chrome, appears to be a regression of:
- #618 

My setup:

- UnoCSS v0.46.1
- Svelte Kit v1.0.0-next.531
- Vite v3.2.2
- Safari v16.1

---

<img width="768" alt="image" src="https://user-images.githubusercontent.com/92698/199511955-4cfdec14-8fab-45cb-a0ee-c9962c1fed97.png">

**Comment by Eacolt** [comment]
in my Iphone Safari, When I use ( import 'uno.css')  in main.ts , there is a error log: 
SyntaxError: Unexpected keyword 'import'
why?

**Comment by antfu** [comment]
https://github.com/unocss/unocss/issues/1804#issuecomment-1298094103

**Comment by pheuter** [comment]
@antfu I'm on the latest version of Safari on latest version of macOS.

**Comment by Eacolt** [comment]
My iphone version is IOS14,  but still not work .
