### ISSUE TITLE
Blur class not working (sveltekit, svelte-scoped mode)

### ISSUE THREAD

**Issue by Nico-Mayer** [unocss/unocss#1841]
Hey, I encountered that the blur class is not applying in my svelte project any other class so far worked just fine, only the blur class seem to add no CSS.

Currently, on:
Unocss 0.46.3
Svelte 3.44.0
Kit 1.0.0 next@532

**Comment by chu121su12** [comment]
Please provide minimal reproduction

**Comment by Nico-Mayer** [comment]
Clone this repo `https://github.com/Nico-Mayer/unoBlurBug.git`

Run `npm i` `npm run dev`
