### ISSUE TITLE
using unocss in Angular

### ISSUE THREAD

**Issue by dekathomas** [unocss/unocss#1842]
Hello, do you have any ideas to use unocss in Angular? Because I don't know how to config the unocss in Angular.
Thank you.

**Comment by Nico-Mayer** [comment]
Hey, I am not as familiar with angular, but I think it uses webpack as build tool, so u can try this. `https://uno.antfu.me/?s=guide:Setup+Webpack`

**Comment by zhmushan** [comment]
Here's a [demo of Vite + Angular](https://github.com/xiaoxiangmoe/vite-ng-app-demo). Maybe this would be a good start.

**Comment by dekathomas** [comment]
waw nice, thank you for your help!
