### ISSUE TITLE
Breakpoint config from css variables

### ISSUE THREAD

**Issue by ThorFjelldalen** [unocss/unocss#1847]
Hi! Loving this package!

Color config can fetch from CSS variables, but breakpoints can not. Currently we have to duplicate breakpoints for media queries outside of template. Is it possible to support this in the same way as colors?

Example image: (This does not work)
![image](https://user-images.githubusercontent.com/25323993/199953429-8d0e1bef-8232-454f-b483-aa192432ee74.png)

**Comment by sudongyuer** [comment]
Sounds nice ～

**Comment by lee-citizen** [comment]
Hello, I have encountered the same problem. Have you found a way

**Comment by ThorFjelldalen** [comment]
I have not, currently I just repeat the breakpoints in my list of css variables
