### ISSUE TITLE
The css attribute inset  is not supported on Chrome 86

### ISSUE THREAD

**Issue by menghany** [unocss/unocss#1853]
i am using @unocss/preset-uno rule.
Do you have a better solution?
![image](https://user-images.githubusercontent.com/13767186/200464412-1367c561-1df3-465b-aaa2-8ad0acc5acfe.png)

**Comment by chu121su12** [comment]
Override with [shortcut](https://unocss.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIwDskFMAuAtAAzoB8QA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHShEahRAPQAengKiT4AdADUAJQAJK0ZPmEZdCWDcAC8AHxwAAYJYInDCHQa7KRVMBtbGhwQrEmb23CpWAcXassV5bIiCo3hkXKiSio%2Bg7LC8kYLDYnB4fH4v3%2BnwUkmkfg%2BqDoEnsqVCAEZegAmKGoCRoXB5fYwMCNVqteggXrVVpmFrFP7lJBqQZIIA&options=N4XyA)

**Comment by menghany** [comment]
> Override with [shortcut](https://unocss.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIwDskFMAuAtAAzoB8QA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHShEahRAPQAengKiT4AdADUAJQAJK0ZPmEZdCWDcAC8AHxwAAYJYInDCHQa7KRVMBtbGhwQrEmb23CpWAcXassV5bIiCo3hkXKiSio%2Bg7LC8kYLDYnB4fH4v3%2BnwUkmkfg%2BqDoEnsqVCAEZegAmKGoCRoXB5fYwMCNVqteggXrVVpmFrFP7lJBqQZIIA&options=N4XyA)

https://unocss.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIwDskFMAuAtAAzoB8wA9OBGQFCiSyIobZ5EAcADgB7pRK9RtHjI0mHAUK8SAoQxrNxbKUQCecwfSA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHShEahRAPQAengKiT4AdADUAJQAJK0ZPmEZdCWDcAC8AHxwAAYJYInDCHQa7KRVMBtbGhwQrEmb23CpWAcXassV5bIiCo3hkXKiSio%2Bg7LC8kYLDYnB4fH4v3%2BnwUkmkfg%2BqDoEnsqVCAEZegAmKGoCRoXB5fYwMCNVqteggXrVVpmFrFP7lJBqQZIIA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g

**Comment by azaleta** [comment]
you mean this?(regex should be sort in order) [x,y, other]
```
export default defineConfig({
  rules: [['custom-rule', { color: 'red' }]],
  shortcuts: [
    [/^inset-x-(.+)$/, ([, s]) => `right-${s} left-${s}`],
    [/^inset-y-(.+)$/, ([, s]) => `top-${s} bottom-${s}`],
    [/^inset-(.+)$/, ([, s]) => `top-${s} right-${s} bottom-${s} left-${s}`],
  ],
```

**Comment by menghany** [comment]
> more complex shortcut should be used to handle [xy]. something like
> 
> ```
>         [/^inset-?([xy])?-(.+)$/, ([_, d, s]) => d
>           ? d === 'x' ? `left-${s} right-${s} ` : `top-${s} bottom-${s}`
>           : `left-${s} right-${s} top-${s} bottom-${s}`,
>         ],
> ```

This is a good idea, but in windicss or tailwindcss, the inset syntax is left right top bottom. I think they are not consistent

**Comment by azaleta** [comment]
This is just a sample.
I don't know what's the correct setting of windi or tailwind.
So I  just set as `xy` word meaning. (x for x-dimension -> left/right, y for y-dimension -> top/bottom)

feel free to change the setting value as you demand.

**Comment by menghany** [comment]
Your solution is great.
I mean the @unocss/preset-uno whether should change this rule.This may need to be decided by the project maintainer
