### ISSUE TITLE
vscode selection style（bug or optimize）

### ISSUE THREAD

**Issue by lishaobos** [unocss/unocss#1864]
@antfu 

history: https://github.com/unocss/unocss/pull/1863

sorry, man, i still found some bug or optimize in your commit

😂😂😂

1. when i select this area, can not show anything（i think user just use it, do not need think about touch or select）.

![image](https://user-images.githubusercontent.com/46661044/200773770-b98b0a5b-4085-4351-aa3a-49acf546bebd.png)
<br>
![image](https://user-images.githubusercontent.com/46661044/200773805-e82622de-44c7-48ff-8782-fd7d150eabca.png)
![image](https://user-images.githubusercontent.com/46661044/200773938-9de383df-ffe4-4f26-b64b-67cbff2f2b6b.png)

2. style should be merge

![image](https://user-images.githubusercontent.com/46661044/200776048-78871273-65cc-443e-bf32-705dfb043606.png)

for my commit，this will make it clearer

![image](https://user-images.githubusercontent.com/46661044/200776421-15551a1d-cb60-4058-a8b5-dced98ca9fee.png)

_Originally posted by @lishaobos in https://github.com/unocss/unocss/issues/1863#issuecomment-1308381583_

**Comment by antfu** [comment]
The first one is intentional. The second one is open for PR.

**Comment by lishaobos** [comment]
> The first one is intentional. The second one is open for PR.

hi，for the seconed one，you have changed my pr https://github.com/unocss/unocss/pull/1863/commits/c449060db8a21f50dc238b56fba95908dce78c7d, should i repeat commit ?

**Comment by antfu** [comment]
Let me think a bit, I will fix it. I was doing the refractor to reduce the code complexity.

**Comment by lishaobos** [comment]
> Let me think a bit, I will fix it. I was doing the refractor to reduce the code complexity.

ok, thanks for your work!!!
