### ISSUE TITLE
UnoCSS for VS Code, uno config file

### ISSUE THREAD

**Issue by flahol** [unocss/unocss#1865]
On the extension page
_...Features
Decoration and tooltip for matched utilities
Loading configs from **uno.config.js**, vite.config.js, svelte.config.js, astro.config.js, iles.config.js or nuxt.config.js (or .ts)
Count of matched utilities..._

Is it uno.config.js(ts) or unocss.config.js(ts) ?

**Comment by lishaobos** [comment]
> On the extension page _...Features Decoration and tooltip for matched utilities Loading configs from **uno.config.js**, vite.config.js, svelte.config.js, astro.config.js, iles.config.js or nuxt.config.js (or .ts) Count of matched utilities..._
> 
> Is it uno.config.js(ts) or unocss.config.js(ts) ?

/^(vite|svelte|astro|iles|nuxt|unocss|uno)\.config/

**Comment by lishaobos** [comment]
Both can do
