### ISSUE TITLE
Hot Update is looping infinitely when windicss and preset-icon are used... | SvelteKit

### ISSUE THREAD

**Issue by schietegal** [unocss/unocss#1871]
# Problem
[vite] hot updated: /__uno.css is looping infinitely when windicss and @unocss/preset-icons are used...

```javascript 
"@fontsource/fira-mono": "^4.5.0",
"@iconify-json/ph": "^1.1.2",
"@neoconfetti/svelte": "^1.0.0",
"@sveltejs/adapter-auto": "next",
"@sveltejs/kit": "next",
"@types/cookie": "^0.5.1",
"@unocss/preset-icons": "^0.46.4",
"prettier": "^2.6.2",
"prettier-plugin-svelte": "^2.7.0",
"svelte": "^3.46.0",
"svelte-check": "^2.7.1",
"typescript": "^4.7.4",
"unocss": "^0.46.4",
"vite": "^3.1.0",
"vite-plugin-windicss": "^1.8.8",
"windicss": "^3.5.6"
```

## Reproduction 
**(check the console)**
[https://stackblitz.com/edit/sveltejs-kit-template-default-pvbhjn?file=src/routes/+layout.svelte](https://stackblitz.com/edit/sveltejs-kit-template-default-pvbhjn?file=src/routes/+layout.svelte) 

### Screenshot
<img width="413" alt="image" src="https://user-images.githubusercontent.com/64729700/201387031-456119d1-b144-411a-a4b2-1549813cdec9.png">

**Comment by microdou** [comment]
I encountered the exact same issue!

Rolling back to 0.46.3 resolves the problem.

**Comment by sudongyuer** [comment]
> 

Sorry, why i didn't see the console in this link https://stackblitz.com/edit/sveltejs-kit-template-default-pvbhjn?file=src/routes/+layout.svelte

**Comment by schietegal** [comment]
@sudongyuer I don't think stackblitz has an integrated console, but I'm not sure

**Comment by schietegal** [comment]
> > 
> 
> 
> 
> Sorry, why i didn't see the console in this link https://stackblitz.com/edit/sveltejs-kit-template-default-pvbhjn?file=src/routes/+layout.svelte

I don't think stackblitz has an integrated console, but I'm not sure

**Comment by sudongyuer** [comment]
Ok , i will Investigate it . And also PR welcome ( ^_^
