### ISSUE TITLE
Random exit in cli mode

### ISSUE THREAD

**Issue by FlatMapIO** [unocss/unocss#1882]
Seems to be the problem of `createCDNLoader` function
```js

 function fetchCollection(name: string) {
    if (!supportedCollection.includes(name))
      return undefined
    if (!cache.has(name))
      cache.set(name, $fetch(`${cdnBase}@iconify-json/${name}/icons.json`))
    return cache.get(name)!
  }
```
I'm not sure how `$fetch ` is implemented,  but i've tested the `fetch` in node and it probably doesn't work.

```js
await fetch("https://esm.sh/@iconify-json/carbon/icons.json")
``` 
<img width="695" alt="image" src="https://user-images.githubusercontent.com/1720349/202152207-cd5008f8-a24a-4cf7-9d2c-4cbf477e7a21.png">

There is no problem running unocss with bun and testing the fetch function above

**Comment by FlatMapIO** [comment]
It seems to be a node problem, bun and deno are working fine. https://github.com/nodejs/node/issues/45419

I propose to raise `$fetch` to the try block to let the process know what happened when it exits

**Comment by sudongyuer** [comment]
Nice catch, PR welcome bro ~
