### ISSUE TITLE
Rpx is not converted to rem in Uniapp when using @apply

### ISSUE THREAD

**Issue by weihongl-unimelb** [unocss/unocss#1883]
A shortcut "text4-reg" is defined in unocss config. when I use @apply in scss to refer it, it works with shortcut's raw data which is "font-size: 34rpx;line-height: 48rpx;". 

But in uniapp, rpx is expected to be converted to rem. 

This is a screenshot:
<img width="2017" alt="image" src="https://user-images.githubusercontent.com/53463249/202340736-bad4d988-ce12-477f-a4fd-ed25a5343c93.png">

part of my `unocss.config.js`
```javascript
rules: [
    [/^text-(\d+)$/, ([, d]) => ({ "font-size": `${d}rpx` })],
    [/^lh-(\d+)$/, ([, d]) => ({ "line-height": `${d}rpx` })],
    ["Semibold", { "font-weight": "600" }],
    ["Regular", { "font-weight": "400" }],
    ["Medium", { "font-weight": "500" }],
    [
      /^bg-(.*)$/,
      ([, c], { theme }) => {
        if (theme.colors[c]) return { "background-color": theme.colors[c] };
      },
    ],
    [/^op-(\d+)$/, ([, d]) => ({ opacity: `${d / 100}` })],
  ],
  shortcuts: [
    {
      "title1-sem": "text-64 lh-72 Semibold",
      "title2-sem": "text-56 lh-72 Semibold",
      "title3-sem": "text-48 lh-64 Semibold",
      "title4-sem": "text-40 lh-56 Semibold",
      "text1-reg": "text-56 lh-72 Regular",
      "text2-reg": "text-48 lh-64 Regular",
      "text3-reg": "text-40 lh-56 Regular",
      "text4-reg": "text-34 lh-48 Regular",
      "text5-reg": "text-28 lh-40 Regular",
      "text4-sem": "text-34 lh-48 Semibold",
      "text5-sem": "text-28 lh-40 Semibold",
      "caption1-sem": "text-24 lh-32 Semibold",
      "caption2-sem": "text-20 lh-24 Semibold",
      "caption1-reg": "text-24 lh-32 Regular",
      "caption2-reg": "text-20 lh-24 Regular",
  ],
```
Wondering if there is anyone encountered the same problem, and how to fix it？

**Comment by zyyv** [comment]
```
[/^text-(\d+)$/, ([, d]) => ({ "font-size": `${d}rpx` })],
```
Check this rule, you make it render `rpx` unit.

**Comment by weihongl-unimelb** [comment]
> ```
> [/^text-(\d+)$/, ([, d]) => ({ "font-size": `${d}rpx` })],
> ```
> 
> Check this rule, you make it render `rpx` unit.
> 
> Or you can use this hook to convert it. e.g.
> 
> https://github.com/unocss/unocss/blob/9710504f571e204cd2edc9c2a59024abcf2d0586/packages/preset-rem-to-px/src/index.ts#L20

I intend to render "rpx" unit in unocss cause "rpx" is the basic unit in uniapp, and it will be converted to differnet unit after compiling to different platform based on uni. For H5, it is supposed to be rem. It works fine when I use shortcut as a class name, but in this case, its not.

**Comment by weihongl-unimelb** [comment]
> ```
> [/^text-(\d+)$/, ([, d]) => ({ "font-size": `${d}rpx` })],
> ```
> 
> Check this rule, you make it render `rpx` unit.
> 
> Or you can use this hook to convert it. e.g.
> 
> https://github.com/unocss/unocss/blob/9710504f571e204cd2edc9c2a59024abcf2d0586/packages/preset-rem-to-px/src/index.ts#L20

thx, I will try this hook

**Comment by weihongl-unimelb** [comment]
> There are some presets in UnoCSS community, don't know if it will help you. https://github.com/unocss-applet/unocss-applet https://github.com/MellowCo/unocss-preset-weapp
> 
> Find more at https://github.com/unocss/unocss#community-presets

Thx for your apply, i check it now!
