### ISSUE TITLE
import 'uno.css'  SyntaxError: Unexpected keyword 'import' in Safari

### ISSUE THREAD

**Issue by Eacolt** [unocss/unocss#1887]
I use Vite on development mode,  and open project in my Iphone10 Safari , when I import 'unocss', Safari get Error: SyntaxError: Unexpected keyword 'import', why?
 I found the reason for the error is this sentence:
  `import 'uno.css'`

<img width="407" alt="iShot2022-11-17 23 57 58" src="https://user-images.githubusercontent.com/15901920/202495342-eb235e99-7473-4eea-9a5e-f99d160a9d64.png">

How to solve this problem

**Comment by zyyv** [comment]
https://github.com/unocss/unocss/issues/1804#issuecomment-1298094103
