### ISSUE TITLE
(bug): issues integrating unocss with astro

### ISSUE THREAD

**Issue by therealokoro** [unocss/unocss#1893]
Tried using unocss with the latest version of astro.

I get the following error when I run the dev script.

![image](https://user-images.githubusercontent.com/41494675/202894434-489d453e-6bcb-4fa1-81fb-2aa699c7bfb4.png)

## Reproduction

https://github.com/unocss/unocss/blob/main/examples/astro

**Comment by zyyv** [comment]
According to your error message, have you installed the corresponding dependencies, `@unocss/reset` ?

**Comment by therealokoro** [comment]
Doesn't this come by default with unocss? I don't usually need to install this separately, same as in the example.

**Comment by zyyv** [comment]
Check https://github.com/unocss/unocss#style-resetting
I guess the example has some trouble, you can send a PR to improve it.
