### ISSUE TITLE
Theme colors cannot contain numbers after a char

### ISSUE THREAD

**Issue by fuwwy** [unocss/unocss#1894]
```js
theme: {
    colors: {
      red: {
        50: '#fef2f2', // Works
        100: '#fee2e2', // Works
        full: '#ff0000', // Works
        l40: '#F7A0A0', // Doesn't
        '40l': '#F7A0A0',  // Works
        '40l4': '#F7A0A0' // Also doesn't
      },
    },
```

Edit: seems like the problem is more specific, I've updated the playground with more granular examples
[Playground demo](https://uno.antfu.me/play/?html=DwCwTgBAxgNghgZwQXgEQCMDmBaMBTAE2wFYAGCAd2wBYIQaIBbBsAewFcA7Aw7AZgjpWYHmFQA%2BAFChIsRCgw58RAIylyVWvVrNabLjyIChIvGKkzo8JGiy5eAM3YwYlBtqYsO3XseGiJaXAreVslXhhqDXcGXQh9HyNBfzNAyzkbRXsiKNdNOlivA19k03Mg2WsFO2UaUki3LUK9b0N%2BUoDxIA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCCMMUwARgK4zDoCeZF1tAJIBjAlT6UaMAKpYIcAL5x0UCCDgByNnOFUqGgFAHUAD0iwUGAIZsANvDSYc%2BQsCIAKBAbhwYAC1QQVAAuRG8fOFFbaCpQrwiIymQ48ISfAFYABlCNAGJ0DAAmdEKNElS0gEZM7M181FRCxrKKhPQ7Wxz89BqalrSI2wAWWryAMQB2Okzp-oHNEdsNLsnp2fL5hczh5brVmczDAYUNiJPw859%2BKVi4AG0K69pZCHcASlOryVoGJlYOLjcd6fcjfGAiMSeVpwKjCKy2EJwSoAOkKIJ8wmQWByfkYYFiAHoCdQQMiqH4CXMfAoPuEALrlGkGIA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g)

**Comment by zyyv** [comment]
Hi, you can check this regex.  https://github.com/unocss/unocss/blob/f2fda68c503d623bd18b8baa60e52cd5bcb59dce/packages/preset-mini/src/_utils/utilities.ts#L74-L76

`bg-red-l40` parsed `bg-red-l-40`, Its corresponding configuration is
```ts
colors: {
  red: {
    l: {
      40: '#fff'
    }
  }
}
```
Other configurations are the same

**Comment by fuwwy** [comment]
Thanks, I've updated my config accordingly
