### ISSUE TITLE
bug  在插槽里面使用，vite热更新不生效

### ISSUE THREAD

**Issue by MinMr** [unocss/unocss#1901]
在vue3+vite的项目中，在插槽里面使用unocss热更新不生效
vue版本：3.2.38
vite版本：3.0.9
unocss版本：0.46.5
<img width="1085" alt="1" src="https://user-images.githubusercontent.com/32814481/203332292-8720b597-4c77-4652-8202-2a3077ea8322.png">

**Comment by antfu** [comment]
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)
