### ISSUE TITLE
Is there any example with aspect-ratio?

### ISSUE THREAD

**Issue by Phyrom** [unocss/unocss#1910]

**Comment by zyyv** [comment]
https://uno.antfu.me/?s=aspect-ratio

**Comment by lointain** [comment]
May I ask if there is a similar ?
`
// tailwind.config.js
module.exports = {
  theme: {
    extend: {
      screens: {
        'max-ar-1/1': { 'raw': '(max-aspect-ratio: 1/1)' },
      },
    },
  },
  variants: {},
  plugins: [],
}
`
