### ISSUE TITLE
unocss covered by other css

### ISSUE THREAD

**Issue by llk2yq** [unocss/unocss#1924]
`main.ts`
```ts
import "@unocss/reset/normalize.css";
import "uno.css";

const app = createApp(App);
export default app.use(pinia).use(router).mount("#app");
```

`vite.config.ts`
```ts
import Components from "unplugin-vue-components/vite";
import AutoImport from "unplugin-auto-import/vite";
// auto import components 
import { ArcoResolver } from "unplugin-vue-components/resolvers";

export default defineConfig({
  plugins:[
    vue(),
    Components({
        dts: "auto/imports.d.ts",
        resolvers: [ArcoResolver({ resolveIcons: true, importStyle: "less" })],
    }),
  ]
})
```

`a.vue`
```vue
<a-button class='w-120px'>Test</a-button>
```

`devtool`

.arco-button{
    width:100%
}

.w-120px{
   // covered
    ~~width:120px~~
}

**Comment by lucyanddarlin** [comment]
same in vant

**Comment by lucyanddarlin** [comment]
maybe can use '!important' to solve.

**Comment by llk2yq** [comment]
@lucyanddarlin You're right, but I think there should be a better way.

**Comment by llk2yq** [comment]
@azaleta sry, I'm too careless, you can try `<a-select class="w-120px" />` or `<a-input class="w-120px" />`  or other acro-design  components, most of them have this problem.

**Comment by azaleta** [comment]
Works fine.
![image](https://user-images.githubusercontent.com/22554452/204241692-67de01da-80de-4b13-99c4-ac1cc0e7e8cc.png)
![image](https://user-images.githubusercontent.com/22554452/204241838-f7de0367-5ebd-4b69-9ca7-e09bd20a942e.png)

**Comment by zyyv** [comment]
Or you can use our important variant 
`!w-100` `important-w-100`

**Comment by llk2yq** [comment]
![image](https://user-images.githubusercontent.com/22813922/204417636-40a170ec-721e-4345-bd0b-b96654803e1d.png)
It doesnt work in my case, I will try again and upload a test project later, thx!

**Comment by llk2yq** [comment]
[unocss-test.zip](https://github.com/unocss/unocss/files/10109247/unocss-test.zip)
@azaleta You can run this project, I found that if I add an input to `app.vue`, then other input works fine.

**Comment by azaleta** [comment]
This is a css order problem.

When the css class is in about page. unocss will be loaded first and override by arco. (cause by on-demand)
![image](https://user-images.githubusercontent.com/22554452/204434314-68026ef4-8ddd-4586-bb77-5ba7733954ba.png)


But if you have an input in App.vue. unocss will keep finally.
![image](https://user-images.githubusercontent.com/22554452/204434251-e43efdfa-f91f-4a56-b24a-5baa49f5d574.png)

I think you can avoid this by 3 solutions.
1. use `important` as mentioned.
2. use a wrapper
```
<div class="w-120px"><a-input></a-input></div>
```
3. Or load arco style in main.ts before uno.css (seems you loaded a part of it)
```
import "@arco-design/web-vue/es/message/style"
import "@arco-design/web-vue/es/modal/style"
import "@arco-design/web-vue/es/notification/style"

import "uno.css"
```

**Comment by llk2yq** [comment]
Thx for you solutions.
But I still think there would be a more elegant way.

**Comment by miaojinsing** [comment]
> 或者您可以使用我们的重要变体 `!w-100` `important-w-100`

这是一个极为愚蠢的答案

**Comment by zyyv** [comment]
> > 或者您可以使用我们的重要变体 `!w-100` `important-w-100`
> 
> 这是一个极为愚蠢的答案

我用得着你来评判吗？  你能用就用  不能用就拉倒   能解决的方式多了去了  我只是不费口舌的讲了一直最简单的方式  你现在遇到问题了来抄答案  还嫌答案又不标准  丑人多作怪  那你自己去悟吧
