### ISSUE TITLE
In version 0.47.1, @forward or @use syntax in scss, causing unocss invalid

### ISSUE THREAD

**Issue by lainbo** [unocss/unocss#1929]
In version 0.47.1, `.scss` files use `@forward` or `@use` to import other scss files, and `@apply` in imported files is invalid
```ts
// main.ts
import index.scss
```

```scss
// index.scss
@forward './a.scss';

.foo {
  // this @apply is work
  @apply bg-red-500;
}
```

```scss
// a.scss
.bar {
  // this @apply is invalid
  @apply bg-red-600 text-white;
}
```

**Comment by sibbng** [comment]
Probably because of #7158

Could you try with that:
```ts
 transformers: [
    transformerDirectives({ enforce: 'default' }),
  ],
```

If you are using Nuxt you may need to disable cssnano's mergeRules optimization as shown [here](https://github.com/unocss/unocss/issues/1849#issuecomment-1328233927).

**Comment by lainbo** [comment]
> Probably because of #1923
> 
> Could you try with that:
> 
> ```ts
>  transformers: [
>     transformerDirectives({ enforce: 'default' }),
>   ],
> ```
> 
> If you are using Nuxt you may need to disable cssnano's mergeRules optimization as shown [here](https://github.com/unocss/unocss/issues/1849#issuecomment-1328233927).

Oh thanks. It's working!
