### ISSUE TITLE
✨ Support new shortcut type `DynamicNamedShortcut` or `DynamicShortcutMap`

### ISSUE THREAD

**Issue by jd-solanki** [unocss/unocss#1932]
Hi 👋🏻 

I have been using UnoCSS for my project [Anu](https://github.com/jd-solanki/anu) and it is doing really great ❤️ 

One thing I am missing is support for named dynamic shortcuts.

## Why?

Excluding dynamic shortcuts, we can merge shortcuts easily using `defu` or simple `Object.assign`. However, if we introduce dynamic shortcuts we have no way to override them because there's no key-value pair to override with dynamic shortcuts.

I noticed there's already `StaticShortcutMap` so I think adding `DynamicShortcutMap` will be more convenient for libs.

Thanks.

**Comment by antfu** [comment]
The map is used for faster lookup and better perf. But since dynamic shortcuts can be regex or function based, what do you expect the key to be?

**Comment by jd-solanki** [comment]
Hi,

Glad to hear from you ☺️ 

> The map is used for faster lookup and better perf. But since dynamic shortcuts can be regex or function based, what do you expect the key to be?

The key should be a string just like `DynamicShortcutMap` and the value will be regex/function _(current type)_.

For better understanding let me explain the scenario:

Assume we have shortcuts like in some preset:
```ts
const defaultShortcuts = {
  'a-btn': 'px-3 py-4',
}
```

and we allow users to override the shortcuts as per their needs in the final preset. To implement this feature we just have to accept the object from the user and we can merge two objects:
```ts
interface PresetOptions {
  shortcutOverrides?: Exclude<Preset['shortcuts'], undefined>
}

export const presetFlexible = (options?: PresetOptions = {}): Preset => {
  return {
    name: 'preset-flexible',
   // other...
  shortcuts: options.shortcutOverrides
      ? Object.assign(shortcuts, options.shortcutOverrides)
      : defaultShortcuts
  }
}
```

With this, if the user wants to change how buttons styles are generated:
```ts
presets: [
  presetFlexible({
    'a-btn': 'px-4 py-6' // user shortcut overrides
  })
],
```

Simple, right?

However, this is not the case with dynamic shortcuts where we have to use Array as shortcuts:
```ts
const defaultShortcuts = [
  // dynamic shortcut
  [/^btn-(.*)$/, ([, c]) => `bg-${c}-400 text-${c}-100 py-2 px-4 rounded-lg`],

  // static shortcut
  { 'a-btn': 'px-3 py-4' },
]
```

With the above shortcuts, we can't merge user overrides with default shortcuts via `Object.assign` or `defu`.

However, if we allow adding key _(naming it)_ for dynamic shortcut like:
```ts
const defaultShortcuts = {
  // dynamic shortcut
  'a-btn-color': [/^btn-(.*)$/, ([, c]) => `bg-${c}-400 text-${c}-100`],

  // or we can also prefix `$` to identify its dynamic shortcut (however I don't know if this will conflict with CSS var generation)
  // '$a-btn-color': [/^btn-(.*)$/, ([, c]) => `bg-${c}-400 text-${c}-100`],

  // static shortcut
  'a-btn': 'px-3 py-4',
}
```

Now, with above and our existing `Object.assign` strategy user can simple override button color via:
```ts
presets: [
  presetFlexible({
    'a-btn-color: [/^btn-(.*)$/, ([, c]) => `bg-${c}-500 text-${c}-100 bg-opacity-50`],
    'a-btn': 'px-4 py-6' // user shortcut overrides
  })
],
```

I hope I have provided a clear explanation and a valid feature request.

Thanks for your time.

**Comment by jd-solanki** [comment]
I don't know the inner workings of UnoCSS and how it parses and compiles the style but I will try to make a PR.

Please guide me on the PR.

**Comment by jd-solanki** [comment]
Sorry, I tried to update the code to resolve this issue but I couldn't even find where should I update the code 😆

**Comment by jd-solanki** [comment]
Oh, I found it and made a PR. Thanks :)

**Comment by jd-solanki** [comment]
To resolve the final outcome of this query is properly merging the preset overrides so does uno have utility to merge/override the preset and its options?

If we have a merge utility then we can use that utility instead of defu for merging the shortcuts.

**Comment by jd-solanki** [comment]
After studying unocss types carefully and with help from @zyyv I was able to resolve the query without any need for an additional type.

This is how user can override the preset shortcuts:
```ts
interface PresetOptions {
  shortcutOverrides?: Exclude<Preset['shortcuts'], undefined>
}

const shortcuts: Exclude<Preset['shortcuts'], undefined | StaticShortcutMap> = [...]

export function presetThemeDefault = (options: PresetOptions = {}): Preset => {

  // other


  shortcuts: options.shortcutOverrides === undefined
    ? shortcuts
    : Array.isArray(options.shortcutOverrides)
      ? [...options.shortcutOverrides, ...shortcuts]
      : [...Object.entries(options.shortcutOverrides), ...shortcuts],

}
```

Thanks so much for the inputs and help 🙏🏻 

Regards.
