### ISSUE TITLE
Adding mdsvex to svelte-scoped example

### ISSUE THREAD

**Issue by willpuckett** [unocss/unocss#1936]
Running `npx svelte-add@latest mdsvex` in the [svelte-scoped example project](https://github.com/unocss/unocss/tree/main/examples/sveltekit-scoped) transforms markdown to html, but Unocss doesn't process the files, regardless of whether they have a .svelte.md, .md, or .svx extension. 

Is there an additional setting that needs to be added to either vite.config.js, svelte.config.js, or mdsvex.config.js?

**Comment by willpuckett** [comment]
When I add ".svelte" to the mdsvex extensions list in mdsvex.config.js, the markdown is processed, but it's obviously less than ideal since it means all the .svelte files are being processed as markdown....

**Comment by henrikvilhelmberglund** [comment]
Same issue here, component styles work fine but the MDsveX layout/element styles are not being applied.

I don't have a stackblitz repo but I have a normal smallish repo if that works: https://github.com/henrikvilhelmberglund/Tutorials/tree/unocss (unocss branch)

**Comment by sibbng** [comment]
You can add `.svx` extension in `include` option:
```ts
    UnoCSS({
      mode: 'svelte-scoped',
      include: [/\.svelte$/, /\.svx$/],
```

In my opinion, we should add svx to default list. PRs welcome!

Related code: https://github.com/unocss/unocss/blob/b19f5955112988b7a0f4916fc3273d68e69d159c/packages/vite/src/modes/svelte-scoped/index.ts
