### ISSUE TITLE
自定义样式padding无效

### ISSUE THREAD

**Issue by TTcom** [unocss/unocss#1938]
尝试多种写法均无效
![image](https://user-images.githubusercontent.com/29853303/204764115-8ef4cd0a-9e0d-4176-9f67-4d39f0efd198.png)

**Comment by zyyv** [comment]
Usage error, you can guide [Playground](https://uno.antfu.me/play/?html=DwEwlgbgBADgtARgAy0Ul9kwB6uQJwFMBbVAZ1PgGMBXMgFwHtSB6APgCgoog&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCCMMUwARgK4zDoCeZF1tAJIBjAlT6UaMAKpYIcAL5x0UCCDgByNnOFUqGgFAHUAD0iwUGAIZsANvDSYc%2BQsCIAKBAbhwYAC1QQVAAuRG8fOCowK2FsIlCvCIjhNioYNVCNAEYABkoQDRJwnwUikrLySVoqUIBtfilZCHcASgkBekZmdk4eVoBdIoUWgyA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g)
