### ISSUE TITLE
Unusual RAM usage

### ISSUE THREAD

**Issue by prazdevs** [unocss/unocss#1941]
Hi, I ran into the same issue as #1931 but even with latest version ,the problem still happens in my Netlify CI.

The project is my personal website, code here: https://github.com/prazdevs/praz.dev

And the CI that fails is here: https://app.netlify.com/sites/prazdev/deploys/6387dc5a3bf8ac70cbda6fb0

By building locally on my machine, i get unusual RAM usage of the Node runtime, up to 2.7GB, which is beyond netlify CI limit, probably what causes it to fail.

This is using the nuxt plugin.

**Comment by sibbng** [comment]
Duplicated of https://github.com/unocss/unocss/issues/1931. It's fixed in #1935 but these are not released yet.

For the time being you better stick with v0.46.5.

**Comment by prazdevs** [comment]
mb, thought it was already released 😅  thanks for the fast answer
