### ISSUE TITLE
using runtime, preset-icons does not take effect

### ISSUE THREAD

**Issue by WangQ98** [unocss/unocss#1946]
I tried to use `unocss` in the **CDN** format, and the `runtime/attributify.global.js` is provided in the document, and the attribute can be analyzed normally, but I did not find the preset icons in global.js, and it is arranged according to the document format. It seems like it wasn't analyzed normally, I hope you can get help.

Below is my usage process：

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>unocss test</title>
  </head>
  <body>
    <div id="app" text-2xl color-red>
      <span>text</span>
      <button i-carbon:3d-cursor-alt color-red text-2xl></button>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@unocss/runtime"></script>
    <script src="https://cdn.jsdelivr.net/npm/@unocss/runtime/uno.global.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@unocss/runtime/attributify.global.js"></script>
    <script type="module">
      import presetIcons from 'https://esm.sh/@unocss/preset-icons/browser'
      window.__unocss = {
        // eslint-disable-next-line no-undef
        presets: [
          presetIcons({
            cdn: 'https://esm.sh/',
          }),
        ],
      }
    </script>
  </body>
</html>
```

![image](https://user-images.githubusercontent.com/115619718/205196159-1fb17f4b-779d-4a5f-8549-2a98cff6a16d.png)

**Comment by laterdays** [comment]
have the same problem

**Comment by laterdays** [comment]
in main.ts  

```
import { icons } from '@/****';
initUnocssRuntime({
  defaults: {
    safelist: [...icons, 'w-min!'],
    shortcuts: {
    },
    rules: [
    ],
    theme: {
      colors: {
      }
    },
    preflights: [
    ],
    presets: [
      presetUno({}),
      presetAttributify({}),
      presetIcons({
        extraProperties: {
        }
      })
    ]
  }
});
```

**Comment by sibbng** [comment]
@WangQ98 

1. `attributify.global.js` [already have](https://github.com/unocss/unocss/blob/main/packages/runtime/src/cdn/attributify.ts) the runtime and uno preset bundled into itself. You don't need the first two scripts.
2. You can't combine global and ESM versions. If you need to customize presets, you should initialize your own runtime:
```html
<body>
  <div id="app" text-2xl color-red>
    <span>text</span>
    <button i-carbon:3d-cursor-alt color-red text-2xl></button>
  </div>
  <script type="module">
    import init from 'https://esm.sh/@unocss/runtime'
    import presetUno from 'https://esm.sh/@unocss/preset-uno'
    import presetAttributify from 'https://esm.sh/@unocss/preset-attributify'
    import presetIcons from 'https://esm.sh/@unocss/preset-icons/browser'
    init({
      defaults: {
        presets: [
          presetUno(),
          presetAttributify(),
          presetIcons({
            cdn: 'https://esm.sh/',
          }),
        ],
      }
    })
  </script>
</body>
```

**Comment by WangQ98** [comment]
> @WangQ98
> 
> 1. `attributify.global.js` [already have](https://github.com/unocss/unocss/blob/main/packages/runtime/src/cdn/attributify.ts) the runtime and uno preset bundled into itself. You don't need the first two scripts.
> 2. You can't combine global and ESM versions. If you need to customize presets, you should initialize your own runtime:
> 
> ```
> <body>
>   <div id="app" text-2xl color-red>
>     <span>text</span>
>     <button i-carbon:3d-cursor-alt color-red text-2xl></button>
>   </div>
>   <script type="module">
>     import init from 'https://esm.sh/@unocss/runtime'
>     import presetUno from 'https://esm.sh/@unocss/preset-uno'
>     import presetAttributify from 'https://esm.sh/@unocss/preset-attributify'
>     import presetIcons from 'https://esm.sh/@unocss/preset-icons/browser'
>     init({
>       defaults: {
>         presets: [
>           presetUno(),
>           presetAttributify(),
>           presetIcons({
>             cdn: 'https://esm.sh/',
>           }),
>         ],
>       }
>     })
>   </script>
> </body>
> ```
Thank you for your answer, my icons are working fine now, it was my understanding, thanks again for your help.
