### ISSUE TITLE
Astro intergation - Infinite uno.css HMR update

### ISSUE THREAD

**Issue by Mehdi-Hp** [unocss/unocss#1961]
I've previously used unocss with Vue and I'm pretty familiar with how it works. But not with Astro.  The bug happens even with this simple astro config:

```js
import { defineConfig } from 'astro/config';
import unocss from 'unocss/astro';


export default defineConfig({
	integrations: [
		unocss()
	]
});
```

Result:  

![Screen Recording 2022-12-04 at 17 14 19](https://user-images.githubusercontent.com/8641684/205494468-55c991a5-3cca-4ea5-8adc-6cf6aee95fd9.gif)

It causes high CPU usage and laggy performance.

**Comment by Mehdi-Hp** [comment]
If anyone has this issue, you can block request to `__uno.css` in devtools as a temporary fix:  

```
localhost:3000/__uno.css?*
```

**Comment by sudongyuer** [comment]
Nice catching ! Can you provide a minimum reproduction thx ~💗

**Comment by Mehdi-Hp** [comment]
Sure. Here:

https://github.com/Mehdi-Hp/unocss-bug-reproduction--1961
git@github.com:Mehdi-Hp/unocss-bug-reproduction--1961.git

P.S.
I couldn't reproduce it on StackBlitz!

**Comment by sudongyuer** [comment]
Hey bro , I have tried your reproduction. But the example in unocss , it doesn't recurrent . You can try this https://github.com/unocss/unocss/tree/main/examples/astro .

**Comment by Mehdi-Hp** [comment]
So, I tried unocss in a Nuxt project and the same thing happened. Turns out it's not unocss itself. It's `cssnano`!

**Comment by zyyv** [comment]
> So, I tried unocss in a Nuxt project and the same thing happened. Turns out it's not unocss itself. It's `cssnano`!

Had the same issue a long time ago, but I don't know the reason, and it's not easy to reproduce, it's getting tricky. Thanks for pointing the way, I'll keep watching.
