### ISSUE TITLE
Vue 3 dynamic value for icon not showing

### ISSUE THREAD

**Issue by jasonlim110396** [unocss/unocss#1976]
On vue3, i trying to add custom icon but it not showing.
Example: 
1. Hardcoded by default will show 
`<i class="i-app-next"></i>`
2. If i add on into custom value will not show 
```
const iconList = ['next', 'back'];
<i :class="i-app-"+iconList ></i>
```

Here was my option:

```
  presets: [
    presetIcons({
      collections: {
        // key as the collection name
        app: FileSystemIconLoader("./src/assets/icons", "utf-8"),
      },
      prefix: "i-",
      extraProperties: {
        display: "inline-block",
      },
    }),
  ],
```

**Comment by chu121su12** [comment]
Dynamic values are [not supported](https://github.com/unocss/unocss#scanning).
However when necessary, one option is to use [safelist](https://github.com/unocss/unocss#safelist).
