### ISSUE TITLE
@unocss/nuxt package does not work when autoImports are disabled [with repro]

### ISSUE THREAD

**Issue by louwers** [unocss/unocss#1977]
The error:

```
at eval (./virtual:nuxt:/home/projects/github-4d1z2m/.nuxt/unocss.mjs:3:32)
at async ViteNodeRunner.directRequest (file://./node_modules/vite-node/dist/client.mjs:301:5)
```

https://stackblitz.com/edit/github-4d1z2m?file=nuxt.config.ts

**Comment by louwers** [comment]
To fix, import defineNuxtPlugin here: https://github.com/unocss/unocss/blob/main/packages/nuxt/src/index.ts#L45

Workaround: set `autoimport: false` in plugin settings:

```
  unocss: {
    autoImport: false,
```

and import manually `import 'uno.css';`

**Comment by zyyv** [comment]
You didn't install `@unocss/nuxt` package. Please guide our docs. https://github.com/unocss/unocss/blob/main/packages/nuxt/README.md#installation

**Comment by sibbng** [comment]
@zyyv Yeah, reproduction is missing the `@unocss/nuxt` package but the issue mentioned in the title appears after you install it. Reopening it to track progress 🙏

**Comment by Vincebe** [comment]
Hello

Same error in a custom nuxt module.

Can't build the playground.

Adding `import { defineNuxtPlugin } from '#app'` in index.mjs > defineNuxtModule > addPluginTemplate fix the issue.

Itt was working with 0.46.5
