### ISSUE TITLE
`VSCode` 插件无法提示预置类名

### ISSUE THREAD

**Issue by evanlong0926** [unocss/unocss#1983]
插件无法对预置的 `windcss` 完整做出提示

**Comment by xijaja** [comment]
我也尝试了，插件确实没有任何提示。

**Comment by evanlong0926** [comment]
> 我也尝试了，插件确实没有任何提示。

我虽然没有证据，但它却是事实🥲

**Comment by antfu** [comment]
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by evanlong0926** [comment]
> We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.
> 
> > [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

Ok.

**Comment by heflyaway** [comment]
.vscode > settings.json  add
{
   "editor.quickSuggestions": {
      "strings": true
   }
}
