### ISSUE TITLE
[vscode plugin] cannot resolve config from nuxt.config.ts

### ISSUE THREAD

**Issue by yuusheng** [unocss/unocss#1984]
When using unocss in nuxt3, if I define unocss config in `nuxt.config.ts`, the unocss vscode plugin cannot work.
And when I use `uno.config.ts`, it can work correctly.

**Comment by lishaobos** [comment]
😂😂😂, for my test, vscode plugin only work with uno/unocss.config

**Comment by yuusheng** [comment]
In fact, it can work in vite.config.ts too. But cannot work in nuxt.config.ts. It seems like a bug 😯.
