### ISSUE TITLE
Icon classes are not detected at runtime

### ISSUE THREAD

**Issue by b-will-c** [unocss/unocss#1985]
### Context

I have a custom component that takes a Vue component builder as a prop, to be used for on-demand list rendering in the DOM, depending on the viewport size. If nothing is provided, a default builder is used, generating numeric icons on the fly.

<details>
  <summary>Looks like this</summary>
  <br>

  ```javascript
  withDefaults(defineProps<P>(), {
    right: (i: number) => <CommonCell icon={`i-ri:number-${i}`}/>
  })
  ```
</details>

The cell is just a basic container, nothing fancy:

<details>
  <summary>SFC</summary>
  <br>

```html
<template>
  <div class="cell" flex justify-center items-center>
    <slot>
      <div :class="icon" />
    </slot>
  </div>
</template>

<script setup lang='ts'>
  interface P { icon?: string }
  withDefaults(defineProps<P>(), { icon: 'i-ri:checkbox-multiple-blank-line' })
</script>
```
</details>

### Expectation

Have the component class parsed and processed at runtime or during the compilation process, detect any matches, download what's needed, and generate the CSS required for that icon to pop up in the DOM.

<details>
  <summary>Intended usage</summary>
  <br>

```html
<component 
  v-for="i in 2" 
  :is="right(i)" 
/>
```
</details>

### Reality

Nothing is detected, CSS classes are empty, no icons to be found on the page. 🤷🏻‍♂️ 

### Research

A few other issues here, relating to dynamic imports, have mentioned `safelist`-s and manual collection specification. Couldn't quite figure out what to indicate, where precisely and how exactly, though. Any additional pointers would be appreciated.

### Workaround

Manually create 'fake' attributes to trick the detector into thinking that the icons are to be used. Quite an annoying thing to do, and only possible for a relatively small (8 icons, in my case) set of these. Utterly impractical for anything bigger.

<details>
  <summary>Current usage</summary>
  <br>

```html
<component 
  v-for="i in 2" 
  :is="right(i)" 
  icons="i-ri:number-1 i-ri:number-2"
/>

<template v-if="smPlus">
  <component 
    v-for="i in 2" 
    :is="right(i+2)" 
    icons="i-ri:number-3 i-ri:number-4"
  />
</template>

<template v-if="mdPlus">
  <component 
    v-for="i in 2" 
    :is="right(i+4)" 
    icons="i-ri:number-5 i-ri:number-6" 
  />
</template>
```

It does look a bit nicer with the auto-preview though, I'll give you that:

![image](https://user-images.githubusercontent.com/66522734/206909350-5287ec29-8927-41e7-a7d0-fe793c1cfc66.png)

</details>

--

Is there anything that I'm missing here? Or would it require some inner refactoring?
<br>

**Comment by antfu** [comment]
https://github.com/unocss/unocss#scanning
