### ISSUE TITLE
Question: Possible to inline CSS similar to Tailwind?

### ISSUE THREAD

**Issue by austin-meadows** [unocss/unocss#1990]
Hey everyone,

Something that I've been doing with Tailwind is inline-ing `@tailwind` directives in a `<style>` tag for my SPA. This allows all CSS for the application to live here, and no CSS files are generated.

```html
<!-- In index.html --> 
    <style type="text/css">
      @tailwind base;
      @tailwind components;
      @tailwind utilities;
    </style>
```

I was wondering if something like this was possible with Uno? I couldn't find an example - most want me to import uno in my app's entry point, but this produces a CSS file. I'd like to avoid installing an inline-ing package if possible.

Thanks!! 😊

**Comment by antfu** [comment]
Also related: https://github.com/vitejs/vite/pull/8400
