### ISSUE TITLE
transformerVariantGroup doesn't expand container query variant correctly

### ISSUE THREAD

**Issue by peter50216** [unocss/unocss#1992]
Currently `@md:(p-2 m-2)` in class is expanded into `@md:p-2 md:m-2` by transformerVariantGroup, but should be `@md:p-2 @md:m-2`.

**Comment by Hongbusi** [comment]
`transformerVariantGroup` does have this problem.

But using `presetUno` to preset `@md:` doesn't work, you can use it with `md:(p-2 m-2)` and there is no problem.

**Comment by peter50216** [comment]
The `@md` variant is the [container query](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Container_Queries) variant, not media query variant, and is supported (experimental) in preset-mini. See https://github.com/unocss/unocss/blob/main/packages/preset-mini/src/_variants/container.ts#L13.

**Comment by Hongbusi** [comment]
Oh, so that's it.😂
