### ISSUE TITLE
How to change the default rem value

### ISSUE THREAD

**Issue by xu-Aurora** [unocss/unocss#1994]
The default is 1=0.25rem, I would like to configure it to 1=1rem, how do I configure it?

**Comment by zyyv** [comment]
Like this [Playground](https://uno.antfu.me/play/?html=DwEwlgbgBALgpgDxgWgEwD4BQUoHsB2yIcAtgIb4hQDtUY%2BAzjBTDVAGYCuANtwJ5QAxpya4SYAF5kARtziZgAenAR0QA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCCMMUwARgK4zDoCeZF1tAKpYIcAL5x0UCCDgByNiIDGVKnIBQ6pQSrxKIAEoBROAF44AegAUAWgD8AbQA6AOifIAugGoAlPotEmqgAHpCwKBgAhmwANvBomDj4hMBEVgjqcOSUNDBUAFxwDvy5whBWPnw5tAxMrBxc3BUeJJnkELoUEErUBXBWDTE%2BZgB8iG1Zgy6oWHXULujQRpFKABZWVsDDpmMZWftw2li6cABukTFsqGZwwA4AjB4T%2B1z955fXAGSfcDDcYKgIOgzhcrmZTOY5LpmFgiHI4N84PpjC4YNQYFZ3lcfD5ngc7o8bljUC5KGAYitUFZkUYyFYAPp8e7bMYAAwAJAgwPc4AAqOAAFjE%2BlZuIOYjF4laEvUQA&options=N4IgzgLgTglgxhEAuAZgQwDZgKYBoTRoB2YKA9lALbLpbYC%2BQA)
