### ISSUE TITLE
When I use unocss, the DOMContentLoaded events for window and document objects not working

### ISSUE THREAD

**Issue by lovefishs** [unocss/unocss#1995]
version

- node.js v16
- vite v3.2.3
- unocss v0.47.5

entry file `main.js`

```js
import 'uno.css'

console.log('test') // output: test

window.addEventListener('DOMContentLoaded', function () {
  console.log('page loaded') // no output, no run
})
```

my fix

- replace `DOMContentLoaded` with `load` event, is working
- remove `import 'uno.css'`

why? how?

**Comment by zyyv** [comment]
I tested it, and it only happens in development.

**Comment by lishaobos** [comment]
or you can use import('uno.css') instead of import, DOMContentLoaded is work.
