### ISSUE TITLE
before伪元素无法生效

### ISSUE THREAD

**Issue by TTcom** [unocss/unocss#1998]
before伪元素无法在content中设置内容
[https://uno.antfu.me/play/?html=FAHgJglgbgBARgUwGYHsBOCBcBjFA7AFwUIFoByAZgCYAWCs%2BZdLACxIEYAGABwA9HUGTHAA2KbAGsBzTAHcSFHv0SCscAOYkMYaULi6sAbQCGcAM4oRAVyIBeAET2AugZwlRVhAD5gMGPhIwBABbYzwdAHaYCDwzAjCCGCikKxERAE8YbCs4lGCIAC9TEQRQAHpIKC8gA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUkNikEA&options=N4XyA](https://uno.antfu.me/play/?html=FAHgJglgbgBARgUwGYHsBOCBcBjFA7AFwUIFoByAZgCYAWCs%2BZdLACxIEYAGABwA9HUGTHAA2KbAGsBzTAHcSFHv0SCscAOYkMYaULi6sAbQCGcAM4oRAVyIBeAET2AugZwlRVhAD5gMGPhIwBABbYzwdAHaYCDwzAjCCGCikKxERAE8YbCs4lGCIAC9TEQRQAHpIKC8gA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUkNikEA&options=N4XyA)

**Comment by zyyv** [comment]
Check those usage demos,
https://github.com/unocss/unocss/blob/92d2470f5e6cd96657ca126aeb8ba017e6b02650/test/assets/preset-mini-targets.ts#L618-L626

**Comment by TTcom** [comment]
> Check those usage demos,
> 
> https://github.com/unocss/unocss/blob/92d2470f5e6cd96657ca126aeb8ba017e6b02650/test/assets/preset-mini-targets.ts#L618-L626



> Check those usage demos,
> 
> https://github.com/unocss/unocss/blob/92d2470f5e6cd96657ca126aeb8ba017e6b02650/test/assets/preset-mini-targets.ts#L618-L626

thank you
