### ISSUE TITLE
Classes are not 'added' with @nuxt/content

### ISSUE THREAD

**Issue by MLoth** [unocss/unocss#2005]
**The issue**
When you add classes in HTML of an `.md`-file in a Nuxt project, the classes are not added.
Maybe these classes are not being [scanned during the build](https://github.com/unocss/unocss#scanning)?
E.g.:
```md
---
title: 'Some content'
description: 'Demo article or whatever'
---

# Markdown

<div class="h-64 text-pink-600 bg-red-100">Test with some UnoCSS classes</div>
```
Those classes are not applied, except when you reuse a class you have elsewhere (in some .vue file).

**Reproduce**

1. Create a Nuxt project.
2. Add unocss.
3. Add @nuxt/content
4. Paste the example given above in the content folder.

**Q**: Is this a bug, is there a common workaround or am I doing something wrong?

**Comment by sibbng** [comment]
Related #1947
Can be fixed by https://github.com/unocss/unocss/pull/1963

> Q: Is this a bug, is there a common workaround or am I doing something wrong?

You can add these classes to `safelist` option.

**Comment by MLoth** [comment]
My bad, I didn't look at the discussion, only in the issues.
I thought about using the `safelist`, but that's not really a scalable solution...

Closing this as a duplicate to #1947 and will check there later on. Thanks!

**Comment by sibbng** [comment]
It's ok. Let's keep that open, so others can see it 😉
