### ISSUE TITLE
Decimal values not working in attributify mode

### ISSUE THREAD

**Issue by toniengelhardt** [unocss/unocss#2006]
Not sure if this is a limit of parsing the attributes or a bug, but e.g.

```html
<div ml-1.5>Scootz a bit</div>
```

doesn't work, while

```html
<div class="ml-1.5">Scootz a bit</div>
```

is working.

**Comment by Hongbusi** [comment]
Regex that handles attributes, will not match decimal points.

See https://github.com/unocss/unocss/blob/main/packages/preset-attributify/src/extractor.ts#L12, this should be a bug.
