### ISSUE TITLE
Is it possible to set a maximum width for containers based on breakpoints in config?

### ISSUE THREAD

**Issue by ErriourMe** [unocss/unocss#2007]
I have a config:

```
theme: {
    breakpoints: {
      sm: '640px',
      md: '768px',
      mg: '880px',
      lg: '992px',
      xl: '1200px',
      '2xl': '1536px',
      fhd: '1920px',
      '2k': '2560px',
    },
    containers: {
      sm: '620px',
      md: '760px',
      mg: '840px',
      lg: '980px',
      xl: '1100px',
      '2xl': '1200px',
      fhd: '1200px',
      '2k': '1200px',
    },
    ...
}
```

In bootstrap I could set it with sass variable `$container-max-widths`. Then, if I have a screen size of 992px, `.conainer` has a maximum width of 980px.
Can I get similar logic here and how is it possible?

**Comment by sherif414** [comment]
It's not what you are looking for but you can make the width dynamic to 90vw and max width 1200px

**Comment by christhofer** [comment]
I've been searching for this too.

I think we just need to define it ourself, I use shortcuts for this.
```js
// using shortcuts
shortcuts: [
    container: 'mx-auto w-full sm:w-620px md:w-760px mg:w-840px lg:w-980px xl:w-1100px 2xl:w-1200px'
]
```

**Comment by pacho26** [comment]
It's possible. You need to set it like this:

```
containers:{
      'sm': '(min-width: 640px)',
      'md': '(min-width: 768px)',
      'lg': '(min-width: 992px)',
      'xl': '(min-width: 1200px)',
      '2xl': '(min-width: 1536px)',
      // lt - less than values
      'lt-sm': '(max-width: 640px)',
      'lt-md': '(max-width: 768px)',
      'lt-lg': '(max-width: 992px)',
      'lt-xl': '(max-width: 1200px)',
      'lt-2xl': '(max-width: 1536px)',
    }
```

**Comment by ErriourMe** [comment]
> It's possible. You need to set it like this:
> 
> ```
> containers:{
>       'sm': '(min-width: 640px)',
>       'md': '(min-width: 768px)',
>       'lg': '(min-width: 992px)',
>       'xl': '(min-width: 1200px)',
>       '2xl': '(min-width: 1536px)',
>       // lt - less than values
>       'lt-sm': '(max-width: 640px)',
>       'lt-md': '(max-width: 768px)',
>       'lt-lg': '(max-width: 992px)',
>       'lt-xl': '(max-width: 1200px)',
>       'lt-2xl': '(max-width: 1536px)',
>     }
> ```

It doesnt work for me :(
Config even doesnt applied to uno. Can you provide full config for example?
