### ISSUE TITLE
Error in installing unocss using pnpm

### ISSUE THREAD

**Issue by Ryongyon** [unocss/unocss#2008]
[![4PQtE.png](https://i.328888.xyz/2022/12/18/4PQtE.png)](https://imgloc.com/i/4PQtE)

**Comment by impcyber** [comment]
@Ryongyon 
To avoid this annoying message you can add the following code to `package.json`:
```json
  "pnpm": {
    "peerDependencyRules": {
      "ignoreMissing": ["vite"]
    }
  }
```
