### ISSUE TITLE
[transformer-variant-group] Not parsing correctly when question mark is added

### ISSUE THREAD

**Issue by dungsil** [unocss/unocss#2013]
Adding `?bg` to display the icon as background doesn't seem to parse the variant group correctly.
If I remove `?bg` or write `checked:i-hericons:check?bg` separately, it works fine.

my config (shortcut): 
```js
[
        'checkbox',
        [
          'appearance-none flex-shrink-0 inline-block w5 h5 p0 m0 border border-ui rounded',
          'bg-white bg-origin-border c-indigo-600 select-none',
          'checked:(border-transparent i-heroicons:check?bg bg-current bg-size-full bg-no-repeat bg-center color-adjust-exact)',
          'focus:ring-indigo-500'                  //  ＾
        ].join(' '),
      ],
```

log: 
```bash
WARN  [unocss] unmatched utility "color-adjust-exact)" in shortcut "checkbox"    
```

**Comment by zyyv** [comment]
> WARN  [unocss] unmatched utility "color-adjust-exact)" in shortcut "checkbox"    

For this log means we didn't have `color-adjust-exact` rule.

Can you provide a playground about your config? ([https://uno.antfu.me/play/](https://uno.antfu.me/play/))

**Comment by dungsil** [comment]
@zyyv 

`color-adjust-exact` is a custom rule I added.

And this is my config file: https://uno.antfu.me/play/?html=DwSwdgDgrgLgBDAnhApgXgEQGMAWKsDWARgPYAeGcWANgIYDO9mu%2Bx5lA9AHxA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAHU8aWWwCGuOlmggMUACLBaE3gDd6aqJu279ANXXtNMAOJQIXMJQC%2BcLB4gcADkXLgQEnR0wUhIGAAekLDo2OpcADbwmDj4RCTApAAUyMLyjHQAXHAA2lSlokoqxXWoctjpBQAWMFVY6ukMsqg%2BAJRDbQosbJw8fPzNra1006ZVbFwY4-U48RhoAPK46fxrUBtbbTtVwWjqMOoAtMHjo%2BMiCpLSC4uXwPHXzxaqCk6XSGFMwGkVRKP1QwU6%2BggwCkWgeEHSaGC0KBPwkCIkAGsKjjYcEADx0MykODxEDpLQAXgARN0YGAKgB6DkAd15ADpuQBmPnQUgcgBMAAZpRzKaQmXBucA0DBOsyAIwYEAKhFdGAarUK976CxMOhgcEwABKd0hzPiAFllQBNJ1oOB6RgKszADDcgBCEHizMlcFDUrgUqZAD4yWA7p1-MBQczuZ1gDAMAqcKCHmcwcyMBZwmg0Aq0MyHeqAGx8gDskrrcAArHzxQBOQXqdVwHuh0N93t8gAs6uH6QeAA44JPu72wwv1Q91SOx2GJ8OHsO54OB0PR5uVweADLT9XivnNyfV9J1tudh53jtdnu7%2BdHteSgBaCokHTAeYZBghbFhApZMhysaylS0aArCwwXD4LxjFQAC6Vg2DoUB6FAlQ1C0GhaFhOFGCY5j0IUYxwFycAEAAynRcCAAujgA4g3AAAGAAC6hgGAxzsYAOh1wAAquE9GMYAHGuABprcCACmzgAANQR1hEXYUCOM4uBuB4XiUeQ1EcnAZhOMALhwKQ2lgIAIuNwIANQOAJVjgAGq3AgAYQ3AgAR44AMTVwIAFqtoWoCJ6Niiw6JpABi6ggMmJyIDidA2FUtTwfpcCACdDgA4E3AgCAE3ZgAYLYAKU1wIAD8uAB1LJIhEyAAKtCZrgtxQO66kmRwYJMnB8HBFVjAYLVTiYpQZU0YAL8uAIw9RWlUlwQPDxfEYA8dD8MsWptaS-odLgBIOuoEh0QtmYgKFxAwMtPzBPNi0gA8XDAMdizBFaEAcBAMAQDdrTBEyAASGDpBYvASOocAAHIYBsrUXHCTJ0RgpAQBgIliGDZXvUwvFgnAdEGHArhPemEhAxgECIxNTKA09EDozYcAANJWkT7VMpt6SkGEWM48idOkkyKMzbR6LQHAACiIAQAAVsAHMnZD0Ow-DgvC2LEu3VLMNw8JYjo-wICPekitvXFqIMOwWCvahfIi0iuCFM8IQoYsSFUPbqD5vQCUtNUwQgtAU1oCLXDLA8CRbUdekICENB4DADye1A3u%2B8sWIhIHpjBHAPjoW7wQcKQc3AAAXrNWAZOk1uh5nW0EuZni1Tn%2BcJ8E6rSgApL2Tcp2nsjp6gdCdNAMASDweGJa0NGABrjgAf3YABh2ZXAgAuC4AGe2ACVDcCAC7jgAhnRnWcPJgYCqsu1uZ9n5nqPwDzNpKwSd607ub9vu-ivvm9HyfDfn5fqDuxIDyZvEwchJ-T9TmlBfcYH9LrXT0h7B4ADJxALfjUSBCJ1CYCgPvf%2B1gT7tlgSAyBfEtoYB7hifQqCoHoNPlgt2HIAB6hRHr1X0AAHzQMAH0mARhgIACQcj0oUaoekzCoRGHABk0YOLsIQGYHwJDj4PEFNKdi6cWg0UAATjgAPpcADWdgAHpYzoXUEdAJC0G6vvbkDwdHpDgJ0ExRdgEZxRPcPARCIHGNMR6dQ8QHjcjrPEMxIA3FpGetYxRBlAAvc4AG%2BXAAwjeNK%2BwQ1oEn3iFSOZ9QyfxUAUCADxqzSnMRACwUAKjJNqqkwBr9sH-Xqg-bOaYMxw27kgiA3I4B0BABUbStU9gPCZtYxYH9eoPDwPgFBECwD8GnGAeIw4GlNNGQ3AJXTonqA4N9OJh0yGhm-pHRpcBP5XU6VfHEwQ8BgB4K9IepJpoYCcJoCQs1wj4EVJY0E1B4iCmoPwcUcBaHIPedAZBYC4AtMwGgB4IB3Q1LQHUuaIBXpwkaRUNZEKoUhB0P3SoHz9C9IKTDFZJszYWytjbcYcD3YHJ4O46wvEHGIrBPEfwVKo7ojMjxdUMzdmkjxOCAkj14jHKRmci5uArkPBuXDLAtLu7sHWg8UMeA1qzWahEAkipmzmKVWAUMIBQyoqgF8uhMcrp-KrgChFB93HpkzO87O0ACh4AeJquAcKvGbPRUwzFGTQwMDBKYQVxAMBGrZYSPYFQaHfLRYRc0ThurwE3v3KAtBNLmprgXIu5jETImkGiDEeT8QEgAPxZ3jeEPMGALR3HjVczS%2BhNl8xjkguOkck4wBGNi82eA8XBFtq0QlHss2ctJWcgZIRaDpFtBYGlCQ4BVJAHQKOEaK2kEZcy9%2BeyOAwFwNyia0r7EmKpXAWtcxp3lq1ROqdZbMxatGeMoZbzbWat%2Bf8tpwKGmdFqcYxpRrN6VLNT3HJFRH6kJfka%2BJKy7UJHWUEOFJ6K1bPATiU2zbLYpzbQS7By7cAPHDiAJw-BylOsKa6rJ37N4pMxQ2JJJqqk7PTqMJAQA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g

**Comment by dungsil** [comment]
If you look at the outputted CSS, you can see that the checked variants are not applied and applied to the base class.
