### ISSUE TITLE
vscode: `defineNuxtConfig` not defined

### ISSUE THREAD

**Issue by cpreston321** [unocss/unocss#2018]
For some reason this was marked as resolved ? https://github.com/unocss/unocss/issues/1665

but this has not been resolved. Still errors out. 

<img width="841" alt="image" src="https://user-images.githubusercontent.com/6619884/209050225-ff42e78f-895b-4f20-b914-5584f66a32ec.png">

<img width="841" alt="image" src="https://user-images.githubusercontent.com/6619884/209049984-538b6668-34ce-4211-86cb-eef752886aef.png">

**Comment by nandordudas** [comment]
Until then, add the import of `defineNuxtConfig` and reload `VSCode` as well.

```diff
+import { defineNuxtConfig } from 'nuxt/config'
```

**Comment by lishaobos** [comment]
Did you installed dependencies?

**Comment by nandordudas** [comment]
@lishaobos yes.

I didn't try without dependency installation.

**Comment by cpreston321** [comment]
@nandordudas I already do! Just doesn't work of out box with a default starter nuxt app.

**Comment by nandordudas** [comment]
I'm using VSCode with devcontainer. I made the previous change and rebuild the container after that - VSCode reload maybe enough natively (host: windows, remote: ubuntu). After the container has been reloaded, fresh installation started.

Before this change I got the same error message which is mentioned but not after.

I'm using a postinstall script which runs `nuxt prepare`.

**Comment by nandordudas** [comment]
I will provide a short recording tomorrow (now +6-7 hours).

Don't forget to reload UnoCSS and check its results on extension outputs.
