### ISSUE TITLE
Attributify preset does not work with svelte-scoped

### ISSUE THREAD

**Issue by Suyashtnt** [unocss/unocss#2019]
the title says it all
minimal repro: https://github.com/Suyashtnt/attributify-scoped-repro

screenshots
![image](https://user-images.githubusercontent.com/45307955/209329096-1139493b-c8e6-466c-bae0-c53705eeb6fb.png)
![image](https://user-images.githubusercontent.com/45307955/209329186-2f62cc16-bb0e-4e62-a97e-cfff483c98eb.png)

~~(unrelated, but why does typescript complain even though I've updated app.d.ts?)~~ Docs seem to be outdated, hmm

**Comment by MahmoodKhalil57** [comment]
I also cant seem to add attributify to svelte scoped, can someone provide an answer?

I see here in the original proposal, there was no solution for svelete-scoped and attributify, but I was hoping this got fixed by now
https://github.com/unocss/unocss/issues/1676

**Comment by jacob-8** [comment]
Hey @MahmoodKhalil57, we've just released an updated [Svelte Scoped package](https://unocss.dev/integrations/svelte-scoped) and in those docs, after getting setup you'll notice that in the [presets support](http://localhost:5173/integrations/svelte-scoped#presets-support) section we say you that you can achieve attributify functionality by adding the [unplugin-attributify-to-class](https://github.com/MellowCo/unplugin-attributify-to-class) Vite plugin (set the include option to `attributifyToClass({ include: [/\.svelte$/]})`) before the Svelte Scoped vite plugin. If you still care about this feature, feel free to give that a try and leave us some feedback on use in the wild.
