### ISSUE TITLE
JIT ambiguous values support

### ISSUE THREAD

**Issue by chu121su12** [unocss/unocss#202]
https://tailwindcss.com/docs/just-in-time-mode#arbitrary-value-support
(sorry, no direct anchor link in the docs)

As per docs
```html
<div class="text-[var(--mystery-var)]">
```
vs
```html
<div class="text-[color:var(--mystery-var)]">
```

> The supported types are:
    - \`length\`
    - \`color\`
    - \`angle\`
    - \`list\`

/cc @userquin #124

**Comment by antfu** [comment]
I kind of prefer to have `text-color-[var(--)]` which I think we do support some of them. Also, I would like to encourage users to create their own rules for specific needs, since we made it fairly easy in UnoCSS, and even with Talwind's DSL users still can't cover all the needs.

**Comment by antfu** [comment]
I am actually still not sure the scope of preset-uno, maybe at some point we should break it down to have 1:1 tailwind & windi compatibility and the other minimal and opinionated one to free the tech debts that Tailwind's DSL have.

**Comment by chu121su12** [comment]
I haven't been relying on this feature, but It showed up when implementing the multiple match generator. I just want to note this support as I was reading the issues list.

With me not being a designer, one of the reason I'm leaning towards tailwind is that it provided sensible opinionated defaults (the .25rem increments and great base colors) early on on its v0.x. 

Personally, I like the variable support from windi and logical property syntax of bootstrap's utilities. My work projects are based on tailwind though, so it may take a while to switch to non-tailwind syntaxes.

**Comment by chu121su12** [comment]
> I kind of prefer to have `text-color-[var(--)]` which I think we do support some of them. Also, I would like to encourage users to create their own rules for specific needs, since we made it fairly easy in UnoCSS, and even with Talwind's DSL users still can't cover all the needs.

I'm not good with api design. so here's my 2-cent.

I was tinkering with the utility and IMO, I found `text-<color>` synergizes better with `bg-<color>` and other utilities so preset-mini may benefit with the addtion of `text-size-[]` rather than `text-color-[]`.

**Comment by chu121su12** [comment]
The logic is now added to `preset-mini` instead because maintaining duplicate `parseColor` functions is less than ideal, especially it may be added to other utility with different color parsers (bg, shadow, etc.). However with the existing mini syntaxes (`x-size-y`) this feature maybe (?) less than useful anymore except for tailwind compatibility.
