### ISSUE TITLE
[unocss:transformers:default] Cannot split a chunk that has already been edited (0:221 – "@screen laptop{.admin-main{@apply ")

### ISSUE THREAD

**Issue by evanlong0926** [unocss/unocss#2022]
In Nuxt3 pnpm build：
`unocss:transformers:default] Cannot split a chunk that has already been edited (0:221 – "@screen laptop{.admin-main{@apply ")`

I wrote it this way.
```css
@screen laptop {
  .admin-main {
    @apply px-30;
  }
}
```

**Comment by itsmnthn** [comment]
I'm having the same issue while using `@screen sm {}` on docs built using [docus](https://github.com/nuxt-themes/docus) theme

To recreate try [this repo/code](https://github.com/hubble-exchange/docs/blob/upgrade-deps/layouts/blog-post.vue#L136-L150)

**Comment by enrique-fernandez-polo** [comment]
Did you figure out how to solve this?

**Comment by zyyv** [comment]
Please take a few minutes to check our [`@screen driective docs`](https://github.com/unocss/unocss/blob/main/packages/transformer-directives/README.md#screen)

More usage example, you can check our test code. https://github.com/unocss/unocss/blob/main/test/transformer-directives.test.ts

>  For this code: `@screen laptop { ... }`

Have you already cutsom the breakpoints and named key is `laptop`.
And you should following to our cutsom `theme.breakpoints` usage docs. https://github.com/unocss/unocss#extend-theme.

**Comment by tysian** [comment]
Hey! Sorry for posting in closed issue, but something similar happened to me.
Long story short - I'm developing my own UnoCSS preset and transformers using Vite integration plugin.

This error appeared both in my transformer, then I've tried the original one ([@unocss/transformer-directives](https://github.com/unocss/unocss/tree/main/packages/transformer-directives)) and the same error showed up.

Everything worked fine until I've added `CSSNano plugin` to my `postcss.config.cjs`, this caused this error.

Here is my [reproduction link](https://stackblitz.com/edit/vitejs-vite-5anp17?file=src/example.scss). 

I'm not sure If I should post this here... or open new issue... Or open issue in CSSNano repo?

**Comment by moldypenguins** [comment]
I am getting this error when trying to build. I am unsure why the flex-basis line is causing the issue.

Nuxt Build Error: [unocss:transformers:undefined] Cannot split a chunk that has already been edited (0:1130 – "@screen lg{section{--uno:p-10}section .component{--uno:flex-basis-47.5%}section ")

with error
`@media lg {
  section {
    --uno: p-10;

    .component {
      --uno: flex-basis-48%;
    }
    .component-narrow {
      --uno: p-0;
    }
  }
}`

no error
`@media lg {
  section {
    --uno: p-10;

    .component-narrow {
      --uno: p-0;
    }
  }
}`
