### ISSUE TITLE
不兼容

### ISSUE THREAD

**Issue by rookiewxy** [unocss/unocss#2025]
在chrome85版本中，不能引入import "uno.css",会报__uno.css:9 Uncaught SyntaxError: Unexpected reserved word,

**Comment by antfu** [comment]
Use the latest browser for development.

**Comment by rookiewxy** [comment]
> Use the latest browser for development.
Is there a solution for browsers with lower versions? The reason for reporting this error is that we use top-level await, but babel only supports resolution, not conversion

**Comment by mei2015** [comment]
难道 chrome 87 版本 还不算新？

**Comment by KaiveYoung** [comment]
我知道最新版没问题,但是有些垃圾设备他最新的只能用老版本的chrome我也没办法啊  所有你这种咋办呢

**Comment by ZedCoding** [comment]
所以老版本的chrome不能用unocss嘛？

**Comment by Deelout** [comment]
请问有解决方案吗？
