### ISSUE TITLE
shortcut or rule starting with "link-" do not work

### ISSUE THREAD

**Issue by vbrajon** [unocss/unocss#2027]
I couldn't find the part of the code that adds a specific "link-" rule to make a PR.

Here is a link to reproduce it: https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCI5gHYGt0B8AMjrlEgBYD2ArnCFAEYCmTcNzwA9OBAQFChIsRCgxY8AWgBOzEIRJ5y1OgxZRZIbrwFA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k7pkfpOeADWPXAABrFQdNCJkHh9UHB4O-iJWKmWmsQDIBhowFy6hphQ9xmmCkUHsvGIiQATHYQWDgBCOE4uBhEgAWAAM6NmEAWSxWiURyLRmMOslQenuu2SnwOxy4p3Ol1w11uuEBj2er2ZiQ%2BXx%2BcD%2Bi0BMIm4NwUJFoLF1LQxKx80Wy36MrlpKoalkIgUjXCWy1jGUEB8AEoyXJRMxWOxuLwBCazfqYJJpH4tqg6BJ1hhQgBGAB0kLNqAkaFweSqrDAjQA9NH6CA-dVo2YWsVTeUkGpjUggA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g

A temporary workaround can be done with a preprocessor like this: https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCI5gHYGt0B8AMjrlEgBYD2ArnCFAEYCmTcNzwA9OBAQFChIsRCgxY8AWgBOzEIRJ5y1OgxZRZIbrwFA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWyIjQQEvR0PiD2MBIAFhhQAJSIkXB8cA1Nre0AdPH2sHQA6sAwLT56TngA1nodXbQwXFC4cI3NbVDDtGBO9rXzi7grGQtXqz0bWzt7Q1BUarJ0LdDNPHSh-lQ%2Bli8SSXx%2BsRgejyMCsMESTlIcFhlnh0HsuFIGDg3wAbu1gij4bD7E50j1bitQgADWJQOjQRKQPCwqC9XCXDCJLCpSyaYjwkAYNDALi6QyYKCcuxSKBNYDERIAJhl6N4io4Ti4XIALAAGPU4iD4qCEuGJTXaxL6vXU2SoSnJYXQuC0rYMqBMiAs9rsznc3n83CC4Wi8W4SXSzCy%2BWKlXRtUK3BOtDWg1Gk1m1EptO22QfKgiBT-cI9IuMZQQHwde1yUTMVjsbi8ATV2vlmCSaR%2BHqoOgSUkYUIARmGStrqAkaFweRarDA-wA9Iv6CBRi1F2YgcUa%2BUkGoOkggA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g

**Comment by impcyber** [comment]
Here is an explanation:
https://github.com/unocss/unocss/issues/1232#issuecomment-1179464169

**Comment by vbrajon** [comment]
Perfect thanks !
