### ISSUE TITLE
WeChat APP has a built-in browser. Using unocss in the "development environment" will make the project inaccessible

### ISSUE THREAD

**Issue by 1014156094** [unocss/unocss#2031]
dev：
![image](https://user-images.githubusercontent.com/16074662/210027325-ce672a04-2e04-4ddf-b17c-92fbd9d8c3cf.png)
build：
![image](https://user-images.githubusercontent.com/16074662/210027332-238d2467-eb7c-4f32-ab8e-2cf3d124f2cf.png)

**Comment by MellowCo** [comment]
I think it's maybe wechat browser not support top level await, like this
![image](https://user-images.githubusercontent.com/47939250/210128767-a8b152d2-53bf-4fd8-a2cb-e18c53cf8bde.png)
