### ISSUE TITLE
upgrade from 0.46.5 to 0.47.0 breaks a react project

### ISSUE THREAD

**Issue by yckbilly1929** [unocss/unocss#2037]
Upgrade from 0.46.5 to 0.47.0 breaks my build (a react SPA project). Below is the diff before and after, running unocss cli:

![Screenshot 2022-12-31 at 20 28 25](https://user-images.githubusercontent.com/12884758/210136836-0290344c-c9cd-4ffc-895c-ae276e382db6.jpg)

and the only places with the word container:

![Screenshot 2022-12-31 at 20 29 31](https://user-images.githubusercontent.com/12884758/210136840-0d22a659-5d21-40ff-a77f-08fbfde8b820.jpg)

and my unocss.config.ts file:

![Screenshot 2022-12-31 at 20 34 41](https://user-images.githubusercontent.com/12884758/210136945-2538e26e-8e88-4c40-a18f-446df3dda56b.jpg)

**Comment by zyyv** [comment]
I don't know what your problem is, does it mean that many styles are generated?

**Comment by zyyv** [comment]
> and the only places with the word container:

Uno will scan your file source code, extract tokens as much as possible and generate styles.

**Comment by yckbilly1929** [comment]
> I don't know what your problem is, does it mean that many styles are generated?

Yes, extra css styles are generated, but none of them exists in class="xxx" or className="xxx".

Like the word `container`, it on exists as a variable name in my source code. So I expect it should not be wrongly extracted.

**Comment by yckbilly1929** [comment]
if I uncomment presetAttributify to include it back, more strange changes will happen:

![Screenshot 2022-12-31 at 20 52 36](https://user-images.githubusercontent.com/12884758/210137452-1bc64ea2-aa50-45fa-aea3-dc4040d8324f.jpg)
![Screenshot 2022-12-31 at 20 54 07](https://user-images.githubusercontent.com/12884758/210137455-8708a196-1f21-4e33-b03d-ffc52344fa71.jpg)

**Comment by zyyv** [comment]
https://github.com/unocss/unocss/blob/b19f5955112988b7a0f4916fc3273d68e69d159c/packages/core/src/extractors/split.ts#L25-L31

It comes from the split extractor. If you don't want use it, you can add it to `blocklist`.

**Comment by zyyv** [comment]
> if I uncomment presetAttributify to include it back, more strange changes will happen:
> 
> ![Screenshot 2022-12-31 at 20 52 36](https://user-images.githubusercontent.com/12884758/210137452-1bc64ea2-aa50-45fa-aea3-dc4040d8324f.jpg) ![Screenshot 2022-12-31 at 20 54 07](https://user-images.githubusercontent.com/12884758/210137455-8708a196-1f21-4e33-b03d-ffc52344fa71.jpg)

You'd better provide a minimal reproduction and explain the operation steps.

**Comment by yckbilly1929** [comment]
No problem, will provide a codesandbox reproduction after holiday. Happy new year 🎆

**Comment by zyyv** [comment]
> No problem, will provide a codesandbox reproduction after holiday. Happy new year 🎆

Happy new year 🎉

**Comment by yckbilly1929** [comment]
here is the reproduction repo (https://github.com/yckbilly1929/uno-demo)
switching from "~0.46.5" to "0.47.0" and rerun `pnpm build`, you will see that there is difference in src/uno-gen.css

**Comment by zyyv** [comment]
Hi, thanks your reproduction repo, i reproduced it. It is indeed a bug, maybe the wrong token was extracted when uno scanned the file. I'll fix it in my free time, maybe a little later.

**Comment by zyyv** [comment]
@yckbilly1929  Use `presetOnly` with `presetAttributify`, you should use `prefix` before your tokens, like `un-bg-red`.
As for your repo(https://github.com/yckbilly1929/uno-demo), i see those css was generated without `un-`(prefix) when i run build commond. Maybe that was a bug before, but you need to follow the meaning of this property when you use.

**Comment by yckbilly1929** [comment]
issue still exists in 0.50.0 🤔
