### ISSUE TITLE
Vite dev servers requests http://localhost:<port>/__uno.css?t=<some integer> every 2ms

### ISSUE THREAD

**Issue by jrolingdev** [unocss/unocss#2039]
Using Unocss with the Vite dev server causes Vite to request a Javascript file from http://localhost:<port>/__uno.css?t=<some integer> approximately every 2ms (on my pc at least but I imagine its sending requests as fast as possible). This is an issue because it causes my browser to freeze making local development impossible.

My network request tab: 

![Screenshot from 2023-01-02 16-56-41](https://user-images.githubusercontent.com/92704614/210200271-d06e788d-61ff-4264-86a9-41c57ce09ab9.png)

My guess is it has to do with Vite's HMR plugin as it only happens on the dev server. However if I build and preview my project the requests no longer happens.

I would love to reproduce this but I don't know how because it requires running the development server. If anyone can help with this I will update this issue with a reproducible demo. 

I'm using Unocss with Vite through the Astro framework. 

My astro.config.mjs: 

![Screenshot from 2023-01-02 17-04-10](https://user-images.githubusercontent.com/92704614/210200770-e36e0507-7bcb-4130-a172-9cc6bd11532f.png)

My uno.config.ts: 

![Screenshot from 2023-01-02 17-04-40](https://user-images.githubusercontent.com/92704614/210200777-c2604a54-134b-440d-b554-714038ec9687.png)

**Comment by sudongyuer** [comment]
Thx for feedback 💗 , Can you leave a minimal reproduction plz ?

**Comment by jrolingdev** [comment]
Hi so I tried to recreate the issue and realised that it only occurs when using cssnano (a postcss plugin) https://cssnano.co alongside Unocss. Should I close the issue now?

**Comment by Mehdi-Hp** [comment]
Related https://github.com/unocss/unocss/issues/1961

**Comment by antfu** [comment]
Can you create a minimal reproduction with cssnano (plain Vite would be preferred)?

From the screenshot, I guess the problem could be cssnano removed CSS comments that our HMR code is relaying on.

**Comment by tjk** [comment]
I'm getting this issue also... I think this should maybe not be getting triggered: https://github.com/unocss/unocss/blob/2e305f3e4ed916a9854def97c635d63572c510b4/packages/vite/src/modes/global/dev.ts#L169

```
import { createHotContext as __vite__createHotContext } from "/@vite/client";import.meta.hot = __vite__createHotContext("/__uno.css");import { updateStyle as __vite__updateStyle, removeStyle as __vite__removeStyle } from "/@vite/client"
const __vite__id = "/__uno.css"
const __vite__css = "<redacted>"
__vite__updateStyle(__vite__id, __vite__css)
import.meta.hot.accept()
export default __vite__css
import.meta.hot.prune(() => __vite__removeStyle(__vite__id))
if (import.meta.hot) {
  try { await import.meta.hot.send('unocss:hmr', ['__ALL__', __vite__css.slice(2,8)]); }
  catch (e) { console.warn('[unocss-hmr]', e) }
  if (!import.meta.url.includes('?'))
    await new Promise(resolve => setTimeout(resolve, 100))
}
```

Means as soon as this pushed chunk arrives, it re-requests the `__ALL__` layer immediately...

**Comment by mateusavila** [comment]
I receive this same error when I update the style of the component. And I didn't use windicss.

if necessary, I can invite any of the maintainers to look at my repository.

**Comment by LittleSound** [comment]
I am having the same problem, maybe it is because I used windicss in my projects. This problem prevents me from upgrading to the new version, and I need the fix in #2066 fix that the new version brings.

**Comment by praburangki** [comment]
> Hi so I tried to recreate the issue and realised that it only occurs when using cssnano (a postcss plugin) https://cssnano.co alongside Unocss. Should I close the issue now?

I can confirm this is due to using cssnano.
I was including it in a nuxt project, i tried to remove then the issue did not occur anymore.

<img width="709" alt="image" src="https://user-images.githubusercontent.com/8610935/215926681-7af28163-338e-4c06-80a0-d568bb3a952b.png">

Maybe this is causing the issue?

**Comment by microdou** [comment]
I've been encountering the issue in SvelteKit. The issue first occurred in version 0.46.4, so I'm stuck at 0.46.3 😅

https://github.com/unocss/unocss/issues/1871

**Comment by antfu** [comment]
Hope v0.49.6 fixes this issue. I don't know how to properly set up cssnano for this to occur. Would be appreciated if anyone could help verify

**Comment by tjk** [comment]
Elegantly simple fix! Thanks!!

(Just did a quick test and it at least works for me)

**Comment by lainbo** [comment]
> Hope v0.49.6 fixes this issue. I don't know how to properly set up cssnano for this to occur. Would be appreciated if anyone could help verify

However, version 0.49.6 has caused some issues in my project, where some of the unocss styles have stopped working, even though there were no issues in version 0.49.5. I have not been able to reproduce this problem in the Playground, but I am working on creating a minimal reproducible example to try and reproduce this issue.

**Comment by Raiondesu** [comment]
Still encountering this at `v0.51.8`.\
Happens mostly after editing a compiled class (`:uno:`).

vite plugins:
```
"@unocss/transformer-compile-class": "^0.51.8"
"@unocss/transformer-variant-group": "^0.51.8"
```

**Comment by yee94** [comment]
I encountered a similar issue and was able to resolve it. 

In my case, the problem occurred when I started multiple Vite projects with the same HMR port, even though the HTTP port was different. 

This caused the projects to dispatch events to each other. 

I was able to fix the issue by changing the port to a different one. I hope this solution helps you as well.
