### ISSUE TITLE
New sveltekit preprocess cause production break

### ISSUE THREAD

**Issue by kamontat** [unocss/unocss#2043]
Sveltekit stable version released with [new default preprocess][new-default-preprocess] cause production build not include preflights and safelist. 

I create stackblitz for demo the issue [here][stackblitz]. 
You can toggle between `vitePreprocess` and `preprocess` variable on svelte.config.js to see the problem.

[new-default-preprocess]: https://kit.svelte.dev/docs/integrations#preprocessors
[stackblitz]: https://stackblitz.com/edit/unocss-unocss-ncmap7?file=svelte.config.js

**Comment by mustofa-id** [comment]
I believe this is due you're utilizing the `svelte-scoped` mode. As mentioned in [svelte-scoped mode example](https://github.com/unocss/unocss/tree/main/examples/sveltekit-scoped#notes), this mode is not currently work with vite plugins.

> Vite plugins can't yet be used to preprocess files emitted by svelte-package as it does not use Vite. Follow https://github.com/sveltejs/vite-plugin-svelte/issues/475 to see when this will be made possible. In the meantime a [temporary svelte preprocessor wrapper](https://www.npmjs.com/package/temp-s-p-u) was published to enable using svelte-scoped mode in component libraries and other context that don't use Vite.

**Comment by fehnomenal** [comment]
Was bitten by the same issue. Using the "old" preprocess works just fine. Now I'm wondering what it would take to allow importing uno.css for the preflights and safelist instead of `<style uno:preflights uno:safelist global></style>`?

Currently `uno.css` can not be found because it is only resolved when using the global mode.

**Comment by fehnomenal** [comment]
Lol this was simple. Just adding

```js
    resolveId,
    async load(id){
      if(!id.match(RESOLVED_ID_RE)){
        return;
      }

      const { css } = await uno.generate("", { preflights:true, safelist:true })
      return css
    },
```

into the `SvelteScopedPlugin` seems to be enough.

Will prepare a PR soon.
