### ISSUE TITLE
variablePrefix option does not work

### ISSUE THREAD

**Issue by UltraCakeBakery** [unocss/unocss#2045]
See the playground below.

All CSS custom properties are still prefixed with `un-`

https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIBGBzAtAJwFMQodcB7ABwRjABcBPXAVgAZ0A%2BOc8gaygR0oAWwZQICfGASY4hJMAD04CByA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqfodwAJBz9uz2HKkACrQ4lr30A0WHagCUssLyjBYbE4PD4-B8v0Ou3EUlwdDOLRadAk6wwoQAjAA6ABMfxaEjQuDyVVYYEaAHpyfQQJjquTNi0frIyj8kEA&options=N4XyA

**Comment by Hongbusi** [comment]
`presetUno` does not support `variablePrefix`, you can try `presetMini`.

**Comment by UltraCakeBakery** [comment]
The type definitions do say it is supported in its config. Is it possible to add support?

**Comment by Hongbusi** [comment]
#2046

**Comment by UltraCakeBakery** [comment]
Thanks guys! <3 🚀
