### ISSUE TITLE
feat: Scan classes in js/ts files or enable adding classes by hand

### ISSUE THREAD

**Issue by zhangzheheng12345** [unocss/unocss#2054]
I want to add classes to an element using string. For example, Vue3 program below:

```Vue
<template>
  <div :class="[a]"></div>
</template>

<script setup lang="ts">
import { ref } from 'vue'

let a = ref('i-logos-vue')
</script>
```

It seems that such won't work in UnoCSS for UnoCSS only add classes that can be scanned. Certainly that string won't be scanned.
So if I want such code to work, we should either enable users to add classes that will be included in the final `uno.css` file by hand, or scan strings in js/ts files (but I think you won't like the latter, because unexpected problems might happen, although including useless classes won't cause anything).

**Comment by zyyv** [comment]
We already support this usage. From your code block, if you want use dynamic class(change value of `a`), i suggest you put the changed value of a into the safelist, then you can use dynamic class successfully.

**Comment by zhangzheheng12345** [comment]
Um sorry I didn't look at the document carefully. Thank you for help me with that!
Issue closed.
