### ISSUE TITLE
vscode extension error when not explicitly importing the defineNuxtConfig

### ISSUE THREAD

**Issue by parz1** [unocss/unocss#2057]
I followed the config steps from [Nuxt3](https://nuxt.com/docs/guide/directory-structure/nuxt.config)
It seems like unocss vscode extension will report error when not explicitly importing the defineNuxtConfig
```typescript
// import { defineNuxtConfig } from 'nuxt/config'
export default defineNuxtConfig({
  // My Nuxt config
})
```
the output of unocss in vscode:

> ⚠️ Error on loading config. Config directory: /Users/parz1/code/parz1/blog
ReferenceError: defineNuxtConfig is not defined

It's not a big problem though.

**Comment by parz1** [comment]
same as  #2018

**Comment by bogdan0083** [comment]
I have the same issue. I've been trying to figure out why `vscode-unocss` extension doesn't work. When I added `defineNuxtConfig` import it worked.

The problem is that it didn't show errors for me, it just didn't work.
