### ISSUE TITLE
question: Why I cannot use dark mode?

### ISSUE THREAD

**Issue by zhangzheheng12345** [unocss/unocss#2062]
I cannot use dark mode. For example, `dark:bg-gray-800` doesn't work. Actually, `dark:` doesn't work anywhere.

My project is [sites-list](https://github.com/zhangzheheng12345/sites-list). So what is happening inside? I've used the inspector and found dark classes are generated. But they just don't work.

**Comment by Hongbusi** [comment]
The final css generated by `dark:` is `.dark .dark\:color-white {...}`, you can try adding class dark to the html tag.

Can refer to:

- https://github.com/antfu/vitesse/blob/main/index.html#L10-L15
- https://github.com/antfu/vitesse/blob/main/src/composables/dark.ts

**Comment by zyyv** [comment]
Or you can check this option.
https://github.com/unocss/unocss/blob/8cf56ab3dfbcea44cb154e20159de8b1da149372/packages/preset-mini/src/index.ts#L31-L36

**Comment by zhangzheheng12345** [comment]
OK I understand that. Many thanks for @Hongbusi and @zyyv !
