### ISSUE TITLE
Error while starting nuxt dev server for interactive doc

### ISSUE THREAD

**Issue by zhangzheheng12345** [unocss/unocss#2063]
I use pnpm to install, then run npm run interactive, but get these errors:

ERROR: Error while requiring module .../unocss/packages/nuxt/node_modules/@unocss/webpack/dist/index.cjs
ERROR: Cannot find module .../unocss/packages/nuxt/node_modules/@unocss/webpack/dist/index.cjs

I enter the directory of interactive and run npm run dev, and get the same error.

**Comment by zyyv** [comment]
1. pnpm install
2. pnpm dev :( run stub

Then you can run other commands
