### ISSUE TITLE
Allow letter spacing and font weight to be set in theme configuration.

### ISSUE THREAD

**Issue by JohnnyMcWeed** [unocss/unocss#2070]
Tailwind CSS allows to set `letter-spacing` and `font-weight` under theme `fontSize` when using the object syntax ([second example here](https://tailwindcss.com/docs/font-size#providing-a-default-line-height)). 
UnoCSS does not seem to be supporting this at the moment
```
unocss.config.ts

export default {
  theme: {
    fontSize: {
      base: ['1rem', {
        lineHeight: '1.5em',
        letterSpacing: '0.01em',
        fontWeight: '400'
      }]
    }
  }
}
```

**Comment by zyyv** [comment]
We don't support this configuration item.
https://github.com/unocss/unocss/blob/65dc7a4f822606592267d9c54d7f04979f85fda0/packages/preset-mini/src/_theme/types.ts#L33

I even think it should be implemented in `shortcuts`.

**Comment by JohnnyMcWeed** [comment]
All good for me. 
(I just wanted to mention it so you and other people are aware of it.)
