### ISSUE TITLE
unocss在capacitor上报错

### ISSUE THREAD

**Issue by luoyi58624** [unocss/unocss#2074]
我在使用capacitor开发混合应用时，引入unocss andriod studio就会报错，手机上的测试应用将出现白屏。
最小示例代码地址： https://github.com/luoyi58624/vite-vue3-app
报错信息如下：
![image](https://user-images.githubusercontent.com/46178521/212059691-557187c7-3854-44c3-8fda-c41187800fbb.png)

手机上正常效果：
![658369dc4b2cc96434eae11ab8bc5d1](https://user-images.githubusercontent.com/46178521/212061943-8eb99a06-bc1e-4576-8b5a-96e431c152e3.jpg)
引入unocss后的报错效果：
![f4e8b58880722d53cf781c56a87eff4](https://user-images.githubusercontent.com/46178521/212062024-d5273ea4-7c65-4277-9615-27039e2ab3a9.jpg)
变动的2处代码：
![image](https://user-images.githubusercontent.com/46178521/212062208-bb340b6e-1d3b-47a8-b443-a64d3b9af002.png)
![image](https://user-images.githubusercontent.com/46178521/212062299-50fc41d8-a762-485f-8ef6-d06804e28e12.png)

**Comment by antfu** [comment]
https://github.com/unocss/unocss/pull/2066
