### ISSUE TITLE
Dynamic classes added with props does not apply in svelteKit

### ISSUE THREAD

**Issue by aadi58002** [unocss/unocss#2077]
I am trying to have class as a prop which i can pass on to components but in the case below the class which are added by the passed prop as well as the class which were already there (form-control,block...etc.) were also not applied.

```svelte
<script lang="ts">
 type HTMLInputTypeAttribute = "password" | "text"
 let Class: string = "";
 export let type: HTMLInputTypeAttribute,placeholder: string
 export {Class as class}
</script>

<input
    {type}
    class={"form-control block w-full px-4 py-2 text-xl font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none " + Class}
    {placeholder}
/>
```
From the svelte kit setup i already included the extrator.
```typescript
import { sveltekit } from '@sveltejs/kit/vite';
import { extractorSvelte } from '@unocss/core';
import UnoCSS from 'unocss/vite';
import {
  presetTypography,
  presetIcons,
  presetUno,
  transformerDirectives,
  transformerVariantGroup,
  transformerCompileClass
} from 'unocss';

const config = {
  plugins: [
    UnoCSS({
      extractors: [extractorSvelte],
      mode: 'svelte-scoped',
      presets: [presetUno(), presetTypography(), presetIcons({ scale: 2.0 })],
      transformers: [transformerDirectives(), transformerVariantGroup(), transformerCompileClass()],
    }),
    sveltekit()
  ]
};

export default config;
```

**Comment by henrikvilhelmberglund** [comment]
I have done something similar in Tailwind but it does indeed not work here right now.

What you could do use the `@apply` for the component style and use it with a class directive class:my-style={true} (with .my-style {} in the style tag), then for the props use the class={Class}. You would probably need to use ! in the props though.

Example: https://stackblitz.com/edit/unocss-unocss-apaqxe?file=src/lib/Input.svelte

**Comment by aadi58002** [comment]
> I have done something similar in Tailwind but it does indeed not work here right now.
> 
> What you could do use the `@apply` for the component style and use it with a class directive `class:my-style={true}` (with `.my-style {}` in the style tag), then for the props use the `class={Class}`. You would probably need to use ! in the props though.
> 
> Example: https://stackblitz.com/edit/unocss-unocss-apaqxe?file=src/lib/Input.svelte

Thanks for the answer and also the example.
