### ISSUE TITLE
Did it meet expectations with vscode ext ? 

### ISSUE THREAD

**Issue by liting-yes** [unocss/unocss#2080]
unocss ext scan the content in script tag of vue sfc

<img width="576" alt="Screenshot 2023-01-14 at 14 20 48" src="https://user-images.githubusercontent.com/69500429/212458925-bc3bec45-33ab-4adc-9d77-1e5dad6398a5.png">

**Comment by zyyv** [comment]
Yes, Uno will scan the tokens in the code as much as possible and generate styles for you.

This example may resolve your doubts. 
```ts
const bgColor = Math.random() > 0.5 ? 'bg-red' : 'bg-blue'
```
```html
<div :class="bgColor" />
```
Uno will scan `bg-red` and `bg-blue`
