### ISSUE TITLE
VitePlugin__default is not a function

### ISSUE THREAD

**Issue by hexiangmaya** [unocss/unocss#2083]
`import Unocss from 'unocss/vite';
import {
  presetAttributify,
  presetIcons,
  presetUno,
  transformerDirectives,
  transformerVariantGroup,
} from 'unocss'; // 这些都是unocss的
`

`      Unocss({
        presets: [
          presetUno(),
          presetAttributify(),
          presetIcons({
            scale: 1.2,
            warn: true,
          }),
        ],
      transformers: [transformerDirectives(), transformerVariantGroup()],
      }),`

![image](https://user-images.githubusercontent.com/52593415/212630987-67ad347d-efc0-4ebe-99a4-5000f64385e1.png)

![image](https://user-images.githubusercontent.com/52593415/212631101-b7f495ff-7f11-48c6-936e-1e8695cae105.png)

**Comment by lishaobos** [comment]
请问可以提供可复现的 git 仓库吗？

**Comment by Liubei1993** [comment]
解决了吗，我也是这个问题

**Comment by wz826** [comment]
> 
请参考我的仓库
https://github.com/wz826/front-demo.git

**Comment by lishaobos** [comment]
> > 
> 
> 请参考我的仓库 https://github.com/wz826/front-demo.git

我跑起来没任何问题，我 node 版本是 16.18.1，可以提供下你的 node，npm 版本吗。

**Comment by wz826** [comment]
> 

![image](https://user-images.githubusercontent.com/122187286/220034228-460cc8e4-db31-48dd-977f-c17f188ac126.png)

PowerShell 7.3.2

└─Δ cnpm -v
cnpm@9.0.1 
npm@8.19.4
node@18.14.0 
npminstall@7.5.0 
win32 x64 10.0.22621
registry=https://registry.npmmirror.com

┖[~]
└─Δ

**Comment by lishaobos** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/122187286/220034228-460cc8e4-db31-48dd-977f-c17f188ac126.png)
> 
> PowerShell 7.3.2
> 
> └─Δ cnpm -v cnpm@9.0.1 npm@8.19.4 node@18.14.0 npminstall@7.5.0 win32 x64 10.0.22621 registry=https://registry.npmmirror.com
> 
> ┖[~] └─Δ

我这边切换了 node，npm 版本，设置了淘宝镜像，还是没问题，你要不要切换不同的镜像，安装试试。

**Comment by wz826** [comment]
> > > 
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/122187286/220034228-460cc8e4-db31-48dd-977f-c17f188ac126.png)
> > PowerShell 7.3.2
> > └─Δ cnpm -v cnpm@9.0.1 npm@8.19.4 node@18.14.0 npminstall@7.5.0 win32 x64 10.0.22621 registry=https://registry.npmmirror.com
> > ┖[~] └─Δ
> 
> 我这边切换了 node，npm 版本，设置了淘宝镜像，还是没问题，你要不要切换不同的镜像，安装试试。

我升级了，unocss版本，代码提交了，你再看下

**Comment by wz826** [comment]
![image](https://user-images.githubusercontent.com/122187286/220263217-679c713b-3843-4f9a-aebb-93c1959222aa.png)
cnpm run dev

> wzblogvue@0.1.0 dev
> vite --mode develop

failed to load config from D:\nodeWorkspace\front-demo\vite.config.ts
error when starting dev server:
TypeError: VitePlugin__default is not a function
    at UnocssVitePlugin (D:\nodeWorkspace\front-demo\node_modules\.store\unocss@0.48.5\node_modules\unocss\dist\vite.cjs:14:10)
    at vite_config_default (D:\nodeWorkspace\front-demo\vite.config.ts:157:32)
    at loadConfigFromFile (file:///D:/nodeWorkspace/front-demo/node_modules/.store/vite@4.1.3/node_modules/vite/dist/node/chunks/dep-ae3fae1b.js:62214:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolveConfig (file:///D:/nodeWorkspace/front-demo/node_modules/.store/vite@4.1.3/node_modules/vite/dist/node/chunks/dep-ae3fae1b.js:61832:28)
    at async createServer (file:///D:/nodeWorkspace/front-demo/node_modules/.store/vite@4.1.3/node_modules/vite/dist/node/chunks/dep-ae3fae1b.js:61142:20)
    at async CAC.<anonymous> (file:///D:/nodeWorkspace/front-demo/node_modules/.store/vite@4.1.3/node_modules/vite/dist/node/cli.js:734:24)

**Comment by lishaobos** [comment]
复现了，应该是 cnpm 的问题，切换到 npm，设置淘宝镜像是 ok 的。

**Comment by hexiangmaya** [comment]
确定不是这里的问题么....
我是强行改了源代码跑的
node_modules\.store\unocss@0.48.4\node_modules\unocss\dist\vite.cjs:14:10
把
const VitePlugin__default = /*#__PURE__*/_interopDefaultLegacy(VitePlugin);
改成了
const VitePlugin__default =()=> /*#__PURE__*/_interopDefaultLegacy(VitePlugin);

**Comment by lishaobos** [comment]
> 确定不是这里的问题么.... 我是强行改了源代码跑的 node_modules.store\unocss@0.48.4\node_modules\unocss\dist\vite.cjs:14:10 把 const VitePlugin__default = /_#**PURE**_/_interopDefaultLegacy(VitePlugin); 改成了 const VitePlugin__default =()=> /_#**PURE**_/_interopDefaultLegacy(VitePlugin);

你切换 npm 试试，我之前用 cnpm 也好多问题，弃了。

**Comment by hexiangmaya** [comment]
npm 老半路报错下不完，换pnpm 可以了 跑得动了！

**Comment by lishaobos** [comment]
> npm 老半路报错下不完，换pnpm 可以了 跑得动了！

哈哈，可以的。

**Comment by wz826** [comment]
> npm 老半路报错下不完，换pnpm 可以了 跑得动了！

确实，pnpm可以正常运行

> 解决了吗，我也是这个问题

换pnpm试一下，参考我的Git
