### ISSUE TITLE
Cannot load vscode extension in vite-solid example

### ISSUE THREAD

**Issue by MellKam** [unocss/unocss#2088]
I have problem with launching vs-code extesion in vite-solid example. 

```
⚪️ UnoCSS for VS Code v0.48.4

🛠 Resolving config for /home/melkam/unocss/examples/vite-solid
⚠️ Error on loading config. Config directory: /home/melkam/unocss/examples/vite-solid
SyntaxError: Unexpected identifier
➖ No config found, UnoCSS is disabled
```

**Comment by MellKam** [comment]
I was playing with this for some time and I was able to find that if you remove ```solidPlugin()``` from the list of vite plugins, the extension runs and everything works. Why could this be?

**Comment by MellKam** [comment]
When i moved the config to unocss.config.ts, the extention works correctly. Then I can return ```solidPlugin()``` in vite config, and it works as well.

**Comment by MellKam** [comment]
Here is a link to reproduce this error -> https://codesandbox.io/p/sandbox/unconfig-vite-solid-bug-2wrobj

**Comment by high1** [comment]
This also happens with @sveltejs/vite-plugin-svelte - the unocss vscode extension does not work if there's no config file, breaks with unexpected identifier. An empty config file fixes this.
```
import { defineConfig } from 'unocss';
export default defineConfig({});
```

**Comment by henrikvilhelmberglund** [comment]
Not sure why a unocss.config.js file with only
```import { defineConfig } from 'unocss';
export default defineConfig({});
``` fixes this but hey, I'll take it.
