### ISSUE TITLE
Documentation about unocss.config file. 

### ISSUE THREAD

**Issue by MellKam** [unocss/unocss#2092]
Where can I find documentation on how to use the unocss.config.[ts/js] file? It seems that the vscode extension prefers to use this type of configuration, but I haven't found a single word about it.

**Comment by alex-belyaev** [comment]
Sam question here. I would like to know if there is an option to point what files to scan, extensions and directory?

**Comment by antfu** [comment]
https://unocss.dev/guide/config-file
