### ISSUE TITLE
Typography styles are not generated in build mode (Attributify preset) #2

### ISSUE THREAD

**Issue by impcyber** [unocss/unocss#2094]
`[un-prose]`  styles are not generated again

see: https://github.com/unocss/unocss/issues/1738

```css
/* generated */
.prose :where(h1,h2,h3,h4,h5,h6)

/* not generated */
.[un-prose] :where(h1,h2,h3,h4,h5,h6)
```
for `.prose` styles are generated but not for `[un-prose]`

repro: https://stackblitz.com/edit/vitejs-vite-l2kkdf?file=unocss.config.ts,src%2Fpages%2Findex.vue,dist%2Fassets%2Findex.2bb39ab8.css

**Comment by zyyv** [comment]
Refer your sample code, it works fine in [playground](https://uno.antfu.me/play/?html=DwEwlgbgBArgdgWgA4CcD2BnApgXgEQB%2BeAfAFBRTAAWAjMQBI1RVYCG4cA5lABQzLpsASmAB6WmQrAkxJKxStOCpFV79UmLCNEzSY8BDJA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcEWSIUAVfpFJQAhmAAWgpAF84WKBBBwA5FxUS6dW0iQYAHpFjpsergA28Jg4%2BEQkwKQAFMioUIH0AFxwANopthJcdDDWALTxARi25IhwUgHQyba0aLZwpgC6DbJ0htAwmTB0ybGodpnZea3tnbZVMJ4wuQGkcBMeU9B6uKQYcG0AbhhQifNTE3oBxVSmavKM3alUwudKKlEAlLI3ojBaOvpG-I-Pcq8sbE4PD43ye1z%2BCkk0hi4NQdAkhwwyQAjAA6ABMv1QEjQuCqhlYYG6AHpifQQKjWsTjn16mDUM0zA8kEA&options=N4XyA).

**Comment by zyyv** [comment]
<img width="554" alt="image" src="https://user-images.githubusercontent.com/42139754/213391307-6ddf66b4-4be4-42d7-804a-f78573d6aa2d.png">
And I test it in build mode, it is also intact

**Comment by impcyber** [comment]
> Refer your sample code, it works fine in [playground](https://uno.antfu.me/play/?html=DwEwlgbgBArgdgWgA4CcD2BnApgXgEQB%2BeAfAFBRTAAWAjMQBI1RVYCG4cA5lABQzLpsASmAB6WmQrAkxJKxStOCpFV79UmLCNEzSY8BDJA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcEWSIUAVfpFJQAhmAAWgpAF84WKBBBwA5FxUS6dW0iQYAHpFjpsergA28Jg4%2BEQkwKQAFMioUIH0AFxwANopthJcdDDWALTxARi25IhwUgHQyba0aLZwpgC6DbJ0htAwmTB0ybGodpnZea3tnbZVMJ4wuQGkcBMeU9B6uKQYcG0AbhhQifNTE3oBxVSmavKM3alUwudKKlEAlLI3ojBaOvpG-I-Pcq8sbE4PD43ye1z%2BCkk0hi4NQdAkhwwyQAjAA6ABMv1QEjQuCqhlYYG6AHpifQQKjWsTjn16mDUM0zA8kEA&options=N4XyA).

Hi, @zyyv 
Yes, it works fine in `dev` mode and in playground.

I've created fresh install with minimal dependencies (JS-only) and it builds fine too.
But if i make `build` in my `astro` project or in clean [ `vitesse`](https://github.com/antfu/vitesse) template, i don't have this attributify `[un-prose]` styles.

As you can see, I used the `vitesse` template in my `repro` above.

**Comment by impcyber** [comment]
With `unocss@0.49.4` works fine
