### ISSUE TITLE
Adding `@unocss/preset-typography` in Nuxt

### ISSUE THREAD

**Issue by vedxp** [unocss/unocss#2099]
1. Since the installation guide have shown unocss configuration can be written inside the `nuxt.config.js` file itself like this:
```
// nuxt.config.js

export default {
  modules: [
    '@unocss/nuxt',
  ],
  unocss: {
    // presets
    uno: true, // enabled `@unocss/preset-uno`
    icons: true, // enabled `@unocss/preset-icons`
    attributify: true, // enabled `@unocss/preset-attributify`,

    // core options
    shortcuts: [],
    rules: [],
  },
}
```

and, `preset-uno`, `preset-icons` and `preset-attributify` can be enabled by setting it true.

Is it possible to do the same for `preset-typography` too?

---

2. What does setting the presets to `true` do, and do I need to install the preset from cli even after doing the same in config file?
```
  unocss: {
    // presets
    uno: true, // enabled `@unocss/preset-uno`
    icons: true, // enabled `@unocss/preset-icons`
    attributify: true, // enabled `@unocss/preset-attributify`,
```

**Comment by jbreuil** [comment]
It should already be possible with : 
`typography: true`

[see here](https://github.com/unocss/unocss/blob/main/packages/nuxt/src/options.ts)

**Comment by vedxp** [comment]
> It should already be possible with : `typography: true`
> 
> [see here](https://github.com/unocss/unocss/blob/main/packages/nuxt/src/options.ts)

Hmm, I see.
That means I don't need to install the plugin from cli which can be enabled by just setting it to enabled in `nuxt.config.js`?

Please confirm me once :)

One more doubt I've, how to set custom Colors and more in unocss as we do in tailwind css in `tailwind.config.js.theme.colors` for colors?

Reference image: 
> ![Screenshot_2023-01-27-17-16-47-75_a2cf8efcdd42a8e6f7906303f104fb67~2](https://user-images.githubusercontent.com/87353286/215080043-5490e2fb-f12c-473c-95eb-f9f3b4fa6473.jpg)

**Comment by vedxp** [comment]
@jbreuil If I add theme.colors in `unocss.config.js` like this:
> ![Screenshot_2023-01-27-18-18-50-52_a2cf8efcdd42a8e6f7906303f104fb67](https://user-images.githubusercontent.com/87353286/215091099-11bd3210-ec75-4dff-8680-fa57125399dc.jpg)

It throws this error:
> ![Screenshot_2023-01-27-18-18-23-05_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/87353286/215091163-ebed654b-ce5f-47d9-94ac-aecbe3d5079f.jpg)

**Comment by vedxp** [comment]
@jbreuil Thanks brother, everything is fine now, except ability to add css properties to body tag.

How can I do it?
In tailwind css, it's added by creating  in `assets/css/tailwind.css` and applying the property using @apply directive.

Is it the same for unocss too?

**Comment by jbreuil** [comment]
> > It should already be possible with : `typography: true`
> > [see here](https://github.com/unocss/unocss/blob/main/packages/nuxt/src/options.ts)
> 
> Hmm, I see. That means I don't need to install the plugin from cli which can be enabled by just setting it to enabled in `nuxt.config.js`?
> 
> Please confirm me once :)

No it's already a [dependency](https://github.com/unocss/unocss/blob/main/packages/nuxt/package.json)

**Comment by jbreuil** [comment]
> @jbreuil Thanks brother, everything is fine now, except the ability to add css properties to body tag. How can I do it?
> 
> In tailwind css, it's added by creating `assets/css/tailwind.css` and applying the property using @apply directive.
> 
> Is it the same for unocss too?
> 
> Thanks in advance :)

There is plenty of way of doing it.

- [Preflight](https://github.com/unocss/unocss#preflight) might be enough for you
- [Use nuxt head](https://nuxt.com/docs/api/composables/use-head#meta) and set a class attribute in bodyAttrs with unocss classes as values
- Just declare a class in the style of your entrypoint or import a css in your entrypoint

You need additional config for [@apply](https://github.com/unocss/unocss/tree/main/packages/transformer-directives)

**Comment by vedxp** [comment]
> There is plenty of way of doing it.
> 
> * [Preflight](https://github.com/unocss/unocss#preflight) might be enough for you
> * [Use nuxt head](https://nuxt.com/docs/api/composables/use-head#meta) and set a class attribute in bodyAttrs with unocss classes as values
> * Just declare a class in the style of your entrypoint or import a css in your entrypoint
> 
> You need additional config for [@apply](https://github.com/unocss/unocss/tree/main/packages/transformer-directives)

#### Thank you so much for your help :)

1.  This seems to be straightforward.
2. Can you please show me the same in action, (the code in app.vue, configured as you've mentioned above)?
I'm curious to know about it :)
