### ISSUE TITLE
Client error only in Safari, `Cannot access uninitialized variable.`

### ISSUE THREAD

**Issue by pheuter** [unocss/unocss#2111]
### Reproduction

https://github.com/pheuter/safari-repro

### Logs

```Shell
[Error] ReferenceError: Cannot access uninitialized variable.
	handleError (client-manifest.js:16)
	handle_error (client.js:1692)
	(anonymous function) (client.js:1630)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob

[Error] Unhandled Promise Rejection: ReferenceError: Cannot access uninitialized variable.
	(anonymous function) (start.js:38)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
```

### System Info

```Shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 4.93 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.4.0 - /opt/homebrew/bin/node
    npm: 9.2.0 - /opt/homebrew/bin/npm
    Watchman: 2022.11.14.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 109.0.5414.87
    Safari: 16.2
  npmPackages:
    unocss: 0.48.5 => 0.48.5
    vite: 4.0.4 => 4.0.4
```

### Severity

blocking all client-side usage of SvelteKit app when unocss is imported on latest versions of Safari

**Comment by pheuter** [comment]
Believe this is an issue with Uno and not SvelteKit: https://github.com/sveltejs/kit/issues/8529#issuecomment-1407213646

**Comment by antfu** [comment]
While I confirm I am able to reproduce that on my Safari. I am not sure if it's related to UnoCSS tho, as the error comes from SvelteKit's client file, and I believe UnoCSS does not touch it. Honestly, I would rather consider this a bug of Safari, as the error does not make sense, and it does not occur on Chrome & FF.

Closing this as I see nothing I can help with from the build pipeline on UnoCSS side. I would need a conclusive clue of it being relevant to Uno.
