### ISSUE TITLE
vite中使用vite build --watch，UnoCSS的修改不会生效

### ISSUE THREAD

**Issue by ListenV** [unocss/unocss#2121]
vite中使用`vite build --watch`，然后修改UnoCSS的class，样式并不会生效

**Comment by dongwa** [comment]
+1

**Comment by dongwa** [comment]
我测试升级到最新版后修复了，这里有一个相关的 pr #963，你可以升级试试

**Comment by aliuq** [comment]
我遇到了相同的问题，`.vue` 文件中可以正常生效，但是当我修改 `unocss.config.ts` 文件时，就需要重新启动

我的场景是在 `unocss.config.ts` `theme` 里面配置了颜色，代码里有使用到，但当我修改颜色时，`dist` 目录下的 `style.css` 没有跟着改变，实际应该是 virtual module `uno.css` 没有跟着变化

一个临时解决方案是，使用 `unocss` 的 cli 模式单独实现监听，不引入 `uno.css`，转而引入 cli 处理后的 uno.css

package.json

使用 [concurrently](https://github.com/open-cli-tools/concurrently) 实现同步执行监听命令

```diff
"scripts": {
-  "stub": "vite build --watch"
+  "build:watch": "vite build --watch",
+  "stub": "concurrently -n vue,unocss npm:build:watch \"unocss -w\""
}
```

unocss.config.ts

```ts
export default defineConfig({
  cli: {
    entry: {
      patterns: ['./src/**/*.{vue,jsx,tsx,md,mdx,html}'], // 修改为对应的路径
      outFile: 'uno.css',
    },
  },
})
```

index.ts 

```diff
- import 'uno.css'
+ import './uno.css'
```

然后执行 `pnpm run stub`, 修改 `unocss.config.ts` 文件，就能达到目标效果

**Comment by ListenV** [comment]
> 我测试升级到最新版后修复了，这里有一个相关的 pr #963，你可以升级试试

感谢提醒，已经解决

**Comment by ListenV** [comment]
@aliuq unocss是通过vite插件的形式使用的，vite本身好像就不支持自己配置文件的热重载

**Comment by chenweiyi** [comment]
> 我遇到了相同的问题，`.vue` 文件中可以正常生效，但是当我修改 `unocss.config.ts` 文件时，就需要重新启动
> 
> 我的场景是在 `unocss.config.ts` `theme` 里面配置了颜色，代码里有使用到，但当我修改颜色时，`dist` 目录下的 `style.css` 没有跟着改变，实际应该是 virtual module `uno.css` 没有跟着变化
> 
> 一个临时解决方案是，使用 `unocss` 的 cli 模式单独实现监听，不引入 `uno.css`，转而引入 cli 处理后的 uno.css
> 
> package.json
> 
> 使用 [concurrently](https://github.com/open-cli-tools/concurrently) 实现同步执行监听命令
> 
> ```diff
> "scripts": {
> -  "stub": "vite build --watch"
> +  "build:watch": "vite build --watch",
> +  "stub": "concurrently -n vue,unocss npm:build:watch \"unocss -w\""
> }
> ```
> 
> unocss.config.ts
> 
> ```ts
> export default defineConfig({
>   cli: {
>     entry: {
>       patterns: ['./src/**/*.{vue,jsx,tsx,md,mdx,html}'], // 修改为对应的路径
>       outFile: 'uno.css',
>     },
>   },
> })
> ```
> 
> index.ts
> 
> ```diff
> - import 'uno.css'
> + import './uno.css'
> ```
> 
> 然后执行 `pnpm run stub`, 修改 `unocss.config.ts` 文件，就能达到目标效果

但是这么做后会导致vite build 2次，有什么解决办法只build 1次吗？

**Comment by Simon-He95** [comment]
> > 我遇到了相同的问题，`.vue` 文件中可以正常生效，但是当我修改 `unocss.config.ts` 文件时，就需要重新启动
> > 我的场景是在 `unocss.config.ts` `theme` 里面配置了颜色，代码里有使用到，但当我修改颜色时，`dist` 目录下的 `style.css` 没有跟着改变，实际应该是 virtual module `uno.css` 没有跟着变化
> > 一个临时解决方案是，使用 `unocss` 的 cli 模式单独实现监听，不引入 `uno.css`，转而引入 cli 处理后的 uno.css
> > package.json
> > 使用 [concurrently](https://github.com/open-cli-tools/concurrently) 实现同步执行监听命令
> > ```diff
> > "scripts": {
> > -  "stub": "vite build --watch"
> > +  "build:watch": "vite build --watch",
> > +  "stub": "concurrently -n vue,unocss npm:build:watch \"unocss -w\""
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > unocss.config.ts
> > ```ts
> > export default defineConfig({
> >   cli: {
> >     entry: {
> >       patterns: ['./src/**/*.{vue,jsx,tsx,md,mdx,html}'], // 修改为对应的路径
> >       outFile: 'uno.css',
> >     },
> >   },
> > })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > index.ts
> > ```diff
> > - import 'uno.css'
> > + import './uno.css'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 然后执行 `pnpm run stub`, 修改 `unocss.config.ts` 文件，就能达到目标效果
> 
> 但是这么做后会导致vite build 2次，有什么解决办法只build 1次吗？

这个问题似乎已经超出了 UnoCSS 的解决范围了
