### ISSUE TITLE
mini preset: Custom CSS Variable generation changed in v0.49.1

### ISSUE THREAD

**Issue by samydoesit** [unocss/unocss#2132]
Hello some of our tests are failing because some custom variables are wrong generated as "--v" instead of some other name. 

```javascript
shortcuts: [
   ['testString', `selector-[.test]:([--min-width:20px] [--col-gap:20px] [--content-min-width:calc(var(--min-width)_-_2_*_var(--col-gap))])`]
],
```
```diff
--- .test{--min-width:20px;--col-gap:20px;--content-min-width:calc(var(--min-width) - 2 * var(--col-gap));}
+++ .test{--min-width:20px;--col-gap:20px;--content-min-width:calc(var(--min-width) - 2 * var(--v));}
```

This could be introduced in relation to v.0.49.1 with this change: : https://github.com/unocss/unocss/pull/2115

Here is a Sample: [UnoCSS Playground](https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIAuBTJmDKmATmAHYDm6AfAFBRTAAOsiKG1NwA9OBFUA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHFYALaDGb0YrAFxwA2itVHaMVKxgBlGFGxFaAGjgADVqjGpmMaAFojADpLawBdfQUjf38QbH8Ad2BkGHV9ACYABjBeMOMY5ggxfyJhMAzs3LMCgkssGFj4pJS05mExZgUAN2EoBRi4rETk1IBKAH1-cfTxgCpxnr6a4tKwUdGw0bcw0zDnTlJRoA&options=N4IgzgLgTglgxhEAuaBXApgGhNAhgOzADMB7KAW2SNwBsx0BfIA)

This has worked until 0.49.0. Is there anything wrong how we generate the variables? We could also move this to preflights.

**Comment by AaronBeaudoin** [comment]
I'm experiencing this issue as well. In my case, a class `pb-[calc(var(--cy)+var(--cx))]` is generated as:

```css
padding-bottom: calc(var(--cy) + var(--v));
```
