### ISSUE TITLE
How to integrate with tailwind-based libs?

### ISSUE THREAD

**Issue by SeryiBaran** [unocss/unocss#2136]
Hello.

How to connect tailwind-based library to UnoCSS, for example SailBoatUI?

**Comment by sibbng** [comment]
It seems SailBoatUI doesn't have any specific Tailwind plugin. So you can use SailBoatUI components by just doing copy-paste. All you need to do just adding `primary` and `secondary` theme colors: [Playground](https://uno.antfu.me/play/?html=FAHgJglgbgBAxgGwIYGcUF4BEAzBBTADxl0IFoB3AJyQAcYArAVxQBcJsBPUuPAOxbyUYAc1qkArJgB8wGDBAAjRixYB7XjBYcaeLEpXrM8ZGiyVVjXmDxhSCYTAWrK1oU5eDSNShAC2SSi5xAAZgx2EvH39AiVCYGgIJeK4AJgA6cU1CFm4%2BASEBAhyUX2J1HN8bCEZSwpzyAAsIARgUBqQwVXJSEs1qXhRmiHVSJAQEGAbVKEEALndXSL8ArgB2OKmZynmI72WY9bDsVThmWZ9eB2PTlHOIS6Xo1LjIFCQFfDBZ08oUZ1JeKocmMEF0bDBXu9PvNnIs9k9SABmF4QN4fGw7R4rJGhaQAIWUag0dRAAHp9ESZHJFIT1JptLpMBTDMZUBhMOZLNZbPZHLDBHyPJRSMJqFxkWEFBFGs08PFEpkaKkMlkirl%2BAK6j1Ssd%2BKRKpAaqqcqKkGs4m0Ol1tX0kAMhiMQZNpnMpSKxaQAIxxa5nC5XE5%2B%2B4RU1cb1hSHor4-P7CwHA8ZgsAQ1FQjELTyhr0otHQt1ZkIp3MYrVZgAsuKkBIMxOyZOZvCp8gb9J0elpvCMiDZZgsVhsdgcGbc-OF8Ox4fCWJik4SSSVpHSmS1PA1BWyNt1FSqRq145iADY4ix%2BoM2I7xs6tjChdPnmFNq7dlFsSkfYHbv6yjc7g990EI1TKMbzhF8YkLSM82ffYAKLNMvj3MCuArYJ8Q7Y16w7JsaRrVtGQbLsTHZTl%2Bx5IdR0FRYTztFAaACPIp2ogY6MoBi50VZVlw3Vd8mNTdyn1Hdag3LNDladpOm6QFeDlJiz2GXhRkvR9tnzD1J0g9MIjkliGM0hCRI9FC0NwklySw0BSUgKAZCAA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcEWWwCGuOlmggMUAGrr2mmAHEoELmEoBfOFksg4Aci4qJdOi6ShIsRDgpABtoOjh7RwhnFwABdwhPOgB6EQUAWhA8YB8kDAAPf3hMLHUuYOLsPEJiMgAKZFQocvoALjgAbQ6XCS46GGj05uCMF3JAkOh2l1o0FwiAXQXZOgALaBhemDp2xtRXAB5e-sG1ja2XaZgCmHTr9WCxqls1VYw9XapUSagdxC-9jRQMZ%2BO0fnQAHQcYJcDCyfZwBhSXBoEFgiChX4QujBdTXeERWQvKhpRh-DoA0lKFR1ACUBKpLDYnB4fH4dIZ8nEyLoDQBqDoEgeGHaAEYIQAmAnfNC4aarVhgHbJZL0EDY1bJJ4I2z0qjLKgaLQ6KB6X7tDpG7S6fRGEy4cyWax0g26pBAA&options=N4IgTgpgzgDg9gOygSwG4RALgGYEMA2UEANCAC5i5LZxgC2WehEAvkA)
