### ISSUE TITLE
Using `:not(selector)` inside class attribute doesn't work

### ISSUE THREAD

**Issue by vedxp** [unocss/unocss#2137]
I need to use `:not(selector)` in the `class` attribute in my project.

I tried using like this:
```html
<div class="text-base [&:not(p)]:font-bold">

<h1>UnoCSS is ❤️</h1>
<p>The instant on-demand atomic CSS engine.</p>

</div>
```

But, the `font-bold` utility gets applied to the `<p>` tag too.

Help would be much appreciated :)

**Comment by sibbng** [comment]
Add a `>` right after `&`

```html
[&>:not(p)]:font-bold
```

**Comment by vedxp** [comment]
> Add a `>` right after `&`
> 
> ```
> [&>:not(p)]:font-bold
> ```

### It didn't seem to work:
> ![Screenshot_2023-02-01-09-05-21-04_a2cf8efcdd42a8e6f7906303f104fb67~2](https://user-images.githubusercontent.com/87353286/215940041-e47e7948-e796-4ada-9b9f-11a69710745e.jpg)

---
## Lemme explain what I want to achieve.

#### I want to apply the css only to the `<p>` tag, which is marked with red
#### And the link text marked with green, which I don't want to apply the css.

#### Additional info:
> The anchor tag isn't the direct child of `<main>`. And it's ok for me to apply the css to all the children of `<main>`.

```html
<a>
Link Text
<p>Paragraph to which the css should be applied only.</p>
</a>
```

> ![Screenshot_2023-02-01-09-07-23-36_40deb401b9ffe8e1df2f1cc5ba480b12~2](https://user-images.githubusercontent.com/87353286/215940064-c83c20e9-fe47-456d-a009-f0801043df18.jpg)


### Hope this will help you understand my issue properly :)

**Comment by sibbng** [comment]
`[&_p]:font-bold`

**Comment by vedxp** [comment]
> `[&_p]:font-bold`

This worked thanks :)

One last question I wanna ask that in another div, I need the opposite of this: `[&_p]:font-bold`

So that in this code below, only the link text gets css applied not the paragraph:
```
<a>
Link Text
<p>Paragraph to which css should not apply.</p>
</a>
```

As you've already told me to use it like this: `[&>:not(p)]:font-bold`.
But it didn't work when I tried.
If I'm missing something, please correct me :)

The structure is same as of the above one:
>The anchor tag isn't the direct child of parent. And it's ok for me to apply the css to all the children of the parent.

**Comment by sibbng** [comment]
`[&_a]:font-bold [&_a>p]:font-normal`

**Comment by vedxp** [comment]
> `[&_a]:font-bold [&_a>p]:font-normal`

Hmm, I've already thought of doing this.

Though, I can use :not()  in pure css too, only for that specific element, but I really need to know how to use `:not()`selector inside class attribute since it's going to be used many times in my project.

If it's currently not possible, I'll go for pure css instead for that specific part, where I need to use `:not()` selector

Thank you for your efforts clearing my doubts :)

**Comment by vedxp** [comment]
> I suppose I've already considered doing this.
> 
> Although I can use the `:not()` selector in pure CSS as well, only for that one particular element, but I really need to learn how to use the `:not()` selector inside class attribute because it will be used frequently throughout my project.
> 
> If it can't be done right now, I'll use pure CSS for that particular section, where I need to use it.
> 
> I appreciate your efforts in helping me with my questions :)

 @sibbng 
Sir, any update regarding this?

**Comment by sibbng** [comment]
If you're looking for help with the arbitrary variants, I would suggest you create a discussion on following links with a playground sample:

- https://github.com/unocss/unocss/discussions
  - Playground: https://uno.antfu.me/play/


- https://github.com/tailwindlabs/tailwindcss/discussions
  - Playground: https://play.tailwindcss.com/
