### ISSUE TITLE
UnoCss prettier class ordering plugin

### ISSUE THREAD

**Issue by Ladvace** [unocss/unocss#2139]
is there an equivalent plugin to this one [here](https://tailwindcss.com/blog/automatic-class-sorting-with-prettier) but for unocss?

**Comment by Shyam-Chen** [comment]
```sh
pnpm i prettier-plugin-tailwindcss -D
```

**Comment by antfu** [comment]
da06c6562ddc15447a4eaa7419fdf7cc73ce8249 this commit added a utility to sort the rules, if anyone is interested, feel free to create a eslint/prettier plugin for that

**Comment by antfu** [comment]
Duplicated of https://github.com/unocss/unocss/issues/1825
