### ISSUE TITLE
vue-cli hmr not work 

### ISSUE THREAD

**Issue by macheteHot** [unocss/unocss#2144]
"@vue/cli-service": "~5.0.0",
    "unocss": "^0.49.4",
   "@unocss/webpack": "^0.49.4",

vue-cli-service serve hmr unocss not work

**Comment by lishaobos** [comment]
Can you provide a reproduction?

**Comment by macheteHot** [comment]
> Can you provide a reproduction?

here https://github.com/macheteHot/demo-css-webpack-use.git

**Comment by macheteHot** [comment]
> Can you provide a reproduction?

here https://github.com/macheteHot/demo-css-webpack-use.git

**Comment by LiuJinYang9527** [comment]
the same problem here

**Comment by a1mersnow** [comment]
Try this
https://github.com/MellowCo/unocss-preset-weapp/issues/54#event-9080881843

**Comment by zhou-tao** [comment]
same problem when using vue-cli4 or vue-cli5.
can reproduction in [unocss vue-cli5 stackblitz](https://stackblitz.com/edit/unocss-unocss-wpkj4q)

**Comment by wyangx** [comment]
have the same problem in vue-cli5

**Comment by mdxiaohu** [comment]
Have you all not solved this problem ？

**Comment by tong822218** [comment]
这个问题有解决方案了吗？
