### ISSUE TITLE
Composing class attributes in Svelte

### ISSUE THREAD

**Issue by mjablecnik** [unocss/unocss#2145]
Hello I found one small issue in combination of Svelte and Tailwind which is detailed described here: https://github.com/sveltejs/svelte/issues/8247
Exists any possibility that UnoCSS can somehow resolve this my issue?

Thank you for response

**Comment by sibbng** [comment]
Unfortunately same limitation also applies to UnoCSS. If all concatenations are known you can add them to `safelist` to use it that way: https://github.com/unocss/unocss#scanning
