### ISSUE TITLE
I customized several rules, but the vscode plug-in could not complete the smart prompt

### ISSUE THREAD

**Issue by leecobaby** [unocss/unocss#2146]
<img width="615" alt="截屏2023-02-04 00 08 21" src="https://user-images.githubusercontent.com/48404687/216651135-01731471-2003-4601-b0f7-5b202fe97a87.png">
<img width="677" alt="截屏2023-02-04 00 09 09" src="https://user-images.githubusercontent.com/48404687/216651236-7a2563e7-6b85-4397-a935-adc6a6948f1b.png">

**Comment by zyyv** [comment]
<img width="393" alt="image" src="https://user-images.githubusercontent.com/42139754/216754690-39caf93c-da11-4222-8d37-b56279a70b21.png">

<img width="219" alt="image" src="https://user-images.githubusercontent.com/42139754/216754679-d4a40747-12f8-41a1-8f76-50dfe1b472ac.png">

Check again, it's work fine.
