### ISSUE TITLE
add prefix , variants not work

### ISSUE THREAD

**Issue by MellowCo** [unocss/unocss#2148]
* no prefix , use `space-x`

![image](https://user-images.githubusercontent.com/47939250/216753535-a783ca07-4537-4185-b04c-1276802a8591.png)

* add prefix , space-x not work

![image](https://user-images.githubusercontent.com/47939250/216753586-730455c3-0f0d-46a3-8e4e-786ed44712ee.png)

> variantSpaceAndDivide not work

![image](https://user-images.githubusercontent.com/47939250/216753626-6a7b8f02-53d5-43e9-af3a-c637d8de5696.png)

**Comment by MellowCo** [comment]
[playgroup](https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCICuA7A9gWgDM4BTADyhwIAt8BWABkr3yQAcEYT8z8AWZgQC2AI3wAOdAD4AUFCihIsRCgxV8IgOb4ATiRCCipXgEZpAF3LngAenARZ8xdHjI0WFlo1xMJQ8XJ8MylLMms7SEcFe2U3NU9tTT0SbH9jIIsrW3tZbMiZAudY1XQAilpGKHZObl4BIXN%2BaTlopVcSrz0DMoyQrIiHFqL29y8RHz8e4NDwnKGYkYwvJJIUqCnMsLzB7dkgA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCqWEcAvnOlBCHAOQCujAYypVuAKFGoAHpFgoMAQ14AbeGkw58hYEQAUCUXHKUaMKgC44AbQOGj1Wgwh6btu5kkW%2BjALTcSLlgBKf0MAXX9mQNEgA&options=N4IgzgLgTglgxhEAuaBXApgGhNAhgOzADMB7KAW2SNwBsx0BfIA)

**Comment by zyyv** [comment]
Had the same problem a long time ago #1246

**Comment by MellowCo** [comment]
but I set the prefix
```ts
presetUno({
   prefix: 'uno-',
}),
```
If do not set `uno-` prefix, it will not be able to use
