### ISSUE TITLE
needed css for valueless attributify classes in safelist not generated

### ISSUE THREAD

**Issue by alisdg** [unocss/unocss#2162]
### UnoCSS version

"0.49.4"

### Describe the bug

Hi, i am new to this wonderful repo and i was trying out unocss for my very first time. 
i was trying to do something like this: 
`<p :bg-blue="someCondition">Some paragraph!</p>
`
i know for runtime cases like this i should put my class in safelist:
`safelist: 'm-auto bg-blue'.split(' '),
`
so i expect to not worry about using 'bg-blue'  anyway. however the above scenario will not work unless i use 'bg-blue' in a static valueless attributify situation somewhere else so the corresponding css can generate at build time. eg: 
`<div bg-blue> ... </div>
`
also this is my unocss.config.ts for attributify preset:
`presetAttributify({
      trueToNonValued: true
    }),`

### Reproduction

https://github.com/alisdg/unocss-test

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [x] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [ ] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by macheteHot** [comment]
app.vue 14 line hidden bg-red is match regex

**Comment by alisdg** [comment]
> app.vue 14 line hidden bg-red is match regex

hi @macheteHot . I don't really get your point. I know the red paragraph is working fine. 
let me simplify the issue, i think `[bg-blue=""], [bg-blue=true]` styles should also be generated alongside `.bg-blue` for bg-blue class if it is in the **safelist**

**Comment by alisdg** [comment]
i don't know if this is the right thing to do, but this can be solved by writing a variant for all my classes in safelist and adding `[bg-blue=""], [bg-blue=true]` selectors manually.

**Comment by chu121su12** [comment]
Since safelist's tokens are just added directly to the list of tokens to be processed without modification, you may want to do additional processing to make attributify tokens. Something like
```js
safelist: 'm-auto bg-blue'.split(' ').flatMap(x => [x, `[${x}=""]`, `[${x}=true]`]), 
```
