### ISSUE TITLE
[plugin:vite:css] [less] @apply rule is missing block or ending semi-colon

### ISSUE THREAD

**Issue by chioio** [unocss/unocss#2173]
### UnoCSS version

^0.49.4

### Describe the bug

Code first:
```html
<style scoped lang="less">
.n-card {
  :deep(.n-card__content) {
    @apply h-[calc(100vh-20vh)] overflow-auto;
  }
}
</style>
```
The code `h-[calc(100vh-20vh)]` triggered this error:
> [plugin:vite:css] [less] @apply rule is missing block or ending semi-colon

### Reproduction

https://stackblitz.com/edit/unocss-unocss-zkjef1?file=vite.config.ts,src%2FApp.vue

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sibbng** [comment]
First of all, you have mixed versions of unocss on your repro. After upgrading unocss to ^0.49.4 the error you mentioned appears. My guess is less don't work nicely with brackets in at-rules.

Some solutions that fixes the error:

- `enfore: "pre"`
```ts
transformers: [transDirectives({enforce:"pre"}), transVariantGroup()],
```

or

- use `--at-apply`

```css
.demo {
  --at-apply: "h-[calc(100vh-20vh)] overflow-auto";
}
```
