### ISSUE TITLE
能实现一个规则，多个样式么？

### ISSUE THREAD

**Issue by rociez** [unocss/unocss#2175]
### Clear and concise description of the problem

bootstrap里，一些hover样式，是直接写在css里的，比如
<div class=''link-primary'>link-primary</div>
.link-primary {
    color: #206bc4 !important;
}

.link-primary:hover, .link-primary:focus {
  color: #1a569d !important;
}

-------------------------------------------------------------
如果我想只写一个 rule ，能在 uno.css 里，动态生成上面两个样式么？

### Suggested solution

能否提供这样的规则：

rules:[
  ['link-primary',{
	'link-primary':{
	   'color': '#206bc4 !important'
	},
	'link-primary:hover':{
	   'color': '#1a569d !important'
	},
	'link-primary:focus':{
           'color': '#1a569d !important'
	}
  }]
]

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [x] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://uno.antfu.me).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by zyyv** [comment]
参考文档：https://github.com/unocss/unocss#full-controlled-rules

或者使用 Shortcuts 配置 [Playground](https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCI5gHYGsAKATmALYKECe6AfACoCmSALrAPYj3AD04E1AUEA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCqWEcAvnOlBCHAOQCujAYypVuAKFGoAHpFgoMAQ14AbeGkw58hYEQAUCUXDhUAFtBgDeMKgC5EBwzyXYA1gAUooeVACe3W9xgpGABaSmQ4UwA3VChgwMkQgCMlXlQ4eQEYYGi4oNz5JW4Se2ZiwwpqWhs4AG0KmnpGHQBKAF1i5mbRIA&options=N4IgzgLgTglgxhEAuaBXApgGhNAhgOzADMB7KAW2SNwBsx0BfIA)

**Comment by rociez** [comment]
已解决，谢谢

**Comment by mdxiaohu** [comment]
> 已解决，谢谢

有示例没，是直接创建爱你多条规则么？
