### ISSUE TITLE
The styles in `--at-apply` are not handled by the plugin in `postcss`

### ISSUE THREAD

**Issue by cinob** [unocss/unocss#2176]
### UnoCSS version

0.48.5

### Describe the bug

I used the `postcss-pxtorem` plugin to convert px to rem.
But the classes written in `--at-apply` are not converted to rem
```
--at-apply:  'px-30px'
```
Is there any way to make it work?

### Reproduction

~

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by MellowCo** [comment]
use `class` can convert px to rem, but use `--at-apply` not ?

**Comment by lincenying** [comment]
```
import { defineConfig, presetAttributify, presetUno, transformerDirectives } from 'unocss'

const pxRE = /(-?[\.\d]+)px/g

function pxToRemPreset(options = {}) {
    const { baseFontSize = 100 } = options

    return {
        name: '@unocss/preset-px-to-rem',
        postprocess: util => {
            util.entries.forEach(i => {
                const value = i[1]
                if (value && typeof value === 'string' && pxRE.test(value)) i[1] = value.replace(pxRE, (_, p1) => `${p1 / baseFontSize}rem`)
            })
        }
    }
}

export default defineConfig({
    shortcuts: [],
    presets: [presetUno(), presetAttributify(), pxToRemPreset()],
    transformers: [transformerDirectives()],
    safelist: 'prose prose-sm m-auto text-left'.split(' '),
    rules: []
})
```

自己弄个转换插件, 把unocss的px单位先转成rem, 不通过postcss插件来处理, 其他手写或者是UI库的px单位则通过postcss插件来处理

<img width="566" alt="image" src="https://user-images.githubusercontent.com/10840991/222074221-9b051ebb-842e-4e08-a6c4-cb80f38fdac3.png">

**Comment by cinob** [comment]
> ```
> import { defineConfig, presetAttributify, presetUno, transformerDirectives } from 'unocss'
> 
> const pxRE = /(-?[\.\d]+)px/g
> 
> function pxToRemPreset(options = {}) {
>     const { baseFontSize = 100 } = options
> 
>     return {
>         name: '@unocss/preset-px-to-rem',
>         postprocess: util => {
>             util.entries.forEach(i => {
>                 const value = i[1]
>                 if (value && typeof value === 'string' && pxRE.test(value)) i[1] = value.replace(pxRE, (_, p1) => `${p1 / baseFontSize}rem`)
>             })
>         }
>     }
> }
> 
> export default defineConfig({
>     shortcuts: [],
>     presets: [presetUno(), presetAttributify(), pxToRemPreset()],
>     transformers: [transformerDirectives()],
>     safelist: 'prose prose-sm m-auto text-left'.split(' '),
>     rules: []
> })
> ```
> 
> 自己弄个转换插件, 把unocss的px单位先转成rem, 不通过postcss插件来处理, 其他手写或者是UI库的px单位则通过postcss插件来处理
> 
> <img alt="image" width="566" src="https://user-images.githubusercontent.com/10840991/222074221-9b051ebb-842e-4e08-a6c4-cb80f38fdac3.png">

非常感谢❤️

**Comment by chenxch** [comment]
@lincenying 这个方案目前存在一定概率不转换，`const pxRE = /(-?[\.\d]+)px/g` 这里直接用pxRE循环使用是有bug的（和这个bug无关）

**Comment by lincenying** [comment]
> 

没有遇到过, 给个例子看看

**Comment by chenxch** [comment]
![image](https://github.com/unocss/unocss/assets/23251408/fe1000a7-9495-4be7-8730-ed96f96d06e5)

![image](https://github.com/unocss/unocss/assets/23251408/f840cc94-fb61-4bd6-96cc-7717201e0bd6)

**Comment by chenxch** [comment]
问题就是插件概率性的不工作了

**Comment by chenxch** [comment]
左边是工作时候转换了，右边是不工作的时候

**Comment by lincenying** [comment]
你可以在插件里打印下`util.entries`, 看看能不能看到原始unocss样式
排查下是unocss就没提供, 还是正则没匹配到

**Comment by MellowCo** [comment]
unocss的presets 只会更新unocss生成的代码的。unocss本事就是主张不用postcss的

**Comment by MellowCo** [comment]
unocss现在有个 postcss 插件，可以尝试下

https://github.com/unocss/unocss/tree/main/packages/postcss

**Comment by lincenying** [comment]
```
if (value && typeof value === 'string' && pxRE.test(value)) {
    i[1] = value.replace(pxRE, (_, p1) => `${p1 / baseFontSize}rem`)	
}
```
可以在这附近打印下, 看下是什么原因没有进入if条件

=======

如果没有用原生的css写, 是不需要用postcss插件的

**Comment by chenxch** [comment]
> unocss现在有个 postcss 插件，可以尝试下
> 
> https://github.com/unocss/unocss/tree/main/packages/postcss

好的，我试一下

**Comment by chenxch** [comment]
> ```
> if (value && typeof value === 'string' && pxRE.test(value)) {
>     i[1] = value.replace(pxRE, (_, p1) => `${p1 / baseFontSize}rem`)	
> }
> ```
> 
> 可以在这附近打印下, 看下是什么原因没有进入if条件
> 
> =======
> 
> 如果没有用原生的css写, 是不需要用postcss插件的

![image](https://github.com/unocss/unocss/assets/23251408/7c409348-c79d-4cc8-98b8-15e939b40d5d)  unocss这把处理的时候已经是被postcss转换过了

**Comment by chenxch** [comment]
https://github.com/cuth/postcss-pxtorem/issues/87
@lincenying  @MellowCo 问题已解决，是postcss-pxtorem的问题，对其降级解决。
