### ISSUE TITLE
sizes sorting error

### ISSUE THREAD

**Issue by wusaby-rush** [unocss/unocss#2180]
### UnoCSS version

0.49.4

### Describe the bug

unocss make sizes sorting descending which should be ascending

for example rounded-full came befor rounded-md, text-2xl came before text-sm, we start from small sizes to big not reverse

### Reproduction

https://uno.antfu.me/play/?html=DwEwlgbgfAUABAupJwMYBsCGBnbBeAIgCMBzAWgHcALMAFwFM4GAPWskTAJwGs4BbMgFY4ABzIAWJvVZlsfKTPQkFbAGzN0cTgHsArgDsQ9EGT4gtew8bIAzXenQFYiRAe2pc8RMAD04aDC%2B-lBAA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiRZDE3sThSANtAAUANwCG7Nx3sYAlIipaGC4oXDgAAyhSDlcPJwASBHdPbww1X19wpDVzDAAPSFh0bDcue3hMHHwiEmBSJ2RUGAALDBAMAC4A1FQHaDouxp7eiEcoQaph1AAGLr1SWgxcPVkpuABWWbtR5z0AWj2%2BqD3NvV9VqYBGaa29AGIbrCwblcmpgCYbuaiY5KcDo4naYZMxrHLDcFwNSyKBlehdADabwRegkXDoMB0e1hPhWiG2Y2%2BGDQeihAF0qGTZHRmtAYGiYANuj1UejMSA9jS6Qy9HMYPkYHt7KQ4Py8oLoG5cKQMHBaS4MOMxYL%2BW57KCobIRAomUjhtrGMoIE5zm8DcxWOxuLwBCaLubJNIGm9UHQJGrOnBLgA6d4XXpoXBzZqsMADAD04foIG9NPDGtQ6VkFPSSCAA&options=N4XyA

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sibbng** [comment]
Thanks for your suggestion, but this is an unnecessary breaking change for existing users. We care about the compatibility of presetUno with Tailwind CSS to make switching between these projects more straightforward. For the example you provided, the order of generated rules matches with Tailwind CSS. Even Tailwind's itself doesn't care much about the order of utilities that comes from the same source. For example, `text-[2rem]` will be generated before `text-lg`. Using multiple utility classes that belong to the same utility is counterintuitive and they should be applied conditionally depending on the context.
