### ISSUE TITLE
✨ Allow writing plain CSS in playground

### ISSUE THREAD

**Issue by jd-solanki** [unocss/unocss#2181]
### Clear and concise description of the problem

We don't have an editor to write raw CSS in the playground for providing a reproducible examples. We do have [preflight](https://github.com/unocss/unocss#preflight) option but providing separate CSS panel is more convenient just like tailwind:
![image](https://user-images.githubusercontent.com/47495003/218000570-cc230710-3b4f-4d1c-83ca-ce92ca814aab.png)
reproducible examples

### Suggested solution

Provide a separate CSS panel just like "Ouput CSS"

### Alternative

Using Tailwind Playground for now

### Additional context

N/A

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://uno.antfu.me).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by zyyv** [comment]
I would like to make it happen. I might need some advice on the UI panel. 
/cc @antfu
