### ISSUE TITLE
Ctrl+Space does not work on archlinux (endeavouros)

### ISSUE THREAD

**Issue by Scouterdev** [unocss/unocss#2182]
### UnoCSS version

0.22.5

### Describe the bug

Issue Type: Bug

- Launch vscode
- Open a *.svelte or *.astro file
- Place your cursor anywhere code completion would be available
- Press Ctrl+Space
    Expected: IntelliSense popover should appear
    Actual: Nothing happens 
- Hover Preview
   Expected: See the complete CSS for a class name by hovering over it.
   Actual: Working, all good.

Used Extensions: **Unocss**, **Svelte**, **Astro**.
VSCODE > settings.json (emty)

update: **[FIX IT](https://github.com/unocss/unocss/issues/2182#issuecomment-1427830173)**

### Reproduction

https://open-vsx.org/extension/antfu/unocss

### System Info

Version: 1.75.0
Date: 2023-02-04T10:31:04.465Z
Electron: 19.1.9
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 6.1.10-arch1-1

**Comment by so1ve** [comment]
I don't think this is an Unocss bug. It should be that some software occupies your shortcut keys?

**Comment by Scouterdev** [comment]
I am try install WindiCSS  extensions and working all good.. 
If be that some software problem, then will does not working WindiCSS..

**Comment by renejfc** [comment]
Came here because of the same issue. After looking for a while it looks like autocompletion isn't fully functional yet.

As [antfu said](https://github.com/unocss/unocss/issues/1363#issuecomment-1221593249) on #1363:

> For now, the autocomplete is only triggered by `:` and `-`.
> 
> https://github.com/unocss/unocss/blob/b727d55121e7b4946a951c6654a48e542f13caaf/packages/vscode/src/autocomplete.ts#L128-L132
> 
> I do not yet know a better way to do that. If you got any idea, PR would be greatly welcome. Thanks.

So basically, it'll work after typing something like `bg-` or `hover:`

**Comment by so1ve** [comment]
yep. here's the real reason: currently autocompletion is only triggered by certain delimiters.

**Comment by Scouterdev** [comment]
I am fix it problem!
uninstalled code (vscode) on archlinux - endeavouros:
yay -S **code**

and instead :+1: 
yay -S **visual-studio-code-bin**

Press Ctrl+Space
Expected: IntelliSense popover should appear
Actual: All working, fix it
