### ISSUE TITLE
Custom preset `prefix` is not works

### ISSUE THREAD

**Issue by aliuq** [unocss/unocss#2184]
### UnoCSS version

0.49.4

### Describe the bug

![image](https://user-images.githubusercontent.com/11707934/218238406-b7602a52-5246-41c9-8834-14f143f3a5f5.png)

### Reproduction

[Link](https://stackblitz.com/edit/vite-unocss-bifaqx?file=unocss.config.ts&file=src%2FApp.vue)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Readpato** [comment]
Hey there! This is not a bug. You are adding the `w` prefix only and in your HTML code you are using the `w-` prefix. If you add a hyphen in front of your prefix on your config like this  `prefix: 'w-'`, it works as it is supposed to.

You chan check it out here: [Stackblitz reproduction](https://stackblitz.com/edit/vite-unocss-cvbhuj?file=unocss.config.ts)

<img width="1326" alt="image" src="https://user-images.githubusercontent.com/87768087/218310926-be228fe4-b58f-4a71-b508-446870895dc4.png">

**Comment by aliuq** [comment]
@Readpato Thank you for your reply
