### ISSUE TITLE
`presetTypography` crashes in `shadow-dom` mode

### ISSUE THREAD

**Issue by kwaa** [unocss/unocss#2189]
### UnoCSS version

0.49.4

### Describe the bug

`import 'uno.css'` works properly.

```bash
[vite] Internal server error: Transform failed with 1 error:
/home/projects/vitejs-vite-4vjnrm/src/my-element.ts:19:1555: ERROR: Expected ";" but found "\";}.prose :where(pre):not(:where(.not-prose,.not-prose *)){padding:1.25rem 1.5rem;overflow-x:auto;border-radius:.375rem;}.prose :where(pre,code):not(:where(.not-prose,.not-prose *)){white-space:pre;word-spacing:normal;word-break:normal;word-wrap:normal;-moz-tab-size:4;-o-tab-size:4;tab-size:4;-webkit-hyphens:none;-moz-hyphens:none;hyphens:none;background:transparent;}.prose :where(pre code):not(:where(.not-prose,.not-prose *)){font-weight:inherit;}.prose :where(ol,ul):not(:where(.not-prose,.not-prose *)){padding-left:1.25em;}.prose :where(ol):not(:where(.not-prose,.not-prose *)){list-style-type:decimal;}.prose :where(ol[type=\""
  Plugin: vite:esbuild
  File: /home/projects/vitejs-vite-4vjnrm/src/my-element.ts:19:1555
```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-4vjnrm

### System Info

StackBlitz

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kwaa** [comment]
The problem still exists in the latest version.

**Comment by kwaa** [comment]
The problem still exists in the latest version.
https://stackblitz.com/edit/vitejs-vite-74rxnx

**Comment by zyyv** [comment]
Thank you for your discovery, I will try to solve it when I have time.

**Comment by kwaa** [comment]
👀
