### ISSUE TITLE
VSCode Extension should not work on css property

### ISSUE THREAD

**Issue by A-kirami** [unocss/unocss#2194]
### UnoCSS version

v0.49.4

### Describe the bug

![image](https://user-images.githubusercontent.com/66513481/218659303-af4ce94f-17b5-4270-abe8-4f1e1640c8cf.png)
![image](https://user-images.githubusercontent.com/66513481/218660664-4c52f066-a108-4ca3-98f2-4d24d7f2d4b4.png)

### Reproduction

1. Use VSCode install the Extension
2. Create a new `style. css` file and write the following contents
```css
.class {
  display: flex;
  overflow: hidden;
}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by imranbarbhuiya** [comment]
https://github.com/unocss/unocss/issues/2203#issuecomment-1434739587
