### ISSUE TITLE
transformerDirectives and theme not working in nextjs / webpack

### ISSUE THREAD

**Issue by Alexnortung** [unocss/unocss#2195]
### UnoCSS version

0.49.4

### Describe the bug

I am trying to use transformerDirectives in my nextjs application that uses webpack. The theme is not taking any effect and the transformer directives does not seem to work.

### Reproduction

https://stackblitz.com/edit/nextjs-uvg3hv?file=lib%2Fassets%2Fglobal.scss,pages%2Findex.tsx,unocss.config.ts

Look at `lib/assets/globals.scss`, `styles/globals.css`, `pages/_app.tsx` and `pages/index.tsx` for the classes applied.

In `pages/index.tsx` I havde added `text-red-500` which works like it should, but `text-lavender` does not work, even though it has been added to the theme in `unocss.config.ts`.

### System Info

Stackblitz and Linux (NixOS)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by MellowCo** [comment]
transformerDirectives only be used in vite

**Comment by Alexnortung** [comment]
Thanks, would it make sense to add support for webpack too, just like windi has?

**Comment by wkeylin** [comment]
> Thanks, would it make sense to add support for webpack too, just like windi has?

Hello, you can modify the `unocss.config.ts` file to support `transformerDirectives`
```diff
+ include: [/(styles|lib|pages).*\.(s?css|[jt]sx?)$/],
+ exclude: [], 
transformers: [
+    transformerDirectives({
+      enforce: 'pre',
+    }),
    transformerDirectives({
      //enforce: 'default',
    }),
  ],
```
In `@unocss/webpack` source code, it filters out transformer with an enforce value other than `pre` and exclude `styles file`. 

https://github.com/unocss/unocss/blob/7164bdecc051078d18ab1765d8d00f110e485b40/packages/webpack/src/index.ts#L57-L61
https://github.com/unocss/unocss/blob/7164bdecc051078d18ab1765d8d00f110e485b40/packages/transformer-directives/src/index.ts#L49-L58
https://github.com/unocss/unocss/blob/7164bdecc051078d18ab1765d8d00f110e485b40/packages/core/src/utils/helpers.ts#L4

https://github.com/unocss/unocss/blob/7164bdecc051078d18ab1765d8d00f110e485b40/packages/shared-integration/src/transformers.ts#L24-L29

**Comment by wkeylin** [comment]
Or you can try the latest `@unocss/postcss`

**Comment by jukrb0x** [comment]
> Or you can try the latest [@unocss/postcss](https://github.com/unocss/unocss/tree/main/packages/postcss)

not working for me, I am using next 13.2.4 along with @unocss/webpack.

**Comment by wkeylin** [comment]
> > Or you can try the latest [@unocss/postcss](https://github.com/unocss/unocss/tree/main/packages/postcss)
> 
> not working for me, I am using next 13.2.4 along with @unocss/webpack.



> > Thanks, would it make sense to add support for webpack too, just like windi has?
> 
> Hello, you can modify the `unocss.config.ts` file to support `transformerDirectives`
> 
> ```diff
> + include: [/(styles|lib|pages).*\.(s?css|[jt]sx?)$/],
> + exclude: [], 
> transformers: [
>     transformerDirectives({
> -      //enforce: 'default',
> +     enforce: 'pre',
>     }),
>   ],
> ```
> 
> In `@unocss/webpack` source code, it filters out transformer with an enforce value other than `pre` and exclude `styles file`.
> 
> https://github.com/unocss/unocss/blob/7164bdecc051078d18ab1765d8d00f110e485b40/packages/webpack/src/index.ts#L57-L61
> 
> 
> https://github.com/unocss/unocss/blob/7164bdecc051078d18ab1765d8d00f110e485b40/packages/transformer-directives/src/index.ts#L49-L58
> 
> 
> https://github.com/unocss/unocss/blob/7164bdecc051078d18ab1765d8d00f110e485b40/packages/core/src/utils/helpers.ts#L4
> 
> https://github.com/unocss/unocss/blob/7164bdecc051078d18ab1765d8d00f110e485b40/packages/shared-integration/src/transformers.ts#L24-L29

@jukrb0x and this?

**Comment by jukrb0x** [comment]
@wkeylin Thanks for your fast reply. I've tried this method as well, it turns out the other parts of stylesheets are messed up, and it doesn't transform `@apply` in .scss file.

<img width="603" alt="image" src="https://user-images.githubusercontent.com/15688641/225610790-8e060b72-382e-43d3-abc4-ab8d30bda706.png">

**Comment by jukrb0x** [comment]
codesandbox: https://codesandbox.io/p/github/jukrb0x/wh0.is/unocss-directive-troubleshoot

<img width="517" alt="image" src="https://user-images.githubusercontent.com/15688641/225616303-04f2695d-b869-4a8d-9a2f-73702cc3037a.png">

**Comment by wkeylin** [comment]
But 

> https://codesandbox.io/p/github/jukrb0x/wh0.is/unocss-directive-troubleshoot

You can change the `include `config to `[/src\/(styles).*\.(s?css)$/]`

In this demo there is no problem, https://stackblitz.com/edit/nextjs-t5xgax?file=lib%2Fassets%2Fglobal.scss,pages%2Findex.tsx,unocss.config.ts

**Comment by sibbng** [comment]
> it doesn't transform `@apply` in .scss file.

@jukrb0x This will be fixed with #2338

**Comment by jheng-jie** [comment]
@sibbng this fix. Can @unocss/postcss use @apply in scss files？

**Comment by sibbng** [comment]
> @sibbng this fix. Can `@unocss/postcss` use `@apply` in scss files？

Yes.

**Comment by Alexnortung** [comment]
I am still having issues with this. It is not working in either my scss files or

**Comment by Alexnortung** [comment]
Oh I forgot the `exclude: []`, apparently it did not work without it.

**Comment by mdxiaohu** [comment]
> Or you can try the latest [@unocss/postcss](https://github.com/unocss/unocss/tree/main/packages/postcss)或者你可以尝试最新的@unocss/postcss
@unocss/postcss .
Can Postcss version 6 be supported .
I think the latest version requires version 8 .

**Comment by greenhat616** [comment]
Not stale
