### ISSUE TITLE
Arbitrary variant grouping doesn't work

### ISSUE THREAD

**Issue by Akryum** [unocss/unocss#2202]
### UnoCSS version

0.49.6

### Describe the bug

Using grouping with an arbitrary variant doesn't work.

Doesn't work:

```html
<div class="[:focus-within>&]:(text-red-500 opacity-100)" />
```

Works:

```html
<div class="[:focus-within>&]:text-red-500 [:focus-within>&]:opacity-100" />
```

### Reproduction

https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIC2BTA9gd3QD4AoKKUSWRFDXABwRjABcBPAWgFYAGKAbQB0OAkQBkAXQBcLbAA8WHAE7YQ3HnyEj846QyatOARg3EAsnnzAA9OAikyFO9WRp0%2B5u3UDhl3VIAKWQVlVXU%2BD0MOEx4ASnNLGztSJMgHSntHDJdad0ZPTl4BKQAzXBgAVyQOfFYACzAAO39gxRU1Xk1S8qqa%2Bqb-SK8Y4kdyCwIs2zSSLOd4Vzp8qKL%2Bbsrq2pYG5slA1tCOjSgh4w14ogmracyspvoKlihrFJvSIA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAkgMbF2Wo32MCquESgF84WKBBBwA5AFcBLOnSlIkGAB6RY6bAEMZAG3iYc%2BIiWCkAFMi60GMOgC44AbSq2eMfhEsBKTqjUdoys7NbugXQsOvoYzgCMAHQATAGBcCxouM5SABYwMGBOAPTF9CCJdLnFyulC-lQAukj1SEA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sibbng** [comment]
Your config missing `transformerVariantGroup`. 

[Working playground](https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIC2BTA9gd3QD4AoKKUSWRFDXABwRjABcBPAWgFYAGKAbQB0OAkQBkAXQBcLbAA8WHAE7YQ3HnyEj846QyatOARg3EAsnnzAA9OAikyFO9WRp0%2B5u3UDhl3VIAKWQVlVXU%2BD0MOEx4ASnNLGztSJMgiKBISSnsM8myXWndGT05eASkAM1wYAFckDnxWAAswADt-YMUVNV5NSuq6hua2-0ivGOJHcgsCR1SczLzneFc6Yqiy-n7a%2BsaWFvbJQM7Qno0oMeMNeKIZq1s0xYo2%2BhqWKGsUh-sSIA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAkgMbF2Wo32MCquETnBhQAhrjpZoIDFABqoqMHEwA4lAgBXMHCQBfOFg0g4Ack0CWdOqaRIMAD0ix02UZoA28TDnxESwKQAFMhctAwwdABccADaVGE8MPwQQQCUQokRrOwhCahwdCyiHhgxAIwAdABMmQUsaLgxpgAWMDBg0QD0XfQglXQtXbYFcHoZVAC6QiLiktKy0XGzElJQMvKKyrhqGtrpk-ppSEA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g)

Config:
```ts
import {
  defineConfig,
  presetIcons,
  presetUno,
  transformerVariantGroup 
} from 'unocss'

export default defineConfig({
  presets: [
    presetUno(),
    presetIcons({
      scale: 1.2,
      cdn: 'https://esm.sh/'
    }),
  ],
  transformers: [transformerVariantGroup()]
})
```

**Comment by Akryum** [comment]
Ok it works by adding the transformer manually. I got confused because it was working in shortcuts :cat2: 
Shouldn't this transformer be included in `presetWind` (and by extension `presetUno`) to be compatible with WindiCSS?

**Comment by antfu** [comment]
Tansformers will modify the source code, and can be bundler specific. Not including them in the default preset is to raise the awareness by explicit opt-in and making it composable.
