### ISSUE TITLE
Comments are not ignored 

### ISSUE THREAD

**Issue by jozefmery** [unocss/unocss#2203]
### UnoCSS version

`v0.49.6`

### Describe the bug

Classes in comments are unexpectedly parsed, and included in the generated CSS. Commented classes are also picked up by the VS Code extension. This provides a safe-listing mechanism, but according to the README, safe-listing should be done using the configuration file, thus I believe this behavior is a bug.

### Reproduction

Simply comment a class, e.g. in HTML: `<!-- bg-red -->`, or JS: `// bg-red`. Assuming the commented class is not present anywhere else, it should not be included in the generated CSS. See [playground](https://uno.antfu.me/play/?html=DwQgtGAEBGDmYCcCmATSBLAzhgdgYwBsBXFVXSAFwAslJYkckEBDCsgYQGVOAaSTKgHsiBNNFpIAtgAcKAT0gQAfACggA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAqrhJQL5xZQQhwDkAV1YBjOnX5IkGAB6RY6bAENBAG3iYc%2BIiWCkAFMlQ16jOgC44AbSrHaDZq30BKSqgC6Sds6RA&options=N4IgzgLgTglgxhEAuaBXApgGhFdYAOA9gHZgwBu6yAZgIYA2Y6AvkA) reproduction. 

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
This is not a bug, unocss uses the `split extractor` from your source code to extract the atomic class name as much as possible, even though the atomic token is in the comment.

**Comment by lvjiaxuan** [comment]
Maybe an option can be added to decide whether to extract utilities in the comments.
