### ISSUE TITLE
Generating style for `color: inherit` + Interactive docs weird classes

### ISSUE THREAD

**Issue by jd-solanki** [unocss/unocss#2208]
### UnoCSS version

v0.49.7

### Describe the bug

Can't create style for `color: inherit`

None of below works:
- https://uno.antfu.me/?s=text-inherit
- https://uno.antfu.me/?s=text-color-inherit

Weird (random) classes:
![image](https://user-images.githubusercontent.com/47495003/219801493-882c53c2-4205-472d-bebe-c2fc6422b455.png)

> **Note**
> Both URL produces wrong styles

### Reproduction

N/A

### System Info

N/A

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by danielwaltz** [comment]
I used `color-inherit` in my project to achieve that, but I agree it's not super intuitive. At least it's possible!

https://uno.antfu.me/?s=color-inherit

**Comment by jd-solanki** [comment]
oh, Previously it was working 🙄
