### ISSUE TITLE
transformerDirectives without postcss

### ISSUE THREAD

**Issue by MellowCo** [unocss/unocss#2209]
### UnoCSS version

0.49.4

### Describe the bug

in wechat miniprogram use rpx as size unit，but in uniapp it will according to the compilation environment, rpx will be transferred to rem in h5

> use class, rpx can transform rem

![image](https://user-images.githubusercontent.com/47939250/219829130-2e3486ab-8c43-4153-81d3-cc80b26b193b.png)

> use @apply rpx can not transform

![image](https://user-images.githubusercontent.com/47939250/219829152-a399ad4f-9428-45c5-984b-3193bfe97d75.png)

### Reproduction

https://github.com/MellowCo/bug-unocss-directives

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by MellowCo** [comment]
1. clone https://github.com/MellowCo/bug-unocss-directives
2. run `nr dev:h5`

**Comment by MellowCo** [comment]
same question https://github.com/unocss/unocss/issues/2176

**Comment by MellowCo** [comment]
> `[unocss-applet](https://github.com/unocss-applet/unocss-applet)` This problem has been fixed in the latest version, but the function of setting conversion ratio is abnormal at H5 platform . The style of the H5 platform is abnormal. I don't know how to solve it. It should be handled by the vite plugin

uniapp has postcss plugin used to convert rpx,`unocss vite` support postcss,preset tranform is not required.
transformerDirectives without transform in postcss plugin

**Comment by Dunqing** [comment]
You can see [here](https://uno.antfu.me/?s=w-200px), `unocss` do not transform to `rem` when the class name contain unit

**Comment by MellowCo** [comment]
> You can see [here](https://uno.antfu.me/?s=w-200px), `unocss` do not transform to `rem` when the class name contain unit

The css generated by class is processed by postcss , but transformerDirectives not
