### ISSUE TITLE
[VSCode] When using alongside Python extension, UnoCSS breaks after opening `package.json` file

### ISSUE THREAD

**Issue by cuongvuong-phoenix** [unocss/unocss#2210]
### UnoCSS version

0.49.7

### Describe the bug

When switching to the `package.json` file, even though I didn't edit anything, the VSCode extension lost all auto-suggestion and I couldn't hover on many classes (some still worked though) to inspect their value.
I then inspect the Output panel of UnoCSS and found that:
- For auto-suggestion loss: 
  ![image](https://user-images.githubusercontent.com/55590597/219829998-924e7024-296c-4e21-9f35-24896a019581.png)
- For hovering on classes not working:
  ![image](https://user-images.githubusercontent.com/55590597/219830028-8c3dbd61-5776-466f-a9c1-11ab42710e85.png)

From the images, you can see that the extension still recognized there are 2 classes being used in the current file, but hovering over them was impossible.

I also realized that if I turn off `unocss.colorPreview` feature, it can successfully parse the classes and I can hover them normally, but the auto-suggestion still results in errors.

I eventually bisect-ed my installed extensions and found that the root cause is from the [Python extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python). Just disable it and everything will work seamlessly!

### Reproduction

This issue is only relevant to the VSCode extension so I won't upload to any playground/online code editors. Just follow these simple steps:

1. Create any project that has UnoCSS in it (I used Vite + Vue)
2. Open the newly created project using VSCode with UnoCSS + [Python](https://marketplace.visualstudio.com/items?itemName=ms-python.python) extensions turned on
3. Edit HTML classes as usual to make sure everything is working fine
4. Open `package.json` file
5. Try to edit HTML classes again and you will see that UnoCSS's auto-suggestion + hover will break

### System Info

- OS: _EndeavourOS Linux x86_64_
- Kernel: _6.1.12-arch1-1_

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sibbng** [comment]
I did reproduce the issue. It seems fixed in [#20626](https://github.com/microsoft/vscode-python/pull/20626). Switching to pre-release version of Python extension fixed the issue.
