### ISSUE TITLE
Feature request: enable providers to resolve to custom urls

### ISSUE THREAD

**Issue by JessicaSachs** [unocss/unocss#2237]
### Clear and concise description of the problem

I can't use a 3rd party font provider in production due to CSP + security issues. I'd like to be able to specify the location of the fonts I'm using.

### Suggested solution

We could add a `provider` function on each font so that you could load custom fonts from certain places (CDN, s3, wherever) and use Google or the primary provider as a fallback.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://uno.antfu.me).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by zyyv** [comment]
We have this field in the `preset-web-fonts` opiton, can it help you? 
https://github.com/unocss/unocss/blob/0e5434f4635981a7812c06b401794564c57731d7/packages/preset-web-fonts/src/index.ts#L53C19-L54

**Comment by JessicaSachs** [comment]
I don't think so. Isn't `customFetch` is executed node-side?

I want to change the value of what `url("https://whateverUrl")`  value in the font-face is.

**Comment by antfu** [comment]
Now the `provider` options accept passing a custom "Provider" object

https://github.com/unocss/unocss/blob/ca4f6686985c3a67bd270d79beea1f2851c5fa4d/packages/preset-web-fonts/src/types.ts#L58-L64
