### ISSUE TITLE
Certain token sequences break matching in attributify mode

### ISSUE THREAD

**Issue by jozefmery** [unocss/unocss#2243]
### UnoCSS version

Started in `v0.49.5`, present in latest `v0.50.0`.

### Describe the bug

Using the attributify preset, certain very specific token sequences can break the matcher, causing certain utilities to be omitted from the generated CSS. The issue reproduction requires very specific conditions, e.g., multiple template literals, and type definitions in specific places. In the playground (or repo), moving the type definition to the top, changing it to `type Type = object;`, or removing the last line (template literal) all fix the issue. I tried enforcing the prefix by using the following preset settings: `presetAttributify({ prefix: "u-", prefixedOnly: true, strict: true })` without success. Downgrading to `v0.49.4` resolves the issue.

A possible source of this issue may be PR #2186. Although it was later somewhat addressed with PR #2207, there may still be an issue. I may be completely wrong on this (apologies if that is the case).

### Reproduction

See [playground](https://uno.antfu.me/play/?html=GYVwdgxgLglg9mABAQQBQEpEG8BQjEBOAplCAUgDwAmMAbosHHALxYAGAJFgKwC%2BbvRAHoAfAG4cvHFACeAByKIAKvMXNEAIgAeGiaEiwEiAEIZseQiTKUa9AEYBzZhuJUNw8ZJwQEAZyiIWojqnDz8EkA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCCMMUwARgK4zDoCeZF1tAKpYIcAL5x0UCCDgByNiIDGVKnIBQ61AA9IsFBgCGbADbw0mHPkLAiACgTq45SjRhUAXHADaT5y4EYYQg7AEoSP2d%2BNwYmVg4ubjCI5wBdCLFQ9SA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwBoQJ84AHJeASwDd9NIBXIkAd2oBMwALTAdgAcATmI981AOY8wAgEwA2AL5A) reproduction (yes, technically there is JavaScript in the HTML window, simulating the usage of .tsx files; should not matter), or my [repo](https://github.com/jozefmery/unocss-issue-repr).

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by chu121su12** [comment]
Shortest reduction I can manage to make: [playground](https://uno.antfu.me/play/?html=DwEwlgbgBA3gBgEhgVgL51VAfAKAEQAeeOokUARgOYC8eATgKYh7Y5xA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUkNikEA&options=N4XyA)
