### ISSUE TITLE
vscode extension: support lit-element

### ISSUE THREAD

**Issue by hopkinson** [unocss/unocss#2245]
### Clear and concise description of the problem

I am using a framework about Lit , but i found there is any sinppets in vscode when i use unocss. 
and i  found it's normal in tailwindCSS when i use vscode 

### Suggested solution

vscode extension will be supported Lit 

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://uno.antfu.me).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sibbng** [comment]
Can you give me more info about your working environment? Such as, your file extension, VS Code extensions etc... If you can link an example project that would be nice.

**Comment by hopkinson** [comment]
i am using the template about Lit+Vite+Typescript all the time .
i used the tailwindCSS before, it was useful for me to show css snippets in Vscode.
late when i found unocss is better then tailwindCSS ,i turned twcss into unocss , but  there is any snippets in vscode when i used unocss and vscode extension--unocss.
there is a simple example in here.
https://stackblitz.com/edit/vitejs-vite-wcwrjd?file=src/my-element.js

**Comment by sibbng** [comment]
Create a uno.config.js file in your root folder, then it should work.

https://github.com/unocss/unocss/blob/main/examples/astro/uno.config.ts

**Comment by hopkinson** [comment]
i created a  uno.config.js file , the Vscode extension also doesn't show any sinppets ..


uno.config.js
```
import { defineConfig } from '@unocss/vite'
import presetUno from '@unocss/preset-uno'
import transformerDirectives from '@unocss/transformer-directives'
import presetIcons from '@unocss/preset-icons'
const config = defineConfig({
  shortcuts: [
    { 'i-logo': 'i-logos-astro w-6em h-6em transform transition-800' }
  ],
  transformers: [transformerDirectives()],
  presets: [
    presetUno(),
    presetIcons({
      extraProperties: {
        display: 'inline-block',
        'vertical-align': 'middle'
      }
    })
  ]
})
export default defineConfig(config)
```

**Comment by sibbng** [comment]
It seems we [don't scan js files by default](https://github.com/unocss/unocss/blob/9fbb3c002212d124e892949c7cfc167509bcbc9d/packages/shared-integration/src/defaults.ts#L5). You can fix that by configuring `include` option:

```ts
export default defineConfig({
  include: [/\.(vue|svelte|[jt]sx?|mdx?|html)($|\?)/],
  presets: [
    presetUno()
  ]
})
```
