### ISSUE TITLE
vscode extensions larger than version `0.48` do not work properly

### ISSUE THREAD

**Issue by cinob** [unocss/unocss#2253]
### UnoCSS version

`>0.48`

### Describe the bug

![image](https://user-images.githubusercontent.com/30230686/221157837-54b8b89c-cba5-4296-878c-006c5e4a671a.png)
![image](https://user-images.githubusercontent.com/30230686/221158141-54bd3232-cbf5-40a9-8871-86f17dd5399c.png)

### Reproduction

https://github.com/antfu/vitesse-lite

### System Info

- Operating System: `Linux`
- Node Version:     `v16.16.0`

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by cinob** [comment]
#2156

**Comment by cinob** [comment]
#2156

**Comment by sibbng** [comment]
Can you show UnoCSS output channel on VS Code? It works for me:

![image](https://user-images.githubusercontent.com/19991745/221164319-8f8a7398-1d73-4b20-9fc6-5095a313d256.png)

**Comment by byyuurin** [comment]
I have the same problem between `v0.49.*` ~ `v0.50.0`,
Problem solved after updating to `v0.50.1`.

**Comment by cinob** [comment]
After upgrading to `0.50.1` it still doesn't work properly. @sibbng 
![image](https://user-images.githubusercontent.com/30230686/221455693-f1c7366b-d80d-4852-9ac6-68ddc1e2e437.png)

**Comment by cinob** [comment]
This is UnoCSS output channel on VS Code
![image](https://user-images.githubusercontent.com/30230686/221458025-1c257f78-53e4-407f-8f67-1caace18e0f4.png)
