### ISSUE TITLE
transformerVariantGroup not work correctly

### ISSUE THREAD

**Issue by harrytran998** [unocss/unocss#2264]
### UnoCSS version

latest

### Describe the bug

After some upgrades unocss version, the transformer variant group seems not to be working anymore. Hope you guy take a look in the playground bellow.

```html
<html class="text-gray-900 text-white text-white hover:(text-red-700 no-underline text-red)" />
```

--> Not transform to 

```html
<html class="text-gray-900 text-white text-white hover:text-red-700 hover:no-underline hover:text-red" />
```

### Reproduction

https://uno.antfu.me/play/?html=DwEwlgbgBA7gtAJgB4BsoAtGqgMxQUySgCsBXAZwBcwcBPOAY3wDtL8AnKMNgW3MZZt2APgBQUYAENxUWXKgMUk8uQC8AIjZJKcAObtJ9AJwAGE1C06Y6bvguErNthgD2EDgC4AFJbjt8IHAA7GZQzC5wpMwgHChgzHa%2B1rYAlOoy8rLo-jga6JSUAA7kHgD0pbrc6KQARgB0DC48pVEuDCot4e3k6ZlylJLsuviUGgD6NUrMANa9mcIAEvgoKC6w6Bx2g3a0LqRhLjAA-MClkmKn4BDCQA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcEWWwCGuOlmggMUAGrr2mmAHEoELmDVRN23foAiwWhN4A3epQC%2BcLJYgcADkXCoSdHTBSEgYAB6QsOjY6lwANvCYOPhEJMCkABTIqFDp9ABccADaVKhVwRJcdDAQIAC0pWkYweSIcFJp0JXBtGjBcD4AulSTsnQAFtAwjTB0lcWoIY3NrW0LSyvBwzDxMG1ppHAncWfQmqQYcIteUOXXZyfqadGoPrIiCjW1VqclEShUBQAlLJhPJGCw2JweHx%2BFCYaCFJJpEUQag6BIvhhKgBGAB0ACZ0agJGhcMN5qwwGsAPTM%2BggUkLZk-TY%2BaEzWz2HRQPSvYGbK52LTC0VGEy4cyWaxokEaaWOKAuNyeegq1DTPlIIA&options=N4IgTgpgzgDg9gOygSwG4RALgGYEMA2UEAvkA

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sibbng** [comment]
Are you facing this issue on your project or just Playground? I see some inconsistencies on Playground but on an actual app, it seems working.

**Comment by harrytran998** [comment]
Sure from my real project. Then I go to the playground to check my config is correct. I use Unocss in my Nextjs company project. Before, this worked well but now, I don't know why but not work anymore --> Break our app style 🥲

**Comment by sibbng** [comment]
Could you provide a minimal reproduction repository? And which version was working properly? Thanks.

**Comment by harrytran998** [comment]
Thank you for your quick response <3.
I double check on my project --> The problem is condition grouping rendering 😆.
I use combine like this --> `before:(text-red ${isTrue ? 'bg-white' : 'bg-yellow'})` --> Doesn work!

I switch to `before:(text-red) ${isTrue ? 'before:(bg-white)' : 'before:(bg-yellow)'})` --> This worked.

I think your team might be adding this to the document 🤔

**Comment by sibbng** [comment]
You're welcome. 

Not specifically mentions variant groups but it's already covered in readme: https://github.com/unocss/unocss#scanning
