### ISSUE TITLE
Request for documentation

### ISSUE THREAD

**Issue by J4gQBqqR** [unocss/unocss#2274]
### Clear and concise description of the problem

There is a current lack of documentation for newcomers who has never used other similar utilities like tailwind, windi, etc.

The amount of documentation is very limited, just some Readme file telling user how to install/config in general and a Interactive site to find style.

Newcomers with 0 knowledge on how such library works are not welcomed with basic information such as the library's syntax, grammar, how it works and how to debug etc.

### Suggested solution

Prepare a well written documentation to users who have only knowledge about CSS.
Do not assume that the user had used other similar solution before coming to this library.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://uno.antfu.me).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by zyyv** [comment]
Focus on #2236 #2191 discussions
