### ISSUE TITLE
Webpack@5 minimal setup not working 

### ISSUE THREAD

**Issue by KeyToLove** [unocss/unocss#2277]
### UnoCSS version

0.50.1

### Describe the bug

`unocss` not working on `webpack@5 ` project.

### Reproduction

https://codesandbox.io/p/github/KeyToLove/webpack-unocss-test/draft/magical-lamport?file=%2Fsrc%2Findex.less&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A5%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A5%7D%5D

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by KeyToLove** [comment]
Any solutions there?

**Comment by dove-xk** [comment]
need to use `mini-css-extract-plugin`
