### ISSUE TITLE
vscode extensions larger than version `0.48` do not work properly

### ISSUE THREAD

**Issue by cinob** [unocss/unocss#2282]
### UnoCSS version

0.49

### Describe the bug

Please don't close this issue after resolving it. This is the third time I've created it. #2156 #2253

I located the error in the vscode output and printed out some debug output. 
![image](https://user-images.githubusercontent.com/30230686/222061158-6df40ac1-5b2d-47a5-81e7-80d33ddebde9.png)

Here's a comparison between 0.48 and later versions
![image](https://user-images.githubusercontent.com/30230686/222061288-4cd6a5db-eeb0-467f-9d22-d4d6f31593df.png)
![image](https://user-images.githubusercontent.com/30230686/222061372-bd426004-a0fb-4eba-9431-ee593d3a6062.png)

### Reproduction

All Projects
For example: https://github.com/antfu/vitesse-lite

### System Info

wsl

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sibbng** [comment]
Can you find the following lines and replace `e3` with `e3.stack`? This will tell where the actual error occurs.

```ts
log.appendLine("\u26A0\uFE0F Error on annotation");
log.appendLine(String(e3));
```

**Comment by cinob** [comment]
> Can you find the following lines and replace `e3` with `e3.stack`? This will tell where the actual error occurs.
> 
> ```ts
> log.appendLine("\u26A0\uFE0F Error on annotation");
> log.appendLine(String(e3));
> ```

![image](https://user-images.githubusercontent.com/30230686/222090144-c09550ba-df0f-4275-84b8-183bc3e56e8f.png)

**Comment by sibbng** [comment]
Your VS Code extension version is out of date. After downgrading my extension to `0.45.21` I was able to reproduce the issue. Please upgrade your VS Code extension to the latest version.

**Comment by cinob** [comment]
> 您的 VS Code 扩展版本已过期。将我的扩展降级到之后，`0.45.21`我能够重现该问题。请将您的 VS Code 扩展升级到最新版本。

Thank you so much.

**Comment by cinob** [comment]
Need to upgrade vscode to the latest version (you may need to download the update manually like I did)
Otherwise unocss extension can not install the latest version only stuck in `0.45.21`
