### ISSUE TITLE
Border (and maybe other) styles not working when vite builds in library mode

### ISSUE THREAD

**Issue by HiggsWRX** [unocss/unocss#2285]
### UnoCSS version

0.50.2

### Describe the bug

I'm building a standalone component library for my company, and in it I'm using unocss of course.
After building and packing, and importing it as a standalone package in another repository, everything works kind of like expected but some properties refuse to work. I can see they are correctly exported in the css file but they're just not being applied for some reason.

In this specific case, the border property is the one being ignored. Everything else styles correctly, font-sans, margins, etc...

I have tried this in a brand new project without anything else installed, so no other unocss or styling packages that could conflict.

### Reproduction

Not sure how to reproduce in playground since this involves building the project in library mode and then importing it from another as a package

### System Info

MacOS, tested on every browser, React 18

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sherif414** [comment]
I remember not having to explicitly set border-solid few months ago but now it's required.
Maybe it was changed in recent versions?

**Comment by sibbng** [comment]
Yes it is removed in #1971.

If you don't want to add b-solid on every rule you have, maybe this code would help:

[Playground](https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIBGBaATgUxChwEZjjsSAHADwpGQAtCoqBPbAVigFtMAWdAD5gAenAQhAKFCRYiFBhyY4AV3wUATOVKbarDtz6CR4yNKA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVABu9uz2uDB0AFxwANpUqP6oiSD2MBIAFj54YDwAlIhxiahSuHTwyalpcAC8cFk8AHTl6T4A9AB6PgD8ERzQmFAAPhw5PiPdALQ%2B9QDUOTmdACQtOQWFfHA%2BTWl5CYWFtDBcULj5e2dwWxhQUXUwsueJaaFoThhRmbjZd3D4ljB5VQAfKcHnt1h8vvUMGF2PRogAGAC6nXqCMR1SqNT0vSg-XGAHdgGgYGk9DtVqDUAcjidfjA-BTKah6izbvcmYVoWxgPQotEWfVblCYTyZDFsX0ruNSvxXnpyPo6BAnES9IjEeyOWoVhzUBoME4GCDdXBqccflZ6bcdbq1Iy9mpNQ77Xazo6Cu7UBqqCIFJEYgVfYxlBBRuyg8xWOxuLwBGGqIikNqkEA&css=Q&options=N4XyA)
```ts
export default defineConfig({
  variants: [
    {
      match(input) {
        const match = input.match(/^(?:border|b)()(?:-(.+))?$/)
        if (match) {
          return {
            matcher: input,
            handle: (input, next) => {
              if (input.entries[0]?.[0] === 'border-width') {
                return next({
                  ...input,
                  entries: [...input.entries, ['border-style', 'solid']],
                })
              }
            },
          }
        }
      },
    },
  ],
  presets: [
    presetUno(),
    presetAttributify(),
  ]
})
```

I'm not sure if this has some edge cases or not. @chu121su12 is better at this stuff than me.

Let me know if you encounter any issues.
