### ISSUE TITLE
Re-toggle SVG animated icons

### ISSUE THREAD

**Issue by J4gQBqqR** [unocss/unocss#2295]
### Clear and concise description of the problem

There is currently no good way to toggle animated SVG icons like this one: https://icon-sets.iconify.design/line-md/

The animation will only be played once and will not replay.

### Suggested solution

Introduce an intuitive `hover:` `click:` way to re-trigger/rerun/re-toggle SVG animation from beginning.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://uno.antfu.me).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by J4gQBqqR** [comment]
Not stale

**Comment by antfu** [comment]
I kind of feel it's how the SVG animation work. I don't think there is a way for us to solve this on our side (there is no API for it AFAIK). Marked as out-of-scope unless someone comes up with a solution. Thanks.

**Comment by Bernankez** [comment]
I also encountered this issue. I think it may be related to https://stackoverflow.com/questions/19177571/restart-background-svg-animation.  However, I have not yet found a solution. Re-mounting the components does not work for me.
