### ISSUE TITLE
width and height at same time like wh-32px

### ISSUE THREAD

**Issue by joseehilton147** [unocss/unocss#2299]
### Clear and concise description of the problem

Its possible to use a alias to generate height and width wich is the same px, like w-32px h-32px being wh-32px

### Suggested solution

make a unified thing like wh-[value]

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://uno.antfu.me).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by killjoy1221** [comment]
I use this shortcut to do what you want.
```ts
// unocss.config.ts
export default defineConfig({
  shortcuts: [
    [/square-(\d+)/, ([, c]) => `w-${c} h-${c}`],
  }
})

**Comment by impcyber** [comment]
@killjoy1221 
In your example you can only use `em` values, otherwise by using `\w` instead of `\d` you can use values like `10px`.

**Comment by zyyv** [comment]
Updated.
```ts
shortcuts: [[/^wh-(.+)$/, ([, d]) => `w-${d} h-${d}`]],
```
