### ISSUE TITLE
Request for a new feature - support Icon Selector

### ISSUE THREAD

**Issue by SKT1yang** [unocss/unocss#2313]
### Clear and concise description of the problem

Hello,

I would like to request a new feature to be added to Uno.css, which is an icon selector.

Currently, there are a lot of icons available in Uno.css, but it can be hard to find the right one when working on a project. An icon selector would allow users to easily search and select the desired icon without having to go through the entire list.
I hope there is a way to get a list of all icon classes

I believe this would greatly improve the user experience for those working with icons in Uno.css.

Thank you for considering my request.

Best regards,

### Suggested solution

There is a method to get the string list of existing icons, which is convenient for us to inject into the client environment code

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [ ] Already used the [Interactive Docs](https://uno.antfu.me).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Aren't https://icones.js.org/ and https://github.com/antfu/vscode-iconify not enough?

**Comment by SKT1yang** [comment]
This selector is for website users rather than website developers. Users can choose different icons to decorate the website, similar to modifying menu navigation icons, etc., and found two difficulties:
1. Unable to dynamically obtain a complete list of icon names
2. Even if it is obtained, I don’t know if the value does not support such a dynamic display

**Comment by SKT1yang** [comment]
> This selector is for website users rather than website developers. Users can choose different icons to decorate the website, similar to modifying menu navigation icons, etc., and found two difficulties:
> 
> 1. Unable to dynamically obtain a complete list of icon names
> 2. Even if it is obtained, I don’t know if the value does not support such a dynamic display

**Comment by SKT1yang** [comment]
> Aren't https://icones.js.org/ and https://github.com/antfu/vscode-iconify not enough?

This selector is for website users rather than website developers. Users can choose different icons to decorate the website, similar to modifying menu navigation icons, etc., and found two difficulties:

Unable to dynamically obtain a complete list of icon names
Even if it is obtained, I don’t know if the value does not support such a dynamic display
