### ISSUE TITLE
Code tips for astro project

### ISSUE THREAD

**Issue by blkcor** [unocss/unocss#2314]
### Clear and concise description of the problem

There are code tips with vue / nuxt project with vscode-unocss-plugin, but recently I want to code a blog with astro as well as use unocss in my project, after full configuration with unocss, I can't get code tips however.

### Suggested solution

How can I get tips outside vue / nuxt project?

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [ ] Already used the [Interactive Docs](https://uno.antfu.me).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sibbng** [comment]
Try moving your config to a separate file:

https://github.com/unocss/unocss/blob/main/examples/astro/uno.config.ts

**Comment by blkcor** [comment]
I do like you say originally. But it still can't work.
Accidentally when I close the astro vscode plugin and reopen it , there are some tips for me.
