### ISSUE TITLE
Problem with `:class` in Vue

### ISSUE THREAD

**Issue by sibbng** [unocss/unocss#2320]
### Discussed in https://github.com/unocss/unocss/discussions/2315

<div type='discussions-op-text'>

<sup>Originally posted by **amir20** March  6, 2023</sup>
I am wondering if anybody else has ran to a similar issue. I would expect it to be a major bug if reproducible. 

I have noticed that `<aside :class="{ 'fixed': isMobile }">` works. However, when removing the quotes `<aside :class="{ fixed: isMobile }">` it does not. I am using @antfu's es-lint which removes the quotes after save. 

Note, that this is inconsistent. If I added the quotes without doing `eslint --fix` it works and after that it continues to work. On a cold boot, it does not. 

For now, I am using `<aside :class="isMobile ? 'fixed' : ''">`. 

Is this a bug? </div>

**Comment by buluterhan** [comment]
empty space  next to your class **' fixed '** should fix the issue for now.
<aside :class="{ ' fixed ': isMobile }"> 

This should be better option than
<aside :class="isMobile ? 'fixed' : ''">
