### ISSUE TITLE
Feature: add transform css to unocss 

### ISSUE THREAD

**Issue by Simon-He95** [unocss/unocss#2324]
### Clear and concise description of the problem

Because compared to the syntax of unocss, the syntax of css is more friendly to users.
I hope that if I want to write css syntax, what is the corresponding unocss.
So I hope to add an display interface to convert css to unocss.

### Suggested solution

I wrote a [library](https://github.com/Simon-He95/transformToUnocss) to convert css to unocss, maybe it can speed up the process.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://uno.antfu.me).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Nice idea! If you can make the tool more international (English by default), I am happy to link it in the readme as `Additional Tools`

**Comment by Simon-He95** [comment]
of course
I made some language updates, please let me know if you think there is anything that needs to be changed.
https://to-unocss.netlify.app/

**Comment by cycle4passion** [comment]
Would be nice as VS code extension.

**Comment by Simon-He95** [comment]
> Would be nice as VS code extension.

we have [vscode extension](https://github.com/Simon-He95/tounocss) :)
