### ISSUE TITLE
`@unocss/astro` doesn't work with `client:only` components

### ISSUE THREAD

**Issue by kidonng** [unocss/unocss#2325]
### UnoCSS version

0.50.4

### Describe the bug

Astro has a [`client:only`](https://docs.astro.build/en/reference/directives-reference/#clientonly) directive that skips server rendering of components. Currently this directive makes UnoCSS's Astro integration unaware of the component and skips generating styles for it.

[It is mentioned](https://github.com/withastro/astro/issues/5468#issuecomment-1328780235) changing `page-ssr` to `page` here works:

https://github.com/unocss/unocss/blob/87b414a3718a92f6000092d1f8cfee8e833b18b9/packages/astro/src/index.ts#L66

This does generate correct CSS, however the CSS file is not imported in the generated HTML, so the fix is not that simple.

### Reproduction

https://stackblitz.com/edit/node-6xfq8u

Notice how in the generated CSS, `.text-blue` in Astro component is present, but `.text-red` in Svelte component with `client:only` is missing.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sibbng** [comment]
It will work if you nest your components under `components` folder.

Alternatively, you can provide additional files in `extraContent` option:

```ts
extraContent: {
  filesystem: ['src/component.svelte']
},
```

**Comment by kidonng** [comment]
I did notice this:

https://github.com/unocss/unocss/blob/87b414a3718a92f6000092d1f8cfee8e833b18b9/packages/astro/src/index.ts#L46

However I never thought it would be the culprit. Just opened a #2326 for this.
