### ISSUE TITLE
最新版本 b-1px必填b-solid 

### ISSUE THREAD

**Issue by jackZmym** [unocss/unocss#2330]
### UnoCSS version

0.50.1

### Describe the bug

0.45版本直接n-1px b-#000  0.5版本必须b-solid，建议默属性

### Reproduction

0.45版本直接n-1px b-#000  0.5版本必须b-solid，建议默属性

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
May this comment https://github.com/unocss/unocss/issues/2285#issuecomment-1452311355 can help you.

**Comment by jackZmym** [comment]
> 愿这条评论[#2285（评论）](https://github.com/unocss/unocss/issues/2285#issuecomment-1452311355)能帮到你。
> 
> 如果您已经使用重置样式，请不要担心
> 
> https://github.com/unocss/unocss/blob/7eab6e283a1e3ea390acd069761fd136552d6961/packages/reset/tailwind.css#L6-L13

谢谢
