### ISSUE TITLE
nuxt3缺少vite,webpack依赖，有影响么？

### ISSUE THREAD

**Issue by Rain-Hsiang** [unocss/unocss#2333]
### UnoCSS version

"@unocss/nuxt": "^0.50.4",

### Describe the bug

nuxt3安装@unocss/nuxt 提示缺少依赖。
![762b78716966157cf2fbb53d8fc34b75](https://user-images.githubusercontent.com/125465912/223648354-5a4d248f-09dd-47bb-8d2a-683116d400a7.png)
当前正常运行，未出现运行错误！
不知道是否有影响！

### Reproduction

[https://gitee.com/rain-f2e/nuxt3-template](https://gitee.com/rain-f2e/nuxt3-template)

### System Info

macOs Ventura: 13.2.1
chrome: 版本 110.0.5481.177（正式版本） (arm64)
nuxt3: ^3.2.3

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
It's how it is, it doesn't affect anything. If you prefer, you can have following content in your `.npmrc`

```rc
strict-peer-dependencies=false
```

or 

```rc
auto-install-peers=true
```

**Comment by Rain-Hsiang** [comment]
> It's how it is, it doesn't affect anything. If you prefer, you can have following content in your `.npmrc`
> 
> ```
> strict-peer-dependencies=false
> ```
> 
> or
> 
> ```
> auto-install-peers=true
> ```

感谢，理解了。
