### ISSUE TITLE
get error in tauri 

### ISSUE THREAD

**Issue by PengBoUESTC** [unocss/unocss#2335]
### UnoCSS version

0.50.4

### Describe the bug

when I add unocss to a tauri project, get an error like this 

<img width="453" alt="截屏2023-03-08 下午8 10 30" src="https://user-images.githubusercontent.com/57180744/223709952-6225305b-ae4f-40f8-8697-12d8de8e3ca5.png">

but i'm not sure about that this is a problem of unocss

### Reproduction

https://github.com/PengBoUESTC/fe-weki-app

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wkeylin** [comment]
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/21221921/224613821-bfe09112-6c90-4684-8854-11716e31b5e2.png">

I ran the demo on a mac without any errors
