### ISSUE TITLE
Deeper color palette

### ISSUE THREAD

**Issue by toniengelhardt** [unocss/unocss#2339]
### Clear and concise description of the problem

A lot of times I find myself out of options when trying to find the perfect color for UI elements, especially in the grayscale, zinc-100 is too light, zinc-200 is too dark, etc.

Too often I have to compromise on contrast, bc the steps are too large, e.g. light text on a panel.

I know I can define a custom palette, but I think it would be amazing if this would come out of the box and it seems it should not be a huge feat to make it happen.

I'm not sure if I'm alone with this, that's why I'm putting it out here to see if other devs would also appreciate it.

### Suggested solution

It would be amazing if the standard color palette would feature colors in steps of 50, aka. zinc-50, zinc-100, zinc-150, ..., zinc-950.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [x] Already used the [Interactive Docs](https://uno.antfu.me).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
I think having separate presets for extended colors would be better

**Comment by toniengelhardt** [comment]
Makes sense, `preset-deep-palette` maybe, closing...
