### ISSUE TITLE
theme does not support setting BackgroundSize

### ISSUE THREAD

**Issue by qxdmmc** [unocss/unocss#2343]
### UnoCSS version

0.50.4

### Describe the bug

hello！why unocss does not support setting BackgroundSize in theme？
I found it in windicss documentation. but unocss does not work. Is there any way to customize BackgroundSize?
looking forward to your reply~
![image](https://user-images.githubusercontent.com/30492972/223979984-c3741786-3c18-4f91-9fe3-54f4620b64e8.png)

### Reproduction

```text
export default {
  theme: {
    backgroundSize: {
      'auto': 'auto',
      'cover': 'cover',
      'contain': 'contain',
      '50%': '50%',
      '16': '4rem',
    },
  },
}

### System Info

_No response_

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
Try to use `bg-[length:xxx]`, like `bg-[length:50%_50%]` `bg-[length:50%_10rem]`
Or you can write rules or shortcuts what you want.
