### ISSUE TITLE
cache loader not found

### ISSUE THREAD

**Issue by jianxing-xu** [unocss/unocss#2347]
### UnoCSS version

0.50.4

### Describe the bug

vue-cli4.x 启动构建报错 
This dependency was not found:

* -!../node_modules/cache-loader/dist/cjs.js??ref--12-0!../node_modules/babel-loader/lib/index.js!../node_modules/vue-loader/lib/index.js??vue-loader-options!../node_modules/unplugin/dist/webpack/loaders/transform.js??unocss:webpack!./App.vue?vue&type=script&lang=js& in ./src/App.vue?vue&type=script&lang=js&

To install it, you can run: npm install --save -!../node_modules/cache-loader/dist/cjs.js??ref--12-0!../node_modules/babel-loader/lib/index.js!../node_modules/vue-loader/lib/index.js??vue-loader-options!../node_modules/unplugin/dist/webpack/loaders/transform.js??unocss:webpack!./App.vue?vue&type=script&lang=js&

### Reproduction

https://github.com/jianxing-xu/unocss-vuecli-issue

### System Info

'use strict'
const UnoCSS = require('@unocss/webpack').default
const path = require('path')
const defaultSettings = require('./src/settings.js')

function resolve(dir) {
  return path.join(__dirname, dir)
}

const name = defaultSettings.title || 'vue Admin Template' // page title

const port = process.env.port || process.env.npm_config_port || 8082

// All configuration item explanations can be find in https://cli.vuejs.org/config/
module.exports = {
  /**
   * You will need to set publicPath if you plan to deploy your site under a sub path,
   * for example GitHub Pages. If you plan to deploy your site to https://foo.github.io/bar/,
   * then publicPath should be set to "/bar/".
   * In most cases please use '/' !!!
   * Detail: https://cli.vuejs.org/config/#publicpath
   */
  publicPath: '/',
  outputDir: 'dist',
  assetsDir: 'static',
  lintOnSave: process.env.NODE_ENV === 'development',
  productionSourceMap: false,
  devServer: {
    host: 'localhost',
    port: port,
    // https: true,
    proxy: {
      '/api/v1': {
        // target: 'http://localhost:8200',
        target: 'https://dreamma.vip/api/admin',
        changeOrigin: true,
        pathRewrite: {
          '^/api/v1': '/v1'
        }
      }
    }
  },
  configureWebpack: {
    // provide the app's title in webpack's name field, so that
    // it can b e accessed in index.html to inject the correct title.
    name: name,
    resolve: {
      alias: {
        '@': resolve('src')
      }
    },
    plugins: [
      UnoCSS({}),
    ],
  },
  chainWebpack(config) {
    // it can improve the speed of the first screen, it is recommended to turn on preload
    config.plugin('preload').tap(() => [
      {
        rel: 'preload',
        // to ignore runtime.js
        // https://github.com/vuejs/vue-cli/blob/dev/packages/@vue/cli-service/lib/config/app.js#L171
        fileBlacklist: [/\.map$/, /hot-update\.js$/, /runtime\..*\.js$/],
        include: 'initial'
      }
    ])

    // when there are many pages, it will cause too many meaningless requests
    config.plugins.delete('prefetch')

    // set svg-sprite-loader
    config.module
      .rule('svg')
      .exclude.add(resolve('src/icons'))
      .end()
    config.module
      .rule('icons')
      .test(/\.svg$/)
      .include.add(resolve('src/icons'))
      .end()
      .use('svg-sprite-loader')
      .loader('svg-sprite-loader')
      .options({
        symbolId: 'icon-[name]'
      })
      .end()

    config
      .when(process.env.NODE_ENV !== 'development',
        config => {
          config
            .plugin('ScriptExtHtmlWebpackPlugin')
            .after('html')
            .use('script-ext-html-webpack-plugin', [{
            // `runtime` must same as runtimeChunk name. default is `runtime`
              inline: /runtime\..*\.js$/
            }])
            .end()
          config
            .optimization.splitChunks({
              chunks: 'all',
              cacheGroups: {
                libs: {
                  name: 'chunk-libs',
                  test: /[\\/]node_modules[\\/]/,
                  priority: 10,
                  chunks: 'initial' // only package third parties that are initially dependent
                },
                elementUI: {
                  name: 'chunk-elementUI', // split elementUI into a single package
                  priority: 20, // the weight needs to be larger than libs and app or it will be packaged into libs or app
                  test: /[\\/]node_modules[\\/]_?element-ui(.*)/ // in order to adapt to cnpm
                },
                commons: {
                  name: 'chunk-commons',
                  test: resolve('src/components'), // can customize your rules
                  minChunks: 3, //  minimum common number
                  priority: 5,
                  reuseExistingChunk: true
                }
              }
            })
          // https:// webpack.js.org/configuration/optimization/#optimizationruntimechunk
          config.optimization.runtimeChunk('single')
        }
      )
    config.module.rule('vue').uses.delete('cache-loader')
    config.module.rule('tsx').uses.delete('cache-loader')
    config.merge({
      cache: false,
    })
  },
  css: {
    extract: {
      filename: '[name].[hash:9].css'
    }
  }
}

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zhoushengdong** [comment]
#### 同模板同问题，刚解决，附上方法

1. 安装unocss @unocss/postcss
2. vue.config.js中css.loaderOptions.postcss配置@unocss/postcss
3. 新建uno.config.js，重启项目即可

```javascript
> vue.config.js

{
    css: {
    sourceMap: !isProduction,
        loaderOptions: {
            sass: {},
            postcss: {
                plugins: [
                    require('@unocss/postcss')({
                        content: ['**/*.{html,js,ts,jsx,tsx,vue,svelte,astro}']
                    })
                ]
            }
        }
    }
}


> uno.config.js

import { defineConfig, presetUno } from 'unocss'

export default defineConfig({
    presets: [
        presetUno()
    ]
})
```

**Comment by zhoushengdong** [comment]
> @zhoushengdong 非常感谢您的回复！刚刚试了一下，好像还是不行，一样的错误，依赖也已经重新装过了。尝试的代码已经提交到复现仓库了。

1. 把你的@unocss/webpack去掉
2. npm update svg-sprite-loader@6

**Comment by mdxiaohu** [comment]
@zhoushengdong Useful, there is a new question. Can I use a class name for '@unocss/postcss'
`For example, this <div class="text-red inline-flex">test</div>`

**Comment by zhoushengdong** [comment]
> @zhoushengdong Useful, there is a new question. Can I use a class name for '@unocss/postcss' . For example, this . `<div class="text-red inline-flex">test</div>`

of course.you can read the [https://unocss.dev/integrations/postcss](documentation)
