### ISSUE TITLE
VSCode Color preview when using css variables for the color

### ISSUE THREAD

**Issue by eweren** [unocss/unocss#2358]
### UnoCSS version

0.50.4

### Describe the bug

When relying on CSS variables for the colors, they do not get resolved correctly and will be displayed as black.
![image](https://user-images.githubusercontent.com/25116822/225569219-5b52050f-82ab-4169-8bb7-c27b89ec06f9.png)

### Reproduction

1. Define the CSS variable `--un-color-primary` with an example color like `red/rgba(...)/#...` as preflight
2. Use a rule like this
 ```[/^bg-primary$/, () => {
  return ({ "background-color": `var(--un-color-primary, rgba(255, 255, 255, 1)`})
}],```
3. Add the class `bg-primary` somewhere in your HTML -> black color preview instead of the defined color in vs code

### System Info

_No response_

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zam157** [comment]
I use regex to simply resolve color values and css vars, this can't handle all the situations

Maybe css ast is needed🤔

**Comment by zam157** [comment]
And I don't know if there is a way to get custom css vars

**Comment by Loongphy** [comment]
Same here. I use the component library global variables like `color-[rgb(var(--danger-6))]`.

**Comment by antfu** [comment]
CSS vars are browser runtime, that we can't decide statically in the extension. Even if we do, it could be inaccurate and potentially confusing. I'd consider this is a hard limit that is not possible to support.

**Comment by ivancuric** [comment]
@antfu is it possible to take the swatch out of the color code comment like the tailwind extension does?

https://github.com/tailwindlabs/tailwindcss-intellisense/issues/809#issuecomment-2221559773
