### ISSUE TITLE
TypeError: First parameter has member 'readable' that is not a ReadableStream.

### ISSUE THREAD

**Issue by qiuqfang** [unocss/unocss#2363]
### UnoCSS version

0.50.6

### Describe the bug

When presetUno() was used in astro2.1.3, this issue occurred and required node18.x to be used to resolve it

### Reproduction

https://github.com/qiuqfang/demo-astro-unocss

### System Info

```
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 196.02 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
Browsers:
    Chrome: 111.0.5563.64
    Safari: 16.3
```

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Adrian-Samuel** [comment]
Facing this exact issue
