### ISSUE TITLE
Extension: high CPU usage

### ISSUE THREAD

**Issue by henrikvilhelmberglund** [unocss/unocss#2370]
### UnoCSS version

0.50.6

### Describe the bug

I find the extension has high CPU usage. Profiled here it was at 8k ms which seems pretty high because the heaviest addon I use normally has about 1.5k. I'm guessing it is a bug at least. I have only used UnoCSS in Svelte-scoped so I have only seen high CPU usage there but it is possible it happens in other modes too.

![Code_18_13-22-141O6GFXIbnn](https://user-images.githubusercontent.com/110549389/226106095-c4260fa4-412e-414e-9306-1bc58d5db16c.png)

Here I just recorded an extension host profile from scrolling in a file and changing a few `md` to `lg` and back.

The repro was done in a new VSCode profile with just the UnoCSS and Svelte for VS Code extensions enabled, all other settings are default (profile was started as an empty profile).

I made the file a bit longer by just copy pasting the markup a bit to make the performance impact more noticable.

If any other information is needed please let me know.

### Reproduction

Minimal repro: https://github.com/henrikvilhelmberglund/sveltekit-scoped (uses npm, sorry)

1. Create a new VSCode profile using "from empty".
2. Install UnoCSS extension.
3. Open command palette, type "running extensions".
4. In Running extensions, click Start Extension Host Profile.
5. Open +page.svelte and just scroll from top to bottom.
6. In Running extensions, click Stop Extension Host Profile.
Result: extension shows high ms.
Expected: extension shows lower ms.

cpuprofile link: https://github.com/henrikvilhelmberglund/sveltekit-scoped/blob/main/CPU-20230318T122602.679Z.cpuprofile.txt

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jacob-8** [comment]
Note to self: circle back to this after #2552

**Comment by jacob-8** [comment]
@henrikvilhelmberglund can you please profile the extension with a few different frameworks (pull from the examples folder) so we can understand if this is an issue with a particular package or if it's just the extension in general? Also maybe trim down each example's usage of classes to a similar size before testing, as they vary.

**Comment by henrikvilhelmberglund** [comment]
> @henrikvilhelmberglund can you please profile the extension with a few different frameworks (pull from the examples folder) so we can understand if this is an issue with a particular package or if it's just the extension in general? Also maybe trim down each example's usage of classes to a similar size before testing, as they vary.

Sure but it will take some time, also I don't really know how to debug extensions so it will only be a list of "a took x ms, b took y ms" and so on.

**Comment by jacob-8** [comment]
> I don't really know how to debug extensions

Don't worry about that part. Your profiling will get the ball rolling so we can determine if this is an general extension problem or a svelte-scoped problem.

**Comment by henrikvilhelmberglund** [comment]
I tested this a bit and it seems more like a general extension issue.

I tested with astro, sveltekit-scoped and vite-vue3.

For each example I opened the folder, made a new file from the default file and copy and pasted until it was at least 100 lines long. Then I started recording the extension host profile (from Running extensions) and opened the file and put the cursor near the top (after the template/script stuff) and pressed enter for about 15 seconds.

All examples showed quite high numbers (2k-5k ms) for just pressing enter. To test if it really was connected to file length I made a second .vue file that was 2k lines long and repeated the process, it was quite laggy and took over 20k ms in the profile. Even after the profile the processing wasn't done and I could see the color icons floating around in the file while it was calculating stuff.

Here are my cpuprofile files, you can open them in VSCode to see the numbers https://github.com/henrikvilhelmberglund/unocss/tree/extension-profiling/cpuprofile

Here are the examples https://github.com/henrikvilhelmberglund/unocss/tree/extension-profiling/examples

**Comment by jacob-8** [comment]
> I tested this a bit and it seems more like a general extension issue.

Thanks! I'll leave this for someone with more experience in the extension. If you have an itch to learn about extension authoring however, now would be a good chance. https://code.visualstudio.com/api/get-started/your-first-extension

Take the extension and keep cutting it in half until you can isolate the cause of the lag.

**Comment by a-type** [comment]
I'm not sure if this is related but I've had the extension lock up entirely generating autocompletions, presumably due to the complexity of some of the other rules I've made in my codebase. That may be my fault for writing incredibly complicated rules, but it's still troubling when the extension freezes up, even preventing Prettier from formatting the file, which in turn prevents saving and TS checking... everything grinds to a halt until I reload the window.

Sometimes before freezing I'll get some output of the kinds of rules the extension was trying to suggest to me, like

```
[hover:.dark:, hover:.dark:], [hover:.light:, hover:.light:], [hover:[&_.ProseMirror_h1,h2,h3,p]:mt-0, hover:[&_.ProseMirror_h1,h2,h3,p]:mt-0], [hover:[&_.ProseMirror_h1]:font-medium, hover:[&_.ProseMirror_h1]:font-medium], [hover:[&_.ProseMirror_h1]:text-xl, hover:[&_.ProseMirror_h1]:text-xl], [hover:[&_.ProseMirror_h2]:font-medium, hover:[&_.ProseMirror_h2]:font-medium], [hover:[&_.ProseMirror_h2]:text-lg, hover:[&_.ProseMirror_h2]:text-lg], [hover:[&_.ProseMirror_h3]:text-md, hover:[&_.ProseMirror_h3]:text-md], [hover:[&[data-disabled]]:color-gray5, hover:[&[data-disabled]]:color-gray5], [hover:[&[data-disabled]]:pointer-events-none, hover:[&[data-disabled]]:pointer-events-none]
```

for the source `hover:`. Seems to be extrapolating from similar rules I have in the codebase like `[&_.ProseMirror_h1]:(...)`, etc. I'm not sure if it's the complexity of these rules causing the problem, but something's definitely up. Any open-ended variant seems to risk triggering this problem.

**Comment by henrikvilhelmberglund** [comment]
I did some more testing and found that getPrettiedCSS() and getPrettiedMarkdown() are running basically all of the time when editing files which causes the high processing load. By removing those function calls in the extension I saw a 17x (3.5k ms to 184ms) speedup when doing line breaks (not editing CSS at all). Of course losing all hover info is not great but these could possibly be fixed to only run when something is hovered.

Anyway I'm not feeling smart enough to actually solve this but I found part of the issue at least I think.

**Comment by antfu** [comment]
Maybe we could use an LRU cache to store the prettied content to avoid repetitive computing?

**Comment by henrikvilhelmberglund** [comment]
Would like this reopened if possible!

**Comment by antfu** [comment]
I don't mind keeping it open, but honestly, I don't see any doable action immediately atm (and actually I don't have such issue on my side). Would be great if someone is interested looking into and and send PRs.

**Comment by henrikvilhelmberglund** [comment]
It's probably not noticable if you've got a reasonable computer. My laptop is pretty ancient and not very reasonable so I can feel the weight of the extension.

I will have some more free time soonish to look into this, not sure if I can solve it by myself though. Doing some caching as you said could work but I think it would be even easier to only calculate the markdown when there's an active hover event and only calculate the markdown for the active line, maybe this would break some things like the color indicator and underlines though. Will see!

**Comment by henrikvilhelmberglund** [comment]
I tried to look into this but VSCode profiler seems broken in this version and I couldn't really find a good solution anyway, splitting the code into a non hover part and a hover part seemed hard.

Also doesn't seem like a problem with newer hardware anyway. I'll close it but anyone who feel that they can improve it feel free to reopen.
