### ISSUE TITLE
UnoCss does not generate pseudo rule

### ISSUE THREAD

**Issue by ThinhVu** [unocss/unocss#2371]
### UnoCSS version

0.50.6

### Describe the bug

UnoCss failed to resolve rules. For example:

Rules:
```
[ 'hide-scroll-bar', {
     '-ms-overflow-style': 'none', /* IE and Edge */ 
     'scrollbar-width': 'none'  /* Firefox */
}],
['hide-scroll-bar::-webkit-scrollbar', {display: 'none'}], /* Chrome, Safari and Opera */
```

Expected output:
`.hide-scroll-bar` and `.hide-scroll-bar::-webkit-scrollbar` should be created.

Actual:
Only `.hide-scroll-bar` was created.

### Reproduction

https://user-images.githubusercontent.com/8122962/226156230-9332dc6f-3bde-46d8-8ffe-ede1b4360606.mp4

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by sibbng** [comment]
This is not how `rules` option work. I was wondering how we could generate multiple CSS rules in a single rule definition. In Tailwind [addUtilities](https://tailwindcss.com/docs/plugins#static-utilities) and [addVariant](https://tailwindcss.com/docs/plugins#static-variants) make this super easy.

I got it working in this [Playground](https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIAWYQFMC0SMATgPZxz4BGCx6AfMAPTgT1A&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCCMMUwARgK4zDoCeZF1tAJIBjAlT6UaMAKpYIcAL5x0UCCDgByNnOFUqGgFChIsRHABuAQ2aWsMALKWYwgBaooi5avUaAAtohdKgB6fikAWhBsYGCOYAAbfQMDVAAPE3g0dEs2eMyMbDwCYgAKBAM4OChc6gAuOABtCsrG5pbNAH0XYDRwqmFVePjwlmsNEjaW8vb2jUiqcIhzd3R4iAB3PphueNQNeo05HA04YIAqOEEAUThbZDgr5CJUODPgiZmWjX7B%2BNGocLrHowFz7TRHPanC4AMWAlHQEFSr3ek0qCg%2BLQAuhjKk1Phouj1UH0BhAhiNrOEAEzjVGIOmVZDAKhgeKWbgHCEnc5wXAubyoMgAZUs2WYtyw9wA8mB3JZkTiWujJtjmqrKlQXNBnBwqPVpl9ur0fmThv8wQSjcSTeT-nBUrVCcbSbbKTSMcrKlYbHY9a12t7gLYHE5XO4ShpUuM4CVsGAOABKOAAXgAfPTPpQYGwoFgM584AA6YtxjiK9pgGhsZAQA61WqA1AsADWwBgJN%2B5vLikmCgTGPV5EktD9eJaYVosggJX7kwn9EYzHYnB4M8V85EYjKdP6ll29QAjIWqd3hMgsAcXIxK7VgsFqCBC5rgrT2n2BxM%2BwYgA&css=Q&options=N4IgzgLgTglgxhEAuaBXApgGhNAhgOzADMB7KAW2SNwBsx0BfIA). But it's super weird and verbose.

/cc @chu121su12 @antfu

**Comment by antfu** [comment]
You can return an array to provide multiple rules: [Playground](https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIAWYQFMC0SMATgPZxz4BGCx6AfMAPTgT1A&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCqWEcAvnOlBCHAOQCujAYypVuAKFCRYiOADcAhlGBysMALJyYAgBaooLNhy7cAAvwhCqAegrVaAWhDZgl3jGAAbEaNGoAHpPg0dDled0CMbDwCYgAKBFE4OChQ6gAuOABtBMTM7Jy4SwA9LWA0OyoBDnd3OwAjBQASSxI8nJiASjgAXgA%2BRFb8yhheKCxc-In%2BycnuByo7CBlddHcIAHdymABPd1RudO5GHG4CgCo4AEkAUThlZDgr5CJUOFPmgenuCqr3eqg7NalGBafY8I57M5wABiwEo6Agvle72mOWYLRRiQABgA6Eplb4Qap1BSpVIA1C1ADWwBg5UqhN%2BCkQyGAVDA7jkW3S4IA3MxMYlLOdcFpDKgyABlOTBRS3LD3ADyYF0ciRH0SAF0PmjWhr0XA9dkbDQYFR0ll8sbaAwIB19YbmO1REA&css=Q&options=N4IgzgLgTglgxhEAuaBXApgGhNAhgOzADMB7KAW2SNwBsx0BfIA)

For pesudo selector it's indeed a bit tricky but for UnoCSS take more static approach for performance. No plan to have runtime utils like addUtilities or addVariant that alter the generator's behavior.

**Comment by sibbng** [comment]
This is cool, but it has some issues:  [Playground](https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIAWB7CBTAJwC5MwQ8BaJGA7OOCgIwQPQD5gB6cCNoA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCqWEcAvnOlBCHAOQCujAYypVuAKFCRYiOADcAhlGBysMALJyYAgBaooLNhy7cAAvwhCqAegrVaAWhDZgl3jGAAbEaNGoAHpPg0dDled0CMbDwCYgAKBFE4OChQ6gAuOABtBMTM7Jy4SwA9LWA0OyoBDnd3OwAjBQASSxI8nJiASjgAXgA%2BRFb8yhheKCxc-In%2BycnuByo7CBlddHcIAHdymABPd1RudO5GHG4CgCo4AEkAUThlZDgr5CJUOFPmgenuCqr3eqg7NalGBafY8I57M5wABiwEo6Agvle72mOWYLRRiQABgA6Eplb4Qap1BSpVIA1C1ADWwBg5UqhN%2BCkQyGAVDA7jkW3S4IA3MxMYlLOdcFpDKgyABlOTBRS3LD3ADyYF0ciRH0SAF0PmjWhr0XA9dlIFQYBRzNQqDFXB52vF8gICFRCahsasiFa3O52tkdYkbDQYFR0ll8v7aAwIB19YbmN6gA&css=Q&options=N4IgzgLgTglgxhEAuaBXApgGhNAhgOzADMB7KAW2SNwBsx0BfIA)

1. It won't work as expected when we use variants.
 ```html
 <div class="hover:hide-scroll-bar"></div>
 ````
 
 2. It won't be processed by postprocess hook (rem to px etc).

In my first Playground these are not an issue.
 
> No plan to have runtime utils like addUtilities or addVariant that alter the generator's behavior.

I don't propose having these utilities on UnoCSS core, but if we can come up with a more structured format for this uses cases we can provide a high level utility in preset-mini for end-users, similar to `variantMatcher`.

**Comment by chu121su12** [comment]
Depending on the pseudo usage afterwards, for multiple matching, one workaround I could think is by [using shortcut](https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIAWB7CBTAJwC5MwQ8BaJGA7OOCgIwQPQD5gB6cCNoA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCqWEcAvnOlBCHAOQCujAYypVuAKFCRYiOADcAhlGBysMALJyYAgBaooLNhy7cAAvwhCqAegrVaAWhDZgl3jGAAbEaNGoAHpPg0dDled0CMbDwCYgAKBFE4OCotaE1XKgAuOABtBMTEPPyeLWA0OyoBDnd3OwAjBW4s7myHKjsIGV10dwgAd3KYAE93VAzGHABdHIqq93qoO17SmC0xglQp7IAyDMXUWoBrYBhyyohq%2BYmM7ORgKjB3OUG1ye4SQpZ3xImv8ggqGAUczUKgxVweACU8SKAgIVHOqAAdD0iGC3O4IXlmL8bDQYJkch9cbQGBAYhDfj9RMxMUA&css=Q&options=N4IgzgLgTglgxhEAuaBXApgGhNAhgOzADMB7KAW2SNwBsx0BfIA)
