### ISSUE TITLE
[feat] CSS line-height Property (as stand alone) 

### ISSUE THREAD

**Issue by moHaHa** [unocss/unocss#2375]
### Clear and concise description of the problem

while  I'm searching for line-height property I found line-height but with font size 
![image](https://user-images.githubusercontent.com/72744132/226390329-f20a8ddd-cf55-4c07-b7e8-b525fb8d599d.png)

### Suggested solution

So 
I **force** it with text-px for (set the old font value, keep the line-height value)

![image](https://user-images.githubusercontent.com/72744132/226391395-8ecd6289-1911-4eb8-8fbd-1726ea899207.png)

![image](https://user-images.githubusercontent.com/72744132/226390773-a961103c-2239-460f-bc50-256c138c082c.png)
![image](https://user-images.githubusercontent.com/72744132/226390897-bb0a24f7-0b5d-4490-bafd-4602d4f24bbb.png)

![image](https://user-images.githubusercontent.com/72744132/226403010-a8948a21-83bf-46f1-b6ac-6887429f173d.png)

but didn't works

### Alternative

it's better to be like  this 
```HTML
<div line-height-18px>
    some text
</div>
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://uno.antfu.me).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sibbng** [comment]
It's `leading-<size>`: https://uno.antfu.me/?s=leading-18px

Alternatively you can use arbitrary properties in class attributes: `[line-height:18px]` https://uno.antfu.me/?s=[line-height:18px]

You can also specify line-height alongside font-size utilities:
- In attributify: `<div text-lg:18px>`
- In class attribute: `text-lg/18px` or `text-lg:18px`

In my opinion, we should also have `line-height-` as an alias to `leading-` utilitiy. @antfu What do you think of that?

**Comment by moHaHa** [comment]
>[https://uno.antfu.me/?s=leading-18px](https://uno.antfu.me/?s=leading-18px) 

I didn't know it 😁,  thanks `@sibbng`

**but** I noticed something  

why this result didn't appear when I search for the first time ?! 

### after this link `https://uno.antfu.me/?s=leading-18px` clicked in my browser
![image](https://user-images.githubusercontent.com/72744132/226442765-33370d57-79dd-408b-a69b-bef6e5c006d8.png)



### new search in gust browser 

![image](https://user-images.githubusercontent.com/72744132/226442296-d9b70536-53f3-4398-bdfb-e70ee7b1bae5.png)


I know that visited pages or queries typed before can affect the result but ... isn't the most important result for "line height" to show its CSS property?  

so is it normal ?!

**Comment by sibbng** [comment]
Yeah, you are right. We still need some improvements on interactive docs.

**Comment by Simon-He95** [comment]
> 

I think [this vscode extension](https://github.com/Simon-He95/tounocss) can help you easier use unocss

**Comment by moHaHa** [comment]
> @moHaHa
> 
> I think [this vscode extension](https://github.com/Simon-He95/tounocss) can help you easier use unocss

it's useful , thanks 
I'll give you star for it  🌠

**Comment by Simon-He95** [comment]
> > @moHaHa
> > I think [this vscode extension](https://github.com/Simon-He95/tounocss) can help you easier use unocss
> 
> it's useful , thanks I'll give you star for it 🌠 @Simon-He95

My pleasure :)

**Comment by userquin** [comment]
you can use [lh](https://github.com/unocss/unocss/blob/main/packages/preset-mini/src/_rules/typography.ts#L75): https://unocss.dev/interactive/?s=lh
