### ISSUE TITLE
Can't import preflights in seperate Svelte component

### ISSUE THREAD

**Issue by ravenclaw900** [unocss/unocss#2379]
### UnoCSS version

0.50.6

### Describe the bug

I'm trying to add preflights to a `svelte-scoped` project. Since my `App.svelte` uses dark mode, I tried adding them to a different component. `vite-plugin-svelte` throws a warning (shown below), and the preflights aren't applied.
```
[vite-plugin-svelte] /src/components/StyleWrapper.svelte:2:1 No scopable elements found in template. If you're using global styles in the style tag, you should move it into an external stylesheet file and import it in JS. See https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#where-should-i-put-my-global-styles.
```

### Reproduction
https://stackblitz.com/edit/vitejs-vite-jkyxue

### System Info

Arch Linux/Fedora Kinoite, Firefox 111.0.1, Node 19.8.0

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jacob-8** [comment]
#2552 will make some adjustments in how preflights are handled. Stay tuned.
