### ISSUE TITLE
HMR not working with Svelte when custom preset files are changed

### ISSUE THREAD

**Issue by bennymi** [unocss/unocss#2384]
### UnoCSS version

0.50.6

### Describe the bug

Making changes to any UnoCSS config files / preset files (like shortcuts or rules) requires the server to be restarted for the changes to appear, so HMR doesn't seem to be working. I am using Svelte and SvelteKit.

My config files look like this. I am creating a custom preset with my own rules and shortcuts. In the `vite.config.ts` file I am pointing to the UnoCSS config file.

`unocss.config.ts`
```javascript
import {
  defineConfig,
  presetAttributify,
  presetUno
} from 'unocss';

import { extractorSvelte } from '@unocss/core';

import { presetCustom } from './src/preset/index';

export default defineConfig({
  extractors: [extractorSvelte],
  presets: [
    presetUno(),
    presetAttributify(),
    presetCustom()
  ]
})
```
`vite.config.ts`
```javascript
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';
import UnoCSS from 'unocss/vite';

export default defineConfig({
	plugins: [
		sveltekit(),
		UnoCSS('./unocss.config.ts'),
	]
});
```

### Reproduction

-

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by bennymi** [comment]
Slight update: HMR works when I put all the configurations in `vite.config.ts` but not when I just point to the UnoCSS config like so: `UnoCSS('./unocss.config.ts')`

**Comment by jacob-8** [comment]
@bennymi I haven't done anything on basic Svelte + UnoCSS Vite plugin usage and I have a lot of things I'd like to do with `svelte-scoped` first but if no one else solves your problem, I'll come back to this. Consider adding a Stackblitz repro in the meantime.

**Comment by bennymi** [comment]
@jacob-8 sorry for the late reply, for some reason I didn't see the notification. I created a Stackblitz so you can have a look at it:

https://stackblitz.com/edit/sveltejs-kit-template-default-vpnz8h?file=src/routes/+page.svelte

Essentially this is the setup.
- A custom preset is created in `unocss-custom-preset.js` which is then added to the `unocss.config.js` file
- I added some simple shortcuts to the custom preset
- When the server is running and you add a new shortcut and then add it as a class (in the `/src/routes/+page.svelte` for example, you don't see the styles being added
- The styles only get added once you restart the server, so HMR is not working

You can try it out by just adding a new shortcut and then adding it somewhere.

**Comment by jacob-8** [comment]
Same solution as in #2613 - as to your repro, just update the `vite.config.js` file:

```js
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';

import UnoCSS from 'unocss/vite';

export default defineConfig({
	plugins: [
		sveltekit(),
		UnoCSS({
			configFile: './unocss.config.js',
			configDeps: ['./unocss-custom-preset.js']
		})
	]
});
```
