### ISSUE TITLE
v0.41.2 The plug-in after the version loses the code suspension prompt under windows, but it is normal on macOS

### ISSUE THREAD

**Issue by mengxuezhixing** [unocss/unocss#2385]
### UnoCSS version

v0.41.2

### Describe the bug

Using the latest version of the unocss plugin in vscode does not take effect, manually execute Unocss:reload unocss and report an error

### Reproduction

https://marketplace.visualstudio.com/items?itemName=antfu.unocss
![image](https://user-images.githubusercontent.com/82667361/226911058-e5532e02-5530-4f9e-8ac7-e0658b9fe560.png)

### System Info

windows：vscode
macOS: vscode

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wkeylin** [comment]
I reproduced the error once and it never happened again
<img width="768" alt="1b7a5240c32b9813a26015fc7d1c951" src="https://user-images.githubusercontent.com/21221921/228279120-fb3b66af-9ca4-44c5-8ae9-58b9d01c9f27.png">

**Comment by wkeylin** [comment]
![image](https://user-images.githubusercontent.com/21221921/228281333-3b639d7e-5dc7-4060-bc25-57e8d6780723.png)
You can open here to see the cause of the error

**Comment by mengxuezhixing** [comment]
> ![图像](https://user-images.githubusercontent.com/21221921/228281333-3b639d7e-5dc7-4060-bc25-57e8d6780723.png) 可以打开这里查看错误原因

Thanks for the reply, maybe my configuration is wrong, I will try again tomorrow

**Comment by mengxuezhixing** [comment]
Sorry, I re-downloaded a vue3+ts+unocss git project template, and it worked after I tried it. It should be a configuration problem of my own project.
