### ISSUE TITLE
[Bug]: `@unocss/cli`'s watch mode has no effect

### ISSUE THREAD

**Issue by 0x219** [unocss/unocss#239]
<img width="1194" alt="WX20211208-194531@2x" src="https://user-images.githubusercontent.com/50414099/145203243-2b5b97fb-deac-452f-8ca6-f4cbbf6c554e.png">

**Comment by Adam-Collier** [comment]
This could be related to #326

**Comment by 0x219** [comment]
> This could be related to #326

yes

**Comment by antfu** [comment]
Close in favor of https://github.com/unocss/unocss/issues/326
