### ISSUE TITLE
Documentation Progress 

### ISSUE THREAD

**Issue by antfu** [unocss/unocss#2392]
- [x] Initial setup (thanks @lucpotage!)
- [x] Playground and Interactive deploy and redirects
- [ ] Complete team member profiles (@chu121su12, @sibbng, @ydcjeff, @sudongyuer, @QiroNT)
- [ ] Fulfill guides (@antfu)
- [ ] Pages marked with TODO:
- [ ] Remove descriptions of each package and link them to the docs page
- [ ] Ensure we advocate standalone config everywhere, instead of inline config (referencing to `/guide/config-file` page)
- [ ] API document for generator

Branch https://github.com/unocss/unocss/tree/docs-next
Preview https://preview.unocss.dev/

If you want to help, feel free to comment below and take the tasks you want. Thank you!

**Comment by userquin** [comment]
missing links for tools folder?

I'm adding links and link texts to features in #2394
