### ISSUE TITLE
Unknown at rule @apply

### ISSUE THREAD

**Issue by J4gQBqqR** [unocss/unocss#2401]
### UnoCSS version

0.50.3

### Describe the bug

The @apply is working, but VS Code annoys me with a ton of errors:

![图片](https://user-images.githubusercontent.com/77554817/227804848-99a35c89-e75f-4879-b0d5-47e803b0dc3d.png)

### Reproduction

vite.config.ts:
```
import { sveltekit } from "@sveltejs/kit/vite";
import { defineConfig } from "vite";

import UnoCSS from "unocss/vite";
import { presetUno, presetIcons, extractorSvelte, transformerDirectives } from "unocss";
import { presetDaisy } from "unocss-preset-daisy";

export default defineConfig({
	server: {
		host: "0.0.0.0",
	},
	plugins: [
		UnoCSS({
			transformers: [transformerDirectives()],
			extractors: [extractorSvelte],
			shortcuts: [
				{
					"svg-rule": "text-6 ma block",
				},
			],
			presets: [
				presetUno(),
				presetDaisy(),
				presetIcons({
				}),
			],
			theme: {
				// This is NOT a theme name, it must be `colors`
				colors: {},
			},
		}),
		sveltekit(),
	],
});

```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by J4gQBqqR** [comment]
Is it to get eslint and unocss extension in vscode to NOT produce error for this syntax?

**Comment by J4gQBqqR** [comment]
I got it working with https://www.npmjs.com/package/@unocss/eslint-config

**Comment by zyyv** [comment]
Or you can refer to https://github.com/unocss/unocss/blob/main/packages/transformer-directives/README.md#css-variable-style

**Comment by sibbng** [comment]
You can disable it in VS Code settings.

```json
"css.lint.unknownAtRules": "ignore",
```

**Comment by a1mersnow** [comment]
> I got it working with [npmjs.com/package/@unocss/eslint-config](https://www.npmjs.com/package/@unocss/eslint-config)

I use @unocss/eslint-config too, but there're still the warnings.
Could you please tell me how does it work?

**Comment by xiangshu233** [comment]
请问 Unknown at rule @apply 是什么导致的，我按照文档https://unocss.dev/transformers/directives来也遇到这个问题了，虽然可以通过 `less.lint.unknownAtRules` 忽略规则，但我觉得这是一个`解决办法`不是解决方案
![image](https://github.com/unocss/unocss/assets/49575330/ec9735e0-2a11-4ee4-8f7c-ad856bcbd615)

**Comment by a1mersnow** [comment]
Guys, the solution:  

.vscode/settings.json
```json
{
  "css.customData": [".vscode/unocss.json"]
}
```
.vscode/unocss.json
```json
{
  "version": 1.1,
  "atDirectives": [
    {
      "name": "@apply"
    },
    {
      "name": "@screen"
    },
  ]
}

```

**Comment by xiangshu233** [comment]
@a1mersnow 感谢大佬，另外还有个问题想请教下
我在 less 文件中 写 `@apply` 样式无法生效是为什么😂，是需要 postcss 插件吗
https://unocss.dev/integrations/postcss
```less
  .layout-header {
    padding: 0 24px;
    color: #fff;
    @apply bg-gradient-to-r from-sky-500 to-indigo-500 px-7 bg-cover bg-center;
  }
```

**Comment by a1mersnow** [comment]
@xiangshu233 Have you installed `less` lib?
If you are using `Vite`:
https://vitejs.dev/guide/features.html#css-pre-processors

And have you add `lang="less"` to the `<style>` tag?

If so, I don't know other reasons and I don't use less usually.

**Comment by xiangshu233** [comment]
@a1mersnow  感谢大佬的热情回复😀
我安装了 less lib
项目使用的是 vite + less , `@apply` 在  .vue `<style scoped lang='less'></style>` tag 中工作正常

我的问题是：  `@apply` 在 `.less` 文件中使用无效
![image](https://github.com/unocss/unocss/assets/49575330/1577c99a-3c82-44ec-a3cf-2ab74469e55d)

另外 unocss 我开启了  `transformer`

---- From Google Translate -----

Thank you for your enthusiastic reply 😀
I installed less lib
My project is using vite + less , `@apply` works fine in .vue `<style scoped lang='less'></style>` tag

My doubt is: `@apply` is invalid when used in `.less` file
![image](https://github.com/unocss/unocss/assets/49575330/1577c99a-3c82-44ec-a3cf-2ab74469e55d)

Also, unocss I enabled `transformer`

**Comment by a1mersnow** [comment]
@xiangshu233 Can you post your entire `uno.config.ts`?

**Comment by xiangshu233** [comment]
@a1mersnow sure
```ts
import {
  defineConfig,
  presetAttributify,
  presetTypography,
  presetUno,
  presetWebFonts,
} from 'unocss'

import transformerVariantGroup from '@unocss/transformer-variant-group'
import transformerDirectives from '@unocss/transformer-directives'
import presetRemToPx from '@unocss/preset-rem-to-px'

export default defineConfig({
  // ...UnoCSS options
  presets: [
    // 此预设尝试提供流行的实用程序优先框架的通用超集，包括 Tailwind CSS、Windi CSS、Bootstrap、Tachyons 等
    presetUno(),

    // rem 转 px 预设: https://unocss.dev/presets/rem-to-px
    presetRemToPx(),

    // 属性模式(在 class 属性过多的情况下优先使用属性模式，否则将会变得难以维护)
    // https://unocss.dev/presets/attributify#attributify-mode
    presetAttributify(),

    // https://unocss.dev/presets/typography#usage
    presetTypography(),

    // 网络字体预设：https://unocss.dev/presets/web-fonts
    presetWebFonts({
      // 默认字体提供商 https://unocss.dev/presets/web-fonts#providers
      provider: 'google',
      // https://unocss.dev/presets/web-fonts#example
      fonts: {
        mono: ['Fira Code'],
      },
    }),
  ],
  transformers: [
    // 启用 Windi CSS for UnoCSS 的变体组功能(就是简写，具体看链接): https://unocss.dev/transformers/variant-group#usage
    transformerVariantGroup(),
    // 在样式类里你也可以写原子化 css 具体看链接: https://unocss.dev/transformers/directives#usage
    transformerDirectives(),
  ],
})

```

**Comment by a1mersnow** [comment]
Is there any error hint in console?
I got a normal demo: https://stackblitz.com/edit/vitejs-vite-rupz4d?file=src%2FApp.vue
You can check the difference with yours.

**Comment by xiangshu233** [comment]
@a1mersnow wow thank you very much!!!😺

**Comment by mdxiaohu** [comment]
@a1mersnow This configuration takes effect in vite, but even if 'transferDirectives' is installed in Vuecli4,' @ apply 'cannot be used .

**Comment by clouds56** [comment]
Since we have vscode extension for unocss, shall we add support for `@apply` in the extension just like what `postcss`/`tailwindcss` do?

1. syntax highlight, add `custom-at-rules` support, both postcss and tailwindcss support this
    * https://github.com/csstools/postcss-language/blob/master/syntaxes/source.css.tmLanguage.json#L939
    * https://github.com/tailwindlabs/tailwindcss-intellisense/blob/master/packages/vscode-tailwindcss/syntaxes/at-apply.tmLanguage.json
2. contribute to `css.customData`
    * https://github.com/tailwindlabs/tailwindcss/discussions/5258#discussioncomment-2417165
    * https://code.visualstudio.com/api/extension-guides/custom-data-extension

**Comment by Qiu-Jun** [comment]
@a1mersnow thanks
