### ISSUE TITLE
Unocss vscode extension has no underline hints in some scenarios

### ISSUE THREAD

**Issue by andywang646691** [unocss/unocss#2411]
### UnoCSS version

0.50.6

### Describe the bug

Configuring transformers with modified className in unocss.config.ts file will result in unocss vscode extensions without class name hints (underscores). 

By studying the source code, it is found that it may be because the class name is transformed before matching the position, resulting in the original class name cannot be matched.

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/19781389/228161351-204f03aa-f1a3-4f24-be1f-4e2c742288eb.png">

### Reproduction

I think the problem is obvious

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [ ] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)
