### ISSUE TITLE
 ::after is not work in parsetWindi or parsetUno

### ISSUE THREAD

**Issue by wzc520pyfm** [unocss/unocss#2412]
### UnoCSS version

0.50.6

### Describe the bug

my code:
```html
<div>
  <span class="inner" after:content-[123]>
    UnoCSS
  </span>
</div>
```
Unocss successfully parsed it, but it didn't work.

### Reproduction

https://uno.antfu.me/play/?html=DwEwlgbgfAUABHYBnADgQwHZwMYBs1JIC8ARGBhgKYBOJcaAZgC40Bc2A9hi9wLQDaAcgCMAJgDMggLqwECAKoYOAYQDKq%2BIgD0qTLGBbw0IA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUkNikEA&css=HQSwdmCmBOBcsEMBmAXGBvAUAAmwYwHsw1jZsByAFgFYA2cgbkwF8g&options=N4XyA

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wzc520pyfm** [comment]
My current solution is Custom Variants:

```js
export default defineConfig({
  rules: [
    [/^aftc-(.*)$/, ([, s]) => ({ content: `'${s === 'DEFAULT' ? '' : s}'` })],
  ],
  presets: [
    presetUno(),
    presetAttributify(),
    presetIcons({
      scale: 1.2,
      cdn: 'https://esm.sh/'
    }),
  ],
  variants: [
    (input) => {
      const prefix = 'o-after:'
      if (input.startsWith(prefix)) {
        return {
          matcher: input.slice(prefix.length),
          selector: s => `${s}::after`,
        }
       }
     },
  ],
})
```

**Comment by zyyv** [comment]
Hi, if you use pseduo and want to show this content, you need add quoted prefix or `'` `"` in bracket.

https://github.com/unocss/unocss/blob/ef02bb17e20e646b3e07d8ef40bd6bf53dd5b7db/test/assets/preset-mini-targets.ts#L656-L667

Refer to [Playground](https://uno.antfu.me/play/?html=DwEwlgbgfAUABHYBnADgQwHZwMYBs1JIC8ARGgGYAuApgE4Bc2A9hjawLQDaA5AIwBMAZm4BdErAQIAqhiYBhAMoL4iAPSpMsYKvDQYMUJAmINWPAWJkqdRizaUuARwCuTGiHoDBY49NmLlBG1TLR0jIA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUkNikEA&css=Q&options=N4XyA)
