### ISSUE TITLE
hover:( ... ) does not work

### ISSUE THREAD

**Issue by bennymi** [unocss/unocss#2413]
### UnoCSS version

0.50.6

### Describe the bug

When applying multiple hover classes inside a group, the styles do not get applied. 

For example: 

`class="hover:(border-2 border-teal-500)`
or `hover="border-2 border-teal-500"`

### Reproduction

https://uno.antfu.me/play/?html=DwEwlgbgBAFgtAMwK4BsVQC4FMAeG4DGWAdtgE5QIq5QDOW1B%2BxA9sVlAIZoBcGZnYrTAYwbOABYADFIB8AKChRQkKAFtOCpUpXRseOAFYc6Aik61aAXgBEMFhCxkeACgBGLMiCdwATFA8vH2xuIxkAShstbSUAVVYAYQBlJMVtYAB6cAhozOyFPMhZIA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyYfKMdABccADaVAGiSio%2BAJSyUQosbJw8fPzxsgC6SGpxSEA&css=Q&options=N4IgzgLgTglgxhEAuaBXApgGhNAhgOzADMB7KAW2SNwBsx0BfIA

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
Hi, you have to add [transformer-variant-group](https://github.com/unocss/unocss/blob/main/packages/transformer-variant-group/README.md) before you use.

[Playground](https://uno.antfu.me/play/?html=DwEwlgbgBAFgtAMwK4BsVQC4FMAeG4DGWAdtgE5QIq5QDOW1B%2BxA9sVlAIZoBcGZnYrTAYwbOABYADFIB8AKChRQkKAFtOCpUpXRseOAFYc6Aik61aAXgBEMFhCxkeACgBGLMiCdwATFA8vH2xuIxkAShstbSUAVVYAYQBlJMVtYAB6cAhozOyFPMhZIA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcEWWwCGuOlmggMUAGrr2mmAHEoELmCQBfOFksg4Aci4qJdOi6RIMAD0hYdGx1LgAbeEwcfCISYFIACmRheUY6AC44AG0qVNElFUSASll8hRY2Th4%2BfhLZAF01KE1tXX1MnLy4DS0dKD1DY2BTCysweqomu2KkIA&css=Q&options=N4IgzgLgTglgxhEAuaBXApgGhNAhgOzADMB7KAW2SNwBsx0BfIA)
