### ISSUE TITLE
Element with empty class attribute breaks UnoCSS classes in next element in SvelteKit scoped

### ISSUE THREAD

**Issue by henrikvilhelmberglund** [unocss/unocss#2420]
### UnoCSS version

0.50.6

### Describe the bug

Element with empty class attribute breaks UnoCSS classes in next element in SvelteKit scoped.

For example if I have a div with an empty class attribute like `<div class=""></div>` the next element gets messed up. Instead of real UnoCSS SvelteKit scoped class names like 
`<p class="_text-4xl_lnitps s-y_bCXRrkrYfP">This is some text</p>` 
it turns into 
`<p class="text-4xl s-y_bCXRrkrYfP">This is some text</p>`
which doesn't work.

### Reproduction

https://stackblitz.com/edit/unocss-unocss-mn6o3t?file=src/routes/+page.svelte

I added `<p class="text-5xl">This is some text</p>` because one time I loaded the stackblitz two elements were bugged instead of just one.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jacob-8** [comment]
Lol, thanks for keeping me honest. Yes, I ran into this once and ignored it as a rare edge case because it's messy to leave empty `class=""` in your files but you're right. It should be fixed. I'll make sure a test for this is added in #2552
