### ISSUE TITLE
@apply directive not honoring prefix

### ISSUE THREAD

**Issue by J4gQBqqR** [unocss/unocss#2427]
### UnoCSS version

0.50.6

### Describe the bug

Related bug:

1. https://github.com/kidonng/unocss-preset-daisy/issues/18#issuecomment-1492259275
2. https://github.com/kidonng/unocss-preset-daisy/issues/19#issuecomment-1493353780

Any style that uses `@apply` with prefix like `lg:` will not work.

### Reproduction

For example, this styled component will not work:
https://github.com/saadeghi/daisyui/blob/master/src/components/unstyled/drawer.css

Because of [this line](https://github.com/saadeghi/daisyui/blob/master/src/components/unstyled/drawer.css#L73):
`        @apply h-auto lg:col-start-2;`

### System Info

Framework: svelte
UI Library: DaisyUI
Preset: DaisyUI preset
However, this bug should be UI and framework agnostic. 

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jacob-8** [comment]
As mentioned in https://github.com/kidonng/unocss-preset-daisy/issues/14#issuecomment-1483790462, 
[unocss-preset-daisy](https://github.com/kidonng/unocss-preset-daisy) doesn't support variants yet. Please follow https://github.com/kidonng/unocss-preset-daisy/issues/14 for updates on when it will.

Note that future bug reports pertaining to a community preset should be filed in that repo.

**Comment by J4gQBqqR** [comment]
What about @apply not recognizing things such as `hover:` etc? This is not really related to any preset. 

I mean no offense, but I tend to interpret your closing of this ticket is to state that @apply in unocss behaves in this way by design and will not support any prefix? So this behavior of @apply is a designed feature rather than incomplete feature comparing to tailwind? Is this statement true? Could you help me understand about why you think this should not be supported?

Thank you for your explanation.

**Comment by jacob-8** [comment]
> Any style that uses `@apply` with prefix like `lg:` will not work.

As seen in the docs https://github.com/unocss/unocss/tree/main/packages/transformer-directives and in the tests, https://github.com/unocss/unocss/tree/main/packages/transformer-directives, UnoCSS does support prefixes. Your bug report only discussed an issue concerning the daisy preset whose author already told us the prefixes are broken if using his preset. If you are having trouble using prefixes in other contexts please create a Stackblitz repro and we'll be in business.

**Comment by J4gQBqqR** [comment]
I see, I have to quote the prefix in @apply. I did use prefix in @apply before and it doesn't work out, never thought about having to put quotes around it. Thanks for pointing me to the docs.

**Comment by jacob-8** [comment]
You're welcome. I actually don't fully understand why quotes around variants sometimes seem to be needed and sometimes not because that plugin is someone else's work. As you can see from the test, they're not used in that context, but they're mentioned in the docs and it seems they are needed in your context. I've used prefixes successfully without needing quotes, but once I had a hiccup myself regarding the need for quotes.
