### ISSUE TITLE
Why is the Shortcuts not working with hover: active: events

### ISSUE THREAD

**Issue by lynxionxs** [unocss/unocss#2428]
### UnoCSS version

0.50.6

### Describe the bug

Shortcut classes does not work with hover: and active: events

```javascript
shortcuts: {
  // default :hover and :active styles
  'hover-bg': 'bg-gray-200 cursor-pointer',
  'hover-active-bg': 'bg-gray-300',
}
```

```html
<div class="flex p-2 bg-content hover:hover-bg active:hover-active-bg"></div>
```

### Reproduction

none

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by action-hong** [comment]
because default separators is `[':', '-']` 

https://github.com/unocss/unocss/blob/ef02bb17e20e646b3e07d8ef40bd6bf53dd5b7db/packages/core/src/config.ts#L100

https://github.com/unocss/unocss/blob/ef02bb17e20e646b3e07d8ef40bd6bf53dd5b7db/packages/preset-mini/src/_variants/pseudo.ts#L139

so you can set `separators`: `[':']`

```ts
export default defineConfig({
  ...
  separators: [':'],
}
```

**Comment by antfu** [comment]
Or rename your shortcut to avoid using `hover-` as the prefix. Yes.
