### ISSUE TITLE
UnoCSS with Nuxt Layers

### ISSUE THREAD

**Issue by kleinpetr** [unocss/unocss#2430]
### UnoCSS version

0.50.6

### Describe the bug

Hi,

I am trying to use UnoCSS with Nuxt Layers and I am facing few issues

1. I need to use `resolver` in `nuxt.config.ts` when defining unocss config file

2. unocss.config.ts can't be extended, as you can see I use 2 shortcuts in the layer config and then I have 1 shortcut within the top layer config, which updating existing shortcut. But the second shortcut, which is not included in the top layer uno config is gone.

3. UnoCSS Extension cannot decorate class from previous layers
- I use monorepo, so I was trying to setup `unocss.root` with all layers but it doesn't work for those layer which don't have `unocss.config.ts` 

Are there any recommendations how to use UnoCSS with Nuxt Layer in a proper way?

### Reproduction

https://stackblitz.com/github/kleinpetr/nuxt-layers

Also I think when I set atributify mode in the `nuxt.config.ts` and not explicitly in the `unocss.config.ts` it doesn't decorate as well.

### System Info

OS: Linux Fedora 37
VSCode: version 1.76.2
Extension version: v0.50.6
"@unocss/nuxt": "^0.50.6"

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kleinpetr** [comment]
Another findings, when I use more than 2 layers, I need to redeclare `unocss.config.ts` in the nuxt.config

- layer1 (declared resolver with unocss config in the nuxt config)
- layer2 (there is no need to redeclare uno config file, just add `unocss.config.ts` and it loads it
- layer3 (if I don't redeclare path to uno config in nuxt config and only create the `unocss.config.ts` it ignores it

so overall, when I set unocss path resolver at the first layer and try to update `unocss.config.ts` I need to explicitly add the same unocss path resolver into second layer in order to loads them in the third layer..

**Comment by kleinpetr** [comment]
For example https://github.com/Tahul/pinceau has already done layers support even with the extension. Looks very good imho :+1: 

cc @antfu

**Comment by antfu** [comment]
While I'd be happy to support it and I think it's possible to do it at runtime. The problem I see is that for IDE integrations (VS Code etc.) may not aware of the layers config to extend.

**Comment by antfu** [comment]
I added some utilities in v0.51.1, currently I think this is the best solution for the good of both worlds: https://stackblitz.com/edit/github-kyvs1z?file=app/unocss.config.ts

The only downside is that it requires an extra step for layer user to config.

**Comment by kleinpetr** [comment]
Thanks

**Comment by kleinpetr** [comment]
@antfu is there any way how to use `transformers` with `definePreset` since that prop doesn't exist on `definePreset` Thanks.

**Comment by itzaks** [comment]
I'm trying this setup as well. However, when updating styles under `definePreset` in the layer's `unocss.config.ts` I have to restart the main app for the changes to come through. Is there a way to make this update as smooth as when you just use one app?

**Comment by userquin** [comment]
There is a problem in Nuxt with virtual modules, there is no way (I haven't found it) to reload virtual, we need to reload the modules and will fire a few pages reload in a row, depending on the virtuals reloaded.

I get it working in my Vuetify Nuxt Module, the logic can be found here to invalidate a few virtual modules, there is no need to restart the dev server: 
https://github.com/userquin/vuetify-nuxt-module/blob/main/src/utils/loader.ts#L101-L139
