### ISSUE TITLE
Backdrop filters broken in Svelte-scoped from 0.50.2

### ISSUE THREAD

**Issue by henrikvilhelmberglund** [unocss/unocss#2433]
### UnoCSS version

0.50.2 to latest

### Describe the bug

Backdrop filters broken in Svelte-scoped from 0.50.2. They apparently worked in 0.50.1 but something changed in 0.50.2 that made them stop working. 
This thing is missing: 
![opera_03_22-29-19QT7JsNtx65](https://user-images.githubusercontent.com/110549389/229623532-2265f060-0e22-49eb-89c5-32d58d370aff.png)

### Reproduction

Broken: (0.50.2) https://stackblitz.com/edit/unocss-unocss-byrlxk?file=src/routes/+page.svelte
Working: (0.50.1) https://stackblitz.com/edit/unocss-unocss-bijr9g?file=src/routes/+page.svelte

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jacob-8** [comment]
Thanks for the bug report. I'm aware of the problem and it will be fixed in #2552
