### ISSUE TITLE
/__uno.css file missing when using `vite build --watch`

### ISSUE THREAD

**Issue by wheatjs** [unocss/unocss#244]
Ran into this issue earlier and haven't had time to look into it yet. Seems like when using `vite build --watch` with unocss it will give the following error message after saving a file

![image](https://user-images.githubusercontent.com/7064956/145363273-3473d402-b8f0-4017-bc4c-e10ccf0fe2b4.png)

Here is a reproduction on stackblitz. Try changing `bg-red-300` to something like `bg-red-500` and you will see the error in the terminal. If you get the `This feature requires a pro account` dialog you can close it and still see the error in the terminal.
https://stackblitz.com/edit/vitejs-vite-cu4dnw?file=src%2Fcomponents%2FHelloWorld.vue&terminal=dev

**Comment by antfu** [comment]
It does not handles watch mode yet I believe

**Comment by antfu** [comment]
If you want to give it a try, here is how we did that in Windi

https://github.com/windicss/vite-plugin-windicss/commit/cc7619f9e1852e316605d243e171bcc5200e3237
https://github.com/windicss/vite-plugin-windicss/commit/cc7619f9e1852e316605d243e171bcc5200e3237

**Comment by Saul-Mirone** [comment]
Should we make the changes here?

https://github.com/antfu/unocss/blob/main/packages/vite/src/modes/global/build.ts#L46

**Comment by clarkf** [comment]
While working on #2108 I was unable to reproduce this. I think this is fixed?
