### ISSUE TITLE
SyntaxError: Unexpected identifier 'fetch' in Safari

### ISSUE THREAD

**Issue by empty333** [unocss/unocss#245]
Safari v14.1 (16611.1.21.161.3)
node v14.16.1
npm v8.1.3
unocss/nuxt "^0.12.12"

Hello. I don’t know how to properly document errors, but I noticed that when using the @unocss package in the nuxt3. Safari browser throws SyntaxError: Unexpected identifier 'fetch'. Which prevents from using nuxt3 correctly in the future. It doesn't matter if I installed the @unocss package on pure nuxt3 or used the assembly https://github.com/antfu/vitesse-nuxt3

**Comment by dioxine** [comment]
same situation here with Safari v13.1.2 and SvelteKit v1.0.0-next.201
`Unhandled Promise Rejection: SyntaxError: Unexpected identifier 'fetch'` pointing to `start.js` line 1210 which holds this line
```javascript
if (hydrate) await renderer.start(hydrate);
```

**Comment by empty333** [comment]
I don't have this problem in Chrome / Firefox browsers either. Dear antfu, can you somehow solve this problem with the Safari browser? Perhaps there is some temporary fix or you need to downgrade the unocss package. I tried updating node.js from 14.16.1 to 16.13.1 but that did not solve the problem, updating the unocss package to the latest available version 0.16.2 did not solve the problem either.

**Comment by antfu** [comment]
We no longer uses `fetch`.
