### ISSUE TITLE
.blade.php include not working

### ISSUE THREAD

**Issue by philharmonie** [unocss/unocss#2457]
### UnoCSS version

latest

### Describe the bug

Using the following config
```

import { defineConfig, presetUno } from 'unocss'

export default defineConfig({
    presets: [
        presetUno(),
    ],
    include: ['./resources/views/**/*.blade.php'],
})
```

is not adding the styles defined in a `./resources/views/home/welcome.blade.php`.

### Reproduction

[Here is an example repo, showing the exact steps](https://github.com/philharmonie/unocss/commit/2eb2dd79cce729cb99d008f1e2866cb6d1984c65)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
`include` is for matching the files in the build pipeline. For additional assets you will need 
https://github.com/antfu/unocss/blob/b393dd62b19151b8bf215aa3d56d080cd4d0312e/packages/core/src/types.ts#L650-L653

Which will be 

```ts
{
  extraContent: {
    filesystem: ['./resources/views/**/*.blade.php'], // maybe better to path as absolute path
  }
}
```

PR welcome if anyone wants to improve the docs.

**Comment by philharmonie** [comment]
@antfu I tried that without success: https://github.com/philharmonie/unocss/blob/master/uno.config.js

**Comment by philharmonie** [comment]
```
{
  extraContent: {
    filesystem: ['resources/views/**/*.blade.php'], // maybe better to path as absolute path
  }
}
```
It's working like that!
