### ISSUE TITLE
How to get all Tailwindcss classes?

### ISSUE THREAD

**Issue by philharmonie** [unocss/unocss#2465]
### Clear and concise description of the problem

I installed the `presetWind` but not all Tailwindcss classes are working:
```
<div class="bg-slate-900">test</div>
```

### Suggested solution

It would be nice to have all tailwindcss classes, or at least an option to select.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://uno.antfu.me).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sibbng** [comment]
`bg-slate-900` is supported by presetWind. Probably you are misconfigured something. If you could provide a reproduction I can help.

**Comment by antfu** [comment]
https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIBGBzAtExAFwFNcBOABgvQD4SlDgB6cCGoA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUkNikEA&css=Q&options=N4XyA
