### ISSUE TITLE
className not effected when Vite+Solid => Web Components ?

### ISSUE THREAD

**Issue by qiuzhanghua** [unocss/unocss#2467]
### UnoCSS version

0.50.7

### Describe the bug

When I develop Web Components with UnoCSS + SolidJS + ViteJS, it seems className will not work.

```ts
<button
   className="bg-blue-400 hover:bg-blue-500 text-sm text-white font-mono font-light py-2 px-4 rounded border-2 border-blue-200 dark:bg-blue-500 dark:hover:bg-blue-600"
   onClick={() => setCount(count => count + 1)}
>TJ Counter {count} by {props.name}</button>
```

### Reproduction

 my code repo :
https://github.com/qiuzhanghua/tj-components

### System Info

MacOS

Chrome

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
That is because web components isolate the style sheets. You could either change your shadow dom to open, or use https://unocss.dev/integrations/vite#shadow-dom

**Comment by mokeyish** [comment]
@antfu BTW, I enable `shadow-dom` mode, and add `@unocss-placeholder` to my component. 

I found that it only generates the css exists in that file, not gobal. 

How to make it to replace all css with that `@unocss-placeholder`.

**Comment by mokeyish** [comment]
I move the function
https://github.com/unocss/unocss/blob/f3d5afc64d0733e24eba12324963ec6c3eee7407/packages/vite/src/modes/global/build.ts#L49

to 

https://github.com/unocss/unocss/blob/f3d5afc64d0733e24eba12324963ec6c3eee7407/packages/vite/src/modes/shadow-dom.ts#L52

, and call it. but not work.

**Comment by qiuzhanghua** [comment]
When I open shdow-dom, the project compile error:
```
❯ pnpm build

> tj-components@0.0.2 build /Users/daniel/code/web/tj-components
> vite build

vite v4.2.1 building for production...
✓ 1 modules transformed.
✓ built in 24ms
[vite]: Rollup failed to resolve import "virtual:uno.css" from "/Users/daniel/code/web/tj-components/src/index.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "virtual:uno.css" from "/Users/daniel/code/web/tj-components/src/index.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at onRollupWarning (file:///Users/daniel/code/web/tj-components/node_modules/.pnpm/vite@4.2.1/node_modules/vite/dist/node/chunks/dep-79892de8.js:46368:19)
    at onwarn (file:///Users/daniel/code/web/tj-components/node_modules/.pnpm/vite@4.2.1/node_modules/vite/dist/node/chunks/dep-79892de8.js:46138:13)
    at Object.onwarn (file:///Users/daniel/code/web/tj-components/node_modules/.pnpm/rollup@3.20.2/node_modules/rollup/dist/es/shared/node-entry.js:25149:13)
    at ModuleLoader.handleInvalidResolvedId (file:///Users/daniel/code/web/tj-components/node_modules/.pnpm/rollup@3.20.2/node_modules/rollup/dist/es/shared/node-entry.js:23784:26)
    at file:///Users/daniel/code/web/tj-components/node_modules/.pnpm/rollup@3.20.2/node_modules/rollup/dist/es/shared/node-entry.js:23744:26
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 ELIFECYCLE  Command failed with exit code 1.
``` 
BTW, I've upgrade unocss to 0.51.4.

**Comment by qiuzhanghua** [comment]
resolved!

https://github.com/qiuzhanghua/tj-components/tree/0.0.3

but CSS generate is bit huge.

**Comment by mokeyish** [comment]
It seems that the styles of child components(non-shadow) will be lost?
