### ISSUE TITLE
When unocss is used as a postcss plugin, it causes "wait - compiling..." for nextjs.

### ISSUE THREAD

**Issue by RealTong** [unocss/unocss#2473]
### UnoCSS version

0.50.8

### Describe the bug

I tried postcss plugin for UnoCSS according to the [documentation](https://unocss.dev/integrations/postcss).

* UnoCSS only works at startup. HMR gets stuck with "wait - compiling...".
* And in globals.css, Tips "Unknown at-rule ".

### Reproduction

https://stackblitz.com/edit/nextjs-dfibap

### System Info

NextJS version: `13.3.0`
Node version: `v18.12.1`
OS: `Windows 11 22H2`

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sibbng** [comment]
It seems there is an issue about path resolving in current directory. This config fixes the issue:

```js
module.exports = {
  plugins: {
    '@unocss/postcss': {
      content: ['pages/*.{js,ts,jsx,tsx}'],
    },
  },
};
```

**Comment by RealTong** [comment]
UnoCSS is now working properly, thanks for your help!
