### ISSUE TITLE
divide-x seems not working as WindiCSS do

### ISSUE THREAD

**Issue by randomseed42** [unocss/unocss#2483]
### UnoCSS version

0.51.2

### Describe the bug

Using `divide-x-4` is not working in UnoCSS, but works in WindiCSS. Refer below screenshots for minimal reproduction on local Macbook using `pnpm create vite` and removed any other css file.

### Reproduction

Minimal code with UnoCSS
<img width="983" alt="截屏2023-04-10 21 30 55" src="https://user-images.githubusercontent.com/50793718/230911040-2010b55c-71ff-4015-8fb1-5a98334c1a0f.png">

Minimal code with WindiCSS
<img width="983" alt="截屏2023-04-10 21 32 15" src="https://user-images.githubusercontent.com/50793718/230911064-73037d83-7d03-4f77-b80a-f9f662ff5a9d.png">

Compare the output
<img width="436" alt="截屏2023-04-10 21 32 35" src="https://user-images.githubusercontent.com/50793718/230911074-86b20993-2e97-405a-9d2a-d0d7dcd919b0.png">

### System Info

MacOS Ventura 13.3.1 & Win10
Chrome 112.0.5615.49
Vue 3.2.47, Vite 4.2.0, Typescript 4.9.3

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sibbng** [comment]
You need to install Tailwind reset: https://unocss.dev/guide/style-reset#tailwind

Alternative solutions: 
- Add `b-solid` class
- https://github.com/unocss/unocss/issues/2285#issuecomment-1452311355
- https://github.com/unocss/unocss/pull/1971#issuecomment-1382000552

**Comment by randomseed42** [comment]
Thank you very much!
