### ISSUE TITLE
how to use rgba, for example, text-rgba(xxx) bg-rgba(xxx)

### ISSUE THREAD

**Issue by alvin0216** [unocss/unocss#2508]
### UnoCSS version

0.51.4

### Describe the bug

 bg-rgba(255, 0, 0, 0.5) 无法生效

### Reproduction

 bg-rgba(255, 0, 0, 0.5) 无法生效

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
You can try adding bracket sometime. `text-[rgba(255, 0, 0, 0.5)]` `bg-[rgba(255, 0, 0, 0.5)]`

**Comment by zouhangwithsweet** [comment]
> text

Doesnot work? Does it need some preset or setting ?

**Comment by zyyv** [comment]
> > You can try adding bracket sometime. text-[rgba(255, 0, 0, 0.5)] bg-[rgba(255, 0, 0, 0.5)]
> 
> Doesnot work? Does it need some preset or setting ?

https://unocss.dev/interactive/?s=bg-[rgba(255,0,0,0.5)]

**Comment by zouhangwithsweet** [comment]
> > > You can try adding bracket sometime. text-[rgba(255, 0, 0, 0.5)] bg-[rgba(255, 0, 0, 0.5)]
> > 
> > 
> > Doesnot work? Does it need some preset or setting ?
> 
> [https://unocss.dev/interactive/?s=bg-[rgba(255,0,0,0.5)]](https://unocss.dev/interactive/?s=bg-%5Brgba(255,0,0,0.5)%5D)

Ao, I found there is a space bettween `,` and `0` in my code, `bg-[rgba(255, 0, 0, 0.5)]`. Thanks very much
