### ISSUE TITLE
__vite_ssr_import_meta__.hot.send is not a function

### ISSUE THREAD

**Issue by sfxcode** [unocss/unocss#2509]
### UnoCSS version

unocss nuxt 0.51.4

### Describe the bug

starting histoire with unocss nuxt throws this error.

Histoire version: 0.16.1 

https://github.com/unocss/unocss/issues/1823 seems to be an equal problem, bit is marked as closed

### Reproduction

https://github.com/sfxcode/nuxt3-primevue-starter

### System Info

------------------------------
- Operating System: Darwin
- Node Version:     v18.15.0
- Nuxt Version:     3.4.1
- Nitro Version:    2.3.3
- Package Manager:  pnpm@8.2.0
- Builder:          vite
- User Config:      devtools, ssr, runtimeConfig, modules, content, unocss, primevue, css, pinia, build, sourcemap
- Runtime Modules:  @formkit/nuxt@0.16.4, @sfxcode/nuxt-primevue@1.1.0, @unocss/nuxt@0.51.4, @pinia/nuxt@0.4.8, @nuxt/content@2.5.2, @vueuse/nuxt@10.0.2
- Build Modules:    -
------------------------------

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Fixed in https://github.com/vitest-dev/vitest/commit/b1624db5d3baf26f7e1c69b23cf4c1335562ccde
