### ISSUE TITLE
Duplicate styles injected when using Astro integration

### ISSUE THREAD

**Issue by markmals** [unocss/unocss#2513]
### UnoCSS version

0.51.4

### Describe the bug

When using the UnoCSS Astro integration, two different sets of the same UnoCSS styles are injected into the `<head>`, one with the attribute `data-astro-dev-id="{path/to}/__uno.css"` and another with the attribute `data-vite-dev-id="/__uno.css"`

### Reproduction

https://stackblitz.com/edit/github-u8fq8k?file=src/pages/index.astro

### System Info

macOS 13.3.1, Chrome 112.0.5615.121, Astro 2.3.0

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jsonleex** [comment]
This problem still exists.

https://stackblitz.com/edit/github-u8fq8k-s1lqwe?file=package.json

<img width="232" alt="image" src="https://github.com/unocss/unocss/assets/25883665/ba178fb3-6c01-4075-935d-0c516760f220">

<img width="830" alt="iShot_2023-05-29_07 56 28" src="https://github.com/unocss/unocss/assets/25883665/01825ad7-8d63-4ffa-a79f-ddd7913d4d10">
