### ISSUE TITLE
How about group attribute selector values?

### ISSUE THREAD

**Issue by lvjiaxuan** [unocss/unocss#2518]
### Clear and concise description of the problem

I had tried to find out which utilities can style the following normal CSS:
```css
input[type=number], input[type=text] {
  color: red
}
```

Available syntax by https://github.com/unocss/unocss/discussions/2498#discussioncomment-5600921
```html
<div class="[&[type=number],&[type=text]]:c-red" />
```

After that, it might be a feature?

### Suggested solution

I demo a [transformer](https://github.com/lvjiaxuan/transformer-attribute-values-group).

Expect any suggestions~

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://uno.antfu.me).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Nice. You can send a PR to add it as a community transformer.
