### ISSUE TITLE
unocss for react native

### ISSUE THREAD

**Issue by electroheadfx** [unocss/unocss#252]
Guys Would like possible to make work UnoCSS/webpack with react native ?

**Comment by edwardnyc** [comment]
I've been trying lately(Demo experiment).

I don't know what will antfu thinks.

**Comment by antfu** [comment]
I am not familiar with React Native, but if it works with CSS, UnoCSS should work.

**Comment by electroheadfx** [comment]
Thanks, Iam testing it :)
The only detail I dont understand is that ReactNative use className instead of class, does UnoCSS can know that ?
and for uno preset I don't know how to install ?

**Comment by edwardnyc** [comment]
> 

![image](https://user-images.githubusercontent.com/31278178/145530008-f0e5b87b-3596-4baa-bfb8-b991f22364f1.png)

Unfortunately: it's not CSS. I demo some work. But a lot of work is expected.

**Comment by electroheadfx** [comment]
so you would inject the UnoCSS to styleSheet object ? uno work only from class. Its a special UnoCSS for react native it needed for that. Maybe some peaple could port it a day.

**Comment by edwardnyc** [comment]
I think we need to complete the code replacement and replace the `class` with the form of `style` = {}`. The other is how to integrate the attributes according to the stylesheet specification. 

However, I have no confidence in performing the operation of code replacement before compiling the source file.
What do you think? Will we support this plugin？

If you plan to support it, you can start by completing the dynamic replacement part of the source code? I'll help you complete the rest. Emmm I don't know about webpack @antfu

**Comment by aktasumut34** [comment]
There is package named "css-to-react-native". if someone want collab with me, we can work on it
