### ISSUE TITLE
Intellisense not working for attributes with the presetAttributify preset

### ISSUE THREAD

**Issue by Rednas83** [unocss/unocss#2523]
### UnoCSS version

0.51.5

### Describe the bug

Intellisense only seems to work with the class attribute. Is there also a way to make it work for attributified attributes?

### Reproduction

This works:
`<div class="navbar-center">`
This is not working:
`<div navbar-center>`

### System Info

Tailwind CSS IntelliSense v0.9.11
@unocss/preset-attributify v0.51.5
daisyui v2.51.5
@kidonng/daisyui  v2.51.3

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sibbng** [comment]
UnoCSS has its own VS Code extension: https://unocss.dev/integrations/vscode
