### ISSUE TITLE
`extraContent` not working as expected

### ISSUE THREAD

**Issue by MLoth** [unocss/unocss#2527]
### UnoCSS version

0.50.6

### Describe the bug

I'm using `extraContent`, but it isn't working as expected:
In the monorepo, I have a package. This package uses another package with Vue & unoCSS components.
To get the styles from the other package, I use the extraContent property that points to the (custom) npm-module.

The thing is, when I go to the @unocss/vite source-code and I comment the following out (function `setupExtraContent`):
```
if (!filter(code, file)) {
  return;
}
```
Everything works as expected, when this check is removed. I can not find any info on what this does?
What am I doing wrong? Is this a bug?

### Reproduction

Pretty hard to reproduce. I have a monorepo with multiple custom npm-packages. These files are also build to `.js`-files.
See the following code that is being build (and where I want to search for classes):
```js
return t.icon && (console.log("Trying to load", t.icon), r()), {
      classes: g(() => ({
        "font-bold rounded-full outline-none focus-visible:ring-2 ring-blue-500 disabled:cursor-not-allowed font-heading": !0,
        "bg-ct-blue-500 px-4 text-white hover:bg-ct-blue-600 active:bg-ct-blue-400 active:text-ct-blue-600 disabled:bg-ct-black-500 disabled:text-ct-black-700 py-2 px-6": t.style === "primary",
        "bg-ct-black-200 px-4 text-ct-blue-500 active:bg-ct-blue-400 active:text-ct-blue-600 hover:bg-ct-blue-200 focus-visible:bg-white disabled:bg-ct-black-300 disabled:text-ct-black-700 py-2 px-6": t.style === "secondary",
        "bg-transparent px-4 text-ct-blue-500 hover:text-ct-blue-600 active:text-ct-blue-600 disabled:text-ct-black-300 py-2 px-6": t.style === "tertiary",
        "bg-transparent text-black hover:bg-ct-black-200 @dark:hover:bg-ct-black-800 active:bg-transparent disabled:text-ct-black-300 p-4 @dark:text-white": t.style === "icon",
        "bg-ct-red-500 px-4 hover:bg-ct-red-600 active:bg-ct-red-400 active:text-ct-red-500 disabled:bg-ct-red-300 disabled:text-ct-red-400 py-2 px-6": t.style === "destructive primary",
        "bg-transparent px-4 text-ct-red-500 hover:text-ct-red-600 active:text-ct-red-600 disabled:text-ct-red-400 py-2 px-6": t.style === "destructive tertiary"
      })),
      onClick() {
        o("click");
      },
      Icon: e
    };
```

I use the `extraContent` like:
```ts
extraContent: {
  filesystem: [`../../node_modules/@creative-therapy/ui/dist/*.js`],
},
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sibbng** [comment]
JS files are not processed by default. 

https://github.com/unocss/unocss/blob/224f90fd9bd11ea74fa1aaba1d80f8ece69d8da2/packages/shared-integration/src/defaults.ts#L5

You can configure this option:

```ts
include: [
  /\.(vue|svelte|[jt]sx|mdx?|astro|elm|php|phtml|html)($|\?)/,
  /@creative-therapy/
],
extraContent: {
  filesystem: [`../../node_modules/@creative-therapy/ui/dist/*.js`],
},
```

Adding JS files to original filter would have been slow down your build process too much. This configuration whilelisting your projects name.
