### ISSUE TITLE
the default export and sideEffects of `virtual:uno.css?inline`

### ISSUE THREAD

**Issue by lisonge** [unocss/unocss#2533]
### UnoCSS version

0.51.5

### Describe the bug

the module `virtual:uno.css?inline` still has sideEffects

![image](https://user-images.githubusercontent.com/38517192/233778821-89f96d7f-efab-40a1-9e00-a080172fc5be.png)

---

when vite build, the default export of module `virtual:uno.css?inline` is `''`

![image](https://user-images.githubusercontent.com/38517192/233778932-18ece001-3a2a-4fc8-aed0-da863561b7d6.png)

![image](https://user-images.githubusercontent.com/38517192/233778939-3a7c73bf-cfbd-49da-849d-bc61e0696129.png)

---

when vite serve, there is not hmr for `virtual:uno.css?inline`

It should behave the same way as vite inline css

### Reproduction

<https://stackblitz.com/edit/vitejs-vite-hcufny?file=src%2Fmain.tsx&terminal=dev>

or

[test-shadow-dom/vite.config.ts](https://github.com/lisonge/vite-plugin-monkey/blob/614fd5d8c87a1e8112ebc6d130cd35521359d2bc/playground/test-shadow-dom/vite.config.ts)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
The reproduction link you provided is wrong.

> [test-shadow-dom/vite.config.ts](https://github.com/lisonge/vite-plugin-monkey/blob/614fd5d8c87a1e8112ebc6d130cd35521359d2bc/playground/test-shadow-dom/vite.config.ts)

In this configuration, I don't see you using any preset. I suggest you add `presetUno` first to test it, and update this issue.

**Comment by lisonge** [comment]
sorry, I uploaded the file yesterday and forgot to save it

now it is correct reproduction

<https://stackblitz.com/edit/vitejs-vite-hcufny?file=src%2Fmain.tsx&terminal=dev>

**Comment by lisonge** [comment]
>  I don't see you using any preset. I suggest you add presetUno first to test it, and update this issue.

Which preset can change the default export and sideEffects of `virtual:uno.css?inline` ?

**Comment by lisonge** [comment]
ok, Let me explain the application scenario of `virtual:uno.css?inline`

In the development of [tampermonkey](https://www.tampermonkey.net/) scripts

we inject vite app js code to the target website by [vite-plugin-monkey](https://github.com/lisonge/vite-plugin-monkey.git)

the target website can be any website, so `style conflict` is inevitable

I think the best solution is render our app in a shadow dom, so we use `.css?inline` in vite

```tsx
// main.tsx
import { render, Portal } from 'solid-js/web';

import App from './App';
import style from './hmr_inline_css';

render(
  () => (
    <Portal useShadow>
      {style}
      <App />
    </Portal>
  ),
  document.body,
);
```
```ts
// hmr_inline_css.ts
import text from './style.css?inline';

const style = document.createElement('style');
style.textContent = text;
export default style;

if (import.meta.hot) {
  import.meta.hot.accept('./style.css?inline', (newModule) => {
    const text2 = newModule?.default as string;
    style.textContent = text2 ?? ``;
  });
}
```

There is no problem for  css/sass/less files

but when I use `virtual:uno.css?inline`,  Its behavior is inconsistent with `.css?inline`

so it doesn't solve the problem above

**Comment by antfu** [comment]
Have you tried https://unocss.dev/integrations/vite#web-components?

**Comment by lisonge** [comment]
> Have you tried https://unocss.dev/integrations/vite#web-components?

https://github.com/lisonge/vite-plugin-monkey/issues/77#issuecomment-1518012507

we just use a shadom-dom to wrap vue/solidjs/react/preact for style isolation

**Comment by lisonge** [comment]
I think that it is not difficult to achieve

if you want it, I can try pull request

**Comment by antfu** [comment]
Hum, ok. Let's see the PR

**Comment by gorankarlic** [comment]
Apparently importing `virtual:uno.css` also breaks DOM events, e.g. in the example below neither event will fire and nothing will logged to the console.

```ts
import "virtual:uno.css";

window.addEventListener("load", () => console.log("window load"));
document.addEventListener("DOMContentLoaded", () => console.log("DOMContentLoaded"));
```

Another wasted hour thanks to the great Vue ecosystem full of excellent engineering.

**Comment by lisonge** [comment]
> Apparently importing `virtual:uno.css` (with and without `?inline`) also breaks important DOM events, e.g. in the example below neither event will fire and nothing will be logged to the console.
> 
> ```ts
> import "virtual:uno.css";
> 
> window.addEventListener("load", () => console.log("window load"));
> document.addEventListener("DOMContentLoaded", () => console.log("DOMContentLoaded"));
> ```

@gorankarlic 

another simple way to solve problems but automatic no tree shaking

https://github.com/unocss/unocss/pull/2570#issuecomment-1666584117
