### ISSUE TITLE
@unocss/preset-uno colors parsing problem?

### ISSUE THREAD

**Issue by ModyQyW** [unocss/unocss#2537]
### UnoCSS version

0.51.8

### Describe the bug

I am developing `unocss-preset-element-plus`, a preset that makes `unocss` and `element-plus` work together.

In `element-plus`, they have `colors-primary`, `colors-primary-light-3`, `colors-primary-light-9`, `colors-primary-dark-2` , and more css vars.

I extend colors on Tailwind Play, try `.text-primary`, `.text-primary-light-1`, `.text-primary-light2`, and I get what I want. [Link here](https://play.tailwindcss.com/OdauDapW43)

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/31850793/233938699-e9ba39e6-67bd-4bc3-98e9-fbe3667f2cc0.png">

<img width="1134" alt="image" src="https://user-images.githubusercontent.com/31850793/233938628-3e60c8a2-ccb2-4817-8b23-90f0951096a3.png">

But when I try them with `@unocss/preset-uno` on `unocss` playground, I can't get the last two. [Link here](https://uno.antfu.me/play/?html=DwBwBAxgNghgznAvAIgC4FMAeqC0IBOAlgLYz4CeyAfBtnkaRcAPQhUBQoksCKtuBEmXI4ohAOYALXAEZq-ekIqiJ0nDJZtO4aPCRosAhsJVTUAJnmHFjEWLPnNVIA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCqWEcAvnOlBCHAOQCujAYypVuAKFGoAHpFgoMAQ14AbeGkw58hYEQAUCUXDgwAFqhCoAXIgOG4AiEuhUr%2B22-JRQ8qAE8XN91sAEQBRADEAQToAGQAVK24AYgAGVO4SAMCeJW1jGABaAEZuBMSANgr0zMDuHKI8gCYSnkSBNqqslmquw2YMwwpqWmc4AG1MwZp6Rh0AShsAXVFmeaA&css=Q&options=N4XyA)

<img width="1919" alt="image" src="https://user-images.githubusercontent.com/31850793/233939313-d2a349ee-073b-43e1-9773-cbea8fa276a7.png">

> This preset is compatible with [Tailwind CSS](https://tailwindcss.com/) and [Windi CSS](https://windicss.org/), you can refer to their [documentation](https://tailwindcss.com/docs) for detailed usage.

Said in `@unocss/preset-uno` https://unocss.dev/presets/uno#rules. Based on it, I think this is a `@unocss/preset-uno` compatibility issue.

Compatibility aside, it's also strange that I can use something like `.text-rose-50` but not `.text-primary-light-1` since I have defined it like what `.text-rose-50` defined. Maybe it is a colors parsing problem?

### Reproduction

https://uno.antfu.me/play/?html=DwBwBAxgNghgznAvAIgC4FMAeqC0IBOAlgLYz4CeyAfBtnkaRcAPQhUBQoksCKtuBEmXI4ohAOYALXAEZq-ekIqiJ0nDJZtO4aPCRosAhsJVTUAJnmHFjEWLPnNVIA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCqWEcAvnOlBCHAOQCujAYypVuAKFGoAHpFgoMAQ14AbeGkw58hYEQAUCUXDgwAFqhCoAXIgOG4AiEuhUr%2B22-JRQ8qAE8XN91sAEQBRADEAQToAGQAVK24AYgAGVO4SAMCeJW1jGABaAEZuBMSANgr0zMDuHKI8gCYSnkSBNqqslmquw2YMwwpqWmc4AG1MwZp6Rh0AShsAXVFmeaA&css=Q&options=N4XyA

### System Info

```shell
  System:
    OS: macOS 13.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 33.70 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.15.0/bin/yarn
    npm: 9.6.5 - ~/.nvm/versions/node/v18.15.0/bin/npm
    Watchman: 2023.04.17.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 112.0.5615.137
    Safari: 16.4
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
Refer to [Playground](https://uno.antfu.me/play/?html=DwBwBAxgNghgznAvAIgC4FMAeqC0IBOAlgLYz4CeyAfBtnkaRcAPQhUBQoksCKtuBEmXI4ohAOYALXAEZq-ekIqiJ0nDJZtO4aPCRosAhsJVTUAJnmHFjEWLPnNHdgsG3TamQAYvQA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCqWEcAvnOlBCHAOQCujAYypVuAKFGoAHpFgoMAQ14AbeGkw58hYEQAUCUXDgwAFqhCoAXIgOG4AiEuhUr%2B27Yqh5UAJ4ubbwwARAFEAMQBBOgAZABUrbgBiAAYU7hJ-AKVtYxg-AICARniEgDYytIz8gCZigTqK-MNmdPzmjLamlvJKGhhnOABtCmpaBggdAEoAXXTmCdEgA&css=Q&options=N4XyA)

Please follow the configuration/parsing logic of UnoCSS, when there is a number in the key, it will look for its subset.

**Comment by ModyQyW** [comment]
Thank you!!!!
