### ISSUE TITLE
Provide `@unocss/transformer-variant-group` for `@unocss/runtime`

### ISSUE THREAD

**Issue by vladrose** [unocss/unocss#2538]
### Clear and concise description of the problem

I use Next.js for my project and `@unocss/runtime` works perfect for me, but there is no support for variant groups. I tried to make `transformers` field in `window.__unocss` and `initUnocssRuntime` but nothing.

### Suggested solution

Add variant groups transformer to the runtime package by default

### Additional context

If I add `shortcuts: { test: "hover:(bg-green-400 p-4) transition-all" }` to the `window.__unocss` it works great.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://uno.antfu.me).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
We are not going to ship every combinations - please use bundler usage for that case, or construct your own CDN build.

**Comment by vladrose** [comment]
It works for shortcuts somehow

**Comment by antfu** [comment]
Yes - shortcuts do not transform your code. By transforming, it needs a build pipeline.

**Comment by vladrose** [comment]
Got it thanks, this is the killer feature anyway! Will try to use both runtime and build approaches with bypass
