### ISSUE TITLE
can not get type of Theme

### ISSUE THREAD

**Issue by wtto00** [unocss/unocss#2542]
### UnoCSS version

0.51.8

### Describe the bug

The generic name "Theme" of defineConfig conflicts with the imported type "Theme", causing the inability to obtain the Theme type in `uno.config.ts`. Although it seems not to be a conflict in the source code, it becomes a conflict after being packaged.
As shown in the following picture:

defineConfig 的泛型名称Theme和导入的类型 Theme 重名了，导致`uno.config.ts`中无法获取到 Theme 类型。我看源代码好像不是重名的，但是打包后变为了重名？
如下图所示

### Reproduction

![screenshot-20230425-174902](https://user-images.githubusercontent.com/30424139/234240720-e339ebd7-7f72-4c7f-a6a5-a279d1a93954.png)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Sounds like a bundler bug, workarounded by changing the generic name
