### ISSUE TITLE
✨ Exploring inversion of compilation mode for shortcuts

### ISSUE THREAD

**Issue by jd-solanki** [unocss/unocss#2543]
### Clear and concise description of the problem

Hi 👋🏻 

I'm here to discuss exciting new feature. Let me explain the problem when we use utility frameworks:

Assume we have UI like this: 
![image](https://user-images.githubusercontent.com/47495003/234483009-254c50e3-440a-44d4-932b-ffafb1fbb629.png)

Here, we need similar styles for user data. Same font-size, color, spacing etc. We have two approaches to complete this:
1. Use same utility classes for both.

<table>
    <tr>
        <td>consistency</td>
        <td>❌</td>
    </tr>
    <tr>
        <td>CSS reusability - Only Utility classes will get generated</td>
        <td>✅</td>
    </tr>
</table>

[Playground](https://unocss.dev/play/?html=DwBwBAxgNghgznAvAIhAWgCxgLYCM0CMYALgKYAexaATqQCbIB8wA9CIwFDB0CWAbpFgIU6DE1a8%2BnUIPhJkeQuLaMgA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUkNikEA&css=Q&options=N4XyA) - No extract CSS is generated except utility classes

2. Use Uno shortcuts

<table>
    <tr>
        <td>consistency</td>
        <td>✅</td>
    </tr>
    <tr>
        <td>CSS reusability - CSS will be generated for both, shortcut and utilities</td>
        <td>❌</td>
    </tr>
</table>

[Playground](https://unocss.dev/play/?html=DwBwBAxgNghgznAvAIggVzgFwPYFsC0cAFtgE6bqbIB8wA9CNQFDAAmAlgG6SwIoj4ALDXodOzUD3hJkuAEb4AjCIbUgA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enlgiQAscCAciQCMcDBWMMkYhVRqsiIKjeGRcqJKKj4AlLLC8owsbJw8fPw7e%2BsKktJ%2Ba6h0EvapoaMAdABMl6gSaLh5VVYYEaAHoQfQQG9qiCzC1irtykg1NskEA&css=Q&options=N4XyA) - Extra CSS in `custom-class` (that can be avaiable via utility classes being used)

### Suggested solution

> **Note**
> This is just theory

Can we create inversion of compile class transformer? (_shortcut replacer_)

**API/Usage:**

When we enable inverted version of compile class transformer, we can allow users to write class like this (like we are using shortcut):
```html
<p class="custom-shortcut"></p>
```

and we can allow new option (or transformer) in UnoCSS:
```
export default defineConfig({
  rules: [],
  shortcuts: [],
  replacableShortcuts: {
    'custom-shortcut': 'p-4 mb-1 text-red'
  }
})
```

that will replace the `custom-shortcut` class in DOM with utilities,  so that rendered DOM will become:
```html
<p class="p-4 mb-1 text-red"></p>
```

This is same strategy when we use compile class transformer. Difference will be instead of removing all utility classes and adding new random class we will replace that specific class with utilities for consitency and CSS reusability.

<table>
    <tr>
        <td>consistency</td>
        <td>✅</td>
    </tr>
    <tr>
        <td>CSS reusability - CSS will be generated for shortcut</td>
        <td>✅</td>
    </tr>
</table>

### Alternative

Randomly using shortcuts and utility class 😅 

### Additional context

I guess this the question, you might have encountered when you need same style at two different places and don't want to repeat the stuff.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://uno.antfu.me).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Well, we have tried a similar idea in Windi CSS called Alias: https://windicss.org/integrations/vite.html#alias-config

I am not sure if this idea ended up being used many. What I feel is that generally ppl don't need to care about what the output is, the expressiveness usually matters more (a.k.a usually a few extra bytes of using shortcuts isn't a concern). The problem I see with the approach you are proposing is it could be a bit overkill. For example:

```html
<p class="custom-shortcut">This is an example of custom-shortcut</p>
```

Without parsing HTML (note that components like Vue, Svelte etc. need specialized parsers to handle well), we will not be able to tell which "custom-shortcut" to replace. That's why we introduced `*` prefix in Windi to distinguish that. Plus, I guess it might not be able to support `hover:custom-shortcut` right?

**Comment by jd-solanki** [comment]
Hey,

Thanks for your response.

> _Well, we have tried a similar idea in Windi CSS called Alias: [windicss.org/integrations/vite.html#alias-config](https://windicss.org/integrations/vite.html#alias-config)_

Wow, I should checkout windi.

> _ppl don't need to care about what the output is_

true 💯  however if you consider consistency this makes much more sense according to me

> _Without parsing HTML (...)_
Aren't we already extracting classes from markup/content? I guess we are already extracting class tokens 🤔 

> _which "custom-shortcut" to replace_
You know this better but to confirm we are on same page, when we generate the CSS for specific class we do have full config, right? So can't we check if the class is present in alias or not 🤷🏻‍♂️ 

> _it might not be able to support hover:custom-shortcut right?_
Yes, alias won't have variants 💯 

---

Thanks for your inputs, I'm interested in how you'll approach to mentioned problem considering consistency?

> _P.S. `alias` is better name_

**Comment by antfu** [comment]
We are extracting using regex, meaning we generate classes for the occurrence but not always in class. A few examples:

```ts
<script setup>
const myClass = 'text-red'
</script>

<template>
  <div :class="myClass" /> 
</template>
```

Statically parsing HTML you will not able to capture `text-red` as it's not directly presented in the `class`. UnoCSS works in that case because it doesn't care about the semantic but only if the token is presented in the file. That also means it works because we don't touch the source file and it's ok for the generated CSS to be a bit overkill sometime.

**Comment by jd-solanki** [comment]
Got it 👍🏻 

Will you merge the implementation if someone makes a PR or we won't see this feature in UnoCSS?

**Comment by zyyv** [comment]
> that will replace the custom-shortcut class in DOM with utilities, so that rendered DOM will become:

> Will you merge the implementation if someone makes a PR or we won't see this feature in UnoCSS?

I think it is possible to implement a `tranformer` and exist as a `community tranformer`

**Comment by antfu** [comment]
Can't give any promises right away. You could try to implement it as a community solution first and we will see :)
