### ISSUE TITLE
Race condition on stackblitz when packages are installed later than the extension tries loading them

### ISSUE THREAD

**Issue by FireMasterK** [unocss/unocss#2546]
### UnoCSS version

0.51.8

### Describe the bug

When a stackblitz repository takes time to install packages, the extension fails to properly load since it can't import the module as it hasn't been installed yet.

I've submitted an issue on stackblitz too, but they suggested opening one here - https://github.com/stackblitz/webcontainer-core/issues/1049

### Reproduction

https://stackblitz.com/~/github.com/teampiped/piped

In this link, the extension fails to actually work since the packages take time to install

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
I don't really know how to resolve it. Ideally it would be nice to have a VS Code event to say an install command is finished or so, so we can trigger a restart. But I am not aware such event exists in VS Code extension. Help wanted

**Comment by FireMasterK** [comment]
Maybe we could resolve it by using a filewatcher to see when the packages have been installed, or otherwise retry when intelisense is actually being used (only when the import fails initially)?
