### ISSUE TITLE
Divide does not work on dark mode when used in a shortcut.

### ISSUE THREAD

**Issue by tonychuuy** [unocss/unocss#2549]
### UnoCSS version

0.51.8

### Describe the bug

When added a shortcut to use the same class name for light and dark mode, the dark style does not work for the divide utility but it works when used with border:

```
export default defineConfig({
  shortcuts: {
    'border-default': 'border-[#F1F1F1] dark:border-[#33334a]',
    'divide-default': 'divide-[#F1F1F1] dark:divide-[#33334a]',
  },
  presets: [
    presetUno(),
  ]
})
```

```
<ul class="divide-y divide-default">
  <li>Uno</li>
  <li>Dos</li>
  <li>Tres</li>
  <li>Cuatro</li>
  <li>Cinco</li>
</ul>

<ul>
  <li class="border-b border-default">Uno</li>
  <li class="border-b border-default">Dos</li>
  <li class="border-b border-default">Tres</li>
  <li class="border-b border-default">Cuatro</li>
  <li class="border-b border-default">Cinco</li>
</ul>
```

By now I added border-default on every `<li>` to workaround this.

### Reproduction

Using the dark mode, the light style is applied for the divide utility. Here is the playground:
https://uno.antfu.me/play/?html=DwVwNgBAxmCGDO8C8AiAJgSwG4bQUwFoBPCTHfA-AM1nABcUA%2BAKAgmDA0YFUA7Ae2AB6TizYcuAEX7xho1u1EAVAE55ZIrgomMAwiFh0VgzWMVddGXlBPzh4Fs1BgzE6HESoARvxX4VBF4QPn54AdS0YAw8AnJa4pzuCMgoIf6Bwb7pEfRM0hryCRhJnqlZYRlpFTlRTKrqca6JMMne5QFBVeF4NLl6Bka28eYlKV2V7ZQ9kdGW1kMs9i5AA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAqrhJQL5xZQQhwDkAV1YBjOnX5IkGAB6RY6bAENBAG3iYc%2BIiWCkAFMlR0AFtBgjBMOgC5EVVPwBG0TFAC0mlev53nrjA8AbQBiADEARkjIgF10JSgAaxsXKDd3UIBmbMyAFiUY-kpURzRgADdgTE9lNRhfATLK6tDoqIi4tATkpqqMDJCcvIKiqnZi6loGazsgh0n6RhYIfQBKCZikdlWkIA&css=FBA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g

### System Info

Firefox Version 112.0.1 (64-bit)
Vue 3.2.45
Vite 4.0.0

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Dunqing** [comment]
Another workaround, you should avoid using `divide-*` naming。
