### ISSUE TITLE
css class无法动态绑定

### ISSUE THREAD

**Issue by TTcom** [unocss/unocss#2562]
### UnoCSS version

0.51.8

### Describe the bug

css class无法动态绑定 z-index无效

### Reproduction

![uTools_1682909341841](https://user-images.githubusercontent.com/29853303/235394718-6b3b1b2e-48ba-41e8-8638-b68596995730.png)

### System Info

window10 chrom浏览器

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by silentmx** [comment]
看一下[safelist](https://unocss.dev/guide/extracting)的内容
