### ISSUE TITLE
`dark:` and `postcss-nested` doesn't work with explicit `presetUno()` declaration 

### ISSUE THREAD

**Issue by enkot** [unocss/unocss#2568]
### UnoCSS version

0.51.8

### Describe the bug

When specify `presetUno()` explicitly in the config, nested @apply classes are not generated:
```vue
<style>
.parent {
  a {
    @apply dark:(bg-green-400 text-white) hover:bg-green-900;
  }
}
</style>
```
```ts
export default defineConfig({
  presets: [presetUno()],
  transformers: [transformerVariantGroup(), transformerDirectives()],
});
```
BUT, it starts working if just remove `presetUno()` from the config:
```ts
export default defineConfig({
  transformers: [transformerVariantGroup(), transformerDirectives()],
});
```

### Reproduction

https://stackblitz.com/edit/github-y5mxex?file=uno.config.ts

Try to uncomment line 7, styles will disappear.

### System Info

- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.4.3
- Nitro Version:    2.3.3
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      modules, postcss
- Runtime Modules:  @unocss/nuxt@0.51.8
- Build Modules:    -

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Wonder why you are using `unocss/nuxt` and the postcss plugin at the same time? I think it might be a bug of the postcss plugin (cc @sibbng). But commenting it out, it would work: https://stackblitz.com/edit/github-y5mxex-hyyqs2?file=nuxt.config.ts%3AL6,uno.config.ts

**Comment by enkot** [comment]
Thanks for the fast feedback!
But what if I need to override some classes, f.e. `.container`. In Windi setup I could do something like this:
```css
@layer base {
  .container {
    @apply w-64 bg-gray-200;
  }
}
```
What is the proper setup to do the same with Uno? Repro: https://stackblitz.com/edit/github-y5mxex?file=nuxt.config.ts,styles%2Fbase.pcss

**Comment by enkot** [comment]
With `postcss` only setup this also doesn't work:
```ts
<style>
.parent {
  a {
    @apply dark:text-green-500;
  }
}
</style>
```
tag `a` also doesn't have hover styles:
```css
@import '@unocss/reset/tailwind.css';

@unocss preflights;
@unocss default;

a {
  @apply hover:underlined;
}
.container {
  @apply w-64 bg-gray-200;
}

@unocss;
```
https://stackblitz.com/edit/github-y5mxex?file=nuxt.config.ts,uno.config.ts,app.vue,styles%2Fbase.css
