### ISSUE TITLE
Compatibility issue with border-[...]

### ISSUE THREAD

**Issue by relferreira** [unocss/unocss#2572]
### UnoCSS version

0.51.8

### Describe the bug

I'm migrating my project from Tailwind, and I saw a strange behavior with `border-[...]`.  Uno is picking `border-color,` but it should be `border-width` based on Tailwind's doc.

Reproduction: https://unocss.dev/interactive/?s=border-[6px]
Tailwind Docs: https://tailwindcss.com/docs/border-width#arbitrary-values

Is this the expected behavior?

Thanks in advance.

### Reproduction

https://unocss.dev/interactive/?s=border-[6px]

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by cesswhite** [comment]
Hi, I have a issue similar with border-


example normal class:
_//Dont work_
```
<div class="border-2 border-green-500">
 </div>
```
example custom color class:
_//Dont work_
```
<div class="border-2 border-brand-green">
 </div>
```

`_unocss.config.ts_`
```
import { defineConfig, presetUno, presetAttributify } from 'unocss'

export default defineConfig({
    theme: {
        colors: {
            'brand': {
                'green': '#036631',
                'yellow': '#D9E021',
                'gray': '#4D4D4D'
            }
        }
    },
    presets: [
        presetAttributify(),
        presetUno()
    ]
})
```

_`main.ts`_
`import 'vritual:uno.css'`

**Comment by henrikvilhelmberglund** [comment]
This is still broken when using `calc` for example `border-[calc(var(--border-width)*1px)]`.

**Comment by zyyv** [comment]
> This is still broken when using `calc` for example `border-[calc(var(--border-width)*1px)]`.

`border-[xxx]` gives priority to colors. As a workaround, you can use `border-width-[xxx]`   
https://unocss.dev/interactive/?s=border-width-[calc(1px%2B2px)]
