### ISSUE TITLE
children selector doesn't work in playground

### ISSUE THREAD

**Issue by UltraCakeBakery** [unocss/unocss#2575]
### UnoCSS version

0.51.8

### Describe the bug

Using the `hover:children` selector in the playground does not work.

### Reproduction

https://unocss.dev/play/?html=DwOwhgbgUABDDGAbMBnFBeARABwLQGYEALAS0QBMAnAUxAC4AKPQgF2oA8XcAmdxAShhEA9hGqU68UhRr0GAIwDmubAFdK2RNRhtOuFAFtBYeCxJjJ0qrUZLc8xKur9MUAHywYwcuYTI0WCJiEnY05LgArAAMUZhuAILAAPQ%2BEB5w3r5IqBiYcQBCyanpXql%2BOVhxAMJF5h7J4GlQQA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcEWWwCGuOlmggMUAGrr2mmAHEoELmDVRN23foAiwWhN4A3erfs6oeqCJwYAAbQhD1OhkqEQUAdQwOADFiGDokAF84LEsQOAByLhUJKPykJAwAD0hYdGx1LhD4TBx8IhJgUgAKZABIft7YxjoALjgAbSQB-qGlFS6p6d6%2Bpd60YwBrMfy9NGB1MtWMxYGASkol2YTk1Lou85OZ%2BXEpLXvHgF0LgY0tPwDRhNHr1fg5-PojCZcOZLNZ7t8fnY-o4oC43J56PDgaD-vogmBQuFIndTp9MqSgA&css=Q&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g

### System Info

I'm using the latest stable version of Microsoft Edge.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by lq-c** [comment]
How to change the variants sort? like `children:hover`

**Comment by UltraCakeBakery** [comment]
That doesn't generate the same selector locally. I wanted to create an issue (feature request) about the expected order.
