### ISSUE TITLE
Config mode to `shadow-dom` and include `@unocss-placeholder` magic placeholder only output preflights css and no other written css

### ISSUE THREAD

**Issue by JianJroh** [unocss/unocss#2579]
### UnoCSS version

0.51.12

### Describe the bug

In console log  `@unocss-placeholder` only include ` /* layer: preflights */ ....`  without  other written class

### Reproduction

https://stackblitz.com/edit/vitejs-vite-nabuxt?file=src/main.tsx

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by JianJroh** [comment]
> `To inline the generated css, you only need to configure the plugin mode to shadow-dom and include @unocss-placeholder magic placeholder on each web component style css block. `
> 
> [Refer the shadow-dom documentation](https://unocss.dev/integrations/vite#shadow-dom)

Yes I have configured mode 'shadow-dom' and use `@unocss-placeholder` magic placeholder. Can help me see the difference between my [reproduction ](https://stackblitz.com/edit/vitejs-vite-nabuxt?file=src/main.tsx)and the document description?

**Comment by Dunqing** [comment]
Notice: include @unocss-placeholder magic placeholder on **each** web component style css block

So, you need to use `@unocss-placeholder` on `App.tsx' to make it work.

**Comment by JianJroh** [comment]
> Notice: include @unocss-placeholder magic placeholder on **each** web component style css block注意：在每个 Web 组件样式 css 块上包括@unocss占位符魔术占位符
> 
> So, you need to use `@unocss-placeholder` on `App.tsx' to make it work.因此，您需要在“App.tsx”上使用 `@unocss-placeholder` 才能使其正常工作。

Is sth wrong?
![image](https://github.com/unocss/unocss/assets/45714701/169c181e-60c4-41a7-9043-44354ace062c)

**Comment by hood** [comment]
Any news on this?

**Comment by kishansripada** [comment]
it seems we need to add @unocss-placeholder to every single react component, despite these react components not being individual web components? any way to have it automatically search the entire shadow dom and inject all the styles into App.tsx?

**Comment by JianJroh** [comment]
> it seems we need to add @unocss-placeholder to every single react component, despite these react components not being individual web components? any way to have it automatically search the entire shadow dom and inject all the styles into App.tsx?看来我们需要将 @unocss-placeholder 添加到每个单独的 React 组件中，尽管这些 React 组件不是单独的 Web 组件？有什么办法让它自动搜索整个 Shadow dom 并将所有样式注入 App.tsx 吗？

Waiting for ```import unocssText from 'virtual:uno.css?inline'```  https://github.com/unocss/unocss/pull/2570

**Comment by ivancuric** [comment]
There is a problem with rendering inline CSS from unoCSS

https://stackblitz.com/edit/unocss-unocss-r5bbsa?file=package.json,src%2FApp.tsx,vite.config.ts,src%2Findex.tsx

The logo here should have a green background. `[&>div]:bg-green-500` should compile to:
```css
/* layer: default */
.\[\&\>div\]\:bg-green-500 > div {
  --un-bg-opacity: 1;
  background-color: rgb(34 197 94 / var(--un-bg-opacity)) /* #22c55e */;
}
```

However, when rendering in a `<style>` tag, it gets escaped to:
```css
.\[\&amp;\>div\]\:bg-green-500>div{--un-bg-opacity:1;background-color:rgb(34 197 94 / var(--un-bg-opacity)) /* #22c55e */;}
```

**Comment by hieunhit** [comment]
same issue, when using compile class no shortcuts are generated.
