### ISSUE TITLE
`transformer-variant-group` doesn't work with `<`, `~` breakpoint aliases

### ISSUE THREAD

**Issue by enkot** [unocss/unocss#2582]
### UnoCSS version

0.51.12

### Describe the bug

1. Enable `transformer-variant-group`
2. Add `<xl` variant group 
```html
<div class="<xl:(bg-green-500 text-black)" />
```
3. 
Expected result:
```html
<div class="<xl:bg-green-500 <xl:text-black" />
```
Actual result:
```html
<div class="<xl:bg-green-500 xl:text-black" />
```
`transformer-variant-group` transforms only first utility in the group

### Reproduction

https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCJgA84C4AUARgOYC0xATgKZUB2pArAAxNQAuVWbphiMA1gEp0APgBQUKAHt6IKgFsEtEFADtUMLSRslbNVABmAVzhwAnrCPap8sAC8EvKmOAB6cBHFA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQokscMUAIZZW6aCFRQAaoKjBhMAOJV6YClRq0AAoxbsA9AOGjxkgLQA3WfKwwzRFWC6dUAD17w06QfQA2njGw8AmIACgROOH4hETEoCShWAC44AG1IqOjjOISZOQVlCFVQgEoMgF1OUjKgA&css=Q&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
https://github.com/unocss/unocss/pull/2583#issuecomment-1537692333

**Comment by enkot** [comment]
@zyyv Why have you closed this? Based on the changelog, aliases are supported in Uno - https://github.com/unocss/unocss/releases/tag/v0.50.2.
