### ISSUE TITLE
webpack plugin fails to resolve uno.css

### ISSUE THREAD

**Issue by cdaringe** [unocss/unocss#2584]
### UnoCSS version

0.51.12

### Describe the bug

# Problem

webpack fails to resolve `uno.css` when integrated into `next.js` webpack instance:

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/1003261/236703057-0fac9080-4851-48df-b398-87217acba26f.png">

```json5
// webpacks resolver content for uno.css import
{
  "context": {},
  "path": "/Users/cdaringe/src/clarity/apps/ui/src/app",
  "request": "uno.css"
}
```

```tsx
// src/app/layout.tsx
import "@unocss/reset/tailwind.css";
import "uno.css";
```

```json
{
  "context": {},
  "path": "/Users/cdaringe/src/clarity/apps/ui/src/app",
  "request": "/Users/cdaringe/src/clarity/apps/ui/_virtual_%2F__uno.css"
}
```

# Discussion

- next.js registers the UnoCSS plugin, as instructed:

```js
const UnoCSS = require("unocss/webpack").default;
/**
 * @warn instructions say to install unocss, but then consume `@unocss/webpack`.
 * unocss/webpack is just a proxy into @unocss/webpack. the later import doesn't
 * work with pnpm due to excellence in hygienic imports, presuming one doesn't install @unocss/webpack as well
 */

const nextConfig = {
  reactStrictMode: true,
  webpack: (config) => {
    config.cache = false; // https://github.com/unocss/unocss/pull/1198
    config.plugins.push(UnoCSS());
    return config;
  },
};
```

Output from shell:

```txt
- wait compiling /_error (client and server)...
- error ./
Module not found: Can't resolve '/Users/cdaringe/src/clarity/apps/ui/_virtual_%2F__uno.css'
```

### Reproduction

https://github.com/cdaringe/clarity/

- git clone <url>
- `git checkout -b feat/tiny-unodemo`
- `cd apps/ui`
- `pnpm install`
- `pnpm dev`

Observe error

### System Info

next.js@13.4.1

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by clyan** [comment]
try:

    ```
  // 为了使用UnoCSS，删除ModuleScopePlugin
      const scopePluginIndex = config?.plugins?.findIndex(
        ({ constructor }) => constructor && constructor.name === 'ModuleScopePlugin'
      );
      if(scopePluginIndex !== undefined && scopePluginIndex > - 1) {
        config?.plugins?.splice(scopePluginIndex, 1);
      }
```

**Comment by clyan** [comment]
try:
`
      const scopePluginIndex = config?.plugins?.findIndex(
        ({ constructor }) => constructor && constructor.name === 'ModuleScopePlugin'
      );
      if(scopePluginIndex !== undefined && scopePluginIndex > - 1) {
        config?.plugins?.splice(scopePluginIndex, 1);
      }
`

**Comment by clyan** [comment]
I got the same error as yours when I used create-react-app.

You can try:

```
      // delete ModuleScopePlugin
      const scopePluginIndex = resolve?.plugins?.findIndex(
        ({ constructor }) => constructor && constructor.name === 'ModuleScopePlugin'
      );
      if(scopePluginIndex !== undefined && scopePluginIndex > - 1) {
        resolve?.plugins?.splice(scopePluginIndex, 1);
      }

```

**Comment by Deerhound579** [comment]
Having the same issue. This workaround works perfectly: https://thundermiracle.com/blog/en/2022-06-07-next-with-unocss/

**Comment by Lstoryc** [comment]
any news here, I have same problem

**Comment by quangkhaidam93** [comment]
I have same issue with CRA (config webpack with craco) setup. Is there any update? Thank in advance.

**Comment by TenviLi** [comment]
any news here, I have same problem

![](https://github.com/unocss/unocss/assets/30214981/1effbd73-c478-4628-8ab2-5bbef5421143)

**Comment by tangkai123456** [comment]
I resolved this problem by setting 'config.snapshot.immutablePaths = [/uno\./];'

**Comment by elarbor** [comment]
我是这样的：
![image](https://github.com/user-attachments/assets/975d0650-322b-424d-a273-1c9fd9e93f1b)
