### ISSUE TITLE
TS2322: Type 'Preset<{}>' is not assignable to type 'Preset<Theme> | Preset<Theme>[]'.

### ISSUE THREAD

**Issue by changyuqing** [unocss/unocss#2587]
### UnoCSS version

0.51.12

### Describe the bug

When i use the preset `@unocss/preset-rem-to-px` ,it report the error TS2322: Type 'Preset<{}>' is not assignable to type 'Preset<Theme> | Preset<Theme>[]'.

error log detail
```text
TS2322: Type 'Preset<{}>' is not assignable to type 'Preset<Theme> | Preset<Theme>[]'.   Type 'Preset<{}>' is not assignable to type 'Preset<Theme>'.     Types of property 'rules' are incompatible.       Type 'Rule<{}>[] | undefined' is not assignable to type 'Rule<Theme>[] | undefined'.         Type 'Rule<{}>[]' is not assignable to type 'Rule<Theme>[]'.           Type 'Rule<{}>' is not assignable to type 'Rule<Theme>'.             Type '[RegExp, DynamicMatcher<{}>]' is not assignable to type 'Rule<Theme>'.               Type '[RegExp, DynamicMatcher<{}>]' is not assignable to type '[string, CSSObject | CSSEntries]'.                 Type at position 0 in source is not compatible with type at position 0 in target.                   Type 'RegExp' is not assignable to type 'string'.
```

### Reproduction

// uno.config.ts

```typescript
import {
    defineConfig,
    presetUno,
} from 'unocss';
import presetRemToPx from '@unocss/preset-rem-to-px';

export default defineConfig({
    presets: [
        presetUno(),
        presetRemToPx({
            baseFontSize: 4,
        }),
    ],
})
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Dunqing** [comment]
It looks like you need to upgrade both `unocss` and `@unocss/preset-rem-to-px` to the latest version.

**Comment by darylteo** [comment]
If having similar issue - check if your import is correct.

IntelliJ accidentally imported this

```
import presetUno from '@unocss/preset-uno'
```

Instead of 

```
import {defineConfig, presetUno} from 'unocss'
```
