### ISSUE TITLE
Support DEFAULT for theme colors

### ISSUE THREAD

**Issue by Shinigami92** [unocss/unocss#2588]
### Clear and concise description of the problem

I'm configuring the preset for my company

```ts
function presetCompany(options: PresetCompanyOptions = {}): Preset<Theme> {
  const uno = presetUno(options);
  return {
    ...uno,
    name: "@company/preset-company",
    theme: {
      ...uno.theme,
      colors: {
        ...uno.theme?.colors,
        primary: {
          50: "#......",
          100: "#......",
          200: "#......",
          300: "#......",
          400: "#......",
          500: "#......",
          600: "#......",
          700: "#......",
          800: "#......",
          900: "#......",
          950: "#......",
          DEFAULT: "#......",
        },
      },
    },
  } as Preset<Theme>;
}
```

However, as we can see, I need to configure a DEFAULT like e.g. possible in TailwindCSS: https://tailwindcss.com/docs/customizing-colors#color-object-syntax

This does not seem to work 🙁 
It always takes the `...-500` as default

How can I change the default so `text-primary === text-primary-700`?

### Suggested solution

support `DEFAULT` like TailwindCSS

### Alternative

Document how it is possible

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://uno.antfu.me).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Dunqing** [comment]
`unocss` already support `DEFAULT`. You can see https://github.com/Dunqing/unocss/blob/main/packages/preset-mini/src/_theme/colors.ts#L360-L371

**Comment by Shinigami92** [comment]
> `unocss` already support `DEFAULT`. You can see [Dunqing/unocss@`main`/packages/preset-mini/src/_theme/colors.ts#L360-L371](https://github.com/Dunqing/unocss/blob/main/packages/preset-mini/src/_theme/colors.ts?rgh-link-date=2023-05-08T12%3A48%3A40Z#L360-L371)

That workes!

Thx, but is there a way so that I don't need to manually copy this

```ts
// assign default color, and color shortcuts
Object.values(colors).forEach((color) => {
  if (typeof color !== "string") {
    color.DEFAULT = color.DEFAULT || color[400];
    Object.keys(color).forEach((key) => {
      const short = +key / 100;
      if (short === Math.round(short)) color[short] = color[key];
    });
  }
});
```

I would have expected that UnoCSS can do this out of the box

**Comment by Dunqing** [comment]
> I would have expected that UnoCSS can do this out of the box.
> 
> Maybe docs and an exported utility function would be nice.

I just wanted to tell you that `unocss` supports `DEFAULT`.

Your usage is correct, if not then there should be an bug

**Comment by Shinigami92** [comment]
> I just wanted to tell you that `unocss` supports `DEFAULT`.
> 
> Your usage is correct, if not then there should be an bug

Strange... now I tested it again and it works...
So maybe I did a typo or something
I did not updated the dep yet so I tested with `0.51.8`

But still, then the docs should be updated to explain that it is possible, because I just assumed from the TailwindCSS docs that this might be the way

**Comment by lyneal** [comment]
Hello,

I have the same problem but concerning the "borderColor" in theme. I can't change the color of the border by default.
