### ISSUE TITLE
Watchers in vite-plugin

### ISSUE THREAD

**Issue by lmexo** [unocss/unocss#2590]
### Clear and concise description of the problem

On a Laravel + Inertia/Vue project I am using unocss with vite, which works awesome.

But for some pages I still need to create views in blade.php without vue. Since it is not served through vite, in this scenario unocss does not extract classes from the blade.php-files, thus I cannot style these pages (or at least not without explicitly stopping the vite server and booting the unocss cli instead).

So I wonder if it is possible to add some kind of "safe includes" (similar to the safelist), which watches files and extracts classes using the same config as it is used for assets served by vite devserver otherwise?

### Suggested solution

Add a config flag, similar to `safelist`, accepting a file list (e.g. glob/regex). These files are watched and classes are extracted on startup and on file change.

I hope you are willing to consider this :) Although, I understand that it is kind of against the concept of the "on-demand"-part of unocss.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://uno.antfu.me).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by schelmo** [comment]
use `extraContent` on the unocss vite plugin
```ts
export default defineConfig(() => ({
  plugins: [
    UnoCSS({                                                                                      
      extraContent: {                                                                             
        filesystem: ['resources/views/**/*.blade.php'],                                                                                        
      },                                                                                          
    }),
  ],
})

**Comment by lmexo** [comment]
I did not even recognize, that there is a different config in the vite plugin than in the unocss.config.ts. It does make sense, though.

But the docs keep that confidential ;) There is no (comprehensive) information about the vite-plugin configuration, just about the mode.

Anyways: Thanks for pointing out @schelmo

**Comment by lmexo** [comment]
Appearently I could also have configured it in unocss.config.ts, but did not see it, since the docs are silent about that
