### ISSUE TITLE
[vscode] no unocss config found in monorepo

### ISSUE THREAD

**Issue by jsonleex** [unocss/unocss#2596]
### UnoCSS version

v0.51.12

### Describe the bug

UnoCSS for VS Code does not work in Monorepo.

<img width="1114" alt="iShot_2023-05-09_22 10 15" src="https://github.com/unocss/unocss/assets/25883665/e4842219-c38f-45e6-909b-5d4c99e67b6f">

### Reproduction

https://github.com/jsonleex/unocss-ext-issue

### System Info

```txt
macOS Ventura 13.31

Visual Studio Code
Version: 1.78.0
Commit: 252e5463d60e63238250799aef7375787f68b4ee
Date: 2023-05-03T20:11:00.813Z (5 days ago)
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 13_3_1) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.78.0 Chrome/108.0.5359.215 Electron/22.4.8 Safari/537.36
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by achinchen** [comment]
I think the issue is related below, and you might give it a try  (:
https://github.com/unocss/unocss/issues/1764

**Comment by jsonleex** [comment]
My bad, It already supports multiple configure in #2101

It works great now for me.

UnoCSS is awesome, thank your contribution!

<img width="1072" alt="iShot_2023-05-10_12 16 03" src="https://github.com/unocss/unocss/assets/25883665/93c2ff65-1fe3-4853-8d16-1bfe90b93711">
