### ISSUE TITLE
Transformer directives not working in styled-jsx

### ISSUE THREAD

**Issue by Alexnortung** [unocss/unocss#2606]
### UnoCSS version

0.51.12

### Describe the bug

Using `@apply` and `@screen` with styled-jsx does not seem to work. We are transitioning from windicss and it worked there.

### Reproduction

https://github.com/Oak-Digital/unocss-directives-bug

in `pages/index.tsx` I am using an `@apply` rule, but it doesn't work

### System Info

system: NixOS 22.11
browser: Firefox
framework: Next.js

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
Transformer depends on the vite environment.

**Comment by Alexnortung** [comment]
It seems that `transformer-directives` works for scss files for my next app and that `transformer-variant-groups` work fine. I would expect `transformer-directives` to also work with styled-jsx.

I don't understand why transformers should not work for other environments?

**Comment by zyyv** [comment]
Sorry, made a wrong guide, I'll take a look at the issue later.

**Comment by Shyam-Chen** [comment]
Would you like to try using `styled-jsx-plugin-postcss`? It can be combined with `@unocss/postcss`. If you want to use Sass syntax, you can also include `@csstools/postcss-sass`.
