### ISSUE TITLE
Nuxt HMR not working with custom preset imports

### ISSUE THREAD

**Issue by Phojie** [unocss/unocss#2613]
### UnoCSS version

0.51.12

### Describe the bug

Nuxt HMR is not working on the [Custom preset docs](https://unocss.dev/guide/#presets) imports

This is Similar problem to #2384

### Reproduction

`my-preset.ts`

```ts
import { Preset } from 'unocss'

export const myPreset: Preset = {
  name: 'my-preset',
  shortcuts: {
      'btn': 'py-4 px-4 font-semibold rounded-lg shadow-md', 
  },
}
```

`uno.config.ts`

```ts
// uno.config.ts
import { defineConfig } from 'unocss'
import { myPreset } from './my-preset'

export default defineConfig({
  presets: [
    myPreset ,// your own preset
    {
       name: 'my-preset',
       shortcuts: {
      'btn': 'py-4 px-4 font-semibold rounded-lg shadow-md', 
    },
  }
 ],
})
```

- HMR not working when change happens in `my-preset.ts` 🐞 

- HMR works when change happens in `uno.config.ts` (without using imports) 

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
By default, it can only detect changes to the config file. You can manually set https://github.com/antfu/unocss/blob/2320bad0d651e7752afd34345e523325742f1c58/packages/core/src/types.ts#L664-L667 to enable HMR for your own files.

**Comment by Phojie** [comment]
thanks man @antfu  gonna check that out

**Comment by bennymi** [comment]
@antfu is there a way to dynamically pass all `.js` files to the `configDeps` argument?

Something like: `./src/preset/**/*.js`?

**Comment by jacob-8** [comment]
> is there a way to dynamically pass all `.js` files inside a folder to the `configDeps` argument?

@bennymi something like this should work: 

```js
export default defineConfig({
	plugins: [
		sveltekit(),
		UnoCSS({
			configFile: './unocss.config.js',
			configDeps: getAllConfigFiles('./src/presets')
		})
	]
});

function getAllConfigFiles(dir) {
	const files = fs.readdirSync(dir);
	return files.filter((file) => path.extname(file) === '.js').map((file) => path.join(dir, file));
}
```

Try it out at: https://stackblitz.com/edit/sveltejs-kit-template-default-zdhkpg?file=vite.config.js

**Comment by bennymi** [comment]
@jacob-8 awesome, that works great! Thank you :)

**Comment by Tzyito** [comment]
This solution only works in development mode. When I need to rely on the packaged dist file, the configuration does not seem to take effect.

**Comment by jacob-8** [comment]
> This solution only works in development mode. When I need to rely on the packaged dist file, the configuration does not seem to take effect.

@Tzyito can you please clarify a bit. This solution is relating to HMR issues, not build. Are you saying that this HMR dev solution breaks the build? If so, please add a minimal repro. If you problem is something, else please explain further (and still add a minimal repro)

**Comment by Tzyito** [comment]
> @Tzyito can you please clarify a bit. This solution is relating to HMR issues, not build. Are you saying that this HMR dev solution breaks the build? If so, please add a minimal repro. If you problem is something, else please explain further (and still add a minimal repro)

@jacob-8 hi, Maybe I didn't express it very clearly. If possible, you can check the playground in my [project](https://github.com/Tzyito/pixel-ui).
when I change [`packages/preset/shortcuts/button.ts`](https://github.com/Tzyito/pixel-ui/blob/main/packages/preset/shortcuts/button.ts#L4C1-L4C1),

**Comment by Tzyito** [comment]
@Tzyito can you please clarify a bit. This solution is relating to HMR issues, not build. Are you saying that this HMR dev solution breaks the build? If so, please add a minimal repro. If you problem is something, else please explain further (and still add a minimal repro)

@jacob-8 hi, Maybe I didn't express it very clearly. If possible, you can check the playground in my [project](https://github.com/Tzyito/pixel-ui).
when I editor [packages/preset/shortcuts/button.ts](https://github.com/Tzyito/pixel-ui/blob/main/packages/preset/shortcuts/button.ts#L4C1-L4C1), the `packages/components/uno.config.ts` This file cannot be monitored. Is this related to HMR, or is this caused by the build?

**Comment by jacob-8** [comment]
> By default, it can only detect changes to the config file. You can manually set https://github.com/antfu/unocss/blob/2320bad0d651e7752afd34345e523325742f1c58/packages/core/src/types.ts#L664-L667 to enable HMR for your own files.

As mentioned earlier you must specifically tell Uno which files you want it to watch. For your project, I believe this would be the way to do it:

```ts
// packages/components/vite.config.ts
export default defineConfig({
  plugins: [
    vue(),
    UnoCSS({
      configFile: './unocss.config.ts',
      configDeps: getAllConfigFiles('../preset') // or use '../preset/dist' and change the below from '.ts' to '.js'
    })
  ]
});

function getAllConfigFiles(dir) {
  const files = fs.readdirSync(dir);
  return files.filter((file) => path.extname(file) === '.ts').map((file) => path.join(dir, file));
}
```

I hope that is what you are asking?

**Comment by Tzyito** [comment]
> ```ts
> // packages/components/vite.config.ts
> export default defineConfig({
>   plugins: [
>     vue(),
>     UnoCSS({
>       configFile: './unocss.config.ts',
>       configDeps: getAllConfigFiles('../preset') // or use '../preset/dist' and change the below from '.ts' to '.js'
>     })
>   ]
> });
> 
> function getAllConfigFiles(dir) {
>   const files = fs.readdirSync(dir);
>   return files.filter((file) => path.extname(file) === '.ts').map((file) => path.join(dir, file));
> }
> ```
thanks for your introduction. As you can see, I added the preset folder in `uno.config.ts` but not work

**Comment by Tzyito** [comment]
> > ```ts
> > // packages/components/vite.config.ts
> > export default defineConfig({
> >   plugins: [
> >     vue(),
> >     UnoCSS({
> >       configFile: './unocss.config.ts',
> >       configDeps: getAllConfigFiles('../preset') // or use '../preset/dist' and change the below from '.ts' to '.js'
> >     })
> >   ]
> > });
> > 
> > function getAllConfigFiles(dir) {
> >   const files = fs.readdirSync(dir);
> >   return files.filter((file) => path.extname(file) === '.ts').map((file) => path.join(dir, file));
> > }
> > ```
> 
> Thanks for your reply. As you can see, I added the preset folder in `uno.config.ts` but not work

**Comment by jacob-8** [comment]
> As you can see, I added the preset folder in `uno.config.ts` but not work

That's correct. Only the config file, but not its imports are being watched.
