### ISSUE TITLE
Add supports for `word-break: break-word` / `overflow-wrap: anywhere`

### ISSUE THREAD

**Issue by serkodev** [unocss/unocss#2614]
### Clear and concise description of the problem

Before we start, according to MDN's  [`word-break`](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break#syntax) introduction:
- `word-break: break-word` is deprecated
- `word-break: break-word` =  `word-break: normal` + `overflow-wrap: anywhere`

The problem is UnoCSS only provides the `break-words` class (corresponding to CSS `overflow-wrap: break-word;`) and does not support `word-break: break-word` / `overflow-wrap: anywhere`.

The [`overflow-wrap`](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap) documentation mentions that the `break-word` and `anywhere` values are almost identical, but there are still some differences.

- `anywhere`
Soft wrap opportunities introduced by the word break are considered when calculating min-content intrinsic sizes.

- `break-word`
... soft wrap opportunities introduced by the word break are `NOT` considered when calculating min-content intrinsic sizes.

### Research
Although I have not delved into the underlying principles in practice, I have done a code test to demonstrate the differences between different values in use:
![Capture](https://github.com/unocss/unocss/assets/44749100/a2b23e56-3ea9-44e9-9dd8-f033e16a66e8)
Source code：[UnoCSS Playground](https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIC2BPAtAJigAdcBGKAIwHNcAnAUxCkwQA9cB3XAVgAZeirKFVpgmIsbhgB7OElwBtfH0EB9BAFcALtIC6lBggDWnabRBJ0APgBQUKKEhXpEerQBmcaVw60ERAC4DemNTcwBuYApaKAB6K2AkIgQAO1hEFAxpEj5rVCh0aJCTDjMLdHTkJGBYpNSE2PAIW3tHaHgqjGpcCjgNemsvaWGR0bHxicmqKAALejgvKFLaOCYU6RSi4wRe+mWQGqbbQ6cbGzbKzKw8QhJyboYmFnYuPgEhCXFREClZeSUVKx1No9MFQggFtY7A4jvseoYjEEtiYIXBItE4gk6mkOldsjxeHkCsjcKiKrjqrVkikGkdoRcKV0aL1+oNJuyORzpnMFtIlmZVlB1psETs4HsyidmudGqdzk1LmhrgRiGRKDQRPR6GlnpwCe9hN9DZIZHJFMp3sCdLoKkgtNhxVlXB4vD4-IEoKlsBw5gxwlDWkcXG5PN5OO6gl6fW56JFZdLA5BFUyen0BlYhpys1nufNFstBcLkWKJeYpcd47Z5UnGcrbmruprtcw2Hq3oJjV8TX9zYCrXpbfbHeg4cikQiwiB-S0YU5Rwjx8VJ3G6Yn2hkld0WenM9m9xNc7z+Ss1hti7t9uWZXSgA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUkNikEA&css=Q&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g)

As you can see in the example above, neither `break-words` nor `break-all` can fully serve as replacements.

### Suggested solution

Current browser support situation:
- Although `word-break: break-word` is deprecated, it can still be used in the latest version of Chrome
- Currently, [caniuse](https://caniuse.com/mdn-css_properties_overflow-wrap_anywhere) for `overflow-wrap: anywhere;` is only at 91.87%, with support in iOS 15.4 and above

Given the above situation, I propose the following solution and fallback methods and hope for feedback from everyone.
```css
.break-anywhere {
  word-break: break-word;
}

@supports (overflow-wrap: anywhere) {
  .break-anywhere {
    overflow-wrap: anywhere;
    word-break: normal;
  }
}
```

Naming reason (`break-anywhere`):
-   Using `break-` as a prefix to easily categorize it with other similar word break classes
-   Using `anywhere` as a suffix because I do not want to confuse it with `break-words`, and `overflow-wrap: anywhere;` is the replacement for `word-break: break-word;`.

### Alternative
For those who looking for UnoCSS class version (able to add to `shortcuts`).
```
[word-break:break-word]
[@supports(overflow-wrap:anywhere)]:[overflow-wrap:anywhere]
[@supports(overflow-wrap:anywhere)]:[word-break:normal]
```

### Additional context

Similar issue: https://github.com/unocss/unocss/issues/96#issuecomment-965441993

I have also seen similar discussions in other communities, but there seems to be no solution yet.
https://github.com/tailwindlabs/tailwindcss/issues/835#issuecomment-1490251144

Finally, I understand that UnoCSS is just an engine, so I'm not sure whether addressing this issue should be done through the default preset or by allowing developers to add their own rules or CSS classes as needed. I'd appreciate hearing everyone's thoughts on this matter.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://uno.antfu.me).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
In general of the engine part, I think it makes sense to have the compatibility of rendering `@supports` tag to make it easier.

As for the CSS rule itself, I also think it would make sense to support it in our preset. Maybe we could wait for Tailwind to avoid introducing misalignment early.

**Comment by serkodev** [comment]
Cool, let me share this research with Tailwind first, and see if they will adopt it.

**Comment by serkodev** [comment]
https://github.com/tailwindlabs/tailwindcss/discussions/12127 Created a related research and discussion for this issue.

**Comment by antfu** [comment]
#2740 should include this
