### ISSUE TITLE
TypeScript import error in Astro integration with moduleResolution `node16` or `nodenext`

### ISSUE THREAD

**Issue by shishkin** [unocss/unocss#2617]
### UnoCSS version

0.51.12

### Describe the bug

Getting TypeScript import error in `astro.config.ts` file when importing UnoCSS integration:

```
This expression is not callable.
  Type 'typeof import("stackblitz:/node_modules/unocss/dist/astro")' has no call signatures.(2349)
```

Despite the error, vite still works and the app starts normally. The issue is only during explicit `tsc` build. This only happens with TypeScript setting `moduleResolution: "node16"` (or `nodenext`).

I noticed that UnoCSS exports Astro integration like `export { UnocssAstroIntegration as default };` when other integration that work with `node16` module resolution seem to export just a default function, e.g. `export default function mdx(partialMdxOptions?: Partial<MdxOptions>): AstroIntegration;`.

### Reproduction

https://stackblitz.com/edit/github-mrekxn?file=astro.config.ts

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by unbiased-dev** [comment]
Same thing happens in sveltekit which also uses nodenext.
