### ISSUE TITLE
Style Declarations in index.html incorrectly output by UnoCSS

### ISSUE THREAD

**Issue by austin-meadows** [unocss/unocss#2623]
### UnoCSS version

0.51.12

### Describe the bug

Normal CSS styles that happen to match the name of a UnoCSS class in a <style> tag within `index.html` are picked up during build and output.

For instance, suppose you have the following in your `index.html`:
```html
...
<style type="text/css">
picture, img {
  display: block;
}

h1 {
 color: red;
}
</style>
...
```
"`block`" and "`h1`" will be picked up by Uno and output in the CSS.
```css
/* build.css */
.block {
  display: block
}
.h1 {
  height: (something)rem
}
```

I believe this is unintentional.

### Reproduction

https://stackblitz.com/edit/unocss-replication-3ufdv?file=dist/assets/index-8db382a6.css&view=editor

### System Info

UnoCSS 0.51.12, Node >= 16, Vite 4.3.5

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
https://unocss.dev/guide/extracting
You can add `@unocss-ignore` tag try again.

**Comment by austin-meadows** [comment]
Good catch, I'll give that a try, thanks! 😄
