### ISSUE TITLE
Classes Not Building w/ Astro Template Syntax

### ISSUE THREAD

**Issue by arimgibson** [unocss/unocss#2639]
### UnoCSS version

0.54.1

### Describe the bug

When using Astro's template syntax, it doesn't appear that ~arbitrary~ classes render properly:

```astro
---
const navItems = [
  {
    label: "About",
    color: "#F1FA43",
  },
  {
    label: "Portfolio",
    color: "#FF7DB8",
  },
  {
    label: "Services",
    color: "#3DBFAF",
  },
  {
    label: "Contact",
    color: "#EC291C",
  },
];
---

<ul
  class="flex justify-between gap-8 md:text-[2.3vw] lg:text-2xl font-base font-bold uppercase"
>
  {
    navItems.map((item) => (
      <li>
        <a
          class={`text-black transition hover:bg-[${item.color}] p-1`}
          href={"/" + item.label.toLowerCase()}
        >
          {item.label}
        </a>
      </li>
    ))
  }
</ul>
```

The classes render as expected (i.e. `hover:bg-[#F1FA43]`) but these styles are missing in the CSS generated by UnoCSS. Before when I was hardcoded these items and their colors, the proper CSS was generated.

### Reproduction

https://stackblitz.com/edit/withastro-astro-ztzzgc?file=src%2Fpages%2Findex.astro

### System Info

Framework: Astro v2.10.1

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by arimgibson** [comment]
Updated title; this issue isn't only for arbitrary values. Appears to be anytime Astro generates the classes dynamically

**Comment by smastrom** [comment]
Hi, I'm facing the same issue. Haven't noticed it earlier because it seems to happen only in such case:

```ts
export function getBorderClasses() {
  return Math.random() > 0.5
    ? 'border-solid border-2 border-blue'
    : 'border-solid border-2 border-green';
}
```

```astro
---
import { getBorderClasses } from "../utils"

const colorClass = "text-red" // Works
const weightClasses = Math.random() > 0.5 ? 'font-bold' : 'font-extrabold' // Works

function getSizeClasses() {
  return Math.random() > 0.5 ? 'text-2xl' : 'text-xl';
} // Works


// Doesn't work
const borderClasses = getBorderClasses()
---
	
<div class={`m-20 ${colorClass} ${weightClasses} ${getSizeClasses()} ${borderClasses}`}>Ciao</div>
```

Classes are appended to the element but related utils are not generated.

![Screenshot 2023-05-20 alle 11 17 31](https://github.com/unocss/unocss/assets/60471784/0cb51251-f308-4eaf-87e6-87289ae6b369)

Haven't noticed it before because sometimes utils are already generated on other nodes. I have created a reproduction on Stackblitz:

https://stackblitz.com/edit/withastro-astro-hpbb1x?file=src%2Fpages%2Findex.astro

**Comment by arimgibson** [comment]
Not my smartest move to link a project that's being actively developed and changed as a my reproduction :facepalm: didn't think that through enough haha.

Forked @smastrom reproduction and updated the original post with a new link. Also has a `fix.astro` file which showcases some simple SCSS I wrote as a fix for my specific usage while this bug is being investigated :smile:

**Comment by arimgibson** [comment]
Issue still apparent on @smastrom's repo, wish I had time to check before this went stale.

@antfu would you mind reopening this issue?

**Comment by userquin** [comment]
@arimgibson you should add `// @unocss-include` hint (magic comment) to the `utils/index.ts` module

https://stackblitz.com/edit/withastro-astro-pdkz2d?file=src%2Futils%2Findex.ts

![imagen](https://github.com/unocss/unocss/assets/6311119/da0778a6-7446-416a-918d-5d4552d61c8c)

**Comment by arimgibson** [comment]
Mmm thanks for the suggestion @userquin ! That didn't do it for me (my repro linked in original post), but it sounds ilke that might solve @smastrom's issue. These are probably different issues then...

Bumped deps in my repro and updated Astro and UnoCSS versions in my original post to reflect this issue is still present with the latest releases.

**Comment by userquin** [comment]
Try adding `hover:bg-[#xxxx]` to the each color entry or add all `hover:bg-[]` variants to safelist:

https://unocss.dev/guide/extracting#safelist

**Comment by userquin** [comment]
@arimgibson from your original SB repro, using safelist:
https://stackblitz.com/edit/withastro-astro-okgoud?file=src%2Fpages%2Findex.astro

**Comment by arimgibson** [comment]
Oh awesome, that did it! Thanks for the help @userquin; I think I understand what's going on now. Instead of building the actual class name at runtime, UnoCSS has the full class name already and is able to add it to the bundle. Does that sound about right?

The safelist fix is great too, although I went with redefining the color variable to have the full class name.

**Comment by userquin** [comment]
> Does that sound about right?

Yes, that's right, check the link in the docs.
