### ISSUE TITLE
I think there should be a distinction between content-empty and content-none.

### ISSUE THREAD

**Issue by nguyentuevuong** [unocss/unocss#2645]
### UnoCSS version

0.51.13

### Describe the bug

With content-empty, we need the content to be an empty character, whereas with content-none, precisely, we need the none attribute of the content.

### Reproduction

https://github.com/unocss/unocss/blob/df6894e0b39e8f357679feb59417535009aba184/packages/preset-mini/src/_rules/static.ts#L87

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Yeah, to align with Tailwind, I think this should be changed to `content: none`. PR welcome :)
