### ISSUE TITLE
Can not use lodash-es in uno.config.js

### ISSUE THREAD

**Issue by gkn1234** [unocss/unocss#2651]
### UnoCSS version

v0.52.1

### Describe the bug

The npm package `lodash-es` can not work in `uno.config.ts`. 

There is no response when I execute `vite build`. 

In addition, the `unocss` vscode extension doesn't work and block the IDE process.

```ts
// uno.config.ts
import { mergeWith } from 'lodash-es';
import { defineConfig, presetUno } from 'unocss';

export default defineConfig(
  mergeWith(
    {
      presets: [presetUno()],
    },
    {}
  )
);
```

Guess the problem exist when using `type: 'module'` package.

Same problem： #1299 

### Reproduction

https://stackblitz.com/edit/vitejs-vite-kgzd7h?file=uno.config.ts

### System Info

  System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 2.86 GB / 31.78 GB
  Binaries:
    Node: 18.16.0 - D:\devAPP\nodejs\node.EXE
    Yarn: 1.22.18 - D:\devAPP\nodejs\yarn.CMD
    npm: 9.5.1 - D:\devAPP\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.50)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vite: ^4.3.5 => 4.3.5

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Upstream issue: https://github.com/unjs/jiti/pull/141
