### ISSUE TITLE
FOUC when editing classes when using svelte-scoped

### ISSUE THREAD

**Issue by henrikvilhelmberglund** [unocss/unocss#2658]
### UnoCSS version

0.52.3

### Describe the bug

It seems like there's FOUC now when editing classes. It happens with both vite plugin and preprocess configurations. Not sure if this is a bug or an expected thing with the rework.

### Reproduction

https://stackblitz.com/edit/unocss-unocss-aasaew?file=src%2Froutes%2F%2Bpage.svelte

In the p tag in +page.svelte change p-40 to p-44 and back, the images and stuff flash to the top before moving down again.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jacob-8** [comment]
> So that's a bug I can fix - this [code ](https://github.com/unocss/unocss/blob/main/packages/svelte-scoped/src/vite/passPreprocessToSveltePlugin.ts#L11-L17) is not setting combine to false in dev as I expected it would.

Fixed in #2685
