### ISSUE TITLE
prestWebFont not fully applying the font

### ISSUE THREAD

**Issue by Sandros94** [unocss/unocss#2659]
### UnoCSS version

0.51.13

### Describe the bug

While discussing an [issue on the Anu repo](https://github.com/jd-solanki/anu/issues/159) we came to the conclusion that the need to specify what fonts needed to be applied could be a UnoCSS related issue.

Even if I defined what fonts to use inside `presetWebFonts` I still have to add the following to my Nuxt `default.vue` layout:
```vue
<style>
body {
    @apply font-sans;
}
</style>
```

### Reproduction

Currently we have been following the issue in [this branch of a test repo](https://github.com/Sandros94/test-nuxt3app/tree/Sandros94/issue4).

### System Info

Nuxt v3.5

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Shyam-Chen** [comment]
Try `bodyAttrs.class` in `useHead`.

**Comment by zyyv** [comment]
I don't think there is any problem with this. The web-fonts preset just helps you provide font resources and inject them into the theme. As for usage, unocss will extract your token and generate font-family styles.

**Comment by jd-solanki** [comment]
@zyyv Should we add option to auto inject mentioned snippet in generated CSS so we don't have to do additional mentioned stuff? This will be convenient because everytime we use fonts preset we have to define the fonts for body.

What's your thoughts on this?
