### ISSUE TITLE
Custom class name isn't work with vite & vue-ts

### ISSUE THREAD

**Issue by nguyentuevuong** [unocss/unocss#2668]
### UnoCSS version

0.52.3

### Describe the bug

I try custom class name with vite and vue-ts, but it isn't work.
![image](https://github.com/unocss/unocss/assets/23444528/e277ff1c-46d2-48bf-80a8-190757a7f0d3)

### Reproduction

StackBlitz sample:
https://stackblitz.com/edit/vitejs-vite-tnvrpy?file=package.json

### System Info

Vite: 4.3.2
Vite/VuePlugin: 4.1.0
Vue: 3.2.47
Vue-tsc: 1.4.2
Typescript: 5.0.2

UnoCSS: 0.52.3

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by nguyentuevuong** [comment]
> You haven't configured `trigger`.
> 
> ```js
> trigger: /(["'`]):uno-foo:\s([^\1]*?)\1/g,
> ```

Yes, I realized that when reviewing the source code and found it unnecessary to have two triggers to handle two different options. And I have fixed it in PR: #2664. It may not be approved, but it is a good solution. You can refer to it.

**Comment by antfu** [comment]
Should be fixed with https://github.com/unocss/unocss/commit/c54f3ee8e1c745dfa5d4ed015e354ecd6eb5c171
