### ISSUE TITLE
When using className of preset-icon in React component props, cli unexpectedly exits

### ISSUE THREAD

**Issue by zjcrender** [unocss/unocss#2670]
### UnoCSS version

0.51.13

### Code
```ts
// test.tsx
import type { FC } from 'react';

type AnyProps = {
  [p: string]: any;
}

const SomeNode: FC<AnyProps> = () => null;

const Test: FC = () => {
  return (
    <SomeNode
      className="w-100px h-100px bg-red"
      icon={ <span className="i-icon:search"/> }
    />
  )
}

export default Test;
```

### config
```ts
// unocss.config.ts
import { defineConfig, presetUno, presetAttributify } from 'unocss';
import presetIcons from '@unocss/preset-icons';
import * as fs from "fs";

export default defineConfig({
  presets: [
    presetAttributify(), // working fine after remove this preset
    presetIcons({
      autoInstall: true,
      collections: {
        'icon': name => fs.readFileSync(`./src/images/icon/${name}.svg`, 'utf-8'),
      }
    }),
  ],
});

```

### command
`npx unocss "src/pages/test.tsx" --out-file ./uno.css --watch`

### Reproduction

https://stackblitz.com/edit/node-uuidvm?file=package.json,README.MD,test.tsx,unocss.config.ts

### System Info

OS: macOS 13.3.1 22E261 arm64
NodeJS：16.20.0
uno: 0.51.13

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zjcrender** [comment]
Hi, I found out what the problem was!

In the above case, in addition to the original `i-collection:filename`, `presetAttributify` generates an `i-collection:attrname-filename` rule.
Passing `attrname-filename` into `loader` will result in an error due to a file not being found, which will cause the cli to terminate.

Doing a proactive checksum can circumvent this problem.

```ts
presetIcons({
  autoInstall: true,
  collections: {
    icon: name => {
      const iconPath = `./src/images/icon/${name}.svg`;
      const exist = fs.existsSync(iconPath);
      if (!exist) return;

      return fs.readFileSync(iconPath, 'utf-8');
    },
  }
}),
```

**Comment by zyyv** [comment]
https://github.com/unocss/unocss/pull/2773#issuecomment-1596131511
