### ISSUE TITLE
In UnoCSS 0.52.3 the button style does not meet the expectations

### ISSUE THREAD

**Issue by lainbo** [unocss/unocss#2671]
### UnoCSS version

0.52.3

### Describe the bug

The styles that function properly in UnoCSS 0.52.2 do not behave as expected in 0.52.3. some styles are missing

### Reproduction

[View 0.52.2](https://codesandbox.io/p/sandbox/unocss-0-52-2-pl7wxg)

[View 0.52.3](https://codesandbox.io/p/sandbox/unocss-0-52-3-forked-4pvmys)

### System Info

- Windows 11 22H2
- Chrome 113.0.5672.127
- pnpm 8.5.1
- Vue 3.3

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
Because of this pr https://github.com/unocss/unocss/pull/2650 changed. Use `content-empty` replace `content-none`

**Comment by lainbo** [comment]
> Because of this pr #2650 changed. Use `content-empty` replace `content-none`
Thanks a lot! It's all good now and working fine!
