### ISSUE TITLE
Color variables are generated to be consistent with tailwind

### ISSUE THREAD

**Issue by FlatMapIO** [unocss/unocss#2672]
### UnoCSS version

head

### Describe the bug

Currently, Tailwind's generated results for CSS variable configuration are direct and effective, while UnoCSS has some limitations. I have to write the CSS hsl variables as comma-separated numbers to avoid problems.

## Config
`uno.config.ts`

```tsx
colors: {  popover: 'hsl(var(--popover))' }
```
At the same time, I also tried the %alpha placeholder configuration, which doesn't seem to work.
```tsx
colors: {  popover: 'hsl(var(--popover) / %alpha)' }

colors: {  popover: 'hsl(var(--popover) / <alpha-value>)' }
```

`theme.css `
```css
:root {  
  --popover: 0 0% 100%;  
}
```

### tailwind
`bg-popover` 
```css
background-color: hsl(var(--popover));
```

`bg-popover/80`

```css
background-color: hsl(var(--popover)/.8);
```

### unocss

`bg-popover` 
```css
--un-bg-opacity: 1;  
background-color: hsla(var(--popover),var(--un-bg-opacity));
```
the final color value is wrong and needs to be written in the form of variables to work properly

`bg-popover/80`
```css
background-color: hsla(var(--popover),0.8);
```
it works, but tw result feels more reasonable?

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kamtugeza** [comment]
It seems intentional: 

https://github.com/unocss/unocss/blob/9f7f6ec84e3def9a7c84daf32edea080e7a54439/packages/preset-mini/src/_utils/colors.ts#L62-L63

Perhaps, we could split this rule on two pieces for rgb/hsl and rgba/hsla.

As a temporary workaround you could use:

```ts
import type { DynamicMatcher } from '@unocss/core';

const colorMapping: Record<string, string> = {
  bg: 'background-color',
  text: 'color',
};

function handleColor(): DynamicMatcher {
  return ([_, property, name, alpha = '100']) => {
    const style = colorMapping[property];
    return style ? { [style]: `hsl(var(--color-${name}) / ${alpha}%)` } : {};
  };
}

const colorRules = [
  [/^(bg|text)-([a-z]+(?:-\d{2,3})?)(?:\/(\d{1,3}))?.*$/, handleColor()]
]
```

**Comment by FlatMapIO** [comment]
Related
- https://github.com/saadeghi/daisyui/issues/650
