### ISSUE TITLE
Arbitrary hsl colors

### ISSUE THREAD

**Issue by rightaway** [unocss/unocss#2674]
### Clear and concise description of the problem

Can't use an arbitrary hsl color like `bg-[hsl(0, 100%, 100%)]` which would make it easy to use it with variants.

### Suggested solution

Add syntax so hsl is possible with arbitrary values.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [ ] Already used the [Interactive Docs](https://uno.antfu.me).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by zyyv** [comment]
Incorrect usage. https://unocss.dev/interactive/?s=bg-[hsl(0_100%25_100%25)]
