### ISSUE TITLE
Safelisted classes don't work when using templates in `svelte-scoped`

### ISSUE THREAD

**Issue by scheatkode** [unocss/unocss#2676]
### UnoCSS version

0.52.4

### Describe the bug

When constructing class names using templates, an extra space is added to the rendered class name, resulting in two class names instead of one. For instance:

```typescript
const se = "se";
```

Using the template syntax, this:

```svelte
<p class="pro{se}">...</p>
```

Results in this:

```svelte
<p class="pro se">...</p>
```

Instead of:

```svelte
<p class="prose">...</p>
```

### Reproduction

The above example is easily reproducible, please do tell if there's a need to provide a full reproduction.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jacob-8** [comment]
Thanks for reporting, @scheatkode! Will be fixed upon merging #2684 

If you have the time in the future, another alternative to add a failing test that needs solved. In this case that would have been this:

https://github.com/unocss/unocss/pull/2684/files#diff-20805950e9231248de26a366b68a26ada46e08ed1bd24935ddbebb34c622f4cbR100-R112
