### ISSUE TITLE
Miss CSS in Qwik example at build time

### ISSUE THREAD

**Issue by mtt-artis** [unocss/unocss#2677]
### UnoCSS version

O.52.4

### Describe the bug

Hello,
the example doesn't seem to work on preview. Only CSS variables are found in the html page.
After qwick build, there are 2 CSS files. One in /dist/build with the CSS variables and the other in /server/build with the full style.

### Reproduction

The qwik example in the Uno-monorepo

### System Info

Windows
Chrome Brave Firefox 

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mtt-artis** [comment]
The CSS inline comes from /server/build/entry.preview.mjs

**Comment by mtt-artis** [comment]
fix it with an `include`.
if that's the way to do it, i'm willing to make a PR

```ts
export default defineConfig(() => {
  return {
    plugins: [
      unocss({
        include: ["./src/**/*.{ts,tsx,js}"],
      }),
      qwikCity(),
      qwikVite(),
      tsconfigPaths(),
    ],
    preview: {
      headers: {
        'Cache-Control': 'public, max-age=600',
      },
    },
  };
});
```

**Comment by datner** [comment]
Very cool!
