### ISSUE TITLE
feat(scan): support for browser plugins similar to taiwincss called tailscan.

### ISSUE THREAD

**Issue by hairyf** [unocss/unocss#2678]
### Clear and concise description of the problem

hi there! https://tailscan.com/ is really useful. It would be great if unocss had this feature too!

### Suggested solution

-

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://uno.antfu.me).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Currently, we don't plan to have it official due to the maintainance scope is already quite large. It would be nice to start as a community project first.
