### ISSUE TITLE
Add utilities usage info to UnoCSS Inspector 

### ISSUE THREAD

**Issue by enkot** [unocss/unocss#2682]
### Clear and concise description of the problem

In WindiCSS Analyzer it was very convenient to see many times each utility is used, so developers can perform additional optimisations (create shortcuts, use inline styles etc.).

<img width="1110" alt="Screenshot 2023-05-29 at 12 39 41" src="https://github.com/unocss/unocss/assets/10506522/8806fe97-e425-4c29-8981-df334e1c02b6">

### Suggested solution

Add another "Analyzer" page (or tab to the "Overview" page) to UnoCSS Inspector with this info:
- top utilities
- utilities usage
- suggested shortcuts
- color palette 

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://uno.antfu.me).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
I currently don't have bandwidth to do so, but PR welcome :)

**Comment by enkot** [comment]
I have started working on it, but currently have one problem. I'm trying to get `currentSelector` value to properly group selectors in Analyzer, but it looks like that `parseToken` produces different result in different contexts. 
Here I printed output of `parseToken()` in `generate()`  function (`packages/core/src/generator/index.ts`):
1. Left - `nr interactive`
2. Right - `nr inspector`

The `RuleContext` is missing in the output from `nr inspector`.

<img width="967" alt="Screenshot 2023-06-01 at 00 46 43" src="https://github.com/unocss/unocss/assets/10506522/7638aa9f-821e-414f-afef-46d664c0cfbb">

Can you please help/give some direction? For sure I'm missing something 🤔 

Another option I see - is to call `matchVariants()` for each selector in the `packages/inspector/node/index.ts`. But it looks like redundant operations, because it already done in the `generate()`.

**Comment by antfu** [comment]
For the additional info you need to turn on https://github.com/unocss/unocss/blob/0d66262d3851db010f7ad6eb8f1fef6e3c9ffaab/interactive/uno.config.ts#L13

**Comment by enkot** [comment]
Hidden gems :) 
Thank you! Thats exactly what I need 👍
