### ISSUE TITLE
custom rule for parsing css selector list containing multiple variants / alternative for @apply

### ISSUE THREAD

**Issue by bhvngt** [unocss/unocss#269]
Thank you for this very well designed library.

I understand that currently `@apply` is not supported by `unocss`. Are there any alternative suggested for use cases catered by `@apply`

I have a particular use case where I need both `focus:next` and `not-placeholder-shown:next` to use same style. 

I was wondering if there is any way custom rule can be created to parse [css selector list](https://developer.mozilla.org/en-US/docs/Web/CSS/Selector_list). CSS selector in this particular case is `input:focus + label, input:not(:placeholder-shown) + label`

**Comment by chu121su12** [comment]
For now, use `peer` with updated rule in https://github.com/antfu/unocss/commit/9a0a7a4b0097eaa1240da07e080fc210fe69ec74.

**Comment by bhvngt** [comment]
Even with `peer` I end up duplicating styling like -  

```html
	<label for=id
           peer-not-placeholder-shown="-translate-y-4 scale-75 origin-top-left text-green-500"
           peer-focus="-translate-y-4 scale-75 origin-top-left text-green-500"
```

Here's the reproduction of my [use case](https://unocss.antfu.me/?html=DwEwlgbgBAFgtAMwK4BsVQC4FMAeG4DGWAdtgE5QIq5QDOW1B%2BxA9sVlAIZoBcGZnYrTAYwbOABYADFKgA%2BAFBQooSFAC2nKARSdatALwAiMMRSmsiajihkGnURA4B3OAGYpBGLDgBGCUaKAJDApgAOSBhQYCDGMUaYAJ5hWMbYeAmcZGCccLoARgzGAKKaYCgJtCloXlgEANbGCNz0mZEsBCzqYdTYxiwICEYKQcpjypztBJxhItxgAF6pRqzsCT2cRDAsKCBYZMZQCcSc6ssnZ8Oj48o6eoZG9CgIcCQgUK7IaD5f6PxIxGm2A0cFkYXwAFYoGEcJJMLh8PldA0oEobuj0dM7PgAOZ2EhwCEyKAsSLmdhwVYcFL7YYY8b5FhkPYHIx4rAEomyWg7GJQfJwADaEhhAF06fTlPkccY8ZxEu5iQgOkhaDw5QrfDIJZKINwkMsrgB6YLAAoMShMgwxNGSmlkSksfAbLY7FlwWjbZzEYxwfiCWi6bBwBUSOjTahwADsUKZYBxpj9LDCeSwCCi6Vx%2BOIhO1tvp9sQKoefoEQiDllD4e4lhjJOyCZzGGTqfT8LwcHZnLz1xud30xmonHAxBxfjs6i4%2BR5KEiHGbKd8RrcUGo6bhYRYpnIrycpFojvY2iQZB5DszmDLtGVZEnGB19P9QhEYh9RgATMTyVgsglM52BAVKN8wxYIgnNFARmAI0IMUcZVGgfsHk4acdjnTAW1%2BVc03wMN1HwXx20RPRLE6UgSHvJ9ryZdRjAAP2rSM6zjRskxTNd7xA8Z-wAEj1B1pTgjEYAYFIyAAFQRfNoPACAhJkyBFAUuSFCAA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0DcAUN6gB6RYKDAEN6AG3hpMOfIWBEAFAm5w4USalYAuOAG016g7Wb1WMagFpNE1LQA0iOMwgToe2gCMJ9e2QBdIwCHIwA3UShgUSwYXQMjdSUQURhmAAtUKABKOABeAD5ERONgdDglAEIUtMyoADoLSLiAdWAYdKVaVmAfbCJdWmzskuMNVBh6KCw4Goys0fHJ6eKxsYB6dbhWCWBmVDgAA3SIMKydQ7gwKAxgfjgY5CvRdlQnyzgOg5x%2BeAiomJxB5YJ62bSLdRzOp6KFZRq7fZKACc2VCa2MrFQdmYligemwYHo8EKRwAJAgCUTyAA-OAAKkOaLWpBKpCZSVhOXyRVU6NcWAscH%2B0Vi%2BTgACIwBJRPsThI0FArKwTgB3LDinjosoVaqpeYNbDMXxoVhKYWA4YQpZTGacxb8wXAVgAOQgxNmerqjRgzVYbQ6SnFTBgVnF2U1awdblQ9XcynFyETyFYyDDEbGN2WM156Lgm22CIOx1O50u11u90ez1e7wgn0ycB%2Bf0iIqBVbBrCtnPxLrdcAA-B7anCdntUGaW4DY6gsEQOgBqACsuRhnpHhYnANi09nC4AjKirZjsbj8VhCcSik7XfBB4dyZSYKQdMGlDopTLUHKFUrVVhspcej3hS55Uu%2B0qym4P7KhAaqMosLJjIhcBBKQ2RAA&options=N4IgzgLgTglgxhEAuaBXApgXyA).

**Comment by chu121su12** [comment]
Does the config below match your use case? 

[playground](https://unocss.antfu.me/?html=DwEwlgbgBAFgtAMwK4BsVQC4FMAeG4DGWAdtgE5QIq5QDOW1B%2BxA9sVlAIZoBcGZnYrTAYwbOABYADFMrUchFugB8AKChRQkKAFtOUAik61aAXgBEYYiitZE8qGQadREDgHc4AZikEYsOABGCXM1AEhgKwAHJAwoMBALBPNMAE8orAtsPBTOMjBOOCMAIwYLAFE9MBQU2gy0PywCAGsLBG56XNiWAhYdKOpsCxYEBHNVMI0pjU5ugk4okW4wAC9M81Z2FIHOIhglECwyCygU4k4ddfPL8cnpjUNjM3N6FAQ4EhAoT2Q0AN-0PwkMR5thdHBZFF8ABWKBRBQSTC4fDFIwtKDqe5YrHzJz4ADmThIcGhMigLFiNnYcE2HAyR3G2OmxRYZEOx3MhKwxNJsloSgSUGKcAA2hJ4QBdRlMjTFfEWQmcVLeMkIHpIWg8RXKwIyaUyiDcJDrW4AenCwBKDEorNMCUxMvpZBpLHwOz2ByOcFo%2B3cxAscH4gloRmwcGViNo82ocAA7LDWWB8VZAywokUsAg4tkCUTiCS9Q6mU7EOrnoGBEJQ3YI3Ro3Z4%2BT8sn8xg0xms0i8HAuTzCzKHkYTBZqJxwMR8UEnDouMV%2BShYhw2%2BnAqavFBqFnJHCWFZyB83KRaC72AYkGR%2Bc6c5hK7Q1WQZxh9Uyg0IRGJ-eYAExkqlYPIpDmPYCMqsZFti4RhFaKATMAprQWo0xaNAjzDuYnBzkoi6YO2AIbpm%2BCIjo%2BCBF2KLGHYvSkCQT6vnerI6BYAB%2BdbcA2CbNimy4dk%2B4HTEBAAkhrOnKiHYjADAZGQAAqyJFnB4AQGJCmQGomLIbo%2Bioc8Vh-vYNBOKGkAeCqfgBMEoSwdEsTxIklggIB6TrDmuT5IU0EVFUNR0PUKCNC0bQdFgXRtr0-SDOsIxjBM2KzKFCxLDYawWLS2xolg%2BwoOyJxnBcVx5bc2LaRYrzvJ83yIKg6DwHhQIgi4HA6BCcIwnCCJkXAqK7M0GIDkyuJYLm3L5ry5KUrYJ50tyZDPtiLJskcCp5gWfICl8wpipKs1YnKS1KiqshqgQGpaiBQT9gOhoLiaEzmrB0E2sc9p9cV5gEHAUTEFEBiIPhY5WJOgTTrO87Ydxq7rpuhE7nuXpYIeGDHrSZ4XqygbIjewb3o%2B233HR75sBYP6yH%2BAEddqcZ8fckHQbB8EYQwYkaBpr0YaDYLcXhUPbsRQQdcUFGKNRpDmHR2PMaxMaNomLapumUO4xognCZ1%2BJM-cEkoFJsl4PJpqKcp%2Buqao6mKZpBhDjp1gTVQBnOK4Jk%2BGZ8AWRa1lxAkSQOWkGRZMirkFEUDMoJ5nDVLUvn%2Ba05jtCgnRcHMfQDINkWjIVWJxT0CUYMsyUbGwwVwulmXZSkuWXClBUxTilslQwZXEF8PxVf8Ld1aCjXNVCJJtduQFdeiVMvXkg3AcNK1jRgenI06itTPNpe9iNZLzoKG3ijgUpD-P8qcmdPiHWWp37bqUhzxoV3GhYZoWg9952iA1f3K970shg-ijuOgPA2zWEc%2B2EN8JbkRFEXc1FnTwxokjAuKNLzozwJjIQ2NMDn0QcIUQhNvy-lsGTICFMwJ9RpsHOmCF5Jm1ZphBc-90xcwIjzEi-NBZUWwCLMWDEJZRjYnGDiSYuLtgVtvZWeRVbq2mJrbWckkJGyUupaRakVIyKAA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0DcAUN6gB6RYKDAEN6AG3hpMOfIWBEAFAm5w4rABbQYzejFYAuOAG016xLWYBaMFjC1jAA3PqAkGFSoo1pjFsSosyo2hJoPloQAO5YhtYwUKJYrIEwqNYAntYALK4W6p7evhD%2BYIHBoeHWkTGGrMyiEukA7ACsefmFPn4BQSEQYUU1sdCK2PEQYNZN6DAdFl3FpeX9gxHatWn8-kRQXljWrQAMRy75pAA0eQhW1uiOcGcWHl4%2B6Cz0RvGJyanpWbl8p1XncPkZ6o0Wu0gQsQe89EZRkRxjBJtMMHMYQU4WDDFsdntUAdjqc8pdrrcAEYlTQPJ7uRY9Mp9SpDDaxb5JFKiNKZHLzbFFJkrVnraKxCFNaxtAVwRklXoVAZVYaGJEotEzTFY%2BXLFnKtnivECAn7Q4nPIvIrwz5xBJcv58wE6nEIuoNKUyrFy1229UHVFTLWyxY2oz46y7M0k%2BlkK7qAC6V1IAEogA&options=N4IgzgLgTglgxhEAuaBXApgXyA)

**Comment by bhvngt** [comment]
While this works with `shortcut` and I did thought of that, I prefer to use `shortcuts` when they are fairly generic and are used across components. I prefer to keep definitions local if they are unique to a particular component. 

I use `svelte`, so my component `style` and `markdown` are all in one place for a given component. Typically, `@apply` would have worked well here. While, this duplication is not a very big deal, I was just exploring right way of handling them.

**Comment by antfu** [comment]
I guess this is mostly solved as we are now supporting arbitrary selectors.
