### ISSUE TITLE
mistaken analysis in vscode plugin

### ISSUE THREAD

**Issue by evilArsh** [unocss/unocss#2697]
### UnoCSS version

^0.52.4

### Describe the bug

![image](https://github.com/unocss/unocss/assets/20971355/8c5e0cbe-210a-4dd5-96b5-89791d1a10c1)

### Reproduction

```typescript
 function print() {
    console.log("[name:age]", `${name.value}:${age.value}`)
  }
```

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
Hi, this is not a bug, uno will try to extract utilities for parsing. https://unocss.dev/interactive/?s=[foo:bar]
