### ISSUE TITLE
I followed the documentation, It seems that uno.config.ts can not be loaded automatically.

### ISSUE THREAD

**Issue by Himmelbleu** [unocss/unocss#2700]
### UnoCSS version

0.52.7

### Describe the bug

I followed the documentation and added `uno.confit.ts` file under the `src` directory, but it does not seem to load automatically.

I specified the configuration file directory, then it's back to normal.

I'm not sure if it's a bug.

### Reproduction

https://stackblitz.com/edit/unocss-unocss-ngajxc

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
> I followed the documentation and added uno.confit.ts file under the src directory

Where did you find that? It's the root directory and never the `src`, same as other tools' config.

**Comment by Himmelbleu** [comment]
It's me. I'm sorry.

Today, I upgraded from version 0.51.12 to latest.

I put it in the root directory before,  also can not.

I'm so embarrassed.😭Thank you for taking the time to answer my question!
