### ISSUE TITLE
`mergeConfigs` removes default `Uno` preset

### ISSUE THREAD

**Issue by enkot** [unocss/unocss#2703]
### UnoCSS version

0.52.7

### Describe the bug

Trying to merge 2 configs. Currently if no preset explicitly specified, the `presets` array will be empty.

```ts
// uno.config.ts
import baseConfig from './base/uno.config';
import commerceConfig from './commerce/uno.config';

export default mergeConfigs([baseConfig, commerceConfig]);
``` 

### Reproduction

https://stackblitz.com/edit/github-mxkbee-stgpe9?file=uno.config.ts

### System Info

------------------------------
- Operating System: Linux
- Node Version:     v16.14.2
- Nuxt Version:     3.5.2
- Nitro Version:    2.4.1
- Package Manager:  npm@7.17.0
- Builder:          vite
- User Config:      extends
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
No, UnoCSS is an atomization engine, its ability to work depends on your configuration.

**Comment by enkot** [comment]
By the way, thats just thoughts, having `presetUno()` explicitly is also fine :)

**Comment by jacob-8** [comment]
> makes sense to not generate field if it is not present in any of the configs

I agree with this. Only return real data and not empty arrays because an empty array is not the same as undefined. In this case the empty array is a signal to override the default preset.

@enkot this shouldn't be too hard. Want to try a PR?

**Comment by enkot** [comment]
Also thinking about merging transformers by name, but it is not clear what to do in this case:
```ts
mergeConfigs([
  {
    transformers: [
      {
        name: 'foo',
        async transform() {},
      },
      {
        name: 'bar',
        async transform() {},
      },
    ],
  },
  {
    transformers: [
      {
        name: 'bar',
        async transform() {},
      },
      {
        name: 'foo',
        async transform() {},
      },
    ],
  },
])
```
and if it makes sense at all 🤔
