### ISSUE TITLE
`mergeConfigs` doesn't merge `theme`

### ISSUE THREAD

**Issue by enkot** [unocss/unocss#2704]
### UnoCSS version

0.52.7

### Describe the bug

Trying to merge 2 configs:
```ts
export default defineConfig({
  theme: {
    colors: {
      brand: {
        '1': '#ddc099',
        '2': '#cf780f',
        '3': '#af231c',
        '4': '#282321',
        '5': '#fffcee',
        '6': '#f8f9f7',
        '7': '#fc6b00',
      },
    },
  },
});
```
```ts
export default defineConfig({
  theme: {
    fontSize: {
      micro: ['0.625rem', '1rem'],
      xs: ['0.75rem', '1rem'],
      sm: ['0.875rem', '1.125rem'],
      base: ['1rem', '1.5rem'],
      md: ['1.125rem', '1.5rem'],
      lg: ['1.25rem', '1.5rem'],
      xl: ['1.375rem', '2rem'],
    },
  },
});
```
But the result config looks like this:
```json
{
  "theme": {
    "colors": {
      "brand": {
        "1": "#ddc099",
        "2": "#cf780f",
        "3": "#af231c",
        "4": "#282321",
        "5": "#fffcee",
        "6": "#f8f9f7",
        "7": "#fc6b00"
      }
    }
  },
  "presets": [],
  "safelist": [],
  "preprocess": [],
  "postprocess": [],
  "preflights": [],
  "rules": [],
  "variants": [],
  "shortcuts": [],
  "extractors": []
}
```
It doesn't contain `fontSize` prop from second config.

### Reproduction

https://stackblitz.com/edit/github-mxkbee-stgpe9?file=uno.config.ts

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by enkot** [comment]
Or it is supposed to have themes in presets in this case? 🤔

**Comment by antfu** [comment]
Yeah I implemented `mergeConfigs` in hurry. PR welcome to fix it, thanks!
