### ISSUE TITLE
Add support for variables like the actual breakpoint

### ISSUE THREAD

**Issue by Rednas83** [unocss/unocss#2707]
### Clear and concise description of the problem

Tried asking chatgpt
https://webapp.chatgpt4google.com/s/Mzc4NjE3
But I am not very satisfied with the answer🤔

### Suggested solution

What I would like to do is something like:
`<div :class="breakpoint == 'sm' ? navbar-start : navbar-center">`

**Comment by Rednas83** [comment]
I still have a requirement for this. Are there plans for supporting something like this in the future?

**Comment by schelmo** [comment]
if you use vue: how about useBreakpoints from vueuse?
https://github.com/unocss/unocss/discussions/2988
https://vueuse.org/core/useBreakpoints/#usebreakpoints

**Comment by Rednas83** [comment]
@schelmo Thanx for pointing me to `useBreakpoints` and I am indeed using vue. I was able to write a composable with it for getting the actual/biggest breakpoint.
![image](https://github.com/unocss/unocss/assets/25219229/aabfa051-48c8-4df5-b738-9f895791bf42)
