### ISSUE TITLE
vscode extension provides wrong color in indicator when class has ! prefix

### ISSUE THREAD

**Issue by H41D4x** [unocss/unocss#2708]
### UnoCSS version

0.51.12

### Describe the bug

It seems that the vscode extension is showing wrong color in the little indicator, when the ! prefix is added to a unocss class:

![image](https://github.com/unocss/unocss/assets/131161505/45eaf2f4-9877-40b0-badd-e2dcabef7a21)

vs

![image](https://github.com/unocss/unocss/assets/131161505/660385e1-452c-4907-880f-f2cddb807f38)

Both applies the right styling, although when the important prefix is present, the vscode extension seems to use a default color for the indicator.

### Reproduction

I think the previous images can describe the problem clearly, although if more information is needed, please let me know!

### System Info

Windows 10, 16GB RAM, i7 6th Gen, WSL2 Ubuntu, Chrome, React + ViteJS

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by arkaroy135** [comment]
I'm also facing the same problem.

**Comment by vargasmesh** [comment]
@H41D4x this is a problem with the capturing group for capturing CSS variables. It was also capturing the `!important` generated by UnoCSS. I have just opened a PR, it will be solved soon. Thank you for raising the bug!

**Comment by H41D4x** [comment]
@vargasmesh Thank you so much!! This is great news!! 🙌🏻 Since I found Unocss, I never looked back, it really delivers the best development experience. Btw, I am sorry, but should I close the issue now? I am not really aware of how the process typically goes 😅 Thank you so much once again!

**Comment by vargasmesh** [comment]
@H41D4x indeed, Unocss is amazing and the tools make it so easy to use it.

About the issue, when the PR is merged, it will close automatically. You will receive a notification about it being closed too.
