### ISSUE TITLE
Cannot write nested css with "&" in nuxt3

### ISSUE THREAD

**Issue by yveeven** [unocss/unocss#2711]
### UnoCSS version

0.52.7

### Describe the bug

I use the "&" class in nested css in nuxt3, and I also added postcss-nested, but there is no difference, I use @apply in the implementation, but I tested and it has nothing to do with it, please see the minimum implementation for details

### Reproduction

[vue](https://stackblitz.com/edit/nuxt-starter-k1km5d?file=app.vue)

### System Info

  System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 138.42 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 114.0.5735.90
    Safari: 16.4

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Rolanddoda** [comment]
@yveeven if you define the postcss config inside `nuxt.config.ts` it should work. 

[Fixed demo](https://stackblitz.com/edit/nuxt-starter-wkkkff?file=nuxt.config.ts)

[Docs](https://nuxt.com/docs/api/configuration/nuxt-config#postcss)

**Comment by yveeven** [comment]
> @yveeven if you define the postcss config inside `nuxt.config.ts` it should work.
> 
> [Fixed demo](https://stackblitz.com/edit/nuxt-starter-wkkkff?file=nuxt.config.ts)
> 
> [Docs](https://nuxt.com/docs/api/configuration/nuxt-config#postcss)

Thanks for solving it, but I'm curious as to why, does nuxt not read postcss configuration files, is this also unreasonable
