### ISSUE TITLE
Reset priority in Astro

### ISSUE THREAD

**Issue by shishkin** [unocss/unocss#2717]
### UnoCSS version

0.52.7

### Describe the bug

I might be missing something, but I wonder why astro integration loads reset styles after the main `__uno.css` style. This prevents me from overriding some defaults with normal means without increasing specificity or using `!important`.

In the reproduction example I'm using `tailwind-compat.css` reset and am trying to make links underlined again from a preflight. I've read docs about resets, preflights and layers, but nothing seems to help since resets apparently don't use layers.

If there is another solution to that I'd be grateful to learn it.

### Reproduction

https://stackblitz.com/edit/github-mrekxn-qfbrtc?file=astro.config.ts

### System Info

Astro

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by shishkin** [comment]
What I also observe in the same repro is that resets and uno styles come _after_ the styles on the page itself. So if page contains generic CSS styles they get reset.

**Comment by shriharip** [comment]
Would love to see it merged with the main :)
