### ISSUE TITLE
Types of property 'transform' are incompatible when using `transformerDirectives`

### ISSUE THREAD

**Issue by trandaison** [unocss/unocss#2718]
### UnoCSS version

0.52.6

### Describe the bug

I do exactly what the docs say, but I get the following error:

<img width="960" alt="Screen Shot 2023-06-04 at 11 07 51" src="https://github.com/unocss/unocss/assets/13447235/ddddfc13-5ff1-4a1a-9b43-90b4aa82688d">

**Fortunately, `@apply` still working somehow** 

### Reproduction

# Install
npm i -D @unocss/transformer-directives

```ts
// uno.config.ts
import { defineConfig } from 'unocss'
import transformerDirectives from '@unocss/transformer-directives'

export default defineConfig({
  // ...
  transformers: [
    transformerDirectives(),
  ],
})
```

### System Info

- Operating System: `Darwin`
- Node Version:     `v18.16.0`
- Nuxt Version:     `3.5.1`
- Nitro Version:    `2.4.1`
- Package Manager:  `pnpm@8.6.0`
- Builder:          `vite`
- User Config:      `plugins`, `css`, `vite`, `build`, `devtools`, `modules`, `routeRules`, `runtimeConfig`, `elementPlus`, `i18n`, `auth`
- Runtime Modules:  `@vueuse/nuxt@10.1.2`, `@pinia/nuxt@0.4.11`, `./modules/auth`, `@nuxtjs/i18n@8.0.0-beta.12`, `@element-plus/nuxt@1.0.5`, `@unocss/nuxt@0.52.6`
- Build Modules:    `-`

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Ebony-Ivory** [comment]
same problem....
I use the `transformerDirectives` in ''unocss'
```
import { transformerDirectives } from 'unocss';
// import transformerDirectives from '@unocss/transformer-directives'
```
