### ISSUE TITLE
VS code extension: support multiple workspace roots and/or autodetection

### ISSUE THREAD

**Issue by PhilippMolitor** [unocss/unocss#2742]
### Clear and concise description of the problem

I am using UnoCSS with a Yarn 1 + Turborepo monorepo.
My uno config lies in `apps/frontend` - which works when I use uno only there.
The issue with monorepos is, that if I decide to create another web application (imagine `apps/docs` ), now there is no way to use unocss in that repo correctly.

### Suggested solution

**Automatic configuration detection**

1. Scan vsc workspace for files names `uno.config.ts`
2. Assume location of each `uno.config.ts` is the package root of that package (maybe consider looking up a `package.json` next to it to be sure)
3. add package root and config location to the list of detected unocss workspaces
4. Probably it is a good idea to allow a settings key for excluding dir globs like `**/node_modules/*` from scanning for performance.

**Manual configuration**
`.vscode/settings.json`:
```json
{
  "unocss.packageRoots": [
    {
        "packageDir": "apps/frontend"
    },
    {
        "packageDir": "apps/docs",
        // config in a custom subdirectory. maybe even make this path relative to the `packageDir`?
        "config": "apps/docs/config/uno.config.ts"
    }
  ]
}
```

**Editor -> UnoCSS associations**
1. Each open VS code editor is monitored for their full path
2. If the path is matching one of the detected or configured packageRoots, look up the config of that package.
3. Apply autocompletion with that configuration

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by GreatAuk** [comment]
https://github.com/unocss/unocss/pull/2101

**Comment by mikestopcontinues** [comment]
The existing functionality doesn't support this.

Another possible improvement is using the relative path params VSCode uses for other settings. Being able to add `{workspaceRoot}`, `{projectRoot}`, etc to the "unocss.root" array would help avoid having to configure this for each project.

**Comment by PhilippMolitor** [comment]
not stale

**Comment by louiss0** [comment]
I was trying to ask for detection for different mono-repos.
I'm not a fan of this non-auto-detection thing.

**Comment by louiss0** [comment]
Can we please have auto-detection I don't want to have to configure the extension every time I open a new repo.
I know that performance is important but. Mental overhead is painful. If Tailwind can do this efficiently so should UnoCSS

**Comment by louiss0** [comment]
> I think this issue could be close

Thank you for solving this problem. You have saved people soo much headache. Not only that you have got rid of one of the biggest weakness of this tool

**Comment by Simon-He95** [comment]
> Thank you for solving this problem. You have saved people soo much headache. Not only that you have got rid of one of the biggest weakness of this tool

I'm very happy to help users who use unocss. I hope everyone can like it.
