### ISSUE TITLE
Support for custom uno class name prop

### ISSUE THREAD

**Issue by jprestidge-nex** [unocss/unocss#2752]
### Clear and concise description of the problem

Coming from Tailwind and the twin.macro ecosystem specifically, there is support for a `tw` prop for adding atomic CSS class names. [For example.](https://github.com/ben-rogerson/twin.macro/blob/master/docs/prop-styling-guide.md)

It would be great with all of UnoCSS's flexibility to be able to define a custom class name prop, in the config (possibly with a transformer 🤔).

Say I wanted `cn` or `uno` for example, that personally would feel very zen and clean.

### Suggested solution

Add an option to the uno.config.js to customize the class name prop.

### Additional context

I know this is quite a small superficial change, but I believe it would give the large number of Twin.Macro users some familiarity when trying out Uno! 🙇 

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by zyyv** [comment]
Refer to: 
- Add prefix in `presetUno` - [Playground](https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIAuB3AtJgUwA9NcAnAkdKHDQk3Iua%2B0whOAPgFUA7AewDCAZWHAA9OAicAUEA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVHQAFtAwEjx0AFyIVKh6AO5Q9mBgGFB6UfEAtACMAAy5AG5xcIE5%2BQWBmk5WcMAwGCB0mRIYuPVQcABWXHS8As2t7WaoarIiCpFwANoxcqJKKn6zwrQ4lhkwcZnDqHBqAJSyK-MsbJw8fPw%2Bh1QAukgHSEA&css=Q&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g)

- Add prefix in `presetAttrbutify` -  [Playground](https://unocss.dev/play/?html=DwEwlgbgBALg7gWhgUwB4wagNrRL1LICGWAfAKoB2A9gMIDK9wA9OBKQFBA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCCMMUwARgK4zDoCeZF1tAJIBjAlT6UaMAKpYIcAL5x0UCCDgByNnOFUqGgFAHUAD0iwUGAIZsANvDSYc%2BQsCIAKBAbhwqAC2gYYQ4qAC5Ebx84AHcoKzAwVChwjWiAWgBGAAYsgDdouD9MnNy-ZVtTOGAYVBAqNOFULBqoOAArNipOHgamlo0SSIVBn34pMLgAbUjRyVpZCHcAShGosdoGJlYOLm5PGaiu5mEYcKY2VFWo8kpMExSYdIGD2YxgE1RkAHksW24zqAXK6KFaRAC6gwUSwMQA&css=Q&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g)
