### ISSUE TITLE
Expose `variantMatcher` and `variantParentMatcher` utils

### ISSUE THREAD

**Issue by enkot** [unocss/unocss#2757]
### Clear and concise description of the problem

It will be helpful to have these utils exported from `@unocss/code`, so users can easily add custom variants. 

### Suggested solution

Usage example:
```ts
import type { Variant } from '@unocss/core'
import { variantMatcher } from '@unocss/core'

export function variantAfterFocusVisible(): Variant {
  return variantMatcher('after-focus-visible', (input) => ({ prefix: `input:focus-visible ~ $$ ${input.prefix}` }))
}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by enkot** [comment]
Haven't noticed, can be imported from `@unocss/preset-mini/utils`. Closing this one 🙈

**Comment by antfu** [comment]
It's not from the core. And you can import it now:

```ts
import { variantMatcher } from '@unocss/preset-mini/utils'
````
