### ISSUE TITLE
✨ Support for individual transform properties

### ISSUE THREAD

**Issue by jd-solanki** [unocss/unocss#2760]
### Clear and concise description of the problem

All the browsers now support individual transform properties like scale, translate, rotate, etc. ATM UnoCSS can't generate these properties.

[Playground](https://unocss.dev/interactive/?s=translate-1/2)

### Suggested solution

None

### Alternative

`[translate:50%]` arbitrary value

### Additional context

What we will do with the existing class 🤔  or what will be the name of the new classes for these individual properties?

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
I guess currently it might be better to live in a separate preset, say `unocss-preset-modern`. As we don't have a good way to do CSS fallback yet. Later if Tailwind have that we could align with them.
