### ISSUE TITLE
Add new magic comment to skip some code for extract utilities

### ISSUE THREAD

**Issue by zyyv** [unocss/unocss#2761]
### Clear and concise description of the problem

When Uno extracts `utilities`, it only extracts the full amount. `@unocss-ignore` can't do something when we have a part of the code that we don't want to be extracted by Uno or transformed by the `transformer`.

### Suggested solution

I suggest add two new magic comments to skip any code between them, like `@unocss-skip-start` `@unocss-skip-end`.

### Usage: 

```vue
<script setup lang="ts">

// ...
// @unocss-skip-start
cosnt testBtnString = '<button class="px-4 py-2 rounded bg-red">test</button>'
// @unocss-skip-end

// ...
</script>
```

Uno will not extract `px-4 py-2 rounded bg-red` in tokens.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by zyyv** [comment]
How about this idea?  i'd like to implement it.

**Comment by antfu** [comment]
Sounds good to me. You can go ahead
