### ISSUE TITLE
Write `@unocss/cli` output to STDOUT

### ISSUE THREAD

**Issue by equt** [unocss/unocss#2765]
### Clear and concise description of the problem

The CLI currently write its generated content to a file.

https://github.com/unocss/unocss/blob/1cb4ce12493bd24c63ed0206ae746deae5ba521d/packages/cli/src/index.ts#L138-L140

I believe writing to STDOUT should allow a better integration with other CLI tools, especially for those who're handling stuffs not in JS world.

😉 glad to help if it's worth working on

### Suggested solution

The [`--out-file`](https://unocss.dev/integrations/cli#options) should accept a `-`, which indicates the STDOUT. (Well, this _could_ potentially break the code if someone has already outputted to a file named `-`)

### Alternative

keep it as is

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [ ] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Making sense. I guess it might be better to introduce a new argument. PR welcome :)
