### ISSUE TITLE
VSCode config file for workspace with multiple projects

### ISSUE THREAD

**Issue by LeCoupa** [unocss/unocss#2768]
### UnoCSS version

0.53.1

### Describe the bug

I work in VSCode with all the repositories open in one window. This seems to create an error with the eslint plugin.

> Error: [@unocss/eslint-plugin] No config file found, create a `uno.config.ts` file in your project root and try again.

```vite.config.ts
import UnoCSS from 'unocss/vite'
import { defineConfig } from 'vite'

export default defineConfig({
  plugins: [
    // ...

    UnoCSS(),
  ],
})
```

```.eslintrc
{
  "extends": [
    "@antfu",
    "@unocss"
  ]
}
```

Looks like the extension is not catching the .uno.config.ts file

### Reproduction

Create a folder that contains multiple respositories

<img width="352" alt="CleanShot 2023-06-15 at 19 39 46@2x" src="https://github.com/unocss/unocss/assets/1658644/f7b540ce-5e60-4c18-be96-3876f33e11f1">

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by vargasmesh** [comment]
I could reproduce just like you mentioned

![image](https://github.com/unocss/unocss/assets/22207414/b47bd7d3-27cd-4326-b8b3-1fe032c733e3)

However, reading the documentation (https://unocss.dev/integrations/vscode) it seems an **expected problem**.

Does your `uno.config.js` change for each project? If not, you can do as the document says: create a separate config so pass the path to `unocss.root`

**Comment by LeCoupa** [comment]
thank you for your answer @vargasmesh I will use turborepo soon so this should fix the issue. :)
