### ISSUE TITLE
background-image will request continually when I resize page

### ISSUE THREAD

**Issue by shanyi-front** [unocss/unocss#2778]
### UnoCSS version

0.53.1

### Describe the bug

**background-image will request continually when I resize page**

![image](https://github.com/unocss/unocss/assets/56287833/29537c80-4468-4354-a892-c7ccf4887093)

**when I resizing**

![image](https://github.com/unocss/unocss/assets/56287833/5e45f5c6-75fd-4cae-9a83-b4cd10b05393)

**Is there something I have missed?**

### Reproduction

https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIDuBaJMBOApoQHZQAWuBxZARgObZEhQPYwD2Eh%2BrjA2gFd8cABTkALhIAOSAFwB6BWAC29AIwA6WgjAhBmziuUSFg1AE4AHBYDMFgAwWAbABYANOrsPnbgKwATFYAZABmKqgBfrZhKhKoCIISHMEI0tKo6rYhoagACgByAOIA-Jiofg4OweSozhYWAJQAuugAfABQUFAdwArgEG1AA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUkNikEA&css=Q&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
<img width="1678" alt="image" src="https://github.com/unocss/unocss/assets/42139754/7b5babf3-0eab-4033-8d9a-01a0d21bad4d">

Oh, it not reproduced in my browser, can you change another browser to test it?

**Comment by shanyi-front** [comment]
Thank，This should be due to the low version of chrome When I update the browser it doesn't  repeat the request

**Comment by shanyi-front** [comment]
Thanks，This should be due to the low version of chrome When I update the browser it doesn't repeat the request
