### ISSUE TITLE
svelte scoped: using preprocessor style, [&>*]: child selector vs child CSS ordering is inconsistent

### ISSUE THREAD

**Issue by henrikvilhelmberglund** [unocss/unocss#2792]
### UnoCSS version

0.53.3

### Describe the bug

Using preprocessor style, [&>*]: child selector vs child CSS ordering is inconsistent.
Aka if I had something like this

```html
<main class="[&>*]:p-4">
	<p class="p-48">Text</p>
</main>
```

sometimes `p-4` would be applied to `<p>` and sometimes `p-48`. It changes when changing `p-48` in the `<p>` tag to something else like `p-44`. I think `[&>*]:p-4` should be the base styling which is then overridden in the child. (which is how it works using the svelte scoped Vite plugin version)

To be fair I can't remember if this is how it should work or if `!p'48` is required. If it is possible to make it work like in the Vite plugin version that would be great though.

### Reproduction

https://stackblitz.com/edit/unocss-unocss-fbxpaz?file=src%2Froutes%2F%2Bpage.svelte

Change p-44 to p-48 and back near the comment in +page.svelte.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jacob-8** [comment]
The [playground places the regular `.p-44` after the special class](https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIDaAyAfAKgF0AuABwFoAWdXAKCimFNkRQwsuroYYAkBTOHAD29RgHpSdYOPARcQA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcEWSIUAVfpFJQAhmAAWgpAF84WKBBBwA5FxUS6dW0iQYAHpFjpsergA28Jg4%2BEQkwKQAFMioUIH0AFxwANpUqCm2Elx0MNYAtPEBGLbkiHBSAdDJtrRotnCmALpUTbJ0htAw2TB0ybGodtm5BR1dPbY1MJ4w%2BQGkcNMes9B6uKQYcJ0AbhhQiUuz03oBpel2HDC4%2BTSgelD8k3aHhRj1sqZq8ox9qefqjGUECiAEpZMJvsxWOxuLwBKDwXJRDAtDp9EZ%2BAj-pDJNIYudUHQJCcMMkAIwAOgATIjUBI0LgaoZWGA%2BgB6Nn0EAUjps1yDRpg1pmEFIIA&css=Q&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwBoQJ84AHJeASwDd9Ns98BfIA) which indicates it has the priority.

Yeah, good find. I'm not sure just yet why and don't have time to look at it now, but do know that both the @unocss/svelte-scoped/vite and @unocss/svelte-scoped/preprocess use the same Svelte preprocessor so if you have a bug like this in one it probably exists in the other.

For the moment just use `!p-44` and also feel free to create a failing test for this situation to get the ball rolling if it's a big bother to you.

**Comment by jacob-8** [comment]
This may be solved as a side-effect of #2922 or another change that happened recently. Let's circle back after that's merged and check.
