### ISSUE TITLE
VSCode extension does not respect include/exclude options for underline decoration

### ISSUE THREAD

**Issue by aleclarson** [unocss/unocss#2802]
### UnoCSS version

v0.53.4 (VSCode extension)

### Describe the bug

Even though I have `include: ["**/src/**/*.{tsx,jsx}"]` in my `unocss.config.ts` file, the extension is still looking for matching tokens in other files and then underlining them.

### Reproduction

You can reproduce this in any UnoCSS project

### System Info

- VSCode 1.80.0-insider

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example). Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)
