### ISSUE TITLE
HMR weirdness with Astro + Uno

### ISSUE THREAD

**Issue by marvin-j97** [unocss/unocss#2812]
### UnoCSS version

0.53.4

### Describe the bug

There are a couple of issues I have noticed trying to use the latest versions of Astro and Uno. I'm not sure if all these problems are caused by Uno, downgrading to Astro ^2.6 (from 2.7.2) fixes it. But I'm not sure if Astro is at fault here.

1. Running dev mode, the first thing you see the web page is completely unstyled. Refreshing fixes it.

2. Uno logs "[unocss-hmr] failed to get unocss hash, hmr might not work"

3. Now, changing some classes, the site sometimes reverts to the unstyled version (I think this happens when a previously unused class is used). Using one that has been used before is fine.

Production build is fine.

### Reproduction

https://github.com/marvin-j97/astro-uno-hmr

### System Info

Ubuntu, Chrome

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Dunqing** [comment]
It looks like `Astro` did some updates that caused this problem, I tested it and it occurs from `2.7.1` onwards.

**Comment by Dunqing** [comment]
I confirmed that it is caused by https://github.com/withastro/astro/pull/7381, I am not sure if I want to fix it in `astro` or in `unocss`, can you report this issue to `astro`?

**Comment by marvin-j97** [comment]
Maybe it's related to https://github.com/withastro/astro/issues/7529 ?

**Comment by Dunqing** [comment]
> Maybe it's related to [withastro/astro#7529](https://github.com/withastro/astro/issues/7529) ?

Yes, but it should have been broken since 2.7.1.

**Comment by marvin-j97** [comment]
HMR is suppoedly fixed (haven't tried yet) in Astro 2.7.4.

The uno hash warning still comes up:
https://github.com/withastro/astro/pull/7565#issuecomment-1621895588

**Comment by marvin-j97** [comment]
Can confirm HMR is working in Astro 2.8.0.

uno hash warning still popping up, not sure if it's important:
https://stackblitz.com/edit/withastro-astro-yrtpg7?file=package.json

**Comment by Dunqing** [comment]
I don't think this warning affects HMR, but I'll try to fix it.

**Comment by GavinXue** [comment]
This uno hash warning still popping up. Sometimes the hmr works, and sometimes not. Still need to refresh page to check the new style. 
`unocss@0.53.6` `astro@2.9.2`

**Comment by JUNGHUNKIM-7** [comment]
The issue is existing until today. "astro": "^2.10.1", "unocss": "^0.54.2"
