### ISSUE TITLE
VSCode extension cannot highlight the last attributify class of tag in monorepo

### ISSUE THREAD

**Issue by CatsJuice** [unocss/unocss#2813]
### UnoCSS version

0.52.2

### Describe the bug

While using pnpm monorepo, VScode extension cannot recognize the last `className` (attributify) in the tag.

In short,
![CleanShot 2023-06-30 at 14 28 10@2x](https://github.com/unocss/unocss/assets/39363750/356827c4-a2bb-4dd0-a2c1-5d40bdccc6af)

**This only happens when open monorepo's root folder as vscode workspace,**
**it works when open `client` folder directly.**

There is a related issue #2603. So I did creating a `uno.config.js` file under the root folder.

### Reproduction

Repo: [https://github.com/CatsJuice/mir-unocss-vscode-attr-last-bug](https://github.com/CatsJuice/mir-unocss-vscode-attr-last-bug)

Clone repo, install deps and open root folder in vscode, look into `packages/client/src/App.vue`

### System Info

- Silicon: Apple M1 Pro
- OS: macOS Sonoma 14.0 Beta2

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
This should already been fixed
