### ISSUE TITLE
The color of the dynamic binding theme is not effective

### ISSUE THREAD

**Issue by fxzer** [unocss/unocss#2817]
### UnoCSS version

 "unocss": "^0.53.4",

### Describe the bug

![image](https://github.com/unocss/unocss/assets/68853957/6af06f38-bcf8-47c4-93c5-3eb999aeefac)

![image](https://github.com/unocss/unocss/assets/68853957/e97aa148-fde3-4edf-b37a-1fa474249274)

![image](https://github.com/unocss/unocss/assets/68853957/3652a424-155d-475c-9288-351d505ea016)

是 unocss 没法解析到动态绑定的类名吗？还是需要再哪里做特殊的配置才可以？我期望的是动态绑定的类名可以生效，请问有什么解决办法呢？

Is it UNOCSS unable to analyze the dynamic binding class name?  Where do I need to configure ？ What I expect is that the dynamic binding class name can take effect. Is there any solution?

### Reproduction

git clone git@github.com:fxzer/epx-admin.git 
git checkout dev
ni && nr dev

### System Info

版本 114.0.5735.198（正式版本） (arm64)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
先在issue里面搜一下「如何支持动态类」吧。keyword：[dynamic class](https://github.com/unocss/unocss/issues?q=dynamic+class)

**Comment by fxzer** [comment]
好的，之前我搜dynamic bind 没搜到，原来是关键词不对

**Comment by fxzer** [comment]
> 先在issue里面搜一下「如何支持动态类」吧。keyword：[dynamic class](https://github.com/unocss/unocss/issues?q=dynamic+class)
实在没找到是哪个，可以发我一下解决方法的链接吗？非常感谢！！
