### ISSUE TITLE
Layers ordering not working properly

### ISSUE THREAD

**Issue by slavamak** [unocss/unocss#2823]
### UnoCSS version

0.53.4

### Describe the bug

I use Unocss as a plugin with Vite. From the documentation [here](https://unocss.dev/config/layers#ordering) if I want to put custom CSS between layers then I have to update the entry module as follows:

```js
// 'uno:[layer-name].css'
import 'uno:components.css'

// layers that are not 'components' and 'utilities' will fallback to here
import 'uno.css'

// your own CSS
import './my-custom.css'

// "utilities" layer will have the highest priority
import 'uno:utilities.css'
```

but it does not match this.

1. Build the project `npm run build`
2. Go to the `dist` folder
3. Check the file `index.css`

At the end of the file you will see the css from `my-custom.css` but not the css from the `utilities` layer.

I also tried adding `layers` option to the config. But nothing changes.

```js
layers: {
  components: -1,
  default: 1,
  utilities: 2,
}
```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-9ajbji

### System Info

Vite 4.3.9

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zoeyzhao19** [comment]
I looked into the code and found the `unocss/vite` plugin can not match the right layer indeed. I would like  to submit a PR if needed. @antfu

**Comment by slavamak** [comment]
I see that this is closed, but I still don't have it working as expected. I have updated the packages but it still doesn't work. Could you please take a look at it again? Maybe I'm doing something wrong?

https://stackblitz.com/edit/vitejs-vite-9ajbji
