### ISSUE TITLE
Rules restriction

### ISSUE THREAD

**Issue by bitsnaps** [unocss/unocss#2825]
### Clear and concise description of the problem

Currently, there is no restriction on applying multiple CSS frameworks within the same project. This lack of restriction can lead to inconsistencies in the generated CSS code, causing confusion and potential conflicts. Several [developers](https://www.youtube.com/watch?v=1vwq4uaYQGU) have raised concerns about this issue, as it can lead to unexpected behavior and increased difficulty in maintaining the codebase.

### Suggested solution

To address this issue, I propose implementing a feature that restricts the use of multiple CSS frameworks within the same project. This feature could be a configuration setting that allows developers to specify the CSS framework they intend to use. Once set, the system would only allow CSS rules from the specified framework to be applied, preventing the mixing of different frameworks. This would ensure the consistency of the generated CSS code and reduce potential conflicts.

### Additional context

I did some research about this feature to make sure it's not already implemented before submitting this request, even GPT-4 has no solution, and here is an excerpt of its answer about this using only Bootstrap (as an example):
```
Unfortunately, UnoCSS does not currently support this feature. You can, however, use a CSS linter like [Stylelint](https://stylelint.io/) to enforce style guidelines in your project. You can create a configuration file for Stylelint and specify that only Bootstrap classes should be used.

if you want to completely restrict the use of any other CSS classes, you would need to add a custom rule to disallow any other classes.```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Can you explain more about "potential conflicts"? You can use blocklist to disable rules you don't want. https://unocss.dev/guide/extracting#blocklist

**Comment by bitsnaps** [comment]
Thanks for your prompt response and for the `blocklist` hint, and here is my point about the "potential conflicts":

In a small dev team, it's quite common to have multiple `presets` being used in the same project, this can lead to a situation where different `presets` might have overlapping or conflicting rules, which can cause confusion and inconsistencies in the project's styling and makes the bundle size even bigger by using redundant rules.

To mitigate this, I'd suggest implementing a feature like `blocklist` but for `presets` instead (something like `blockPreset` or `acceptPreset`), this feature would, by default, block all presets except for the default `preset-uno`, unless other `presets` are explicitly allowed. I understand that this might be a more complex way of implementing this feature and you can definitely implement this feature in much easier and simpler way, but I believe it could help prevent potential conflicts within a team, and streamline the use of presets.

I'm confident that with such a feature, UnoCSS would become even more popular within the Nuxt community, UnoCSS seems like a natural fit for Nuxt developers, and I believe it could be beneficial if it were pre-shipped by default with Nuxt.
