### ISSUE TITLE
`transition-[property]` syntax doesn't work with `translate`

### ISSUE THREAD

**Issue by thetarnav** [unocss/unocss#2826]
### UnoCSS version

0.53.4

### Describe the bug

The syntax for using transitions with custom properties doesn't work with the [`translate`](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/translate) property.

### Reproduction

https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIAuAnBA7JAMwHtsBbKAC2IgFNsAuHfJRTWgWgA8OAmKZgTCYwxPB0FFSZDgBYADPPQA%2BAFBQoAd1IBrJKuAB6cBDUGTUMCAxhxMFOliIUGScNHjJbTgqVqNIMS0SHgA5JhaugbGkGagkJbW6LYc9kh8KuqR2HpQCADmCLbRJspAA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUkNikEA&css=MQSwdgtAxgzjBcALA9gNwKYCcA0ACUksMEATEmlrgN4BQuuALpgIZgwA2zD68uADADoArJnQBbANw0AvjRoFocUtTqMWbEAxDIwvJqw5d0uACx8%2BYmLigBXAEYgoEO%2BgBeILAApBJvHz8CJHgAjACUUtJAA&options=N4XyA

**Comment by zyyv** [comment]
Use [property-translate](https://unocss.dev/interactive/?s=property-translate) and `duration-400`.

**Comment by zyyv** [comment]
I will send a pr to try and support it.

**Comment by thetarnav** [comment]
> Use [property-translate](https://unocss.dev/interactive/?s=property-translate) and `duration-400`.

[I'm I trying it wrong?](https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIAuAnBA7JAMwHtsBbKAC2IgFNsAuHfJRTWgWgA8OAmKZgTCYwxPB0FFSZDgBYADPPQA%2BAFBQoAd1IBrJKuAB6cBDUGTsRCgyS2nMOJgoBuISLETXrBOzmKV6lAgxLRIeADkmFq6BsaQZqCQlshoWF52HA4cTkguLMKieFAADtjExfSYAJ6eLHZBAK647uIKSmoawaERUdrYOlC8sSYJFvApNuk%2B9o7OkgUeWTkBGn16UAgA5ggOw-FAA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUkNikEA&css=HQFwTghgdgzgNhEBTAtASyigxjGAuACwHsA3JMAAgG8AoCi8aeRJPCgBmAFYwkBbANw0AvjRqhIsNCDRFMGbLmp0GkmNNlQ2jWAmQUALO3Z8YFLAFcARmiworSAF5pyACk4GANB2%2BcATN4AjACUQsJAA&options=N4XyA)

Also the [property-translate](https://unocss.dev/interactive/?s=property-translate) link doesn't search anything.

![image](https://github.com/unocss/unocss/assets/24491503/c044a2ef-b3ae-4fb8-9fa2-e2f41626928f)

**Comment by zyyv** [comment]
> > Use [property-translate](https://unocss.dev/interactive/?s=property-translate) and `duration-400`.
> 
> [I'm I trying it wrong?](https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIAuAnBA7JAMwHtsBbKAC2IgFNsAuHfJRTWgWgA8OAmKZgTCYwxPB0FFSZDgBYADPPQA%2BAFBQoAd1IBrJKuAB6cBDUGTsRCgyS2nMOJgoBuISLETXrBOzmKV6lAgxLRIeADkmFq6BsaQZqCQlshoWF52HA4cTkguLMKieFAADtjExfSYAJ6eLHZBAK647uIKSmoawaERUdrYOlC8sSYJFvApNuk%2B9o7OkgUeWTkBGn16UAgA5ggOw-FAA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUkNikEA&css=HQFwTghgdgzgNhEBTAtASyigxjGAuACwHsA3JMAAgG8AoCi8aeRJPCgBmAFYwkBbANw0AvjRqhIsNCDRFMGbLmp0GkmNNlQ2jWAmQUALO3Z8YFLAFcARmiworSAF5pyACk4GANB2%2BcATN4AjACUQsJAA&options=N4XyA)
> 
> Also the [property-translate](https://unocss.dev/interactive/?s=property-translate) search link doesn't find anything.
> 
> ![image](https://user-images.githubusercontent.com/24491503/250786544-c044a2ef-b3ae-4fb8-9fa2-e2f41626928f.png)

Sorry, `property-[translate]` https://unocss.dev/interactive/?s=property-[translate]
