### ISSUE TITLE
group-data doesn't work

### ISSUE THREAD

**Issue by Lesik** [unocss/unocss#2827]
### UnoCSS version

0.53.4

### Describe the bug

I'm new to UnoCSS (first project using it) so pardon me if I'm doing something wrong.

I noticed that group-data selectors that work in Tailwind don't seem to work with UnoCSS:

```
<div class="group" data-state="open">
  <span class="group-data-[state=open]:text-red-400">
    hello
  </span>
</div>
```

(Text is supposed to turn red. Instead, the CSS output is simply empty.)

### Reproduction

- [Tailwind Playground](https://play.tailwindcss.com/JrEeGTGxrT) (works)
- [UnoCSS Playground](https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIDmAnA9gVwAd0oQEAXBAWiUvIFMNdD6A7dAPgCgopglCCVrEQoMOAoSplKVANq0KjZmwC6ALgYAPclWz0QVACwAGE5x68oAC3pw4uS8AD0AodxfgIHIA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUkNikEA&css=Q&options=N4XyA) (doesn't work)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by liquiFruit** [comment]
Can confirm I'm having the same problem. I discovered it while using Shadcn-ui with Unocss. I am working on as a solution until UnoCSS catches up to TailwindCSS. It definitely isn't comprehensive, and may even be incorrect, but will hopefully give people a starting point to help them patch in the functionality they need. [Here is it in UnoCSS playground.](https://unocss.antfu.me/play/?html=DwEwlgbgBCCGAusC0BnR8CmBeARAewAcMA7HKAYwBtYUVcBzAJzwFcCcA%2BAKCilEgrVauHlCasCSOIiQBtNAmyESAXQBcAI3pImGEl06Y0wAPTgI3U%2Ba5A&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHABuwqMGFYYrAFxwA2irgB6M3CJV6YALTJhMYXaMA6DwF19phSCfMABaoUACUcAC8AHyIpqrMBKzwUKhEfABKqKzi8BFw-jBBIW4FQQpm1hC2dgqOznYAOkZGAHpwngBUDZ6h%2Bgqt7R2hZqFxcMDocAoAhClpvJnZEuEpMPRQWPkBwVDcqvGJkk7CkXBzGVk5RgCMnm4pYGLCzKgAgmJi5UZN3Z4VADRwABEQNG%2BzgCSwSQhT3YWGEIFQp3OC0uEiMACZPGMxqt1ptlODVKUdoZmLDWPDEf8xqpWKgxKhmDBoIZWJEYgADNyVWxGAAkCDqwlInjggtYpE5NPBpFMcs8NNIoSAA&css=Q&options=N4IgzgLgTglgxhEAuaBXApgGhNAhgOzADMB7KAW2SNwBsx0BfIA) It is based off of [TailwindCSS v3.2 test cases](https://github.com/tailwindlabs/tailwindcss/pull/9559/commits/ad82dadb0c78f77d557626792047f2ae76196da1) for adding dynamic 'data-*' variants. I only implemented exactly what I need for now, but may implement more later. 

```js
(matcher) => {
    const regexResult = matcher.match(/group-(data-\[[^ ]*\]):([^ ]*)/)
    if (!regexResult) return matcher

    const data = regexResult[1].replaceAll(/[\[\]]/g, "")
    const classname = regexResult[2]
    
    return {
        matcher: classname,
        selector: s => `.group[${data}] ${s}`,
    }
}
```
