### ISSUE TITLE
uniapp+vite+unocss（run to the WeChat miniprogram） == Error: EBUSY: resource busy or locked

### ISSUE THREAD

**Issue by StrivingRabbit** [unocss/unocss#2829]
### UnoCSS version

0.53.1

### Describe the bug

After configuring unocss for the vite project, after running the project with 'yarn dev', an error 'Error: EBUSY: resource busy or locked' is reported from time to time：

- git clone https://github.com/StrivingRabbit/uni-app-vue3-scaffold
- pnpm i
- yarn dev:mp-weixin

then wait for ERROR

### Reproduction

https://github.com/StrivingRabbit/uni-app-vue3-scaffold

### System Info

Window 10

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [x] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by notthistrain** [comment]
![image](https://github.com/unocss/unocss/assets/87973979/c17ef873-f493-4528-b47f-69df6270cf45)
I found something similar,i running the project with 'vite build -- watch',the error will be thrown later and build failed,
after i delete "import 'virtual:uno.css'" and run again,the building is running normally.

**Comment by StrivingRabbit** [comment]
@notthistrain where is the "import 'virtual:uno.css'"？

**Comment by notthistrain** [comment]
> @notthistrain where is the "import 'virtual:uno.css'"？

in the entry file index.tsx

**Comment by StrivingRabbit** [comment]
It may be caused by the '/' preceding resolveId '/__uno.css'，It can be viewed in the following code：
```js
// vite.config.js
defineConfig({
 plugins;[
{
	name: 'virtual-file',
	enforce: "pre",
	buildEnd() {
		console.log('watchFiles', this.getWatchFiles());
	},
}
]
})
```

**Comment by notthistrain** [comment]
`
import { defineConfig } from "vite"
import react from "@vitejs/plugin-react"
import unocss from "unocss/vite"
import { reload } from "./reload"
import { resolve } from "path"

export default defineConfig({
  build: {
    watch: {
      exclude: ['node_modules/**', "/__uno.css"]
    },
  },
})
`
after add exclude options, the project has been running for half a day and is still ongoing.

**Comment by StrivingRabbit** [comment]
> after add exclude options, the project has been running for half a day and is still ongoing.
> 
> `export default defineConfig({ build: { watch: { exclude: ['node_modules/**', "/__uno.css"] }, }, })`

YES

One of the methods I use is to trigger stably: when you use unocss, just create a file in the root directory of the disk where the project is located.

After removing '/__uno.css' from 'build watch', the project can be compiled normally without errors

**Comment by notthistrain** [comment]
栓q

> > after add exclude options, the project has been running for half a day and is still ongoing.
> > `export default defineConfig({ build: { watch: { exclude: ['node_modules/**', "/__uno.css"] }, }, })`
> 
> YES
> 
> One of the methods I use is to trigger stably: when you use unocss, just create a file in the root directory of the disk where the project is located.
> 
> After removing '/__uno.css' from 'build watch', the project can be compiled normally without errors
