### ISSUE TITLE
Nuxt 3 + @unocss/nuxt "content.pipeline.exclude" not work.

### ISSUE THREAD

**Issue by chz** [unocss/unocss#2840]
### UnoCSS version

@unocss/nuxt@0.53.4

### Describe the bug

Fresh install Nuxt3 add @unocss/nuxt s module. When provide exlude option it must exclude that dirs. Also you can check it in devtools.

### Reproduction

Fresh install Nuxt3 add @unocss/nuxt.

```
export default defineConfig({
  content: {
    pipeline:{
      // include: ['pages/**/*.vue','components/**/*.vue'],
      exclude: ['node_modules','.git','.output'],
    }
  },
  ...
})
```

It will not work and when build project it will contain classnames from node_modules

but if i uncomment include it will work. 

### System Info

------------------------------
- Operating System: Darwin
- Node Version:     v20.3.0
- Nuxt Version:     3.6.2
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.19
- Builder:          vite
- User Config:      devtools, modules
- Runtime Modules:  @unocss/nuxt@0.53.4
- Build Modules:    -
------------------------------

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by xinlei3166** [comment]
mark

**Comment by chz** [comment]
> mark

mark what ?)
