### ISSUE TITLE
uniapp 上使用运行到h5正常，当运行到手机就报错 [plugin:unocss:global:build:scan] [postcss] D:/代码/zzt-uniapp-vue3-vite/app-service.js-unocss-hash.css:1:103107: Missed semicolon

### ISSUE THREAD

**Issue by baiyajin** [unocss/unocss#2847]
### UnoCSS version

"unocss": "^0.53.4",

### Describe the bug

[plugin:unocss:global:build:scan] [postcss] D:/代码/zzt-uniapp-vue3-vite/app-service.js-unocss-hash.css:1:103107: Missed semicolon

uniapp package.json 依赖如下

  "dependencies": {
    "@dcloudio/uni-app": "3.0.0-3080420230531001",
    "@dcloudio/uni-app-plus": "3.0.0-3080420230531001",
    "@dcloudio/uni-components": "3.0.0-3080420230531001",
    "@dcloudio/uni-h5": "3.0.0-3080420230531001",
    "@dcloudio/uni-mp-alipay": "3.0.0-3080420230531001",
    "@dcloudio/uni-mp-baidu": "3.0.0-3080420230531001",
    "@dcloudio/uni-mp-jd": "3.0.0-3080420230531001",
    "@dcloudio/uni-mp-kuaishou": "3.0.0-3080420230531001",
    "@dcloudio/uni-mp-lark": "3.0.0-3080420230531001",
    "@dcloudio/uni-mp-qq": "3.0.0-3080420230531001",
    "@dcloudio/uni-mp-toutiao": "3.0.0-3080420230531001",
    "@dcloudio/uni-mp-weixin": "3.0.0-3080420230531001",
    "@dcloudio/uni-quickapp-webview": "3.0.0-3080420230531001",
    "pinia": "^2.0.12",
    "vconsole": "^3.15.1",
    "vue": "^3.2.45",
    "vue-i18n": "^9.1.9"
  },
  "devDependencies": {
    "@dcloudio/types": "^3.3.2",
    "@dcloudio/uni-automator": "3.0.0-3080420230531001",
    "@dcloudio/uni-cli-shared": "3.0.0-3080420230531001",
    "@dcloudio/uni-stacktracey": "3.0.0-3080420230531001",
    "@dcloudio/vite-plugin-uni": "3.0.0-3080420230531001",
    "@iconify/json": "^2.2.76",
    "@iconify/vue": "^4.1.1",
    "@types/node": "^20.3.0",
    "@unocss/preset-icons": "^0.53.4",
    "sass": "^1.63.2",
    "sftp-uploader": "^1.0.3",
    "unocss": "^0.53.4",
    "unplugin-icons": "^0.16.3",
    "unplugin-vue-components": "^0.25.1",
    "vite": "4.3.9"
  }

### Reproduction

[plugin:unocss:global:build:scan] [postcss] D:/代码/zzt-uniapp-vue3-vite/app-service.js-unocss-hash.css:1:103107: Missed semicolon

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by chizukicn** [comment]
Please use [unocss-applet](https://github.com/unocss-applet/unocss-applet) or [unocss-preset-weapp](https://github.com/MellowCo/unocss-preset-weapp)

**Comment by baiyajin** [comment]
谢谢指点，感激不尽。
