### ISSUE TITLE
Playground  long press problem

### ISSUE THREAD

**Issue by chizukicn** [unocss/unocss#2848]
### UnoCSS version

0.53.4

### Describe the bug

if long pressed  on playground editor, cursor will move to end and copy

https://github.com/unocss/unocss/assets/16945858/38dd45a9-1a57-41a5-8aba-c00f23ba67e5

### Reproduction

https://unocss.dev/play/

or
```
nr play
```
### System Info

Browser: **Only Microsoft Edge (Windows / macOS both)**, Safiri and Chrome not reproduction

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ziloen** [comment]
Disable "Immersive Translate" extension
