### ISSUE TITLE
Nested presets (using preset in a preset)

### ISSUE THREAD

**Issue by silveltman** [unocss/unocss#2850]
### Clear and concise description of the problem

Being able to set one or more presets within a preset, so that if the parent preset is used, all the child presets are used too. 

### Suggested solution

Same syntax as the regular uno.config.ts

### Alternative

Something similar might be possible by destructurting a preset into antoher one or something. Not sure though, since I'm a UnoCSS beginner.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
It's already supported. Otherwise please provide more details description for what you want. Thanks.
