### ISSUE TITLE
[RFC] support background opacity with css var

### ISSUE THREAD

**Issue by zhihengGet** [unocss/unocss#2851]
### Clear and concise description of the problem

currently if i have 

preflight that returns an css var :  ` --primary=0 0 0 1`

`hsla(var(--primary)) `defined in theme, and use it as  bg-primary/5 , this won't work, opacity isn't applied

i think nested boxShadow does not work also,  `shadow-border-light`  

repro: 
https://unocss.dev/play/?html=FAHgJglgbgBARgcwLQHcAWEAuBTGM1IBmArgDal4w4AemSAxtgHY4BOMhp21MAztl3p0mAeya4AhuQBcmVhKa8sEMUgAsABg3wRrMNlbqdeg0lbYwSAKxaYAPmB5w0PmglgRKJHF37DpCAQ0TBgAW2okCWJMEUoaOjhSCXoAazwfE0M1Yz8zCyQARls7HF5MEAB6SCgHRydqmHok3l4AXgAiXjcPLwzcgKCQ8Mjo2Lx47yTU9N9TbL7Tc0si7UQkAAdWCFCJVgBPCoBmDXaYdpLsMoAmSuqHW%2BgHIA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCVCIlhO3gAWMHShEaj%2BqHCkjAQAyl2hfnAwtRggGMUAlHAAvAB8cAAGkajB2hAwrW2JiTSg9lD8oQBMRwB0BxkALADsx%2BcApBkAjA%2Bnt3DkAAzHAKwA3Iuom22IF2-AeoUu70eAGZIXBLg8-m1UGpFgtkUgKlQ6LVoDBYg1Qut9LF4klsbj8Xo8jArDBEk5SANaYloPZcB04DiAG4YKDBGmWOk0%2BxOMzI2QiBSNcKLSWMZQQHxjWTCeSMFhsTg8Pj8JUquSiGCSaR%2Bf5wOgSEUYULPM5miRoXB5eowMCNAD07voIGO2PdYraamV5Vkg2G1qJ2WgjSJqAAkECQYSkHHU3HPQARACiADEmIoADIAFWddCc9h8XN2PkB7GBezGY3SKbT2bzhZL%2BigpA4FarUBrWzrIIejebabjWGgGFI2kMaFL5cr1drOz2iSntFnEHnY5bcZRSLU%2BtTHAgli6tXsaAgAHdk2maqR6ry8t3ez5YV%2BMp8HgA2CZ3jASw4AeYC4HOYDx1TJ96jfHsKwATkQjJkNQlC4E%2BA5APAg5wIADnAoDLGguM6DAXYGGCfc43yBDPx-RjMNOL4cJAr5IPYr5gIyd8K2-TCf2OB5sMw8DEhE8CYR4uA%2BIYwSFN-UTiIg8C-xkuSBK-YTLjY0C8JAh4oQ0%2BitKE95EL0xJjPY4CflIs8oEwPlEBo2CYHgj8zOY-89LAkDON4nsfC%2BB4MlC8LRzEkCVJUmzSLjdzXxo2jNKY7SHl06K4ESA4bLgA5uJi8C8AUIKvPSoSHlY7LrPUkDpOKkDSsYcr%2BMqnyrMuRDwPOWKStwMrZNMjrPneADsoM0CTIqxTzMs7LOIKmb2rm5iLL0wiApW%2BStOODbsv-Aidu8saFriqajpI-cUVTQ9iiQIMkCAA&css=Q&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g

### Suggested solution

https://tailwindcss.com/docs/customizing-colors#using-css-variables

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by chizukicn** [comment]
This seems to be possible through presets, such as [unocss-preset-palette](https://github.com:chizukicn/unocss-preset-palette)
