### ISSUE TITLE
transformer-compile-class changes neither generate nor update

### ISSUE THREAD

**Issue by oy-paddy** [unocss/unocss#2866]
### UnoCSS version

0.53.5

### Describe the bug

> in playground

`<button bg-white class=':uno-my-test: text-(black 2xl) w-22 h-22'>你好</button>`

When you change

`<button bg-white class=':uno-my-test: text-(black 2xl) w-22 h-10'>你好</button>`

**It is not compiled and updated**

> in my project **Error screenshot**

<img width="1315" alt="image" src="https://github.com/unocss/unocss/assets/24783915/7ec697a0-e812-4a84-aba9-408c48654b71">
<img width="1216" alt="image" src="https://github.com/unocss/unocss/assets/24783915/f2b286b8-17c0-40cc-a675-3c65bb768b8b">
<img width="1362" alt="image" src="https://github.com/unocss/unocss/assets/24783915/75c21289-d0c3-446a-9784-b4b9a4335c8a">

https://github.com/unocss/unocss/assets/24783915/1de2aded-55a6-4a2b-a9ac-1fb2e00a64bf

### Reproduction

[playground](https://unocss.dev/play/?html=DwBwBAxgNghgznAvAIggVzgFwPYFsC0cAFtgE6bqbIB8ATLcAPQjUBQwAJgJYBuksCFCHwAWGgGZJtcU2482ofvCTJcAI3wBGMMJFg1ZDgFNSNEeZFMWrdmrSYcAO30BzfAHciXTEaWCA5ABcaI7Y%2BLgAnvg%2BWIFgPgAemPgAFGqwEADWYLQJUACUYO749GBEJbT%2B1IAG8oC%2Bmkx2DtiO1EA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcEWWwCGuOlmggMUAGrr2mmAHEoELmDVRN23fqLhgAG0Kv1dOkgC%2BcLEsQOAByLhUJbxCkJAwAD0hYdGx1Lld4TBx8IhJgUgAKZFQoNPoALjgAbSpUSpCJLjoYCBAAWhL3EPJEOClXaAqQ2jQQuF8AXSpx2ToAC2gYBpg6CqLUUIamlta5haWQwbBWgBY4EA5WgEY4GHiYdowRql8hDS0dKD0oFaqam7t3o4oM4wG4PF46IU-qgJJ5vAAFWg4OKDKz8TSkVpdAD02MAG3mAEujALJKgAB-QAw-4B75UAmYoUwCwclT8vTCYBGHUA9GbhCCtQDxaYAucwAlIAgBkA-vKACldACFugDfTQCYCmUOa04gqKr04XQALwAIllKlatyaZXVcEANvGAI2NAHAqgC45ZUQjVojE6%2BgwdV-Xx82SoN4OT76IwmXDmSzWfKulDTKgiBQ-arrOSiJQqINumMKFhsTg8Pj8BN-cPiKRaKHR1B0CTqdwVS4AOgATImYWhcINZqwwCtcfQQBW5tjotGXbJJi6kEA&css=Q&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g)

### System Info

mac: 13-inch, 2018 os:13.4.1
chrome:114.0.5735.198

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by oy-paddy** [comment]
This is similar to the previous problem, except that here we use a custom class prefix. I have seen that it is said that this problem has been solved, but in fact there is still a problem. Referenc：[playground](https://unocss.dev/play/?html=DwBwBAxgNghgznAvAIggVzgFwPYFsC0cAFtgE6bqbIB8ATLcAPQjUBQwAJgJYBuksCFCHwAWGgGZJtcU2482ofvCTJcAI3wBGMMJFg1ZDgFNSNEeZFMWrdmrSYcAO30BzfAHciXTEaWCA5ABcaI7Y%2BLgAnvg%2BWIFgPgAemPgAFGqwEADWYLQJUACUYO749GBEJbT%2B1IAG8oC%2Bmkx2DtiO1EA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcEWWwCGuOlmggMUAGrr2mmAHEoELmDVRN23fqLhgAG0Kv1dOkgC%2BcLEsQOAByLhUJbxCkJAwAD0hYdGx1Lld4TBx8IhJgUgAKZFQoNPoALjgAbSpUSpCJLjoYCBAAWhL3EPJEOClXaAqQ2jQQuF8AXSpx2ToAC2gYBpg6CqLUUIamlta5haWQwbBWgBY4EA5WgEY4GHiYdowRql8hDS0dKD0oFaqam7t3o4oM4wG4PF46IU-qgJJ5vAAFWg4OKDKz8TSkVpdAD02MAG3mAEujALJKgAB-QAw-4B75UAmYoUwCwclT8vTCYBGHUA9GbhCCtQDxaYAucwAlIAgBkA-vKACldACFugDfTQCYCmUOa04gqKr04XQALwAIllKlatyaZXVcEANvGAI2NAHAqgC45ZUQjVojE6%2BgwdV-Xx82SoN4OT76IwmXDmSzWfKulDTKgiBQ-arrOSiJQqINumMKFhsTg8Pj8BN-cPiKRaKHR1B0CTqdwVS4AOgATImYWhcINZqwwCtcfQQBW5tjotGXbJJi6kEA&css=Q&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g) [issue:2667](https://github.com/unocss/unocss/issues/2667)

**Comment by greenhat616** [comment]
ENV: Nuxt + UnoCSS

-------

Same issue, and I dont use custom prefix. `transformer-compile-class` will generate prefix-shortcode instantly, however, not generate css in _unocss.css file.

**Comment by arkaroy135** [comment]
I am facing the same issue. I have to restart the server every time manually to see the transformer's effect.
