### ISSUE TITLE
Disable autocomplete for attributify props when not using that mode in VSCode

### ISSUE THREAD

**Issue by thetarnav** [unocss/unocss#2867]
The autocomplete for classes in vscode works great, but it also shows same suggestions when tying component props even though I'm not using the attributify mode.

![image](https://github.com/unocss/unocss/assets/24491503/7702fdc3-e75b-4d33-a3d9-9651e9b26421)

Since there is no setting for it, I'm guessing that is either by design or not implemented?

### Suggested solution

It would make sense to either disable/enable it manually or based on the configuration as the attributify mode has to be explicitly enabled there to work.

**Comment by chizukicn** [comment]
You can try to explicitly set a presetUno in uno.config.ts, since presetAttributify is set by default

**Comment by ziloen** [comment]
@chizukicn Even all presets are deleted, the contents of the rules are still autocomplete. The VSCode extension does not detect if the attribute context

**Comment by antfu** [comment]
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example). Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by ziloen** [comment]
@antfu Here is a reproduction [GitHub repo](https://github.com/ziloen/reproduction-unocss-230810)

**Comment by ap32** [comment]
I'm not using attributify and it messes up autocompletion in vscode. Need an option to disable attributify in vscode plugin

**Comment by chizukicn** [comment]
I wrote a test to pinpoint the cause of this issue. I thought it might be an issue with `searchUsageBoundary` matching too large a range in `jsx` files @antfu 
https://stackblitz.com/edit/vitest-dev-vitest-sbpput?file=test%2Fsuite.test.ts
<img width="331" alt="image" src="https://github.com/unocss/unocss/assets/16945858/f663e91b-19be-41eb-a1d1-90ca4d218e99">

**Comment by arisris** [comment]
any update for this issue?

**Comment by tealina** [comment]
My solution: 
1. Create uno.config.ts on your root folder
2. Config Presets to `presetMini()`
```ts
import { defineConfig } from 'unocss'
import presetMini from 'unocss/preset-mini'
export default defineConfig({
  presets: [presetMini()],
})

```
3. Reload Uno CSS plugin

**Comment by moHaHa** [comment]
any update pleaze for this ?? 
@antfu

**Comment by MrWangJustToDo** [comment]
waiting...
