### ISSUE TITLE
Auto completion is missing

### ISSUE THREAD

**Issue by ElvinKyungu** [unocss/unocss#2870]
### Clear and concise description of the problem

As a developer using UnoCSS, I want auto-completion to be in real time to make development faster and more efficient, I feel like I'm wasting my time when I write everything manually.

### Suggested solution

Add a mechanism so that when the unocss extension is installed, it can be used for rapid development thanks to a real-time auto-completion system.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by kedniko** [comment]
You have to enable `quickSuggestions` in vscode. Add this in `settings.json`

```
{
  "editor.quickSuggestions": {
    "strings": true
  }
}
```

Alternatively you can trigger suggestions by pressing `ctrl`+`space` (on windows)

**Comment by ElvinKyungu** [comment]
okay, thanks i try it
