### ISSUE TITLE
[vite] Layers ordering not working properly

### ISSUE THREAD

**Issue by slavamak** [unocss/unocss#2871]
### UnoCSS version

0.53.5

### Describe the bug

I see that this issue https://github.com/unocss/unocss/issues/2823 is closed, but I still don't have it working as expected. I have updated the packages but it still doesn't work. Could you please take a look at it again? Maybe I'm doing something wrong?

### Reproduction

https://stackblitz.com/edit/vitejs-vite-9ajbji

### System Info

Vite 4.4.3

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zoeyzhao19** [comment]
![image](https://github.com/unocss/unocss/assets/70888488/65905939-25dc-493f-9739-ed30dd02e76e)

I prettied the build result, Does not this what you want?

**Comment by slavamak** [comment]
@zoeyzhao19 Yeah it seems to be working fine now, thanks!
