### ISSUE TITLE
The custom rules in unocss are not effective when using CDN runtime. 

### ISSUE THREAD

**Issue by popdo** [unocss/unocss#2875]
### UnoCSS version

cdn

### Describe the bug

```htm
<script src="https://cdn.jsdelivr.net/npm/@unocss/runtime"></script>
<script>
window.__unocss = {
  rules: [
    ['text-muted', { color: '#868e96' }],
    ['color-base', { color: 'var(--v-gray-dark)' }],
    [/^text-(primary|secondary|success|info|warning|danger)$/, ([, c]) => ({ 'color': `var(--v-${c})` })],
    [/^bg-(primary|secondary|success|info|warning|danger)$/, ([, c]) => ({ 'background-color': `var(--v-${c})` })]
  ]
}
</script>
```
Whether they are placed in the head or at the bottom of the body in the HTML, the rules will not take effect.

### Reproduction

```htm
<script src="https://cdn.jsdelivr.net/npm/@unocss/runtime"></script>
<script>
window.__unocss = {
  rules: [
    ['text-muted', { color: '#868e96' }],
    ['color-base', { color: 'var(--v-gray-dark)' }],
    [/^text-(primary|secondary|success|info|warning|danger)$/, ([, c]) => ({ 'color': `var(--v-${c})` })],
    [/^bg-(primary|secondary|success|info|warning|danger)$/, ([, c]) => ({ 'background-color': `var(--v-${c})` })]
  ]
}
</script>
```
Whether they are placed in the head or at the bottom of the body in the HTML, the rules will not take effect.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by exside** [comment]
@popdo you have to define them BEFORE you load the runtime:

```
<script>
window.__unocss = {
  rules: [
    ['text-muted', { color: '#868e96' }],
    ['color-base', { color: 'var(--v-gray-dark)' }],
    [/^text-(primary|secondary|success|info|warning|danger)$/, ([, c]) => ({ 'color': `var(--v-${c})` })],
    [/^bg-(primary|secondary|success|info|warning|danger)$/, ([, c]) => ({ 'background-color': `var(--v-${c})` })]
  ]
}
</script>
<script src="https://cdn.jsdelivr.net/npm/@unocss/runtime"></script>
```

this will work!

It's because runtime checks `window.__unocss` global var when initializing:

https://github.com/unocss/unocss/blob/580a30165a021365e6f426277486ec0b1161274c/packages/runtime/src/index.ts#L114
