### ISSUE TITLE
Please provide a code example for integrating unocss with react+webpack

### ISSUE THREAD

**Issue by cong1223** [unocss/unocss#2880]
### Clear and concise description of the problem

As the title suggests.

### Suggested solution

none

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by henrikvilhelmberglund** [comment]
Does this not work? https://unocss.dev/integrations/webpack#installation

**Comment by quangkhaidam93** [comment]
> https://unocss.dev/integrations/webpack#installation

I found that `import "uno.css"` is not working (with some errors related to import this file) → don't know why and how to fix it.

Instead, I use `postcss` and use directive `@unocss` in `index.css` file. It works perfectly.
