### ISSUE TITLE
Eslint rule @unocss/order-attributify doesn't work

### ISSUE THREAD

**Issue by MrFoxPro** [unocss/unocss#2883]
### UnoCSS version

0.53.5

### Describe the bug

Eslint rule `@unocss/order-attributify` doesn't show error and doesn't sort attributes.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-vxgncx?file=.eslintrc

Run `npm run lint`

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by pywuziming** [comment]
yup，I also meet it. Excuse me,  did you solve this problem?

**Comment by MrFoxPro** [comment]
No

> yup，I also meet it. Excuse me, did you solve this problem?

No
