### ISSUE TITLE
The requested module '@unocss/vite' does not provide an export named 'default'

### ISSUE THREAD

**Issue by sh-web-lee** [unocss/unocss#2900]
### UnoCSS version

0.53.6

### Describe the bug

This is my first time using unocss.I follow the steps of the official documentation: installation, import, and finally when the project is started, the console throws an error ”The requested module '@unocss/vite' does not provide an export named 'default'“
![QQ图片20230722150856](https://github.com/unocss/unocss/assets/82861708/9264de87-d08d-404e-bbef-0eec83411cf0)
![QQ图片20230722150833](https://github.com/unocss/unocss/assets/82861708/45e0aaef-ce32-42af-95f1-3e079872c0ab)

### Reproduction

https://github.com/sh-web-lee/unocss-issue.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by henrikvilhelmberglund** [comment]
I cloned your repro but it works for me. Maybe try removing your package lock file and node modules folder and try installing again. Also when you get it working don't forget to add `import 'virtual:uno.css'` in main.ts

**Comment by sh-web-lee** [comment]
> I cloned your repro but it works for me. Maybe try removing your package lock file and node modules folder and try installing again. Also when you get it working don't forget to add `import 'virtual:uno.css'` in main.ts
It does't work.

**Comment by henrikvilhelmberglund** [comment]
1. Delete package-lock.json
2. Delete /node-modules
3. `npm install`
4. `npm run dev`

Do you get the same error?

**Comment by pegiadise** [comment]
If you are on a monorepo, check that you have the same version in all your packages because the resolution starts from the top hoisted node_modules, so you might get an version mismatch.
