### ISSUE TITLE
Support additional config `letter-spacing` inside `fontSize`

### ISSUE THREAD

**Issue by steakscience** [unocss/unocss#2906]
### Clear and concise description of the problem

Currently, UnoCSS supports specifying font size inside the fontSize theme config:
```js
theme: {
    fontSize: {
      sm: ['15px'],
    },
```
or additionally, also specify line-height:
```js
theme: {
    fontSize: {
      sm: ['15px', '1.5em'],
    },
```
Similar to Tailwind theme config, we should also allow an additional config for letter-spacing:
```js
theme: {
    fontSize: {
      sm: ['15px', '1.5em', '-0.004em'],
    },
```
This is helpful for typesetting for perfect looking text :)

### Suggested solution

Allow an optional additional config inside the array:

```js
theme: {
    fontSize: {
      sm: [size, line height, letter-spacing],
    },
```

```js
theme: {
    fontSize: {
      sm: ['15px', '1.5em', '-0.004em'],
    },
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by everyx** [comment]
I think the way of tailwind is very good and flexible

```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    fontSize: {
      '2xl': ['1.5rem', {
        lineHeight: '2rem',
        letterSpacing: '-0.01em',
        fontWeight: '500',
      }],
      '3xl': ['1.875rem', {
        lineHeight: '2.25rem',
        letterSpacing: '-0.02em',
        fontWeight: '700',
      }],
    }
  }
}
``` 

https://tailwindcss.com/docs/font-size#customizing-your-theme
