### ISSUE TITLE
This PR will cause problems with the JSX conversion

### ISSUE THREAD

**Issue by Wxw-Gu** [unocss/unocss#2907]
### UnoCSS version

0.53.6

### Describe the bug

`transformer-attributify-jsx`  this [PR](https://github.com/unocss/unocss/pull/2334) `elementRE `can cause many conversion errors，that cause the page stuck

### Reproduction

https://stackblitz.com/~/github.com/Wxw-Gu/dF1-cE2-cF4-k

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Wxw-Gu** [comment]
Repeat the steps: find home.tsx and remove the comments，Terminal. browser will crash
![error22](https://github.com/unocss/unocss/assets/84499436/1afc3106-fd83-401f-80a3-42e375df3456)

**Comment by zhiyuanzmj** [comment]
In v0.55.7 this will be resovled.
