### ISSUE TITLE
`transformerDirectives` doesn't work with lightningcss.

### ISSUE THREAD

**Issue by MrFoxPro** [unocss/unocss#2910]
### UnoCSS version

0.53.6

### Describe the bug

Error when using @apply at css and setting `css.transformer = 'lighningcss'` in Vite
```
8:26:31 PM [vite] Internal server error: Unknown at rule: @apply
  Plugin: vite:css
  File: /@toad/home/foxpro/craft/sferadel/next/web/core/app.scss:18:13
  16 |     }
  17 |     body {
  18 |        @apply dark:(bg-gray-900 color-white-000);
     |               ^
  19 |     }
  20 |  
  ```

### Reproduction

https://github.com/MrFoxPro/unocss-directives-lighningcss

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zoeyzhao19** [comment]
`@appy` is support by other css pre-processors or css language, but not lightingcss. you can change to `--at-apply` as the [document](https://unocss.dev/transformers/directives#at-apply) said
