### ISSUE TITLE
Custom container variants are sorted alphabetically instead of as given

### ISSUE THREAD

**Issue by cheshirecode** [unocss/unocss#2913]
### UnoCSS version

0.53.5

### Describe the bug

```
  theme: {
  "containers": {
    "xs": "(min-width: 480px)",
    "sm": "(min-width: 640px)",
    "1sm": "(min-width: 640px)",
    "lg": "(min-width: 1024px)",
    "2lg": "(min-width: 1024px)",
    "md": "(min-width: 768px)",
    "xl": "(min-width: 1280px)",
    "xxl": "(min-width: 1440px)",
    "2xl": "(min-width: 1536px)",
    "xxxl": "(min-width: 1920px)",
    "4xl": "(min-width: 2560px)"
  }
}

```

will generate this output whereby CSS for both `lg` and `2lg` breakpoints come before `sm` one, thus they get overriden when container size exceeds `lg` breakpoint

```
@container (min-width: 1024px) {
  .\@2lg\:border-blue {
    --un-border-opacity: 1;
    border-color: rgba(96, 165, 250, var(--un-border-opacity));
  }
}
@container (min-width: 640px) {
  .\@1sm\:border-black {
    --un-border-opacity: 1;
    border-color: rgba(0, 0, 0, var(--un-border-opacity));
  }
}
```

as can be observed in the playground link (black border instead of blue). This feels similar to https://github.com/unocss/unocss/pull/784 but for container queries instead.

### Reproduction

https://uno.antfu.me/play/?html=DwEwlgbgBAFgtARgAxKgFwKYA81wMYYB2mATlAGYA22UAzhtXroQPaEZQCGllAXGiU6FaYNGDZwALCgBQUKHkqdatALwAiAOYkwIfC0q04AbU4BXNCwD6CciRt2H985YC6UYwDIAfL1ZoACl4lWlw8GDBKEABKV14AgCMWEhAMEjgAJigklLS4ASFaAAdOEiI0bOTU9IS4MpBK3PTKOATKMwxo9Tkobx7QSAUQtXUAdzhyMx5YRFQEzTgATwZKFlH1b3lgAHpwCD6tvaHlEfHJ6fhkbIXlnjWNrd3IA6gB6EUTjTOpyhmr%2BaWK3um1eT32-SOHxUXwmPz%2BcxuQPWIJ2ez6qOeMje1zqGAa8AyqHGGQArKgoSMAAJ4NhoThgdgkDYQwYUjQ5apQSmUTTxDl5NodaJc2gAWz5VQFSjwAGthfCoON-gtRhFMOooNt0WD0UdOAlaAYLBwkmhLKK4CSoDpNDBcKhqOR7ehsGFymkoCwigBmVDkUa%2BpAvCSpUVCBoAdqgDNCQgqUfOlEWCjMoRYorAAC99dQsTqgA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcEWWwCGuOlmggMUAGrr2mmAHEoELmCQBfOFksg4Aci4qJdOi6RIMAD0hYdGx1LgAbeEwcfCISYFIACmRUKAj6AC44AG0qVGyXCS46GAgQAFo08IwXckQ4KXDoLJdaNBc4WwBdKi7ZOgALaBgimDoslNRXIpKy8sHh0ZcWmACYcvDSOFX-dehNUgw4IYA3fQyd9dX1cJ9UW1kRBXGcvLlRJRVEgEpZYXlGCw2JweHx%2BD8-u8FJJpMk3qg6BIbhgsgBGAB0ACZIagJGhcC0BqwwOMAPSk%2BggdGDUl3Ka2X69NRQTTaXT6F7ZDRaHRQPSGYzAUwWKxgH59KgwAYYPQTN5SXAwdR4Dly1D%2BF4uRIgPDlADuwDQUqyABYABwABjA-m%2BtSodBALW1uoNRoGWQAbCarTbaqgqJsnTrcPrDca4KiLZiTdbbbIQGggy6w%2B64AB2D1m2N29XhJMh13h1GYy3Z2T%2Bfx51zOgsptEm71lqguTGV5bV4Oht1ogCsAGYPU31RWq1rO4XU6iAJyYn1x5smtv5rvhzE9j1zu22Xz3OzfJBAA&css=Q&options=N4IgTgpgzgDg9gOygSwG4RALgGYEMA2UEANCAC5i5LZxgC2WehEAvkA

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zoeyzhao19** [comment]
@cheshirecode  [Unocss breakpoints usage is different Windi CSS](https://unocss.dev/presets/wind#breakpoints)
Try class like `lg:border-blue sm:border-black`

**Comment by cheshirecode** [comment]
@zoeyzhao19 thanks for replying! This is different though, `lg:border-blue` is for media query (which works as intended). My usage was for [container query](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Container_Queries), which was coded [here](https://github.com/unocss/unocss/blob/main/packages/preset-mini/src/_variants/container.ts).

Compare the output of `lg:border-blue` 
```
@media (min-width: 1024px) {
  .lg\:border-blue {
    --un-border-opacity: 1;
    border-color: rgba(96, 165, 250, var(--un-border-opacity));
  }
}
```

with `@lg:border-blue`
```
@container (min-width: 1024px) {
  .\@lg\:border-blue {
    --un-border-opacity: 1;
    border-color: rgba(96, 165, 250, var(--un-border-opacity));
  }
}
```

and the issue is as I wrote in description, generated container queries are in the wrong order whereas generated media queries are correct. see the output for `lg:(border-yellow) sm:(border-red) @lg:(border-blue) @sm:(border-black)` 

```
@container (min-width: 1024px) {
  .\@lg\:border-blue {
    --un-border-opacity: 1;
    border-color: rgba(96, 165, 250, var(--un-border-opacity));
  }
}
@container (min-width: 640px) {
  .\@sm\:border-black {
    --un-border-opacity: 1;
    border-color: rgba(0, 0, 0, var(--un-border-opacity));
  }
}
@media (min-width: 640px) {
  .sm\:border-red {
    --un-border-opacity: 1;
    border-color: rgba(248, 113, 113, var(--un-border-opacity));
  }
}
@media (min-width: 1024px) {
  .lg\:border-yellow {
    --un-border-opacity: 1;
    border-color: rgba(250, 204, 21, var(--un-border-opacity));
  }
}
```

**Comment by zoeyzhao19** [comment]
Sorry for the misunderstanding  😢

**Comment by cheshirecode** [comment]
bump for visibility
