### ISSUE TITLE
(`shadow-dom` + Svelte) `class:` directives do not work in custom elements

### ISSUE THREAD

**Issue by ibhuu** [unocss/unocss#2917]
### UnoCSS version

0.53.6

### Describe the bug

When building a custom element, the `:class` directive does not seem to work. The classes applied depending on conditions are not reflected.

### Reproduction

Small reproduction repo can be found [here](https://github.com/ibhuu/svelte-class-example). In the `vite.config.js` file, uncomment `mode: shadow-dom`, and comment `import 'virtual:uno.css'` in the `main.js` file to see the `:class` directive not working in a custom element (both the `h1` text color and `button` background-color (after clicking once) do not change).

### System Info

Linux 6.1.38-1, Firefox and Chrome.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jacob-8** [comment]
I've never played with either shadow-dom more nor svelte custom elements and so am not the one to find a solution but wanted to confirm from the repro that indeed conditional classes such as `class:bg-orange-500={count > 0}` are not properly placed into the `style` block by using `@unocss-placeholder` in `shadow-dom` mode.
