### ISSUE TITLE
Unable to override default variant `hover`

### ISSUE THREAD

**Issue by Rock070** [unocss/unocss#2919]
### UnoCSS version

0.53.6

### Describe the bug

I'm trying to override the default variant `hover` in the Unocss configuration to only apply hover styles when the device supports it. I've tried using the following configuration:

```ts
// config
variants: [
  (matcher) => {
    if (!matcher.startsWith('hover:')) return matcher
    return {
      matcher: matcher.slice(7),
      parent: '@media (hover) and (pointer: fine)',
      selector: s => `${s}:hover`,
    }
  }
]
```

However, it seems that the override for 'hover' variant doesn't work as expected. The generated CSS doesn't intercept the `hover` variant. Instead, if I change the prefix to any other value like `foohover:`, it works as expected:

```js
// config
variants: [
  (matcher) => {
    if (!matcher.startsWith('foohover:')) return matcher
    return {
      matcher: matcher.slice(9),
      parent: '@media (hover) and (pointer: fine)',
      selector: s => `${s}:hover`,
    }
  }
]
```

### Expected Output

The hover styles should be wrapped in the '@media (hover) and (pointer: fine)' query as shown in the Playground example when using 'foohover:'.

### Actual Output

The hover styles are not wrapped in the '@media (hover) and (pointer: fine)' query, and the override for the 'hover' variant doesn't seem to work.

### Reproduction

[playground](https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIAWB7CBTAJwC4AjAcwFoC8R0A%2BAKCmampAeAHpwJGg&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcEWWwCGuOlmggMUACLBaE3gDd6lAL5wsUCCDgByLiol06TpEgwAPSLDo2OpcADbwmDj4RCTApAAUyKhm6uyaMHQAXHAA2lSocPEg6jASABb6AJRwALwAfIjeBXB8hQCExaUVUAB0dDCpGQDqwDBl8U5lEBZQmU6VlfkFtDBcULhwneX6SytrG0nNmyXbs8dd%2Bn2hwBIY8QDslbLNYKkYuDDZTgACemjA6kKUxm1U0aEKkDwMH02SiGEqTmeBQYoQwpmg2TotQaAAMACQIOhWTLA-Q4pFWKiU1AAXTUUE02l0MNyGi0OigekMxjR5no8UqdKaclEGWyeRe8kYyggAqRIgULDYnB4fH4cqWCvEUi0iSWqDoEnUqOyAEYegAmJGoCRoXBfMqsMBZAD0LvoID6ZRdiKWVieVCF-qQQA&css=Q&options=N4XyA)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by henrikvilhelmberglund** [comment]
Maybe not a solution to this issue but there is `@hover:` which does what you want.

**Comment by Rock070** [comment]
Thank you for the suggestions, and this is the approach I'm currently using as well. However, I can't help but wonder if unocss provides the flexibility to override the hover variant 🙏.

**Comment by zoeyzhao19** [comment]
@Rock070  you can use the `order` option to override the default **@hover** variant util

**Comment by Rock070** [comment]
@zoeyzhao19 

Thank you very much for your help. This undoubtedly solved my problem, and I will close this issue. 

Once again, thanks to unocss and everyone who kindly assisted me.
