### ISSUE TITLE
install with `pnpm`,  config file has type error `ts(2742)`

### ISSUE THREAD

**Issue by liuzw2579** [unocss/unocss#2921]
### UnoCSS version

0.53.6

### Describe the bug

![image](https://github.com/unocss/unocss/assets/30503937/71ab9555-13fc-43bf-8994-b1ac07fef1ec)

### Reproduction

no

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
It works fine, check our example to adjust appropriately. https://unocss.dev/guide/#examples

**Comment by liuzw2579** [comment]
> It works fine, check our example to adjust appropriately. https://unocss.dev/guide/#examples

This reply repo: `git@github.com:liuzw2579/uno-demo.git`

This repo use `pnpm`, init by `pnpm init vue@latest`, default set `Referenced projects`, `tsconfig.node.json` include `uno.config.ts`, and must `composite: true`.

`pnpm & composite` break `uno.config.ts`, but `vite.config.ts` or `vitest.config.ts` no.

it seems in https://github.com/microsoft/TypeScript/issues/42873.

![image](https://github.com/unocss/unocss/assets/30503937/2294cdf8-fe77-4a54-83c3-5c08d1af5eb3)

**Comment by WangQ98** [comment]
> 

I have also encountered this problem, is there any solution

**Comment by zyyv** [comment]
Can you provide a minimal reproduction repo?

**Comment by liuzw2579** [comment]
> git@github.com:liuzw2579/uno-demo.git

https://github.com/liuzw2579/uno-demo.git

**Comment by zyyv** [comment]
Work fine? https://stackblitz.com/github/liuzw2579/uno-demo?file=uno.config.ts

<img width="600" alt="image" src="https://github.com/unocss/unocss/assets/42139754/be743c42-01cf-4644-94dc-8b9e61d298db">

**Comment by liuzw2579** [comment]
> Work fine? https://stackblitz.com/github/liuzw2579/uno-demo?file=uno.config.ts
> 
> <img alt="image" width="600" src="https://user-images.githubusercontent.com/42139754/260404056-be743c42-01cf-4644-94dc-8b9e61d298db.png">

use `pnpm i` ?

**Comment by LinmonK** [comment]
I encountered the same mistake, but not because of pnpm, I used yarn. My mistake was in the package.json, two packages are repeatedly introduced, the@unocss/preset-wind and the@unocss/transformer-directive, which are actually already included in the UNOCSS NPM package.
