### ISSUE TITLE
Cannot find module 'virtual:uno.css"

### ISSUE THREAD

**Issue by Laxmanan-Krishnapillai** [unocss/unocss#2923]
### UnoCSS version

0.53.6

### Describe the bug

Unocss example doesn't work in Codesandbox.

### Reproduction

Try to open the SvelteKit Codesandbox example on the UnoCSS page. 

### System Info

Edge, Sveltekit

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Laxmanan-Krishnapillai** [comment]
I don't know if it is related, but Edge also crashes when installing unocss (using npm like "npm install -D unocss") on Stackblitz and gives an error of "This page is having a problem".

**Comment by paulm17** [comment]
@Laxmanan-Krishnapillai Did you resolve this in the end?  I'm getting the same problem.
