### ISSUE TITLE
UnoCSS does not add  after:content-[''] class automatically when I want to use pseudo classes like after and before.

### ISSUE THREAD

**Issue by cibilex** [unocss/unocss#2924]
### Clear and concise description of the problem

I used both Tailwind and WİndiCSS.I started to learn UnoCSS before one week ago.I noticed that UnoCSS does not add ' after:content-['']' class(content:'') automatically when I use before or after pseudo classes.
If you can add this feature will be helpful.
Thanks in advance :)

### Suggested solution

Add 'after:content-['']' if A user describes before or after pseudo classes. 

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by zyyv** [comment]
Our behavior should already be aligned with tailwind, windi. 
If so, can you send a link to the online playground?

Otherwise it sounds like an own requirement, you can use [`shortcuts`](https://unocss.dev/config/shortcuts)

**Comment by onlyfortesting** [comment]
> Our behavior should already be aligned with tailwind, windi. If not, can you send a link to the online playground?
> 
> Otherwise it sounds like an own requirement, you can use [`shortcuts`](https://unocss.dev/config/shortcuts)

[TailwindCSS Playground](https://play.tailwindcss.com/SXB6aQm3IF)
[UnoCSS Playground](https://unocss.dev/play/?html=DwIwNg9gxg1gjgVwgFwKYAIpgIYGdcC8ARCAOYC0A7gBYCWa6aAHsuVKgHZoBOjqL5AExMw6AGYQu5XKgC2tEBDAATdPWxhaUPgNw405AJwAGY0QB8AKHToA6tU7oAnhATpIEGNfTBcAB2wOTBx8Ym5UfVoANwxaDk0OVHJwaBh0EFQJcIAubBBcJQQGDKzUbPI4mVYARnTMiByU2DrS8twYVEpyJ3IAZhaGsrJyPziYcgBWUwtvG18AoKw8QiJwyJidVhp6VAtAjggnVGVgAHp-QKs584Wr9A1RZAdGWllUABp0P1QIPzAMJ5jRjUbDIZyuADk4XSCFwTgAdJYzk14Eg0OYgA&config=PTAEFcDsHsDoGNqQGYEsDmsAuBnAUKgLYAO0ATlqAN6gAmApmpPQMJJroA0xZ9O9WAOqpItUAF9QyMtEKgA5FGjwcOeXhCgipCqB58Bw0VJlz5AASUqcwffywBaAO4ja6vPQAeOyg2QBDcAAbX0YRVnYMAAoqPFA9XnscAC5QAG04%2BISDIVcogEpOTIBdIvF8oA&css=Q&options=N4XyA)

Looks like `content` is indeed automatically set in TailwindCSS

**Comment by zyyv** [comment]
<img width="384" alt="image" src="https://github.com/unocss/unocss/assets/42139754/6b587d12-06ce-45e6-a6bf-c7dbc4ce7c48">
From the devtools, `tailwind` adds `content` to each pseudo-element, but from the output, I don't think this is a wise choice.

**Comment by onlyfortesting** [comment]
Is it because of the generated CSS bundle size? Using `before` and `after` pseudo-elements is already a rare case, and gzip will compress them to virtually nothing, as they are all the same. I truly don't believe bundle size should be a concern in this situation. However, if there is another reason, I would be open to understanding it.

**Comment by zyyv** [comment]
I personally don't like too much style overrride, and increase the invalid css bundle size, thank you for a `content-empty`nothing bad. You can send a PR to get more people to review it.

**Comment by xsjcTony** [comment]
@zyyv At least we should have a way to write arbitrary values, but currently this is not offered.
https://tailwindcss.com/docs/content#arbitrary-values

Or alternatively, I think aligning with WindiCSS's `content-DEFAULT` would be a good way
https://windicss.org/utilities/general/variants.html#pseudo-element-content

**Comment by xsjcTony** [comment]
For a temp workaround, this is how you can define it in `shortcuts`
```ts
['content-DEFAULT', [{ content: `''` }], { layer: 'utilities' }]
```

**Comment by zyyv** [comment]
> At least we should have a way to write arbitrary values, but currently this is not offered.


We already supported it. https://unocss.dev/interactive/?s=content-[%27test%27]

> For a temp workaround, this is how you can define it in `shortcuts`
> 
> ```ts
> ['content-DEFAULT', [{ content: `''` }], { layer: 'utilities' }]
> ```

Use `content-empty`. https://unocss.dev/interactive/?s=content-empty

**Comment by zyyv** [comment]
I think we should choose good ones to align. I personally think there is no need to align with tailwind in this issue. There is nothing wrong with writing an unitility `content-empty`. If you have other comments, PR welcome, let everyone review.

**Comment by xsjcTony** [comment]
Emm yeah, you are right. I've no idea why it didn't work for me, guess it's some kind of HMR issue. After I restart the dev server again it works. Thanks!
