### ISSUE TITLE
Icons not rendering in a dynamic  Array creation

### ISSUE THREAD

**Issue by RayyanNafees** [unocss/unocss#2926]
### UnoCSS version

latest

### Describe the bug

I tried creating flag icons based on the country name using unocss icons 

```typescript

interface Country {
  name: string
  code: string
  icon: Element
}

const countryfy = (countryArr: CountryData[]): Country[] =>
  countryArr.map((c) => ({
    name: c.countryNameEn,
    icon: (
      <span class={'i-twemoji-flag-' + c.countryNameEn.toLowerCase()}></span>
    ),
    code: c.countryCallingCode,
  }))
```

# What would be the better approach for this scenario ? Defining country flag icons one-by-one ? 

### Reproduction

[Vite Solid-ts](https://stackblitz.com/edit/vitejs-vite-6i3zfn?file=src%2FApp.tsx)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
https://unocss.dev/guide/extracting#safelist
