### ISSUE TITLE
When can I use a unocss prompt plugin for webstorm？

### ISSUE THREAD

**Issue by Soumns777** [unocss/unocss#2928]
### Clear and concise description of the problem

I think I often encounter some abnormal bugs in the process of using vscode, which greatly affects my development experience, so I think you can develop a version of the webstorm plug-in for us to use, thank you very much

### Suggested solution

1I think I often encounter some abnormal bugs in the process of using vscode, which greatly affects my development experience, so I think you can develop a version of the webstorm plug-in for us to use, thank you very much

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [ ] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by yzqdev** [comment]
This is a community-maintained plugin, not reviewed or maintained by the UnoCSS team. https://unocss.dev/integrations/jetbrains
BTW,I also hope there is an official webstorm plugin for unocss

**Comment by Soumns777** [comment]
But now this plugin is not working
