### ISSUE TITLE
After the preset-attribute function is turned on, you should provide location information and complete attribute value information in rules

### ISSUE THREAD

**Issue by Autumn-one** [unocss/unocss#2934]
### Clear and concise description of the problem

I write the following code
```html
<div m="10px 20px 30px 40px"></div>
```
The objects expected to be generated are:
```javascript
{
   "margin": "10px 20px 30px 40px"
}
// or
{
    "margin-top": "10px",
    "margin-right": "20px",
    "margin-bottom": "30px",
    "margin-left": "40px"
}
```

But the function arguments in the current rules don't give me enough information to generate these style objects

### Suggested solution

It is recommended to add more information to the function parameters in rules, for example, the following is a way

```javascript
export default defineConfig( {
    rules: [
            /^([mp])-(\S+)$/,
            ([, attr, value], origin_info) => 
             {
                     console.log(origin_info.full_value); // If I write m = "50px 100px" then full_value is "50px 100px"
              }
    ]
})
```

The above is just an example to express the effect I hope to achieve, and the specific api design may be better

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Autumn-one** [comment]
I summarized the problem as follows: I wrote `< div m = “50px 100px”> </div >` I should be able to get the full information in rules `m = “50px 100px”`

**Comment by antfu** [comment]
You can't use space in the rules. It's how selectors work fundamentally.
