### ISSUE TITLE
!text-[var(--damu-font-size)] is incorrect

### ISSUE THREAD

**Issue by bighamD** [unocss/unocss#2936]
### UnoCSS version

^0.47.6

### Describe the bug

![image](https://github.com/unocss/unocss/assets/41603686/033ca610-51d4-4aaa-a532-fd064156de17)

why not 

### Reproduction

Shouldn't the snippet result be ??
![image](https://github.com/unocss/unocss/assets/41603686/ddb94110-4858-4844-871e-002b7a2bd2ea)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
You could do:
- `!text-size-[var(--damu-font-size)]`
- `![font-size:var(--damu-font-size)]`
