### ISSUE TITLE
Current Nuxt + Uno docs on minimal install does not apply styles

### ISSUE THREAD

**Issue by sambedingfield** [unocss/unocss#2938]
### UnoCSS version

0.54.1

### Describe the bug

After following the current default Nuxt 3 install and Uno integration docs, utility classes on `app.vue` have no affect, and shows no errors.

### Reproduction

Maybe I'm missing something super obvious here, but I'm following Nuxt's current [install guide](https://nuxt.com/docs/getting-started/installation) (v3.6.5):

And Uno's current [integration guide](https://unocss.dev/integrations/nuxt) (v0.54.1):

Which equates to:
1. `npx nuxi@latest init nuxt-uno`
2. `npm install -D @unocss/nuxt`
3. Add `@unocss/nuxt` module to Nuxt config
4. Create default `uno.config.ts` config
5. In `app.vue`, replace `<NuxtWelcome />` with `<div class="p-10 bg-black text-white">Hello World</div>`
6. Run `npm run dev`

Minimal [repo](https://github.com/sambedingfield/nuxt-uno) if needed.

Thanks

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tasiotas** [comment]
same, stopped working few hours ago

**Comment by toimc** [comment]
same here, use `@unocss/nuxt: 0.53.5` works well, but `0.54.1` fail.

**Comment by sfxcode** [comment]
same problems after update to 0.54.1

**Comment by sfxcode** [comment]
Latest working version for me: 0.54.0

**Comment by andy-study** [comment]
> Latest working version for me: 0.54.0

not work for me

**Comment by antfu** [comment]
Investigating, presumably, it's some transmit dependencies break it. So downgrading might not help, if you still have the older lockfile, you can revert to the old lock to workaround it temporarily while we are investigating it.

**Comment by toimc** [comment]
@antfu after use the cmd `pnpm up unimport`,  the project works well:

```
"nuxt": "^3.6.5",
"@unocss/nuxt": "^0.54.1",
```
