### ISSUE TITLE
UNOCSS Plugin for Jetbrain Products like PHPStorm and WebStorm

### ISSUE THREAD

**Issue by BroJenuel** [unocss/unocss#2945]
### Clear and concise description of the problem

So currently most of us are now started using jetbrain products because of its wonderful features. And their are 2 popular tool that I believe a lot of people are using, which is the webstorm that is dedicated for web dev, and phpStorm which is dedicated for PHP stuffs which is also mostly used for web development.

### Suggested solution

A plugin that will support UnoCss on jetbrain products specially webstorm and phpStorm.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by userquin** [comment]
https://unocss.dev/integrations/jetbrains
