### ISSUE TITLE
there are some questions of priority  in the same rule

### ISSUE THREAD

**Issue by frienkiss** [unocss/unocss#2954]
### UnoCSS version

lastest

### Describe the bug

<div display-block  display-none display-flex></div>
result: displya: none priority over others

how to analysic block, none, flex  priority?
wirte order? 

### Reproduction
```html
<div h-full text-center flex select-none all:transition-400>
  <div ma>
    <div text-5xl h-2 fw100 animate-bounce-alt display-block  display-none display-flex animate-count-infinite animate-duration-1s>
     <div>1</div><div>2</div>
      
    </div>
    <div op30 text-lg fw300 m1>
      The instant on-demand Atomic CSS engine.
    </div>
    <div m2 flex justify-center text-2xl op30 hover="op80">
      <a
        i-carbon-logo-github
        text-inherit
        href="https://github.com/unocss/unocss"
        target="_blank"
      ></a>
    </div>
  </div>
</div>
<div absolute bottom-5 right-0 left-0 text-center op30 fw300>
  on-demand · instant · fully customizable
</div>
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by userquin** [comment]
The rules are applied in the order you include them

**Comment by GavinXue** [comment]
I have the same problem. when seting flex and hidden in one class `class="flex hidden"`, no matter `hidden` place first or last. It always set display as `flex`. I didn't find any generated order's info in docs.

I find one way to inhance the priority of hidden. Setting a custom rule in config will work fine at temporarily. You can also add a layer to insure it works. [here is playground demo](https://unocss.dev/play/?html=DwEwlgbgBAFgtAMwK4BsVQC4FMAeG4DGWAdtgE5QIq5QDOW1B%2BxA9sVlAIZoBcGZnYrTAYwbOABYADFIB8AKChRQkKAFtOlajlhgQIEgqVKAKgAkAkgGUo1qCYCiVk1EsARNw4Byi5QHpwCCNlQPVOYKUATxYkKAJBKANqbDikWgwWNSgyVCxaKDBiOLYEMABzLmIQWE5oTQIYLAIAawA6X2AAyAUVOoAjWhYUJBS%2BlgwMtTgAVmzymHwpKGoERcxcfCJSLAoWAAcAZiWEAHcjuV9xAw0qqAB2gqEMQQx7ylQUSNT0zLAAL04fWo8k6gVkQA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhegAWwGiYuHrkiOjAdGBO9vyheir4enBqALpUxbJ0MdAwEjx0of6o%2BrV0MDoAtJXVtTB6uTBWMO1OpHADlkPQ9rikGHBVAG4YUMHjQwP2TmaoarIiCvXhkXKiSio%2BAJSywvKMLGycPHz8l9cnCpLSfseodBKbGFCAEYAHQAJjeqAkaFwuRirDA9QA9Ej6CAQZUkdsmmormUkLikEA&css=Q&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g)

```uno.config.js
{
  rules: [
    ['hidden', {display: 'none'}]
  ],
}
```

**Comment by eikaramba** [comment]
same problem here with "flex" and "hidden" in the same class. even reordering the classes does not help. with windicss and tailwind `class="flex hidden"` will hide the element, however in unocss it does not as flex comes after hidden in the CSS declarations.

**Comment by eikaramba** [comment]
no stale bot, it is still very relevant.

**Comment by chu121su12** [comment]
> wirte order?

Use `uno-layer-<x>` variant or `!<x>` important variant.
