### ISSUE TITLE
有没有一种方式我想自定义这个rem的转化方法

### ISSUE THREAD

**Issue by xuyifeiOnly** [unocss/unocss#2963]
### Clear and concise description of the problem

比如我写的类名rounded-20,现在编译之后是border-radius: 5rem; 我想的是这种数字的我编译生成border-radius: 2rem，请问这个功能现在有吗？

### Suggested solution

比如我写的类名rounded-20,现在编译之后是border-radius: 5rem; 我想的是这种数字的我编译生成border-radius: 2rem，请问这个功能现在有吗？

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ziloen** [comment]
试试自定义 rule 覆盖
```ts
const rules = [
  [/^rounded-(\d{1,3})$/, match => ({ 'border-radius': `${(+match[1]) / 10}rem` })]
]
```

**Comment by antfu** [comment]
Or you can disable all presets and write your own rules.
