### ISSUE TITLE
@unocss/svelte-scoped SSL / TLS crashes on page load

### ISSUE THREAD

**Issue by zs-ko** [unocss/unocss#2965]
### UnoCSS version

0.54.3

### Describe the bug

When running vite with https and ssl enabled the following error is logged on startup when using svelte-scoped plugin

```
const str = chunk instanceof Buffer ? chunk.toString() : Array.isArray(chunk) || "at" in chunk ? Buffer.from(chunk).toString() : `${chunk}`;`
```

```
Internal server error: Cannot use 'in' operator to search for 'at' in import * as client_hooks from "/src/hooks.client.ts";
```

source function
```
const SVELTE_KIT_ERROR = `[unocss] You have not setup the svelte-scoped global styles correctly. You must place '${PLACEHOLDER_USER_SETS_IN_INDEX_HTML}' in your app.html file. You also need to have a transformPageChunk hook in your hooks.server.js file with: \`html.replace('${PLACEHOLDER_USER_SETS_IN_INDEX_HTML}', '${GLOBAL_STYLES_PLACEHOLDER}')\`. You can see an example of the usage at https://github.com/unocss/unocss/tree/main/examples/sveltekit-scoped.`;
function checkTransformPageChunkHook(server, isSvelteKit) {
  server.middlewares.use((req, res, next) => {
    const originalWrite = res.write;
    res.write = function(chunk, ...rest) {
      const str = chunk instanceof Buffer ? chunk.toString() : Array.isArray(chunk) || "at" in chunk ? Buffer.from(chunk).toString() : `${chunk}`;
      if (str.includes("<head>") && !str.includes(DEV_GLOBAL_STYLES_DATA_TITLE))
        server.config.logger.error(isSvelteKit ? SVELTE_KIT_ERROR : SVELTE_ERROR, { timestamp: true });
      return originalWrite.call(this, chunk, ...rest);
    };
    next();
  });
}
```

### Reproduction

standard sveltekit repo layout with
command: vite dev 
vite.config.ts

stackblitz do not allow running vite under tls

```
import { sveltekit } from '@sveltejs/kit/vite'
import type { UserConfig } from 'vite'
import UnoCSS from '@unocss/svelte-scoped/vite'
import mkcert from 'vite-plugin-mkcert'

const config: UserConfig = {
	plugins: [
		mkcert(),
		UnoCSS({
			onlyGlobal: true,
			injectReset: '@unocss/reset/tailwind.css'
		}),
		sveltekit()
	],

	optimizeDeps: {
		exclude: ['@urql/svelte']
	},
	experimental: {},
	server: {
		https: true
	}
}

export default config
```

### System Info

node 18
sveltekit
unocss

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by feugy** [comment]
I'm facing the same issue with `@vitejs/plugin-basic-ssl`, so my hunch is: `mkcert`  and `basic-ssl` are the suspects.
Still searching for a workaround.

**Comment by feugy** [comment]
@zs-ko, can you try with version 0.55.3  please? it should be fixed now

**Comment by zs-ko** [comment]
@feugy can confirm it works
