### ISSUE TITLE
importing icons from dir and safelisting

### ISSUE THREAD

**Issue by tasiotas** [unocss/unocss#2966]
### UnoCSS version

0.54.3

### Describe the bug

I have defined a bunch of `safelist` items.
When I load svg icons from directory and add them to a collection, they are evaluated many more times than they should.

Loading 1 icon, but its evaluated 34 times. It does work properly without safelisting, but I do need it.

```
gb                                                                                11:45:44 AM
gb                                                                                11:45:44 AM
gb (repeated 37 times)                                                            11:45:44 AM
gb                                                                                11:45:52 AM
gb                                                                                11:45:52 AM
gb                                                                                11:45:52 AM
gb                                                                                11:45:52 AM
gb                                                                                11:45:52 AM
gb (repeated 34 times)                                                            11:45:52 AM

```

### Reproduction

https://stackblitz.com/edit/github-j6aj8e?file=uno.config.js

### System Info

nuxt 3.6.5

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by userquin** [comment]
include missing icons in the assets folder or remove/disable those icons from safelist

**Comment by tasiotas** [comment]
thanks for help
I added missing icons to the folders, matched safelist to reflect it.
but still, weird pattern of loading them in the console

stackblitz updated

```
gb                                                                               12:56:23 PM
gb                                                                               12:56:23 PM
gb                                                                               12:56:23 PM
gb                                                                               12:56:23 PM
3dsmax                                                                           12:56:23 PM
3dsmax                                                                           12:56:23 PM
3dsmax                                                                           12:56:23 PM
3dsmax                                                                           12:56:23 PM
gb                                                                               12:56:24 PM
gb                                                                               12:56:24 PM
3dsmax                                                                           12:56:24 PM
3dsmax                                                                           12:56:24 PM
ℹ Vite client warmed up in 624ms                                                12:56:24 PM
✔ Nitro built in 324 ms                                                   nitro 12:56:24 PM
```

**Comment by userquin** [comment]
we're figuring out what's happening...

**Comment by userquin** [comment]
@tasiotas this is a workaround but you shouldn't use it since it is not optimal (check the readme), we're updating the `@iconify/tools` UnoCSS repro to use another approach, stay tuned: 
https://github.com/userquin/iconify-demo-unocss/blob/main/unocss.config.ts#L16-L66

Here your repro with the custom collection configured with similar approach provided in previous repro (don't use it in large fs collections):
https://stackblitz.com/edit/github-j6aj8e-krsqjv?file=uno.config.js

**Comment by tasiotas** [comment]
thank you!

**Comment by tasiotas** [comment]
Hi,

I transitioned to your workaround. I does load faster and looks like there is less overhead from repeating processing the same name multiple times, but there is another issue.

Some icons are not rendering up at all. I can see them in the HTML/CSS but they don't render. They do work in my previous method. Not sure what's the problem now.

Here is simple repro, two icons out of three are rendering, `i-assets-houdini` doesn't. That icon is a valid SVG, opens fine in the browser.

https://stackblitz.com/edit/github-j6aj8e-h75ept?file=uno.config.js,app.vue

Thanks

**Comment by userquin** [comment]
@tasiotas I was talking with cyberalien, the [iconify example](https://github.com/iconify/tools/blob/main/%40iconify-demo/unocss/unocss.config.ts) repo linked in the preset icons page has been updated using my fix (I forgot to ping you here, sorry).

**Comment by tasiotas** [comment]
hi, thanks!
I did try this approach. See my previous comment, I don't know why, but its not loading all icons.

Are you still planning to update the `@iconify/tools` with permanent solution that will work on large collection of custom icons?

**Comment by tasiotas** [comment]
I am loading only 3 icons, don't do any transformation. Yet one of the icons is not being loaded, without any error/warning.

Correct me if I am wrong, this code only loads icons, right?

```js
function loadCustomIconSet() {
  const promise = new Promise((resolve, reject) => {
    importDirectory('assets', { ignoreImportErrors: 'warn' }).then(
      (iconSet) => {
        iconSet
          .forEach(async (name) => {
            console.log(name);
            const svg = iconSet.toSVG(name);
            iconSet.fromSVG(name, svg);
          })
          .then(() => {
            resolve(iconSet);
          })
          .catch((err) => {
            reject(err);
          });
      }
    );
  });

  return async (name) => {
    const iconSet = await promise;
    return iconSet.toSVG(name)?.toMinifiedString();
  };
}
```

**Comment by userquin** [comment]
@tasiotas yes, if you aren't applying any transformation use FileSystemIconLoader (IIRC). Anyway, try adding a log in the reject.

Maybe you icon name doesn't match the svg name in the assets folder.

**Comment by tasiotas** [comment]
thank you, ill do some investigation

**Comment by tasiotas** [comment]
got it, had to pass customizations to `toString` method. Default for some reason didnt work for some icons.

```js
  return async (name) => {
    const iconSet = await promise;
    return iconSet.toSVG(name)?.toMinifiedString({
      width: '1em',
      height: '1em',
    });
  };
```

thanks for help
