### ISSUE TITLE
Docs: Missing example within icon preset docs on how to use custom icon with "CustomIconLoader"

### ISSUE THREAD

**Issue by awacode21** [unocss/unocss#2967]
### UnoCSS version

v0.55.0

### Describe the bug

Not a bug, but incomplete icon preset documentation.
The documentation refers several times to the opportunity to use custom icon via "CustomIconLoader". But there is absolute no example on how to use this CustomIconLoader. So it is an option, but its in the dark.
Please adjust documentation at this point.

### Reproduction

https://unocss.dev/presets/icons

### System Info

Macbook Pro, Apple M2 Max, MacOS Ventura Version 13.4.1
Google Chrome Version 115.0.5790.114 (Offizieller Build) (arm64)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by awacode21** [comment]
The way i found now is not to use the referenced "CustomIconLoader" from documentation but to use the FileSystemIconLoader of iconify which somehow uses the CustomIconLoader. Don't know if this is meant to be like this, but it is working.

```
// uno.config.ts
import { defineConfig, presetIcons, presetUno } from 'unocss';
import { FileSystemIconLoader } from '@iconify/utils/lib/loader/node-loaders'

export default defineConfig({
    presets: [
      presetUno(),
      presetIcons({
        collections: {
            custom: FileSystemIconLoader('./public/icons')
        },
      }),
    ]
});
```

**Comment by userquin** [comment]
https://github.com/userquin/iconify-demo-unocss/blob/main/unocss.config.ts#L16-L66

**Comment by awacode21** [comment]
@userquin thank you very much

**Comment by userquin** [comment]
@awacode21 it is just an example, read the readme file, but you can get an idea, don't use that example in large fs collections

We're working to include a few more functions at iconify, maybe later I can add some example to the docs.
