### ISSUE TITLE
Using `bg-[url(vueVariable)]` does not take effect

### ISSUE THREAD

**Issue by pdsuwwz** [unocss/unocss#2971]
### UnoCSS version

0.55.0

### Describe the bug

It seems that the writing method of dynamic variables is not supported, `bg-[url(testUrl)]` does not work

The normal `bg-[url(xxxx.png)]` writing method can take effect, but if the `xxxx.png` is changed to a `vue variable`, it will not work.

I also found that once the image has been rendered, such as `baiduPng`, the variable corresponding to the url can take effect, otherwise the background image will not work(eg:githubPng)

![image](https://github.com/unocss/unocss/assets/19891724/4bf1cf4c-9e2a-48f7-9d50-eb2e3b16818d)

```vue
<script setup>
const githubPng = 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'

const baiduPng = 'https://www.baidu.com/img/PCtm_d9c8750bed0b3c7d089fa7d55720d6cf.png'

</script>

<template>
  <p>it works 1</p>
  <div class="w-100px h-100px bg-contain bg-[url(https://www.baidu.com/img/PCtm_d9c8750bed0b3c7d089fa7d55720d6cf.png)]">
  </div>

  <p>it works 2</p>
  <div
    class="w-100px h-100px bg-contain"
    :class="`bg-[url(${baiduPng})]`"
  >
  </div>

  <p>not working 3</p>
  <div
    class="w-100px h-100px bg-contain"
    :class="`bg-[url(${githubPng})]`"
  >
  </div>
</template>
```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-pxjqnb?file=package.json,unocss.config.js,src%2FApp.vue

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
https://unocss.dev/config/shortcuts#shortcuts
