### ISSUE TITLE
clamp inside text-[] not working

### ISSUE THREAD

**Issue by gauel** [unocss/unocss#2973]
### UnoCSS version

0.55.0

### Describe the bug

clamp() inside text-[] brackets not working

### Reproduction

[UnoCSS playground](https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIAuBTAHpgWgG14EBbABwAoBGADgtwBoB2CAdyYBYHcBKALpQc%2BAgCdsIdAD4AKnkxR2YTAAtYiSlAB2Ae0XtdYgNZhtAc2AB6cBGkAoUJA3I0WBcXqMBM%2BfiheuNa2Dk7QpCgYIoREbOw%2BcgpQccGQobYuke6iRDzevkl5QTZpQA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAqrhJQL5xZQQhwDkAV1YBjOnX5IkGAB6RY6bAENBAG3iYc%2BIiWCkAFMlRQ19AFxwA2lVSX%2BIwXRi8AtCdUZ%2B5RHBERV0Bb8tGj8cOwAulQRlKh0ABbQMA4wdBZGqAIOTq4JSSn8QTCyMC6qpHDFMqXQSrikGHCJAG4YUGZVpcVKqpKo7LHUtAypFtaZQ-SMLBD6AJSDUexzSEA&css=Q&options=N4XyA) (not working)

[TailwindCSS playground](https://play.tailwindcss.com/fuJOU4NjNI) (working)

### System Info

Windows 11, Chrome, Svelte

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by userquin** [comment]
use `text-size-[clamp(18px,7vw,48px)]`: [Playground](https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIAuBTAHpgWiTAC9sCBteBAWwAcAKARgA47cAaAdggHcOALG1wBKALpQc%2BAgCdsIdAD4AKnkxReYTAAtYielAB2Ae3W9jMgNZhDAc2AB6cBEUAoUJD3I0WNZVbsYkqq%2BFABuI7Obh7Q1CgYUoQUPLxBKmpQKZGQ0c5e8b7SFEKBwRklEU45QA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAqrhJQL5xZQQhwDkAV1YBjOnX5IkGAB6RY6bAENBAG3iYc%2BIiWCkAFMlRQ19AFxwA2lVSX%2BIwXRi8AtCdUZ%2B5RHBERV0Bb8tGj8cOwAulQRlKh0ABbQMA4wdBZGqAIOTq4JSSn8QTCyMC6qpHDFMqXQSrikGHCJAG4YUGZVpcVKqpKo7LHUtAypFtaZQ-SMLBD6AJSDUexzSEA&css=Q&options=N4XyA)
