### ISSUE TITLE
VSCode extension doesn't work with Handlebars (.hbs)

### ISSUE THREAD

**Issue by phenomen** [unocss/unocss#2974]
### UnoCSS version

0.55.0

### Describe the bug

I'm using Handlebars templates (`.hbs` extension) and UnoCSS VSCode extension doesn't detect it - no class highlights, no autocompletion.

I've tried adding Handlebars to config but no luck.
```json
    "unocss.languageIds": [
        "handlebars",
    ],
```

I think it's supposed to work out of the box since `hbs` is in the default language list: https://github.com/unocss/unocss/blob/401510f3fc154f99ccaad7c3d71e03640abb37f9/packages/vscode/src/autocomplete.ts#L15

Note: as soon as change file extension to `.html` UnoCSS instantly "loads" - highlights and autocompletion works, but I can't rename files all the time...

### Reproduction

1. Create a file with `.hbs` extension.
2. Copy some minimal code into it:
```html
<div class="w-full bg-blue-100">
  <h1 class="text-2xl font-bold">Hello World</h1>
</div>
```
3. UnoCSS autocompletion and class highlight should work.

### System Info

- Windows 11
- VSCode 1.81.1
- UnoCSS 0.55.0

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Daniel-Knights** [comment]
Also having this issue with `.liquid` files.

The `ContextLoader` class is using `createContext` from `packages/shared-integration`, which only passes `defaultPipelineInclude` to Rollup's `createFilter`, so the filter used to check files doesn't include any configured languages, just the default ones. I haven't had time to look at this in depth, but just from a quick debug, this looks like the cause to me.

Relevant lines:

https://github.com/unocss/unocss/blob/main/packages/vscode/src/contextLoader.ts#L113
https://github.com/unocss/unocss/blob/main/packages/shared-integration/src/context.ts#L21
https://github.com/unocss/unocss/blob/main/packages/shared-integration/src/defaults.ts#L5
https://github.com/unocss/unocss/blob/main/packages/vscode/src/annotation.ts#L91
https://github.com/unocss/unocss/blob/main/packages/vscode/src/autocomplete.ts#L117
