### ISSUE TITLE
More intelligent underlining in VS Code extension

### ISSUE THREAD

**Issue by ap-1** [unocss/unocss#2975]
### Clear and concise description of the problem

The extension underlines classnames that are detected anywhere in the included files, e.g.: 
```jsx
app.get("/", (c) =>
	c.html(
		<Root>
			<button class="text-cyan">Click me!</button>
		</Root>
	)
);
```

Here, the extension will correctly underline `text-cyan`, but it will also underline `me!`. https://github.com/unocss/unocss/pull/940 created a partial solution by allowing us to disable underlines entirely.

### Suggested solution

I was looking for something more along the lines of the Tailwind CSS extension's settings:

```json
"tailwindCSS.experimental.classRegex"
"tailwindCSS.classAttributes"
```

These would let us instruct the extension to use specific regex patterns to determine where to show underlines, and/or which HTML attributes to target for showing underlines, respectively. 

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
You can set blocklist in your uno.config.ts, and the VS Code extension will pick it up automatically: https://unocss.dev/guide/extracting#blocklist
