### ISSUE TITLE
Astro file used directives transformer shows `points to missing source files`

### ISSUE THREAD

**Issue by GavinXue** [unocss/unocss#2981]
### UnoCSS version

0.55.0

### Describe the bug

When using directives like `@apply` in .astro file's style tag. It seems two problems happened(no matter use `@apply` or `--at-apply`).
1. It will not apply on hmr, until restart dev server, it works.
2. There is a sourcemap hint shows (refer next) 
> Sourcemap for "/home/projects/unocss-unocss-ua6ez6/src/pages/index.astro" points to missing source files
> Sourcemap for "/home/projects/unocss-unocss-ua6ez6/src/components/Card.astro" points to missing source files

It may related to astro's problem. https://github.com/withastro/astro/issues/5053#issue-1404339628
But this warning shows only when I using `@apply` directive(every file show once, It will not show when update file.).

### Reproduction

here is the official astro demo shows: https://stackblitz.com/edit/unocss-unocss-ua6ez6?file=package.json

### System Info

macOS 13.4.1;
Astro 2.10.7;

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by KingImoh** [comment]
same here with `"astro": "3.0.12"` and `"unocss": "0.55.7"`

**Comment by Daydreamer-riri** [comment]
Same. Can you reopen this issue？
astro: 4.0.8
unocss: 0.58.2

I am willing to submit PR.
