### ISSUE TITLE
@apply with !important not working.

### ISSUE THREAD

**Issue by whidy** [unocss/unocss#2982]
### UnoCSS version

0.55.0

### Describe the bug

css code below

```
.test {
  @apply text-blue !important;
}
```

not transform to 

```
.test {
  --un-border-opacity: 1 !important;
  border-color: rgba(96,165,250,var(--un-border-opacity)) !important;
}
```

not same behavious as TailwindCSS [@apply](https://tailwindcss.com/docs/functions-and-directives#apply)

### Reproduction

see the [demo](https://codesandbox.io/p/sandbox/wispy-bird-xvst5l) of codesandbox.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
```diff
.test {
-  @apply text-blue !important;
+  @apply !text-blue;
or
+ @apply important-text-blue;
}
```

**Comment by whidy** [comment]
> ```diff
> .test {
> -  @apply text-blue !important;
> +  @apply !text-blue;
> or
> + @apply important-text-blue;
> }
> ```

It's a good solution, but someone often use tailwindcss may not know that.

Does it necessary to add `@apply text-blue !important;` or not.

**Comment by zyyv** [comment]
I think we should focus on writing the atomic utility(with some variants), try to avoid mixing with traditional css.
