### ISSUE TITLE
can breakpoints change sm: =>@media only screen and (hover: none) and (pointer: coarse)

### ISSUE THREAD

**Issue by im-pan** [unocss/unocss#2985]
### UnoCSS version

0.53.5

### Describe the bug

I tried writing like this but it didn't work
` theme: {
    breakpoints: {
      sm: 'only screen and (hover: none) and (pointer: coarse)',
    },
  },`

<img width="955" alt="image" src="https://github.com/unocss/unocss/assets/5241116/5df48cf8-777f-41ed-8243-c8040a04e336">

Is there something I'm missing?

### Reproduction

-

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
duplicate #2984
