### ISSUE TITLE
HMR with Astro + Uno

### ISSUE THREAD

**Issue by LiMao00** [unocss/unocss#2987]
### UnoCSS version

"@unocss/astro": "^0.55.0",

### Describe the bug

Whether following the steps on the official website (https://unocss.dev/integrations/astro) or the steps recommended by astro (https://www.elian.codes/blog/23-02-11-implementing-unocss-in-astro/), the integrated unocss has problems. During the initial load, the computer CPU will surge by about 20-30%, the tab page will continue to spin, and it will take about 10 seconds to finally load. In src\pages\index.astro, if you modify `<h1 class="bg-yellow">` to `<h1 class="bg-green">`, you will also encounter the same issues: CPU surge, tab page spinning, and waiting for about 10 seconds to load completely.

### Reproduction

https://gitee.com/limao-xs/del-astro

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by userquin** [comment]
/cc @Dunqing 

It seems the load hook returning empty string when `uno-with-astro-key` present, even when requesting `/__uno.css?uno-with-astro-key`, the HMR warning is there since the `__vite_css` is empty.

Excluding `__uno.css` here https://github.com/unocss/unocss/blob/main/packages/astro/src/index.ts#L88 seems to work.

![imagen](https://github.com/unocss/unocss/assets/6311119/428ce07f-95cb-4218-9647-4053b0b4d295)

![imagen](https://github.com/unocss/unocss/assets/6311119/463874fc-d9c7-4a84-b756-ea8f64fb871e)

**Comment by Dunqing** [comment]
> It seems the load hook returning empty string when `uno-with-astro-key` present, even when requesting `/__uno.css?uno-with-astro-key`, the HMR warning is there since the `__vite__css` is empty.
> 
> Excluding `__uno.css` here https://github.com/unocss/unocss/blob/main/packages/astro/src/index.ts#L88 seems to work.

After some research, I've reimplemented this piece of logic, Thanks.

**Comment by LiMao00** [comment]
> > It seems the load hook returning empty string when `uno-with-astro-key` present, even when requesting `/__uno.css?uno-with-astro-key`, the HMR warning is there since the `__vite__css` is empty.
> > Excluding `__uno.css` here https://github.com/unocss/unocss/blob/main/packages/astro/src/index.ts#L88 seems to work.
> 
> After some research, I've reimplemented this piece of logic, Thanks.

Thank you for your dedication!
If the fix/astro/hmr version has not been merged into the main branch yet and I want to use it as soon as possible, what should I do? One option that comes to mind is to clone the fix/astro/hmr version, publish it as an npm package, and then import it into my project to replace the unocss package. However, I feel like this process might be a bit cumbersome. Is there a simpler way?
I'm sorry, I'm a beginner and not very familiar with this.

**Comment by LiMao00** [comment]
> > It seems the load hook returning empty string when `uno-with-astro-key` present, even when requesting `/__uno.css?uno-with-astro-key`, the HMR warning is there since the `__vite__css` is empty.
> > Excluding `__uno.css` here https://github.com/unocss/unocss/blob/main/packages/astro/src/index.ts#L88 seems to work.
> 
> After some research, I've reimplemented this piece of logic, Thanks.

https://gitee.com/limao-xs/del-astro
Sorry, the performance is the same as before with the latest update. It's even worse. After modifying `<h1 class="bg-yellow">` to `<h1 class="bg-green">` in `src\pages\index.astro`, the color is lost, and the server needs to be restarted (pnpm dev) to have the color.
Since unocss is more troublesome, I will try tailwind.
Thank you.

**Comment by mrcaidev** [comment]
Still an issue in v0.55.1.

See [reproduction on CodeSandbox](https://codesandbox.io/p/sandbox/elastic-james-2ksdht). Change `text-red-500` to `text-red-300` or similar, and see the text go black, which means the new style is not applied after hot reload.

**Comment by Dunqing** [comment]
@LiMao00 @mrcaidev 

I apologize, I'm trying to fix this in #2997. Can you test it?

**Comment by userquin** [comment]
@Dunqing full page reload + empty HRM update: changing something getting page reload and any change stop working after first one.

**Comment by mrcaidev** [comment]
> @LiMao00 @mrcaidev
> 
> I apologize, I'm trying to fix this in #2997. Can you test it?

Works now. Lots of thanks!

**Comment by Mkassabov** [comment]
Seeing this issue again with
Astro: `v3.0.6`
UnoCSS: `v0.55.4`

**Comment by silveltman** [comment]
Also seeing this with:
Uno 0.55.6
Astro 3.0.7

On mac it works, on windows it doesnt

**Comment by Dunqing** [comment]
> Also seeing this with: Uno 0.55.6 Astro 3.0.7
> 
> On mac it works, on windows it doesnt

Sorry, I don't have Windows to debug currently. please create a new issue which describes your problem so that more people know
