### ISSUE TITLE
vscode extension cannot init in vscode  v1.81.1 with unocss-extension 0.55.1

### ISSUE THREAD

**Issue by zouhangwithsweet** [unocss/unocss#2993]
### UnoCSS version

0.55.1

### Describe the bug

Cannot init.

### Reproduction

版本: 1.81.1
提交: 6c3e3dba23e8fadc360aed75ce363ba185c49794
日期: 2023-08-09T22:20:33.924Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 21.1.0

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by 1oo1** [comment]
+1. Resolved via rollback to 0.55.0.

**Comment by JunVincetHuo** [comment]
+1. Resolved via rollback to 0.55.0.

**Comment by JianJia2018** [comment]
I have also encountered this issue. In version 0.55.1, it doesn't work within a VSCode project. I had to revert to the previous version.

**Comment by im-pan** [comment]
+1

**Comment by xkli1220** [comment]
+1

**Comment by subframe7536** [comment]
same here

**Comment by loosheng** [comment]
Related: #2979 #2992

**Comment by zaydek** [comment]
Oh I thought I was going crazy. Definitely rollback to 0.55.0 if you are having problems.

**Comment by sixdjango** [comment]
+1

**Comment by sixdjango** [comment]
you can "command + p" reload unocss , force reload

**Comment by Jannchie** [comment]
I apologize, it was my pr that introduced this issue...

I tried to commit #3005 to fix the problem.
