### ISSUE TITLE
config HMR not working for svelte-scoped

### ISSUE THREAD

**Issue by KraXen72** [unocss/unocss#2995]
### UnoCSS version

0.55.1

### Describe the bug

vite doesen't trigger hmr when config is changed. I checked the source and it looks like this version that's supposed to be a drop-in replacement doesen't even support config hmr. It is a shame since that's probably what component library makers want to have, reloading the site when config / config deps change (config deps is unsupported too).

### Reproduction

https://stackblitz.com/edit/unocss-unocss-c1zvpn?file=README.md
even in the default example it doesen't work.

### System Info

Windows 10, Vivaldi, Svelte / SvelteKit

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by henrikvilhelmberglund** [comment]
A workaround is to add `export const reloadMe = true;` in `uno.config.js` and
`import { reloadMe } from "./uno.config";` in `vite.config.js`, this will make uno.config.js a dependency.

**Comment by jacob-8** [comment]
HMR on config (and deps a seen in https://github.com/unocss/unocss/blob/40cc694de6bdd878cb82e81d25bc4bb6348355c0/examples/sveltekit-scoped/vite.config.ts#L17) will be supported once the PR above is merged.

Thanks for the excellent help @henrikvilhelmberglund with the workaround in the meantime.
