### ISSUE TITLE
VSCode extension does not provide intellisense for shortcuts or rules added in custom preset.

### ISSUE THREAD

**Issue by KraXen72** [unocss/unocss#3000]
### UnoCSS version

0.55.1

### Describe the bug

Shortcuts and rules added in custom preset files (which are defined in `configDeps` vite plugin option and imported to `uno.config.ts`) work in the resulting app, but don't have autocomplete, unless VSCode extension is reloaded with the reload command.

### Reproduction

I tried to reproduce it in stackblitz, but that apparently doesen't use the VSCode extension (i got no autocomplete at all), and the playground does not allow creating arbitrary ts files to import in the config.
Anyway, i made the basic repro in stackblitz, you can download it and open in VSCode.

How to repro:
- https://stackblitz.com/edit/unocss-unocss-i31ibt?file=uno.config.ts
- run `UnoCSS: reload` command to load the unocss extension LSP (workaround for extension version 0.55.1)
- add a new shortcut / rule in the custom-preset file.
- try using it in the code; it will work, but you will not get intellisense for it
    - old shortcut:
    ![image](https://github.com/unocss/unocss/assets/21956756/bbe7438c-36f4-4b56-bf3c-1345e32f1c0c)
    - new shortcut:
    ![image](https://github.com/unocss/unocss/assets/21956756/5ac75c86-0891-4b43-8622-002ad267c3ec)

- current workaround: if you define your shortcuts / rules directly in `uno.config.ts`, you will get intellisense immediately
- run `UnoCSS: reload` command, you now have intellisense

### System Info

Windows 10, Vivaldi, svelte

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sixdjango** [comment]
me too bro~

**Comment by KraXen72** [comment]
this is still not resloved by #3005 . i updated `unocss` and all `@unocss/*` packagages to `0.55.2`, the VSCode extension too. Luckily, since #3005 did resolve #3001, (reloading launching multiple UnoCSS LSP instances) a quick reload of the extension is all you need. still a workaround, but pretty usable at this point.l

**Comment by Jannchie** [comment]
You are right, I am sure that to address this issue, changes need to be made [here](https://github.com/unocss/unocss/blob/580a30165a021365e6f426277486ec0b1161274c/packages/vscode/src/annotation.ts#L26-L29). It appears that making it detect changes to the `presets.ts` file is necessary. This seems to be a bit complicated, as it might require parsing the import section of `uno.config.ts`.

**Comment by KraXen72** [comment]
> it appears that making it detect changes to the `presets.ts` file is necessary. 
  
i could not find a `presets.ts` file anywhere, using github codeserach or sourcegraph.  
 Do you prehaps mean the presets field in config? if you are planning on checking just that, remember that people can import and edit stuff *other than presets* in different files. for example, one could create a file that exports a `shortcuts` object, include the file in vite plugin's `configDeps` options, and import that `shortcuts` field in config.

**Comment by Jannchie** [comment]
Oh, I mean `presets.ts` is your custom preset file.

Currently the extension only reload config on changes to the config file (`uno.config.ts`), not to your custom preset that is imported into it. Trying to listen for updates to all dependencies of `uno.config.ts` doesn't seem to be very simple.

I'm not sure, but I think in general, custom preset usually would be another standalone library. So most people will not have a need to auto-reload presets. If you need to auto reload config like shortcuts, the easiest way is to write everything in `uno.config.ts`...

**Comment by KraXen72** [comment]
the [`@unocss/config`](https://github.com/unocss/unocss/blob/main/packages/config/src/index.ts) package has an option called `configDeps` - it already reloads the app when any file in this array is changed. maybe just use the same behaviour? it's a lot of work to implement some import resolution algorithm if the user defines the files the config depends on anyway.
It would be also great if the [config documentation](https://github.com/unocss/unocss/blob/main/docs/config/index.md) was updated to mention that the user needs to define this `configDeps` key, as it is currently not well documented.

**Comment by Tzyito** [comment]
I found that when the custom preset rules are changed, hmr cannot be triggered. It may be that unocss does not monitor the changes of the preset files in config？

**Comment by Simon-He95** [comment]
I think this issue could be closed
