### ISSUE TITLE
VSCode IntelliSense does not work if the configuration file is outside of the root directory

### ISSUE THREAD

**Issue by jozefmery** [unocss/unocss#3009]
### UnoCSS version

v0.55.2

### Describe the bug

Placing the UnoCSS configuration file outside of the project root directory breaks the VSCode IntelliSense. Based on the extension's output, it seems that the extension correctly finds and loads the configuration. Also, I'm using the CLI for generation and it seems to work correctly.

### Reproduction

1. Move the UnoCSS configuration file from the project root `/unocss.config.ts` into a sub-directory, e.g., `/foo/bar/unocss.config.ts` 
2. Point the extension to the configuration file by adding the following line in your VSCode `settings.json`: `"unocss.root": "foo/bar"`
3. Reload the editor (`Close & Open VSCode`, or `F1 > Developer: Reload Window`, or `F1 > UnoCSS: Reload UnoCSS`)
4. The IntelliSense should be broken

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by harrytran998** [comment]
Same problem with me!

Do like the docs said (https://unocss.dev/integrations/vscode#config) - but no luck 😆. Hope team can fix this!

**Comment by darkyelox** [comment]
This happens to me too, the settings.json configuration seems to be recognized but the intellisense is not working until I move my config file to root and removed the settings.json property :/ this is a problem for monorepos

**Comment by Simon-He95** [comment]
I think this issue could be closed
