### ISSUE TITLE
VSCode extension fails on ESM imports (Deno)

### ISSUE THREAD

**Issue by adamgreg** [unocss/unocss#3014]
### UnoCSS version

0.55.1

### Describe the bug

The VS Code extension does not work with Deno if there is an ESM import in the config file.

For example, if I import `presetUno` from esm.sh, in the Runtime Status I see a message like `Cannot find module 'https://esm.sh/@unocss/preset-uno@0.55.1' Require stack: - /workspace/uno.config.ts`

It does not seem to make a difference whether I import from an absolute URL or using the import map.

### Reproduction

Minimal Github repo for reproduction: https://github.com/adamgreg/unocss_vscode_extension

Alternatively, set up a Deno workspace, create a `uno.config.ts` file that includes an import (see below), and enable the extension.

```typescript
import presetUno from "https://esm.sh/@unocss/preset-uno@0.55.1";

export default {
  presets: [presetUno()]
}
```

### System Info

Deno 1.36.1, VS Code 1.81.1

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by adamgreg** [comment]
By the way, thank you very much for UnoCSS! Other than this VS Code issue, my experience so far of using it in my Deno Fresh project has been excellent. It's great to have the convenience of Tailwind utility classes, but with full control over the rules, and a great interface for SSR.

I've been helping with a PR for Deno Fresh which will hopefully lead to UnoCSS becoming the default solution for styling using that framework - https://github.com/denoland/fresh/pull/1303 .

**Comment by zhmushan** [comment]
https://github.com/unocss/unocss/blob/580a30165a021365e6f426277486ec0b1161274c/packages/config/src/index.ts#L38-L57

UnoCSS uses [JITI](https://github.com/unjs/jiti) to compile configuration files. Unfortunately, it cannot handle modules imported from HTTP.

**Comment by adamgreg** [comment]
If we use bare module specifiers in the config file itself, and resolve to HTTP URLs in Deno's import map, presumably JITI would be able to resolve them differently? Does it need look for modules under a `node_modules` folder, or is configurable somehow?

**Comment by zhmushan** [comment]
> If we use bare module specifiers in the config file itself, and resolve to HTTP URLs in Deno's import map, presumably JITI would be able to resolve them differently? Does it need look for modules under a `node_modules` folder, or is configurable somehow?

If you use bare module specifiers, JITI will search for modules in the same way as Node.js.

Another approach is through [JITI#alias](https://github.com/unjs/jiti#alias), which allows us to transform any specifiers (including HTTP) into the desired format (Deno's module local storage path).

However, both of these methods are cumbersome and can result in a lot of Deno-related configurations in UnoCSS code. I prefer using a Babel plugin to enable JITI to import JS/TS modules from HTTP.

**Comment by zhmushan** [comment]
Currently, UnoCSS and Deno can work well together, but they haven't met the expectations in terms of DX because the UnoCSS VSCode plugin doesn't understand Deno-style configuration files.

For example, when I import UnoCSS presets via HTTPS, the plugin encounters an error:
```ts
import { defineConfig, presetUno } from 'https://esm.sh/unocss'

export default defineConfig({
  presets: [presetUno()],
})
```
This is not only because JITI currently does not support importing modules from remote, but Deno itself also has some opinionated specifiers like `npm:`.

To address the aforementioned scenario, I suggest modifying `createConfigLoader` in `unocss/config`. (The reason for not handling it in `unconfig` is that I think, as a library used in Node.js, it doesn't need to be concerned with Deno-specific functionality)

First, we use [deno_emit](https://deno.land/x/emit/mod.ts) to bundle the configuration file and output the result to stdout:
```ts
import { bundle } from 'https://deno.land/x/emit/mod.ts'
const { code } = await bundle(filepath)
console.log(code)
```
Next, we can use execSync to execute Deno-related commands and obtain the bundled code. We can then pass it as the result of the transform function to JITI.

@antfu If you approve, I'll create PR for this.

**Comment by zhmushan** [comment]
One additional: We can add `unocss.deno: true` in the VSCode configuration to determine whether to use this method for bundling.

**Comment by pluiedev** [comment]
Bump - this is still very much relevant as a [Lume](https://lume.land) user

**Comment by sant123** [comment]
Bump, please this would be really nice to have

**Comment by adamgreg** [comment]
I've just confirmed with Deno 1.41 that if I avoid https imports in the `uno.config.ts` module (and any local modules it imports), then the VS Code extension works ok. I'm using an import map in `deno.jsonc` to map the UnoCSS imports to `npm:` specifiers. I'm not using a `node_modules` folder.

It is also now safe to import directly from `unocss` (the only place to get `defineConfig()` from). Previously that would hit a node API call in the preset-icons package and fail.
