### ISSUE TITLE
`ts(2742)` error in `uno.config.ts`

### ISSUE THREAD

**Issue by lvjiaxuan** [unocss/unocss#3022]
### UnoCSS version

0.55.2

### Describe the bug

The `uno.config.ts` reports an unexpected  `ts(2742)` error. I tried to figure it out but failed (bacause I'm a rookie).

![image](https://github.com/unocss/unocss/assets/11309921/7f39493b-eef3-42d8-916d-559071b4ae34)

### Reproduction

https://github.com/lvjiaxuan/reproduce-uno-config

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
Related #2921 @liuzw2579 Sorry for hastily closing your issue, I'll try to find out.

**Comment by chizukicn** [comment]
> Related #2921 @liuzw2579 Sorry for hastily closing your issue, I'll try to find out.

This problem occurs when `unocss.config.ts` is included to `tsconfig.node.json`, it seems to be the cause of some typescript configuration

**Comment by lvjiaxuan** [comment]
> > Related #2921 @liuzw2579 Sorry for hastily closing your issue, I'll try to find out.
> 
> This problem occurs when `unocss.config.ts` is included to `tsconfig.node.json`, it seems to be the cause of some typescript configuration

Additional, when using pnpm.

**Comment by zyyv** [comment]
> Additional, when using pnpm.

Yep, when i use `npm i`, those error was disappear.
