### ISSUE TITLE
Dynamic icon properties, unable to load

### ISSUE THREAD

**Issue by shenlipython** [unocss/unocss#3024]
### UnoCSS version

0.53.6

### Describe the bug

Dynamic icon properties, unable to load
` <div :class="[item.icon + '-' + `${isDark ? 'dark' : 'light'}`]" /> bad
          <div class='i-skill-icons:remix-light' /> good
`

### Reproduction

LAN Development

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by chz** [comment]
This is not bug you must use like: 

```html
<div :class="isDark ? 'i-skill-icons:remix-dark' :  'i-skill-icons:remix-light'" />
```

**Comment by shenlipython** [comment]
> This is not bug you must use like:
> 
> ```
> <div :class="isDark ? 'i-skill-icons:remix-dark' :  'i-skill-icons:remix-light'" />
> ```
Icon type remix, which is a variable.

**Comment by shenlipython** [comment]
> This is not bug you must use like:
> 
> ```
> <div :class="isDark ? 'i-skill-icons:remix-dark' :  'i-skill-icons:remix-light'" />
> ```

   <div :class="isDark ? `${item.icon}-dark` :  `${item.icon}-light`" /> It's still not going to work.

**Comment by zyyv** [comment]
Or use `safelist`https://unocss.dev/guide/extracting#safelist. In the past issues, there are similar use cases, you can find solutions from them.
