### ISSUE TITLE
VS Code IntelliSense break when use CustomIconLoader or FileSystemIconLoader

### ISSUE THREAD

**Issue by chz** [unocss/unocss#3034]
### UnoCSS version

0.55.3

### Describe the bug

1. Clone reproduction link to local computer. 
2. Run in vscode. 

**Custom CustomIconLoader will break VS code IntelliSense.**

Uncomment in **uno.config.ts**
```js
 // load: loadCustomIconSet(),
```
Uncomment in **pages/index.vue**
```html
<!-- <div>
      Test Icon Loaded: <i class="text-blue i-load:plus"></i>
    </div> -->
```

Also IntelliSense not work for FileSystemIconLoader loaded icons: 
```js
umico: FileSystemIconLoader(
  './assets/svg',
  svg => svg.replace(/#fff/, 'currentColor'),
),
```

### Reproduction

Repo: https://stackblitz.com/edit/unocss-unocss-xyzsnc?file=uno.config.ts

### System Info

------------------------------
- Operating System: Darwin
- Node Version:     v18.16.1
- Nuxt Version:     3.7.0
- CLI Version:      3.7.0
- Nitro Version:    2.6.1
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools, modules, sourcemap, nitro, app, vite, routeRules, experimental, imports
- Runtime Modules:  @unocss/nuxt@0.55.3
- Build Modules:    -
------------------------------

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by chz** [comment]
Also only usage will break suggestion but intellisense will work for default uno presets:
```js
umico: FileSystemIconLoader(
  './assets/svg',
  svg => svg.replace(/#fff/, 'currentColor'),
),
```

**Comment by userquin** [comment]
it seems to be ok: 

![imagen](https://github.com/unocss/unocss/assets/6311119/68cf6958-1ab8-4939-a50b-ad3ecbfa9572)

**Comment by userquin** [comment]
ok, the problem is about vscode is broken...

**Comment by chz** [comment]
@userquin  Check images: 

<img width="949" alt="Screenshot 2023-08-26 at 17 31 35" src="https://github.com/unocss/unocss/assets/3233370/23e95b1e-8a3c-4bbe-b000-028e8ba57ef4">
<img width="814" alt="Screenshot 2023-08-26 at 17 31 49" src="https://github.com/unocss/unocss/assets/3233370/8151c282-71a7-46a2-af41-c964eeeb1be8">
