### ISSUE TITLE
presetMini: Breakpoints not being overridden

### ISSUE THREAD

**Issue by rafael-lua** [unocss/unocss#3038]
### UnoCSS version

v0.55.3

### Describe the bug

According to the [docs](https://unocss.dev/presets/mini#theme), by setting breakpoints in presetMini configuration, they will override the defaults. But it seems the configuration is being ignored, and the breakpoints are still the default ones.

I'm using unoCss with a default scaffold for `vue-ts` from [vite-ssr-plugin](https://vite-plugin-ssr.com/scaffold).

https://github.com/unocss/unocss/assets/54607854/d0c643d9-addc-4beb-a3f2-4bda9b3cf428

The playground seems to have the same behavior. I used the following config:

```ts
import {
  defineConfig,
  presetAttributify,
  presetIcons,
  presetMini,
} from 'unocss'

export default defineConfig({
  rules: [
    ['custom-rule', { color: 'red' }]
  ],
  shortcuts: {
    'custom-shortcut': 'text-lg text-orange hover:text-teal'
  },
  presets: [
    presetMini({
      theme: {
        breakpoints: {
          md: "768px",
          lg: "1440px"
        }
      }
    }),
    presetAttributify(),
    presetIcons({
      scale: 1.2,
      cdn: 'https://esm.sh/'
    }),
  ]
})
```

The `lg:` [searches](https://unocss.dev/interactive/?s=lg:) all show up with min-width 1024 instead of 1440. The `sm:` searches are shown as well, I would expect it to not be present.

### Reproduction

Minimal repro: https://github.com/rafael-lua/bug-breakpoints

### System Info

- Browser: Brave 

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
We don't have `theme` option in `presetMini`.
You should add theme configration in uno.

[Playground](https://unocss.dev/play/?html=DwEwlgbgBA7gTgQwA5IKZwHwCgpVJbXXfaAYwBsEBnKgXgCIBbEALgCMBzAWjlRCiqN23Dr1QA7KEi4BGAGz0MASQEALAPYBXcvzaoovfuskB2OQA4oCcf3GoI6KKNQSAdMAD04CITzeoFNR09OQcwlxs5Jr6guHOElKyCspqWjpQehlR%2BsZQMgAs%2BQAMVjZQdg5wTmLi7l4EOHj1Plie3thAA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCCMMUwARgK4zDoCeZF1tAJIBjAlT6UaMAKpYIcAL5x0UCCDgByNnOFUqGgFAHUAD0iwUGAIZsANvDSYc%2BQsCIAKBAbhwqAC2gYYQ4qAC5Ebx84AHcoKzAwVChwjWiAWgBGAAYsgDdouD9MnNy-ZVtTOGAYVBAqNOFULBqoOAArNipOHgamlo0SSIVBnxg-WtRwryi4FkorAGtIbBgwiJmfEGQUgHYANgAOMBMByJnbIhSMgBZrrOPTmeGhkfJJWjWAbTO3gRk5dwASlePn4UgYTFYHC43CBIN%2BUhEYk8Px8VGEVgq4QyADoAEzwnzCZBYFJ%2BRhgMIAeip1BAOP8VMeUQUwMiAF1BqyDEA&css=Q&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g)

**Comment by rafael-lua** [comment]
> We don't have `theme` option in `presetMini`. You should add theme configration in uno.

I see. But, I am still confused because the [docs show an example with presetMini](https://unocss.dev/presets/mini#theme):

```
presetMini({
  theme: {
    // ...
    breakpoints: {
      sm: '320px',
      md: '640px',
    },
  },
})
```

Is it a doc issue in this case?

**Comment by zyyv** [comment]
> Is it a doc issue in this case?

Yes, nice catch，pr welcome to fix it.

**Comment by ryoppippi** [comment]
I faced this problem rn, we need update docs

**Comment by zyyv** [comment]
@ryoppippi I'm sorry that this is not mentioned in the presets documentation. But it is actually documented at https://unocss.dev/config/theme#breakpoints. I will sync the documentation.

**Comment by zyyv** [comment]
@ryoppippi You can also get better type protection like this: 
```ts
export default defineConfig({
 // ...
  extendTheme: (theme) => {
    return {
      ...theme,
      breakpoints: {
        ...theme.breakpoints,
        tiny: '375px',
      },
    }
  },
})
```
