### ISSUE TITLE
shortcuts warning: unmatched utility

### ISSUE THREAD

**Issue by XioDone** [unocss/unocss#3041]
### UnoCSS version

@unocss/nuxt: 0.55.3

### Describe the bug

uno.config.ts
```
shortcuts: [
    [/^btn-(.*)$/, ([, c]) => `bg-${c}-400 text-${c}-100 py-2 px-4 rounded-lg`],
  ],
```

class mode, everything is normal
```html
<div class=" btn-red"> btn </div>
```

attributify mode
```html
<div btn-red> btn </div>
```
``` shell
 Terminal: WARN  [unocss] unmatched utility "text-red>-100" in shortcut "btn-red>
```

### Reproduction

[playground](https://stackblitz.com/edit/github-2pskmu?file=app.vue,uno.config.ts)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
This is working as expected. When writing rules, you are responsible for validating the input. For example, you can change the regex to `/^btn-([\w-]+)$/` or return `undefined` in the ruby body to bypass unwanted input.

**Comment by hermit99** [comment]
I might have to disagree with @antfu in this comment. It's more of an attributify problem than unocss. Adding a space after red `<div btn-red >` should solve the warning. @XioDone
