### ISSUE TITLE
Some ideas in vs Code extension?

### ISSUE THREAD

**Issue by zhangfengsheng1** [unocss/unocss#3044]
### Clear and concise description of the problem

Can you add the function of hiding class or className in vs Code extension?

### Suggested solution

add...

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by henrikvilhelmberglund** [comment]
There are other extensions that do this though. Did you try https://marketplace.visualstudio.com/items?itemName=moalamri.inline-fold&ssr=false#overview?

**Comment by zhangfengsheng1** [comment]
> There are other extensions that do this though. Did you try https://marketplace.visualstudio.com/items?itemName=moalamri.inline-fold&ssr=false#overview?

thinks
