### ISSUE TITLE
`@unocss/postcss` - option to suppress experimental warning

### ISSUE THREAD

**Issue by silverwind** [unocss/unocss#3045]
### Clear and concise description of the problem

The postcss module unconditionally outputs [this annoying warning](https://github.com/unocss/unocss/blob/3a909d3e4597fa31480fd3bad160eadc85b59cbd/packages/postcss/src/index.ts#L19-L22) which I'd like to get rid because it's distracting.

### Suggested solution

Add an option `suppressExperimentalWarning` or similar to the [module options](https://github.com/unocss/unocss/blob/3a909d3e4597fa31480fd3bad160eadc85b59cbd/packages/postcss/src/types.ts#L3).

### Alternative

Stabilize the module and remove the warning or limit breaking changes to minor versions as is usually the practice for 0.x packages.

### Additional context

I'm happy to contribute this if it is accepted.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by chz** [comment]
+

**Comment by Dunqing** [comment]
Maybe we can remove the experimental warning currently. What do you think about this? @antfu

**Comment by antfu** [comment]
Yeah I think we could get it out of experimental indeed.
