### ISSUE TITLE
bug on transformer-variant-group parsing directive with child groups 

### ISSUE THREAD

**Issue by fernandolguevara** [unocss/unocss#3046]
### UnoCSS version

latest

### Describe the bug

variant group can not parse directive properly on child groups

```html
<button class="bg-blue(5 hover:6) focus:(outline-none ring(2 offset-2 green-5)) disabled:(bg-gray-2 cursor-default)">
click</button>
```

should be parsed as 

```html
<button class="bg-blue-5 hover:bg-blue-6 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-5 disabled:bg-gray-2 disabled:cursor-default">
click</button>
```

### Reproduction

check the bug

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
Your usage error. 

Refer to [Playground](https://unocss.dev/play/?html=DwEwlgbgBA7gTgQwA5IKZwHwCgpVJbXXAVQDsB7AYQGVqcjgAjAVwBdXzT6ioBjAGwQBnIQF4ARIwDmAWkb9mqGQAoArAEooAC3IR0c2fMUyAbFABm5XsyEAuZeTb8wpJRVdQ4L2coBMUcnNzIVRWGX8pOFRUUhkNTXAhBHlUEHtpGUiEAE9wvmY4IXI4GRBUcwRmflZ1cW4oQh4%2BZ14Aa3rgAHoWdk5GrvAIbAGCLCA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcEWWwCGuOlmggMUAGrr2mmAHEoELmCQBfOFksg4Aci4qJdOi6RIMAD0hYdGx1LgAbeEwcfCISYFIACmRUOgALaBgJHjoALkQqVBcAdyh1MDB9F3ySgFoARgAGRoA3Yrg0huaWtIdwgLhgGAwQOlqJDFxhqDgAKy46XgFxyemfVFtZEQU8uABtQrlRJRVEgEpZYXlGFjZOHj5%2Bc8ujhUlpZMPUiXV%2B-PqAHQAJheqAkaFwNTSrDAeQA9HD6CAAek4etUHBbBcqABdNRlLQ6KB6KC7PYaQm6fRGExTCxWMDnHF2M5IIA&css=Q&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g)

**Comment by fernandolguevara** [comment]
> Your usage error. 
> 
> 
> 
> Refer to [Playground](https://unocss.dev/play/?html=DwEwlgbgBA7gTgQwA5IKZwHwCgpVJbXXAVQDsB7AYQGVqcjgAjAVwBdXzT6ioBjAGwQBnIQF4ARIwDmAWkb9mqGQAoArAEooAC3IR0c2fMUyAbFABm5XsyEAuZeTb8wpJRVdQ4L2coBMUcnNzIVRWGX8pOFRUUhkNTXAhBHlUEHtpGUiEAE9wvmY4IXI4GRBUcwRmflZ1cW4oQh4%2BZ14Aa3rgAHoWdk5GrvAIbAGCLCA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcEWWwCGuOlmggMUAGrr2mmAHEoELmCQBfOFksg4Aci4qJdOi6RIMAD0hYdGx1LgAbeEwcfCISYFIACmRUOgALaBgJHjoALkQqVBcAdyh1MDB9F3ySgFoARgAGRoA3Yrg0huaWtIdwgLhgGAwQOlqJDFxhqDgAKy46XgFxyemfVFtZEQU8uABtQrlRJRVEgEpZYXlGFjZOHj5%2Bc8ujhUlpZMPUiXV%2B-PqAHQAJheqAkaFwNTSrDAeQA9HD6CAAek4etUHBbBcqABdNRlLQ6KB6KC7PYaQm6fRGExTCxWMDnHF2M5IIA&css=Q&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g)

So why not consider my comment as a feature request?

**Comment by Suyashtnt** [comment]
> > Your usage error.
> > Refer to [Playground](https://unocss.dev/play/?html=DwEwlgbgBA7gTgQwA5IKZwHwCgpVJbXXAVQDsB7AYQGVqcjgAjAVwBdXzT6ioBjAGwQBnIQF4ARIwDmAWkb9mqGQAoArAEooAC3IR0c2fMUyAbFABm5XsyEAuZeTb8wpJRVdQ4L2coBMUcnNzIVRWGX8pOFRUUhkNTXAhBHlUEHtpGUiEAE9wvmY4IXI4GRBUcwRmflZ1cW4oQh4%2BZ14Aa3rgAHoWdk5GrvAIbAGCLCA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcEWWwCGuOlmggMUAGrr2mmAHEoELmCQBfOFksg4Aci4qJdOi6RIMAD0hYdGx1LgAbeEwcfCISYFIACmRUOgALaBgJHjoALkQqVBcAdyh1MDB9F3ySgFoARgAGRoA3Yrg0huaWtIdwgLhgGAwQOlqJDFxhqDgAKy46XgFxyemfVFtZEQU8uABtQrlRJRVEgEpZYXlGFjZOHj5%2Bc8ujhUlpZMPUiXV%2B-PqAHQAJheqAkaFwNTSrDAeQA9HD6CAAek4etUHBbBcqABdNRlLQ6KB6KC7PYaQm6fRGExTCxWMDnHF2M5IIA&css=Q&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g)
> 
> So why not consider my comment as a feature request?

Then label it as a feature request and not a bug
