### ISSUE TITLE
Incorrect Content-Type header for unocss files during dev 

### ISSUE THREAD

**Issue by UltraCakeBakery** [unocss/unocss#3048]
### UnoCSS version

0.55.3

### Describe the bug

UnoCSS generated files (like 'uno.css') have the wrong Content-Type header set in vite dev:

![image](https://github.com/unocss/unocss/assets/12383587/d5697c62-6f17-4f57-bd19-d7f0f4b2e4a9)

### Reproduction

stackblitz is offline and the playground does not work the same as the dev enviroment.

I assume this happens in any vite powered development enviroment.

Simply open the `issues` panel in your devtools. It should be reflected there.

Or use the network tab:

![image](https://github.com/unocss/unocss/assets/12383587/0886ef26-5ecf-44d6-b402-7c568163f0d6)

### System Info

SvelteKit
Microsoft Edge
Windows

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by UltraCakeBakery** [comment]
This is still a nonbreaking issue

**Comment by UltraCakeBakery** [comment]
This is still a nonbreaking issue

**Comment by zyyv** [comment]
![image](https://github.com/user-attachments/assets/93e7b967-dda8-4ba4-a476-2f26a2bca275)
![image](https://github.com/user-attachments/assets/3927343e-5b0a-4c3c-b974-e143c44891e1)


`__uno.css` is a javascript type file at the beginning, it needs to inject the css generated by uno into the html `style` tag.
