### ISSUE TITLE
Support `zIndex` in `Theme`

### ISSUE THREAD

**Issue by xsjcTony** [unocss/unocss#3049]
### Clear and concise description of the problem

Both `windi` and `tailwind` support this in `theme`, however there's no such option in `uno`, and I can't find any relevant posts
https://windicss.org/utilities/layout/positioning.html#z-index
https://tailwindcss.com/docs/z-index#customizing-your-theme

### Suggested solution

Add support of `zIndex` to `theme`

### Additional context

![image](https://github.com/unocss/unocss/assets/45784210/85bccd99-7209-48bf-ba1b-7088d35c05f4)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by chz** [comment]
HI, do you want use zIndex in plugins ? or what ?

**Comment by xsjcTony** [comment]
@chz I'll give an example here as how I use it before the migration.
In settings I have
```ts
zIndex: {
  'home-header-nav': '4999',
  header: '5000',
  'select-dropdown': '10000',
  modal: '20000',
  'tooltip': '1000000'
}
```
Then in code, I can have something like
```tsx
<header className="z-header" /> // will be `z-index: 5000;`
<div className="z-modal" /> // will be `z-index: 20000;`
```
Thus I can manage all z-index in a single place.

**Comment by Dunqing** [comment]
You can use `shortcuts` instead if desired
![image](https://github.com/unocss/unocss/assets/29533304/2c289b1a-560e-467f-8ccc-077b1bfa1e8d)

**Comment by xsjcTony** [comment]
@Dunqing Yeah this could be a last resort for me... but since this is the feature supported by both Windi and Tailwind, which is pretty common, so It would be really good if it is built-in by default.

**Comment by chz** [comment]
> @Dunqing Yeah this could be a last resort for me... but since this is the feature supported by both Windi and Tailwind, which is pretty common, so It would be really good if it is built-in by default

I think there is no need to add to theme. You can define via shortcuts and this resolve issue.

**Comment by xsjcTony** [comment]
@chz No I don't think `shortcuts` should be the right place to go.
1. Lots of users are coming from tailwind / windi and they are used to it.
2. `z-index` all in one places is a pretty common pattern and easy to manage

3. If we define tons of `z-index` in `shortcuts`, then what's the purpose of a theme?
- Image in the `shortcuts` we can also do
```ts
{
  'shadow-shallow': '0 5px 16px 0 rgba(112, 144, 176, .2)',
  'shadow-header': '0 3px 8px 0 rgba(29, 29, 29, .03)'
}
```
then what's the purpose of the `boxShadow` field in the theme? we can eliminate it totally right? and the same logic applies to `zIndex` IMO.

**Comment by zyyv** [comment]
> I think there is no need to add to theme.

Uno is already very flexible, although I don't really want to put it in the `theme`, but we should consider aligning the `tailwind/windi` theme configuration.
I will send a PR to try to resolve it.
