### ISSUE TITLE
[Bug🐞]: Type Error on `presetUno` with `theme` using `satisfies` keyword

### ISSUE THREAD

**Issue by xsjcTony** [unocss/unocss#3050]
### UnoCSS version

latest

### Describe the bug

Please refer to the reproduction link (https://stackblitz.com/edit/unocss-unocss-vrqatk?file=uno.config.ts)

Note, I added `<typeof theme>` generic in StackBlitz because I'm not able to reproduce the issue without it, however in my local, this is not a necessary step. But I do think I should pass it in otherwise what's the purpose of the generic? If I'm wrong on this, please correct me.
![image](https://github.com/unocss/unocss/assets/45784210/a36dab63-87e7-4f7d-809a-205a82b41b53)
![image](https://github.com/unocss/unocss/assets/45784210/d364e9f8-05d6-4f26-a8c2-6fbc71a1517f)

This also happens with `presetAttributify()` and `presetRemToPx()` as well, although I'm not using it, and I guess it's actually for all presets....

This issue doesn't stop me from using the actual functionality, but it's annoying

### Reproduction

https://stackblitz.com/edit/unocss-unocss-vrqatk?file=uno.config.ts

### Additional context

This is another error of `unocss-preset-primitives`, of course it's beyond the scope of this ticket, but the Error ends up basically the same which is `Type RegExp is not assignable to type string`, from `Rule<>`, so it might be some issue with this specific part of type system.
![image](https://github.com/unocss/unocss/assets/45784210/97760bf1-96ad-4c4d-8e77-47ba8ffb8cfd)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Ferdydh** [comment]
Also happens to me. I'm using this template.

https://github.com/solidjs/templates/tree/main/ts-unocss

**Comment by xsjcTony** [comment]
Just checked in the reprod, this is still an issue with unocss version of the "latest"

**Comment by Simon-He95** [comment]
<img width="574" alt="image" src="https://github.com/unocss/unocss/assets/57086651/f6326ba3-ff9e-4257-9ca5-4f42bdf366b0">
It seems to be normal.
