### ISSUE TITLE
Custom CSS between layers doesn't work in vite dev mode

### ISSUE THREAD

**Issue by lukaskleinschmidt** [unocss/unocss#3052]
### UnoCSS version

0.55.3

### Describe the bug

When using unocss with [`npm run dev`](https://stackblitz.com/edit/vitejs-vite-ufvwpb?file=index.html,style.css,main.js&terminal=dev) I can't get the [custom layer ordering](https://unocss.dev/config/layers#ordering) to work properly. It works fine once the assets are [bundled](https://stackblitz.com/edit/vitejs-vite-ufvwpb?file=index.html,style.css,main.js&terminal=preview).

### Reproduction

https://stackblitz.com/edit/vitejs-vite-ufvwpb?file=index.html,style.css,main.js&terminal=dev

### System Info

Windows 10
Firefox 117 / Chrome 116
Vite 4.4.9

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by lukaskleinschmidt** [comment]
I updated to the latest version and the issue still persists

**Comment by lukaskleinschmidt** [comment]
This issue still persists.

**Comment by duckradu** [comment]
Not sure if related, but using vite and importing my css like so:

```typescript
import "@unocss/reset/tailwind-compat.css";

import "virtual:uno.css";

import "~/styles/root.css";
```

Some styles inside my root.css are overwritten by the tailwind-compat.css.

```css
// root.css
* {
  @apply border-border;
}

a {
  @apply underline underline-offset-4;
}

a:hover {
  @apply no-underline;
}
```

The styles for * and a are replaced by the ones in tailwind-compat.css. While debugging this I figured that the order of imports is incorrect, even though in my code I imported them correctly.

**Comment by RebeccaStevens** [comment]
@lukaskleinschmidt The title says the issus exists in vite dev mode. Does it also exist in prod mode?
I've made a PR to fix this but don't want to accidentally break prod mode.

**Comment by lukaskleinschmidt** [comment]
It was only an issue when running `vite dev`. Once bundled the order of the layers was correct.
I also gave your fix a try locally and it seems to work as expected now.
