### ISSUE TITLE
[@unocss/webpack] Output CSS code doesn't reflect changes in files provided in `content.filesystem` config

### ISSUE THREAD

**Issue by adeys** [unocss/unocss#3057]
### UnoCSS version

0.55.4

### Describe the bug

Hello guys.
It's said in the docs :

> In cases that you are using integrations that does not have access to the build tools pipeline (for example, the [PostCSS](https://unocss.dev/integrations/postcss) plugin), or you are integrating with backend frameworks that the code does not go through the pipeline, you can manually specify the files to be extracted. [...] The files matched will be read directly from the filesystem and watched for changes at dev mode.

Using this config feature in practice did not help : the generated css file didn't contain any of the used classes and the filesystem provided files weren't watched in dev mode.
Diving in the source code, it appeared that only the content.include and content.exclude were used to filter the watched files.

I'd be happy to add a pull request for this as I happened to fix it in local.
Thanks

### Reproduction

```
import { defineConfig, presetUno } from 'unocss'

export default defineConfig({
  content: {
    pipeline: { include: [ 'assets/**/*.js' ] },
    filesystem: [ 'templates/**/*.twig' ]
  },
  presets: [ presetUno() ]
}
```

Using this config, only classes used in files within the `assets` directory will be generated. 
None of the classes used in files within the `templates` directory will be generated and there won't be any change on the watch process even if these filees were updated

### System Info

System :

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kedniko** [comment]
I have the same problem. I'm trying to include classes from `node_modules`:
i.e. `node_modules/primevue/passthrough/tailwind/index.js`

**Comment by arpansaha13** [comment]
I am also having the same problem. In my case i was trying to include the styles from a sub directory of "assets" and "content". But it didn't work.

I am using Nuxt 3.

**Comment by kedniko** [comment]
Be aware that "pipeline" filter is applied **after** "filesystem"

**Comment by adeys** [comment]
Hey @kedniko, I believe the bug cause has nothing to do with the processing order.

When working with UnoCSS alongside backend technologies, the template files aren't being processed by our build tools. Consequently, the content of the filesystem configuration files will never be included in the generated CSS file because they don't match the filter in the pipeline configuration files.

My suggestion is to treat the filesystem source as a separate entity, similar to how we handle inline and pipeline sources.
