### ISSUE TITLE
UnoCss doesn't restrict classes based on presets.

### ISSUE THREAD

**Issue by louiss0** [unocss/unocss#3070]
### UnoCSS version

0.55.6

### Describe the bug

When I use UnoCSS I notice that I'm able to use classes from presets that are unrelated to the preset that I set.
This is not good. I only used presetWind but yet I'm able to use classes like `ma4` I'm only supposed to use `m-4`. 

I was told.
> This preset inherits [@unocss/preset-mini](https://unocss.dev/presets/mini).

I don't understand what it does but. I thought only the classes from windi were allowed. 

I don't know if this was by design but this is not good. Windi and tailwind only allowed one way of writing a set of classes based on a specific concept. 

![Proof-UnoCSS-Intellisense-is-wrong](https://github.com/unocss/unocss/assets/29028601/443bc553-fab5-42e7-ab21-76c152676824)

### Reproduction

This is the [link](https://github.com/louiss0/dummy-astro-unocss)

1. Clone the repo
2. Download the dependecies
3. Make sure the UnoCSS extension is installed
4. Look at the src/MyComponent file to see the problem. 

You can start the server to see the way the classes are bundled.

```
pnpm dev
```

### System Info

System: Using Ubuntu
Browser: Google Chrome
Framework: Astro

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by texastoland** [comment]
It's included in the Mini preset TW inherets from:
https://github.com/unocss/unocss/blob/44b7ebb91c9460f3d8d23f330213b7d0aac7b991/packages/preset-mini/src/_rules/spacing.ts#L14

The rule looks for `m`, optional `a`, optional `-`, and captures the rest as the size. It appears to have been written as flexible as possible to reduce maintenance. I agree with https://github.com/unocss/unocss/issues/406#issuecomment-1004779052 that it makes sense to have more specific rules in each preset.

@antfu asked in https://github.com/unocss/unocss/issues/406#issuecomment-1004826490 for a list of inconsistencies besides margin and padding? Mini would still need a sensible default. Probably better to wait and see if this issue receives reactions before causing a breaking change to _every_ preset.

**Comment by louiss0** [comment]
Please make windi strict. People should not be able to produce too many of the same classes. 
First of all this is not intuitive.
Second of all this is disruptive.
- People will have a hard time remembering the classes that represent a design system
- Standards across a codebase would not be enforced leading to many conflicts
- Why add unnecessary bundle size. 
  - Even though bundlers are smart enough to sort identical classes with commas bundle size will increase.
- Having two classes that do the same things makes debugging utilities harder to debug.

**Comment by louiss0** [comment]
If you can't change the presets then. I'd like a setting for the Vs Code extension that detects duplicates and throws an error.  
I hope there can be some way to not allow duplicates when it comes to classes.

**Comment by texastoland** [comment]
A realistic solution would be to propose a [lint rule](https://unocss.dev/integrations/eslint) (more config but wouldn't break anything).

Does adding a rule to your [blocklist](https://unocss.dev/guide/extracting#blocklist) fix autocomplete? Maybe not I haven't tried yet.

**Comment by louiss0** [comment]
> A realistic solution would be to propose a [lint rule](https://unocss.dev/integrations/eslint) (more config but wouldn't break anything).
> 
> Does adding a rule to your [blocklist](https://unocss.dev/guide/extracting#blocklist) fix autocomplete? Maybe not I haven't tried yet.

The problem with that is that I would have to blocklist for too many classes. I need you to understand that duplicates don't only exist for margin and padding but for many other concepts as well. flex, grid, color, text-transform, border, line-height. 

```astro
<div
  class:list={[
    "case-lower lowercase",

    "text-trueGray text-truegray",

    "bg-green-100 bg-green-1",

    "border border-1",

    " border-blueGray  border-bluegray",

    "m-4 ma-4",

    "b-current border-current",

    "c-black text-black",

    "flex-justify-end justify-end",

    "line-height-9 leading-9",
    
  ]}
>
  Random classes.
</div>

```

**Comment by texastoland** [comment]
Hmmm yep I agree. I guess just have to wait for him to reply!

**Comment by antfu** [comment]
It's intentional behavior, and we don't have a plan to move away from that. Uno will merge CSS selector that come from the same rule, so ideally using the same rule in different ways won't add up too much to the bundle size. In terms of strictness, my PoV it's more like a management issue rather than a tooling problem. For example, JavaScript won't prevent you from writing bad code, dead loops, etc., while the linters do. In atomic CSS I don't really feel that would matter much, but if you really do, we have blocklist that accepts regex etc, or you can always write your own presets with the strictness in mind. Thanks for bringing this up.

**Comment by texastoland** [comment]
Would it be reasonable to convert this to a linter issue to enforce certain styles?

**Comment by louiss0** [comment]
> It's intentional behavior, and we don't have a plan to move away from that. Uno will merge CSS selector that come from the same rule, so ideally using the same rule in different ways won't add up too much to the bundle size. In terms of strictness, my PoV it's more like a management issue rather than a tooling problem. For example, JavaScript won't prevent you from writing bad code, dead loops, etc., while the linters do. In atomic CSS I don't really feel that would matter much, but if you really do, we have blocklist that accepts regex etc, or you can always write your own presets with the strictness in mind. Thanks for bringing this up.

Can we at least get a lint rule?

**Comment by antfu** [comment]
I am ok with enhancing the `blocklist` feature to allow throw warnings or errors if you think that would help. In that case, PR is welcome. But I don't see we would maintain an list of to be 100% compatible officials in the short term. I think it could start as a community preset if someone wants to work on it.

**Comment by texastoland** [comment]
@louiss0 I'm happy to help with that!

**Comment by antfu** [comment]
Created https://github.com/unocss/unocss/issues/3073 this track
