### ISSUE TITLE
Enhance `blocklist`

### ISSUE THREAD

**Issue by antfu** [unocss/unocss#3073]
### Clear and concise description of the problem

Context: https://github.com/unocss/unocss/issues/3070#issuecomment-1704427138

### Suggested solution

I think we could make `blocklist`:

- Accept a custom function
- Able to provide an additional meta
- Can be contributed by presets (so we could also have blocklist-only presets)
- Integrate with ESLint plugin

The interface I imagine:

```ts
blocklist: [
  'p-1', // plain string
  /$ma-(\d+)$/, // RegExp
  (selector) => { // custom string
    return selector.includes('foo')
  },
  [/$ma-(\d+)$/, { warn: true /* additional meta for this rule */ }], // print out warning
]
```

Open for discussions

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [ ] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by texastoland** [comment]
This would solve the user complaint which is primarily autocompleting other styles and possibly enforcing a convention 🙌🏼 The meta would be for tools like ESLint right?

**Comment by louiss0** [comment]
I would like this feature. I wish it gave me access to the rules that were already being enforced. 
That way I could write a condition that would allow me to check for duplicates.

**Comment by louiss0** [comment]
> This would solve the user complaint which is primarily autocompleting other styles and possibly enforcing a convention 🙌🏼 The meta would be for tools like ESLint right?

These are all the differences between preset-windi and preset-uno that I could find. 

| Uno                                     | Windi                                  |
| --------------------------------------- | -------------------------------------- |
| ma-*                                    | m-*                                    |
| pa-*                                    | p-                                     |
| op-*                                    | opacity                                |
| {bg\| text\| border}-{color}-{1-9}      | {bg \| text\| border}-{color}-{50-900} |
| decoration                              | underline                              |
| b                                       | border                                 |
| of                                      | overflow                               |
| position-{absolute \| fixed}            | {absolute \| fixed\| sticky}           |
| flex-{basis\|content\|justify\|items}-* | {basis\|content\|justify\|items}-*     |
| grid-{content\|justify\|items}-*        | {content\|justify\|items}-*            |
| trueGray                                | truegray                               |
|  c-gray                                         | text-gray*  |

`c-` stands for color. 

I hope you can figure this out. The differences are too small for me to complain about. I can migrate and suck it up.

**Comment by antfu** [comment]
- https://github.com/unocss/unocss/commit/339202030b9189c8426c063a0067b762a7ebb264
- https://github.com/unocss/unocss/commit/0956f354f7a91dfea7713856f8dfe33634054b40

These two features have been shipped, let me know if anything else is needed for your case.

**Comment by louiss0** [comment]
> * [3392020](https://github.com/unocss/unocss/commit/339202030b9189c8426c063a0067b762a7ebb264)
> * [0956f35](https://github.com/unocss/unocss/commit/0956f354f7a91dfea7713856f8dfe33634054b40)
> 
> These two features have been shipped, let me know if anything else is needed for your case.

How does this work with the vscode extension. I want to send a message that says no-duplicates.

**Comment by louiss0** [comment]
> > This would solve the user complaint which is primarily autocompleting other styles and possibly enforcing a convention 🙌🏼 The meta would be for tools like ESLint right?
> 
> These are all the differences between preset-windi and preset-uno that I could find.
> 
> Uno	Windi
> ma-*	m-*
> pa-*	p-
> op-*	opacity
> {bg| text| border}-{color}-{1-9}	{bg | text| border}-{color}-{50-900}
> decoration	underline
> b	border
> of	overflow
> position-{absolute | fixed}	{absolute | fixed| sticky}
> flex-{basis|content|justify|items}-*	{basis|content|justify|items}-*
> grid-{content|justify|items}-*	{content|justify|items}-*
> trueGray	truegray
> c-gray	text-gray*
> `c-` stands for color.
> 
> I hope you can figure this out. The differences are too small for me to complain about. I can migrate and suck it up.

I solved the problem this this set of regex. 

```js
{
    blocklist: [
        /^(?:(?:m|p|b)a-)/,
        /^(?:(?:op|of|position|flex|case|grid|decoration|line-height|b|c)-)/,
        /^(?:bg|text|border|outline)-(?:[a-z]+[A-Z][a-z]+)/,
        /^(?:bg|text|border|outline)-(?:[a-z]+)-[1-9]$/,
        /^(?:object)-[a-z]{2}$/,
    ],

}
```

**Comment by texastoland** [comment]
Looks like he already started in 3392020 🙀

This isn't complete. For example Uno doesn't require the dash but TW does. There are also attribtify rules that (I think) extract like `[ma~="4"]`. The best strategy will be to go rule by rule and write a filter. Then we can create `preset-wind-strict` following that convention.

**Comment by texastoland** [comment]
Does Tailwind prevent this? It seems pretty complex!

**Comment by antfu** [comment]
> Then we can create preset-wind-strict

Yes, probably. But no, as I mentioned, we don't have an interest in doing that officially, as it would require a lot of effort, creating duplications, and I don't really see the benefit.

**Comment by enkot** [comment]
@antfu It would be nice to support an additional `message` meta field so that it can be displayed in the warning/error.
For example:
```ts
blocklist: [
  [/^border-/, { message: 'use "b-[val]"' }]
]
```

**Comment by antfu** [comment]
@enkot That sounds like a good idea. Would you like to implement it? We could later figure out how to pass it to ESLint
