### ISSUE TITLE
Result Different between Dev and Build

### ISSUE THREAD

**Issue by mzaini30** [unocss/unocss#3075]
### UnoCSS version

^0.55.6

### Describe the bug

In dev:

![image](https://github.com/unocss/unocss/assets/7939342/a946aac6-3573-4414-93d3-eef8dad2c03a)

After build:

![image](https://github.com/unocss/unocss/assets/7939342/f1b0d5dc-495b-4c71-91e3-6274e8563125)

Not generate after build:

![image](https://github.com/unocss/unocss/assets/7939342/bbac24f2-1f73-49b4-b1c0-70848eabfb5b)

(Inside box are not generate like `[&_.kotak]`)

### Reproduction

https://github.com/mzaini30/support-zen

### System Info

OS: Windows
Browser: Brave
Framework: Svelte

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by chz** [comment]
@antfu, @userquin please help same shit( After production build some classes lost
