### ISSUE TITLE
[✨Feature Request] Support `@hover` in `group-hover`

### ISSUE THREAD

**Issue by xsjcTony** [unocss/unocss#3076]
### Clear and concise description of the problem

First of all, thanks for the `@hover` experimental feature, as this is one of the main reasons I'm migrating.
However, I found that seems `group-hover:` does not support that.
None of `group-@hover:`, `group:@hover:`, `@group-hover:`, `@group:hover:` works for me.

💚

### Suggested solution

`group-@hover:` or `group:@hover:`

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by chu121su12** [comment]
Please see example in usage & test in #3235
