### ISSUE TITLE
[Bug🐞]: Transformer is transfoming HTML content beyond the scope

### ISSUE THREAD

**Issue by xsjcTony** [unocss/unocss#3086]
### UnoCSS version

latest

### Describe the bug

HTML content `hover:(bg-blue-400 font-medium)` is being transformed to `hover:bg-blue-400 hover:font-medium`, and there's no way to stop it with transformer enabled (which is really needed).

It's related to https://github.com/unocss/unocss/issues/1581

### Reproduction

https://unocss.dev/play/?html=DwEwlgbgBAFgtAMwK4BsVQC4FMAeG4DGWAdtgE5QIq5QDOW1B%2BxA9sVlAIZoBcGZnYrTAYwbOABYADFIB8AKChRQkKAFtOCpUpXRseOAFYc6BAHcAjDK7EwG7HABGLJMSJxuGG3c4OCL0jgwYgRgkQ5BHwcQJAFRcQtaLW0lAFVWAGEAZSzFbWAAenAIZJ1iqBYABwBmKUxcfBQAc0ozWrq1C1LtGBYILDIeAApHJqcUJCxJawQ2fDUscCQ1AEo8nSLIbt11ACZKahwoACskWlEEAE9CEnJ6g12TCpq63v6yAF4AIiqADikvt0dJx1ikoGBCJwyM5iHAUCwmiw4E0RDAkI5QSl9PhgjABiJMT0yFgEN8YBgMJVaDwCgUURg0Y4AHT%2BNQFVwsAi0Wjs1hc2hfQlKDBQppYDDfAD6jhQggA1oKwVBZIVNKDCsVkhqtvJtSVdeVOI5aCwJtgoM4KSw1EYoGQwE1yXA6tQEPg6tibqQBs9aq12slxCAsBpiCAoAB28FCEWkSOUVAoS5QAhnDDWsAALyN1F1mxKQA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUlCRYcNgENcdLNBAYoANRvs7MAOLauYTW1dPQABQwhjOgB6W3tHKGcoAFoANw9gLyTSPzAzJAwAD0t4TCwbLgAbEuw8QmIyAApkVChK%2BgAuOABtKlQuvQkuOhgdJNaKjD1yRDgpCuhOvVo0PTg1AF0qddk6AAtoGEGYOk7m1H1B4dG9g6O9RZhCmCSK0msnpOg7Ugw4fZSXO1HgVno8bBUzKg1LIRAoTt1enJREoVA0AJSyYTyRgsNicHh8fjozFIhSSaRNRGoOgScEYToARgAdAAmEmoCRoXCLXasMAnKJReggJl7KKQ85qDFbWSxBxOFzwnrnaxQOzyhIudyeXA%2BHLorZIKVIIA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgTgpgzgDg9gOygSwG4RALgGYEMA2UEANCAC5i5LZxgC2AEmXflnoRAL5A

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
https://unocss.dev/guide/extracting#extracting-from-build-tools-pipeline

**Comment by zyyv** [comment]
You can see https://github.com/unocss/unocss/pull/2770 test case in changed files.
