### ISSUE TITLE
transformer-attributify-jsx is not working with react + nextjs ( postcss )

### ISSUE THREAD

**Issue by siduck** [unocss/unocss#3089]
### UnoCSS version

v0.55.7

### Describe the bug

transformer-attributify-jsx is not working with react + nextjs ( postcss )

error message : 

![image](https://github.com/unocss/unocss/assets/59060246/ecdd9db0-04ea-40c9-8dd2-f6990aea1e29)

### Reproduction

```html
<div bg-red> abc </div>
```

add this in any component of nextjs project that uses postcsss for unocss

minimal project repo : https://github.com/siduck/test_next_unocss

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Dunqing** [comment]
`postcss` only handles `css`, Consider using `@unocss/webpack`?

**Comment by siduck** [comment]
hi @Dunqing i had tried using webpack but it had the same issue :(

also seems like webpack has some issue with unocss, https://github.com/unocss/unocss/issues/419

**Comment by Dunqing** [comment]
Yes, the postcss doesn't support transformer-attributify-jsx
