### ISSUE TITLE
Variant Transformer groups do not get applied when coming from an NPM package

### ISSUE THREAD

**Issue by bennymi** [unocss/unocss#3095]
### UnoCSS version

0.55.7

### Describe the bug

If I'm using an npm package that uses UnoCSS with the variant group transformer (https://unocss.dev/transformers/variant-group) it seems like the styles applied to the components using the `:(...)` grouping do not get applied when using the components of the package, even if the user has the transformer installed and added to the uno config. 

Is there a way to tell UnoCSS to also apply to packages in the nodes folder?

### Reproduction

Reproduction link:

When you click on the dropdown menu the items do not have hover effects.

https://www.sveltelab.dev/76brf4kf9ahbmwm?files=.%2Fsrc%2Froutes%2F%2Bpage.svelte%2C.%2Fvite.config.js%2C.%2Funo.config.ts%2C.%2Fsrc%2Froutes%2F%2Blayout.svelte

They should look like this:

https://ato-ui.vercel.app/docs/components/dropdown-menu

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jacob-8** [comment]
> Is there a way to tell UnoCSS to also apply to packages in the nodes folder?

In my experience when I build UI components to put in a package to be used elsewhere, I find things work better if I preprocess the UnoCSS into CSS on package build. That way I can use them anywhere regardless of whether consumers use UnoCSS or not (or use it differently than I). Take a look at https://unocss.dev/integrations/svelte-scoped#svelte-preprocessor and see if that can help your situation. Maybe that in combination with CSS variants can give you the customization you're looking for? Though I'm not sure if this helps at all if your system is dependent on consumers having a specific UnoCSS setup...
