### ISSUE TITLE
VSCode Extension doesn't seem to work in Devcontainers

### ISSUE THREAD

**Issue by Dan6erbond** [unocss/unocss#3106]
### UnoCSS version

v0.55.6 (Unocss) / v0.55.7 (Extension)

### Describe the bug

I am using the Unocss extension for VSCode with a monorepo project that I'm developing in Devcontainers. I'm using a Node.js based Devcontainer from Microsoft with the following `Dockerfile`:

```dockerfile
FROM mcr.microsoft.com/devcontainers/javascript-node:1-20-bullseye
```

Since it's a monorepo, I also have the following `.vscode/settings.json`:

```json
{
  "unocss.root": "client"
}
```

I also tried switching to multi-root workspaces to see if it would make any difference, to no avail, with the following config:

```json
{
  "folders": [
    {
      "path": "."
    },
    {
      "path": "client"
    },
    {
      "path": "server"
    }
  ],
  "settings": {
    "unocss.root": [
      "client"
    ]
  }
}
```

Without the Devcontainer both configurations work. It's only in Devcontainers where Unocss isn't able to give me Intellisense or autocomplete. There's also no output in the extensions tab that seems suspicious. 

### Reproduction

Can't, this is a VSCode extension issue.

### System Info

MacOS, VSCode latest, all updates installed.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
I think this issue could be closed.
