### ISSUE TITLE
Add support for string: type hint or type hints in from CSS Types.

### ISSUE THREAD

**Issue by louiss0** [unocss/unocss#3107]
### Clear and concise description of the problem

The problem with unoCSS is that it's variable type hinting feature is incomplete it only supports color and number.
It has to support words as well.  If it doesn't then variables won't be used properly in many situations.

When I type. 
```html
<div
  class="border-[color:--gray-500] border-[length:--gray-500]"
>
Hello world
  </div>
```

The `color:` hint tells the compiler to use `border-color:`. The `length:` hint tells the compiler to use  `border-width:`. 

But If I try.

```html 
<div
  class="border-[color:--gray-500] border-[length:--gray-500] border-[string:--key-win-9]"
>
 Hello world
</div>
```

The compiler doesn't know what to do the default is used.

 

 

### Suggested solution

You can support the`string:` variable type hint. it's a hint that will help the organization of variables.
That way when a word is typed for border the compiler can receive the right hint.

When I type. 

```html 

<div
  class="border-[string:--variable-]"
>
Hello World
</div>
``` 
The compiler would infer that I'm using `border-style`. 

This is all I want but you can also use the [this site](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Types)
To provide even better type hints.

### Alternative

None. 

### Additional context

I'm creating a library that will use this type hint to attempt to figure out how to move classes around properly. 
I discovered the need this there. I could have just relied on the `color:` and the `length:` hint but this one is enough. 
The `string:` type hint is for properties that need a keyword as a value. 

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [ ] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by louiss0** [comment]
If you want to know what I mean use this [repo](https://github.com/louiss0/dummy-astro-unocss).
Make sure you have the VS Code extension installed.
Go to the `MyComponent.astro` file. 
You will see three border classes there all you have to do is hover over the

**Comment by louiss0** [comment]
omg

**Comment by chu121su12** [comment]
The intention of typing `border-[string:--key-win-9]` can still be interpreted 4 way due to the nature of variable syntax: color, width, style, globals

Color and number are prioritized due to their regularity. Even if you force `--key-win-9` as string, the colors and width have string values too.
![image](https://github.com/unocss/unocss/assets/379924/b48ad8b5-e1cd-4c39-aacc-e67dfb7b0e93)

I'd recommend to override the border implementation to handle these cases.
