### ISSUE TITLE
Use of template strings in reactive variables does not generate corresponding style

### ISSUE THREAD

**Issue by HighSky2GT** [unocss/unocss#3110]
### UnoCSS version

latest

### Describe the bug

use of template strings in reactive variables does not generate corresponding style

### Reproduction

https://stackblitz.com/edit/unocss-unocss-eqsbmj?file=src%2FApp.vue

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
Please use full utiility string to use.
```ts
const color = val ? 'bg-black' : 'bg-red';
```
Or put them into `safelist`
```ts
const color = val ? `${bg}black` : 'bg-red';

// uno.config.ts
safelist: ['bg-black']
```

**Comment by HighSky2GT** [comment]
Can't just use `${bg}black`? I'm not familiar with unocss yet. Can I follow up this feature

**Comment by HighSky2GT** [comment]
> Please use full utiility string to use.
> 
> ```ts
> const color = val ? 'bg-black' : 'bg-red';
> ```
> 
> Or put them into `safelist`
> 
> ```ts
> const color = val ? `${bg}black` : 'bg-red';
> 
> // uno.config.ts
> safelist: ['bg-black']
> ```


Can't just use ${bg}black? I'm not familiar with unocss yet. Can I follow up this feature
