### ISSUE TITLE
Variant combinator(s) working badly with nested util

### ISSUE THREAD

**Issue by AsakuraMizu** [unocss/unocss#3124]
### UnoCSS version

0.55.7

### Describe the bug

(Variant `combinator`(s) refer to https://github.com/unocss/unocss/blob/main/packages/preset-mini/src/_variants/combinators.ts)

Current implementation of combinators generates undesired selector order. Variants other than combinators can not be applied to the correct position.

There are previous discussions about this in #958 and #1104, but they do not consider nesting when the order of variants can not be changed.

### Reproduction

[Playground](https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIFzgWgNoAOAugFwAWA9hAKYBOJARgOY63UjoB8AUFFMAU4AXakiEBGAuOAB6Qb36CRYyQCZZ82eAg9uoSLEQoMlGvSy5CpZq3ZcFA4aKGqpGnn0fKXBdXJ5akLr60PDIaJjY%2BMQkMACuYhQAtjhIlLRC8UL2nkrOAMxu-g55YoV%2BmjLaPEA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVHQAFtAwEjx0AFyIVKh6YXQwOgC0QSFhMHpResEAbhhQERykSbRoZqhqsiIKkXAA2jFyokoqPgCUssLyjCxsnDx8-O2dTQqS0n6NARL2ThhRAIwAdABMI6gSaLhZgaxgkQD0B-QgS0EH5ahwah1UALpIN0hAA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYgFyQK4FMA0408yaAwtnGEqmQMp2YJQA2cBRsiKqAEmKhZNW7QhFxwADkngBLAG65hbXAF8gA)

When I write:
```html
<div class="all-[p]:hover:bg-red">
  <p>test1p1</p>
  <p>test1p2</p>
</div>
```
It will make the background of two `p`s inside `div` turn red when hover on `div`. What I want is to change the hovered one's background. So I have to write:
```html
<div class="hover:all-[p]:bg-red">
  <p>test2p1</p>
  <p>test2p2</p>
</div>
```
In a reverse order!

When it comes to more complex situations, the solution is not so simple. For example I have a shortcut `custom-shortcut` aliasing to `hover:bg-red` and I want to use it like:
```html
<div class="all-[p]:custom-shortcut">
  <p>test3p1</p>
  <p>test3p2</p>
</div>
```
It works just like what `all-[p]:hover:bg-red` does.

By the way #2575 is still not fixed, using `all` instead of `all-[p]` does not work for the second example.

### System Info

(agnostic)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by chu121su12** [comment]
For complex nesting, is it possible to rewrite with dynamic variant? 
https://github.com/unocss/unocss/blob/5dcc8ceddb7b6acbb06be914b5f1bd3a444c8976/test/assets/preset-mini-targets.ts#L1079-L1082
