### ISSUE TITLE
Here are some elements that don't need to be compiled, but appear in the output file

### ISSUE THREAD

**Issue by micisse** [unocss/unocss#3125]
### UnoCSS version

0.55.7

### Describe the bug

Here are some elements that don't need to be compiled, but appear in the output file. Screenshots and video should help to understand the problem in vscode with unocss extension. I've attached a small zip file for reproduction. The components were created just for the test. In css/scss files, highlighting is also applied to elements that match. If we compile css files, matching elements will also be output, even if they're not used.

https://github.com/unocss/unocss/assets/56940294/c934e406-04a2-4225-b407-8824f827e749

![Capture d’écran_2023-09-14_21-51-29](https://github.com/unocss/unocss/assets/56940294/f7600f4a-6b0c-41a5-bf94-fc483b04788e)
![Capture d’écran_2023-09-14_21-51-47](https://github.com/unocss/unocss/assets/56940294/372ff66d-a04e-4cd8-8ebf-081bb3b9f580)
![Capture d’écran_2023-09-14_21-58-23](https://github.com/unocss/unocss/assets/56940294/1b8b4222-7a16-413f-866e-b8144080cecf)
![Capture d’écran_2023-09-14_22-19-26](https://github.com/unocss/unocss/assets/56940294/b9cfff69-e582-45e8-82fa-43ca7c00037e)
![Capture d’écran_2023-09-14_22-31-13](https://github.com/unocss/unocss/assets/56940294/4c4d6067-fd18-4ec5-95a2-9dab018da901)
![Capture d’écran_2023-09-14_22-41-45](https://github.com/unocss/unocss/assets/56940294/501975e6-12ab-4d2d-b871-0fe2429e317c)
![Capture d’écran_2023-09-15_00-56-38](https://github.com/unocss/unocss/assets/56940294/1c7a75a1-4eb1-4442-96b0-b0db0953474f)
![Capture d’écran_2023-09-15_00-34-16](https://github.com/unocss/unocss/assets/56940294/d2a75699-b99a-4600-acd6-6d047c308209) - **If unocss needs to compile this css file, it will compile @apply ... + "relative" and if there are other elements that match in the file, it will also generate them even if they are not used. I tested it**

### Reproduction

[vite-react-uno.zip](https://github.com/unocss/unocss/files/12614016/vite-react-uno.zip)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by MarvinXu** [comment]
I also found [this](https://unocss.dev/play/?html=DwZwxgTglgDgLgPgFAAIUBsCmcUCMUC8KAjANxLAD0408CQA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMA6nmkgL5xZQQhwDkAV1wQAxnTr8kSDAA9IsdNgCGggDbxMOfERLBSACmSoa9RnQBccANpUTtBs1YGAlFQC6HN0A&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g). Not sure if it's a intended behavior or a bug.
