### ISSUE TITLE
CSS directive intellisense

### ISSUE THREAD

**Issue by silveltman** [unocss/unocss#3127]
### Clear and concise description of the problem

I'm currently using shortcuts for creating a little component library. However, things get messy very quickly, extremely long lines of classes, especially when using mediaqueries. Even worse with arbitrary selectors. 

However, to my knowledge the shortcuts are the only way to create these components WITH intellisense. And intellisense is very much needed.

The problem is worse because to my knowledge we're not able to use features like Variant Groups within the shortcuts.

### Suggested solution

Intellisense for CSS directives with @apply.

This would allow us to better organize and make use of sass nesting which would eliminate a lot of the mesyness.

### Alternative

1. Shortcuts
2. Allowing Variant Groups in shortcuts
3. Make the vscode extension automatically organize things, like each variant on a new line (havent found a solution like this yet)
4. There is probably a way with javascript to write everything in css > turn it into css-in-js > add it as shortcuts. However, have not found a good working example of this

### Additional context

This would also eliminate the need for a server restart every time the shortcuts change.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by silveltman** [comment]
Update:

Hot reloading of my shortcuts was not working because I'm setting the shortcuts in a preset. If there's a way to fix it, would gladly hear it! :) 

Same appear to be true for Variant Groups, correct?

**Comment by Simon-He95** [comment]
> Update: 更新：
> 
> Hot reloading of my shortcuts was not working because I'm setting the shortcuts in a preset. If there's a way to fix it, would gladly hear it! :)快捷方式的热重载不起作用，因为我正在预设中设置快捷方式。如果有办法修复它，很乐意听到它！:)
> 
> Same appear to be true for Variant Groups, correct?变体组似乎也是如此，对吗？

Your hot update does not take effect. Are you referring to the update of the uno.config file and the intellisense on the plug-in? #3194

**Comment by silveltman** [comment]
It might have had something to do with me importing all my presets into a preset, and then that preset into the main config.

Also, I added the following (referenced in antoher issue):
```
function getUnoPresets(dir) {
  const files = fs.readdirSync(dir);
  return files
    .filter((file) => path.extname(file) === '.ts')
    .map((file) => path.join(dir, file));
}


UnoCSS({
  configDeps: getUnoPresets('src/uno/tenants'),
}), 
````

Anyway, it's fixed right now, thanks!
