### ISSUE TITLE
Open VSX version of VSCode Extension is outdated

### ISSUE THREAD

**Issue by aviadmini** [unocss/unocss#3129]
### UnoCSS version

0.55.7

### Describe the bug

Extension version is severely outdated on OpenVSX

v0.55.7 at [Microsoft VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=antfu.unocss)
v0.22.5 at [OpenVSX ](https://open-vsx.org/extension/antfu/unocss)

### Reproduction

Doesn't apply

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Enderchief** [comment]
I wonder why it stopped being updated.
First it was removed from the GitHub workflow https://github.com/unocss/unocss/commit/0b83d0d74dbfb7221b766fda747d043f14cd3504 on Feb 7, 2022
Then re-added https://github.com/unocss/unocss/commit/2001c488ebcd682fd08ec3df6d5423528a7fedd3 on March 16, 2020 and removed https://github.com/unocss/unocss/commit/4bb41efb0efa47b5fe10fa4b04dcfa72efcbe014 the same day.

**Comment by antfu** [comment]
It was because the OVSX cli was left behind and unmaintained at that time, causing the release to fail. I'll check again

**Comment by antfu** [comment]
Brought it back https://github.com/unocss/unocss/commit/5e31913f5074d57c81f3d161f255587bd2912910
