### ISSUE TITLE
raise TypeError when dynamic imports icon

### ISSUE THREAD

**Issue by zhlgh603** [unocss/unocss#3132]
### UnoCSS version

0.55.7

### Describe the bug

> yarn dev
Failed to load custom icon "3d-cursor" in "carbon": TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".json" for P:\projects\vue\my-vue-app\node_modules\@iconify\json\json\carbon.json
    at new NodeError (node:internal/errors:371:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:87:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:102:38)
    at defaultLoad (node:internal/modules/esm/load:21:14)
    at ESMLoader.load (node:internal/modules/esm/loader:359:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:280:58)
    at new ModuleJob (node:internal/modules/esm/module_job:66:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:297:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:261:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}

// vite.config.ts
import { resolve } from 'node:path'
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import UnoCSS from 'unocss/vite'
import presetIcons from '@unocss/preset-icons'
import { FileSystemIconLoader } from '@iconify/utils/lib/loader/node-loaders'

const iconDirectory = resolve(__dirname, 'icons')

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue(),  
    UnoCSS({
      presets: [
        presetIcons({
          collections: {
            custom: FileSystemIconLoader(iconDirectory),
            carbon: () => import('@iconify/json/json/carbon.json').then(i => i.default),
            'assets': FileSystemIconLoader(
              './assets/icons',
              svg => svg.replace(/#fff/, 'currentColor')
              )
          },
        }),
      ],
    }),
  ],
})

### Reproduction

https://github.com/zhlgh603/unocss-icons-demo.git

### System Info

VSCode Version: 1.82.1 
Node: 16.14.2
npm: 8.6.0
OS: Windows_NT x64 10.0.19045

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jokerwon** [comment]
Has the issue been solved?
