### ISSUE TITLE
Parcel JS Bundler support

### ISSUE THREAD

**Issue by activivan** [unocss/unocss#3133]
### Clear and concise description of the problem

For usage with bundlers, UnoCSS currently supports Webpack and Vite/Rollup. Parcel is another web-bundler that gains more and more popularity among developers because it is easier to set up and convinces with its speed, however is not supported by UnoCSS. 

### Suggested solution

Adding support for Parcel could be achieved by creating a transformer plugin. More information about Parcels plugin system can be found on its website: https://parceljs.org/plugin-system/overview/

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by yzqdev** [comment]
Currently I'm using unocss cli to generate css files, and a parcel plugin is better.

**Comment by mochaaP** [comment]
Will be nice if we can get <https://unocss.dev/transformers/compile-class> support here.
