### ISSUE TITLE
[BUG🐞] Unocss/webpack and thread-loader are not compatible.

### ISSUE THREAD

**Issue by NNNaix** [unocss/unocss#3139]
### UnoCSS version

0.55.7

## Environment
webpack: 5.88.2
thread-loader: 4.02
nodejs: 16.17.1
os: MacOS  Big Sur  11.4 (20F71)  [Apple M1] 

## Webpack Config
when I config webpack loader like this
```ts

{
    test: /\.(tsx?|js)$/,
    use: [
        {
            loader: 'thread-loader',
            options: {
                // 选项可以直接传递给 thread-loader
                worker: 'worker', // 默认为 'worker'，也可以是一个字符串或函数
                poolTimeout: 2000 // 空闲线程等待任务的超时时间，默认为 2000（2 秒）
            }
        },
        {
            loader: 'babel-loader',
            options: {cacheDirectory: true,},
        }
    ],
    exclude: /node_modules/,
},

// .... other config

{
   plugins: [     
      UnoCSSPlugin({
          configFile: resolve(appRootPath, './uno.config.ts'),
      }),
    ]
}
```

## Error trace: 
![image](https://github.com/unocss/unocss/assets/22340567/fcf97353-4802-4943-ad94-aa429c5c57c9)

###  both the unocss webpack plugin and thread-loader are present in wepback configuration file.

> If I comment out thread-loader or UnoCSSPlugin, this problem will be solved.

If it’s a normal construction, this._compiler?.$unpluginContext should have the following value.
```ts
{
  'unocss:webpack': {
    name: 'unocss:webpack',
    enforce: 'pre',
    transformInclude: [Function: transformInclude],
    transform: [AsyncFunction: transform],
    resolveId: [Function: resolveId],
    loadInclude: [Function: loadInclude],
    load: [Function: load],
    webpack: [Function: webpack],
    __unpluginMeta: { framework: 'webpack', webpack: [Object] },
    __virtualModulePrefix: '/Users/nnnaix/EpicShit/spotter/sevc-group/finance/_virtual_',
    __vfsModules: Set(1) {
      '/Users/nnnaix/EpicShit/spotter/sevc-group/finance/_virtual_%2F__uno.css'
    },
    __vfs: VirtualModulesPlugin {
      _compiler: [Compiler],
      _watcher: null,
      _staticModules: null
    }
  }
}


```
If both the unocss webpack plugin and thread-loader are present, this._compiler?.$unpluginContext will be undefined.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
It's a known limitation of unplugin. UnoCSS also requires a single global context to work. I am not sure how to workaround it.
