### ISSUE TITLE
Support for variables with Negative variant

### ISSUE THREAD

**Issue by XEngine** [unocss/unocss#3141]
### Clear and concise description of the problem

When using a class like `mt-[var(--header-height,81px)]`, it gets transformed to `"margin-top: var(--header-height, 81px)."` However, it appears that adding a "-" (negative sign) as a prefix to the mt class has no effect on the transformed result except it only transforms the default numeric value and add a negative sign to beginning like -81px.

### Suggested solution

it can be transformed to "```calc(var(--header-height,81px) * -1)```"

### Additional context

[_UnoCSS Playground Link_
](https://unocss.dev/play/?html=FAAjIHgEwSwNzAYwDYEMDO6C8AiAtALYAueA2nKgE4AUeeAFgKapSOUOMwDm9RANAEYArAAYADgA8AlAF0cAPlDgwAVQB2AewDCAZR1KwEAPSw4i5UA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUkNikEA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmjraakVYcKb%2BNjbktIwUM44ubmAAHJ6CcgNAA&options=N4XyA)
### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by chu121su12** [comment]
With the parser we have right now, it may be difficult to do selective negative replacement. Adding var() to negateable candidate does `calc(var(--un-blur) * -1)` and many interesting css surprise.

It may require adding new rule context/logic to detect supported rule such as `m-<1 side>`, but not `m-<global>`.
