### ISSUE TITLE
unocss 中使用theme主题配置项，文档说明不清楚。目前只知道colors 和 spacing 配置项。 其他比如字体的配置项找不到。

### ISSUE THREAD

**Issue by fslflame** [unocss/unocss#3154]
### UnoCSS version

0.56.1

### Describe the bug

目前只知道colors 和 spacing 配置项。 其他比如字体的配置项找不到。

### Reproduction

![image](https://github.com/unocss/unocss/assets/101857530/81022bff-aab4-477f-94ee-330086cd3a35)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
参照 Tailwind 文档
