### ISSUE TITLE
unoCSS grid-template-columns不支持自定义参数. tailwindcss中使用中括号[ ] unocss中没有方式

### ISSUE THREAD

**Issue by fslflame** [unocss/unocss#3160]
### Clear and concise description of the problem

![image](https://github.com/unocss/unocss/assets/101857530/8b452764-0c21-43f3-841d-df485942d375)
![image](https://github.com/unocss/unocss/assets/101857530/486ba4d3-d23f-42fb-b9b6-e2eafedf6ae7)

### Suggested solution

有更好的处理方法吗？ 如果可以rules可以处理可以给个示例吗 谢谢大佬！

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
https://unocss.dev/interactive/?s=grid-cols-[50%25_50%25]

**Comment by fslflame** [comment]
Thank you, boss. I don't see the document
