### ISSUE TITLE
Too many atomic classes make saving files very sluggish

### ISSUE THREAD

**Issue by diamond2221** [unocss/unocss#3161]
### UnoCSS version

v0.56.1

### Describe the bug

Many atomic classes were used in the file, and saving the file was very cumbersome。

### Reproduction

*

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
You can always disable ESLint rules if you don't want using it.
