### ISSUE TITLE
Files in `node-modules` not extracted by default anymore

### ISSUE THREAD

**Issue by johannschopplich** [unocss/unocss#3170]
### UnoCSS version

0.56.3

### Describe the bug

Although by default, `node_modules` and `dist` should also be extracted, with PR https://github.com/unocss/unocss/pull/3069 the default exclude list got overridden:

https://github.com/unocss/unocss/blob/783135c079de97b7edcfe56439a619ffde079c86/packages/shared-integration/src/defaults.ts#L4
The regex `/[\/](node_modules|dist|\.temp|\.cache|\.vscode)[\/]/` was added, effectively disallowing utility generation for these folders.

As a result, UnoCSS won't generate utilities for imported components from UI packages.

### Reproduction

Not needed in my opinion, since origin of issue is pointed out above.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Oh yeah, that was a mistake.

**Comment by johannschopplich** [comment]
PR incoming, or will you be faster already? 🙂

**Comment by antfu** [comment]
Oh yeah, I did. Thanks :P

**Comment by johannschopplich** [comment]
Damn. I thought so. Thanks a lot! 🤗
