### ISSUE TITLE
Will inline properties conflict with props?

### ISSUE THREAD

**Issue by Simon-He95** [unocss/unocss#3174]
### Clear and concise description of the problem

Maybe the props required by the component like left will be compiled into class by unocss

<Foo left="20"></Foo>

### Foo
```vue
defineProps({left:0})
```

It may also generate the left:0 class on the foo container.

### Suggested solution

There is a filter that can only enable the detection and conversion of attributes in class or className for the page, not for all attr.

```
{
  onlyClassDetection: {
    include: [],
    exclude: []
  }
}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Dunqing** [comment]
It sounds like you can use [blocklist](https://unocss.dev/guide/extracting#blocklist).

**Comment by Simon-He95** [comment]
> It sounds like you can use [blocklist](https://unocss.dev/guide/extracting#blocklist).

This should cause the global class to become unusable. I might just want it to be specific to individual pages, and I just want it to not take effect as an attribute, but I still need to keep it working within the class.

**Comment by antfu** [comment]
You don't need to disable globally: https://github.com/unocss/unocss/blob/f9a4e81dc20cea2f880b21aae99f0ac97fcbeb26/packages/preset-attributify/src/types.ts#L35-L39

**Comment by Simon-He95** [comment]
> You don't need to disable globally:
> 
> https://github.com/unocss/unocss/blob/f9a4e81dc20cea2f880b21aae99f0ac97fcbeb26/packages/preset-attributify/src/types.ts#L35-L39

This attribute is really helpful. This means that if I use ignoreAttributes:['left', 'top'], all `left=""` & `top=""` in the page will be invalid for unocss. It would be nice to have a more accurate one. Controls, for example, only for individual pages, their components may have props and unocss attribute conflicts. You need to enable this ignoreAttributes, otherwise, other pages that need to use the left or top as an attribute will lose this style.
