### ISSUE TITLE
feat: ask for !(bg-black text-white) variant transformer group support

### ISSUE THREAD

**Issue by SnowingFox** [unocss/unocss#3175]
### Clear and concise description of the problem

```ts
<div className={'!bg-black !text-white'} />
```
we will write `!` twice to implement this style, and it's not intuitive

### Suggested solution

we can do it like this

```ts
<div className={'!(bg-black text-white)'} />
```

### Alternative

```ts
<div className={'!bg-black !text-white'} />
```

### Additional context

i will try to provide a pr to solve this problem

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
You could do `important:(bg-black text-white)` today tho 👀
