### ISSUE TITLE
Changing configuration in auto roots mode creates duplicate instances

### ISSUE THREAD

**Issue by csvn** [unocss/unocss#3181]
### UnoCSS version

0.56.0

### Describe the bug

When using "auto-roots search mode" and editing the `unocss.config.js` file, each restart will create a new watcher and process resulting in duplication. Each of the following will be duplicated once for every edit of the config file:

- Color-badge eannotations on HTML classes
- CSS rules tooltip when hovering HTML classes
- Output in VSCode for "UnoCSS" (resolved config, loaded presets, etc)
- And maybe more

https://github.com/unocss/unocss/assets/8770194/1014fb40-8b94-4488-9918-92d2a73dcefe

I can't reproduce this issue with the "Manual roots search mode". In that mode, it will only print "🛠 Config reloaded by CONFIG_FILE", and there are no duplicated color badges or hover hints.

### Reproduction

1. Install the UnoCSS extension in VSCode
2. Open a blank project
3. Install `unocss` with npm/pnpm/yarn/etc
4.  Add `unocss.config.js` & `main.tsx` files (see below).
5. Make some edits to config file
6. Every time config file is saved, extra color badges, hover text sections and logs can be seen.

```ts
// unocss.config.js
import { defineConfig, presetUno } from 'unocss';

export default defineConfig({
  presets: [
    presetUno({}),
  ],
});
```

```tsx
// main.tsx

function Test() {
  return <p class="color-amber">Lorem ipsum</p>
}
```

### System Info

No framework, just VSCode and a few files:

- VSCode (1.82.2)
- A config file
- A file to trigger UnoCSS extension completions

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by csvn** [comment]
It may be a separate issue, but I also found that the automatic mode did not respect `"unocss.languageIds"` in VSCode settings. It still highlight strings found in `unocss.config.js` itself, even with `["typescriptreact"]` set explicitly in `languageIds`.

**Comment by Simon-He95** [comment]
> ### UnoCSS version
> 0.56.0
> 
> ### Describe the bug
> When using "auto-roots search mode" and editing the `unocss.config.js` file, each restart will create a new watcher and process resulting in duplication. Each of the following will be duplicated once for every edit of the config file:
> 
> * Color-badge eannotations on HTML classes
> * CSS rules tooltip when hovering HTML classes
> * Output in VSCode for "UnoCSS" (resolved config, loaded presets, etc)
> * And maybe more
> 
>  Screenshare.-.2023-09-27.5_57_22.PM.mp4 
> 
> I can't reproduce this issue with the "Manual roots search mode". In that mode, it will only print "🛠 Config reloaded by CONFIG_FILE", and there are no duplicated color badges or hover hints.
> 
> ### Reproduction
> 1. Install the UnoCSS extension in VSCode
> 2. Open a blank project
> 3. Install `unocss` with npm/pnpm/yarn/etc
> 4. Add `unocss.config.js` & `main.tsx` files (see below).
> 5. Make some edits to config file
> 6. Every time config file is saved, extra color badges, hover text sections and logs can be seen.
> 
> ```ts
> // unocss.config.js
> import { defineConfig, presetUno } from 'unocss';
> 
> export default defineConfig({
>   presets: [
>     presetUno({}),
>   ],
> });
> ```
> 
>  ```tsx
> // main.tsx
> 
> function Test() {
>   return <p class="color-amber">Lorem ipsum</p>
> }
> ```
> 
> ### System Info
> No framework, just VSCode and a few files:
> 
> * VSCode (1.82.2)
> * A config file
> * A file to trigger UnoCSS extension completions
> 
> ### Validations
> * [x]  Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
> * [x]  Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
> * [x]  Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
> * [x]  The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

You can try to uninstall and reinstall it to see if it can be solved. I will continue to track this problem later.

**Comment by csvn** [comment]
I switched to the manual mode, by adding `"unocss.root"` config, so for now I don't have this issue myself. I just reported it felt like a footgun that the default automatic mode produced this.

When I created a minimal repro, I also did a new `npm install` etc, and that did not help.
