### ISSUE TITLE
transformer-attributify-jsx false positive

### ISSUE THREAD

**Issue by alexander-entin** [unocss/unocss#3182]
### UnoCSS version

0.56.4

### Describe the bug

The transformer should not touch below code:

````javascript
export function App() {
  let card = {};
  return <div {...{ card }} />;
}
````

but it does:
````
[plugin:vite:preact-jsx] /home/projects/unocss-unocss-beuqvz/src/app.tsx: Invalid shorthand property initializer. (3:24)

/home/projects/unocss-unocss-beuqvz/src/app.tsx:3:20
1  |  export function App() {
2  |    let card = {};
3  |    return <div {...{ card="" }} />;
   |                            ^
4  |  }
5  |
````

### Reproduction

https://stackblitz.com/edit/unocss-unocss-beuqvz?file=src%2Fapp.tsx,vite.config.mts

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zhiyuanzmj** [comment]
> /cc @zhiyuanzmj since you made https://github.com/unocss/unocss/pull/3116, and might be related. Would you be interested in helping out? Thanks

👌
