### ISSUE TITLE
Endless Loop of Hot Updates in Unocss Caused by Adding Class Names to `uno.generator.config.safelist` in Custom Rule

### ISSUE THREAD

**Issue by euwei7** [unocss/unocss#3190]
### UnoCSS version

^0.56.4

### Describe the bug

我正在使用 unocss 开发 UI 组件库和组件库的 unocss 预设。这个组件库的特点是在编译后不会生成任何 CSS，而是通过自定义的预设来生成。所以其他开发人员在使用组件库时，只需要将组件库的预设添加到他们的 `uno.config.ts` 文件中，而不需要引入任何 CSS。这样他们的 unocss 就能根据预设生成组件的 CSS 样式。

组件库中的组件使用了很多动态的类名，同时组件库需要实现按需引入并生成 CSS。因此，我不能直接将动态的类名添加到预设中的 `safelist` 配置项中，因为这样会导致 CSS 冗余。经过一番思考，我在自定义的预设中添加了一个规则，用来匹配代码中使用的组件，并将该组件所使用到的动态类名添加到 `uno.generator.config.safelist` 中，以满足按需生成 CSS 的要求。

一直以来都很正常，但为了实现组件库的更多功能，我增加了一些规则到预设中。然后，我发现热更新异常，修改代码保存有时会导致 unocss 无限触发热更新，直到浏览器卡死。经过排查，我发现当将类名添加到 `uno.generator.config.safelist` 时，如果添加的类名对应的规则是耗时操作，unocss 会无限触发 uno.css 的热更新。

I'm using unocss to develop a UI component library and its unocss preset. The unique feature of this component library is that it doesn't generate any CSS during compilation. Instead, it generates CSS based on a customized preset. So, when other developers use the component library, they simply need to add the library's preset to their `uno.config.ts` file without importing any CSS. This allows their unocss to generate CSS styles for the components based on the preset.

The components in the library utilize many dynamic class names, and the library needs to support on-demand importing and CSS generation. Therefore, I can't directly add the dynamic class names to the `safelist `configuration in the preset, as it would result in CSS redundancy. After careful consideration, I added a rule to the custom preset to match the components used in the code. I then included the dynamic class names used by those components in `uno.generator.config.safelist` to fulfill the requirement of generating CSS on-demand.

Everything has been running smoothly so far. However, in order to implement additional functionalities for the component library, I added some extra rules to the preset. Subsequently, I encountered an issue with hot updates. Occasionally, saving the code would trigger an infinite loop of hot updates in unocss, causing the browser to freeze. After investigation, I discovered that when adding class names to `uno.generator.config.safelist`, if the corresponding rules for those class names involve time-consuming operations, unocss would continuously trigger hot updates in uno.css.

Reproduction Steps:
1. Run `pnpm run install`.
2. Run `pnpm run dev`.
3. Modify `uno.config.ts` or other files and save the changes to trigger unocss hot update. Open the browser console to view the messages.

https://github.com/unocss/unocss/assets/120472761/469786d2-1a31-4942-a745-f4e647d3a68d

### Reproduction

https://github.com/euwei7/test

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by euwei7** [comment]
另外，能否在自定义预设中添加 "includes" 配置项？因为组件库作为第三方库安装在 "node_modules" 中，使用时需要在 "vite.config" 或 "uno.config" 中配置 "includes"，以扫描组件库文件，例如：`include: [/(.*\/)unop-ui(.*)\.(c|m)?(js)(x?)$/, '**/*.vue', '**/*.ts']`。这样做太繁琐了。如果能在预设中添加 "includes" 配置项，我就可以直接在组件库的预设中配置，而使用组件库的开发人员就不用再进行配置了。

Additionally, could add an "includes" configuration option in the custom preset? As the component library is installed as a third-party library in "node_modules", developers need to configure "includes" in "vite.config" or "uno.config" to scan the component library files, for example: `include: [/(.*\/)unop-ui(.*)\.(c|m)?(js)(x?)$/, '**/*.vue', '**/*.ts']`. This process is too cumbersome. If could add an "includes" configuration option in the preset, I could directly configure it in the component library's preset, and developers using the component library would not need to configure it again.

🌹🌹🌹🌹🌹❤️❤️❤️❤️❤️❤️

**Comment by zyyv** [comment]
Even if this is a bug, I recommend treating uno `context` as a read-only object using.

**Comment by euwei7** [comment]
> Even if this is a bug, I recommend treating uno `context` as a read-only object using.

Thank you for your suggestion, I will look for other workarounds
