### ISSUE TITLE
Nested shortcuts configuration

### ISSUE THREAD

**Issue by silveltman** [unocss/unocss#3193]
### Clear and concise description of the problem

When needing classes like `button-primary` and `button-secondary` defining shortcuts gets very messy. Especially when having a lot of them. 

### Suggested solution

Allowing to define shortcuts in a nested way:
```
    button: {
      primary: 'my-cool-classes',
      secondary: 'my-cool-classes',
    },
```
Suboptimal solution would be to automatically transform camelCase to kebab-case. This would make things more readable, since the key doesn't have to be a string, but thats about it.

### Alternative

Manually do it, like this:

```
const components = {
    button: {
        primary: '',
        secondary: '',
        tertiary: '',
    },
    heading: {
      primary: '',
      secondary: ''
   }
};

function flattenShortcut(name, shortcut) {
  return Object.entries(shortcut).reduce((acc, [key, value]) => {
    acc[`${name}-${key}`] = value;
    return acc;
  }, {});
}

function flattenShortcuts(shortcuts) {
  return Object.entries(shortcuts).reduce((acc, [key, values]) => {
    const flattened = flattenShortcut(key, values);
    return { ...acc, ...flattened };
  }, {});
}

console.log(flattenedComponents(components);
```
This script will output:
```
{
    "button-primary": "",
    "button-secondary": "",
    "button-tertiary": "",
    "heading-primary": "",
    "heading-secondary": ""
}
```

### Additional context

Similar to https://github.com/unocss/unocss/issues/1677, but thought it could be described better. Also, that one has been closed for a very long time without reason.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Since it's not hard to do it in the userland (as you have shown). I think it would be better to leave that to users and not to bloat the core which is aiming to be simple and lightweight.  Thanks for bringing this up.
