### ISSUE TITLE
Rename preset wind

### ISSUE THREAD

**Issue by benmccann** [unocss/unocss#3195]
### UnoCSS version

Any

### Describe the bug

WindiCSS is sunset. That would lead one to believe you shouldn't use preset wind in new projects. However it's unclear if preset wind is sunset as well. There was a bit of discussion about this on the Svelte Discord. It'd probably be clearer to call it preset tailwind 

### Reproduction

Library available via npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
It's `wind` not `windi`. Meaning it would be a common part between `tailwind` and `windi`.

WindiCSS the tools are sunsetting (but not deprecated btw), that said it doesn't mean the good conventions it brought up should be sunset as well.

`preset-wind` is not a 1:1 equivalent of tailwind, and we are not going to maintain one (leaving that to the community if someone finds that valuable). I don't think we are going to rename it any sooner. Thanks for bringing this up.
