### ISSUE TITLE
ring-offset-0 missing unit

### ISSUE THREAD

**Issue by DSeeLP** [unocss/unocss#3196]
### UnoCSS version

0.55.7

### Describe the bug

`ring-offest-0` is missing unit in generated css and declaring a unit explicitly doesn't work either `ring-offset-0px`.

CSS output from playground from reproduction:
```css
.ring-offset-0,
.ring-offset-0px,
.ring-offset-0rem{--un-ring-offset-width:0;}
```

### Reproduction

https://unocss.dev/play/?html=DwEwlgbgBAFgtAMwK4BsVQC4FMAeG4DGWAdtgE5QIq5QDOW1B%2BxA9sVlAIZoBcGZnYrTAYwbOABYADFKgAjAOZw5KTgQDWAPgBQUKKEiVqOI7kIt0IrAFtahEuSgArJLVEIAnvdJYKAd0RUdAVOAAc4AEYJHT09A2gCVVpaAF4AIkU4BQEPKDIwYiUJPIKlMiwQEsK4FgQEenwpNJjYvQB5OoaoKV1Y4AB6cAgWuKGoRM5k9Mzszlz86uKFsoqqpVr6rEbQnGbe1o7NjG6d-f1ByBH9MYmpjKVZ%2BdLJNbhyyuWazq24KXLrPatdrfY5-GxnAZDK7xcZJVL3LI5V5LZ7vV4bBqRHaAoGHLoRU6tSGXCE3OHTB5Iz4o6poz4Yn5SAB0ACYAKz-HEHEHdVkc8FEi7DXrE4WizRAA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDASSarID3fsMBVKtoAvqByNJScoADkFlRMkJCRgoLEoogy8pgW0GmyCoQqarDqABSS0jRZUABcoADaOtK1kUwWkIjhtJWRmhKg7tB8NZF0qJGggQC6XlM6kAAWfIgtAjVl0lEtbR3zi8uRQ6wkyNDqoIcofJjw6uCgCwBu4DRV58ismNDdOoFeTgYrdQa3mciH8lGKAEovI4fMZTIxLNY7JDocD-m4PKUgdJIEwPuAagBGAB0ACZUdImKh4EM5qZuJAqiAoJxifNgF91uMoToZoEIYIgA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4XyA

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by DSeeLP** [comment]
I'm using this rule as a workaround:
```ts
["ring-offset-0", {
    "--un-ring-offset-width": "0px"
}],
```

**Comment by Simon-He95** [comment]
> I'm using this rule as a workaround:
> 
> ```ts
> ["ring-offset-0", {
>     "--un-ring-offset-width": "0px"
> }],
> ```

this is intentional。
related：#2153

**Comment by henrikvilhelmberglund** [comment]
> > I'm using this rule as a workaround:
> > ```ts
> > ["ring-offset-0", {
> >     "--un-ring-offset-width": "0px"
> > }],
> > ```
> 
> this is intentional。 related：#2153

For `inset` maybe but `ring-offset-0` should give `0px` for Tailwind alignment. It also generally seems strange that setting the offset to 0 should remove the ring itself instead of just setting the offset to 0.

Also you can use `ring-offset-[0px]` if you want another workaround.

**Comment by henrikvilhelmberglund** [comment]
I don't believe this is completed, `ring-offset-0` and `decoration-offset-0` don't work correctly.

https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIAWBaAZgVzjigBcBTADxOxjIDtyAnKXOSqJMtmaugezpkoCIgC4SjBHSRgSYAdgAsABmVQARgHNs6xDADW6AHwAoKFFCRYiFBlbt7FGn2KyyAWyQ16TUpWq6CAZQAFb4SHK4AJ7eDGTMAO54hMSaCAAO2ACMisZm5hbg0PDIaOha2JqSUVCMYHTairX12oxkINgAbKp5BQUASi2iUAByfFB8uLicJPnmwAD0RaZ9lsU2ZRVVCDV1DUrN%2B20d3Wp72pPTZNTKvX1Qgw3Dj5oTUzNQynMWS5ArBWtrKUMFtqhN8CQ4PUyAc%2BBCoYJsEgXGAQODIdDsMcuj1-n0APLw6HDMZvK6zVa-CB4wpWEq2crabY1OEYxFNVkImHIqFozmY7GndFc7CXGbYW408yEtlkYYyrlkj5fSnLb6A%2BmbJlg-B0EDxRX6mB8SRyBRNI0mhBmuhIlFoy2m%2BS2wW477mAAiZGNToEJPGYuu6qpNI1GxB2p2UF1%2BsYhu9VptB0d1uddt5UBTSddaizacDNzufS9PtTfqgJcTzqV10%2BwbV8xDJkWyyAA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDASSarID3fsMBVKtoAvqByNJScoADkFlRMkJCRgoLEoogy8pgW0GmyCoQqarDqABSS0jo0WVAAXKAA2jrSdZFMFpCI4bRVkZoSoO7QfLWRdKiRoIEAul6g0zqQABZ8iK0CtWXSUa3tnYvLq5HDrCTI0Oqgxyh8mPDq4KBLAG7gNNWXyKyY0D06gV5OBjW9Ua3mciH8lGKAEoZqDASYzJZrHZobCAa53PBIKUQdJIEwvuBagBGAB0ACZYdImKh4MMFqZuJBqiAoJxSYtgD9NhMYTo5oEoYIgA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgzgLgTglgxhEAuaBXApgGhNAhgOzADMB7KAW2SNwBswscoDizyAJCcmq2%2BgXyA

**Comment by Simon-He95** [comment]
The corresponding display effect on tailwindcss
https://play.tailwindcss.com/pxoBNZhfsx

**Comment by henrikvilhelmberglund** [comment]
Apparently in Tailwind it's `underline-offset-4` instead of `decoration-offset-4`.
