### ISSUE TITLE
display-flex (or any other display-(.+)) not work

### ISSUE THREAD

**Issue by noy4** [unocss/unocss#3197]
### UnoCSS version

0.56.5

### Describe the bug

`display-flex` doesn't work anymore (due to https://github.com/unocss/unocss/commit/f406a0b1 ?). Is this expected?

### Reproduction

https://unocss.dev/play/?html=ATA8BMEsDdihnADgGwIYE8C0AzZBTADwD4AoEECGI1UAeimlPLAaICM7WzzLGBjTlW6DGJYQ2C5CTHqxr0hzXuxEyKrAQtEUtpIA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUkNikEA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgTgpgzgDg9gOygSwG4RALgGYEMA2UEANCAC5i5LZxgC2WehJ5l1tdAEmXfowUQC%2BQA

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
I think it's expected because it adds a test to void `display-a` tobe `display: a`

**Comment by noy4** [comment]
I was doing like `display="inline-flex"`, `display="inline-block"` with attributify sometime, but `inline-flex`, `inline-block` are the right ways from now on?

**Comment by Simon-He95** [comment]
is correct, I usually just write `flex, inline-flex` directly, `display` can still work for `'inherit',
  'initial',
  'revert',
  'revert-layer',
  'unset',`
