### ISSUE TITLE
vscode intellisense in ts files (or anywhere else)

### ISSUE THREAD

**Issue by silveltman** [unocss/unocss#3200]
### Clear and concise description of the problem

I define a lot of styles in TS file, to make shortcuts. These shortcuts consist out of already existing classes, like w-full, mt-10 etc.

The file where I create the shortcuts does not have intellisense enabled by the vscode extension.

### Suggested solution

Add 'file association' or 'content' (similar to tailwind) option to the config, where we can define where to look.

### Alternative

There might already be a solution, but I cannot find it. Why is think this is because I know there are features like 'configDeps' and 'configFile', but these are not findable when searching the docs

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Simon-He95** [comment]
> ### Clear and concise description of the problem
> 清晰简洁地描述问题
> I define a lot of styles in TS file, to make shortcuts. These shortcuts consist out of already existing classes, like w-full, mt-10 etc.我在 TS 文件中定义了很多样式，以制作快捷方式。这些快捷方式由已经存在的类组成，如 w-full、mt-10 等。
> 
> The file where I create the shortcuts does not have intellisense enabled by the vscode extension.我创建快捷方式的文件没有通过 vscode 扩展启用智能感知。
> 
> ### Suggested solution 建议的解决方案
> Add 'file association' or 'content' (similar to tailwind) option to the config, where we can define where to look.在配置中添加“文件关联”或“内容”（类似于顺风）选项，我们可以在其中定义查找位置。
> 
> ### Alternative 另类
> There might already be a solution, but I cannot find it. Why is think this is because I know there are features like 'configDeps' and 'configFile', but these are not findable when searching the docs可能已经有解决方案，但我找不到它。为什么认为这是因为我知道有“configDeps”和“configFile”等功能，但在搜索文档时找不到这些功能
> 
> ### Additional context 其他上下文
> _No response 无响应_
> 
> ### Validations 验证
> * [x]  Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).阅读贡献指南。
> * [x]  Read the `README.md` of using the package.阅读 `README.md` 使用包的内容。
> * [x]  Already used the [Interactive Docs](https://unocss.dev/interactive/).已经使用了交互式文档。
> * [x]  Check that there isn't already an issue that request the same feature to avoid creating a duplicate.检查是否还没有请求相同功能的问题，以避免创建重复项。

You can try it by adding `// @unocss-include` at the top of the ts file

**Comment by Simon-He95** [comment]
I think this issue could be close
