### ISSUE TITLE
多个 preset 都设置了 prefix 时， prefix 会被叠加

### ISSUE THREAD

**Issue by lin52025iq** [unocss/unocss#3201]
### UnoCSS version

v0.56.5

### Describe the bug

```js
import { defineConfig, presetAttributify, presetMini } from 'unocss'

export default defineConfig({
  presets: [
    presetAttributify({ prefix: 'un-', strict: true, prefixedOnly: true }),
    presetMini({ prefix: 'un-' }),
  ],
})
```

上述配置中，presetAttributify 和 presetMini 都设置了 prefix,  需要使用 'un-un-' 作为前缀才能让 presetAttributify 生效；而 presetMini 只需要使用 'un-' 就可以生效。

### Reproduction

https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCICuA7AtAFwFMAPfXAVmLnSh1zqNNwCdCQA%2BAVWwHsBhAMoDgAenAR2AKCA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCCMMUwARgK4zDoCeZF1tALLZgcAL5x0UCCDgByNlggBjKlTkAoDagAekWCgwBDNgBt4aTDnyFgRABQINccpRowqALjgBtZy9cBekZmdk4eR0DMHW8FLABaOTIqJmBlGG8mNlQ%2BSmjUZAB5LFNuTKhs8QBKEn8XfndhLGBI-mjYxUTq2pcAXVqxKo0gA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmAvkA

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
The prefixes have different meanings for each preset (please refer to the jsdoc). I'd say this is the expected behavior.
