### ISSUE TITLE
Expect official documentation to support multiple languages

### ISSUE THREAD

**Issue by xiaofei3062** [unocss/unocss#3202]
### Clear and concise description of the problem

Expect official documentation to support multiple languages

### Suggested solution

Expect official documentation to support multiple languages

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [ ] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by zyyv** [comment]
https://github.com/unocss/unocss/pull/3077#issuecomment-1704984842
