### ISSUE TITLE
设置透明黑色没有生效 bg-black-50

### ISSUE THREAD

**Issue by im-pan** [unocss/unocss#3208]
### UnoCSS version

0.53.5

### Describe the bug

bg-black-50 好像没有生效 透明度

### Reproduction

https://unocss.dev/interactive/?s=bg-black-50

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
https://unocss.dev/interactive/?s=bg-black:50
