### ISSUE TITLE
unocss中没有zoom 以及 border-image 属性

### ISSUE THREAD

**Issue by fslflame** [unocss/unocss#3212]
### UnoCSS version

0.56.1

### Describe the bug

unocss中没有zoom 以及 border-image 属性

### Reproduction

unocss中没有zoom 以及 border-image 属性

### System Info

unocss中没有zoom 以及 border-image 属性

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
tailwindcss is not provided either
