### ISSUE TITLE
Make `extendTheme` to accept a simple theme object rather than force a function

### ISSUE THREAD

**Issue by xsjcTony** [unocss/unocss#3214]
### Clear and concise description of the problem

Imagine this use case: I want to add a `color` called "test": [Playground](https://unocss.dev/play/?html=DwEwlgbgBA7gTgQwA5IKZwHwCgpVJKAF1QA9CBaYgZ0IwFUA7AewGEBlN4AenAm297YgA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAKq4IlAL5wsUCCDgByLpIDGdOsqRIMAD0ix02AIZcANvEw58REsFIAKZKjoALaDHU86ALkQqVGUAdyhTMDAMKGUA0IBaAEYABmSANxC4dyTUtPc5CwM4YBgMEDp49QxcUqg4ACsuOl4BSuranVRpITgDUtw0ABV3MownGBGQDABKV1Q4dWI6CEKAOgsIZwnR6aC4WhguKFxA%2BfnVi%2B2pnrPFjah-ObPUUua42jRO5%2Bk9n66ekQMGD%2BOAAbT2gPEkic0xu1FoQJYbE4PD4-BhPQAukhpLsgA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g)

However, due to `colors` overwrites the original `theme.colors`, hence other default color like `blue` is not usable anymore.

In the function you need to define like this, which is a bit inconveinent: [Playground](https://unocss.dev/play/?html=DwEwlgbgBA7gTgQwA5IKZwHwCgpVJKAF1QA9CBaAIwBsBXVDAVQDsB7AYQGVPgB6cCNj4DsQA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAKq4IlAL5wsUCCDgByLpIDGdOsqRIMAD0ix02AIZcANvEw58REsFIAKZKjoALaDHU86ALkQqVGUAdyhTMDAMKGUA0IBaAEYABmSANxC4dyTUtPc5CwM4YBgMEDp49QxcUqg4ACsuOl4BSuranVRpITgDUtw0ABV3MownGBGQDABKV1Q4dWI6CEKAOgsIZwnR6aC4WhguKFxA%2BfnVi%2B2pnrPFjah-ObPUC9WrjFW76Dob59LmuK0NCdZ7SPZgro9EQMGD%2BOAAbT20PEkic01%2ByOYrHY3Ba-DRPQAukhpLsgA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g) 
```js
  extendTheme(theme){
    return {
      ...theme,
      colors:{
        ...theme.colors,
        test: 'red'
      }
    }
  },
```
This is even worse if you are defining `animation`.
You have to use `...` for every single field, otherwise it's getting overridden, which is really annoying and inconvenient.
Example:
```js
extendTheme = theme => ({
  ...theme,
  colors: {
    ...theme.colors,
    border: 'hsl(var(--border))',},
  borderRadius: {
    ...theme.borderRadius,
    lg: 'var(--radius)',
  },
  animation: {
    ...theme.animation,
    keyframes: {
      ...theme.animation?.keyframes,
      'accordion-down': 'from{height:0}to{height:var(--radix-accordion-content-height);'
    },
    durations: {
      ...theme.animation?.durations,
      'accordion-down': '0.2s'
    },
    timingFns: {
      ...theme.animation?.timingFns,
      'accordion-down': 'ease-out'
    }
  }
})
```

### Suggested solution

Either let `extendTheme` be able to receive an theme object,
Or provide an `extend` field in `theme` object just like in Tailwind.
https://tailwindcss.com/docs/theme#extending-the-default-theme

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by zyyv** [comment]
You can use `theme` option to avoid this issue.
[Playground](https://unocss.dev/play/?html=DwEwlgbgBA7gTgQwA5IKZwHwCgpVJKAF1QA9CBaYgZ0IwFUA7AewGEBlN4AenAm13zRiZcgCMANgFdU9Zu049I2br2xA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAKq4IlAL5wsUCCDgByLpIDGdOsqRIMAD0ix02AIZcANvEw58REsFIAKZKjoALaDHU86ALkQqVGUAdyhTMDAMKGUA0IBaAEYABmSANxC4dyTUtPc5CwM4YBgMEDp49QxcUqg4ACsuOl4BSuranVRpITgYdzKMP1dUOHUIC2h-YZHe%2Bhg42jROkekqbqoRBhh-OABtIOpaLYkIJwBKHuEjxhY2Th4%2BfnOegF0kaTOkIA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g)

**Comment by zyyv** [comment]
`extendTheme` provide original theme to use, and it means full control your theme. 
If you don't like using structural syntax, you can use `mergeDeep` function optimize your use.

```ts
extendTheme(theme): {
  return mergeDeep(theme, {
    colors: {
      test: 'red',
    }
  })
}
```

**Comment by xsjcTony** [comment]
@zyyv Thanks. So am I correct that the `theme` option is the same as using `mergeDeep` with the default theme? or what's the behavior?

**Comment by Simon-He95** [comment]
> @zyyv Thanks. [@zyyv Thanks.] So am I correct that the `theme` option is the same as using `mergeDeep` with the default theme? [So am I correct that the theme option is the same as using mergeDeep with the default theme?] or what's the behavior? [or what's the behavior?]

It will be based on the base theme provided by unocss, and then merge your customized theme. Of course, if the name is the same, your customized one will overwrite the base.

**Comment by xsjcTony** [comment]
So it means e.g. in `animation`, if I want to keep the original default animations, I have to write `extendTheme` with `mergeDeep` myself right?

**Comment by Simon-He95** [comment]
You understood it correctly
