### ISSUE TITLE
[🐞color]: `hsl` and `rgb` is opinionated to the legacy comma-separated syntax

### ISSUE THREAD

**Issue by xsjcTony** [unocss/unocss#3218]
### UnoCSS version

latest

## This issue is pretty critical.

First please look at this playground: [Playground Link](https://unocss.dev/play/?html=DwEwlgbgBAFgtAZgAxIA4A8oHc4GcDGATgKbEB2UARgOZ6oCG%2BxAfAFBRQDKACgIIDCAUTidBfAEq8AKoIAi7KMEqE2HGLgA29ABQR6hbXDqNiASgA0eg0YCuZODTgB7BvjAAXAJ6nTCpSoVtADkAeSkoAHUQ8QBpAEkggHFfYAB6cAg2UEhYRBQMbDwiUgpHfCcAWwr6VSh%2BEIBZBt4RMV5JGXkOf1r1LV19QzhyqvoLKyG7B1oXRg9vX27lWu0o2ITk1jSM5iA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAKq4IlAL5wsUCCDgByLpIDGdOsqRIMAD0ix02AIZcANvEw58REsFIAKZMNoMYdAFxwA2lTdRGAkIJwBKIVRqd0YWNk4ePn5wqgBdSJgACwwQDB9XKPUIC2hvRACoujBTdTzyqIa4ABEAUQAxJjEAGQAVH2VMugsnADdTKCcAWkmqmowwsJ1GuGlIhqKQEFN8iobWju6%2BlUHhsYnpja2FpcbpCrvUO%2BkwpCA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmjpqRVhwpv42NuiCuepgAEwAbAti0QAcAMximwCkYO4A7GLru5lgU%2BU4OLQay6uRNFs7uzRHJ2cDQA&options=N4IgTgpgzgDg9gOygSwG4RALgGYEMA2UEANCAC5i5LZxgC2AEmXflnoSeZdbXQMIBXKGTj8AymLYEiAXyA)

Nowadays, `hsl()` and `rgb()` (as well as `hsla()` and `rgba()`) [or any other more?] supports both comma-separated syntax and space-separated syntax. e.g.
```css
color: hsl(262.1 83.3% 57.8% / 0.5);
color: hsl(262.1, 83.3%, 57.8%, 0.5);

color: rgb(255 255 255 / 0.5);
color: rgb(255, 255, 255, 0.5);
```
Both of them are valid
https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/hsl#legacy_syntax_hsla
https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/rgb#legacy_syntax_rgba

Although the comma-separated syntax has a wider browser support range, it's being marked as legacy already. And the support for space-separated syntax is good enough: https://caniuse.com/?search=hsl%20space

## My use case:

Space-separated syntax is now the recommended way by MDN, hence of course, the modern ui library I'm using `shadcn/ui`'s theme system is using the space-separated syntax. https://ui.shadcn.com/themes (Just simply click the `Copy code` button)

But it result in the first-case in the [Playground Link](https://unocss.dev/play/?html=DwEwlgbgBAFgtAZgAxIA4A8oHc4GcDGATgKbEB2UARgOZ6oCG%2BxAfAFBRQDKACgIIDCAUTidBfAEq8AKoIAi7KMEqE2HGLgA29ABQR6hbXDqNiASgA0eg0YCuZODTgB7BvjAAXAJ6nTCpSoVtADkAeSkoAHUQ8QBpAEkggHFfYAB6cAg2UEhYRBQMbDwiUgpHfCcAWwr6VSh%2BEIBZBt4RMV5JGXkOf1r1LV19QzhyqvoLKyG7B1oXRg9vX27lWu0o2ITk1jSM5iA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAKq4IlAL5wsUCCDgByLpIDGdOsqRIMAD0ix02AIZcANvEw58REsFIAKZMNoMYdAFxwA2lTdRGAkIJwBKIVRqd0YWNk4ePn5wqgBdSJgACwwQDB9XKPUIC2hvRACoujBTdTzyqIa4ABEAUQAxJjEAGQAVH2VMugsnADdTKCcAWkmqmowwsJ1GuGlIhqKQEFN8iobWju6%2BlUHhsYnpja2FpcbpCrvUO%2BkwpCA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmjpqRVhwpv42NuiCuepgAEwAbAti0QAcAMximwCkYO4A7GLru5lgU%2BU4OLQay6uRNFs7uzRHJ2cDQA&options=N4IgTgpgzgDg9gOygSwG4RALgGYEMA2UEANCAC5i5LZxgC2AEmXflnoSeZdbXQMIBXKGTj8AymLYEiAXyA) above, which result in `hsla(262.1 83.3% 57.8%, 1)` and definitely it's not going to work.

I've had a look into the source code, currently UnoCSS defaults them to comma-separated syntax without any condition:
https://github.com/unocss/unocss/blob/78d1d03b461288b472b8c71e0b23d8e4f07c8245/packages/rule-utils/src/colors.ts#L62-L63

I wanted to give a PR at first but turns out this is a decision-making issue and may impact a lot of things.

## Suggested Solution
1. ✨Tailwind now defaults `rgb()` and `hsl()` to space-separated syntax, where `rgba()` and `hsla()` remain as comma-separated syntax. This is aligned with what recommended by MDN, as e.g. The legacy `hsla()` syntax is an alias for `hsl()`, so this could be a valid solution, and I personally suggested that.
2. 👍Due to the fact they are alias to each other (although `rgba()` and `hsla()` is marked legacy, they can be used fully interchangeably with their modern version `rgb()` and `hsl()`, which means all 4 cases will work), we may provide an global option to let user choose which syntax they prefer in the project. This will be unopinionated and it does make sense to align the behaviour in a single project.
3. ❌Even better, maybe there's a chance we can dynamically look into the color format and apply proper format, but I don't think it's achievable because if `css variable` is used in the theme, we just simply get something like `{ type: 'hsl', components: [ 'var(--primary)' ], alpha: undefined }` which does not have any useful information to this issue🤣

## Additional
I also suggest to replace the built-in UnoCSS color system with space-separated, since MDN has marked comma-separated syntax as legacy.

Please carefully consider about this, Cheers💚

## Workaround
Currently I have to change all my copied themes from `shadcn/ui` from `--primary: 262.1 83.3% 57.8%;` into `--primary: 262.1, 83.3%, 57.8%;` due to this issue. What a nightmare🤣. I could switch back to Tailwind but I love Uno!

### Reproduction

[Playground Link](https://unocss.dev/play/?html=DwEwlgbgBAFgtAZgAxIA4A8oHc4GcDGATgKbEB2UARgOZ6oCG%2BxAfAFBRQDKACgIIDCAUTidBfAEq8AKoIAi7KMEqE2HGLgA29ABQR6hbXDqNiASgA0eg0YCuZODTgB7BvjAAXAJ6nTCpSoVtADkAeSkoAHUQ8QBpAEkggHFfYAB6cAg2UEhYRBQMbDwiUgpHfCcAWwr6VSh%2BEIBZBt4RMV5JGXkOf1r1LV19QzhyqvoLKyG7B1oXRg9vX27lWu0o2ITk1jSM5iA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAKq4IlAL5wsUCCDgByLpIDGdOsqRIMAD0ix02AIZcANvEw58REsFIAKZMNoMYdAFxwA2lTdRGAkIJwBKIVRqd0YWNk4ePn5wqgBdSJgACwwQDB9XKPUIC2hvRACoujBTdTzyqIa4ABEAUQAxJjEAGQAVH2VMugsnADdTKCcAWkmqmowwsJ1GuGlIhqKQEFN8iobWju6%2BlUHhsYnpja2FpcbpCrvUO%2BkwpCA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmjpqRVhwpv42NuiCuepgAEwAbAti0QAcAMximwCkYO4A7GLru5lgU%2BU4OLQay6uRNFs7uzRHJ2cDQA&options=N4IgTgpgzgDg9gOygSwG4RALgGYEMA2UEANCAC5i5LZxgC2AEmXflnoSeZdbXQMIBXKGTj8AymLYEiAXyA)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
Since you are using css variables, I didn’t think of any way to judge the content inside to determine whether it is used or / for the final alpha. Maybe you need to judge by adding a parameter, or there are other tricks.

**Comment by xsjcTony** [comment]
> Since you are using css variables, I didn’t think of any way to judge the content inside to determine whether it is used or / for the final alpha. Maybe you need to judge by adding a parameter, or there are other tricks.

Yeah, I don't think it's achievable, since we have no idea what's the value at runtime. So I'd suggest to go with either of my purposed solution.

> ✨Tailwind now defaults rgb() and hsl() to space-separated syntax, where rgba() and hsla() remain as comma-separated syntax. This is aligned with what recommended by MDN, as e.g. The legacy hsla() syntax is an alias for hsl(), so this could be a valid solution, and I personally suggested that.

Align with Tailwind is a really good idea and their behaviour totally makes sense since it's aligned with what MDN is recommending. And also, this makes UnoCSS compatible with Tailwind's ecosystem (e.g. `shadcn/ui`), as you know, ecosystem is the key to success for an open-source project.

> 👍Due to the fact they are alias to each other (although rgba() and hsla() is marked legacy, they can be used fully interchangeably with their modern version rgb() and hsl(), which means all 4 cases will work), we may provide an global option to let user choose which syntax they prefer in the project. This will be unopinionated and it does make sense to align the behaviour in a single project.

This option is also valid, which will make UnoCSS unopinionated on this, or at least let user config what they want.

**Comment by antfu** [comment]
Thanks for the detailed information! I think, in general, aligning with Tailwind makes sense.
