### ISSUE TITLE
[🐞bg]: Arbitrary `bg-[url(base64)]` is not working

### ISSUE THREAD

**Issue by xsjcTony** [unocss/unocss#3222]
### UnoCSS version

latest

### Describe the bug

The arbitrary base64 background image syntax is not working.
However, setting it in `shortcuts` works.

In Tailwind, this is working. I'm not sure whether I used the wrong syntax of arbitrary value in uno, but I don't think so, since normal URL arbitrary value is working.

Tailwind playground for this (working): [Tailwind Playground Link](https://play.tailwindcss.com/RCW8yY4cCI)

### Reproduction

[Playground Link](https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIAWBaJMBOApoQHZQDuuBxZARgObb34JgkCe6AfMAPTgQuAKFCRYiFBhx4ipClVl1GAbQCu%2BOAAoQCAC4IAXGAC2CeoV4AHEvQDctZIQBsAFgA0YAGoAhAPIAlcgAGAGkAcXoAewBBWOiAOQBlAFVMAFFk%2BjiAETjY8m9ogFk4gGE4ABlfRKC8tLhvIs8MnIAOXggALyDWiAAVIIBOftaAai6kAHZVAA8ACQBGJz7CPOiADX9EvrgSgEVfWgBNAC0suLhyRIAxOE643xmcpD3vOESkXzDyONVrgCl-GlrslfABJIKeADWowAzPEKmA0mD-GEFt5WuVokdoi8AEzRMFpXQubKDQgABV0EAArOtLLxjGcjv88QAzXwAkJpNlgkhQzwAdSOeLMcGMe2uUJM-j6nkmRVocCO7E8AEdspM5ut2JgQkhEqoKesFniioRsph-HMKrowhBUaMKaNvLwap5VC5fEhyP5BrpjBByPEKbqQKVsrRPAh2P8wggQEheIKwMlBTAAFalCClEj4VR9bzxOaJQb0YzrPGeTqeWhQyYnCDeBb0WgLTBQwXXMJwUbRXgkUa8a6RcgwXywlzJXjrCAhNUnXhsuZHUZOCD0fxs5KDPHrfC%2BbzJWhhYjZNl7YwZwUZkD4EKjNn4GBOa4gML%2BQh7TBsm40-4Onigy%2BHiez4Gy8TkO2BbkHA9BIOw6wVJEQSqKMNKJJErR4kg9AQJMuhINcJz%2BHiJAzN4ThwOsYBqqoczgdkrQkGypyDIkhADIiqgQJhnj4DMYRHEslilPE-gnPOQaCkgJA0r4czsJYFLeGkFSdJEmBFKUCD%2BAgCBBDAnErmqhCTOsvD0Gy-xpMSITXLQ-yWIKkTxGqvijAgiQLDABbsFCYQUpYIQ0vGLitMYTgVPChBsn0%2BBBAssLzkc3h7Kou6DGAFILJEey8JMyRXP4oxgLCnRqvmyTGH0rQuGqxiYJ0FSWDM7AZpMlj4IMUL0JMFQhBAaoIOsMwnMYIDWGuWFIHMaqJGqkQZuwQR4vQySwskrRqoMFIkJYYDgAgFRQkgQTGLQRRHJ0oxqniqieOsSCRGlrS0Nu-jJBURwzP49AnJ4RylHMRQQIM1xetEkxqjMfR4iGQUQGE%2BVIH02RzHi7CdCQISYJMaQEjAaTgTA8RIAgYKuQsYCdJ0jlgAgRxOLCMwuHsGbJG%2B3iJBA2TZqo9BBaoNIzNkHBBBmnRpIQqjJHstAwDlCBhH0gyeIMqFgDMNh9P433xMiYInE47CcgscytAGkz4BmeL-DMYCxUgnjsDS5VhC7sJmDSqhGkgICqKxvidD9FT%2BNr9AhGZJCYDMsKeNEao0i4ljGJ0vDZCEgy8HsXvZAgxh4kcuiwpg8TrN4LhzLLrSTBmITxCAvClCEJwkJMkx7CAcl7FC6wUmy81Qh2kyYGEvjrBXoyTBAQwhLQ3i0GqIAQIJw21GqbIhLwehgvgFR4oK6wgNE9DrNE-wuLCgq6OQFgU5ECAwOshCdIQgVFHAmDZApkaJMuJARpIAPnsOmtU8QfnICcVQr8QBjkiIKToMwaTWF8CQMIRRkggGrmAI4kwv4gHYIglMcwSCqBgBUE4ewZhHESLoIo-xaC6BgOwbBCA9jrnobQQgtQYCRkEqMPYaIXDRAqIMFwMx8DsBcEBSYMxLDsEGKUSwbIFi%2BEiGNSYLggj0DmOee8ox6CERWjMBAtByD-GMGyIxpRCBgDAJMQYlEEAZiCIkf4hAKi0BAJMNY9Rrh9ChIaS8pRSgAEoAC63A%2BACGEKIaA8BkBoCwAoGg8gZBpIYNgdQWgdD6CMKYcwVgbD2EcK4DwPgAjBHCFEPISRUgZHONEXIeQCjFDKJUaotQ4j1EaM0ZIbQOjdF6AMYYtVxidCmLMRYyxVh5E2NsXY0QDjHDOHkS4Nw7gPCeLEbILw3gfC%2BD8WIfxATAlBBCaEcIERIhRGiDEWIcT4kJMSUk5IqS0npIyZkrIORch5HyAUwpRT0HFJKaUxhZTykVMqVUGotQ6j1AaI0JozQWitDaO0DowhOhdG6SEnpvS%2Bn9IGYMoZMDhkjNGWM8ZEzJlTOmLMOY8wFiLCWMsFYqw1jrA2JsLY2wdi7D2PsA4hwjjHBOKcM45wLiXCuNcG4tw7j3AeI8J4zwXivDeO8D4nwvjfB%2BL8P4-wAVIsBUC4FILQT6LBeCiFkKoXQphbCuF8KEWIqRcilFqK0XooxZirETjsU4kEbivFIj8UEsJJwolxKSTVNJWS8lFLKVUupTS2ldL6UMsZI4plzKWWsrZXQ9lHLOVcu5Ty3lfJ9H8oFYKoUEDhUitFeIsV4qJWSmqVK6VMrZVyvlQqxVSrlUqrLGqdUGpNRam1DqXUep9QGkNEaY0JpTScDNOaC0lorTWhtLaO09oHSOidM6F0ro3Tug9J6L09hvQ%2Bl9H6f0AZAxBmDCGvgoYwzhgjSwSMUZowxljHGeMCbRCJiTMmD94jU1pvTRmzNWbs05iAbmvN%2BaC0sMLUW4tJbS1lvLRWCxlaq3VprCOut9aG2Nqba45tLbGGtrbe2js2TO1du7T23tfYUn9oHI4wdQ7hxsFHSYMc44JyTinNOGcs45zzgXIuJcy4VyrjXOuDcm4tzbh3LuPc%2B4DyHiPMeE8p4zzngvJeK814GUTlvHeug94HyPifM%2BF8r43zvjvSmT8X5vw-l-H%2BejaD-1IUAkBYDsKQOgbA%2BBiDkGoPQZg7BqhcH4IpUQzoJCyEUKoTQuhDCmEsLYRwiAXCeHgf4TioRCwRFiIkVImRgw5EKKUSotRGiThaJ0Xop8D4jEISCKY8xljrG6FsfYxxzjXHuM8d43xdQ4ABKCaoEJ4Ton8EgFwIAA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCqVbQF9QcmpU6gA5AFcqTSJDuDBxUYhnzMD6B9ZBUIVNVh1AApJaT0oQ0gALlAAbR1Y-UMTSkiASh0AXW1pSAALPkQmBwFktOlpFLtsdWR1GkwEAE87TXtm5BSHGmhI1ExETESuTHVwYG54dQBubEwDADYAFk1YADUAIQB5ACUAdwAGAGkAcXVKAEFH%2B4A5AGUjUoBRI3UngBEno9Tvt7gBZJ5KaAAGUOr3OgM%2B0H2oN233%2BAA5gAA3ABe53RWIAKucAJxE9EAalxkAA7A4iAAJACM60J4EB9wAGsdXoToOCAIqHbAATQAWr8ntBTq8AGLQHFPQ5Ef6QAX7aCvSCHa6nJ4OWUAKWOn1lRkOAElzrsANYUgDMzyhsE%2BFuO1yZ%2B3RkPuIvuaoATPcLZ9EJs-iTwAAFRBYgCsnO4wE4EpFhoDckORsunzkFvgNt2AHURQGZtBOALZTauMdCbsaaDcCLOrsAI5-GkMzmdUqXSCvBxRzlMgOg8B-UrHBlQxDXLHuilRin7YBw3YOTaHSCnY4kxCcLGnZ5R3uoJR-bC7TCdQ3XTCoSDAIuwIxFpgAKyUWKU8BoDkJfZngZV4SXUThOQDXYcV2bAbRpMUsX2Jl1GwJlShtItZWuaAKXuYB4ApYBZUoU4mEOe1NiMYBOSxS42zFYA5AZEUKXWLF1GOOQjBJANORoQ59iMbBrnACc5AFTgPyLD9UBoS4KSsJh1llVBrmOcABVKOQ5TjQ0FwDElDgDAUaDkZ5TnQgDTmgdRIE6TkoUoc4HApONXkodEA0gdQsRpARZTFY4A3gIh9nWaBOVgNsHAZMy-nRNRxRJV5wGJZ0HCxDzdhoIhrhFFluCUZ5jjFeijyLSB4DjQ4GU6bgo32T4oRxShSlBJRMGOTBMHOJg0pYttwBpTlgHUORDU%2BUNLllbBDW4ItKGeNtDgpTBXiZKpCU6G1rijbhLjje9NnRTh1ihR15EJGhziZe16JFfYBQcXiSVgKMmUoAVgBpIwZWOClYHtHE23-IxOEJdFNjbThShxKFuCIToPxpPQSRtdQaShS4sTbTBOSIMVOFQBY2M8yAGTbV420oD9OnOAN1CMe0jHRNsSSjeBuFgdBMChG1IHOThsFBEUcQpNsAwcXZOUgSgnvRbBuOOIwoRFIhjnUMVdhFJQGVBLESVlLd7hpNsiEJAMT32rFrm%2ByBCT%2BBkA06HF4EuUoaU%2BIMmE%2BMymGeLALSWplYBxHE5tgTARXWe0iE2AUPyMVT9leLE-m-Bx1H2hw4yIP54Hpj8cU%2BcAHCMAVsCYD7MGuQkSV2EkXNgIhFkJY41eeV0LTFdZOizJkGXRA8aRoD8A0NIhYHkSBdk6ONgeuOf7RmOMHCHSBUAcOQRUOHF1ahY5W-US5hvgUoiHtXZ7jbONNm4TgcWAP5LhJYABRXv5ME4AMRUQe1SjPE5PsTYDJy7ohpB%2BS4zxUDACUJcMU8AaQ0gFKgaqAobScijHIKmNoMI0lKNcQ4nJgEUhpFiUklxsD7GwG2VAWI8p43hG2OQlxgDjAtDQKEAYiyclQPcdQnJ7iGk2PaIsiBThzEwMHTATBOTgBxOAPaoJoClD%2BLVS8rxmLwHxpAbhAoI6QwDOpU4YoHAKNQGRSgRYcREDjAsQ48BrigiMKgMBsARQ0lUagToNiXwMngA4JgUIxQCiICKV4iBQSGmwJUTobjMACnYlE7A4B4RMEvHlCkAoPSbHuFCEkmwiA0E6JsQyNIiDcE6CSJQ3A5BMkOJQQmNJNjnHUAyP4VgFLqAEPTIgOBTiGk4HIHpShwCwFgDSEk4VMAfnOK8Q04AoTYFQDSDkiJZSEhtIOSSSglC5AKD0CQoBoA3nADQZIjhECwDgNcqAdhQBmAKIUQQZh8hAA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmAvkA)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
You can try to use unpreset/unocss-preset-useful patch this feature.
https://github.com/unpreset/unocss-preset-useful/blob/main/test/extractor.test.ts

**Comment by xsjcTony** [comment]
Thanks for the suggestion. Actually as long as it works in `shortcuts` it should be fine, as it's really ugly to inline the base64 img URL into classname straight away honestly.
But wondering why `shortcuts` works but inline one doesn't🤔

**Comment by zyyv** [comment]
All work fine.
[PLayground](https://unocss.dev/play/?html=DwEwlgbgBA7gTgQwA5IKZwHwCgpVJKAYwBsEBnMgXgCIYBaAVgAYoALRlgIwHM6BtAK5xiAChAIALggBcYALYJuqAPRIAdtwDcncqgBsAFgA0YAGoAhAPIAlGEwDSAcW4B7AIIe3AOQDKAVVYAUT9uTwARTw8YczcAWU8AYWIAGUsfJkjA4nNY02DwgA5lCAAvJgKIABUmAE4qgoBqUrIAdgEADwAJAEY9StRItwANax9K4niARUtOAE0ALVDPYhgfADFiEs9LdvCySfNiHzJLRxhPATWAKWtAtb9LAEkmUwBrBoBmL2SwQMfrRzdcwFJJuWZufYAJjcj0CEgMYRqqAAChIIAwhkhlHJFrMrpCAGaWa72QIEx5qV6mADqs0himIckma1e8mslVMLVinGIswAnqYAI5hFqdIZ81j2Mg%2BATIobdSGxVBhVjWTrJCSOCAAhrIhrmZTpUwCAyWMgwaw1CRyCAwLzIiUgBJhTimBB8q6OBAgMjKalgPzUwgAKwSEASajgAkq5i8nR8NW4ciGkNMJVMnFeLXmEHM3W4nG6rFe1LWjmIDTcyjUDWUaxcMEIlg%2BBj8yiGEHsgvmygJnVmDT0EG41gJfhqkKGcEs5j8nEcqGVBMmcmD1ODIDg9gaBLghD0axAjmsqEmrAJ6wYV21kJqlkhkzgBK8MCL0ZgxG4ZD5Q2SLiYAgNAwPguAUkJkNwEAtBIZBrPM1iQmo7TmHoxBDGAgoCJ0T5hAUagEgsNQ%2BKg1Q-AIEAgaYcDtI4sy9EgCReNY8xdra1JkGoDCWJ0fJIMi5iBMkJQuKwsQJAg1gIAgTCECR-aCqgLRDMo3AElcgRwvYaycFcSDUi4XiCpYDQID43SENGfKvI4yJIPYDBegYBRyHoyRfKgBKVHATDdB8XazOYkwCBONRgMi3QuJMygtH4qzWA0YAfCUgpRn4ciVAUBiCnIrAlMkSDtHywYtEgcA1K83AtMk9gQIKCBDO08xyCA6iDqBZCdIKPiCi4wZ8kwkLcH4Hx%2BAUgo1MiahIGA4AIMkrxkEwcicLEswlA0gqQgIphDGQLiBQUnBjtYfjJLM7TWNw8ymLMCSdLEEA1GsppuC0grtJUkL2rZECOFFZCVGEnSQnyJRqPYrAtIE0KEIET6EF4ZAII8BndGAJQlDpYAILMegfO0BiTMGfiHuYPgQGEYYCNwtkCAw7RhGo-XBiUgSoAIfiTJwhDhQgjiVDUpg1ABYDtBolTWGdXh-I88x6HyxLdJ0BTWi0cDBpCVztGAHlkKYfIMEljj6x8igMAIspkCAAgEZYJTnck1hi9w9iKWorDtB8phuIKDAGEgcglMoYT2DUyiTKbYQIHIkKzBIHysF4QzmAYnQcwULTBvYXggMoCT2PMagtC0kwgJxkyvEMyIEl1rzFi0rCOJYQzJw0LQQLU9icOYnCCiAEA0XVGSCgS9jKJIjxwMkkLUkMIBuNwQxuFcBgfNSEgwCoyMuAghBDKgJSoDZsTEKwYTcS6Ph9mo9VkNPkyYxlkLHjA8wCAfICNi41IlO0DDqJYNQjhYh%2BBAGnMAswWinxAHyH%2B-pOhqAEIQZI8xJjtFmD4CQsQricAkIQPkYCECTCHFgzgqAMiEBdDRBokxAQGDcMkGoBh2hwD5AYW8LR2hID5DUBISACTdEsC4RqLQDBMG4J0MIu5tzcBgv1doCBOAwCuHIAksiEioDAGAFoNQUIIGDEwHwVxUDJE4CAFogwshrEqK8GUK4EgJAAJQAF1qAYGAMocAEBsC4GAJwOAUBlA%2BLwF4ogpAKA0HoMwNgHAoA6DIKgR4chuDUECdgDxXjsBAA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpwxQCGuAzltCBlACLBQYDGMwANwwNKqGvSYs2ANVpRg9GAHEoEAK5hKAXzhZVIOAHI1uCDwYNDSUJFiI4YbgwwwAqs6xqANnB16IBsam5gwAtI7CLqFqHt5WSBgAHrbwmFi03qnYeITEZAAUyKgMABbQMDxqMAwAXIhUqADudGBgbHWGjaEMPNwYuHAl3b0Y-bo8E4aiqHAARrTOAJIgpB2zpKEA2mpQXvlotDC0NaC0pBgA9GC4pADc884AbAAs5MDSAEIA8gBKjQAMAGklKQIABBCFggByAGVXCUAKKuUiQ9iQiGND5ggCykIIXgAMl8Yf90QivB9sdIkaiABwXAQAL3%2BtIEABV-gBOdm0gDUTIYAHY1IkABIARkebIw6LBAA0fjC2V5cQBFL6zACaAC0UZCvI0YQAxLyMyFfRKohiqj5eGEML5KRqQtRGgBSPwRRtcX0W-2kAGteQBmKEE4AIxY-JTij60-FgzVg60AJjBiwRMGe7E5GAACjABABWOVgC4gXWat0prBfd2AhFYRa4APSADqmpTZy8IFVRoDoB%2BbOkguxsy8moAntIAI7sQWiuWTkqAhgwtR5uXilPYjDsEo-UUE5QCaO8vO8j4XEnSNTPL4MRo-TkwEACRpQvPLtAEdizWSTm6Si0GgDAXG2wCuG2PAAFYEAIBC4FAahsh8UKijCnKkCAcoptIjLSLMAaCtqAgfOKpCzOKJQBm2RpKF4vJghcuC8hcRoQI0PBfMGzyuBccoCICM7ahcWCipqvKPAIpA-FgricimcpQF8HyuLMSijOwWCqiAMFtjBaBQICvJ6DwjxGmgSg-BgqolFgxpFm6p4ppyXwpqqUBYFCjTUShjReKQDCTnKBIQP8ai8kWMIQLSKYMKQAiCtURraj8Ka4IkHyPF4crADOaiil57C0iQOqcjCGAcuGagCDF0hQIkSiapKYAEFCPzasJ75tgwuBFl8oqTmAeYfAiBKMhAJTYgQtA-LQtD-DwVUSTOGCCnKFykFgboIpmgJGrMbpgG2EBQjOXy8rQMLipUbKTgGSh5mAgJFsBzy0iAjwEqG2BslA-zisGwmah8qpqIpnLAHm4oQKqFyCq4ho-LywDBoyM7Ia4IBsrSzwziAJSMgSYCJJOMGCo4nIBqQgoEoCAgzrQcqJNqIBoNcUmxQwoozjCM4QDBk7-CmpCuMGri0jOnJ5rgYDAGgCgEgGDD-CAszYpqjK8jOKZqNIcoMBAYO0rM8k-K4BKaokPykNq0iagQorYgInJGveYKCjOiRsimn7PQISjwwwbLsKKKaToyuCAiUgoImmPAIl5PBQgwtCLGd4rAIyjJHQomqPMGiTPKqMGuJZHwwgI7DwWopDPWoRaJOwuDCzBjIIhgaiuKqsw8DDtBKGynLSJyEXAIkNxsj8VtQpGizao8k51uKoq0q%2BgpQDBKZuokwDYAw0iTkW6NKEfwZnEWagbgwaBqFgmpfIy1sEj8k%2BkIC624CUiTBtIYIziLM8MAIBGQXHYICTkFxVQX3YLQEAKZNQwGDCUKEcoPjPFFN3WkgoYKAihGgC4BBATalwIKQUqo0D9VVAGOUeYsB8wDDRQUJQlBfDlOg3kgoBBckBLMD4swZxoAEE1JmpIZxYEBBcQ4iwoAEhTG2OUaAwSkDlGCN0zxgxthgI0S46cIC0B4HKDAjIMBPWxF4Eo7BBp-hhOJXAzMGDyNVLnXGKZrKNG1GoExaAuIQDbIyRIRZrhfFwEobErg0BYOAJqQUli0CTgCRBUUuA1A8AJNqVUiRNQwhgNiN0swKiTiibQVU0k8mzAwKSHgf4mq8lVDGZ4YICScmeIkKAk5niuUFMkScnICBgCwOKL4EBWaCmeP8UgoptLGV5KQaowtEi0FmI0N0IAsDzIIBgYAwBBScmyrQGC-wYRugwASWYaBBSynJEaNkAZ1y6QIAQAAlAAXSsKgLQ0wIjOGqHUTYDQHBOBcO4bA3hCiAtQMAHgxBaj1BmAiuAPRaBeAwHUcUAA6FM0xEVwB4FQjoJQYAwDALUC4FxhAgAxaUC4UxIW%2BBxb4Z50xXnTHEIwZgUBWBQDhZsdlkguVsE4NwPgghhD5GZdQOgHKpBQFkPIRQKh1BgAlaypAWhnlICAA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwBpxp5k0BhAVzjCVQoGVHNs8iTZEVUAJMVDla4CAXyA)

**Comment by xsjcTony** [comment]
Yeah, it works with the preset you suggested. I want to know what's happening under the hood with the `presetUno` only, that `shortcuts` works but inline doesn't. Aren't they using the same extractor?

**Comment by zyyv** [comment]
> Yeah, it works with the preset you suggested. I want to know what's happening under the hood with the `presetUno` only, that `shortcuts` works but inline doesn't. Aren't they using the same extractor?

In the `shortcut`, it means that the utility already exists and proceeds to the next round of rules and variant parse.

If you use `inline`, uno will extract the utility in the template, but now uno's extractor does not support base64 extraction, so inline does not support base64 utility.

**Comment by xsjcTony** [comment]
Oh. So `extractors` proceed first and then `rules`. Makes sense, but it's a little bit weird that in the same preset (`presetUno` in the context) that `extractors` are not extracting what `rules` support🤣. No idea why Anthony rejected it as it's just a small change to the regex.

Thanks for the explanation!
