### ISSUE TITLE
TransformerVariantGroup conflicts with unplugin-vue-i18n and causes vite build to fail when sourcemaps: true on mac/linux

### ISSUE THREAD

**Issue by stephenhebert** [unocss/unocss#3224]
### UnoCSS version

0.56.5

### Describe the bug

Build fails with error "Error: Multiple conflicting contents for sourcemap source" when:
- a single VueSFC file contains:
  - transformerVariantGroup (eg, sm:(p-4 m-auto))
  - VueI18n <i18n> block
- platform is MacOS or Linux (seems to work fine on Windows)

### Reproduction

https://github.com/stephenhebert/vue-i18n-unocss-issue-reproduction

### System Info

MacOS 13.4.1
Node: 20
Npm: 10.2

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by stephenhebert** [comment]
Same issue reported also to vite-plugin-vue-i18n: https://github.com/intlify/bundle-tools/issues/107

**Comment by flyingalex** [comment]
I found this error will be gone if removing `pre` in `createTransformerPlugins` method

https://github.com/unocss/unocss/blob/5d0a295860edc6c905af831b29ef9050f73086ff/packages/vite/src/transformers.ts#L6

This issue also exists in other project which is using windcss: https://github.com/nuxt/nuxt/issues/14981

So seems its unocss side issue

maybe @antfu can provide some ideas? I am happy to fix it If I can, thanks

**Comment by stephenhebert** [comment]
Confirming that this is still an issue
