### ISSUE TITLE
is:issue is:open examples 中的 vue-cli4 vue-cli5 都不能热更新，必须刷新浏览器才能有效果

### ISSUE THREAD

**Issue by tong822218** [unocss/unocss#3225]
### UnoCSS version

0.56.5

### Describe the bug

examples 中的 vue-cli4 vue-cli5 都不能热更新，必须刷新浏览器才能有效果

### Reproduction

[is:issue is:open examples 中的 vue-cli4 vue-cli5 都不能热更新，必须刷新浏览器才能有效果](https://github.com/unocss/unocss/examples)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
duplicate：#2144
