### ISSUE TITLE
提供一个css转unocss的功能

### ISSUE THREAD

**Issue by aofong19871029** [unocss/unocss#3227]
### Clear and concise description of the problem

unocss的语言，关键词不熟悉，希望在uno官网上提供一个功能
先设置uno config
然后我输入 原生css语法
uno 告诉我对应的unocss 应该怎么写

### Suggested solution

可以引入gpt或其他ai 辅助实现

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by aofong19871029** [comment]
比如我输入 css
background: linear-gradient(-90deg, rgb(245, 247, 250) 100%, rgb(255, 255, 255) 100%, rgb(245, 247, 250) 0%);
告诉我对应的unno是什么

**Comment by aofong19871029** [comment]
这样做也有助于unocss的推广

**Comment by Simon-He95** [comment]
> 比如我输入 css background: linear-gradient(-90deg, rgb(245, 247, 250) 100%, rgb(255, 255, 255) 100%, rgb(245, 247, 250) 0%); 告诉我对应的unno是什么

I think thi lib can help you. https://github.com/Simon-He95/transformToUnocss

**Comment by aofong19871029** [comment]
I tried below libs
 https://github.com/Simon-He95/transformToUnocss
 https://github.com/Simon-He95/tounocss
 https://github.com/Simon-He95/transform-to-unocss-core


these libs can help to transform general css, seems not work for complex css like 
background: linear-gradient(-90deg, rgb(245, 247, 250) 100%, rgb(255, 255, 255) 100%, rgb(245, 247, 250) 0%);

**Comment by Simon-He95** [comment]
> I tried below libs https://github.com/Simon-He95/transformToUnocss https://github.com/Simon-He95/tounocss https://github.com/Simon-He95/transform-to-unocss-core
> 
> these libs can help to transform general css, seems not work for complex css like background: linear-gradient(-90deg, rgb(245, 247, 250) 100%, rgb(255, 255, 255) 100%, rgb(245, 247, 250) 0%);

unocss does not provide such complex linear-gradient, it should only be for position from and to rules.

**Comment by lxccc812** [comment]
It’s really painful 😣 to upgrade old CSS to unocss. Many properties found in the official documents do not have corresponding unocss variables, such as some animation effects and some box-shadown. It is really not easy to implement these attributes that are not particularly common one to one.

![image](https://github.com/unocss/unocss/assets/110974969/10950547-a103-45d8-8c37-1ab1f6d1161e)

When I try to search for the `transition-behavior: normal;` attribute, unocss does not have a corresponding variable name.
[transition-behavior: normal;](https://unocss.dev/interactive/?s=transition-behavior)

**Comment by Simon-He95** [comment]
> It’s really painful 😣 to upgrade old CSS to unocss. Many properties found in the official documents do not have corresponding unocss variables, such as some animation effects and some box-shadown. It is really not easy to implement these attributes that are not particularly common one to one.
> 
> ![image](https://user-images.githubusercontent.com/110974969/274879734-10950547-a103-45d8-8c37-1ab1f6d1161e.png)
> 
> When I try to search for the `transition-behavior: normal;` attribute, unocss does not have a corresponding variable name. [transition-behavior: normal;](https://unocss.dev/interactive/?s=transition-behavior)

This vscode plugin that https://github.com/Simon-He95/unot.git will help you It can help you solve most of the conversion problems, and the rest can be done by yourself through other methods. Not all classes completely need to use unocss, and they can be used in a mixed manner.
Hope it can help you

**Comment by zyyv** [comment]
> When I try to search for the `transition-behavior: normal;` attribute, unocss does not have a corresponding variable name.
[transition-behavior: normal;](https://unocss.dev/interactive/?s=transition-behavior)

Our basic rules are aligned with tailwind, and tailwind does not have rules to change. I think it is not a mainstream usage.
You can write your own rules to implement it. https://unocss.dev/config/rules
