### ISSUE TITLE
variants 对 full controlled rule 不生效

### ISSUE THREAD

**Issue by sszlime00** [unocss/unocss#3228]
### Clear and concise description of the problem

需要根据用户位置动态选择合适的cdn域名来获取对应的图片资源。
当前的解决方案是在外层元素设置 data-domain="example" ，并通过 CSS 选择器设置动态设置图片链接
```css
[data-domain='example'] icon-example {
    background: https://example.com/example.svg;
}
```
```html
<div data-domain="example">
  <div class="icon-example"></div>
</div>
```
但是在使用 UnoCSS 尝试生成这样的 CSS 时，因为无法通过 rule 修改 CSS 选择器，导致只能使用 full controlled rule 来实现。
```ts
import { toEscapedSelector as e } from '@unocss/core';
[
  /^icon-(example)$/, ([, name], {rawSelector}) => {
    const selector = e(rawSelector);
    return `
[data-domain='example'] ${selector} {background: https://example.com/example.svg;}
[data-domain='example2'] ${selector} {background: https://example2.com/example.svg;}
`
  }
]
```
这样会使得无法通过 variants 对这些 rule 进行进一步的处理，例如 hover 或 before，after 等。
请问是否有能够在 rule 中对 selector 进行处理，得到 variant 应用之后的选择器，或者是否有更好的实现方法？

### Suggested solution

提供一种在 rule 中对 selector 进行处理，得到 variant 应用后的选择器的方式

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by zyyv** [comment]
For your application scenario, I suggest you write a `variant` instead of `rules`.

**Comment by antfu** [comment]
"full controlled rule" by its name means you take over the full control of it and UnoCSS won't process it further (as it's a raw string instead of a structural data). This is the limitation of this feature.
