### ISSUE TITLE
If class names include "space-x" or "space-y", it will result in incorrect CSS selectors being generated

### ISSUE THREAD

**Issue by euwei7** [unocss/unocss#3231]
### UnoCSS version

0.56.5

### Describe the bug

example:
```vue
<div class="my-[var(--hello-space-y)]"></div>
```
The css selector should be generated: `.my-\[var\(--hello-space-y\)\]`

But it generated:`.my-\[var\(--hello-space-y\)\] > :not([hidden]) ~ :not([hidden])`

The correct CSS selector to generate should be: `.my-\[var\(--hello-space-y\)\]`. However, there was an inclusion of `> :not([hidden]) ~ :not([hidden])` after the selector, which resulted in the CSS style not being applied correctly.

https://github.com/unocss/unocss/assets/120472761/5f319bcf-c995-416d-8485-8b8ed6be88b0

### Reproduction

https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIDuBaAjABigAs9CAjAc2zLgFcBTKAWwE9sBtCBAJwAptsRenDgB7bEgAOCGPWwsAlAF10APmAB6cBFUAoUJFiIUGHAWKkolbN3og1m7aqA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCqVbQF9QcmpU6gA5AFcqTSJDuDBxUYhnzMD6B9ZBUIVNVh1AApJaT0oQ0gALlAAbR1Y-UMTSkiASm1pUB0AXXNcwSA&css=FwJw9mAuDeBQAE8C0SAWBTANpsSDOADgIYDG6SAnsAIwAMtBAHgNywC%2BQA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwBoQJ84AHJeASwDd9Ns8jxp5k0AJMVHR3AgF8gA

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
I will follow up on this issue, As a workaround, you can use `my-$hello-space-y`.
In uno, `$` symbol represents the use of css variable.
