### ISSUE TITLE
vscode: Completion need to enhance

### ISSUE THREAD

**Issue by Simon-He95** [unocss/unocss#3234]
### Clear and concise description of the problem

![屏幕录制2023-10-15 20 47 51](https://github.com/unocss/unocss/assets/57086651/a025797c-5bc0-4e67-915e-0036b74cd8d1)

### Suggested solution

I feel that the current prompts provided are quite limited, not friendly enough and need to be enhanced.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by Simon-He95** [comment]
Of course, I will try to optimize it in my free time

**Comment by henrikvilhelmberglund** [comment]
You could try the fuzzy autocomplete mode, it gives more results. Some of them are strange though like `transform-translate-x` instead of `translate-x`.

**Comment by Simon-He95** [comment]
> You could try the fuzzy autocomplete mode, it gives more results. Some of them are strange though like `transform-translate-x` instead of `translate-x`.

It does not work and this will be difficult to use

**Comment by henrikvilhelmberglund** [comment]
> > You could try the fuzzy autocomplete mode, it gives more results. Some of them are strange though like `transform-translate-x` instead of `translate-x`.
> 
> It does not work and this will be difficult to use

I understand.

There are some other things that are just weird like the colors, let's say I want `bg-green-500`, I have to either type `bg-green-` and scroll down (past `bg-green-1` and whatever) until the thing I want or type the whole string `bg-green-500`.

Most of the times I just give up and use the Tailwind extension instead. 😱

**Comment by Simon-He95** [comment]
> > > You could try the fuzzy autocomplete mode, it gives more results. Some of them are strange though like `transform-translate-x` instead of `translate-x`.
> > 
> > 
> > It does not work and this will be difficult to use
> 
> I understand.
> 
> There are some other things that are just weird like the colors, let's say I want `bg-green-500`, I have to either type `bg-green-` and scroll down (past `bg-green-1` and whatever) until the thing I want or type the whole string `bg-green-500`.
> 
> Most of the times I just give up and use the Tailwind extension instead. 😱

haha， I previously supported similar functions in the unot plug-in. Later, I saw that unocss had this function, so I removed it. Maybe I will help improve this function in my free time.
