### ISSUE TITLE
unocss @apply directives not work with vue-cli5

### ISSUE THREAD

**Issue by Elias-cug** [unocss/unocss#3245]
### UnoCSS version

0.56.5

### Describe the bug

unocss @apply directives not work with vue-cli5. My config like this：
`import {
  defineConfig,
  presetAttributify,
  presetUno,
  transformerVariantGroup,
  transformerDirectives,
} from 'unocss';

export default defineConfig({
  presets: [presetAttributify(), presetUno()],
  transformers: [transformerDirectives(), transformerVariantGroup()],
});`

### Reproduction

https://stackblitz.com/edit/unocss-unocss-ue86xi?file=src%2FAbout.vue

### System Info

mac

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by flyingalex** [comment]
Need to use https://unocss.dev/integrations/postcss
