### ISSUE TITLE
bg-[url('/path/to/image')] quotes in url not supported

### ISSUE THREAD

**Issue by MarvinXu** [unocss/unocss#3247]
### UnoCSS version

v0.56.5

### Describe the bug

`preset-wind` is supposed to be [compatible](https://unocss.dev/presets/wind#rules) with tailwind, but `bg-[url('/img/hero-pattern.svg')]` with single quotes is not supported.

### Reproduction

[tailwind playground](https://play.tailwindcss.com/vCpAyA8tKm)
[unocss playground](https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIAWBaATABigHc9CAjAc2zMRgGspLsBtAVwCc4AKAckwBd%2BAByQAuAPTii0gHQUA9vIpwApjJjyAtuLCaEFFUnFl2CAHbgzFcQqWq4S%2BeNwAPG4uUqHCgPpwwFAI%2BGg7sPgCcrgDM%2BCBCMkJWPACUALroAHzA4uAQGQBQQA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAqrhEgL5xZQQhwDkAV1YBjOnX5IkGAB6RY6bAENBAG3iYc%2BIiWCkAFMlQ16jOgC44AbSrHaDZq30BKKgF0OroA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwBpxp5k0AJMVHTbPfAXyA)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
https://github.com/unocss/unocss/blob/d0e101d68c9c4492e90053c09030da6690105014/packages/core/src/extractors/split.ts#L3-L8

We use this extractor by default to extract unitilities to maximize uno extraction capabilities.
`'` `"` will break the extractor's ability to extract unitilities, i don't recommend using them.

**Comment by MarvinXu** [comment]
I don't think you get my point.

I use quotes with bg url and it costs me 1 hour to figure out why it doesn't work.

If you don't recommend using quotes it's best to clarify in the doc as it's NOT [compatible](https://unocss.dev/presets/wind#rules) with tailwind.
