### ISSUE TITLE
ts + react + vite tsx files will be underlined in places other than className when using the vscode extension

### ISSUE THREAD

**Issue by foreinbug** [unocss/unocss#3258]
### UnoCSS version

0.56.5

### Describe the bug

ts + react + vite tsx files will be underlined in places other than className when using the vscode extension

### Reproduction

https://codesandbox.io/p/sandbox/laughing-darkness-mdfssp?file=%2Fsrc%2FApp.tsx%3A1%2C1-41%2C1

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
> ![image](https://private-user-images.githubusercontent.com/29174474/350318193-2b013c9b-5089-4aad-ab73-95d17ddce39e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNzc0OTUsIm5iZiI6MTcyMTM3NzE5NSwicGF0aCI6Ii8yOTE3NDQ3NC8zNTAzMTgxOTMtMmIwMTNjOWItNTA4OS00YWFkLWFiNzMtOTVkMTdkZGNlMzllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDA4MTk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjNmZlZGU4MzU5YTM4YWYxYTM2ZjQyYjljMGRkNjA0NTM1OTdhMWNkMzQxYmU3N2ZjMjg0ODhiYTBiOGZmNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8T2qLZox43UiEMNgrymz7QMZfFc-17KeYLJuPvbUqbA) <img alt="image" width="659" src="https://private-user-images.githubusercontent.com/29174474/350318325-f337272c-733b-43b1-9caa-25738e7a0bd1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNzc0OTUsIm5iZiI6MTcyMTM3NzE5NSwicGF0aCI6Ii8yOTE3NDQ3NC8zNTAzMTgzMjUtZjMzNzI3MmMtNzMzYi00M2IxLTljYWEtMjU3MzhlN2EwYmQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDA4MTk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzNzA3ZTFhN2IxZGYzY2ZjOTYxODMwNzY1MDI5MGU2YjY2NzI5OWE5Yzc2MWVhOGZkZjU1M2I3NzZjOWM3N2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KXlaL8Ro-eTozCgDMRRJR7x3xHO6uC7vQK4CwOJX3tA"> 这个怎么解决，把变量编译成了css class

https://unocss.dev/guide/extracting

**Comment by lhf6623** [comment]
> > ![image](https://private-user-images.githubusercontent.com/29174474/350318193-2b013c9b-5089-4aad-ab73-95d17ddce39e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNzc0OTUsIm5iZiI6MTcyMTM3NzE5NSwicGF0aCI6Ii8yOTE3NDQ3NC8zNTAzMTgxOTMtMmIwMTNjOWItNTA4OS00YWFkLWFiNzMtOTVkMTdkZGNlMzllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDA4MTk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjNmZlZGU4MzU5YTM4YWYxYTM2ZjQyYjljMGRkNjA0NTM1OTdhMWNkMzQxYmU3N2ZjMjg0ODhiYTBiOGZmNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8T2qLZox43UiEMNgrymz7QMZfFc-17KeYLJuPvbUqbA) <img alt="image" width="659" src="https://private-user-images.githubusercontent.com/29174474/350318325-f337272c-733b-43b1-9caa-25738e7a0bd1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNzc0OTUsIm5iZiI6MTcyMTM3NzE5NSwicGF0aCI6Ii8yOTE3NDQ3NC8zNTAzMTgzMjUtZjMzNzI3MmMtNzMzYi00M2IxLTljYWEtMjU3MzhlN2EwYmQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDA4MTk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzNzA3ZTFhN2IxZGYzY2ZjOTYxODMwNzY1MDI5MGU2YjY2NzI5OWE5Yzc2MWVhOGZkZjU1M2I3NzZjOWM3N2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KXlaL8Ro-eTozCgDMRRJR7x3xHO6uC7vQK4CwOJX3tA">这个怎么解决，把变量编译成了css class
> 
> https://unocss.dev/guide/extracting

I now know: @ unocss skip start @ unocss skip end.

But my code is in tsx, and I don't want to have to think about whether it will be compiled into CSS by unocss every time I write code

**Comment by Simon-He95** [comment]
Because unocss scans the entire file, you can only use the vscode plug-in to sense the underline at the bottom of the matching element. If it is not expected, you can filter it out manually. Of course, the plug-in now supports shortcut commands to let you quickly generate skip statements. I hope it will be helpful to you.

<img width="445" alt="image" src="https://github.com/user-attachments/assets/0a50419b-bb1c-4618-9db1-7276ec8bb113">
