### ISSUE TITLE
ANIMATIONS: animate-bounce-in-down/animate-bounce-in-up has an annoying delay.

### ISSUE THREAD

**Issue by mainseq** [unocss/unocss#3266]
### UnoCSS version

0.57.0

### Describe the bug

'bounce-in-down': '{from,60%,75%,90%,to{animation-timing-function:cubic-bezier(0.215,0.61,0.355,1)}0%{opacity:0;transform:translate3d(0,**-3000px**,0)}60%{opacity:1;transform:translate3d(0,25px,0)}75%{transform:translate3d(0,-10px,0)}90%{transform:translate3d(0,5px,0)}to{transform:translate3d(0,0,0)}}',

The -3000px is taking nearly (1) second to appear on the screen. Is there anyway to offer the bounce-in just off the top of the page/body? We are using it for notifications and the delay makes it unusable. Is there any work around?       

### Reproduction

https://uno.antfu.me/play/?html=DwEwlgbgBAFgtAMwK4BsVQC4FMAeG4DGWAdtgE5QIq5QDOW1B%2BxA9sVlAIZoBcGZnYrTAYwbOABYADFIB8AKChRQkKAFtOCpUpXRseOAFYc6BAHcAjDK7EwG7HABGLJMSJwwxOCBZniNu04HECQBUXEAJlotbSUAVVYAYQBlZMVtYAB6cAgYnRyoFgAHAGYpTFx8FABzSjMy8rULPO0AFRgOT1oMQQxCrxAsDWIQKABBDBY1MAIoFOSoEmrPLAA6dJ1syBbddQjKahwoACskbrAEAE9CEnIKgwiTQtLymBYILDIAXgAiYoAOKQ-Fo6TgbWJQMCEThkZxeFAsaosODLDAwJCOcGxfT4TwdMgiLHaGBkLAIX4wDAYIq0HiZTKo9GOVYEKaZVwsAi0Wjs1hc2g-IlKHpkapYDC-AD6jhQggA1oKIVBZFlNOCsjkYhrtvJtbldQVOI5aCwUEhsFBnFSpkYoATqpS4OVqAh8OUcTdSJ9nmU6g0YuJBsNRgB2yFCHqkKBh5BoS5QAhnSbTABeRuouq2uSAA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDASSarID3fsMBVKtoAvqByNJScoADkFlRMkJCRgoLEoogy8pgW0GmyCoQqarDqABSS0jRZUABcoADaOtK1kUwWkIjhtJWRmhKg7tB8NZF0qJGggQC6XlM6kAAWfIgtAjVl0lEtbR3zi8uRQ6wkyNDqoIcofJjw6uCgCwBu4DRV58ismNDdOoFeTgYrdQa3mciH8lGKAEovI4fMZTIxLNY7JDocD-m4PKUgdJIEwPuAagBGAB0ACZUdImKh4EM5qZuJAqiAoJxifNgF91uMoToZoEIYIgA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwBpxp5k0AJMVHTbPfAXyA

### System Info

Windows11/Chrome

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by henrikvilhelmberglund** [comment]
You can create a custom animation pretty easily, in your uno.config.js/ts add this
```js
theme: {
	animation: {
		keyframes: {
			"in-out-custom":
				"{from,60%,75%,90%,to{animation-timing-function:cubic-bezier(0.215,0.61,0.355,1)}0%{opacity:0;transform:translate3d(0,-100px,0)}60%{opacity:1;transform:translate3d(0,25px,0)}75%{transform:translate3d(0,-10px,0)}90%{transform:translate3d(0,5px,0)}to{transform:translate3d(0,0,0)}}",
		},
		durations: {
			"in-out-custom": "1s",
		},
		timingFns: {
			"in-out-custom": "ease-in-out",
		},
		counts: {
			"in-out-custom": "infinite",
		},
	},
},
```
and you can use your animation with `animate-in-out-custom`. After that you can tweak your keyframes, duration, pixel transform value, percentages and so on until you get something you like. You may have to restart the server for the animation to update, if you find that annoying you can use the playground until you get something that looks good.

When you're happy with the animation you can set the counts to 1.

**Comment by mainseq** [comment]
I was thinking more like bounce-in-down-[-100px] where you can pick an arbitrary starting point. The -3000px drop is only useful in very limited situations. Of course I can override the existing animation. But I'd rather use the built-in one if possible. That's why I entered the issue.

**Comment by henrikvilhelmberglund** [comment]
> I was thinking more like bounce-in-down-[-100px] where you can pick an arbitrary starting point. The -3000px drop is only useful in very limited situations. Of course I can override the existing animation. But I'd rather use the built-in one if possible. That's why I entered the issue.

Yes but changing this existing animation would break the animation for everyone who is using it right now and who wanted the 3000px drop. I think it's easier to start with some animation, copy its properties from the source and refine it until you've got what you need.

Dynamic animation rules like `bounce-in-down-[-100px]` would be interesting but I'm not sure if that's even possible right now, it's probably best to just create custom animations for now. If you create a nice one and would like to have have it in base UnoCSS it may be possible to just add it as a new animation (or in some kind of animation preset).

**Comment by mainseq** [comment]
Adding arbitrary values would probably be useful for all animations not just this one. Things such as duration, counts, easing functions, etc. Nearly all Uno classes allow for arbitrary values already so it's not that out of the realm. I appreciate the feedback. I have a workaround that is what I need. Thank you.

**Comment by userquin** [comment]
Animations were extracted from WindiCSS plugins: https://github.com/windicss/plugins/blob/main/packages/animations/animate/keyframes/bounceIn.js

Check the original issue: https://github.com/unocss/unocss/issues/89
