### ISSUE TITLE
Inconsistent color representation of rgba and rgb when passing CSS variables and constants in version 0.57.1

### ISSUE THREAD

**Issue by lanseria** [unocss/unocss#3268]
### UnoCSS version

0.57.1

### Describe the bug

In version 0.57.1 of the software/library, there is an inconsistency in the way rgba and rgb colors are represented when passing them as CSS variables and constants.

### Reproduction

# Steps to Reproduce:

- Define an rgba or rgb color value as a CSS variable or constant.
- Use the defined variable or constant to apply the color to an element.
- Observe the rendered color on the element.

demo url:  https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIACMD2A7AFwTDwFMAndAPgCgopRJZEUMBbAgWgCYAGABwAeUNnB4DhmOAHMAXAVKCuSANYBPTgBZevKACMc5EBX2Hj5TkhxwwIU0YqcA2uWl6AFJ04JyuPXABXUk4AdgBKAF1qOnoARnj4mOAAenAIWnpGaHhkNHQOcSERMT4iqTkFJUt1LR17c3rHKxs7AwcLFzd3WM0AGgA2ft7uWN5I6PooBMTM1MhaFLSqIA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUkNikEA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2Bmjo2NrRQ5VnKqAg2AOwakZ1UAGzLVABMkb5AA&options=N4XyA

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
Hope it helps you
https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIACMD2A7AFwTDwFMAndAPgCgopRJZEUMBbAgWgCYAGABwAeUNnB4DhmOAHMAXAVKCuSANYBPTgBZevKACMc5EBX2Hj5TkhxwwIU0YqcA2uWl6AFBATl3nTt9w9OABXUk4AdgBKSIBdajp6AEZk5ITgAHpwCFp6Rmh4ZDR0DnEhETE%2BMqk5BSVLdS0de3NmxysbOwMHCxc3d0TNABoANmHB7kTeWPj6KBTU3MzIWgysqiA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUkNikEA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmjraakVYcGY2NrRQ5VnKqAg2AOwakZ1gAGybYABMkb4D2kA&options=N4XyA

**Comment by lanseria** [comment]
@Simon-He95 
need to use the format "14 66 210"? But previously, [Arco](https://arco.design/vue/en-US/docs/start) framework used a lot of 
```
--arcoblue-1: 232,243,255;
--arcoblue-2: 190,218,255;
--arcoblue-3: 148,191,255;
--arcoblue-4: 106,161,255;
--arcoblue-5: 64,128,255;
--arcoblue-6: 22,93,255;
--arcoblue-7: 14,66,210;
--arcoblue-8: 7,44,166;
--arcoblue-9: 3,26,121;
--arcoblue-10: 0,13,77;
```

Is there any compatible solution?

**Comment by Simon-He95** [comment]
https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIACMD2A7AFwTDwFMAndAPgCgopRJZEUMBbAgWgCYAGABwAeUNnB4DhmOAHMAXAVKCuSANYBPTgBZevKACMc5EBX2Hj5TkhxwwIU0YqcA2uWl6EACggJyHzpx9cPTgAV1JOAHYASiiAXWo6egBGFJTE4AB6cAhaekZoeGQ0dA5xIRExPnKpOQUlS3UtHXtzFscrGzsDBwsXNw8kzQAaADYRoe4k3jiE%2BihUtLysyFpM7KogA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUkNikEA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmjraakVYcGY2NrRQ5VnKqAg2AOwakZ1UAGybVABMkb4D2kA&options=N4XyA
