### ISSUE TITLE
[BUG] Unocss v0.57.1 cannot  transform `hsl(var(--primary))` correct.

### ISSUE THREAD

**Issue by zouhangwithsweet** [unocss/unocss#3274]
### UnoCSS version

v0.57.1

### Describe the bug

expect: 
`hsla(var(--primary),var(--un-bg-opacity))`

actually:
`hsl(var(--primary) / var(--un-bg-opacity))`

### Reproduction

https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIDmAnA9gVwAd0oQEAXBAWiUvIFMNdD6A7Esyq5tjBGcpHokAFhgDaMBHBgAKAIwAGRRBEB9KmoAs2egFsAlAF10APgBQUKMCSEErWIhQYcBQlXHjO1Hq1T9BCHojIwAuBgAPcioAT3o4OFwAdyoAdmUoM0srKBF4xOzgAHpbewsrGzsHeGQ0dEjowmwwPQRsGLMANm7O4tLWC2LwCFMgA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUdrQsE5vLD9mFmi1pjACABlKmhc5wAC8AD44AADL7BbQQeBklpwRKJGigexQfihAAM5AB4vFAFJyABWOUAbi%2Bai%2B7K2FSoMCqGBA-0Qh2y0H2vKuwtFMLoTh8cxFPgFQpAIv4ZzOmK2VHV2KQQA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgTgpgzgDg9gOygSwG4RALgGYEMA2UEAvkA

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zouhangwithsweet** [comment]
#3221

**Comment by Simon-He95** [comment]
https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIDmAnA9gVwAd0oQEAXBAWiUvIFMNdD6A7Esyq5tjBGcpHokAFhgDaMBHBgAKAIwAGRRBEB9KmoAs2egFsAlAF10APgBQUKMCSEErWIhQYcBQlXHjO1Hq1T9BCHojIwAuBgAPcioAT3o4OFwAdyoAdmUoM0srKBF4xOzgAHpbewsrGzsHeGQ0dEjowmwwPQRsGLMANm7O4tLWC2LwCFMgA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6VCWydAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k5mqGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWmoLuUdrQsE5vLD9mFmi1pjACABlKmhc5wAC8AD44AADL7BbQQeBklpwRKJGigexQfihAAMcAB4vFAFI4ABWOUAbi%2Bai%2B7K2FSoMCqGBA-0Qh2y0H2vKuwtFMLoTh8cxFPgFQpAIv4ZzOmK2VHV2KQQA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgTgpgzgDg9gOygSwG4RALgGYEMA2UEAvkA

**Comment by zouhangwithsweet** [comment]
So it's a breaking change ?
