### ISSUE TITLE
vscode extension is over hinting, including variable

### ISSUE THREAD

**Issue by aboveyunhai** [unocss/unocss#3278]
### UnoCSS version

not applicable, latest Unocss vscode extension v0.57.1

### Describe the bug

The latest unocss vscode is running correctly, but it over hinting, cause confusion on reading regular variable, shouldn't it check string only?.
![image](https://github.com/unocss/unocss/assets/35160613/17b3a603-b182-408c-94d0-b5db733cfaae)

For the typescript, it's very tricky since it's a valid `string`, so I can't tell it's the intention, fixable or not, but I will leave it here as reference.

![image](https://github.com/unocss/unocss/assets/35160613/68d38755-f753-4efc-82d1-2121cc08145e)

### Reproduction

install the unocss vscode extension and use the example code from screenshot.

### System Info

Windows 10

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by louiss0** [comment]
This is a problem that I see as well.  I don't know why Uno does this.

**Comment by rick-ast** [comment]
I also get the unexpected hints in css file.
<img width="514" alt="Screenshot 2023-12-28 at 08 09 14" src="https://github.com/unocss/unocss/assets/130942798/3244d244-1481-4505-8ea0-cf27826fa019">

**Comment by antfu** [comment]
This is how UnoCSS works by scanning for occurrence. I initially designed VS Code extension that way it's more consistent with the runtime behavior, but yeah I agree this can be annoying at some point. I think we could treat VS Code a bit, especially by only highlighting a certain context.
