### ISSUE TITLE
unocss 打包遇到重复unocss会输出2份代码，然后停止其他外部css的编译输出

### ISSUE THREAD

**Issue by aofong19871029** [unocss/unocss#3282]
### UnoCSS version

0.56.4

### Describe the bug

unocss编译器: "@unocss/postcss": "0.56.4",

### Reproduction

有一个poplayer组件，使用unocss, 打包后生成一个单独的index.css
在开发另外个list组件的时候，引用poplayer组件和它的css, 以及另外个非unocss组件usp及其css

poplayer组件代码
`const Layer = (props: LayerProps): JSX.Element => {
    const { open, onClose, children, shouldCloseOnOverlayClick = true, contentClassName = '', layerClassName = '' } = props

    const closeModalOnOverlayClick = () => {
        if (shouldCloseOnOverlayClick) {
            onClose()
        }
    }

    const preventClose = (e: React.MouseEvent) => {
        if (shouldCloseOnOverlayClick) {
            e.stopPropagation()
        }
    }

    if (!open) {
        return <></>
    }

    return (
        <div className={`fixed inset-0 z-1000 bg-[rgba(0,0,0,0.6)] flex items-center justify-center translate-0 translate-z-0 transition-opacity duration-0.3s layer ${layerClassName}`} onClick={closeModalOnOverlayClick}>
            <div className={`absolute shadow-[0_8px_20px_0_rgba(0,41,99,0.2)] max-h-80% max-w-1000px ${contentClassName}`} onClick={preventClose}>{children}</div>
        </div>
    )
}

export default Layer`
poplayer组件生成的css
`/* 导入uno入口, 不要删除 */
/* layer: preflights */
*,::before,::after{--un-rotate:0;--un-rotate-x:0;--un-rotate-y:0;--un-rotate-z:0;--un-scale-x:1;--un-scale-y:1;--un-scale-z:1;--un-skew-x:0;--un-skew-y:0;--un-translate-x:0;--un-translate-y:0;--un-translate-z:0;--un-pan-x: ;--un-pan-y: ;--un-pinch-zoom: ;--un-scroll-snap-strictness:proximity;--un-ordinal: ;--un-slashed-zero: ;--un-numeric-figure: ;--un-numeric-spacing: ;--un-numeric-fraction: ;--un-border-spacing-x:0;--un-border-spacing-y:0;--un-ring-offset-shadow:0 0 rgba(0,0,0,0);--un-ring-shadow:0 0 rgba(0,0,0,0);--un-shadow-inset: ;--un-shadow:0 0 rgba(0,0,0,0);--un-ring-inset: ;--un-ring-offset-width:0px;--un-ring-offset-color:#fff;--un-ring-width:0px;--un-ring-color:rgba(147,197,253,0.5);--un-blur: ;--un-brightness: ;--un-contrast: ;--un-drop-shadow: ;--un-grayscale: ;--un-hue-rotate: ;--un-invert: ;--un-saturate: ;--un-sepia: ;--un-backdrop-blur: ;--un-backdrop-brightness: ;--un-backdrop-contrast: ;--un-backdrop-grayscale: ;--un-backdrop-hue-rotate: ;--un-backdrop-invert: ;--un-backdrop-opacity: ;--un-backdrop-saturate: ;--un-backdrop-sepia: ;}
::backdrop{--un-rotate:0;--un-rotate-x:0;--un-rotate-y:0;--un-rotate-z:0;--un-scale-x:1;--un-scale-y:1;--un-scale-z:1;--un-skew-x:0;--un-skew-y:0;--un-translate-x:0;--un-translate-y:0;--un-translate-z:0;--un-pan-x: ;--un-pan-y: ;--un-pinch-zoom: ;--un-scroll-snap-strictness:proximity;--un-ordinal: ;--un-slashed-zero: ;--un-numeric-figure: ;--un-numeric-spacing: ;--un-numeric-fraction: ;--un-border-spacing-x:0;--un-border-spacing-y:0;--un-ring-offset-shadow:0 0 rgba(0,0,0,0);--un-ring-shadow:0 0 rgba(0,0,0,0);--un-shadow-inset: ;--un-shadow:0 0 rgba(0,0,0,0);--un-ring-inset: ;--un-ring-offset-width:0px;--un-ring-offset-color:#fff;--un-ring-width:0px;--un-ring-color:rgba(147,197,253,0.5);--un-blur: ;--un-brightness: ;--un-contrast: ;--un-drop-shadow: ;--un-grayscale: ;--un-hue-rotate: ;--un-invert: ;--un-saturate: ;--un-sepia: ;--un-backdrop-blur: ;--un-backdrop-brightness: ;--un-backdrop-contrast: ;--un-backdrop-grayscale: ;--un-backdrop-hue-rotate: ;--un-backdrop-invert: ;--un-backdrop-opacity: ;--un-backdrop-saturate: ;--un-backdrop-sepia: ;}
* {box-sizing: border-box; -webkit-box-sizing: border-box}
/* layer: default */
.absolute{position:absolute;}
.fixed{position:fixed;}
.inset-0{top:0;right:0;bottom:0;left:0;}
.z-1000{z-index:1000;}
.hidden{display:none;}
.max-h-80\%{max-height:80%;}
.max-w-1000px{max-width:1000px;}
.flex{display:flex;}
.translate-0{--un-translate-x:0;--un-translate-y:0;transform:translateX(var(--un-translate-x)) translateY(var(--un-translate-y)) translateZ(var(--un-translate-z)) rotate(var(--un-rotate)) rotateX(var(--un-rotate-x)) rotateY(var(--un-rotate-y)) rotateZ(var(--un-rotate-z)) skewX(var(--un-skew-x)) skewY(var(--un-skew-y)) scaleX(var(--un-scale-x)) scaleY(var(--un-scale-y)) scaleZ(var(--un-scale-z));}
.translate-z-0{--un-translate-z:0;transform:translateX(var(--un-translate-x)) translateY(var(--un-translate-y)) translateZ(var(--un-translate-z)) rotate(var(--un-rotate)) rotateX(var(--un-rotate-x)) rotateY(var(--un-rotate-y)) rotateZ(var(--un-rotate-z)) skewX(var(--un-skew-x)) skewY(var(--un-skew-y)) scaleX(var(--un-scale-x)) scaleY(var(--un-scale-y)) scaleZ(var(--un-scale-z));}
.items-center{align-items:center;}
.justify-center{justify-content:center;}
.bg-\[rgba\(0\,0\,0\,0\.6\)\]{--un-bg-opacity:0.6;background-color:rgba(0,0,0,var(--un-bg-opacity));}
.shadow-\[0_8px_20px_0_rgba\(0\,41\,99\,0\.2\)\]{--un-shadow:0 8px 20px 0 var(--un-shadow-color, rgba(0,41,99,0.2));box-shadow:var(--un-ring-offset-shadow), var(--un-ring-shadow), var(--un-shadow);}
.transition-opacity{transition-property:opacity;transition-timing-function:cubic-bezier(0.4, 0, 0.2, 1);transition-duration:150ms;}
.duration-0\.3s{transition-duration:0.3s;}
.layer {
    transform: translate(0) translateZ(0);
    transition: opacity 0.3s;
    animation: 0.3s ease 0s 1 normal forwards running maskAnimation
}
@keyframes maskAnimation {
    0% {
        opacity: 0
    }

    100% {
        opacity: 1
    }
}`

list组件引用poplayer和usp的代码
`import poplayer from 'poplayer'
 import 'poplayer/dist/index.css

<Layer 
                open={showQuestionModal}
                onClose={() => setShowQuestionModal(false)}>
                {/*弹窗的内容*/}
            </Layer>
`

list引用usp的代码
`
import USP from '@companty/usp'
import '@company/usp/dist/index.css'

const USP = (): JSX.Element => {
    return (
        <USP/>
    )
}

export default USP`

usp的css内容
`@font-face{font-family:fi;src:url(../assets/442933c39a10b10dce021cb7ab870c64.woff2) format("woff2"),url(../assets/f79a09682f12708aa8880959e35e8f8a.woff) format("woff"),url(../assets/d50cf2eabd6294ed4b1bc72db670950a.ttf) format("truetype")}.fi{font-family:fi!important;font-size:16px;font-style:normal;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}`

打包后, poplay/dist/css的内容出现了2份， usp css内容没有出现
删除 import 'poplayer/dist/index.css 或者把这句话移到其他文件，生成的css就包含了usp css的内容
另外删除import 'poplayer/dist/index.css 之后poplayer的css就正常，只输出一次了

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
Please provide a minimum reproducible demo and its reproducible operation so that we can troubleshoot the problem faster. Thank you.
