### ISSUE TITLE
unocss异步问题

### ISSUE THREAD

**Issue by fslflame** [unocss/unocss#3288]
### UnoCSS version

0.56.1

### Describe the bug

页面元素在dom生成后获取其宽高， 但是这个元素的padding是UnoCSS写的，第一次进入的时候，padding加上了，但是js获取的dom元素的宽高不包裹padding。刷新页面或者加个定时器就能获取到，但是如果用原生class或style写的pdding 就能实时获取到。只有项目第一次启动的时候进入页面会有该问题，这属于UnoCSS的异步问题吗？ 如何解决呢
下面是引入顺序
![image](https://github.com/unocss/unocss/assets/101857530/27113a70-15cc-4166-ba49-b21efc0aed5b)
![image](https://github.com/unocss/unocss/assets/101857530/db080c07-ae16-41ce-9f7b-c1613136384c)

### Reproduction

页面元素在dom生成后获取其宽高， 但是这个元素的padding是UnoCSS写的，第一次进入的时候，padding加上了，但是js获取的dom元素的宽高不包裹padding。刷新页面或者加个定时器就能获取到，但是如果用原生class或style写的pdding 就能实时获取到。只有项目第一次启动的时候进入页面会有该问题，这属于UnoCSS的异步问题吗？ 如何解决呢
下面是引入顺序
![image](https://github.com/unocss/unocss/assets/101857530/27113a70-15cc-4166-ba49-b21efc0aed5b)
![image](https://github.com/unocss/unocss/assets/101857530/db080c07-ae16-41ce-9f7b-c1613136384c)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
First of all, I hope you will submit the issue in English so that people who encounter the same problem can find the answer. In addition, you need to provide the smallest demo that can be reproduced so that we can solve the problem faster. I will temporarily close this issue, and please reopen it after providing a minimal reproducible demo.
