### ISSUE TITLE
Variant groups not working with @unocss-include

### ISSUE THREAD

**Issue by silveltman** [unocss/unocss#3291]
### UnoCSS version

0.57.1

### Describe the bug

I have a project where I define some of my classes in my cms. Therefore, unocss does not see then and does not know to load those classes.

My solution is automatically downloading these classes and writing them somewhere in the repo, so that unocss can read them. The following file gets writter:
```
// @unocss-include
     export default [
  {
    "id": "653f67a05ff5cbbff714de00",
    "name": "Primary herooo",
    "for": [
      "hero"
    ],
    "block": {
      "frame": "fill",
      "layout": "col",
      "x": "stretch",
      "y": "start",
      "size": "large",
      "class": "!pt-0 min-h-screen mb-0 pb-0 [&+*]:(pt-0 mt-0)"
    },
    "segment": {
      "layout": "row",
      "x": "between",
      "y": "center",
      "class": "border-b border-hue6 py-size5"
    },
    "list": {},
    "writeup": {
      "class": "[&_p:first-child]:(hue-brand) [&_h1]:leading-none [&_h1]:lg:text-80px"
    },
....
];
```

The bug here is that the classes applied using variant groups do not work. The classes are attached to the elements via props, and I know 100% sure that they are attached correctly. 

### Reproduction

Don't know how to re-create this, since unocss playground does not have this problem, because unocss reads everything in there correctly. 

### System Info

Astro, mac

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
[Playground](https://unocss.dev/play/?html=KYDwDg9gTgLgBAE2AMwIYFcA28DaAoOOAbwMLgCIBLBcgLgoDYBWAZmQYHZUAGJ5ZJgGMARsP4cAjABYk3buQA0pQuQB2qALbA6FAApRKG1FACecABbAoEG4uUVk0HfjJlyl6%2BXsBdJa-LCmBCCANY6JK4qyFCa2vTkyJSYmHaRFJioJhDoMDrkghApfpHkIHkAzjBQwDCC5qklJhUwxrnF-uWUAF5x6cYA5trtboIZ5eV5AIRgMAC03HAalKqz5rPlgtXAqovC83Bgews4AGQA1ABU3rQAFDP7GnPcAJRergC%2Bw%2BTlwP1aqrl6BEShksjk8tYAO4NfxleLCGqQ4DbGFuJrxQTbGBWVEqUaocZ5YTQJBQWbCODEqCk1boYAMA4mdbdYBMN5kT72ciYSiVcKc-yQgzY9BgcL2PFjCbxU4AfTAtESUEqszqSQQ1xu5jp5JiqgQzzgcvMEmumGAqAQy36s1UEFUwCNJ1lJrN-Vo2JAcwAHNwwGV7JzvABuIA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpwxQCGuAzltCBlACLBQYDGMwANwwNKqGvSYs2ANVpRg9GAHEoEAK5hKAXzhZVIOAHI1uCDwYNDSUJFiI4YbgwwwAqs6xqANnB16IBsam5gwAtI7CLqFqHt5WSBgAHrbwmFi03qnYeITEZAAUyKgMABbQMDxqMAwAXIhUqADudGBgbHWGjaEMPNwYuHAl3b0Y-bo8E4aivtMRztV1ANoNDk4u7tjehSuowDzEtfWox8c9tF4YdQCMAHQATNMnqDxouB0lMDBgtQD0P8IgG6lH5THYzFZaACU0wAutNxIxmFBWFBDosEZJkWxONw%2BIJhPlodQ6IipFBZPJFCp1GBCXCkFCkEA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwBpxp5k0BhAVzjCVQoGVHNs8iTZEVUAJMVDla4CAXyA) 

I see this has some utilities extracted and converted. 

I don't know the injection timing of this file or maybe it needs a custom stronger `extractor` to work.
