### ISSUE TITLE
Confusion over the order of the same rules

### ISSUE THREAD

**Issue by yveeven** [unocss/unocss#3293]
### UnoCSS version

0.57.1

### Describe the bug

As with the minimal implementation, it's not retrieved from the beginning nor the end, instead it uses red in the middle, but that's not to say that it's necessarily the middle, my feeling seems to be that there's a set of default rules in order for a reason, but that doesn't cover the same rules

### Reproduction

https://stackblitz.com/edit/nuxt-starter-a4phwp?file=app.vue

### System Info

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yveeven** [comment]
I noticed your solution and I am now asking how the solution is, thank you

**Comment by chu121su12** [comment]
By default, output of those kind of rules (as in example, `bg-<color>`) are sorted alphabetically

**Comment by chu121su12** [comment]
> I noticed your solution and I am now asking how the solution is, thank you

Try #3261

**Comment by yveeven** [comment]
> By default, output of those kind of rules (as in example, `bg-<color>`) are sorted alphabetically

First of all I'm not defining my own rules, I'm just using the official presets, so I don't think it has anything to do with layers!

Then I would like to point out that the current unocss implementation does not match the order explicitly stated in the documentation

Also there is an unclear order relationship in the case of non-colour values as in the minimal implementation of two/two-1 positions, if it is alphabetical then why is `rounded-sm` a lower priority than `xl`.

Secondly alphabetical ordering is not as intuitive as the documented priority of the latter, and the main point I'm trying to make is that priority is in effect when there are multiple occurrences of the same rule, whereas alphabetical ordering of a collection of rules doesn't seem to be a problem to me.


![CleanShot 2023-11-01 at 15 25 55](https://github.com/unocss/unocss/assets/76424723/8f75fa66-ffe6-4df8-8f1b-003f7304ee35)

**Comment by chu121su12** [comment]
> First of all I'm not defining my own rules, I'm just using the official presets, so I don't think it has anything to do with layers!

Layering can help when you want to force the order/priority

> Then I would like to point out that the current unocss implementation does not match the order explicitly stated in the documentation

There are 2 type of rules: static and dynamic. Order will be followed as documented, but the dynamic rule is a callback and have access to api that can modify the default behavior

> Also there is an unclear order relationship in the case of non-colour values as in the minimal implementation of two/two-1 positions, if it is alphabetical then why is `rounded-sm` a lower priority than `xl`.

rounded uses the dynamic rule and follows alpha ordering by default. also `sm` is less than `xl` by ascii order

> Secondly alphabetical ordering is not as intuitive as the documented priority of the latter, and the main point I'm trying to make is that priority is in effect when there are multiple occurrences of the same rule, whereas alphabetical ordering of a collection of rules doesn't seem to be a problem to me.

Apparent similar rule that uses dynamic rule definition is sorted alphabetically by default. This, I concur, warrant documentation update

Sorry for the confusion, but the way sorting works is just one of the implementation detail in the unocss itself vs the presets

**Comment by yveeven** [comment]
> > 首先，我没有定义自己的规则，我只是使用官方的图层，所以我不认为它与图层有任何关系！
> 
> 当你想强制执行顺序/优先级时，分层可以提供帮助。
> 
> > 然后我想指出，目前unocss的执行与文档中明确说明的顺序不匹配
> 
> 有两种类型的规则：静态和动态。将按照文档中的顺序执行，但动态规则是回调，可以访问可以修改默认行为的API
> 
> > 同样，在非颜色值的情况下，如在两个/两个-1位置的最小实现中，存在不清楚的顺序关系，如果它是字母的，那么为什么`rounded-sm`的优先级低于`xl`。
> 
> 四舍五入使用动态规则并默认遵循alpha排序。`sm`也按顺序小于`xl`
> 
> > 其次，按字母顺序排序并不像后者的文档优先级那样直观，我试图说明的主要观点是，当同一规则多次出现时，优先级是有效的，而按字母顺序排序规则集合对我来说似乎不是问题。
> 
> 默认情况下，使用动态规则定义的表观相似规则按顺序排序。我同意这一点，
> 
> 很抱歉造成混淆，但是排序工作的方式只是unocss本身与unocss的实现细节之一。

Understand, thank you for your detailed explanation, I understand, but I personally feel from the bottom of my heart even if the dynamic rules, according to the order of writing the implementation of the priority is more intuitive, because if in accordance with the current way if you want to take into account the alphabetical order of the words, to a certain extent, limit the use of the rules of repeatability, of course, can be resolved through the layer, but then the configuration will be more troublesome, I do not know whether this implementation details are not destructive and will be considered for the proposal, if it is destructive, then it may not be necessary!

**Comment by chu121su12** [comment]
I understand the concern, but we just don't have enough information to guess developer intention when using class for style selector. I'd be happy if there's alternatives. In the meantime, please consider the example in the [linked PR](https://github.com/unocss/unocss/pull/3294#issuecomment-1788292837).

**Comment by wencongNew** [comment]
> I understand the concern, but we just don't have enough information to guess developer intention when using class for style selector. I'd be happy if there's alternatives. In the meantime, please consider the example in the [linked PR](https://github.com/unocss/unocss/pull/3294#issuecomment-1788292837).

If using unocss to develop component libraries, write a button.for example:
```js
let style = {
      'primary': 'bg-blue',
      'primary-outline': 'bg-transparent',
      'primary-outline-active': 'bg-gray',
}

```
```html
<button class="bg-blue bg-transparent bg-gray"></button>
```
At this time, it is necessary to make bg-gray weight the highest
It would be very convenient to use it if it could be sorted in writing order

**Comment by yveeven** [comment]
> > 我理解这种担忧，但我们没有足够的信息来猜测开发人员在使用类作为样式选择器时的意图。如果有其他选择我会很高兴。同时，请考虑[链接PR](https://github.com/unocss/unocss/pull/3294#issuecomment-1788292837)中的示例。
> 
> 如果使用unocss开发组件库，请编写一个按钮。例如：
> 
> ```js
> letstyle={
>       'primary'：'bg-blue'，
>       'primary-outline'：'bg-transparent'，
>       'primary-outline-active'：'bg-gray'，
> }
> ```
> 
> ```
> <buttonclass=”bg-blue bg-transparent bg-gray“</button>
> ```
> 
> 此时，有必要使bg-gray权重最高 如果能按书写顺序排序，使用起来会非常方便

@antfu May I ask if this view might be of some benefit to unocss, where style overrides are common in the case of component libraries?
