### ISSUE TITLE
Suppress %unocss-svelte-scoped.global% warning in svelte-scoped under certain scenarios.

### ISSUE THREAD

**Issue by unbiased-dev** [unocss/unocss#3295]
### UnoCSS version

0.57.1

### Describe the bug

When using unocss in sveltekit-scoped with a preset that doesn't need a global css (`presetIcons`) the warning gets annoying even tho everything works fine.

Warning in question
> [vite] [unocss] You have not setup the svelte-scoped global styles correctly. You must place '%unocss-svelte-scoped.global%' in your app.html file. You also need to have a transformPageChunk hook in your hooks.server.js file with: `html.replace('%unocss-svelte-scoped.global%', 'unocss_svelte_scoped_global_styles')`. You can see an example of the usage at https://github.com/unocss/unocss/tree/main/examples/sveltekit-scoped.

Yes, I can add the `%unocss-svelte-scoped.global%` and the appropriate `hooks` handler but:
a) it will pollute the hooks for no reason
b) it will pollute the `head` with an empty `style` for no reason

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-uhwn4x?file=src%2Froutes%2F%2Bpage.svelte

Just let the project run, verify the icon is on the page and the warning/error in the console.

### System Info

- Sveltekit
- svelte-scoped

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by henrikvilhelmberglund** [comment]
If you only use it for icons you can use the preprocessor style https://unocss.dev/integrations/svelte-scoped#svelte-preprocessor or just the normal Vite plugin https://unocss.dev/integrations/vite#sveltekit instead.

**Comment by unbiased-dev** [comment]
Thanks this does solve my problem.
Small caveat for those doing the same
If you move to the preprocessor version you need to inject the css reset manually
Just put your `import '@unocss/reset/tailwind.css';` in the `+layout.page` and not in the UnoCSS config.inject
