### ISSUE TITLE
unocss does not support dynamic variables

### ISSUE THREAD

**Issue by fslflame** [unocss/unocss#3297]
### UnoCSS version

0.56.1

### Describe the bug

![image](https://github.com/unocss/unocss/assets/101857530/00dcd87e-de62-43ae-b21b-030408c03634)
Variables like the one shown in the figure are not valid for styles and are not supported for all styles

### Reproduction

![image](https://github.com/unocss/unocss/assets/101857530/00dcd87e-de62-43ae-b21b-030408c03634)
Variables like the one shown in the figure are not valid for styles and are not supported for all styles

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by henrikvilhelmberglund** [comment]
You need to use a safelist: https://unocss.dev/guide/extracting#safelist
