### ISSUE TITLE
transformerAttributifyJsx 在React18+Webpack5下不能工作

### ISSUE THREAD

**Issue by O-Connects** [unocss/unocss#3299]
### UnoCSS version

0.57.1

### Describe the bug

控制台报错
Uncaught SyntaxError: missing ) after argument list (at index.js:454:6)

className 正常工作

### Reproduction

```
// uno.config.js
import { defineConfig } from "@unocss/webpack";
import presetUno from "@unocss/preset-uno";
import presetAttributify from "@unocss/preset-attributify";
import transformerAttributifyJsx from "@unocss/transformer-attributify-jsx";

export default defineConfig({
  presets: [presetUno(), presetAttributify()],
  transformers: [transformerAttributifyJsx()],
});


// App.jsx
import * as React from 'react';

export default function App() {
  return (
    <div flex>Hello</div>
  );
}

// webpack.config.js
const UnoCSS = require("@unocss/webpack").default;

module.exports = {
  ...
  plugins: [UnoCSS()],
  optimization: {
    realContentHash: true,
  },
};
```

### System Info

MacOS M1, Electron

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by O-Connects** [comment]
也试过 @unocss/transformer-attributify-jsx-babel
错误相同

**Comment by Jarvie789** [comment]
跟一个，同等环境下，这个不行
```
<div className='flex-[0_0_auto]'></div>
```
