### ISSUE TITLE
This Example not Work on Uno CSS but work on Tailwind

### ISSUE THREAD

**Issue by taymakz** [unocss/unocss#3300]
### UnoCSS version

5.7.1

### Describe the bug

None of theese examples work with unocss ( work with Tailwind )

https://codesandbox.io/p/github/lepikhinb/example-meilisearch-hover/master?file=%2Fsrc%2Fcomponents%2FBaseCard.vue%3A1%2C1-43%2C1

https://codesandbox.io/p/github/lepikhinb/example-nuxt-studio-gradient/master?file=%2Fsrc%2Fcomponents%2FBaseCard.vue%3A27%2C1-34%2C2

### Reproduction

https://uno-problem.vercel.app/
https://github.com/taymakz/uno-problem
### System Info

   "@antfu/eslint-config": "^1.1.0",
    "@nuxtjs/color-mode": "^3.3.0",
    "@unocss/eslint-config": "^0.56.5",
    "@unocss/nuxt": "^0.57.1",
    "@vite-pwa/nuxt": "^0.1.1",
    "@vueuse/nuxt": "^10.5.0",
    "aos": "^2.3.4",
    "eslint": "^8.52.0",
    "nuxt": "^3.8.0",

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by chu121su12** [comment]
I know reproduction is really appreciated, but please also describe what the examples are trying to achieve and what they cannot.

**Comment by taymakz** [comment]
> I know reproduction is really appreciated, but please also describe what the examples are trying to achieve and what they cannot.

the Color effect dosn't work on UnoCSS : ,

https://github.com/unocss/unocss/assets/71381670/7fa280e2-e53e-459f-9765-1c8021a29d0e


in Tailwind : 

https://github.com/unocss/unocss/assets/71381670/ab2c2213-1ee5-48ab-a7bf-3f89a64887a7

**Comment by sadeghbarati** [comment]
@chu121su12 

TailwindCSS preflight has a pre-defined variable called `--tw-content` which UnoCSS hasn't

```
::before, ::after {
    --tw-content: '';
}
```

[TailwindCSS Playground](https://play.tailwindcss.com/1l9xZKq2x4)

[UnoCSS Playground](https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIkAsEgPYDuUAtgLQAsUARgKYBmeATjQFxV4AuHeZADOgD4AUFCgBJAHZIADjRgcoAWRpQACnBrIaIqMGnNho0RLzV6TFTDwSONGzuAB6fTWFPwEYUNCRYiFBjYuIQkFGYMzGyc3HzhFixWNnYcpADaAOQAEjRwcHjpALqCOpIycgrKahpaDi5eRlAAdLQRNAA6Cda2NqRtqW1ZOXkDbQUsbObMUADeOg2wXcksUIO5%2BQDcc1AAvkJbzZPtUVw8pLzjLRYzWw3sJ8TLvNIAHpsNu6JOdd6OHl5CQA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDASSarID3fsMBVKtoAvqByNJScoADkFlRMkJCRgoLEoogy8pgW0GmyCoQqarDqABSS0jRZUABcoADaOtK1kUwWkIjhtJWRmhKg7tB8NZF0qJGggQC6XlM6kAAWfIgtAjVl0lEtbR3zi8uRQ6wkyNDqoIcofJjw6uCgCwBu4DRV58ismNDdOoFeTgYrdQa3mciH8lGKAEovI4fMZTIxLNY7JDocD-m4PKUgdJIEwPuAagBGAB0ACZUdImKh4EM5qZuJAqiAoJxifNgF91uMoToZoEIYIgA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4XyA)

**Comment by henrikvilhelmberglund** [comment]
Yes just adding `before:content-['']` (or `before:content-empty``) to the classes makes it work.

Related: https://github.com/unocss/unocss/issues/2924

**Comment by taymakz** [comment]
> Yes just adding `before:content-['']` (or `before:content-empty`) to the classes makes it work.
> 
> Related: #2924

Thanks Fixed,

**Comment by bekjon-me** [comment]
> Yes just adding `before:content-['']` (or `before:content-empty`) to the classes makes it work.
> 
> Related: #2924

Can you provide a code example, pleae
