### ISSUE TITLE
Can't render uno css in legacy chunks when working with @vitejs/plugin-legacy plugin

### ISSUE THREAD

**Issue by xxllxhdj** [unocss/unocss#3302]
### UnoCSS version

0.57.1

### Describe the bug

Just render #--unocss--{layer:__ALL__} refer to the follow reproduction.

<img width="655" alt="image" src="https://github.com/unocss/unocss/assets/12881488/62f816e6-f6ae-456b-ba1b-c29553f4a978">

### Reproduction

https://stackblitz.com/edit/vitejs-vite-pwbyj3?file=dist%2Fassets%2Findex-legacy-983bb6f9.js

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Jungzl** [comment]
Could someone reopen this and add `not stale` label
