### ISSUE TITLE
Custom colors aren't working in presetUno

### ISSUE THREAD

**Issue by moaali** [unocss/unocss#3309]
### UnoCSS version

0.57.2

### Describe the bug

Custom colors added to configs aren't working.

```
import extractorSvelte from "@unocss/extractor-svelte";
import transformerDirectives from "@unocss/transformer-directives";
import transformerVariantGroup from "@unocss/transformer-variant-group";
import { defineConfig, presetIcons, presetUno } from "unocss";

export default defineConfig({
  presets: [
    presetUno({
      theme: {
        colors: {
          cool: "#0000ff",
        },
      },
    }),
    presetIcons(),
  ],
  extractors: [extractorSvelte()],
  transformers: [transformerVariantGroup(), transformerDirectives()],
});
```

```
<!-- NOT WORKING -->
<h1 class="text-cool">Welcome to SvelteKit</h1>
```

### Reproduction

Here is a repo for reproduction https://github.com/moaali/unocss-custom-color

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by henrikvilhelmberglund** [comment]
You have a few issues in your config. 

- You should add `%unocss-svelte-scoped.global%` to your app.html above `%sveltekit.head%`.
- You should add a hooks.server.js file in /src with the following code:
```js
/** @type {import('@sveltejs/kit').Handle} */
export async function handle({ event, resolve }) {
  const response = await resolve(event, {
    transformPageChunk: ({ html }) => html.replace('%unocss-svelte-scoped.global%', 'unocss_svelte_scoped_global_styles'),
  })
  return response
}
```
- You should move the `theme` config to the same level as `presets` so it looks like this:
```js
presets: [
  theme: {
    colors: {
      cool: "#0000ff",
    },
  },
  presetUno(),
```
- You should remove `extractorSvelte` and the transformers since this is already handled by Svelte-scoped.

After doing all of that it should work.

It would be nice if trying to add a theme inside of a preset gave an error though.

**Comment by zyyv** [comment]
[presetUno has](https://unocss.dev/presets/uno#options) hasn't `theme` options. Refer to `theme` or `extendTheme` option in root configuration.
