### ISSUE TITLE
[Feature Request] Download the icons and fonts resource while buildilng

### ISSUE THREAD

**Issue by s3xysteak** [unocss/unocss#3318]
### Clear and concise description of the problem

Need an option to download the preset icons and web fonts used in the project while building because the usage environment may be an internal network environment.

### Suggested solution

i..dk :(

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by zyyv** [comment]
For icons, uno parse it and convert to base64 image.
If you are using web-fonts with `preset-web-fonts`, try to use this option https://unocss.dev/presets/web-fonts#inlineimports
, it will be download font source and inject uno output.

**Comment by s3xysteak** [comment]
> For icons, uno parse it and convert to base64 image. If you are using web-fonts with `preset-web-fonts`, try to use this option https://unocss.dev/presets/web-fonts#inlineimports , it will be download font source and inject uno output.

About the icons, I still do not get it. 
I am using `presetIcons` and `@iconify-json/material-symbols`. And it can be noticed that it post a request to api.iconify.design to get the icon, so I think it could not be used in an internal network environment and needed a way to download it while building.

**Comment by kedniko** [comment]
You can download the font:
1. go to https://icones.js.org
2. select the collection you want (i.e. material-symbols)
3. click on the hamburger menu on the top-right corner
4. download "iconfont"
5. import the font in your app

**Comment by s3xysteak** [comment]
This has finally been resolved. I realized that the icon is actually stored in `node_modules/@iconify-json/.../icons.json`, and the previous mentioned HTTP request was not from unocss, but from somewhere else.
