### ISSUE TITLE
support for separate values for `backgroundColor`, `borderColor`, and `textColor`

### ISSUE THREAD

**Issue by mammadataei** [unocss/unocss#3329]
### Clear and concise description of the problem

Tailwindcss theme already supports separate values for color-related properties like `backgroundColor`, `borderColor`, and `textColor`. I think it's missing in Unocss, and it is really helpful if you need to define different tokens for each property.

```typescript
theme: {
  // ...
  colors: {
    // ...
  },
  backgroundColors: {
    // ...
  },
  borderColors: {
    // ...
  },
  textColors: {
    // ...
  },
}
```
I know it's possible to extend the theme object, but overriding the rules to make it work isn't straightforward.

### Suggested solution

Define separate entries for `backgroundColors`, `borderColors`, and `textColors` in the `Theme` Object with a default value of `theme.colors`.

### Additional context

[Tailwindcss playground example](https://play.tailwindcss.com/xLT6Z9ILfi)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by henrikvilhelmberglund** [comment]
I don't really see how this should work. Can you give an example that uses the Tailwind playground?

**Comment by mammadataei** [comment]
@henrikvilhelmberglund [Check this example](https://play.tailwindcss.com/xLT6Z9ILfi)

**Comment by henrikvilhelmberglund** [comment]
> @henrikvilhelmberglund [Check this example](https://play.tailwindcss.com/xLT6Z9ILfi)

So something like this but merging `bg-bg-blue-500` into `bg-blue-500`?

https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIBmcCmAPKACwFokYAnHHAOyjABccBbJYmGx8qAKwFcl6YTAE82HHFwDmCAA7EALOgB8AKChRgAI1716Ae1rxkadJsnEzFuLxxE9ECQC5LL6zmIBWAAxeojPPTEAO6EDLaaeuQgEhaR0eTEkuQIwlARUTEATFAyeAo5opnKAMJwYDAA1lBMOMAA9Nq6BqpqGgCExMRQACqhSFAGtiB6OEjUAOT0UEGRVUhg1OxQAAaWSSlpcTGabstQCJRQ1HpT0ZgLOCBQnarqWjr6hogoGC7m66mE9k5vicmi3l86XisQyCR2Nk2YJyeXkBWIRSUADk9FABMJcEh6o1Hqp6uAIEogA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6hU4AGYJwAYUrw5AcwA0obnUjhEAQUQNY2AK6JYMgJ6btUPQEkmyyLZ16AqlVABfUDJpKTlAAclMqJkhIEMFBYlFEKVlMU2hE6TlCJRVYVQAKcUFQUEQAC3BOcAAuCSLi0GdoPkgawvr67FVWuvbi3FNq2t7egBEAUQAxfQ8AGQAVGpCAYgAGNZXMTBD1HuHQAFY1xdX1mRlt3fafHb3QVRpMK27b4vGp2YXQpYAmX7%2BLl4HI5fABsYPBAL210uvhuvWwfGkNGee36gzaLze03mx3WKyYTEht0OK2Of2%2BZyJvWht3ujxRtyxH2OAEY2eyqcMSccABx8-mc%2Bo06lw4rC4U0VJQGoAbRlISYpkgiCCtCl2wkDUoTWRoToqBCvgAuka4ZBSnxEIqBAzQorlarzZbrSFFqwSMhoKoSsQUHxMPBVOBQBaAG7gZHulCsTDQSHCuy6G2gGW7ROeKh5ACUoq07gMRkYZgs1mzufTiCcLgKMMgTFjgxZADpvrnikxUPBFqUjNwWiAoJwm%2BbgFSfDm6qbBOPBEA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmAvkA

**Comment by mammadataei** [comment]
@henrikvilhelmberglund Kinda. But I think having separate properties like `backgroundColors`, `borderColors`, and `textColors` is more flexible than a nested colors object. This way it's possible to override one of the properties while others use the `colors`.

**Comment by henrikvilhelmberglund** [comment]
The problem is that `theme: {background: colors{}} ` doesn't exist right now, the things that exist right now are more general things like `spacing`, `colors` and so on.

I don't really personally see when this would be that useful, the only thing I can think of is for theming but for that https://github.com/unpreset/unocss-preset-theme already exists.

**Comment by mammadataei** [comment]
Here's the theme interface from Tailwind: 
```typescript
interface ThemeConfig {
  // ...
  colors: ResolvableTo<RecursiveKeyValuePair>
  borderColor: ThemeConfig['colors']
  backgroundColor: ThemeConfig['colors']
  textColor: ThemeConfig['colors']
  // ...
}
```
It's not like :
```typescript
{
  background: colors{
  // ...
  }
}
```

If the `backgroundColors`, `borderColors`, and `textColors` do not exist in the configuration, it will use the `colors` as default; otherwise, it uses those keys for each property.

As I mentioned before, it is useful for implementing design systems when you need different tokens for each property

**Comment by mammadataei** [comment]
Both Tailwindcss and Windicss support this feature; but somehow, it's missing from Unocsss. I think it must be available at the very least in the wind preset.

**Comment by domisooo** [comment]
Hello, we also hope to add this new feature. Our team currently uses windicss, which uses extended background colors in dark and light modes. For example, `bg-primary` displays different colors in dark and light modes.

```scss
// dark
body[data-theme='dark'] {
  --bg-primary: #000;
}

// light
body[data-theme='light'] {
  --bg-primary: #fff;
}
```

```javascript
export default {
  theme: {
    extend: {
      backgroundColor: {
        primary: "var(--bg-primary)",
      },
    },
  },
};
```


```javascript react
<div className="bg-primary"></div>
```

**Comment by henrikvilhelmberglund** [comment]
> Hello, we also hope to add this new feature. Our team currently uses windicss, which uses extended background colors in dark and light modes. For example, `bg-primary` displays different colors in dark and light modes.
> 

For this there is https://github.com/unpreset/unocss-preset-theme

**Comment by domisooo** [comment]
> > Hello, we also hope to add this new feature. Our team currently uses windicss, which uses extended background colors in dark and light modes. For example, `bg-primary` displays different colors in dark and light modes.
> 
> For this there is https://github.com/unpreset/unocss-preset-theme

Thanks, but the semantics are not friendly, such as `bg-bg-primary` `text-text-error`, if it can support extended theme colors, `bg-primary` `text-error`

**Comment by henrikvilhelmberglund** [comment]
> Thanks, but the semantics are not friendly, such as `bg-bg-primary` `text-text-error`, if it can support extended theme colors, `bg-primary` `text-error`

My example in the playground above does not use `unocss-preset-theme` at all (and is completely unrelated to what you are asking for), what `unocss-preset-theme` means is that you can have a theme that is enabled by a class like "blue" or "dark" (or a media query) and then define the specific colors in the preset as blue: {} or dark: {} and so on. You can also do this with a loop or something eg. https://gist.github.com/henrikvilhelmberglund/4b27d4ef92b8dcec0bd52f62b3718213

I think this is a better solution for your particular problem because I don't see the Tailwind style utility color merging being implemented soon.

**Comment by chu121su12** [comment]
@domisooo This seemed like different usage entirely. Please open a new issue instead
