### ISSUE TITLE
Class don't get in build when there's a single class in component - SolidStart

### ISSUE THREAD

**Issue by Vexcited** [unocss/unocss#3336]
### UnoCSS version

0.57.4

### Describe the bug

In SolidStart, when writing

```tsx
<p class="text-sm">
  Hello World!
</p>
```

`text-sm` is not included in the build CSS.

---

The reason for this is how the code is bundled, see the output : 

```javascript
const _tmpl$ = /*#__PURE__*/_$template(`<p class=text-sm>Hello World!</p>`);
```

Quotes aren't added until a second class is here. For example...

```tsx
<p class="text-sm a">
  Hello World!
</p>
```

Gives

```javascript
const _tmpl$ = /*#__PURE__*/_$template(`<p class="text-sm a">Hello World!</p>`);
```

and here `text-sm` is in the built CSS.

### Reproduction

```tsx
<p class="text-sm">
  Hello World!
</p>
```

or write any component with a single class.

### System Info

Windows 10 22H2 (19045.3570) (64-bit)
Chrome Version 119.0.6045.124
`solid-start@0.3.10` with `solid-js@1.8.5`

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by untlsn** [comment]
Quick fix:
Change order of plugins inside vite (unocss before solid)
