### ISSUE TITLE
unocss className priority is inexact

### ISSUE THREAD

**Issue by lyandzao** [unocss/unocss#3338]
### UnoCSS version

0.57.3

### Describe the bug

I have a component ***Foo***, Its initial height is 200px
```typescript
export const Foo = ({className=''}:{className?:string}) => {
  return (
    <div className={`b-solid h-200px ${className}`}>Foo</div>
  )
}
```
When I used it externally and re-set the height to 100px, I expected 100px but unfortunately I got 200px
```typescript
import { Foo } from './Foo'

function App() {
  return (
    <div>
      <Foo className='h-100px' />
    </div>
  )
}

export default App
```
![image](https://github.com/unocss/unocss/assets/33866716/be356d46-0711-44b9-a16f-15d6479ef9cb)
One solution is to add for subsequent styles !important, but this is so weird
```typescript
import { Foo } from './Foo'

function App() {
  return (
    <div>
      <Foo className='!h-100px' />
    </div>
  )
}

export default App
```

### Reproduction

```typescript
export const Foo = ({className=''}:{className?:string}) => {
  return (
    <div className={`b-solid h-200px ${className}`}>Foo</div>
  )
}

function App() {
  return (
    <div>
      <Foo className='h-100px' />
    </div>
  )
}

```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
duplicate: #3293
