### ISSUE TITLE
preset里添加边框复合写法的支持

### ISSUE THREAD

**Issue by cunzaizhuyi** [unocss/unocss#3339]
### Clear and concise description of the problem

目前只支持边框单个属性设置，建议支持复合写法；

比如，对于border-bottom: 1px solid #ccc;
如果使用现有的class，只能写成class="b-b-1 b-b-solid b-b-#ccc"，比较麻烦（事实上，我经常因为这个原因而把边框的设置放到css里去写，而非直接在div上写class）。
建议可以简写成诸如：class="b-b-1px-solid-#ccc"的形式；

同理，对于border: 1px solid #ccc;
希望能简写成：class="b-1px-solid-#ccc"的形式；

### Suggested solution

因为不熟悉unocss项目的结构，可能还要涉及改文档，代码规范之类的问题，所以如果维护者觉得本提议可以支持，可以照以下代码帮忙实现一下。

```
// 抄自unocss
export const directionMap = {
  l: ['-left'],
  r: ['-right'],
  t: ['-top'],
  b: ['-bottom'],
  s: ['-inline-start'],
  e: ['-inline-end'],
  x: ['-left', '-right'],
  y: ['-top', '-bottom'],
  '': [''],
  bs: ['-block-start'],
  be: ['-block-end'],
  is: ['-inline-start'],
  ie: ['-inline-end'],
  block: ['-block-start', '-block-end'],
  inline: ['-inline-start', '-inline-end'],
};


rules: [
        [/^b-([rltbxy])-(\w+)-(\w+)-([#\w]+)$/, (match) => {
          const resultMap = {};
          directionMap[match[1]].forEach((direction) => {
            resultMap[`border${direction}`] = `${match[2]} ${match[3]} ${match[4]}`;
          });
          return resultMap;
        }],
        [/^b-(\w+)-(\w+)-([#\w]+)$/, match => ({
          border: `${match[1]} ${match[2]} ${match[3]}`,
        })],
      ],
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [ ] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Simon-He95** [comment]
First option:
https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIBmcCmAPKACwFokYAnHHAOyjABccBbJYmGx8qAKwFcl6YTAE82HHOXQA%2BAFBQowAEa969APa1Fa8iAnFFGAIwAHAiGSEcIKJRDStOiVC2q1TYAHplr6rM-gIKSA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6hU4AGYJwAYUrw5AcwA0obnUjhEAQUQNY2AK6JYMgJ6btUPQEkmyyLZ16AqlVABfUDJpKTlAAclMqJkhIEMFBYlFEKVlMU2hE6TlCJRVYVQAKcUFQUEQAC3BOcAAuCSLi0GdoPkgawvr67FVWuvbi3FNq2t7egBEAUQAxfQ8AGQAVGpCAYgAGNZXMTBD1HuHQAFY1xdX1mRlt3fafHb3QVRpMK27b4vGp2YXQpYAmX7%2BLl4HI5fABsYPBAL210uvhuvWwfGkNGee36gzaLze03mx3WKyYTEht0OK2Of2%2BZyJvWht3ujxRtyxH2OAEY2eyqcMSccABx8-mc%2Bo06lw4rC4U0VJQGoAbRlISYpkgiCCtCl2wkDUoTWRoToqBCvgAuka4ZBSnxEIqBAzQorlarzZbrSFFqwSMhoKoSsQUHxMPBVOBQBaAG7gZHulCsTDQSHCuy6G2gGW7ROeKh5ACUoq07gMRkYZgs1mzufTiCcLgKMMgTFjgxZADpvrnikxUPBFqUjNwWiAoJwm%2BbgFSfDm6qbBOPBEA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmAvkA

Second option: `b-b-[1px_dashed_red]`, Theoretically, this method should also be possible, but there are problems with my current attempts. I will open a PR later to fix this situation.

**Comment by muweigg** [comment]
This issue has been puzzling me as well.
Using the latest version 0.58.3, writing "b-[1px_solid_#fff]" will output as "border-color: 1px solid #fff". Why is it "border-color"?

**Comment by studyforhuihui** [comment]
还有个小问题，[&>:first-child]:(border='1px solid black') ，像是这样写并不会起效果
