### ISSUE TITLE
Replace CSS Variables with Static Values

### ISSUE THREAD

**Issue by shellscape** [unocss/unocss#3341]
### Clear and concise description of the problem

I'm using unocss to author emails. One of the limitations with email html is that CSS variables are not consistently supported. For example, Gmail will completely strip them. I'd like unocss (or a transform) to replace the CSS variables with their static values. 

### Suggested solution

A transform to tackle this would be nice. I attempted to leverage some of the code found here https://github.com/unocss/unocss/blob/main/packages/vscode/src/utils.ts#L129 quickly to do that, but the regex used by `getCssVariables` doesn't handle empty variable declarations or multiline CSS very well (it chokes on the preflight as well).

### Alternative

Packages like [`juice`](https://github.com/Automattic/juice) have this capability, but they use rather slow parsers in `cheerio` and `css` comparatively. There's an obscure plugin for PostCSS to do this, but it was written for a much older version, and again I'd rather not use a different parser because it defeats the purpose of using unocss.

_Update:_ I've just happened across this newer plugin for PostCSS which may give inspiration https://www.npmjs.com/package/postcss-css-variables

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by chu121su12** [comment]
I think this is better done with external/postcss plugin that understands the whole css context thus can properly replace var()s with their replacements.

**Comment by shellscape** [comment]
And yet one of the selling points of uno is that it doesn't use postcss. I think you may have missed that above.

**Comment by shellscape** [comment]
Ping

**Comment by beedell-roke** [comment]
> https://github.com/unocss/unocss/issues/3341#issuecomment-1899845844

@stale, you're a useless pain. Per [`stackoverflow.com/q/59544716`][1], this remains desired by many, and https://github.com/parcel-bundler/lightningcss/issues/69#issuecomment-1264325390 has discussed the potential advantages and disadvantages well.

[1]: https://stackoverflow.com/q/59544716/9731176
