### ISSUE TITLE
🐞: `animate-*` doesn't work with `@apply` directive. `@keyframes` generated is scoped

### ISSUE THREAD

**Issue by xsjcTony** [unocss/unocss#3344]
### UnoCSS version

latest

### Describe the bug

`@keyframes` generated by `animate-*` via `@apply` directive is scoped, hence it has no effect. The `@keyframes` should always be generated outside the selector. 
Refer to reproduction.

### Reproduction

https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIDmAnMIoAOiMApgLRgAuJAtkmaQHbXZQAWZSM2JJjU1AB6UyADkFx0APgBQUKKEixEKDNSSUoNAEZkATAAZpAAQQEiAT2AB6cBFnzF0eMjToEjMDQTVOBMIzSAJKMcAEkNnaykZCyQA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAKq4IQuGwCGuOlmggMUACLBaAY14A3ekgC%2BcLFAgg4Aci6StdOpaRIMAD0ix02WVwA28TDj4RCTApAAUyMK0DDB0AFxwANpUUaIwEhBhAJRUALrScgpKUCpQ8UkpMlDyisqqGtp69Nl5RjlAA&css=HQFwpgziAEDeBQ1oAECGAHdAbAntVAdgJYC2q4AtAEYD2ArgQMZgDc8AvkA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g

### System Info

Not relevant

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by henrikvilhelmberglund** [comment]
It works if you use `animate-spin` in the `@apply`as well so it seems like a safelist (class detection) issue. Also works if `animate-bounce` is added to `safelist`.

**Comment by xsjcTony** [comment]
Yeah it would be doable via `safelist`, but I don't think it's ideal. If you have tons of `animate-*` in `@apply`, it doesn't make sense to maintain another `safelist` as they might be out of sync. `@apply` should behaves the same as inline classnames, where `@keyframes` is a special case that it should be placed outside the selector.
