### ISSUE TITLE
the version 0.57.5 of UnoCSS for VS Code doesn't work

### ISSUE THREAD

**Issue by MCheery** [unocss/unocss#3347]
### UnoCSS version

0.57.5

### Describe the bug

It has no prompt in version 0.57.5 and behaves as if it is not installed. After I tried rolling it back to version 0.57.4, it behaved normally and could provide completion prompts. I'm sure my `uno.config.ts` file is in the correct location, and the style can be displayed correctly in the browser. Has anyone encountered the problem as me?

### Reproduction

the version 0.57.5 of UnoCSS for VS Code does not provide color preview
```html
<div class="bg-black"></div>
```

```ts
// uno.config.ts
import { defineConfig } from 'unocss'
export default defineConfig({})
```

### System Info

System: Windows 11
Framework: Vite & Solidjs
IDE: VS Code

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
Hi, @MCheery 
There is no problem on my side. You can try uninstalling and reinstalling. If you still have problems, can you provide a reproducible template so that I can copy it locally and reproduce it?

**Comment by urbanscratcher** [comment]
Hi, same thing happened to me. I also had to downgrade Vite from 5.0.0 to 4.5.0 (Vite & React / Mac). IntelliSense only was not working.

**Comment by littledenny** [comment]
Seem, I installed the lower version (0.75.4), It is normal now

**Comment by Simon-He95** [comment]
it will be fixed in the next version

**Comment by jods4** [comment]
Is this really fixed?

With 0.58 I'm still having very similar issues.

I have a file `uno.config.js` that is extremely basic, just the wind preset.
Looking at UnoCSS Output pane in VS Code, it seems to pick up the configuration file alright.
Everything is working fine in browser.

I get a lot of completions, but some are missing.
Notably, as the OP here, no colors are proposed on `bg-`.
Strangely, if I fully type a color like `bg-red`, it's fully recognized: it has the underline in code, the little red color dot, and the tooltip showing the matching CSS code. Same for `bg-yellow` or `bg-yellow-200`.
But if I start typing `bg-r|` nothing is proposed in completions.

Colors are obvious missing suggestions but I noticed a few others. For example `bg-right` is not proposed either in completions (but is still highlighted in IDE and works in browser).

**Comment by jods4** [comment]
Or maybe it's not the same problem after all. Reverting extension to `0.57.4` does not fix.
I'll add the strangely colors work in other contexts. E.g. `text-y|` suggests `text-yellow`, yet `bg-y|` doesn't suggests `bg-yellow`.

**Comment by jods4** [comment]
This problem is easy to observe in UnoCSS interactive documentation as well, I've opened https://github.com/unocss/unocss/issues/3450
