### ISSUE TITLE
vscode extension No more Underline after >.57.3

### ISSUE THREAD

**Issue by jojojojojoj5564656465465** [unocss/unocss#3350]
### UnoCSS version

unocss@0.57.5

### Describe the bug

I'd like to have the highlighting under the unocss classes as before, but since updating the extension it doesn't work any more, I don't have the highlighting under the classes.

I've found the solution, I'll have to go back to version 0.57.3 of the extension to fix the problem.

### Reproduction

no link

### System Info

arch manjaro linux
vscode

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
duplicate: #3347, Will be fixed in next version
