### ISSUE TITLE
Uno Css Vs Code Extension doesn't work with Astro.

### ISSUE THREAD

**Issue by anasmohammed361** [unocss/unocss#3352]
### UnoCSS version

v0.57.5

### Describe the bug

I am using astro with Uno css , i do have a seperate `uno.config.ts` file.

```
// uno.config.ts
import { defineConfig, presetUno, presetWebFonts,presetIcons } from "unocss";

export default defineConfig({
  presets: [
    presetUno({
      arbitraryVariants:true
    }),
    presetWebFonts({
      fonts: {
        inter: "Inter",
        poppins: "Poppins",
      },
    }),
    presetIcons()
  ],
  theme:{
    colors:{
      'primary':'#64ffda',
      'background':'#0a192f'
    }
  }
});

```
i use `pnpm` . when i opened up my extension settings it said , unable to find module `unocss` . But once i dropped my extension version everything seems to work fine. 

### Reproduction

I just followed the docs for astro .

```
 "dependencies": {
    "@astrojs/check": "^0.3.1",
    "astro": "^3.5.4",
    "typescript": "^5.2.2"
  },
  "devDependencies": {
    "@iconify/json": "^2.2.143",
    "@unocss/reset": "^0.57.5",
    "unocss": "^0.57.4"
  }

```

Here are my versions , if you are interested

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
duplicate：#3347
