### ISSUE TITLE
Quasar (Vite) | Error on startup: "Hook is not a function"

### ISSUE THREAD

**Issue by xSavior-of-God** [unocss/unocss#3357]
### UnoCSS version

v0.57.6

### Describe the bug

Hello,
I have a problem with Unocss and Quasar, the Unocss plugins gives me and error related to the hook...

When starting the dev server ('quasar dev') this error appears.

![image](https://github.com/unocss/unocss/assets/66216419/c0b5b7a8-5e3f-42ee-9630-cd36f5ae1269)

After various tests I discovered that it's fault of the UnoCSS plugin which returns "undefined" instead of the "transform()" function, the error is caused by the "resolveHtmlTransforms" function that require the function "transform" inside the "transformIndexHtml" if is an object or just transformIndexHtml as function.

```javascript
...node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:36775:27

function resolveHtmlTransforms(plugins) {
    const preHooks = [];
    const postHooks = [];
    for (const plugin of plugins) {
        const hook = plugin.transformIndexHtml;
        if (hook) {
            if (typeof hook === 'function') {
                postHooks.push(hook);
            }
            else if (hook.enforce === 'pre') {
                preHooks.push(hook.transform);
            }
            else {
                postHooks.push(hook.transform);
            }
        }
    }
    return [preHooks, postHooks];
}
async function applyHtmlTransforms(html, hooks, ctx) {
    const headTags = [];
    const headPrependTags = [];
    const bodyTags = [];
    const bodyPrependTags = [];
    for (const hook of hooks) {
        const res = await hook(html, ctx);
        if (!res) {
            continue;
        }
```

Currently I did a work around for my project... and it works now, but this for sure is not the correct way to fix this bug/error and idk how many other unknown issues it can cause...
```javascript
...quasar.config.js

      // extendViteConf (viteConf) {},
      extendViteConf(config) {
        let _UnoCSS = UnoCSS.default({
          onlyGlobal: true,
          presets: [
            presetUno(),
            presetAttributify(),
            presetIcons({
              scale: 1.2,
              cdn: 'https://esm.sh/',
            }),
          ],
        });
        for(let plugin of _UnoCSS) {
          if(plugin && plugin.transformIndexHtml) {
            plugin.transformIndexHtml.enforce = 'pre';
            plugin.transformIndexHtml.transform = function(){};
          }
        }
        config.plugins.push(..._UnoCSS);
      },
```

### Reproduction

To reproduce the problem, just run the official UnoCSS with Quasar example on GitHub via Stackblitz.

[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz_small.svg)](https://stackblitz.com/fork/github/unocss/unocss/tree/main/examples/quasar)

### System Info

**NodeJS:** v18.18.0
**NPM:** v9.4.2
**System:** Windows 10/11
**Browser:** Edge & Chrome
**Framework:** Quasar CLI (with Vite)
**Quasar:** v2.14.0
**Vue:** v3.3.8

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Yooye** [comment]
npm install -D unocss@0.56.1      
应该是unocss版本与vite的版本不兼容导致的，我用vite3搭建的项目，使用上面的命令将版本后，可以恢复正常

**Comment by xSavior-of-God** [comment]
> npm install -D unocss@0.56.1 我也遇到了这个问题，我用vite3搭建的项目，使用上面的命令降版本后，可以恢复正常 下面是我项目依赖的版本信息：
> 
> ```
> {
>   "name": "vuets-admin-2304",
>   "private": true,
>   "version": "0.0.0",
>   "type": "module",
>   "scripts": {
>     "dev": "vite",
>     "build": "vue-tsc && vite build",
>     "preview": "vite preview"
>   },
>   "dependencies": {
>     "element-plus": "^2.4.2",
>     "normalize.css": "^8.0.1",
>     "reset-css": "^5.0.2",
>     "vue": "^3.2.41"
>   },
>   "devDependencies": {
>     "@vitejs/plugin-vue": "^3.2.0",
>     "typescript": "^4.6.4",
>     "unocss": "^0.56.1",
>     "unplugin-auto-import": "^0.16.7",
>     "unplugin-vue-components": "^0.25.2",
>     "vite": "^3.2.3",
>     "vue-tsc": "^1.0.9"
>   }
> }
> ```
Thanks for the comment... the problem starts from version `0.57.2`, so at the moment the latest working version with (Quasar) Vite is `0.57.1`

`npm install -D unocss@0.57.1`
