### ISSUE TITLE
`group` and `peer` selectors are broken when prefixes are used

### ISSUE THREAD

**Issue by iivvaannxx** [unocss/unocss#3360]
### UnoCSS version

^0.57.6

### Describe the bug

While I was playing with both `group` and `peer` classes I noticed that they are broken if used inside a `class` but not if used with `presetAttributify` and `presetUno` with `attributifyPseudo`. Also if using attributify prefixes, neither do work.

You can try the [playground link](https://uno.antfu.me/play/?html=DwEwlgbgBAxgFmANiATgUwHYF4BEAjAexRDRSgFsBaADigAdKAWKPAc0oHcEAXNHAPgBQUKKEixEAQwDO03KxQEArnQHCRouAGYovAB7dKAJj2IoAMwIZD5NOCXkKeJvwCq0sBlYSZ04AHptIQ1ROigFZQY4AghSAC42SnQQfgAJNEREAgC6YNF-cAghdTFoCJU8kWBtXTQDY1MLKxs7MAcnF3dPb0lubhQwPCVeAKD1KrDyqJj4xOS0jKycvIDCoVXIISA&config=JYWwDg9gTgLgBAbzmKBTAzqmBBGMrABGArjMAGYCeANMmpjAKoB2EtAJqucM6gMIRm3AOZwAvnHJQIIOAHJirAMbp0cgFDrUAD0iw4ncgENiAG3iGe-QSIAUCdXDoYs6AFxwA2o6fOGufCJSCkpbAEpqHycUFyZWeyjfIzwCEjIqAAVMYnYID3xiVESxMJ8AXXUSoA&options=N4IgzgLgTglgxhEAuaBXApgXyA) commented by @chu121su12 in [an old PR](https://github.com/unocss/unocss/issues/655#issuecomment-1052934514) where the same issue happened, but inverted (working in `class` and not in `attribute`). You'll notice that the hover works on the second group (attributify mode) but not in the first (class mode).

I will also link a reproduction below of the same example, but with prefixes (when used, attributify does not work either).

### Reproduction

[Link to the playground](https://uno.antfu.me/play/?html=DwEwlgbgBArgdgewLQGMAWYA2IBOBTOAXgCIAjBHEPHKAWyQA4oAHJAFilIHMkB3DAC55iAPgBQUKKEhQUmAIYBnRSS44EMZlFETJUtAGYoQgB4CkAJhOYoAMwRxztPOBi06pdiICqisHC5ZBWVgAHpDcT0pLTUNVjQECGoALm4kfBARAAk8TEwEMOZIqVDwCHFdaWh4ZFjNYslgQ2M8M0trOwcnFzA3Dy9ff0DmfFswExcoeQEBHDBSGCEwiN1GmPVNJASknFSeDOzc-MLisLKKxrKoOqLV-SNTcysbe0ckZ1d3Wk82Hz8AqYzOYLJbhAwNaLXDbxRIpNIHHJ5AqhW6NUqQYpiM4YoA&config=JYWwDg9gTgLgBAbzmKBTAzqmBBGMrABGArjMAGYCeANMmpjAKoB2EtAJqucM6gMIRm3AOZwAvnHJQIIOAHJirAMbp0cgFDrUAD0iw4ncgENiAG3iGe-QSIAUCdXDoYs6AFxwA2o6fOGufCJSCkp7TV9fFC5gbQ8FVgBaOWpwiLgAenS4FiUZEFRmeBgAC2B0OCNmdjgS1BrSqGrCUwglAGs4AHdgU1M4VnhO6DafCMznbm1UdgB5ZlNKD3xiVFHfNbEAShSIqIYWCDC0irwCEjIqAAVMYnYIJagVjc2fAF11LaA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgzgLgTglgxhEAuaBXApgXyA)

### System Info

Linux, Brave, Astro

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by henrikvilhelmberglund** [comment]
It seems like `attributifyPseudo` is mutually exclusive and you can't use it with `class=""`. (I have no idea, don't really use attributify)

For the last box the syntax is incorrect, it should be `<p class='group-data-[state=active]:bg-red'>Hello</p>`

**Comment by iivvaannxx** [comment]
Mm, I'll wait before closing the issue, may be it was expected behaviour after all. 
Thanks for the catch on the syntax! My bad, let me fix the issue title and examples.

**Comment by chu121su12** [comment]
> You can try the [playground link](https://uno.antfu.me/play/?html=DwEwlgbgBAxgFmANiATgUwHYF4BEAjAexRDRSgFsBaADigAdKAWKPAc0oHcEAXNHAPgBQUKKEixEAQwDO03KxQEArnQHCRouAGYovAB7dKAJj2IoAMwIZD5NOCXkKeJvwCq0sBlYSZ04AHptIQ1ROigFZQY4AghSAC42SnQQfgAJNEREAgC6YNF-cAghdTFoCJU8kWBtXTQDY1MLKxs7MAcnF3dPb0lubhQwPCVeAKD1KrDyqJj4xOS0jKycvIDCoVXIISA&config=JYWwDg9gTgLgBAbzmKBTAzqmBBGMrABGArjMAGYCeANMmpjAKoB2EtAJqucM6gMIRm3AOZwAvnHJQIIOAHJirAMbp0cgFDrUAD0iw4ncgENiAG3iGe-QSIAUCdXDoYs6AFxwA2o6fOGufCJSCkpbAEpqHycUFyZWeyjfIzwCEjIqAAVMYnYID3xiVESxMJ8AXXUSoA&options=N4IgzgLgTglgxhEAuaBXApgXyA)

Let me understand this first. Isn't this works as intended? Did I miss something? The `attributifyPseudo` is standalone toggle that switch between parent generation to output either data or class, so it is currently an exclusive behavior (since rule cannot output > 1 result); even without needing `presetAttributify`. 

https://github.com/unocss/unocss/blob/69c1420b5a058ee5cd923765378e42bdd95ff774/packages/preset-mini/src/_variants/pseudo.ts#L293-L300

Which means the issue is only when the prefix option is enabled? (as in title & reproduction link)

**Comment by iivvaannxx** [comment]
I wasn't expecting that to be the default behaviour, thus the issue. Now I went back to the docs and noticed the `instead` part.
> Generate pseudo selector as [group=""] instead of .group.

I was used to combine `class` and `attributes` for the majority of my styles and I expected the same for this special pseudo-classes, my apologies. Also, is there a specific reason they are mutually exclusive? Why not having an opt-in option to do both?

However, as you said, the issue can remain active as it stops working if you want to use prefixes.
