### ISSUE TITLE
grid-area不起作用

### ISSUE THREAD

**Issue by geeksmy** [unocss/unocss#3369]
### UnoCSS version

*

### Describe the bug

```html
<header class="grid-area-header">This is my lovely blog</header>
无法对生成
.grid-area-header {
    grid-area: header;
}
```

### Reproduction

```html
<header class="grid-area-header">This is my lovely blog</header>
无法对生成
.grid-area-header {
    grid-area: header;
}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
We will try our best to be consistent with tailwind. If tailwind does not support it, there are no plans to support it unless it is a feature that many people specifically need.

https://tailwindcss.com/docs/grid-auto-rows
