### ISSUE TITLE
transformerDirectives is not working for animations

### ISSUE THREAD

**Issue by samadadi** [unocss/unocss#3379]
### UnoCSS version

0.57.7

### Describe the bug

`transformerDirectives` is not working for animations.

### Reproduction

[Playground](https://unocss.dev/play/?html=DwEwlgbgBAFgtAMwK4BsVQC4FMAeG4DGWAdtgE5QIq5QDOW1B%2BxA9sVlAIZoBcGZnYrTAYwbOABYADFIB8AKChRQkKAFtOCpUpXQCKTrVoBeAETZaGU5lz4ArDnQIA7gEYZsgKqsAwgGU-YAB6cAgtbV0oFgAHAGYpGzw4FABzSmd4hLVXWQAVGA4wIQxBDCjiOBAsDWIQKABBDBY1MAIofz8oEhSirAA6YNDwnVD1ACZKahwoACskSzAEAE9CEnJE-DHHKLiEmBYILDIzGIAOKVNhiM5FbTuwQk4yACNxFBYUljgejBgkZ9udyU2CSRQKZBEgKBMDIWAQZhgGAw0VoPCCQR%2Bf2efQIzSCSFYBCM%2BMJRlMULuJTIKSwGDMAH1ngZiABrclAqCyYKaKGDSDhPlheSChSRTjPWgsFBIbBQV5I5pwOxQCEpRFwBLUBD4BIg-BEUhHHbxdKZcLiKo1OoAdqgRUspSgtuQaCWUAI8yaLQAXuLqMKQvz5EA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDASSarID3fsMBVKl4MmPCQcnyc4DQAIrB0LLAAblDaAL6gcjSUnKAA5BZUTJCQOYKCxKKIMvKYFtCVsgqEKmqw6gAUktKIABbgEQBcEjrSwVyY1qqDndIzANbgthmYEZBTwzPSlNzg8IMABtMbGxlZQ0fnoFuYTLCItoMADADc6xegkEyYeI8AdACsLze0hSryOiEoZyBm2411u91AAEZAVD3p9vojkW8QVi9l4Nik8aACTpidIaLUoIMANpUnJMCyQcGcWgUnKaCSgdzQPiDHJ0VA5IkAXSFXkg3T4iHpAjWGzpDKZyHFkulOV5rBIyGg6lAGpQfGC6nAoAlSRo-T1yFYXzZJMCNGCoXCkVWoCpQRCYRoEWisXA8SSkDaAEpRTonAYZW71hG-FQQ4TY8ZTIxLNY7AmYz5EG4PB1QR8vuBBgifgAmQnSJioXa5bqmbirEBQTg-cXAW344NeMMpYOCIA&css=CYSwbgdALgpgzlABAbwFCMQegFSIAICGADkQDYCeiBAdiALYGwC0A9kTNVbQ8wMYsBXalCYhqAMzEhYXeoxhNgAgE6MQLakwCMcANyJsmdPmJlKywdWAxgiAEYBzJsptMAzAAYPsngrYcfeSZ%2BIRExSVpYXVQAXyA&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmANONPMmgMICucYSqtAym-ocSQL5A)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
You need to add them to the safelist
[playground](https://unocss.dev/play/?html=DwEwlgbgBAFgtAMwK4BsVQC4FMAeG4DGWAdtgE5QIq5QDOW1B%2BxA9sVlAIZoBcGZnYrTAYwbOABYADFIB8AKChRQkKAFtOCpUpXQCKTrVoBeAETZaGU5lz4ArDnQIA7gEYZsgKqsAwgGU-YAB6cAgtbV0oFgAHAGYpGzw4FABzSmd4hLVXWQAVGA4wIQxBDCjiOBAsDWIQKABBDBY1MAIofz8oEhSirAA6YNDwnVD1ACZKahwoACskSzAEAE9CEnJE-DHHKLiEmBYILDIzGIAOKVNhiM5FbTuwQk4yACNxFBYUljgejBgkZ9udyU2CSRQKZBEgKBMDIWAQZhgGAw0VoPCCQR%2Bf2efQIzSCSFYBCM%2BMJRlMULuJTIKSwGDMAH1ngZiABrclAqCyYKaKGDSDhPlheSChSRTjPWgsFBIbBQV5I5pwOxQCEpRFwBLUBD4BIg-BEUhHHbxdKZcLiKo1OoAdqgRUspSgtuQaCWUAI8yaLQAXuLqMKQvz5EA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDASSarID3fsMBVKl4MmPCQcnyc4DQAIrB0LLAAblDaAL6gcjSUnKAA5BZUTJCQOYKCxKKIMvKYFtCVsgqEKmqw6gAUktKIABbgEQBcEjrSwVyY1qqDndIzANbgthmYEZBTwzPSlNzg8IMABtMbGxlZQ0fnoFuYTLCItoMADADc6xegkEyYeI8AdACsLze0hSryOiEoZyBm2411u91AAEZAVD3p9vojkW8QVi9l4Nik8aACTpidIaLUoIMANpUnJMCyQcGcWgUnKaCSgdzQPiDHJ0VA5IkAXSFXkg3T4iHpAjWGzpDKZyHFkulOV5rBIyGg6lAGpQfGC6nAoAlSRo-T1yFYXzZJLFmDk4DgjP6tNGnHG%2BC2OzZOXdnuQ7nyKAQjVu4Byop0QRCYRoERoq1AVJjoXCkRicWsSUgbQAlFHHD4Zcn1k4DIh-JR84Ty4YTGZLNY7DWy8W3B4OqCPl9wIMET8AEyE6RMVC7XLdUzcVYgKCcH7i4C2-F5rxRlJ5wRAA&css=CYSwbgdALgpgzlABAbwFCMQegFSIAICGADkQDYCeiBAdiALYGwC0A9kTNVbQ8wMYsBXalCYhqAMzEhYXeoxhNgAgE6MQLakwCMcANyJsmdPmJlKywdWAxgiAEYBzJsptMAzAAYPsngrYcfeSZ%2BIRExSVpYXVQAXyA&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmANONPMmgMICucYSqtAym-ocSQL5A)

**Comment by zyyv** [comment]
Bug of transformerDirectives. Duplicate of #3344.
