### ISSUE TITLE
UnoCSS runtime disable recalculating style not working in react

### ISSUE THREAD

**Issue by ThimoDEV** [unocss/unocss#3389]
### UnoCSS version

UnoCSS runtime cdn

### Describe the bug

I want to disable the recalculating style feature because it fires in combination with Reactflow and react three fiber. 

As far as I could see in issues and docs this is the code that should do that: 

`useEffect(() => {
    const unoRuntime = window.__unocss_runtime;
    console.log(appMode);
    unoRuntime?.toggleObserver(false);
  }, []);`
  
  I run this on mount, but I keep seeing the recalculating style running. Is this the proper way to toggle the recalculating style feature of unocss?
  

### Reproduction

- On the way, I'll try to reproduce it in a simple environment. It seems like either I do something wrong to trigger the toggleObserver or that function doesnt always disable the unocss style calculation

### System Info

Windows
Chrome
React vite

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by chu121su12** [comment]
How about pausing the runtime at creation time:

https://github.com/unocss/unocss/blob/130943e802ec36f3001222115dd0e8905a0654b5/packages/runtime/src/index.ts#L47-L50
