### ISSUE TITLE
Variant Group Transformer not working with CLI

### ISSUE THREAD

**Issue by steakscience** [unocss/unocss#3398]
### UnoCSS version

0.57.7

### Describe the bug

According to [this](https://github.com/unocss/unocss/pull/1592), transformers should work with CLI

However, I can't seem to get variant groups working. Is there something special I need to do?

### Reproduction

Something like [this](https://unocss.dev/play/?html=DwEwlgbgBADgTgewM4FNYFoAcUAuKAeO6ARgDYCGAxgNZQAWCEKcAXABR6HpwojoCsABkFQArgDsQzUmHEoAlAD4AUFCjAYimOTjkA5rph1gAek3LT4CCqA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcEWWwCGuOlmggMUAGrr2mmAHEoELmEoBfOFksg4Aci4qJdOi6RIMAD0hYdGx1LgAbeEwcfCISYFIACmRUKAj6AC44AG0qVGyXCS46GAgQAFo08IwXckQ4KXDoLJdaNBc4WwBdKi7ZOgALaBgimDoslNRXIpKy8sHh0ZcWmACYcvDSOFX-dehNUgw4IYA3fQyd9dX1cJ9UW1kRBXGcvLlRJRVEgEpZYXlGCw2JweHx%2BD8-u8FJJpMk3qg6BIbhgsgBGAB0ACZIagJGhcC0BqwwOMAPSk%2BggdGDUl3Ka2X69NRQTTaXT6F65KbbFlaHRQPSGYzAUwWKxgCFMpAMpBAA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmAvkA) wouldn't work when using CLI

### System Info

- Next.js 13
- UnoCSS CLI

Running CLI like this:
```
"scripts": {
    "dev": "concurrently \"next dev\" \"npm run dev:css\"",
    "build": "npm run build:css && next build",
    "dev:css": "unocss -c uno.config.ts -o styles/uno.css -w app/**",
    "build:css": "unocss -c uno.config.ts -o styles/uno.css app/**"
  },
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by steakscience** [comment]
After adding the `--write-transformed` flag, it does work, even without adding transformers in the UnoCSS config file.

Not sure if that is the intended behavior.

**Comment by apkrieg** [comment]
I'm running into this same issue. I don't want something like `class="md:(mx-auto flex-col)"` exploded to `class="md:mx-auto md:flex-col"` in my source, but the only way I can get variant groups working atm is by using `--write-transformed`.

I thought the point was to reduce cognitive load and keep things clean, this doesn't do that at all.

**Comment by chioio** [comment]
Same problem.
