### ISSUE TITLE
attributify did not generate css in specific case.

### ISSUE THREAD

**Issue by Eden-Sun** [unocss/unocss#3415]
### UnoCSS version

v0.58.0

### Describe the bug

In case using arrow function in multi-line `v-for` preset-attributify does not work whlie class works
It works well in vite dev but fails on production build.

### Reproduction

a simple repo [here](https://unocss.dev/play/?html=MYQwzgpgBAjAdFEAXJAnAlgIwK5PQMwE8p0wp90A7aAd3SQAsoBbbAGzwFo2roA3TvgD2qAFAAeACbo%2BUAcNQBeAEQAKUVDkAaEqICUUIfigBtAAwBdZaIacYZgA4APUQHoAfKNCQoAJgTIaFi4BMSk5LxQdIxygiJR9EwgqKhCNOTYlMB4QpQS0rLyIiqqfDroBkamlnDMIA6qqgaK7rB6ylC2vo5OUB6iooEYOHhE5CDobAkxyanp%2BJnZ6Ln5MrEKJRqa2rqalcbmFrX1jc2tMO1btgDMPW6eQA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDASSarID3fsMBVKtoAvqByNJScoADkFlRMkJCRgoLEoogy8pgW0GmyCoQqarDqABSS0jRZUABcoADaOtK1kUwWkIjhtJWRmhKg7tB8NZF0qJGggQC6XlM6kAAWfIgtAjVl0lEtbR3zi8uRQ6wkyNDqoIcofJjw6uCgCwBu4DRV58ismNDdOoFeTgYrdQa3mciH8lGKAEovI4fMZTIxLNY7JDocD-m4PKUgdJIEwPuAagBGAB0ACZUdImKh4EM5qZuJAqiAoJxifNgF91uMoToZoEIYIgA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmAvkA)

### System Info

vue3 + vite

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by carina-akaia** [comment]
Same issue here, but I use React and Attributify doesn't work for me in production build at all

**Comment by chu121su12** [comment]
Seems to be bug with the extractor. Workaround I could find is to place utilities [before the arrow fns](https://unocss.dev/play/?html=MYQwzgpgBAjAdFEAXJAnAlgIwK5PQMwE8p0wp90A7aAd3SQAsoBbbAGzwFo2roA3TvgD2qAFAAeACbo%2BUAcNQBeAEQAKUVDkAaEqICUUIfigBtAAwBdZaIacYZgA4APUQHoAfKNCQoAJgTIaFi4BMSk5LxQdIxygiJR9EwgqKhCNOTYlMB4QpQS0rLyIiqqfDroBkamlnDMIA6qqgaK7rB6ylC2vo5OUB6iooEYOHhE5CDobAkxyanp%2BJnZ6Ln5Mp2cACw9sQolGpraupqVxuYWtfWNza0w7fu2AMw9bp5AA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDASSarID3fsMBVKtoAvqByNJScoADkFlRMkJCRgoLEoogy8pgW0GmyCoQqarDqABSS0jRZUABcoADaOtK1kUwWkIjhtJWRmhKg7tB8NZF0qJGggQC6XlM6kAAWfIgtAjVl0lEtbR3zi8uRQ6wkyNDqoIcofJjw6uCgCwBu4DRV58ismNDdOoFeTgYrdQa3mciH8lGKAEovI4fMZTIxLNY7JDocD-m4PKUgdJIEwPuAagBGAB0ACZUdImKh4EM5qZuJAqiAoJxifNgF91uMoToZoEIYIgA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmAvkA). Also not yet tested with production build.
