### ISSUE TITLE
column-gap and row-gap shorthand naming

### ISSUE THREAD

**Issue by yheuhtozr** [unocss/unocss#3416]
### UnoCSS version

0.58.0

### Describe the bug

Currently, `column-gap` and `row-gap` are output from `gap-x-*` and `gap-y-*` respectively, but if I understand correctly, it looks like an inconsistent behavior.

`column-gap` and `row-gap` are used in multi-column, flex, or grid layouts, thus always tied with logical directions. Other rules as far as I found in the repo with `[xy]` all compile to `-x`/`-y` or `-left|right`/`-top|bottom`, leaving this one as exception.

Since CSSWG is not going to add new physical direction properties regarding text flow, we probably don't need to delete `[xy]` shorthand, but better add synonyms that clearly indicate logical directions.

### Reproduction

See how `px-*` and `gap-x-*` behave differently.

https://unocss.dev/play/?html=DwEwlgbgBA7gTmALgUwLQWXRYDGBDAG1QQHMALRKAMwOQA9ra7UlkBbAZ1R2QDsU4UEngAOqZgCYAfACgoUYCKgjmAFigAjEqjxsNmKQEFgAehGz5i5Ws3bd%2BuFIBCp83IVKRAT1TqtOvQMAYVdZU3AIKSA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDASSarID3fsMBVKtoAvqByNJScoADkFlRMkJCRgoLEoogy8pgW0GmyCoQqarDqABSS0jRZUABcoADaOtK1kUwWkIjhtJWRmhKg7tB8NZF0qJGggQC6XlM6kAAWfIgtAjVl0lEtbR3zi8uRQ6wkyNDqoIcofJjw6uCgCwBu4DRV58ismNDdOoFeTgYrdQa3mciH8lGKAEovI4fMZTIxLNY7JDocD-m4PKUgdJIEwPuAagBGAB0ACZUdImKh4EM5qZuJAqiAoJxifNgF91uMoToZoEIYIgA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmAvkA

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Any better suggestions?

**Comment by yheuhtozr** [comment]
Hi, what do you exactly mean by "static"? Do you perhaps mean "static so that we could identify that", or is there any side effect when modifying the regex?

**Comment by antfu** [comment]
I mean, for `gap-x` it has to map to `column-gap` or `row-gap` statically, we can't have a way to detect that if it's inside a row container or col container for a consistent left&right direction.

**Comment by yheuhtozr** [comment]
Great. It will be fine with me too, at least it will contribute findability. Actually I had a hard time looking them up on the interactive docs before raising this issue.
