### ISSUE TITLE
按照官网的教程配置presetIcons ，导致默认的presetUno失效

### ISSUE THREAD

**Issue by luqiudi** [unocss/unocss#3419]
### UnoCSS version

0.57.7

### Describe the bug

按照官网的教程配置presetIcons ，导致默认的presetUno失效
https://unocss.dev/presets/icons

### Reproduction

```javascript
import { defineConfig,presetIcons,presetUno } from 'unocss'

export default defineConfig({
    presets:[
        // presetUno(),
        presetIcons({
            prefix: 'i-',
            collections:{
                svgs:()=>import('@iconify-json/svg-spinners/icons.json').then(i=>i.default),
                mat:()=>import('@iconify-json/material-symbols/icons.json').then(i=>i.default),
            }
        })
    ]
})

```
只有手动导入presetUno() 配置以后才能正常使用

```javascript
import { defineConfig,presetIcons,presetUno } from 'unocss'

export default defineConfig({
    presets:[
        presetUno(),
        presetIcons({
            prefix: 'i-',
            collections:{
                svgs:()=>import('@iconify-json/svg-spinners/icons.json').then(i=>i.default),
                mat:()=>import('@iconify-json/material-symbols/icons.json').then(i=>i.default),
            }
        })
    ]
})

```

### System Info

118.0.5993.71（正式版本） （64 位）

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Yee0403** [comment]
因为你指定了 presets，默认的 presets 将失效，所以需要手动配上，官网有讲，我也没细看，碰到这个问题。
