### ISSUE TITLE
VSCode Extension：同一个工作区内有两个或多个vue项目，只有排在最上面的项目 能激活 插件，获得提示等功能

### ISSUE THREAD

**Issue by yyqqing** [unocss/unocss#3426]
### UnoCSS version

0.57.7

### Describe the bug

VSCode Extension：同一个工作区内有两个或多个vue项目，只有排在最上面的项目 能激活 插件，获得提示等功能。其他项目能够使用 UnoCSS正常编译运行，但无法获取提示等功能

### Reproduction

在同一个工作区内建立两个或多个vue项目，可观察到只有在排在最上面的项目中的 vue 文件能获得插件支持，有提示等功能，其他项目没有插件支持

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
First, you need to configure uno.config in both subdirectories. Secondly, check whether there is an option to configure uno.root in the settings. If so, you need to remove it.

**Comment by yyqqing** [comment]
Extension 是新安装的，没有修改过默认设置值；每个项目中都有一个 uno.config.js ，内容如下：
// uno.config.js
import { defineConfig, presetIcons, presetUno } from 'unocss'

export default defineConfig({
  // ...UnoCSS options
  presets: [
    presetUno(),
    presetIcons({
      scale: 1.2,
      warn: true,
    }),
  ],
})
没有配置 unocss.root。

**Comment by Simon-He95** [comment]
> Extension 是新安装的，没有修改过默认设置值；每个项目中都有一个 uno.config.js ，内容如下： // uno.config.js import { defineConfig, presetIcons, presetUno } from 'unocss'
> 
> export default defineConfig({ // ...UnoCSS options presets: [ presetUno(), presetIcons({ scale: 1.2, warn: true, }), ], }) 没有配置 unocss.root。

I have found the problem and it will be fixed in the next version. Thank you for your issue.

**Comment by yyqqing** [comment]
此问题在 版本v0.58.3 中尚未得到解决，希望能重新打开该 issue @Simon-He95 @antfu

**Comment by Simon-He95** [comment]
I will check later

> 此问题在 版本v0.58.3 中尚未得到解决，希望能重新打开该 issue @Simon-He95 @antfu

**Comment by Simon-He95** [comment]
Hi,@yyqqing
I tested it and there is no problem. Please check whether you have set `unocss.root`. Specifying the path causes the dynamic detection to fail. If there is still a problem, please provide a minimal demo that can be reproduced. Thank you.

**Comment by yyqqing** [comment]
可以按如下步骤重现问题：
1. 使用 npm create vue@latest 创建了 两个工程：demoA、demoB
2. 按照 https://unocss.dev/integrations/vite 加入 unocss 并进行了配置：
`// uno.config.js
import { defineConfig, presetIcons, presetUno } from 'unocss'

export default defineConfig({
  presets: [
    presetUno(),
    presetIcons({
      scale: 1.2
    })
  ]
})
`
3. 将这两个工程 拖入到 Visual Studio Code，两个工程出现在 工作区下，demoA 排在 demoB 前面。此时打开 demoA 或 demoB 中的 App.vue ，下方状态栏均不会出现 UnoCSS 提示
4.  退出 Visual Studio Code，再重新打开，此时打开 demoA 下的 App.vue，可以看到 下方状态栏均出现 UnoCSS 提示，在 class 里敲入空格，有提示；再打开 demoB 下的 App.vue，下方状态栏没有了 UnoCSS 提示，在 class 里敲入空格，也没有了提示
5. 附件为 重现问题所用 demo
[归档.zip](https://github.com/unocss/unocss/files/13885381/default.zip)

**Comment by Simon-He95** [comment]
> 1. npm create vue@latest

I downloaded your demo, but the performance is normal. There are highlights and prompts when switching between the two warehouses.

**Comment by newbill** [comment]
I have the same problem.

**Comment by Simon-He95** [comment]
> I have the same problem.我有同样的问题。

It is necessary to provide a reproducible demo, just like my gif above, my performance in this scenario is good

**Comment by ZXheart** [comment]
![GIF-demo](https://github.com/unocss/unocss/assets/43435025/152a3388-cee3-4b84-a0c9-66a37bf403dd)
same here.
- 家里和公司的都有这样的问题（都是Windows）。
- 插件版本0.58.6 下载后没做任何设置
- demo是上边朋友提供的
- settings.json没设置"unocss.root": ...

**Comment by Simon-He95** [comment]
> ![GIF-demo](https://private-user-images.githubusercontent.com/43435025/313050423-152a3388-cee3-4b84-a0c9-66a37bf403dd.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NzM5MDksIm5iZiI6MTcxMDU3MzYwOSwicGF0aCI6Ii80MzQzNTAyNS8zMTMwNTA0MjMtMTUyYTMzODgtY2VlMy00Yjg0LWEwYzktNjZhMzdiZjQwM2RkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDA3MjAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3NWIzZGQ2YTQyNjgyMjJmMjllMTE1Y2Y1NDY2ZWQ2MGFlZjU3NGYzZDA4ZmRlZDc4NjM1NWY0ZTY0MzIxYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BecUryI89JkvlupkpZMqFoqc8ebE7lozgm8Ntg2XniA) [ ](https://private-user-images.githubusercontent.com/43435025/313050423-152a3388-cee3-4b84-a0c9-66a37bf403dd.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NzM5MDksIm5iZiI6MTcxMDU3MzYwOSwicGF0aCI6Ii80MzQzNTAyNS8zMTMwNTA0MjMtMTUyYTMzODgtY2VlMy00Yjg0LWEwYzktNjZhMzdiZjQwM2RkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDA3MjAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3NWIzZGQ2YTQyNjgyMjJmMjllMTE1Y2Y1NDY2ZWQ2MGFlZjU3NGYzZDA4ZmRlZDc4NjM1NWY0ZTY0MzIxYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BecUryI89JkvlupkpZMqFoqc8ebE7lozgm8Ntg2XniA) ![GIF-demo](https://private-user-images.githubusercontent.com/43435025/313050423-152a3388-cee3-4b84-a0c9-66a37bf403dd.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NzM5MDksIm5iZiI6MTcxMDU3MzYwOSwicGF0aCI6Ii80MzQzNTAyNS8zMTMwNTA0MjMtMTUyYTMzODgtY2VlMy00Yjg0LWEwYzktNjZhMzdiZjQwM2RkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDA3MjAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3NWIzZGQ2YTQyNjgyMjJmMjllMTE1Y2Y1NDY2ZWQ2MGFlZjU3NGYzZDA4ZmRlZDc4NjM1NWY0ZTY0MzIxYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BecUryI89JkvlupkpZMqFoqc8ebE7lozgm8Ntg2XniA) [ ](https://private-user-images.githubusercontent.com/43435025/313050423-152a3388-cee3-4b84-a0c9-66a37bf403dd.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NzM5MDksIm5iZiI6MTcxMDU3MzYwOSwicGF0aCI6Ii80MzQzNTAyNS8zMTMwNTA0MjMtMTUyYTMzODgtY2VlMy00Yjg0LWEwYzktNjZhMzdiZjQwM2RkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDA3MjAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3NWIzZGQ2YTQyNjgyMjJmMjllMTE1Y2Y1NDY2ZWQ2MGFlZjU3NGYzZDA4ZmRlZDc4NjM1NWY0ZTY0MzIxYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BecUryI89JkvlupkpZMqFoqc8ebE7lozgm8Ntg2XniA) same here.
> 
> * 家里和公司的都有这样的问题（都是Windows）。
> * 插件版本0.58.6 下载后没做任何设置
> * demo是上边朋友提供的
> * settings.json没设置"unocss.root": ...

My Windows computer also performs normally

**Comment by dingdingrao** [comment]
I'm having the same problem with windows, using all the latest versions.

**Comment by Simon-He95** [comment]
Can you give me a reproducible demo, directory level, such as monorepo, and how to reproduce it?

> I'm having the same problem with windows, using all the latest versions.

**Comment by warmthsea** [comment]
https://github.com/warmthsea/element-plus/tree/test/unocss-vscode-in
https://github.com/warmthsea/element-plus/commit/ede398ca1fc1b50535a68210a8535f4dcdb69f6b

There seems to be this problem.

![screenshots](https://github.com/unocss/unocss/assets/45450994/9327056b-2738-458d-b4f3-b3363b388fbe)
