### ISSUE TITLE
Before:block class Tailwind Misaligned

### ISSUE THREAD

**Issue by relferreira** [unocss/unocss#3436]
### UnoCSS version

0.58.0

### Describe the bug

The `before:block` class doesn't have the same behavior of Tailwind.

Tailwind result:
```css
.before\:block::before {
    content: var(--tw-content);
    display: block;
}
```

UnoCSS result:
```css
.before\:block::before{display:block;}
```

Thanks a lot for your work. I'm a huge fan!

### Reproduction

Tailwind example:
https://play.tailwindcss.com/iYKghOK9o8

UnoCSS example:
https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIDmAnMIo54C0MA9nEkQCxQBGApgGanb0BctcpMA1ugHwAoKFFCRYiFBlosQ9bAIAu9JMuAB6cBCEix0eMjToZ2OQv7LV9DVp2itEw9NnylKtZshCbXoA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcEWSIUB1DBwBixGDKQBfOFigQQcAORcVEunStIkGAB6RY6bAEMuAG3hMHHwiEmBSAApkVCh-egAuOABtJKsJLjoYCwBaWL8MK3JEOCk-aESrWjQrOCMAXTrZOgALaBh0g0To1Gt0zJyWto6rCpg3GGy-Ujgx1wnob1xSDDhWgDcMKHjZibHvP0KqIzV5RjpEpKphU6UVCIBKWWvRZlZ2bl4BB6e5F61dfR0KJXHo0CBrYCYLbWUgQCCkfKFOAAemRXiwvgCcnBkM2INQeD8eAwYnAbXOpn2DB%2BqCwgK6%2BJ6qJmzVEcAA7sA-H44OMMLg0CyVkFMfAYKyQBhGag6IsKVYAEoQDgQLJOHo9Y4goyPEHqcRSXBA7oaugSfYYRIARgAdAAmGklNC4CrNVhgc6o%2BggG0tZGHDU62SNYz3JBAA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmAvkA

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by chu121su12** [comment]
IIRC this is intended. You may want to find the older issues/pr regarding this. Also the reset compat does not have content cssvar.

As workaround for now, you can use shortcut to remap this utility

**Comment by relferreira** [comment]
I'm really sorry about that. I didn't find it on the older issues.
Thank you for your response and patience.

**Comment by NamesMT** [comment]
Hi, I'm also encountering an issue regarding this,

I'm setting up Primevue to work with Unocss, for the most part it's working but I got a bug with the `InputSwitch` component, wheres it uses styling on the `before:` class for the state dot inside, Unocss generated classes for it doesn't have `content: ''` style and the dot is invisible.

Ref: https://v3.primevue.org/inputswitch/
Image: 
![image](https://github.com/unocss/unocss/assets/23612546/180ca986-2f3c-4f16-9e6e-1320faae92a2)
