### ISSUE TITLE
希望unocss有个中文文档

### ISSUE THREAD

**Issue by dong-lufei** [unocss/unocss#3438]
### Clear and concise description of the problem

https://unocss.dev/guide
希望有中文

### Suggested solution

参考vue3 官网

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [ ] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Thanks for bringing this up, but sorry we don't have a plan for translations.
