### ISSUE TITLE
"all" CSS properties 

### ISSUE THREAD

**Issue by lyneal** [unocss/unocss#3440]
### Clear and concise description of the problem

Hello, could we have an implementation of the CSS property "all" knowing that this property should ideally respect the positioning order in which it is declared?

This would make it easy to reset the upper properties.

https://developer.mozilla.org/fr/docs/Web/CSS/all

### Suggested solution

I've created a rule that works, but doesn't apply the property to the desired location (order matters).

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by chu121su12** [comment]
You may want to use `[all:x]` since `all-x` is already used in a variant. As for ordering, the simplest approach is to use [uno-layer](https://unocss.dev/config/layers#usage).

**Comment by lyneal** [comment]
Thanks for your comments!

From what I've seen about the "all-x" variant, it allows you to target all elements inside the class.
Thus, "all-break-keep" generates :
`
.all-break-keep * {
  word-break : keep-all ;
}
`
Your suggestion to use [all-x] or [all:x] works largely because it generates the desired CSS property in the desired block, so there's no need to create a specific rule. This is already a very good thing and will certainly suffice to meet the need.

The "all" CSS property takes on the following values:
`
all : initial ;
all : inherit ;
all : unset ;
all : revert ;
all : revert-layer ;
`

If I've understood correctly, this property applies to the other CSS properties above it, which also includes the other properties in the same block, hence the importance of the declaration order.

If I create a shortcut `btn: 'c-red [all:initial]` in this case, the order won't be respected. I don't know if this is a bug or the way unoCSS works.
 I'm also attaching an example to be more explicit about the problem encountered.

https://unocss.dev/play/?html=DwEwlgbgBAFgtAMwK4BsVQOYCcwigBxQEMBjAUzhIHsA7AFzPssYawD4AoKKYAIyTp1aUEsQDOYgLwAiXnRoBGaWwAqZMXSgLgAen6DanbnwFCaI8VNnyATMrUaoN3frNGer4aKISZcmgDM9uqaAS6mhhy64BBsQA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdIaZ4kOX07gaAEVh0WsADcoB119QwBVKm0AX1A5GkpOUAByCyomSEhkwUFiUUQZeUwLaALZBUIVNVh1AApJaUgACz5EJitIAC4JHWlk7ER4AEZk7uSmWjZQAG1MaGhOhFhrOYBdZJC%2BgfgAJlGU2fnF%2BGXYNdAJulQNnWiQpxc3Gg8aLpne0AfXd08fP2sgpBagBKEKrEJ6KCGN7TD6QgyISKUEGbUJQ4ymRiWax2EE6cGCaLAwRAA&css=HQIwLgdgzABA3gKBjAAgQwA4YDYE8YDGAtAE4CmAJgNxIxrbYBcMAlhC2C-TQL5A&options=N4IgLgTghgdgzgMwPYQLYGECucxIwZXxAC4EoAbOAUwBpxp5k0AJMVcksyqgXyA

**Comment by Simon-He95** [comment]
<img width="545" alt="image" src="https://github.com/unocss/unocss/assets/57086651/ae77bbca-ddef-411f-b529-5f84df18365f">
[play](https://unocss.dev/play/?html=DwEwlgbgBAFgtAMwK4BsVQOYCcwigBxQEMBjAUzhIHsA7AFzPssYawD4AoKKYAIyTp1aUEsQDOYgLwAiXnRoBGaWwAqZMXSgLgAen6DanbnwFCaI8VNnyATMrUaoN3frNGer4aKISZcmgDMUACEANpEaABcYDRgdGARALr26poBLqaGHLrgEGxAA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdIaZ4kOX07gaAEVh0WsADcoB119QwBVKm0AX1A5GkpOUAByCyomSEhkwUFiUUQZeUwLaALZBUIVNVh1AApJaUgACz5EJitIAC4JHWlk7ER4AEZk7uSmWjZQAG1MaGhOhFhrOYBdZJC%2BgfgAJlGU2fnF%2BGXYNdAJulQNnWiQpxc3Gg8aLpne0AfXd08fP2sgpBagBKEKrEJ6KCGN7TD6QgyISKUEGbUJQ4ymRiWax2EE6cGCaLAwRAA&css=HQIwLgdgzABA3gKBjAAgQwA4YDYE8YDGAtAE4CmAJgNwIC%2BQA&options=N4IgLgTghgdgzgMwPYQLYGECucxIwZXxAC4EoAbOAUwBpxp5k0AJMVcksyqgXyA)
