### ISSUE TITLE
Cannot use multiple nested named groups in a selector

### ISSUE THREAD

**Issue by andrew-boyd** [unocss/unocss#3441]
### UnoCSS version

0.58.0

### Describe the bug

**Issue:**
When using UnoCSS I am unable to use multiple named groups within a selector. eg (`group-outer` & `group-inner` as parent selectors). I'm able to do many other permutations of groups / named groups but when using two named groups together UnoCSS fails in a way that TailwindCSS does not.

**Motivation**
We recently started shipping new Tailwind-based themes for FormKit and have started getting [requests from users to support UnoCSS officially](https://github.com/orgs/formkit/discussions/1065). In looking into what that would take I've come across this issue. Due to the complex nature of custom form inputs some of our selectors get pretty wild. Mainly opening up this issue to see if this is something that can be supported from UnoCSS' side or if supporting UnoCSS means we'll need to try and adjust our themes to use a limited subset of Tailwinds' features.

### Reproduction

I'm attaching the same code in both the UnoCSS and Tailwind online playgrounds that shows 4 working increasingly complex group selectors and then a 5th selector that works with TW but is not successfully parsed by Uno.

- [UnoCSS Playground](https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIDmAnA9gVwAcpCBaADijADs4aBTUgIzlxgGtZ9sldtTCuGgBd62dAD4AUFCjAAFgEZYiFBhwEy83BDEAuUQA9hpbPRCkArAAZrUIyYBshuFCZ8QYkoYqSAErhwiMAA9ErSssCEEhpEpNq62Ab0xqbmVrah0VKh4BDSOXkqyGhYeEQh1AgAtuYkFFS0DMysHFw8fAJC1KLiEXJKxWplmvE6YpU15smpZhY2dg6kzq7u2J7Y3r4SAUEIoeEyctGxWuPYk7UgMyZzGdZZ0rmQBaCQQ6Wn6FAgCMIIpAAZrhcBhhNh8PRJEc3tB4CV1OVCJc6mRKDQ6NRGCw2JwYNxePxBCIxNDZJFBvDhqdSL9-qQANrA0HgyEAXT0NISEyqVxuaXmtnsKScLjcHi8hB85H8gWCYUU-UiJyRtL%2BAKZINQrPoHK55xR1yWdwWjxhITyTwtLykhXeVM%2BSO%2BdIBzLBEKh-VhH0RmkN9XRTSxLVx7UJXRJfSOFOUCGwYABiCY9DgYPoSGE3wdvriLsZbp1etV3IuvOmcYTjKTKe16eEHON6QWwtSK3F60l0tlewOiujxxiqrzmpZHqLoxLhr0FY11dTogzDZFAvuZsi1vyOQ3ryK2ZGRGd6qBWvQOrJcl3qkdfoIvUP9KYcfdkPPkUvCP3yJoWM2aMamOxVo8QJTpiR6UklXJBRY3jRMEGTVNTzrLMrxzMhh0fbBtTHEJb30fVEhCb99EbQVFmXNs1g2LYZR2OV9gVSDlUHUYMKfQtcPwXpOWLA1iKSUjVxCbJyTkbdzUtLdJKAA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDASSarID3fsMBVKtoAvqByNJScoADkFlRMkJCRgoLEoogy8pgW0GmyCoQqarDqABSS0jRZUABcoADaOtK1kUwWkIjhtJWRmhKg7tB8NZF0qJGggQC6XlM6kAAWfIgtAjVl0lEtbR3zi8uRQ6wkyNDqoIcofJjw6uCgCwBu4DRV58ismNDdOoFeTgYrdQa3mciH8lGKAEovI4fMZTIxLNY7JDocD-m4PKUgdJIEwPuAagBGAB0ACZUdImKh4EM5qZuJAqiAoJxifNgF91uMoToZoEIYIgA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmAvkA)
- [TailwindCSS Playground](https://play.tailwindcss.com/Qf041BpHMD)

### System Info

MacOS 14.1 (M2)
Brave Browser v1.60.125

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
Is this a problem with the tailwind performance?
It should be group-data-[foo=true] to take effect
<img width="1517" alt="image" src="https://github.com/unocss/unocss/assets/57086651/a4e5d0f1-ef3d-42b9-9b92-06d6fce20788">
