### ISSUE TITLE
Config `cssExtend` in presetTypography cannot use `@apply` in build mode

### ISSUE THREAD

**Issue by wtto00** [unocss/unocss#3452]
### UnoCSS version

0.57.7

### Describe the bug

I have configured a theme color `accent`:
```ts
theme: {
  colors: {
    accent: 'rgb(255, 107, 1)'
  }
}
```

I want to override some styles in the presetTypography, for example, I want the color of `h1` to be the theme color `accent`, and the opacity of color to be 80. I can write it like this:
```ts
presetTypography({
  cssExtend: (theme) => ({
    h1: {
      '--uno': 'c-accent c-op-80',
    }
  })
})
```
This works fine in the development environment, but when packaged, it will output something like `h1 {--uno:c-accent c-op-80;}`. So I can only configure like this:
```ts
h1: {
  color: theme.colors?.['accent'] as string 
}
```
But this way, I cannot achieve the opacity of the color.

I ultimately had to give up the `cssExtend` configuration option and instead overwrote these styles in the project's global stylesheet.

### Reproduction

[Playground](https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIYFckBcD2AtugHwBQUUwAFgIwkCqAdvgMIDK7wA9HeZcBj4QAUxK4ReWMJE8ho8j3ARyQA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAqrhJajfYwCoCekpKAEMwAC17s4MYbjpZoIDFAAiwWgGMYwAG71KAXzhYoEEHADkAV1bq6dc0iQYAHpFjpsQywBt4mHPhEJMCkABTIHLQMMHQAXHAA2lSRXMysoQCUkinRfALCYrzhyahwDN4YmtAAckKK8ebqlnQwpubZpbZ0AKLOMBi4aPEwohiKcAC8AHxwxaXzcKIAjPERC-MA9Btw6hDe0A2CGAPtJevmALQXQjDXYGDevOYN6tfq6gMwDuuo%2Bmdw%2BgyJUBkgAupIRmMMKsSrt9lA4oh-kJ3p8GlBSAAjUIABnIcCWOIAHPilgB2ABMGVO8z%2BvwhMjkCiUiIS0iEsnkUEUKjUlS0ujomXBSEBSCAA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUGLSZcYAN7awYAAK1hygJ5hBULOgQBubQF8gA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwBpxp5k0BhAVzjCVQoGVHNs8iTZEVUAJMVDla4CAXyA)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
It seems to go beyond the scenario in which it is applied, and I don't recommend you use it like this.

Or you can try to create a context and actively use the API to convert the code in advance and inject it into uno config.

like this: 
```ts
// uno.config.ts

import { transformDirectives } from '@unocss/transformer-directives'

async function transform(code: string, uno: UnoGenerator) {
    const s = new MagicString(code)
    await transformDirectives(s, uno, {})
    return s.toString()
}

// ...
presetTypography({
  cssExtend: async (theme) => ({
    h1: toCssObject(`{${await transform('c-accent c-op-80')}}`)
  })
}) 
```

For reference only.

**Comment by wtto00** [comment]
Hello, @zyyv 

Thanks for your reply.

Is there a plan to support this feature in `presetTypography` or `transformerDirectives`?

**Comment by zyyv** [comment]
@wtto00 It is not in the plan. If this requirement is forcibly implemented, it will bring additional dependency overhead.

As I said above, this is not its own application scenario. You may need to use related APIs to combine and implement it.

**Comment by wtto00** [comment]
Ok, got it.
