### ISSUE TITLE
How to turn off automatic conversion

### ISSUE THREAD

**Issue by ayangweb** [unocss/unocss#3460]
### Clear and concise description of the problem

Examples 1:

```html
<div class="text-14"><div>
```

👇

```html
<div class="text-sm"><div>
```

Examples 2:

```html
<div class="w-100"><div>
```

👇

```html
<div class="w100"><div>
```

### Suggested solution

This automatic conversion happens in many places, but I don't want it to convert automatically, how do I turn this off?

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [x] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Simon-He95** [comment]
This is provided by the unocss plug-in. You should have unot installed. There is a uno-magic switch at the bottom. If you don’t want to automatically handle it for you, you can choose to turn it off.
<img width="112" alt="image" src="https://github.com/unocss/unocss/assets/57086651/be01e846-c590-46c9-a003-3dcb7e8df4b2">

**Comment by ayangweb** [comment]
> This is provided by the `unocss` plug-in. You should have `unot` installed. There is a uno-magic switch at the bottom. If you don’t want to automatically handle it for you, you can choose to turn it off. <img alt="image" width="112" src="https://private-user-images.githubusercontent.com/57086651/292763829-be01e846-c590-46c9-a003-3dcb7e8df4b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1NTE0NDMsIm5iZiI6MTcwMzU1MTE0MywicGF0aCI6Ii81NzA4NjY1MS8yOTI3NjM4MjktYmUwMWU4NDYtYzU5MC00NmM5LWEwMDMtM2RjYjdlOGRmNGIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDAwMzkwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkYzdlMmQ2YWRiZDRkN2NiMzUxYjk3YjhjYmNiODdkYTRhNWZhMGI3NmFhZmI2NWE1ZDdlZmViNjY1YTU5ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XOYsm4lJrnh03Ky3eDfbYw6a_69Fln5-GYA95bkDHcc">

Okey, thanks for the reply, sure enough it was `UnoT` that caused it!
