### ISSUE TITLE
vite transformer lightningcss, --at-apply, bg-white/10 is not work, but bg-hex-FFFFFF1A is work.

### ISSUE THREAD

**Issue by luvletterldl** [unocss/unocss#3465]
### UnoCSS version

0.58.0

### Describe the bug
![1703663469318](https://github.com/unocss/unocss/assets/26115291/add9f773-4584-4029-bbb8-cd7e867afc21)

vite 5.0.10
vue 3.3.13
unocss 0.58.0

I try to use 'lightning CSS' in my project, but I found 'bg-white/10' is not work, but 'bg-hex-FFFFFF1A' is work. 'bg-white/10': var(--un-bg-opacity) --un-bg-opacity always is 1.

w-1/2 top-1/2 translate-x-1/2 same issue, --at-apply not work.

### Reproduction

StackBlitz: Pre-transform error: Cannot find package 'napi-wasm' imported from /home/projects/unocss-unocss-9m7yj8/node_modules/lightningcss/wasm-node.mjs
just start a vite + unocss project, you can reproduction it.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zoeyzhao19** [comment]
Tests show that `bg-red/10` is transformed to `bg-red / 10`  by  `lightningcss`, so the real token `unocss` got is `bg-red`. Maybe you could find some solution on `lightningcss` side, or `bg-red\/10` would be a workaround.

**Comment by luvletterldl** [comment]
> Tests show that `bg-red/10` is transformed to `bg-red / 10` by `lightningcss`, so the real token `unocss` got is `bg-red`. Maybe you could find some solutions on `lightningcss` side, or `bg-red\/10` would be a workaround.

But why it just happen at `--at-apply`? `<div class="bg-red/10">Cli Index Page</div>` is work.

**Comment by zoeyzhao19** [comment]
> > Tests show that `bg-red/10` is transformed to `bg-red / 10` by `lightningcss`, so the real token `unocss` got is `bg-red`. Maybe you could find some solutions on `lightningcss` side, or `bg-red\/10` would be a workaround.
> 
> But why it just happen at `--at-apply`? `<div class="bg-red/10">Cli Index Page</div>` is work.

It does not affect inline styles. `lightningcss` in vite  just  apply on `css assets`, i.e. it transforms sources in a css asset request.

**Comment by luvletterldl** [comment]
> > > Tests show that `bg-red/10` is transformed to `bg-red / 10` by `lightningcss`, so the real token `unocss` got is `bg-red`. Maybe you could find some solutions on `lightningcss` side, or `bg-red\/10` would be a workaround.
> > 
> > 
> > But why it just happen at `--at-apply`? `<div class="bg-red/10">Cli Index Page</div>` is work.
> 
> It does not affect inline styles. `lightningcss` in vite just apply on `css assets`, i.e. it transforms sources in a css asset request.

Thank you for your replay.

**Comment by luvletterldl** [comment]
Thank you for your reply.
