### ISSUE TITLE
VSCode Extension root not working for monorepo, 0.51.12 is ok

### ISSUE THREAD

**Issue by GGBeng1** [unocss/unocss#3467]
### UnoCSS version

0.58.2

### Describe the bug

<img width="313" alt="image" src="https://github.com/unocss/unocss/assets/40552498/66fe0831-5acf-4654-bb04-be98ba2212e8">
<img width="809" alt="image" src="https://github.com/unocss/unocss/assets/40552498/941ef939-3d6e-4071-9501-e20e5d0bb987">
<img width="784" alt="image" src="https://github.com/unocss/unocss/assets/40552498/a568d1db-9096-4fdc-bf0e-b5c786af8550">

### Reproduction

-

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
Please try to delete `unocss.root`. The latest version can be automatically detected.

**Comment by GGBeng1** [comment]
> Please try to delete `unocss.root`. The latest version can be automatically detected.

Thanks for reply, I change `uno.config.mjs => uno.config.ts`  , it is work.
