### ISSUE TITLE
Nuxt 3.9.0 Build Error: [unocss] does not found CSS placeholder in the generated chunks

### ISSUE THREAD

**Issue by silverwolf42** [unocss/unocss#3468]
### UnoCSS version

0.58.2

### Describe the bug

Integration with the Nuxt(nuxt 3.9.0) module for UnoCSS(0.58.2).

Run `nuxt build` or `nuxt generate` got the error:

```
ERROR  [unocss:global:build:bundle] [unocss] does not found CSS placeholder in the generated chunks
```

### Reproduction

https://stackblitz.com/edit/github-onkxmp

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by designbyfaizi** [comment]
Same issue. I'm not able to build since upgrading to Unocss v0.58.2

**Comment by antfu** [comment]
This is caused by #3448 + Nuxt 3.9 changes. 

An workaround for now is to add this to your nuxt config:

```ts
export default defineConfig({
  features: {
    inlineStyles: false,
  },
})
```

Need to investigate deeper to find a better fix.

/cc @zyyv

**Comment by Nuzzlet** [comment]
I'm experiencing this error on Nuxt 3.8.2 when I update @unocss/nuxt beyond version 0.58.0

**Comment by QaahirStewart** [comment]
Same issue here on unocss 0.58.2
