### ISSUE TITLE
[🐞Bug]: Valueless attribute not working in React JSX, with `presetAttributify` and `transformerAttributifyJsx`

### ISSUE THREAD

**Issue by xsjcTony** [unocss/unocss#3471]
### UnoCSS version

latest

### Describe the bug

Valueless attribute not working in React JSX, with `presetAttributify` and `transformerAttributifyJsx`
![Snipaste_2023-12-29_23-50-41](https://github.com/unocss/unocss/assets/45784210/7748b72b-6c12-40cc-9ae2-5caca0ae956e)

### Reproduction

https://stackblitz.com/edit/vitejs-vite-tndpa7?file=src%2FApp.tsx

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zhiyuanzmj** [comment]
Now, I used `ast-grep` to match attributes, and it works well for me. 
relation  discussion:
 https://github.com/unocss/unocss/discussions/3346

**Comment by xsjcTony** [comment]
Is this fixed? I've updated the reprod to the latest version, seems it's working all good (at least for the minimal reprod)

**Comment by Simon-He95** [comment]
yeah，it seem to be fixed
