### ISSUE TITLE
Accidentally include CSS when only file content match rule's regex

### ISSUE THREAD

**Issue by i7slegend** [unocss/unocss#3473]
### UnoCSS version

0.58.2

### Describe the bug

Rules (like **tab** in the preset-mini) can be appears in a final bundle but never used (i mean explicit use CSS classes).

For example, it's can be prop name in the defineProps or prop name of a component. In the reproduce link i attach example with defineProps and component's property not used in the App.vue file, but **.tab** anyway included in .css file (production bundle and also can be inspected via the __unocss)

### Reproduction

https://stackblitz.com/edit/unocss-unocss-gku7tz?file=src%2Fcomponents%2FAnyName.vue

### System Info

vite + Vue 3

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by i7slegend** [comment]
I think nearly to #3174 but cause that issue when uses component prop.

Now this can be fixed only with `blocklist` option

**Comment by zyyv** [comment]
This is because `Uno` parses the template string as fully as possible, I guess it just doesn't have bad side effects.
If you want to ignore it, refer to the reply in #3174

**Comment by Simon-He95** [comment]
This is a known situation. Because of the ability of unocss, it can parse global modules, so you can use dynamic uno syntax in the template, but the disadvantage is that there may be redundant classes generated, and users need to handle and filter some scenarios by themselves.
