### ISSUE TITLE
Add `important` option to `preset-wind` as it's supported in tailwind

### ISSUE THREAD

**Issue by xsjcTony** [unocss/unocss#3474]
### Clear and concise description of the problem

Support tailwind's `important` config.

It's going to help resolve my issue when using with ant design: https://github.com/ant-design/ant-design/issues/46707

### Suggested solution

https://tailwindcss.com/docs/configuration#important

More specifically, this is what I needed: https://tailwindcss.com/docs/configuration#selector-strategy

I want to be able to transform those atomic classes with an selector prefix, e.g. `.p-4` => `#root .p-4`

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by zyyv** [comment]
I implemented this in [unocss-preset-useful](https://github.com/unpreset/unocss-preset-useful/blob/60df1b3f0c59475637dc6b4b10bbaf69c995edbd/packages/core/src/core/postprocess.ts#L23-L30).

Check the test case. https://github.com/unpreset/unocss-preset-useful/blob/60df1b3f0c59475637dc6b4b10bbaf69c995edbd/test/postprocess.test.ts#L39-L61

**Comment by zyyv** [comment]
We provide `postprocess` hook, I guess you can handle it yourself?

**Comment by xsjcTony** [comment]
I want to add `#root ` selector before the atomic classname. Let me try whether I can figure it out using variant.

**Comment by antfu** [comment]
I am ok having it to align with tailwind, PR welcome

**Comment by xsjcTony** [comment]
@antfu Wondering whether you want it in `preset-wind` or `preset-mini`?

Also, beyond the tailwind behavior (which I will introduce an option called `important: boolean | string`) which will apply globally, I also want to introduce something like `ancestor-xxx:yyy` variant to partially opt-in.

E.g. `ancestor-#root:m-4` will be `#root .m-4 { ... }`, `ancestor-[#root_>_#container_>]:p-2` will be `#root > #container > .p-2`

Any thoughts on this? If you approve, would you like me to do it in the same PR or separately?
