### ISSUE TITLE
Nuxt 3.9.0 "hidden" attribute not working as expected

### ISSUE THREAD

**Issue by kylegl** [unocss/unocss#3477]
### UnoCSS version

v0.58.2

### Describe the bug

```
    <div hidden sm="flex bg-red h-50"  />
```

Does not change display to flex at breakpoint.

### Reproduction

https://stackblitz.com/edit/github-hztdxt?file=nuxt.config.ts

### System Info

``` 
"devDependencies": {
    "@unocss/nuxt": "^0.58.2",
    "nuxt": "^3.9.0",
    "vue": "^3.4.3",
    "vue-router": "^4.2.5"
  }
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by henrikvilhelmberglund** [comment]
This is because of the Tailwind reset `tailwind.css`
```
/*
Make elements with the HTML hidden attribute stay hidden by default.
*/

[hidden] {
  display: none;
}
```

You can either use the class attribute or remove those lines from the reset.

**Comment by kylegl** [comment]
Huh is that new?

**Comment by henrikvilhelmberglund** [comment]
> Huh is that new?

No, it is unrelated to UnoCSS's attributify mode and allows you to hide elements by simply adding a `hidden` attribute on the element. In your case it creates a conflict though.

**Comment by kylegl** [comment]
Well i know it worked before this version. Good to know tho, thanks

**Comment by henrikvilhelmberglund** [comment]
> Well i know it worked before this version. Good to know tho, thanks

If you have a stackblitz where it worked before please share it, the `tailwind.css` hasn't changed for several months. It is possible something other made it behave differently.

**Comment by Simon-He95** [comment]
This has been fixed in the latest version.
