### ISSUE TITLE
Not clear why `class=` is not needed in the playground

### ISSUE THREAD

**Issue by ledenis** [unocss/unocss#3491]
### Clear and concise description of the problem

As someone that discovers UnoCSS, when I read the [Getting Started](https://unocss.dev/guide/) page, then follow the link to the [playground](https://unocss.dev/play/), I see there are no `class=` needed.

e.g.

```
<div op30 text-lg fw300 m1>
```

instead of

```
<div class="op30 text-lg fw300 m1">
```

But I did not understand why, and it is not explained in the doc until I find it in [attributify](https://unocss.dev/presets/attributify#valueless-attributify) page.

### Suggested solution

Maybe explain it somewhere in the Getting Started page?

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Simon-He95** [comment]
<img width="1322" alt="image" src="https://github.com/unocss/unocss/assets/57086651/243875af-b1eb-4e00-9f5a-ff043ec1c3eb">
In fact, this function has already been introduced on the homepage of the document

**Comment by ledenis** [comment]
Yeah I saw it afterwards, but one might miss it since the landing page is not part of the docs. Plus, I don't find it clear either what it does from its text.

**Comment by AndrewBogdanovTSS** [comment]
you can also check WindiCSS docs since as stated in the link it's a feature ported from WindiCSS https://windicss.org/features/attributify.html
When working with Uno I frequently use all sources of docs, Tailwind, Windi, Tachyons etc

**Comment by Simon-He95** [comment]
If you have suggestions for better documentation, please feel free to PR
