### ISSUE TITLE
VSCode Extension - When a prefix is used, the IntelliSense is not work

### ISSUE THREAD

**Issue by mccube2000** [unocss/unocss#3493]
### UnoCSS version

@unocss/nuxt: ^0.58.3  

### Before set prefix
![image](https://github.com/unocss/unocss/assets/57378429/4a62cfe9-2864-474b-ac0b-b32c3ad41683)

### uno.config.ts
```TypeScript
import {
  // ...
  presetAttributify
} from 'unocss'

export default defineConfig({
  // ...
  presets: [
    presetAttributify({
      prefix: 'u-',
      prefixedOnly: false
    })
  ],
  // ...
})
```

### After
![image](https://github.com/unocss/unocss/assets/57378429/b84a7d19-f6e5-4547-8dd4-8d49952050be)

### uno.config.ts
```TypeScript
import {
  // ...
  presetAttributify
} from 'unocss'

export default defineConfig({
  // ...
  presets: [
    presetAttributify({
      prefix: 'u-',
      prefixedOnly: false
    })
  ],
  // ...
})
```

### app.vue
```Vue
<template>
  <div
    u-flex
    u-flex-wrap
  >
  </div>
</template>
```

### System Info

VS code
Windows11

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mccube2000** [comment]
VSCode Extension:
UnoCSS
v0.58.3

![image](https://github.com/unocss/unocss/assets/57378429/2c3b6dd2-420a-4ff8-beb4-bb7e07cbdc81)

**Comment by Simon-He95** [comment]
https://github.com/unocss/unocss/blob/main/packages/vscode/src/utils.ts#L23C29-L23C37
It seems that there is no way to correctly parse the element with prefix. I wonder whether I should use regular expressions to erase the content of prefix and then parse it again.
Do you have any good advice? @antfu
