### ISSUE TITLE
Incorrect grid-template-columns syntax

### ISSUE THREAD

**Issue by Jason7158** [unocss/unocss#3501]
### UnoCSS version

0.58.3

### Describe the bug

![Snipaste_2024-01-06_18-35-52](https://github.com/unocss/unocss/assets/26430685/b0cb92a7-3335-41c0-a720-4a412543e457)
Commas should be replaced with ' '(space). 
Check the correct syntax [here](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-columns).

### Reproduction

[Interactive doc](https://unocss.dev/interactive/?s=grid-cols-[1fr,1px,1fr])

### System Info

Edition	Windows 11 Pro
Version	23H2
Installed on	‎9/‎6/‎23
OS build	22631.2861
Experience	Windows Feature Experience Pack 1000.22681.1000.0

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by luke358** [comment]
may be you can like this: `grid-cols-[1fr_1px_1fr]`

**Comment by Jason7158** [comment]
@luke358 

> may be you can like this: `grid-cols-[1fr_1px_1fr]`

Hi, where can I find documentation for this kind of syntax?

**Comment by luke358** [comment]
here: https://github.com/unocss/unocss/blob/b60149d837b77db458ee5381cc7a798390e3b54b/packages/preset-mini/src/_utils/handlers/handlers.ts#L196

`handlers` is used to handle basic syntax.
