### ISSUE TITLE
Enables the `content` field of the preset.

### ISSUE THREAD

**Issue by Jannchie** [unocss/unocss#3502]
### Clear and concise description of the problem

I am trying to create a component library based on unocss. In the components of the library, I directly use atomic CSS. When I build, a CSS file is generated. I anticipate that some users, while using this component library, will also use unocss. In this case, some rules (like p-2, flex, etc.) will be introduced twice. I hope that for users using unocss, they don't need to import the built CSS, but instead allow unocss to scan the component library files in node_modules (usually a JS file). It seems possible through configuring content, but node_modules is hardcoded as an excluded area.

Currently, I have made a preset and hoped to use fs to read the text of JS files and then write it into `content.inline` in the preset. But I find that the `content` property seems to be ineffective in the preset.

### Suggested solution

In summary, I am seeking a straightforward method to scan files in `node_modules` and preferably utilize it within a preset.

My current approach involves defining a preset as follows:

```ts
const preset: () => Preset<object> = () => () => {
  let file = ''
  try {
    file = fs.readFileSync('node_modules/xxx/dist/index.js', 'utf-8')
  }
  catch { }
  return {
    // some other configs
    content: {
      inline: [file],
    },
  }
}
export { preset }
```

However, this doesn't work. Although I can read the contents of file, unocss seems not to recognize the content field in the preset.

### Alternative

I can specify the files to read in `uno.config.ts` and it works, but I find this method inelegant and prefer not to expose the file-reading logic to users.

```ts
import fs from 'node:fs'
import { defineConfig } from 'unocss'
import { myUILibPreset } from '@xxx/preset'

const file = fs.readFileSync('node_modules/@xxx/dist/index.js', 'utf-8')

export default defineConfig({
  presets: [
    myUILibPreset (),
  ],
  content: {
    inline: [file],
  },
})
```

Instead, I want users to be able to do this:

```ts
import { defineConfig } from 'unocss'
import { myUILibPreset } from '@xxx/preset'

export default defineConfig({
  presets: [
    myUILibPreset (),
  ],
})
```

### Additional context

Or perhaps there are other ways to accomplish this better?

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Simon-He95** [comment]
Maybe you can try to first read package.json to find the source of the installation library, obtain node_modules at the same level, and implement this logic inside the plug-in yourself.
