### ISSUE TITLE
vite5 build error in jenkins（@unocss/vite/dist/index.cjs:110:5 ）

### ISSUE THREAD

**Issue by zxuanhong** [unocss/unocss#3504]
### UnoCSS version

0.58.3（node js v20.11.0）

### Describe the bug

1. building error in Jenkins, vite is using 5.0. login info:
```
@anyi/webeezeebe:build: Error: deprecation warning
@anyi/webeezeebe:build:     at deprecationCheck (/var/jenkins_home/workspace/anyi-zeebe-web/node_modules/.pnpm/@unocss+vite@0.58.3_rollup@4.9.4_vite@5.0.11/node_modules/@unocss/vite/dist/index.cjs:86:11)
@anyi/webeezeebe:build:     at reloadConfig (/var/jenkins_home/workspace/anyi-zeebe-web/node_modules/.pnpm/@unocss+vite@0.58.3_rollup@4.9.4_vite@5.0.11/node_modules/@unocss/vite/dist/index.cjs:110:5)[39m
@anyi/webeezeebe:build:  ELIFECYCLE  Command failed with exit code 1.
```

### Reproduction

1. Create a Vue project and use version 5.0.11 of Vite（UnoCSS 0.58.3）
2. Create a free project in Jenkins and run the compile command pnpm run build

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by akinoccc** [comment]
Hi, how did you fix it?

**Comment by 23forever** [comment]
> Hi, how did you fix it?

this code caused
```TS
// @unocss\vite\dist\index.mjs
if (warned && typeof process !== "undefined" && process.env.CI)
    throw new Error("deprecation warning");
```
You should either dismiss the warning generated by the uno.config.ts file, or add an environment variable CI under a global properties to jenkins and set it to false to fix the problem

config jenkins global properties

![Image](https://github.com/user-attachments/assets/3eb81b4d-d42c-488e-98de-b74d9ec58fd4)

![Image](https://github.com/user-attachments/assets/499c7ac7-fb7a-44aa-bd70-2cce9d32fc88)
