### ISSUE TITLE
keyframes can not use object

### ISSUE THREAD

**Issue by robin-dongbin** [unocss/unocss#3508]
### Clear and concise description of the problem

I want to define keyframes use object like tailwindcss

### Suggested solution

Allow define keyframes use object

### Additional context

![image](https://github.com/unocss/unocss/assets/24680921/da899796-15e2-4883-9054-0de1eee476cd)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by henrikvilhelmberglund** [comment]
Any reason why you need an object? For an example of custom animations see this: https://uno.antfu.me/play/?html=DwBwBAxgNghgznAvAIgGZQKYA8zuwWggHsowBLAFwwFs5CMA7KgJzBAvwFYAGMKrDgGYspGAzLUYVfAHcyAc3mYwAawwBPVMxjUMdOYszIAfACgwYA0oyngAehBmgA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6hU4AGYJwAYUrw5AcwA0obnUjhEAQUQNY2AK6JYMgJ6btUPQEkmyyLZ16AqlVABfUDJpKTlAAclMqJkhIEMFBYlFEKVlMU2hE6TlCJRVYVQAKcUFQUEQAC3BOcAAuCSLi0Ex4LkwLZRrC%2BvqAa3ArAMxKyHa6zuKAd1zVPCqR0eKQ8QAGAFJNAEZFlYkGRsgZPk4awMQW8DzkAGZpVQBKPwBWLfEd%2BD2Do8oT1jyr8FufHwhdSzYo%2BYFzVCmGgtWAuYZzcaTaahNbRcGjMEgkpcBCqABir3hCImqim1VC4Ewug48GQlHMQKxmLm2ko3HA-FgUCJcxAJWhr32NE4dMYqgQDXgqFA2EwTC6Mjl%2BAAbhgTLA4IgrKBynQmejOs5wgIeaMSWSaiEEJlYKxGXNmfVHZi6jRUtzQABtT0hJimSCIIK0d1AiSgZzQPiWuioEK%2BAC68fRkFKfEQfpNtU6vv9gZFKbTGZCltYJGQ0FUJWIKD4jVU4B1lGVHKqpZQrEw0HtvnRdl0mc9sz7nioeRuBq07gMRkYZgs1jHE%2BHiCcLgKWMgTE75LWADoAEwT4pMVDwS2lIzcIYgKCcXcp4Dd0HjupJwQ%2BG6CIA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmAvkA

also see https://github.com/unocss/unocss/blob/main/packages/preset-wind/src/theme.ts for more examples.

**Comment by robin-dongbin** [comment]
The representation of objects is more intuitive, comfortable, easy to write

**Comment by henrikvilhelmberglund** [comment]
If you want the keyframes on separate lines you could do something like
```
wiggle: `{
          0%, 100% {transform: rotate(-3deg)} 
          50% {transform: rotate(3deg)}
          }`,
```

I could see objects being useful if we could have something like 
```
animation: {
  pulse: { 
    keyframes: '{0%, 100% {opacity:1} 50% {opacity:.5}}',
    durations: '2s',
    timingFns: 'cubic-bezier(0.4,0,.6,1)',
    counts: 'infinite',
  }
}
```
but I don't really see the benefit of the Tailwind notation.

**Comment by zyyv** [comment]
You can try to use this way in [`unocss-preset-useful`](https://github.com/unpreset/unocss-preset-useful/blob/60df1b3f0c59475637dc6b4b10bbaf69c995edbd/test/theme.test.ts#L7-L23).
