### ISSUE TITLE
`bundler usage` of `@unocss/runtime` not working

### ISSUE THREAD

**Issue by CNSeniorious000** [unocss/unocss#3509]
### UnoCSS version

latest

### Describe the bug

I try to use the css-in-js usage of unocss, but if I try to use the bundler usage it fails to generate css.

I took a look of the dom and find that there is an empty `style` tag in `head`.

The CDN usage works fine, but I want to import it and call it because I think initiating it with config instead of use `window.__unocss` in a script tag is more beautiful.

### Reproduction

This is a minimal vanilla ts vite template, which reproduce the bug well:

https://stackblitz.com/edit/vitejs-vite-atta5x?file=src%2Fmain.ts

### System Info

latest Edge on Windows 11

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Because `initUnocssRuntime` takes different config as the uno config:

```ts
initUnocssRuntime({ defaults: config });
```

**Comment by daixiangwen** [comment]
Could you tell me how to configure this? When I use packaged app in mian.js, I can't load the class I assigned in js.

**Comment by intzaaa** [comment]
> Could you tell me how to configure this? When I use packaged app in mian.js, I can't load the class I assigned in js.

https://github.com/intzaaa/RegularFramework/blob/61746951e20c34952ed9578710849df130892824/example/vite/src/main.ts#L1C1-L21C1
