### ISSUE TITLE
Not generate source map in shadow-dom mode

### ISSUE THREAD

**Issue by artmarydotir** [unocss/unocss#3510]
### UnoCSS version

0.58.3

### Describe the bug

I am using Vue version 3 (Custom Element Feature) with Vite and UnoCSS.
After npm install and building (npm run build) [vue-tsc --noEmit && vite build], no sourcemap is generated in shadow-dom mode.
However, if we change the mode to global, the sourcemap will be generated.

![Screenshot 2024-01-14 at 6 30 51 PM](https://github.com/unocss/unocss/assets/11363931/015dfdfb-bc34-4089-b1c0-e43210adddf6)

### Reproduction

stackblitz:
check the **dist** directory to see the broken sourcemap:
[simple btn custom element](https://stackblitz.com/edit/vue-3-composition-api-demo-ohhdu2?file=vite.config.ts)

- [X] The provided reproduction is a [minimal reproducible example](https://stackblitz.com/edit/vue-3-composition-api-demo-ohhdu2?file=vite.config.ts) of the bug.

**Comment by LoTwT** [comment]
Same problem in `vue-scope` mode.

repro url: <https://stackblitz.com/edit/vitejs-vite-8bngod?file=vite.config.ts>
