### ISSUE TITLE
UnoCSS() typescript import error when using "moduleResolution": "NodeNext" in SvelteKit Package

### ISSUE THREAD

**Issue by lumosminima** [unocss/unocss#3512]
### UnoCSS version

0.58.3

### Describe the bug

When using typescript compiler options:
```TS
{
        ...
	"module": "NodeNext",
	"moduleResolution": "NodeNext"
}
```

Calling `UnoCSS()` from `import UnoCSS from 'unocss/vite';` gives error:
```TS
This expression is not callable.
  Type 'typeof import("/home/projects/.../node_modules/.pnpm/unocss@0.58.3_postcss@8.4.33_vite@5.0.11/node_modules/unocss/dist/vite")' has no call signatures.ts(2349)
 ```
This is needed in svelte package so typescript can give error when importing from `../index` rather than `../index.js`. [Svelte Docs](https://kit.svelte.dev/docs/packaging#caveats)

There is also #2617 which is Astro specific but it went stale

### Reproduction

Add `NodeNext` to your `tsconfig.json`:
```
{
	"extends": "...",
	"compilerOptions": {
		...
		"module": "NodeNext",
		"moduleResolution": "NodeNext"
	}
}
```

### System Info

WSL2, Firefox, SvelteKit

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by shellscape** [comment]
@antfu just ran into this today after converting a CJS repo to ESM. issue stems from the export as defined `export { type CompileClassOptions, transformerCompileClass as default };`. That then requires this solution:

```js
import transformerCompileClass from '@unocss/transformer-compile-class';

transformerVariantGroup.default()
```

Looks like y'all need a test around your exports

**Comment by userquin** [comment]
That's the problem with dual package exports using default module exports: we're working to move UnoCSS to ESM first/only with some dual CJS/ESM packages exports here https://github.com/unocss/unocss/pull/3380

Anyway, you can try using `Bundler` module resolution (the new default in kit 2).

**Comment by shellscape** [comment]
@userquin I generally don't have any issues with that using tsup. Ive only run into one edge case in a year of use.

**Comment by userquin** [comment]
The problem is in UnoCSS, not in your application (current version is CJS):

https://arethetypeswrong.github.io/?p=unocss%400.58.5
