### ISSUE TITLE
shadow: inset can't parsed

### ISSUE THREAD

**Issue by lin52025iq** [unocss/unocss#3515]
### UnoCSS version

v0.58.3

### Describe the bug

```html
<div w-300px h-30px un-bg-red shadow="[1px_0_0_0_#000] inset"></div>
<div mt-8px w-300px h-30px un-bg-red shadow="[1px_0_0_0_#000_inset]"></div>
```
In v58, the inset that does not exist in `[1px_0_0_0_#000_inset]` is not parsed correctly. It can be parsed correctly in previous versions eg.v56.

### Reproduction

https://unocss.dev/play/?html=DwEwlgbgBA7gtAZgAxIA4A8oAtFswVwDs4AjAczgCcBTEKAZywEMQB7GAXgCIBtARgwB9JMNEBiFEgC6UMIXrUALlwB8wAPTgIKgFA7QkKAFtFcABwZYuPNlyWipCjTqMW7bvyEjvgiSkFyCopSqhpaukA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDASSarID3fsMBVKtoAvqByNJScoADkFlRMkJCRgoLEoogy8pgW0GmyCoQqarDqABSS0jRZUABcoADaOtK1kUwWkIjhtJWRmhKg7tB8NZF0qJGggQC6XlM6kAAWfIgtAjVl0lEtbR3zi8uRQ6wkyNDqoIcofJjw6uCgCwBu4DRV58ismNDdOoFeTgYrdQa3mciH8lGKAEovI4fMZTIxLNY7JDocD-m4PKUgdJIEwPuAagBGAB0ACZUdImKh4EM5qZuJAqiAoJxifNgF91uMoToZoEIYIgA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmjpAA&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmANCBCXAA5LwCWAbifocSQL5A

![image](https://github.com/unocss/unocss/assets/87741822/acdee386-bf31-4b1e-b325-7fd442b5868e)

### System Info

UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by chu121su12** [comment]
In the meantime, one workaround is to place color last in the bracket
