### ISSUE TITLE
在create-react-app的webpack项目中使用@unocss/webpack会导致sourceMap源代码定位不到，打完debugger定位到的代码是编译后的代码

### ISSUE THREAD

**Issue by badlym** [unocss/unocss#3517]
### UnoCSS version

^0.58.3

### Describe the bug

![image](https://github.com/unocss/unocss/assets/38027590/af15e2aa-37bc-44cf-a3d7-bc83269c3794)
如图所示，我使用create-react-app创建的项目我就在代码出打了一个debugger，但是浏览器调试的时候无法调试源代码
<img width="1580" alt="image" src="https://github.com/unocss/unocss/assets/38027590/0e3555ab-e8f7-4173-8a19-18e4de1554cb">

### Reproduction

我的存储库地址是https://github.com/badlym/cra-test

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by badlym** [comment]
github 我推送不上去，这是我的gitee的存储库地址 
https://gitee.com/liucj2/cra-test

**Comment by badlym** [comment]
现在github上也有代码了， https://github.com/badlym/cra-test。我提交一下代码很辛苦的，希望不要删了这个问题。麻烦您帮我解决一下吧。

**Comment by badlym** [comment]
当我去掉引入 import uno.css 之后就可以正常定位到源码了，请问是什么原因呢？

**Comment by Simon-He95** [comment]
I tested the latest unocss version and it seems to have been fixed.

**Comment by badlym** [comment]
这个问题并没有解决

**Comment by badlym** [comment]
我用的是create-react-app eject之后配置项，这是我的配置表
{
  "name": "cra-test",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@unocss/webpack": "^0.59.2",
    "unocss": "^0.59.2",
    "@babel/core": "^7.16.0",
    "@pmmmwh/react-refresh-webpack-plugin": "^0.5.3",
    "@svgr/webpack": "^5.5.0",
    "@testing-library/jest-dom": "^5.14.1",
    "@testing-library/react": "^13.0.0",
    "@testing-library/user-event": "^13.2.1",
    "@types/jest": "^27.0.1",
    "@types/node": "^16.7.13",
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    "babel-jest": "^27.4.2",
    "babel-loader": "^8.2.3",
    "babel-plugin-named-asset-import": "^0.3.8",
    "babel-preset-react-app": "^10.0.1",
    "bfj": "^7.0.2",
    "browserslist": "^4.18.1",
    "camelcase": "^6.2.1",
    "case-sensitive-paths-webpack-plugin": "^2.4.0",
    "css-loader": "^6.5.1",
    "css-minimizer-webpack-plugin": "^3.2.0",
    "dotenv": "^10.0.0",
    "dotenv-expand": "^5.1.0",
    "eslint": "^8.3.0",
    "eslint-config-react-app": "^7.0.1",
    "eslint-webpack-plugin": "^3.1.1",
    "file-loader": "^6.2.0",
    "fs-extra": "^10.0.0",
    "html-webpack-plugin": "^5.5.0",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^27.4.3",
    "jest-resolve": "^27.4.2",
    "jest-watch-typeahead": "^1.0.0",
    "mini-css-extract-plugin": "^2.4.5",
    "postcss": "^8.4.4",
    "postcss-flexbugs-fixes": "^5.0.2",
    "postcss-loader": "^6.2.1",
    "postcss-normalize": "^10.0.1",
    "postcss-preset-env": "^7.0.1",
    "prompts": "^2.4.2",
    "react": "^18.2.0",
    "react-app-polyfill": "^3.0.0",
    "react-dev-utils": "^12.0.1",
    "react-dom": "^18.2.0",
    "react-refresh": "^0.11.0",
    "resolve": "^1.20.0",
    "resolve-url-loader": "^4.0.0",
    "sass-loader": "^12.3.0",
    "semver": "^7.3.5",
    "source-map-loader": "^3.0.0",
    "style-loader": "^3.3.1",
    "tailwindcss": "^3.0.2",
    "terser-webpack-plugin": "^5.2.5",
    "typescript": "^4.4.2",
    "web-vitals": "^2.1.0",
    "webpack": "^5.64.4",
    "webpack-dev-server": "^4.6.0",
    "webpack-manifest-plugin": "^4.0.2",
    "workbox-webpack-plugin": "^6.4.1"
  },
  "scripts": {
    "start": "node scripts/start.js",
    "build": "node scripts/build.js",
    "test": "node scripts/test.js"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "jest": {
    "roots": [
      "<rootDir>/src"
    ],
    "collectCoverageFrom": [
      "src/**/*.{js,jsx,ts,tsx}",
      "!src/**/*.d.ts"
    ],
    "setupFiles": [
      "react-app-polyfill/jsdom"
    ],
    "setupFilesAfterEnv": [
      "<rootDir>/src/setupTests.ts"
    ],
    "testMatch": [
      "<rootDir>/src/**/__tests__/**/*.{js,jsx,ts,tsx}",
      "<rootDir>/src/**/*.{spec,test}.{js,jsx,ts,tsx}"
    ],
    "testEnvironment": "jsdom",
    "transform": {
      "^.+\\.(js|jsx|mjs|cjs|ts|tsx)$": "<rootDir>/config/jest/babelTransform.js",
      "^.+\\.css$": "<rootDir>/config/jest/cssTransform.js",
      "^(?!.*\\.(js|jsx|mjs|cjs|ts|tsx|css|json)$)": "<rootDir>/config/jest/fileTransform.js"
    },
    "transformIgnorePatterns": [
      "[/\\\\]node_modules[/\\\\].+\\.(js|jsx|mjs|cjs|ts|tsx)$",
      "^.+\\.module\\.(css|sass|scss)$"
    ],
    "modulePaths": [],
    "moduleNameMapper": {
      "^react-native$": "react-native-web",
      "^.+\\.module\\.(css|sass|scss)$": "identity-obj-proxy"
    },
    "moduleFileExtensions": [
      "web.js",
      "js",
      "web.ts",
      "ts",
      "web.tsx",
      "tsx",
      "json",
      "web.jsx",
      "jsx",
      "node"
    ],
    "watchPlugins": [
      "jest-watch-typeahead/filename",
      "jest-watch-typeahead/testname"
    ],
    "resetMocks": true
  },
  "babel": {
    "presets": [
      "react-app"
    ]
  }
}
unocss 我已经更新到了最新的版本，请把我github存储库的代码拉下来跑一下就知道了，这个问题困扰了我很久。因为我的老项目用的cra，现在导致我的老项目无法debugg，严重影响了开发效率。请帮帮忙，特别感谢！

**Comment by Simon-He95** [comment]
@badlym Excuse me, please help me test whether my pr version can solve your problem. You can try to enter my pr version and build, replace the content of `@unocss/webpack/dist` with your local file and then start your local project to see if it can meet your needs
https://github.com/unocss/unocss/pull/3732
<img width="359" alt="image" src="https://github.com/unocss/unocss/assets/57086651/cb65ff59-d61c-4046-bfa6-77ddae0c6a52">
