### ISSUE TITLE
vue2/3 keep-alive + transformerVariantGroup hmr error

### ISSUE THREAD

**Issue by webaddkevin** [unocss/unocss#3518]
### UnoCSS version

0.58.3

### Describe the bug

In a Vue + Unocss project, using the keep-alive component, the code hot update during inactive pages will cause the components containing the "unocss transformerVariantGroup" code to reload as well

### Reproduction

https://github.com/unocss/unocss/assets/20873249/a3925961-8ac3-4bd9-89fc-a610e905fcfc

### System Info
demo：https://github.com/webaddkevin/uno-test

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by webaddkevin** [comment]
demo：https://github.com/webaddkevin/uno-test

**Comment by MrFoxPro** [comment]
Probably I have similiar issue with SolidJS + UnoCSS as well. Enabling `transformerVariantGroup` make Solid's HMR go crazy on first run. But then, after caching. it works fine.

**Comment by MrFoxPro** [comment]
Well, it doesn't fix issue, but whole page refresh is not so annoying
Had to disable HMR at all due UnoCSS continues to infinity refresh iteself

**Comment by webaddkevin** [comment]
> Well, it doesn't fix issue, but whole page refresh is not so annoying Had to disable HMR at all due UnoCSS continues to infinity refresh itself



> Probably I have similiar issue with SolidJS + UnoCSS as well. Enabling `transformerVariantGroup` make Solid's HMR go crazy on first run. But then, after caching. it works fine.
> 
> UPD: @webaddkevin setting `mode: "per-module"` in config fixed issue for me.



> Probably I have similiar issue with SolidJS + UnoCSS as well. Enabling `transformerVariantGroup` make Solid's HMR go crazy on first run. But then, after caching. it works fine.
> 
> UPD: @webaddkevin setting `mode: "per-module"` in config fixed issue for me.

Thanks, setting 'mode: "per-module" is useful, problem solved

**Comment by webaddkevin** [comment]
> Probably I have similiar issue with SolidJS + UnoCSS as well. Enabling `transformerVariantGroup` make Solid's HMR go crazy on first run. But then, after caching. it works fine.
> 
> UPD: @webaddkevin setting `mode: "per-module"` in config fixed issue for me.

Thanks, setting 'mode: "per-module" is useful, problem solved

**Comment by MrFoxPro** [comment]
Seems like configuring `transformerVariantGroup({ separators: [":"] })` reduce flickering for me. My theory is that rules like `c-blue-important` can affect plugin when separator `-` is used.

**Comment by MrFoxPro** [comment]
https://github.com/unocss/unocss/assets/17229619/b0625e52-1145-447b-8207-053fc85c034a

**Comment by Simon-He95** [comment]
> unocss.mp4

Can you provide a reproducible demo?

**Comment by MrFoxPro** [comment]
> > unocss.mp4
> 
> Can you provide a reproducible demo?

I'd be happy too, but I have large project. I'll try

**Comment by MrFoxPro** [comment]
More clear description of my problem:

I have SolidJS project with vite-plugin-solid, HMR enabled. I have self-made "keep-alive" components. They probably very different from OP's Vue components. 
Anyway, after enabling `transformerVariantGroup`, navigating to any "keep-alive" page triggers HMR for many components on page and page flickers. Sometimes new page doesn't load at all. However, after navigating multiple times seems components become cached and it works kinda ok. Switching to `mode: "per-module"` fixes this flickering, but, if exception throws in my code, in about half of times it starts to infinity refresh HMR as [shown on video.](https://github.com/unocss/unocss/issues/3518#issuecomment-2075149157)

I'm not sure I can provide repdoducable demo, because I have pretty large project which is closed-source for now. But, if any maintainer is interested to help and fix this, I can send project in PM. 

Also, I tried to use https://github.com/unocss/unocss/pull/3741 branch, but wasn't able to. I wasn't able to correctly replace pnpm dependency with local one. Is there a complete guide?

**Comment by Simon-He95** [comment]
> vite

@MrFoxPro If possible, I hope you can streamline the project and send it to me, and I can help debug it.

**Comment by Simon-He95** [comment]
> > > vite 迅速地
> > 
> > 
> > @MrFoxPro If possible, I hope you can streamline the project and send it to me, and I can help debug it.如果可以的话，希望您能把项目精简一下发给我，我可以帮忙调试。
> 
> Ok,seems like the main problem is resolved with using `mode: 'per-module'` in dev mode. When using "global" it changes Solid plugin HMR behaviour, namely: it starts reloading all components dependening on target instead of only target itself. Repro & demo:好吧，似乎主要问题是通过在开发模式下使用 `mode: 'per-module'` 解决的。当使用“global”时，它会改变 Solid 插件 HMR 行为，即：它开始重新加载依赖于目标的所有组件，而不仅仅是目标本身。重现和演示：
> 
>  unocsshmr.mp4 
> https://github.com/MrFoxPro/unocss-hmr-bug
> 
> But since `per-module` is experimental, it doesn't work well, like in [this video](https://private-user-images.githubusercontent.com/17229619/325270712-b0625e52-1145-447b-8207-053fc85c034a.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzODk2NTcsIm5iZiI6MTcxNDM4OTM1NywicGF0aCI6Ii8xNzIyOTYxOS8zMjUyNzA3MTItYjA2MjVlNTItMTE0NS00NDdiLTgyMDctMDUzZmM4NWMwMzRhLm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDExMTU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5NTliOGM4ZGI1ZDQ0Yjc3NGI3ZjE3NmJjYTI1N2I2Y2FmNjc4ZTAwNzIwOTc0OTc1NWEwN2I2MzJmNWU4MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JDvF309WWnCmPeVMSDPT9YeYRF4J9jFvktcmQVqkWYg) (I wasn't able to reproduce this so far) and also seems like styles are applied in different order, so result is kinda inconsistent with build output. It also produces large number of CSS files, so firefox slows down a lot.但由于 `per-module` 是实验性的，它效果不佳，就像在这个视频中一样（到目前为止我无法重现这个），而且似乎样式以不同的顺序应用，所以结果有点与构建输出不一致。它还会产生大量的 CSS 文件，因此 Firefox 的运行速度会变慢很多。

Hi,@MrFoxPro  
Can you please find the corresponding code in your project and then also pay attention to the following content to see the result?
<img width="1230" alt="image" src="https://github.com/unocss/unocss/assets/57086651/bc5a69e0-646e-46af-bf2e-4457ba89d87c">

**Comment by MrFoxPro** [comment]
@Simon-He95 
Seems like this helped and now only affected module is being reloaded in HMR. But I need to spend some time until I can say it works overall correctly. Thank you very much!
