### ISSUE TITLE
[🐞Bug]: `place-items-center` is not working when attributifying `grid` and `flex`

### ISSUE THREAD

**Issue by xsjcTony** [unocss/unocss#3525]
### UnoCSS version

latest

### Describe the bug

Below is not working for `place-items-center`. It should be supported in both `grid` and `flex`, just like `justify-center`, `items-center`, `justify-items-center` and `content-center`
```html
<div h-50vh grid="~ place-items-center">
  Should be centered, but doesn't work
</div>

<div h-50vh grid="~ justify-items-center items-center">
  justify-items-center and items-center works
</div>
```

### Reproduction

https://unocss.dev/play/?html=DwEwlgbgBAFgtAVgAwRlA5gJzCAvAIgD8oAHAGwEMBjAUzjABcaBbAZzloDsnN8A%2BAFBQoAZRgB7AK5kQUAEY0oXHjRAAaeZIZQQ4mq04BybQHdxmANYDgAenARB1%2B7EQo0WHAWIArSawZgAGYAnvRMbBw03DSYUIws7Mox-EJQvv5BofERSbEUnLLZiVE8UGaWrNZ2kIJAA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAqrhJajfYwIIwxTAARgFcYwLAE8kAXzhYoEEHADkw1gGM6dZUlCRY1WgxgAlDCAAqEAAoAPOQqXKAAmoia6Aek7GAtLRBfGAhfMFsdJCQMW314TCwAQ2EAGzjsPEJiMgAKZA4jRjoALjgAbSp8rmZWbIBKdlRDKt5%2BIVFxCTqqAF0ZWqQgA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgTgpgzgDg9gOygSwG4RALgGYEMA2UEANCAC5i5LZxgC2AEmXflnoSeZdbXQMIBXKGTj8AymLYEiAXyA

### System Info

N/A

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
https://unocss.dev/play/?html=DwEwlgbgBAFgtAVgAwRlA5gJzCAvAIgD98oAHAGwEMBjAUzjABdaBbAZzjoDtnMA%2BAFBQoAZRgB7AK7kQUAEa0o3XrRAAaeZMZQQ42my4BybQHdxmANYDgAenARB1%2B7EQo0WHAUJQAVpLaMYABmAJ4MzOyctDy0mFBMrBzKsfiCwn4BwWEJkclxlFyyOUnRvFBmlmzWdpCCQA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAqrhJajfYwIIwxTAARgFcYwLAE8kAXzhYoEEHADkw1gGM6dZUlCRY1WgxgAlDCAAqEAAoAPOQqXKAAmoia6Aek7GAtLRBfGAhfMFsdJCQMW314TCwAQ2EAGzjsPEJiMgAKZA4jRjoALjgAbSp8rmZWbIBKdlRDKt5%2BIVFxCTqqAF0ZWqQgA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgTgpgzgDg9gOygSwG4RALgGYEMA2UEANCAC5i5LZxgC2AEmXflnoSeZdbXQMIBXKGTj8AymLYEiAXyA

**Comment by xsjcTony** [comment]
@Simon-He95 Yeah I got the idea it's working when standalone, but
- I prefer to group corresponding utilities into a set e.g. (flex, grid)
- It doesn't make sense that `place-items` is the only one that's not supported. i.e. either we support it, or we should drop support for others too (`items-*`, `justify-*`, etc.)
- ⚠️There's a current bug in JSX preventing me using that standalone syntax without `=""`: https://github.com/unocss/unocss/issues/3471

So I believe this is truly a BUG / Feature Request, which should not be closed.

**Comment by Simon-He95** [comment]
Got it～，I'll check it out later

**Comment by xsjcTony** [comment]
I do want to send a PR but unfortunately I can't really understand how attributify actually works in a short period😥.
I'll learn from how this is being resolved. ☺️

**Comment by xsjcTony** [comment]
@Simon-He95 Emm, so, the attributify is just modifying the extractor but nothing else right? For why `flex="items-center"` works, it's because `className="flex-items-center` also works.

In other words, for a given `key="value"` pair, it's the same as `key-value` or `key:value` (based on separators or rules defined) in string format right?

If I'm correct with above, it then makes a lot of sense how it works. I was trying to find how to fix it in the `preset-attributify` package but essentially that's not where it should be. 🤣

**Comment by Simon-He95** [comment]
`flexGridJustifiesAlignments`
The reason I modified it is because it is only related to `place-`. If you want it to take effect as you want, you should also need to configure the corresponding rules.
<img width="791" alt="image" src="https://github.com/unocss/unocss/assets/57086651/28f94549-8722-4d55-a298-71eea1a4b6cb">

**Comment by xsjcTony** [comment]
Cheers. let me ask a bit clearly.
Please look at this example: https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIBmcCmAPAWgFsFCkiAuAB0RhwLABccikC6A7ZgJ3Sm3wYSZSjQR0GzVuxxccvAHwBGAEwBmYAHpwEBUA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCqWEZF1tAgjDFMAEYCuMYOgCecAL5x0UCCDgByPowDGVKnIBQ61AA9IsFBgCGfADbw0mHPkLAiACgTq45SjRhUAXHADaLNwwg7AEpmV3ZObn5BEWCAXRJ1MSD1IA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwBpxp5k0BhAVzjCVQoGVHNs8iTZEVUAJMVDla4CAXyA

Why variants like `max-sm:` , `md:` , etc. works in `flex="***"` but not `flex-max-sm:***` ?
I know that I should use `max-sm:flex-place-items-center` instead but wondering how those variants are being put to prefix position😭

**Comment by Simon-He95** [comment]
> Cheers. let me ask a bit clearly. Please look at this example: https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIBmcCmAPAWgFsFCkiAuAB0RhwLABccikC6A7ZgJ3Sm3wYSZSjQR0GzVuxxccvAHwBGAEwBmYAHpwEBUA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCqWEZF1tAgjDFMAEYCuMYOgCecAL5x0UCCDgByPowDGVKnIBQ61AA9IsFBgCGfADbw0mHPkLAiACgTq45SjRhUAXHADaLNwwg7AEpmV3ZObn5BEWCAXRJ1MSD1IA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwBpxp5k0BhAVzjCVQoGVHNs8iTZEVUAJMVDla4CAXyA
> 
> Why variants like `max-sm:` , `md:` , etc. works in `flex="***"` but not `flex-max-sm:***` ? I know that I should use `max-sm:flex-place-items-center` instead but wondering how those variants are being put to prefix position😭

<img width="479" alt="image" src="https://github.com/unocss/unocss/assets/57086651/7c4fc159-990b-4a4f-9bcb-1f057617d3cc">

because `flex="max-sm:flex-place-items-center"` will be transformed to `flex-place-items-center` after `matchVariants`

<img width="881" alt="image" src="https://github.com/unocss/unocss/assets/57086651/b9e5b908-1711-4c86-8995-e9d7bc0eef84">
