### ISSUE TITLE
feat(preset-mini): remove outline-color in color properties

### ISSUE THREAD

**Issue by mrguamos** [unocss/unocss#3527]
### Clear and concise description of the problem

changes made with this PR [#2116](https://github.com/unocss/unocss/pull/2116) were actually reverted from tailwind  
https://github.com/tailwindlabs/tailwindcss/pull/10604

### Suggested solution

perhaps we should also revert these?

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Simon-He95** [comment]
Are you interested in submitting a PR?

**Comment by henrikvilhelmberglund** [comment]
Example of the issue: https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIAOBaAjAJnQD4AoKKYAIwFcAXWgewDtZEUNaAnBJpMWsMygAzBjGpIAXNSYgAppzhgmckWImSGdJSuxNmc4gCE6jJsAD0Nes1LkqpofGRp0XHnwFDR4qTPmKyqo%2BGlq0OnJ6BsaO5laxpJbgEKRAA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6hU4AGYJwAYUrw5AcwA0obnUjhEAQUQNY2AK6JYMgJ6btUPQEkmyyLZ16AqlVABfUDJpKTlAAclMqJkhIEMFBYlFEKVlMU2hE6TlCJRVYVQAKcUFQUEQAC3BOcAAuCSLi0Ex4LkwLZRrC%2BvqAa3ArAMxKyHa6zuKAd1zVPBqAAw7RzoAGAFJNAEZFlYkGRsgZPk4awMQW8DyAEnEAWRbSgDoaRtQgvI2ASgAqDZ9pVTe-EYLUAAVi24h28D2ByOlBOrDyyEuNzKDyeL3eX0WP3Afx8gIWPhm6nxvmJC1QpkerUhwyBoAmqim1VCa2iZNGPnZnQsnAQqgAYjTanSGUyaiFwJhdBx4MhKOYQlz6pySdpKNxwPxYFBaUCQCVHpD9jROHLGKoEA14KhQNhMEwujJ7fgAG4YEywOCIKygcp0EkqhbOcICXULUXTUIITKwViKgNKwOk2LFGipHWgADamZCTFMkEQQVo6cVElAzmgfHFdFQIV8AF16%2BzIKU%2BIg86HhfVc-nC6aW22OyFxawSMhoKoSsQUHxGqpwL7KC7NVVRyhWJhoPHikm7LpO5nAXvPFQ8m8lceDEZGGYLNYzxf3IgnC4CiTIExN8y1ncAExK4omFQeBxVKIxuCGEAoE4O4W2AbdlXPOom0EHw3kEIA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmAvkA
