### ISSUE TITLE
[Feature Proposal] - Safelist values should have access to RuleContext

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [unocss/unocss#3531]
### Clear and concise description of the problem

Variants, rules and shortcuts supports syntax that allows to access RuleContext object that contains active theme and other useful information. Safelist for some reason doesn't support such syntax which prevents generating safelist based on main project configuration.

### Suggested solution

I will provide a practical example why access to theme might be needed.
Let's suppose we want to generate safelist for utility on all media breakpoints specified in the project.
In theme we may have something like this:
```
const breakpoints = {
  "md": 768,
  "lg": 1024
}
...
theme: {
    screens: mapObject(breakpoints, (size) => `${size}px`),
}
```

than I would like to access those screens in my safelist to generate utility on those resolutions

```
safelist: ['md:p-1 lg:m-1'] // Currently I have to define them manually which is misaligned with a theme
```

sagelist should allow such syntax: 
```
safelist: [( { theme } ) => Objec.keys(theme.screens).map(mq => `${mq}:m-1`)]
```

### Alternative

At the moment I have to manually import needed data from a JSON file but this is inflexible solution taking into account that my project uses Nuxt layers where every layer potentially can override/augment Uno theme object. So breakpoints as any other parts of config are determined only once `unocss:config` Nuxt hook was executed. 

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
I am not against it. Feel free to PR - tho I am not sure if the timing allows it to have such context, but if we do, happy to have that capability
