### ISSUE TITLE
[Feature Proposal] 'object-' part should be optional when specifying object-fit utilities 

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [unocss/unocss#3534]
### Clear and concise description of the problem

I would like to have a way to specify shorter versions of **object-fit** rules

Current implementation is: 
https://github.com/unocss/unocss/blob/8505f48d4ccba055c0613bd22f120312447682ca/packages/preset-wind/src/rules/static.ts#L70
```
// object fit
  ['object-cover', { 'object-fit': 'cover' }],
  ['object-contain', { 'object-fit': 'contain' }],
  ['object-fill', { 'object-fit': 'fill' }],
  ['object-scale-down', { 'object-fit': 'scale-down' }],
  ['object-none', { 'object-fit': 'none' }],
```

```
import type { Rule } from 'unocss'

export const object: Rule[] = [
  ['cover', { 'object-fit': 'cover' }],
  ['contain', { 'object-fit': 'contain' }],
  ['fill', { 'object-fit': 'fill' }],
  ['scale-down', { 'object-fit': 'scale-down' }]
]

```

### Suggested solution

Suggested rules with object-
```
// object fit
  ['/^(:?object-)cover/', { 'object-fit': 'cover' }],
  ['/^(:?object-)contain', { 'object-fit': 'contain' }],
  ['/^(:?object-)fill', { 'object-fit': 'fill' }],
  ['/^(:?object-)scale-down', { 'object-fit': 'scale-down' }],
  ['object-none', { 'object-fit': 'none' }],
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
I am not sure about this - usually I'd like to avoid one-word utility as it can create necessary false positive (we have quite a few from Tailwind that I want to remove but can't 🫣)

So, I'd take a no for the official preset. But feel free to do it on userland as you already did :)
