### ISSUE TITLE
[Feature Proposal] - Allow 'flex-' to be optional when specifying flex-wrap utilities

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [unocss/unocss#3535]
### Clear and concise description of the problem

I would like to use a shorter syntax when specifying flex wrap behavior

**Example:**
class="flex flex-wrap" => class="flex wrap"

**Current implementation:**
https://github.com/unocss/unocss/blob/8505f48d4ccba055c0613bd22f120312447682ca/packages/preset-mini/src/_rules/flex.ts#L30
```
// wraps
  ['flex-wrap', { 'flex-wrap': 'wrap' }],
  ['flex-wrap-reverse', { 'flex-wrap': 'wrap-reverse' }],
  ['flex-nowrap', { 'flex-wrap': 'nowrap' }],
```

### Suggested solution

```
// wraps
  ['/^(:?flex-)wrap/', { 'flex-wrap': 'wrap' }],
  ['/^(:?flex-)wrap-reverse', { 'flex-wrap': 'wrap-reverse' }],
  ['/^(:?flex-)nowrap', { 'flex-wrap': 'nowrap' }],
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
I am not sure about this, as it can create confusion with whitespace: nowrap and so

**Comment by AndrewBogdanovTSS** [comment]
Yeah, makes sense. In our project, we use flex wrap properties way more frequently than whitespace so it's more convenient to use the flex version with shorter syntax, and for whitespace just specify it in full but I agree that from the point of common usage, it may be debatable. Closing.
