### ISSUE TITLE
[Feature Proposal] Add support for 'font-stretch' utilities

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [unocss/unocss#3536]
### Clear and concise description of the problem

I would like to be able to specify font-stretch CSS properties with Uno utility classes

### Suggested solution

```
// Font Stetch
[/^(:?font-)stretch-(.*)$/, ([, c]) => ({ 'font-stretch': c })],
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Sure! Tho we should have a more strict handling for the value part similar to other rules.
