### ISSUE TITLE
autocomplete ignores user snippets in vscode when using the unocss extension

### ISSUE THREAD

**Issue by 2-NOW** [unocss/unocss#3537]
### UnoCSS version

0.58.4

### Describe the bug

I'm using `cl` in vscode by registering `className="$1"` as a snippet
`<div cl` // When typing up to this point, `cl` as a snippet should be recommended.
However, clear-both is recommended.

<img width="310" alt="image" src="https://github.com/unocss/unocss/assets/71202076/5abe2307-49fc-4bd1-850d-cf30b58196f2">

If i disabled the unocss extension, the correct snippet will be recommended.

<img width="290" alt="image" src="https://github.com/unocss/unocss/assets/71202076/ff86618d-f4f3-4689-88a2-03f7b456874c">

### Reproduction

If you type `<div cl` in order, UNOCSS's suggestion takes precedence.
`<div cl + backspace + l` is correctly snippet and suggestion together.

I'd like to change the settings so that vscode's suggestions take precedence even when no backspace is entered, or that unocss suggests autocomplete for the area after `className=`.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
I think so too. Some components will provide hints for their internal props, but as unocss hints on attributes will make it difficult for me to find hints for their internal props. What I want is that there is a switch that is only for classes. There are unocss prompts only in the attribute. The other way is to find ways to reduce the unocss code prompts in the attribute.

**Comment by Preyou** [comment]
+1

**Comment by Simon-He95** [comment]
<img width="279" alt="image" src="https://github.com/unocss/unocss/assets/57086651/922aad76-3bfa-4e57-ad8c-0524614eb212">
Has this issue been fixed in the latest version? It seems that the performance is as expected. I have closed it for now. If there is any problem, I can open it again at any time.

**Comment by 2-NOW** [comment]
I have confirmed that the problem is not reproduced in the latest version 0.58.6 ! Thanks
