### ISSUE TITLE
'unocss' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by xsjcTony** [unocss/unocss#3545]
### UnoCSS version

latest

### Describe the bug

Following the guide in https://unocss.dev/integrations/cli, but turns out it's not working.
![Snipaste_2024-02-01_22-34-09](https://github.com/unocss/unocss/assets/45784210/5e3d27c2-1255-4782-a34d-a915353bf474)

### Reproduction

This is a minimal repo that's created by `create-next-app` with `uno.config.ts` setup. Currently at the stage to generate `uno.css` by CLI but failed to do so.
https://github.com/xsjcTony/PokeTool

### System Info

Windows 11, Chrome 121, Next.js 14

![Snipaste_2024-02-01_22-40-50](https://github.com/unocss/unocss/assets/45784210/bd742ec2-e090-41a2-96e2-349bbf8311ad)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by xsjcTony** [comment]
Turns out the doc is incorrect, at least for `pnpm`.

If only `unocss` is installed, then the binary file won't be included in the `.bin` folder:
![Snipaste_2024-02-02_19-48-02](https://github.com/unocss/unocss/assets/45784210/0e963f0e-a2db-491f-bde7-fa9995d2525b)

After installing `@unocss/cli` explicitly:
![Snipaste_2024-02-02_19-49-09](https://github.com/unocss/unocss/assets/45784210/ba750515-094a-42a8-a7df-37e584440945)

@antfu Please confirm whether the above is the expected behaviour. If yes, then we need to update the doc correspondingly.

**Comment by antfu** [comment]
It seems we don't have `bin` field in `unocss`. And we are not deps in `@unocss/cli` by `unocss` probably because the deps size - I guess it's better to keep it as-is, and fix the docs. Thanks!
