### ISSUE TITLE
Custom content property doesn't work with nested structure

### ISSUE THREAD

**Issue by ErriourMe** [unocss/unocss#3546]
### UnoCSS version

0.58.4

### Describe the bug

I'm trying to set point delimiters between elements (First * second * third).
Class to resolve this my thing: `[&>div+div]:before:content-['•']`. But it doesnt work. It works for any other classes, for empty content (`[&>div+div]:before:content-empty`), but custom content can't be accepted.
Looks like a bug.

### Reproduction

[UnoCSS Playground link](https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIAOBaArOgPgCgopRICB1ACwQBcoBJKAdwQDsG6B7KJAU35Qw7KHWpCY3EEIAU4sEmFKEUAEYBXAOYBKAFzAA9OAjFS5CCVKxEKDADM4-AB7C6-ALZJsMfp34ATurcATIB2ACMUDgALFAA2gBkBCYA1CYAunpq-PYh-HpS-pzY8QDkgEQEZRkJyWmZ2bn5eh7OpbiYzhnoVmbWFgQAYmABSHRGJn3mkwDK-EUgExRW0xQAKtQji8bL5jumRFYWNsho6B50eIQ09FAIMHQaCHBwAJ6sIQDWSixg4lD2DQvPh0AIaB4aAIFJYHVaWawnOzoRwuNyeby%2BfxBNQhMKRaLYOJJFKQdKQLI5PJQwrcYqXTyYOjvYn1cmNKkFVrtTrdXorMiTYajcb7KYCihzBYwsUDDZbaVHUWHOGIs4XK5UL4IALcDTsEAAGlYtAYzDYnDEvAEQhEYgk6h1LAEAQMSpV8FODicrj%2B6J8fnc2NxgXxsUI-IGQrGCoRxw9SMpzSK7hK5SqNUT1K58Q6XUIktp20mEZMqowmYKyYDpUq1XUTSzbRzPMIctCMbISoVQA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDASSarID3fsMBVKtoAvqByNJScoADkFlRMkJCRgoLEoogy8pgW0GmyCoQqarDqABSS0jRZUABcoADaOtK1kUwWkIjhtJWRmhKg7tB8NZF0qJGggQC6XlM6kAAWfIgtAjVl0lEtbR3zi8uRQ6wkyNDqoIcofJjw6uCgCwBu4DRV58ismNDdOoFeTgYrdQa3mciH8lGKAEovI4fMZTIxLNY7JDocD-m4PKUgdJIEwPuAagBGAB0ACZUdImKh4EM5qZuJAqiAoJxifNgF91uMoToZoEIYIgA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmAvkA)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by study-heitaitou** [comment]
fucku

**Comment by henrikvilhelmberglund** [comment]
I don't really know why but you need to place `before:` in front of the arbitrary selector for it to work: 
https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIAOBaArOgPgCgopRICB1ACwQBcoBJKAdwQDsG6B7KJAU35Qw7KHWpCY3EEIAU4sEmFKEUAEYBXAOYBKAFzAA9OAjFS5CCVKxEKDADM4-AB7C6-ALZJsMfp34ATurcATIB2ACMUDgALOr89iH8egDaAGQEJgDUJgC6elL%2BnNgpAOSARASluVDpmZA5kPlqCUl6Hs4luJjOuehWZtYWBABiYAFIdEYmA%2BbTAMr8hSBTFFazFAAq1GPLxqvme6ZEVhY2yGjoHnR4hDT0UAgwdBoIcHAAnqwhANZKLGDiKD2DRvPh0AIaJ4aALJFZHdaWaxnOzoRwuNyeby%2BfxBNQhMKRaLYOLNRIw1IZbJ5ArcIrXTyYOifWpUxp6Umtdqdbq9fprMjTUbjSaHGYCigLJZwsVDLY7aUnUXHBHIi5XG5UH4IALcDTsEAAGlYtAYzDYnDEvAEQhEYgk6h1LAEAQMSpV8HODicrgBmJ8fncuPxgUJsUI-KGQomCqRpw9KI55MK7mKZUq1UTyS5KS6PUIktpu2mEZMqowmZpdJKFSq8TJWY6OZ5hDloRjZCVCqAA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDASSarID3fsMBVKtoAvqByNJScoADkFlRMkJCRgoLEoogy8pgW0GmyCoQqarDqABSS0jRZUABcoADaOtK1kUwWkIjhtJWRmhKg7tB8NZF0qJGggQC6XlM6kAAWfIgtAjVl0lEtbR3zi8uRQ6wkyNDqoIcofJjw6uCgCwBu4DRV58ismNDdOoFeTgYrdQa3mciH8lGKAEovI4fMZTIxLNY7JDocD-m4PKUgdJIEwPuAagBGAB0ACZUdImKh4EM5qZuJAqiAoJxifNgF91uMoToZoEIYIgA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmAvkA

**Comment by RebeccaStevens** [comment]
> I don't really know why but you need to place `before:` in front of the arbitrary selector for it to work

`before:` is a variant so it needs to go first.
A variant modifies what comes after it, in this case modifying the `[&>div+div]` selector to select the `:before` of it.

**Comment by henrikvilhelmberglund** [comment]
> > I don't really know why but you need to place `before:` in front of the arbitrary selector for it to work
> 
> `before:` is a variant so it needs to go first. A variant modifies what comes after it, in this case modifying the `[&>div+div]` selector to select the `:before` of it.

Isn't the selector also a variant? I don't really see why the order should matter here, it also works fine in the Tailwind playground https://play.tailwindcss.com/wPJpEcPN78

**Comment by RebeccaStevens** [comment]
> > > I don't really know why but you need to place `before:` in front of the arbitrary selector for it to work
> > 
> > 
> > `before:` is a variant so it needs to go first. A variant modifies what comes after it, in this case modifying the `[&>div+div]` selector to select the `:before` of it.
> 
> Isn't the selector also a variant? I don't really see why the order should matter here, it also works fine in the Tailwind playground [play.tailwindcss.com/wPJpEcPN78](https://play.tailwindcss.com/wPJpEcPN78)

Ahh, yes sorry, my bad. `[&>div+div]` and `before` are both variants. `content-['•']` is the selector.
This does in fact look like a bug to me.

**Comment by RebeccaStevens** [comment]
Did a small amount of digging.

With `before:[&>div+div]:content-['•']`, the `pseudo:before` variant get allied first just fine.
But then the `variables` variant matches twice, instead of once.
The first match returns `content-['•']` as the next part to match against (this is what we want).
But the second match returns `content-['`.

This issue isn't obviously noticeable though as one of the matches is right.

The issue with `[&>div+div]:before:content-['•']` is that it only matches once and that returns `before:content-[` as the next part to match against.

The issue seems to be caused by the double use of square brackets.

**Comment by Simon-He95** [comment]
https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIAOBaArOgPgCgopRICB1ACwQBcoBJKAdwQDsG6B7KJAU35Qw7KHWpCY3EEIAU4sEmFKEUAEYBXAOYBKAFzAA9OAjFS5CCVKxEKDADM4-AB7C6-ALZJsMfp34ATurcATIB2ACMUDgALFAA2gBkBCYA1CYAunpq-PYh-HpS-pzY8QDkgEQEZRkJyWmZ2bn5eh7OpbiYzhnoVmbWFgQAYmABSHRGJn3mkwDK-EUgExRW0xQAKtQji8bL5jumRFYWNsho6B50eIQ09FAIMHQaCHBwAJ6sIQDWSixg4lD2DQvPh0AIaB4aAIFJYHVaWawnOzoRwuNyeby%2BfxBNQhMKRaLYOJJFKQdKQLI5PJQwrcYqXTyYOjvYn1cmNKkFVrtTrdXorMiTYajcb7KYCihzBYwsUDDZbaVHUWHOGIs4XK5UL4IALcDTsEAAGlYtAYzDYnDEvAEQhEYgk6h1LAEAQMSpV8FODicrj%2B6J8fnc2NxgXxsUI-IGQrGCoRxw9SMpzSK7hK5QqACZquomtSufEOl1CJLadtJhGTKqMInqcmA6VKhEs9XOW18zzCHLQjGyEqFUA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDASSarID3fsMBVKtoAvqByNJScoADkFlRMkJCRgoLEoogy8pgW0GmyCoQqarDqABSS0jRZUABcoADaOtK1kUwWkIjhtJWRmhKg7tB8NZF0qJGggQC6XlM6kAAWfIgtAjVl0lEtbR3zi8uRQ6wkyNDqoIcofJjw6uCgCwBu4DRV58ismNDdOoFeTgYrdQa3mciH8lGKAEovI4fMZTIxLNY7JDocD-m4PKUgdJIEwPuAagBGAB0ACZUdImKh4EM5qZuJAqiAoJxifNgF91uMoToZoEIYIgA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmAvkA
