### ISSUE TITLE
Latest @iconify/utils seems to break unocss in nuxt

### ISSUE THREAD

**Issue by sfxcode** [unocss/unocss#3552]
### UnoCSS version

unocss nuxt 0.58.4

### Describe the bug

pnpm update --latest caused this issue -> [vite-node] [ERR_MODULE_NOT_FOUND] /__uno.css

### Reproduction

add ```"@iconify/utils": "2.1.21"``` to your package.json

### System Info

------------------------------
- Operating System: Darwin
- Node Version:     v20.11.0
- Nuxt Version:     3.10.0
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.15.1
- Builder:          -
- User Config:      devtools, ssr, runtimeConfig, modules, content, i18n, primevue, css, build, sourcemap
- Runtime Modules:  nuxt-primevue@0.2.2, @formkit/nuxt@1.5.5, @unocss/nuxt@0.58.4, @pinia/nuxt@0.5.1, @nuxtjs/i18n@8.0.1, @nuxt/content@2.11.0, @vueuse/nuxt@10.7.2
- Build Modules:    -
------------------------------

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sfxcode** [comment]
Fix dependency to ```"@iconify/utils": "2.1.20"``` fix it for the moment

**Comment by wtto00** [comment]
Yes, I have encountered this issue as well. Here is an example project: [stackblitz](https://stackblitz.com/edit/withastro-astro-4yqdzp?file=package.json,uno.config.ts,astro.config.mjs,src%2Fpages%2Findex.astro&title=Astro%20Starter%20Kit:%20Basics)

I have defined a custom icon named `custom-back`.

Using `i-custom-back` will throw an error, while `i-custom:back` works fine.

PS: In Astro with UnoCSS parsing, comments do not prevent the code from being processed. As shown in the example project, even if you comment out `i-custom-back`, it will still throw an error. This means that UnoCSS parses the commented templat

**Comment by userquin** [comment]
https://github.com/unocss/unocss/issues/3551#issuecomment-1925754688

**Comment by userquin** [comment]
should be fixed in new `@iconify/utils` release, update the dependency or use  `^2.1.22`: https://stackblitz.com/c/edit/unocss-unocss-v79njm?file=package.json

**Comment by wtto00** [comment]
```shell
rm -rf node_modules/ pnpm-lock.yaml
pnpm i
```
This will download and install a new version of `@iconify/utils`. `^2.1.22` has fixed it for me.

**Comment by sfxcode** [comment]
Latest version 2.1.22 fixed my issue also. Will close this issue for now. Thanks to everybody ...
