### ISSUE TITLE
@apply Directives Not Working With Custom Variant

### ISSUE THREAD

**Issue by mr-thomas-z** [unocss/unocss#3574]
### UnoCSS version

0.58.5

### Describe the bug

I followed the docs to wrap custom variant with quotes (e.g., `"hover:bg-white"`, but the output CSS was not converted. Instead, here are the before and after code:
|Original|Converted|
|:-|:-|
|`@apply flex flex-row p-4 text-white "hover:color-red-400";`|`display:flex;flex-direction:row;padding:1rem;--un-text-opacity:1;color:rgb(255 255 255 / var(--un-text-opacity));`<br><br>(custom variant is gone?)|
|`@apply "hover:bg-white" "hover:bg-opacity-5";`|`@apply "hover:bg-white" "hover:bg-opacity-5";`<br><br>(custom variant is not converted?)|

The only way I would get it working is to use a `--at-apply:` for each custom variant class. I'm not sure if this is the intended behavior or a bug.
|Not working|Worked|
|:-|:-|
|`@apply "hover:bg-white" "hover:bg-opacity-5";`|`--at-apply: 'hover:bg-white';`<br>`--at-apply: 'hover:bg-opacity-5';`|

### Reproduction

https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIAWYQgKYB2UADgLQBMUARnAPYwDW6UOGxATrQGZhx6kBbQgFd0APgBQASGDC4sRCgxwwSAC6kCtAnhKkADOOkyVkqeeAIomdni4YAxMzUJ2AczxqMAfRoICTGbmMkjE-mIAErRCYR7AAPSh4cYy8QhBCaYSxsBZwZbWtvbo8RzcvHjiAGpgeADuUAAKnDx8Cek58Vk5eRZWIAgupEgQeHBqeAxgGhxjtAggpAMuGNxczDZ2GGnCaphdtG60u%2BIAModQx2rtGV1gZglykgngEGJAA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDASSarID3fsMBVKtoAvqByNJScoADkFlRMkJCRwjx8iKAMmPCQcnyc4DQAIrB0LLAAblAhYRGRAAIxlHGQwOmZ2TS5NGhF4CXlCQDcgoLEoqmycpgW0GPyiipqsOoAFJLSLVk5eZAAXKAA2uttHYXF1n1LAJQAul40U1C7ezrSe5FMFpCI4bT3kZoSoHc0D4u0idFQkVAgRuOhh0kgAAsUu8BLtVtIou9Pt9EcirJFQawSMhoOo0sQUHwMupwKAkeUaNsiShWJhoH8dIEvE4DKj9s9vM5EP5KJcvI4fMZTIxLNY7GKBTzXO5MisBfCmGzwLsAIwAOgATOKMUxUPBQQjTNwdiAoJw9YjgByMVCLl4YYELoIgA&css=JAVwNgBGCWEN4ChjAAIEMAOGwE8ICIALAewDcBTAJwC4AjAcwFoB3Q6AF3PwJIpocbEMaAMYccjAKz4A3AiTAAZBDTwFqTNjwAzMOQAeEXQcaVizCBkYAWCJ33sWbTjzJVqI4mGKVT5ACY2AAxBsgoAvkjhQA&options=N4XyA

### System Info

- Windows 11
- SvelteKit

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zhangzheheng12345** [comment]
I've looked into the test cases of unocss (`test/transformer-directives.test.ts`) and found that you actually don't need to use the quotes. Writing `@apply hover:bg-red` is ok. Perhaps the doc causes misunderstanding, so a bit modification may required.

**Comment by zhangzheheng12345** [comment]
Well, since the formatter will add that space by default, I think supporting quotes in `@apply` is necessary.
