### ISSUE TITLE
VSCode unocss extension doesn't activate in sveltekit project

### ISSUE THREAD

**Issue by oonicks** [unocss/unocss#358]
Hey,
I can use unocss very well in my sveltekit project but the vscode extension doesn't activate there. It throws an error.

![Screenshot from 2021-12-31 07-40-19](https://user-images.githubusercontent.com/58259314/147807913-24718649-20a5-4977-b2c6-d2cefb51e927.png)

Thank you in advance!

**Comment by vipero07** [comment]
What does your svelte.config.js look like?

While importing the following
```js
import { presetIcons, presetUno, extractorSvelte } from 'unocss';
import Unocss from 'unocss/vite';
```

The plugins line should look like this
```js
plugins: [
				Unocss({
					extractors: [extractorSvelte],
					presets: [presetUno(), presetIcons({})]
				})
			]
```

**Comment by oonicks** [comment]
I tried many things, sequences and so on. Now my svelte.config.js looks like this (your recommendation) and same error occurs. Also tried actual version 0.22.2

```
import adapter from "@sveltejs/adapter-auto";
import preprocess from "svelte-preprocess";
import { presetIcons, presetUno, extractorSvelte, presetWebFonts, presetAttributify } from 'unocss';
import Unocss from "unocss/vite";

/** @type {import('@sveltejs/kit').Config} */
const config = {
  // Consult https://github.com/sveltejs/svelte-preprocess
  // for more information about preprocessors
  preprocess: preprocess(),

  kit: {
    adapter: adapter(),

    // hydrate the <div id="svelte"> element in src/app.html
    target: "#svelte",
    vite: {
      plugins: [
        Unocss({
          extractors: [extractorSvelte],
          presets: [
            presetUno(),
            presetIcons({}),
            presetWebFonts({
              provider: "google",
              fonts: {
                sans: "Roboto",
                mono: ["Fira Code", "Fira Mono:400,700"],
              },
            }),
            presetAttributify({}),
          ],
        }),
      ],
    },
  },
};

export default config;
```

**Comment by vipero07** [comment]
That is really strange, I have roughly the same configuration and it works for me.
More precisely this works on my end:
```js
import adapter from '@sveltejs/adapter-auto';
import preprocess from 'svelte-preprocess';
import { presetIcons, presetUno, extractorSvelte } from 'unocss';
import Unocss from 'unocss/vite';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://github.com/sveltejs/svelte-preprocess
	// for more information about preprocessors
	preprocess: preprocess(),
	kit: {
		adapter: adapter(),

		// hydrate the <div id="svelte"> element in src/app.html
		target: '#svelte',
		vite: {
			plugins: [
				Unocss({
					extractors: [extractorSvelte],
					presets: [presetUno(), presetIcons({})]
				})
			]
		}
	}
};

export default config;
```

I'm using pnpm for package managing instead of npm, though I doubt that's related aside from one of the presets you are using not working I'm not sure what it could be.

**Comment by oonicks** [comment]
Yeah, it's really strange. Same config as you. New project with pnpm created, same error. I have the import in __layout.svelte. unocss works perfectly in my project it's just the vscode extension who won't start/work. I thought maybe somebody else also has this issue but you for example have no problem with it. I will check my personal environment. Thanks so far.

**Comment by Snukii** [comment]
I have the same problem, the extension doesn't appear to do anything in my sveltekit project.

**Comment by deklanw** [comment]
Same issue. Same error in console. Using pnpm.

Full `svelte.config.js` file here:

```js
import adapter from '@sveltejs/adapter-auto';
import { mdsvex } from 'mdsvex';
import UnoCss from 'unocss/vite'
import { presetUno, presetAttributify } from 'unocss'
import { extractorSvelte } from '@unocss/core'

/** @type {import('@sveltejs/kit').Config} */
const config = {
	extensions: ['.svelte', '.svx', '.md'],
	preprocess: mdsvex({ extensions: ['.svx', '.md'] }),
	kit: {
		adapter: adapter(),
		// hydrate the <div id="svelte"> element in src/app.html
		target: '#svelte',
		vite: {
			plugins: [
				UnoCss({
					extractors: [extractorSvelte],
					presets: [
						presetAttributify({ prefix: 's-' }),
						presetUno(),
					]
				})
			]
		}

	}
};

export default config;
```

**Comment by vipero07** [comment]
I figured out the issue as to why mine is working differently. I have a vite.config.js file in addition to the svelte.config.js file (long story short I'm using svelte kit to develop a library of prebuilt svelte components). It didn't occur to me earlier but the unocss vs code extension is reading the vite.config.js file.

This should fix you:
## vite.config.js
```js
import { defineConfig } from 'vite';
import { presetIcons, presetUno, extractorSvelte } from 'unocss';
import Unocss from 'unocss/vite';

// https://vitejs.dev/config/
export default defineConfig({
	plugins: [
		Unocss({
			extractors: [extractorSvelte],
			presets: [presetUno(), presetIcons()]
		})
	]
});
```
## svelte.config.js
```js
import viteConfig from './vite.config.js';
const config = {
  //...
  kit: {
    //...
    vite: viteConfig
  }
}
```

> sveltekit used to complain about the vite.config.js file, but it didn't break anything. It seems to work fine with no warnings now though.

**Comment by antfu** [comment]
Please use the `uno.config.ts` config if possible for the extension to grab it easily.
