### ISSUE TITLE
Arbitrary gradient value generated output uses `background-color` instead of `background-image`

### ISSUE THREAD

**Issue by csabaxyz** [unocss/unocss#3581]
### UnoCSS version

v0.58.5

### Describe the bug

When you try to create an arbitrary gradient, like: `bg-[linear-gradient(45deg,#0072ff,#00d2e8,#04fd8f,#70fd6c)]` it generates:
```css
.bg {
  background-color: linear-gradient(45deg,#0072ff,#00d2e8,#04fd8f,#70fd6c);
}
```
Instead of:
```css
.bg {
  background-image: linear-gradient(45deg,#0072ff,#00d2e8,#04fd8f,#70fd6c);
}
```

It works in Tailwind:
https://play.tailwindcss.com/3EyO2DVdnF

### Reproduction

https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIBGBzAtAbTjADsBTBAJ12woXFOIBcAKAFgFYRTsAaAYgAMAgOwAmAGbj%2BQkKNIAOaa3Eh5UvsIEqAbDACUAXSiYA9hS5UAjFAAWubaygB3e4-FxSADyhhGpALZIuDAMfhRQfp6MwaGkFOgAfABQUFAAIiakSMQA5IzOZgDWKVDAmBTJqcxIAK4ADnUmSKQgESa2CBCkUDR0YKHGCDCFNCY1xCB6ScAA9OAQCUA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcEWWwCGuOlmggMUAGrr2mmAHEoELmDVRN23foAiwWhN4A3erfs6oeqCJwYAAbQhD1OhkqEQUAdQwOADFiGDokAF84LEsQOAByLhUJKPykJAwAD0hYdGx1LhD4TBx8IhJgUgAKZABIft7YxjoALjgAbSQB-qGlFS6p6d6%2Bpd60YwBrMfy9NGB1MtWMxYGASkol2YTk1Lou85OZ%2BXEpLXvHgF0LgY0tPwDRhNHr1fg5-PojCZcOZLNZ7t8fnY-o4oC43J56PDgaD-vogmBQuFIndTp9MqSgA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by henrikvilhelmberglund** [comment]
This is a bug for now but as a workaround for now you can add a rule `['bg-gradient', { 'background-image': 'var(--un-gradient)' }],` and use the arbitrary `bg-gradient` instead.

https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIBGBzAtNgJwXAFMA7AFyh3yNMtwG04wySEDbixyKAKACwBWECWwAaAMQAGaQHYATADMlU2SAUkAHGoFKQW1ZLnT9ANhgBKALrUA9gVGcAjFAAWuMwKgB3T96U4EgAPKDAKEgBbJFwYXhICKAjgilj4gnQAPgAoKCgWNg5s4AB6cAgc4vLYRBQMGkJuXmo8RvpUxhg7MjAYLna%2BJQI7SIB9aQA6BSEKAFcCMlGEClGhaQBSUYBmDaklMwBOEC2YcWdpUQlJLaUtOQQzcS21y6kSTFuSZxt7RwTcVweLy%2BfxQQIhMIRaJpSgJJIhVJxWEZHJ5Lo9GDFMqQTJAA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcEWWwCGuOlmggMUAGrr2mmAHEoELmDVRN23foAiwWhN4A3erfs6oeqCJwYAAbQhD1OhkqEQUAdQwOADFiGGiAXzgsSxA4AHIuFQkovKQkDAAPSFh0bHUuEPhMHHwiEmBSAApkYXlGOgAuOABtKl7RJRVusdR0YwBrIby9NGB1PNlUdIBKTbkJhOTUuk7dmdjxKS1T2QBdWSgG%2BiHR2ZG8jlIAWlI7VYxcDANoh8hx1BJ5r8rLg0F9QOpSBg8ksPMZOl8voUfn9gACYNs8nB0vcZsNll8AIzAhBwEDGUh4JYABgAdAAmACstBAhOJdx8Wj8AUGIxmGkFjkMxjWgIsVjANzFdgl-mcrgw7mAXhOZze4ocqsCEGCYQIESiitQJJ2SCAA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g
