### ISSUE TITLE
UnoCSS extension isn't suggesting colors right

### ISSUE THREAD

**Issue by Zenthae** [unocss/unocss#3594]
### UnoCSS version

0.58.5

### Describe the bug

First, When using the extension, it's reporting unavailable colors as valid, the generated CSS is good though, as it's not showing in the inspector

![image](https://github.com/unocss/unocss/assets/32647899/e0638874-306f-49fb-96fc-6dcce1f61696)

![image](https://github.com/unocss/unocss/assets/32647899/a87f0e43-4457-4cbc-add1-21afa79abf92)

Second, custom available colors are missing in the suggestions, even if it gets picked up when written manually

![image](https://github.com/unocss/unocss/assets/32647899/8891d085-a1f7-47e1-9851-77137a1c4d51)

![image](https://github.com/unocss/unocss/assets/32647899/ed679804-c9b6-421c-9f96-ea55d46da792)

![image](https://github.com/unocss/unocss/assets/32647899/331afab8-cb65-4612-af66-59c765f93968)

### Reproduction

I don't understand why, but it's working perfectly fine in the [playground](https://unocss.dev/play/?html=DwEwlgbgfAUABHUk4CMDmBeARABwE5gC2AhngJ5awILACEAtPXAHpz4CmAzp3AMIAueADZwA1HADKOYgGN2cQWDRp2eOMQCu-APYzthHEPb95jKtWKcQxEAC94iAPThoMYM8iwgA&config=JYWwDg9gTgLgBAbwFB1XAJgUwGbAHaYDCEeuA5gDQppa4EAKUmAzpjFWnGE6zAIIwYUYACMArjGDYAnhzTcWbAKp4IVAL5xsUCCDgAiMaoDGzZvoDcSJMZLN4C3nzBg4AXgw58mRopgAKfwgwSTt3RHUASncAPkRqVFs8ezgjCHDHZVV-SKsEuCYYMSg8eM5OADoqtLlyuDwAQxBMAC4DBpcAWkyYfVrymAALTGa25Dq6qoq0iqGRzH6JuFsAG2hmMfylzm5QBqhpNv0AYkwAFgAmADYARgAOPq3t1FYk9H3Dg2PsK4BObBu6EezzqDWMxkweBgR2%2BAFYGu8GsCQZwCBIoA0VjDsHdsAAGTDGZEo1AiBqsbHYKlU4kk-DYCAwvF49DoGmLEHMMTglgbL4AZju6GMgtpKIA7vs8PgyNiLiLYWcxSDMFAdFAYZhfvyAOwXETKurqDmoY35dRWKJ5TAAD0gsE82AaYhW8Fo3mIpGAZH843kPDYfIA2j1nGAKFwA-xBMJxJIZDkALoaXJIIA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwBpxp5k0AJMVHTbPfAXyA). Is it using a different extension ?

My local workspace only have Volar + Unocss extensions enabled. I don't know if anyone has the same issue or something is wrong on my side.

`uno.config.ts`
```ts
import {
    defineConfig,
    definePreset,
    presetAttributify,
    presetUno,
    type Preset,
    type PresetOptions,
} from "unocss";

const presetApp = definePreset((options: PresetOptions = {}) => {
    const uno = presetUno();

    return {
        ...uno,
        name: "app-preset",
        theme: {
            ...uno.theme,
            colors: {
                primary: "#e42618",
                secondary: "#f69f1d",
                accent: "#f5adaa",
                neutral: "#f8f0ec",
                base: "#ffffff",
                info: "#00ddff",
                success: "#38dc38",
                warning: "#f2c354",
                error: "#e9372b",
            },
        },
    } satisfies Preset;
});

export default defineConfig({
    presets: [presetApp, presetAttributify()],
});
```

### System Info

VSCode : 1.87.0
antfu.unocss : 0.58.5
vue.volar : 2.0.4

Windows 11
WSL2 : Ubuntu 22.04.3

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
@Zenthae bg-$colors autocomplete is in presetUno. You need to add it to presets
<img width="367" alt="image" src="https://github.com/unocss/unocss/assets/57086651/8e889fd8-6da4-4349-a587-ed18163e001f">
