### ISSUE TITLE
RollupError: [unocss] does not found CSS placeholder in the generated chunks

### ISSUE THREAD

**Issue by wangping1408** [unocss/unocss#3595]
### UnoCSS version

0.58.5

### Describe the bug

Introducing unocss in my project, it was used normally during development, but when I run build, the following error message appeared.
![A0E4EA6D-DA43-4ee3-94AA-8EE1B2A78FF3](https://github.com/unocss/unocss/assets/43232577/8b45f654-6375-41fe-bf77-a26d20c56152)

### Reproduction

I used it this way in the project
![AB9E64AB-37FB-4651-B7D5-D2F60E993069](https://github.com/unocss/unocss/assets/43232577/bf42bc4a-9a7c-4829-85f5-06edf72700e2)
![3861B0BE-DDF5-4de1-B8C1-41FDE971F58E](https://github.com/unocss/unocss/assets/43232577/302ed596-0178-4538-b152-9e3dbf142998)

I have tried solutions to similar problems, but they have not worked for me

### System Info

vite: 4.0.0
unocss: 0.58.5

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
Please provide a minimal demo that can be reproduced
