### ISSUE TITLE
unocss loading triggers a Google Chrome bug?

### ISSUE THREAD

**Issue by hengshanMWC** [unocss/unocss#3599]
### UnoCSS version

0.57.7

### Describe the bug

The hover did not display any text in the past and requires double clicking to display it. I won't encounter this problem when using native HTML&CSS, please refer to [demo.html](https://github.com/hengshanMWC/gugebug/blob/main/demo.html) for details

### Reproduction

[https://github.com/hengshanMWC/gugebug](https://github.com/hengshanMWC/gugebug)
[https://hengshanmwc.github.io/gugebug/dist/index.html#/](https://hengshanmwc.github.io/gugebug/dist/index.html#/)

### System Info

Google Chrome：版本 122.0.6261.94（正式版本） (arm64)
macOS: 14.0 (23A344)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
I can't reproduce the phenomenon you mentioned

**Comment by hengshanMWC** [comment]
> I can't reproduce the phenomenon you mentioned

It looks rare, it's normal for me to try using another computer. I'm going to wrap it around with native CSS now, and I'll add a video later

**Comment by hengshanMWC** [comment]
No text appears in Google Chrome hover, double click is required
https://github.com/unocss/unocss/assets/45714422/941aea4c-0c36-4562-9cb8-68208b12f610

**Comment by Simon-He95** [comment]
> No text appears in Google Chrome hover, double click is requiredGoogle Chrome 悬停时不显示任何文本，需要双击 https://github.com/unocss/unocss/assets/45714422/941aea4c-0c36-4562-9cb8-68208b12f610

Do you have any practical differences between the attributes in the class after unocss and the attributes in direct html css?

**Comment by Simon-He95** [comment]
Temporarily closed, waiting for more information to be provided later, then open again
