### ISSUE TITLE
Variant popover-open:

### ISSUE THREAD

**Issue by jods4** [unocss/unocss#3605]
### Clear and concise description of the problem

Unocss has variants for pretty much all CSS selectors existing:
https://github.com/unocss/unocss/blob/main/packages/preset-mini/src/_variants/pseudo.ts

The recent `:popover-open` selector is missing.

### Suggested solution

Add a new variant to enable things like `popover-open:animate-slide-down`.

### Alternative

In the meantime, the following config will fill in the gap:
```js
variants: [
  // popover-open:
  matcher => matcher.startsWith('popover-open:')
    ? { matcher: matcher.slice(13), selector: s => s + ":popover-open" }
    : matcher,
]
```

### Additional context

https://developer.mozilla.org/en-US/docs/Web/CSS/:popover-open

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by henrikvilhelmberglund** [comment]
Reference: https://developer.mozilla.org/en-US/docs/Web/API/Popover_API/Using
https://developer.mozilla.org/en-US/docs/Web/CSS/@starting-style (for supporting transitions)
