### ISSUE TITLE
@unocss/webpack 开启 watch 时报错 

### ISSUE THREAD

**Issue by StephenPCG** [unocss/unocss#3613]
### UnoCSS version

0.58.5

### Describe the bug

webpack 中的配置如下：

```
import UnoCSS from '@unocss/webpack';

...

memo.plugin('unocss').use(UnoCSS({
    configFile: './uno.config.ts',
    watch: true,
}));
```

启动 webpack 时：

```
node:internal/modules/esm/utils:213
  throw new ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING();
        ^

TypeError: A dynamic import callback was not specified.
    at importModuleDynamicallyCallback (node:internal/modules/esm/utils:213:9)
    at setupContentExtractor (/.../node_modules/@unocss/webpack/dist/index.cjs:255:25)
    at async Promise.all (index 0)
    at async flushTasks (/.../node_modules/@unocss/webpack/dist/index.cjs:133:5)
    at async Timeout.updateModules [as _onTimeout] (/.../node_modules/@unocss/webpack/dist/index.cjs:411:7) {
  code: 'ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING'
}
```

### Reproduction

查看 `node_modules/@unocss/webpack/dist/index.cjs` ，报错的是这一行：

```
const { watch } = await import('chokidar');
```

手动改为 `const { watch } = require('chokidar');` 即可正常运行。

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by StephenPCG** [comment]
BTW，我这里并不是直接使用的 webpack，而是在 [umijs/father](https://github.com/umijs/father) 中使用，`fatherrc.ts` 文件这样配置：

```ts
export default defineConfig({
    umd: {
        chainWebpack: (memo) => {
            ...
            memo.plugin('unocss').use(UnoCSS({
            configFile: './uno.config.ts',
            watch: true,
            }));
            ...
            return memo
        }
    }
})
```

不清楚这个问题是 father 的还是哪里的。

我对 js 生态不太熟悉，平时主要写后端代码。提的问题如果太 naive 还请见谅😂

**Comment by StephenPCG** [comment]
还有一个额外的问题（不是 bug）：

```ts
      const watcher = watch(files, {
        ignorePermissionErrors: true,
        ignored,
        cwd: root,
        ignoreInitial: true,
      })
```

这里的 `watch(files)` 能否改为 `watch(content.filesystem)`，因为 `files` 已经被展开了，后续有新增的文件不会被发现，如果直接把 `content.filesystem` 传递给 `watch`，则新增的文件也能被发现。不知道设计上是否有什么特殊的考虑？

**Comment by Simon-He95** [comment]
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by xmsz-stu** [comment]
你解决了吗
