### ISSUE TITLE
Feature: Supports definePreset async

### ISSUE THREAD

**Issue by zhangmo8** [unocss/unocss#3616]
### Clear and concise description of the problem

async definePreset can be help default developers dynamically introduce dependencies.

The actual place of use is [here](https://github.com/unpreset/unocss-preset-useful/pull/9/files#diff-9a4ceebe7c6f86856371906c3f061d3b56b7457022b05179884a113e7ced67e8L13)

and the dynamic import is [here](https://github.com/unpreset/unocss-preset-useful/pull/9/files#diff-3d8c5ca317843422789d25aaff575f9a3c9c1f37c13a5b350b952951696abd89L30)

### Suggested solution

I tried to handle this asynchronous behavior in the resolvePreset phase, but it ended up pointing to the constructor of a class, so it was unsuccessful. I was thinking about whether to synchronize this behavior directly in the definePreset phase.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [ ] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by zhangmo8** [comment]
Maybe We should be await it in the plugin and not in unocss.

Emmm. But It's that can be a feature in future?

**Comment by zyyv** [comment]
Complete in #4268
