### ISSUE TITLE
How to combine background-image and background-size?

### ISSUE THREAD

**Issue by mortona42** [unocss/unocss#3627]
### UnoCSS version

58.6

### Describe the bug

Using `bg-[url(/path/to/my/image.jpg)_50%]` comes out as `background-color: url(/path/to/my/image.jpg) 50%;`

### Reproduction

Here is a playground with some attempts to combine them:

https://uno.antfu.me/play/?html=CoCwlgzgBA9gdgUygExgicDkAXKiHJTYxQQK7YhIRgBeCANFAgG4IBOAnpWHAOZQA7jHYBrCADoAUAB5kYFlADGAGwCGECAF4ARCAC0AbQAsABlMAHAB4BdIUbOXbUAEYjkHKVFd8jAV3YVAAoQbGwLCAAuAHpolREEAFsAMxUwJVF2CSUYROiAJnMCoqU1bABKGy8ffXYwPlD9NzDcmrgYWoQLBDKdAD4ZaPkWPqlQSCgwRLU%2BJAnKajVE6jokDSIqZXhsNV4OJhAYQSISMlwXNQy%2Bdhg-OGR9GnpIqABWUwBSAH5ZYeV1TS6AwmczWOyCByg5xudgedjVFy%2BQwBYKhcJRWLxdhJVLpTLZXLRRxEkplSoI3x1BrYJowFqJNodbHdMo1QzvD42fqDYajcbQMrYJIWXDJXYqCBMHLLaC3XDrC5XG53B45LHSOQKf4abR6SFOcH6sGudyebyI-yBEJhCIxOIJFJpDJZaUk0xu6KlCoAfQ5VXNlPqjWaxAZFvanRZ2G5QwUoyAA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHCjjUrAFxwA2itV7azeqxjUAtOrGpaAGkRxmEMdB20oqZLTIBdA752BqzC6KhiwGY6urQwfDAWrCD2dCZmlta2gZykAJRAA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgzgLgTglgxhEAuaBXApgGhNAhgOzADMB7KAWwAkJyAbZI3WsdAXyA

### System Info

Linux, firefox, vite plugin.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
`bg-[size:50%]`

**Comment by Simon-He95** [comment]
`bg-[length:50%]`

**Comment by mortona42** [comment]
Is that syntax from tailwind or uno? Where can I find docs?
Thanks.

**Comment by Simon-He95** [comment]
> Is that syntax from tailwind or uno? Where can I find docs? Thanks.

https://tailwindcss.com/docs/background-size#arbitrary-values

**Comment by mortona42** [comment]
Thank you very much.
