### ISSUE TITLE
docs: Rules usage is unclear

### ISSUE THREAD

**Issue by 1001v** [unocss/unocss#3635]
### UnoCSS version

0.58.6

### Describe the bug

Hello. The [rules definition example](https://unocss.dev/config/rules) is a bit unclear, since it's not stated, that kebab-case properties should be used, and there's no auto convert from camelCase. I'd like to suggest to indicate it explicitly. Thanks.

### Reproduction

https://unocss.dev/config/rules

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
PR welcome, thanks!
