### ISSUE TITLE
Sourcemap warning with Nuxt

### ISSUE THREAD

**Issue by antfu** [unocss/unocss#3636]
### UnoCSS version

^0.58.6

### Describe the bug

https://github.com/nuxt/nuxt/issues/26332

### Reproduction

https://stackblitz.com/edit/nuxt-starter-mxdo6f?file=package.json

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wvovaw** [comment]
I'm not sure if this will be helpful, but here's what I've noticed.
I have  40 globally registered components under `~/components/global` directory. The warning only appears for components 
 where the [@unocss/transformer-variant-group](https://unocss.dev/transformers/variant-group) is used.
