### ISSUE TITLE
RTL unocss tool for Arabic sites

### ISSUE THREAD

**Issue by sszlime00** [unocss/unocss#3643]
### Clear and concise description of the problem

I would like to ask if there is any RTL unocss plug-in for Arabic sites that can automatically add rtl to the required class names？

### Suggested solution

 RTL unocss plugin for Arabic sites that can automatically add rtl

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Simon-He95** [comment]
#3438
We currently have no plans for other languages, English is spoken internationally
