### ISSUE TITLE
Could it throw a `warn` on `Attributify Mode` when be conflict with component's attributy?

### ISSUE THREAD

**Issue by s3xysteak** [unocss/unocss#3644]
### Clear and concise description of the problem

Assume we have a component:
```vue
<script setup>
defineProps(['text'])
</script>

<template>
  <div>
    Uno~
  </div>
</template>
```

Usage:
```vue
<MyComponent text="8" />
```
The component will get a `text -> '8'` prop and the `text-8` unocss will be invalid.

Now:
Nothing happened on the console. 

Expect:
Throw a console.warn to explicitly indicate that the `text` attribute is invalid as unocss.

It should be an option that defaults to `false`. Or it will be a break change because it force user prevent use possibly ambiguous props.

### Suggested solution

It seems that unocss know if it is conflict with component's attributy. So maybe it can just throw a console.warn on the code where how it know the conflict.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Simon-He95** [comment]
#3174
unocss will not do such a thing. It only works at the CSS level and should not monitor whether the props required by your component conflict with it. You should handle it yourself
