### ISSUE TITLE
Download functionality to presetWebFonts for offline/local network website

### ISSUE THREAD

**Issue by HassanDomeDenea** [unocss/unocss#3646]
### Clear and concise description of the problem

When you add fonts using presetWebFonts, for example:

```
//uno.config.ts
export default defineConfig({
  presets: [
    //   ...
    presetWebFonts({
      fonts:{
        lobster: 'Lobster',
        vibes: 'Vibes',
      }
    })
  ]
})
```

this will create `@font-face` definition for each font, containing the URL from google for example:

```

@font-face {
  font-family: Vibes;
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url(https://fonts.gstatic.com/s/vibes/v14/QdVYSTsmIB6tmYd1FJfcuA.woff2) format("woff2");
  unicode-range: U+0600-06FF, U+0750-077F /* .... */
}
```

For some web application that works offline or inside (local network), we cannot use this as we need the files to those fonts in the assets of our applications to work properly.

### Suggested solution

My suggested solution is inspired from a vite plugin [vite-plugin-webfont-dl](https://github.com/feat-agency/vite-plugin-webfont-dl)
An option (global or per font) inside presetWebFonts config, to allow downloading fonts locally, thus the generated styles use the relative path to font file from our project.

Example for suggested config:
```

presetWebFonts({
  downloadLocally: true, //Global setting, unless overridden 
  fonts: {  
       vibes: 'Vibes',
       lobster: [
           {
                 name: 'Lobster,
                 provider: 'none',
                 downloadLocally: false, // Overridden here
           }
        ],
    ],
  },
})

```

Generated code will be for example:
```
@font-face {
  font-family: Vibes; 
  src: url(assets/font-vibes-QdVYSTsmIB6tmYd1FJfcuA.woff2) format("woff2");
}
```

### Additional context

This vite plugin [https://github.com/feat-agency/vite-plugin-webfont-dl](url) unfortunately does not work with font-faces generated by unocss/presetWebFonts (whether inline import is true or false)
Or did I miss a working configuration or workaround? 

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
I'd love to have that feature! PR welcome if anyone wants to work on that. Thanks
