### ISSUE TITLE
【unocss/vite】 vue-scoped 使用问题

### ISSUE THREAD

**Issue by yuanyxh** [unocss/unocss#3659]
### UnoCSS version

0.58.5

### Describe the bug

vite + vue + unocss，我的 `uno.config` 中定义了 `content.pipeline.include`，需要对 `.vue`、`.tsx` 进行处理，使用 `{ mode: 'vue-scoped' }` 后构建失败，发现 unocss 在我的 `.tsx` 里插入了 `<style scoped>code<style>`。

查看实现 [vue-scoped]，默认是生成 `<style scoped>code<style>` 插入到代码底部，这种方式应该只针对 `.vue` 文件，为什么会允许对 `content.pipeline.include` 中的其他文件进行处理？

[vue-scoped]: https://github.com/unocss/unocss/blob/f4a39b4b036cfa4223db9dbd3814de094f0e6587/packages/vite/src/modes/vue-scoped.ts#L19C1-L27C7

### Reproduction

我的描述足够清晰

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
Because it not only works in vue, maybe some other frameworks also support <style scoped></style>, and vue can also be written in astro
