### ISSUE TITLE
fontSize theme configuration, css not compiled correctly.

### ISSUE THREAD

**Issue by RayGuo-ergou** [unocss/unocss#3663]
### UnoCSS version

0.58.7

### Describe the bug

```ts
export default defineConfig({
  theme: {
    fontSize: {
      // '2xl': ['1.5rem', {
      //   'line-height': '2rem',
      //   'letter-spacing': '-0.01em',
      //   'font-weight': '500',
      // }],
      '2xl': ['1.5rem', {
        lineHeight: '2rem',
        letterSpacing: '-0.01em',
        fontWeight: '500',
      }],
    },
  },
});
```

Pass in this config, the css will build like this:

```css
.text-2xl{font-size:1.5rem;lineHeight:2rem;letterSpacing:-.01em;fontWeight:500}
```

which does not recognize by any browser.
![image](https://github.com/unocss/unocss/assets/33137074/63529743-3d4d-4d13-9c56-2801d180a7df)
 

### Reproduction

https://stackblitz.com/edit/vitejs-vite-2mouvf

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
https://unocss.dev/config/rules#static-rules

**Comment by RayGuo-ergou** [comment]
Why this is closed? They are not even the same thing. ( theme vs rules )

Or does this mean it will never been supported?

**Comment by Simon-He95** [comment]
The document gives the method of use - splicing. You should follow the document when using it.

**Comment by RayGuo-ergou** [comment]
I understand that there's a work around of this issue ( I even have that in the issue report ).

The main purpose of this issue is because camel case `lineHeight` etc if from tailwind's configuration ( see: [here](https://tailwindcss.com/docs/font-size#providing-a-default-line-height)).

As also in unocss documentation:
> UnoCSS also supports the theming system that you might be familiar with in Tailwind CSS / Windi CSS. At the user level, you can specify the theme property in your config, and it will be deep-merged to the default theme.

It would be super nice that unocss can support tailwind's configuration out of box without any extra work.

**Comment by Simon-He95** [comment]
I got you. In order to better migrate from tailwind to unocss, I will submit a PR later to be compatible with this issue.

**Comment by antfu** [comment]
https://github.com/unocss/unocss/pull/3666#issuecomment-2024901671

Let's keep consistent on usage rules and themes (in this case, it's the escape hatch so they are actually part of the rule object).

I am up to improving the documentation if you think it needs clarification. We don't plan to have that feature.

**Comment by RayGuo-ergou** [comment]
> Let's keep consistent on usage rules and themes (in this case, it's the escape hatch so they are actually part of the rule object).

okay got it.

> I am up to improving the documentation if you think it needs clarification. 

I do think the documentation could be more clear about `theme` as at least to me the docs tells that I can migrate my current tailwind configuration to unocss without any modification. 

And thank you @Simon-He95 for your time and effort, much appreciated.

**Comment by hoangnhan2ka3** [comment]
> Emm, no, I made that decision on purpose. I don't think we should allow ppl to use camelCase especially because it's not that hard to write kebab-case that aligns with how CSS would work. TBH it's more like a "bad habit" the community has inherited from CSS-in-JS. Uno has no plan to support that for both performance as well as convention-free.

I think the main problem here is "syntax highlighting", if it is written in camelCase, it will stand out and be easier to identify than if surrounded with `quotes`.

On the other hand, do you think (why) Tailwind is likened to the `Apple` of the CSS framework world?

**Comment by RayGuo-ergou** [comment]
I think it's nothing about highlight.

**Comment by hoangnhan2ka3** [comment]
Yep, it's probably up to each person's taste, but I have no opinion on turning it into a string, but somehow I still like the method below more than the above.

<img width="549" alt="Screenshot 2024-04-03 144607" src="https://github.com/unocss/unocss/assets/147973044/590cf991-bf01-41fd-84f0-f9cf1cfaf2ff">

<img width="539" alt="Screenshot 2024-04-03 144708" src="https://github.com/unocss/unocss/assets/147973044/077d6138-fa2d-41da-b5b2-29f3494a9396">
