### ISSUE TITLE
@unocss/preset-icons Icons are not bundled into css

### ISSUE THREAD

**Issue by Alkaidcc** [unocss/unocss#3682]
### UnoCSS version

0.59.0-beta.1

### Describe the bug

When the class name of the icon is imported from another file, the icon is not bundled.

```vue
// App.vue
<script setup>
import {ref} from 'vue';
import {classNameList} from './constants';
const iconList = ref(classNameList);
</script>

<template>
  <div>
    <div v-for="(i,index) in iconList" :class="i" :key="index"></div>
  </div>
</template>
```
```javascript
// src/constants/index.js
export const classNameList = ['i-lucide-file-cog', 'i-lucide-file-output', 'i-lucide-atom', 'i-lucide-palette','i-lucide-arrow-big-right']

```

### Reproduction

https://github.com/Alkaidcc/unocss-issue

1.  `pnpm install`
2. `pnpm build`
check css file in `dist/assets` folder, icon css was not found

### System Info

- macOS14
- Nodejs 20.11

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
This kind of dynamic should be added to the safelist.
<img width="577" alt="image" src="https://github.com/unocss/unocss/assets/57086651/b074313f-fa86-4b3a-8d22-c5f0e32a115d">

**Comment by userquin** [comment]
You can also add `// @unocss-include` comment at top in the constants module
