### ISSUE TITLE
@unocss/eslint-config doesn't work in @unocss-include

### ISSUE THREAD

**Issue by Skiyee** [unocss/unocss#3683]
### UnoCSS version

0.59.0-beta.1

### Describe the bug

Unocss works fine, but @unocss-eslint-config doesn't.

![image](https://github.com/unocss/unocss/assets/120664167/e37da948-5ba4-47d1-a69f-30205c5d285d)

### Reproduction

``` typescript
// @unocss-include
const root = 'bg-red-500        top-0 left-0 right-0 z-50 fixed';
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Skiyee** [comment]
这是在vscode里面的，我无法提供最小复现
如果解决这个issue需要什么帮助，请在评论区告知，能力范围内我很乐意帮忙 ❤

This is in vscode.
I cannot provide a minimum reproduction.
If you need any help to fix this issue, please let me know in the comment. 
I will be happy to help within my ability. ❤

**Comment by antfu** [comment]
The eslint rule only applies to HTML/JSX like strings in components. It's almost impossible to know the indentation of a string in JS to treat them as the "class strings": https://github.com/unocss/unocss/blob/be94f1814ecf782120bf64ba0f7f0488c2b283e8/packages/eslint-plugin/src/rules/order.ts#L47-L67

I would say this is a limitation. Open to documentation improvements, or an implementation PR if anyone is brilliant enough to improve it.
