### ISSUE TITLE
[@unocss/transformer-variant-group] cannot be with vitepress

### ISSUE THREAD

**Issue by Skiyee** [unocss/unocss#3690]
### UnoCSS version

0.59.0-beta.1

### Describe the bug

in `.md` file
````
```ts
const unocss = 'vitepress:(unocss)'
```
````
with `@unocss/transformer-variant-group` generate 👇
```
const unocss = 'vitepress:unocss'
```
should generate 👇
```
const unocss = 'vitepress:(unocss)'
```

### Reproduction

https://stackblitz.com/edit/vite-rggqvj?file=docs%2F.vitepress%2Fvite.config.ts,docs%2F.vitepress%2Funo.config.ts,docs%2Fexample.md

### System Info

System: os: window-11
Binaries: pnpm: 8.15.3
npmPackages: vitepress: 1.0.2 | unocss: 0.59.0-beta.1

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
<img width="1076" alt="image" src="https://github.com/unocss/unocss/assets/57086651/37a76bcc-72fb-419a-af88-e2c662846ab8">
Skip local area transformation rules can be used
