### ISSUE TITLE
Postcss + async rules doesn't work well

### ISSUE THREAD

**Issue by DarkHole1** [unocss/unocss#3699]
### UnoCSS version

0.59.0

### Describe the bug

`@unocss/postcss` doesn't replaces `@apply` with rule contents on a certain conditions:
* Source extractors didn't found class (probably)
* File has `@unocss` directive
* Rule is async

The problems comes from here: https://github.com/unocss/unocss/blob/5ae78dfb3e4a9c6d5de326de6a9ac6de9b5e87c6/packages/postcss/src/apply.ts#L11-L12
I tried patching package locally and awaiting all functions something like that:
```ts
let promises: Promise<unknown>[] = [];
root.walkAtRules(directiveName, (rule) => {
    promises.push((async () => {
        // ...
    })())
});
await Promise.all(promises);
```
And this fixes it.

### Reproduction

https://github.com/DarkHole1/uno-postcss-bug

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Would you like to send a quick PR? Thanks
