### ISSUE TITLE
I am using UnoCSS+element plus to do some interesting things, and my goal is to move input to change the style of the subcomponents，but it didn't achieve my goal

### ISSUE THREAD

**Issue by QSYSMoric** [unocss/unocss#3716]
### UnoCSS version

0.59.1

### Describe the bug

```
Example:
            <el-card shadow="never" class="group card cursor-pointer">
              <template #header>
                <el-row justify="center">
                  <el-icon :size="42">
                    <svg-icon :name="item.icon" />
                  </el-icon>
                </el-row>
              </template>
              <el-row justify="center">
                <el-text class="font-size-18! text-blod group-hover:color-#008EED!">
                  {{ item.title }}
                </el-text>
              </el-row>
            </el-card>
```
When I moved into the card component, the el text did not change colors as expected

now：
![Snipaste_2024-04-12_19-33-25](https://github.com/unocss/unocss/assets/109967979/1ee34ec0-45ee-47f9-9e72-0149602f1f69)

expect:
![image](https://github.com/unocss/unocss/assets/109967979/9f4a3004-dc10-4dfa-982e-ffafe3a1757c)

### Reproduction

[Example link](https://github.com/QSYSMoric/UnoCSS-element-plus-example)

### System Info

environment：
node：v20.11.1
nuxt：3.8.2
@unocss/eslint-config: "^0.59.1",
@unocss/nuxt: "^0.58.0",

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by henrikvilhelmberglund** [comment]
You need to post an actual reproduction project on stackblitz or a repo.

**Comment by QSYSMoric** [comment]
> You need to post an actual reproduction project on stackblitz or a repo.

Sorry, due to work reasons, I am unable to provide a complete project. I quickly built an example to reproduce this defect. If you could help me solve this problem, I would greatly appreciate it link: [example](https://github.com/QSYSMoric/UnoCSS-element-plus-example)

**Comment by henrikvilhelmberglund** [comment]
> > You need to post an actual reproduction project on stackblitz or a repo.
> 
> Sorry, due to work reasons, I am unable to provide a complete project. I quickly built an example to reproduce this defect. If you could help me solve this problem, I would greatly appreciate it link: [example](https://github.com/QSYSMoric/UnoCSS-element-plus-example)

The group functionality is not included in preset-scalpel so you need to import the base UnoCSS preset.
`nuxt.config.ts`
```diff
+ import { presetUno } from "unocss";
- presets: [presetScalpel()],
+ presets: [presetUno(), presetScalpel()],
```

**Comment by QSYSMoric** [comment]
> > > You need to post an actual reproduction project on stackblitz or a repo.
> > 
> > 
> > Sorry, due to work reasons, I am unable to provide a complete project. I quickly built an example to reproduce this defect. If you could help me solve this problem, I would greatly appreciate it link: [example](https://github.com/QSYSMoric/UnoCSS-element-plus-example)
> 
> The group functionality is not included in preset-scalpel so you need to import the base UnoCSS preset. `nuxt.config.ts`
> 
> ```diff
> + import { presetUno } from "unocss";
> - presets: [presetScalpel()],
> + presets: [presetUno(), presetScalpel()],
> ```

Thank you for your help. This is a very useful suggestion that has been of great help to me
