### ISSUE TITLE
Configuration anomalies due to upgraded versions

### ISSUE THREAD

**Issue by ZhongYanZhiShi** [unocss/unocss#3721]
### UnoCSS version

0.59.0

### Describe the bug

0.58.9 doesn't have this problem, but upgrading to 0.59.0+ does.

### Reproduction

# Bug Realization Methods

- `npx create-next-app@latest`
- `yarn add @unocss/postcss@0.59.0` or `yarn add @unocss/postcss@0.59.2`

- postcss.config.js

  ```js
  module.exports = {
    plugins: {
      '@unocss/postcss': {
        content: ['**/*.{html,js,ts,jsx,tsx}'],
      },
    },
  }
  ```

- uno.config.ts

  ```js
  import { defineConfig, presetUno } from 'unocss'

  export default defineConfig({
    presets: [
      presetUno(),
      // ...
    ],
  })
  ```

As of 2024/04/13, the latest version 0.59.2, installing 0.59.0 and above gives this following error.

<img width="965" alt="img-20240413-153129" src="https://github.com/unocss/unocss/assets/74604296/58e5ad5c-b5d9-41a7-9740-e2f751d8914a">

### System Info

```json
{
  "name": "nextjs14.2",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "14.2.1",
    "react": "^18",
    "react-dom": "^18"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "@unocss/postcss": "^0.59.0",
    "eslint": "^8",
    "eslint-config-next": "14.2.1",
    "typescript": "^5",
    "unocss": "^0.59.0"
  }
}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by lzl0304** [comment]
Had same error.
The reason is that after building, the default export of `CJS` was replaced.
https://github.com/unocss/unocss/pull/3380/files#diff-21462feba05a79008c54d9a3267569b27b8897540ac86e47110e57f25402d224R11

But `Next.js` plugins must be provided as strings.
https://nextjs.org/docs/messages/postcss-shape

You can roll back to version 0.58.9 until a solution is found.
