### ISSUE TITLE
[@unocss/postcss] [object Object] is not a PostCSS plugin

### ISSUE THREAD

**Issue by Jungzl** [unocss/unocss#3724]
### UnoCSS version

latest

### Describe the bug

[postcss] [object Object] is not a PostCSS plugin

### Reproduction

https://stackblitz.com/fork/github/unocss/unocss/tree/main/examples/vite-svelte-postcss

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by geodic** [comment]
I am pretty sure that  this was caused by the recent migration of UnoCSS to ESM-only. To fix this you will have to rename your config file to `postcss.config.mjs` and replace `module.exports = ...` with `export const config = ...`

**Comment by Jungzl** [comment]
> I am pretty sure that this was caused by the recent migration of UnoCSS to ESM-only. To fix this you will have to rename your config file to `postcss.config.mjs` and replace `module.exports = ...` with `export const config = ...`

Yeah, it starts successfully but don't generate CSS either

![image](https://github.com/unocss/unocss/assets/35426360/ae557a16-8737-4c97-878c-243663d7b34d)

**Comment by mevlutbucan** [comment]
You can fix this by importing modules in your config file:

```js
import unocss from '@unocss/postcss';
import autoprefixer from 'autoprefixer';

export default {
  plugins: [
    unocss(),
    autoprefixer(),
    // ...other plugins
  ],
};
```

**Comment by Jungzl** [comment]
> ```js
> unocss(),
> ```

Thank you, it works now. Might update docs later.
