### ISSUE TITLE
No longer compatible with ESLint v8?

### ISSUE THREAD

**Issue by Stanzilla** [unocss/unocss#3751]
### UnoCSS version

0.59.4

### Describe the bug

On a dependabot PR that upgrades @unocss/eslint-config from 0.58.8 to 0.59.4 I'm getting the following error:

Error: ESLint configuration in .eslintrc.json » @unocss/eslint-config is invalid:
	- Unexpected top-level property "default".

https://github.com/WeakAuras/WeakAuras-Companion/pull/2452

### Reproduction

I hope the linked repo is good enough, otherwise I can set up a playground as well.

See https://github.com/WeakAuras/WeakAuras-Companion/pull/2452

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [ ] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by cl1107** [comment]
same isuue

**Comment by fzf404** [comment]
i have same issue

**Comment by zhuba-Ahhh** [comment]
meto

**Comment by linkscope** [comment]
I have the same problem and it seems that I can only use flat config?

**Comment by antfu** [comment]
Should be resolved in v0.60
