### ISSUE TITLE
`commaStyleColorFunction` conversion error

### ISSUE THREAD

**Issue by coderwyd** [unocss/unocss#3752]
### UnoCSS version

^0.59.4

### Describe the bug

Conversion error when encountering bg-[rgba(x,x,x,x)] when converting rgb function using `@unocss/preset-legacy-compat`

### Reproduction

https://codesandbox.io/p/devbox/unocss-repo-4gtmt6?file=%2Fsrc%2FApp.vue&embed=1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvc1n2ek00073j6jfu4wk4jf%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvc1n2ej00023j6jbit1289q%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvc1n2ej00043j6jl460cmtq%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvc1n2ej00063j6jrwc84sje%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvc1n2ej00023j6jbit1289q%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvc1n2ej00013j6jn0fxss7k%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clvc21tgv00023j6jus98g9ym%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A4%252C%2522startColumn%2522%253A63%252C%2522endLineNumber%2522%253A4%252C%2522endColumn%2522%253A63%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clvc1n2ej00023j6jbit1289q%2522%252C%2522activeTabId%2522%253A%2522clvc21tgv00023j6jus98g9ym%2522%257D%252C%2522clvc1n2ej00063j6jrwc84sje%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvc1n2ej00053j6jy0i9qabo%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clvc1n2ej00063j6jrwc84sje%2522%252C%2522activeTabId%2522%253A%2522clvc1n2ej00053j6jy0i9qabo%2522%257D%252C%2522clvc1n2ej00043j6jl460cmtq%2522%253A%257B%2522id%2522%253A%2522clvc1n2ej00043j6jl460cmtq%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvc1n2ej00033j6jofgkshpb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clvc1n2ej00033j6jofgkshpb%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by coderwyd** [comment]
![image](https://github.com/unocss/unocss/assets/53386850/db26a13c-b4a5-4e13-ba26-b57e2a120a5d)

**Comment by Simon-He95** [comment]
> ### UnoCSS version
> ^0.59.4
> 
> ### Describe the bug
> Conversion error when encountering bg-[rgba(x,x,x,x)] when converting rgb function using `@unocss/preset-legacy-compat`
> 
> ### Reproduction
> https://codesandbox.io/p/devbox/unocss-repo-4gtmt6?file=%2Fsrc%2FApp.vue%3A4%2C63
> 
> ### System Info
> _No response_
> 
> ### Validations
> * [x]  Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
> * [x]  Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
> * [x]  Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
> * [x]  The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

- reproduction link is broken
<img width="636" alt="image" src="https://github.com/unocss/unocss/assets/57086651/21192a1c-a91d-4bbf-84cf-9ccd45a829f8">

**Comment by coderwyd** [comment]
> * reproduction link is broken

Sorry, I changed the link again. Please try again.
