### ISSUE TITLE
@unocss/runtime does not work

### ISSUE THREAD

**Issue by coderlzw-cn** [unocss/unocss#3757]
### UnoCSS version

0.58.6

### Describe the bug

<img width="395" alt="image" src="https://github.com/unocss/unocss/assets/55791848/35687022-f947-4b32-8242-a338f441c5de">
Does this thing need any more configuration

### Reproduction

https://stackblitz.com/edit/vitejs-vite-bd9mbx?file=uno.config.ts

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
> https://stackblitz.com/edit/vitejs-vite-bd9mbx?file=uno.config.ts

Refer to [https://unocss.dev/integrations/runtime#usage](https://unocss.dev/integrations/runtime#usage), your uno runtime config is empty, so it doesn't work.

<img width="724" alt="image" src="https://github.com/unocss/unocss/assets/42139754/8cab8336-7041-4f90-8e2f-aa079621b12c">


I see your demo are using dynamic class, put them in `safelist` will be work.

```ts
{
  safelist: ['text-zinc-200', 'text-zinc-500']
}
```

**Comment by zyyv** [comment]
I don't recommend you to use `runtime` in vite env, they have different context.
