### ISSUE TITLE
在create-react-app的webpack项目中使用presetTypography预设会报错

### ISSUE THREAD

**Issue by badlym** [unocss/unocss#3758]
### UnoCSS version

0.59.4

### Describe the bug

在create-react-app的webpack项目中使用presetTypography预设，会报错
具体报错信息为
bundle.js:39371 Uncaught SyntaxError: Invalid or unexpected token (at bundle.js:39371:3805)
<img width="1409" alt="image" src="https://github.com/unocss/unocss/assets/38027590/2e0653e7-fba9-4137-83eb-813f2fb2e789">

### Reproduction

这是我的github存储库的地址[https://github.com/badlym/cra-test](url)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
@badlym the Reproduction Link can't be used

**Comment by badlym** [comment]
https://github.com/badlym/cra-test[](url)

**Comment by badlym** [comment]
[https://github.com/badlym/cra-test](url) 好了现在可以用了

**Comment by badlym** [comment]
[这是链接](https://github.com/badlym/cra-test) 好了现在可以用了

**Comment by badlym** [comment]
我说的不是这个bug解决了，而是我的仓库更新好了。之前仓库地址写错了
