### ISSUE TITLE
Preset icons empty `prefix` makes things very slow in Nuxt

### ISSUE THREAD

**Issue by Kylyi** [unocss/unocss#3766]
### UnoCSS version

0.59.4 (but applies for older versions as well)

### Describe the bug

Once you use `prefix = ''` for the `presetIcons` package, the startup time goes up by A LOT.

![image](https://github.com/unocss/unocss/assets/19700450/15174d40-4e4c-4185-9d82-8176112f5e67)

### Reproduction

https://stackblitz.com/edit/nuxt-starter-v1rmrn?file=app.vue,unocss.config.ts,nuxt.config.ts

### System Info

Mac M2, Google Chrome, Nuxt

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by userquin** [comment]
Dont do that

**Comment by Kylyi** [comment]
> Dont do that

Why not? Using `<icon_set_prefix>:<icon>` makes it unique more than enough already

**Comment by userquin** [comment]
Because without the prefix , every parsed token  from every file ( vue, tsx, jsx... ) must be checked against every collection.

With the prefix, the preset will not be called if the token doesn't start with it: if you are using full iconify that's a lot of checks.

**Comment by Kylyi** [comment]
> Because without the prefix , every parsed token from every file ( vue, tsx, jsx... ) must be checked against every collection.
> 
> With the prefix, the preset will not be called if the token doesn't start with it: if you are using full iconify that's a lot of checks (and ofc if your codebase is huge).

Thanks for the explanation! I'll adjust the codebase.

I'm gonna leave this issue open as it technically still is a bug but feel free to close.
