### ISSUE TITLE
"unocss/vite" resolved to an ESM file. ESM file cannot be loaded by `require`

### ISSUE THREAD

**Issue by sugar258596** [unocss/unocss#3776]
### UnoCSS version

0.59.4

### Describe the bug

![image](https://github.com/unocss/unocss/assets/84883966/9fb479ed-e31c-4a2c-b129-d5997d55e8f7)

This problem occurs when building small programs using uniapp
![image](https://github.com/unocss/unocss/assets/84883966/b9f5b7a5-097f-4b97-9c0c-a87d8de3eeaf)
I don't know why it happened，Importing unocss with pure vue does not have this problem，I hope someone can answer it for me. Thank you

### Reproduction

![image](https://github.com/unocss/unocss/assets/84883966/4d8f3de5-0a64-41a4-a1cd-1e8f8eed4943)

### System Info

node -v     v18.19.0
pnpm -v   8.15.4
pnpm show vite version    5.2.11
pnpm show unocss version   0.59.4

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by userquin** [comment]
try adding type module to your package.json or rename vite config to .mjs/.mts

**Comment by sugar258596** [comment]
> 尝试将类型模块添加到 package.json 或将 vite 配置重命名为 .mjs/.mts
> 
> https://vitejs.dev/guide/troubleshooting.html#this-package-is-esm-only

It's configured, but there's still an error

**Comment by sugar258596** [comment]
> 尝试将类型模块添加到 package.json 或将 vite 配置重命名为 .mjs/.mts
> 
> https://vitejs.dev/guide/troubleshooting.html#this-package-is-esm-only
This error occurs when you change the ts file to mts
![image](https://github.com/unocss/unocss/assets/84883966/03e2f6e7-1fba-47c6-813e-dcfb81682fa1)

**Comment by userquin** [comment]
what's you moduleResolution entry in the tsconfig.json file? Can you try with `.default()` suffix on uni?

**Comment by sugar258596** [comment]
> tsconfig.json 文件中的 moduleResolution 条目是什么？你可以尝试`.default()`在uni上使用后缀吗？

![image](https://github.com/unocss/unocss/assets/84883966/2581d2f9-b6b0-42f4-8528-4744bbe82387)

**Comment by userquin** [comment]
`@dcloudio/*`  seems to be only CJS and the plugin doesn't have types: 
- https://arethetypeswrong.github.io/?p=%40dcloudio%2Ftypes%403.4.8
- https://arethetypeswrong.github.io/?p=%40dcloudio%2Fvite-plugin-uni%403.0.0-alpha-3000020210521001

**Comment by userquin** [comment]
add `console.log(uni.default || uni)` before   `export default defineConfig({`

**Comment by sugar258596** [comment]
> add `console.log(uni.default || uni)` before `export default defineConfig({` and run dev or build script...

I refer to the https://github.com/dcloudio/uni-app/issues/4815, seems can be solved，Thank you very much for your answer

**Comment by RobertZSun** [comment]
你需要的是这个：https://github.com/uni-helper/plugin-uni

终极解决方案，截止目前2025/9/6
