### ISSUE TITLE
Error prompt for Unocss plugin in VSCode

### ISSUE THREAD

**Issue by rtpacks** [unocss/unocss#3779]
### UnoCSS version

v0.59.4

### Describe the bug

<img width="439" alt="IMG_2024-05-08_18-00-00" src="https://github.com/unocss/unocss/assets/97966585/7d6f9f39-4240-47cb-b16e-45ce6913801a">

unocss will prompt useless information in non-CSS areas, what information should I provide to help solve this problem?

### Reproduction

<img width="439" alt="IMG_2024-05-08_18-00-00" src="https://github.com/unocss/unocss/assets/97966585/7d6f9f39-4240-47cb-b16e-45ce6913801a">

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by userquin** [comment]
wrap the button between: `<!-- @unocss-skip-start -->` and `<!-- @unocss-skip-end -->`, check https://unocss.dev/guide/extracting#extracting-from-build-tools-pipeline

**Comment by rtpacks** [comment]
Thanks @userquin
