### ISSUE TITLE
vite引入unocss报错

### ISSUE THREAD

**Issue by Sharang-heng** [unocss/unocss#3781]
### UnoCSS version

0.60.0

### Describe the bug

在vite.config.js引入unocss会报错
![image](https://github.com/unocss/unocss/assets/69613396/0dc7a819-58e1-44b7-8f20-5b4a24fda920)
![image](https://github.com/unocss/unocss/assets/69613396/4351fde1-188c-4e83-808c-caf65f1dd2f2)

### Reproduction

在0.60.0版本会报错
但是降到0.56.5时能正常运行

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
The vite plugin is now ESM only. Change your `vite.config.ts` to `vite.config.mts`, or set `type: module` in your package json.

**Comment by Sharang-heng** [comment]
没理解，按照vite的说法https://cn.vitejs.dev/config/，我是不需要配置type:module吧
![image](https://github.com/unocss/unocss/assets/69613396/70f14a9c-6cee-4fdf-95b3-504b8c6cd041)
