### ISSUE TITLE
vscode multi-workspace plugin is invalid

### ISSUE THREAD

**Issue by mojiefong** [unocss/unocss#3782]
### UnoCSS version

0.60.0

### Describe the bug

I use the monorepo+vscode multi-workspace mode. The plug-in in the `sso` workspace can work, but it does not work in the `system-manage` workspace.

After looking at the unocss plug-in log, it is normal and no error is reported.

<img width="1540" alt="image" src="https://github.com/unocss/unocss/assets/17779577/a253c30b-b8a5-4555-a5bf-07f85f1f138a">

### Reproduction

no

### System Info

vue 3.4.23
vite 5.2.8
pnpm 9.0.5
node 20.10.0

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
I will temporarily close this issue and wait for the reproduction steps or demo. You are welcome to open it again.
<img width="1536" alt="image" src="https://github.com/unocss/unocss/assets/57086651/e0dc0ea7-a6cf-498c-942f-2909acb16654">
