### ISSUE TITLE
`--at-apply` Hex colors not working

### ISSUE THREAD

**Issue by pdsuwwz** [unocss/unocss#3788]
### UnoCSS version

0.60.0

### Describe the bug

Hex color is invalid after '--at-apply' is used:
```scss
.test-box {
  --at-apply: bg-#f8ce3d; //  <- Not working
  --at-apply: c-red;   // ✓ Correct rendering
}
```

### Reproduction

`v0.60.0` reproduction: https://stackblitz.com/edit/unocss-unocss-2mfxtm?file=package.json,src%2FApp.vue

`v0.59.4` reproduction: https://stackblitz.com/edit/unocss-unocss-7tdkfw?file=package.json,src%2FApp.vue

It seems that Hex colors are not compiling correctly at `v0.60.0`:

![image](https://github.com/unocss/unocss/assets/19891724/3dee8a98-0e6c-40e7-ba41-cd63d3829ff9)

### System Info

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
You either use `bg-hex-f8ce3d` or `bg-[#f8ce3d]`

**Comment by pdsuwwz** [comment]
> You either use `bg-hex-f8ce3d` or `bg-[#f8ce3d]`

Thanks, I tried `bg-hex-f8ce3d` and it worked, but `bg-[#f8ce3d]` still didn't work. Did the usage change? I remember the previous version with no problems at all:

![image](https://github.com/unocss/unocss/assets/19891724/a79d3940-dd83-40f3-8652-de1c68964b5b)

**Comment by antfu** [comment]
Try `--at-apply: "bg-[#f8ce3d]"` maybe it's the CSS parser no longer parse `#` as part of the content anymore

**Comment by 15200596294git** [comment]
Thanks, it helped me
