### ISSUE TITLE
transformerDirectives fails to apply in nested CSS

### ISSUE THREAD

**Issue by CodeF53** [unocss/unocss#3823]
### UnoCSS version

0.60.2

### Describe the bug

`@apply` doesn't work following nested css.
```css
.a {
  @apply 'ma'; /* applies */
  .b { @apply 'bg-green' } /* applies */
  @apply 'bg-red'; /* doesn't apply */
}
```

### Reproduction

[Reproduction](https://uno.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIHoHwCgpQCC%2BUoksiKGARjiQQEInAD04Eer72QA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQokscMUAIZZW6aCFRQAIsCipmMYADdUrClRq0AAoxbsA9AOGjxkgLTJZ8xSo6dOqAB694adIPoAbVxmx4CxAAUCJxw-EIiYlASUKwAXHAA2kaRptJWCsqqgQCUALoANJykOZxAA&css=HQQwBA3gUGYAIgA6IDYE8wHIDuBaAjAKxgC2ImA3GAPQBUYSqAlgKYDOYt1MYwARpHiN0WPgHNcYgE4sWAO0xgAvjXrDWHLjwTIRmcbhkATSqrBGA9uwUAXBroxalUIA&options=N4IgzgLgTglgxhEAuaBXApgGhNAhgOzADMB7KAWwGFVISqBle5I3AGzCxygOLPIAkI5VszYcAvkA)

### System Info

Windows 10, WSL Ubuntu, Firefox and Chromium, UnoCSS CLI, Ruby On Rails

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
[css-tree](https://github.com/csstree/csstree#readme) does not currently support nested css, so there may be problems with parsing and it is not recommended to use it this way.
