### ISSUE TITLE
grid

### ISSUE THREAD

**Issue by hansondy** [unocss/unocss#3824]
### UnoCSS version

0.59.4

### Describe the bug

grid-cols-[1fr,2fr] 写法无效
必须写成grid-cols-[1fr_2fr]
![uno_grid](https://github.com/unocss/unocss/assets/38905106/f9c2f024-b10d-4244-8c74-b7719884033b)
![uno_css2](https://github.com/unocss/unocss/assets/38905106/eacf7392-a87b-4f3f-8ffb-fd9e8a60a288)

### Reproduction

none

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
设计如此～

**Comment by Simon-He95** [comment]
<img width="548" alt="image" src="https://github.com/unocss/unocss/assets/57086651/ebc26502-04dc-49bf-b68d-c64b481df4e0">
tailwind is compatible with this situation, maybe we can consider synchronization. What do you think？ @zyyv @antfu
