### ISSUE TITLE
How to use use vue deep selector in unocss ?

### ISSUE THREAD

**Issue by vikyd** [unocss/unocss#3826]
### Clear and concise description of the problem

Vue deep selector: https://vuejs.org/api/sfc-css-features.html#deep-selectors

### Suggested solution

wanted

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Simon-He95** [comment]
try it `class="[&_.deepClass]"`

**Comment by vikyd** [comment]
@Simon-He95 

Where is the doc in https://unocss.dev/  for `class="[&_.deepClass]"` ?

**Comment by Simon-He95** [comment]
> @Simon-He95
> 
> Where is the doc in https://unocss.dev/ for `class="[&_.deepClass]"` ?

I'm sorry to say that the documentation needs improvement :)

**Comment by vikyd** [comment]
@Simon-He95 

if i want to set color green ( `color-green` ) for deep element( class `my-deep-class` ), how to set it in `class="[&_.deepClass]"` ?

**Comment by Simon-He95** [comment]
> @Simon-He95
> 
> if i want to set color green ( `color-green` ) for deep element( class `my-deep-class` ), how to set it in `class="[&_.deepClass]"` ?

try use [playground](https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIDaAyA%2BgOgFsBPAWhAFMKAHU%2BZJAXQC4AXCgD1dIHMAnKgDt0APmAB6cBBFA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6hU4AGYJwAYUrw5AcwA0obnUjhEAQUQNY2AK6JYMgJ6btUPQEkmyyLZ16AqlVABfUDJpKTlAAclMqJkhIEMFBYlFEKVlMU2hE6TlCJRVYVQAKcUFQUBpUqAAuUABtKpCmU0hEINoykM1JZ2g%2BSpC6VBDfAF1B9SLQSAALPkR6gUrC4uK6hqbOZEnp2ZCe1hJkaFVQXZQ%2BTHhVcFApgDdwGnLj5FZMaDaxn1Hiu1056rGv9yILyUPIASk%2Bi2%2BekMxjMFmsYIhAPsiCcLgK-0WkCYL3AlQAjAA6ABMSMWTFQ8B6EyM3Eg5RAUE4hMmwDei184LGI0EPlBgiAA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmAvkA)

**Comment by vikyd** [comment]
not working with underscore in class name: [playground](https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIDaAyA%2BgOgFsBPAWhAFMKAHUgVwDtKAnJGAe2Yt3mSQF0AXABcKAD2GkA5lwoMooiaQCcABmpj0APgBQ1BFwbCdUKKEixEKDCXJVajFm07deKbTAAWYOCGAB6cAhdAKCtIA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6hU4AGYJwAYUrw5AcwA0obnUjhEAVSqgAvqBk1KnUAHIArlSaRI1wYOKjEU2ZlvRP0uUIlFVhVAApxQVAtHT1IAC5QAG0o6JioPUNKMIBKdVSAXXzjHMEgA&css=Q&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmAvkA)

**Comment by Simon-He95** [comment]
> not working with underscore in class name: [playground](https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIDaAyA%2BgOgFsBPAWhAFMKAHUgVwDtKAnJGAe2Yt3mSQF0AXABcKAD2GkA5lwoMooiaQCcABmpj0APgBQ1BFwbCdUKKEixEKDCXJVajFm07deKbTAAWYOCGAB6cAhdAKCtIA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6hU4AGYJwAYUrw5AcwA0obnUjhEAVSqgAvqBk1KnUAHIArlSaRI1wYOKjEU2ZlvRP0uUIlFVhVAApxQVAtHT1IAC5QAG0o6JioPUNKMIBKdVSAXXzjHMEgA&css=Q&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmAvkA)

[PLAY](https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIDaAyA%2BgOgFsBPAWhAFMKAHUgVwDtKAnJGAe2YtPmSQF0AXABcKAD2GkA5lwoMooiaQCcABmpj0APgBQ1BFwbCdUKKEixEKDCXJVajFm07deKbTAAWYOCGAB6cAhdAKCtIA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6hU4AGYJwAYUrw5AcwA0obnUjhEAVSqgAvqBk1KnUAHIArlSaRI1wYOKjEU2ZlvRP0uUIlFVhVAApxQVAtHT1IAC5QAG0o6JioPUNKMIBKdVSAXXzjHMEgA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmAvkA) don't use `_` in class ，it will be transformed to ` `
![image](https://github.com/unocss/unocss/assets/57086651/4d74084d-26f2-43ad-ac6e-bc246cc3e52f)

**Comment by vikyd** [comment]
This issue should be reopened, as it's not documented, not working with underscore `_` in class name.

**Comment by Simon-He95** [comment]
> This issue should be reopened, as it's not documented, not working with underscore `_` in class name.

`_` is considered a space, this is by design

**Comment by Preyou** [comment]
有没有什么方法使得下划线不被转译为空格
