### ISSUE TITLE
Attributify JSX does not work when attributes are passed as props to SolidJs component

### ISSUE THREAD

**Issue by kylegl** [unocss/unocss#3834]
### UnoCSS version

0.60.3

### Describe the bug

When attributes are passed as props to component they are not applied. I'm not sure if this is solidJs specific or not.

Example:

```ts
// does not work 
<MyComponent text-red /> 
```
text-red is transformed to `text-red={true}`

For this to work, I've found that its needed to set the `trueToNonValued` option to `true` in `presetAttributify`'s options. Maybe we can add a note in both `presetAttributify` and `Attributify JSX`?

### Reproduction

https://stackblitz.com/~/github.com/kylegl/solid-uno-attributify

### System Info

system: Ubuntu 20.04.5 LTS
browser: Chrome Version 124.0.6367.208 (Official Build) (64-bit)
framework: @solidJs/start  v1.0.0

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
<img width="1092" alt="image" src="https://github.com/unocss/unocss/assets/57086651/414b7d97-7a0d-4900-9787-dbf2b787839b">
Your reaping Demo will always be stuck when installing dependencies. Can you help solve it?

> ### UnoCSS version
> 0.60.3
> 
> ### Describe the bug
> When attributes are passed as props to component they are not applied. I'm not sure if this is solidJs specific or not.
> 
> Example:
> 
> ```ts
> // does not work 
> <MyComponent text-red /> 
> ```
> 
> text-red is transformed to `text-red={true}`
> 
> For this to work, I've found that its needed to set the `trueToNonValued` option to `true` in `presetAttributify`'s options. Maybe we can add a note in both `presetAttributify` and `Attributify JSX`?
> 
> ### Reproduction
> https://stackblitz.com/~/github.com/kylegl/solid-uno-attributify
> 
> ### System Info
> system: Ubuntu 20.04.5 LTS browser: Chrome Version 124.0.6367.208 (Official Build) (64-bit) framework: @solidJs/start v1.0.0
> 
> ### Validations
> * [x]  Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
> * [x]  Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
> * [x]  Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
> * [x]  The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
I will temporarily close this issue and wait for you to provide a usable mini-repo

**Comment by kylegl** [comment]
Sorry i missed this let me look into it
