### ISSUE TITLE
在less 中 @apply  非整数值 不能增长解析

### ISSUE THREAD

**Issue by miaojinsing** [unocss/unocss#3835]
### UnoCSS version

0.60.2

### Describe the bug

py-0.5 => padding-top: 0;
    padding-bottom: 0;

### Reproduction

vite + react-ts  + css module

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
duplicate：#3823
if you not use nested css，please provide mini repo
