### ISSUE TITLE
Not all rules get considered (first rule wins?)

### ISSUE THREAD

**Issue by MatthiasDunker** [unocss/unocss#3836]
### UnoCSS version

Latest

### Describe the bug

Given the following config, I would expect unocss to generate the following code:

```
// part of the config
      rules: [
        [
          /^(test|test2)$/,
          ([match, classVariant]) => {
            return `:root { --color-from-root: red; }`;
          },
          {
            layer: "settings",
          },
        ],
        [
          /^(test|test2)$/,
          ([match, classVariant]) => {
            return `.${match} { background: var(--color-from-root); }`;
          },
          {
            layer: "objects",
          },
        ],
      ],
```

```
/* generated CSS */

/* layer: settings */
:root { --color-from-root: red; }

/* layer: objects */
.test { background: var(--color-from-root); }
.test2 { background: var(--color-from-root); }
```

**Experienced**
Unfortunately, the rule on the settings layer does not get rendered. Only if I remove the second rule (on the object layer).

### Reproduction

[Codesandbox.io](https://codesandbox.io/p/devbox/unocss-rule-overwrite-ns5k9r?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwkewet600073b6o2wxqxn73%2522%252C%2522sizes%2522%253A%255B69.86719787999999%252C30.132802120000008%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwkewet600023b6ofadnlmg6%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwkewet600043b6o32sngsix%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwkewet600063b6oibkec4yk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B48.44402277%252C51.55597723%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwkewet600023b6ofadnlmg6%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwkewet500013b6o0uq1mgb9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clwkewet600023b6ofadnlmg6%2522%252C%2522activeTabId%2522%253A%2522clwkewet500013b6o0uq1mgb9%2522%257D%252C%2522clwkewet600063b6oibkec4yk%2522%253A%257B%2522id%2522%253A%2522clwkewet600063b6oibkec4yk%2522%252C%2522activeTabId%2522%253A%2522clwkglzfi00p73b6o5r6ooa0y%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A3000%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clwkg3px901253b6odemcdx47%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A3000%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clwkglzfi00p73b6o5r6ooa0y%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clwkewet600043b6o32sngsix%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwkewet600033b6oj371ca5l%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clwkewet600043b6o32sngsix%2522%252C%2522activeTabId%2522%253A%2522clwkewet600033b6oj371ca5l%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
<img width="644" alt="image" src="https://github.com/unocss/unocss/assets/57086651/6f97fa59-6c89-4f12-8968-3948016df495">
Your rules configuration is wrong

**Comment by antfu** [comment]
Yes, the first matched wins. This is expected behavior.

**Comment by MatthiasDunker** [comment]
> Your rules configuration is wrong

I am not sure what you mean. In your image it looks like a [Static Rule](https://unocss.dev/config/rules#static-rules), but there are also [Dynamic Rules](https://unocss.dev/config/rules#dynamic-rules) (and my example is actually working as can be seen in the codesandbox).

**Comment by MatthiasDunker** [comment]
> Yes, the first matched wins. This is expected behavior.

Thanks for clarifying @antfu . That was not clear to me. Actually, this is kind of against the flexibility of having the option to render CSS to specific layers in my opinion.

Is there a concept that you can render to different layers from within one rule? Or any other chance to reach the expected (from my initial post) behavior?

**Comment by antfu** [comment]
Maybe we could have a flag for a rule to say they don't stop the processing the following rules. But that feels like quite some changes as it might affect how our caching and utilties works. I am not sure if I would implement it myself, but if you are interested, feel free to drop an PR and then we could discuss how we could do it in the least breaking way.

For now, you can use shortcuts to merge multiple rules into one.

**Comment by antfu** [comment]
This is how you can do it: 

https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIAuBTJn0B8AKrpsAPTgQFA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwARFxUS6dPQG4kSDAA9IsdNgCGXADbxMOfERLBSACmRUF0d%2BDCg6AC5EKlQFXlxSSLgAWgAmWVQORwYotIy4KXBiDFwYJOSARnyPZzcoqpi4CA4AKwwJMqj0xp5gF2BeeiiAZlk1WToAC2gYCR4kgG1GhYB6AD0-GHoYAB8tuhhUgEoAEhXyOD8FgH0LkEdZyYBdI7gAXgA%2BOAWAciYfi4-ABCALgPwIPyeADp7mA-MB3l97o8ANQ-a7XH5wFFwYBHJ5UJ6yEQKRaNEmMZQQAKNVBoRxQADWUT0IAwaGAjj0%2BTUR3yFOYrHY3F4Aj8fPJ8nEUlwdBpqAVcBsbEcAAVtGAwoMkoFFQqOXQwMF%2BCy8P18MkOC4IBJGdzaQq9AA3LXACSOFzJD2%2BXB6FkgYBoNAuDD2vVwcaNXn5XWK3CONksgXJfYwMN6qCuIbfB2oJbhxXrTbbPbbY4YghnfLhq7IiSTC4SYImABqDM5pReiOiBYzjC4UFwcAABhFtBB4AgUskpNaoMktDpkuOYFFaGgzBHhxZe6hI7uewe4Mawiy4nhEune-uC0TczmD0XU6WDuXrkCq-fULWHvXG826DbdhHE7V5PkPA9aBgAch2HKETgQOtJg0KcsltUhtEMNAoidBk-GSGcIDnBdtBAZcIAnI5NzUbcvwjas9VjXcTygFlmjaDpTAYxUb3DO9e3zXcnxLVM3yYT8Dx-R4iUQOBSBKMIHmgCMwK%2BJjeygmCR3gxDf2Q2S0MZDCICwnC8II2doBIpcVyorcd13Xi9X45yeVkO9eQsIA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgTgpgzgDg9gOygSwG4RALgGYEMA2UEANCAC5i5LZxgC2AEmXflnoSeZdbXQMIBXKGTj8AymLYEiAXyA

Just for demo, but ofc you refactoring it to make it better

**Comment by MatthiasDunker** [comment]
Great. I already had a look at the code....yes, might require some work here and there.
Let me get to know the codebase and see if I find a simple and non-breaking solution 👍

Thanks for the demo. This works great.
I am currently working on a CSS vars framework and am looking for integration possibilities (unocss, tailwind, ...). So, I hope to find time for a PR (but am eager to do so) :)
