### ISSUE TITLE
`content-none` not working

### ISSUE THREAD

**Issue by CNSeniorious000** [unocss/unocss#3841]
### UnoCSS version

latest

### Describe the bug

`prose`'s backticks on `<code>` elements can't be removed by `[&_code]:(before:content-none after:content-none)` or `@apply before:!content-none after:!content-none`.

### Reproduction

**[unocss playground](https://unocss.dev/play/?html=DwEwlgbgBA5gTmEUAOAbAhgYwKYFowAu2AtgM644B2RcUYlp2BuADFAGZgAe2IAfACgoUUJA6psXcZIoB7VLHTJcAVihEuzOL1wAWQQKHCR6OATCYJKOLMbrJzeNmyVcAZkHHjwTLJDYoACNsdlltAC5fahdmSllKAPR2Gkj4ompcOIS%2BOKCsAGtzTHyoAAoEGAALAgBKYAB6X39Pb3rTIokDL2B2iytkG0YW7qbsPgB3Qkq84qKS0vGbShg6xr8xo2EG3ssNzZMzPoCB2wDLdFJSAF4AIgBtADIAfVGAXXDS4NCIqPTY%2BMSyWwcFS0QyWWwNRuw28owmUxmhQsJQIslkZUW8RWDTh%2B22h12BiMDXAEEEJMggiAA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDAVSoPd%2BwwBVbvdTSY3AAW9joMmPCQcnyc4DQAIrB0LLAAblDaAL6gcjSUnKAA5BZUTJCQRYKCxKKIMvKYFtD1sgqEKmqw6gAUktIRUTE0cTSQAFygANqD0bHxSSnWGZA9AJQAuh5OBgKTUzuuVOuans7GpoyW1nYnZ7u%2B-oEhtutbgllrgkA&css=HQBwTg9gzgpgBAYwgE3gbwFBzgAQIYggA2AnnAEYwBmEYMAXAIRIB2ALjOwLQsQvx4qHME1YduvfgG4MAXwxA&options=N4IgLgTghgdgzgMwPYQLYGECucxIwZXxAC4EoAbOAUwBpxp5k0AJMVcksyqgXyA)**

### System Info

Edge, Windows

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by henrikvilhelmberglund** [comment]
You need to write it like this:
```html
<article prose class="before:[&_code]:content-none after:[&_code]:content-none text-green-300">
  <code>no backticks</code>
</article>
```

**Comment by CNSeniorious000** [comment]
Thanks!

And another issue is, if you open the `custom css` panel in the playground example I provided, I wrote

```css
.prose code {
  @apply before:!content-none after:!content-none;
}
```

And I added `transformerDirectives` in config, but this don't work too. I wonder why this transformer doesn't work

**Comment by henrikvilhelmberglund** [comment]
> Thanks!
> 
> And another issue is, if you open the `custom css` panel in the playground example I provided, I wrote
> 
> ```css
> .prose code {
>   @apply before:!content-none after:!content-none;
> }
> ```
> 
> And I added `transformerDirectives` in config, but this don't work too. I wonder why this transformer doesn't work

This is because of attributify, you can't really target .prose because the class doesn't exist on the element, it's an attribute.

```css
[prose] code {
  @apply before:content-none after:content-none;
}
```

or `class="prose"`.
