### ISSUE TITLE
pnpm add -D @unocss/nuxt  bug

### ISSUE THREAD

**Issue by TomatoDroid** [unocss/unocss#3844]
### UnoCSS version

0.60.3

### Describe the bug

After running pnpm add -D @unocss/nuxt, there are no unocss packages in node_modules, resulting in a unocss not found ts error in uno.config.ts.
<img width="1163" alt="image" src="https://github.com/unocss/unocss/assets/22388686/d13e4ff8-6962-4d87-9ade-d16fd365d762">
<img width="310" alt="image" src="https://github.com/unocss/unocss/assets/22388686/e2cd0bf2-330e-4114-b20e-8c33da6e93ee">

I don't know why, I just find that the correct project with node_modules will have the unocss package。

thank you very much!!

### Reproduction

git@github.com:TomatoDroid/since-then.git

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
You need to install `unocss` as devDeps, or enable hoisted mode in pnpm.

**Comment by brokuka** [comment]
@antfu It would be great if you mentioned it in the documentation
