### ISSUE TITLE
Map long class to short class

### ISSUE THREAD

**Issue by 321paranoiawhy** [unocss/unocss#3852]
### Clear and concise description of the problem

Suppose we have an element like this:

```html
<div opacity-50>Example</div>
```

We know `opacity-50` is equal to `op-50`, the latter is shorter and can reduce code size.

So can `UnoCSS` do this transform work automatically? That is:

```html
<!-- developer write `opacity-50`, unocss transform it to `op-50` -->
<!-- of cource, this feature is optional, depends on unocss config-->
<div op-50>Example</div>
```

Or, `UnoCSS` already have this solution, if you know, please comment, thanks.

### Suggested solution

add `useAbbr`/`useAbbreviation`/`useShorthand` param in unocss config

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [ ] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Simon-He95** [comment]
try to use shortcuts
https://unocss.dev/config/shortcuts#usage

**Comment by 321paranoiawhy** [comment]
> try to use shortcuts https://unocss.dev/config/shortcuts#usage

But we need enumerate shortcuts, often we do not known all classes and we want the framework automatically do this mapping work.

Imagine this:

```js
const SHOULD_TRANSFORMED_CLASSES = {
  'opacity-(.*)': 'op-(.*)'
};
```

**Comment by Simon-He95** [comment]
You can get the solution from the [documentation](https://unocss.dev/config/rules#dynamic-rules)

**Comment by 321paranoiawhy** [comment]
> You can get the solution from the [documentation](https://unocss.dev/config/rules#dynamic-rules)

I just do not want enumerate classes, that's too incredible...
