### ISSUE TITLE
Allow `virtual:uno.css` to generate an url

### ISSUE THREAD

**Issue by machour** [unocss/unocss#3853]
### Clear and concise description of the problem

In https://github.com/unocss/unocss/pull/3850, I updated the Remix template to the latest version that uses Vite.

The implementation still uses the CLI to generate a CSS file, that is later imported by Remix as a `<link rel="stylesheet" ../>`

I looked into using UnoCSS's vite plugin instead, and take advantage of the `virtual:uno.css` import, but as far as I understand, this dump the CSS into a `<style>` tag in the HTML, and doesn't currently allow to retrieve an URL.

### Suggested solution

To stay in the Remix philosophy, would it be possible to make the following work ?

```ts
import styles from "virtual:uno.css?url"

export const links: LinksFunction = () => [
  { rel: 'stylesheet', href: styles },
]
```

### Alternative

The alternative is either to continue generating the CSS file from the cli, or just dump the CSS into the root.tsx file, but that's not really the "remix way" as the page would be heavier, and no caching is possible.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Couldn't we just add 

```ts
import `uno.css`
```

to the app entry?

**Comment by machour** [comment]
This would dump the whole CSS within the HTML document, whereas I'm trying to use it via a `<link />` tag.

Imagine if you disabled React on the frontend with Remix, turning the app into a classic MPA. Each page would have the whole CSS injected in the page, instead of using a cached (and fingerprinted) `.css` asset file.

**Comment by hi-ogawa** [comment]
> This would dump the whole CSS within the HTML document

Can you provide a reproduction? I think this is Remix's development-only behavior to prevent FOUC. For build, `import "virtual:uno.css"` side effect should become `<link />` tag and that allows css asset to be cached properly.

**Comment by machour** [comment]
@hi-ogawa You are absolutely right, sorry for the noise 🙏🏼

**Comment by ryoppippi** [comment]
Hi
I'd like to get a css url like tailwind did.
when I try to use UnoCSS with Remix or Tanstack router, it doesn't work on SSR mode because the generated CSS is not in the head tag

**Comment by ryoppippi** [comment]
I'm facing this issue on tanstack start.
https://github.com/TanStack/router/issues/3023#issuecomment-2646293866
So I need to get url!

**Comment by mtt-artis** [comment]
same here +1
