### ISSUE TITLE
Renaming layers is not working

### ISSUE THREAD

**Issue by mortona42** [unocss/unocss#3864]
### UnoCSS version

0.60.4

### Describe the bug

I am trying to rename layers by copying the instructions here: https://unocss.dev/config/layers#css-cascade-layers

This does enable layers, but default remains default instead of changing to utilities.

I have tried with vite and unocss cli but get the same results.

The layers config and js imports (EX import 'uno:utilities.css') don't seem to work either.

See the playground link.

### Reproduction

https://unocss.dev/play/?html=DwEwlgbgBAFgtAMwK4BsVQC4FMAeG4DGWAdtgE5QIq5QDOW1B%2BxA9sVlAIZoBcGZnYrTAYwbOABYADFIB8AKChRQkKAFtOCpUpXRseOAFYc6BAHcAjDK7EwG7HABGLJMSJxuGG3c4OCL0jgwYgRgkQ5BHwcQJAFRcQtaLW0lAFVWAGEAZSzFbWAAenAIZJ1iqBYABwBmKUxcfBQAc0ozWrq1C1LtABUYDmDaDEEvcRAsDWIQKABBDBY1MAIobKyoEibgrAA6PJ0iyG7ddQAmSmocKAArJCGwBABPQhJyeoMTkwqaupgWCCwyABeABEVQAHFJgd0dJw9ikoGBCJwyM5iHAUCwmiw4JsMDAkI44Sl9Phgv0yCIidoYGQsAgQTAMBhKrQeAUCrj8Y5tv41AVXCwCLRaPzWELaMCqUphmQmlgMCCAPqOFCCADWkvhUFkhU0cMKxWSBsO8mNJVN5U4jloLBQSGwUGcTIWRigFKajLgdWoCHwdRJz1IAK%2BtVa7WSYwmgmmAHaEUJhqQoHHkGgHlACLd5osAF5W6img4lIA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDASSarID3fsMBVKtoAvqByNJScoADkFlRMkJCRgoLEoogy8pgW0GmyCoQqarDqABSS0pRW3FYAKpRK8QAymLbgNJAAXKDF0M2tAJSgALwAfBI6IKDVABbg6XKZ2aA9LTSgAO6w0NCg2LMViFVpiJSgiDOgAERWm7DWUBegSgDKT0u9NAB0OjZdy61Dg0GUVyC0QkT6OmkdEQFho8Ci1zgdwSSWkE2ms0gUz4iCYVkgbxW602212oH2h1OJzOswuWJxeIED0gFlw71O50ockuiNusHujxehNaX2kP267MBQMi9P4jISEOkUMMsPh0WsSP5kA%2Bstx%2BMS4zARi25Jpqz%2BbWJJoAVhZIGk7bMabBVvBMJxZpgCTTBa8LRR3eAvoEvDQslBOgBtSGgSORPH28K0cORTQSUDuaB8TqROioSKgQIAXS8JZ0uvlnTKSvjduOnGQFaskRzrBIyGg6lOxBQfEw8HUs2xADdWu02yhWJhoKmdCGdE4DAIozHF34qMU%2Bl5HD5jKZGJZrHZN9vvM5EG4PKUY9JIExp%2BBOgBGD4AJlP0iYqHgOampm4HQgFAnA6lMwCzkqhZbjoZaBBCQA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYGECucxIwZXxAC4EoAbOAUwBpxp5k0AJMVcksyqgXyA

### System Info

Linux Mint 21.2
Firefox 126.0.1
Unocss 0.60.4

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by lzl0304** [comment]
The configuration for [outputtocsslayers](https://unocss.dev/config/#outputtocsslayers) document is correct. It seems like the example hasn't been updated. The following configuration can rename a layer.

```JavaScript
outputToCssLayers: {
  cssLayerName: (layer) => {
    if (layer === 'default')
      return 'utilities'

    if (layer === 'shortcuts')
      return 'utilities.shortcuts'
  },
}
```
