### ISSUE TITLE
error when starting dev server: TypeError: (0 , _presetWind.presetWind) is not a function

### ISSUE THREAD

**Issue by pdsuwwz** [unocss/unocss#3869]
### UnoCSS version

0.60.4

### Describe the bug

Running the project results in an error：

```sh
➜  unocss-vite-test npm run dev

> unocss-vite-test@0.0.0 dev
> vite

error when starting dev server:
TypeError: (0 , _presetWind.presetWind) is not a function
    at /Users/wisdom/Documents/workspace/others/unocss-vite-test/node_modules/@unocss/preset-uno/dist/index.mjs:69:43
    at /Users/wisdom/Documents/workspace/others/unocss-vite-test/uno.config.ts:10:25
    at evalModule (/Users/wisdom/Documents/workspace/others/unocss-vite-test/node_modules/jiti/dist/jiti.js:1:247359)
    at jiti (/Users/wisdom/Documents/workspace/others/unocss-vite-test/node_modules/jiti/dist/jiti.js:1:245172)
    at loadConfigFile (file:///Users/wisdom/Documents/workspace/others/unocss-vite-test/node_modules/unconfig/dist/index.mjs:177:13)
    at async Object.load (file:///Users/wisdom/Documents/workspace/others/unocss-vite-test/node_modules/unconfig/dist/index.mjs:98:24)
    at async loadConfig (file:///Users/wisdom/Documents/workspace/others/unocss-vite-test/node_modules/@unocss/config/dist/index.mjs:43:18)
    at async reloadConfig (file:///Users/wisdom/Documents/workspace/others/unocss-vite-test/node_modules/@unocss/vite/dist/index.mjs:93:20)
    at async Object.updateRoot (file:///Users/wisdom/Documents/workspace/others/unocss-vite-test/node_modules/@unocss/vite/dist/index.mjs:125:12)
    at async configResolved (file:///Users/wisdom/Documents/workspace/others/unocss-vite-test/node_modules/@unocss/vite/dist/index.mjs:1031:7)
    at async Promise.all (index 2)
    at async resolveConfig (file:///Users/wisdom/Documents/workspace/others/unocss-vite-test/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:69639:5)
    at async _createServer (file:///Users/wisdom/Documents/workspace/others/unocss-vite-test/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:65857:20)
    at async CAC.<anonymous> (file:///Users/wisdom/Documents/workspace/others/unocss-vite-test/node_modules/vite/dist/node/cli.js:762:24)
```

![image](https://github.com/unocss/unocss/assets/19891724/a5ac2ea4-7284-46d9-9b4f-48ca9397a007)

![image](https://github.com/unocss/unocss/assets/19891724/437ba019-1771-498d-9b70-fea24467c701)

uno.config.ts：

```ts
import {
  defineConfig,
  presetAttributify,
  presetUno,
  transformerDirectives
} from 'unocss'

export default defineConfig({
  presets: [
    presetUno(),
    presetAttributify(),
  ],
  transformers: [
    transformerDirectives()
  ],
})

```

vite.config.ts:

```ts
import { fileURLToPath, URL } from 'node:url'

import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

import UnoCSS from 'unocss/vite'


// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    UnoCSS(),
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    }
  }
})

```

### Reproduction

https://github.com/pdsuwwz/unocss-vite-test

https://stackblitz.com/edit/unocss-unocss-whabz3?file=uno.config.ts,vite.config.ts

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by xtqjh** [comment]
同问
![image](https://github.com/unocss/unocss/assets/7663676/8039ff33-d98a-4ecc-99fc-4f1aa22dcf14)

**Comment by KaneOne** [comment]
我也是，刚刚出现了，本地可以编译，阿里云云效流水线报错
> ### UnoCSS version
> 0.60.4
> 
> ### Describe the bug
> Running the project results in an error：
> 
> ```shell
> ➜  unocss-vite-test npm run dev
> 
> > unocss-vite-test@0.0.0 dev
> > vite
> 
> error when starting dev server:
> TypeError: (0 , _presetWind.presetWind) is not a function
>     at /Users/wisdom/Documents/workspace/others/unocss-vite-test/node_modules/@unocss/preset-uno/dist/index.mjs:69:43
>     at /Users/wisdom/Documents/workspace/others/unocss-vite-test/uno.config.ts:10:25
>     at evalModule (/Users/wisdom/Documents/workspace/others/unocss-vite-test/node_modules/jiti/dist/jiti.js:1:247359)
>     at jiti (/Users/wisdom/Documents/workspace/others/unocss-vite-test/node_modules/jiti/dist/jiti.js:1:245172)
>     at loadConfigFile (file:///Users/wisdom/Documents/workspace/others/unocss-vite-test/node_modules/unconfig/dist/index.mjs:177:13)
>     at async Object.load (file:///Users/wisdom/Documents/workspace/others/unocss-vite-test/node_modules/unconfig/dist/index.mjs:98:24)
>     at async loadConfig (file:///Users/wisdom/Documents/workspace/others/unocss-vite-test/node_modules/@unocss/config/dist/index.mjs:43:18)
>     at async reloadConfig (file:///Users/wisdom/Documents/workspace/others/unocss-vite-test/node_modules/@unocss/vite/dist/index.mjs:93:20)
>     at async Object.updateRoot (file:///Users/wisdom/Documents/workspace/others/unocss-vite-test/node_modules/@unocss/vite/dist/index.mjs:125:12)
>     at async configResolved (file:///Users/wisdom/Documents/workspace/others/unocss-vite-test/node_modules/@unocss/vite/dist/index.mjs:1031:7)
>     at async Promise.all (index 2)
>     at async resolveConfig (file:///Users/wisdom/Documents/workspace/others/unocss-vite-test/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:69639:5)
>     at async _createServer (file:///Users/wisdom/Documents/workspace/others/unocss-vite-test/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:65857:20)
>     at async CAC.<anonymous> (file:///Users/wisdom/Documents/workspace/others/unocss-vite-test/node_modules/vite/dist/node/cli.js:762:24)
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/19891724/336729684-a5ac2ea4-7284-46d9-9b4f-48ca9397a007.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NzUwMzMsIm5iZiI6MTcxNzU3NDczMywicGF0aCI6Ii8xOTg5MTcyNC8zMzY3Mjk2ODQtYTVhYzJlYTQtNzI4NC00NmQ5LTliNGYtNDhjYTkzOTdhMDA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDA4MDUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjYTI5ZjEyODM4ZWY2YWZhMjAxMzBmZTg4M2JhZjYyMzRhYzc4MzhmNDQzYWJmNTFmZmQ4NjRiZDM4YmFlNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tHeH3Eam1cBZSr3PoeDqK7Z00S0uPnje-WUQiLd_sYA)
> 
> ![image](https://private-user-images.githubusercontent.com/19891724/336742024-437ba019-1771-498d-9b70-fea24467c701.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1NzUwMzMsIm5iZiI6MTcxNzU3NDczMywicGF0aCI6Ii8xOTg5MTcyNC8zMzY3NDIwMjQtNDM3YmEwMTktMTc3MS00OThkLTliNzAtZmVhMjQ0NjdjNzAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDA4MDUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0MzYyM2I1MzE2MjEzMDk1NDZhNWI5NzI4MmVjZjJiYTNlODdjMzU4NWQ1MDQ0ODAyODQ5NmUyODQ5MDQ0MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r0cHOjN43rgbpRrQYAiY3-msUABEcUfMKZqC5Q1Xa-c)
> 
> uno.config.ts：
> 
> ```ts
> import {
>   defineConfig,
>   presetAttributify,
>   presetUno,
>   transformerDirectives
> } from 'unocss'
> 
> export default defineConfig({
>   presets: [
>     presetUno(),
>     presetAttributify(),
>   ],
>   transformers: [
>     transformerDirectives()
>   ],
> })
> ```
> 
> vite.config.ts:
> 
> ```ts
> import { fileURLToPath, URL } from 'node:url'
> 
> import { defineConfig } from 'vite'
> import vue from '@vitejs/plugin-vue'
> 
> import UnoCSS from 'unocss/vite'
> 
> 
> // https://vitejs.dev/config/
> export default defineConfig({
>   plugins: [
>     vue(),
>     UnoCSS(),
>   ],
>   resolve: {
>     alias: {
>       '@': fileURLToPath(new URL('./src', import.meta.url))
>     }
>   }
> })
> ```
> 
> ### Reproduction
> https://github.com/pdsuwwz/unocss-vite-test
> 
> https://stackblitz.com/edit/unocss-unocss-whabz3?file=uno.config.ts,vite.config.ts
> 
> ### System Info
> _No response_
> 
> ### Validations
> * [x]  Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
> * [x]  Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
> * [x]  Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
> * [x]  The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by renardsas** [comment]
> I also encountered this issue today. The reason is that the upstream `jiti` package was upgraded from 1.21.0 to 1.21.1, which caused problems with the downstream `unocss` package. The solution is to fix the version of the `jiti` package. If you are using pnpm, you can write this in the package.json:
> 
> ```
> {
>   "pnpm": {
>     "overrides": {
>       "jiti": "1.21.0"
>     }
>   }
> }
> ```

Thank you 💯

**Comment by PixelForm** [comment]
Had the same problem with a clean install of UnoCSS and I saw the example from UnoCSS docs in stackblitz had the exact same error.

**Comment by renardsas** [comment]
> Had the same problem with a clean install of UnoCSS and I saw the example from UnoCSS docs in stackblitz had the exact same error.

Yes, and older versions are also impacted: 0.60.3, 0.60.2, etc.
@hex-ci  provided an explanation and a solution that works (thanks @hex-ci 🙏).

**Comment by yknn** [comment]
If you are using npm, add it to the package.json root tag：
"overrides": {
    "jiti": "1.21.0"
}

**Comment by Azir-11** [comment]
If you are using pnpm, You can update the pnpm version to 9.x

**Comment by pi0** [comment]
[jiti@1.21.2](https://github.com/unjs/jiti/releases/tag/v1.21.2) was released as a hotfix for this issue. You can remove the resolution and upgrade your lock file to receive the fix 🤞🏼
