### ISSUE TITLE
TypeError: (0 , _vite.defineConfig) is not a function

### ISSUE THREAD

**Issue by YellowDaHe** [unocss/unocss#3870]
### UnoCSS version

1.21.0

### Describe the bug

TypeError: (0 , _vite.defineConfig) is not a function

### Reproduction

![error](https://github.com/unocss/unocss/assets/105106106/a0a47f20-b2e1-456f-b452-d0aa9c95350f)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YellowDaHe** [comment]
版本更新出问题了？

**Comment by Simon-He95** [comment]
duplicate: #3869
