### ISSUE TITLE
parseCssColor return CSSColorValue have wrong type 

### ISSUE THREAD

**Issue by sheng-ri** [unocss/unocss#3871]
### UnoCSS version

0.60.3

### Describe the bug

parseCssColor in @unocss/rule-utils return wonrg type of hex color.
```js
parseCssColor('#1111') ->  {type: "rgb", components: Array(3), alpha: 0.07}
parseCssColor('#11111111') -> {type: "rgb", components: Array(3), alpha: 0.07}
parseCssColor('rgba(1,1,1,1)') -> {type: "rgba", components: Array(3), alpha: "1"}
```
This should return rgba in this case.

### Reproduction

parseCssColor('#1111') ->  {type: "rgb", components: Array(3), alpha: 0.07}
parseCssColor('#11111111') -> {type: "rgb", components: Array(3), alpha: 0.07}
parseCssColor('rgba(1,1,1,1)') -> {type: "rgba", components: Array(3), alpha: "1"}

### System Info

Os: Windows 11
Framework: Vue, Vite

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
parseCssColor does this, if you want to get rgba you should refer to this [test](https://github.com/unocss/unocss/blob/main/test/color.test.ts)
