### ISSUE TITLE
Vscode unocss not working

### ISSUE THREAD

**Issue by wuchaoxin** [unocss/unocss#3883]
### UnoCSS version

0.60.3

### Describe the bug

When using ` npm create ' vite@latest `After creating the project, the vscode unocss plugin does not work and the perception is invalid.

当使用 `npm create vite@latest` 创建项目后，vscode  unocss 插件不起作用，感知失效（在其他项目中 unocss 插件可正常使用）。

### Reproduction

复现步骤（由于是 vscode 插件影响，难以给出一个示例）：
1. `npm create vite@latest` 创建 vue3 项目 + TS；
2. `pnpm add -D unocss`
3. 安装插件
```
// vite.config.ts
import UnoCSS from 'unocss/vite'
import { defineConfig } from 'vite'

export default defineConfig({
  plugins: [
    UnoCSS(),
  ],
})
```
4. 创建 uno.config.ts 文件：
```
// uno.config.ts
import { defineConfig } from 'unocss'

export default defineConfig({
  // ...UnoCSS options
})
```
5. 将 virtual:uno.css 添加到您的主入口文件：
```
// main.ts
import 'virtual:uno.css'
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by wuchaoxin** [comment]
@antfu 谢谢你的回复，不过我这边有一个疑惑，想让 unocss 插件生效，并且让感知起作用，需要哪一些配置？
目前我所知为：
1. 安装了 unocss；
2. 插件正常配置；
3. 创建 uno.config.ts 文件；
4. 将 virtual:uno.css 添加到您的主入口文件。
而 unocss 插件会自动寻找 root，完成配置，我是否遗漏了某一步？

**Comment by Simon-He95** [comment]
> @antfu 谢谢你的回复，不过我这边有一个疑惑，想让 unocss 插件生效，并且让感知起作用，需要哪一些配置？ 目前我所知为：
> 
> 1. 安装了 unocss；
> 2. 插件正常配置；
> 3. 创建 uno.config.ts 文件；
> 4. 将 virtual:uno.css 添加到您的主入口文件。
>    而 unocss 插件会自动寻找 root，完成配置，我是否遗漏了某一步？

你创建完重启 vscode 了嘛

**Comment by wuchaoxin** [comment]
@Simon-He95 嗯嗯，重启了。在 vite 创建的项目模板中，我能够正常使用 unocss，但是 unocss 插件并没有生效。而我切换到 vitesse 模板中 unocss 插件表现正常。我不太清楚是否跟本地依赖是否有额外关系。

**Comment by Simon-He95** [comment]
> // main.ts
> import 'virtual:uno.css'

抱歉回复有些晚了，我按照你的步骤尝试过了，unocss插件能够正常使用，配置完成后重启vscode就生效了
