### ISSUE TITLE
css not working properly (UnoCSS/Storyblok)

### ISSUE THREAD

**Issue by webmaster-dexontechnology** [unocss/unocss#3892]
### UnoCSS version

^0.60.0

### Describe the bug

I get css value from input field of storyblok but it's not working properly. When I comment out the CSS code, it works fine, but when I remove the comment, it doesn't work.

Thank you in advanced.

### Reproduction

**Storyblok:**
![image](https://github.com/unocss/unocss/assets/134662978/941c1fa1-7a19-4ffb-a381-ebc26baf0662)

**Working:**
![working](https://github.com/unocss/unocss/assets/134662978/c56da5bf-7541-4b42-baca-5c00e692df3e)

**Not working:**
![not working](https://github.com/unocss/unocss/assets/134662978/f140b23e-7ec3-43d8-91fa-3fb273870358)

**Repo:**
https://stackblitz.com/edit/nuxt-3-quickstart-demo-q2gaf3?file=storyblok%2FHero%2FHome.vue

### System Info

"nuxt": "^3.11.2",
"@unocss/eslint-config": "^0.60.0",
"@unocss/nuxt": "^0.60.0",
"@storyblok/nuxt": "^6.0.10"

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
Because `my-16` is not in the template, it seems to be added by storyblok
