### ISSUE TITLE
【Feature】Select alternative versions with playground support.

### ISSUE THREAD

**Issue by Tzyito** [unocss/unocss#3895]
### Clear and concise description of the problem

When I want to verify a problem with a version of unocss in my project, I can't reproduce it on playground (because it's always the latest version), so I can't provide the minimum repository when I want to reproduce the problem (the project is private).

### Suggested solution

We can provide playground with the option to select the unocss version in order to restore the problem most easily

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Tzyito** [comment]
like this
<img width="400" alt="image" src="https://github.com/unocss/unocss/assets/37643993/1bd7deda-ea22-41a4-8ede-9be2d5bfd052">

**Comment by Simon-He95** [comment]
If you have problems with previous versions, I think you should upgrade to the latest version instead of reproducing the problem with the old version

**Comment by Simon-He95** [comment]
BTW, Even if you reproduce the problem of the old version, there is no need to reproduce it again if the new version has solved it.

**Comment by Tzyito** [comment]
> BTW, Even if you reproduce the problem of the old version, there is no need to reproduce it again if the new version has solved it.

thanks for reply!  IMO, if the latest version (eg: 0.1.2) has an error that does not appear in 0.1.1, can the problem be located and verified more quickly? Instead of comparing by upgrading or downgrading the version in the project

**Comment by Simon-He95** [comment]
We can use stackblitz to achieve this requirement, because I can't think of any good way to switch versions in the current playground. Do you have any good ideas，@antfu?

**Comment by Tzyito** [comment]
> We can use stackblitz to achieve this requirement, because I can't think of any good way to switch versions in the current playground. Do you have any good ideas，@antfu?

stackblitz not easy. We can use the playground to reappear error problem, if we can provide other version. Not only to verify other versions, but also to better verify the current version

IMO, we can replace the local resource library with cdn. just like this [case](https://github.com/microsoft/TypeScript-Website/blob/7cf9aa0f3abd547f76573a73bda753fa5e381c14/packages/sandbox/script/downloadReleases.js#L11)

But I have no idea how to replace unocss resources, maybe we can exclude them before packaging and introduce them through cdn?

**Comment by henrikvilhelmberglund** [comment]
I would also like this, makes testing for regressions really easy.

**Comment by Tzyito** [comment]
I made a PR to solve this problem. Can anyone help to check it? @Simon-He95
