### ISSUE TITLE
 it doesn't work when I use unocss to set some  antd component style

### ISSUE THREAD

**Issue by Sharang-heng** [unocss/unocss#3907]
### UnoCSS version

0.60.3

### Describe the bug

`<RangePicker important-w-50px allowClear style={{ width: '50px' }} />`
It works when I use ` style={{ width: '50px' }}` 
![image](https://github.com/unocss/unocss/assets/69613396/96eb3e69-1ecf-4cd6-b4a0-3bb27a12f617)
but it doesn't work when I use `important-w-50px`
![image](https://github.com/unocss/unocss/assets/69613396/f47a91ae-25cb-4df3-aa05-ccdcc3a95cbd)
It works when I  set antd Select component 
` <Select w-600px />`

### Reproduction

https://github.com/Sharang-heng/vue3-issue

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
Because antdv's components do not receive attrs

**Comment by Simon-He95** [comment]
BTW it receive `class`, so you can use `class="w-260px"`
