### ISSUE TITLE
Unocss Interactive Docs is freezing

### ISSUE THREAD

**Issue by edimitchel** [unocss/unocss#3911]
### UnoCSS version

N/A

### Describe the bug

When I access to the [interactive docs](https://unocss.dev/interactive/) the application is frozen, no way (or very difficult) for using it.

### Reproduction

Go the the URL and see

### System Info

Firefox 126.0.1 (64 bits) / Safari 17.5 on OSX Sorona 14.5 (23F79)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by userquin** [comment]
hey @edimitchel , I guess it is vue 3.4 (too reactive), same problem when updating elk and vitest (the main thread blocked)

**Comment by antfu** [comment]
I tried to improve it a bit. Ultimately, I think we might better move the search into a worker to not block the main thread.

**Comment by userquin** [comment]
This should be fixed now: https://github.com/unocss/unocss/commit/8490c543c8401c99eeef5c3282175bbb708de4dd
