### ISSUE TITLE
uni-ui的内部样式被意外转换

### ISSUE THREAD

**Issue by dengsong666** [unocss/unocss#3921]
### UnoCSS version

^0.61.0

### Describe the bug
不希望被转换，转换后我的搜索图标显示不出来
![image](https://github.com/unocss/unocss/assets/120550985/6a0b58d1-9ee1-404e-9ae8-5ea60ab6f624)

### Reproduction

无

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
Use `blocklist` to skip parse. https://unocss.dev/guide/extracting#blocklist

**Comment by Simon-He95** [comment]
Currently, you can use the instructions provided by vscode plugin to skip the local code block converted by unocss, but I still hope there is a special representation that can control the skipping more accurately for a certain attribute. Any good suggestions or ideas? @antfu

**Comment by antfu** [comment]
I think blocklist is the way to go. Or if you build your own rulesets, you can avoid introducing the convention that conflicts.
