### ISSUE TITLE
svg解析出错

### ISSUE THREAD

**Issue by Sharang-heng** [unocss/unocss#3923]
### UnoCSS version

0.60.3

### Describe the bug

会莫名奇妙地解析出等号
![image](https://github.com/unocss/unocss/assets/69613396/f63b7239-9f7e-4929-8864-0bee825fb74c)

### Reproduction

https://github.com/Sharang-heng/vue3-issue

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
<img width="429" alt="image" src="https://github.com/unocss/unocss/assets/57086651/f62caa1f-054c-40e1-ab4f-7ec50464e0a3">

You can temporarily skip it by using unocss-skip and wait for it to be fixed later.
