### ISSUE TITLE
unconsistent behaviour when overriding transition duration

### ISSUE THREAD

**Issue by sanba-anass** [unocss/unocss#3936]
### UnoCSS version

0.61.0

### Describe the bug

strange things happen when i put duration-2000 directly after duration-300 it does not work but when i switched duration-300 to duration-100 it works just fine idon't know why 
example 1 (not working):
```vue
<template>
	<div bg-blue flex items-center justify-center h-screen>
		<button
			py-4
			px-8
			rounded-md
			cursor-pointer
			@click="togglebgColor"
			transition-colors
			duration-300
			duration-2000
			:class="active ? 'bg-black' : 'bg-amber'"
		>
			Click me
		</button>
	</div>
</template>
<script setup lang="ts">
const active = ref(false);

const togglebgColor = () => {
	active.value = !active.value;
};
</script>

example 2 (working):
```vue
<template>
	<div bg-blue flex items-center justify-center h-screen>
		<button
			py-4
			px-8
			rounded-md
			cursor-pointer
			@click="togglebgColor"
			transition-colors
			duration-100
			duration-2000
			:class="active ? 'bg-black' : 'bg-amber'"
		>
			Click me
		</button>
	</div>
</template>
<script setup lang="ts">
const active = ref(false);

const togglebgColor = () => {
	active.value = !active.value;
};
</script>
```

### Reproduction

https://stackblitz.com/edit/unocss-unocss-7565vhg?file=app.vue

### System Info

system: windows 10
browser : chrome , firefox,edge,brave
framework : nuxt

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by CofCat456** [comment]
The reason is that in the sorting after CSS compilation, `duration-200` and `duration-300` using `localeCompare` result in -1, while `duration-200` and `duration-100` result in 1.

 This causes the final order to be different.
 https://github.com/unocss/unocss/blob/e3d3b2ed21f02c213351d2d2c1d46ae57cae808b/packages/core/src/generator/index.ts#L298

**Comment by sanba-anass** [comment]
@CofCat456 yeah and this behaviour is not just for the duration i tested in colors as well some colors over the previous ones while  others doesn't

**Comment by henrikvilhelmberglund** [comment]
I don't think relying on the alphabetical order works great, you can either add `!` to add important or a new layer. [play](https://unocss.dev/play/?html=DwBwBAxgNghgznAvAIgC4FMAeqC0BzAJ3XQDscBWABkrA2xwCMoBXdC65APgEkw4ALAPbMoAEzAN0ElumAB6EJwBQoSLAQo6uQsTJUaAQi2MZ7Sl14DhYiVKat5ileGjwkaLNqKkzYZiUEcWABPdAIcAC8ALmN7Nn0LPiERcUlpBwVOIA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDASSarID3fsMBVKtoAvqByNJScoADkFlRMkJCRgoLEoogy8pgW0GmyCoQqarDqABSS0jRZUABcoADaOtK1kUwWkIjhtJWRmhKg7tB8NZF0qJGggQC6XlM6kAAWfIgtAjVl0lEtbR3zi8uRQ6wkyNDqoIcofJjw6uCgCwBu4DRV58ismNDdOoFeTgYrdQa3mciH8lGKAEovI4fMZTIxLNY7JDocD-m4PKUgdJIEwPuAagBGAB0ACZUdImKh4EM5qZuJAqiAoJxifNgF91uMoToZoEIYIgA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmAvkA)

**Comment by sanba-anass** [comment]
@henrikvilhelmberglund  isn't that a bad practice ? i'm looking for something more convenient without adding important everytime . i want to override styles for various buttons . it's seems like the only way to do it is using props but again i find it impractical to do so . is there any way to merge styles like tailwindcss does?

**Comment by henrikvilhelmberglund** [comment]
> @henrikvilhelmberglund isn't that a bad practice ? i'm looking for something more convenient without adding important everytime . i want to override styles for various buttons . it's seems like the only way to do it is using props but again i find it impractical to do so . is there any way to merge styles like tailwindcss does?

If you only have a base state with classes and want to override a certain class imo `!` is the ideal way to do it. Important is bad practice when writing normal non utility style CSS when you (ab)use the cascading part but should be fine for utility classes.

If you've got some different buttons that have different styles you may want to use [shortcuts](https://unocss.dev/config/shortcuts) instead. And then you could have base classes with the default classes you want, using [layers](https://unocss.dev/config/layers) to give them a lower specificity, that way you don't need `!`. Or just switch the whole  shortcut for every button.

**Comment by Simon-He95** [comment]
Unocss is a runtime framework. I don't want it to check if users write conflicting override rules on the same attribute. It will add extra burden to the runtime. This problem should be paid by the users themselves.
