### ISSUE TITLE
Invalid loading of local SVG resources in shadow dom mode

### ISSUE THREAD

**Issue by MQYForverT** [unocss/unocss#3938]
### UnoCSS version

0.61.0

### Describe the bug

I followed the description on the [official website](https://unocss.nodejs.cn/presets/icons#filesystemiconloader) to configure the local SVG, but it didn't take effect. I don't know where I configured it incorrectly? Please give me some guidance

### Reproduction

https://stackblitz.com/edit/vitejs-vite-hjfpc7?file=package.json,vite.config.ts,src%2FApp.vue

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
https://unocss.dev/integrations/vite#shadow-dom
<img width="1041" alt="image" src="https://github.com/unocss/unocss/assets/57086651/5a8bf5d8-7407-4e5c-a620-837c4a0e8e62">
