### ISSUE TITLE
[VS Code Extension] auto suggestion not work when className using single quote

### ISSUE THREAD

**Issue by peetck** [unocss/unocss#3945]
### UnoCSS version

0.61.0

### Describe the bug

When I use `className` with double quotes, it suggests correctly. However, when I switch to single quotes, it seems like it doesn't work anymore.

<img width="421" alt="image" src="https://github.com/unocss/unocss/assets/42176460/0a38f219-75a8-4272-a893-2d3f5fa22215">

<img width="1024" alt="image" src="https://github.com/unocss/unocss/assets/42176460/a5a9b9c1-9dda-42cc-b273-77049c6cecd7">

### Reproduction

vite.config.ts
```ts
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import UnoCSS from 'unocss/vite'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [UnoCSS(), react()],
})
```

uno.config.ts
```ts
// uno.config.ts
import { defineConfig } from "unocss"
import presetUno from "unocss/preset-uno"

export default defineConfig({
  // ...UnoCSS options
  presets: [presetUno()],
})
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
I can't reproduce it here, please provide a reproducible demo

**Comment by peetck** [comment]
thanks
