### ISSUE TITLE
unocss vscode extension activeEvent

### ISSUE THREAD

**Issue by image72** [unocss/unocss#3960]
### Clear and concise description of the problem

unocss vscode extension install global, sometimes may interferential in not used unocss project code autocomplete. please provide some condition restrict extension active.

### Suggested solution

`main/packages/vscode/package.json`
```json
"activationEvents": [
    "workspaceContains:unocss.config.ts",
    "workspaceContains:unocss.config.js"
  ]
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Simon-He95** [comment]
But it can't do that. It listens to the scene where my project adds uno.config. I have to restart the plugin to be detected again.

**Comment by image72** [comment]
很高兴看到你也可以使用中文交流.

- unocss 扩展`启用`肯定存在于已经使用unocss技术的项目中, 如果项目本身并未包含和打算使用unocss相关技术, 默认启用了, 只会对用户的代码自动补全造成困惑和干扰; 
- 以及, 普通前端开发乃至全站开发人员的vscode 扩展数量 通常至少都在30个以上, 每一个扩展都想要自己在vscode 启动的第一时间启用, 只会造成资源抢占,卡顿.
- 我观察到了unocss项目整体代码以及结构, 基本都做到了按需取用, 不做无谓的功能. 如无需求不增加实体. 希望unocss扩展也能够在使用体验上也能做到极致的编程体验感.

**Comment by Simon-He95** [comment]
In fact, the internal cache and config judgment logic are done, and it will not further get autocomplete. If there is no uno.config
