### ISSUE TITLE
Inconsistent behavior with playground

### ISSUE THREAD

**Issue by Dragon-GCS** [unocss/unocss#3961]
### UnoCSS version

0.61.2

### Describe the bug

1. `b-2` can't display the border without `b-solid`, but on the playground, `b-2` can display the border directly
2. `divide-solid` will add a border for the children `div` (except the first)

### Reproduction

This is playground behavior: [playground](https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIBGBaATOgPgEYBmXYAenAgIChRJZEUNqwQBTbJAezncK0oUBjVLkqkOsNHEylanQVSgA&config=Q&css=Q&options=N4IgLgTghgdgzgMwPYQLYGECucxIwZXxAC4EoAbOAUwF8g)
![image](https://github.com/unocss/unocss/assets/54531807/62d005f8-1c54-46ff-89b1-dd977cb79dc5)

Here is my code
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <script src="https://cdn.jsdelivr.net/npm/@unocss/runtime/uno.global.js"></script>
  </head>
  <body>
    <div class="b-2">132</div>
    <div class="divide-solid">
      <div>132</div>
      <div>132</div>
    </div>
  </body>
</html>
```

![image](https://github.com/unocss/unocss/assets/54531807/4ccac0b9-b0ce-4fc1-ad12-5c1483844a92)

### System Info

System: Windows 11 23H2
Browser: Microsoft Edge 126.0.2592.87
Framework: CDN script

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by henrikvilhelmberglund** [comment]
The playground uses a style reset: https://unocss.dev/guide/style-reset#tailwind

I don't know what you mean in `2.`. For `divide-solid` to do something you need an actual divider like [this](https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIBGBaATOgPgEYBmXYAenAgIChRJZEUNqwQBTbEZACw5BQ2nbAE88hWlCgMapclUh1ps4mUrU6GpUA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDASSarID3fsMBVKtoAvqByNJScoADkFlRMkJCRgoLEoogy8pgW0GmyCoQqarDqABSS0jRZUABcoADaOtK1kUwWkIjhtJWRmhKg7tB8NZF0qJGggQC6XlM6kAAWfIgtAjVl0lEtbR3zi8uRQ6wkyNDqoIcofJjw6uCgCwBu4DRV58ismNDdOoFeTgYrdQa3mciH8lGKAEovI4fMZTIxLNY7JDocD-m4PKUgdJIEwPuAagBGAB0ACZUdImKh4EM5qZuJAqiAoJxifNgF91uMoToZoEIYIgA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYGECucxIwZXxAC4EoAbOAUwF8g)
