### ISSUE TITLE
在uniapp开发小程序希望分包内的样式打包到各自的分包内

### ISSUE THREAD

**Issue by KDWangBoss** [unocss/unocss#3966]
### Clear and concise description of the problem

在uniapp开发小程序希望分包内的样式打包到各自的分包内

### Suggested solution

none

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by KDWangBoss** [comment]
[uniapp.zip](https://github.com/user-attachments/files/16122119/uniapp.zip)

**Comment by KDWangBoss** [comment]
1、下载微信开发者工具；安装好相关依赖
2、运行npm run serve 
3、运行npm run dev:mp-weixin
4、微信开发者工具导入编译后的程序


在src/static/uno.css下有mt-20rpx、h-100vh、flex、flex-col、bg-red、bg-yellow样式，

bg-yellow是分包packageB下的

能否将bg-yellow输出到src/packageB/common/css/uno.css

**Comment by MellowCo** [comment]
try this
https://unocss.dev/integrations/vite#vue-scoped

**Comment by antfu** [comment]
By default, UnoCSS works with a specific order of the rules, which is not really possible to do chunking - of course, you can try with the different modes it provides, but also be aware of their own limitations. I would say a single shared CSS would be the best way to go if possible,

**Comment by KDWangBoss** [comment]
> try this https://unocss.dev/integrations/vite#vue-scoped

🌹
