### ISSUE TITLE
配置presetUno({important: '#app'})后，style中的@apply会失效

### ISSUE THREAD

**Issue by ying-tch** [unocss/unocss#3969]
### UnoCSS version

0.61.0

### Describe the bug

为了覆盖第三方UI库（element plus）的内联样式，我在uno.config.js中配置了presetUno({important: '#app'})，它是成功的修改掉了内联样式，但却使得我整个项目中，在style里使用的Directives transformer都失效了。我不知道这属于bug，还是这样配置后就要接受这样的代价？
![image](https://github.com/unocss/unocss/assets/31296940/92c74614-d036-47f6-aebd-0a5d52e98850)
![image](https://github.com/unocss/unocss/assets/31296940/737feab3-de8f-4238-90e8-66d290eaec68)

### Reproduction

如果是注释掉important后，代码就正常可用了，但样式覆盖就失效了
![image](https://github.com/unocss/unocss/assets/31296940/2ae9468d-18b2-4648-b223-c922558ce552)
![image](https://github.com/unocss/unocss/assets/31296940/fde00b52-a431-4337-809a-95bb07ad95ab)
![image](https://github.com/unocss/unocss/assets/31296940/e3d2e12e-df36-4319-a176-6af1813c8776)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
This may be a bug, but I have never used it this way. Can you provide a minimized demo and I can help troubleshoot it?

**Comment by ying-tch** [comment]
> This may be a bug, but I have never used it this way. Can you provide a minimized demo and I can help troubleshoot it?

https://unocss.dev/play/?html=DwEwlgbgBGILwHICGAHFCB8AoKVSSgGMAbJAZzLgCJiwyAXARiqgDMB3ANgAZu2B7AHb0AtGTAAvAKYjGfQv2L8ATiOVSQ2XNrzhoJcpSph6UgLYszAIxEBWDCfONgAej1aduggYrVHFqGs7B1MzACZXdxxPfH1SX2NQyxt7fwBmSMgPXEyID2jYonijWgYwqmztQp8jfwr-Zzcs6J1q4r8kkPMIpryWqr0iww7zetCM3o9c7CwCsDZ2O14BYTFJGU4MUvowwBC3QHYLQHh9QEzFQAp1QDC5AGEAVwZ%2BMyIKQFo5VzApq2UXKfmOJb5WISicTSESbQAXNoApxMAkcZEISsMAAcygTzAZhQKnoSGEAC4EABiVDoQAw-9s9kdALJGgCx5QD4roAJU1e2GmWCAA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6hU4AGYJwAYUrw5AcwA0obnUjhEAQUQNY2AK6JYMgJ6btUPQEkmyyLZ16AqlXUNM8SDJ8nOA0ACKwdCywAG5QPjR%2BAUEhAGqYjH6IAOI0lKbcoAC%2BoDK5nKAA5KZUTJCQFYKCxKKIUrKYptCt0nKESiqwqgAU4oKgoDSdUABcoADacxVMppCIlJy0UxWaks7QfLMVdKgVRQC6Z%2BpjoJAAFnyIywKzo%2BPjSytrG3cPTxWHrBIyGgqlAgJQfD8qnAoHusRo03ByFYmGg22uhSu4zsume82u2PciC8lBGBLeIgemUOAGJMNxuNtQCBQIB36MAFQaAC5tAFOJgEjjQCn0YAZCMAMP9wVYAJkAIW6AdgtAPD6gEYdQDG1oAOPUAYXLkwoASixbxxekMxjMFmsQ215L1iCcLjJbzekCYqPAswAjAA6cU621MVDwQ63IzcSDTEBQTiuu7AdG2rU6y7XXz%2BQI0YI0IPzBNJZMhcKRCyxSCmzQZpMptIZJA5PLcU1xrWCIA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUGOUxMAJjABvbWDAABWsOUBPMBwDuANgAMbx1npwAtOhgALwRfAEZPZCxlbl9KRgBubQBfbV19IzAAPjAxeAQ8MwtrWwccACNfAFZElKA&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmANCBCXAA5LwCWAbifoceeNPMmgMIBXOGCSo%2BAZXFsipAL5A

问题复现的样例，请您帮忙查看一下

**Comment by ying-tch** [comment]
您好，UnoCSS Playground中确实修复了该问题。但在实际开发应用中，为了限定css作用域，防止样式污染。vue的<style>标签一般会带有scoped属性，但恰好是这个属性生成的v-data-xxxxxx在样式中，从而会导致@apply的效果失败。
这是问题复现地址 [https://stackblitz.com/edit/vitejs-vite-quhgl2?file=src%2Fcomponents%2FText2.vue](url)
![image](https://github.com/user-attachments/assets/03a67658-74a3-46c5-8b03-1a3ce9661dca)

**Comment by ying-tch** [comment]
> @Simon-He95 您好，UnoCSS Playground中确实修复了该问题。但在实际开发应用中，为了限定css作用域，防止样式污染。vue的<style>标签一般会带有scoped属性，但恰好是这个属性生成的v-data-xxxxxx在样式中，从而会导致@apply的效果失败。 这是问题复现地址 [https://stackblitz.com/edit/vitejs-vite-quhgl2?file=src%2Fcomponents%2FText2.vue](url) ![image](https://private-user-images.githubusercontent.com/31296940/349788363-03a67658-74a3-46c5-8b03-1a3ce9661dca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyNzc1ODQsIm5iZiI6MTcyMTI3NzI4NCwicGF0aCI6Ii8zMTI5Njk0MC8zNDk3ODgzNjMtMDNhNjc2NTgtNzRhMy00NmM1LThiMDMtMWEzY2U5NjYxZGNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA0MzQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwMGIwMDg0NTg3YmNmYzk3NjllYTk5NzAxNTgzYTYzYWVjNzNjZmFhNGQ0MjdjMTFhMGNkZGU5YjY1MDdjYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kIbJuEx6mXZZZeghc4cBY5a8wbvY-jtn04bjzLBSNOA)
