### ISSUE TITLE
使用postcss-px-to-viewport和@apply时，@apply内的px不会转换成vw

### ISSUE THREAD

**Issue by messchow** [unocss/unocss#3985]
### UnoCSS version

0.60.3

### Describe the bug

![微信截图_20240715093307](https://github.com/user-attachments/assets/a7f2919b-4f47-42fa-a2a7-4286b204025d)
![微信截图_20240715093316](https://github.com/user-attachments/assets/a7af1c32-220a-47ab-bae2-8e0bfd996328)

### Reproduction

.btn {
  background: linear-gradient(141deg, #70BBFF 0%, #3C77FF 100%);
  box-shadow: 0px 12px 24px 0px rgba(70, 126, 255, 0.4);
  @apply w-300px;
}

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
插件处理的时机可能不正确，在 UnoCss 转换后，再调用 postcss-px-to-viewport 试试

**Comment by messchow** [comment]
> 插件处理的时机可能不正确，在 UnoCss 转换后，再调用 postcss-px-to-viewport 试试

```js
/** @format */
import {defineConfig} from "vite"
import vue from "@vitejs/plugin-vue"
import AutoImport from 'unplugin-auto-import/vite';
import {VantResolver} from "unplugin-vue-components/resolvers"
import Components from "unplugin-vue-components/vite"
import path from "path"
import UnoCSS from "unocss/vite"
import postcssPxToViewport from 'postcss-px-to-viewport';

// https://vitejs.dev/config/
export default defineConfig({
    base: "./",
    plugins: [
        vue(),
        UnoCSS({
            transformCSS: 'pre',
            postcss: true
        }),
        AutoImport({
            imports: ['vue', 'vue-router'],
            resolvers: [VantResolver()],
        }),
        Components({
            resolvers: [VantResolver()],
        }),
    ],
    build: {
        outDir: "nfkjverify-history-V" + process.env.npm_package_version,
    },
    css: {
        preprocessorOptions: {
            scss: {
                additionalData: `@import "./src/assets/scss/iframe.scss";`,
            },
        },
        postcss: {
            plugins: [
                postcssPxToViewport({
                    viewportWidth: 750,
                    viewportUnit: "vw"
                }),
            ]
        }
    },
    resolve: {
        alias: [
            {
                find: "@",
                replacement: path.resolve(__dirname, "src"),
            },
        ],
    },
})

```

尝试添加 transformCSS: 'pre', postcss: true还是不行，写在标签上的w-100px是能正常转换的，只有@apply里的无法正常转换。似乎跟时序也没有关系

**Comment by messchow** [comment]
https://unocss.dev/integrations/postcss
只需要引入这个就好了
