### ISSUE TITLE
The display cannot be restored in the un-cloak mode

### ISSUE THREAD

**Issue by laterdayi** [unocss/unocss#3988]
### UnoCSS version

lastest

### Describe the bug

The display cannot be restored in the un-cloak mode

```
<div op30 text-lg fw300 m1 un-cloak>
      The instant on-demand Atomic CSS engine.
    </div>
```

```
[un-cloak] {
  display: none;
}
```

### Reproduction

https://unocss.dev/play/?html=DwEwlgbgBAFgtAMwK4BsVQC4FMAeG4DGWAdtgE5QIq5QDOW1B%2BxA9sVlAIZoBcGZnYrTAYwbOABYADFIB8AKChRQkKAFtOCpUpXRseOAFYc6BAHcAjDK7EwG7HABGLJMSJxuGG3c4OCL0jgwYgRgkQ5BHwcQJAFRcQtaLW0lAFVWAGEAZSzFbWAAenAIZJ1iqBYABwBmKUxcfBQAc0ozWrq1CyhXQhQWTgBrUu0AFRgOYNoMQS9xECwNYhAoAEEMFjUwAihsrKgSJuCsADo8nSLIYd11ACZKahwoACskKbAEAE9CEnJ6gxuTBUanUYCwIFgyABeABEVQAHFJocMdJwzikoGBCJwyM5iHA%2Bk0WHBDhgYEhHGiUvp8MFxmQRJTtDAyFgEDCYBgMJVaDwCgUSWTHMd-GoCq4WARaLQxaxJbRoYylNMyE0sBgYQB9RwoQQDBXoqCyQqaNGFYrJM2XeSWkrW8qcRy0FgoJDYKDOTkbIxQelNDlwOrUBD4OrU76kCFA2qtdrJOYLQTLADtGKE01IUBTyDQHygBFe602AC8HdRrRcSkA&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDASSarID3fsMBVKtoAvqByNJScoADkFlRMkJCRgoLEoogy8pgW0GmyCoQqarDqABSS0jRZUABcoADaOtK1kUwWkIjhtJWRmhKg7tB8NZF0qJGggQC6XlM6kAAWfIgtAjVl0lEtbR3zi8uRQ6wkyNDqoIcofJjw6uCgCwBu4DRV58ismNDdOoFeTgYrdQa3mciH8lGKAEovI4fMZTIxLNY7JDocD-m4PKUgdJIEwPuAagBGAB0ACZUdImKh4EM5qZuJAqiAoJxifNgF91uMoToZoEIYIgA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmjoA2iVllbR5ALqm-oww6Cq0oRr0WPQIfv3a2kA&options=N4XyA

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
un-cloak seem for initruntime，if you just want to be `display：none`，should use `hidden`

**Comment by laterdayi** [comment]
Looking forward to help, this should be a problem caused by a recent version update, which was normal before

**Comment by Simon-He95** [comment]
It seems to have been fixed in the latest version.
