### ISSUE TITLE
Unable to run `vite dev` on v0.61.4

### ISSUE THREAD

**Issue by SinnySupernova** [unocss/unocss#3991]
### UnoCSS version

=0.61.4

### Describe the bug

Error from running `vite dev`:

```
278 | function createSvelteScopedContext(configOrPath) {
279 |   const uno = createGenerator();
280 |   const ready = reloadConfig();
281 |   const loadConfig = createRecoveryConfigLoader();
282 |   async function reloadConfig() {
283 |     const { config, sources } = await loadConfig(process.cwd(), configOrPath);
                                            ^
ReferenceError: Cannot access 'loadConfig' before initialization.
      at /home/user/project_dir/node_modules/@unocss/svelte-scoped/dist/vite.mjs:283:39
      at reloadConfig (/home/user/project_dir/node_modules/@unocss/svelte-scoped/dist/vite.mjs:282:33)
      at createSvelteScopedContext (/home/user/project_dir/node_modules/@unocss/svelte-scoped/dist/vite.mjs:280:17)
      at UnocssSvelteScopedVite (/home/user/project_dir/node_modules/@unocss/svelte-scoped/dist/vite.mjs:258:19)
      at /home/user/project_dir/vite.config.js.timestamp-1721135614680-89ba977444b6d8.mjs:6:13
```

Doesn't happen on version =0.61.3

### Reproduction

Run `vite dev` with this `vite.config.js`:

```js
import { sveltekit } from "@sveltejs/kit/vite";
import { defineConfig } from "vite";
import UnoCSS from "@unocss/svelte-scoped/vite";

export default defineConfig({
  plugins: [UnoCSS(), sveltekit()],
});
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by henrikvilhelmberglund** [comment]
Will be fixed by https://github.com/unocss/unocss/pull/3992 but for now you can also control click the `(/home/user/project_dir/node_modules/@unocss/svelte-scoped/dist/vite.mjs:282:33)` and just move the line `const loadConfig = createRecoveryConfigLoader();` up so it is run before `const ready = reloadConfig();`.
