### ISSUE TITLE
Fetch Web fonts failed in `fontshare` provider when use `Serve Fonts Locally` 

### ISSUE THREAD

**Issue by Kutius** [unocss/unocss#3998]
### UnoCSS version

0.61.5

### Describe the bug

After running project, the console reports an error displaying: 
```
[unhandledRejection] Failed to parse URL from //cdn.fontshare.com/wf/H24CDKHEVFT7VMEKEAMBO4CDKYCYCADH/5GC5PFP4RRVV5U2J36ZYOZGV6AWWHIMD/YFYSWSSMGACJCYW3MMXEH33GQBMRFKTE.woff2
```
When `unocss` parses CSS from `fontshare`, their CSS uses `Protocol-Relative` URL, such as "//cdn.fontshare.com/xxxxx". But Node's fetch maybe does not support parsing this link, leading to an exception.

I have tested it both locally with Node v20.15 and in the browser. `Protocol-Relative` URL will be fetched successfully in browser but not in Node.

Since `unocss` uses `ofetch`, and it seems that ofetch calls the native fetch method based on the environment. I think, to fundamentally solve this problem, it might be necessary to fix it from the upstream.

Or just fix this problem temporary by detecting `Protocol-Relative` URL, and add the url with Protocol like `https:`

I'm not sure what's the right thing to do.

## presets
```ts
    presetWebFonts({
      provider: 'bunny',
      fonts: {
        sans: 'Noto Sans SC',
        serif: [
          {
            provider: 'fontshare',
            name: 'Technor',
          },
          'Noto serif SC',
        ],
        mono: 'Fira Mono',
      },
      processors: createLocalFontProcessor(),
    }),
```

Then run project.

PS: I tried to create StackBlitz to reproduction. But I saw timeout to fetch, maybe my network cause timeout. But for reference, I'll post it here: https://stackblitz.com/edit/unocss-unocss-2wjwc3?file=src%2FApp.vue

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
> Or just fix this problem temporary by detecting Protocol-Relative URL, and add the url with Protocol like https:

Yeah I think that would do. Do you want to send a quick PR to fix that? Thanks

**Comment by Kutius** [comment]
> Yeah I think that would do. Do you want to send a quick PR to fix that? Thanks

Yeah, It's pleasure to me to paticipate in the `unocss` community
