### ISSUE TITLE
可以加一个图标存储的功能吗？

### ISSUE THREAD

**Issue by thikiiii** [unocss/unocss#4008]
### Clear and concise description of the problem

可以离线和动态使用图标

### Suggested solution

类似[@iconify/vue](https://iconify.design/docs/icon-components/vue/add-collection.html)的`addCollection`api，它可以将图标集合存储到项目中，并且可以离线和动态使用图标，缺点就是加大了项目打包体积

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
UnoCSS does not have a runtime. It generates a `.css` file during build and disappear in the final client build - which means by its natural dynamic icons is not possible to support.

Of course, if you want to ship the UnoCSS engine to the client side, you can already do with https://unocss.dev/integrations/runtime - where the icons preset could fetch icons dynamically. However it would be extremely inefficient compare to the build-time approach. Please make your own trade-offs.
