### ISSUE TITLE
Use @unocss/cli(which version greate 0.61.0) generate wrong css code

### ISSUE THREAD

**Issue by chenweiyi** [unocss/unocss#4009]
### UnoCSS version

\> 0.61.0

### Describe the bug

when I use cli generate css，but i found some class not valid, and I find some error in generate css.

And this issue occur when version > 0.61.0 , 0.61.0 is ok!

![image](https://github.com/user-attachments/assets/71c99c25-d4e0-4716-99c5-453932595877)

### Reproduction

https://github.com/chenweiyi/unocss-demo-bug

### System Info

System: Macos Big Sur 11.7.4
Browser: MS Edge 126.0.2592.113
Frame: unocss react

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wkeylin** [comment]
similar to #3930
