### ISSUE TITLE
使用runtime临时使用unocss，结合presetIcons功能异常

### ISSUE THREAD

**Issue by z-sq** [unocss/unocss#4011]
### UnoCSS version

0.61.5

### Describe the bug

使用官网的教程示例代码 https://unocss.dev/integrations/runtime#core

最终渲染出来，class样式丢失，只存在icons样式
<img width="702" alt="image" src="https://github.com/user-attachments/assets/af909568-7e2c-44c8-984c-e39ea7045d79">

### Reproduction

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="i-ph-anchor-simple-thin"></div>
    <div class="container mx-auto text-2xl">测试测试</div>

    <script src="https://cdn.jsdelivr.net/npm/@unocss/runtime/preset-icons.global.js"></script>
    <script>
    window.__unocss = {
        presets: [
        () => window.__unocss_runtime.presets.presetIcons({
            scale: 1.2,
            cdn: 'https://esm.sh/'
        }),
        ],
    }
    </script>
    <script src="https://cdn.jsdelivr.net/npm/@unocss/runtime/core.global.js"></script>
</body>
</html>
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
You will also need to install the Uno or Wind preset - you only use the icons preset.
