### ISSUE TITLE
UnoCSS not working with SvelteScoped in Dev Mode

### ISSUE THREAD

**Issue by FireSpike0** [unocss/unocss#4014]
### UnoCSS version

0.61.5

### Describe the bug

When using Svelte Scoped with UnoCSS, the styles in dev (`npm run dev`, Vites dev mode) break after a few changes when editing a routes HTML (e.g. appending or removing a single character within a paragraph). Break means, that all styles are not applied anymore after the pages reload.

Initially, the styles are contained in the following style tag:
```html
<style type="text/css" data-vite-dev-id="/Projects/feedback/src/routes/+page.svelte?svelte&amp;type=style&amp;lang.css">._color-red_van38g{--un-text-opacity:1;color:rgb(248 113 113 / var(--un-text-opacity))}._underline_van38g{text-decoration-line:underline}.s-y_bCXRrkrYfP{}</style>
```

But after an edit, the same style tag contains:
```html
<style type="text/css" data-vite-dev-id="/Projects/feedback/src/routes/+page.svelte?svelte&amp;type=style&amp;lang.css"><h1 class="color-red underline">Hello, world!</h1>
<p>Hello, world!</p>
</style>
```

Theres another style tag, which contains UnoCSS styles, but that style tag is removed by SvelteKits `client.js` file due to its `data-svelte` attribute:
```html
<style data-sveltekit="">._color-red_van38g{--un-text-opacity:1;color:rgb(248 113 113 / var(--un-text-opacity))}._underline_van38g{text-decoration-line:underline}.s-y_bCXRrkrYfP{}</style>
```

### Reproduction

The GitHub repository I used is [here](https://github.com/FireSpike0/feedback/)
1. (Install dependencies including Node and npm; I used Node 22)
2. Start dev mode
3. Edit the default route located under `/src/routes/+page.svelte`
4. The style attribute (and thus the styles) breaks after a random amount of changes until you restart the entire dev server.

### System Info

Firefox (latest), SvelteKit (using Sveltes Template), TypeScript, UnoCSS in SvelteScoped mode, NodeJS 22.2.0 or NodeJS 20.12.2 (can reproduce in both versions)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by henrikvilhelmberglund** [comment]
Can't reproduce here, works fine in Brave and Firefox. Did you test in a private tab to make sure it's not an extension?

**Comment by henrikvilhelmberglund** [comment]
You can open devtools and the network tab, try to make it break, then paste the contents of `+page.svelte(numbers etc here)` of the last file and the file before it.
