### ISSUE TITLE
eslint  presetMini presetUno sort different

### ISSUE THREAD

**Issue by MellowCo** [unocss/unocss#4020]
### UnoCSS version

0.61.5

### Describe the bug

`unocss/test/eslint-plugin-worker.test.ts`  add test

```ts
import { presetMini } from '@unocss/preset-mini'


it('sort presetMini', async () => {
    const uno = createGenerator({
      presets: [
        presetMini() as any,
      ],
    })
    setGenerator(uno, undefined)
    const rs = await runAsync(undefined, 'sort', 'absolute left-1/2 top-1/2 h-100 w-100 flex items-center justify-center -translate-1/2')
    expect(rs).toMatchInlineSnapshot(`"flex absolute h-100 w-100 justify-center items-center left-1/2 top-1/2 -translate-1/2"`)
  })

  it('sort presetUno', async () => {
    const uno = createGenerator({
      presets: [
        presetUno(),
      ],
    })
    setGenerator(uno, undefined)
    const rs = await runAsync(undefined, 'sort', 'absolute left-1/2 top-1/2 h-100 w-100 flex items-center justify-center -translate-1/2')
    expect(rs).toMatchInlineSnapshot(`"absolute left-1/2 top-1/2 h-100 w-100 flex items-center justify-center -translate-1/2"`)
  })

```

different sorting results

* presetMini
> flex absolute h-100 w-100 justify-center items-center left-1/2 top-1/2 -translate-1/2

* presetUno
> absolute left-1/2 top-1/2 h-100 w-100 flex items-center justify-center -translate-1/2

### Reproduction

https://github.com/unocss add test 

### Validations

- [ ] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [x] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [ ] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Could you help to send a PR with the failing tests? Thanks!
