### ISSUE TITLE
[VSCode] UnoCSS Extension not highlight and auto complete

### ISSUE THREAD

**Issue by serkodev** [unocss/unocss#4028]
### UnoCSS version

0.61.7

### Describe the bug

All of the underline-highlight and auto complete are not works in VSCode but it works <= `v0.61.6`.

UnoCSS Log

```
⚪️ UnoCSS for VS Code v0.61.7

📂 roots search mode.

-----------
🛠 Resolving config for /Users/user/repo
🗂️ Enabled context: [none]
```

The weird thing is when I am trying to debug `@unocss/vscode`, it works when launch debug process on VSCode.

```
⚪️ UnoCSS for VS Code v0.61.7

📂 roots search mode.

-----------
🛠 Resolving config for /Users/user/repo
🛠 New configuration loaded from
  - /Users/user/repo/uno.config.ts
ℹ️ 5 presets, 1067 rules, 14 shortcuts, 50 variants, 1 transformers loaded
🗂️ Enabled context: /Users/user/repo
```

### Reproduction

Create a minimum Nuxt project and UnoCSS setup, open VSCode with UnoCSS Extension installed.

### System Info

VSCode: Version: 1.91.1 (Universal)
macOS 14

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by coderwyd** [comment]
Roll back to version 0.61.6 and it will work normally.

**Comment by zcmk123** [comment]
me too, and roll back to 0.61.6 is working for me

**Comment by Deer404** [comment]
back to 0.61.6

**Comment by laodengjuntuan** [comment]
roll back to 0.61.6 will work.
and how to do this
1. click vscode extension panel
2. right click UnoCSS extension and choose the ‘Install Another Version’

**Comment by antfu** [comment]
Hopefully ac7c804448ffaf9a8574c6ebc06b42b3335d23c9 should fix it

**Comment by antfu** [comment]
Seems to be fixed now
