### ISSUE TITLE
After upgrading to unocss 0.61.7+ (and unconfig 0.3.13 -> 0.5.5.4), unocss-preset-daisyui stopped working.

### ISSUE THREAD

**Issue by kingyang** [unocss/unocss#4033]
### UnoCSS version

0.61.7

## 项目结构

nuxt + unocss +daisyui
unocss-preset-daisyui https://github.com/LeekJay/unocss-preset-daisyui
unocss-preset-component https://github.com/LeekJay/unocss-preset-component

## 问题描述
在unocss系列是0.61.6版本以下时 项目是可以正常工作的.
当在升级到0.61.7之后发现不能工作了, 主要是unocss-preset-daisyui不能正常工作

查看unocss主要是把unconfig 升级到了0.5.4,  通过强制版本为0.3.13也行
研究了好久, 没找到问题的解决方案, 还望大佬指点一下
```json
"pnpm": {
    "overrides": {
      "unconfig": "^0.3.13"
    }
  },
```

### Reproduction

https://stackblitz.com/~/github.com/kingyang/demo-nuxt-daisyui-unocss
https://github.com/kingyang/demo-nuxt-daisyui-unocss

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kingyang** [comment]
![异常](https://github.com/user-attachments/assets/a88b89de-92e2-42ca-b3e3-c2ea5f5305d8)
![正常](https://github.com/user-attachments/assets/1b62a933-235a-4b92-aeb9-29e768a4042d)

**Comment by QaahirStewart** [comment]
Yeah any updates after  0.61.4, anything in my Uno.config.js doesn't work/ not getting loaded.
