### ISSUE TITLE
Support custom icons IntelliSense like Iconity IntelliSense

### ISSUE THREAD

**Issue by s3xysteak** [unocss/unocss#4045]
### Clear and concise description of the problem

I love icones very much but it is more often to use the icons given by the fellow art designer in actual project. So if we can have the features Iconity Intellisense extension provided, it will be so great. 

### Suggested solution

I think if we have already registered icons in uno.config.ts, we can make a vscode extension read the config and achieve the target, like Iconity Intellisense. 

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
This is honestly not the responsibility of UnoCSS but more like the VS Code extension. But on the other hand I don't have the bandwidth (or incentive) to work on the feature on the extension yet. Feel free to propose solutions/PRs there instead.

**Comment by s3xysteak** [comment]
I made a plugin to resolve that https://github.com/s3xysteak/unplugin-iconify-generator

The principle is, I found [antfu.iconify](https://github.com/antfu/vscode-iconify) have a option `iconify.customCollectionJsonPaths` to receive customized icons, so there could be a bundler plugin, which just generate json files and edit `.vscode/settings.json` to make the option work. The plugin works to my team althought it is simple.

**Comment by antfu** [comment]
Awesome, if you want, you can send a PR to the docs mentioning your tool.
