### ISSUE TITLE
Unocss sometimes doesn't generate utility class when using variable

### ISSUE THREAD

**Issue by GeekSquirrel** [unocss/unocss#4054]
### UnoCSS version

0.61.9

### Describe the bug

```vue
<script setup lang="ts">
const _class = 'opacity-[0.1]'  // work
const _class = 'opacity' + '-10'  // work
const _class = 'opacity' + '-[0.1]'  // not work
</script>

<template>
  <div :class="_class">test</div>
</template>
```

It seems unocss won't generate utility class for the third example. But if there is 'opacity-[0.1]'  in other places of your code, even in comment, it works well. So you need to delete, not comment out, the first two examples, and restart your server to see the bug. I found it when using slidev, but I think it's more likely an Unocss issue.

### Reproduction

https://stackblitz.com/edit/unocss-unocss-8kbxqk?file=src%2FApp.vue

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by henrikvilhelmberglund** [comment]
When rules aren't detected you can use the [safelist](https://unocss.dev/guide/extracting#safelist) feature.
`safelist: ["opacity-[0.1]"]`

**Comment by GeekSquirrel** [comment]
> When rules aren't detected you can use the [safelist](https://unocss.dev/guide/extracting#safelist) feature.
> `safelist: ["opacity-[0.1]"]`

Get it, thanks for your help!
