### ISSUE TITLE
如何屏蔽扫描 vite 中的入口文件 index.html / How to block scanning of the entry file index.html in vite

### ISSUE THREAD

**Issue by hezulong1** [unocss/unocss#4058]
### UnoCSS version

0.61.9

### Describe the bug

你好，我不确定这算不算是一个 Bug，但是因为特殊原因，需要屏蔽扫描 index.html，我在 `packages/vite/src/transformers.ts` 中发现在 `createTransformerPlugins` 已经成功返回 undefined，即认为应该不扫描 index.html，但是似乎仍在扫描。我做了以下尝试，似乎依旧不可以

首先，通过 `@unocss-ignore` 屏蔽，但是失效
然后，再次参考[文档 extracting](https://unocss.dev/guide/extracting)配置，但还是失败了

恕我技术稍欠火候，实在没办法，来此提出疑问，还请帮忙解答下，谢谢

---

谷歌翻译：

Hello, I'm not sure if this is a bug, but for special reasons, I need to block the scanning of index.html. I found in `packages/vite/src/transformers.ts` that `createTransformerPlugins` has successfully returned undefined, which means that index.html should not be scanned, but it seems to be still being scanned. I tried the following, but it still doesn't seem to work

First, block it with `@unocss-ignore`, but it doesn't work
Then, refer to the [extracting](https://unocss.dev/guide/extracting) configuration again, but it still fails

Please forgive my lack of technical skills, there is really no way, I came here to ask questions, please help answer them, thank you

### Reproduction

这是最小展现的地址：https://stackblitz.com/edit/unocss-unocss-wjdbut?file=index.html

--- 

谷歌翻译：

This is the minimal display address: https://stackblitz.com/edit/unocss-unocss-wjdbut?file=index.html

### System Info

win10, chrome125,  vue3， vite5

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zoeyzhao19** [comment]
It seems `@unocss-ignore` does not be recognized when it's presented in a html file. I don't know whether it's intended or a bug. 
A pair of  **skip** comment would work.
```html
<!-- @unocss-skip-start -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script>
    </script>
  </head>
  <body class="font-sans">
    <div id="app"></div>
    <script type="module" src="/src/main.ts"></script>
  </body>
</html>
<!-- @unocss-skip-end -->
```

**Comment by s3xysteak** [comment]
https://unocss.dev/config/#pipeline

`pipeline.exclude` could help you

**Comment by hezulong1** [comment]
> https://unocss.dev/config/#pipeline
> 
> `pipeline.exclude` could help you

谢谢提醒，但是尝试后，似乎并没有作用（Thank you, but after trying it, it doesn't seem to work.）：

```js
pipeline: {
  exclude: [/\.html/],
 // exclude: ['index.html']
}
```

**Comment by hezulong1** [comment]
> It seems `@unocss-ignore` does not be recognized when it's presented in a html file. I don't know whether it's intended or a bug. A pair of **skip** comment would work.
> 
> ```
> 
> <!DOCTYPE html>
> <html lang="en">
>   <head>
>     <meta charset="UTF-8" />
>     <meta name="viewport" content="width=device-width, initial-scale=1.0" />
>     <script>
>     </script>
>   </head>
>   <body class="font-sans">
>     <div id="app"></div>
>     <script type="module" src="/src/main.ts"></script>
>   </body>
> </html>
> 
> ```

Yes, it works for me, thank you!
