### ISSUE TITLE
Does unocss not support dynamic writing

### ISSUE THREAD

**Issue by vbnew** [unocss/unocss#4059]
### UnoCSS version

"^0.57.7"

### Describe the bug

this is my code:

`<el-form-item
 v-for="item in highFormConfig"
 :key="item.prop" :label="item.label"
 :class="`col-span-${item.span || 2}`" >
</el-form-item>`

but has some issues. The class is not parsed properly.
<img width="540" alt="微信图片_20240807174127" src="https://github.com/user-attachments/assets/b5a502de-5013-4943-b281-02736adc2c93">

### Reproduction

no repo

### System Info

- Node.js ^18.16.0  pnpm ^9.0.6
- pinia 
- vue-query 
- vueuse 
- unocss 
- api request axios fetch

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by henrikvilhelmberglund** [comment]
Generally no, you need to tell UnoCSS which dynamic values are possible. The way to do so is by using [safelist](https://unocss.dev/guide/extracting#safelist).

If you have lots of values you can use a function like `...Array.from({ length: 17 }, (_, i) => `col-span-${i}`),`

**Comment by vbnew** [comment]
> Generally no, you need to tell UnoCSS which dynamic values are possible. The way to do so is by using [safelist](https://unocss.dev/guide/extracting#safelist).
> 
> If you have lots of values you can use a function like `` ...Array.from({ length: 17 }, (_, i) => `col-span-${i}`), ``

My problem has been solved, thank you very much for your help!
