### ISSUE TITLE
rfc: align preset-wind with tailwind & windi docs

### ISSUE THREAD

**Issue by alexanderniebuhr** [unocss/unocss#406]
as far I can tell, preset-wind is just superset to `preset-mini`.

`preset-mini` so far allows multiple versions of utility classes for different things. I found just an example: `m-4` (Tailwind & windi), `m4` (Tachyons) -> will both generate the output.

Since we would like to use preset-wind as the ruleset for the opinionated windi v4 setup, because windi v4 will use UnoCSS as its engine, I think the preset would have to get fine-tuned.
I propose that the `preset-wind` just allows rules defined in the Tailwind & windi docs, rather than allowing other syntaxes as well (`m4`)

**Comment by chu121su12** [comment]
Another alternative maybe to define preset-windi separately. Or maybe wind-core that aligns only to both windi & tailwind.

**Comment by alexanderniebuhr** [comment]
We had this discussion with core team of windi as-well, but we think it might not be great to define two similar presets.
I think we can also use `preset-wind` as of now, but this is my personal suggestion to have it more inline.

Whatever you think is the best, is fine for me.

**Comment by chu121su12** [comment]
Is the discussion public? I'd like to have the link if it is.

Another option, personally, is to split mini into sub preset.

I mainly uses preset uno with as close as tailwind's syntax, since I am familiar with their api.

**Comment by antfu** [comment]
Other than margin and padding, I think the rest rules are basically identical, or can you make a list full list of the rules you think are excrescent?

For margin and padding, I feel it's no harm to have them in the next version of Windi, we could document it. Some of the conventions are necessary for attrubutify to work, for example, `<div m="t-4 b-2">` will be transformed into `m-t-4`, `m-b-2`, which they are technically not valid syntax in windi's class mode, therefore windi have specific treatment to handle them in attrubutify mode. Where from my point of view, special rules are the eval leading to the complexity of a system, there are too many special cases in Windi which make it hard to understand and maintain. So in UnoCSS, one of my philosophies is to make things as general as possible so we could avoid dealing with the extra complexity.

In addition, with the auto rules merging, the generated size of CSS has very little impact on the different variations you are using.

```html
<div class="mt-4" mt="4" m="t-4">
</div>
```

```css
/* only one rule will be generated */
.mt-4,[m~="t-4"],[mt~="\34 "]{margin-top:1rem;}
```

**Comment by antfu** [comment]
@chu121su12 add me on Discord with antfu#3212

**Comment by chu121su12** [comment]
@antfu added

**Comment by alexanderniebuhr** [comment]
> generated size of CSS has very little impact on the different variations

yes I totally agree. my main concern was not based on size at all. It was just on my personal gut feeling that it might be better to not include other syntax and leave windi very opinionated. While people wanting to have more variants and options, would always use uno with another preset.
I will update this issue once we have decided finally to either add the variants in windi docs or to use a more specific preset.

Thank you for your input :)

**Comment by antfu** [comment]
Closing this for now. For misalignments with Tailwind, they should be open as separate issues per feature.

**Comment by louiss0** [comment]
> > generated size of CSS has very little impact on the different variations
> 
> yes I totally agree. my main concern was not based on size at all. It was just on my personal gut feeling that it might be better to not include other syntax and leave windi very opinionated. While people wanting to have more variants and options, would always use uno with another preset. I will update this issue once we have decided finally to either add the variants in windi docs or to use a more specific preset.
> 
> Thank you for your input :)

Please make windi strict. People should not be able to produce too many of the same classes. 
First of all this is not intuitive.
Second of all this is disruptive.
- People will have a hard time remembering the classes that represent a design system
- Standards across a codebase would not be enforced leading to many conflicts
- Why add unnecessary bundle size. 
  - Even though bundlers are smart enough to sort identical classes with commas bundle size will increase.
- Having two classes that do the same things makes debugging utilities harder to debug.

**Comment by louiss0** [comment]
Please make windi strict. People should not be able to produce too many of the same classes. 
First of all this is not intuitive.
Second of all this is disruptive.
- People will have a hard time remembering the classes that represent a design system
- Standards across a codebase would not be enforced leading to many conflicts
- Why add unnecessary bundle size. 
  - Even though bundlers are smart enough to sort identical classes with commas bundle size will increase.
- Having two classes that do the same things makes debugging utilities harder to debug.
