### ISSUE TITLE
Vite plugin can not work on bun runtime

### ISSUE THREAD

**Issue by Gn3po4g** [unocss/unocss#4061]
### UnoCSS version

0.61.9

### Describe the bug

`bunx vite` works correctly, but `bunx --bun vite` gives the error:
```log
error when starting dev server:
ReferenceError: Cannot access 'default' before initialization.
    at <anonymous> (E:\projects\app\node_modules\jiti\dist\jiti.cjs:1:180987)
    at jitiInteropDefault (E:\projects\app\node_modules\jiti\dist\jiti.cjs:1:181414)
    at <anonymous> (E:\projects\app\node_modules\jiti\dist\jiti.cjs:1:185158)
    at processTicksAndRejections (:12:39)
```

### Reproduction

add UnoCSS() into vite plugins and run `bunx --bun vite`

### System Info

bun version: 1.1.22
vite version: 5.4.0

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by henrikvilhelmberglund** [comment]
This is a Bun issue and should be posted here instead: https://github.com/oven-sh/bun/issues

**Comment by chrisbbreuer** [comment]
It can be followed here btw https://github.com/oven-sh/bun/issues/13338

**Comment by chrisbbreuer** [comment]
```
  "overrides": {
    "unconfig": "0.3.10"
  }
```
add this into your package.json and UnoCSS will work in Bun again. `importx` somehow introduced a Bun compat issue that I am not sure of yet
