### ISSUE TITLE
[eslint-plugin]: Bump to `typescript-eslint@v8`

### ISSUE THREAD

**Issue by pauliesnug** [unocss/unocss#4064]
### Clear and concise description of the problem

Currently throws a peer dependency error with ESLint v9.

### Suggested solution

Update dependency, seems like no breaking changes effect the plugin.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Should be fixed in the next version
