### ISSUE TITLE
unocss styles override each other  in vite http module 

### ISSUE THREAD

**Issue by leookun** [unocss/unocss#4066]
### UnoCSS version

0.61.9

### Describe the bug

When two vite services appear in the same html, the generated styles override each other.
Only in vite  dev mode

### Reproduction

codesandbox: https://codesandbox.io/p/devbox/vite-unocss-forked-m96tq5?file=%2Fsrc%2Fmain.ts%3A6%2C19-11%2C7
preview :https://m96tq5-3000.csb.app/

When you access port 3000 and click "import second vite server", className "bg-green" overwritten by the second service

### System Info

codesandbox

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Why do you use two Vite on a same page? I think that's the natural output if you want to do so, as CSS by themselves are order sensitive, I'd suggest you to disable UnoCSS on one of your server.

**Comment by leookun** [comment]
I have a platform .When the user enters the development mode of the platform,he can mount the local vite development service to the platform, and obtain the development experience of on-the-spot debugging. This is only available at development . After the user builds the plugins, he uploads the bundles through another route

![画板](https://github.com/user-attachments/assets/6dc7b914-c24a-4444-87df-5fb8af28037b)

**Comment by leookun** [comment]
https://unocss.dev/integrations/cli
