### ISSUE TITLE
preset-uno `px-toString` will generate javascript code to css

### ISSUE THREAD

**Issue by s3xysteak** [unocss/unocss#4069]
### UnoCSS version

0.62.1/0.61.9

### Describe the bug

`px-toString `
--output-->
`[px-toString=""]{padding-left:function toString() { [native code] };padding-right:function toString() { [native code] };}`

In my project `unocss` always broke with `echarts`, and finally I found that issue above. I am not sure why my echarts make unocss think should generate `px-toString` but anyway that might be a bug. #3967

### Reproduction

[playground](https://unocss.dev/play/?version=0.61.9&html=DwEwlgbgBADgHgWgC4HsDKSBOYB2BzAPgCgooBXHFAQiOAHpwJig&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDASSarID3fsMBVKtoAvqByNJScoADkFlRMkJCRgoLEoogy8pgW0GmyCoQqarDqABSS0jRZUABcoADaOtK1kUwWkIjhtJWRmhKg7tB8NZF0qJGggQC6XlM6kAAWfIgtAjVl0lEtbR3zi8uRQ6wkyNDqoIcofJjw6uCgCwBu4DRV58ismNDdOoFeTgYrdQa3mciH8lGKAEovI4fMZTIxLNY7JDocD-m4PKUgdJIEwPuAagBGAB0ACZUdImKh4EM5qZuJAqiAoJxifNgF91uMoToZoEIYIgA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmAvkA)

See the output css.

### System Info

  System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i3-10100 CPU @ 3.60GHz
    Memory: 3.45 GB / 15.90 GB
  Binaries:
    Node: 20.16.0 - ~\AppData\Local\fnm_multishells\6388_1723513781525\node.EXE
    npm: 10.8.1 - ~\AppData\Local\fnm_multishells\6388_1723513781525\npm.CMD
    pnpm: 9.6.0 - ~\AppData\Local\pnpm\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.4355

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by henrikvilhelmberglund** [comment]
The other object instance methods do the same thing `propertyIsEnumerable`, `valueOf` and so on.

Until it is fixed you can add `blocklist: ["px-toString"],` in uno.config.js|ts.
