### ISSUE TITLE
UnoCSS causes Vite CJS warning in Tutorialkit project

### ISSUE THREAD

**Issue by henrikvilhelmberglund** [unocss/unocss#4074]
### UnoCSS version

pinned 0.59.4 and latest

### Describe the bug

UnoCSS causes Vite CJS warning in default Tutorialkit project.

Seems caused by `...unoCSSConfig` inside `uno.config.ts` -
https://github.com/stackblitz/tutorialkit/blob/main/packages/astro/src/index.ts
which itself is an export of https://github.com/stackblitz/tutorialkit/blob/main/packages/theme/src/index.ts. 

`VITE_CJS_TRACE=true astro dev` showed a bunch of lines but not too clear to me what the root cause is.

Related: https://github.com/stackblitz/tutorialkit/issues/244

### Reproduction

https://stackblitz.com/github/henrikvilhelmberglund/tutorialkit-repro

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
https://github.com/stackblitz/tutorialkit/blob/main/packages/theme/src/index.ts 
I am a bit confused why the exported from `*.js` in `ts file`, maybe this is the cause of the problem?
By the way, I want to say that UnoCSS is now `ESM only`.

**Comment by henrikvilhelmberglund** [comment]
Yes, I thought it was weird to get a CJS error in Vite caused by UnoCSS considering UnoCSS is ESM only.

If I do something like this
`unoCSSConfig.js`
```js
import { rules, shortcuts, theme } from "@tutorialkit/theme";

var unoCSSConfig = {
  theme,
  rules,
  shortcuts
};

export {
  unoCSSConfig
}
```

`uno.config.ts`
```ts
// import { unoCSSConfig } from '@tutorialkit/astro';
import { unoCSSConfig } from './unoCSSConfig';
```

I don't get the error, even though they seem the same to me.

**Comment by zyyv** [comment]
So can we classify this as an internal error in `@tutorialkit/theme`?

**Comment by henrikvilhelmberglund** [comment]
If it's caused by UnoCSS it's an UnoCSS issue imo. `VITE_CJS_TRACE=true astro dev` shows where it's triggered.

**Comment by henrikvilhelmberglund** [comment]
TutorialKit is going to simplify and improve the UnoCSS integration so their issue with this gets fixed. There's still some weirdness since there's a CJS warning but I honestly have no idea how to fix this so closing this for now. Maybe it reappears when Vite 6 is released but hopefully not!
