### ISSUE TITLE
unocss style repeated loading

### ISSUE THREAD

**Issue by mojiefong** [unocss/unocss#4076]
### UnoCSS version

0.62.2

### Describe the bug

![image](https://github.com/user-attachments/assets/39d100a1-0300-406b-98af-8568b109f927)

Using unocss style will load multiple times.

At first I thought it was due to element plus, but the problem still exists after commenting it out

There are problems in Chrome and Edge, but Firefox seems to be normal

### Reproduction

https://github.com/mojiefong/my-vue-app

### System Info

macOS

pnpm v9.7.0
nodejs v20.10.0

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by LiYuzZ** [comment]
太影响样式调试了，期待解决

**Comment by antfu** [comment]
How do you trigger that behavior? I couldn't reproduce with your reproduction

**Comment by mojiefong** [comment]
> How do you trigger that behavior? I couldn't reproduce with your reproduction

Hmm? Can't my repository be reproduced?

Open the debug mode, select the `div` element and scroll down to see it

Actually, my demo is very simple, I just use vite to initialize the project and then install unocss

I uploaded a gif, you can take a look：

![20240823-100235](https://github.com/user-attachments/assets/95002474-1890-418a-b9cc-a70ba3e42a49)

**Comment by zoeyzhao19** [comment]
This is not kind of repeat. The `repeat` you called is just the same global styles inherited from its parent and its acestors, and it is expected to be overrided since the element itselt also applys the global styles. You can see in the style panel that `all styles with line-through` are listed in its own group, such as `body`
![image](https://github.com/user-attachments/assets/e2412467-be28-462a-8b5a-43ba2b3ee26b)

**Comment by mojiefong** [comment]
> 这不是重复。你调用的只是从其父级和前代继承的相同全局样式，并且预计它会被覆盖，因为它的元素也应用了全局样式。您可以在样式面板中看到其自己的组中列出的内容，例如`repeat``all styles with line-through``body`
> 
> ![图像](https://private-user-images.githubusercontent.com/70888488/361230176-e2412467-be28-462a-8b5a-43ba2b3ee26b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMjk2MTksIm5iZiI6MTcyNTMyOTMxOSwicGF0aCI6Ii83MDg4ODQ4OC8zNjEyMzAxNzYtZTI0MTI0NjctYmUyOC00NjJhLThiNWEtNDNiYTJiM2VlMjZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDAyMDgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliNzJmMDQ5YzI5ODg0MGJmMzQzNWM5OTcxYjBhY2JmZWE3ZjBjY2M2MjgxNWZiZmE1OWRjMjViZGEzZjRlNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZSQw78HZ3EQBup6rOXFP0OUjpyU1hKVTkFn8mFbdGqA)

@zoeyzhao19 

So how to optimize this? It affects the debugging of the style a bit.

**Comment by mojiefong** [comment]
> This is not kind of repeat. The `repeat` you called is just the same global styles inherited from its parent and its acestors, and it is expected to be overrided since the element itselt also applys the global styles. You can see in the style panel that `all styles with line-through` are listed in its own group, such as `body`
> 
> ![image](https://private-user-images.githubusercontent.com/70888488/361230176-e2412467-be28-462a-8b5a-43ba2b3ee26b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMjk5OTAsIm5iZiI6MTcyNTMyOTY5MCwicGF0aCI6Ii83MDg4ODQ4OC8zNjEyMzAxNzYtZTI0MTI0NjctYmUyOC00NjJhLThiNWEtNDNiYTJiM2VlMjZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDAyMTQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiYzAyNDU1NzYzMDhlMTNhMDY2OTM4YTdmODgwOTM4MWRjYzc5ZTM2YTRjZGZhNjcwYTUyODJjNDAyMmI1YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dJ6ENONvuXKQOGNdXtEVHxjPqv-JLEm7aePgB7r1vhk)

@zoeyzhao19 
So how to optimize this? It affects the debugging of the style a bit.

**Comment by Simon-He95** [comment]
It is currently consistent with [tailwind](https://play.tailwindcss.com/), so I think it should be reasonable
