### ISSUE TITLE
transformer-variant-group broken in 0.62

### ISSUE THREAD

**Issue by urzhumskov** [unocss/unocss#4088]
### UnoCSS version

0.62

### Describe the bug

Looks like transformer-variant-group is broken in 0.62.2 (with webpack/react at least)

Styles like `b-(2 solid red)` are not properly extracted when the project is built with `webpack build`

Reverting to 0.61.0 fixes this

### Reproduction

Minimal reproduction repo: https://github.com/urzhumskov/unocss-trans-v-g

```
$ pnpm install
$ NODE_ENV=production webpack build
$ grep b-solid build/*.css
```

App.tsx contains a single div with `className="b-t-blue b-(2 solid red)"` -- while the `b-t-blue` is properly extracted during build, the expected `b-2 b-solid b-red` classes are missing from the resulting CSS

Simply reverting everything uno-related to 0.61.0 seems to fix this:
```
$ pnpm add @unocss/webpack@0.61.0 @unocss/preset-uno@0.61.0 @unocss/transformer-variant-group@0.61.0 unocss@0.61.0
$ NODE_ENV=production webpack build
$ grep b-solid build/*.css
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by henrikvilhelmberglund** [comment]
This broke in [0.61.7](https://github.com/unocss/unocss/releases/tag/v0.61.7), not sure why but my guess is https://github.com/unocss/unocss/pull/3814.
