### ISSUE TITLE
When I use CDN to introduce it directly into HTML for development, the unocss plug-in of vscode does not work.

### ISSUE THREAD

**Issue by cMing1997** [unocss/unocss#4096]
### UnoCSS version

0.62.2

### Describe the bug

When I use CDN to directly introduce it into HTML for development, the unocss plug-in of vscode does not work, there is no preview, and there is no prompt.

### Reproduction

1. Create a new html page
2. Install UnoCSS’s vscode plug-in
3. Insert the following code in html
```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@unocss/reset/tailwind.min.css">
</head>

<body>
    <div class="index">
        <header class="index-header h-500px bg-#eee"></header>
    </div>
</body>
<script src="https://cdn.jsdelivr.net/npm/@unocss/runtime/uno.global.js"></script>

</html>
```

### System Info

vscode：1.79.0 (system setup)
node: v14.18.2

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Yeah unfortunately that's how it is, the extension can't detect those cases. You can create a fake `uno.config.ts` file to activate the extension.
