### ISSUE TITLE
feat: `.d.ts` auto generation for attributify mode in TSX

### ISSUE THREAD

**Issue by jiangyijie27** [unocss/unocss#41]
I add a custom declaration to avoid the type error in `.tsx` file:
```ts
import { AriaAttributes, DOMAttributes } from 'react';

declare module 'react' {
  interface HTMLAttributes<T> extends AriaAttributes, DOMAttributes<T> {
    w?: string;
    h?: string;
    ...
  }
}
```

```tsx
<div w='screen' h='screen' />
```

Is there another recommended way for  attributify mode in `.tsx` ?

**Comment by edwardnyc** [comment]
```
declare module 'react' {
  interface HTMLAttributes<T> extends AriaAttributes, DOMAttributes<T>, Record<string, string> {
  }
}
```

Maybe it's not a good solution

**Comment by antfu** [comment]
Unfortunately, I think it's the only workaround I can think of for now. It's possible to make the `.d.ts` generation automated (like https://github.com/antfu/unplugin-auto-import) when hooking into the matched result, but I will leave it for the community to do that.

**Comment by antfu** [comment]
After a second thought, I think it's better to have this functionality part for the default tools with a flag behind. Reopen for tracking.
