### ISSUE TITLE
Postcss Unknown Word on build on Nuxt with autoImport false

### ISSUE THREAD

**Issue by Aterbonus** [unocss/unocss#4105]
### UnoCSS version

0.63.3

### Describe the bug

When building for production on nuxt and autoImport false (importing unocss with ```import uno.css``` on Vue SFC) gives an Postcss Unknown Word error when using certain classes.

In particular, classes in the style of ```after:content-['']``` trigger the error. 

After further investigation, the css processed by postcss appears to be something like this:

```... .after\:content-\[\'\'\]::after{content:'';}.after\:content-\[\&\#39\;\&\#39\;\]::after{content:&#39;&#39;;} ...```

Note the repetition and the use of ```&#39;```

It appears that the last version where it works is 0.60.4.

Meanwhile, we can use the class ```after:content-empty``` as it appears to work fine. But if we use something like ```after:content-['*']``` we don't have an option.

### Reproduction

Not working: https://stackblitz.com/edit/nuxt-starter-s5ubpw
Working: https://stackblitz.com/edit/nuxt-starter-1kuhmy

Run ```npm run build```

### System Info

I tried with latest Nuxt version (3.13.0) for the minimal reproduction and Nuxt 3.5.2 on my production app, both with autoImport false.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by InvincibleJun** [comment]
me too
