### ISSUE TITLE
`@unocss/nuxt` Custom local fonts reload

### ISSUE THREAD

**Issue by Rcoxx** [unocss/unocss#4109]
### UnoCSS version

0.62.3

### Describe the bug

- The presetWebFonts is used in the uno config.
- Custom font styles are imported in the Vue page.
- The font files are reloaded repeatedly when the window is resized.

https://github.com/user-attachments/assets/ecd00194-7911-419b-a308-0571a6723e03

### Reproduction

https://github.com/Rcoxx/unoc-font-reproduction

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
I didn't reproduce it on https://stackblitz.com/github/Rcoxx/unoc-font-reproduction.

**Comment by Rcoxx** [comment]
> I didn't reproduce it on https://stackblitz.com/github/Rcoxx/unoc-font-reproduction.

I switched to different systems( macos/win) and devices, and the problem still exists. You should probably download it to test locally.

**Comment by JohnieXu** [comment]
I downloaded this project and ran it locally. It can be reproduced, but it only appears when the window size is adjusted within a certain range.
![微信截图_20240909151330](https://github.com/user-attachments/assets/575fd120-431e-4ef5-9c28-7eb87e0c45e7)

**Comment by zyyv** [comment]
@Rcoxx Is this a problem with unocss? I don't see any place in the code where uno is used, and the request in the network is also requesting local fonts, which has nothing to do with uno.

@JohnieXu Can you help test if this happens without `@unocss/nuxt` ?

```diff
export default defineNuxtConfig({
- modules: ['@unocss/nuxt'],
})
```

**Comment by JohnieXu** [comment]
> @Rcoxx Is this a problem with unocss? I don't see any place in the code where uno is used, and the request in the network is also requesting local fonts, which has nothing to do with uno.
> 
> @JohnieXu Can you help test if this happens without `@unocss/nuxt` ?
> 
> ```diff
> export default defineNuxtConfig({
> - modules: ['@unocss/nuxt'],
> })
> ```
After I removed `@unocss/nuxt`, this bug did not occur.

**Comment by zyyv** [comment]
@JohnieXu @Rcoxx I found that this is a component in the `vite-plugin-vue-inspector` plugin that registered a `resize` event on the `body`. Disable `@nuxt/devtools` can solve this behavior.

```diff
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  modules: ['@unocss/nuxt'],
+ devtools: {
+   enabled: false
+ }
})

```
