### ISSUE TITLE
`@unocss/svelte-scoped` requires `@unocss/preset-uno` to be installed

### ISSUE THREAD

**Issue by benmccann** [unocss/unocss#4116]
### UnoCSS version

0.62.3

### Describe the bug

`@unocss/svelte-scoped` imports `@unocss/preset-uno` and requires it to be installed, which was confusing to me since I'm only using `@unocss/preset-icons`

### Reproduction

https://github.com/unocss/unocss/blob/243623ddb7decd7002e4110ef3674e1feeef6297/packages/svelte-scoped/src/_vite/index.ts#L6

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by userquin** [comment]
Should be added to dependencies:
```json
"@unocss/preset-uno": "workspace:*"
```
/cc @jacob-8

**Comment by benmccann** [comment]
It'd be nice not to add the extra dependency. Perhaps we could instead dynamically import it if the user did not specify any presets.

**Comment by userquin** [comment]
We also need to check `@unocss/reset`, it is external in the build config

**Comment by userquin** [comment]
> It'd be nice not to add the extra dependency. Perhaps we could instead dynamically import it if the user did not specify any presets.

Maybe we can even use Nuxt integration approach where you just enable flags per preset (ofc, we'll need to install missing dependencies): https://github.com/unocss/unocss/blob/main/packages/nuxt/src/types.ts

**Comment by benmccann** [comment]
Maybe we can just remove the default preset? It doesn't seem like the other integrations have the same function call:
https://github.com/search?q=repo%3Aunocss%2Funocss%20setConfig&type=code

**Comment by benmccann** [comment]
There's one other place that would need to be updated as well:

https://github.com/unocss/unocss/blob/243623ddb7decd7002e4110ef3674e1feeef6297/packages/svelte-scoped/src/_preprocess/index.ts#L4

I'm still not sure if the defaults are required. Other places don't use them:

https://github.com/unocss/unocss/blob/243623ddb7decd7002e4110ef3674e1feeef6297/packages/eslint-plugin/src/worker.ts#L20

**Comment by jacob-8** [comment]
> @unocss/svelte-scoped imports @unocss/preset-uno and requires it to be installed

As long as you install svelte-scoped as directed with
`pnpm add -D unocss @unocss/svelte-scoped` you won't need to install @unocss/preset-uno manually.

Also you should know it the default behavior of UnoCSS to use preset-uno if no presets are provided by the user (see https://unocss.dev/guide/presets).

If you've followed the above install instruction and still have an issue please share a minimal reproduction link, otherwise I think this can be closed.

**Comment by benmccann** [comment]
> As long as you install svelte-scoped as directed with pnpm add -D unocss @unocss/svelte-scoped you won't need to install @unocss/preset-uno manually.

The point is that you shouldn't have to install the entire `unocss` package, but just be able to use `@unocss/svelte-scoped`

**Comment by benmccann** [comment]
I've sent a fix to dynamically import `presetUno`: https://github.com/unocss/unocss/pull/4119

**Comment by jacob-8** [comment]
> The point is that you shouldn't have to install the entire `unocss` package, but just be able to use `@unocss/svelte-scoped`

Please read the docs. The [Nuxt](https://unocss.dev/integrations/nuxt), [svelte-scoped](https://unocss.dev/integrations/svelte-scoped#vite-plugin), and [webpack](https://unocss.dev/integrations/webpack) integration all require it. Then the Vite and Astro integrations are part of the main `unocss` package. _The install line for webpack has an omission typo - if you read further on that page or look in the code, you'll find `unocss` needs installed also._

Please read the `svelte-scoped` code and note all the necessary imports from `@unocss/core` necessary to make `svelte-scoped` run. It sits on top on of `unocss` and lets you use the generator in our custom Svelte use case.

Please read the [`sveltekit-scoped` example](https://github.com/unocss/unocss/blob/4e3cdc7e5a5c6ec2b3e3065d7ff8b45e57020060/examples/sveltekit-scoped/uno.config.ts) and note all the imports from `unocss`. Even just to create a `uno.config.ts` file and get the typing helper function requires `unocss`.

**Comment by jacob-8** [comment]
Haha, I give up. You win, @benmccann - let's make it so you don't need to bring unocss ([the graph you're trying to avoid](https://npmgraph.js.org/?q=unocss#select=exact%3Aunocss%400.62.3)) into your project.

I would like to go the route of just adding `"@unocss/preset-uno": "workspace:*",` to the dependencies as done in #4121. It's a [small](https://npmgraph.js.org/?q=@unocss/preset-uno#select=exact%3A%40unocss%2Fpreset-uno%400.62.3), addition considering `magic-string` and `@unocss/core` are already dependencies. This will avoid needing the messy if checks and dynamic imports of preset-uno and keep the code in sync with the original [vite plugin](https://github.com/unocss/unocss/blob/cc114b1f237bd2188f9d9fc3e51b3c46c4db90f4/packages/unocss/src/vite.ts) it came out of.

Tell me more about your svelte-add plans. Are you hoping the svelte-add operation will run without making users install `unocss`?  If so, we should make the `defineConfig` available in `@unocss/config` so we can do `import { defineConfig } from '@unocss/config'`. svelte-add is there to make things simpler and new users can get going a lot faster with the type definitions. _Though I think new users should bring down unocss... so yes, let me know your thoughts on this note._
