### ISSUE TITLE
Expect theme breakpoints configuration to support Tailwindcss breakpoint advanced configuration

### ISSUE THREAD

**Issue by AAABingBing** [unocss/unocss#4125]
### Clear and concise description of the problem

Expect theme breakpoints configuration to support Tailwindcss breakpoint advanced configuration

For example:
Unocss screen breakpoint defaults to min-width, I don't know how to configure it to max-width

[Tailwindcss screens advanced-configuration](https://tailwindcss.com/docs/screens#advanced-configuration)

### Suggested solution

```js
theme: {
  // ...
  breakpoints: {
    sm: {'max': '319px'},
    md: {'max': '639px'},
  },
}
```

[Tailwindcss screens advanced-configuration](https://tailwindcss.com/docs/screens#advanced-configuration)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by AAABingBing** [comment]
#2983

**Comment by cloydlau** [comment]
@AAABingBing May I ask how you solved it?

**Comment by AAABingBing** [comment]
> @AAABingBing May I ask how you solved it?

[Playground](https://unocss.dev/play/?html=DwEwlgbgBA7gTgQwA5IKZwHwCgpVJKBAFwFoBbEALiNQA9S5UQoAbUgZzOrtICMWArqlYBzbvRIjGqAHYYAqjID2AYQDKa4AHpwEbNt3YgA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCCMMUwARgK4zDoCeZF1tAJIBjAlT6UaMAKpYIcAL5x0UCCDgByNnOFUqGgFAHUAD0iwUGAIZsANvDSYc%2BQsCIAKBAbhwqAC2gYYQ4qAC5Ebx84AHcoKzAwVChwjWiAWgBGAAYsgDdouD9MnNy-ZVtTOGAYVBAqNOFULBqoOAArNipOHgamlo0SSIVBnxg-WtRwryi4FkorAGtIbBgwiJmfKhAUgGYAJiywEwHImZBkFIA2ABZD45GN2yIUgHYADjuTmeGhh-4pNYAbVO5EktFkEHcAEoHj5-rQGExWBwuNxobDQQIYCIxJ4QZthFYKuEMgA6PYYnzCZBYFJ%2BRhgMIAeiZ1BApP8TK%2BUQUMMiAF1BryDEA&css=Q&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g)

See #2983
