### ISSUE TITLE
Feature proposal: replace `screen-<unit>` strings in arbitrary values with their actual pixel value

### ISSUE THREAD

**Issue by UltraCakeBakery** [unocss/unocss#4126]
### Clear and concise description of the problem

I  want to be able to do this: `px-[calc(screen-xl/2)]` to easily create padding that centers the content of an scrollable to emulates `mx-auto` centration of content.

Now I have to manually convert the pixel value of screen-xl like so `px-[calc(1280px/2]`

### Suggested solution

UnoCSS should replace `screen-xl` in the `[]` arbitrary value with its actual value which also gets used in utilities such as `w-screen-xl`

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by henrikvilhelmberglund** [comment]
Use https://unocss.dev/transformers/directives and `theme()`.

`px-[calc(theme(breakpoints.xl)/2)]`

[play](https://unocss.dev/play/?version=0.62.3&html=DwIwrgLhD2B2AEBjANgQwM7oLwCIQHMBaEZMAU0IBYAGa%2BABwA9CBtRVZRACggAsyAtmS4gATmVQBretACWsCOgB0jZAEoA9ACY1AXQYBPQqpwA%2BcFDjANFmLFNA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6smVUdAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k7pVGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWsULlQKmozkggA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYGECucxIwZXxAC4EoAbOAUwBpxp5k0AJMVcksyqgXyA)

**Comment by UltraCakeBakery** [comment]
Pff, I forgot about that directive! Thanks for making me aware. I think that using the directive is a sufficient, so I'll close this issue as not planned.
