### ISSUE TITLE
bug: variants not applied correctly with `transformerDirectives`

### ISSUE THREAD

**Issue by HigherOrderLogic** [unocss/unocss#4127]
### UnoCSS version

0.62.3

### Describe the bug

Class variants like `dark:xxx` are not applied correctly when used with `transformerDirectives`.

### Reproduction

[Playground](https://unocss.dev/play/?version=0.62.3&html=DwEwlgbgBAxgNgQwM5ILwCIQIE4Gt0B8AFgKZxwD2okBQA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcEWWwCGuOlmggMUACLBaE3gDd6lAL5wsUCCDgByLiol06TpEgwAPSLDo2OpcADbwmDj4RCTApAAUyKhQYfQAXHAA2lSomU4SXHQwDgC0KaEYTuSIcFKh0BlOtGhOcFYAurKdVHQAFtAwBTB0GUmozgVFpX0DQ06NMH4wJaGkcIu%2By9CapBhw-RZQaRvLi%2BqhVVRWsiIKI1k5cqJKKvEAlLLC8owsbJw8fH470%2BTwUkmkiUeqDoEnOGAyAEYAHQAJhBqAkaFwjV6rDAIwA9AT6CAkX0CZdxm0PlRuqgNFodFA9FB7pkGdpdPojCZzPR3u0kFY3kggA&css=CYSwbgBA3gUBEFoEEMAuKAOGA2BPAXBAETDIBOA1vqgKYAe6AziAF40LYDmRA3DAL5A&options=N4IgLgTghgdgzgMwPYQLYGECucxIwZXxAC4EoAbOAUwF8g)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zoeyzhao19** [comment]
If you mean the font size, it's been rendered correctly.

**Comment by HigherOrderLogic** [comment]
I dont think that's correct. Even when I change to [text color](https://unocss.dev/play/?version=0.62.3&html=DwEwlgbgBAxgNgQwM5ILwCIQIE4Gt0B8AFgKZxwD2okBQA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcEWWwCGuOlmggMUACLBaE3gDd6lAL5wsUCCDgByLiol06TpEgwAPSLDo2OpcADbwmDj4RCTApAAUyKhQYfQAXHAA2lSomU4SXHQwDgC0KaEYTuSIcFKh0BlOtGhOcFYAurKdVHQAFtAwBTB0GUmozgVFpX0DQ06NMH4wJaGkcIu%2By9CapBhw-RZQaRvLi%2BqhVVRWsiIKI1k5cqJKKvEAlLLC8owsbJw8fH470%2BTwUkmkiUeqDoEnOGAyAEYAHQAJhBqAkaFwjV6rDAIwA9AT6CAkX0CZdxm0PlRuqgNFodFA9FB7pkGdpdPojCZzPR3u0kFY3kggA&css=CYSwbgBA3gUBEFoEEMAuKAOGA2BPAXBAETDIBOA1vqgKYAe6ZNwRA3DAL5A&options=N4IgLgTghgdgzgMwPYQLYGECucxIwZXxAC4EoAbOAUwF8g), the element stays the same.

**Comment by zoeyzhao19** [comment]
> I dont think that's correct. Even when I change to [text color](https://unocss.dev/play/?version=0.62.3&html=DwEwlgbgBAxgNgQwM5ILwCIQIE4Gt0B8AFgKZxwD2okBQA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcEWWwCGuOlmggMUACLBaE3gDd6lAL5wsUCCDgByLiol06TpEgwAPSLDo2OpcADbwmDj4RCTApAAUyKhQYfQAXHAA2lSomU4SXHQwDgC0KaEYTuSIcFKh0BlOtGhOcFYAurKdVHQAFtAwBTB0GUmozgVFpX0DQ06NMH4wJaGkcIu%2By9CapBhw-RZQaRvLi%2BqhVVRWsiIKI1k5cqJKKvEAlLLC8owsbJw8fH470%2BTwUkmkiUeqDoEnOGAyAEYAHQAJhBqAkaFwjV6rDAIwA9AT6CAkX0CZdxm0PlRuqgNFodFA9FB7pkGdpdPojCZzPR3u0kFY3kggA&css=CYSwbgBA3gUBEFoEEMAuKAOGA2BPAXBAETDIBOA1vqgKYAe6ZNwRA3DAL5A&options=N4IgLgTghgdgzgMwPYQLYGECucxIwZXxAC4EoAbOAUwF8g), the element stays the same.

![image](https://github.com/user-attachments/assets/38fd2e3f-fa2b-447e-8e72-e91da9a139d4)

**Comment by HigherOrderLogic** [comment]
Seems like a browser specific issue then. I'm running on Edge and the text's white for me.

**Comment by henrikvilhelmberglund** [comment]
I tested in edge and it's red for me. Can you inspect the element and check if you have the `.dark div` selector and what it's doing?

**Comment by HigherOrderLogic** [comment]
It seems like the `.dark div` selector isn't doing anything on my side.

**Comment by henrikvilhelmberglund** [comment]
Sounds weird, this is how the element looks for me:
![image](https://github.com/user-attachments/assets/bd74d090-4e07-4970-a95c-66c6e8b47879)

**Comment by HigherOrderLogic** [comment]
![image](https://github.com/user-attachments/assets/47afcf4f-e95b-4cec-9090-f2aefe0404c8)

This is it for me.

**Comment by henrikvilhelmberglund** [comment]
Do you get the same result in a private window? (without extensions)

And the actual playground is in dark mode? (using the icon in the top right)

**Comment by HigherOrderLogic** [comment]
Oh yeah, changing the playground to dark mode solve it. Even then, I think the text should still be red without turning the whole playground into dark mode.

**Comment by henrikvilhelmberglund** [comment]
I think `dark` with a class only works if you set it eaclier in the HTML tree. Usually you set it on the <html> tag like `<html class="dark">`, this is what the icon in the top right does.

So it should look something like this: [play](https://unocss.dev/play/?version=0.62.3&html=DwWwhglgdgBAxgGzAZ2QXgEQBMwCcDWGAfAFAwzBYQBuRAFgKYIID2wA9FbSR%2BNKUA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcEWWwCGuOlmggMUACLBaE3gDd6lAL5wsUCCDgByLiol06TpEgwAPSLDo2OpcADbwmDj4RCTApAAUyKhQYfQAXHAA2lSomU4SXHQwDgC0KaEYTuSIcFKh0BlOtGhOcFYAurKdVHQAFtAwBTB0GUmozgVFpX0DQ06NMH4wJaGkcIu%2By9CapBhw-RZQaRvLi%2BqhVVRWsiIKI1k5cqJKKvEAlLLC8owsbJw8fH470%2BTwUkmkiUeqDoEnOGAyAEYAHQAJhBqAkaFwjV6rDAIwA9AT6CAkX0CZdxm0PlRuqgNFodFA9FB7pkGdpdPojCZzPR3u0kFY3kggA&css=CYSwbgBA3gUBEFoEEMAuKAOGA2BPAXBAETDIBOA1vqgKYAe6ZNwRA3DAL5A&options=N4IgLgTghgdgzgMwPYQLYGECucxIwZXxAC4EoAbOAUwF8g)

**Comment by HigherOrderLogic** [comment]
Yeah you are right. I just check the docs again and `.dark div {}` is for `<element class="dark"><div /><element>` and isn't for the parent `<element />`.

So maybe I should convert this issue into a feature request for variants that apply to element with specific classes, for example `&.dark:xxx`?

**Comment by henrikvilhelmberglund** [comment]
> So maybe I should convert this issue into a feature request for variants that apply to element with specific classes, for example `&.dark:xxx`?

You can already make a custom variant: [play](https://unocss.dev/play/?version=0.62.3&html=DwEwlgbgBAxgNgQwM5ILwCIQIE4Gt0B8AUFFMAA7GkAWApnHAPYlkD0lRwr4ExnPBAHaMALlCx4uAoA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcEWWwCGuOlmggMUACLBaE3gDd6lAL5wsUCCDgByLiol06TpEgwAPSLDo2OpcADbwmDj4RCTApAAUyKhm6uyaMHQAXHAA2lSo8SDqMBIAFvoAlHAAvAB8iPmocHxw8QCERSXlUAB0dDCpGQDqwDCl8U4SXP0OALRoqQDWmU4VVbQwXFC4cJ1l%2Bo2oG1s7SU3ne93Zl-p9ocASGPEAjABMFbLnqAyhGKbQ2XidCqdTgAAM4AASBB0Kw9BZQRZgz5fAD0qKhMJswDocGgcTw6lCcB%2Bfxg0EOcCsjSssgAurIoGF6NkcjlJtNySBZkzfk5yIg4FJQgDnLQ0E4qXSGVQ6KVoCUeFkGucOTNuXKFVMYE5sk4YH4YLNQqQ4AbfEboJpSBg4PKLFBMuajQaifyqLSqCIFMq8udvYxlBB4h9GgHmKx2NxeAIQyjw5JpIlKXQJESMNlnj1XijUBI0Lg9aVWGAsuj6CA%2BqVUe7zlZQ6gZagNFodFA9FBfS3tLp9EYTOZ6CGZfWkEA&css=CYSwbgBA3gUBEFoEEMAuKAOGA2BPAXBAEQDGArgM6oD2AtgsMgE4DW%2BqApgB7pMfBEA3DAC%2BQA&options=N4IgLgTghgdgzgMwPYQLYGECucxIwZXxAC4EoAbOAUwF8g)

You just need to customize the selector and matcher to what you want.

**Comment by zyyv** [comment]
I think there is nothing wrong with this. The `dark` class name in this example conflicts with the `default dark variant`. You can refer to this configuration to modify it. https://unocss.dev/presets/mini#dark
