### ISSUE TITLE
在uniapp x项目中使用unocss报错

### ISSUE THREAD

**Issue by chenxiaosi666** [unocss/unocss#4130]
### UnoCSS version

0.62.3

### Describe the bug

在uniapp x中使用unocss开发iOS，Android报错原因是无法导入在main.uts文件中导入virtual:uno.css文件，而tailwind css导入 css文件这种方式没问题

### Reproduction

[Uploading 归档.zip…]()

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
Refer to 
- https://github.com/MellowCo/unocss-preset-weapp  
- https://github.com/uni-helper/unocss-preset-uni
