### ISSUE TITLE
fetch & autoinstall fonts from `fontsource`

### ISSUE THREAD

**Issue by ryoppippi** [unocss/unocss#4147]
### Clear and concise description of the problem

Downloading and hosting Google Fonts locally requires creating an asset directory and determining if the license is correct. It's a bit inconvenient.

### Suggested solution

`fontsource` is a open-sourced font registry, and we can install fonts via npm.
If we can use `fontsource` to download font fies instead of google fonts, we don't need to manage assets directory.
Also, auto-installing feature enables version-management of font files.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by henrikvilhelmberglund** [comment]
Fontshare is available as a provider in https://unocss.dev/presets/web-fonts. What is the actual problem?

**Comment by ryoppippi** [comment]
`Fontshare` and `Fontsource` is different, some fonts are missing in `Fontshare`

**Comment by henrikvilhelmberglund** [comment]
> `Fontshare` and `Fontsource` is different, some fonts are missing in `Fontshare`.

Ah, my bad! You can use `fontsource` by installing the fonts like normal and using web fonts with `provider: "none"`.

**Comment by ryoppippi** [comment]
Yes! That is what I'm doing rn!

**Comment by zyyv** [comment]
I have researched `fontsource` before, but I stopped the process for some reason. I will consider pr later.

**Comment by ryoppippi** [comment]
Nice thanks!!!
