### ISSUE TITLE
unocss cant transform less variable

### ISSUE THREAD

**Issue by xjccc** [unocss/unocss#4150]
### UnoCSS version

0.62.4

### Describe the bug

https://github.com/nuxt/nuxt/issues/29066

### Reproduction

In Nuxt: https://stackblitz.com/edit/github-e1dfk2?file=nuxt.config.ts,app.vue
Without Nuxt: https://stackblitz.com/edit/github-7qswuv

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
Have you enable UnoCSS transformer? https://unocss.dev/transformers/directives

**Comment by xjccc** [comment]
> Have you enable UnoCSS transformer? https://unocss.dev/transformers/directives

In my actual project, my `unocss.config`

```
// uno.config.ts
import { defineConfig, presetAttributify, presetUno } from 'unocss'
import presetRemToPx from '@unocss/preset-rem-to-px'
import transformerVariantGroup from '@unocss/transformer-variant-group'
import transformerDirectives from '@unocss/transformer-directives'

export default defineConfig({
  presets: [
    presetAttributify({
      /* preset options */
      ignoreAttributes: [':src']
    }),
    presetUno(),
    presetRemToPx()
  ],
  transformers: [transformerVariantGroup(), transformerDirectives()],
  variants: [],
  theme: {
    breakpoints: {},
    colors: {}
  },
  shortcuts: [],
  rules: []
})
```

**Comment by zyyv** [comment]
<img width="430" alt="image" src="https://github.com/user-attachments/assets/6fc31870-6914-466d-95b8-96bdacc17218">

I saw it was converted successfully, but when I replace to the actual web image link, the less variable definition caused the build to fail, perhaps the less definition was causing a file conflict.
