### ISSUE TITLE
`svelte-scoped` always parses `theme()`

### ISSUE THREAD

**Issue by vdawg-git** [unocss/unocss#4166]
### UnoCSS version

0.62.4

### Describe the bug

I want to use `unocss-icons` in my UI library with Tailwind.

However, I get compile errors as I am using the Tailwind `theme()` directive.

As this also happens with an empty UnoCss config it's probably a bug.
```js
import { defineConfig } from 'unocss'

export default defineConfig({
  presets: [],
  // presets: [require('@unocss/preset-icons')],
  rules: [],
  extractors: [],
  transformers: [],
  extractorDefault: false,
  shortcuts: {},
  variants: [],
})
```

```js
> "olors.slate.5" is not found in your theme
    at getThemeValue (file:///home/vdawg/dev/efront/node_modules/.pnpm/@unocss+svelte-scoped@0.62.4/node_modules/@unocss/svelte-scoped/dist/shared/svelte-scoped.C_b8iifX.mjs:378:13)
    at file:///home/vdawg/dev/efront/node_modules/.pnpm/@unocss+svelte-...
```

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-kcbfsk?file=uno.config.ts&view=editor

Run `npm run package`

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by userquin** [comment]
Use `theme('xxx')`: https://unocss.dev/integrations/postcss#theme

Check https://unocss.dev/integrations/svelte-scoped#add-plugin (you're using vite instead vite svelte-scoped)

**Comment by vdawg-git** [comment]
Is it possible to tell UnoCss to ignore the `theme()` directive?

Tailwind should handle it

**Comment by henrikvilhelmberglund** [comment]
`@unocss/svelte-scoped/preprocess` right now has hard coded `theme()` support (https://github.com/unocss/unocss/blob/main/packages/svelte-scoped/src/_preprocess/transformTheme.ts), this can probably be changed to be a Svelte Scoped preprocess specific setting.

**Comment by vdawg-git** [comment]
Yes, like the `applyVariable`. 
I keep the issue open. For now, I just use regular svgs.

And thank you for your help :)
