### ISSUE TITLE
After updating to v0.63.1, vscode's plug-in does not work

### ISSUE THREAD

**Issue by TianQian-A** [unocss/unocss#4177]
### UnoCSS version

0.63.1

### Describe the bug

![image](https://github.com/user-attachments/assets/70428373-d404-4fe2-bfb5-3ddd3b505ff6)
![image](https://github.com/user-attachments/assets/93da8b48-cffa-481c-81cb-ae4a0082a95b)

Am I missing anything?

### Reproduction

Create a all-new vue project and add UnoCSS

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by 132789** [comment]
just go back to the previous version

**Comment by TianQian-A** [comment]
> just go back to the previous version

That's what I did for now

**Comment by zhouLion** [comment]
Same issue with me: 

## VSCode version
```
Version: 1.94.0-insider
Commit: 1cbbe85eaad55215833e597d675e778db74ae80e
Date: 2024-09-27T14:53:58.142Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0
```

## Extension log of UnoCSS
```
⚪️ UnoCSS for VS Code v0.63.1

📂 roots search mode.

-----------
🛠 Resolving config for /Users/admin/Documents/code/xxxxx
🗂️ Enabled context: [none]
```

**Comment by giserman001** [comment]
Same issue with me

**Comment by charlie0228** [comment]
UnoCSS for VS Code v0.63.1 is not compatible with previous version.

So I rollback to previous version (v0.62.4)

**Comment by Simon-He95** [comment]
It seems that this change is caused by 4e72e19605e3b085a1e61bd5281362e04a9e8e98
<img width="732" alt="image" src="https://github.com/user-attachments/assets/2d5107e0-7521-424a-aa76-be0a20fd6ff7">

**Comment by Mr54233** [comment]
Same issue with me

**Comment by zhouLion** [comment]
> It seems that this change is caused by [4e72e19](https://github.com/unocss/unocss/commit/4e72e19605e3b085a1e61bd5281362e04a9e8e98) <img alt="image" width="732" src="https://private-user-images.githubusercontent.com/57086651/371853938-2d5107e0-7521-424a-aa76-be0a20fd6ff7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2NjYyNzQsIm5iZiI6MTcyNzY2NTk3NCwicGF0aCI6Ii81NzA4NjY1MS8zNzE4NTM5MzgtMmQ1MTA3ZTAtNzUyMS00MjRhLWFhNzYtYmUwYTIwZmQ2ZmY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDAzMTI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2NjhmY2NhNTlkMWE5NDNkNzUyNDRjZTk3NmUzMjU3ZWJjNDkwZTk4Njc3ZGUxOTAzYWExYTRiMDEzZWY2MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zJusm6Ipp1MOdvNwGRrAVrQ-Lj5CuV00PrdgwZBmym4">

This [line-/packages/vscode/src/contextLoader.ts#L125](https://github.com/unocss/unocss/blob/4e72e19605e3b085a1e61bd5281362e04a9e8e98/packages/vscode/src/contextLoader.ts#L125) uses the `require` statement, with the new field `type: module` in the `package.json` which will cause some problems with building with `tsup`.

**Comment by lizyChy0329** [comment]
The Unocss@v0.62.4  is work

**Comment by lederhaus** [comment]
> UnoCSS for VS Code v0.63.1 is not compatible with previous version.
> 
> So I rollback to previous version (v0.62.4)

Even I install unocss 0.63.1 still autocomplete is not worrking

**Comment by dbstd2333** [comment]
Same issue with me

**Comment by chanon** [comment]
Same issue, reverted to 0.62.4 and it works.

**Comment by nakorndev** [comment]
Same problem +1.

Workaround right now I using UnoCSS on project 0.63.1 but on VSCode extension using 0.62.4 is working fine.

**Comment by trydofor** [comment]
`0.63.2` works
