### ISSUE TITLE
Support adding a prefix to each class name in the output.

### ISSUE THREAD

**Issue by hellohejinyu** [unocss/unocss#4179]
### Use Case

In my main project, I am using UnoCSS. I also dynamically import components from another project that also uses UnoCSS. However, when importing components from the other project, the CSS loading order sometimes changes, affecting the styles in the main project. 

To avoid conflicts, I would like to add a prefix to the class names in the CSS output of the secondary project. For example, if I use the `m-0` syntax in the secondary project, the final build output should be something like `prefix-m-0` with the corresponding CSS:

```css
.prefix-m-0 {
  margin: 0;
}
```

This way, the styles from both projects won't clash.

### Suggested solution

Support adding a prefix to each class name in the output.

### Additional context

<img width="1209" alt="image" src="https://github.com/user-attachments/assets/8d68ddc2-08c7-4f4d-ba64-d33fa93a5cc3">

### Attempted Solution

As shown in the screenshot, I tried writing a transformer to achieve this. The red parts represent the main module, and the blue parts represent the submodule. You can see that the class names in the blue parts have been prefixed with `x-`.

Unfortunately, this transformer does not handle every type of class name correctly. I am not very familiar with transformers, so I am hoping the official team can implement this feature. I believe this would be very helpful in resolving style priority conflicts between open-source components using UnoCSS and the developer's main project using UnoCSS.

![image](https://github.com/user-attachments/assets/ee271bfd-a2b9-4339-b13b-9026fb168553)

The issue I encountered is that I used regular expressions to match class names. However, in my project, I use `clsx` to dynamically select different classes. Therefore, I am unsure of a good solution to accurately match these and then add the prefix.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by henrikvilhelmberglund** [comment]
Did you try the compile class transformer? https://unocss.dev/transformers/compile-class

**Comment by hellohejinyu** [comment]
Yes, I found this transformer. It works well, but I need to add `:uno:` to all class names. Therefore, I prefer to find a solution that doesn't require me to review all the existing code again. Perhaps adding a default active configuration to the `compile-class` transformer would also be a good option.😝

**Comment by zyyv** [comment]
I think `prefix` option is enough.
[Playground](https://unocss.dev/play/?html=DwEwlgbgUABDDGAbAhgZ1QXgEQAcBOApgGZgAeAtAC4GmXkCspiM%2BxZVNdhIWUAfLBgBVAHYB7AMIBlKVGAB6cBAFA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCqWEcAvnOlBCHAOQCujAYypVuAKFGoAHpFgoMAQ14AbeGkw58hYEQAUCUXHKUaMKgC44AbQOGj1Wgwh6btu5kkXuFDMEkBabhIXFgBKIMMAXSDmENEgA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4XyA)

**Comment by zyyv** [comment]
Or you can use this hook to change outputs. [docs postprocess](https://unocss.dev/play/?html=DwEwlgbgUABDDGAbAhgZ1QXgEQAcBOApgGZgAeAtAC4GmXkCspiM%2BxZVNdhIWUAfLBgBVAHYB7AMIBlKVGAB6cBAFA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCqWEcAvnOlBCHAOQCujAYypVuAKFGoAHpFgoMAQ14AbeGkw58hYEQAUCUXHKUaMKgC44AbQOGj1Wgwh6btu5kkXuFDMEkBabhIXFgBKIMMAXSDmENEgA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4XyA)
