### ISSUE TITLE
When the mode of UnoCSS is set to vue-scoped, errors occur during project startup and packaging, as detailed below.

### ISSUE THREAD

**Issue by umbrella22** [unocss/unocss#4182]
### UnoCSS version

0.63.1

### Describe the bug

1. Fork the official vue-ts demo, add UnoCSS({ mode: 'vue-scoped', }) in vite.config.ts. 
2. Restart and see the error.
------------------------------------
![image](https://github.com/user-attachments/assets/70345c8e-60f2-456d-8aa5-24a23c2ba739)
------------------------------------
![image](https://github.com/user-attachments/assets/dcf87e6b-94ca-4758-9f61-8225f8264b7a)

### Reproduction

https://stackblitz.com/edit/unocss-unocss-zw3jg5?file=src%2Fmain.ts

### System Info

- node: 20.5.0
- npm: 9.8.1
- Browser: Microsoft Edge: 129.0.2792.65
- System: Windows 11 23H2

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
When you use `vue-scoped` mode, you no longer need the `uno.css` virtual file to save the output of UnoCSS. Uno will automatically create a `style` tag in the `sfc` file to output the converted css.

It only works in `global`(By default) and `dist-chunk` modes.
