### ISSUE TITLE
Nuxt(Bun): Unable to start Nuxt with `transformerDirectives`

### ISSUE THREAD

**Issue by 27rogi** [unocss/unocss#4186]
### UnoCSS version

0.63.2

### Describe the bug

Usage of the directive transformer results in ` ERROR  Cannot start nuxt:  ResolveMessage {}` that has no verbose information about issue, but stops Nuxt. Usage of transformer like `VariantGroup` has no such issue. Issue only appears while using Bun with their engine e.g. `bun run --bun dev`.

### Reproduction

Initialize Nuxt repo and add `@unocss/nuxt` module, after that create a UnoCSS config that includes `transformerDirectives()` in transformers. Try to run it with `bun run --bun dev`.

https://codesandbox.io/p/devbox/wonderful-morning-c2s6dz

### System Info

Firefox, Nuxt 3.13.2 (v4 features enabled), Windows, Bun 1.1.30

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by henrikvilhelmberglund** [comment]
Bun issues should be filed here: https://github.com/oven-sh/bun/issues as we can't really fix them here (except telling you not to use the runtime for now)

**Comment by 27rogi** [comment]
Probably it has to do something with this issue oven-sh/bun#13338
