### ISSUE TITLE
typography preset cssExtend rules conditionally for dark mode (`prose-invert`)

### ISSUE THREAD

**Issue by ChrAlpha** [unocss/unocss#4187]
### Clear and concise description of the problem

[cssExtend options](https://unocss.dev/presets/typography#cssextend) for typography preset already could extend or override CSS selectors with CSS declaration block. And it seemed like a alternative method for [element modifiers](https://github.com/tailwindlabs/tailwindcss-typography#element-modifiers) or [customizing CSS](https://github.com/tailwindlabs/tailwindcss-typography?tab=readme-ov-file#customizing-the-css) in Tailwind CSS Typography.

Color style customization usually requires changing according to whether you're in dark mode or not. And it's pretty easy to achieve in Tailwind CSS Typography: 

- element modifiers
  ```html
  <article class="prose prose-a:text-black/60 dark:prose-a:text-white/60">
    {{ markdown }}
  </article>
  ```
- Customizing the CSS
  ```javascript
  /** @type {import('tailwindcss').Config} */
  module.exports = {
    theme: {
      extend: {
        typography: (theme) => ({
          DEFAULT: {
            css: {
              a: { color: rgb(0 0 0 / .6) }
            },
          },
          invert: {
            css: {
              a: { color: rgb(255 255 255 / .6) }
            },
          },
        }),
      },
    },
    plugins: [
      require('@tailwindcss/typography'),
    ],
  }
  ```

However, when I try migrating from Tailwind CSS to UnoCSS, I found this pattern was too hard to achieve by all methods mentioned in [docs](https://unocss.dev/presets/typography) including cssExtend.

### Suggested solution

Adding relative logic into mergeDeep methods used to process cssExtend rules conditionally for dark mode (invert). 

- https://github.com/unocss/unocss/blob/fc0a91e443eba0d5c9e4b054da59f85e4d10650c/packages/preset-typography/src/preflights/index.ts#L85
- https://github.com/unocss/unocss/blob/fc0a91e443eba0d5c9e4b054da59f85e4d10650c/packages/core/src/utils/object.ts#L52

### Alternative

Adding another option that allow users to customize their own paried `--un-prose-*`&`--un-prose-invert-*` variables.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by zyyv** [comment]
I also think that the invert style using the theme color scale is not very appropriate because it is not suitable for everyone.
I will consider optimizing this option, and PR welcome.

**Comment by zyyv** [comment]
I added elements modifier in #4341. As for the other custom theme colors, I will consider the design method and implement it in another PR.
