### ISSUE TITLE
Transition styles missing

### ISSUE THREAD

**Issue by itpropro** [unocss/unocss#4188]
### UnoCSS version

0.63.3

### Describe the bug

Bracket syntax for `transition` doesn't support some arbitrary variants. 
`transition-[width,height]` - works
`transition-[display]` - doesn't work
`transition-[display,overlay]` - doesn't work

`display` and `overlay` are important to be able to transition some of the newer html components like popover.

### Reproduction

https://unocss.dev/play/?version=0.63.3&html=DwEwlgbgBAFgtAMwK4BsVQC4FMAeG4DGWAdtgE5QIq5QDOW1B%2BxA9sVlAIZoBcGZnYrTAYwbOABYADFIB8AKChRQkKAFtOCpUpXQCKTrVoBeAETY8cAKw50CAO4BGGaa3alAVVYBhAMq-FbWAAenAINx0wqH1DE3MBIRExYjgAbXswEAwYABoWAAdOAhEATwBdV0D3AHUWMgBrWirlUMgI5SiYozN%2BQWFRcVTwWnyDcsr3JQARFixaYgByDCh7OvqoAAp2LBAdyjqoXE41UY4EA-yClggsCkEwDQHiAEpmkLD23WiDbvi%2BpMG11uYwq7Wms3mSxWa02212IH2FCOJ2oiKgl0uNzuxAenCer3c7zagSJ4XkpNkQA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6smVUdAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k7pVGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWsULlQKmozkggA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmANCBCXAA5LwCWAbifocSQL5A

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by itpropro** [comment]
> @itpropro That's because your transition properties are not in [the default theme's transition properties](https://github.com/unocss/unocss/blob/c9d2e0155b7d7503355832676ce1f7cf713ee754/packages/preset-mini/src/_theme/transition.ts#L11-L21) and [the preset css properties](https://github.com/unocss/unocss/blob/c9d2e0155b7d7503355832676ce1f7cf713ee754/packages/preset-mini/src/_utils/handlers/handlers.ts#L6-L68), so it doesn't take effect. You can add the missing properties in the theme.
> 
> Refer to [Playground](https://unocss.dev/play/?version=0.63.3&html=DwEwlgbgBAFgtAMwK4BsVQC4FMAeG4DGWAdtgE5QIq5QDOW1B%2BxA9sVlAIZoBcGZnYrTAYwbOABYADFIB8AKChRQkKAFtOCpUpXQCKTrVoBeAETY8cAKw50CAO4BGGaa3alAVVYBhAMq-FbWAAenAINx0wqH1DE3MBIRExYjgAbXswEAwYABoWAAdOAhEATwBdV0D3AHUWMgBrWirlUMgI5SiYozN%2BQWFRcVTwWnyDcsr3JQARFixaYgByDCh7OvqoAAp2LBAdyjqoXE41UY4EA-yClggsCkEwDQHiAEpmkLD23WiDbvi%2BpMG11uYwq7Wms3mSxWa02212IH2FCOJ2oiKgl0uNzuxAenCer3c7zabxgFGCn06PzivUST0ILBOLHoE0mNP6yXpjPob1a4UCRL5AtkQA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyVFDO9ABccADaVKhhehJcdDA6ALSBThh65IhwUk7QoXq0aHpwagC6smVUdAAW0DCxMHSh-qj6sfFJ1bX1enkwVjCJTqRwfZYD0Pa4pBhwNQBuGFDBowN99k7pVGqyIgqN4ZFyokoqPgCUssLyjCxsnDx8-OeXRwqS0n6HqHQS6xihAEYAHQAJheqAkaFweSqrDAjQA9Aj6CAgdUEZsWsULlQKqgYFUMCB-ohDmxJnRgLxiAAFbRgRYwfjBZpYtDAOhgJz2Zn6dmc7n8TFYuAQBZQQV5MWLQXCrFScAQBh5flcnnkaUSnlmLFqLZINRnJBAA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmANCBCXAA5LwCWAbifocSQL5A)
> 
> ```diff
> + theme:  {
> +     transitionProperty: {
> +       display: 'display',
> +       overlay: 'overlay',
> +       compose: 'display,overlay'
> +    }
> + }
> ```

Thanks for that @zyyv, that's how I solved it, but the issue was more about adding them to the default set or change the way that arbitrary variants work (directly transforming it to css). 
The reason would be that it is not that well documented and it is not the behavior a user would expect from an arbitrary variant, which should basically handle everything you throw at it independently of the content.
I just want to make it as easy as possible for users coming from Tailwind for example to use it, as this would behavior that works in Tailwind without config changes.

**Comment by zyyv** [comment]
I want to explain why the arbitrary value here is not applied

When we parse arbitrary values, we consider that we may reuse the previous combined property value (such as this 
[Playground](https://unocss.dev/play/?version=0.63.3&html=DwEwlgbgBAxgNgQwM5ILwCIAuBTAHpgWgFZc4pMAnBAOyTEzAHtqCBtcJAB0QE8AaGIziMKSALroAfAFVqjAMIBlRcAD04CJIBQoSLEQoMOfMVLkqtekxatGnBDHr9BAW06Mk2CTLlKV6yG0gA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyYfKMdABccADaVAGiSio%2BAJSyALqyMAAWGCAYof6ocGz2uHTAvMQACtpgGLD8wTm56MB0YE72Nfpojc2terL1EABuVS1tegND3b25UuAQDKF6HU3D5GNQw2b1alRbanFIQA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmANCBCXAA5LwCWAbifocSQL5A)), or perform strict property verification on the value.

Our built-in properties cover most of the high-frequency attributes. The attribute reported in this issue is not in the attribute list, so I will try to complete some properties in it.

**Comment by itpropro** [comment]
> I want to explain why the arbitrary value here is not applied
> 
> When we parse arbitrary values, we consider that we may reuse the previous combined property value (such as this [Playground](https://unocss.dev/play/?version=0.63.3&html=DwEwlgbgBAxgNgQwM5ILwCIAuBTAHpgWgFZc4pMAnBAOyTEzAHtqCBtcJAB0QE8AaGIziMKSALroAfAFVqjAMIBlRcAD04CJIBQoSLEQoMOfMVLkqtekxatGnBDHr9BAW06Mk2CTLlKV6yG0gA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcESgF84WKBBBwA5FxUS6dPUiQYAHpFjpsAQy4AbeJhz4iJYKQAUyYfKMdABccADaVAGiSio%2BAJSyALqyMAAWGCAYof6ocGz2uHTAvMQACtpgGLD8wTm56MB0YE72Nfpojc2terL1EABuVS1tegND3b25UuAQDKF6HU3D5GNQw2b1alRbanFIQA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmANCBCXAA5LwCWAbifocSQL5A)), or perform strict property verification on the value.
> 
> Our built-in properties cover most of the high-frequency attributes. The attribute reported in this issue is not in the attribute list, so I will try to complete some properties in it.

Thanks for explaining! Does this mean you would add the properties to the attribute list? 
I can also create a PR for that I just wanted to know what you think the best way would be to get the same behavior as in Tailwind.

**Comment by henrikvilhelmberglund** [comment]
> Thanks for explaining! Does this mean you would add the properties to the attribute list? I can also create a PR for that I just wanted to know what you think the best way would be to get the same behavior as in Tailwind.

Yes, in here: https://github.com/unocss/unocss/blob/main/packages/preset-mini/src/_utils/handlers/handlers.ts

**Comment by itpropro** [comment]
> > Thanks for explaining! Does this mean you would add the properties to the attribute list? I can also create a PR for that I just wanted to know what you think the best way would be to get the same behavior as in Tailwind.
> 
> Yes, in here: https://github.com/unocss/unocss/blob/main/packages/preset-mini/src/_utils/handlers/handlers.ts

Thanks for the reference, I know that file, like I said, I just wanted to know if extending this would be the best way or if there would be a better alternative in regards to the bracket syntax in general.

**Comment by henrikvilhelmberglund** [comment]
Right now you can't do something like `transition-[frog]` and get `transition-property: frog`, values are only referenced from your theme. Arbitrary transition styles imo doesn't make too much sense because you can't really create a transition style, they are what they are.

But, `transition-display` and `transition-display,overlay` should work, these need to be added to the file I mentioned.
