### ISSUE TITLE
[Attributify] Regression in UnoCSS v0.63.3 - Media Queries Not Being Generated

### ISSUE THREAD

**Issue by onmax** [unocss/unocss#4189]
### UnoCSS version

v0.63.3

### Describe the bug

There seems to be a regression in UnoCSS version 0.63.3. Using the same configuration and HTML code that worked correctly in version 0.63.2, I am now experiencing a problem where media queries are not being generated when using Attributify.

### Reproduction

In [v0.63.2 works](https://uno.antfu.me/play/?version=0.63.2&html=DwEwlgbgBADgHgXgEQGYBMUC2IBcA2AFijgBscB2NJAPgCgAJAUxJIHsoB1VgJxJFuAB6cBGpA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCCMMUwARgK4zDoCeZF1tAKpYIcAL5x0UCCDgByNiIDGVKnIBQ61AA9IsFBgCGbADbw0mHPkLAiACgTq45SjRhUAXHADaT5y4EYYQg7AEoSP2d%2BNwYmVg4ubjCI5wBdCLFQ9SA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgzgLgTglgxhEAuaBXApgXyA)

In [v0.63.3](https://uno.antfu.me/play/?version=0.63.3&html=DwEwlgbgBADgHgXgEQGYBMUC2IBcA2AFijgBscB2NJAPgCgAJAUxJIHsoB1VgJxJFuAB6cBGpA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCCMMUwARgK4zDoCeZF1tAKpYIcAL5x0UCCDgByNiIDGVKnIBQ61AA9IsFBgCGbADbw0mHPkLAiACgTq45SjRhUAXHADaT5y4EYYQg7AEoSP2d%2BNwYmVg4ubjCI5wBdCLFQ9SA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgzgLgTglgxhEAuaBXApgXyA) does NOT work

### System Info

N/A

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by onmax** [comment]
I guess is related to https://github.com/unocss/unocss/commit/c9d2e0155b7d7503355832676ce1f7cf713ee754

**Comment by antfu** [comment]
I reverted https://github.com/unocss/unocss/commit/c9d2e0155b7d7503355832676ce1f7cf713ee754, it's indeed a bit ambiguous, probably better to not allow `:` as an operator modifier in attributify
