### ISSUE TITLE
bug(postcss): node_modules are not resolved

### ISSUE THREAD

**Issue by j0nl1** [unocss/unocss#4191]
### UnoCSS version

0.63.3

### Describe the bug

I notice that the postcss plugin exclude all node_modules, while I see this as a good practice for a default behavior, there are cases where a node_module package should be included.

In my case I have a library with shared components, and it build the library using tsup. The expected behavior for me, is to use the components and resolve their classes.

I found this impossible to achieve for two reasons:
1. The postcss plugin always exclude node_modules (https://github.com/unocss/unocss/blob/main/packages/postcss/src/esm.ts#L111). 

2. Tinyglobby has a bug where it excludes node_modules folder. (https://github.com/SuperchupuDev/tinyglobby/issues/58)

In order to achieve this would be necessary to replace tinyglobby for fast-glob and not ignore node_modules when some of the glob patterns include node_modules.Additionally we could show a warn message when node_modules will be provided as pattern.

### Reproduction

https://stackblitz.com/edit/tinyglobby-behavior?file=glob.ts&view=editor

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
This is indeed a problem, it will make the pipeline invalid, maybe it is a good idea to switch back to fast-glob before tinyglobby is willing to support it.

**Comment by SuperchupuDev** [comment]
FYI i've just released `tinyglobby` 0.2.10 which fixed symlinks resolution, which should fix this issue
