### ISSUE TITLE
number only + variant + `Attributify mode`  is broken on 0.63.3

### ISSUE THREAD

**Issue by ryoppippi** [unocss/unocss#4193]
### UnoCSS version

0.63.3

### Describe the bug

`dark:` with `Attributify mode`  is broken since v0.63.3.

### Reproduction

uno.config.ts
```ts
import { 
  defineConfig, 
  presetUno,
  presetAttributify,
  transformerDirectives,
} from "unocss";
import { defu } from "defu";

export default defineConfig({
  presets: [presetUno(),presetAttributify()],
  transformers: [transformerDirectives()],
  extendTheme: _theme=> defu({
    colors: {
      text: {
	    100: '#FF6B6B',
        200: '#ffffff',
      }
    }
  },_theme)
});
```

html
```html
<p
  text-text='100 dark:200'
>
  hello wold
</p>

<p
  text='text-100 dark:text-200'
>
  hello wold
</p>
```

So, in dark mode, both `p` tag should be white.

v0.63.2
https://unocss.dev/play/?version=0.63.2&html=DwBwUABBAuCmAe0C0dEF4DkBGADDiAJgIYBOA1gFwBMeGYAfJBABawA2bA9hAO6dsEwwAPQhGwAIRIkEQImEvTuVgEIAVwB2AS2hsIANxwA6AGwBmQ1QA0EAEaroEdZwcGT50xGmMwQ8FFTQmAFIuPjE5BTBNDh0jFCsHNx8AkKi4lIyfOQAzhCc6vpGZoYeXmBAA&config=JYWwDg9gTgLgBAbzgKDnAJgUwGbAHaYDCEeuA5gDQpphSYDOmMAqnhBanLQ0wIIwwowAEYBXGMGwBPDmkEBDPPWzQQmKABFgdAMYSAbgw4BfONigQQcAESi2O+vWsBuZKEixEGHKLinzljZY2KIuyMiYAB4e8MHyogA2sTj4RCTkABQInNyMMPQAXHAA2rlMrBAZAJQUZTD8giLiklLVALqycApKKlBqUIUl3cqq6lq6BgztnVEwmHjoACoAFphqRQD6MKtqALwAfN4hWZxoOhAJ0IPZaLdds0XZAJB3AIwADO9FAOQAxABi-wAbAAhUHfTp3NAAJk+P1+2ERSIhp1uxlR6LQxgoWx2mCqyGMVVcQA&css=FwJw9mAuAEDeBQ1oFpkDMAmyDGYA2YIw0A5iAKbkB2A3PAL7xA&options=N4IgLgTghgdgzgMwPYQLYGECucxIwZXxAC5JMBTAXyA
![SCR-20241007-qwcm](https://github.com/user-attachments/assets/e57b787d-8a7c-498d-b117-e483cba05b56)

v0.63.3
https://unocss.dev/play/?version=0.63.3&html=DwBwUABBAuCmAe0C0dEF4DkBGADDiAJgIYBOA1gFwBMeGYAfJBABawA2bA9hAO6dsEwwAPQhGwAIRIkEQImEvTuVgEIAVwB2AS2hsIANxwA6AGwBmQ1QA0EAEaroEdZwcGT50xGmMwQ8FFTQmAFIuPjE5BTBNDh0jFCsHNx8AkKi4lIyfOQAzhCc6vpGZoYeXmBAA&config=JYWwDg9gTgLgBAbzgKDnAJgUwGbAHaYDCEeuA5gDQpphSYDOmMAqnhBanLQ0wIIwwowAEYBXGMGwBPDmkEBDPPWzQQmKABFgdAMYSAbgw4BfONigQQcAESi2O+vWsBuZKEixEGHKLinzljZY2KIuyMiYAB4e8MHyogA2sTj4RCTkABQInNyMMPQAXHAA2rlMrBAZAJQUZTD8giLiklLVALqycApKKlBqUIUl3cqq6lq6BgztnVEwmHjoACoAFphqRQD6MKtqALwAfN4hWZxoOhAJ0IPZaLdds0XZAJB3AIwADO9FAOQAxABi-wAbAAhUHfTp3NAAJk+P1+2ERSIhp1uxlR6LQxgoWx2mCqyGMVVcQA&css=FwJw9mAuAEDeBQ1oFpkDMAmyDGYA2YIw0A5iAKbkB2A3PAL7xA&options=N4IgLgTghgdgzgMwPYQLYGECucxIwZXxAC5JMBTAXyA

![SCR-20241007-qwal](https://github.com/user-attachments/assets/a7d99150-7f9a-4a86-b9e9-9d296f9da7fe)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ryoppippi** [comment]
I found another issue

```
	grid-cols='1 md:3'
```

works fine at [0.63.2](https://unocss.dev/play/?version=0.63.2&html=DwEwlgbgUABDDmAnMJYOSAtAYwPYBsBnAXgHIBGGfeALgGZSoA+NYAByZgAsBTffXDGAB6Dqw7c+AoaJZx2nXv0EixI8BCZA&config=JYWwDg9gTgLgBAbzgKDnAJgUwGbAHaYDCEeuA5gDQpphSYDOmMAqnhBanLQ0wIIwwowAEYBXGMGwBPDmkEBDPPWzQQmKABFgdAMYSAbgw4BfONigQQcAESi2O+vWsBuZKEixEGHKLinzljZY2KIuyMiYAB4e8MHyogA2sTj4RCTkABQInNyMMPQAXHAA2rlMrBAZAJQUZTD8giLiklLVALqycApKKlBqUIUl3cqq6lq6BgztnVEwmHjoACoAFphqRQD6MKtqALwAfN4hWZxoOhAJ0IPZaLdds0XZAJB3AIwADO9FAOQAxABi-wAbAAhUHfTp3NAAJk+P1+2ERSIhp1uxlR6LQxgoWx2mCqyGMVVcQA&css=FwJw9mAuAEDeBQ1oFpkDMAmyDGYA2YIw0A5iAKbkB2A3PAL7xA&options=N4IgLgTghgdgzgMwPYQLYGECucxIwZXxAC5JMBTAXyA), but not [0.63.3](https://unocss.dev/play/?version=0.63.3&html=DwEwlgbgUABDDmAnMJYOSAtAYwPYBsBnAXgHIBGGfeALgGZSoA+NYAByZgAsBTffXDGAB6Dqw7c+AoaJZx2nXv0EixI8BCZA&config=JYWwDg9gTgLgBAbzgKDnAJgUwGbAHaYDCEeuA5gDQpphSYDOmMAqnhBanLQ0wIIwwowAEYBXGMGwBPDmkEBDPPWzQQmKABFgdAMYSAbgw4BfONigQQcAESi2O+vWsBuZKEixEGHKLinzljZY2KIuyMiYAB4e8MHyogA2sTj4RCTkABQInNyMMPQAXHAA2rlMrBAZAJQUZTD8giLiklLVALqycApKKlBqUIUl3cqq6lq6BgztnVEwmHjoACoAFphqRQD6MKtqALwAfN4hWZxoOhAJ0IPZaLdds0XZAJB3AIwADO9FAOQAxABi-wAbAAhUHfTp3NAAJk+P1+2ERSIhp1uxlR6LQxgoWx2mCqyGMVVcQA&css=FwJw9mAuAEDeBQ1oFpkDMAmyDGYA2YIw0A5iAKbkB2A3PAL7xA&options=N4IgLgTghgdgzgMwPYQLYGECucxIwZXxAC5JMBTAXyA).

**Comment by onmax** [comment]
see #4189

**Comment by antfu** [comment]
Let's keep track on https://github.com/unocss/unocss/issues/4189 then.

**Comment by ryoppippi** [comment]
Works fine on the latest version! Thanks
