### ISSUE TITLE
when use mergeConfigs generate -> [unocss] `content.plain` option is renamed to `content.inline`. 

### ISSUE THREAD

**Issue by adrian-ub** [unocss/unocss#4194]
### UnoCSS version

0.63.4

### Describe the bug

when use mergeConfigs generate warn: [unocss] `content.plain` option is renamed to `content.inline`. 

and this option is not being used

![image](https://github.com/user-attachments/assets/362f50b4-0997-4432-a280-2224e2d0f376)

### Reproduction

repo: https://github.com/adrian-ub/astro-vitesse/tree/cbc94e8da2faed2827476754d5ead31bd10b6b30

mergeConfigs is used in https://github.com/adrian-ub/astro-vitesse/blob/cbc94e8da2faed2827476754d5ead31bd10b6b30/src/theme.ts

and this function is used in https://github.com/adrian-ub/astro-vitesse/blob/cbc94e8da2faed2827476754d5ead31bd10b6b30/docs/uno.config.ts

when running `nr docs:build` the warn is displayed and in deploy it fails

![image](https://github.com/user-attachments/assets/05d66b07-00e1-487a-bcb5-c80d3679e0de)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by adrian-ub** [comment]
I think there should be some extra validation on this line, however I am not familiar with the project.

https://github.com/unocss/unocss/blob/main/packages/core/src/config.ts#L89

**Comment by zyyv** [comment]
I'll help fix this later.

**Comment by zyyv** [comment]
@adrian-ub I didn't reproduce this error, I checked your configuration again and I didn't find any deprecated options
<img width="942" alt="image" src="https://github.com/user-attachments/assets/fee8fab2-1ea3-452e-9fd0-ced880c826f4">

Or some other error, in my opinion it does not belong to unocss. Please check again.

**Comment by zyyv** [comment]
> 我认为这行应该有一些额外的验证，但我不熟悉这个项目。
> 
> https://github.com/unocss/unocss/blob/main/packages/core/src/config.ts#L89
> 
> ```ts
> const plain = uniq(optionsArray.flatMap(options => options.plain ?? []))
> 
> return {
>     filesystem: uniq(optionsArray.flatMap(options => options.filesystem ?? [])),
>     inline: uniq(optionsArray.flatMap(options => options.inline ?? [])),
>     plain: plain.length === 0 ? undefined : plain,
>     pipeline: pipelineDisabled
>       ? false
>       : {
>           include: uniq(mergeFilterPatterns(...pipelineIncludes)),
>           exclude: uniq(mergeFilterPatterns(...pipelineExcludes)),
>         },
>   }
> ```

This is the merge configuration.

**Comment by adrian-ub** [comment]
@zyyv  repro two

https://stackblitz.com/edit/github-wtgzc6?file=docs%2Fpackage.json

![image](https://github.com/user-attachments/assets/1e873ea1-010a-4daa-b9d5-971ebf65a476)

**Comment by adrian-ub** [comment]
![image](https://github.com/user-attachments/assets/4e1c2c56-4a10-44a7-95c6-cd3a3f5e8b42)


![image](https://github.com/user-attachments/assets/f9f3010c-f502-46db-8c13-c4ef40cf6535)

**Comment by zyyv** [comment]
Thanks, I saw this error, I'll fix it quickly. @adrian-ub
