### ISSUE TITLE
register vscode extension when separate config file doesn't exists

### ISSUE THREAD

**Issue by clouds56** [unocss/unocss#4199]
### Clear and concise description of the problem

Now vscode extension only activated when `uno.config.ts` exists
https://github.com/unocss/unocss/blob/1ef2366305ab721447ed702c2f70a6cf83c84302/packages/vscode/src/index.ts#L137

when I embed config in vite, the extension won't work
```ts
import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import vueDevTools from 'vite-plugin-vue-devtools'
import UnoCSS from 'unocss/vite'
import { presetUno } from 'unocss'

// https://vitejs.dev/config/
export default defineConfig(async () => ({
  plugins: [
    vue(),
    vueDevTools(),
    UnoCSS({ presets: [presetUno()]}),
  ],
  // ...
}))
```

### Suggested solution

1. search up `package.json`, when unocss in dependencies, activate the vscode extension as well.
2. add config in .vscode that register root in workspace

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [ ] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Simon-He95** [comment]
We prefer to use `uno.config` to configure
