### ISSUE TITLE
theme breakpoints 使用Css变量后无效

### ISSUE THREAD

**Issue by thikiiii** [unocss/unocss#4202]
### UnoCSS version

^0.62.4

### Describe the bug

[复现连接](https://stackblitz.com/edit/vitejs-vite-xiwsyq?file=src%2FApp.vue)
breakpoints 使用 Css变量无效

### Reproduction

```css
:root {
  --breakpoints-xs: 567px;
  --breakpoints-ms: 800px;
  --breakpoints-md: 1000px;
  --breakpoints-lg: 1200px;
  --breakpoints-xl: 1500px;
}
```
```js
// uno.config.ts
import { defineConfig, presetUno } from 'unocss';

export default defineConfig({
  content: {
    pipeline: {
      exclude: ['node_modules', 'dist'],
    },
  },
  presets: [presetUno()],
  theme: {
    breakpoints: {
      xs: 'var(--breakpoints-xs)',
      sm: 'var(--breakpoints-sm)',
      md: 'var(--breakpoints-md)',
      lg: 'var(--breakpoints-lg)',
      // xs: '567px',
      // sm: '800px',
      // md: '1200px',
      // lg: '1500px',
    },
  },
});
```
```vue
<script setup></script>

<template>
  <div class="xs:bg-red sm:bg-black md:bg-blue">test</div>
</template>

<style scoped></style>

```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by henrikvilhelmberglund** [comment]
` var()` doesn't work inside media queries in CSS at all so you will probably have to find some other method.

**Comment by Simon-He95** [comment]
<img width="931" alt="image" src="https://github.com/user-attachments/assets/bed81b37-65fb-4e33-97f8-0a7871a20515">
Indeed, @media does not support the use of CSS variables
