### ISSUE TITLE
`presetIcons` ignored the file names of icons starting with uppercase letters

### ISSUE THREAD

**Issue by s3xysteak** [unocss/unocss#4206]
### UnoCSS version

0.63.4

### Describe the bug

The file names of icons starting with uppercase letters do not be rendered, which are just ignored (not in `/__unocss`).

### Reproduction

https://github.com/s3xysteak/repro-unocss-icons.git

Please refer to `src/App.vue`

There are two icons in the repo: `Uno.svg` and `uno-sm.svg`.

- `i-my-uno` works.
- `i-my-Uno` does not work.
- `i-my-uno-sm` works.

### System Info

  System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i3-10100 CPU @ 3.60GHz
    Memory: 5.21 GB / 15.90 GB

  Binaries:
    Node: 20.17.0 - ~\AppData\Local\fnm_multishells\26504_1729061004255\node.EXE
    npm: 10.8.2 - ~\AppData\Local\fnm_multishells\26504_1729061004255\npm.CMD
    pnpm: 9.11.0 - ~\AppData\Local\pnpm\pnpm.CMD

  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.4355

  npmPackages:
    unocss: ^0.63.3 => 0.63.3

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by s3xysteak** [comment]
Btw if this is an expected behavior, I think it may need to be improved. It seems strange that you have to pass `foo` to use `Foo.svg`. At least it should be mentioned in the document :flushed:.

**Comment by s3xysteak** [comment]
https://github.com/unocss/unocss/blob/main/packages/preset-icons/src/core.ts#L83

`/^([a-z0-9:_-]+)(?:\?(mask|bg|auto))?$/`

The regex does not match the uppercase letter. I am not sure is that a expected behavior.

**Comment by zyyv** [comment]
@s3xysteak I think this is an expected behavior. Related https://github.com/unocss/unocss/pull/4149

**Comment by s3xysteak** [comment]
Or at least we metion it [in the document](https://unocss.dev/presets/icons#configuring-collections-and-icons-resolvers) to avoid misunderstanding.

**Comment by userquin** [comment]
> /cc @userquin Should we support uppercase syntax?

I guess we can, we only need to change the regex: https://github.com/unocss/unocss/blob/main/packages/preset-icons/src/core.ts#L83C9-L83C49
