### ISSUE TITLE
fix(extractor-md): attributify mode preset is not recognized in markdown

### ISSUE THREAD

**Issue by phojie** [unocss/unocss#4210]
### UnoCSS version

latest

### Describe the bug

Hello, I am trying to create a `nuxt-content` template similar to docus but with [Unaui.com](unaui.com). 

The problem is that, it does not recognize preset-attributify in the markdown which `una-ui` fully relies on.

eg:

✅ class="text-lime" - this will work

❌ text="lime" - and this will not work

I appreciate any kind of help. Thanks!

### Reproduction

https://stackblitz.com/github/una-ui/content?file=README.md

ref: content/index.md

code:

![Screenshot 2024-10-18 at 12 05 04 PM](https://github.com/user-attachments/assets/b6bcc228-f8cb-445e-ad8b-c23bedbb718f)

output:

![Screenshot 2024-10-18 at 12 06 14 PM](https://github.com/user-attachments/assets/c7a8fe4b-92b5-412e-ba8d-677774a8ba87)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
<img width="202" alt="image" src="https://github.com/user-attachments/assets/8b48f2ab-8d92-4c8a-a361-36d6d9143c82">

`class mode` also does not work

**Comment by phojie** [comment]
@Simon-He95  Sorry, forgot to add `" "` in class mode, it should be working by now.

![Screenshot 2024-10-18 at 8 43 32 PM](https://github.com/user-attachments/assets/8c5afa16-39cc-4930-bf19-e6988c8dd7c4)

**Comment by zyyv** [comment]
@phojie Because your usage does not satisfy the extraction mechanism of uno attributify mode, you can simulate a fragment code to make uno extract correctly.
<img width="1465" alt="image" src="https://github.com/user-attachments/assets/97ecadf1-3ace-4378-b715-fd5928682fb4">

**Comment by phojie** [comment]
@zyyv, I understand this might be considered "not planned for now," but I believe it's essential for `Unocss MD`, as attributify is one of the core advantages of Unocss. Please don't close this type of PR immediately. I'm contributing to help the Unocss ecosystem grow. This PR is not about seeking an instant solution, but about coordinating and raising awareness for everyone using this package.

Rest assured, I'm also working on finding a solution. I'm not just waiting for others or any core member to fix it. 😊

**Comment by phojie** [comment]
I am wondering about @antfu opinion regarding this Issue though
