### ISSUE TITLE
vscode extension cannot highlight class names within single quotation marks

### ISSUE THREAD

**Issue by ocavue** [unocss/unocss#4217]
### UnoCSS version

0.63.4

### Describe the bug

If I have a single quotation mark in the comment, the vscode extension cannot highlight following class names with two single quotation marks

Giving the following code:

```
// A comment with a single quotation mark: '

const a = "sr-only box-border m-1";
const b = 'sr-only box-border m-1';
const c = "sr-only box-border m-1";
const d = 'sr-only box-border m-1';
```

You can see that lines `b` and `d` are not highlighted.

<img width="365" alt="image" src="https://github.com/user-attachments/assets/57fcf5e7-0211-4aea-a928-3d36a8f57dcf">

### Reproduction

1. Clone https://github.com/issueset/unocss-vscode-issue
2. Open `a.ts` with vscode.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
The symbol is extracted in the wrong position, maybe we can just delete the commented code in vscode. 
/cc @Simon-He95

**Comment by zyyv** [comment]
Closed due to https://github.com/unocss/unocss/pull/4325

**Comment by ocavue** [comment]
Thanks for the fix. I have a simple question for #4325. Do I have to use `@unocss-skip-start` and `@unocss-skip-end` to make the example work? 

People might insert single quotation mark into their comment without knowing that it will break UnoCSS extension (for example, adding a like like <https://en.wikipedia.org/wiki/The_Power_of_the_Powerless#Havel's_greengrocer>).

**Comment by Simon-He95** [comment]
> Thanks for the fix. I have a simple question for #4325. Do I have to use `@unocss-skip-start` and `@unocss-skip-end` to make the example work?
> 
> People might insert single quotation mark into their comment without knowing that it will break UnoCSS extension (for example, adding a link like https://en.wikipedia.org/wiki/The_Power_of_the_Powerless#Havel's_greengrocer).

You can use a hook to remove comment before uno parser in runtime

**Comment by ocavue** [comment]
It's still weird to me that I need to write some custom code (`@unocss-skip-start` or a hook) to make UnoCSS work, as I'm not writing any unusual code in my in my humble opinion.
