### ISSUE TITLE
Easy way to set an icon from `@unocss/preset-icons` as a `::marker`'s `content`

### ISSUE THREAD

**Issue by samualtnorman** [unocss/unocss#4219]
### Clear and concise description of the problem

Currently there is no easy way to set the `content` of a `::marker` to an icon from `@unocss/preset-icons`.

### Suggested solution

Maybe something like `?marker` to go alongside `?bg` and `?mask`. 

### Alternative

Maybe some special class that is basically equivalent to `marker:content-[var(--un-icon)]` that is used alongside `marker:i-some-set:some-icon`.

### Additional context

I'm trying to override the browser default icon for my `<details>`' `<summary>`'s `::marker` with a nice icon provided by `@unocss/preset-icons`.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by zyyv** [comment]
@samualtnorman  I have simply implemented the syntax of marker icon #4222 , but it is not a good proposal. In order to be compatible with more syntax tags in the future, such as `marker`, we need to find a good proposal.
Suggestions are welcome.

**Comment by samualtnorman** [comment]
> @samualtnorman  I have simply implemented the syntax of marker icon #4222 , but it is not a good proposal. In order to be compatible with more syntax tags in the future, such as `marker`, we need to find a good proposal.
> Suggestions are welcome.

I gave an alternative suggestion if you're interested in that

**Comment by zyyv** [comment]
> I gave an alternative suggestion if you're interested in that

I fixed the `marker` syntax error in #4221, so it will support `marker:i-some-set:some-icon`. No changes required.
