### ISSUE TITLE
Using transformerVariantGroup causes replace to fail

### ISSUE THREAD

**Issue by ketao4869** [unocss/unocss#4224]
### UnoCSS version

0.63.6

### Describe the bug

开启 `transformerVariantGroup` 导致执行后 `replace`异常
```ts
// uno.config.ts

import {
    defineConfig,
    transformerVariantGroup,
  } from 'unocss'

export default defineConfig({
  transformers: [
    transformerVariantGroup(), // 注释掉就正常
  ],
})
```

```ts

function camelCase(word: string): string {
  return word.replace(/-(\w)/g, (_, c) => {
    console.log(c) // 应该是:b    实际上：7

    return c.toUpperCase()
  })
}
console.log(camelCase('message-box'));
```

### Reproduction

![image](https://github.com/user-attachments/assets/1cd276ea-6581-457a-9d5a-3e22615c25c3)

https://stackblitz.com/edit/vitejs-vite-f7ngdy?file=src%2FApp.vue

### System Info

```json
{
  "dependencies": {
    "vue": "^3.5.12"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^5.1.4",
    "typescript": "~5.6.2",
    "unocss": "^0.63.6",
    "vite": "^5.4.9",
    "vue-tsc": "^2.1.6"
  }
}
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ketao4869** [comment]
我还有一个问题，我的`uniapp-cli`项目中使用了`unocss`，
在使用第三方组件库[wot-design-uni](https://github.com/Moonofweisheng/wot-design-uni)出现错误

```vue
    <wd-config-provider>
      <wd-button>主要按钮</wd-button>
      <wd-button type="success">
        成功按钮
      </wd-button>
      <wd-button type="info">
        信息按钮
      </wd-button>
      <wd-button type="warning">
        警告按钮
      </wd-button>
      <wd-button type="error">
        危险按钮
      </wd-button>
      <slot />
      <wd-toast />
      <wd-message-box />
    </wd-config-provider>
```

第一次运行是正常的，但是`Ctrl + C`关闭，重新启动项目，就会出现报错（它修改了第三方组件库中的内容）：
![image](https://github.com/user-attachments/assets/f5c1dbb9-038d-4c17-a434-28b8b4cda644)
这是组件库源代码：
![image](https://github.com/user-attachments/assets/54f2776f-3f47-414d-b0a8-080ee6a966a8)


解决办法是删除`node_modules/.vite`缓存，重新运行就正常

**Comment by zyyv** [comment]
@ketao4869 `transformer` will process `node_modules` files by default. You can filter by [content](https://unocss.dev/config/#pipeline)

**Comment by ketao4869** [comment]
Thank you. Is this also the problem in the last comment area

**Comment by zyyv** [comment]
@ketao4869 You can temporarily solve the problem by filtering `node_module` by `content`. I will release this change in the next version. Please wait for a while. ❤️
