### ISSUE TITLE
Container queries don't work with custom container sizes

### ISSUE THREAD

**Issue by thraizz** [unocss/unocss#4229]
### UnoCSS version

0.63.6

### Describe the bug

Custom container sizes, defined by a config like:
```ts
import { defineConfig, presetWind } from 'unocss'

export default defineConfig({
  theme: {
    containers: {
      tablet: '352px',
      desktop: '768px',
    },
  },
  presets: [presetWind()],
})
```
do not work while it works in tailwind, see https://github.com/tailwindlabs/tailwindcss-container-queries?tab=readme-ov-file#configuration. Their custom values are ignored when applying these sizes with e.g. `bg-blue @tablet/mainGrid:bg-red @desktop/mainGrid:bg-green`.

### Reproduction

This uno playground does not work: [https://unocss.dev/play](https://unocss.dev/play/#html=DwEwlgbgBAxgNgQwM5ILwCIACMD2A7AFwTDwFMAnAegFti8BxcsEdAPgCgopRJZEUMAcyYgAtIgCeOAK4Eow5lASyco8jgDuSUcoI55I0QDM4mtWZCk8SUm05du4aPGRp0AI0Gj3caaSiYRD6kBDR0jMwAXJ5qpCABlkgA1noADmEkESDRXsKkVmwAQjgAHlAAjMCUThwOjrwuAh5ePn4BQXAhGQwiObHxmIkpOOm0mb0xeQWsxWUATFU19lw8zvxuMa3%2BgQjBoWM9UTHkcQmkyWndWX1TeEWlUADMi5C1Dqt8rhibvtsdXQdrsdToNzsNRuEJrkTtNZlAACwvCBvFZOT5NH5tHZ7K5Q-pnC4jXFHaH5O4zB4AViRKPqay%2BzW8v3au06%2B0hJPxoMJEPGnNu9zKADYacs6eiNi1mdi2cTssCBkNLoC8QKKWUAOyiuofRqSplY-7svnyrwnRVg5Uc02iNVwgAc2u41Ve7FFQA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCCMMUwARgK4zDoCeZF1tAOrZkcAL5x0UCCDgByNlggBjKlTkAoDagAekWCgwBDNgBt4aTDnyFgRABQINcODAAWqEKgBciZy7hlAhgjbFQoKl8nAICAeli4AHFmUQAhSiMAa0hsGCo4ewBmAFYAJjAdOGB8gBZAiFM2ECwqMgB2ADYADgqq-K76xuaqAEp-GJCWU1pfORLynTkScYC0KkyYCDBZzp7F5ZixA-Fj-ho83wBtM6ERexGAXWWxMaA&css=HQcwTglgJgtANgQwJ4HsCuAXABAbwFBZbjQwYCmAtgA6LkwDGKcaFAdgM4BcWYZVZCDAAoATABosFCKwoIAHkIDsIqnIkBGAGZgAlDoDcBIgird1ANlWGjAAUasMCaWTCSnrAOKQoWIVNYwAO7QGAAW3ADMAKwqcjq4RoQgJmaWclgAhBDUKGCODoaESd6klDSCZAxMLBzcvPyCQgAsEv6yCsqqGtp6hVgAvni29o7OrrLSXtC%2B-kEh4ViK5gAcqvH4RUQl5NS0lYzMbFw8fALCy63S7Uqx3boGicamWCJNqpnZVLn5GH2Dg0A&options=N4XyA)

This same config/html/css works in tailwind: https://play.tailwindcss.com/0BvpaAzgYT

### System Info

-

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by thraizz** [comment]
Inspecting the generated output CSS we can see that the config needs to be:
```ts
import { defineConfig, presetAttributify, presetWind } from 'unocss'

export default defineConfig({
  theme: {
    containers: {
      // Grid Breakpoints (352px is 4 columns, 768px is 8 columns)
      tablet: '(min-width: 352px)',
      desktop: '(min-width: 768px)',
    },
  },
  presets: [presetWind()],
})
```
in unocss, while in tailwind it can be 

```ts
/** @type {import('tailwindcss').Config} */
export default {
  theme: {
    extend: {
      containers: {
        // Grid Breakpoints (352px is 4 columns, 768px is 8 columns)
        'tablet': '352px',
        'desktop': '768px',
      },
    },
  },
  plugins: [
        require('@tailwindcss/container-queries'),
  ],
}
```
so there is a configuration difference between unocss and tailwind here.

**Comment by zyyv** [comment]
@thraizz We are different from tw container. 
Refer to
- https://unocss.dev/presets/mini#rules
- https://unocss.dev/config/theme#breakpoints

See [Playground](https://unocss.dev/play/#html=DwEwlgbgBALghgIwDYFMYC4DGB7AdvMXFAJygSgFsBaARgAYA%2BAKCilElhQA8YrkBXFLESoMMbr2IoQUECgDOAaxjYADunE8qAcykpcDHPjiESwAPTgIzC1eZA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQoksicYKKlaoYAVRHp6AGzIUqNBkzasAtIOGjV9STK6dUAD17w06AIYzTGbHgLEAFAk5w4RmKizIAKgAtUIKgOMP6BAJSILq5wQjD0UFiR0dEAdGkhAagANFHJAEZC5gDWkNgwrABcScnRAPS1cGkpGYEpBajFpVjlWXD1boYeXnAtqHDtnRBlrLk1MOZ50qJVtADMAKwATGCGtDk10WisRTAQYCsA7ABsABw7e7OupPvRpFHPUf2jVc6u-a4TEpTbqVar-aLzRbLOgbba7F7g1xHE5nS63e4IhpPTFkF4aETlKoAbVm%2BNEEgwMicjzcWAWSwASpoYABlGAATyWoIs0hEL2SwGYBFBvwOcFYzHMSyqAEYUpt%2BTVmMgsCtfDAYGBKvVhCAUqxfLUHgcPslSGEXgBdHLmzhAA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwBpxp5k0BhAVzjCVQoGVHNs8iTZEVUAJMVDla4CAXyA)

**Comment by henrikvilhelmberglund** [comment]
> @thraizz We are different from tw container. Refer to
> 
> * https://unocss.dev/presets/mini#rules
> * https://unocss.dev/config/theme#breakpoints

This is not mentioned in https://unocss.dev/presets/wind#differences-from-tailwind-css. Even if it was and `breakpoints` is the way to do it (why does container not default to min width with px values anyway?) it still doesn't work - [playground](https://unocss.dev/play/#html=DwEwlgbgBAxgNgQwM5ILwCIACMD2A7AFwTDwFMAnAegFti8BxcsEdAPgCgopRJZEUMAcyYgAtIgCeOAK4Eow5lASyco8jgDuSUcoI55I0QDM4mtWZCk8SUm05du4aPGRp0AI0Gj3caaSiYRD6kBDR0jMwAXJ5qpCABlkgA1noADmEkESDRXsKkVmwAQjgAHlAAjMCUThwOjrwuAh5ePn4BQXAhGQwiObHxmIkpOOm0mb0xeQWsxWUATFU19lw8zvxuMa3%2BgQjBoWM9UTHkcQmkyWndWX1TeEWlUADMi5C1Dqt8rhibvtsdXQdrsdToNzsNRuEJrkTtNZlAACwvCBvFZOT5NH5tHZ7K5Q-pnC4jXFHaH5O4zB4AViRKPqay%2BzW8v3au06%2B0hJPxoMJEPGnNu9zKADYacs6eiNi1mdi2cTssCBkNLoC8QKKWUAOyiuofRqSplY-7svnyrwnRVg5Uc02iNVwgAc2u41Ve7FFQA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQoksicYKKlaoYAVRHp6AGzIUqNBkzasAtIOGjV9STK6dUAD17w06AIYzTGbHgLEAFAk5w4RmKizIAKgAtUIKgOMP6BAJSILq5wQjD0UFiR0dEAdGkhAagANFHJAEZC5gDWkNgwrABcScnRAPS1cGkpGYEpBajFpVjlWXD1boYeXnAtqHDtnRBlrLk1MOZ50qJVtADMAKwATGCGtDk10WisRTAQYCsA7ABsABw7e7OupPvRpFHPUf2jVc6u-a4TEpTbqVar-aLzRbLOgbba7F7g1xHE5nS63e4IhpPTFkF4aETlKoAbVm%2BNEEgwMicjzcWAWSwASpoYABlGAATyWoIs0hEL2SwGYBFBvwOcFYzHMSyqAEYUpt%2BTVmMgsCtfDAYGBKvVhCAUqxfLUHgcPslSGEXgBdHLmzhAA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmjpihTCMNsq0ocVwpv6j44hKk4hlFag49OgalIIItHBxAEw0ODD0OLRycQDsR4JyNJEcUGl9Fk7BGpEAbA9%2B-gC5WstHOfEu5wA4rBmHEzvR7GMahoAMzue5yNJzCwfL5gX4PMAAQhgSlEDDgmRxCxsSxUBwQa2UGy2OwQewOcU6p3Ol2udweTxebyp-W0gOBcFB9HB0uhYzAcPOiMYyLANx%2BAA4HlizDiwDS6StGU0WdswLt9odNTyLldbhiha93tS8UdOoSSWSoFLrKKBtogA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwBpxp5k0BhAVzjCVQoGVHNs8iTZEVUAJMVDla4CAXyA)

Imo it's a bug.

**Comment by henrikvilhelmberglund** [comment]
> I see it the same way @henrikvilhelmberglund sees it. Container queries are supported and can be extended/configured, but differently from tw. It should be either documented accurately what is supported how, or it should be fixed and done as tw does it. I can try either gladly in a PR.

PRs are welcome, imo it would be great if in `containers` the current (strange) method of writing `min-width etc etc` could be kept while still allowing for the shorter `<x> px` syntax that would be interpreted as `min-width`. If it's not possible to fix the docs could be updated mentioning that `container` does not work the same way as in TW.

**Comment by zyyv** [comment]
@thraizz @henrikvilhelmberglund My mistake, I went to understand the container implementation and found that I only needed to make the following simple changes to achieve it.

```diff
  theme: {
    containers: {
      // Grid Breakpoints (352px is 4 columns, 768px is 8 columns)
-     tablet: '352px',
+     tablet: '(min-width: 352px)',
-     desktop: '768px',
+     desktop: '(min-width: 768px)',
    },
  },
```

[Playground](https://unocss.dev/play/#html=DwEwlgbgBAxgNgQwM5ILwCIACMD2A7AFwTDwFMAnAegFti8BxcsEdAPgCgopRJZEUMAcyYgAtIgCeOAK4Eow5lASyco8jgDuSUcoI55I0QDM4mtWZCk8SUm05du4aPGRp0AI0Gj3caaSiYRD6kBDR0jMwAXJ5qpCABlkgA1noADmEkESDRXsKkVmwAQjgAHlAAjMCUThwOjrwuAh5ePn4BQXAhGQwiObHxmIkpOOm0mb0xeQWsxWUATFU19lw8zvxuMa3%2BgQjBoWM9UTHkcQmkyWndWX1TeEWlUADMi5C1Dqt8rhibvtsdXQdrsdToNzsNRuEJrkTtNZlAACwvCBvFZOT5NH5tHZ7K5Q-pnC4jXFHaH5O4zB4AViRKPqay%2BzW8v3au06%2B0hJPxoMJEPGnNu9zKADYacs6eiNi1mdi2cTssCBkNLoC8QKKWUAOyiuofRqSplY-7svnyrwnRVg5Uc02iNVwgAc2u41Ve7FFQA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCCMMUwARgK4zDoCeZF1tAOrZkcAL5x0UCCDgByNlggBjKlTkAoDagAekWCgwBDNgBt4aTDnyFgRABQINcODAAWqEKgBciZy7hlAhgjbFQoKl8nAICAeli4AHFmUQAhSiMAa0hsGCo4ewBmAFYAJjAdOGB8gBZAiFM2ECwqMgB2ADYADgqq-K76xuaqAEp-GJCWU1pfOXsQbABaAHdgZHdfEvKdEbkScYC0KkyYCDBZ%2BaXV9bdfTp6dvYOxfZcX-34aPN8AbU%2BhET2EYAXX2YjGQA&css=HQcwTglgJgtANgQwJ4HsCuAXABAbwFBZbjQwYCmAtgA6LkwDGKcaFAdgM4BcWYZVZCDAAoATABosFCKwoIAHkIDsIqnIkBGAGZgAlDoDcBIgird1ANlWGjAAUasMCaWTCSnrAOKQoWIVNYwAO7QGAAW3ADMAKwqcjq4RoQgJmaWclgAhBDUKGCODoaESd6klDSCZAxMLBzcvPyCQgAsEv6yCsqqGtp6hVgAvni29o7OrrLSXtC%2B-kEh4ViK5gAcqvH4RUQl5NS0lYzMbFw8fALCy63S7Uqx3boGicamWCJNqpnZVLn5GH2Dg0A&options=N4XyA)
