### ISSUE TITLE
【vscode plugin】Support fuzzy matching, like Tailwind CSS. 

### ISSUE THREAD

**Issue by seepine** [unocss/unocss#4230]
### Clear and concise description of the problem

Support fuzzy matching, like Tailwind CSS plugin. 

### Suggested solution

<img width="160" alt="image" src="https://github.com/user-attachments/assets/a02e7067-df5b-4503-bbf1-93f5fd72f9e6">

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by zyyv** [comment]
We already support fuzzy search. https://github.com/unocss/unocss/pull/2769

**Comment by JenuelDev** [comment]
I just confirmed fuzzy matching not working from the unocss in vs code extension,,
![image](https://github.com/user-attachments/assets/08950c68-a09d-4c0b-af82-ed660d18306f)


I have to write exact spelling of the class
![image](https://github.com/user-attachments/assets/1fde1fd2-e4da-4a49-94f6-382cb99d2041)

**Comment by henrikvilhelmberglund** [comment]
Did you configure the extension by changing the autocomplete type to fuzzy?
