### ISSUE TITLE
Type "Preset<object>" cannot be assigned to type "PresetOrFactory<object> | PresetOrFactory<object>[]".

### ISSUE THREAD

**Issue by maxfrees** [unocss/unocss#4241]
### UnoCSS version

lastest

### Describe the bug

Type "Preset<object>" cannot be assigned to type "PresetOrFactory<object> | PresetOrFactory<object>[]".

Before I defined it in the initUnocssRuntime, now I define it in the initUnocssRuntime, it will prompt a type error

### Reproduction

```
initUnocssRuntime({
  defaults: {
    presets: [
      presetUno(),
      presetAttributify(),
      presetIcons({
        extraProperties: { display: 'inline-block', 'vertical-align': 'middle' },
        collections: {
          carbon: () => import('@iconify-json/carbon/icons.json').then(i => i.default)
        }
      })
    ],
    safelist: [
      ...ICONS,
      'w-full',
      'w-240px',
      'w-274px',
      'w-auto',
      'h-auto',
      'w-min!',
      'ml-5px',
      'mr-5px',
      'px-0',
      'w-1/2',
      'flex',
      'flex-center',
      'items-center',
      'text-center',
      'flex-wrap',
    ]
  }
});

```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
Let's focus on #4242 to solve it.
