### ISSUE TITLE
You cannot assign type "UserConfig" to type "UserConfigDefaults<object>"

### ISSUE THREAD

**Issue by maxfrees** [unocss/unocss#4242]
### UnoCSS version

lastest

### Describe the bug

```
import initUnocssRuntime from '@unocss/runtime'
import config from './uno.config'

initUnocssRuntime({ defaults: config })
```

```
import { standardVars } from '@standard-semi/vars';
import { defineConfig, transformerVariantGroup } from 'unocss';

export default defineConfig({
  preflights: [
    {
      getCSS: () => '* { outline: none; }'
    }
  ],
  theme: {
    spacing: {
      DEFAULT: standardVars.margin
    },
    colors: {
      primaryColor: 'var(--primary-color)',
      infoColor: 'var(--info-color)',
      errorColor: 'var(--error-color)',
      warningColor: 'var(--warning-color)',
      successColor: 'var(--success-color)',
      placeholderColor: 'var(--placeholder-color)',
      placeholderColorDark: 'var(--placeholder-color-dark)'
    }
  },
  shortcuts: {
    'flex-center': 'flex justify-center items-center',
    'min-component-width': 'w-240px',
    'modal-content-height': 'h-70vh',
    'card-title': 'text-18px text-#1F2225 mb'
  },
  transformers: [transformerVariantGroup()]
});

```

### Reproduction

*

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
Can you provide a minimal reproducation?
