### ISSUE TITLE
unocss/Astro still has the problem that presets and transformers cannot be used simultaneously

### ISSUE THREAD

**Issue by shiheme** [unocss/unocss#4251]
### UnoCSS version

0.63.6

### Describe the bug

#4071 #4056 
"astro": "^4.16.5"
In Astro，Transformers from a custom preset are ignored

### Reproduction

`// uno.config.ts
import { defineConfig, transformerCompileClass, presetIcons } from 'unocss'

export default defineConfig({
  presets: [preset()],
transformers: []transformerCompileClass() ],
})`

`//astro.config.mjs
import UnoCSS from "unocss/astro";

export default defineConfig({
  integrations: [
    UnoCSS()
  ],
})`

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
Can you provide a minimal reproduction?

**Comment by shiheme** [comment]
It's my problem, I used tailwindcss in Astro. I did not use presetUno() in the preset
