### ISSUE TITLE
transformer-attributify-jsx not work with rsbuild

### ISSUE THREAD

**Issue by Qingmao-w** [unocss/unocss#4253]
### UnoCSS version

0.64.0

### Describe the bug

I am using unocss on the rsbuild project and introduced transformerAttributing Jsx in uno.config.ts, 
but did not convert the
`<div w-30 h-30 bg red>App</div>`
to 
`<div w-30="" h-30="" bg red="">App</div>`

Console Error: Warning: Received `true` for a non-boolean attribute `bg-red`.
If you want to write it to the DOM, pass a string instead: bg-red="true" or bg-red={value.toString()}. Error Component Stack

But if you write it this way, it will work.
`<div className="w-30 h-30 bg blue">App</div>`

![6](https://github.com/user-attachments/assets/c7948362-d98a-4788-a56c-e15bc9263bb9)
![7](https://github.com/user-attachments/assets/9f982aba-37dd-4614-af30-622d491f9bff)

Link  https://codesandbox.io/p/github/Wxw-Gu/rsbuild-demo/master?import=true

### Reproduction

https://codesandbox.io/p/github/Wxw-Gu/rsbuild-demo/master?import=true

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
I noticed that you use `@unocss/postcss` package with `rsbuild`. Transformer is not supported in `postcss`.
I'm sorry to tell you that transformer package is usually used in conjunction with vite plugin `transform` api. I'm not sure about the plugin capabilities of rspack.
