### ISSUE TITLE
Prose Styles are not marked as important when the whole config is

### ISSUE THREAD

**Issue by kolaente** [unocss/unocss#4260]
### UnoCSS version

0.64.0

### Describe the bug

When styles are marked as important using `important: true` in `presetUno`, styles from `presetTypography` are not marked as important. That might be logical, because the two are different presets, but it's at least confusing. The problem here is that styles which are defined with a higher specificity (which is the reason I'm using important in the first place) will override the prose styles.

I can think of a few solutions:

- When `important: true` is set in `presetUno`, make all generated prose styles important as well (most intuitive)
- Provide an additional option in `presetTypography` to make generated prose styles important
- Make the `selectorName` more flexible so that I could set it to something like `#container .prose` so that prose styles have a higher specificy than what is defined elsewhere (see my reproduction).

### Reproduction

https://unocss.dev/play/#html=DwEwlgbgBGILwCIDGB7AdgFwIZjQUwCcEA%2BAKCimAGcAHLNKJAGyyqsQzwA8MBaAvCBIYAFmCowJAkMAD0temQqhIjFm0Q0CKKnhLkKlGsQAqIvLqhYBUAGYEArmAwSA7mKQioVESgdMQKBEsCDwoOhBwNABzKHweKAwURPMAWwAuOWMDZX8lQ2UmMGIAQRoaJgs5IvyC4BqAIXpmqmrinMN64oB5AnpoqtkajsLigGUMPtcAI0ICMEHhgtHiAFl%2BlEX2utk8gzlwCDIDyDIgA&config=JYWwDg9gTgLgBAbwCYFMBmwB2KDCFMYDmANHGFCgM4owAqAnpIVAIZgAW9p5VNAqpggBfOGigQQcAOQBXQQGNKlKQCgVKAB6RYcVGhYyANvD1Zc%2BIgAoEKgJA9qMSgC44AbTv2KjgRGufbUG0YFkwYVxgoGRRiTyEASljbL146RghmNk5LRLsAXViEoA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmjoAxOXWtDD0fGYWqMqm-haCtIyMk042qhxuYL7%2B-QPaQA&options=N4IgLgTghgdgzgMwPYQLYAkyoDYgFwJTZwCmAvkA&version=0.64.0

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
> The problem here is that styles which are defined with a higher specificity (which is the reason I'm using important in the first place) will override the prose styles.

```css
.prose {
  color: var(--un-prose-body) !important;
  max-width: 65ch !important;
}
```

-------

Your question is, does your use of the `important` option affect the style of `prose`, also made it important?

**Comment by kolaente** [comment]
@zyyv Please take a look at the playground. It seems like prose styles are not important when the main CSS is important, but I'd expect the prose styles to be important in that case.
