### ISSUE TITLE
Would it be possible to export the rules in @unocss/preset-wind separately, like @unocss/preset-mini does?

### ISSUE THREAD

**Issue by CommanderXL** [unocss/unocss#4266]
### Clear and concise description of the problem

Well, `@unocss/preset-mini` export the rules separately [here.](https://github.com/unocss/unocss/blob/main/packages/preset-mini/src/rules.ts). So I don't need to write the raw regExp rule in the `uno.config.js`, I can get the raw rule like textShadows and textStrokes directly from `@unocss/preset-mini/rules`, and overwrite the group rule in the `uno.config.js`, like this:

```javascript
//  I can get the raw rule here and overwrite
const { textShadows } = require('@unocss/preset-mini/rules')
```

But `@unocss/preset-wind` doesn't exports the raw rules group separately, all of those rules are flatten in one array，so if I want to get some special rule group，I need to do some other work to get the rule I want，like this:

```javascript
const { rules } = require('@unocss/preset-wind')

const findRawRules = (matcher, rules) => {
   // do something to get the raw rules
}

// get the background-repeat raw rules
const rawBackgroundRules = findRawRules(/^bg-repeat-?.*/,  rules)
```

### Suggested solution

export `@unocss/preset-wind` rules separately like `@unocss/preset-mini`

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
PR welcome, I think this is more like something we forgot to add

**Comment by CommanderXL** [comment]
https://github.com/unocss/unocss/pull/4267 for this issue
