### ISSUE TITLE
Type "Promise<{}>" cannot be assigned to type "Promise<IconifyJSON>".

### ISSUE THREAD

**Issue by maxfrees** [unocss/unocss#4271]
### UnoCSS version

lastest

### Describe the bug

```
presetIcons({
        extraProperties: { display: 'inline-block', 'vertical-align': 'middle' },
        collections: {
          'material-symbols': () => import('@iconify-json/material-symbols/icons.json').then(i => i.default)
        }
      })
```

Type "() => Promise<{}>" cannot be assigned to type "(() => Awaitable<IconifyJSON>) | CustomIconLoader | InlineCollection | undefined".
Can't type "() = > Promise < {} >" assigned to type "() = > Awaitable < IconifyJSON >".
Type "Promise<{}>" cannot be assigned to type "Awaitable<IconifyJSON>".
Type "Promise<{}>" cannot be assigned to type "Promise<IconifyJSON>".
Type "{}" is missing the following attributes in type "IconifyJSON" : prefix, icons

### Reproduction

![image](https://github.com/user-attachments/assets/f093f713-0a40-43c8-8573-89f2e326da18)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
You can use an `as any` or ignore the error. This is due to that `@iconify-json/material-symbols/icons.json` doesn't have a type, but not UnoCSS's issue.
