### ISSUE TITLE
Include `nuxt.config.ts` to source files in nuxt module

### ISSUE THREAD

**Issue by zumm** [unocss/unocss#4272]
### Clear and concise description of the problem

I like to set some utility classes to nuxt root element by `nuxt.config.ts`:
```ts
  app: {
    // @unocss-include
    rootAttrs: { class: 'font-montserrat' },
  },
```

But to get it worked i also need to add `nuxt.config.ts` to [content sources](https://unocss.dev/guide/extracting#extracting-from-build-tools-pipeline) manually. It's a bit clunky.

It's also possible to add needed utilities to `safelist`, but i don't like this approach either because it forces changes to be made in two places.

### Suggested solution

Would be nice if `@unocss/nuxt` module handled it and added `nuxt.config.ts` to source files, resulting in tigher nuxt integration.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by zyyv** [comment]
I don't recommend adding it to the sources by default, but there may be multiple configuration files that require this in the future. The current `content` option already does this.
