### ISSUE TITLE
When using elmentupiplus, the style is updated by elmentupiplus after it takes effect

### ISSUE THREAD

**Issue by kejiyouzhua** [unocss/unocss#4274]
### UnoCSS version

0.64.1

### Describe the bug

I am using nuxt+vue3+elmentuiplus+unocss. I want to use Uno to modify the el button of elmentupiplus, but the style takes effect for 1 second and is replaced by elmentupiplus's own style. How can I solve this problem?

### Reproduction

https://gitee.com/liuzihao2009/novel_home

### System Info

window vue3+nuxt 
![bug2](https://github.com/user-attachments/assets/fbab1de7-6010-49cd-afbd-11e65117b236)
![bug1](https://github.com/user-attachments/assets/5514af1f-0269-4a34-adf0-488b8a098740)
![bug2](https://github.com/user-attachments/assets/8d49f71f-7bf3-44a0-953d-d7874b0d5c06)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
Refer to https://unocss.dev/guide/style-reset#tailwind-compat
