### ISSUE TITLE
Feature proposal: add "outputPrefix" option to attributifyPreset

### ISSUE THREAD

**Issue by smashercosmo** [unocss/unocss#4277]
### Clear and concise description of the problem

The problem with attributifyPreset is that you end up with non-valid HTML, as HTML allows custom attributes only in the form of `data-attribute-name`.

### Suggested solution

Introduce `outputPrefix` option, which, if provided, will make attributifyPreset prefix attributes in the generated css. User will have to transform unprefixed attributes to prefixed ones in runtime. Example:

```ts
import {
    defineConfig,
    presetAttributify,
    presetUno,
} from 'unocss'

const config = defineConfig({
    theme,
    presets: [
        presetUno(),
        presetAttributify({
          outputPrefix: "data-"
        }),
    ],
})
```

```tsx
import type { Spacing } from "./theme.ts";
import type { ReactNode } from "react";

type Props = {
  children: ReactNode;
  w?: Spacing;
  h?: Spacing;
}

export function Box({ children, w, h }: Props) {
  return <div data-w={w} data-h={h}>{children}</div>
}
```

```tsx
function App() {
  return (
      <Box h="size-24" w="size-40">Hello from unocss</Box>
  );
}
```

```css
[data-w~="size-40"] {
    width: 2.5rem;
}
[data-h~="size-24"] {
    height: 1.5rem;
}
```

### Alternative

The alternative is to just use `prefix` option and set it to `data-`. But in this case it's just more to write, and the code will be more verbose.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by zyyv** [comment]
Even without add this option also can do it.

```ts
// uno.config.ts
postprocess(utilities) {
  utilities.selector = utilities.selector.replace(
    /(\[)([^\]]+)(\])/g,
    (match, p1, p2, p3) => {
      return `${p1}data-${p2}${p3}`
    }
  )
}
```

Or refer to our documents https://unocss.dev/presets/attributify#prefix.

[Playground](https://unocss.dev/play/#html=DwEwlgbgBCCGAusC0B3ATrADpgpmgfAFBRSiQwLLw4Ae8SARgDYCuO%2BAqgHYD2AwgGUBwAPTgIREmWhxESMEjQKA5mHgALFgyRMwXHFBFFR4okA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQoksicYKKlaoYAVRHp6AGzIUqNBkzasAtIOGjV9STK6dUAD17w06AIYzTGbHgLEAFAk5w4rABbQYzejFYAuRBdXOAB3KHMwMFQoQNpQ1VZmIVQsOHdE5NRUimY82gAaYNIi1w0RP0CAbWCyoQqJDBknWpCNdGlgIndKinNpEVKQ13MYGChgACNfYHQAT0DnYeH24EM45FHzVULWlaFMQ1RkAHksaQW4cfpUPbIh4eBmAgCg5ZCk-tRAgEYAOgATA9lsxkFg4j0YGAAgB6GHCEB-Dww3bvEqtUgASiGAF0hkYYKlkAAVdyoECoBwwMkUzFvELPLCsCDSVB-aQQIhUmmoTHFIpYzhAA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwBpxp5k0BhAVzjCVQoGVHNs8iTZEVUAJMVDla4CAXyA&version=0.64.0)

**Comment by smashercosmo** [comment]
Alright. Thx for the tip. If it's something that can be easily achieved in the userland, I guess the issue can be closed.
