### ISSUE TITLE
Unknown at rule @apply scss(unknownAtRules)

### ISSUE THREAD

**Issue by yi-boide** [unocss/unocss#4280]
### UnoCSS version

0.64.1

### Describe the bug

Unknown at rule @applyscss(unknownAtRules)
<img width="538" alt="image" src="https://github.com/user-attachments/assets/25f1116c-84f1-4793-923a-5cf90c1ce088">

### Reproduction

vite vue 

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
https://unocss.dev/transformers/directives#at-apply

**Comment by zdxxxxxx** [comment]
遇到同样问题，在sveltekit中

![Image](https://github.com/user-attachments/assets/2b6cfd6e-e42c-4573-a4c5-546f9230e1c1)

**Comment by zdxxxxxx** [comment]
官方demo也会复现https://stackblitz.com/edit/unocss-unocss-zkeexxna?file=README.md
