### ISSUE TITLE
components/photo/Modal.vue:50:36 - error TS2322: Type '"y--1/2"' is not assignable to type '"no" | "yes" | undefined'.

### ISSUE THREAD

**Issue by Archetipo95** [unocss/unocss#4281]
### UnoCSS version

"@unocss/nuxt": "^0.64.1",

### Describe the bug

components/photo/Modal.vue:50:36 - error TS2322: Type '"y--1/2"' is not assignable to type '"no" | "yes" | undefined'.

### Reproduction

In this repo: https://github.com/nuxt/movies
If I do a typecheck I get errors from "translate" property

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
You should report the problem in the upstream repository

From the TS error, the property does not provide a string type.

More like: 
```ts
defineProps<{
  translate?: 'yes' | 'no'
}>()
```

Also you can use `un-` prefix avoid ts error.

```html
<Modal un-translate='y--1/2' />
```
