### ISSUE TITLE
Compatibility issue with oklch for gradients

### ISSUE THREAD

**Issue by Zhang-Wei-666** [unocss/unocss#4284]
### UnoCSS version

0.63.6

#### Firefox browser is not supported

version: 116.0

![PixPin_2024-11-23_10-38-07](https://github.com/user-attachments/assets/16911b57-6a87-47cc-b5f6-92e4acde30f9)

#### Quark mobile browser is not supported

---

#4211 

### Reproduction

https://unocss.dev/play/#html=DwEwlgbgBAxgNgQwM5ILwCIlgF4FMC0AjAAxRIAWCIA9gO5QBGA5vkwE5Vi4B2ALvr2r4GjFu049%2BAMzbUAtvja4Q%2BAGyjWHcJIFClKgJxQ5ADwTH%2BAJnQA%2BYAHpwEG0A&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDASSarID3fsMBVKtoAvqByNJScoADkFlRMkJCRwjx8iBLezogAoiQ0mKDBoeFRMZRxkMhOBijEDJiRANyCgsSiqbJymBbQbfKKKmqw6gAUktI0XVAAXKAA2jrSM5FMFpCI4bQTkZpp7tB805F0qJH5ALpe5zqQABYpywLTo9JRy6vrN3dWkQesJMjQ6lAvxQfEw8HU4FAtwAbuAaJNgchWJhoFsdIEvJVDJBpnNnukqv5KEMAJReRw%2BYymRiWax2UnkgmudzwSAjebPSBMFHgaYARgAdAAmRnSJioeAHa6mbg4kBQTgCm7ANH4wJkjkgJlZHKYBk6S7qwRAA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4XyA

### System Info

System:
  OS: Windows 11 10.0.22631
  CPU: (20) x64 13th Gen Intel(R) Core(TM) i9-13900H
  Memory: 15.77 GB / 31.75 GB
Browsers:
  Edge: Chromium (128.0.2739.42)
  Internet Explorer: 11.0.22621.3527

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
I test it on Firefox(129.0.2 ARM64) works well. 
<img width="128" alt="image" src="https://github.com/user-attachments/assets/ad7962d6-8ae5-4783-b4ea-2aafe4727ce9">

Sorry, I don't think I can help you with compatibility.

**Comment by Zhang-Wei-666** [comment]
> I test it on Firefox(129.0.2 ARM64) works well. <img alt="image" width="128" src="https://private-user-images.githubusercontent.com/42139754/389155937-ad7962d6-8ae5-4783-b4ea-2aafe4727ce9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMjk0NzIsIm5iZiI6MTczMjMyOTE3MiwicGF0aCI6Ii80MjEzOTc1NC8zODkxNTU5MzctYWQ3OTYyZDYtOGFlNS00NzgzLWI0ZWEtMmFhZmU0NzI3Y2U5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDAyMzI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwYjY0Zjk5Yjk0YmJmY2M5NWY4NjE4YWE3MmU1ODNhMzAzYWNiZDJmNjIxM2QwMGZlYzFmNTYwMzM5MGIyY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XmPHW9ufJlni3e1zBAgQRTyircaFw3G9rIHr89QbcvQ">
> 
> Sorry, I don't think I can help you with compatibility.

是的, Firefox 在 128 及以后才支持

---

Yes, Firefox supports it from version 128 onwards.

https://caniuse.com/mdn-css_types_color_oklch_relative_syntax

![PixPin_2024-11-23_10-48-20](https://github.com/user-attachments/assets/c6ef6bf5-da86-4fd3-be37-c0e8caa02e9c)

**Comment by zyyv** [comment]
@Zhang-Wei-666 
Hi, I tried adding this option to https://unocss.dev/presets/legacy-compat, but found that this might be too coupled to the color format, and we don't know the requirements after the downgrade, so we leave this configuration to the user.

```ts
postprocess: (util) => {
  util.entries.forEach((i) => {
    i[1] = i[1].replace(/in (oklch|oklab)/g, '')
  })
}
```
Refer to [Playground](https://unocss.dev/play/#html=DwEwlgbgBAxgNgQwM5ILwCIlgF4FMC0AjAAxRIAWCIA9gO5QBGA5vkwE5Vi4B2ALvr2r4GjFu049%2BAMzbUAtvja4Q%2BAGyjWHcJIFClKgJxQ5ADwTH%2BAJnQA%2BYAHpwEG0A&config=PTAEFMGcBsEsDsAuBaAJrSBDARtcz5wAPFOQ0eAe2QCcpEbYBjRcVZWAWwAdKbFIAKC69%2BoAN6DQoVOABmCcAGFK8BQHMANFNDc6kcIgCCiBrGwBXRLDkBPbdL1RDASSarID3fsMBVKtoAvqByNJScoADkFlRMkJCRwjx8iBLezogAoiQ0mKDBoeFRMZRxkMhOBijEDJiRANyCgsSiqbJymBbQbfKKKmqw6gAUktI0XVAAXKAA2jrSM5FMFpCI4bQTkZpp7tB805F0qJH5ALpe5zqQABYpywLTo9JRy6vrN3dWkQesJMjQ6lAvxQfEw8HU4FAtwAbuAaJNgchWJhoFsdIEvJVDJBpnNnukqv5KEMAJReRw%2BYymRiWax2UnkgmudzwSAjebPSBMFHgaYARgAdAAmRnSJioeAHa6mbg4kBQTgCm7ANH4wJkjkgJlZHKYBk6S6OSirPSlKA40BDKywaAk0AAXgAfBIOdJrdABeAkIwoAK5HxMpgmNchkNYHanS78fjYDM%2BacHaBY-GBXRuNAg%2BAhsAEJbKABraDBgA%2BBYz2BJwC0UUiJNd%2BTraqCdaAA&css=PQKgBA6gTglgLgUzAYwK4Gc4HsC2YDCAyoWABYJQIA0YAhgHYAmYcUD6AZllDhWOqgAOg7nAB0YAGLcwCAB60cggDYIAXGBDAAUKDBi0mXGADe2sGC704AWgDuCGAHNScDQFYADJ4Dc5sAACtMLKAJ5gggCMLPK2ABR2pPBIcsoAlH4WAEa0yADWTlBYqEw2yFjK3Bpw5LxxAOTllVDoYpSMYgAs3vUZ2gC%2BmsBAA&options=N4XyA&version=0.64.1)
