### ISSUE TITLE
VS Code Extension stuck on some grammar

### ISSUE THREAD

**Issue by XHanL** [unocss/unocss#4293]
### UnoCSS version

0.64.1

### Describe the bug

- Using the following minimum reproducible example, the extention looks falls into an infinite loop, the CPU load is 100%, and VS Code freezes. 
- There is also a cpuprofile generate from VS Code for the minimum reproducible example
[antfu.unocss-unresponsive.cpuprofile.txt](https://github.com/user-attachments/files/17942375/antfu.unocss-unresponsive.cpuprofile.txt)

#### Main Reproduction
- Since it is difficult to prepare an environment in StackBlitz for this VS Code Extension, reproducible source files are provided.

- The problem may be with `StaticProps<“span”, IconProps>`,  if we replace it with `StaticProps<IconProps>`(not the correct usage for StaticProps but unocss does not care) and restart the VS Code then the extension work fine.
- The clsx part may have some performance issues, not sure..

  ```tsx
  import { clsx } from "clsx";
  import type { StaticProps } from "utils";
  
  export type IconProps = {}
  
  export const Icon = (props: StaticProps<"span", IconProps>) => {};
  
  export const iconVariants = clsx("", {
      variants: {
          text: {
              "100": "text-100",
              "200": "text-200",
              "300": "text-300",
              "400": "text-400",
              "500": "text-500",
              "600": "text-600",
              "700": "text-700",
          },
          weight: {
              "100": "font-100",
              "200": "font-200",
              "300": "font-300",
              "400": "font-400",
              "500": "font-500",
              "600": "font-600",
              "700": "font-700",
          }
      },
  })
  ```

#### Utils
- Not a reproduction file, provide StaticProps reference
  ```ts
  import type { JSX, ComponentProps, ValidComponent } from "solid-js";
  import { Dynamic } from "solid-js/web";
  
  export type OverrideProps<Source = {}, Override = {}> = Omit<Source, keyof Override> & Override;
  export type StaticProps<T extends ValidComponent, P extends {} = {}> = OverrideProps<ComponentProps<T>, P>;
  ```

### System
- macOS 15.1.1

### Browser
- Chrome 131.0.6778.86 (arm64)

### Framework: 
- Vite@5.4.11
- SolidJS @1.9.3

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Could you share your project setup as a git repo? This might caused to the presets you enabled
