### ISSUE TITLE
Custom sorting for multi-selector rules

### ISSUE THREAD

**Issue by ameinhardt** [unocss/unocss#4303]
### Clear and concise description of the problem

For making daisyui components work efficiently with unocss, I'd like to create related rules in a specific order.
My first attempt of having many dynamic rules for one selector = component doesn't seem to work, as unocss just seems to evaluate the first match for a token.
The second attempt of having multi-selector rules for a component doesn't fully work, as it re-groups css rules. Sort seem to only work on rule level, not on multi-selector level.

### Suggested solution

Introducing another special symbol `selectors.sort`, applying to each entries meta in `UnoGenerator.parseUtil()`, for being able to define sort order of multi-selector rules within their layer

### Alternative

Apply all matching dynamic rules for one token

### Additional context

[Playground](https://uno.antfu.me/play/#html=DwEwlgbgBAxgNgQwM5ILwCIAuBTJmoAWAtAGYCuccUJc2AHtbXUTAPZVg4C2SL2AdjgBOUAFZk8YEgE8%2Bg7EPQA%2BAFBQooSLEQoMSVl2xRWmAgqidsXZWvUbwEJQCE4ZbABoo07JVYB3YxEhbBAAfmAAegdVdUjolTjIJSA&config=JYWwDg9gTgLgBDKBDAdgZwGbRAUygEWChwGMZgA3HNODKCEOAcgAEBXFCEtNAekVSZseALQATIqXJU0TAFChIsOAG85cOGJwZgKHAGEIKHQHMANOrhhiaHDACCMRMABGbchgCeFjdep2ASRIjNB8rGzsAVU4wtE8QFwgAG1C5AF9aekYmDi4eeTkcAA8leC0MJDYksu1dAyNTAAo1DSgq6gAuOABtSw1u3gA9GGoYABJeMzhGgEo4AF4APmmWjTXgpOgupk8cJM2AdyYwtZ64hOS0ADpbJKloAF0uxpQ5pbgAAzGVFAzlq4gMAAFngPn04GkZg8Tj1wRohiM0ONJnDpm9lo1eqdTqtsWsmFgUDARGhgAAvHBMbYAJhwIGOqI0aRhOMZ62SW2YxDEDLxp2650SKRue3uUCe01eC2WXx%2BfzgNwYODBfIhLLWuL5G05TBcSTYlPV-MFlxFdzIj2eUvest%2BcH%2BwBGIBVfLSqIeMxh0Ms3t8ERgaC63T8thg0Qgs19CGQ6CwUFwUEDPQEseEBEkZEo1EjFkhciAA&css=HQFwpgziAEDeBQ1oAECGAHdAbAntARgOYC0hATmGAHbECcADPQNzwC%2BQA&options=N4IgzgLgTglgxhEAuaBXApgGhNAhgOzADMB7KAW2SNwBswscoDizyBhVSE9gZR6tr1seQqQoAJCORoC66AL5A&version=0.64.1)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by henrikvilhelmberglund** [comment]
There is `[symbols.layer]`. I don't really understand what you're trying to do though.

**Comment by ameinhardt** [comment]
Daisyui uses defined classes as comonents (.btn, .menu etc.). In one layer `daisy-components`, they are not only used atomically, but also in composite css selectors. See e.g. [styled.css](https://cdn.jsdelivr.net/npm/daisyui@4.12.14/dist/styled.css).
I want to produce one multi-selector uno rule for every class selector, while maintaining the rule order.
Spelling mistake before: the symbol to introduce could be named `[symbols.sort]` and be applied to `meta` per multi-selector rule. Currently, `meta.sort` of the overall rule would be applied only, I think

**Comment by ameinhardt** [comment]
I'm trying to hint the rule order at [unocss-preset-daisy/src/index.ts](https://github.com/ameinhardt/unocss-preset-daisy/blob/6fefcd09d866b8e563015ec1bc3cf4401ffe760c/src/index.ts#L103) to be the same as the original. It mostly works without, but the result differs in some cases to daisyui without it.
