### ISSUE TITLE
Do not generate CSS variables for unused classes in "virtual:uno.css"

### ISSUE THREAD

**Issue by ecstrema** [unocss/unocss#4305]
### UnoCSS version

0.64.1

### Describe the bug

When importing `virtual:unco.css`, a ton of unused CSS variables are imported during development:

![image](https://github.com/user-attachments/assets/301169b2-1bb0-437a-9e63-ace748cb9af9)

These make it hard too see which rules are actually active in the dev tools.

Would there be any way to only create these variables within the mutation observer?

### Reproduction

create any empty project and `import "virtual:uno.css"`

### System Info

All browsers

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
Resolved on https://github.com/unocss/unocss/pull/4252
