### ISSUE TITLE
When shortcuts are configured with the CSSValue type, the CSSValue cannot be applied to the corresponding shortcuts

### ISSUE THREAD

**Issue by nixwai** [unocss/unocss#4326]
### UnoCSS version

0.65.1

### Describe the bug

<img width="1280" alt="Snipaste_2024-12-13_15-07-01" src="https://github.com/user-attachments/assets/f0ab06c8-ba6f-46a0-a08b-d5af673d6ccc" />

### Reproduction

https://stackblitz.com/edit/vitejs-vite-1x6sbuot?file=src%2FApp.vue

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Uhm, interesting. This looks like a bug indeed - but I wonder why you don't put the second rule in to `rules`?

**Comment by nixwai** [comment]
> Uhm, interesting. This looks like a bug indeed - but I wonder why you don't put the second rule in to `rules`?

Um...I found this problem because I was developing something like OnuUI. I want to use css variables to achieve dynamic brightness of the UI. Inspired by the Button component in [ElementPlus](https://element-plus.org/en-US/component/button.html).

Here's a simple dome(https://stackblitz.com/edit/vitejs-vite-dcscndlj?file=uno.config.js)
