### ISSUE TITLE
Upgrade sirv dependency to v3

### ISSUE THREAD

**Issue by HummingMind** [unocss/unocss#4329]
### Clear and concise description of the problem

Upgrade sirv dependency to v3

### Suggested solution

Upgrade sirv dependency to v3

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [ ] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by zyyv** [comment]
https://github.com/unocss/unocss/blob/09887aef1d72791621005f56fa2ca5157f2e5ee7/pnpm-workspace.yaml#L122

Already v3
