### ISSUE TITLE
Can unocss be introduced on specific pages?

### ISSUE THREAD

**Issue by eachann1024** [unocss/unocss#4331]
### Clear and concise description of the problem

Currently, we can only introduce unocss in main, if we want to introduce unocss in old project, we can only ➕ prefix, how can we introduce unocss in single file (.tsx/.vue)?

```vue
import { ref } from 'vue' 
import 'uno.css'

...
```

### Suggested solution

It's not a bug

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by zyyv** [comment]
`uno.css` exists as the generated CSS. It does not affect which page you use it on. You can use the syntax of unocss on any page.

**Comment by eachann1024** [comment]
> `uno.css` exists as the generated CSS. It does not affect which page you use it on. You can use the syntax of unocss on any page.

My concern is that after the introduction of unocss in the old project, the previous class naming method is consistent with unocss, which affects the page effect, which is a concern for all the old projects.

**Comment by zyyv** [comment]
You can refer to the preset configuration to make reasonable special distinctions to achieve the minimum impact. 
https://unocss.dev/presets/mini#options

**Comment by eachann1024** [comment]
> You can refer to the preset configuration to make reasonable special distinctions to achieve the minimum impact. https://unocss.dev/presets/mini#options

I've read this document before, and it seems that it can only be done by prefixing, so I'm asking if there are any other solutions.
