### ISSUE TITLE
Rsbuild support

### ISSUE THREAD

**Issue by a81n9** [unocss/unocss#4345]
### Clear and concise description of the problem

It is recommended to support `rsbuild`

### Suggested solution

/

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [ ] Already used the [Interactive Docs](https://unocss.dev/interactive/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Simon-He95** [comment]
https://github.com/unocss/unocss/pull/4173 It seems we can use uno in rspack
