### ISSUE TITLE
bg-gradient anomaly

### ISSUE THREAD

**Issue by Wuchieh** [unocss/unocss#4356]
### UnoCSS version

0.64.1

### Describe the bug

The bg-gradient property does not display correctly on iPhone 7 Plus.
The issue is caused by the --un-gradient-shape property in bg-gradient-to-([rltb]{1,2}), which defaults to in oklch.
This results in an error for background-image in older versions of Safari.

### Reproduction

unocss/packages/preset-wind/src/rules
/background.ts: 90

### System Info

This is the code I modified, adding some compatibility support.

```
    [
      /^bg-gradient-in-(oklch|srgb|lab)$/,
      ([_, v]) => ({
        '--un-gradient-shape-color-space': `in ${v}`,
      }),
      { autocomplete: 'bg-gradient-in-(oklch|srgb|lab)' },
    ],
    [
      /^bg-gradient-to-([rltb]{1,2})$/,
      ([, d]) => {
        if (d in positionMap) {
          return [
            ['--un-gradient-shape', `to ${positionMap[d]} var(--un-gradient-shape-color-space, )`],
            ['--un-gradient', 'var(--un-gradient-shape), var(--un-gradient-stops)'],
            ['background-image', 'linear-gradient(var(--un-gradient))'],
            ['background-image', `linear-gradient(to ${positionMap[d]}, var(--un-gradient-stops))`],
          ]
        }
      },
      {
        autocomplete: `bg-gradient-to-(${Object.keys(positionMap)
          .filter((k) => k.length <= 2 && Array.from(k).every((c) => 'rltb'.includes(c)))
          .join('|')})`,
      },
    ],
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
You can use https://unocss.dev/presets/legacy-compat#legacycolorspace together.

**Comment by Wuchieh** [comment]
> You can use https://unocss.dev/presets/legacy-compat#legacycolorspace together.

If I directly use this method, although it works fine on older versions, the style will be lost in browsers that already support it.
