### ISSUE TITLE
preset-attributify: Character mapping and chaining

### ISSUE THREAD

**Issue by UltraCakeBakery** [unocss/unocss#529]
This weekend I am looking in to converting all my personal projects from WindiCSS with FontAwesome to UnoCSS with the Attributify and Icons preset. 

**Problem:**
In one of my Svelte projects I am running in to the problem that Svelte doesn't like `-`, `%` and `<` characters in attribute names. 
The work around is to wrap everything that requires those characters in `class=""`. Example:

```html
    <div absolute left-full p-1 px-2 font-medium text-xs whitespace-nowrap shadow rounded-sm bg-theme text-theme-contrast opacity-0 pointer-events-none transition-all ease-out group-hover:translate-x-2 group-hover:opacity-100 group-hover:delay-200 group-hover:ease-in class="top-1/2 -translate-y-1/2">
        Hello world
        <div absolute left-1 class="top-1/2 -translate-y-1/2 -translate-x-full arrow-left"></div>
    </div>
```

I don't really like wrapping things in `class=""` besides using Attributify, as it kinda defeats the point.

I'm also not a fan of the `group-hover:translate-x-2 group-hover:opacity-100 group-hover:delay-200 group-hover:ease-in` part. In WindiCSS I can do `group-hover:(translate-x-2 opacity-100 delay-200 ease-in)` which has my preference, as it is smaller and easier to read and faster to write.

**Proposed solutions**
For the forbidden characters, It would be great if we could map characters to strings. For example:
`-` => `minus`
`%` => `percent`
`/` => `divided-by`
`<` => `less-then`

This would result in:
`minus-translate-x-10` to be the same as `-translate-x-10`
`top-50-percent` to be the same as `top-50%`
and `width-1-divided-by-4` to be the same as `width-1/4`
`less-then-md:hidden` === `<md:hidden`

For chaining it would be nice if we could specify a separator (null by default, which disables the feature entirely).

Something like `__` would have my preference. This would turn the previous example in to:
`group-hover:translate-x-2__opacity-100__delay-200__ease-in`. It would generate more css, yes. But it would be very convenient, also when just feeding the generator function.

**Comment by chu121su12** [comment]
How about attributify grouping?

- `transform="translate-y-1/2 -translate-x-full"`
- `inset="t-1/2"`
- `group-hover="translate-x-2 opacity-100 delay-200 ease-in"`

**Comment by UltraCakeBakery** [comment]
Not a fan of grouping. I kinda like everything to be boolean attributes. That way it looks like you are enabling a behavior/style, instead of configuring variants/styles. It makes it less clear what is going too imo

**Comment by vipero07** [comment]
Something like this could work for you:

```js
shortcuts: [
  [/^minus-(.*)$/, ([,m]) => `-${m}`],
  [/^(.*)?-percent$/, ([,m]) => `${m}%`],
  [/^(.*)?-divided-by-(.*)$/, ([,m,n]) => `${m}/${n}`],
  //etc
]
```

I don't think this kind of thing belongs specifically in the unocss presets though as the preset goal is to align with windi which aligns itself with tailwind. It could, however, be an additional preset or a community one.

**Comment by chu121su12** [comment]
Or the more powerful version preprocessor

**Comment by domnantas** [comment]
Or if you'd like to optionally use `-` as separators
```js
preprocess: (matcher) =>
	matcher
		.replace(/-?minus-?/, "-")
		.replace(/-?percent-?/, "%")
		.replace(/-?divided-by-?/, "/"),
```
