### ISSUE TITLE
Support for @apply tailwind operator

### ISSUE THREAD

**Issue by rubiin** [unocss/unocss#531]
Hi,
Is there is a way we can reuse styles as TailwindCss does with @apply key

More: https://tailwindcss.com/docs/reusing-styles#extracting-classes-with-apply

**Comment by ccollie** [comment]
see https://github.com/antfu/unocss#shortcuts

**Comment by rubiin** [comment]
thats exactly not the same though. @apply allows you to include the utility classes inside your own class. Shortcuts in unocss are rather used for grouping and you cannot incude them in your css classes

**Comment by uma-uc** [comment]
Yes - @apply feature will be much appreciated. Aside from it being a useful feature, it will also enable to port existing tailwind classes

**Comment by vipero07** [comment]
https://github.com/antfu/unocss#non-goal

It is possible you'd see apply in the next windi, it is a non goal of unocss.

**Comment by rubiin** [comment]
Closing in favor of https://github.com/unocss/unocss/pull/630
