### ISSUE TITLE
Generating styles/icons from AJAX content

### ISSUE THREAD

**Issue by jd-0001** [unocss/unocss#544]
Hi,

I am really satisfied by using unocss and DX it provides. ❤️  Specifically icon preset 😍 

One thing I wanted to know that, can I generate styles for AJAX content? i.e.

1. I get icons list via AJAX request and I want to let unocss know that I also have this icons now and I want to generate style for it
2. Another use case can be, if I fetch HTML via AJAX and render using let's say using `v-html` in vue then we do need to generate styles for that markup.

I guess `@unocss/runtime` can do this but it is experimental as per README. So, I wanted to know what is the correct approach to achieve this.

Thanks :)

Edit: I get icons list via AJAX

**Comment by chu121su12** [comment]
For no. 2, the runtime now has __unocss_runtime.extract(string)

https://github.com/antfu/unocss/blob/a6785d9968c2961be05658481c504de229988294/packages/runtime/src/index.ts#L30-L35

**Comment by jd-0001** [comment]
Hi @chu121su12 

Thanks for responding. I updated the issue body a bit to clarify that I get icons list or class list in AJAX data, not icon styles.

How can I leverage the extract function in my code? Any example?

**Comment by chu121su12** [comment]
Something like this
```js
axios(...)
.then(async (r) => {
  await __unocss_runtime.extract(
    JSON.stringify(r.data) // or r.data.viewTemplate
  );
  return r;
})
.then(...)
```

**Comment by chu121su12** [comment]
Icons should be ok too as long as they're available in preset.

**Comment by jd-0001** [comment]
So I can't do this only using unocss, right?

Do I have to use unocss runtime as well?

**Comment by chu121su12** [comment]
You can add them to safelist to let the compiler pre generate the css

**Comment by jd-0001** [comment]
Thanks.

Before closing I wanted to ask, can I use runtime in production? Readme says it is experimental 🤔

**Comment by chu121su12** [comment]
See #121

**Comment by jd-0001** [comment]
Hi @chu121su12 

Sorry for the confusion. I was referring to unocss runtime instead of core unocss while asking for production.

**Comment by chu121su12** [comment]
What the runtime does is mainly exposing unocss core to the browser environment. So I’d say something similar to the linked issue.

**Comment by jd-0001** [comment]
Thanks for the help :)

I will try it soon and will let you know if something goes wrong.

**Comment by jd-0001** [comment]
Hi @chu121su12 

I tried using unocss runtime with icon preset but I am unable to generate classes for dynamic content.

GitHub repo: https://github.com/jd-0001/vue-unocss

I am getting `{ "icon": "i-mdi-home" }` as a response from a fake API (hosted online thanks to https://mocki.io/fake-json-api). Now, with below code I am unable to make it work:

```ts
fetch('https://mocki.io/v1/cc254402-ebd0-4878-b0a0-4fb4dac0ad09')
  .then(response => response.json())
  .then(data => {
    iconObj.value = data
    __unocss_runtime.extract(data.icon)
  });
```

possible issues:
- I don't know if I have to configure unocss runtime to let it know I have icon preset or I have unocss configured
- unocss runtime config is written in `main.ts` file and not in vite config

**Comment by chu121su12** [comment]
I'm unsure if icon can work on runtime. currently the preset is not part of any runtime presets.

**Comment by jd-0001** [comment]
Thanks for your response. I will keep it open, no worries :)

**Comment by antfu** [comment]
https://github.com/unocss/unocss/tree/main/packages/preset-icons#browser

**Comment by jd-solanki** [comment]
I want to reopen this because I am unable to resolve the dynamic icon issue. Sorry but I am unable to understand what your link refers to.

I have created a reproduction repo: https://github.com/jd-solanki/unocss-dynamic-icons

Regards.

**Comment by jd-solanki** [comment]
Hi @chu121su12,

Sorry for ping but I think we should take a look at this as this issue isn't resolved yet.

**Comment by chu121su12** [comment]
> I'm unsure if icon can work on runtime. currently the preset is not part of any runtime presets.

The [interactive docs](https://uno.antfu.me) has presetIcons enabled by config on runtime. See its config; type some supported icons and watch the network console as the icons get downloaded.

You may have to build your own runtime for now. Follow examples as [the other builds](https://github.com/unocss/unocss/tree/main/packages/runtime/src/cdn) or this [playground](https://unocss.antfu.me/play/?html=DwEwlgbgBAxgNgQwM5ILwCIBmcCmAPKMAFxwFskBaGHAOxICcoArAVySLEwE8raHCaSHEQoAGKPRyIOEHFAAWFTCzhx0APgBQUKKEixEKDGApEA7mQD2TE6QQBzMDApmENEFCQwEuCgBZRUQ1gAHpwCC1Q8K1NIA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAkgMbF2Wo32MCquESgF84WKBBBwA5AFcBLOnSlIkGAB6RY6bAEMZAG3iYc%2BIiWCkAFMi60GMOgC44AbSq2eMfhEsBKTqjUdoys7NbugXQsOvoYzgCMAHQATAGBcCxouM5SABYwMGBOAPTF9CCJdLnFyulC-lQAukj1SEA&options=N4IgzgLgTglgxhEAuAZgQwDZgKYF8g).

**Comment by jahnli** [comment]
@jd-solanki  Have you solved it

**Comment by jd-solanki** [comment]
> @jd-solanki Have you solved it

I haven't tried the above suggestions but I opened another issue https://github.com/unocss/unocss/issues/1359 which requests fallback mode and I guess it might solve this issue.

I have tried that as well 😆 beucase till then I was already moved to Iconify vue component. Using Iconify vue component (with vuetify) allowed me to use any locally installed icons + if someone write or fetch we fetch icon which is not present in installed collection _(maybe someone wrote icons of some another collection)_ then iconify component fetches it from its API.

Isn't it cool 😍 

I hope this is added in unocss with completion on mentioned feature request but I haven't tried UnoCSS fallback mode.

**Comment by jd-solanki** [comment]
@muchenfine You mean how I am getting data _(which in turn renders icon)_ from network request if icon's collection isn't installed?

Do note that I am not using UnoCSS for icons now, I am doing this using [Iconify component](https://docs.iconify.design/icon-components/vue/).
