### ISSUE TITLE
Access to theme in rule Regex before callback

### ISSUE THREAD

**Issue by milesingrams** [unocss/unocss#556]
Some of my rule Regexes are generated by joining theme keys with pipes `|`.
An example of which is:
```new RegExp(`font-family-(?<theme_key>${getThemeRegexGroup('font-family')})$`),```
where `getThemeRegexGroup` takes that theme key and generates a group like `(inter-serif|inter-sans|inter-mono)`
Since this it made outside of the rule callback I don't have access to the merged theme. Was wondering if maybe there could be a function or way to access the merged theme anywhere in the config?

**Comment by chu121su12** [comment]
For now, I think how you do it is to do wildcard match and check the `theme_key` inside the callback. Something like:

https://github.com/antfu/unocss/blob/f395cfd12362c10a12d5c96ae17e166b9597919a/packages/preset-mini/src/rules/typography.ts#L25-L28
