### ISSUE TITLE
Running on the client?

### ISSUE THREAD

**Issue by Zachiah** [unocss/unocss#557]
I'm making a ui builder, and I want the user to be able to use unocss classes in there markup. Is it possible to run unocss on the client and generate the css from a certain string?

**Comment by chu121su12** [comment]
Using runtime, you can see how it is achieved:

https://github.com/antfu/unocss/blob/f395cfd12362c10a12d5c96ae17e166b9597919a/packages/runtime/src/index.ts#L118-L123

**Comment by Zachiah** [comment]
@chu121su12 How is `@unocss/runtime` used?

**Comment by chu121su12** [comment]
The runtime register a mutation observer by itself. But I'm sure there's some dom manipulation quirks that will bypass mutation observer event. That's the weakness of runtime version, in addition to lagging behind the update.

However there's methods to force the css to be updated, regardles of the condition above:

https://github.com/unocss/unocss/blob/f395cfd12362c10a12d5c96ae17e166b9597919a/packages/runtime/src/index.ts#L34-L39

https://github.com/unocss/unocss/blob/f395cfd12362c10a12d5c96ae17e166b9597919a/packages/runtime/src/index.ts#L41-L46

Personally, I use vue's `onRenderTriggered` + `nextTick` to call the `extractAll`.

**Comment by chu121su12** [comment]
Could you make a repo/pen with the reproduction?
