### ISSUE TITLE
Bitbucket icon not working

### ISSUE THREAD

**Issue by toniengelhardt** [unocss/unocss#560]
For some reason the BitBucket icon is not working for me, neither from the `logos` nor from the `vscode-icons` collection:

```json
"@iconify-json/logos": "^1.0.4", 
"@iconify-json/vscode-icons": "^1.0.3",
```

I'm using it like in the example:

```html
<i class="i-logos-bitbucket" />
<i class="i-vscode-icons-file-type-bitbucketpipeline" />
```

All other icons I tested are working:

```html
<i class="i-logos-gitlab" />
<i class="i-logos-github-icon" />
<!-- etc. -->
```

I copied the raw SVG for 'bitbucket' key from `@iconify-json/logos/icons.json` into an <svg /> tag (directly inside the HTML) to see if it works and it does, so the SVG code seems to be valid.

Any ideas?

__Update:__

```html
<i class="i-logos-bitcoin" />
```

is also not working.

That one seems to be missing a `height` attribute in `@iconify-json/logos/icons.json`.

![Screen Shot 2022-01-29 at 19 11 02](https://user-images.githubusercontent.com/2703233/151674303-9722a6c6-4362-41d7-945b-ef7ab20fa41a.png)

**Comment by userquin** [comment]
on [this playground](https://unocss.antfu.me/?html=DwEwlgbgBAFgtAMwK4BsVQC4FMAeG4DGWAdtgE5QIq5QDOW1B%2BxA9sVlAIZoBcGZnYrTAYwbOABYADFIB8AKChRQkKAFtOCpUpXRseOAFYc6BAHcAjDK7EwG7HABGLJMSJxuGG3c4OCL0jgwYgRgkQ5BHwcLWi1tJVcWAlpaRW1gAHpwCDidbKgWAAcAZilMXHwUAHNKM1KytQtc7QAVGA5g2gxBL3EQLA1iECgAQQwWNTACKABhAGU5qBIq4KwAOjSdLMhm3XUAJkpqHCgAKyQusAQAT0IScnKDfZMCkrKYFggsMgBeACIigAOKR-Zo6TibeJQMBwFAsKosWhOESOJAEADWWAwkPi%2BnwwXaZBEOO0MDIWAQ-xgGAwhVoPAyGRWGBgSEca38agyPWQGUSyVofxJSm6ZCqWP%2BAH1HChBOihVCoLJMppIZlsnF1Tt5Fqcjr8pxHLQWCgkNgoM4aRMjFAiVVqXAytQEPgyni7qRvq9SrV6nE%2BgNBMMAO3QoTdUhQUPINDXKAEC7jSYAL0N1B12xyQA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHCjjUrAFxwA2itV7azeqxjUAtOrGpaAGkRxmEMdB20oqZLTIBdA-6kAJRAA&options=N4IgzgLgTglgxhEAuaBXApgXyA) working

**Comment by userquin** [comment]
@toniengelhardt just use `<i class="i-logos-bitcoin></i>`, on previous playground if using `<i class="i-logos-bitcoin" />` not working.

**Comment by toniengelhardt** [comment]
Thanks for looking at it @userquin! Also `<i class="i-logos-bitcoin></i>` doesn't work for me, I have a `Nuxt 3` project with `Vite` and `windicss` and the following config for uno: 

```ts
unocss: {
  uno: false,
  attributify: false,
  preflight: false,
  icons: {
    scale: 1.1,
  },
},
```

Maybe there is a conflict with `windi` or `vite`?

It's weird, BitBucket and Bitcoin both contain the syllable "bit", but I tried also other icons with "bit" in it and they worked.

**Comment by userquin** [comment]
@toniengelhardt try `<i class="i-logos:bitcoin></i>`

**Comment by toniengelhardt** [comment]
Also no luck unfortunately 😔

**Comment by userquin** [comment]
@toniengelhardt try adding an alias on the plugin, for example:
```ts
shortcuts: {
  'my-icon-1': 'i-logos:bitcoin',
  'my-icon-2': 'i-logos:bitbucket',
}
```
then in you html use `class="my-icon-1"` and/or `class="my-icon-2"`

**Comment by toniengelhardt** [comment]
Sorry for the delay! The shortcuts also don't work.

Here is a simple reproduction: [https://stackblitz.com/edit/nuxt-starter-urwt8r?file=app.vue](https://stackblitz.com/edit/nuxt-starter-urwt8r?file=app.vue)

Thanks so much for looking into it 🙏🏽

**Comment by userquin** [comment]
@toniengelhardt it seems it is the windicss plugin (added `vite-plugin-inspect`): https://streamable.com/h7tq0t

You can check it here https://stackblitz.com/edit/nuxt3-iconify-missing-icon-bug-yyk9oc, open the url with `/__inspect` on a new tab once opened outside.

**Comment by userquin** [comment]
@toniengelhardt just exclude `uno.css` variants using `windicss.config.ts` file, check https://stackblitz.com/edit/nuxt3-iconify-missing-icon-bug-yyk9oc?file=windi.config.ts (I don't know why this behavior): 

```ts
import { defineConfig } from 'windicss/helpers'
export default defineConfig({
  extract: {
    exclude: ['/uno.css', '/__uno.css', '/__uno.css?direct']
  }
})
```

![imagen](https://user-images.githubusercontent.com/6311119/151996930-c218cdf9-c0f9-4c21-a825-2c1949f7a6f8.png)

**Comment by toniengelhardt** [comment]
@userquin amazing, it works! Thanks so much for the help!

**Comment by redaabdellah21** [comment]
hi, 
i am trying to use iconify in my Vue app, i have créated an object:

`{
        path: '/',
        title: 'Agenda',
        icon: 'i-material-symbols:calendar-today-outline-rounded',
        isActive: false,
    },`
using it in my view this way:
`<i
                    :class="[route.icon]"
                ></i>`


the problem is that the icon is not showing when i use it this way, but if i use it in the classic way it works fine.

`<i class="i-material-symbols:calendar-today-outline-rounded"><i>`

do you have any idea what could be the problem and how can i solve it? 

thanx in advance.

**Comment by toniengelhardt** [comment]
@redaabdellah21 I think maybe you have to add the icon to the safelist in `unocss.config.ts` like so:

```ts
export default defineConfig({
  safelist: [
    'i-material-symbols:calendar-today-outline-rounded',
  ],
  shortcuts: {
    // ...
  }
})
```

**Comment by toniengelhardt** [comment]
No problem. The way it works I think is by default it scans the templates and generates CSS for all the classes it finds. Everything that you use dynamically via code has to be added to the safelist to be included, otherwise the CSS is not generated.

**Comment by redaabdellah21** [comment]
@toniengelhardt i see, thank you so much for your time.
