### ISSUE TITLE
Is there  a way we can use tailwind plugins in unocss?

### ISSUE THREAD

**Issue by codeitlikemiley** [unocss/unocss#561]
Is there a way I can do use  tailwind plugins?

https://tailwindcss.com/docs/plugins

As per your read me 
```
UnoCSS is designed NOT to be/have:

A CSS preprocessor (e.g. @apply) - but you can use shortcuts.
Tailwind's plugin system - but you can write custom rules in seconds and share them as presets!

```

So i guess we need to use custom rules ?

I hope we can have community custom rules that translate existing tailwind plugins to unocss rules

or simple a config where we can easily use tailwind plugins

this is a good feature in the sense all tailwind users can just easily use the tailwind plugins 

without even creating custom rules, coz some plugins are really hard to put in config 1 page file.

**Comment by chu121su12** [comment]
Which plugin did you use most often?

**Comment by codeitlikemiley** [comment]
tailwind forms , tailwind aspect ratio and typography...

i believe you already have the preset for typography

**Comment by chu121su12** [comment]
aspect ratio is already built in, while forms you can copy the css and use it as preflight

**Comment by feitian124** [comment]
i  want use [daisyui](https://github.com/saadeghi/daisyui).

is there a guide about how to translate existing tailwind plugins to unocss rules?

**Comment by antfu** [comment]
Sorry no. We won't support tailwind's plugin interface, but I believe they will be straight forward to create presets with similiar functions. FYI, we have typography preset. Aspect ratio and animations built-in in preset-wind/preset-uno.

**Comment by CharlesOkwuagwu** [comment]
> while forms you can copy the css and use it as preflight

Please do you have a sample of where we could copy this from as you mentioned?

I have used '`windicss/plugin/forms`', in another project, but could not isolate all the form-specific CSS to re-use as you mentioned.

**Comment by shellscape** [comment]
@antfu I'm evaluating unicss for use in https://jsx.email. Twind was on my radar but it's no longer maintained. Would it be possible to get a doc authored that explained clearly how people who have written custom tailwind plugins should migrate to a preset? Would be immensely helpful to point users to.
