### ISSUE TITLE
unocss config for setting  arrays of globs/pattern to watch with outfile name?

### ISSUE THREAD

**Issue by goldcoders** [unocss/unocss#566]
I'm using unocss cli

and for me to generate css from html i need to do this

```
 "unocss": "unocss \"layouts/**/**/*.html\" --watch -o ./assets/css/uno.css",
```

is there a way i can passed multiple instance of 
paths to watch and output file name?

is there a unocss.config for this?

i dont wanna end up with my solution like this

```
 "uno-home": "unocss \"layouts/index.html\" --watch -o ./assets/css/home.css",
"uno-blog": "unocss \"layouts/blog/*.html\" --watch -o ./assets/css/blog.css",
"css-watch": "run-p uno-home uno-blog"
```

just to generate a css for home.css, blog.css

and watch 2 instance in parallel to create 2 files....

i think it would be great if we can pass on the unocss.config.ts/js

an array of path patterns to watch and paths to output the file css

I think it has good usecase for jamstacks , espcially hugo framework...

but the config now dont have that features

**Comment by sudongyuer** [comment]
I am working on this
