### ISSUE TITLE
Support for config not in project root vscode plugin

### ISSUE THREAD

**Issue by Zachiah** [unocss/unocss#573]
I'm frequently working in a monorepo setup in which the vite config isn't in the root, but is in a subpackage. If I have the whole repo open in vscode, the plugin won't detect the config. The only solution I've found is putting a uno.config.ts in the monorepo root just for the purpose of telling the uno plugin to start

**Comment by harrytran998** [comment]
Yeah, the same with me! But currently, it's acceptable BCS the human resources of this project is OSS :v

**Comment by antfu** [comment]
Supported https://github.com/unocss/unocss/blob/8bd428447b1f290f9d5656f3ee42df216bcfe563/packages/vscode/package.json#L30-L33
