### ISSUE TITLE
h-screen-xx rule may be missing

### ISSUE THREAD

**Issue by gwsbhqt** [unocss/unocss#591]
https://github.com/unocss/unocss/blob/f08765a559a491fed45b1dbec7fa802c5694319e/packages/preset-mini/src/rules/size.ts#L37

w-screen-xx rule is exist, but h-screen-xx is missing.

the regex may be written as `/^(min-|max-)?([wh])-screen-(.+)$/`, isn't it?

please forgive if I'm wrong.

**Comment by chu121su12** [comment]
What do you expect the output on each breakpoints? So when you write `h-screen-sm` or  `-lg`, what should the css look like?

**Comment by gwsbhqt** [comment]
@chu121su12 

Honestly, because unocss documentation is incomplete, I am using windicss preset and documents instead. 

In [windicss](https://windicss.org/utilities/layout/sizing.html#height), exist h-screen breakpoint, for reference only.

Even without reference to other documentation, it is intuition that paired breakpoints should be provided, and if there is a w-screen breakpoint, a symmetric h-screen breakpoint should also be provided.

**Comment by gwsbhqt** [comment]
There is some truth to what you said, I look forward to your thinking more carefully, thank you.

**Comment by gwsbhqt** [comment]
Thanks for your work and answers.
