### ISSUE TITLE
utility/variant groups

### ISSUE THREAD

**Issue by dragonwocky** [unocss/unocss#594]
[WindiCSS's variant groups feature](https://windicss.org/features/variant-groups.html) is pretty handy. It lets you group utilities while still containing everything within the `class` attribute (for users like me who prefer not to use the attributify mode).

E.g.
`font-bold m-4 dark:(font-blue text-lg hover:(p-8 h-full)) focus:(w-12 px-18)`
becomes
`font-bold m-4 dark:font-blue dark:text-lg dark:hover:p-8 dark:hover:h-full focus:w-12 focus:px-18`

Obviously, these are very random utilities, but it'd be a convenient addition to Uno. I've written a simple expansion function that uses a bit of regex and recursion to safely expand variant groups- at the moment, I'm just using it within a custom extractor.

Is this something I should/could open a PR to add to Uno? Whereabouts would I add that? (I'd imagine as part of one of the presets?)

Is there a better place for it than within an extractor? It might be nice to add it as some sort of pre-extractor, that expands any utilities within the code and then hands off the modified code to the extractors for them to do their thing.

**Edit:**

Just after I created this issue I remembered that, of course, expanding variant groups within an extractor leaves you the problem of the actual classes within the source not being expanded.

I've refactored the way I'm using Uno to handle that, wrapping the generator within a template function that will expand the string, pass it on to the generator, and then return the modified className, e.g.
```tsx
<p class={uno`font-bold m-4`}></p>
```

This works pretty well as far as I can tell, but I'm no longer certain if this could be integrated within Uno/an Uno preset? It'd be a shame if every user had to manually/separately handle it this way.

**Edit 2/3:**

After a little bit of tweaking, this can be used for general utility grouping, not only variant grouping.

`font-(bold mono) m(y-4 x-3) dark:(font-blue hover:(p-8 h-full))`
becomes
`font-bold font-mono my-4 mx-3 dark:font-blue dark:hover:p-8 dark:hover:h-full`

**Edit 4:**

[Implementation](https://github.com/dragonwocky/nadder/blob/8c9aff512b929b1fdb278568247ba1593e50cb84/ssr.tsx#L90-L124)

Usage: 
```tsx
const { uno, sheet } = unoInstance();
<>
  <p class={uno`font-bold m(x-3 y-4) hover:(text-red underline cursor-pointer)`}>
    Hover me!
  </p>
  {await sheet()}
</>;
  ```

**Comment by veritem** [comment]
[Attributify preset](https://github.com/unocss/unocss/tree/main/packages/preset-attributify) does that. 

```ts
import presetAttributify from '@unocss/preset-attributify'

Unocss({
  presets: [
    presetAttributify({ /* options */ })
    // ...other presets
  ]
})
```
```jsx
<button 
  bg="blue-400 hover:blue-500 dark:blue-500 dark:hover:blue-600"
  text="sm white"
  font="mono light"
  p="y-2 x-4"
  border="2 rounded blue-200"
>
  Button
</button>
```

**Comment by dragonwocky** [comment]
@veritem attributify is great, and useful in some situations, **but it is not equivalent to variant grouping.**

Variant grouping is a) specifically for variants, and b) _can be used within a class name._ This is particularly useful if you have other processors running as well (either during generation or at runtime) or would like to avoid non-standard element attributes.

I did mention in the original message I "prefer not to use the attributify mode".

**Comment by chu121su12** [comment]
@dragonwocky Maybe you could check out how attributify grouping works and port it to be used as a general purpose grouping? I’m sure it works similarly

**Comment by gwsbhqt** [comment]
I also had the same problem.

Writing too many repeated prefixes when writing styles for before and after placeholders.

**Comment by dragonwocky** [comment]
@chu121su12 I've had a look, and I don't think it would work.

The CSS generated by attributify mode matches the attributes directly. This works well because a) you can't nest attributes, and b) you can test for inclusion of a value with CSS attributes. 

E.g.
```html
<div absolute p="y-5 x-4"></div>
```
```css
/* layer: default */
.absolute,
[absolute=""]{position:absolute;}
[p~="x-4"]{padding-left:1rem;padding-right:1rem;}
[p~="y-5"]{padding-top:1.25rem;padding-bottom:1.25rem;}
```

This unfortunately doesn't transfer across well to groups within the `class` attribute, because a) they *can* be nested, and b) though you can test if the `class` contains an individual utility, selectors to match a utility within a group would get very complicated.

To be clear, **I have a working solution.** Expanding classes prior to Uno doing its thing is simple, fast, and reliable. The only shortcoming to this is it requires expanding classes within the HTML as well, but there are plenty of options for that:
- If at runtime, then a simple `$.className = expandVariantGroup($.className)` will do the trick.
- If using JSX or [JSX-like syntax](https://github.com/developit/htm), then processing classes as they are generated will work (e.g. `<p class={expandVariantGroup('m-4 hover:(font-bold text-red)'}></p>`).
- If using a static site generator, there'll usually be a way to post-process pages through which class name expansion could be done.

My question here is not *how* to do it, but if it fits into Uno somehow and if it does, which part of it I should make a PR to.

**Comment by chu121su12** [comment]
I now realized it is difficult to be done directly without source modification, especially with nested grouping. My guess it could be added in the vite sub package but this would be moving away from the core usage.

**Comment by rubiin** [comment]
This is a nice to have feature for someone as me migrating from windicss
