### ISSUE TITLE
Suggestion: How about adding scope field to vite plugin?

### ISSUE THREAD

**Issue by young-do** [unocss/unocss#607]
Hi
How about adding "scope" field only in "global mode" as shown below?

```js
// vite.config.js
export default defineConfig({
  plugins: [
    unocss({
      ...
      mode: 'global',
      scope: {classname or something} // 👈
    }),
  ],
  ...
}
```

The reason for this suggestion is that rather than separate layers using prefix, it would be better to limit scope and use utility classes only under a specific class name.
I think it's too much of a hassle to continuously attach prefix beyond performance issues.
I found that the scope field is used internally(`uno.generate(code, { scope: ... })`), but I can't use it from outside.

Thanks

**Comment by chu121su12** [comment]
There's recent PR #612 that should help with this. Otherwise, feel free to open a PR for the plugin implementation.

**Comment by young-do** [comment]
@chu121su12 
#612 PR helped a lot.
Thanks to you, I was able to solve it in the following way:

```ts
export default defineConfig({
  plugins: [
    unocss({
      variants: [
        function (matcher) {
          return {
            matcher,
            selector: s => `${classname or something} $$ ${s}`,
          };
        },
      ],
    }),
  ],
});
```
