### ISSUE TITLE
Adding import  of 'uno.css' in SvelteKit's __layoute.svelte file causes error only in Safari.

### ISSUE THREAD

**Issue by dioxine** [unocss/unocss#618]
Hello. When i do usual import of uno.css like `import 'uno.css'` in `__layoute.svelte` of `SvelteKit`, i get  strange `"Cannot access uninitialized variable"` error directly in browser window, not in console, but this is only in Safari. After doing some HMR change, Vite renders page  and works ok, but after doing full reload page, error comes again.  Chrome and Firefox are working normally. Putting this import not in `__layout.svelte` but into `index.svelte` for example - also works as expected even in Safari.
So i found a kind of solution to dynamically import uno.css in `__layout.svelte` and get it working in Safari:
```js
import { onMount } from 'svelte';

onMount(async () => {
	await import('uno.css');
});
```
but im not sure im doing right.

for testing and reproduction purposes [https://github.com/dioxine/svelte-unocss.git](https://github.com/dioxine/svelte-unocss.git)

my setup:
NodeJS v16.13.0 
SvelteKit v1.0.0-next.272
Safari v15.3
macOS Catalina v10.15.7

**Comment by antfu** [comment]
Fixed.

**Comment by 524c** [comment]
> Hello. When i do usual import of uno.css like `import 'uno.css'` in `__layoute.svelte` of `SvelteKit`, i get strange `"Cannot access uninitialized variable"` error directly in browser window, not in console, but this is only in Safari. After doing some HMR change, Vite renders page and works ok, but after doing full reload page, error comes again. Chrome and Firefox are working normally. Putting this import not in `__layout.svelte` but into `index.svelte` for example - also works as expected even in Safari. So i found a kind of solution to dynamically import uno.css in `__layout.svelte` and get it working in Safari:
> 
> ```js
> import { onMount } from 'svelte';
> 
> onMount(async () => {
> 	await import('uno.css');
> });
> ```
> 
> but im not sure im doing right.
> 
> for testing and reproduction purposes https://github.com/dioxine/svelte-unocss.git
> 
> my setup: NodeJS v16.13.0 SvelteKit v1.0.0-next.272 Safari v15.3 macOS Catalina v10.15.7

Yes, it solves the bug with Safari, but unfortunately it has a [side effect, FOUC](https://en.wikipedia.org/wiki/Flash_of_unstyled_content).
