### ISSUE TITLE
How to cope with conditional classes

### ISSUE THREAD

**Issue by jd-0001** [unocss/unocss#622]
Hi,

I am trying to build my own tiny component library and I button which accepts color prop and adds `bg-<color>` class to the button element.

The problem is unocss can't generate a style of it. Adding it to safelist can be an instant solution but what if their hex code passed as prop:
```html
<x-button color="#000">...</x-button>
```

If we don't provide dynamic values like above and create theme pallets like primary, success, etc then we have to write tones of safelist string.
```js
safelist: ['bg-primary-100', ..., 'text-primary-100', ..., 'border-primary-100']
```

I wanted to know how can I overcome this issue.

One thought that came to my mind is to instead of accepting a list of string we can accept the function is possible which also provide the final config of unocss as a parameter.

```js
safelist: (config) => [
  ...config.colors.map(c => `bg-${c}-500`)
]
```

I also have a sample repo: https://github.com/jd-0001/unocss-conditional-test

Regards.

**Comment by jd-0001** [comment]
I guess, I better ask how can I ship unocss along with my component library because I only want to generate `bg-primary` or `bg-primary-500`class if the user actually uses the button or any component which has bg-primary like class.

Does anyone have any idea or suggestion?

**Comment by chu121su12** [comment]
How about using shortcuts?

https://github.com/unocss/unocss#shortcuts

**Comment by jd-0001** [comment]
Hi @chu121su12 

I tried using shortcuts and it is resolving the issue. However, I have few queries.

1. Regarding shortcuts, Don't you think creating new classes for each component adds unnecessary CSS. (i.e. `btn-primary`, `alert-primary`).
2. I guess unocss don't scan the source code so I thought I will resolve the conditional classes which is the downside of windi & tw. I want to know what does the unocss scan for if not the source code so I can leverage it.

Awaiting your response.

**Comment by antfu** [comment]
https://windicss.org/guide/extractions.html#extractions

**Comment by jd-0001** [comment]
Thanks for the info. I will use:

```js
safelist: (config) => [
  ...config.colors.map(c => `bg-${c}-500`)
]
```

**Comment by phiberber** [comment]
> https://windicss.org/guide/extractions.html#extractions

How would this work with attributify mode? 
`<div :text="active ? 'green-400' : 'orange-400'" />`

**Comment by tomardern** [comment]
@phiberber I found that this works:
```
safelist: [
	'[text="right"]'
]
```
