### ISSUE TITLE
Error with vitest

### ISSUE THREAD

**Issue by rubiin** [unocss/unocss#632]
when I run test with vitest, I get the following error
`entry module not found, have you add `import 'uno.css'` in your main entry`
My main.ts has import 
`import 'uno.css'`

**Comment by veritem** [comment]
Can you please share a  link to repro?

**Comment by rubiin** [comment]
https://github.com/rubiin/vitely

**Comment by veritem** [comment]
I included `import "uno.css"` in `test/basic.test.ts` and it's not showing warning anymore.

**Comment by rubiin** [comment]
The question is should  I be adding it on test files? That doesnt make sense as its already included in the src main.ts
