### ISSUE TITLE
Error when used in Deno

### ISSUE THREAD

**Issue by tmikaeld** [unocss/unocss#633]
Using it via esm.sh, gives this error:

error: Loading unprepared module: https://cdn.esm.sh/v66/@unocss/preset-icons@0.25.0/deno/fs.js

**Comment by tmikaeld** [comment]
Could we get support for Deno so it can be used as a simple atomic processor, like this:
https://github.com/TomokiMiyauci/mapcss

**Comment by veritem** [comment]
@tmikaeld  Have you tried using our cli?

**Comment by tmikaeld** [comment]
I got it working by using createGenerator, however, generated classes don't match that of the UnoCSS playground. Does UnoCSS infer usage from the html tags too?

**Comment by veritem** [comment]
Yes, it does,
How does your setup look like could you please share with us a repro link?

**Comment by tmikaeld** [comment]
I'm on a private repo unfortunately, it would be fine also if we could generate the CSS by feeding unocss with a HTML string. Does it require a DOM to work?

**Comment by tmikaeld** [comment]
Ah, I see, .generate takes a full HTML string. I mistakenly thought it only took the css class names 😄

**Comment by tmikaeld** [comment]
How close is UnoCSS to production ready?

**Comment by tmikaeld** [comment]
Hm, noticed that it takes 150ms to generate from a 76kb html file, 2555 utilities total. Seems slower than expected?

**Comment by antfu** [comment]
We just refactored out the `./fs` module with https://github.com/unocss/unocss/pull/730

Not sure if it will work in Deno tho. But since we are not using Deno, contributions welcome.

**Comment by tmikaeld** [comment]
Deno can't use the fs module anyway, so it should be just fine 👍

**Comment by ije** [comment]
nice!

**Comment by ije** [comment]
```ts
import presetIcons from "https://esm.sh/@unocss/preset-icons@0.30.3?no-require";
import carbonIcons from "https://esm.sh/@iconify-json/carbon@1.1.2/icons.json" assert { type: "json" };

presetIcons({
  collections: {
    carbon: () => carbonIcons,
  },
})
```

this works in Deno now, but need `?no-require` to avoid import `@iconify/utils/lib/loader/node-loader.cjs`
