### ISSUE TITLE
Make cli standalone binary

### ISSUE THREAD

**Issue by veritem** [unocss/unocss#634]
Making cli a stand-alone binary can open doors for unocss to be used in other projects like ruby on rails or laravel not node related

**Comment by veritem** [comment]
What if you don't have nodejs installed on your system?

**Comment by antfu** [comment]
I think this is a non-goal. UnoCSS is meant to be a Node.js package and I don't think it make sense to use it without Node.js. Feel free to bundle it to binrary to fix your need on your own, or create a community package that we might be able to link to. Thanks.
