### ISSUE TITLE
`setWarnTimer` is too aggressive

### ISSUE THREAD

**Issue by aleclarson** [unocss/unocss#637]
This warning is accidentally logged when the optimizer doesn't run due to a consistent hash. If we wait for the first `transformIndexHtml` hook to be called, this won't happen.

https://github.com/unocss/unocss/blob/aea7b13883fc0b80fa1313368dc1d354e141a93b/packages/vite/src/modes/global/dev.ts#L57-L72

### Suggested solution

1. Rename it to `warnMissingImport` and remove the `setTimeout` stuff.
2. Call it from one of the `transformIndexHtml` hooks.
```ts
function warnMissingImport() {
  if (!resolved) {
    const msg = "[unocss] entry module not found, have you add `import 'uno.css'` in your main entry?";
    console.warn(msg);
    servers.forEach(({ ws }) => ws.send({
      type: "error",
      err: { message: msg, stack: "" }
    }));
  }
}
```

**Comment by antfu** [comment]
Ok, PR welcome :)

**Comment by anujdatar** [comment]
I too see this error often, and Unocss doesn't load, none of the style classes work. Just re-saving `unocss.config.ts` seems to temporarily fix things, without making any changes. I am using a slightly modified Vitesse starter template, but I haven't touched the Unocss config.
