### ISSUE TITLE
Feature: make all classes important

### ISSUE THREAD

**Issue by rubiin** [unocss/unocss#642]
Currently we can make individual class rules important by prefixing them with `! `. It would be nice to have a config on unocss config to make all classes important so you dont have to prefix everyone with `!` . People coming from tailwind will find this pretty useful

**Comment by wheatjs** [comment]
Any particular reason you might want this? Seems like if every class is important then none of them are important

**Comment by rubiin** [comment]
Only applied classes should be important. Similar to how tailwind classes behave.

**Comment by wheatjs** [comment]
Still why would you want that though? It would make it impossible to override classes on reusable components

**Comment by rubiin** [comment]
That would ease migrating from tailwind easier.

**Comment by chu121su12** [comment]
I'm sure tailwind doesn't set important by default. Bootstraps' does.

**Comment by fylica** [comment]
Tailwind has `important: true` setting in its `tailwind.config.js` file to set them all important.
The use case is, let say I'm using a UI framework in a Vue project, say Quasar Framework or Vuetify, but I am not happy all the helper css helpers shipped with them. Therefore I want to use a unocss feature over their styles and all of the unocss/tailwind styles I am using should be important.

**Comment by chu121su12** [comment]
For now, try [preprocess](https://github.com/unocss/unocss#utilities-preprocess--prefixing) to append the important variant. Something like:

```js
preprocess: (t) => {
  if (t.includes('!')) return t;
  return `!${t}`;
}
```

**Comment by antfu** [comment]
You could either use preprocess or postcess to achieve your goal. Since we are utils agnostic, we probably won't provide an option for that by default.

**Comment by hellohejinyu** [comment]
> Any particular reason you might want this? Seems like if every class is important then none of them are important

https://github.com/vitejs/vite/issues/3924 Due to a bug in Vite (which seems hard to fix), unocss cannot override existing component styles. So at this time, it would be very useful if all unocss styles have `!important`.Fortunately, `preprocess` solved this problem.

**Comment by LeCoupa** [comment]
@hellohejinyu how did you do it with `preprocess`? :) I am struggling with it

**Comment by hellohejinyu** [comment]
> @hellohejinyu how did you do it with `preprocess`? :) I am struggling with it

```js
// uno.config.ts
export default defineConfig({
  preprocess: (t: string) => {
    if (t.includes('!')) {
      return t
    }
    return `!${t}`
  },
}
```
