### ISSUE TITLE
grid-cols-[xxx] parsed incorrectly to CSS

### ISSUE THREAD

**Issue by jefflam** [unocss/unocss#645]
First off, love all the work you guys do :)

Currently using the latest version of UnoCSS via Vitesse.

Attempting to create a grid layout as so:

```
<li grid="~ cols-[1fr,2fr]">
          <div>
            <img src="icon.svg" alt="Icon">
          </div>
          <div>
            <span>Menu 1</span>
          </div>
        </li>
```

Seems like the compiler recognizes `cols-[1fr,2fr]` and turns it into `grid-template-columns: 1fr,2fr`, but incorrectly not remove the `,` between `1fr` and `2fr` which results in a CSS error. Attempting to write `cols-[1fr 2fr]` results in the compiler not recognizing it.

Would this be considered a bug in the preset? I've not added any other presets or anything btw

**Comment by hannoeru** [comment]
Use `cols-[1fr_2fr]` instead, `_` will be replaced to space.
