### ISSUE TITLE
@apply is not transformed in CSS style

### ISSUE THREAD

**Issue by pierredewilde** [unocss/unocss#649]
Tested with SvelteKit fixture 
https://github.com/unocss/unocss/tree/main/test/fixtures/sveltekit

Transformer-directives
https://github.com/unocss/unocss/tree/main/packages/transformer-directives

Install transformer-directives package (v0.26.2)
`$ npm i -D @unocss/transformer-directives`

Add transformer-directives in `svelte.config.js`
```
...
import UnoCss from 'unocss/vite'
import transformerDirective from '@unocss/transformer-directives'
...
const config = {
  ...
  kit: {
    adapter: adapter(),
    vite: {
      plugins: [
        UnoCss({
          ...
          transformers: [
            transformerDirective()
          ]
        })
      ]
    }
  }
}
...
```

### Steps to reproduce
in `src/routes/__layout.svelte` 
- replace `<main class="text-center p-1em my-0 mx-auto">` by `<main>`
- in `<style>`, replace `main {}`by `main { @apply text-center p-1em my-0 mx-auto; }`

### Actual result
main style is not transformed (checked with Chrome DevTools Styles)
```
main.s-PoaHcXV6SIWL {
  @apply text-center p-1em my-0 mx-auto: ;
}
```

### Expected result
main style should be transformed
```
main.s-PoaHcXV6SIWL {
  text-align: center;
  padding: 1em;
  margin-top: 0rem;
  margin-bottom: 0rem;
  margin-left: auto;
  margin-right: auto;
}
```

**Comment by antfu** [comment]
https://github.com/sveltejs/kit/issues/4125#issuecomment-1052473818

**Comment by pierredewilde** [comment]
Thank you.

**Comment by pierredewilde** [comment]
It works with `vite-plugin-svelte` 1.0.0-next.38+.

But when using variants (eg hover:) with @apply, I got a `Semicolon or block is expected` error.
