### ISSUE TITLE
Add support for `@apply` with complex classes that use colons like `hover:bg-green-200`

### ISSUE THREAD

**Issue by jacob-8** [unocss/unocss#664]
Thanks for adding the `@unocss/transformer-directives` that supports using `@apply ...` inside of style tags! I do want to mention that in a SvelteKit project it doesn't work for complex classes that use colons unfortunately, so `@apply bg-green-100 hover:bg-green-200` will not work presently.

Tailwind had this issue for a long time and solved it finally in 2020. Perhaps the solution for this could be pulled from their resolution of the same issue, https://github.com/tailwindlabs/tailwindcss/pull/2159 may be a good starting point.

**Comment by chu121su12** [comment]
@jacobbowdoin The variant syntax isn't limited to colon `hover:x` and you can try with a regular dash `hover-x`

**Comment by pierredewilde** [comment]
Related to [@apply is not transformed in CSS style #649](https://github.com/unocss/unocss/issues/649)

Regular dash `hover-x` is indeed a workaround.

It would be great if normal Tailwind CSS variant syntax `hover:x` is also supported.

**Comment by mshamaseen** [comment]
hmmm, any fix for this so far?

**Comment by mshamaseen** [comment]
I'm trying to set `!important` to apply directive but it throws an error
`@apply bg-gray-100 rounded p-2 text-gray-800 outline-gray-400 !important;`

` Error: expected ";".`

**Comment by chris-zhu** [comment]
> I'm trying to set `!important` to apply directive but it throws an error
> 
> `@apply bg-gray-100 rounded p-2 text-gray-800 outline-gray-400 !important;`
> 
> 
> 
> ` Error: expected ";".`

well, you shouldn't add the important variant to the tokens end, rather than like  `@apply bg-gray-100! important-rounded ...;`
