### ISSUE TITLE
Intellisense in vscode

### ISSUE THREAD

**Issue by Zenthae** [unocss/unocss#671]
Hello, is there a way to get intellisense at all in vscode ? I've seen some past issues talk about that but I've also seen other people post issue with `.gif` showing auto-complete

**Comment by milos018** [comment]
You can try three different extensions in VSCode: UnoCSS, WindiCSS, TailwindCSS. They should give you autocompletion.

**Comment by Zenthae** [comment]
Oh, you need to install Wind/Tail extension too ? i thought that Uno was enough to do the job
