### ISSUE TITLE
`@unocss/preset-wind` 构建失败

### ISSUE THREAD

**Issue by Kritsu** [unocss/unocss#672]
在unocss 0.2.7中 unocss/preset-wind这个包依然存在构建失败的问题，之前的ISSUE #654 

![image](https://user-images.githubusercontent.com/16945858/156218962-4d1832f2-ec70-4889-a25c-10304d3901c8.png)

系统环境: Windows 11  10.0.22000 (根据其他的PR #659 和ISSUES的消息，**该问题可能仅在Windows系统中发生**)

经过我的测试，在unocss的packages中，似乎只有unocss-preset-wind会发生构建失败的问题

而且被**unocss/preset-wind**所依赖的**unocss/core**和**unocss/preset-mini**，以及依赖于其的**unocss/preset-uno** 都能成功构建

![image](https://user-images.githubusercontent.com/16945858/156219266-75af5080-00d9-4cd5-b6f3-ffb68ede6ae6.png)

这个问题似乎是因为unocss/preset-wind -> unocss/core -> unconfig -> jiti 被加入到了构建中

**在preset-wind的build.config.ts中加入和unocss/core相同的配置可以临时解决这个问题**

![image](https://user-images.githubusercontent.com/16945858/156223885-68e5daab-6f8b-4cfc-8636-52f49571e67e.png)

**代价是unocss/core的dts内容会被打包到preset-wind的dts中**

![image](https://user-images.githubusercontent.com/16945858/156229927-e7cda88e-64bf-43a9-8972-7bef9081c335.png)

@antfu

**Comment by userquin** [comment]
@Kritsu we're fixing it, there is a problem on `unbuild`, check https://github.com/unocss/unocss/pull/659
