### ISSUE TITLE
Nuxt JavaScript not work after build

### ISSUE THREAD

**Issue by ririen** [unocss/unocss#676]
Nuxt 3 is affected.

Everything works fine on the development version, every JavaScript function in `<script setup>` and styles.

However, after building `nuxi build` and running `nuxi preview`, there are bad references to styles (which are not needed?), a bit strange situation because the page displays perfectly normal and works with CSS, but JavaScript does not work in it because Nuxt throws an error.

It's an unocss problem, I checked. After removing `unocss` from `buildModules` and replace it to e.g. `windicss`, no problem.

![Zrzut ekranu z 2022-03-02 12-55-31](https://user-images.githubusercontent.com/18102267/156357963-66a761fc-e015-4d8c-ae6f-8f48be03680c.png)

**Comment by antfu** [comment]
Same as the request in the Nuxt issue, reproduction is needed in order to investigate.
