### ISSUE TITLE
@unocss/preset-typography never do not render ol li 

### ISSUE THREAD

**Issue by veritem** [unocss/unocss#679]
[@unocss/preset-typography](https://github.com/unocss/unocss/tree/main/packages/preset-typography)  doesn't apply any style to `ol li` elements

**Comment by ydcjeff** [comment]
Yes, it doesn't have any styles for `li`.

**Comment by veritem** [comment]
why @ydcjeff ?

**Comment by ydcjeff** [comment]
Because I found browser's default styles good enough.

**Comment by veritem** [comment]
There isn't browser defaults when you've used tailwind reset.

**Comment by ydcjeff** [comment]
I see. PR welcome.

**Comment by veritem** [comment]
Not sure why it's not fixed

**Comment by ydcjeff** [comment]
It has not released yet.
