### ISSUE TITLE
Safelist not working together with Attributify

### ISSUE THREAD

**Issue by phiberber** [unocss/unocss#684]
Playground: [Click here](https://unocss.antfu.me/?html=DwEwlgbgBAZgNgUwB5TAFwQWwM4F4BEAxggHYYBOAtAIZprlgBGArhpSQPZqVgmFzMQCEPigB6AHxA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnAJCth6VGOCsYALjgBtAETAYqEKwC0zVFnNRjAXU6kAlEA&options=N4IgzgLgTglgxhEAuaBXApgXyA)

A lot of times we need to use dynamic values that the compiler can't really guess, that's why safelist is of good use, but seems that safelist will not add the rules to represent attributes, even when using the attributify plugin. The playground above shows a little example, where you can see that in the CSS only the `[flex=""]` and `.items-center` are included.

**Comment by antfu** [comment]
```js
import { defineConfig } from 'unocss'

export default defineConfig({
  safelist: ['[items="center"]']
})
```

https://unocss.antfu.me/?html=DwEwlgbgBAZgNgUwB5TAFwQWwM4F4BEAxggHYYBOAtAIZprlgBGArhpSQPZqVgmFzMQCEPigB6AHxA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnAJCth6VGOCsYALjgBtWoeAxUIVgF4ARM1RZzUGwF1aLzqQCUQA&options=N4IgzgLgTglgxhEAuaBXApgXyA
