### ISSUE TITLE
How to enable @unocss/transformer-directives and @unocss/transformer-variant-group in @unocss/nuxt

### ISSUE THREAD

**Issue by chrislutw** [unocss/unocss#690]
Hi, I want to using @unocss/transformer-directives and @unocss/transformer-variant-group in nuxt2 app

my env: 
- OS: windows 10
- node: 14.18.2
- pnpm: 6.32.3
- nuxt: 2.15.8
- @unocss/nuxt: 0.27.4
- @unocss/transformer-directives: 0.27.4
- @unocss/transformer-variant-group: 0.27.4

and setting like this
```js
// nuxt.config.js
import transformerDirective from '@unocss/transformer-directives'
import transformerVariantGroup from '@unocss/transformer-variant-group'

export default {
target: 'static',
buildModules: [
  '@unocss/nuxt'
],
...
unocss: {
  uno: true,
  attributify: true,
  preflight: true,
  icons: {
    scale: 1.2,
  },
  transformers: [
    transformerDirective(),
    transformerVariantGroup(), 
  ]
}
...
}
```

```vue
<template>
  <main class="text-center py-20 px-10">
    <nuxt />
    <div class="custom-div">test</div>
  </main>
</template>

<style>
.custom-div {
  @apply font-medium my-0 text-center;
}
</style>
```

the result as this picture, `@apply` not working.

![image](https://user-images.githubusercontent.com/18047748/157653955-9d510486-6397-496c-abef-fae9a2a6750f.png)

**Comment by hannoeru** [comment]
Currently transformers only works with Vite plugin, so you will need Nuxt Bridge or Nuxt 3.

https://github.com/unocss/unocss/tree/main/packages/nuxt#supporting-status

**Comment by chrislutw** [comment]
thx, i should to using @unocss/icon only, and get nuxt/windicss or tailwind
