### ISSUE TITLE
Sometimes unocss style are not works on first time running

### ISSUE THREAD

**Issue by aliuq** [unocss/unocss#691]

**Comment by antfu** [comment]
Probably cuased by presetWebFonts. Need to investigate further.

**Comment by antfu** [comment]
Should be fixed in v0.27.6

**Comment by aliuq** [comment]
On Windows 11, it exists in v0.28.0 yet, I used vitesse-lite.

repeat `pnpm dev` more times, they are not works.

**Comment by lainbo** [comment]
I also have the same problem, when I use pnpm
The current version of unocss is 0.45.13
`nx taze -w`
`ni` (Must have update)
`nr`
it will definitely have this issue.
I checked that it only generated part of the class

**Comment by lizy-CZ** [comment]
I have the same problem in 0.46.3 by first run dev. Change some class, like: top-[50%] => top-[49%] , the bug is gone.

**Comment by lainbo** [comment]
> I have the same problem in 0.46.3 by first run dev. Change some class, like: top-[50%] => top-[49%] , the bug is gone.

You can try upgrading. This problem has not been encountered in the new version
