### ISSUE TITLE
@apply 在嵌套的样式中不起作用

### ISSUE THREAD

**Issue by izhaoqing** [unocss/unocss#694]
```vue
<style lang="less" scoped>
.text {
  span {
    @apply text-black;
  }
}
</style>
```

生成的 CSS:

```css
.text span[data-v-7853adf1] {
    @apply text-black: ;
}
```

**Comment by hannoeru** [comment]
Can you provide a repo with the code required to reproduce this issue?

**Comment by izhaoqing** [comment]
https://github.com/izhaoqing/unocss-demo

![image](https://user-images.githubusercontent.com/23057194/157848906-0050ba08-d64e-4b72-9cd9-f384e18f159f.png)

**Comment by hannoeru** [comment]
Currently we don't support parsing nested classes, still working on it.

**Comment by hannoeru** [comment]
With PR #695 and #697 it should works with `less`.

**Comment by izhaoqing** [comment]
👍

**Comment by bhvngt** [comment]
@hannoeru Thank you for your PR. How one can use [postcss-nesting](https://www.npmjs.com/package/postcss-nesting) with `unocss`. Would you have any example config to share? 

I am using [sveltekit](https://kit.svelte.dev/) based project using `unocss`. Do I also need to configure [postcss](https://postcss.org/) with that project?

**Comment by bhvngt** [comment]
After some tinkering, I was able to  figured it out.

`package.json` - Requires addition of only `postcss-nesting`
```
"devDependencies": {
    ....
    "postcss-nesting": "^10.1.3",
    ....
}
````

`unocss.config.ts` - everything started working after I gave `{ enforce: "pre" }` as an option to [transformerDirective](https://github.com/unocss/unocss/tree/main/packages/transformer-directives)
```
transformers: [transformerDirective({ enforce: "pre" })],
```

`svelte.config.js`
```
import { extractorSvelte } from "unocss";
import postcssNesting from "postcss-nesting";
const config = {
	preprocess: [preprocess({ postcss: { plugins: [postcssNesting()] } })],
        vite: {
	    plugins: [UnoCss({ extractors: [extractorSvelte] })],
        .....
}
```

Then in my svelte component, I could write nested css like

```
<style lang="postcss">
	input {
		& {
			@apply h-[calc(2.875rem_+_2px)] b-gray-300 b-1 px-2 py-4 bg-[hsla(0,0%,100%,0.3)] outline-none;
			@apply transition-(shadow duration-300 delay-150);
			@apply focus-(shadow bg-white text-[#495057] outline-none);
		}
		&:focus {
			box-shadow: 0 0 0 0.2rem hsla(222, 39%, 47%, 0.25);
			& ~ button {
				@apply transition-(color duration-300 delay-150);
			}
		}
       }
```
 Note that I had to give an plain block `& {}` else it was giving me error.

**Comment by char101** [comment]
Rather than `postcss-nesting`, [postcss-nested](https://github.com/postcss/postcss-nested) is better since it is similar to `tailwind-nesting`.

postcss.config.js
```
module.exports = {
  plugins: {
    'postcss-nested': {},
  },
};
```
