### ISSUE TITLE
.dark class applied after .group class

### ISSUE THREAD

**Issue by sibbng** [unocss/unocss#70]
[Playground](https://unocss.antfu.me/?html=DwEwlgbgBAxgNgQwM5ILwCIQIE4Gt0B8AUFFKJLIihgObYD2ArgA6FECQ508yamOuAFx0mzALQALehACm2YQxZiAZvRiMkYgO5gALhLAA7QQCMaY7DJBiAbAAY7bduyx4oysNiS6OnI80ZdYk4AenAIYlJgMMhiaPDiIi5KXgxXfEiycJTqdBEWJ2SeXPzxKVl5UpU1DW09A2N003NLa3tHYJcBKCofZ2B-QOD42JIyGIikiYIgA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHCjjUrAFxwA2itV7azeqxjUAtOrGpaAGkRxmEMdB20oqZLTIBdA-6kAJRAA&options=N4IgzgLgTglgxhEAuaBXApgXyA)

I tried using `unshift()` method here. It works but now changes the order of pseudo-classes. It shouldn't be big deal at runtime since it doesn't matter in what order pseudo-classes are applied *(afaik)* I thought there might be a better way to do this.

https://github.com/antfu/unocss/blob/afbd1ed08425a9ce1180c0568b13469abfddf86b/packages/core/src/generator/index.ts#L226

**Comment by antfu** [comment]
I guess we could have a extra `order` field for handlers and sort them before applying

**Comment by sibbng** [comment]
> I guess we could have an extra `order` field for handlers and sort them before applying

Variants should be applied in order as they defined in class selector. Adding order property to give high priority to certain variants will limit composability of unocss. For example use cases you can look at https://github.com/tailwindlabs/tailwindcss/pull/6018 Giving dark class high priority will limit .group > .dark like use cases.

My proposed solution is:
- Use `unshift()` method at https://github.com/antfu/unocss/blob/afbd1ed08425a9ce1180c0568b13469abfddf86b/packages/core/src/generator/index.ts#L226
- Force move **pseudo-elements** _(::after, :before etc.)_ to end of  selector with `selector.replace(/(.*)(::.+?)(:.*)/, '$1$3$2') `https://github.com/antfu/unocss/blob/afbd1ed08425a9ce1180c0568b13469abfddf86b/packages/core/src/generator/index.ts#L243
- As I said, **pseudo-classses** _(:hover, :focus etc.)_ will be applied in reversed order but this will not change their behavior.
