### ISSUE TITLE
[BUG]Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.

### ISSUE THREAD

**Issue by yanbowe** [unocss/unocss#701]
__uno.css:8 [unocss-hmr] DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
    at Object.hot.send (http://localhost:3000/@vite/client:539:33)
    at http://localhost:3000/__uno.css:8:46

vite: 2.8.6
unocss: 0.28.0

复现链接： https://github.com/yanbowe/vite-vant-demo

**Comment by number304** [comment]
Same here, and after some configuration with the shortcuts unocss stops working. Had to remove it from my project, it came with the vitesse template.

**Comment by tienpv222** [comment]
I'm running `vite` with `--host` as a workaround; worked on Windows 10, `vite@2.8.6`, `unocss@0.29.3`.

**Comment by Alfxjx** [comment]
found this error,  and when you change the style and save, the HMR will force vite to reload and the page shows right.
maybe the vite websocket is not established when unoCSS preset applies.
https://www.yuque.com/alfxjx/notes/iy60u2

**Comment by antfu** [comment]
Improved in 0.30.1
