### ISSUE TITLE
CLI does not create directories

### ISSUE THREAD

**Issue by brattonross** [unocss/unocss#703]
When using the CLI, if I set `--out-file` to generate a file in a directory that does not yet exist, then my CSS (and the directory) is not generated and there is no error message to indicate what went wrong.

For example, if I run:

```
unocss src/**/*.tsx --out-file styles/uno.css
```

And the `styles` directory does not exist, then I get only this output, with no CSS generated:

```
unocss v0.28.0
start UnoCSS for production...
```

I would expect that either when the CSS is generated, the directory is created as well, or if that is not supported then I would expect to see an error message explaining that the directory must exist first.

**Comment by brattonross** [comment]
Just realised that this might have been fixed by the recent commit [1bda7ce](https://github.com/unocss/unocss/commit/1bda7ce44464a6ad179b5e83ee774fcd05909c5a) 😆

**Comment by ydcjeff** [comment]
@brattonross So is it already fixed?

**Comment by brattonross** [comment]
It looks like it was fixed in v0.28.1, according the to the release note https://github.com/unocss/unocss/releases/tag/v0.28.1

**Comment by ydcjeff** [comment]
Then this can be closed?

**Comment by brattonross** [comment]
Yes, I cannot reproduce the issue with v0.28.1, so it appears to now be working correctly 😄
