### ISSUE TITLE
Pug-support

### ISSUE THREAD

**Issue by Septias** [unocss/unocss#704]
Hi,

I've noticed that this works:
```html
<template lang="pug">
p(class="bg-blue-500") hi
</template>
```

but this doesn't:
```html
<template lang="pug">
p.bg-blue-500 hi
</template>
```

Is it possible to support the pug-syntax?

**Comment by antfu** [comment]
https://github.com/unocss/unocss/tree/main/packages/extractor-pug

**Comment by Septias** [comment]
nice, ty :-)

**Comment by Septias** [comment]
Is there something equal for icons?

Because this also doesn't work:

```pug
div(i="carbon:cloud-download")
```

while this works:
```htm
<div i-carbon:cloud-download />
```

**Comment by Septias** [comment]
Ok this works: 
```pug
div(class="i-carbon:cloud-download")
```

**Comment by antfu** [comment]
You can use `.i-carbon-cloud-download`, `:` and `-` are interchangable.

**Comment by alphaelf** [comment]
how about dynamic class?
```.mr-2(class=`i-${icon}`)```

**Comment by Fauny** [comment]
> Hi,
> 
> I've noticed that this works:
> 
> ```
> <template lang="pug">
> p(class="bg-blue-500") hi
> </template>
> ```
> 
> but this doesn't:
> 
> ```
> <template lang="pug">
> p.bg-blue-500 hi
> </template>
> ```
> 
> Is it possible to support the pug-syntax?

same issue in  unocss version 0.61.0 and  "@unocss/extractor-pug": "^0.61.0"
