### ISSUE TITLE
Button error 

### ISSUE THREAD

**Issue by muzidudu** [unocss/unocss#708]
if button add `type="submit"` add bg-red-500  is background transparent

`import 'uno.css';
	import '@unocss/reset/tailwind.css';`

`<button class="w-full text-white bg-red-500" type="submit">Button</button>`

**Comment by antfu** [comment]
You need to add the reset before `uno.css`

**Comment by muzidudu** [comment]
> You need to add the reset before `uno.css`

Thank you for reminding me
