### ISSUE TITLE
[vscode-intelisence] can not trigger intellisnece on .tsx in soildjs

### ISSUE THREAD

**Issue by Innei** [unocss/unocss#712]
This is my vite.config.ts. Add add UnoCSS plugins, Windi preset.

And in `main.ts`, imported `uno.css`.

```ts
import presetWind from '@unocss/preset-wind'
import transformerDirective from '@unocss/transformer-directives'
import { presetAttributify, presetUno } from 'unocss'
import Unocss from 'unocss/vite'
import { defineConfig } from 'vite'
import solidPlugin from 'vite-plugin-solid'

export default defineConfig({
  plugins: [
    solidPlugin(),
    Unocss({
      transformers: [transformerDirective()],
      presets: [
        presetWind({ dark: 'class' }),
        presetAttributify({}),
        presetUno(),
      ],
    }),
  ],
  build: {
    target: 'esnext',
    polyfillDynamicImport: false,
  },
})

```

UnoCSS inline class is work fine in render page, but vscode intelisence is not working.

<img width="619" alt="image" src="https://user-images.githubusercontent.com/41265413/158300530-8067762c-2593-4287-a17d-4aa28dced05c.png">

In output of vscode UnoCSS, there are nothing output.

<img width="837" alt="image" src="https://user-images.githubusercontent.com/41265413/158300593-d3a3acda-2a04-468e-ac53-9652fe65397a.png">

**Comment by 0xsven** [comment]
I had great success with the windi intellisense plugin

**Comment by antfu** [comment]
It wasn't supported until yesterday. Please upgrade your local deps and the extension to the latest version and try out.

**Comment by 0xsven** [comment]
@antfu 
I have just upgraded the vs-code plugin to v0.29.2. I have also made sure to upgrade dependencies to latest (`unocss` and `@unocss/cli`).

Terminal output is:
![Screenshot 2022-03-17 at 14 04 14](https://user-images.githubusercontent.com/973379/158814425-e9838715-59cf-4e97-b0a3-87047662ab87.png)

The output doesn't match the logs of your commit (f963dc0a23372e1a0808afcd0948a92e5496ae52)

It seems that your commit  has not been part of the release v0.29.2 ?

**Comment by antfu** [comment]
Yeah, it's not released yet.

**Comment by 0xsven** [comment]
VS code v0.29.3 extension accepts the property `unocss.root`

Unfortunately it still cannot find the config file...
![Screenshot 2022-03-18 at 22 58 53](https://user-images.githubusercontent.com/973379/159090436-da19ee1d-6831-4c66-8d54-7a7c2b01ec09.png)

**Comment by lvjiaxuan** [comment]
v0.31.12 can not trigger intellisnece?

![image](https://user-images.githubusercontent.com/11309921/164676570-2ccef45d-f233-4b70-b7e0-f2fc5f648ade.png)

**Comment by wyrd-code** [comment]
> v0.31.12 can not trigger intellisnece?
> 

You seem to not have an unocss.config.js file, only vite.config.ts?
