### ISSUE TITLE
Working with full controlled rules and `@apply`

### ISSUE THREAD

**Issue by jasontheiler** [unocss/unocss#717]
Hey there 👋 

I'm not entirely sure whether I'm handling full controlled rules correctly, but I encountered an issue when trying to use full controlled rules with `@apply`. It doesn't seem to replace the selector correctly and instead includes the returned code of the rule as the CSS properties.

Example:
```ts
// uno.config.ts

export default defineConfig({
  ...
  rules: [
    [
      /^rule-static$/,
      ([], {}) => ({
        color: "#f00",
      }),
    ],
    [
      /^rule-full-controlled$/,
      ([], { theme, constructCSS }) => {
        // @ts-expect-error
        const { md } = theme.breakpoints;

        return `
          ${constructCSS({
            color: "#0f0",
          })}

          @media (min-width: ${md}) {
            ${constructCSS({
              color: "#00f",
            })}
          }
        `;
      },
    ],
  ],
});
```
```css
body {
  @apply rule-static rule-full-controlled;
}
```
Result:
```css
body {
  color:#f00;
.rule-full-controlled{color:#0f0;}
@media (min-width: 768px) {
.rule-full-controlled{color:#00f;}
}
}
```
![image](https://user-images.githubusercontent.com/50220557/158411256-a20dd79a-58db-4e83-82c8-3634e17852f3.png)

(`rule-static` is applied correctly, while `rule-full-controlled` isn't)

I prepared a StackBlitz for reproduction and testing purposes: https://stackblitz.com/edit/vitejs-vite-nxk6rj?file=uno.config.ts

**Comment by antfu** [comment]
I generally do not recommend using full control rules, which is essentially meant to opt-out all the post-processing and optimizing that unocss could do.

**Comment by chris-zhu** [comment]
How about this? @jasontheiler 
```ts
{
  shortcuts: [
    ['rule-full-controlled', 'c-#0f0 md-c-#00f']
  ]
}
```

```css
body {
  @apply rule-static rule-full-controlled;
}
```

**Comment by jasontheiler** [comment]
Yea, that's probably just the way to go @chris-zhu. My actual use case would be a little more complex but it should suffice nonetheless. Thank you two.

P.S. You guys have done an amazing job with UnoCSS, simply lovely 🔥
