### ISSUE TITLE
Allow returning multiple matchers from variants

### ISSUE THREAD

**Issue by Cr3atable** [unocss/unocss#719]
Currently variants can return a matcher to be passed to other variants (I think?) and rules. I was attempting to make a variant groups variant (for the UnoCSS CLI since transforms aren't available there) by essentially extracting the variants from something like `hover:(bg-red-500,text-white)` and returning multiple matchers, either with spaces as a separator (ex: `hover:bg-red-500 hover:text-white`) or by having `matcher` be capable of being an array (ex: `['hover:bg-red-500', 'hover:text-white']`) but this is currently not possible.

If this were possible you could return an array of matchers, and other variants could generate CSS for a single class with said array of matchers. I'm not sure what uses this'd have outside of non-transform based variant groups, but I see this as a valuable change for true extensibility.

**Comment by chris-zhu** [comment]
I'm not sure if this is what you want.
e.g. : `<div hover="bg-red-500 text-white" />`

**Comment by Cr3atable** [comment]
> I'm not sure if this is what you want. e.g. : `<div hover="bg-red-500 text-white" />`

I would prefer to not have to use attributify if I don't have to, but that is a viable alternative, yes.

**Comment by Cr3atable** [comment]
I just now realized `shortcuts` is a viable alternative. Sorry!
