### ISSUE TITLE
pug shortcuts warning

### ISSUE THREAD

**Issue by caikan** [unocss/unocss#720]
Repro:
https://codesandbox.io/s/repro-unocss-shortcuts-warning-cwg866

Shortcuts in pug did work, but warning will be triggered.
```vue
<template lang="pug">
.text-c-f00 hello
</template>
```

Console log:
```shell
 WARN  [unocss] unmatched utility ".text-#f00" in shortcut ".text-c-f00"
```

**Comment by antfu** [comment]
Your regex is matching with leading `.`

```diff
- [/^(.+)-c-((?:[0-9a-f]{3,4}){1,2})$/i, ([, p, c]) => `${p}-#${c}`],
+ [/^([\w-]+)-c-((?:[0-9a-f]{3,4}){1,2})$/i, ([, p, c]) => `${p}-#${c}`],
```

**Comment by caikan** [comment]
Thank you. But I think we should let the regular expression match only the part of the class name, not the whole line of pug code. In this way, it is semantically consistent with HTML.
