### ISSUE TITLE
Unocss include doesn't considering the dist file

### ISSUE THREAD

**Issue by jd-0001** [unocss/unocss#722]
Hi,

I want to scan the dist file of the library which has the `.js` extension. Unfortunetly, even if I copy the dist file in src and use the `include` option of UnoCSS, UnoCSS is not scanning that file for classes.

I have zipped the project as a reproduction
[unocss-include-issue.zip](https://github.com/unocss/unocss/files/8262514/unocss-include-issue.zip)

**Comment by jd-0001** [comment]
I have some addition.

I use lerna and If I don't use it from node_modules and instead use relative path and include the file from dist dir of my main pkg then it loads the CSS. 🥂 

So I am thinking why it isn't loading classes from dist file I use from node_modules?

Any idea 🤔

**Comment by jd-0001** [comment]
Here's stackblitz example: [Hi, Thanks for your interest.](https://stackblitz.com/edit/vite-rvasxb?file=vite.config.js)

If you uncomment the local mylib.js include then primary button gets rendered correctly but if I use it from node_modules it is ignored.

**Comment by userquin** [comment]
@jd-0001 check https://stackblitz.com/edit/vite-ns3hmw?file=vite.config.js

https://imgur.com/9xtBcbU

**Comment by jd-0001** [comment]
I am attaching the discord conversation for future reference.

https://discord.com/channels/937808017016119440/937811334907723806/955702285361631254
