### ISSUE TITLE
[@unocss/transformer-directives] @apply directives not transformed in prod build

### ISSUE THREAD

**Issue by Innei** [unocss/unocss#725]
In prod build preivew, like this.

<img width="402" alt="image" src="https://user-images.githubusercontent.com/41265413/158725605-2f053d07-89cc-4c5a-9f7c-17cb4f728943.png">

Dev mode is working.

**Comment by antfu** [comment]
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Comment by Innei** [comment]
In dev:

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/41265413/158776542-511eee97-ae93-40d1-96ea-19382d88270f.png">

In prod:
<img width="1201" alt="image" src="https://user-images.githubusercontent.com/41265413/158776629-89060076-f32a-4ade-8306-a567f89456ce.png">

Reproduction: https://github.com/Innei/unocss-reproduction

**Comment by Innei** [comment]
@antfu Thank you.

**Comment by xmsz** [comment]
Any update?

**Comment by kidonng** [comment]
Can no longer reproduce this issue.

**Comment by aspiiire** [comment]
I have the same issue, do you have any idea on how you solved? @kidonng
