### ISSUE TITLE
animate-* doesn't work with @apply

### ISSUE THREAD

**Issue by impcyber** [unocss/unocss#733]
Code:
```scss
// src/main.css
.lazy {
  @apply animate-pulse;
}
```

Result:
![image](https://user-images.githubusercontent.com/1425691/158994282-20883335-4a5e-4be7-aa7f-85c6778e6962.png)

**Update**:
Not work with `shortcuts` too:
Code:
```ts
// unocss.config.ts
shortcuts: [
  ['lazy', 'bg-red-500 animate-pulse'],
],
```

Result:
![image](https://user-images.githubusercontent.com/1425691/158994677-52ea3c55-6155-414b-8b28-4d091fcc3ab3.png)
[Playground](https://unocss.antfu.me/?html=DwEwlgbgBAFgtAMwK4BsVQC4FMAeG4DGWAdtgE5QIq5QDOW1B%2BxA9sVlAIZoBcGZnYrTAYwbOABYADFIB8AKChRQkKAFtOCpUpXRseOAFYc6BAHcAjDKgEUnWrQC8AIjsAvAJ7Ot2pUlYEDorawAD04BA%2BOhFQLAAOAMxSmLj4KADmlGZJyWoWUdoAKjAcYEIYghixxHAgWBrEIFAAghgsamAEUADCAMq9UCTpZVgAdME64ZAFuuoATJTUOFAAVki0oggehCTkKQZzJrGJyTAsEFhkLvEAHFLeEyGcj75ghJxkAEbiKCzpLHBhhgYEhPi9tPp8GUSmQROClDAyFgEC4YBgMHFaDxQqEgSDPqMCO1Qv4WIFaCSAg5nPDMB90lgMC4APqfOzEADWNN8SlkYU0jzCER8Qum8lFkXFMU4n1oLBQSGwUG%2B6PaRigsPSaLgyWoCHwyUhO1Il2OSSyOR84jqDSaAHaoGUNpUoA7kGgPDZ1m0Om4ZdRxVNIkA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHFYALaDGb0YrAFxwA2itXHaY4QC8AnrQA0dAEZEAtFFTJXAVgAMvuGEsUGEYVFcwcVZUQOCQUPDmCEYYV2xpYDDYkLDXAEYOAF17U2LTKHFUA2NTVSNaHVYYandKh0Q4JLFoQ1oPZFoyQtLOUgBKIA&options=N4IgzgLgTglgxhEAuaBXApgXyA)

**Comment by chris-zhu** [comment]
I found no problem, maybe fixed.
