### ISSUE TITLE
Attributify mode - Typescript errors: Property xxx does not exist on type

### ISSUE THREAD

**Issue by MarkLyck** [unocss/unocss#742]
I'm trying to set up a new project with vitejs + unocss + TypeScript + React

unocss works fine for me in "normal" mode, but as soon as I try to do anything with attributify mode I get typescript errors like this:

```
Type '{ children: string; bg: string; }' is not assignable to type 'DetailedHTMLProps<ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>'.
  Property 'bg' does not exist on type 'DetailedHTMLProps<ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>'.ts(2322)
```

for the following component in my `src/test.tsx` file.

`<button bg="blue-400">Button</button>`

Clearly Typescript doesn't know about the "attributify" mode and options.

Here is my tsconfig.json

```
{
  "compilerOptions": {
    "strict": true,
    "target": "ESNext",
    "module": "esnext",
    "moduleResolution": "Node",
    "lib": ["DOM", "DOM.Iterable", "ESNext"],
    "types": ["vite/client"],
    "jsx": "preserve",
    "skipLibCheck": true,
    "esModuleInterop": true
  },
  "ts-node": {
    "transpileOnly": true,
    "compilerOptions": {
      "module": "CommonJS"
    }
  }
}

```

I have tried both "react" and "preserve" for jsx.

Vite.config.ts

```
import path from 'path'
import { defineConfig } from 'vite'

// plugins
import ssr from 'vite-plugin-ssr/plugin'
import react from '@vitejs/plugin-react'
import Unocss from 'unocss/vite'
import { presetAttributify, presetUno } from 'unocss'

export default defineConfig({
  resolve: {
    alias: {
      'src/': `${path.resolve(__dirname, 'src')}/`,
    },
  },
  plugins: [
    Unocss({
      presets: [presetAttributify(), presetUno()],
    }),
    react(),
    ssr(),
  ],
})
```

I have tried moving the Unocss both before and after the react plugin, but both threw the same typescript error.

I can't find any information anywhere on how to solve this :| or even an example with react + TypeScript where it is working.

I also installed unocss VSCode extension. But that doesn't seem to do anything either?

I also tried putting the attributes directly on the  button instead of doing `text=`

The result of that is that Typescript no longer complains, but React does when running the code:

Code:

```
const App = () => {
  return <div text-blue-400>App test</div>
}

export default App

```

React error:
```
react-dom.development.js:86 Warning: Received `true` for a non-boolean attribute `text-blue-400`.

If you want to write it to the DOM, pass a string instead: text-blue-400="true" or text-blue-400={value.toString()}.
    at div
    at App
```

and unlike the previews method of `text=` it doesn't actually change the color at all. (the style is not even applied).

Here is a minimal reproduction repo: https://github.com/MarkLyck/love-box

**Comment by antfu** [comment]
Here is a reference https://github.com/windicss/windicss/pull/322

PR welcome to bring it to UnoCSS :)

**Comment by antfu** [comment]
Related https://github.com/unocss/unocss/issues/41

**Comment by teenjuna** [comment]
@antfu I'm trying to achieve the same with Solid. My `shims.d.ts` looks like this:
```typescript
declare module "solid-js" {
  namespace JSX {
    interface HTMLAttributes<T> extends AttributifyAttributes {}
  }
}
```

It seems to work, but now I get another error:
<img width="612" alt="image" src="https://user-images.githubusercontent.com/53595243/164879071-018eee1e-bec4-4ed5-ae29-7250c1abfd1e.png">

**Comment by liuyiqi1999** [comment]
@antfu Same issue came up with my Svelte project, looks like this:
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/42669906/168411838-3bd142ac-191a-49d2-a8bf-e11f6808b01b.png">

It's working fine but with this error. Since it's not a JSX, is there anything I set wrong? 

I'm using Svelte + Vite with both UnoCSS and Svelte VSCode Plugin. My vite.config.js looks like this: 
```
import { defineConfig } from 'vite'
import { svelte } from '@sveltejs/vite-plugin-svelte'
import Unocss from 'unocss/vite'
import { presetAttributify, presetUno, presetIcons } from 'unocss'
import { extractorSvelte } from '@unocss/core'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    Unocss({
      extractors: [extractorSvelte],
      presets: [
        presetAttributify({ /* preset options */}),
        presetUno(),
        presetIcons({
          extraProperties: {
            'display': 'inline-block',
            'vertical-align': 'middle',
            'margin': '5px'
          },
        }),
      ],
      rules: [
        ['mono', {'font-family': `'Major Mono Display', monospace;`}],
        ['less-mono', {'font-family': `'Space Mono', monospace;`}],
      ]
    }),
    svelte(),
  ]
})
```

**Comment by guxuerui** [comment]
> 

Have any solutions now?

**Comment by zyyv** [comment]
> Have any solutions now?

https://github.com/unocss/unocss/blob/main/packages/preset-attributify/README.md#typescript-support-jsxtsx

**Comment by guxuerui** [comment]
> > Have any solutions now?
> 
> https://github.com/unocss/unocss/blob/main/packages/preset-attributify/README.md#typescript-support-jsxtsx

OK, Thank you!!

**Comment by lisonge** [comment]
> @antfu I'm trying to achieve the same with Solid. My `shims.d.ts` looks like this:
> 
> ```ts
> declare module "solid-js" {
>   namespace JSX {
>     interface HTMLAttributes<T> extends AttributifyAttributes {}
>   }
> }
> ```
> 
> It seems to work, but now I get another error: <img alt="image" width="612" src="https://user-images.githubusercontent.com/53595243/164879071-018eee1e-bec4-4ed5-ae29-7250c1abfd1e.png">

```ts
import type { AttributifyAttributes } from '@unocss/preset-attributify';

declare module 'solid-js' {
    namespace JSX {
        interface HTMLAttributes<T> extends AttributifyAttributes {
          [key: string]: any // Add this extra line
        }
    }
}
```

it work for me

**Comment by j10ccc** [comment]
@liuyiqi1999 I also counter the same issue after reading official [TSX guidance](https://unocss.dev/presets/attributify#typescript-support-jsx-tsx) in my astro project. I solved this by install `@unocss/preset-attributify`.

The official document should note that this package should be manually installed.
