### ISSUE TITLE
@unocss/core types are not exported

### ISSUE THREAD

**Issue by chenzhq** [unocss/unocss#744]
I want create a custom preset by reuse some core types, but i can't import those types from @unocss/core/src/types.ts.

<img width="1463" alt="image" src="https://user-images.githubusercontent.com/8817002/159201682-7ef29fd9-3375-404b-b4f9-1255747b0831.png">

**Comment by chenzhq** [comment]
Maybe I can solve it by creating the preset in a fork project

**Comment by userquin** [comment]
@chenzhq just use:
```ts
import type { UnoGenerator } from '@unocss/core'
import { createGenerator } from '@unocss/core'
```
