### ISSUE TITLE
`-` can't be the beginning?

### ISSUE THREAD

**Issue by Hongbusi** [unocss/unocss#750]
![image](https://user-images.githubusercontent.com/53554371/159664681-d78ee2bf-8a96-4890-a2e7-932321f43dc1.png)

[Playground](https://unocss.antfu.me/?html=DwEwlgbgBAFgtAMwK4BsVQC4FMAeG4DGWAdtgE5QIq5QDOW1B%2BxA9sVlAIZoBcGZnYrTAYwbOABYADFIB8AKChRQkKAFtOUODABGtOAEYFSpSujY8cAKw50CAO4GZUAik61aAXgBEbgF4Ant7GJkpIrAQeiibAAPTgECGmCVAsAA4AzFKYuPgoAOaU9lnZakbRoQAqMBxgQhiCGKnEcCBYGsQgUACCGCxqYARQAMIAyqNQJPl1WAB0FcrxkEnKKWoATJTUOFAAVki0oggBhCTkOZbrtqmZ2TAsEFhkPukAHFLBC6acXyZghJwyDpxCgWPkWHBphgYEgdL8lBZ8HUamQRPDYGQsAgfDAMBg0rQeLFYlCYTpZgR%2BrFwixIrRqREPN50Q0yPksBgfAB9HRuYgAa2ZoSUsjinBWcQSIUly3kMsScpSnD0LBQSGwUGBeP61igqPyuLg2WoCHw2URp1ITxuWSKJRC4jaHS6AHaoHVDo0oG7kGgAi4Dn0Bn5ldQ5UtEkA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHFYALaDGb0YrAFxwA2itXHaY4QC8AnrQA0dAEZEAtFFTJXAVgAMvuGEsUGEYVFcwcVZUQOCQUPDmCEYYV2xpYDDYkLDXAEYOAF17U2LTKHFUA2NTVSNaHVYYandKh0Q4JLFoQ1oPZFoyMrNzV3UnVnz2pHioImxe3wA6ACZvDxBB0kLSzlIASiA&options=N4IgzgLgTglgxhEAuaBXApgXyA)

**Comment by chris-zhu** [comment]
It will be intercepted by `variantNegative`
<img width="659" alt="image" src="https://user-images.githubusercontent.com/42139754/159666108-ec9f5fc8-1f10-42a4-9374-78f59491f958.png">

**Comment by Hongbusi** [comment]
Thank you. @chris-zhu
