### ISSUE TITLE
[unocss] entry module not found - with 0.30 update:

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [unocss/unocss#753]
with 0.30 update:

`[unocss] entry module not found, have you add `import 'uno.css'` in your main entry?`

**Comment by ydcjeff** [comment]
As the message shown, you need to add `import 'uno.css'` in the main JS/TS entry. Otherwise please provide a minimal reproduction to reproduce the issue.

**Comment by CharlesOkwuagwu** [comment]
> As the message shows, you need to add `import 'uno.css'` in the main JS/TS entry. Otherwise please provide a minimal reproduction to reproduce the issue.

As I mentioned, I only updated to 0.30, the code is the same ... `import 'uno.css'` already in `main.ts`

```

import { createApp } from 'vue'
import { createRouter, createWebHistory } from 'vue-router'
import routes from 'virtual:generated-pages'
import App from './App.vue'

import '@unocss/reset/tailwind.css'
import './assets/css/main.css'
import 'uno.css'

const app = createApp(App)
const router = createRouter({
  history: createWebHistory(import.meta.env.BASE_URL),
  routes
})
app.use(router)
app.mount('#app')

```

**Comment by antfu** [comment]
0.30.0 does not change that part. Probably just some time racing issue. Please check if it's improved in 0.30.1
