### ISSUE TITLE
bug(prose, nuxt): color do not respect elements

### ISSUE THREAD

**Issue by 0ri2N** [unocss/unocss#772]
Using `prose prose-{color}` ex: `prose prose-yellow` colors the entire text instead of specific elements such as links.

Reproduction Preview: https://xux94y.sse.codesandbox.io/anything
Reproduction Source Code: https://codesandbox.io/embed/serene-agnesi-xux94y

**Comment by ydcjeff** [comment]
Yes, prose colors are used for body, headings, links, lists, etc. You can see here:

https://github.com/unocss/unocss/blob/b6b6adeee5225ff2018c07320c3f8b7297708795/packages/preset-typography/src/index.ts#L80-L99

Tailwind CSS 3 provides link-only prose classes for backward compatibility which usage would be like `prose prose-zinc prose-red`. It looks confusing IMO. We can't which colors are used for which html tags.

If you only want links to be styled for specific colors, you can use `cssExtend` for that.
Example: https://github.com/unocss/unocss/tree/main/packages/preset-typography#example
