### ISSUE TITLE
Breakpoint variants are not sorted properly

### ISSUE THREAD

**Issue by impcyber** [unocss/unocss#778]
Config:
```ts
unocss.config.ts
export default defineConfig({
...
  theme: {
    breakpoints: {
      'xs': '320px',
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
      'xxl': '1536px',
    },
...
})
```

HTML code:
```html
<template>
  <div class="grid xs:grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5">
    <Item v-for="(item, index) in products" :key="index" :item="item" />
  </div>
</template>
```

Result:
![image](https://user-images.githubusercontent.com/1425691/160620177-7a177839-f7ea-4885-ac4e-d2347a8c1475.png)

[Playground](https://unocss.antfu.me/?html=DwEwlgbgBAFgtAMwK4BsVQC4FMAeG4DGWAdtgE5QIq5QDOW1B%2BxA9sVlAIZoBcGZnYrTAYwbOABYADFIB8AKChRQkKAFtOCpUpXRseOAFYcKALwAic5QDuARhkXzW7UqSsCtWou3AA9OAhnHQDMXHxjM0sbeylHWQAhMixOAGsABxYwUlooJNpUDD8AoOUQtIBPCTioHFoeAHMyMBBCFhRaOAAmOjUGppaCNo6AZnUQPubW9skoFHqJgaGjIsgS3SgCFE5PC0bmmrq9xenu2l6jqZGxhcuZuZvB6cMnbxdg1dsVwNe33VlP-yrH4uP4A4rAnzFMFAt6Qj5fEogqEIiHvQLQ74gwGYuHQFhpYZSUIGOY2QlEtS2RFQAAqMA4WVoGEEGCg4hAWA0xBAUAAghgWGowAQoABhADK4qgJHqWSwADofiikao1N0qDQAFZIJlgBDlQgkcjE-CdExsglEmAsCBYMgWfEADikL1hwE4qKgYEInDIACNxCgWPUWHBZRgYEg-Z79PgsvSmhhPTAkggLDAMBg0nVfL5w5G-fLBmpfG4WB5aKX3J5zDHffUsBgLAB9P1bYgpWuw2R%2BTRK7HOFFDkKcP20NpIbBQAOZwVGXJgeoZuBE6gIfBE2OG0h2i2EskyZzszmCHkAdq9QmZpCgF%2BQaHKGx1AqFAC9R9R5AigA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHCjjUrAFxwA2itV7azeqxjUAtOrGpaAGkRxmEMdB20oqZLTIBdA752BjAAFqggqDrKhnAARp7CANaQ2DDaiAYxtLwc7gDMAEwADGC89pmGtKwgtO4AbAAsJWVBMaq0IN7uAOx1AByl5W10YkS1dACMRQUNg61t2WLjtBMFfc1DCwW8S%2B4TAKx5dXMV7bw7ywdHJzGk86ScpACUQA&options=N4IgzgLgTglgxhEAuaBXApgXyA)

xs breakpoint has the highest priority with the lowest value

UPD: If i will add custom breakpoints with same values, then the order becomes correct

[Playground](https://unocss.antfu.me/?html=DwEwlgbgBAFgtAMwK4BsVQC4FMAeG4DGWAdtgE5QIq5QDOW1B%2BxA9sVlAIZoBcGZnYrTAYwbOABYADFIB8AKChRQkKAFtOCpUpXRseOAFYcKALwAic5QDuARhkXzW7UqSsCtWou3AA9OAhnHQDMXHxjM0sbeylHWQAhMixOAGsABxYwUlooJNpUDD8AoOUQtIBPCTioHFoeAHMyMBBCFhRaOAAmOjUGppaCNo6AZnUQPubW9skoFHqJgaGjIsgS3SgCFE5PC0bmmrq9xenu2l6jqZGxhcuZuZvB6cMnbxdg1dsVwNe33VlP-yrH4uP4A4rAnzFMFAt6Qj5fEogqEIiHvQLQ74gwGYuF6MJGEyOaIOSyyADCSFoGBYvRR60221ou36UDSMDYWAeS26bM4ACNqBgudNRhh%2BYLhR0JLNOGlqWlJUYXrC0f8USrSvDsYjcWrtajNej1SrQcbYab9RqLeCsTbcVAWGlhlJQgY5jZnS61LYdQAVGAcLJUwQYB3EOAgLAaYggKAAQWpajABCgZIAymmoCR6lksAA6H5mw3qbpUGgAK0pogQ5UIJHIrvwnRMDqdLvZECwZAsjoAHFJlb9OAawIROGQ%2BeIUCx6iw4DmMDAkHyDfp8FkA00MAaYEkEBYYBgMGk6r5fAul3y84M1L43CwPLQ7%2B5POZV%2BP6lgMBYAPoCwQpG%2BsKyH4miFpayj6nSIT8rQbRINgUCTkeNJGLkYD1IecAutQCD4C6a51qQXats6HoyM44iRtGsYAO1QEGYqkFA9HIGg5QbFWNJgAAXuKWDyAiQA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHCjjUrAFxwA2itV7azeqxjUAtOrGpaAGkRxmEMdB20oqZLTIBdA752BjAAFqggqDrKhnAARp7CANaQ2DDaiAYxtLwc7gDMAEwADGC89pmGtKwgtO4AbAAsJWVBMaq0IN7uAOx1AByl5W10YkS1dACMRQUNg61t2WLjtBMFfc1DCwW8S%2B4TAKx5dXMV7bw7ywdHJ8NgIQSRdIUb8zF3wrE2MPVNN20wHy%2BPX6fxiYmEYHMYD201mLVOQlYiShezWLwRIWQe0Ox3hMVI81InFIAEogA&options=N4IgzgLgTglgxhEAuaBXApgXyA)

**Comment by stephenhebert** [comment]
I'm also observing this issue.  Another quirk is that using at-xs creates rule matching `xs > w > xxl` instead of expected `xs > w > sm`, where `w` is viewport width

**Comment by chu121su12** [comment]
Most likely this is due to how js object are merged. The default values are here:

https://github.com/unocss/unocss/blob/9de788ae4b980a2ff72466f05626a6f154b6a59a/packages/preset-mini/src/theme/misc.ts#L2-L8

Adding custom breakpoints will append the keys at the end of the theme config.

> UPD: If i will add custom breakpoints with same values, then the order becomes correct

Use this workaround for now.

**Comment by antfu** [comment]
I guess we could sort it instead of relying on the object key order?

**Comment by chu121su12** [comment]
I'm afraid sorting may cause other problem with numbers with different units.

([Tailwind's for reference](https://tailwindcss.com/docs/screens#adding-smaller-breakpoints))

**Comment by userquin** [comment]
> I'm afraid sorting may cause other problem with numbers with different units.
> 
> ([Tailwind's for reference](https://tailwindcss.com/docs/screens#adding-smaller-breakpoints))

Maybe we can use `generator.userConfig` to acces the `breakpoints` keys to sort them on the variant.

**Comment by userquin** [comment]
ok, using the `breakpoints` from the `userConfig` if present instead merged from theme works, PR in a few minutes.

On playground just adding the breakpoints works:

![imagen](https://user-images.githubusercontent.com/6311119/161015453-05476be0-8460-48f6-8b4b-3340768dbcda.png)

on node also works:

![imagen](https://user-images.githubusercontent.com/6311119/161015752-366c65ff-a7dd-4cde-8def-81a255cdc3f4.png)

**Comment by userquin** [comment]
![imagen](https://user-images.githubusercontent.com/6311119/161017494-64a52b64-fff8-4ace-8ad6-09e83ece2837.png)
