### ISSUE TITLE
@unocss/nuxt 0.30.0 and upwards failing to compile

### ISSUE THREAD

**Issue by eyrewiut** [unocss/unocss#782]
Hi, Thank you for your hard work on this brilliant tool.

I am using the nuxt module with nuxt 2.15.8. The module works was working perfectly fine until I updated it, and now it is giving me the following error and failing to compile.

```
This dependency was not found:                                                                                                                   friendly-errors 16:49:16
                                                                                                                                                           friendly-errors 16:49:16
* !!../node_modules/css-loader/dist/cjs.js??ref--3-oneOf-1-1!../node_modules/postcss-loader/src/index.js??ref--3-oneOf-1-2!../node_modules/unplugin/dist/webpack/loaders/load.js??ref--13-0!../_virtual_/__uno.css in ./_virtual_/__uno.css
                                                                                                                                                 friendly-errors 16:49:16
To install it, you can run: npm install --save !!../node_modules/css-loader/dist/cjs.js??ref--3-oneOf-1-1!../node_modules/postcss-loader/src/index.js??ref--3-oneOf-1-2!../node_modules/unplugin/dist/webpack/loaders/load.js??ref--13-0!../_virtual_/__uno.css
```

After some testing I discovered that that all versions of the module seem to be working for me up to version 0.30.0.
This problem also persisted when I tried it in a blank project with a different version of nuxt.

I appreciate any help or advice..

System:
`Mac OS 11.6.4`
`MacBookPro16,2`
`Processor Name: Quad-Core Intel Core i5`

**Comment by antfu** [comment]
@eyrewiut would be great if you can share a minimal reproduction

**Comment by userquin** [comment]
> /cc @userquin probably related to the iconify loader?

we only move the logic to `@iconify/utils`, awaiting for the reproduction

**Comment by eyrewiut** [comment]
@antfu Thank You for replying so quickly and sorry for the delay. 
I have created a repository containing a blank nuxt project created using *create-nuxt-app* and added `@unocss/nuxt 0.30.0` with default config. 
[Minimal Reproduction repo](https://github.com/eyrewiut/symmetrical-octo-journey)

**Comment by userquin** [comment]
@eyrewiut your repo is using npm not yarn, I can update to latest `@unocss/nuxt` and run the generate script, do you know how to force nuxt to rebuild?

![imagen](https://user-images.githubusercontent.com/6311119/161435115-c8d91ca1-0b1a-4815-ab17-db6822540d0d.png)

**Comment by productdevbook** [comment]
react-nextjs build -> ./_virtual_\__uno.css.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[8].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[8].use[2]!./_virtual_\__uno.css

**Comment by eyrewiut** [comment]
@userquin Thank you for your advice and sorry again for my delayed response.

I tried what you suggested but as far as I can see it doesn't seem to be having the same effect. 
As far as I can see nuxt doesn't seem to be rebuilding.. Do you have any idea what I am doing wrong?

Here is what I did: https://streamable.com/16az62

Thank you again for your time
