### ISSUE TITLE
v-bind:class with template string utilities not detected

### ISSUE THREAD

**Issue by chenghsuanhe** [unocss/unocss#785]
## Summery

When I tried to bind a unocss class using template strings to an element, the class won't be detected.

## Example code

<details> 
<summary>main.js</summary>

```js
import { createApp } from "vue";
import App from "./App.vue";
import "uno.css";

createApp(App).mount("#app");
```

</details>

<details> 
<summary>App.vue</summary>

```vue
<script setup>
import { ref } from "vue";

const color = ref("blue");
</script>

<template>
  <div class="w-8 h-8" :class="[`bg-${color}`]"></div>

  <button @click="color = 'red'">Change color</button>
</template>
```

</details>

<details> 
<summary>vite.config.js</summary>

```js
import { defineConfig } from "vite";
import Vue from "@vitejs/plugin-vue";
import Unocss from "unocss/vite";
import { presetWind } from "unocss";

export default defineConfig({
  plugins: [
    Vue(),
    Unocss({
      presets: [presetWind()],
    }),
  ],
});
```

</details>

**Comment by kikyous** [comment]
This is expected behavior

**Comment by cll123456** [comment]
> ## Summery
> When I tried to bind a unocss class using template strings to an element, the class won't be detected.
> 
> ## Example code
> main.js
> App.vue
> ```
> <script setup>
> import { ref } from "vue";
> 
> const color = ref("blue");
> </script>
> 
> <template>
>   <div class="w-8 h-8" :class="[`bg-${color}`]"></div>
> 
>   <button @click="color = 'red'">Change color</button>
> </template>
> ```
> 
> vite.config.js

@chenghsuanhe  I think unocss can’t dynamic caculate generate class at present. but we use utilities full-name, it's be usefully.
![image](https://user-images.githubusercontent.com/41314419/161068552-d9eab0b4-0876-467d-836a-6dbb75f3c454.png)
![image](https://user-images.githubusercontent.com/41314419/161068639-37cd2442-06a5-467e-beb9-215620afbede.png)
![image](https://user-images.githubusercontent.com/41314419/161068750-7050c0de-e326-4324-8126-5bdab0e8a403.png)

**Comment by chenghsuanhe** [comment]
Okay, since this is a expected behavior, I will close this issue. Thanks.
