### ISSUE TITLE
How to use unocss with quasar-cli with vite

### ISSUE THREAD

**Issue by rowild** [unocss/unocss#790]
Since some time now the quasar-cli has beta support for using vite. It does NOT use a separate vite-config.js file as it was the case with earlier version. So far tutorials out there "only" show the older way of using quasar with vite and unocss (via vite-config.js), but there is no information available on how to integrate unocss with the new quasar-cli vite feature.

Any chance you could give us some hints, @antfu ?

**Comment by mila76** [comment]
Here a quick guide:
`npm i -D unocss`
`quasar new boot unocss`
in src/boot/unocss.js `import "uno.css";`
in quasar.config.js `boot: ["unocss"]` and under build section `vitePlugins: [["unocss/vite", {}]]`

**Comment by rowild** [comment]
@mila76 Adding your repo here, too:
[repo](https://github.com/mila76/quasar-vite)

Thank you very much, @mila76 !

**Comment by philippedasilva-orizone** [comment]
@mila76 not trying to revive this issue but with your setup, did you manage to get the unocss vscode extension to work? I believe it requires some sort of uno config file to work and Quasar-Cli doesn't use the standard vite config nor unocss.config.js

thanks by advance

**Comment by mila76** [comment]
Sorry don't use. But i think they need classic config. Try create one and if it works i think is possibile to import in quasar.conf and use

**Comment by mila76** [comment]
I don't use unoCSS extension but just use uno.config.js instead on putting on quasar.conf and all work
Updated my [repo](https://github.com/mila76/quasar-vite)

**Comment by philippe-dasilva** [comment]
Thanks @mila76 I will give it a try.

**Comment by wjndy4** [comment]
Hi @mila76, I tried your config, but I always receive errors messages from cli "[vite] Internal server error: Failed to resolve import "uno.css" from "src\boot\unocss.ts". Does the file exist?". Could you give me some hints?

**Comment by philippedasilva-orizone** [comment]
Make sure you installed the unocss plug-in for vite and configured it in
the quasar config file.

**Comment by wjndy4** [comment]
I installed this plugin. I migrated from project using vite-plugin to project app-vite. I followed quick guide of Mila76. But I still receive that error.

**Comment by mila76** [comment]
Never used ts. Try rename boot/unicss.js in .ts

**Comment by todoroff** [comment]
@mila76  I'm having the same issue after the following quasar update. 
```
"quasar": "^2.11.6" -> "^2.12.0",
"@quasar/app-vite": "^1.2.0" -> "^1.4.3",
"@quasar/extras": "^1.15.11" -> "^1.16.4"
```

It was working fine before that.

**Comment by mrcluo** [comment]
> Hi @mila76, I tried your config, but I always receive errors messages from cli "[vite] Internal server error: Failed to resolve import "uno.css" from "src\boot\unocss.ts". Does the file exist?". Could you give me some hints?

@wjndy4  i met the same problem as you ，it It looks like a version issue of unocss,   and  i resolved it by useing  "0.55.7" instead of  "0.59.3"

**Comment by todoroff** [comment]
> > Hi @mila76, I tried your config, but I always receive errors messages from cli "[vite] Internal server error: Failed to resolve import "uno.css" from "src\boot\unocss.ts". Does the file exist?". Could you give me some hints?
> 
> @wjndy4 i met the same problem as you ，it It looks like a version issue of unocss, and i resolved it by useing "0.55.7" instead of "0.59.3"

I made it work. Keep your unocss boot file and then in quasar.config.js add the following:

Imports:

```js
const Unocss = require('unocss/vite').default;
const { presetAttributify, presetUno } = require('unocss');
```

vitePlugins config:

```js
      vitePlugins: [
        ...Unocss({
          presets: [
            presetAttributify({}),
            presetUno(),
          ],
        }),
      ]
```

**Comment by mila76** [comment]
If i'm not wrong latest version dont work because uno removed CJS that is required with the current version on quasar vite
With the app-vite v2.0.0-beta.1 i think can be done

**Comment by crowd4gpt** [comment]
incredibly frustrating experience with quasar:

followed just about every single guide on how to get UnoCSS (all i want is daisyUI + unocss) and the project just throws Error: Dynamic require of "unocss/vite" is not supported and no idea how to fix

**Comment by mila76** [comment]
As i said in my previous comment UnoCSS now is only ESM. But for all of you i Updated my [repo](https://github.com/mila76/quasar-vite) to the latest quasar app-vite full ESM and now work like before

**Comment by SgtPepper27** [comment]
@mila76 Downloaded your repo and everything works fine, so I wanted to create a new Quasar project from scratch and follow your steps.

In the end, I´m struggling with the following error:
[vite] Internal server error: Failed to resolve import "virtual:uno.css" from "src\boot\unocss.js". Does the file exist?

**Comment by berial** [comment]
I solved this problem.

1.create `src/boot/unocss.ts`
```
import 'virtual:uno.css'
```
2.in `quasar.config.ts`
```
import Unocss from 'unocss/vite'

export default configure(() => {
  return {
    boot: ['unocss'],
    ...
    build: {
      ...
      vitePlugins: [
        ...
      ],
      extendViteConf(viteConf) {
        viteConf.plugins?.push(
          Unocss(),
        )
      },
    }
  }
}
```

current version:
```
"@quasar/app-vite": "^2.0.0-beta.12",
"unocss": "^0.61.5",
```
