### ISSUE TITLE
"prose" default styles are not applied with attributify

### ISSUE THREAD

**Issue by impcyber** [unocss/unocss#795]
When using attributify mode, default prose styles are listened to in the uno inspector but are not actually applied.

[Playground](https://unocss.antfu.me/?html=DwEwlgbgBAFgtAMwK4BsVQC4FMAeG4DGWAdtgE5QIq5QDOW1B%2BxA9sVlAIZoBcGZnYrTAYwbOABYADFIB8AKChRQkKAFtOCpUpXRseOAFYc6BAHcAjDK7EwG7HABGLJMSJxuGG3c4OCL0jgwYgRgkQ5BHwcLWi1tJVcWAlpaRW1gAHpwCDidbKgkHgAHMhZ6KAIUThSAXgAiErKsOtz0mAtZABkWMiw1KDAi2iR%2BkBYUHroRLjUsDAAaTPbWnSLZfyEsJjmkCk5wIrBaAmCAcygGEXm6LBAoMYuwJFo1FjvsNSLJ4JPwEFcvEgvFVnL0Ll4xhMwRpTsROFwUGAAI5ITgAOigAFUvCQ7Fw7mowv0ILjOGpriijlBWLR%2BEg7rgsGQThhfGJiAU0GT-FAQT0qbZhAUvNxkUhBhccBd4f41K8Hht6CjfBiACLi2hcIEcMBkXYcSHfDm9EpYGAkEBM6bBKAQcZIIqs7C2y44lIcE5oEb3cY9DhYJCUJCnMC%2BamoKpQIqcMihjC7DEAURwREdAYowlIUCSBE4WzDBAdYBAvjDrA5jWLJAWdABAw5hZQ0aglOzCFCJ3hlvoeqzrzQ00i-WLF1pvM4oJGaMyazSOiykFawBgZCX%2BUq1Vo9Ua9Bac7aHW6vWHQ29hozg9mCyWHX3q3WbHo23jewORxOxHOruu9DuDywTwvG8mB9F8FA-MWxZ1kC46gv6EK%2BtCnCwvCorKhi2IXLY-T7OoRIurYZIUhq1JlHSDI4EyLJsmwnJVGoPJ8rGmqCmAwoImKEo0FgMosHKbwsBUj5YMqGBqiRnDagMepgue9ZQCavTmsQlqxl4Np2igDpOhwJKIm65SelpoyIf6gbICGZYRvC0axr4CZQMmqbYLsUxZjmea5l4haHCWTqkRWpRVqQP51jajbNq2LDtmAnb3FgPZ1v2%2BneMODJjkxU4zkuC45PuujqAATJQ1BSgAVs8ogIAAnoQ1ZMiBBiFSY2ZFAAzFIsAsCSZD1CwRQABxSHu8Q6Jwd7aGAhAxs4xBwBMpwsHAIYYDASCOBNSj6PgwTmmpm2wL0CD1DAGAYEMPAZBkK1rY4aKyhkiTJLQj2sM9dQHayZCnHM9QAPqOFUxAANYfaNUCyJkmj5blcSZNkCjw4u8gFROtD2s6zhnXxRgKWApynXAnXUAg%2BCddtdWkA1-UdZQZgdXIaTiJaGgqVAADt9a0oIXic8gaDVRUlV8WAABeE7UCjsNAA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCqWEZF1tAgjDFMAEYCuMYOgCezSjRgAVYZCJQAhmAAWwuAF846KBBBwA5H0YBjKlT0Aoc6gAekWCgzy%2BAG3hpMOfIWBEAFAnM4cnFaKgAuOABtQKDg1npGXwBKEhiglgkOLl4BIWF-NNiqbKMYCPR5ZxpU2NiWTGsIgzC9Gti1FMKM2mlZBWV8hA62uABdNqgXagjo2si9Iz5inQBaSedUVsQ4IwhnaCbKZD11UZizjqA&options=N4IgzgLgTglgxhEAuaBXApgXyA)

![image](https://user-images.githubusercontent.com/1425691/161454214-04d6dea9-08cb-4d05-bd6a-9e4227908dc0.png)

UPD:
Sometimes it apply successful after changes:
![image](https://user-images.githubusercontent.com/1425691/161455483-fcd28532-360c-49d5-8625-bd7a8f0f1c68.png)

**Comment by chris-zhu** [comment]
Try setting the config option `strict` to true

<img width="475" alt="image" src="https://user-images.githubusercontent.com/42139754/161674393-72348e21-89f2-4b24-8b75-57aed264baf3.png">


[playground](https://unocss.antfu.me/?html=DwEwlgbgBAFgtAMwK4BsVQC4FMAeG4DGWAdtgE5QIq5QDOW1B%2BxA9sVlAIZoBcGZnYrTAYwbOABYADFIB8AKChRQkKAFtOCpUpXRseOAFYc6BAHcAjDK7EwG7HABGLJMSJxuGG3c4OCL0jgwYgRgkQ5BHwcLWi1tJVcWAlpaRW1gAHpwCDidbKgkHgAHMhZ6KAIUThSAXgAiErKsOtz0mAtZABkWMiw1KDAi2iR%2BkBYUHroRLjUsDAAaTPbWnSLZfyEsJjmkCk5wIrBaAmCAcygGEXm6LBAoMYuwJFo1FjvsNSLJ4JPwEFcvEgvFVnL0Ll4xhMwRpTsROFwUGAAI5ITgAOigAFUvCQ7Fw7mowv0ILjOGpriijlBWLR%2BEg7rgsGQThhfGJiAU0GT-FAQT0qbZhAUvNxkUhBhccBd4f41K8Hht6CjfBiACLi2hcIEcMBkXYcSHfDm9EpYGAkEBM6bBKAQcZIIqs7C2y44lIcE5oEb3cY9DhYJCUJCnMC%2BamoKpQIqcMihjC7DEAURwREdAYowlIUCSBE4WzDBAdYBAvjDrA5jWLJAWdABAw5hZQ0aglOzCFCJ3hlvoeqzrzQ00i-WLF1pvM4oJGaMyazSOiykFawBgZCX%2BUq1Vo9Ua9Bac7aHW6vWHQ29hozg9mCyWHX3q3WbHo23jewORxOxHOruu9DuDywTwvG8mB9F8FA-MWxZ1kC46gv6EK%2BtCnCwvCorKhi2IXLY-T7OoRIurYZIUhq1JlHSDI4EyLJsmwnJVGoPJ8rGmqCmAwoImKEo0FgMosHKbwsBUj5YMqGBqiRnDagMepgue9ZQCavTmsQlqxl4Np2igDpOhwJKIm65SelpoyIf6gbICGZYRvC0axr4CZQMmqbYLsUxZjmea5l4haHCWTqkRWpRVqQP51jajbNq2LDtmAnb3FgPZ1v2%2BneMODJjkxU4zkuC45PuujqAATJQ1BSgAVs8ogIAAnoQ1ZMiBBiFSY2ZFAAzFIsAsCSZD1CwRQABxSHu8Q6Jwd7aGAhAxs4xBwBMpwsHAIYYDASCOBNSj6PgwTmmpm2wL0CD1DAGAYEMPAZBkK1rY4aKyhkiTJLQj2sM9dQHayZCnHM9QAPqOFUxAANYfaNUCyJkmj5blcSZNkCjw4u8gFROtD2s6zhnXxRgKWApynXAnXUAg%2BCddtdWkA1-UdZQZgdXIaTiJaGgqVAADt9a0oIXic8gaDVRUlV8WAABeE7UCjsNAA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCqWEZF1tAgjDFMAEYCuMYOgCezSjRgAVYZCJQAhmAAWwuAF846KBBBwA5H0YBjKlT0Aoc6gAekWCgzy%2BAG3hpMOfIWBEAFAnM4cnFaKgAuOABtQKDg1npGXwBKEhiglgkOLl4BIWF-NNiqbKMYCK4%2BVFTY2JZMawiDML1q2LUUwozaaVkFZXyEdta4AF1WqBdqCOiayL0jPmKdAFoJ51QWxDgjCGdoRspkPXURmNP2oA&options=N4IgzgLgTglgxhEAuaBXApgXyA)

**Comment by impcyber** [comment]
@chris-zhu Thank you
But this work only with `class`, `u:prose` still not working:
![image](https://user-images.githubusercontent.com/1425691/161749803-26a9bfd9-5bd7-48cc-83d5-985df98d6167.png)

[Playground](https://unocss.antfu.me/?html=DwEwlgbgBAFgtAMwK4BsVQC4FMAeG4DGWAdtgE5QIq5QDOW1B%2BxA9sVlAIZoBcGZnYrTAYwbOABYADFIB8AKChRQkKAFtOCpUpXRseOAFYc6BAHcAjDK7EwG7HABGLJMSJxuGG3c4OCL0jgwYgRgkQ5BHwcLWi1tJVcWAlpaRW1gAHpwCDidbKgkHgAHMhZ6XPSYC1kAGRYyLDUoMCLaJCaQFhR6uhEuNSwMABpMqoqdItl-ISwmQaQKTnAisFoCYIBzKAYRIbosEChO7bAkWjUWQ%2Bw1Ip7g9fAQVy8kLxROZwbtr07ur40NsROFwUGAAI5ITgAOigAFUvCQ7FxDmowk0IIjOGo9hDVlBWLR%2BEhDrgsGR1hhfGJiAU0Fj-FB3p88bZhAUvNxwUgWtscNtgf41BdjtN6BDfDCACLc2hcV4cMBkBYcX53GkNEpYGAkEBkvrBKAQLpIIqU7CGnYIlIcdZodpHLr1DhYJCUJAbMC%2BfGod5QIqcMiejALGEAURwRFNLoowlIUCSBE4sy9BBNYBAvi9rBpJRY6ZIwzoz2aNNTKH9UFx8YQoXWwN19CVcYuaD6kSa6e2hMZH3q7ShmUmaR0WUgFWAMDI4-yBHeKQAvAAiXP0RfjZRjOoNDute2qmNtgbDUbVYfpSai2bYYOLZardbELaWvb0Q7HLCnc6XTCNW4Ue7pumxavD2nzOj8jr-JwgLApy4owvC2y2E0SzqGiFq2FiOIyviZREiSOBkhSVJsLS7xqAyTL1CyqxgOyIJcjyNBYAKLBCpcLBQJe4oYFKOGcPKzRKl8%2B4llAGoNNqxC6oGXgGkaKAmmaHAYqCVr0FxYB2h0kHOq6yAelmPrAv6ga%2BCGUDhpG2ALL0cYJkmiZeKmKwZmauE5qU%2BakC%2BxYGmWFZViwNZgHWRxYI2xYtmp3gdiS3ZUUqagDhkQ7xJk2TTqoagAEyUNQfIAFZnKICAAJ6EAWZI-gYOUmPGRQAMxSLALAYmQS4sEUAAcUhrmeOicAN2hgIQAbOMQcDdBsLBwB6GAwEgjjDUo%2Bj4ME2qyStsANAgS4wBgGCtDwGQZPNi2OFCgoZIkyS0DdrB3Yu22UmQGyDEuAD6jjvMQADWz3xEosiZJoZ4ZWOaQQzk8jQwouhcI4tDGuaziHWxRjiWAGwHXALXUAg%2BAtWtlWkNVXXNZQZjNXIaTiLqGjSVAADtJaEoIXis8gaBlVxJVsWAABeHzULDo45EAA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCqWEZF1tAgjDFMAEYCuMYOgCezSjRgAVYZCJQAhmAAWwuAF846KBBBwA5H0YBjKlT0Aoc6gAekWCgzy%2BAG3hpMOfIWBEAFAnM4cnFaKgAuOABtQKDg1npGXwBKEhiglgkOLl4BIWF-NNiqbKMYCK4%2BVFTY2JZMawiDML1q2LUUwozaaVkFZXyEdta4AF1WqBdqCOiayL0jPmKdAFoJ51QWxDgjCGdoRspkPXURmNP2oA&options=N4IgzgLgTglgxhEAuaBXApgXyA)
