### ISSUE TITLE
Is there a feature in DevTools that allows me to modify a class directly and see how it behaves?

### ISSUE THREAD

**Issue by oekazuma** [unocss/unocss#796]
I really like the ability in Windi CSS to change classes directly in DevTools to see how they work.

Does Uno CSS have this feature?

Reference: https://windicss.org/integrations/vite.html#design-in-devtools

**Comment by antfu** [comment]
Not yet, since I don't design in that way. I am open for PR if anyone is interested to port it back to UnoCSS as a package.
