### ISSUE TITLE
LaravelMix support - Webpack plugin

### ISSUE THREAD

**Issue by ivodolenc** [unocss/unocss#797]
Hi,

Is it possible to run `UnoCSS` in the `LaravelMix` configuration?

**Project setup:**

WordPress - LocalByFlywheel - Vue3 - LaravelMix

**Example:**

Here is an example of `config` files:

```js
// webpack.mix.js

const mix = require('laravel-mix')
const UnoCSS = require('@unocss/webpack').default

/**
 * Webpack Configuration
 */
mix.webpackConfig({
  plugins: [UnoCSS()]
})

/**
 * Scripts
 */
mix.js('src/main.js', 'public/scripts/main.js').vue().extract()

/**
 * LiveReload
 */
mix.browserSync({
  proxy: 'https://local-dev.local',
  port: '6969',
  https: true,
  open: false,
  files: ['public/styles/*.css', 'public/scripts/*.js']
})
```

**Edit**
I forgot to mention, I use `BrowserSync` to track changes on save (autoreload). 

```js
// unocss.config.js

const presetWind = require('@unocss/preset-wind')

module.exports = {
  presets: [presetWind()],
  rules: [
    // ...
  ]
}
```

```js
// main.js

import { createApp } from 'vue'
import { createPinia } from 'pinia'

import 'uno.css' // Gives an webpack error

import App from './App.vue'
import router from './router'

const pinia = createPinia()
const app = createApp(App)

app.use(router)
app.use(pinia)

app.mount('#app')
```

This leads to a webpack error.

```
webpack compiled with 1 error

ERROR in ./_virtual_\__uno.css
Module not found: Error: Can't resolve '../_virtual_/__uno.css'
```

Do you have any idea how to set up this correctly? Any advice is welcome..

Btw awesome job on UnoCSS 😉 👍🏻

**Comment by peterroe** [comment]
I meet the same problem. Did you fixed it?

**Comment by ivodolenc** [comment]
No, still throws out that warning.

**Comment by userquin** [comment]
Check https://github.com/unocss/unocss/issues/931#issuecomment-1120289227

**Comment by ivodolenc** [comment]
Hey great news! I can confirm that there is no more error in the latest version `0.33.1`. Setup is the same as above. As far as I'm concerned this can be closed as resolved.  Thanks for your work!

However, I notice that there is no speed gain over tailwind via webpack module. Is this normal? 

With `webpack/unocss` setup, I get something between 200-300 ms of compilation time which is almost the same as with tailwind.

```bash
# unocss
Compiled Successfully in 253ms

webpack compiled successfully
[Browsersync] Reloading Browsers...
```

With `vite/unocss` setup it's superfast, like 10-20ms 😃 

Since I have a custom `wordpress` project, it’s too complicated to set up `vite` so I can’t use it.

**Comment by userquin** [comment]
> However, I notice that there is no speed gain over tailwind via webpack module. Is this normal?

I think it is webpack, but hey 300ms is fast compared to the time of bundling...

closing this

**Comment by userquin** [comment]
> Hey great news! I can confirm that there is no more error in the latest version `0.33.1`. Setup is the same as above. As far as I'm concerned this can be closed as resolved. Thanks for your work!

From a fresh install? it has not been fixed, the `@unocss/webpack` package still using `unplugin 0.6.2` and we need `0.6.3`.

**Comment by ivodolenc** [comment]
> I think it is webpack, but hey 300ms is fast compared to the time of bundling...

@userquin, Yep it's still fast 👍

> From a fresh install? it has not been fixed, the @unocss/webpack package still using unplugin 0.6.2 and we need 0.6.3.

The setup is like from the first comment. I only added the latest versions of unocss:

```json
{
  "@unocss/webpack": "^0.33.1",
  "unocss": "^0.33.1",
}
```
