### ISSUE TITLE
Use icon classes dynamically (from prop)

### ISSUE THREAD

**Issue by demiro** [unocss/unocss#801]
Hello,

so I have a component that has an icon as definedProp and I would it like to work like this

`const props = defineProps<{icon?: string}>();`
.
.
.

`<div v-if="icon" :class="`carbon-${icon}`" />`

When I use it like
`<MyComponent icon="printer" />`

it is not working... I just get rendered
`<div class="carbon-printer"></div>`

without an actual svg

if I do
`<carbon-printer>` it actually work

**Comment by antfu** [comment]
https://windicss.org/guide/extractions.html#extractions

**Comment by chris-zhu** [comment]
This is expected behavior, please use full name instead of it.  ( #785 )
If the behavior is predictable, try using the `safelist`

**Comment by antfu** [comment]
Icons should be prefixed with `i-`. Please share a minimal reproduction otherwise it hard to help without your configuration.

**Comment by PMLS3** [comment]
> Icons should be prefixed with `i-`. Please share a minimal reproduction otherwise it hard to help without your configuration.

https://github.com/PMLS3/nuxt3-unocss.git

Here is a minimal setup - thank you

**Comment by userquin** [comment]
You must install mdi dep
