### ISSUE TITLE
Preset wind - Border appears on all sides even when setting only one side

### ISSUE THREAD

**Issue by Extarys** [unocss/unocss#803]
In the [tailwind docs](https://tailwindcss.com/docs/border-width#individual-sides):
`<div class="border-t-4 border-indigo-500 ..."></div>`
should put a border only on the top side.

Trying it results in having a border all around:
`<div class="border-t-4 border-indigo-500 w-1/2">Fail</div>`
![image](https://user-images.githubusercontent.com/11581433/162018870-368293ca-a4b3-407a-92b7-f75678792e73.png)

Generated CSS (FF Dev tools):
```
.border-indigo-500 {
  --un-border-opacity: 1;
  border-color: rgba(99,102,241,var(--un-border-opacity));
}
.border-t-4 {
  border-style: solid; // <<--- This should be border-top-style
  border-top-width: 4px;
}
.w-1\/2 {
  width: 50%;
}
```

**Comment by chris-zhu** [comment]
Your code does not reproduce.

[playground](https://unocss.antfu.me/?html=DwEwlgbgBA7gtAMwK4BsVQSgpgDw9nOAYwHt0wAXLAWwGdisA7KgJygCslaKwEBPBsyxtqFAEwAGAHwAoKFFCQoRFAENatALwAiAEYkWIYXApwALFH2HjYRuADmJOAFYJE2HACMAejHapSIwkRBrA3uAQsvLAuizeUQoRlgZGLCbmydZptg5Oru7wrgCkAUEhtGERCTFx1UkwOj5%2Bmak6phY5YI4ubv6BwaHhkLKVwzIyQA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owCqWEZF1tAgjDFMAEYCuMYOgCecAL5x0UCCDgByPowDGVKnIBQ61AA9IsFBgCGfADbw0mHPkLAiACgTq45SjRhUAXHADaT5y9Z6RjsAShI-ZxY3Di5eASFhUPD-AF1kuChTai9ffx85JT4qGBkAWkyTVDkyJCUIE2gvOUpkOXEUvw6xEKA&options=N4IgzgLgTglgxhEAuaBXApgXyA)

**Comment by Extarys** [comment]
I'm not sure how to add it in the playground, but this is using preset-wind.

**Comment by chris-zhu** [comment]
> I'm not sure how to add it in the playground, but this is using preset-wind. It would be quite strange as I'm using an empty project.

Add `presetWind` or `presetMini` is the same effect (add  preset package in playground config option). Maybe you should check local version in you project try to resolve it

[playground](https://unocss.antfu.me/?html=DwEwlgbgBA7gtAMwK4BsVQSgpgDw9nOAYwHt0wAXLAWwGdisA7KgJygCslaKwEBPBsyxtqFAEwAGAHwAoKFFCQoRFAENatALwAiAEYkWIYXApwALFH2HjYRuADmJOAFYJE2HACMAejHapSIwkRBrA3uAQsvLAuizeUQoRlgZGLCbmydZptg5Oru7wrgCkAUEhtGERCTFx1UkwOj5%2Bmak6phY5YI4ubv6BwaHhkLKVwzIyQA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmANHGFKgM6owDq2yZF1tAgjDFMAEYCuMYOgCecAL5x0UCCDgByPlggBjKlTkAoDagAekWCgwBDPgBt4aTDnyFgRABQINccpRowqALjgBtZy9dWekZ7AEoSfxcWdw4uXgEhYTCIgIBdFLgoM2pvPwDfOWU%2BKhgZAFos01Q5MiRlCFNobzlKZDlxVP9OsVCgA&options=N4IgzgLgTglgxhEAuaBXApgXyA)

> But I'm not sure what are the differences between preset-uno and preset-wind since the classes you are using are the same and preset-wind wasn't imported. Might ditch wind and just use preset-uno 🤔

You can simply understand that `presetUno` is equal to `presetWind`, `presetWind` includes `presetMini`

**Comment by Extarys** [comment]
I have no idea then why I'm having such issues but next time I'll test in the playground.

Thanks for your time :)

**Comment by julien-terral** [comment]
Hello, I have the exact same weird behavior too.

![Image](https://i.ibb.co/chGS7Yg/Capture-d-e-cran-2022-04-09-a-18-40-19.png)

I tried in the unocss playground, it works fine, any idea please?
