### ISSUE TITLE
[bug] Playground Unresponsive

### ISSUE THREAD

**Issue by zojize** [unocss/unocss#804]
## What Happened

I was testing something with the variant group transformer, but soon I found that the website was stuck on the following HTML content:

```html
<div class="w-10 h-10 border-(~ rounded dashed gray-400 opacity-80)"
```
[repro link](https://unocss.antfu.me/?html=DwEwlgbgBAxgNgQwM5ILwCIDuBaAjABigAs9CAjAewCcQBTK7ACgD8oqKBXAOzpChGRFafAOZUEAT2wAWfIQoAHBDDAAXKQA58ASnRA) (this will open an unresponsive page)

After some investigation, I found that this has nothing to do with the transformer but seems like it was with the extractor, and I wasn't able to reproduce this in a project so this might be playground specific.

<img width="867" alt="image" src="https://user-images.githubusercontent.com/52692296/162105029-571bb0c3-aff9-4b6f-9706-3724d44ce962.png">

**Comment by userquin** [comment]
use `<div class="w-10 h-10" border="~ rounded dashed 1px gray-400 opacity-80">XXX</div>`

**Comment by SIGUSR97** [comment]
> use `<div class="w-10 h-10" border="~ rounded dashed 1px gray-400 opacity-80">XXX</div>`

Your code is correct but it does not address the problem... Copying my code above to playground will still kill it.

**Comment by userquin** [comment]
I check your repo, we need to investigate it

**Comment by userquin** [comment]
@SIGUSR97 this works with no error, just closing the div and adding some text: [playground](https://unocss.antfu.me/?html=DwEwlgbgBAxgNgQwM5ILwCIDuBaAjABigAs9CAjAewCcQBTK7ACgD8oqKBXAOzpChGRFafAOZUEAT2wAWfIQoAHBDDAAXKQA58ASnQA%2BAB5HgAenAQ9QA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHCjjUrAFxwA2itV7azeqxjUAtOrGpaAGkRxmEMdB20oqZLTIBdA-6kAJRAA&options=N4IgzgLgTglgxhEAuaBXApgXyA)

**Comment by SIGUSR97** [comment]
> @SIGUSR97 this works with no error, just closing the div and adding some text: [playground](https://unocss.antfu.me/?html=DwEwlgbgBAxgNgQwM5ILwCIDuBaAjABigAs9CAjAewCcQBTK7ACgD8oqKBXAOzpChGRFafAOZUEAT2wAWfIQoAHBDDAAXKQA58ASnQA%2BAB5HgAenAQ9QA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHCjjUrAFxwA2itV7azeqxjUAtOrGpaAGkRxmEMdB20oqZLTIBdA-6kAJRAA&options=N4IgzgLgTglgxhEAuaBXApgXyA)
> 
> `<div class="w-10 h-10 border-(~ rounded dashed gray-400 opacity-80)">xxx</div>`

You're not getting the point. The point is, I should not experience any error or entire page halting as I'm halfway typing my HTML. I know how to write the above code correctly, I'm here to address the issue that the playground abnormally halts with an unclosed HTML tag input. Hope I've made myself clear this time.

**Comment by chris-zhu** [comment]
> ## What Happened
> I was testing something with the variant group transformer, but soon I found that the website was stuck on the following HTML content:
> 
> ```
> <div class="w-10 h-10 border-(~ rounded dashed gray-400 opacity-80)"
> ```
> 
> [repro link](https://unocss.antfu.me/?html=DwEwlgbgBAxgNgQwM5ILwCIDuBaAjABigAs9CAjAewCcQBTK7ACgD8oqKBXAOzpChGRFafAOZUEAT2wAWfIQoAHBDDAAXKQA58ASnRA) (this will open an unresponsive page)
> 
> After some investigation, I found that this has nothing to do with the transformer but seems like it was with the extractor, and I wasn't able to reproduce this in a project so this might be playground specific.
> 
> <img alt="image" width="867" src="https://user-images.githubusercontent.com/52692296/162105029-571bb0c3-aff9-4b6f-9706-3724d44ce962.png">

I also reproduced. 
> Action: In playground with default demo code, then keep deleting code.

This doesn't seem to be a problem with the `extractor`. It is suspected that the wrong parsing of `codemirror` caused the page to crash

![image](https://user-images.githubusercontent.com/42139754/162869802-253d067b-3d9e-41bc-a1f2-57a5eacf213c.png)
