### ISSUE TITLE
vscode 插件提供 class 模式转换成 attributify 的功能的可能性

### ISSUE THREAD

**Issue by Lanseria** [unocss/unocss#808]
我正在改写class
like this:
```html
<a  class="border border-gray-200 rounded px-4 py-2 text-gray-600 text-sm mx-1">
高德地图
</a>
```
转换成
```html
<a
  border="~ gray-200"
  rounded
  p="x4 y2"
  text="sm gray-600"
  m="x1"
>
  高德地图
</a>
```

有可行性嘛

**Comment by antfu** [comment]
https://twitter.com/wheatjs/status/1387583803661684745

/cc @wheatjs

**Comment by antfu** [comment]
> `a` 标签的中 `text` 似乎是冲突的，有解决方案吗? 去windcss找了，似乎没人提

In attributify mode, you can always use prefixes like `uno-text` to avoid conflicts.
