### ISSUE TITLE
border-left-style-solid  border-l-style-dotted  Cannot take effect

### ISSUE THREAD

**Issue by cll123456** [unocss/unocss#820]
`‘border-left-style-solid’` `‘ border-l-style-dotted’`  Cannot take effect
![image](https://user-images.githubusercontent.com/41314419/162912591-d81ed2c3-aead-414e-baba-c169e5c491ba.png)

**Comment by xiaojieajie** [comment]
border-solid or b-solid

**Comment by cll123456** [comment]
> border-solid or b-solid

yes, you are right, but it's use to set boder all style. but i just wanna set left style

**Comment by cll123456** [comment]
> border-solid or b-solid


@xiaojieajie 
 yes, you are right, but it's use to set boder all style. but i just wanna set left style

**Comment by xiaojieajie** [comment]
![image](https://user-images.githubusercontent.com/39750199/162925870-98e92c1d-66e3-4aca-b885-8c1e554b34fe.png)

**Comment by cll123456** [comment]
@xiaojieajie thanks
