### ISSUE TITLE
[bug] `@unocss/transformer-variant-group` transforms empty variant when there is extra space after ( and before ) and between classes

### ISSUE THREAD

**Issue by itsmnthn** [unocss/unocss#828]
It seems `@unocss/transformer-variant-group` generates extra class on class attribute when there is space after `(` and before `)`

For example below code transforms
```HTML
<div class="before:( dark:bg-dark bg-light opacity-0 ) hover:( before:opacity-100 )" ></div>
```
as below
```HTML
<div class="before: before:dark:bg-dark before:bg-light before:opacity-0 before: hover: hover:before:opacity-100 hover:" ></div>
```

For each extra space inside `()` we have empty variant as mentioned in above example

**Comment by david-plugge** [comment]
Same issue here and vscode does not provide any information about the class without a space.
