### ISSUE TITLE
[bug]: 从ts中引入icon名称加载为动态calss时，图标不显示

### ISSUE THREAD

**Issue by yanbowe** [unocss/unocss#829]
问题描述: 
当我将icon名称放置ts中，引入vue文件作为动态class时，无法显示图标
![image](https://user-images.githubusercontent.com/43030980/163529574-646e333d-e494-41e2-a15f-71e7b2d436d4.png)
![image](https://user-images.githubusercontent.com/43030980/163529680-e34cad14-bd6f-4d0a-b802-c2e977f81ce1.png)

![image](https://user-images.githubusercontent.com/43030980/163529560-cdba344b-4910-4dcc-9e75-45b1129bed4e.png)

复现仓库：https://github.com/yanbowe/vite-vant-demo

**Comment by antfu** [comment]
Try adding `// @unocss-include` to your TS file.

**Comment by antfu** [comment]
https://github.com/unocss/unocss#scanning

**Comment by yanbowe** [comment]
> // @unocss-include

thanks, It's ok
