### ISSUE TITLE
后定义的样式无法覆盖前面的，如：在组件内外定义了相同的样式，组件内部的会被应用。按照常理，应该应用外部定义的

### ISSUE THREAD

**Issue by Fate-ui** [unocss/unocss#835]
![image](https://user-images.githubusercontent.com/69997002/163709053-73f429ab-890d-4ad6-b9d7-d0b1db4f833c.png)
![image](https://user-images.githubusercontent.com/69997002/163709059-e873ccc8-67bd-42a2-b909-da59961a88f3.png)

**Comment by antfu** [comment]
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.
