### ISSUE TITLE
[BUG] Class-names created from wrong attributes

### ISSUE THREAD

**Issue by MathiasWP** [unocss/unocss#838]
I checked one of the generated CSS files from using unocss, and noticed that there were a lot of weird classnames. After searching for similar names throughout my codebase i found that unocss was generating classnames from a "d" attribute on a `path` element.

This behaviour heavily pollutes the bundled CSS.

I've created a repo that reproduces the bug with minimal setup: https://github.com/MathiasWP/unocss-attribute-bug

**Comment by action-hong** [comment]
try this 

```
  presetAttributify({
    strict: true,
  }),
```
