### ISSUE TITLE
separator config

### ISSUE THREAD

**Issue by Youdaman** [unocss/unocss#839]
Is there a way to set the separator character?

e.g. https://tailwindcss.com/docs/configuration#separator has:
```js
module.exports = {
  separator: '_',
}
```

However trying to add this to unocss.config.ts warns:
> Object literal may only specify known properties, and 'separator' does not exist in type 'UserConfig<{}>'.ts(2345)

I'm wanting to use Pug in my templates which does not accept `:` in class names.

My current workaround is instead of:
```pug
    .shrink-0.w-4.sm:w-48
```
I instead write:
```pug
    .shrink-0.w-4(class="sm:w-48")
```

**Comment by antfu** [comment]
In variants, `:` and `-` are interchangeable. Hope that fits what you need.

**Comment by Youdaman** [comment]
Perfect! Thank you.
