### ISSUE TITLE
Unnecessary Scope for Icons

### ISSUE THREAD

**Issue by equt** [unocss/unocss#847]
After setting the `mode` to `vue-scoped`, the preset `@unocss/preset-icons` also bundles scoped icons data, which is unnecessary since

1. in most cases, the same identifiers refer to the same icon, and
2. this leads to a bug that the actual icon data is required by a child component ([minimal reproducible example](https://github.com/equt/unocss-preset-icons-vue-scoped)).

Think of two components, `<a-button />` & `<an-icon />`, where `<a-button />` calls `<an-icon />` to handle the icon rendering & styling stuff, and only the `<a-button />` gets exposed, the icon data will not available to the internal `<an-icon />` component.

**Comment by equt** [comment]
P.S., this should be doable by a hole in the core package to allow bypassing the scoping-related logic.

**Comment by antfu** [comment]
That's how `scoped` is supposed to work, isn't it? If you don't need this behavior, why configure the mode to it?

**Comment by equt** [comment]
Well, that seems to make sense.
