### ISSUE TITLE
Attributify mode not working in Svelte

### ISSUE THREAD

**Issue by juanmesa2097** [unocss/unocss#859]
I'm trying to use the [attributify](https://github.com/unocss/unocss/tree/main/packages/preset-attributify) mode in a Svelte (vite) project but it doesn't work at all

![image](https://user-images.githubusercontent.com/64181348/164610884-ba2fb144-4c37-4e27-b876-5a497224565d.png)

The styles are being included
![image](https://user-images.githubusercontent.com/64181348/164611065-ec3a850e-e189-4660-9ddc-c0c85d14f34f.png)

But are not being applied
![image](https://user-images.githubusercontent.com/64181348/164611331-0d4b54c8-0df5-4365-88f9-8d95dcfd7654.png)

Plugin config
![image](https://user-images.githubusercontent.com/64181348/164611436-8bb3aead-d209-48e0-9bf3-0a8fa7716e36.png)

package.json
![image](https://user-images.githubusercontent.com/64181348/164611541-6ede1702-d533-41a3-a325-343d2a5fb19f.png)

I tested this with vue using the same configuration and it worked successfully

**Comment by userquin** [comment]
You should add svelte plugin after unocss plugin, read the readme file on vite folder. Attributify will not work well with svelte.

**Comment by juanmesa2097** [comment]
@userquin thank you, it worked as you recommended.
