### ISSUE TITLE
neovim/LSP support

### ISSUE THREAD

**Issue by Suyashtnt** [unocss/unocss#869]
read the title.

The best way would be to turn the vscode extension into an LSP and make separate packages for integration into various IDEs (or in neovims case addition to nvim-lspconfig).

**Comment by Suyashtnt** [comment]
This would also allow support for other IDEs btw :)

**Comment by ouuan** [comment]
It seems that the `exemptLabels` setting for the stale bot only works when the `stale` tag is not added :thinking:

**Comment by xna00** [comment]
Try https://github.com/xna00/unocss-language-server
