### ISSUE TITLE
divide class issue

### ISSUE THREAD

**Issue by imbeard** [unocss/unocss#873]
I have a problem with divide class (using unocss with vite)  is not working as expected, I'm using latest unocss version

looks incorrect on unocss site too: https://unocss.antfu.me/?html=DwEwlgbgBAxgNgQwM5ILwCIBGBzAtJxGAaymwCcwRSKRcYB7OJXAJinAkoFNcB3ACzAAXLu0jdcSRpTGcQPAJ6yJADygiVQvoJFQAtitwIArkPrqumulwB2IsuihIhCuFwxCyCG0gBm9Mj0ALicYBDcACgBGAEoAbnQAPgAoAEhU0EhEgE5gAHoORMyIRIA5fMK0jMKADgqs4sSASXqSqsaAdlaiwvKCrPbCgDZuxoBRbsGsgFZRwoAVSfTGgBY5rIB5JeqsgGZ1koAtbcaWA8SJ-rblwqjzgCUTwoAGc62rlIyPoA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHCjjUrAFxwA2itV7azeqxjUAtOrGpaAGkRxmEMdB20oqZLTIBdA-6kAJRAA&options=N4IgzgLgTglgxhEAuaBXApgXyA

**Comment by chu121su12** [comment]
If I'm interpreting correctly, you are using `divide` for 2d-grid (divide-x and divide-y together). The divide-x/y don't work for this case. It only work on 1-d row or column. See the generated css in the playground.

**Comment by imbeard** [comment]
Ok thanks for the clarification!
