### ISSUE TITLE
VSCode extension not showing annotations for variant groups

### ISSUE THREAD

**Issue by tgrelka** [unocss/unocss#875]
VS Code will not show annotaions for variant groups, to profit from the extension, one has to type out each single classname.
I know there is complexity involved with correctly recognising these, as well as transforming both ways to generate the required tooltip information, and then back to generate the correct editor decorations (e.g. the tooltip for `border` should end up with `~` in the end, and `border-2` with `2`.)

Please see an attached example of where the plugin fails: (`border-(~ 2)` vs `border border-2`)
![CleanShot 2022-04-26 at 08 45 55](https://user-images.githubusercontent.com/22134144/165238472-0968456d-b1ca-4c36-ae6c-25b2d4bdd9fa.png)

**Comment by antfu** [comment]
I would perferally suggest to use [attributify](https://github.com/unocss/unocss/tree/main/packages/preset-attributify) over variant groups.

**Comment by tgrelka** [comment]
Attributify is a mixed bag for me.
Unlike the screenshot suggests, I actually use pug most of the time for html / templates, it’s much more comfortable to use and refactor. However, when working with web frameworks and components, much of the actual html I end up writing is just divs for layouting and structure - where I hugely benefit from pug’s shorthand for divs with classes `.max-w-25rem.w-full` e.g. instead of `div(class="max-w-25rem.w-full")`.
I know the VSCode extension doesn’t work with pug at all (at least for me), so in that case this whole issue does not matter.
Another problem I have with attributify is the visual clutter it introduces. Being able to organise attributes instead of having one large class string is great, until you end up with seven lines of attributes per element, plus the functional ones (binding props, events, etc. in Vue, e.g.) I much prefer being able to visually quickly differentiate between what is functional and what is styling, which I feel like attributify doesn’t offer, especially with pug.
Thirdly, since I work with bootstrap and use UnoCSS to fill the gaps (like replacing all bootstrap utilities to be more flexible regarding sizing and positioning), I use classes anyway, and many additional stylings just sparingly - same goes for variant groups, it’s not often I need them. In that case, attributify no longer offers any advantage for me.

I realize this turned into quite a long text, and I want to assure you this is not a rant - I think attributify is awesome for people who use UnoCSS or Windi in the “traditional” way, but just not the right tool for me.

Anyway, I’ll take a look at the code and familiarise myself with the way the extension generates the annotations, maybe I can provide an implementation for this. Thank you for your work with UnoCSS, and all the other open-source projects you created and/or contribute to!
