### ISSUE TITLE
[preset-uno & preset-attributify] weird behaviour of text-transform utilities 

### ISSUE THREAD

**Issue by teenjuna** [unocss/unocss#876]
So, I'm using `preset-uno` and `preset-attributify` (with TypeScript) and want to make my text `uppercase`. The only way do it without errors is using `class="uppercase"`. When I try to specify just the `uppercase` attribute on the tag, it actually works on the page, but I get `TypeScript` error telling me that there's no such attribute (because it's not specified [here](https://github.com/unocss/unocss/blob/d515bc677b4ccd1d3b7a0fa1c8f764dc9015f28b/packages/preset-attributify/src/jsx.ts#L1) I guess). By the way, the behaviour is the same with `lowercase` and `capitalize`.

And that's not all. Somewhere here I've read that there's also `case-` attributes (`case-upper`, `case-lower`, etc.). When I try to use them, I receive no type errors, but they don't affect the page (e.g. don't work).

**Comment by teenjuna** [comment]
Similar situation with the `scale` attribute.

**Comment by chu121su12** [comment]
The case-x rules are available in preset-mini. Currently when exporting the rules collection for preset-wind which is fhe base of preset-uno, some of the rules from mini don't get included, and case-x is one of them.

**Comment by teenjuna** [comment]
A couple of questions:

1. Why are those styles not included?
2. How to deal with attributify types? Looks like they aren't really related with the presets, so that I can have an utility available in classes but not in attributes and vice versa. 

For the second point: I guess there are two ways: add absolutely all available utilities to the attributify types (which will make typeacript accept many attributes from presets that are not included; and which is probably not possible anyway) or somehow split attributify for different presets (like `preset-attributify-uno` or, even better, specify the presets as arguments to the `preset-attributify`).

**Comment by chu121su12** [comment]
1. The uno-preset is based off as an alias of preset-wind. While preset-wind tried to follow windi/tailwind, some of the rules were skipped. I'll try to open a PR to re-add missing preset-mini rules onto preset-uno.
2. I'm sorry I can't realy help with the types. Code-wise, preset-attributify is a separate extractor that account for attributes to be extracted out for rule-matching, along with variant that helps 'translating' the atteibute-based tokens into the version that the regular rules can match. So it generates attributify classses only when the non-attibute version of the class can be matched by the currently loaded rules.
