### ISSUE TITLE
[bug] Attribute mode doesn't work with SolidJS components

### ISSUE THREAD

**Issue by teenjuna** [unocss/unocss#878]
I have a component:
```ts
import { Component, JSX } from "solid-js";

export type CardProps = JSX.HTMLAttributes<HTMLDivElement>;

export const Card: Component<CardProps> = (props) => {
  return (
    <div p-4 bg-white rounded-2xl {...props}>
      {props.children}
    </div>
  );
};
```

It extends Solid's `JSX.HTMLAttributes`, so it can receive UnoCSS attributes. But when I try to use them with the component, they don't work (although they are accepted as valid props by TypeScript).

In other words, this works:
```ts
<Card class="h-full text-center group-hover:shadow-lg group-active:shadow-none">
  content
</Card>
```
But this doesn't:
```ts
<Card h-full text-center group-hover="shadow-lg" group-active="shadow-none">
  content
</Card>
```

In the latter case, the attributes are present in HTML, but the styles for them are not generated (note that the attributes specified in the root tag of the `Card` component (e.g. `p-4 bg-white rounded-2xl` do have generated styles).

A person in Solid's discord suggested the following:
> Most likely it's failing because uno is running too late, after solid's transform.
Classes work because it looks like uno just looks for strings, so it doesn't matter what solid does, the strings are still intact: https://github.com/unocss/unocss/blob/main/packages/core/src/extractors/split.ts
But attributify fails because it's looking for tags, which are already transformed into `createComponent` calls: https://github.com/unocss/unocss/blob/main/packages/preset-attributify/src/extractor.ts

I tried changing Vite config: put `solidPlugin` after `unocssPlugin` and set `enfore: "post"` for `solidPlugin`. It didn't help.

**Comment by XiNiHa** [comment]
It's happening because SolidJS passes valueless attributes as boolean props. So just supporting `[attr="true"]{...}` will make it work
