### ISSUE TITLE
Where is the docs website?

### ISSUE THREAD

**Issue by SnowingFox** [unocss/unocss#880]
It may be my own reason, but I searched `README` and didn't see the link of the document website, which means we need to build the document with the [docs](https://github.com/unocss/unocss/tree/main/docs) in the repo?

**Comment by SnowingFox** [comment]
> It may be my own reason, but I searched `README` and didn't see the link of the document website, which means we need to build the document with the [docs](https://github.com/unocss/unocss/tree/main/docs) in the repo?

I just find the playground..

**Comment by userquin** [comment]
@SnowingFox we're working on it, stay tuned...

**Comment by SnowingFox** [comment]
> 

@userquin Can i working for this project? I love the atomic css,  i want to contribute to this

**Comment by kecrily** [comment]
[Interactive docs](https://uno.antfu.me).

Of course we may also need an explanatory document, although the README already has many explains.

**Comment by kecrily** [comment]
May not. It should be as used as in the framework, how to create a class that belongs to your own presets in my opinion.

**Comment by antfu** [comment]
https://twitter.com/antfu7/status/1519684898344554500

We will keep improve it and full fill it with more entries.

**Comment by SnowingFox** [comment]
> https://twitter.com/antfu7/status/1519684898344554500
> 
> We will keep improve it and full fill it with more entries.

That's great. I think unocss can write atomic CSS on the attributes of DOM is great and more convenient. I want to make some contributions to this. Can I participate in the improvement of this document?

**Comment by antfu** [comment]
> Can I participate in the improvement of this document

Sure thing. We are always open for PR and contributions.
