### ISSUE TITLE
unocss will lost class when use attribute mode on merge

### ISSUE THREAD

**Issue by TangsWang** [unocss/unocss#913]
unocss会丢失class， 当使用属性模式书写融合的时候，
例如：

`<p m-1 p-1 :class={...}> ` ...里的class会编译丢失。
另外就是使用组件时，组件上的属性模式class和组件内部根组件的属性模式class融合会有问题。

用class=“”正规书写方式，则没有问题。

**Comment by TangsWang** [comment]
@antfu :)

**Comment by action-hong** [comment]
给个复现的例子嗯

**Comment by TangsWang** [comment]
> 给个复现的例子嗯

sorry, 我复现发现好像不是unocss的问题，而是nuxt3 中 nuxt-layout组件的问题，

当使用nuxt-layout作为组件顶层元素时，nuxt-layout响应动态class会有问题。

**Comment by antfu** [comment]
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.
