### ISSUE TITLE
backdrop merging

### ISSUE THREAD

**Issue by ameinhardt** [unocss/unocss#918]
In WindiCSS, I would combine (light/dark) backdrop filter like `backdrop-blur-sm backdrop-brightness-75 dark:backdrop-brightness-125`. It works fine in @apply and inline.
In UnoCSS, I noticed that @apply doesn't merge but overwrites all `backdrop-*` filter of an element. Inline works better, but the `dark:backdrop-` still overwrites the other backdrop-filters.
Would you elaborate on how [the array response](https://github.com/unocss/unocss/blob/e7d2fa0e2979d2be8a309408a22a03cdf75aede1/packages/preset-wind/src/rules/filters.ts#L50-L57) with CONTROL_SHORTCUT_NO_MERGE for dynamic rules/shortcuts is (supposed to be) used in these cases?

See [overlay example in playground](https://uno.antfu.me/play/?html=DwEwlgbgBAFgtAMwK4BsVQC4FMAeG4DGWAdtgE5QIq5QDOW1B%2BxA9sVlAIZoBcGZnYrTAYwbOABYADFIB8AKChRQkKAFtOCpUpXRseOAFYc6BAHcAjDK7EwG7HABGLJMSJxuGG3c4OCL0jgwYgRgkQ5BHwcLWi1tJVcWAlpaRW1gAHpwCDidbKgWAAcAZilMXHwUAHNKM1KytQtc7QAVGA5g2gxBL3EQLA1iECgAQQwWNTACKABhAGU5qBIq4KwAOjSdLMhm3XUAJkpqHCgAKyQusAQAT0IScnKDfZMCkrKYFggsMgBeACIigAOKR-Zo6TibeJQMCEThkZzEOAoFhVFhwFYYGBIRyQ%2BL6fDBdpkES47QwMhYBD-GAYDCFWg8DIZDFYxxrfxqDKJZK0LmsHl-UlKbpkKpYDD-AD6jhQggA1oKoVBZJlNJDMtk4hqdvJtTldflOI5aCwUEhsFBnLSJkYoMSqjS4GVqAh8GV8XdSN9XqVavU4n0BoJhgB26FCbqkKBh5Boa5QAgXcaTABeRuouu2%2Br2RpNZot40KTtgiFQ6DMpbQls4BDlIDIRScZrIcFoaigIDhcp4jhrdYbRcc9pp7BScH2MhVWdkQA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHCjjUrAFxwA2itV7azeqxjUAtOrGpaAGkRxmEMdB20oqZLTIBdA-6kAJRAA&options=N4IgzgLgTglgxhEAuaBXApgXyA) (btw., maybe playground [forwards](https://github.com/unocss/unocss/blob/832c201f7995d8601b37c3b5f3bb62bd85d34ffd/playground/src/logics/url.ts#L15) to wrong baseurl / instead of /play ?)

**Comment by antfu** [comment]
Should be fixed.
