### ISSUE TITLE
move docs and playground into place

### ISSUE THREAD

**Issue by veritem** [unocss/unocss#921]
Having playground and docs in different places doesn't resonate with me. I wished we could have them in the same place.

I can do it if you allow :)

**Comment by antfu** [comment]
What's your plan for it?

**Comment by veritem** [comment]
I would create a new route on interactive docs and put playground there.

**Comment by antfu** [comment]
Well you can try on that if you want to. But what would be a huge task to migrate as the playground is built on Vite while the docs are Nuxt 3. The subentry __play.html would be a challenging one.
