### ISSUE TITLE
issue(preset-attributify) (group-{modifier})

### ISSUE THREAD

**Issue by zirbest** [unocss/unocss#925]
```html
<div grid place-content-center h-full font-sans all:transition>
<button bg-blue2:20 b="~ blue9" p="x3 y2" group
        active="outline outline-blue">
  <span v-text-bottom>CLICK</span>
  <span
        i-carbon-arrow-right inline-block v-base 
        transform group-hover:translate-x-1
        />
</button>
</div>
```
not working
until
```diff
-<button bg-blue2:20 b="~ blue9" p="x3 y2" group"
+<button bg-blue2:20 b="~ blue9" p="x3 y2" class="group"
.
```
[REPL](https://uno.antfu.me/play/?html=DwEwlgbgBA5gTmEUAOAbAhgYwKYFpMD2AdgC7an7llxQAWuAZgK6qpQPEm4DO6R3UdKwBcJOH25gSYYgD4AUMACEuXFGAAjJiRLEoGmLg2om2AEzCzABn0BeAEQA-fSewBOeygcAPAMxQATzNPeAImZChVBU1tXSJ9Q2NTC2s7JxdTDy97P0DgqEwMbm4HUPD7eSgq6qqsaQhsBzCSVDAibChm1vajV3sFKuBuZD4oCFwyby4NAh0CAFtZAGEAGQBJJYBpYAB6Yb4B9X2iSprqsHx0OBmiXCu4AgB3XAQYWhIoNu68YwJMAGsxkZ0NwOqczlAxBIOHB5rAHuFcLQCA04KJxPwMGRcN5cABGcFnHbRHZaOZEEngCAKIA&config=JYWwDg9gTgLgBAbzgEwKYDNgDtUGEJaYDmcAvnOlBCHAOQCuWEAxgM6u0BQnqAHpLBQYAhvQA28NJhz5CwIgAoEnOHCjjUrAFxwA2itV7azeqxjUAtOrGpaAGkRxmEMdB20oqZLTIBdOwaqgXDBegD0AHomZpYKADrIANQAlBYKAHQpACRhDgq6dsgOWMIgqP6hjlDCAO4Ayqg2zOZQDiZQnlgwDU0tDgBuwlDAwl0AEqPINlCsDjAAFqhlZMlwALwAfIiVzlisLqjpyMBQCoPDozATWFOoM8mVnjD0UFiqAAZZCCVl5AA%2BcC%2ByDCACZ-oCENV6o1UM1oOCvu1Ot0YXCoAiEOcRuNJtNWLoAAy%2BdIgYQwZiLdFwAFfBZLQ4AI08wgA1pBsDBWOlWCBSO8QoZBaFSL5ggZRaRkkA&options=N4IgzgLgTglgxhEAuaBXApgXyA)

**Comment by antfu** [comment]
You need to pass an additional option:

```ts
presets: [
  presetAttributify(),
  presetUno({ attributifyPseudo: true }),
],
```

**Comment by zirbest** [comment]
aaa thnks
Is there is a way to activate it automatically if the `presetAttributify` is enabled?

**Comment by antfu** [comment]
Possibly. PR Welcome.
