### ISSUE TITLE
UnoCSS vscode extension does not take effect in projects using midwayjs

### ISSUE THREAD

**Issue by biuuu** [unocss/unocss#926]
http://midwayjs.org/docs/hooks/config#vite-viteconfig
The midwayjs configuration file wraps viteconfig so it cannot be recognized by the vscode extension.

The configuration file name may be `midway.config.ts` or `midway.config.js`.
The content is as follows:
```
import vue from '@vitejs/plugin-vue'
import { defineConfig } from '@midwayjs/hooks-kit'
import Unocss from 'unocss/vite'
import { presetAttributify, presetUno } from 'unocss'

export default defineConfig({
  vite: {
    plugins: [
      vue(),
      Unocss({
        presets: [
          presetAttributify({}),
          presetUno()
        ],
      }),
    ],
  },
})

```

**Comment by antfu** [comment]
Consider moving to `uno.config.ts`. We can't possibly support every framework out-of-box.
