### ISSUE TITLE
Set shortcuts with the same name as the class

### ISSUE THREAD

**Issue by NicolaSpadari** [unocss/unocss#928]
Just started using unocss in a nuxt project, I'm migrating my `apply` classes to unocss `shortcuts`, and I'd like the container to be centered by default, like bootstrap does

My issue:
```js
shortcuts: [
  // ...
  ["container", "container mx-auto"],
  // ...
],
```

This doesn't work, the container still doesn't have the margin properties, it's intended or it's a bug?
For now I'm using another class, like `.box` for the alias.

**Comment by antfu** [comment]
This causes a circular reference and naming collision. It just won't work.

If you want to extend some utils, you could simply add

```css
.container {
  @apply mx-auto;
}
```

in your CSS.
