### ISSUE TITLE
Reuse interactive docs for custom Design System

### ISSUE THREAD

**Issue by edimitchel** [unocss/unocss#936]
I'm really enjoying UNO Interactive Docs application to let users knows how to use uno, and especially the fact it accept to understand in 2 ways: **know what specifics rules applied with a class or find out the class for applying specific rules.**

I'm working for a [design system](https://edisondesignsystem.com) where we provide few utilities classes but it's very difficult to use them, they are documented but it's splitted in differents pages.

We have customer who complaint about utility classes and the fact it's not always explicit enough. So, I thought about something Uno's Interactive Docs is exactly doing!

So, my question are:
- How difficult is to port specific utility classes (and some component BEM classes) into a preset. 
- How to incorporate that in the interactive docs without all the uno background (as we don't work with uno for the moment).

Thank you!

**Comment by antfu** [comment]
The interactive docs now support passing your own config so you can use your custom rules or preset as the source of the search result (with the setting icon). Does that fit what you need?

**Comment by edimitchel** [comment]
Our utility classes are now following tailwind or windycss naming (e.g. `.u-mb++` instead of `.mb-10`).

We don't facing surprise when creating a custom preset, right?

**Comment by antfu** [comment]
> We don't facing surprise when creating a custom preset

Sorry I still don't understand what you mean. If you just want the word, I would say yes, UnoCSS is the engine aim to support any atomic CSS you'd like.
