### ISSUE TITLE
Specifying Dynamic Class Does not Render icons

### ISSUE THREAD

**Issue by Codermar** [unocss/unocss#942]
I have:
```
<script setup lang="ts">
const iconClass = `i-symbol:${props.icon}`
</script>
```
Then in template: 

```<i :class="[iconClass]" text-10 />```

Icons do not render. Sometimes one of them does (of a group of 5) which is strange. Also if I render the icons with hardcoded names first either on the same page or some other page, they do  display  (probably using a cached icon)

Vue 3
Vitesse template with updated deps ("unocss": "^0.32.13")

**Comment by antfu** [comment]
https://github.com/unocss/unocss#safelist
