### ISSUE TITLE
Problem developing preset with HMR support & Nuxt

### ISSUE THREAD

**Issue by jd-solanki** [unocss/unocss#954]
Hi,

I am trying to create a lib and for this, I am using nuxtjs + UnoCSS.

I want to create a preset for my lib. Everything is working fine except HMR (or something else) is broken.

## Problem

When I update the `rule` of my preset it doesn't reflect in the front.

## Reproduction

- Clone the [project](https://github.com/jd-solanki/galudiyu) & change branch to **_next_**
- Run `pnpm --shamefully hoist` to install packages
- Run `pnpm run dev` for developing lib
- Run `pnpm run docs:dev` for running nuxt
- update the line `#46` in `packages/galudiyu/src/presets/theme-default/index.ts` so that it updates the `btn` class

Notice, there's no change in nuxt app.

I don't know what's causing this.

**Comment by jd-solanki** [comment]
I also tried `configDeps: ['node_modules/galudiyu/**'],` bit it's not working 😢

**Comment by jd-solanki** [comment]
Closing this as I am not working on it now and it might now be valid

**Comment by hi-ogawa** [comment]
(Sorry to comment on already closed issues)

I think I had a potentially same issue when creating a toy unocss plugin of my own.
I didn't dig into the detail, but my quick hack was to create a tiny vite plugin to invalidate `require.cache` of local monorepo dependency and `touch uno.config.ts`.
Here is the code: https://github.com/hi-ogawa/unocss-preset-antd/blob/7efed8414be77496255f0067a661d0a6185ff0d3/packages/app/vite.config.ts#L21
It might not work for every use case, but I hope it could give some hint of the underlying issue.
