### ISSUE TITLE
How to dynamically import icons instead of directly use them in templates

### ISSUE THREAD

**Issue by widcardw** [unocss/unocss#955]
I'd like to dynamically import icons instead of directly use them in templates. However, I cannot see the icons, until I add them to template manually. 

So I wonder that whether unocss can read the `.ts` or `.json` file to import icons...
<img width="1570" alt="Snipaste_2022-05-10_19-21-58" src="https://user-images.githubusercontent.com/55699713/167617755-47bff407-6b10-4dd9-acf3-dec18e693fda.png">

**Comment by chris-zhu** [comment]
Yes, it's surpported.  And it works successfully in my project.

**Comment by antfu** [comment]
https://github.com/unocss/unocss#scanning

**Comment by zhuzhuaicoding** [comment]
> https://github.com/unocss/unocss#scanning

no scanning section

**Comment by widcardw** [comment]
> no scanning section

https://unocss.dev/guide/extracting#extracting-from-build-tools-pipeline
