### ISSUE TITLE
Unknown file extension ".json" when using `@unocss/preset-icons`

### ISSUE THREAD

**Issue by SnowingFox** [unocss/unocss#960]
This is reproduce https://stackblitz.com/edit/github-rgqsff?file=vite.config.ts

I cannot import 'json' file when using dynamic import

**Comment by whidy** [comment]
for example

```js
collections: {
  mdi: () => import("@iconify-json/mdi/icons.json", { assert: { type: "json" }}).then(i => i.default),
},
```

**Comment by Aex12** [comment]
I'm having the same error. I cant seem to make this work with Typescript/Vite project using ESModules

**Comment by SnowingFox** [comment]
> I'm having the same error. I cant seem to make this work with Typescript/Vite project using ESModules

`import()` is brower's api, not nodejs. you can use `required()` instead
