### ISSUE TITLE
Safelist within Presets not working

### ISSUE THREAD

**Issue by praburangki** [unocss/unocss#968]
Try creating a custom preset and there is a `safelist` define within the preset.
When we implement the preset the safelist classes are not working.

# Reproduction

https://github.com/praburangki/reproduce-unocss

**Comment by antfu** [comment]
Interesting, I didn't expect presets to contribute to `safelist` initially. Feel free to send a PR!

Here is the reference

https://github.com/antfu/unocss/blob/6c10af9bc2608e49996b119af561b61be205d901/packages/core/src/config.ts#L75-L76

Where might want to use `mergePresets` to merge them.
