### ISSUE TITLE
css formater brokes @apply

### ISSUE THREAD

**Issue by kleinpetr** [unocss/unocss#971]
Hi guys,

what settings do you use in vscode to format your code (Vue3+TS)? Because The default formatting drives me crazy when it comes to 
 css @apply directives such as

![image](https://user-images.githubusercontent.com/17269309/168279766-43f02529-eea5-44a3-9051-0917492f388a.png)

any suggestions? Thanks :)

**Comment by antfu** [comment]
https://github.com/unocss/unocss/tree/main/packages/transformer-directives#css-variable-style

**Comment by Valentin-Seehausen** [comment]
Great!

-> Can we have better errors when the engine cannot find the directive?

Example:

This works:

```
@apply bg-gray-200;
```

This throws a complicated error:
```
@apply dark:bg-gray-200;
```

This is the error:
```
[vite] Internal server error: Cannot read properties of undefined (reading 'forEach')
  Plugin: unocss:transformers:default
```

I migrated a CSS file from an old vitesse to the current version (great library, btw). It took me 20 minutes to arrive here and understand what is happening. 

Thanks for your ultra-great work!

**Comment by kleinpetr** [comment]
cool, but it is not work for some reason :thinking: I've solved it by create a custom rules, I prefer to use attributiffy mode instead of class=".." so with rules the html looks bit more clear. But keeping in mind and will try it in the future. thanks

**Comment by antfu** [comment]
I believe this is more related to the formatter you use rather something we could do on our side.

**Comment by kleinptr9** [comment]
ok, didn't know that. I was searching in https://uno.antfu.me/?s=grid-cols
Thanks for clarify.
