### ISSUE TITLE
Release workflow failed

### ISSUE THREAD

**Issue by chris-zhu** [unocss/unocss#975]
I found the release workflow was failed
> TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of URL. Received undefined

https://github.com/unocss/unocss/blob/cb61f2a6326133c96ff364a64c03a7833f114fed/packages/vscode/scripts/publish.ts#L7

I have debugged locally, maybe `import.meta.url` was the wrong reason.

-------

Now, Interactive(0.33.1) 、Playground(0.33.1) and Vscode extension(0.33.2) version is different from the latest veison.

Please update it to be consistent.

p.s. 
I personally use `playground` a lot, but now, there is no drak mode in it. It's so terriable. hhhh😂

**Comment by antfu** [comment]
Nuxt was broken so I locked to previous version for the site before I can take time to loolk into it.
