### ISSUE TITLE
[VSCode extension]: the extension will parse the js vars as shortcut

### ISSUE THREAD

**Issue by zouhangwithsweet** [unocss/unocss#978]
<img width="557" alt="image" src="https://user-images.githubusercontent.com/21095710/168532148-845d1b59-ac1c-49a0-863e-36a02b18f460.png">

**Comment by antfu** [comment]
This is how UnoCSS works. We scan the presentation of utilities regardless of the context (we don't parse). You can avoid this by using more explicit util names.
