### ISSUE TITLE
[VSCode extension] Provide autocompletion for style file, eg `.css` file

### ISSUE THREAD

**Issue by 0x-jerry** [unocss/unocss#985]
WindiCSS provides `@apply` autocompletion for style file, eg. `.css` file. It could be very nice if this feature includes in UnoCSS extension.

![image](https://user-images.githubusercontent.com/14226737/169098229-eb5f2975-42b5-46a8-87b5-7b84db7cedbe.png)

btw, I can contribute if someone can point me in the right direction.

**Comment by NicolaSpadari** [comment]
+1

For now I just install the windicss intellisense extension and disable almost everything.
Would be nice to have some of its features in the unocss extension too
