### ISSUE TITLE
`@unocss/preset-typography` invalidates `prism` setting for background color of code block in `Vitesse`

### ISSUE THREAD

**Issue by WindyNanzi** [unocss/unocss#990]
As the title says, in the URL  [https://vitesse.netlify.app/about](https://vitesse.netlify.app/about), you can see that the background color of the code block is not displayed as it is preset. You must additionally configure 'presetTypography' in 'unocss.config.ts'.
![image](https://user-images.githubusercontent.com/39194294/169465143-fd7721a0-a399-4903-9d4c-163677803155.png)

![image](https://user-images.githubusercontent.com/39194294/169467790-6df475cc-8ebc-4ca2-8cb1-107b29dcf6f1.png)

**Comment by ydcjeff** [comment]
This is working correctly. `pre[class*=language-]` has low CSS specificity than `.prose :where(pre,code):not(.not-prose)` so the background is overwritten.
