### ISSUE TITLE
[Feature] Color preview in vscode

### ISSUE THREAD

**Issue by zam157** [unocss/unocss#993]
**Windi:**
![image](https://user-images.githubusercontent.com/24277775/169586756-49c6c5b7-b13f-4e41-b284-f829f1148754.png)

**Uno:**
![image](https://user-images.githubusercontent.com/24277775/169587060-fe5e9e58-c476-4d43-802b-f240f52e357d.png)

**Comment by antfu** [comment]
I don't need this feature personally so I might not have motivation to do it. PR welcome
