### ISSUE TITLE
use a function to get class, but no effect.

### ISSUE THREAD

**Issue by Circkoooooo** [unocss/unocss#998]
![图片](https://user-images.githubusercontent.com/75945382/169682157-af33d83a-ac8d-4c3d-bb5e-0449e94464e1.png)
![图片](https://user-images.githubusercontent.com/75945382/169682176-e6e1ebb8-743f-441c-a2a9-f3bb1d4f21d0.png)
if I use 'bg-#999' in the script, it's right, but I use the funciton to get 'bg-#999', it doesn't works.

**Comment by Circkoooooo** [comment]
> have you tried to put it into the [safelist](https://github.com/unocss/unocss#safelist)?


Actually i haven't. But it will be work if i put the 'bg-#999' to the script.
I thought that uno can auto parse the hexadecimal color, but i don't think so now. So i will put it into the safelist. Thank you.

**Comment by antfu** [comment]
https://github.com/unocss/unocss#scanning

Add `// @unocss-include` to your script file.
